/**
 * Referral Status Constants
 * Status definitions for referral lifecycle
 */

export const MARKETINGREFERRAL_STATUS = {
  // Referral Statuses
  STATUSES: {
    PENDING: 'pending',
    SENT: 'sent',
    DELIVERED: 'delivered',
    OPENED: 'opened',
    VIEWED: 'viewed',
    CLICKED: 'clicked',
    REGISTERED: 'registered',
    QUALIFIED: 'qualified',
    CONVERTED: 'converted',
    COMPLETED: 'completed',
    EXPIRED: 'expired',
    CANCELLED: 'cancelled',
    REJECTED: 'rejected',
    FRAUD: 'fraud',
    UNDER_REVIEW: 'under_review',
    ON_HOLD: 'on_hold',
    PARTIAL: 'partial',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    PENDING: '#F59E0B',
    SENT: '#3B82F6',
    DELIVERED: '#10B981',
    OPENED: '#8B5CF6',
    VIEWED: '#8B5CF6',
    CLICKED: '#3B82F6',
    REGISTERED: '#10B981',
    QUALIFIED: '#10B981',
    CONVERTED: '#10B981',
    COMPLETED: '#10B981',
    EXPIRED: '#6B7280',
    CANCELLED: '#6B7280',
    REJECTED: '#EF4444',
    FRAUD: '#EF4444',
    UNDER_REVIEW: '#F59E0B',
    ON_HOLD: '#F59E0B',
    PARTIAL: '#F59E0B',
  } as const,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    FRAUD: 'fraud',
    REVIEW: 'review',
  } as const,

  // Status Priority Order
  ORDER: {
    PENDING: 0,
    SENT: 1,
    DELIVERED: 2,
    OPENED: 3,
    VIEWED: 4,
    CLICKED: 5,
    REGISTERED: 6,
    QUALIFIED: 7,
    CONVERTED: 8,
    COMPLETED: 9,
    PARTIAL: 10,
    ON_HOLD: 11,
    UNDER_REVIEW: 12,
    EXPIRED: 13,
    CANCELLED: 14,
    REJECTED: 15,
    FRAUD: 16,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    PENDING_TO_SENT: 'pending_to_sent',
    PENDING_TO_CANCELLED: 'pending_to_cancelled',
    SENT_TO_DELIVERED: 'sent_to_delivered',
    SENT_TO_OPENED: 'sent_to_opened',
    SENT_TO_CANCELLED: 'sent_to_cancelled',
    DELIVERED_TO_OPENED: 'delivered_to_opened',
    DELIVERED_TO_VIEWED: 'delivered_to_viewed',
    OPENED_TO_CLICKED: 'opened_to_clicked',
    OPENED_TO_VIEWED: 'opened_to_viewed',
    VIEWED_TO_CLICKED: 'viewed_to_clicked',
    CLICKED_TO_REGISTERED: 'clicked_to_registered',
    CLICKED_TO_EXPIRED: 'clicked_to_expired',
    REGISTERED_TO_QUALIFIED: 'registered_to_qualified',
    REGISTERED_TO_EXPIRED: 'registered_to_expired',
    QUALIFIED_TO_CONVERTED: 'qualified_to_converted',
    QUALIFIED_TO_PARTIAL: 'qualified_to_partial',
    QUALIFIED_TO_EXPIRED: 'qualified_to_expired',
    CONVERTED_TO_COMPLETED: 'converted_to_completed',
    CONVERTED_TO_PARTIAL: 'converted_to_partial',
    PARTIAL_TO_COMPLETED: 'partial_to_completed',
    PARTIAL_TO_CANCELLED: 'partial_to_cancelled',
    COMPLETED_TO_ARCHIVED: 'completed_to_archived',
    ON_HOLD_TO_UNDER_REVIEW: 'on_hold_to_under_review',
    ON_HOLD_TO_CANCELLED: 'on_hold_to_cancelled',
    UNDER_REVIEW_TO_QUALIFIED: 'under_review_to_qualified',
    UNDER_REVIEW_TO_REJECTED: 'under_review_to_rejected',
    UNDER_REVIEW_TO_FRAUD: 'under_review_to_fraud',
    EXPIRED_TO_CANCELLED: 'expired_to_cancelled',
    REJECTED_TO_CANCELLED: 'rejected_to_cancelled',
    FRAUD_TO_CANCELLED: 'fraud_to_cancelled',
  } as const,
} as const;

// Referral Statuses
export type MarketingReferralStatusType =
  (typeof MARKETINGREFERRAL_STATUS.STATUSES)[keyof typeof MARKETINGREFERRAL_STATUS.STATUSES];

// Status Colors
export type MarketingReferralStatusColor =
  (typeof MARKETINGREFERRAL_STATUS.COLORS)[keyof typeof MARKETINGREFERRAL_STATUS.COLORS];

// Status Categories
export type MarketingReferralStatusCategory =
  (typeof MARKETINGREFERRAL_STATUS.CATEGORIES)[keyof typeof MARKETINGREFERRAL_STATUS.CATEGORIES];

// Status Priority Order
export type MarketingReferralStatusOrder =
  (typeof MARKETINGREFERRAL_STATUS.ORDER)[keyof typeof MARKETINGREFERRAL_STATUS.ORDER];

// Status Transitions
export type MarketingReferralStatusTransition =
  (typeof MARKETINGREFERRAL_STATUS.TRANSITIONS)[keyof typeof MARKETINGREFERRAL_STATUS.TRANSITIONS];

// Utility Functions
export function marketingreferralGetStatusLabel(status: MarketingReferralStatusType): string {
  const labels: Record<MarketingReferralStatusType, string> = {
    [MARKETINGREFERRAL_STATUS.STATUSES.PENDING]: 'Pending',
    [MARKETINGREFERRAL_STATUS.STATUSES.SENT]: 'Sent',
    [MARKETINGREFERRAL_STATUS.STATUSES.DELIVERED]: 'Delivered',
    [MARKETINGREFERRAL_STATUS.STATUSES.OPENED]: 'Opened',
    [MARKETINGREFERRAL_STATUS.STATUSES.VIEWED]: 'Viewed',
    [MARKETINGREFERRAL_STATUS.STATUSES.CLICKED]: 'Clicked',
    [MARKETINGREFERRAL_STATUS.STATUSES.REGISTERED]: 'Registered',
    [MARKETINGREFERRAL_STATUS.STATUSES.QUALIFIED]: 'Qualified',
    [MARKETINGREFERRAL_STATUS.STATUSES.CONVERTED]: 'Converted',
    [MARKETINGREFERRAL_STATUS.STATUSES.COMPLETED]: 'Completed',
    [MARKETINGREFERRAL_STATUS.STATUSES.EXPIRED]: 'Expired',
    [MARKETINGREFERRAL_STATUS.STATUSES.CANCELLED]: 'Cancelled',
    [MARKETINGREFERRAL_STATUS.STATUSES.REJECTED]: 'Rejected',
    [MARKETINGREFERRAL_STATUS.STATUSES.FRAUD]: 'Fraud',
    [MARKETINGREFERRAL_STATUS.STATUSES.UNDER_REVIEW]: 'Under Review',
    [MARKETINGREFERRAL_STATUS.STATUSES.ON_HOLD]: 'On Hold',
    [MARKETINGREFERRAL_STATUS.STATUSES.PARTIAL]: 'Partial',
  };
  return labels[status] || 'Unknown Status';
}

export function marketingreferralGetStatusColor(
  status: MarketingReferralStatusType
): MarketingReferralStatusColor {
  const colors: Record<MarketingReferralStatusType, MarketingReferralStatusColor> = {
    [MARKETINGREFERRAL_STATUS.STATUSES.PENDING]: MARKETINGREFERRAL_STATUS.COLORS.PENDING,
    [MARKETINGREFERRAL_STATUS.STATUSES.SENT]: MARKETINGREFERRAL_STATUS.COLORS.SENT,
    [MARKETINGREFERRAL_STATUS.STATUSES.DELIVERED]: MARKETINGREFERRAL_STATUS.COLORS.DELIVERED,
    [MARKETINGREFERRAL_STATUS.STATUSES.OPENED]: MARKETINGREFERRAL_STATUS.COLORS.OPENED,
    [MARKETINGREFERRAL_STATUS.STATUSES.VIEWED]: MARKETINGREFERRAL_STATUS.COLORS.VIEWED,
    [MARKETINGREFERRAL_STATUS.STATUSES.CLICKED]: MARKETINGREFERRAL_STATUS.COLORS.CLICKED,
    [MARKETINGREFERRAL_STATUS.STATUSES.REGISTERED]: MARKETINGREFERRAL_STATUS.COLORS.REGISTERED,
    [MARKETINGREFERRAL_STATUS.STATUSES.QUALIFIED]: MARKETINGREFERRAL_STATUS.COLORS.QUALIFIED,
    [MARKETINGREFERRAL_STATUS.STATUSES.CONVERTED]: MARKETINGREFERRAL_STATUS.COLORS.CONVERTED,
    [MARKETINGREFERRAL_STATUS.STATUSES.COMPLETED]: MARKETINGREFERRAL_STATUS.COLORS.COMPLETED,
    [MARKETINGREFERRAL_STATUS.STATUSES.EXPIRED]: MARKETINGREFERRAL_STATUS.COLORS.EXPIRED,
    [MARKETINGREFERRAL_STATUS.STATUSES.CANCELLED]: MARKETINGREFERRAL_STATUS.COLORS.CANCELLED,
    [MARKETINGREFERRAL_STATUS.STATUSES.REJECTED]: MARKETINGREFERRAL_STATUS.COLORS.REJECTED,
    [MARKETINGREFERRAL_STATUS.STATUSES.FRAUD]: MARKETINGREFERRAL_STATUS.COLORS.FRAUD,
    [MARKETINGREFERRAL_STATUS.STATUSES.UNDER_REVIEW]: MARKETINGREFERRAL_STATUS.COLORS.UNDER_REVIEW,
    [MARKETINGREFERRAL_STATUS.STATUSES.ON_HOLD]: MARKETINGREFERRAL_STATUS.COLORS.ON_HOLD,
    [MARKETINGREFERRAL_STATUS.STATUSES.PARTIAL]: MARKETINGREFERRAL_STATUS.COLORS.PARTIAL,
  };
  return colors[status] || MARKETINGREFERRAL_STATUS.COLORS.PENDING;
}

export function marketingreferralGetStatusCategory(
  status: MarketingReferralStatusType
): MarketingReferralStatusCategory {
  const categories: Record<MarketingReferralStatusType, MarketingReferralStatusCategory> = {
    [MARKETINGREFERRAL_STATUS.STATUSES.PENDING]: MARKETINGREFERRAL_STATUS.CATEGORIES.PENDING,
    [MARKETINGREFERRAL_STATUS.STATUSES.SENT]: MARKETINGREFERRAL_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGREFERRAL_STATUS.STATUSES.DELIVERED]: MARKETINGREFERRAL_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGREFERRAL_STATUS.STATUSES.OPENED]: MARKETINGREFERRAL_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGREFERRAL_STATUS.STATUSES.VIEWED]: MARKETINGREFERRAL_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGREFERRAL_STATUS.STATUSES.CLICKED]: MARKETINGREFERRAL_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGREFERRAL_STATUS.STATUSES.REGISTERED]: MARKETINGREFERRAL_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGREFERRAL_STATUS.STATUSES.QUALIFIED]: MARKETINGREFERRAL_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGREFERRAL_STATUS.STATUSES.CONVERTED]: MARKETINGREFERRAL_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGREFERRAL_STATUS.STATUSES.COMPLETED]: MARKETINGREFERRAL_STATUS.CATEGORIES.COMPLETED,
    [MARKETINGREFERRAL_STATUS.STATUSES.PARTIAL]: MARKETINGREFERRAL_STATUS.CATEGORIES.COMPLETED,
    [MARKETINGREFERRAL_STATUS.STATUSES.EXPIRED]: MARKETINGREFERRAL_STATUS.CATEGORIES.FAILED,
    [MARKETINGREFERRAL_STATUS.STATUSES.CANCELLED]: MARKETINGREFERRAL_STATUS.CATEGORIES.CANCELLED,
    [MARKETINGREFERRAL_STATUS.STATUSES.REJECTED]: MARKETINGREFERRAL_STATUS.CATEGORIES.FAILED,
    [MARKETINGREFERRAL_STATUS.STATUSES.FRAUD]: MARKETINGREFERRAL_STATUS.CATEGORIES.FRAUD,
    [MARKETINGREFERRAL_STATUS.STATUSES.UNDER_REVIEW]: MARKETINGREFERRAL_STATUS.CATEGORIES.REVIEW,
    [MARKETINGREFERRAL_STATUS.STATUSES.ON_HOLD]: MARKETINGREFERRAL_STATUS.CATEGORIES.REVIEW,
  };
  return categories[status] || MARKETINGREFERRAL_STATUS.CATEGORIES.PENDING;
}

export function marketingreferralIsCompletedStatus(status: MarketingReferralStatusType): boolean {
  const completedStatuses: MarketingReferralStatusType[] = [
    MARKETINGREFERRAL_STATUS.STATUSES.COMPLETED,
    MARKETINGREFERRAL_STATUS.STATUSES.CONVERTED,
    MARKETINGREFERRAL_STATUS.STATUSES.QUALIFIED,
  ];
  return completedStatuses.includes(status);
}

export function marketingreferralIsInProgressStatus(status: MarketingReferralStatusType): boolean {
  const inProgressStatuses: MarketingReferralStatusType[] = [
    MARKETINGREFERRAL_STATUS.STATUSES.SENT,
    MARKETINGREFERRAL_STATUS.STATUSES.DELIVERED,
    MARKETINGREFERRAL_STATUS.STATUSES.OPENED,
    MARKETINGREFERRAL_STATUS.STATUSES.VIEWED,
    MARKETINGREFERRAL_STATUS.STATUSES.CLICKED,
    MARKETINGREFERRAL_STATUS.STATUSES.REGISTERED,
    MARKETINGREFERRAL_STATUS.STATUSES.PARTIAL,
  ];
  return inProgressStatuses.includes(status);
}

export function marketingreferralIsFailedStatus(status: MarketingReferralStatusType): boolean {
  const failedStatuses: MarketingReferralStatusType[] = [
    MARKETINGREFERRAL_STATUS.STATUSES.EXPIRED,
    MARKETINGREFERRAL_STATUS.STATUSES.REJECTED,
    MARKETINGREFERRAL_STATUS.STATUSES.FRAUD,
  ];
  return failedStatuses.includes(status);
}

export function marketingreferralCanTransition(
  currentStatus: MarketingReferralStatusType,
  targetStatus: MarketingReferralStatusType
): boolean {
  const validTransitions: Record<MarketingReferralStatusType, MarketingReferralStatusType[]> = {
    [MARKETINGREFERRAL_STATUS.STATUSES.PENDING]: [
      MARKETINGREFERRAL_STATUS.STATUSES.SENT,
      MARKETINGREFERRAL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGREFERRAL_STATUS.STATUSES.SENT]: [
      MARKETINGREFERRAL_STATUS.STATUSES.DELIVERED,
      MARKETINGREFERRAL_STATUS.STATUSES.OPENED,
      MARKETINGREFERRAL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGREFERRAL_STATUS.STATUSES.DELIVERED]: [
      MARKETINGREFERRAL_STATUS.STATUSES.OPENED,
      MARKETINGREFERRAL_STATUS.STATUSES.VIEWED,
    ],
    [MARKETINGREFERRAL_STATUS.STATUSES.OPENED]: [
      MARKETINGREFERRAL_STATUS.STATUSES.CLICKED,
      MARKETINGREFERRAL_STATUS.STATUSES.VIEWED,
    ],
    [MARKETINGREFERRAL_STATUS.STATUSES.VIEWED]: [MARKETINGREFERRAL_STATUS.STATUSES.CLICKED],
    [MARKETINGREFERRAL_STATUS.STATUSES.CLICKED]: [
      MARKETINGREFERRAL_STATUS.STATUSES.REGISTERED,
      MARKETINGREFERRAL_STATUS.STATUSES.EXPIRED,
    ],
    [MARKETINGREFERRAL_STATUS.STATUSES.REGISTERED]: [
      MARKETINGREFERRAL_STATUS.STATUSES.QUALIFIED,
      MARKETINGREFERRAL_STATUS.STATUSES.EXPIRED,
    ],
    [MARKETINGREFERRAL_STATUS.STATUSES.QUALIFIED]: [
      MARKETINGREFERRAL_STATUS.STATUSES.CONVERTED,
      MARKETINGREFERRAL_STATUS.STATUSES.PARTIAL,
      MARKETINGREFERRAL_STATUS.STATUSES.EXPIRED,
    ],
    [MARKETINGREFERRAL_STATUS.STATUSES.CONVERTED]: [
      MARKETINGREFERRAL_STATUS.STATUSES.COMPLETED,
      MARKETINGREFERRAL_STATUS.STATUSES.PARTIAL,
    ],
    [MARKETINGREFERRAL_STATUS.STATUSES.PARTIAL]: [
      MARKETINGREFERRAL_STATUS.STATUSES.COMPLETED,
      MARKETINGREFERRAL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGREFERRAL_STATUS.STATUSES.ON_HOLD]: [
      MARKETINGREFERRAL_STATUS.STATUSES.UNDER_REVIEW,
      MARKETINGREFERRAL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGREFERRAL_STATUS.STATUSES.UNDER_REVIEW]: [
      MARKETINGREFERRAL_STATUS.STATUSES.QUALIFIED,
      MARKETINGREFERRAL_STATUS.STATUSES.REJECTED,
      MARKETINGREFERRAL_STATUS.STATUSES.FRAUD,
    ],
    [MARKETINGREFERRAL_STATUS.STATUSES.COMPLETED]: [],
    [MARKETINGREFERRAL_STATUS.STATUSES.EXPIRED]: [MARKETINGREFERRAL_STATUS.STATUSES.CANCELLED],
    [MARKETINGREFERRAL_STATUS.STATUSES.CANCELLED]: [],
    [MARKETINGREFERRAL_STATUS.STATUSES.REJECTED]: [MARKETINGREFERRAL_STATUS.STATUSES.CANCELLED],
    [MARKETINGREFERRAL_STATUS.STATUSES.FRAUD]: [MARKETINGREFERRAL_STATUS.STATUSES.CANCELLED],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
