/**
 * AI Embedding Status Constants
 * Status tracking for embedding lifecycle
 */

// First define the status types
export const AI_EMBEDDING_STATUS_TYPES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Processing States
  INITIALIZING: 'initializing',
  GENERATING: 'generating',
  PROCESSING: 'processing',
  NORMALIZING: 'normalizing',
  VALIDATING: 'validating',

  // Intermediate States
  GENERATED: 'generated',
  PROCESSED: 'processed',
  NORMALIZED: 'normalized',
  VALIDATED: 'validated',
  OPTIMIZED: 'optimized',

  // Storage States
  STORING: 'storing',
  STORED: 'stored',
  CACHING: 'caching',
  CACHED: 'cached',

  // Terminal States
  COMPLETED: 'completed',
  FAILED: 'failed',
  EXPIRED: 'expired',
  ARCHIVED: 'archived',
} as const;

export type AIEmbeddingStatusType =
  (typeof AI_EMBEDDING_STATUS_TYPES)[keyof typeof AI_EMBEDDING_STATUS_TYPES];

export const AI_EMBEDDING_STATUS = {
  // Status Types
  STATUSES: AI_EMBEDDING_STATUS_TYPES,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CACHED: 'cached',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_EMBEDDING_STATUS_TYPES.CREATED]: '#gray',
    [AI_EMBEDDING_STATUS_TYPES.QUEUED]: '#gray',
    [AI_EMBEDDING_STATUS_TYPES.PENDING]: '#yellow',
    [AI_EMBEDDING_STATUS_TYPES.INITIALIZING]: '#blue',
    [AI_EMBEDDING_STATUS_TYPES.GENERATING]: '#blue',
    [AI_EMBEDDING_STATUS_TYPES.PROCESSING]: '#blue',
    [AI_EMBEDDING_STATUS_TYPES.NORMALIZING]: '#blue',
    [AI_EMBEDDING_STATUS_TYPES.VALIDATING]: '#purple',
    [AI_EMBEDDING_STATUS_TYPES.GENERATED]: '#green',
    [AI_EMBEDDING_STATUS_TYPES.PROCESSED]: '#green',
    [AI_EMBEDDING_STATUS_TYPES.NORMALIZED]: '#green',
    [AI_EMBEDDING_STATUS_TYPES.VALIDATED]: '#green',
    [AI_EMBEDDING_STATUS_TYPES.OPTIMIZED]: '#green',
    [AI_EMBEDDING_STATUS_TYPES.STORING]: '#orange',
    [AI_EMBEDDING_STATUS_TYPES.STORED]: '#green',
    [AI_EMBEDDING_STATUS_TYPES.CACHING]: '#orange',
    [AI_EMBEDDING_STATUS_TYPES.CACHED]: '#green',
    [AI_EMBEDDING_STATUS_TYPES.COMPLETED]: '#green',
    [AI_EMBEDDING_STATUS_TYPES.FAILED]: '#red',
    [AI_EMBEDDING_STATUS_TYPES.EXPIRED]: '#gray',
    [AI_EMBEDDING_STATUS_TYPES.ARCHIVED]: '#gray',
  } as const,
} as const;

export type AIEmbeddingStatusCategory =
  (typeof AI_EMBEDDING_STATUS.CATEGORIES)[keyof typeof AI_EMBEDDING_STATUS.CATEGORIES];
export type AIEmbeddingStatusSeverity =
  (typeof AI_EMBEDDING_STATUS.SEVERITY)[keyof typeof AI_EMBEDDING_STATUS.SEVERITY];
export type AIEmbeddingStatusColor =
  (typeof AI_EMBEDDING_STATUS.COLORS)[keyof typeof AI_EMBEDDING_STATUS.COLORS];

export function getAiEmbeddingStatusLabel(status: AIEmbeddingStatusType): string {
  const labels: Record<AIEmbeddingStatusType, string> = {
    [AI_EMBEDDING_STATUS_TYPES.CREATED]: 'Created',
    [AI_EMBEDDING_STATUS_TYPES.QUEUED]: 'Queued',
    [AI_EMBEDDING_STATUS_TYPES.PENDING]: 'Pending',
    [AI_EMBEDDING_STATUS_TYPES.INITIALIZING]: 'Initializing',
    [AI_EMBEDDING_STATUS_TYPES.GENERATING]: 'Generating',
    [AI_EMBEDDING_STATUS_TYPES.PROCESSING]: 'Processing',
    [AI_EMBEDDING_STATUS_TYPES.NORMALIZING]: 'Normalizing',
    [AI_EMBEDDING_STATUS_TYPES.VALIDATING]: 'Validating',
    [AI_EMBEDDING_STATUS_TYPES.GENERATED]: 'Generated',
    [AI_EMBEDDING_STATUS_TYPES.PROCESSED]: 'Processed',
    [AI_EMBEDDING_STATUS_TYPES.NORMALIZED]: 'Normalized',
    [AI_EMBEDDING_STATUS_TYPES.VALIDATED]: 'Validated',
    [AI_EMBEDDING_STATUS_TYPES.OPTIMIZED]: 'Optimized',
    [AI_EMBEDDING_STATUS_TYPES.STORING]: 'Storing',
    [AI_EMBEDDING_STATUS_TYPES.STORED]: 'Stored',
    [AI_EMBEDDING_STATUS_TYPES.CACHING]: 'Caching',
    [AI_EMBEDDING_STATUS_TYPES.CACHED]: 'Cached',
    [AI_EMBEDDING_STATUS_TYPES.COMPLETED]: 'Completed',
    [AI_EMBEDDING_STATUS_TYPES.FAILED]: 'Failed',
    [AI_EMBEDDING_STATUS_TYPES.EXPIRED]: 'Expired',
    [AI_EMBEDDING_STATUS_TYPES.ARCHIVED]: 'Archived',
  };
  return labels[status] || 'Unknown';
}

export function getAiEmbeddingStatusCategory(
  status: AIEmbeddingStatusType
): AIEmbeddingStatusCategory {
  const categories: Record<AIEmbeddingStatusType, AIEmbeddingStatusCategory> = {
    [AI_EMBEDDING_STATUS_TYPES.CREATED]: AI_EMBEDDING_STATUS.CATEGORIES.PENDING,
    [AI_EMBEDDING_STATUS_TYPES.QUEUED]: AI_EMBEDDING_STATUS.CATEGORIES.PENDING,
    [AI_EMBEDDING_STATUS_TYPES.PENDING]: AI_EMBEDDING_STATUS.CATEGORIES.PENDING,
    [AI_EMBEDDING_STATUS_TYPES.INITIALIZING]: AI_EMBEDDING_STATUS.CATEGORIES.PROCESSING,
    [AI_EMBEDDING_STATUS_TYPES.GENERATING]: AI_EMBEDDING_STATUS.CATEGORIES.PROCESSING,
    [AI_EMBEDDING_STATUS_TYPES.PROCESSING]: AI_EMBEDDING_STATUS.CATEGORIES.PROCESSING,
    [AI_EMBEDDING_STATUS_TYPES.NORMALIZING]: AI_EMBEDDING_STATUS.CATEGORIES.PROCESSING,
    [AI_EMBEDDING_STATUS_TYPES.VALIDATING]: AI_EMBEDDING_STATUS.CATEGORIES.PROCESSING,
    [AI_EMBEDDING_STATUS_TYPES.GENERATED]: AI_EMBEDDING_STATUS.CATEGORIES.PROCESSING,
    [AI_EMBEDDING_STATUS_TYPES.PROCESSED]: AI_EMBEDDING_STATUS.CATEGORIES.PROCESSING,
    [AI_EMBEDDING_STATUS_TYPES.NORMALIZED]: AI_EMBEDDING_STATUS.CATEGORIES.PROCESSING,
    [AI_EMBEDDING_STATUS_TYPES.VALIDATED]: AI_EMBEDDING_STATUS.CATEGORIES.PROCESSING,
    [AI_EMBEDDING_STATUS_TYPES.OPTIMIZED]: AI_EMBEDDING_STATUS.CATEGORIES.PROCESSING,
    [AI_EMBEDDING_STATUS_TYPES.STORING]: AI_EMBEDDING_STATUS.CATEGORIES.PROCESSING,
    [AI_EMBEDDING_STATUS_TYPES.STORED]: AI_EMBEDDING_STATUS.CATEGORIES.COMPLETED,
    [AI_EMBEDDING_STATUS_TYPES.CACHING]: AI_EMBEDDING_STATUS.CATEGORIES.PROCESSING,
    [AI_EMBEDDING_STATUS_TYPES.CACHED]: AI_EMBEDDING_STATUS.CATEGORIES.CACHED,
    [AI_EMBEDDING_STATUS_TYPES.COMPLETED]: AI_EMBEDDING_STATUS.CATEGORIES.COMPLETED,
    [AI_EMBEDDING_STATUS_TYPES.FAILED]: AI_EMBEDDING_STATUS.CATEGORIES.FAILED,
    [AI_EMBEDDING_STATUS_TYPES.EXPIRED]: AI_EMBEDDING_STATUS.CATEGORIES.FAILED,
    [AI_EMBEDDING_STATUS_TYPES.ARCHIVED]: AI_EMBEDDING_STATUS.CATEGORIES.COMPLETED,
  };
  return categories[status] || AI_EMBEDDING_STATUS.CATEGORIES.PENDING;
}

export function getAiEmbeddingStatusSeverity(
  status: AIEmbeddingStatusType
): AIEmbeddingStatusSeverity {
  const severities: Record<AIEmbeddingStatusType, AIEmbeddingStatusSeverity> = {
    [AI_EMBEDDING_STATUS_TYPES.CREATED]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.QUEUED]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.PENDING]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.INITIALIZING]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.GENERATING]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.PROCESSING]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.NORMALIZING]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.VALIDATING]: AI_EMBEDDING_STATUS.SEVERITY.WARNING,
    [AI_EMBEDDING_STATUS_TYPES.GENERATED]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.PROCESSED]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.NORMALIZED]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.VALIDATED]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.OPTIMIZED]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.STORING]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.STORED]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.CACHING]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.CACHED]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.COMPLETED]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
    [AI_EMBEDDING_STATUS_TYPES.FAILED]: AI_EMBEDDING_STATUS.SEVERITY.ERROR,
    [AI_EMBEDDING_STATUS_TYPES.EXPIRED]: AI_EMBEDDING_STATUS.SEVERITY.WARNING,
    [AI_EMBEDDING_STATUS_TYPES.ARCHIVED]: AI_EMBEDDING_STATUS.SEVERITY.INFO,
  };
  return severities[status] || AI_EMBEDDING_STATUS.SEVERITY.INFO;
}

export function getAiEmbeddingStatusColor(status: AIEmbeddingStatusType): AIEmbeddingStatusColor {
  return AI_EMBEDDING_STATUS.COLORS[status] || '#gray';
}

export function isAiEmbeddingActive(status: AIEmbeddingStatusType): boolean {
  const activeStatuses: AIEmbeddingStatusType[] = [
    AI_EMBEDDING_STATUS_TYPES.CREATED,
    AI_EMBEDDING_STATUS_TYPES.QUEUED,
    AI_EMBEDDING_STATUS_TYPES.PENDING,
    AI_EMBEDDING_STATUS_TYPES.INITIALIZING,
    AI_EMBEDDING_STATUS_TYPES.GENERATING,
    AI_EMBEDDING_STATUS_TYPES.PROCESSING,
    AI_EMBEDDING_STATUS_TYPES.NORMALIZING,
    AI_EMBEDDING_STATUS_TYPES.VALIDATING,
    AI_EMBEDDING_STATUS_TYPES.GENERATED,
    AI_EMBEDDING_STATUS_TYPES.PROCESSED,
    AI_EMBEDDING_STATUS_TYPES.NORMALIZED,
    AI_EMBEDDING_STATUS_TYPES.VALIDATED,
    AI_EMBEDDING_STATUS_TYPES.OPTIMIZED,
    AI_EMBEDDING_STATUS_TYPES.STORING,
    AI_EMBEDDING_STATUS_TYPES.CACHING,
  ];
  return activeStatuses.includes(status);
}

export function isAiEmbeddingGenerated(status: AIEmbeddingStatusType): boolean {
  const generatedStatuses: AIEmbeddingStatusType[] = [
    AI_EMBEDDING_STATUS_TYPES.GENERATED,
    AI_EMBEDDING_STATUS_TYPES.PROCESSED,
    AI_EMBEDDING_STATUS_TYPES.NORMALIZED,
    AI_EMBEDDING_STATUS_TYPES.VALIDATED,
    AI_EMBEDDING_STATUS_TYPES.OPTIMIZED,
    AI_EMBEDDING_STATUS_TYPES.STORED,
    AI_EMBEDDING_STATUS_TYPES.CACHED,
    AI_EMBEDDING_STATUS_TYPES.COMPLETED,
  ];
  return generatedStatuses.includes(status);
}

export function isAiEmbeddingCompleted(status: AIEmbeddingStatusType): boolean {
  const completedStatuses: AIEmbeddingStatusType[] = [
    AI_EMBEDDING_STATUS_TYPES.COMPLETED,
    AI_EMBEDDING_STATUS_TYPES.STORED,
    AI_EMBEDDING_STATUS_TYPES.CACHED,
    AI_EMBEDDING_STATUS_TYPES.ARCHIVED,
  ];
  return completedStatuses.includes(status);
}

export function isAiEmbeddingFailed(status: AIEmbeddingStatusType): boolean {
  const failedStatuses: AIEmbeddingStatusType[] = [
    AI_EMBEDDING_STATUS_TYPES.FAILED,
    AI_EMBEDDING_STATUS_TYPES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}

export function getAiEmbeddingStatusProgress(status: AIEmbeddingStatusType): number {
  const progress: Record<AIEmbeddingStatusType, number> = {
    [AI_EMBEDDING_STATUS_TYPES.CREATED]: 0,
    [AI_EMBEDDING_STATUS_TYPES.QUEUED]: 5,
    [AI_EMBEDDING_STATUS_TYPES.PENDING]: 10,
    [AI_EMBEDDING_STATUS_TYPES.INITIALIZING]: 20,
    [AI_EMBEDDING_STATUS_TYPES.GENERATING]: 30,
    [AI_EMBEDDING_STATUS_TYPES.PROCESSING]: 40,
    [AI_EMBEDDING_STATUS_TYPES.NORMALIZING]: 50,
    [AI_EMBEDDING_STATUS_TYPES.VALIDATING]: 55,
    [AI_EMBEDDING_STATUS_TYPES.GENERATED]: 60,
    [AI_EMBEDDING_STATUS_TYPES.PROCESSED]: 65,
    [AI_EMBEDDING_STATUS_TYPES.NORMALIZED]: 70,
    [AI_EMBEDDING_STATUS_TYPES.VALIDATED]: 75,
    [AI_EMBEDDING_STATUS_TYPES.OPTIMIZED]: 80,
    [AI_EMBEDDING_STATUS_TYPES.STORING]: 85,
    [AI_EMBEDDING_STATUS_TYPES.STORED]: 90,
    [AI_EMBEDDING_STATUS_TYPES.CACHING]: 92,
    [AI_EMBEDDING_STATUS_TYPES.CACHED]: 95,
    [AI_EMBEDDING_STATUS_TYPES.COMPLETED]: 100,
    [AI_EMBEDDING_STATUS_TYPES.FAILED]: 0,
    [AI_EMBEDDING_STATUS_TYPES.EXPIRED]: 0,
    [AI_EMBEDDING_STATUS_TYPES.ARCHIVED]: 100,
  };
  return progress[status] || 0;
}
