/**
 * Analytics Types
 * Type definitions for analytics module based on shared-constants
 * @module AnalyticsTypes
 */

import { BaseEntity, Timestamp, Metadata, ID } from '../common/core-primitives.types';

// ============================================================
// Import from shared-constants analytics
// ============================================================
import {
  // Main Analytics
  ANALYTICS,
  AnalyticsType,
  AnalyticsStatus,
  AnalyticsTimeframe,
  AnalyticsInterval,
  AnalyticsAggregation,
  AnalyticsComparison,
  AnalyticsTrend,
  AnalyticsEvent,
  AnalyticsDimension,
  AnalyticsMetric,
  AnalyticsFilter,
  AnalyticsPermission,
  AnalyticsExportFormat,
  getAnalyticsMainStatusLabel,
  getAnalyticsTimeframeLabel,
  getAnalyticsMainIntervalLabel,
  getAnalyticsMainTrendLabel,
  getAnalyticsEventLabel,
  getAnalyticsMainMetricLabel,
  getAnalyticsMainPermissionLabel,
  isAnalyticsCompleted,
  isAnalyticsProcessing,
  isAnalyticsFailed,
  isAnalyticsFinal,
  // Aggregation
  ANALYTICS_AGGREGATION,
  AnalyticsAggregationType,
  AnalyticsAggregationCategory,
  AnalyticsAggregationLevel,
  AnalyticsAggregationScope,
  AnalyticsAggregationPrecision,
  getAnalyticsAggregationLabel,
  getAnalyticsAggregationCategoryLabel,
  getAnalyticsAggregationLevelLabel,
  getAnalyticsAggregationScopeLabel,
  getAnalyticsAggregationPrecisionLabel,
  isAnalyticsAggregationStatistical,
  isAnalyticsAggregationMathematical,
  isAnalyticsAggregationTimeSeries,
  isAnalyticsAggregationApproximate,
  getAnalyticsAggregationCategory,
  // Campaign
  ANALYTICS_CAMPAIGN,
  AnalyticsCampaignType,
  AnalyticsCampaignStatus,
  AnalyticsCampaignChannel,
  AnalyticsCampaignObjective,
  AnalyticsCampaignBudgetType,
  AnalyticsCampaignROIStatus,
  AnalyticsCampaignMetric,
  AnalyticsCampaignPriority,
  AnalyticsCampaignVisibility,
  getAnalyticsCampaignTypeLabel,
  getAnalyticsCampaignStatusLabel,
  getAnalyticsCampaignChannelLabel,
  getAnalyticsCampaignObjectiveLabel,
  getAnalyticsCampaignROIStatusLabel,
  getAnalyticsCampaignMetricLabel,
  getAnalyticsCampaignPriorityLabel,
  isAnalyticsCampaignActive,
  isAnalyticsCampaignScheduled,
  isAnalyticsCampaignCompleted,
  getAnalyticsCampaignObjective,
  // Category
  ANALYTICS_CATEGORY,
  AnalyticsCategoryType,
  AnalyticsSubCategoryType,
  AnalyticsCategoryGroup,
  AnalyticsCategoryPriority,
  AnalyticsCategoryVisibility,
  AnalyticsCategoryStatus,
  getAnalyticsCategoryLabel,
  getAnalyticsSubCategoryLabel,
  getAnalyticsCategoryGroupLabel,
  getAnalyticsCategoryPriorityLabel,
  getAnalyticsCategoryStatusLabel,
  isAnalyticsCategoryActive,
  isAnalyticsCategoryArchived,
  // Comparison
  ANALYTICS_COMPARISON,
  AnalyticsComparisonType,
  AnalyticsComparisonMethod,
  AnalyticsComparisonDirection,
  AnalyticsComparisonSignificance,
  AnalyticsComparisonUnit,
  getAnalyticsComparisonLabel,
  getAnalyticsComparisonMethodLabel,
  getAnalyticsComparisonDirectionLabel,
  getAnalyticsComparisonSignificanceLabel,
  getAnalyticsComparisonUnitLabel,
  isAnalyticsComparisonPeriodBased,
  isAnalyticsComparisonBenchmarkBased,
  getAnalyticsComparisonDirection,
  getAnalyticsComparisonSignificance,
  // Dimension
  ANALYTICS_DIMENSION,
  AnalyticsUserDimension,
  AnalyticsSessionDimension,
  AnalyticsLocationDimension,
  AnalyticsDeviceDimension,
  AnalyticsTrafficDimension,
  AnalyticsProductDimension,
  AnalyticsOrderDimension,
  AnalyticsTimeDimension,
  AnalyticsPageDimension,
  AnalyticsEventDimension,
  AnalyticsMarketingDimension,
  AnalyticsSystemDimension,
  AnalyticsDimensionCategory,
  AnalyticsDimensionType,
  AnalyticsDimensionGranularity,
  getAnalyticsDimensionLabel,
  getAnalyticsDimensionCategoryLabel,
  getAnalyticsDimensionTypeLabel,
  getAnalyticsDimensionCategory,
  // Error
  ANALYTICS_ERROR,
  AnalyticsErrorType,
  AnalyticsErrorCode,
  AnalyticsErrorSeverity,
  AnalyticsErrorCategory,
  AnalyticsErrorAction,
  AnalyticsErrorSource,
  getAnalyticsErrorLabel,
  getAnalyticsErrorCodeLabel,
  getAnalyticsErrorSeverityLabel,
  getAnalyticsErrorCategoryLabel,
  getAnalyticsErrorActionLabel,
  getAnalyticsErrorSourceLabel,
  getAnalyticsErrorCategory,
  getAnalyticsErrorSeverity,
  // Event
  ANALYTICS_EVENT,
  AnalyticsEventCategory,
  AnalyticsEventAction,
  AnalyticsEventLabel,
  AnalyticsEventValue,
  AnalyticsEventPriority,
  AnalyticsEventStatus,
  getAnalyticsEventCategoryLabel,
  getAnalyticsEventActionLabel,
  getAnalyticsEventLabelName,
  getAnalyticsEventPriorityLabel,
  getAnalyticsEventStatusLabel,
  isAnalyticsEventCompleted,
  isAnalyticsEventProcessing,
  isAnalyticsEventFailed,
  // Filter
  ANALYTICS_FILTER,
  AnalyticsFilterOperator,
  AnalyticsFilterDataType,
  AnalyticsFilterCategory,
  AnalyticsFilterLogicType,
  AnalyticsFilterMatchType,
  AnalyticsFilterPriority,
  AnalyticsFilterScope,
  getAnalyticsFilterOperatorLabel,
  getAnalyticsFilterDataTypeLabel,
  getAnalyticsFilterCategoryLabel,
  getAnalyticsFilterLogicTypeLabel,
  getAnalyticsFilterMatchTypeLabel,
  getAnalyticsFilterPriorityLabel,
  getAnalyticsFilterScopeLabel,
  isAnalyticsFilterComparisonOperator,
  isAnalyticsFilterStringOperator,
  isAnalyticsFilterSetOperator,
  isAnalyticsFilterNullOperator,
  isAnalyticsFilterLogicalOperator,
  // Interval
  ANALYTICS_INTERVAL,
  AnalyticsIntervalType,
  AnalyticsIntervalCategory,
  AnalyticsIntervalUnit,
  AnalyticsIntervalFormat,
  AnalyticsIntervalGroupingType,
  getAnalyticsIntervalDetailLabel,
  getAnalyticsIntervalCategoryLabel,
  getAnalyticsIntervalUnitLabel,
  getAnalyticsIntervalFormatLabel,
  getAnalyticsIntervalCategory,
  getAnalyticsIntervalUnit,
  getAnalyticsIntervalSeconds,
  // Medium
  ANALYTICS_MEDIUM,
  AnalyticsMediumType,
  AnalyticsMediumCategory,
  AnalyticsMediumTypeEnum,
  AnalyticsMediumChannel,
  AnalyticsMediumPriority,
  getAnalyticsMediumLabel,
  getAnalyticsMediumCategoryLabel,
  getAnalyticsMediumTypeLabel,
  getAnalyticsMediumChannelLabel,
  getAnalyticsMediumPriorityLabel,
  isAnalyticsMediumOrganic,
  isAnalyticsMediumPaid,
  isAnalyticsMediumSocial,
  isAnalyticsMediumEmail,
  getAnalyticsMediumCategory,
  getAnalyticsChannelFromMedium,
  // Metric
  ANALYTICS_METRIC,
  AnalyticsBusinessMetric,
  AnalyticsCustomerMetric,
  AnalyticsSalesMetric,
  AnalyticsMarketingMetric,
  AnalyticsProductMetric,
  AnalyticsWebsiteMetric,
  AnalyticsSupportMetric,
  AnalyticsSystemMetric,
  AnalyticsMetricCategory,
  AnalyticsMetricType,
  AnalyticsMetricAggregation,
  AnalyticsMetricFormat,
  AnalyticsMetricPriority,
  getAnalyticsMetricDetailLabel,
  getAnalyticsMetricCategoryLabel,
  getAnalyticsMetricTypeLabel,
  getAnalyticsMetricFormatLabel,
  getAnalyticsMetricPriorityLabel,
  getAnalyticsMetricCategory,
  // Period
  ANALYTICS_PERIOD,
  AnalyticsPeriodType,
  AnalyticsPeriodTypeEnum,
  AnalyticsPeriodGranularity,
  AnalyticsPeriodComparisonType,
  AnalyticsPeriodFormat,
  getAnalyticsPeriodLabel,
  getAnalyticsPeriodTypeLabel,
  getAnalyticsPeriodGranularityLabel,
  getAnalyticsPeriodComparisonTypeLabel,
  isAnalyticsPeriodRolling,
  isAnalyticsPeriodFixed,
  isAnalyticsPeriodRelative,
  getAnalyticsPeriodDays,
  // Permission
  ANALYTICS_PERMISSION,
  AnalyticsPermissionDetailType,
  AnalyticsPermissionResource,
  AnalyticsPermissionLevel,
  AnalyticsPermissionScope,
  AnalyticsPermissionAction,
  AnalyticsPermissionEffect,
  AnalyticsPermissionCondition,
  getAnalyticsPermissionDetailLabel,
  getAnalyticsPermissionResourceLabel,
  getAnalyticsPermissionLevelLabel,
  getAnalyticsPermissionScopeLabel,
  getAnalyticsPermissionActionLabel,
  getAnalyticsPermissionEffectLabel,
  getAnalyticsPermissionConditionLabel,
  isAnalyticsPermissionAdmin,
  isAnalyticsPermissionManagement,
  isAnalyticsPermissionView,
  getAnalyticsPermissionLevel,
  // Source
  ANALYTICS_SOURCE,
  AnalyticsSourceType,
  AnalyticsSourceCategory,
  AnalyticsSourceSubCategory,
  AnalyticsSourceTypeEnum,
  AnalyticsSourceConfidence,
  AnalyticsSourceValidity,
  getAnalyticsSourceLabel,
  getAnalyticsSourceCategoryLabel,
  getAnalyticsSourceConfidenceLabel,
  getAnalyticsSourceValidityLabel,
  isAnalyticsSocialMedia,
  isAnalyticsSearchEngine,
  isAnalyticsOrganic,
  isAnalyticsPaid,
  getAnalyticsSourceCategory,
  // Status
  ANALYTICS_STATUS,
  AnalyticsStatusCode,
  AnalyticsStatusCategory,
  AnalyticsStatusPriority,
  AnalyticsStatusVisibility,
  AnalyticsStatusAction,
  getAnalyticsStatusCodeLabel,
  getAnalyticsStatusCategoryLabel,
  getAnalyticsStatusPriorityLabel,
  getAnalyticsStatusVisibilityLabel,
  getAnalyticsStatusActionLabel,
  isAnalyticsStatusSuccess,
  isAnalyticsStatusProcessing,
  isAnalyticsStatusFailure,
  isAnalyticsStatusFinalState,
  getAnalyticsStatusCategory,
  // Trend
  ANALYTICS_TREND,
  AnalyticsTrendType,
  AnalyticsTrendStrength,
  AnalyticsTrendDirection,
  AnalyticsTrendPattern,
  AnalyticsTrendMethod,
  AnalyticsTrendConfidence,
  AnalyticsTrendHorizon,
  getAnalyticsTrendDetailLabel,
  getAnalyticsTrendStrengthLabel,
  getAnalyticsTrendDirectionLabel,
  getAnalyticsTrendPatternLabel,
  getAnalyticsTrendMethodLabel,
  getAnalyticsTrendConfidenceLabel,
  getAnalyticsTrendHorizonLabel,
  isAnalyticsTrendUpward,
  isAnalyticsTrendDownward,
  isAnalyticsTrendStable,
  getAnalyticsTrendDirectionFromSlope,
  getAnalyticsTrendStrengthFromRSquared,
  // Type
  ANALYTICS_TYPE,
  AnalyticsDataType,
  AnalyticsReportType,
  AnalyticsDataSource,
  AnalyticsGranularity,
  AnalyticsQuality,
  AnalyticsAnalysisType,
  AnalyticsRefreshRate,
  AnalyticsRetention,
  AnalyticsSensitivity,
  AnalyticsUsage,
  getAnalyticsDataTypeLabel,
  getAnalyticsReportTypeLabel,
  getAnalyticsDataSourceLabel,
  getAnalyticsQualityLabel,
  getAnalyticsAnalysisTypeLabel,
  getAnalyticsSensitivityLabel,
  isAnalyticsRealtime,
  isAnalyticsHistorical,
  isAnalyticsPredictive,
  // Retention Analytics
  RETENTION_ANALYTICS,
  RetentionAnalyticsType,
  RetentionAnalyticsStatus,
  RetentionAnalyticsPeriod,
  RetentionAnalyticsCohort,
  RetentionAnalyticsMetric,
  RetentionAnalyticsSegment,
  getRetentionAnalyticsLabel,
  getRetentionAnalyticsStatusLabel,
  getRetentionAnalyticsPeriodLabel,
  getRetentionAnalyticsCohortLabel,
  getRetentionAnalyticsMetricDetailLabel,
  getRetentionAnalyticsSegmentLabel,
  isRetentionAnalyticsActive,
  isRetentionAnalyticsCompleted,
  getRetentionAnalyticsRateValue,
} from '@vubon/shared-constants';

// ============================================================
// Analytics Extended Types
// ============================================================

/**
 * Analytics retention
 */
export interface AnalyticsRetentionData extends BaseEntity, Timestamp {
  id: ID;
  type: RetentionAnalyticsType;
  status: RetentionAnalyticsStatus;
  period: RetentionAnalyticsPeriod;
  cohort: RetentionAnalyticsCohort;
  metric: RetentionAnalyticsMetric;
  segment: RetentionAnalyticsSegment;
  value: number;
  rate: number;
  isActive: boolean;
  isCompleted: boolean;
  metadata?: Metadata;
}

// ============================================================
// Re-export Everything
// ============================================================

export {
  // Main Analytics
  ANALYTICS,
  AnalyticsType,
  AnalyticsStatus,
  AnalyticsTimeframe,
  AnalyticsInterval,
  AnalyticsAggregation,
  AnalyticsComparison,
  AnalyticsTrend,
  AnalyticsEvent,
  AnalyticsDimension,
  AnalyticsMetric,
  AnalyticsFilter,
  AnalyticsPermission,
  AnalyticsExportFormat,
  getAnalyticsMainStatusLabel,
  getAnalyticsTimeframeLabel,
  getAnalyticsMainIntervalLabel,
  getAnalyticsMainTrendLabel,
  getAnalyticsEventLabel,
  getAnalyticsMainMetricLabel,
  getAnalyticsMainPermissionLabel,
  isAnalyticsCompleted,
  isAnalyticsProcessing,
  isAnalyticsFailed,
  isAnalyticsFinal,
  // Aggregation
  ANALYTICS_AGGREGATION,
  AnalyticsAggregationType,
  AnalyticsAggregationCategory,
  AnalyticsAggregationLevel,
  AnalyticsAggregationScope,
  AnalyticsAggregationPrecision,
  getAnalyticsAggregationLabel,
  getAnalyticsAggregationCategoryLabel,
  getAnalyticsAggregationLevelLabel,
  getAnalyticsAggregationScopeLabel,
  getAnalyticsAggregationPrecisionLabel,
  isAnalyticsAggregationStatistical,
  isAnalyticsAggregationMathematical,
  isAnalyticsAggregationTimeSeries,
  isAnalyticsAggregationApproximate,
  getAnalyticsAggregationCategory,
  // Campaign
  ANALYTICS_CAMPAIGN,
  AnalyticsCampaignType,
  AnalyticsCampaignStatus,
  AnalyticsCampaignChannel,
  AnalyticsCampaignObjective,
  AnalyticsCampaignBudgetType,
  AnalyticsCampaignROIStatus,
  AnalyticsCampaignMetric,
  AnalyticsCampaignPriority,
  AnalyticsCampaignVisibility,
  getAnalyticsCampaignTypeLabel,
  getAnalyticsCampaignStatusLabel,
  getAnalyticsCampaignChannelLabel,
  getAnalyticsCampaignObjectiveLabel,
  getAnalyticsCampaignROIStatusLabel,
  getAnalyticsCampaignMetricLabel,
  getAnalyticsCampaignPriorityLabel,
  isAnalyticsCampaignActive,
  isAnalyticsCampaignScheduled,
  isAnalyticsCampaignCompleted,
  getAnalyticsCampaignObjective,
  // Category
  ANALYTICS_CATEGORY,
  AnalyticsCategoryType,
  AnalyticsSubCategoryType,
  AnalyticsCategoryGroup,
  AnalyticsCategoryPriority,
  AnalyticsCategoryVisibility,
  AnalyticsCategoryStatus,
  getAnalyticsCategoryLabel,
  getAnalyticsSubCategoryLabel,
  getAnalyticsCategoryGroupLabel,
  getAnalyticsCategoryPriorityLabel,
  getAnalyticsCategoryStatusLabel,
  isAnalyticsCategoryActive,
  isAnalyticsCategoryArchived,
  // Comparison
  ANALYTICS_COMPARISON,
  AnalyticsComparisonType,
  AnalyticsComparisonMethod,
  AnalyticsComparisonDirection,
  AnalyticsComparisonSignificance,
  AnalyticsComparisonUnit,
  getAnalyticsComparisonLabel,
  getAnalyticsComparisonMethodLabel,
  getAnalyticsComparisonDirectionLabel,
  getAnalyticsComparisonSignificanceLabel,
  getAnalyticsComparisonUnitLabel,
  isAnalyticsComparisonPeriodBased,
  isAnalyticsComparisonBenchmarkBased,
  getAnalyticsComparisonDirection,
  getAnalyticsComparisonSignificance,
  // Dimension
  ANALYTICS_DIMENSION,
  AnalyticsUserDimension,
  AnalyticsSessionDimension,
  AnalyticsLocationDimension,
  AnalyticsDeviceDimension,
  AnalyticsTrafficDimension,
  AnalyticsProductDimension,
  AnalyticsOrderDimension,
  AnalyticsTimeDimension,
  AnalyticsPageDimension,
  AnalyticsEventDimension,
  AnalyticsMarketingDimension,
  AnalyticsSystemDimension,
  AnalyticsDimensionCategory,
  AnalyticsDimensionType,
  AnalyticsDimensionGranularity,
  getAnalyticsDimensionLabel,
  getAnalyticsDimensionCategoryLabel,
  getAnalyticsDimensionTypeLabel,
  getAnalyticsDimensionCategory,
  // Error
  ANALYTICS_ERROR,
  AnalyticsErrorType,
  AnalyticsErrorCode,
  AnalyticsErrorSeverity,
  AnalyticsErrorCategory,
  AnalyticsErrorAction,
  AnalyticsErrorSource,
  getAnalyticsErrorLabel,
  getAnalyticsErrorCodeLabel,
  getAnalyticsErrorSeverityLabel,
  getAnalyticsErrorCategoryLabel,
  getAnalyticsErrorActionLabel,
  getAnalyticsErrorSourceLabel,
  getAnalyticsErrorCategory,
  getAnalyticsErrorSeverity,
  // Event
  ANALYTICS_EVENT,
  AnalyticsEventCategory,
  AnalyticsEventAction,
  AnalyticsEventLabel,
  AnalyticsEventValue,
  AnalyticsEventPriority,
  AnalyticsEventStatus,
  getAnalyticsEventCategoryLabel,
  getAnalyticsEventActionLabel,
  getAnalyticsEventLabelName,
  getAnalyticsEventPriorityLabel,
  getAnalyticsEventStatusLabel,
  isAnalyticsEventCompleted,
  isAnalyticsEventProcessing,
  isAnalyticsEventFailed,
  // Filter
  ANALYTICS_FILTER,
  AnalyticsFilterOperator,
  AnalyticsFilterDataType,
  AnalyticsFilterCategory,
  AnalyticsFilterLogicType,
  AnalyticsFilterMatchType,
  AnalyticsFilterPriority,
  AnalyticsFilterScope,
  getAnalyticsFilterOperatorLabel,
  getAnalyticsFilterDataTypeLabel,
  getAnalyticsFilterCategoryLabel,
  getAnalyticsFilterLogicTypeLabel,
  getAnalyticsFilterMatchTypeLabel,
  getAnalyticsFilterPriorityLabel,
  getAnalyticsFilterScopeLabel,
  isAnalyticsFilterComparisonOperator,
  isAnalyticsFilterStringOperator,
  isAnalyticsFilterSetOperator,
  isAnalyticsFilterNullOperator,
  isAnalyticsFilterLogicalOperator,
  // Interval
  ANALYTICS_INTERVAL,
  AnalyticsIntervalType,
  AnalyticsIntervalCategory,
  AnalyticsIntervalUnit,
  AnalyticsIntervalFormat,
  AnalyticsIntervalGroupingType,
  getAnalyticsIntervalDetailLabel,
  getAnalyticsIntervalCategoryLabel,
  getAnalyticsIntervalUnitLabel,
  getAnalyticsIntervalFormatLabel,
  getAnalyticsIntervalCategory,
  getAnalyticsIntervalUnit,
  getAnalyticsIntervalSeconds,
  // Medium
  ANALYTICS_MEDIUM,
  AnalyticsMediumType,
  AnalyticsMediumCategory,
  AnalyticsMediumTypeEnum,
  AnalyticsMediumChannel,
  AnalyticsMediumPriority,
  getAnalyticsMediumLabel,
  getAnalyticsMediumCategoryLabel,
  getAnalyticsMediumTypeLabel,
  getAnalyticsMediumChannelLabel,
  getAnalyticsMediumPriorityLabel,
  isAnalyticsMediumOrganic,
  isAnalyticsMediumPaid,
  isAnalyticsMediumSocial,
  isAnalyticsMediumEmail,
  getAnalyticsMediumCategory,
  getAnalyticsChannelFromMedium,
  // Metric
  ANALYTICS_METRIC,
  AnalyticsBusinessMetric,
  AnalyticsCustomerMetric,
  AnalyticsSalesMetric,
  AnalyticsMarketingMetric,
  AnalyticsProductMetric,
  AnalyticsWebsiteMetric,
  AnalyticsSupportMetric,
  AnalyticsSystemMetric,
  AnalyticsMetricCategory,
  AnalyticsMetricType,
  AnalyticsMetricAggregation,
  AnalyticsMetricFormat,
  AnalyticsMetricPriority,
  getAnalyticsMetricDetailLabel,
  getAnalyticsMetricCategoryLabel,
  getAnalyticsMetricTypeLabel,
  getAnalyticsMetricFormatLabel,
  getAnalyticsMetricPriorityLabel,
  getAnalyticsMetricCategory,
  // Period
  ANALYTICS_PERIOD,
  AnalyticsPeriodType,
  AnalyticsPeriodTypeEnum,
  AnalyticsPeriodGranularity,
  AnalyticsPeriodComparisonType,
  AnalyticsPeriodFormat,
  getAnalyticsPeriodLabel,
  getAnalyticsPeriodTypeLabel,
  getAnalyticsPeriodGranularityLabel,
  getAnalyticsPeriodComparisonTypeLabel,
  isAnalyticsPeriodRolling,
  isAnalyticsPeriodFixed,
  isAnalyticsPeriodRelative,
  getAnalyticsPeriodDays,
  // Permission
  ANALYTICS_PERMISSION,
  AnalyticsPermissionDetailType,
  AnalyticsPermissionResource,
  AnalyticsPermissionLevel,
  AnalyticsPermissionScope,
  AnalyticsPermissionAction,
  AnalyticsPermissionEffect,
  AnalyticsPermissionCondition,
  getAnalyticsPermissionDetailLabel,
  getAnalyticsPermissionResourceLabel,
  getAnalyticsPermissionLevelLabel,
  getAnalyticsPermissionScopeLabel,
  getAnalyticsPermissionActionLabel,
  getAnalyticsPermissionEffectLabel,
  getAnalyticsPermissionConditionLabel,
  isAnalyticsPermissionAdmin,
  isAnalyticsPermissionManagement,
  isAnalyticsPermissionView,
  getAnalyticsPermissionLevel,
  // Source
  ANALYTICS_SOURCE,
  AnalyticsSourceType,
  AnalyticsSourceCategory,
  AnalyticsSourceSubCategory,
  AnalyticsSourceTypeEnum,
  AnalyticsSourceConfidence,
  AnalyticsSourceValidity,
  getAnalyticsSourceLabel,
  getAnalyticsSourceCategoryLabel,
  getAnalyticsSourceConfidenceLabel,
  getAnalyticsSourceValidityLabel,
  isAnalyticsSocialMedia,
  isAnalyticsSearchEngine,
  isAnalyticsOrganic,
  isAnalyticsPaid,
  getAnalyticsSourceCategory,
  // Status
  ANALYTICS_STATUS,
  AnalyticsStatusCode,
  AnalyticsStatusCategory,
  AnalyticsStatusPriority,
  AnalyticsStatusVisibility,
  AnalyticsStatusAction,
  getAnalyticsStatusCodeLabel,
  getAnalyticsStatusCategoryLabel,
  getAnalyticsStatusPriorityLabel,
  getAnalyticsStatusVisibilityLabel,
  getAnalyticsStatusActionLabel,
  isAnalyticsStatusSuccess,
  isAnalyticsStatusProcessing,
  isAnalyticsStatusFailure,
  isAnalyticsStatusFinalState,
  getAnalyticsStatusCategory,
  // Trend
  ANALYTICS_TREND,
  AnalyticsTrendType,
  AnalyticsTrendStrength,
  AnalyticsTrendDirection,
  AnalyticsTrendPattern,
  AnalyticsTrendMethod,
  AnalyticsTrendConfidence,
  AnalyticsTrendHorizon,
  getAnalyticsTrendDetailLabel,
  getAnalyticsTrendStrengthLabel,
  getAnalyticsTrendDirectionLabel,
  getAnalyticsTrendPatternLabel,
  getAnalyticsTrendMethodLabel,
  getAnalyticsTrendConfidenceLabel,
  getAnalyticsTrendHorizonLabel,
  isAnalyticsTrendUpward,
  isAnalyticsTrendDownward,
  isAnalyticsTrendStable,
  getAnalyticsTrendDirectionFromSlope,
  getAnalyticsTrendStrengthFromRSquared,
  // Type
  ANALYTICS_TYPE,
  AnalyticsDataType,
  AnalyticsReportType,
  AnalyticsDataSource,
  AnalyticsGranularity,
  AnalyticsQuality,
  AnalyticsAnalysisType,
  AnalyticsRefreshRate,
  AnalyticsRetention,
  AnalyticsSensitivity,
  AnalyticsUsage,
  getAnalyticsDataTypeLabel,
  getAnalyticsReportTypeLabel,
  getAnalyticsDataSourceLabel,
  getAnalyticsQualityLabel,
  getAnalyticsAnalysisTypeLabel,
  getAnalyticsSensitivityLabel,
  isAnalyticsRealtime,
  isAnalyticsHistorical,
  isAnalyticsPredictive,
  // Retention Analytics
  RETENTION_ANALYTICS,
  RetentionAnalyticsType,
  RetentionAnalyticsStatus,
  RetentionAnalyticsPeriod,
  RetentionAnalyticsCohort,
  RetentionAnalyticsMetric,
  RetentionAnalyticsSegment,
  getRetentionAnalyticsLabel,
  getRetentionAnalyticsStatusLabel,
  getRetentionAnalyticsPeriodLabel,
  getRetentionAnalyticsCohortLabel,
  getRetentionAnalyticsMetricDetailLabel,
  getRetentionAnalyticsSegmentLabel,
  isRetentionAnalyticsActive,
  isRetentionAnalyticsCompleted,
  getRetentionAnalyticsRateValue,
};
