/**
 * Auth Types - Root Barrel Export
 * Enterprise Grade for vubon.com.bd - Bangladesh's #1 E-commerce
 * 
 * @module shared-types/index
 * 
 * RULES:
 * ✅ ONLY re-exports - NO logic, NO initialization
 * ✅ NO functions, NO side effects
 * ✅ Pure TypeScript type exports only
 */

// ============================================================
// Common Utility Types (Re-export all from common)
// ============================================================
export * from './common';

// ============================================================
// Auth Domain Types (Re-export all from auth)
// ============================================================
export * from './auth';

// ============================================================
// Value Object Types (Enterprise Grade)
// ============================================================
export type {
  // Core Value Object Types
  ValueObjectComparison,
  TemporalEqualityConfig,
  
  // Metadata and Snapshot Types
  ValueObjectMetadata,
  ValueObjectSnapshot,
  
  // Validation Types
  ValidationErrorCode,
  ValidationResult,
  
  // Serialization Types
  ValueObjectSerializationOptions,
  ValueObjectDeserializationOptions,
  
  // Performance and Optimization Types
  EqualityCacheConfig,
  ValueObjectPerformanceMetrics,
  
  // Domain-Specific Value Object Types
  EmailValueObject,
  PhoneValueObject,
  DeviceIdValueObject,
  
  // Utility Types
  ValueObjectConstructor,
  ValueObjectPredicate,
  ValueObjectTransformer,
  ValueObjectFactory,
  
  // Error Types
  ValueObjectError,
  ValueObjectErrorFactory,
} from './common/value-object.types';

// ============================================================
// Auth Domain Types (Selective export to avoid conflicts)
// ============================================================
export {
  // User Types
  type UserStatus,
  type UserVerificationStatus,
  type UserTier,
  type User,
  type UserMetadata,
  type UserDTO,
  type UserProfileDTO,
  type CreateUserRequest,
  type UpdateUserRequest,
  type UserListResponse,
  type UserFilters,
  type UserActivitySummary,
  type UserPreferences,
  type UserSessionInfo,
  type ChangePasswordRequest,
  type ResetPasswordRequest,
  type ForgotPasswordRequest,
  type VerifyEmailRequest,
  type VerifyPhoneRequest,
  type SendPhoneOTPRequest,
  type BulkUserOperation,
  type BulkUserOperationResult,
  type UserExportOptions,
  type UserExportResult,
  type UserAddress,
  type UserKYCDocument,
  type UserStatistics,
  type UserWebhookEventType,
  type UserWebhookPayload,
  
  // Session Types
  type SessionStatus,
  type ExtendedSessionStatus,
  type SessionTokens,
  type Session,
  type SessionDTO,
  type CreateSessionRequest,
  type CreateSessionResponse,
  type SessionValidationResult,
  type SessionError,
  type RefreshSessionRequest,
  type RefreshSessionResponse,
  type TerminateSessionRequest,
  type TerminateSessionsOptions,
  type TerminateSessionsResult,
  type SessionTransferRequest,
  type SessionTransferResponse,
  type SessionMetadata,
  type SessionAction,
  type SessionStatistics,
  type SessionCleanupCriteria,
  type SessionCleanupResult,
  type SessionFilterOptions,
  type SessionWebhookEventType,
  type SessionWebhookPayload,
  type SessionAlertConfig,
  type SessionHeartbeatRequest,
  type SessionHeartbeatResponse,
  type PublicDeviceWarning,
  
  // Token Types
  type TokenType,
  type TokenAlgorithm,
  type BaseTokenPayload,
  type AccessTokenPayload,
  type RefreshTokenPayload,
  type VerificationPurpose,
  type VerificationTokenPayload,
  type MFATokenPayload,
  type MagicLinkTokenPayload,
  type SessionTransferTokenPayload,
  type DeviceTrustTokenPayload,
  type MFSProviderPayload,
  type WhatsAppOTPPayload,
  type APIKeyPayload,
  type Token,
  type TokenMetadata,
  type TokenValidationResult,
  type TokenError,
  type CreateTokenRequest,
  type TokenResponse,
  type BlacklistedToken,
  type CreateAPIKeyRequest,
  type APIKeyResponse,
  type APIKeyValidationResult,
  type TokenIntrospectionRequest,
  type TokenIntrospectionResponse,
  type TokenRotationRequest,
  type TokenRotationResponse,
  type TokenStatistics,
  
  // Role Types
  type Role,
  type ExtendedRole,
  type RoleHierarchyMap,
  type RoleHierarchyValue,
  type RoleCategory,
  type RoleMetadata,
  type RoleInheritance,
  type RoleAssignment,
  type RoleDTO,
  type CreateCustomRoleRequest,
  type UpdateRoleRequest,
  type DeleteRoleRequest,
  type AssignRoleRequest,
  type RemoveRoleRequest,
  type BulkRoleAssignmentRequest,
  type BulkRoleAssignmentResult,
  type UserRolesResponse,
  type RoleValidationResult,
  type RoleStatistics,
  type RoleFilterOptions,
  type RoleComparisonResult,
  type RoleEventType,
  type RoleEvent,
  type SystemRole,
  type RoleHierarchyCheckResult,
  type RolePermissionSummary,
  type RoleAssignmentHistory,
  type RoleExportData,
  type RoleImportResult,
  type AvailableRole,
  
  // Permission Types
  type PermissionResource,
  type ExtendedPermissionResource,
  type PermissionAction,
  type ExtendedPermissionAction,
  type PermissionString,
  type UserPermissions,
  type RolePermissions,
  type PermissionManagementPermissions,
  type ProductPermissions,
  type CategoryPermissions,
  type OrderPermissions,
  type PaymentPermissions,
  type VendorPermissions,
  type DeliveryPermissions,
  type MFSPaymentPermissions,
  type Permission,
  type PermissionGroup,
  type RolePermissionAssignment,
  type PermissionCheckRequest,
  type PermissionContext,
  type PermissionCheckResult,
  type PermissionDeniedReason,
  type PermissionDTO,
  type PermissionTreeNode,
  type UserPermissionsResponse,
  type BulkPermissionCheckRequest,
  type BulkPermissionCheckResult,
  type PermissionMigration,
  type PermissionSyncRequest,
  type PermissionSyncResult,
  type PermissionCacheInvalidation,
  type PermissionStatistics,
  type PermissionFilterOptions,
  type PermissionEventType,
  type PermissionEvent,
  type WildcardPermission,
  type WildcardMatchResult,
  type PermissionValidationResult,
  type PermissionDependency,
  type PermissionDependencyGraph,
  
  // MFA Types
  type MFAProvider,
  type ExtendedMFAProvider,
  type MFAStatus,
  type ExtendedMFAStatus,
  type MFAVerificationType,
  type ExtendedMFAVerificationType,
  type MFAMethod,
  type MFAMethodMetadata,
  type TOTPMetadata,
  type BackupCode,
  type BackupCodesResponse,
  type WebAuthnMetadata,
  type WebAuthnRegistrationRequest,
  type WebAuthnRegistrationResponse,
  type WebAuthnAuthRequest,
  type WhatsAppMetadata,
  type MFSMetadata,
  type MFASetupRequest,
  type MFASetupResponse,
  type MFAVerificationRequest,
  type MFAVerificationResult,
  type MFAStatusResponse,
  type MFAMethodDTO,
  type DisableMFARequest,
  type MFARecoveryRequest,
  type MFARecoveryResponse,
  type MFAChallengeRequest,
  type MFAChallengeResponse,
  type MFARiskAssessment,
  type MFARiskFactor,
  type MFAPreset,
  type MFAPresetConfig,
  type MFATrustedDevice,
  type MFAEventType,
  type MFAEvent,
  type MFASettings,
  type MFAFilterOptions,
  type MFAStatistics,
  type MFAWebhookEventType,
  type MFAWebhookPayload,
  
  // Device Types (excluding LocationInfo to avoid conflict)
  type BaseDeviceType,
  type DeviceType,
  type ExtendedDeviceType,
  type BaseOSType,
  type OSType,
  type ExtendedOSType,
  type BaseBrowserType,
  type BrowserType,
  type ExtendedBrowserType,
  type NetworkType,
  type MobileOperator,
  type DeviceTrustLevel,
  type ExtendedTrustLevel,
  type DeviceInfo,
  type FingerprintComponentValue,
  type DeviceFingerprint,
  type FingerprintData,
  type TrustedDevice,
  type RegisterDeviceRequest,
  type DeviceDTO,
  type UpdateDeviceTrustRequest,
  type RemoveDeviceRequest,
  type DeviceActivityType,
  type DeviceActivity,
  type DeviceRiskAssessment,
  type DeviceRiskFactor,
  type RiskIndicator,
  type DeviceStatistics,
  type DeviceSessionTransfer,
  type DevicePairing,
  type PairedDevicePermission,
  type PublicDeviceSession,
  type PublicDeviceRestriction,
  type DeviceVerificationRequest,
  type DeviceWebhookEventType,
  type DeviceWebhookPayload,
  type DeviceFilterOptions,
  type DeviceTrustDurationValue,
  type DeviceTrustDuration,
  type DeviceCategory,
  type DeviceTypeToCategoryMap,
  type BrowserTrustScore,
  type BrowserTrustLevels,
  type NetworkSecurityScore,
  type NetworkSecurityLevels,
  type DeviceMetrics,
  
  // Verification Types
  type VerificationType,
  type VerificationStatus,
  type VerificationMethod,
  type Verification,
  type VerificationMetadata,
  type CreateVerificationRequest,
  type VerifyRequest,
  type VerificationResult,
  type ResendVerificationRequest,
  type ResendVerificationResponse,
  type VerificationDTO,
  type MagicLinkRequest,
  type MagicLinkResponse,
  type MagicLinkVerification,
  type EmailChangeRequest,
  type EmailChangeResponse,
  type EmailChangeVerification,
  type PhoneChangeRequest,
  type PhoneChangeResponse,
  type PhoneVerificationRequest,
  type PhoneVerificationResponse,
  type WhatsAppVerificationRequest,
  type WhatsAppVerificationResponse,
  type VoiceVerificationRequest,
  type VoiceVerificationResponse,
  type VerificationStatistics,
  type VerificationFilterOptions,
  type VerificationRateLimit,
  type VerificationCleanupCriteria,
  type VerificationCleanupResult,
  type VerificationWebhookEventType,
  type VerificationWebhookPayload,
  type OTPConfig,
  type EmailVerificationTemplate,
  type SMSVerificationTemplate,
  type WhatsAppVerificationTemplate,
  type VerificationAuditLog,
  type VerificationHealthStatus,
  
  // Account Lock Types
  type LockReason,
  type LockStatus,
  type LockLevel,
  type LockLevelConfig,
  type AccountLock,
  type LockMetadata,
  type LockEscalationEvent,
  type AccountLockStatusResponse,
  type LockAccountRequest,
  type UnlockAccountRequest,
  type AccountLockHistoryResponse,
  type LockThresholdConfig,
  type FailedAttemptEvent,
  type LockNotificationType,
  type LockNotificationPayload,
  type LockAuditLogEntry,
  type BulkLockRequest,
  type BulkUnlockRequest,
  type BulkLockResult,
  type AutoUnlockSchedule,
  type LockDashboardStats,
  type ProgressiveLockoutLevel,
  type ProgressiveLockoutConfig,
  type SmartLockDetectionResult,
  type UnusualPattern,
  
  // Login Attempt Types
  type LoginAttemptStatus,
  type LoginFailureReason,
  type LoginAttempt,
  type LocationInfo as AuthLocationInfo,
  type LoginAttemptMetadata,
  type CreateLoginAttemptRequest,
  type LoginAttemptResponse,
  type LoginAttemptDTO,
  type DeviceSummary,
  type LoginAttemptStatistics,
  type LoginHistoryResponse,
  type RateLimitStatus,
  type RateLimitEndpoint,
  type RateLimitConfig as AuthRateLimitConfig,
  type BlockedIP,
  type BlockIPRequest,
  type UnblockIPRequest,
  type BlockedDevice,
  type SuspiciousPattern,
  type MitigationAction,
  type SuspiciousPatternType,
  type PatternDetectionResult,
  type LoginAlertConfig,
  type LoginAlertEvent,
  type LoginAttemptFilterOptions,
  type LoginAuditLog,
  type LoginWebhookEventType,
  type LoginWebhookPayload,
  type LoginAttemptCleanupConfig,
  type LoginRecoveryRequest,
  type LoginRecoveryResponse,
  type FailedAttemptSummary,
  
  // Social Types
  type SocialProvider,
  type ExtendedSocialProvider,
  type SocialProviderCategory,
  type SocialAccount,
  type SocialAccountMetadata,
  type SocialProviderData,
  type GoogleProviderData,
  type GitHubProviderData,
  type FacebookProviderData,
  type AppleProviderData,
  type TwitterProviderData,
  type LinkedInProviderData,
  type MicrosoftProviderData,
  type InstagramProviderData,
  type TikTokProviderData,
  type WhatsAppProviderData,
  type ImoProviderData,
  type TelegramProviderData,
  type MFSProviderData,
  type OAuthAuthorizationRequest,
  type OAuthAuthorizationResponse,
  type OAuthCallbackRequest,
  type OAuthCallbackResponse,
  type SocialUserInfo,
  type ConnectSocialAccountRequest,
  type ConnectSocialAccountResponse,
  type DisconnectSocialAccountRequest,
  type DisconnectSocialAccountResponse,
  type SocialAccountDTO,
  type OAuthProviderConfig,
  type OAuthStateData,
  type SocialLoginOptions,
  type LinkSocialAccountsRequest,
  type LinkSocialAccountsResponse,
  type SocialAuthStatistics,
  type SocialAccountFilterOptions,
  type SocialAuthEventType,
  type SocialAuthEvent,
  type SocialOTPRequest,
  type SocialOTPResponse,
  type SocialOTPVerificationRequest,
  type MFSAuthRequest,
  type MFSAuthResponse,
  type SocialProviderPriority,
  type SocialLoginButtonConfig,
} from './auth';

// ============================================================
// Common Utility Types (Selective export to avoid conflicts)
// ============================================================
export {
  // API Types
  type ApiResponse,
  type ApiErrorResponse,
  type PaginatedApiResponse,
  type ApiErrorCode,
  type ErrorCodeMapping,
  type ValidationErrorDetail,
  type ValidationErrorResponse,
  type ApiRequestOptions,
  type RequestCache,
  type HttpMethod,
  type ApiEndpoint,
  type RateLimitConfig as CommonRateLimitConfig,
  type RateLimitHeaders,
  type ApiHealthStatus,
  type ApiMetrics,
  type WebSocketMessage,
  type WebSocketMessageType,
  type WebSocketAuthMessage,
  type WebSocketSubscribeMessage,
  type SSEMessage,
  type SSEEventType,
  type ApiVersionInfo,
  type ApiCorsConfig,
  type RequestContext,
  type ApiCacheConfig,
  type ApiWebhookPayload,
  type ApiWebhookDeliveryResult,
  type ApiRetryConfig,
  type ApiCircuitBreakerConfig,
  type ApiCircuitBreakerState,
  
  // Pagination Types
  type SortOrder,
  type PaginationMetadata,
  type PaginationParams,
  type ExtendedPaginationParams,
  type PaginationSort,
  type OffsetPaginationResponse,
  type CursorPaginationParams,
  type CursorPaginationResponse,
  type CursorInfo,
  type InfiniteScrollResponse,
  type PaginationFilters,
  type PageRequest,
  type PageResult,
  type BatchProcessingOptions,
  type BatchProcessingResult,
  type PaginationLink,
  type PaginationLinks,
  type PaginationMetaWithLinks,
  type FullPaginatedResponse,
  type PaginationDefaults,
  type SortableField,
  type SortableFieldsConfig,
  type PaginationValidationResult,
  type SearchPaginationParams,
  type ProductSearchPaginationParams,
  type OrderPaginationParams,
  type PaginationEvent,
  type PaginationCacheConfig,
  type PaginationMetrics,
  
  // Audit Types
  type AuditAction,
  type AuditSeverity,
  type AuditResource,
  type AuditLog,
  type AuditChange,
  type AuditMetadata,
  type CreateAuditLogRequest,
  type AuditLogFilters,
  type AuditLogDTO,
  type AuditStatistics,
  type AuditRetentionPolicy,
  type AuditExportRequest,
  type AuditExportResponse,
  type AuditCleanupResult,
  type AuditWebhookEvent,
  type AuditSearchResult,
  type AuditComplianceReport,
  
  // SEO Types
  type MetaTag,
  type OpenGraphTags,
  type OgType,
  type TwitterCardTags,
  type TwitterCardType,
  type StructuredData,
  type ProductStructuredData,
  type OfferStructuredData,
  type OfferAvailability,
  type OfferItemCondition,
  type ArticleStructuredData,
  type BreadcrumbStructuredData,
  type OrganizationStructuredData,
  type PersonStructuredData,
  type ReviewStructuredData,
  type FAQStructuredData,
  type HowToStructuredData,
  type LocalBusinessStructuredData,
  type MerchantStructuredData,
  type SEOMetadata,
  type RobotDirective,
  type SitemapEntry,
  type ChangeFrequency,
  type SitemapVideo,
  type SEOAnalysisResult,
  type SEOIssue,
  type ProductSEOSettings,
  type CategorySEOSettings,
  type PageSEOSettings,
  type RobotsTxtConfig,
  type SEOPerformanceMetrics,
  
  // Location Types
  type LocationInfo,
  type Coordinates,
  type GeoLocation,
  type Division,
  type District,
  type Upazila,
  type Union,
  type Ward,
  type Address,
  type DeliveryZone,
  type DeliveryCoverageResult,
  type UserLocationHistory,
  type LocationChangeResult,
  type BangladeshDivisionName,
  type BangladeshDivisionNameBn,
  type LocationFilterOptions,
  type IPGeolocationResponse,
} from './common';
