/**
 * SMS Marketing Status Constants
 * Status definitions for SMS lifecycle
 */

export const MARKETINGSMS_STATUS = {
  // SMS Statuses
  STATUSES: {
    DRAFT: 'draft',
    PENDING_APPROVAL: 'pending_approval',
    APPROVED: 'approved',
    REJECTED: 'rejected',
    SCHEDULED: 'scheduled',
    QUEUED: 'queued',
    PROCESSING: 'processing',
    SENT: 'sent',
    DELIVERED: 'delivered',
    FAILED: 'failed',
    UNDELIVERED: 'undelivered',
    EXPIRED: 'expired',
    REJECTED_BY_PROVIDER: 'rejected_by_provider',
    DEFERRED: 'deferred',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    PAUSED: 'paused',
    OPT_OUT: 'opt_out',
    CLICKED: 'clicked',
    REPLIED: 'replied',
    PENDING_DELIVERY: 'pending_delivery',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    DRAFT: '#6B7280',
    PENDING_APPROVAL: '#F59E0B',
    APPROVED: '#10B981',
    REJECTED: '#EF4444',
    SCHEDULED: '#3B82F6',
    QUEUED: '#8B5CF6',
    PROCESSING: '#3B82F6',
    SENT: '#10B981',
    DELIVERED: '#10B981',
    FAILED: '#EF4444',
    UNDELIVERED: '#EF4444',
    EXPIRED: '#6B7280',
    REJECTED_BY_PROVIDER: '#EF4444',
    DEFERRED: '#F59E0B',
    CANCELLED: '#6B7280',
    ARCHIVED: '#6B7280',
    PAUSED: '#F59E0B',
    OPT_OUT: '#6B7280',
    CLICKED: '#10B981',
    REPLIED: '#10B981',
    PENDING_DELIVERY: '#3B82F6',
  } as const,

  // Status Categories
  CATEGORIES: {
    DRAFT: 'draft',
    PENDING: 'pending',
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    ENGAGED: 'engaged',
    OPT_OUT: 'opt_out',
  } as const,

  // Status Priority Order
  ORDER: {
    DRAFT: 0,
    PENDING_APPROVAL: 1,
    APPROVED: 2,
    REJECTED: 3,
    SCHEDULED: 4,
    QUEUED: 5,
    PROCESSING: 6,
    SENT: 7,
    PENDING_DELIVERY: 8,
    DELIVERED: 9,
    CLICKED: 10,
    REPLIED: 11,
    OPT_OUT: 12,
    UNDELIVERED: 13,
    FAILED: 14,
    REJECTED_BY_PROVIDER: 15,
    DEFERRED: 16,
    EXPIRED: 17,
    PAUSED: 18,
    CANCELLED: 19,
    ARCHIVED: 20,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    DRAFT_TO_PENDING: 'draft_to_pending',
    DRAFT_TO_CANCELLED: 'draft_to_cancelled',
    DRAFT_TO_ARCHIVED: 'draft_to_archived',
    PENDING_TO_APPROVED: 'pending_to_approved',
    PENDING_TO_REJECTED: 'pending_to_rejected',
    PENDING_TO_CANCELLED: 'pending_to_cancelled',
    APPROVED_TO_SCHEDULED: 'approved_to_scheduled',
    APPROVED_TO_REJECTED: 'approved_to_rejected',
    SCHEDULED_TO_QUEUED: 'scheduled_to_queued',
    SCHEDULED_TO_CANCELLED: 'scheduled_to_cancelled',
    QUEUED_TO_PROCESSING: 'queued_to_processing',
    QUEUED_TO_CANCELLED: 'queued_to_cancelled',
    PROCESSING_TO_SENT: 'processing_to_sent',
    PROCESSING_TO_FAILED: 'processing_to_failed',
    PROCESSING_TO_CANCELLED: 'processing_to_cancelled',
    SENT_TO_PENDING_DELIVERY: 'sent_to_pending_delivery',
    SENT_TO_FAILED: 'sent_to_failed',
    SENT_TO_DEFERRED: 'sent_to_deferred',
    PENDING_DELIVERY_TO_DELIVERED: 'pending_delivery_to_delivered',
    PENDING_DELIVERY_TO_UNDELIVERED: 'pending_delivery_to_undelivered',
    PENDING_DELIVERY_TO_FAILED: 'pending_delivery_to_failed',
    PENDING_DELIVERY_TO_EXPIRED: 'pending_delivery_to_expired',
    DELIVERED_TO_CLICKED: 'delivered_to_clicked',
    DELIVERED_TO_REPLIED: 'delivered_to_replied',
    DELIVERED_TO_OPT_OUT: 'delivered_to_opt_out',
    DELIVERED_TO_FAILED: 'delivered_to_failed',
    CLICKED_TO_REPLIED: 'clicked_to_replied',
    CLICKED_TO_OPT_OUT: 'clicked_to_opt_out',
    REPLIED_TO_OPT_OUT: 'replied_to_opt_out',
    UNDELIVERED_TO_ARCHIVED: 'undelivered_to_archived',
    FAILED_TO_ARCHIVED: 'failed_to_archived',
    REJECTED_BY_PROVIDER_TO_ARCHIVED: 'rejected_by_provider_to_archived',
    EXPIRED_TO_ARCHIVED: 'expired_to_archived',
    DEFERRED_TO_PROCESSING: 'deferred_to_processing',
    DEFERRED_TO_FAILED: 'deferred_to_failed',
    DEFERRED_TO_CANCELLED: 'deferred_to_cancelled',
    OPT_OUT_TO_ARCHIVED: 'opt_out_to_archived',
    PAUSED_TO_PROCESSING: 'paused_to_processing',
    PAUSED_TO_CANCELLED: 'paused_to_cancelled',
    REJECTED_TO_DRAFT: 'rejected_to_draft',
    REJECTED_TO_ARCHIVED: 'rejected_to_archived',
    CANCELLED_TO_ARCHIVED: 'cancelled_to_archived',
  } as const,
} as const;

// SMS Statuses
export type MarketingSMSStatusType =
  (typeof MARKETINGSMS_STATUS.STATUSES)[keyof typeof MARKETINGSMS_STATUS.STATUSES];

// Status Colors
export type MarketingSMSStatusColor =
  (typeof MARKETINGSMS_STATUS.COLORS)[keyof typeof MARKETINGSMS_STATUS.COLORS];

// Status Categories
export type MarketingSMSStatusCategory =
  (typeof MARKETINGSMS_STATUS.CATEGORIES)[keyof typeof MARKETINGSMS_STATUS.CATEGORIES];

// Status Priority Order
export type MarketingSMSStatusOrder =
  (typeof MARKETINGSMS_STATUS.ORDER)[keyof typeof MARKETINGSMS_STATUS.ORDER];

// Status Transitions
export type MarketingSMSStatusTransition =
  (typeof MARKETINGSMS_STATUS.TRANSITIONS)[keyof typeof MARKETINGSMS_STATUS.TRANSITIONS];

// Utility Functions
export function marketingsmsGetStatusLabel(status: MarketingSMSStatusType): string {
  const labels: Record<MarketingSMSStatusType, string> = {
    [MARKETINGSMS_STATUS.STATUSES.DRAFT]: 'Draft',
    [MARKETINGSMS_STATUS.STATUSES.PENDING_APPROVAL]: 'Pending Approval',
    [MARKETINGSMS_STATUS.STATUSES.APPROVED]: 'Approved',
    [MARKETINGSMS_STATUS.STATUSES.REJECTED]: 'Rejected',
    [MARKETINGSMS_STATUS.STATUSES.SCHEDULED]: 'Scheduled',
    [MARKETINGSMS_STATUS.STATUSES.QUEUED]: 'Queued',
    [MARKETINGSMS_STATUS.STATUSES.PROCESSING]: 'Processing',
    [MARKETINGSMS_STATUS.STATUSES.SENT]: 'Sent',
    [MARKETINGSMS_STATUS.STATUSES.DELIVERED]: 'Delivered',
    [MARKETINGSMS_STATUS.STATUSES.FAILED]: 'Failed',
    [MARKETINGSMS_STATUS.STATUSES.UNDELIVERED]: 'Undelivered',
    [MARKETINGSMS_STATUS.STATUSES.EXPIRED]: 'Expired',
    [MARKETINGSMS_STATUS.STATUSES.REJECTED_BY_PROVIDER]: 'Rejected by Provider',
    [MARKETINGSMS_STATUS.STATUSES.DEFERRED]: 'Deferred',
    [MARKETINGSMS_STATUS.STATUSES.CANCELLED]: 'Cancelled',
    [MARKETINGSMS_STATUS.STATUSES.ARCHIVED]: 'Archived',
    [MARKETINGSMS_STATUS.STATUSES.PAUSED]: 'Paused',
    [MARKETINGSMS_STATUS.STATUSES.OPT_OUT]: 'Opt Out',
    [MARKETINGSMS_STATUS.STATUSES.CLICKED]: 'Clicked',
    [MARKETINGSMS_STATUS.STATUSES.REPLIED]: 'Replied',
    [MARKETINGSMS_STATUS.STATUSES.PENDING_DELIVERY]: 'Pending Delivery',
  };
  return labels[status] || 'Unknown Status';
}

export function marketingsmsGetStatusColor(
  status: MarketingSMSStatusType
): MarketingSMSStatusColor {
  const colors: Record<MarketingSMSStatusType, MarketingSMSStatusColor> = {
    [MARKETINGSMS_STATUS.STATUSES.DRAFT]: MARKETINGSMS_STATUS.COLORS.DRAFT,
    [MARKETINGSMS_STATUS.STATUSES.PENDING_APPROVAL]: MARKETINGSMS_STATUS.COLORS.PENDING_APPROVAL,
    [MARKETINGSMS_STATUS.STATUSES.APPROVED]: MARKETINGSMS_STATUS.COLORS.APPROVED,
    [MARKETINGSMS_STATUS.STATUSES.REJECTED]: MARKETINGSMS_STATUS.COLORS.REJECTED,
    [MARKETINGSMS_STATUS.STATUSES.SCHEDULED]: MARKETINGSMS_STATUS.COLORS.SCHEDULED,
    [MARKETINGSMS_STATUS.STATUSES.QUEUED]: MARKETINGSMS_STATUS.COLORS.QUEUED,
    [MARKETINGSMS_STATUS.STATUSES.PROCESSING]: MARKETINGSMS_STATUS.COLORS.PROCESSING,
    [MARKETINGSMS_STATUS.STATUSES.SENT]: MARKETINGSMS_STATUS.COLORS.SENT,
    [MARKETINGSMS_STATUS.STATUSES.DELIVERED]: MARKETINGSMS_STATUS.COLORS.DELIVERED,
    [MARKETINGSMS_STATUS.STATUSES.FAILED]: MARKETINGSMS_STATUS.COLORS.FAILED,
    [MARKETINGSMS_STATUS.STATUSES.UNDELIVERED]: MARKETINGSMS_STATUS.COLORS.UNDELIVERED,
    [MARKETINGSMS_STATUS.STATUSES.EXPIRED]: MARKETINGSMS_STATUS.COLORS.EXPIRED,
    [MARKETINGSMS_STATUS.STATUSES.REJECTED_BY_PROVIDER]:
      MARKETINGSMS_STATUS.COLORS.REJECTED_BY_PROVIDER,
    [MARKETINGSMS_STATUS.STATUSES.DEFERRED]: MARKETINGSMS_STATUS.COLORS.DEFERRED,
    [MARKETINGSMS_STATUS.STATUSES.CANCELLED]: MARKETINGSMS_STATUS.COLORS.CANCELLED,
    [MARKETINGSMS_STATUS.STATUSES.ARCHIVED]: MARKETINGSMS_STATUS.COLORS.ARCHIVED,
    [MARKETINGSMS_STATUS.STATUSES.PAUSED]: MARKETINGSMS_STATUS.COLORS.PAUSED,
    [MARKETINGSMS_STATUS.STATUSES.OPT_OUT]: MARKETINGSMS_STATUS.COLORS.OPT_OUT,
    [MARKETINGSMS_STATUS.STATUSES.CLICKED]: MARKETINGSMS_STATUS.COLORS.CLICKED,
    [MARKETINGSMS_STATUS.STATUSES.REPLIED]: MARKETINGSMS_STATUS.COLORS.REPLIED,
    [MARKETINGSMS_STATUS.STATUSES.PENDING_DELIVERY]: MARKETINGSMS_STATUS.COLORS.PENDING_DELIVERY,
  };
  return colors[status] || MARKETINGSMS_STATUS.COLORS.DRAFT;
}

export function marketingsmsGetStatusCategory(
  status: MarketingSMSStatusType
): MarketingSMSStatusCategory {
  const categories: Record<MarketingSMSStatusType, MarketingSMSStatusCategory> = {
    [MARKETINGSMS_STATUS.STATUSES.DRAFT]: MARKETINGSMS_STATUS.CATEGORIES.DRAFT,
    [MARKETINGSMS_STATUS.STATUSES.PENDING_APPROVAL]: MARKETINGSMS_STATUS.CATEGORIES.PENDING,
    [MARKETINGSMS_STATUS.STATUSES.APPROVED]: MARKETINGSMS_STATUS.CATEGORIES.PENDING,
    [MARKETINGSMS_STATUS.STATUSES.REJECTED]: MARKETINGSMS_STATUS.CATEGORIES.FAILED,
    [MARKETINGSMS_STATUS.STATUSES.SCHEDULED]: MARKETINGSMS_STATUS.CATEGORIES.PENDING,
    [MARKETINGSMS_STATUS.STATUSES.QUEUED]: MARKETINGSMS_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGSMS_STATUS.STATUSES.PROCESSING]: MARKETINGSMS_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGSMS_STATUS.STATUSES.SENT]: MARKETINGSMS_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGSMS_STATUS.STATUSES.PENDING_DELIVERY]: MARKETINGSMS_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGSMS_STATUS.STATUSES.DELIVERED]: MARKETINGSMS_STATUS.CATEGORIES.COMPLETED,
    [MARKETINGSMS_STATUS.STATUSES.CLICKED]: MARKETINGSMS_STATUS.CATEGORIES.ENGAGED,
    [MARKETINGSMS_STATUS.STATUSES.REPLIED]: MARKETINGSMS_STATUS.CATEGORIES.ENGAGED,
    [MARKETINGSMS_STATUS.STATUSES.OPT_OUT]: MARKETINGSMS_STATUS.CATEGORIES.OPT_OUT,
    [MARKETINGSMS_STATUS.STATUSES.UNDELIVERED]: MARKETINGSMS_STATUS.CATEGORIES.FAILED,
    [MARKETINGSMS_STATUS.STATUSES.FAILED]: MARKETINGSMS_STATUS.CATEGORIES.FAILED,
    [MARKETINGSMS_STATUS.STATUSES.REJECTED_BY_PROVIDER]: MARKETINGSMS_STATUS.CATEGORIES.FAILED,
    [MARKETINGSMS_STATUS.STATUSES.DEFERRED]: MARKETINGSMS_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGSMS_STATUS.STATUSES.EXPIRED]: MARKETINGSMS_STATUS.CATEGORIES.FAILED,
    [MARKETINGSMS_STATUS.STATUSES.PAUSED]: MARKETINGSMS_STATUS.CATEGORIES.PENDING,
    [MARKETINGSMS_STATUS.STATUSES.CANCELLED]: MARKETINGSMS_STATUS.CATEGORIES.CANCELLED,
    [MARKETINGSMS_STATUS.STATUSES.ARCHIVED]: MARKETINGSMS_STATUS.CATEGORIES.ARCHIVED,
  };
  return categories[status] || MARKETINGSMS_STATUS.CATEGORIES.DRAFT;
}

export function marketingsmsIsDelivered(status: MarketingSMSStatusType): boolean {
  const deliveredStatuses: MarketingSMSStatusType[] = [
    MARKETINGSMS_STATUS.STATUSES.DELIVERED,
    MARKETINGSMS_STATUS.STATUSES.CLICKED,
    MARKETINGSMS_STATUS.STATUSES.REPLIED,
  ];
  return deliveredStatuses.includes(status);
}

export function marketingsmsIsEngaged(status: MarketingSMSStatusType): boolean {
  const engagedStatuses: MarketingSMSStatusType[] = [
    MARKETINGSMS_STATUS.STATUSES.CLICKED,
    MARKETINGSMS_STATUS.STATUSES.REPLIED,
  ];
  return engagedStatuses.includes(status);
}

export function marketingsmsIsFailed(status: MarketingSMSStatusType): boolean {
  const failedStatuses: MarketingSMSStatusType[] = [
    MARKETINGSMS_STATUS.STATUSES.FAILED,
    MARKETINGSMS_STATUS.STATUSES.UNDELIVERED,
    MARKETINGSMS_STATUS.STATUSES.REJECTED_BY_PROVIDER,
    MARKETINGSMS_STATUS.STATUSES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}

export function marketingsmsIsPending(status: MarketingSMSStatusType): boolean {
  const pendingStatuses: MarketingSMSStatusType[] = [
    MARKETINGSMS_STATUS.STATUSES.PENDING_APPROVAL,
    MARKETINGSMS_STATUS.STATUSES.APPROVED,
    MARKETINGSMS_STATUS.STATUSES.SCHEDULED,
    MARKETINGSMS_STATUS.STATUSES.QUEUED,
    MARKETINGSMS_STATUS.STATUSES.PROCESSING,
    MARKETINGSMS_STATUS.STATUSES.SENT,
    MARKETINGSMS_STATUS.STATUSES.PENDING_DELIVERY,
    MARKETINGSMS_STATUS.STATUSES.DEFERRED,
  ];
  return pendingStatuses.includes(status);
}

export function marketingsmsIsTerminal(status: MarketingSMSStatusType): boolean {
  const terminalStatuses: MarketingSMSStatusType[] = [
    MARKETINGSMS_STATUS.STATUSES.DELIVERED,
    MARKETINGSMS_STATUS.STATUSES.CLICKED,
    MARKETINGSMS_STATUS.STATUSES.REPLIED,
    MARKETINGSMS_STATUS.STATUSES.OPT_OUT,
    MARKETINGSMS_STATUS.STATUSES.UNDELIVERED,
    MARKETINGSMS_STATUS.STATUSES.FAILED,
    MARKETINGSMS_STATUS.STATUSES.REJECTED_BY_PROVIDER,
    MARKETINGSMS_STATUS.STATUSES.EXPIRED,
    MARKETINGSMS_STATUS.STATUSES.ARCHIVED,
    MARKETINGSMS_STATUS.STATUSES.CANCELLED,
  ];
  return terminalStatuses.includes(status);
}

export function marketingsmsCanTransition(
  currentStatus: MarketingSMSStatusType,
  targetStatus: MarketingSMSStatusType
): boolean {
  const validTransitions: Record<MarketingSMSStatusType, MarketingSMSStatusType[]> = {
    [MARKETINGSMS_STATUS.STATUSES.DRAFT]: [
      MARKETINGSMS_STATUS.STATUSES.PENDING_APPROVAL,
      MARKETINGSMS_STATUS.STATUSES.CANCELLED,
      MARKETINGSMS_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGSMS_STATUS.STATUSES.PENDING_APPROVAL]: [
      MARKETINGSMS_STATUS.STATUSES.APPROVED,
      MARKETINGSMS_STATUS.STATUSES.REJECTED,
      MARKETINGSMS_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGSMS_STATUS.STATUSES.APPROVED]: [
      MARKETINGSMS_STATUS.STATUSES.SCHEDULED,
      MARKETINGSMS_STATUS.STATUSES.REJECTED,
      MARKETINGSMS_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGSMS_STATUS.STATUSES.REJECTED]: [
      MARKETINGSMS_STATUS.STATUSES.DRAFT,
      MARKETINGSMS_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGSMS_STATUS.STATUSES.SCHEDULED]: [
      MARKETINGSMS_STATUS.STATUSES.QUEUED,
      MARKETINGSMS_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGSMS_STATUS.STATUSES.QUEUED]: [
      MARKETINGSMS_STATUS.STATUSES.PROCESSING,
      MARKETINGSMS_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGSMS_STATUS.STATUSES.PROCESSING]: [
      MARKETINGSMS_STATUS.STATUSES.SENT,
      MARKETINGSMS_STATUS.STATUSES.FAILED,
      MARKETINGSMS_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGSMS_STATUS.STATUSES.SENT]: [
      MARKETINGSMS_STATUS.STATUSES.PENDING_DELIVERY,
      MARKETINGSMS_STATUS.STATUSES.FAILED,
      MARKETINGSMS_STATUS.STATUSES.DEFERRED,
    ],
    [MARKETINGSMS_STATUS.STATUSES.PENDING_DELIVERY]: [
      MARKETINGSMS_STATUS.STATUSES.DELIVERED,
      MARKETINGSMS_STATUS.STATUSES.UNDELIVERED,
      MARKETINGSMS_STATUS.STATUSES.FAILED,
      MARKETINGSMS_STATUS.STATUSES.EXPIRED,
    ],
    [MARKETINGSMS_STATUS.STATUSES.DELIVERED]: [
      MARKETINGSMS_STATUS.STATUSES.CLICKED,
      MARKETINGSMS_STATUS.STATUSES.REPLIED,
      MARKETINGSMS_STATUS.STATUSES.OPT_OUT,
      MARKETINGSMS_STATUS.STATUSES.FAILED,
    ],
    [MARKETINGSMS_STATUS.STATUSES.CLICKED]: [
      MARKETINGSMS_STATUS.STATUSES.REPLIED,
      MARKETINGSMS_STATUS.STATUSES.OPT_OUT,
    ],
    [MARKETINGSMS_STATUS.STATUSES.REPLIED]: [MARKETINGSMS_STATUS.STATUSES.OPT_OUT],
    [MARKETINGSMS_STATUS.STATUSES.UNDELIVERED]: [MARKETINGSMS_STATUS.STATUSES.ARCHIVED],
    [MARKETINGSMS_STATUS.STATUSES.FAILED]: [MARKETINGSMS_STATUS.STATUSES.ARCHIVED],
    [MARKETINGSMS_STATUS.STATUSES.REJECTED_BY_PROVIDER]: [MARKETINGSMS_STATUS.STATUSES.ARCHIVED],
    [MARKETINGSMS_STATUS.STATUSES.DEFERRED]: [
      MARKETINGSMS_STATUS.STATUSES.PROCESSING,
      MARKETINGSMS_STATUS.STATUSES.FAILED,
      MARKETINGSMS_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGSMS_STATUS.STATUSES.EXPIRED]: [MARKETINGSMS_STATUS.STATUSES.ARCHIVED],
    [MARKETINGSMS_STATUS.STATUSES.OPT_OUT]: [MARKETINGSMS_STATUS.STATUSES.ARCHIVED],
    [MARKETINGSMS_STATUS.STATUSES.PAUSED]: [
      MARKETINGSMS_STATUS.STATUSES.PROCESSING,
      MARKETINGSMS_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGSMS_STATUS.STATUSES.CANCELLED]: [MARKETINGSMS_STATUS.STATUSES.ARCHIVED],
    [MARKETINGSMS_STATUS.STATUSES.ARCHIVED]: [],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
