[build]
builder = "nixpacks"
buildCommand = "pnpm --filter @vubon/payment-service build"

[deploy]
startCommand = "node apps/payment-service/dist/main.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[env]
NODE_ENV = "production"
