/**
 * SEO কন্টেন্ট অপটিমাইজেশন স্ট্যাটাস এনাম
 */
export const SEO_CONTENT_OPTIMIZATION_STATUS = {
  PENDING: 'pending',
  ANALYZING: 'analyzing',
  SUGGESTED: 'suggested',
  IMPLEMENTED: 'implemented',
  APPLIED: 'applied',
  REJECTED: 'rejected',
  PARTIAL: 'partial',
} as const;

/**
 * SEO_CONTENT_OPTIMIZATION_STATUS থেকে টাইপ
 */
export type SEOContentOptimizationStatus =
  (typeof SEO_CONTENT_OPTIMIZATION_STATUS)[keyof typeof SEO_CONTENT_OPTIMIZATION_STATUS];

/**
 * SEO কন্টেন্ট অপটিমাইজেশন স্ট্যাটাস লেবেল
 */
export const SEO_CONTENT_OPTIMIZATION_STATUS_LABELS: Record<SEOContentOptimizationStatus, string> =
  {
    [SEO_CONTENT_OPTIMIZATION_STATUS.PENDING]: 'Pending',
    [SEO_CONTENT_OPTIMIZATION_STATUS.ANALYZING]: 'Analyzing',
    [SEO_CONTENT_OPTIMIZATION_STATUS.SUGGESTED]: 'Suggested',
    [SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED]: 'Implemented',
    [SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED]: 'Applied',
    [SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED]: 'Rejected',
    [SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL]: 'Partial',
  } as const;

/**
 * SEO কন্টেন্ট অপটিমাইজেশন স্ট্যাটাস বিবরণ
 */
export const SEO_CONTENT_OPTIMIZATION_STATUS_DESCRIPTIONS: Record<
  SEOContentOptimizationStatus,
  string
> = {
  [SEO_CONTENT_OPTIMIZATION_STATUS.PENDING]:
    'Optimization request is pending and waiting to be processed',
  [SEO_CONTENT_OPTIMIZATION_STATUS.ANALYZING]:
    'Content is currently being analyzed for optimization opportunities',
  [SEO_CONTENT_OPTIMIZATION_STATUS.SUGGESTED]:
    'Optimization suggestions have been generated and proposed',
  [SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED]:
    'Optimization has been implemented in the codebase',
  [SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED]:
    'Optimization has been applied and is live on the site',
  [SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED]: 'Optimization suggestion has been rejected',
  [SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL]: 'Optimization has been partially implemented',
} as const;

/**
 * SEO কন্টেন্ট অপটিমাইজেশন স্ট্যাটাস আইকন
 */
export const SEO_CONTENT_OPTIMIZATION_STATUS_ICONS: Record<SEOContentOptimizationStatus, string> = {
  [SEO_CONTENT_OPTIMIZATION_STATUS.PENDING]: '⏳',
  [SEO_CONTENT_OPTIMIZATION_STATUS.ANALYZING]: '🔬',
  [SEO_CONTENT_OPTIMIZATION_STATUS.SUGGESTED]: '💡',
  [SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED]: '🔧',
  [SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED]: '✅',
  [SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED]: '❌',
  [SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL]: '🔄',
} as const;

/**
 * SEO কন্টেন্ট অপটিমাইজেশন স্ট্যাটাস কালার (হেক্স কোড)
 */
export const SEO_CONTENT_OPTIMIZATION_STATUS_COLORS: Record<SEOContentOptimizationStatus, string> =
  {
    [SEO_CONTENT_OPTIMIZATION_STATUS.PENDING]: '#94a3b8', // Slate-400
    [SEO_CONTENT_OPTIMIZATION_STATUS.ANALYZING]: '#3b82f6', // Blue-500
    [SEO_CONTENT_OPTIMIZATION_STATUS.SUGGESTED]: '#f59e0b', // Amber-500
    [SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED]: '#8b5cf6', // Violet-500
    [SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED]: '#22c55e', // Green-500
    [SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED]: '#dc2626', // Red-600
    [SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL]: '#f97316', // Orange-500
  } as const;

/**
 * SEO কন্টেন্ট অপটিমাইজেশন স্ট্যাটাস ট্রানজিশন রুলস
 */
export const SEO_CONTENT_OPTIMIZATION_STATUS_TRANSITIONS: Record<
  SEOContentOptimizationStatus,
  SEOContentOptimizationStatus[]
> = {
  [SEO_CONTENT_OPTIMIZATION_STATUS.PENDING]: [
    SEO_CONTENT_OPTIMIZATION_STATUS.ANALYZING,
    SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED,
  ],
  [SEO_CONTENT_OPTIMIZATION_STATUS.ANALYZING]: [
    SEO_CONTENT_OPTIMIZATION_STATUS.SUGGESTED,
    SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED,
  ],
  [SEO_CONTENT_OPTIMIZATION_STATUS.SUGGESTED]: [
    SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED,
    SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED,
    SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL,
  ],
  [SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED]: [
    SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED,
    SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED,
    SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL,
  ],
  [SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED]: [
    SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED,
    SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL,
  ],
  [SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED]: [SEO_CONTENT_OPTIMIZATION_STATUS.PENDING],
  [SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL]: [
    SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED,
    SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED,
    SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED,
  ],
} as const;

/**
 * SEO কন্টেন্ট অপটিমাইজেশন স্ট্যাটাস কনফিগারেশন
 */
export interface SEOContentOptimizationStatusConfig {
  status: SEOContentOptimizationStatus;
  label: string;
  description: string;
  icon: string;
  color: string;
  isTerminal: boolean;
  isError: boolean;
  isSuccess: boolean;
  isActive: boolean;
  order: number;
}

/**
 * SEO কন্টেন্ট অপটিমাইজেশন স্ট্যাটাস মেটাডেটা
 */
export const SEO_CONTENT_OPTIMIZATION_STATUS_METADATA: Record<
  SEOContentOptimizationStatus,
  SEOContentOptimizationStatusConfig
> = {
  [SEO_CONTENT_OPTIMIZATION_STATUS.PENDING]: {
    status: SEO_CONTENT_OPTIMIZATION_STATUS.PENDING,
    label: SEO_CONTENT_OPTIMIZATION_STATUS_LABELS[SEO_CONTENT_OPTIMIZATION_STATUS.PENDING],
    description:
      SEO_CONTENT_OPTIMIZATION_STATUS_DESCRIPTIONS[SEO_CONTENT_OPTIMIZATION_STATUS.PENDING],
    icon: SEO_CONTENT_OPTIMIZATION_STATUS_ICONS[SEO_CONTENT_OPTIMIZATION_STATUS.PENDING],
    color: SEO_CONTENT_OPTIMIZATION_STATUS_COLORS[SEO_CONTENT_OPTIMIZATION_STATUS.PENDING],
    isTerminal: false,
    isError: false,
    isSuccess: false,
    isActive: true,
    order: 0,
  },
  [SEO_CONTENT_OPTIMIZATION_STATUS.ANALYZING]: {
    status: SEO_CONTENT_OPTIMIZATION_STATUS.ANALYZING,
    label: SEO_CONTENT_OPTIMIZATION_STATUS_LABELS[SEO_CONTENT_OPTIMIZATION_STATUS.ANALYZING],
    description:
      SEO_CONTENT_OPTIMIZATION_STATUS_DESCRIPTIONS[SEO_CONTENT_OPTIMIZATION_STATUS.ANALYZING],
    icon: SEO_CONTENT_OPTIMIZATION_STATUS_ICONS[SEO_CONTENT_OPTIMIZATION_STATUS.ANALYZING],
    color: SEO_CONTENT_OPTIMIZATION_STATUS_COLORS[SEO_CONTENT_OPTIMIZATION_STATUS.ANALYZING],
    isTerminal: false,
    isError: false,
    isSuccess: false,
    isActive: true,
    order: 1,
  },
  [SEO_CONTENT_OPTIMIZATION_STATUS.SUGGESTED]: {
    status: SEO_CONTENT_OPTIMIZATION_STATUS.SUGGESTED,
    label: SEO_CONTENT_OPTIMIZATION_STATUS_LABELS[SEO_CONTENT_OPTIMIZATION_STATUS.SUGGESTED],
    description:
      SEO_CONTENT_OPTIMIZATION_STATUS_DESCRIPTIONS[SEO_CONTENT_OPTIMIZATION_STATUS.SUGGESTED],
    icon: SEO_CONTENT_OPTIMIZATION_STATUS_ICONS[SEO_CONTENT_OPTIMIZATION_STATUS.SUGGESTED],
    color: SEO_CONTENT_OPTIMIZATION_STATUS_COLORS[SEO_CONTENT_OPTIMIZATION_STATUS.SUGGESTED],
    isTerminal: false,
    isError: false,
    isSuccess: false,
    isActive: true,
    order: 2,
  },
  [SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED]: {
    status: SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED,
    label: SEO_CONTENT_OPTIMIZATION_STATUS_LABELS[SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED],
    description:
      SEO_CONTENT_OPTIMIZATION_STATUS_DESCRIPTIONS[SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED],
    icon: SEO_CONTENT_OPTIMIZATION_STATUS_ICONS[SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED],
    color: SEO_CONTENT_OPTIMIZATION_STATUS_COLORS[SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED],
    isTerminal: false,
    isError: false,
    isSuccess: true,
    isActive: true,
    order: 3,
  },
  [SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED]: {
    status: SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED,
    label: SEO_CONTENT_OPTIMIZATION_STATUS_LABELS[SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED],
    description:
      SEO_CONTENT_OPTIMIZATION_STATUS_DESCRIPTIONS[SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED],
    icon: SEO_CONTENT_OPTIMIZATION_STATUS_ICONS[SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED],
    color: SEO_CONTENT_OPTIMIZATION_STATUS_COLORS[SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED],
    isTerminal: true,
    isError: false,
    isSuccess: true,
    isActive: false,
    order: 4,
  },
  [SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED]: {
    status: SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED,
    label: SEO_CONTENT_OPTIMIZATION_STATUS_LABELS[SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED],
    description:
      SEO_CONTENT_OPTIMIZATION_STATUS_DESCRIPTIONS[SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED],
    icon: SEO_CONTENT_OPTIMIZATION_STATUS_ICONS[SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED],
    color: SEO_CONTENT_OPTIMIZATION_STATUS_COLORS[SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED],
    isTerminal: true,
    isError: true,
    isSuccess: false,
    isActive: false,
    order: 5,
  },
  [SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL]: {
    status: SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL,
    label: SEO_CONTENT_OPTIMIZATION_STATUS_LABELS[SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL],
    description:
      SEO_CONTENT_OPTIMIZATION_STATUS_DESCRIPTIONS[SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL],
    icon: SEO_CONTENT_OPTIMIZATION_STATUS_ICONS[SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL],
    color: SEO_CONTENT_OPTIMIZATION_STATUS_COLORS[SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL],
    isTerminal: false,
    isError: false,
    isSuccess: false,
    isActive: true,
    order: 6,
  },
} as const;

/**
 * টার্মিনাল স্ট্যাটাসের তালিকা
 */
export const SEO_CONTENT_OPTIMIZATION_TERMINAL_STATUSES = [
  SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED,
  SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED,
] as const;

/**
 * সাফল্যের স্ট্যাটাসের তালিকা
 */
export const SEO_CONTENT_OPTIMIZATION_SUCCESS_STATUSES = [
  SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED,
  SEO_CONTENT_OPTIMIZATION_STATUS.APPLIED,
] as const;

/**
 * ত্রুটির স্ট্যাটাসের তালিকা
 */
export const SEO_CONTENT_OPTIMIZATION_ERROR_STATUSES = [
  SEO_CONTENT_OPTIMIZATION_STATUS.REJECTED,
] as const;

/**
 * অ্যাক্টিভ স্ট্যাটাসের তালিকা
 */
export const SEO_CONTENT_OPTIMIZATION_ACTIVE_STATUSES = [
  SEO_CONTENT_OPTIMIZATION_STATUS.PENDING,
  SEO_CONTENT_OPTIMIZATION_STATUS.ANALYZING,
  SEO_CONTENT_OPTIMIZATION_STATUS.SUGGESTED,
  SEO_CONTENT_OPTIMIZATION_STATUS.IMPLEMENTED,
  SEO_CONTENT_OPTIMIZATION_STATUS.PARTIAL,
] as const;
