/**
 * SEO কীওয়ার্ড ইনটেন্ট এনাম
 */
export const SEO_KEYWORD_INTENT = {
  INFORMATIONAL: 'informational',
  NAVIGATIONAL: 'navigational',
  COMMERCIAL: 'commercial',
  TRANSACTIONAL: 'transactional',
  LOCAL: 'local',
  BROWSING: 'browsing',
  RESEARCH: 'research',
} as const;

/**
 * SEO_KEYWORD_INTENT থেকে টাইপ
 */
export type SEOKeywordIntent = (typeof SEO_KEYWORD_INTENT)[keyof typeof SEO_KEYWORD_INTENT];

/**
 * SEO কীওয়ার্ড ইনটেন্ট লেবেল
 */
export const SEO_KEYWORD_INTENT_LABELS: Record<SEOKeywordIntent, string> = {
  [SEO_KEYWORD_INTENT.INFORMATIONAL]: 'Informational',
  [SEO_KEYWORD_INTENT.NAVIGATIONAL]: 'Navigational',
  [SEO_KEYWORD_INTENT.COMMERCIAL]: 'Commercial',
  [SEO_KEYWORD_INTENT.TRANSACTIONAL]: 'Transactional',
  [SEO_KEYWORD_INTENT.LOCAL]: 'Local',
  [SEO_KEYWORD_INTENT.BROWSING]: 'Browsing',
  [SEO_KEYWORD_INTENT.RESEARCH]: 'Research',
} as const;

/**
 * SEO কীওয়ার্ড ইনটেন্ট বিবরণ
 */
export const SEO_KEYWORD_INTENT_DESCRIPTIONS: Record<SEOKeywordIntent, string> = {
  [SEO_KEYWORD_INTENT.INFORMATIONAL]: 'User wants to learn or find information about a topic',
  [SEO_KEYWORD_INTENT.NAVIGATIONAL]: 'User wants to find a specific website or brand',
  [SEO_KEYWORD_INTENT.COMMERCIAL]: 'User is researching products/services before purchasing',
  [SEO_KEYWORD_INTENT.TRANSACTIONAL]: 'User wants to make a purchase or complete an action',
  [SEO_KEYWORD_INTENT.LOCAL]: 'User is looking for local businesses or services',
  [SEO_KEYWORD_INTENT.BROWSING]: 'User is casually exploring options without specific intent',
  [SEO_KEYWORD_INTENT.RESEARCH]: 'User is conducting in-depth research on a topic',
} as const;

/**
 * SEO কীওয়ার্ড ইনটেন্ট আইকন
 */
export const SEO_KEYWORD_INTENT_ICONS: Record<SEOKeywordIntent, string> = {
  [SEO_KEYWORD_INTENT.INFORMATIONAL]: '📚',
  [SEO_KEYWORD_INTENT.NAVIGATIONAL]: '🧭',
  [SEO_KEYWORD_INTENT.COMMERCIAL]: '🛍️',
  [SEO_KEYWORD_INTENT.TRANSACTIONAL]: '💳',
  [SEO_KEYWORD_INTENT.LOCAL]: '📍',
  [SEO_KEYWORD_INTENT.BROWSING]: '👀',
  [SEO_KEYWORD_INTENT.RESEARCH]: '🔬',
} as const;

/**
 * SEO কীওয়ার্ড ইনটেন্ট কালার (হেক্স কোড)
 */
export const SEO_KEYWORD_INTENT_COLORS: Record<SEOKeywordIntent, string> = {
  [SEO_KEYWORD_INTENT.INFORMATIONAL]: '#3b82f6', // Blue-500
  [SEO_KEYWORD_INTENT.NAVIGATIONAL]: '#8b5cf6', // Violet-500
  [SEO_KEYWORD_INTENT.COMMERCIAL]: '#f59e0b', // Amber-500
  [SEO_KEYWORD_INTENT.TRANSACTIONAL]: '#22c55e', // Green-500
  [SEO_KEYWORD_INTENT.LOCAL]: '#ec4899', // Pink-500
  [SEO_KEYWORD_INTENT.BROWSING]: '#94a3b8', // Slate-400
  [SEO_KEYWORD_INTENT.RESEARCH]: '#06b6d4', // Cyan-500
} as const;

/**
 * SEO কীওয়ার্ড ইনটেন্ট কনভার্সন সম্ভাবনা (০-১০০)
 */
export const SEO_KEYWORD_INTENT_CONVERSION: Record<SEOKeywordIntent, number> = {
  [SEO_KEYWORD_INTENT.INFORMATIONAL]: 20,
  [SEO_KEYWORD_INTENT.NAVIGATIONAL]: 40,
  [SEO_KEYWORD_INTENT.COMMERCIAL]: 60,
  [SEO_KEYWORD_INTENT.TRANSACTIONAL]: 90,
  [SEO_KEYWORD_INTENT.LOCAL]: 70,
  [SEO_KEYWORD_INTENT.BROWSING]: 30,
  [SEO_KEYWORD_INTENT.RESEARCH]: 50,
} as const;

/**
 * SEO কীওয়ার্ড ইনটেন্ট বুয়িং স্টেজ
 */
export const SEO_KEYWORD_INTENT_BUYING_STAGE: Record<SEOKeywordIntent, string> = {
  [SEO_KEYWORD_INTENT.INFORMATIONAL]: 'Awareness',
  [SEO_KEYWORD_INTENT.NAVIGATIONAL]: 'Consideration',
  [SEO_KEYWORD_INTENT.COMMERCIAL]: 'Consideration',
  [SEO_KEYWORD_INTENT.TRANSACTIONAL]: 'Decision',
  [SEO_KEYWORD_INTENT.LOCAL]: 'Decision',
  [SEO_KEYWORD_INTENT.BROWSING]: 'Awareness',
  [SEO_KEYWORD_INTENT.RESEARCH]: 'Consideration',
} as const;

/**
 * SEO কীওয়ার্ড ইনটেন্ট কনফিগারেশন
 */
export interface SEOKeywordIntentConfig {
  intent: SEOKeywordIntent;
  label: string;
  description: string;
  icon: string;
  color: string;
  conversion: number;
  buyingStage: string;
  order: number;
}

/**
 * SEO কীওয়ার্ড ইনটেন্ট মেটাডেটা
 */
export const SEO_KEYWORD_INTENT_METADATA: Record<SEOKeywordIntent, SEOKeywordIntentConfig> = {
  [SEO_KEYWORD_INTENT.INFORMATIONAL]: {
    intent: SEO_KEYWORD_INTENT.INFORMATIONAL,
    label: SEO_KEYWORD_INTENT_LABELS[SEO_KEYWORD_INTENT.INFORMATIONAL],
    description: SEO_KEYWORD_INTENT_DESCRIPTIONS[SEO_KEYWORD_INTENT.INFORMATIONAL],
    icon: SEO_KEYWORD_INTENT_ICONS[SEO_KEYWORD_INTENT.INFORMATIONAL],
    color: SEO_KEYWORD_INTENT_COLORS[SEO_KEYWORD_INTENT.INFORMATIONAL],
    conversion: SEO_KEYWORD_INTENT_CONVERSION[SEO_KEYWORD_INTENT.INFORMATIONAL],
    buyingStage: SEO_KEYWORD_INTENT_BUYING_STAGE[SEO_KEYWORD_INTENT.INFORMATIONAL],
    order: 0,
  },
  [SEO_KEYWORD_INTENT.NAVIGATIONAL]: {
    intent: SEO_KEYWORD_INTENT.NAVIGATIONAL,
    label: SEO_KEYWORD_INTENT_LABELS[SEO_KEYWORD_INTENT.NAVIGATIONAL],
    description: SEO_KEYWORD_INTENT_DESCRIPTIONS[SEO_KEYWORD_INTENT.NAVIGATIONAL],
    icon: SEO_KEYWORD_INTENT_ICONS[SEO_KEYWORD_INTENT.NAVIGATIONAL],
    color: SEO_KEYWORD_INTENT_COLORS[SEO_KEYWORD_INTENT.NAVIGATIONAL],
    conversion: SEO_KEYWORD_INTENT_CONVERSION[SEO_KEYWORD_INTENT.NAVIGATIONAL],
    buyingStage: SEO_KEYWORD_INTENT_BUYING_STAGE[SEO_KEYWORD_INTENT.NAVIGATIONAL],
    order: 1,
  },
  [SEO_KEYWORD_INTENT.COMMERCIAL]: {
    intent: SEO_KEYWORD_INTENT.COMMERCIAL,
    label: SEO_KEYWORD_INTENT_LABELS[SEO_KEYWORD_INTENT.COMMERCIAL],
    description: SEO_KEYWORD_INTENT_DESCRIPTIONS[SEO_KEYWORD_INTENT.COMMERCIAL],
    icon: SEO_KEYWORD_INTENT_ICONS[SEO_KEYWORD_INTENT.COMMERCIAL],
    color: SEO_KEYWORD_INTENT_COLORS[SEO_KEYWORD_INTENT.COMMERCIAL],
    conversion: SEO_KEYWORD_INTENT_CONVERSION[SEO_KEYWORD_INTENT.COMMERCIAL],
    buyingStage: SEO_KEYWORD_INTENT_BUYING_STAGE[SEO_KEYWORD_INTENT.COMMERCIAL],
    order: 2,
  },
  [SEO_KEYWORD_INTENT.TRANSACTIONAL]: {
    intent: SEO_KEYWORD_INTENT.TRANSACTIONAL,
    label: SEO_KEYWORD_INTENT_LABELS[SEO_KEYWORD_INTENT.TRANSACTIONAL],
    description: SEO_KEYWORD_INTENT_DESCRIPTIONS[SEO_KEYWORD_INTENT.TRANSACTIONAL],
    icon: SEO_KEYWORD_INTENT_ICONS[SEO_KEYWORD_INTENT.TRANSACTIONAL],
    color: SEO_KEYWORD_INTENT_COLORS[SEO_KEYWORD_INTENT.TRANSACTIONAL],
    conversion: SEO_KEYWORD_INTENT_CONVERSION[SEO_KEYWORD_INTENT.TRANSACTIONAL],
    buyingStage: SEO_KEYWORD_INTENT_BUYING_STAGE[SEO_KEYWORD_INTENT.TRANSACTIONAL],
    order: 3,
  },
  [SEO_KEYWORD_INTENT.LOCAL]: {
    intent: SEO_KEYWORD_INTENT.LOCAL,
    label: SEO_KEYWORD_INTENT_LABELS[SEO_KEYWORD_INTENT.LOCAL],
    description: SEO_KEYWORD_INTENT_DESCRIPTIONS[SEO_KEYWORD_INTENT.LOCAL],
    icon: SEO_KEYWORD_INTENT_ICONS[SEO_KEYWORD_INTENT.LOCAL],
    color: SEO_KEYWORD_INTENT_COLORS[SEO_KEYWORD_INTENT.LOCAL],
    conversion: SEO_KEYWORD_INTENT_CONVERSION[SEO_KEYWORD_INTENT.LOCAL],
    buyingStage: SEO_KEYWORD_INTENT_BUYING_STAGE[SEO_KEYWORD_INTENT.LOCAL],
    order: 4,
  },
  [SEO_KEYWORD_INTENT.BROWSING]: {
    intent: SEO_KEYWORD_INTENT.BROWSING,
    label: SEO_KEYWORD_INTENT_LABELS[SEO_KEYWORD_INTENT.BROWSING],
    description: SEO_KEYWORD_INTENT_DESCRIPTIONS[SEO_KEYWORD_INTENT.BROWSING],
    icon: SEO_KEYWORD_INTENT_ICONS[SEO_KEYWORD_INTENT.BROWSING],
    color: SEO_KEYWORD_INTENT_COLORS[SEO_KEYWORD_INTENT.BROWSING],
    conversion: SEO_KEYWORD_INTENT_CONVERSION[SEO_KEYWORD_INTENT.BROWSING],
    buyingStage: SEO_KEYWORD_INTENT_BUYING_STAGE[SEO_KEYWORD_INTENT.BROWSING],
    order: 5,
  },
  [SEO_KEYWORD_INTENT.RESEARCH]: {
    intent: SEO_KEYWORD_INTENT.RESEARCH,
    label: SEO_KEYWORD_INTENT_LABELS[SEO_KEYWORD_INTENT.RESEARCH],
    description: SEO_KEYWORD_INTENT_DESCRIPTIONS[SEO_KEYWORD_INTENT.RESEARCH],
    icon: SEO_KEYWORD_INTENT_ICONS[SEO_KEYWORD_INTENT.RESEARCH],
    color: SEO_KEYWORD_INTENT_COLORS[SEO_KEYWORD_INTENT.RESEARCH],
    conversion: SEO_KEYWORD_INTENT_CONVERSION[SEO_KEYWORD_INTENT.RESEARCH],
    buyingStage: SEO_KEYWORD_INTENT_BUYING_STAGE[SEO_KEYWORD_INTENT.RESEARCH],
    order: 6,
  },
} as const;

/**
 * SEO কীওয়ার্ড ইনটেন্ট গ্রুপ (বুয়িং স্টেজ ভিত্তিক)
 */
export const SEO_KEYWORD_INTENT_GROUPS = {
  AWARENESS: [SEO_KEYWORD_INTENT.INFORMATIONAL, SEO_KEYWORD_INTENT.BROWSING] as const,
  CONSIDERATION: [
    SEO_KEYWORD_INTENT.NAVIGATIONAL,
    SEO_KEYWORD_INTENT.COMMERCIAL,
    SEO_KEYWORD_INTENT.RESEARCH,
  ] as const,
  DECISION: [SEO_KEYWORD_INTENT.TRANSACTIONAL, SEO_KEYWORD_INTENT.LOCAL] as const,
} as const;

/**
 * SEO কীওয়ার্ড ইনটেন্ট গ্রুপ লেবেল
 */
export const SEO_KEYWORD_INTENT_GROUP_LABELS = {
  AWARENESS: 'Awareness Stage',
  CONSIDERATION: 'Consideration Stage',
  DECISION: 'Decision Stage',
} as const;

/**
 * SEO কীওয়ার্ড ইনটেন্ট গ্রুপ কালার
 */
export const SEO_KEYWORD_INTENT_GROUP_COLORS = {
  AWARENESS: '#3b82f6',
  CONSIDERATION: '#f59e0b',
  DECISION: '#22c55e',
} as const;
