/**
 * Campaign Status Constants
 * Status definitions for campaign lifecycle
 */

export const MARKETINGCAMPAIGN_STATUS = {
  // Campaign Statuses
  STATUSES: {
    DRAFT: 'draft',
    PENDING_APPROVAL: 'pending_approval',
    UNDER_REVIEW: 'under_review',
    APPROVED: 'approved',
    REJECTED: 'rejected',
    SCHEDULED: 'scheduled',
    READY: 'ready',
    ACTIVE: 'active',
    PAUSED: 'paused',
    COMPLETED: 'completed',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    FAILED: 'failed',
    ON_HOLD: 'on_hold',
    IN_PROGRESS: 'in_progress',
  } as const,

  // Status Categories
  CATEGORIES: {
    DRAFT: 'draft',
    PENDING: 'pending',
    ACTIVE: 'active',
    PAUSED: 'paused',
    COMPLETED: 'completed',
    CANCELLED: 'cancelled',
    FAILED: 'failed',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    DRAFT: '#6B7280',
    PENDING_APPROVAL: '#F59E0B',
    UNDER_REVIEW: '#8B5CF6',
    APPROVED: '#10B981',
    REJECTED: '#EF4444',
    SCHEDULED: '#3B82F6',
    READY: '#10B981',
    ACTIVE: '#10B981',
    PAUSED: '#F59E0B',
    COMPLETED: '#10B981',
    CANCELLED: '#6B7280',
    ARCHIVED: '#6B7280',
    FAILED: '#EF4444',
    ON_HOLD: '#F59E0B',
    IN_PROGRESS: '#3B82F6',
  } as const,

  // Status Transitions
  TRANSITIONS: {
    DRAFT_TO_PENDING: 'draft_to_pending',
    PENDING_TO_UNDER_REVIEW: 'pending_to_under_review',
    UNDER_REVIEW_TO_APPROVED: 'under_review_to_approved',
    UNDER_REVIEW_TO_REJECTED: 'under_review_to_rejected',
    APPROVED_TO_SCHEDULED: 'approved_to_scheduled',
    SCHEDULED_TO_READY: 'scheduled_to_ready',
    READY_TO_ACTIVE: 'ready_to_active',
    ACTIVE_TO_PAUSED: 'active_to_paused',
    PAUSED_TO_ACTIVE: 'paused_to_active',
    ACTIVE_TO_COMPLETED: 'active_to_completed',
    ACTIVE_TO_CANCELLED: 'active_to_cancelled',
    PAUSED_TO_CANCELLED: 'paused_to_cancelled',
    ACTIVE_TO_FAILED: 'active_to_failed',
  } as const,

  // Status Priority
  PRIORITY: {
    DRAFT: 0,
    PENDING_APPROVAL: 1,
    UNDER_REVIEW: 2,
    APPROVED: 3,
    REJECTED: 4,
    SCHEDULED: 5,
    READY: 6,
    ACTIVE: 7,
    PAUSED: 8,
    COMPLETED: 9,
    CANCELLED: 10,
    ARCHIVED: 11,
    FAILED: 12,
    ON_HOLD: 13,
    IN_PROGRESS: 14,
  } as const,
} as const;

// Campaign Statuses
export type MarketingCampaignStatusType =
  (typeof MARKETINGCAMPAIGN_STATUS.STATUSES)[keyof typeof MARKETINGCAMPAIGN_STATUS.STATUSES];

// Status Categories
export type MarketingCampaignStatusCategory =
  (typeof MARKETINGCAMPAIGN_STATUS.CATEGORIES)[keyof typeof MARKETINGCAMPAIGN_STATUS.CATEGORIES];

// Status Colors
export type MarketingCampaignStatusColor =
  (typeof MARKETINGCAMPAIGN_STATUS.COLORS)[keyof typeof MARKETINGCAMPAIGN_STATUS.COLORS];

// Status Transitions
export type MarketingCampaignStatusTransition =
  (typeof MARKETINGCAMPAIGN_STATUS.TRANSITIONS)[keyof typeof MARKETINGCAMPAIGN_STATUS.TRANSITIONS];

// Status Priority
export type MarketingCampaignStatusPriority =
  (typeof MARKETINGCAMPAIGN_STATUS.PRIORITY)[keyof typeof MARKETINGCAMPAIGN_STATUS.PRIORITY];

// Utility Functions
export function marketingcampaignGetStatusLabel(status: MarketingCampaignStatusType): string {
  const labels: Record<MarketingCampaignStatusType, string> = {
    [MARKETINGCAMPAIGN_STATUS.STATUSES.DRAFT]: 'Draft',
    [MARKETINGCAMPAIGN_STATUS.STATUSES.PENDING_APPROVAL]: 'Pending Approval',
    [MARKETINGCAMPAIGN_STATUS.STATUSES.UNDER_REVIEW]: 'Under Review',
    [MARKETINGCAMPAIGN_STATUS.STATUSES.APPROVED]: 'Approved',
    [MARKETINGCAMPAIGN_STATUS.STATUSES.REJECTED]: 'Rejected',
    [MARKETINGCAMPAIGN_STATUS.STATUSES.SCHEDULED]: 'Scheduled',
    [MARKETINGCAMPAIGN_STATUS.STATUSES.READY]: 'Ready',
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ACTIVE]: 'Active',
    [MARKETINGCAMPAIGN_STATUS.STATUSES.PAUSED]: 'Paused',
    [MARKETINGCAMPAIGN_STATUS.STATUSES.COMPLETED]: 'Completed',
    [MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED]: 'Cancelled',
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ARCHIVED]: 'Archived',
    [MARKETINGCAMPAIGN_STATUS.STATUSES.FAILED]: 'Failed',
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ON_HOLD]: 'On Hold',
    [MARKETINGCAMPAIGN_STATUS.STATUSES.IN_PROGRESS]: 'In Progress',
  };
  return labels[status] || 'Unknown Status';
}

export function marketingcampaignGetStatusCategory(
  status: MarketingCampaignStatusType
): MarketingCampaignStatusCategory {
  const categories: Record<MarketingCampaignStatusType, MarketingCampaignStatusCategory> = {
    [MARKETINGCAMPAIGN_STATUS.STATUSES.DRAFT]: MARKETINGCAMPAIGN_STATUS.CATEGORIES.DRAFT,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.PENDING_APPROVAL]:
      MARKETINGCAMPAIGN_STATUS.CATEGORIES.PENDING,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.UNDER_REVIEW]: MARKETINGCAMPAIGN_STATUS.CATEGORIES.PENDING,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.APPROVED]: MARKETINGCAMPAIGN_STATUS.CATEGORIES.PENDING,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.REJECTED]: MARKETINGCAMPAIGN_STATUS.CATEGORIES.CANCELLED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.SCHEDULED]: MARKETINGCAMPAIGN_STATUS.CATEGORIES.PENDING,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.READY]: MARKETINGCAMPAIGN_STATUS.CATEGORIES.PENDING,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ACTIVE]: MARKETINGCAMPAIGN_STATUS.CATEGORIES.ACTIVE,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.PAUSED]: MARKETINGCAMPAIGN_STATUS.CATEGORIES.PAUSED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.COMPLETED]: MARKETINGCAMPAIGN_STATUS.CATEGORIES.COMPLETED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED]: MARKETINGCAMPAIGN_STATUS.CATEGORIES.CANCELLED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ARCHIVED]: MARKETINGCAMPAIGN_STATUS.CATEGORIES.COMPLETED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.FAILED]: MARKETINGCAMPAIGN_STATUS.CATEGORIES.FAILED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ON_HOLD]: MARKETINGCAMPAIGN_STATUS.CATEGORIES.PAUSED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.IN_PROGRESS]: MARKETINGCAMPAIGN_STATUS.CATEGORIES.ACTIVE,
  };
  return categories[status] || MARKETINGCAMPAIGN_STATUS.CATEGORIES.DRAFT;
}

export function marketingcampaignGetStatusColor(
  status: MarketingCampaignStatusType
): MarketingCampaignStatusColor {
  const colors: Record<MarketingCampaignStatusType, MarketingCampaignStatusColor> = {
    [MARKETINGCAMPAIGN_STATUS.STATUSES.DRAFT]: MARKETINGCAMPAIGN_STATUS.COLORS.DRAFT,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.PENDING_APPROVAL]:
      MARKETINGCAMPAIGN_STATUS.COLORS.PENDING_APPROVAL,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.UNDER_REVIEW]: MARKETINGCAMPAIGN_STATUS.COLORS.UNDER_REVIEW,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.APPROVED]: MARKETINGCAMPAIGN_STATUS.COLORS.APPROVED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.REJECTED]: MARKETINGCAMPAIGN_STATUS.COLORS.REJECTED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.SCHEDULED]: MARKETINGCAMPAIGN_STATUS.COLORS.SCHEDULED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.READY]: MARKETINGCAMPAIGN_STATUS.COLORS.READY,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ACTIVE]: MARKETINGCAMPAIGN_STATUS.COLORS.ACTIVE,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.PAUSED]: MARKETINGCAMPAIGN_STATUS.COLORS.PAUSED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.COMPLETED]: MARKETINGCAMPAIGN_STATUS.COLORS.COMPLETED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED]: MARKETINGCAMPAIGN_STATUS.COLORS.CANCELLED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ARCHIVED]: MARKETINGCAMPAIGN_STATUS.COLORS.ARCHIVED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.FAILED]: MARKETINGCAMPAIGN_STATUS.COLORS.FAILED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ON_HOLD]: MARKETINGCAMPAIGN_STATUS.COLORS.ON_HOLD,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.IN_PROGRESS]: MARKETINGCAMPAIGN_STATUS.COLORS.IN_PROGRESS,
  };
  return colors[status] || MARKETINGCAMPAIGN_STATUS.COLORS.DRAFT;
}

export function marketingcampaignGetStatusPriority(
  status: MarketingCampaignStatusType
): MarketingCampaignStatusPriority {
  const priorities: Record<MarketingCampaignStatusType, MarketingCampaignStatusPriority> = {
    [MARKETINGCAMPAIGN_STATUS.STATUSES.DRAFT]: MARKETINGCAMPAIGN_STATUS.PRIORITY.DRAFT,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.PENDING_APPROVAL]:
      MARKETINGCAMPAIGN_STATUS.PRIORITY.PENDING_APPROVAL,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.UNDER_REVIEW]:
      MARKETINGCAMPAIGN_STATUS.PRIORITY.UNDER_REVIEW,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.APPROVED]: MARKETINGCAMPAIGN_STATUS.PRIORITY.APPROVED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.REJECTED]: MARKETINGCAMPAIGN_STATUS.PRIORITY.REJECTED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.SCHEDULED]: MARKETINGCAMPAIGN_STATUS.PRIORITY.SCHEDULED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.READY]: MARKETINGCAMPAIGN_STATUS.PRIORITY.READY,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ACTIVE]: MARKETINGCAMPAIGN_STATUS.PRIORITY.ACTIVE,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.PAUSED]: MARKETINGCAMPAIGN_STATUS.PRIORITY.PAUSED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.COMPLETED]: MARKETINGCAMPAIGN_STATUS.PRIORITY.COMPLETED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED]: MARKETINGCAMPAIGN_STATUS.PRIORITY.CANCELLED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ARCHIVED]: MARKETINGCAMPAIGN_STATUS.PRIORITY.ARCHIVED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.FAILED]: MARKETINGCAMPAIGN_STATUS.PRIORITY.FAILED,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ON_HOLD]: MARKETINGCAMPAIGN_STATUS.PRIORITY.ON_HOLD,
    [MARKETINGCAMPAIGN_STATUS.STATUSES.IN_PROGRESS]: MARKETINGCAMPAIGN_STATUS.PRIORITY.IN_PROGRESS,
  };
  return priorities[status] || MARKETINGCAMPAIGN_STATUS.PRIORITY.DRAFT;
}

export function marketingcampaignIsActiveStatus(status: MarketingCampaignStatusType): boolean {
  const activeStatuses: MarketingCampaignStatusType[] = [
    MARKETINGCAMPAIGN_STATUS.STATUSES.ACTIVE,
    MARKETINGCAMPAIGN_STATUS.STATUSES.IN_PROGRESS,
  ];
  return activeStatuses.includes(status);
}

export function marketingcampaignIsPausedStatus(status: MarketingCampaignStatusType): boolean {
  const pausedStatuses: MarketingCampaignStatusType[] = [
    MARKETINGCAMPAIGN_STATUS.STATUSES.PAUSED,
    MARKETINGCAMPAIGN_STATUS.STATUSES.ON_HOLD,
  ];
  return pausedStatuses.includes(status);
}

export function marketingcampaignIsCompletedStatus(status: MarketingCampaignStatusType): boolean {
  const completedStatuses: MarketingCampaignStatusType[] = [
    MARKETINGCAMPAIGN_STATUS.STATUSES.COMPLETED,
    MARKETINGCAMPAIGN_STATUS.STATUSES.ARCHIVED,
    MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED,
    MARKETINGCAMPAIGN_STATUS.STATUSES.REJECTED,
    MARKETINGCAMPAIGN_STATUS.STATUSES.FAILED,
  ];
  return completedStatuses.includes(status);
}

export function marketingcampaignIsEditableStatus(status: MarketingCampaignStatusType): boolean {
  const editableStatuses: MarketingCampaignStatusType[] = [
    MARKETINGCAMPAIGN_STATUS.STATUSES.DRAFT,
    MARKETINGCAMPAIGN_STATUS.STATUSES.PENDING_APPROVAL,
    MARKETINGCAMPAIGN_STATUS.STATUSES.REJECTED,
    MARKETINGCAMPAIGN_STATUS.STATUSES.SCHEDULED,
    MARKETINGCAMPAIGN_STATUS.STATUSES.READY,
    MARKETINGCAMPAIGN_STATUS.STATUSES.PAUSED,
    MARKETINGCAMPAIGN_STATUS.STATUSES.ON_HOLD,
  ];
  return editableStatuses.includes(status);
}

export function marketingcampaignCanTransition(
  currentStatus: MarketingCampaignStatusType,
  targetStatus: MarketingCampaignStatusType
): boolean {
  const validTransitions: Record<MarketingCampaignStatusType, MarketingCampaignStatusType[]> = {
    [MARKETINGCAMPAIGN_STATUS.STATUSES.DRAFT]: [
      MARKETINGCAMPAIGN_STATUS.STATUSES.PENDING_APPROVAL,
      MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGCAMPAIGN_STATUS.STATUSES.PENDING_APPROVAL]: [
      MARKETINGCAMPAIGN_STATUS.STATUSES.UNDER_REVIEW,
      MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.DRAFT,
    ],
    [MARKETINGCAMPAIGN_STATUS.STATUSES.UNDER_REVIEW]: [
      MARKETINGCAMPAIGN_STATUS.STATUSES.APPROVED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.REJECTED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.DRAFT,
    ],
    [MARKETINGCAMPAIGN_STATUS.STATUSES.APPROVED]: [
      MARKETINGCAMPAIGN_STATUS.STATUSES.SCHEDULED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGCAMPAIGN_STATUS.STATUSES.REJECTED]: [
      MARKETINGCAMPAIGN_STATUS.STATUSES.DRAFT,
      MARKETINGCAMPAIGN_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGCAMPAIGN_STATUS.STATUSES.SCHEDULED]: [
      MARKETINGCAMPAIGN_STATUS.STATUSES.READY,
      MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.DRAFT,
    ],
    [MARKETINGCAMPAIGN_STATUS.STATUSES.READY]: [
      MARKETINGCAMPAIGN_STATUS.STATUSES.ACTIVE,
      MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.DRAFT,
    ],
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ACTIVE]: [
      MARKETINGCAMPAIGN_STATUS.STATUSES.PAUSED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.COMPLETED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.FAILED,
    ],
    [MARKETINGCAMPAIGN_STATUS.STATUSES.PAUSED]: [
      MARKETINGCAMPAIGN_STATUS.STATUSES.ACTIVE,
      MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.COMPLETED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.ON_HOLD,
    ],
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ON_HOLD]: [
      MARKETINGCAMPAIGN_STATUS.STATUSES.ACTIVE,
      MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.PAUSED,
    ],
    [MARKETINGCAMPAIGN_STATUS.STATUSES.IN_PROGRESS]: [
      MARKETINGCAMPAIGN_STATUS.STATUSES.COMPLETED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.PAUSED,
      MARKETINGCAMPAIGN_STATUS.STATUSES.FAILED,
    ],
    [MARKETINGCAMPAIGN_STATUS.STATUSES.COMPLETED]: [MARKETINGCAMPAIGN_STATUS.STATUSES.ARCHIVED],
    [MARKETINGCAMPAIGN_STATUS.STATUSES.CANCELLED]: [MARKETINGCAMPAIGN_STATUS.STATUSES.ARCHIVED],
    [MARKETINGCAMPAIGN_STATUS.STATUSES.FAILED]: [
      MARKETINGCAMPAIGN_STATUS.STATUSES.DRAFT,
      MARKETINGCAMPAIGN_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGCAMPAIGN_STATUS.STATUSES.ARCHIVED]: [],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
