/**
 * Campaign Channel Constants
 * Channel definitions for marketing campaigns
 */

export const MARKETINGCAMPAIGN_CHANNEL = {
  // Channels
  CHANNELS: {
    EMAIL: 'email',
    SMS: 'sms',
    PUSH_NOTIFICATION: 'push_notification',
    IN_APP: 'in_app',
    SOCIAL_MEDIA: 'social_media',
    SEARCH_ENGINE: 'search_engine',
    DISPLAY_ADS: 'display_ads',
    VIDEO_ADS: 'video_ads',
    AFFILIATE: 'affiliate',
    REFERRAL: 'referral',
    INFLUENCER: 'influencer',
    CONTENT: 'content',
    BLOG: 'blog',
    PODCAST: 'podcast',
    WEBINAR: 'webinar',
    EVENT: 'event',
    DIRECT_MAIL: 'direct_mail',
    PR: 'pr',
    OUTDOOR: 'outdoor',
    RADIO: 'radio',
    TV: 'tv',
    PRINT: 'print',
    D2C: 'd2c',
    MARKETPLACE: 'marketplace',
    OTHER: 'other',
  } as const,

  // Channel Categories
  CATEGORIES: {
    DIGITAL: 'digital',
    TRADITIONAL: 'traditional',
    SOCIAL: 'social',
    DIRECT: 'direct',
    PAID: 'paid',
    OWNED: 'owned',
    EARNED: 'earned',
    OFFLINE: 'offline',
    ONLINE: 'online',
    OTHER: 'other',
  } as const,

  // Channel Costs (relative: 1-10)
  COSTS: {
    EMAIL: 1,
    SMS: 2,
    PUSH_NOTIFICATION: 1,
    IN_APP: 2,
    SOCIAL_MEDIA: 5,
    SEARCH_ENGINE: 7,
    DISPLAY_ADS: 6,
    VIDEO_ADS: 8,
    AFFILIATE: 4,
    REFERRAL: 3,
    INFLUENCER: 8,
    CONTENT: 4,
    BLOG: 3,
    PODCAST: 6,
    WEBINAR: 5,
    EVENT: 9,
    DIRECT_MAIL: 6,
    PR: 7,
    OUTDOOR: 8,
    RADIO: 7,
    TV: 10,
    PRINT: 7,
    D2C: 3,
    MARKETPLACE: 5,
    OTHER: 5,
  } as const,

  // Channel Effectiveness (relative: 1-10)
  EFFECTIVENESS: {
    EMAIL: 7,
    SMS: 6,
    PUSH_NOTIFICATION: 5,
    IN_APP: 6,
    SOCIAL_MEDIA: 7,
    SEARCH_ENGINE: 9,
    DISPLAY_ADS: 6,
    VIDEO_ADS: 8,
    AFFILIATE: 7,
    REFERRAL: 8,
    INFLUENCER: 7,
    CONTENT: 7,
    BLOG: 6,
    PODCAST: 5,
    WEBINAR: 6,
    EVENT: 7,
    DIRECT_MAIL: 4,
    PR: 6,
    OUTDOOR: 4,
    RADIO: 4,
    TV: 6,
    PRINT: 5,
    D2C: 8,
    MARKETPLACE: 7,
    OTHER: 5,
  } as const,

  // Channel Reach (relative: 1-10)
  REACH: {
    EMAIL: 7,
    SMS: 6,
    PUSH_NOTIFICATION: 5,
    IN_APP: 5,
    SOCIAL_MEDIA: 9,
    SEARCH_ENGINE: 9,
    DISPLAY_ADS: 8,
    VIDEO_ADS: 8,
    AFFILIATE: 6,
    REFERRAL: 6,
    INFLUENCER: 7,
    CONTENT: 7,
    BLOG: 6,
    PODCAST: 5,
    WEBINAR: 5,
    EVENT: 4,
    DIRECT_MAIL: 3,
    PR: 6,
    OUTDOOR: 7,
    RADIO: 8,
    TV: 10,
    PRINT: 7,
    D2C: 6,
    MARKETPLACE: 8,
    OTHER: 5,
  } as const,

  // Channel Defaults
  DEFAULTS: {
    DEFAULT_CHANNELS: ['email', 'social_media', 'search_engine'],
    MIN_CHANNELS_PER_CAMPAIGN: 1,
    MAX_CHANNELS_PER_CAMPAIGN: 10,
    DEFAULT_BUDGET_ALLOCATION: 0.3,
  } as const,
} as const;

// Channels
export type MarketingCampaignChannel =
  (typeof MARKETINGCAMPAIGN_CHANNEL.CHANNELS)[keyof typeof MARKETINGCAMPAIGN_CHANNEL.CHANNELS];

// Channel Categories
export type MarketingCampaignChannelCategory =
  (typeof MARKETINGCAMPAIGN_CHANNEL.CATEGORIES)[keyof typeof MARKETINGCAMPAIGN_CHANNEL.CATEGORIES];

// Channel Costs
export type MarketingCampaignChannelCost =
  (typeof MARKETINGCAMPAIGN_CHANNEL.COSTS)[keyof typeof MARKETINGCAMPAIGN_CHANNEL.COSTS];

// Channel Effectiveness
export type MarketingCampaignChannelEffectiveness =
  (typeof MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS)[keyof typeof MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS];

// Channel Reach
export type MarketingCampaignChannelReach =
  (typeof MARKETINGCAMPAIGN_CHANNEL.REACH)[keyof typeof MARKETINGCAMPAIGN_CHANNEL.REACH];

// Utility Functions
export function marketingcampaignGetChannelLabel(channel: MarketingCampaignChannel): string {
  const labels: Record<MarketingCampaignChannel, string> = {
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.EMAIL]: 'Email',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SMS]: 'SMS',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PUSH_NOTIFICATION]: 'Push Notification',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.IN_APP]: 'In-App',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SOCIAL_MEDIA]: 'Social Media',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SEARCH_ENGINE]: 'Search Engine',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.DISPLAY_ADS]: 'Display Ads',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.VIDEO_ADS]: 'Video Ads',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.AFFILIATE]: 'Affiliate',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.REFERRAL]: 'Referral',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.INFLUENCER]: 'Influencer',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.CONTENT]: 'Content',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.BLOG]: 'Blog',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PODCAST]: 'Podcast',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.WEBINAR]: 'Webinar',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.EVENT]: 'Event',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.DIRECT_MAIL]: 'Direct Mail',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PR]: 'Public Relations',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.OUTDOOR]: 'Outdoor',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.RADIO]: 'Radio',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.TV]: 'Television',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PRINT]: 'Print',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.D2C]: 'Direct to Consumer',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.MARKETPLACE]: 'Marketplace',
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.OTHER]: 'Other',
  };
  return labels[channel] || 'Unknown Channel';
}

export function marketingcampaignGetChannelCategory(
  channel: MarketingCampaignChannel
): MarketingCampaignChannelCategory {
  const categories: Record<MarketingCampaignChannel, MarketingCampaignChannelCategory> = {
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.EMAIL]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.DIGITAL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SMS]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.DIGITAL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PUSH_NOTIFICATION]:
      MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.DIGITAL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.IN_APP]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.DIGITAL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SOCIAL_MEDIA]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.SOCIAL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SEARCH_ENGINE]:
      MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.DIGITAL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.DISPLAY_ADS]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.PAID,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.VIDEO_ADS]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.PAID,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.AFFILIATE]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.PAID,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.REFERRAL]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.EARNED,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.INFLUENCER]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.EARNED,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.CONTENT]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.OWNED,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.BLOG]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.OWNED,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PODCAST]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.OWNED,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.WEBINAR]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.OWNED,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.EVENT]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.OFFLINE,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.DIRECT_MAIL]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.OFFLINE,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PR]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.EARNED,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.OUTDOOR]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.TRADITIONAL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.RADIO]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.TRADITIONAL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.TV]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.TRADITIONAL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PRINT]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.TRADITIONAL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.D2C]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.DIRECT,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.MARKETPLACE]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.DIGITAL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.OTHER]: MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.OTHER,
  };
  return categories[channel] || MARKETINGCAMPAIGN_CHANNEL.CATEGORIES.OTHER;
}

export function marketingcampaignGetChannelCost(
  channel: MarketingCampaignChannel
): MarketingCampaignChannelCost {
  const costs: Record<MarketingCampaignChannel, MarketingCampaignChannelCost> = {
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.EMAIL]: MARKETINGCAMPAIGN_CHANNEL.COSTS.EMAIL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SMS]: MARKETINGCAMPAIGN_CHANNEL.COSTS.SMS,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PUSH_NOTIFICATION]:
      MARKETINGCAMPAIGN_CHANNEL.COSTS.PUSH_NOTIFICATION,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.IN_APP]: MARKETINGCAMPAIGN_CHANNEL.COSTS.IN_APP,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SOCIAL_MEDIA]: MARKETINGCAMPAIGN_CHANNEL.COSTS.SOCIAL_MEDIA,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SEARCH_ENGINE]:
      MARKETINGCAMPAIGN_CHANNEL.COSTS.SEARCH_ENGINE,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.DISPLAY_ADS]: MARKETINGCAMPAIGN_CHANNEL.COSTS.DISPLAY_ADS,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.VIDEO_ADS]: MARKETINGCAMPAIGN_CHANNEL.COSTS.VIDEO_ADS,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.AFFILIATE]: MARKETINGCAMPAIGN_CHANNEL.COSTS.AFFILIATE,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.REFERRAL]: MARKETINGCAMPAIGN_CHANNEL.COSTS.REFERRAL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.INFLUENCER]: MARKETINGCAMPAIGN_CHANNEL.COSTS.INFLUENCER,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.CONTENT]: MARKETINGCAMPAIGN_CHANNEL.COSTS.CONTENT,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.BLOG]: MARKETINGCAMPAIGN_CHANNEL.COSTS.BLOG,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PODCAST]: MARKETINGCAMPAIGN_CHANNEL.COSTS.PODCAST,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.WEBINAR]: MARKETINGCAMPAIGN_CHANNEL.COSTS.WEBINAR,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.EVENT]: MARKETINGCAMPAIGN_CHANNEL.COSTS.EVENT,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.DIRECT_MAIL]: MARKETINGCAMPAIGN_CHANNEL.COSTS.DIRECT_MAIL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PR]: MARKETINGCAMPAIGN_CHANNEL.COSTS.PR,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.OUTDOOR]: MARKETINGCAMPAIGN_CHANNEL.COSTS.OUTDOOR,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.RADIO]: MARKETINGCAMPAIGN_CHANNEL.COSTS.RADIO,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.TV]: MARKETINGCAMPAIGN_CHANNEL.COSTS.TV,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PRINT]: MARKETINGCAMPAIGN_CHANNEL.COSTS.PRINT,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.D2C]: MARKETINGCAMPAIGN_CHANNEL.COSTS.D2C,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.MARKETPLACE]: MARKETINGCAMPAIGN_CHANNEL.COSTS.MARKETPLACE,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.OTHER]: MARKETINGCAMPAIGN_CHANNEL.COSTS.OTHER,
  };
  return costs[channel] || MARKETINGCAMPAIGN_CHANNEL.COSTS.OTHER;
}

export function marketingcampaignGetChannelEffectiveness(
  channel: MarketingCampaignChannel
): MarketingCampaignChannelEffectiveness {
  const effectiveness: Record<MarketingCampaignChannel, MarketingCampaignChannelEffectiveness> = {
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.EMAIL]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.EMAIL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SMS]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.SMS,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PUSH_NOTIFICATION]:
      MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.PUSH_NOTIFICATION,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.IN_APP]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.IN_APP,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SOCIAL_MEDIA]:
      MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.SOCIAL_MEDIA,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SEARCH_ENGINE]:
      MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.SEARCH_ENGINE,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.DISPLAY_ADS]:
      MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.DISPLAY_ADS,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.VIDEO_ADS]:
      MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.VIDEO_ADS,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.AFFILIATE]:
      MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.AFFILIATE,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.REFERRAL]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.REFERRAL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.INFLUENCER]:
      MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.INFLUENCER,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.CONTENT]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.CONTENT,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.BLOG]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.BLOG,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PODCAST]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.PODCAST,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.WEBINAR]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.WEBINAR,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.EVENT]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.EVENT,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.DIRECT_MAIL]:
      MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.DIRECT_MAIL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PR]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.PR,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.OUTDOOR]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.OUTDOOR,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.RADIO]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.RADIO,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.TV]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.TV,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PRINT]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.PRINT,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.D2C]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.D2C,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.MARKETPLACE]:
      MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.MARKETPLACE,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.OTHER]: MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.OTHER,
  };
  return effectiveness[channel] || MARKETINGCAMPAIGN_CHANNEL.EFFECTIVENESS.OTHER;
}

export function marketingcampaignGetChannelReach(
  channel: MarketingCampaignChannel
): MarketingCampaignChannelReach {
  const reach: Record<MarketingCampaignChannel, MarketingCampaignChannelReach> = {
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.EMAIL]: MARKETINGCAMPAIGN_CHANNEL.REACH.EMAIL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SMS]: MARKETINGCAMPAIGN_CHANNEL.REACH.SMS,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PUSH_NOTIFICATION]:
      MARKETINGCAMPAIGN_CHANNEL.REACH.PUSH_NOTIFICATION,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.IN_APP]: MARKETINGCAMPAIGN_CHANNEL.REACH.IN_APP,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SOCIAL_MEDIA]: MARKETINGCAMPAIGN_CHANNEL.REACH.SOCIAL_MEDIA,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SEARCH_ENGINE]:
      MARKETINGCAMPAIGN_CHANNEL.REACH.SEARCH_ENGINE,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.DISPLAY_ADS]: MARKETINGCAMPAIGN_CHANNEL.REACH.DISPLAY_ADS,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.VIDEO_ADS]: MARKETINGCAMPAIGN_CHANNEL.REACH.VIDEO_ADS,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.AFFILIATE]: MARKETINGCAMPAIGN_CHANNEL.REACH.AFFILIATE,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.REFERRAL]: MARKETINGCAMPAIGN_CHANNEL.REACH.REFERRAL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.INFLUENCER]: MARKETINGCAMPAIGN_CHANNEL.REACH.INFLUENCER,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.CONTENT]: MARKETINGCAMPAIGN_CHANNEL.REACH.CONTENT,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.BLOG]: MARKETINGCAMPAIGN_CHANNEL.REACH.BLOG,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PODCAST]: MARKETINGCAMPAIGN_CHANNEL.REACH.PODCAST,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.WEBINAR]: MARKETINGCAMPAIGN_CHANNEL.REACH.WEBINAR,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.EVENT]: MARKETINGCAMPAIGN_CHANNEL.REACH.EVENT,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.DIRECT_MAIL]: MARKETINGCAMPAIGN_CHANNEL.REACH.DIRECT_MAIL,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PR]: MARKETINGCAMPAIGN_CHANNEL.REACH.PR,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.OUTDOOR]: MARKETINGCAMPAIGN_CHANNEL.REACH.OUTDOOR,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.RADIO]: MARKETINGCAMPAIGN_CHANNEL.REACH.RADIO,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.TV]: MARKETINGCAMPAIGN_CHANNEL.REACH.TV,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PRINT]: MARKETINGCAMPAIGN_CHANNEL.REACH.PRINT,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.D2C]: MARKETINGCAMPAIGN_CHANNEL.REACH.D2C,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.MARKETPLACE]: MARKETINGCAMPAIGN_CHANNEL.REACH.MARKETPLACE,
    [MARKETINGCAMPAIGN_CHANNEL.CHANNELS.OTHER]: MARKETINGCAMPAIGN_CHANNEL.REACH.OTHER,
  };
  return reach[channel] || MARKETINGCAMPAIGN_CHANNEL.REACH.OTHER;
}

export function marketingcampaignIsDigitalChannel(channel: MarketingCampaignChannel): boolean {
  const digitalChannels: MarketingCampaignChannel[] = [
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.EMAIL,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SMS,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PUSH_NOTIFICATION,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.IN_APP,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SOCIAL_MEDIA,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SEARCH_ENGINE,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.DISPLAY_ADS,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.VIDEO_ADS,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.AFFILIATE,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.CONTENT,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.BLOG,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.PODCAST,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.WEBINAR,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.D2C,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.MARKETPLACE,
  ];
  return digitalChannels.includes(channel);
}

export function marketingcampaignIsSocialChannel(channel: MarketingCampaignChannel): boolean {
  const socialChannels: MarketingCampaignChannel[] = [
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.SOCIAL_MEDIA,
    MARKETINGCAMPAIGN_CHANNEL.CHANNELS.INFLUENCER,
  ];
  return socialChannels.includes(channel);
}

export function marketingcampaignGetChannelScore(channel: MarketingCampaignChannel): number {
  const cost = marketingcampaignGetChannelCost(channel);
  const effectiveness = marketingcampaignGetChannelEffectiveness(channel);
  const reach = marketingcampaignGetChannelReach(channel);

  // Calculate weighted score (effectiveness * reach / cost)
  return (effectiveness * reach) / cost;
}
