/**
 * চ্যাটবট ইনটেন্ট সংক্রান্ত কনস্ট্যান্টসমূহ
 */

/**
 * চ্যাটবট ইনটেন্ট
 */
export const CHATBOT_INTENT = {
  GREETING: 'greeting',
  FAREWELL: 'farewell',
  HELP: 'help',
  SUPPORT: 'support',
  ORDER_STATUS: 'order_status',
  PRODUCT_INFO: 'product_info',
  PAYMENT: 'payment',
  SHIPPING: 'shipping',
  RETURN: 'return',
  COMPLAINT: 'complaint',
  FEEDBACK: 'feedback',
  ACCOUNT: 'account',
  TECHNICAL: 'technical',
  GENERAL: 'general',
  FALLBACK: 'fallback',
  ESCALATE: 'escalate',
  PRODUCT_SEARCH: 'product_search',
  PRICE_INQUIRY: 'price_inquiry',
  AVAILABILITY: 'availability',
  DELIVERY: 'delivery',
  WARRANTY: 'warranty',
  SUBSCRIPTION: 'subscription',
  BILLING: 'billing',
  CANCEL_ORDER: 'cancel_order',
  MODIFY_ORDER: 'modify_order',
  TRACK_SHIPMENT: 'track_shipment',
  RETURN_POLICY: 'return_policy',
  REFUND_STATUS: 'refund_status',
  COMPLAINT_STATUS: 'complaint_status',
  ACCOUNT_SETUP: 'account_setup',
  PASSWORD_RESET: 'password_reset',
  TWO_FA: 'two_fa',
  DATA_PRIVACY: 'data_privacy',
  INTEGRATION: 'integration',
  API_HELP: 'api_help',
  DOCUMENTATION: 'documentation',
  TROUBLESHOOTING: 'troubleshooting',
  FEATURE_REQUEST: 'feature_request',
  PARTNERSHIP: 'partnership',
  CAREER: 'career',
} as const;

/**
 * চ্যাটবট ইনটেন্টের ডিসপ্লে নাম
 */
export const CHATBOT_INTENT_DISPLAY_NAMES = {
  [CHATBOT_INTENT.GREETING]: 'অভিবাদন',
  [CHATBOT_INTENT.FAREWELL]: 'বিদায়',
  [CHATBOT_INTENT.HELP]: 'সাহায্য',
  [CHATBOT_INTENT.SUPPORT]: 'সাপোর্ট',
  [CHATBOT_INTENT.ORDER_STATUS]: 'অর্ডার স্ট্যাটাস',
  [CHATBOT_INTENT.PRODUCT_INFO]: 'পণ্যের তথ্য',
  [CHATBOT_INTENT.PAYMENT]: 'পেমেন্ট',
  [CHATBOT_INTENT.SHIPPING]: 'শিপিং',
  [CHATBOT_INTENT.RETURN]: 'রিটার্ন',
  [CHATBOT_INTENT.COMPLAINT]: 'অভিযোগ',
  [CHATBOT_INTENT.FEEDBACK]: 'ফিডব্যাক',
  [CHATBOT_INTENT.ACCOUNT]: 'অ্যাকাউন্ট',
  [CHATBOT_INTENT.TECHNICAL]: 'প্রযুক্তিগত',
  [CHATBOT_INTENT.GENERAL]: 'সাধারণ',
  [CHATBOT_INTENT.FALLBACK]: 'ফলব্যাক',
  [CHATBOT_INTENT.ESCALATE]: 'এস্কেলেট',
  [CHATBOT_INTENT.PRODUCT_SEARCH]: 'পণ্য অনুসন্ধান',
  [CHATBOT_INTENT.PRICE_INQUIRY]: 'দাম জিজ্ঞাসা',
  [CHATBOT_INTENT.AVAILABILITY]: 'প্রাপ্যতা',
  [CHATBOT_INTENT.DELIVERY]: 'ডেলিভারি',
  [CHATBOT_INTENT.WARRANTY]: 'ওয়ারেন্টি',
  [CHATBOT_INTENT.SUBSCRIPTION]: 'সাবস্ক্রিপশন',
  [CHATBOT_INTENT.BILLING]: 'বিলিং',
  [CHATBOT_INTENT.CANCEL_ORDER]: 'অর্ডার বাতিল',
  [CHATBOT_INTENT.MODIFY_ORDER]: 'অর্ডার পরিবর্তন',
  [CHATBOT_INTENT.TRACK_SHIPMENT]: 'শিপমেন্ট ট্র্যাক',
  [CHATBOT_INTENT.RETURN_POLICY]: 'রিটার্ন পলিসি',
  [CHATBOT_INTENT.REFUND_STATUS]: 'রিফান্ড স্ট্যাটাস',
  [CHATBOT_INTENT.COMPLAINT_STATUS]: 'অভিযোগের স্ট্যাটাস',
  [CHATBOT_INTENT.ACCOUNT_SETUP]: 'অ্যাকাউন্ট সেটআপ',
  [CHATBOT_INTENT.PASSWORD_RESET]: 'পাসওয়ার্ড রিসেট',
  [CHATBOT_INTENT.TWO_FA]: 'টু-ফ্যাক্টর অথেন্টিকেশন',
  [CHATBOT_INTENT.DATA_PRIVACY]: 'ডেটা প্রাইভেসি',
  [CHATBOT_INTENT.INTEGRATION]: 'ইন্টিগ্রেশন',
  [CHATBOT_INTENT.API_HELP]: 'এপিআই সাহায্য',
  [CHATBOT_INTENT.DOCUMENTATION]: 'ডকুমেন্টেশন',
  [CHATBOT_INTENT.TROUBLESHOOTING]: 'ট্রাবলশুটিং',
  [CHATBOT_INTENT.FEATURE_REQUEST]: 'ফিচার রিকোয়েস্ট',
  [CHATBOT_INTENT.PARTNERSHIP]: 'পার্টনারশিপ',
  [CHATBOT_INTENT.CAREER]: 'ক্যারিয়ার',
} as const;

/**
 * চ্যাটবট ইনটেন্টের আইকন (অনুষঙ্গিক নাম)
 */
export const CHATBOT_INTENT_ICONS = {
  [CHATBOT_INTENT.GREETING]: 'wave',
  [CHATBOT_INTENT.FAREWELL]: 'bye',
  [CHATBOT_INTENT.HELP]: 'help-circle',
  [CHATBOT_INTENT.SUPPORT]: 'headphones',
  [CHATBOT_INTENT.ORDER_STATUS]: 'shopping-bag',
  [CHATBOT_INTENT.PRODUCT_INFO]: 'package',
  [CHATBOT_INTENT.PAYMENT]: 'credit-card',
  [CHATBOT_INTENT.SHIPPING]: 'truck',
  [CHATBOT_INTENT.RETURN]: 'rotate-ccw',
  [CHATBOT_INTENT.COMPLAINT]: 'alert-triangle',
  [CHATBOT_INTENT.FEEDBACK]: 'message-square',
  [CHATBOT_INTENT.ACCOUNT]: 'user',
  [CHATBOT_INTENT.TECHNICAL]: 'cpu',
  [CHATBOT_INTENT.GENERAL]: 'help-circle',
  [CHATBOT_INTENT.FALLBACK]: 'help-circle',
  [CHATBOT_INTENT.ESCALATE]: 'arrow-up-circle',
  [CHATBOT_INTENT.PRODUCT_SEARCH]: 'search',
  [CHATBOT_INTENT.PRICE_INQUIRY]: 'dollar-sign',
  [CHATBOT_INTENT.AVAILABILITY]: 'check-circle',
  [CHATBOT_INTENT.DELIVERY]: 'clock',
  [CHATBOT_INTENT.WARRANTY]: 'shield',
  [CHATBOT_INTENT.SUBSCRIPTION]: 'repeat',
  [CHATBOT_INTENT.BILLING]: 'file-text',
  [CHATBOT_INTENT.CANCEL_ORDER]: 'x-circle',
  [CHATBOT_INTENT.MODIFY_ORDER]: 'edit',
  [CHATBOT_INTENT.TRACK_SHIPMENT]: 'map-pin',
  [CHATBOT_INTENT.RETURN_POLICY]: 'file-text',
  [CHATBOT_INTENT.REFUND_STATUS]: 'dollar-sign',
  [CHATBOT_INTENT.COMPLAINT_STATUS]: 'clock',
  [CHATBOT_INTENT.ACCOUNT_SETUP]: 'user-plus',
  [CHATBOT_INTENT.PASSWORD_RESET]: 'key',
  [CHATBOT_INTENT.TWO_FA]: 'shield-check',
  [CHATBOT_INTENT.DATA_PRIVACY]: 'lock',
  [CHATBOT_INTENT.INTEGRATION]: 'link',
  [CHATBOT_INTENT.API_HELP]: 'code',
  [CHATBOT_INTENT.DOCUMENTATION]: 'book',
  [CHATBOT_INTENT.TROUBLESHOOTING]: 'wrench',
  [CHATBOT_INTENT.FEATURE_REQUEST]: 'star',
  [CHATBOT_INTENT.PARTNERSHIP]: 'handshake',
  [CHATBOT_INTENT.CAREER]: 'briefcase',
} as const;

/**
 * চ্যাটবট ইনটেন্টের রঙের কোড (হেক্স)
 */
export const CHATBOT_INTENT_COLORS = {
  [CHATBOT_INTENT.GREETING]: '#2ecc71',
  [CHATBOT_INTENT.FAREWELL]: '#95a5a6',
  [CHATBOT_INTENT.HELP]: '#3498db',
  [CHATBOT_INTENT.SUPPORT]: '#9b59b6',
  [CHATBOT_INTENT.ORDER_STATUS]: '#e67e22',
  [CHATBOT_INTENT.PRODUCT_INFO]: '#f39c12',
  [CHATBOT_INTENT.PAYMENT]: '#27ae60',
  [CHATBOT_INTENT.SHIPPING]: '#2980b9',
  [CHATBOT_INTENT.RETURN]: '#e74c3c',
  [CHATBOT_INTENT.COMPLAINT]: '#c0392b',
  [CHATBOT_INTENT.FEEDBACK]: '#8e44ad',
  [CHATBOT_INTENT.ACCOUNT]: '#34495e',
  [CHATBOT_INTENT.TECHNICAL]: '#e74c3c',
  [CHATBOT_INTENT.GENERAL]: '#95a5a6',
  [CHATBOT_INTENT.FALLBACK]: '#7f8c8d',
  [CHATBOT_INTENT.ESCALATE]: '#e67e22',
  [CHATBOT_INTENT.PRODUCT_SEARCH]: '#3498db',
  [CHATBOT_INTENT.PRICE_INQUIRY]: '#27ae60',
  [CHATBOT_INTENT.AVAILABILITY]: '#2ecc71',
  [CHATBOT_INTENT.DELIVERY]: '#f39c12',
  [CHATBOT_INTENT.WARRANTY]: '#2c3e50',
  [CHATBOT_INTENT.SUBSCRIPTION]: '#8e44ad',
  [CHATBOT_INTENT.BILLING]: '#27ae60',
  [CHATBOT_INTENT.CANCEL_ORDER]: '#e74c3c',
  [CHATBOT_INTENT.MODIFY_ORDER]: '#f39c12',
  [CHATBOT_INTENT.TRACK_SHIPMENT]: '#2980b9',
  [CHATBOT_INTENT.RETURN_POLICY]: '#e67e22',
  [CHATBOT_INTENT.REFUND_STATUS]: '#27ae60',
  [CHATBOT_INTENT.COMPLAINT_STATUS]: '#f39c12',
  [CHATBOT_INTENT.ACCOUNT_SETUP]: '#2ecc71',
  [CHATBOT_INTENT.PASSWORD_RESET]: '#e67e22',
  [CHATBOT_INTENT.TWO_FA]: '#9b59b6',
  [CHATBOT_INTENT.DATA_PRIVACY]: '#34495e',
  [CHATBOT_INTENT.INTEGRATION]: '#1abc9c',
  [CHATBOT_INTENT.API_HELP]: '#2980b9',
  [CHATBOT_INTENT.DOCUMENTATION]: '#34495e',
  [CHATBOT_INTENT.TROUBLESHOOTING]: '#e67e22',
  [CHATBOT_INTENT.FEATURE_REQUEST]: '#f1c40f',
  [CHATBOT_INTENT.PARTNERSHIP]: '#2ecc71',
  [CHATBOT_INTENT.CAREER]: '#9b59b6',
} as const;

/**
 * চ্যাটবট ইনটেন্টের ক্যাটাগরি
 */
export const CHATBOT_INTENT_CATEGORIES = {
  [CHATBOT_INTENT.GREETING]: 'social',
  [CHATBOT_INTENT.FAREWELL]: 'social',
  [CHATBOT_INTENT.HELP]: 'support',
  [CHATBOT_INTENT.SUPPORT]: 'support',
  [CHATBOT_INTENT.ORDER_STATUS]: 'order',
  [CHATBOT_INTENT.PRODUCT_INFO]: 'product',
  [CHATBOT_INTENT.PAYMENT]: 'financial',
  [CHATBOT_INTENT.SHIPPING]: 'logistics',
  [CHATBOT_INTENT.RETURN]: 'order',
  [CHATBOT_INTENT.COMPLAINT]: 'feedback',
  [CHATBOT_INTENT.FEEDBACK]: 'feedback',
  [CHATBOT_INTENT.ACCOUNT]: 'account',
  [CHATBOT_INTENT.TECHNICAL]: 'technical',
  [CHATBOT_INTENT.GENERAL]: 'general',
  [CHATBOT_INTENT.FALLBACK]: 'system',
  [CHATBOT_INTENT.ESCALATE]: 'system',
  [CHATBOT_INTENT.PRODUCT_SEARCH]: 'product',
  [CHATBOT_INTENT.PRICE_INQUIRY]: 'product',
  [CHATBOT_INTENT.AVAILABILITY]: 'product',
  [CHATBOT_INTENT.DELIVERY]: 'logistics',
  [CHATBOT_INTENT.WARRANTY]: 'product',
  [CHATBOT_INTENT.SUBSCRIPTION]: 'financial',
  [CHATBOT_INTENT.BILLING]: 'financial',
  [CHATBOT_INTENT.CANCEL_ORDER]: 'order',
  [CHATBOT_INTENT.MODIFY_ORDER]: 'order',
  [CHATBOT_INTENT.TRACK_SHIPMENT]: 'logistics',
  [CHATBOT_INTENT.RETURN_POLICY]: 'order',
  [CHATBOT_INTENT.REFUND_STATUS]: 'financial',
  [CHATBOT_INTENT.COMPLAINT_STATUS]: 'feedback',
  [CHATBOT_INTENT.ACCOUNT_SETUP]: 'account',
  [CHATBOT_INTENT.PASSWORD_RESET]: 'account',
  [CHATBOT_INTENT.TWO_FA]: 'account',
  [CHATBOT_INTENT.DATA_PRIVACY]: 'account',
  [CHATBOT_INTENT.INTEGRATION]: 'technical',
  [CHATBOT_INTENT.API_HELP]: 'technical',
  [CHATBOT_INTENT.DOCUMENTATION]: 'knowledge',
  [CHATBOT_INTENT.TROUBLESHOOTING]: 'technical',
  [CHATBOT_INTENT.FEATURE_REQUEST]: 'feedback',
  [CHATBOT_INTENT.PARTNERSHIP]: 'business',
  [CHATBOT_INTENT.CAREER]: 'business',
} as const;

/**
 * চ্যাটবট ইনটেন্টের ডিফল্ট প্রায়োরিটি
 */
export const CHATBOT_INTENT_DEFAULT_PRIORITY = {
  [CHATBOT_INTENT.GREETING]: 10,
  [CHATBOT_INTENT.FAREWELL]: 10,
  [CHATBOT_INTENT.HELP]: 50,
  [CHATBOT_INTENT.SUPPORT]: 80,
  [CHATBOT_INTENT.ORDER_STATUS]: 70,
  [CHATBOT_INTENT.PRODUCT_INFO]: 40,
  [CHATBOT_INTENT.PAYMENT]: 80,
  [CHATBOT_INTENT.SHIPPING]: 70,
  [CHATBOT_INTENT.RETURN]: 60,
  [CHATBOT_INTENT.COMPLAINT]: 90,
  [CHATBOT_INTENT.FEEDBACK]: 30,
  [CHATBOT_INTENT.ACCOUNT]: 60,
  [CHATBOT_INTENT.TECHNICAL]: 70,
  [CHATBOT_INTENT.GENERAL]: 20,
  [CHATBOT_INTENT.FALLBACK]: 0,
  [CHATBOT_INTENT.ESCALATE]: 100,
  [CHATBOT_INTENT.PRODUCT_SEARCH]: 40,
  [CHATBOT_INTENT.PRICE_INQUIRY]: 40,
  [CHATBOT_INTENT.AVAILABILITY]: 50,
  [CHATBOT_INTENT.DELIVERY]: 60,
  [CHATBOT_INTENT.WARRANTY]: 40,
  [CHATBOT_INTENT.SUBSCRIPTION]: 60,
  [CHATBOT_INTENT.BILLING]: 70,
  [CHATBOT_INTENT.CANCEL_ORDER]: 80,
  [CHATBOT_INTENT.MODIFY_ORDER]: 70,
  [CHATBOT_INTENT.TRACK_SHIPMENT]: 60,
  [CHATBOT_INTENT.RETURN_POLICY]: 40,
  [CHATBOT_INTENT.REFUND_STATUS]: 70,
  [CHATBOT_INTENT.COMPLAINT_STATUS]: 50,
  [CHATBOT_INTENT.ACCOUNT_SETUP]: 50,
  [CHATBOT_INTENT.PASSWORD_RESET]: 70,
  [CHATBOT_INTENT.TWO_FA]: 60,
  [CHATBOT_INTENT.DATA_PRIVACY]: 50,
  [CHATBOT_INTENT.INTEGRATION]: 40,
  [CHATBOT_INTENT.API_HELP]: 40,
  [CHATBOT_INTENT.DOCUMENTATION]: 30,
  [CHATBOT_INTENT.TROUBLESHOOTING]: 70,
  [CHATBOT_INTENT.FEATURE_REQUEST]: 30,
  [CHATBOT_INTENT.PARTNERSHIP]: 30,
  [CHATBOT_INTENT.CAREER]: 20,
} as const;

/**
 * চ্যাটবট ইনটেন্ট গ্রুপ
 */
export const CHATBOT_INTENT_GROUPS = {
  SOCIAL: ['greeting', 'farewell'] as const,
  SUPPORT: ['help', 'support', 'escalate'] as const,
  ORDER: ['order_status', 'return', 'cancel_order', 'modify_order', 'return_policy'] as const,
  PRODUCT: ['product_info', 'product_search', 'price_inquiry', 'availability', 'warranty'] as const,
  FINANCIAL: ['payment', 'subscription', 'billing', 'refund_status'] as const,
  LOGISTICS: ['shipping', 'delivery', 'track_shipment'] as const,
  FEEDBACK: ['complaint', 'feedback', 'complaint_status', 'feature_request'] as const,
  ACCOUNT: ['account', 'account_setup', 'password_reset', 'two_fa', 'data_privacy'] as const,
  TECHNICAL: ['technical', 'integration', 'api_help', 'troubleshooting'] as const,
  KNOWLEDGE: ['documentation'] as const,
  BUSINESS: ['partnership', 'career'] as const,
  GENERAL: ['general'] as const,
  SYSTEM: ['fallback'] as const,
} as const;

export type ChatbotIntent = (typeof CHATBOT_INTENT)[keyof typeof CHATBOT_INTENT];
export type ChatbotIntentDisplayNames = typeof CHATBOT_INTENT_DISPLAY_NAMES;
export type ChatbotIntentIcons = typeof CHATBOT_INTENT_ICONS;
export type ChatbotIntentColors = typeof CHATBOT_INTENT_COLORS;
export type ChatbotIntentCategories = typeof CHATBOT_INTENT_CATEGORIES;
export type ChatbotIntentDefaultPriority = typeof CHATBOT_INTENT_DEFAULT_PRIORITY;
export type ChatbotIntentGroups = typeof CHATBOT_INTENT_GROUPS;

export type ChatbotIntentGroup = keyof typeof CHATBOT_INTENT_GROUPS;

export interface ChatbotIntentConfig {
  intent: ChatbotIntent;
  displayName: string;
  icon: string;
  color: string;
  category: string;
  defaultPriority: number;
  group: ChatbotIntentGroup;
  examples?: string[];
  responses?: string[];
  description?: string;
}

/**
 * চ্যাটবট ইনটেন্ট কনফিগারেশন অবজেক্ট
 */
export const CHATBOT_INTENT_CONFIGS: Record<ChatbotIntent, ChatbotIntentConfig> = {
  [CHATBOT_INTENT.GREETING]: {
    intent: CHATBOT_INTENT.GREETING,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.GREETING],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.GREETING],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.GREETING],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.GREETING],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.GREETING],
    group: 'SOCIAL',
    description: 'ব্যবহারকারীর অভিবাদন',
  },
  [CHATBOT_INTENT.FAREWELL]: {
    intent: CHATBOT_INTENT.FAREWELL,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.FAREWELL],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.FAREWELL],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.FAREWELL],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.FAREWELL],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.FAREWELL],
    group: 'SOCIAL',
    description: 'ব্যবহারকারীর বিদায়',
  },
  [CHATBOT_INTENT.HELP]: {
    intent: CHATBOT_INTENT.HELP,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.HELP],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.HELP],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.HELP],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.HELP],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.HELP],
    group: 'SUPPORT',
    description: 'সাহায্য প্রয়োজন',
  },
  [CHATBOT_INTENT.SUPPORT]: {
    intent: CHATBOT_INTENT.SUPPORT,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.SUPPORT],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.SUPPORT],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.SUPPORT],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.SUPPORT],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.SUPPORT],
    group: 'SUPPORT',
    description: 'সাপোর্ট প্রয়োজন',
  },
  [CHATBOT_INTENT.ORDER_STATUS]: {
    intent: CHATBOT_INTENT.ORDER_STATUS,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.ORDER_STATUS],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.ORDER_STATUS],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.ORDER_STATUS],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.ORDER_STATUS],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.ORDER_STATUS],
    group: 'ORDER',
    description: 'অর্ডারের স্ট্যাটাস জানতে চাওয়া',
  },
  [CHATBOT_INTENT.PRODUCT_INFO]: {
    intent: CHATBOT_INTENT.PRODUCT_INFO,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.PRODUCT_INFO],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.PRODUCT_INFO],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.PRODUCT_INFO],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.PRODUCT_INFO],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.PRODUCT_INFO],
    group: 'PRODUCT',
    description: 'পণ্যের তথ্য জানতে চাওয়া',
  },
  [CHATBOT_INTENT.PAYMENT]: {
    intent: CHATBOT_INTENT.PAYMENT,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.PAYMENT],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.PAYMENT],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.PAYMENT],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.PAYMENT],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.PAYMENT],
    group: 'FINANCIAL',
    description: 'পেমেন্ট সম্পর্কিত প্রশ্ন',
  },
  [CHATBOT_INTENT.SHIPPING]: {
    intent: CHATBOT_INTENT.SHIPPING,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.SHIPPING],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.SHIPPING],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.SHIPPING],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.SHIPPING],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.SHIPPING],
    group: 'LOGISTICS',
    description: 'শিপিং সম্পর্কিত প্রশ্ন',
  },
  [CHATBOT_INTENT.RETURN]: {
    intent: CHATBOT_INTENT.RETURN,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.RETURN],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.RETURN],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.RETURN],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.RETURN],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.RETURN],
    group: 'ORDER',
    description: 'রিটার্ন সম্পর্কিত প্রশ্ন',
  },
  [CHATBOT_INTENT.COMPLAINT]: {
    intent: CHATBOT_INTENT.COMPLAINT,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.COMPLAINT],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.COMPLAINT],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.COMPLAINT],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.COMPLAINT],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.COMPLAINT],
    group: 'FEEDBACK',
    description: 'অভিযোগ জানানো',
  },
  [CHATBOT_INTENT.FEEDBACK]: {
    intent: CHATBOT_INTENT.FEEDBACK,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.FEEDBACK],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.FEEDBACK],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.FEEDBACK],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.FEEDBACK],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.FEEDBACK],
    group: 'FEEDBACK',
    description: 'ফিডব্যাক প্রদান',
  },
  [CHATBOT_INTENT.ACCOUNT]: {
    intent: CHATBOT_INTENT.ACCOUNT,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.ACCOUNT],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.ACCOUNT],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.ACCOUNT],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.ACCOUNT],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.ACCOUNT],
    group: 'ACCOUNT',
    description: 'অ্যাকাউন্ট সম্পর্কিত প্রশ্ন',
  },
  [CHATBOT_INTENT.TECHNICAL]: {
    intent: CHATBOT_INTENT.TECHNICAL,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.TECHNICAL],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.TECHNICAL],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.TECHNICAL],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.TECHNICAL],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.TECHNICAL],
    group: 'TECHNICAL',
    description: 'প্রযুক্তিগত সমস্যা',
  },
  [CHATBOT_INTENT.GENERAL]: {
    intent: CHATBOT_INTENT.GENERAL,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.GENERAL],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.GENERAL],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.GENERAL],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.GENERAL],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.GENERAL],
    group: 'GENERAL',
    description: 'সাধারণ প্রশ্ন',
  },
  [CHATBOT_INTENT.FALLBACK]: {
    intent: CHATBOT_INTENT.FALLBACK,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.FALLBACK],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.FALLBACK],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.FALLBACK],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.FALLBACK],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.FALLBACK],
    group: 'SYSTEM',
    description: 'অজ্ঞাত প্রশ্নের জন্য ফলব্যাক',
  },
  [CHATBOT_INTENT.ESCALATE]: {
    intent: CHATBOT_INTENT.ESCALATE,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.ESCALATE],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.ESCALATE],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.ESCALATE],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.ESCALATE],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.ESCALATE],
    group: 'SUPPORT',
    description: 'এজেন্টে স্থানান্তর প্রয়োজন',
  },
  [CHATBOT_INTENT.PRODUCT_SEARCH]: {
    intent: CHATBOT_INTENT.PRODUCT_SEARCH,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.PRODUCT_SEARCH],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.PRODUCT_SEARCH],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.PRODUCT_SEARCH],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.PRODUCT_SEARCH],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.PRODUCT_SEARCH],
    group: 'PRODUCT',
    description: 'পণ্য অনুসন্ধান',
  },
  [CHATBOT_INTENT.PRICE_INQUIRY]: {
    intent: CHATBOT_INTENT.PRICE_INQUIRY,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.PRICE_INQUIRY],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.PRICE_INQUIRY],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.PRICE_INQUIRY],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.PRICE_INQUIRY],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.PRICE_INQUIRY],
    group: 'PRODUCT',
    description: 'দাম সম্পর্কে জিজ্ঞাসা',
  },
  [CHATBOT_INTENT.AVAILABILITY]: {
    intent: CHATBOT_INTENT.AVAILABILITY,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.AVAILABILITY],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.AVAILABILITY],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.AVAILABILITY],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.AVAILABILITY],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.AVAILABILITY],
    group: 'PRODUCT',
    description: 'পণ্যের প্রাপ্যতা জানতে চাওয়া',
  },
  [CHATBOT_INTENT.DELIVERY]: {
    intent: CHATBOT_INTENT.DELIVERY,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.DELIVERY],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.DELIVERY],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.DELIVERY],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.DELIVERY],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.DELIVERY],
    group: 'LOGISTICS',
    description: 'ডেলিভারি সম্পর্কিত প্রশ্ন',
  },
  [CHATBOT_INTENT.WARRANTY]: {
    intent: CHATBOT_INTENT.WARRANTY,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.WARRANTY],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.WARRANTY],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.WARRANTY],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.WARRANTY],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.WARRANTY],
    group: 'PRODUCT',
    description: 'ওয়ারেন্টি সম্পর্কিত প্রশ্ন',
  },
  [CHATBOT_INTENT.SUBSCRIPTION]: {
    intent: CHATBOT_INTENT.SUBSCRIPTION,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.SUBSCRIPTION],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.SUBSCRIPTION],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.SUBSCRIPTION],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.SUBSCRIPTION],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.SUBSCRIPTION],
    group: 'FINANCIAL',
    description: 'সাবস্ক্রিপশন সম্পর্কিত প্রশ্ন',
  },
  [CHATBOT_INTENT.BILLING]: {
    intent: CHATBOT_INTENT.BILLING,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.BILLING],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.BILLING],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.BILLING],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.BILLING],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.BILLING],
    group: 'FINANCIAL',
    description: 'বিলিং সম্পর্কিত প্রশ্ন',
  },
  [CHATBOT_INTENT.CANCEL_ORDER]: {
    intent: CHATBOT_INTENT.CANCEL_ORDER,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.CANCEL_ORDER],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.CANCEL_ORDER],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.CANCEL_ORDER],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.CANCEL_ORDER],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.CANCEL_ORDER],
    group: 'ORDER',
    description: 'অর্ডার বাতিল করতে চাওয়া',
  },
  [CHATBOT_INTENT.MODIFY_ORDER]: {
    intent: CHATBOT_INTENT.MODIFY_ORDER,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.MODIFY_ORDER],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.MODIFY_ORDER],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.MODIFY_ORDER],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.MODIFY_ORDER],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.MODIFY_ORDER],
    group: 'ORDER',
    description: 'অর্ডার পরিবর্তন করতে চাওয়া',
  },
  [CHATBOT_INTENT.TRACK_SHIPMENT]: {
    intent: CHATBOT_INTENT.TRACK_SHIPMENT,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.TRACK_SHIPMENT],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.TRACK_SHIPMENT],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.TRACK_SHIPMENT],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.TRACK_SHIPMENT],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.TRACK_SHIPMENT],
    group: 'LOGISTICS',
    description: 'শিপমেন্ট ট্র্যাক করতে চাওয়া',
  },
  [CHATBOT_INTENT.RETURN_POLICY]: {
    intent: CHATBOT_INTENT.RETURN_POLICY,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.RETURN_POLICY],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.RETURN_POLICY],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.RETURN_POLICY],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.RETURN_POLICY],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.RETURN_POLICY],
    group: 'ORDER',
    description: 'রিটার্ন পলিসি জানতে চাওয়া',
  },
  [CHATBOT_INTENT.REFUND_STATUS]: {
    intent: CHATBOT_INTENT.REFUND_STATUS,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.REFUND_STATUS],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.REFUND_STATUS],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.REFUND_STATUS],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.REFUND_STATUS],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.REFUND_STATUS],
    group: 'FINANCIAL',
    description: 'রিফান্ড স্ট্যাটাস জানতে চাওয়া',
  },
  [CHATBOT_INTENT.COMPLAINT_STATUS]: {
    intent: CHATBOT_INTENT.COMPLAINT_STATUS,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.COMPLAINT_STATUS],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.COMPLAINT_STATUS],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.COMPLAINT_STATUS],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.COMPLAINT_STATUS],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.COMPLAINT_STATUS],
    group: 'FEEDBACK',
    description: 'অভিযোগের স্ট্যাটাস জানতে চাওয়া',
  },
  [CHATBOT_INTENT.ACCOUNT_SETUP]: {
    intent: CHATBOT_INTENT.ACCOUNT_SETUP,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.ACCOUNT_SETUP],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.ACCOUNT_SETUP],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.ACCOUNT_SETUP],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.ACCOUNT_SETUP],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.ACCOUNT_SETUP],
    group: 'ACCOUNT',
    description: 'অ্যাকাউন্ট সেটআপ করতে চাওয়া',
  },
  [CHATBOT_INTENT.PASSWORD_RESET]: {
    intent: CHATBOT_INTENT.PASSWORD_RESET,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.PASSWORD_RESET],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.PASSWORD_RESET],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.PASSWORD_RESET],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.PASSWORD_RESET],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.PASSWORD_RESET],
    group: 'ACCOUNT',
    description: 'পাসওয়ার্ড রিসেট করতে চাওয়া',
  },
  [CHATBOT_INTENT.TWO_FA]: {
    intent: CHATBOT_INTENT.TWO_FA,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.TWO_FA],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.TWO_FA],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.TWO_FA],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.TWO_FA],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.TWO_FA],
    group: 'ACCOUNT',
    description: 'টু-ফ্যাক্টর অথেন্টিকেশন সম্পর্কিত প্রশ্ন',
  },
  [CHATBOT_INTENT.DATA_PRIVACY]: {
    intent: CHATBOT_INTENT.DATA_PRIVACY,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.DATA_PRIVACY],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.DATA_PRIVACY],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.DATA_PRIVACY],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.DATA_PRIVACY],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.DATA_PRIVACY],
    group: 'ACCOUNT',
    description: 'ডেটা প্রাইভেসি সম্পর্কিত প্রশ্ন',
  },
  [CHATBOT_INTENT.INTEGRATION]: {
    intent: CHATBOT_INTENT.INTEGRATION,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.INTEGRATION],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.INTEGRATION],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.INTEGRATION],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.INTEGRATION],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.INTEGRATION],
    group: 'TECHNICAL',
    description: 'ইন্টিগ্রেশন সম্পর্কিত প্রশ্ন',
  },
  [CHATBOT_INTENT.API_HELP]: {
    intent: CHATBOT_INTENT.API_HELP,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.API_HELP],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.API_HELP],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.API_HELP],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.API_HELP],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.API_HELP],
    group: 'TECHNICAL',
    description: 'এপিআই সাহায্য প্রয়োজন',
  },
  [CHATBOT_INTENT.DOCUMENTATION]: {
    intent: CHATBOT_INTENT.DOCUMENTATION,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.DOCUMENTATION],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.DOCUMENTATION],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.DOCUMENTATION],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.DOCUMENTATION],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.DOCUMENTATION],
    group: 'KNOWLEDGE',
    description: 'ডকুমেন্টেশন সম্পর্কিত প্রশ্ন',
  },
  [CHATBOT_INTENT.TROUBLESHOOTING]: {
    intent: CHATBOT_INTENT.TROUBLESHOOTING,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.TROUBLESHOOTING],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.TROUBLESHOOTING],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.TROUBLESHOOTING],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.TROUBLESHOOTING],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.TROUBLESHOOTING],
    group: 'TECHNICAL',
    description: 'ট্রাবলশুটিং প্রয়োজন',
  },
  [CHATBOT_INTENT.FEATURE_REQUEST]: {
    intent: CHATBOT_INTENT.FEATURE_REQUEST,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.FEATURE_REQUEST],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.FEATURE_REQUEST],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.FEATURE_REQUEST],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.FEATURE_REQUEST],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.FEATURE_REQUEST],
    group: 'FEEDBACK',
    description: 'নতুন ফিচারের জন্য অনুরোধ',
  },
  [CHATBOT_INTENT.PARTNERSHIP]: {
    intent: CHATBOT_INTENT.PARTNERSHIP,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.PARTNERSHIP],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.PARTNERSHIP],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.PARTNERSHIP],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.PARTNERSHIP],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.PARTNERSHIP],
    group: 'BUSINESS',
    description: 'পার্টনারশিপ সম্পর্কিত প্রশ্ন',
  },
  [CHATBOT_INTENT.CAREER]: {
    intent: CHATBOT_INTENT.CAREER,
    displayName: CHATBOT_INTENT_DISPLAY_NAMES[CHATBOT_INTENT.CAREER],
    icon: CHATBOT_INTENT_ICONS[CHATBOT_INTENT.CAREER],
    color: CHATBOT_INTENT_COLORS[CHATBOT_INTENT.CAREER],
    category: CHATBOT_INTENT_CATEGORIES[CHATBOT_INTENT.CAREER],
    defaultPriority: CHATBOT_INTENT_DEFAULT_PRIORITY[CHATBOT_INTENT.CAREER],
    group: 'BUSINESS',
    description: 'ক্যারিয়ার সম্পর্কিত প্রশ্ন',
  },
};

/**
 * চ্যাটবট ইনটেন্ট গ্রুপ কনফিগারেশন
 */
export const CHATBOT_INTENT_GROUP_CONFIGS: Record<
  ChatbotIntentGroup,
  {
    group: ChatbotIntentGroup;
    displayName: string;
    icon: string;
    color: string;
    intents: readonly ChatbotIntent[];
    description?: string;
  }
> = {
  SOCIAL: {
    group: 'SOCIAL',
    displayName: 'সামাজিক',
    icon: 'users',
    color: '#2ecc71',
    intents: ['greeting', 'farewell'] as const,
    description: 'অভিবাদন ও বিদায়',
  },
  SUPPORT: {
    group: 'SUPPORT',
    displayName: 'সাপোর্ট',
    icon: 'headphones',
    color: '#9b59b6',
    intents: ['help', 'support', 'escalate'] as const,
    description: 'সাপোর্ট ও সাহায্য',
  },
  ORDER: {
    group: 'ORDER',
    displayName: 'অর্ডার',
    icon: 'shopping-bag',
    color: '#e67e22',
    intents: ['order_status', 'return', 'cancel_order', 'modify_order', 'return_policy'] as const,
    description: 'অর্ডার সম্পর্কিত',
  },
  PRODUCT: {
    group: 'PRODUCT',
    displayName: 'পণ্য',
    icon: 'package',
    color: '#f39c12',
    intents: [
      'product_info',
      'product_search',
      'price_inquiry',
      'availability',
      'warranty',
    ] as const,
    description: 'পণ্য সম্পর্কিত',
  },
  FINANCIAL: {
    group: 'FINANCIAL',
    displayName: 'আর্থিক',
    icon: 'dollar-sign',
    color: '#27ae60',
    intents: ['payment', 'subscription', 'billing', 'refund_status'] as const,
    description: 'পেমেন্ট ও আর্থিক বিষয়',
  },
  LOGISTICS: {
    group: 'LOGISTICS',
    displayName: 'লজিস্টিকস',
    icon: 'truck',
    color: '#2980b9',
    intents: ['shipping', 'delivery', 'track_shipment'] as const,
    description: 'শিপিং ও ডেলিভারি',
  },
  FEEDBACK: {
    group: 'FEEDBACK',
    displayName: 'মতামত',
    icon: 'message-square',
    color: '#8e44ad',
    intents: ['complaint', 'feedback', 'complaint_status', 'feature_request'] as const,
    description: 'অভিযোগ ও মতামত',
  },
  ACCOUNT: {
    group: 'ACCOUNT',
    displayName: 'অ্যাকাউন্ট',
    icon: 'user',
    color: '#34495e',
    intents: ['account', 'account_setup', 'password_reset', 'two_fa', 'data_privacy'] as const,
    description: 'অ্যাকাউন্ট সম্পর্কিত',
  },
  TECHNICAL: {
    group: 'TECHNICAL',
    displayName: 'প্রযুক্তিগত',
    icon: 'cpu',
    color: '#e74c3c',
    intents: ['technical', 'integration', 'api_help', 'troubleshooting'] as const,
    description: 'প্রযুক্তিগত বিষয়',
  },
  KNOWLEDGE: {
    group: 'KNOWLEDGE',
    displayName: 'জ্ঞান',
    icon: 'book',
    color: '#34495e',
    intents: ['documentation'] as const,
    description: 'ডকুমেন্টেশন ও জ্ঞান',
  },
  BUSINESS: {
    group: 'BUSINESS',
    displayName: 'ব্যবসা',
    icon: 'briefcase',
    color: '#9b59b6',
    intents: ['partnership', 'career'] as const,
    description: 'ব্যবসা ও ক্যারিয়ার',
  },
  GENERAL: {
    group: 'GENERAL',
    displayName: 'সাধারণ',
    icon: 'help-circle',
    color: '#95a5a6',
    intents: ['general'] as const,
    description: 'সাধারণ প্রশ্ন',
  },
  SYSTEM: {
    group: 'SYSTEM',
    displayName: 'সিস্টেম',
    icon: 'settings',
    color: '#7f8c8d',
    intents: ['fallback'] as const,
    description: 'সিস্টেম স্তরের ইনটেন্ট',
  },
};

/**
 * চ্যাটবট ইনটেন্ট স্ট্যাটাস
 */
export const CHATBOT_INTENT_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  TRAINING: 'training',
  DEPRECATED: 'deprecated',
} as const;

export type ChatbotIntentStatus =
  (typeof CHATBOT_INTENT_STATUS)[keyof typeof CHATBOT_INTENT_STATUS];
