/**
 * চ্যাটবট এন্টিটি সংক্রান্ত কনস্ট্যান্টসমূহ
 */

/**
 * চ্যাটবট এন্টিটি টাইপ
 */
export const CHATBOT_ENTITY = {
  DATE: 'date',
  TIME: 'time',
  NUMBER: 'number',
  EMAIL: 'email',
  PHONE: 'phone',
  NAME: 'name',
  ADDRESS: 'address',
  ORDER_ID: 'order_id',
  PRODUCT_ID: 'product_id',
  PRICE: 'price',
  QUANTITY: 'quantity',
  LOCATION: 'location',
  URL: 'url',
  CURRENCY: 'currency',
  UNIT: 'unit',
  PERCENTAGE: 'percentage',
  USERNAME: 'username',
  PASSWORD: 'password',
  OTP: 'otp',
  CARD_NUMBER: 'card_number',
  EXPIRY_DATE: 'expiry_date',
  CVV: 'cvv',
  COMPANY: 'company',
  DEPARTMENT: 'department',
  ROLE: 'role',
  SKILL: 'skill',
  LANGUAGE: 'language',
  COUNTRY: 'country',
  CITY: 'city',
  POSTAL_CODE: 'postal_code',
  IP_ADDRESS: 'ip_address',
  MAC_ADDRESS: 'mac_address',
  DEVICE: 'device',
  OS: 'os',
  BROWSER: 'browser',
  VERSION: 'version',
  STATUS: 'status',
  PRIORITY: 'priority',
  CATEGORY: 'category',
  TAGS: 'tags',
  KEYWORDS: 'keywords',
} as const;

/**
 * চ্যাটবট এন্টিটি টাইপের ডিসপ্লে নাম
 */
export const CHATBOT_ENTITY_DISPLAY_NAMES = {
  [CHATBOT_ENTITY.DATE]: 'তারিখ',
  [CHATBOT_ENTITY.TIME]: 'সময়',
  [CHATBOT_ENTITY.NUMBER]: 'সংখ্যা',
  [CHATBOT_ENTITY.EMAIL]: 'ইমেইল',
  [CHATBOT_ENTITY.PHONE]: 'ফোন',
  [CHATBOT_ENTITY.NAME]: 'নাম',
  [CHATBOT_ENTITY.ADDRESS]: 'ঠিকানা',
  [CHATBOT_ENTITY.ORDER_ID]: 'অর্ডার আইডি',
  [CHATBOT_ENTITY.PRODUCT_ID]: 'পণ্য আইডি',
  [CHATBOT_ENTITY.PRICE]: 'দাম',
  [CHATBOT_ENTITY.QUANTITY]: 'পরিমাণ',
  [CHATBOT_ENTITY.LOCATION]: 'অবস্থান',
  [CHATBOT_ENTITY.URL]: 'ইউআরএল',
  [CHATBOT_ENTITY.CURRENCY]: 'মুদ্রা',
  [CHATBOT_ENTITY.UNIT]: 'ইউনিট',
  [CHATBOT_ENTITY.PERCENTAGE]: 'শতাংশ',
  [CHATBOT_ENTITY.USERNAME]: 'ব্যবহারকারী নাম',
  [CHATBOT_ENTITY.PASSWORD]: 'পাসওয়ার্ড',
  [CHATBOT_ENTITY.OTP]: 'ওটিপি',
  [CHATBOT_ENTITY.CARD_NUMBER]: 'কার্ড নম্বর',
  [CHATBOT_ENTITY.EXPIRY_DATE]: 'মেয়াদ শেষের তারিখ',
  [CHATBOT_ENTITY.CVV]: 'সিভিভি',
  [CHATBOT_ENTITY.COMPANY]: 'কোম্পানি',
  [CHATBOT_ENTITY.DEPARTMENT]: 'বিভাগ',
  [CHATBOT_ENTITY.ROLE]: 'ভূমিকা',
  [CHATBOT_ENTITY.SKILL]: 'দক্ষতা',
  [CHATBOT_ENTITY.LANGUAGE]: 'ভাষা',
  [CHATBOT_ENTITY.COUNTRY]: 'দেশ',
  [CHATBOT_ENTITY.CITY]: 'শহর',
  [CHATBOT_ENTITY.POSTAL_CODE]: 'পোস্টাল কোড',
  [CHATBOT_ENTITY.IP_ADDRESS]: 'আইপি ঠিকানা',
  [CHATBOT_ENTITY.MAC_ADDRESS]: 'ম্যাক ঠিকানা',
  [CHATBOT_ENTITY.DEVICE]: 'ডিভাইস',
  [CHATBOT_ENTITY.OS]: 'ওএস',
  [CHATBOT_ENTITY.BROWSER]: 'ব্রাউজার',
  [CHATBOT_ENTITY.VERSION]: 'সংস্করণ',
  [CHATBOT_ENTITY.STATUS]: 'স্ট্যাটাস',
  [CHATBOT_ENTITY.PRIORITY]: 'প্রায়োরিটি',
  [CHATBOT_ENTITY.CATEGORY]: 'ক্যাটাগরি',
  [CHATBOT_ENTITY.TAGS]: 'ট্যাগ',
  [CHATBOT_ENTITY.KEYWORDS]: 'কীওয়ার্ড',
} as const;

/**
 * চ্যাটবট এন্টিটি টাইপের আইকন (অনুষঙ্গিক নাম)
 */
export const CHATBOT_ENTITY_ICONS = {
  [CHATBOT_ENTITY.DATE]: 'calendar',
  [CHATBOT_ENTITY.TIME]: 'clock',
  [CHATBOT_ENTITY.NUMBER]: 'hash',
  [CHATBOT_ENTITY.EMAIL]: 'mail',
  [CHATBOT_ENTITY.PHONE]: 'phone',
  [CHATBOT_ENTITY.NAME]: 'user',
  [CHATBOT_ENTITY.ADDRESS]: 'home',
  [CHATBOT_ENTITY.ORDER_ID]: 'shopping-bag',
  [CHATBOT_ENTITY.PRODUCT_ID]: 'package',
  [CHATBOT_ENTITY.PRICE]: 'dollar-sign',
  [CHATBOT_ENTITY.QUANTITY]: 'hash',
  [CHATBOT_ENTITY.LOCATION]: 'map-pin',
  [CHATBOT_ENTITY.URL]: 'link',
  [CHATBOT_ENTITY.CURRENCY]: 'dollar-sign',
  [CHATBOT_ENTITY.UNIT]: 'ruler',
  [CHATBOT_ENTITY.PERCENTAGE]: 'percent',
  [CHATBOT_ENTITY.USERNAME]: 'user',
  [CHATBOT_ENTITY.PASSWORD]: 'key',
  [CHATBOT_ENTITY.OTP]: 'shield',
  [CHATBOT_ENTITY.CARD_NUMBER]: 'credit-card',
  [CHATBOT_ENTITY.EXPIRY_DATE]: 'calendar',
  [CHATBOT_ENTITY.CVV]: 'shield',
  [CHATBOT_ENTITY.COMPANY]: 'building',
  [CHATBOT_ENTITY.DEPARTMENT]: 'layers',
  [CHATBOT_ENTITY.ROLE]: 'badge',
  [CHATBOT_ENTITY.SKILL]: 'zap',
  [CHATBOT_ENTITY.LANGUAGE]: 'globe',
  [CHATBOT_ENTITY.COUNTRY]: 'flag',
  [CHATBOT_ENTITY.CITY]: 'map',
  [CHATBOT_ENTITY.POSTAL_CODE]: 'mail',
  [CHATBOT_ENTITY.IP_ADDRESS]: 'wifi',
  [CHATBOT_ENTITY.MAC_ADDRESS]: 'wifi',
  [CHATBOT_ENTITY.DEVICE]: 'smartphone',
  [CHATBOT_ENTITY.OS]: 'monitor',
  [CHATBOT_ENTITY.BROWSER]: 'globe',
  [CHATBOT_ENTITY.VERSION]: 'code',
  [CHATBOT_ENTITY.STATUS]: 'circle',
  [CHATBOT_ENTITY.PRIORITY]: 'flag',
  [CHATBOT_ENTITY.CATEGORY]: 'folder',
  [CHATBOT_ENTITY.TAGS]: 'tag',
  [CHATBOT_ENTITY.KEYWORDS]: 'search',
} as const;

/**
 * চ্যাটবট এন্টিটি টাইপের রঙের কোড (হেক্স)
 */
export const CHATBOT_ENTITY_COLORS = {
  [CHATBOT_ENTITY.DATE]: '#3498db',
  [CHATBOT_ENTITY.TIME]: '#2ecc71',
  [CHATBOT_ENTITY.NUMBER]: '#f39c12',
  [CHATBOT_ENTITY.EMAIL]: '#e74c3c',
  [CHATBOT_ENTITY.PHONE]: '#9b59b6',
  [CHATBOT_ENTITY.NAME]: '#1abc9c',
  [CHATBOT_ENTITY.ADDRESS]: '#e67e22',
  [CHATBOT_ENTITY.ORDER_ID]: '#2980b9',
  [CHATBOT_ENTITY.PRODUCT_ID]: '#d35400',
  [CHATBOT_ENTITY.PRICE]: '#27ae60',
  [CHATBOT_ENTITY.QUANTITY]: '#f39c12',
  [CHATBOT_ENTITY.LOCATION]: '#e74c3c',
  [CHATBOT_ENTITY.URL]: '#3498db',
  [CHATBOT_ENTITY.CURRENCY]: '#2ecc71',
  [CHATBOT_ENTITY.UNIT]: '#95a5a6',
  [CHATBOT_ENTITY.PERCENTAGE]: '#e67e22',
  [CHATBOT_ENTITY.USERNAME]: '#1abc9c',
  [CHATBOT_ENTITY.PASSWORD]: '#c0392b',
  [CHATBOT_ENTITY.OTP]: '#9b59b6',
  [CHATBOT_ENTITY.CARD_NUMBER]: '#34495e',
  [CHATBOT_ENTITY.EXPIRY_DATE]: '#3498db',
  [CHATBOT_ENTITY.CVV]: '#c0392b',
  [CHATBOT_ENTITY.COMPANY]: '#2c3e50',
  [CHATBOT_ENTITY.DEPARTMENT]: '#7f8c8d',
  [CHATBOT_ENTITY.ROLE]: '#8e44ad',
  [CHATBOT_ENTITY.SKILL]: '#2ecc71',
  [CHATBOT_ENTITY.LANGUAGE]: '#3498db',
  [CHATBOT_ENTITY.COUNTRY]: '#e67e22',
  [CHATBOT_ENTITY.CITY]: '#f39c12',
  [CHATBOT_ENTITY.POSTAL_CODE]: '#95a5a6',
  [CHATBOT_ENTITY.IP_ADDRESS]: '#2980b9',
  [CHATBOT_ENTITY.MAC_ADDRESS]: '#7f8c8d',
  [CHATBOT_ENTITY.DEVICE]: '#d35400',
  [CHATBOT_ENTITY.OS]: '#34495e',
  [CHATBOT_ENTITY.BROWSER]: '#3498db',
  [CHATBOT_ENTITY.VERSION]: '#16a085',
  [CHATBOT_ENTITY.STATUS]: '#f39c12',
  [CHATBOT_ENTITY.PRIORITY]: '#e74c3c',
  [CHATBOT_ENTITY.CATEGORY]: '#9b59b6',
  [CHATBOT_ENTITY.TAGS]: '#e67e22',
  [CHATBOT_ENTITY.KEYWORDS]: '#3498db',
} as const;

/**
 * চ্যাটবট এন্টিটি টাইপের ক্যাটাগরি
 */
export const CHATBOT_ENTITY_CATEGORIES = {
  [CHATBOT_ENTITY.DATE]: 'temporal',
  [CHATBOT_ENTITY.TIME]: 'temporal',
  [CHATBOT_ENTITY.NUMBER]: 'numeric',
  [CHATBOT_ENTITY.EMAIL]: 'contact',
  [CHATBOT_ENTITY.PHONE]: 'contact',
  [CHATBOT_ENTITY.NAME]: 'personal',
  [CHATBOT_ENTITY.ADDRESS]: 'location',
  [CHATBOT_ENTITY.ORDER_ID]: 'identifier',
  [CHATBOT_ENTITY.PRODUCT_ID]: 'identifier',
  [CHATBOT_ENTITY.PRICE]: 'financial',
  [CHATBOT_ENTITY.QUANTITY]: 'numeric',
  [CHATBOT_ENTITY.LOCATION]: 'location',
  [CHATBOT_ENTITY.URL]: 'web',
  [CHATBOT_ENTITY.CURRENCY]: 'financial',
  [CHATBOT_ENTITY.UNIT]: 'measurement',
  [CHATBOT_ENTITY.PERCENTAGE]: 'numeric',
  [CHATBOT_ENTITY.USERNAME]: 'personal',
  [CHATBOT_ENTITY.PASSWORD]: 'security',
  [CHATBOT_ENTITY.OTP]: 'security',
  [CHATBOT_ENTITY.CARD_NUMBER]: 'financial',
  [CHATBOT_ENTITY.EXPIRY_DATE]: 'financial',
  [CHATBOT_ENTITY.CVV]: 'security',
  [CHATBOT_ENTITY.COMPANY]: 'organization',
  [CHATBOT_ENTITY.DEPARTMENT]: 'organization',
  [CHATBOT_ENTITY.ROLE]: 'organization',
  [CHATBOT_ENTITY.SKILL]: 'personal',
  [CHATBOT_ENTITY.LANGUAGE]: 'personal',
  [CHATBOT_ENTITY.COUNTRY]: 'location',
  [CHATBOT_ENTITY.CITY]: 'location',
  [CHATBOT_ENTITY.POSTAL_CODE]: 'location',
  [CHATBOT_ENTITY.IP_ADDRESS]: 'technical',
  [CHATBOT_ENTITY.MAC_ADDRESS]: 'technical',
  [CHATBOT_ENTITY.DEVICE]: 'technical',
  [CHATBOT_ENTITY.OS]: 'technical',
  [CHATBOT_ENTITY.BROWSER]: 'technical',
  [CHATBOT_ENTITY.VERSION]: 'technical',
  [CHATBOT_ENTITY.STATUS]: 'system',
  [CHATBOT_ENTITY.PRIORITY]: 'system',
  [CHATBOT_ENTITY.CATEGORY]: 'system',
  [CHATBOT_ENTITY.TAGS]: 'system',
  [CHATBOT_ENTITY.KEYWORDS]: 'system',
} as const;

/**
 * চ্যাটবট এন্টিটি গ্রুপ
 */
export const CHATBOT_ENTITY_GROUPS = {
  TEMPORAL: ['date', 'time'] as const,
  NUMERIC: ['number', 'quantity', 'percentage'] as const,
  CONTACT: ['email', 'phone'] as const,
  PERSONAL: ['name', 'username', 'skill', 'language'] as const,
  LOCATION: ['address', 'location', 'country', 'city', 'postal_code'] as const,
  IDENTIFIER: ['order_id', 'product_id'] as const,
  FINANCIAL: ['price', 'currency', 'card_number', 'expiry_date'] as const,
  SECURITY: ['password', 'otp', 'cvv'] as const,
  ORGANIZATION: ['company', 'department', 'role'] as const,
  TECHNICAL: ['ip_address', 'mac_address', 'device', 'os', 'browser', 'version'] as const,
  WEB: ['url'] as const,
  MEASUREMENT: ['unit'] as const,
  SYSTEM: ['status', 'priority', 'category', 'tags', 'keywords'] as const,
} as const;

export type ChatbotEntity = (typeof CHATBOT_ENTITY)[keyof typeof CHATBOT_ENTITY];
export type ChatbotEntityDisplayNames = typeof CHATBOT_ENTITY_DISPLAY_NAMES;
export type ChatbotEntityIcons = typeof CHATBOT_ENTITY_ICONS;
export type ChatbotEntityColors = typeof CHATBOT_ENTITY_COLORS;
export type ChatbotEntityCategories = typeof CHATBOT_ENTITY_CATEGORIES;
export type ChatbotEntityGroups = typeof CHATBOT_ENTITY_GROUPS;

export type ChatbotEntityGroup = keyof typeof CHATBOT_ENTITY_GROUPS;

export interface ChatbotEntityConfig {
  entity: ChatbotEntity;
  displayName: string;
  icon: string;
  color: string;
  category: string;
  group: ChatbotEntityGroup;
  synonyms?: string[];
  description?: string;
}

/**
 * চ্যাটবট এন্টিটি কনফিগারেশন অবজেক্ট
 */
export const CHATBOT_ENTITY_CONFIGS: Record<ChatbotEntity, ChatbotEntityConfig> = {
  [CHATBOT_ENTITY.DATE]: {
    entity: CHATBOT_ENTITY.DATE,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.DATE],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.DATE],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.DATE],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.DATE],
    group: 'TEMPORAL',
    description: 'তারিখ সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.TIME]: {
    entity: CHATBOT_ENTITY.TIME,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.TIME],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.TIME],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.TIME],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.TIME],
    group: 'TEMPORAL',
    description: 'সময় সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.NUMBER]: {
    entity: CHATBOT_ENTITY.NUMBER,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.NUMBER],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.NUMBER],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.NUMBER],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.NUMBER],
    group: 'NUMERIC',
    description: 'সংখ্যা সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.EMAIL]: {
    entity: CHATBOT_ENTITY.EMAIL,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.EMAIL],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.EMAIL],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.EMAIL],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.EMAIL],
    group: 'CONTACT',
    description: 'ইমেইল ঠিকানা সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.PHONE]: {
    entity: CHATBOT_ENTITY.PHONE,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.PHONE],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.PHONE],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.PHONE],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.PHONE],
    group: 'CONTACT',
    description: 'ফোন নম্বর সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.NAME]: {
    entity: CHATBOT_ENTITY.NAME,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.NAME],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.NAME],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.NAME],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.NAME],
    group: 'PERSONAL',
    description: 'ব্যক্তির নাম সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.ADDRESS]: {
    entity: CHATBOT_ENTITY.ADDRESS,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.ADDRESS],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.ADDRESS],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.ADDRESS],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.ADDRESS],
    group: 'LOCATION',
    description: 'ঠিকানা সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.ORDER_ID]: {
    entity: CHATBOT_ENTITY.ORDER_ID,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.ORDER_ID],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.ORDER_ID],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.ORDER_ID],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.ORDER_ID],
    group: 'IDENTIFIER',
    description: 'অর্ডার আইডি সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.PRODUCT_ID]: {
    entity: CHATBOT_ENTITY.PRODUCT_ID,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.PRODUCT_ID],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.PRODUCT_ID],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.PRODUCT_ID],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.PRODUCT_ID],
    group: 'IDENTIFIER',
    description: 'পণ্য আইডি সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.PRICE]: {
    entity: CHATBOT_ENTITY.PRICE,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.PRICE],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.PRICE],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.PRICE],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.PRICE],
    group: 'FINANCIAL',
    description: 'দাম সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.QUANTITY]: {
    entity: CHATBOT_ENTITY.QUANTITY,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.QUANTITY],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.QUANTITY],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.QUANTITY],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.QUANTITY],
    group: 'NUMERIC',
    description: 'পরিমাণ সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.LOCATION]: {
    entity: CHATBOT_ENTITY.LOCATION,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.LOCATION],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.LOCATION],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.LOCATION],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.LOCATION],
    group: 'LOCATION',
    description: 'অবস্থান সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.URL]: {
    entity: CHATBOT_ENTITY.URL,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.URL],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.URL],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.URL],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.URL],
    group: 'WEB',
    description: 'ইউআরএল সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.CURRENCY]: {
    entity: CHATBOT_ENTITY.CURRENCY,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.CURRENCY],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.CURRENCY],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.CURRENCY],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.CURRENCY],
    group: 'FINANCIAL',
    description: 'মুদ্রা সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.UNIT]: {
    entity: CHATBOT_ENTITY.UNIT,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.UNIT],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.UNIT],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.UNIT],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.UNIT],
    group: 'MEASUREMENT',
    description: 'ইউনিট সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.PERCENTAGE]: {
    entity: CHATBOT_ENTITY.PERCENTAGE,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.PERCENTAGE],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.PERCENTAGE],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.PERCENTAGE],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.PERCENTAGE],
    group: 'NUMERIC',
    description: 'শতাংশ সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.USERNAME]: {
    entity: CHATBOT_ENTITY.USERNAME,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.USERNAME],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.USERNAME],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.USERNAME],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.USERNAME],
    group: 'PERSONAL',
    description: 'ব্যবহারকারী নাম সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.PASSWORD]: {
    entity: CHATBOT_ENTITY.PASSWORD,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.PASSWORD],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.PASSWORD],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.PASSWORD],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.PASSWORD],
    group: 'SECURITY',
    description: 'পাসওয়ার্ড সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.OTP]: {
    entity: CHATBOT_ENTITY.OTP,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.OTP],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.OTP],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.OTP],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.OTP],
    group: 'SECURITY',
    description: 'ওয়ান টাইম পাসওয়ার্ড সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.CARD_NUMBER]: {
    entity: CHATBOT_ENTITY.CARD_NUMBER,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.CARD_NUMBER],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.CARD_NUMBER],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.CARD_NUMBER],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.CARD_NUMBER],
    group: 'FINANCIAL',
    description: 'কার্ড নম্বর সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.EXPIRY_DATE]: {
    entity: CHATBOT_ENTITY.EXPIRY_DATE,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.EXPIRY_DATE],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.EXPIRY_DATE],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.EXPIRY_DATE],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.EXPIRY_DATE],
    group: 'FINANCIAL',
    description: 'মেয়াদ শেষের তারিখ সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.CVV]: {
    entity: CHATBOT_ENTITY.CVV,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.CVV],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.CVV],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.CVV],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.CVV],
    group: 'SECURITY',
    description: 'সিভিভি সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.COMPANY]: {
    entity: CHATBOT_ENTITY.COMPANY,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.COMPANY],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.COMPANY],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.COMPANY],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.COMPANY],
    group: 'ORGANIZATION',
    description: 'কোম্পানি সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.DEPARTMENT]: {
    entity: CHATBOT_ENTITY.DEPARTMENT,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.DEPARTMENT],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.DEPARTMENT],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.DEPARTMENT],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.DEPARTMENT],
    group: 'ORGANIZATION',
    description: 'বিভাগ সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.ROLE]: {
    entity: CHATBOT_ENTITY.ROLE,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.ROLE],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.ROLE],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.ROLE],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.ROLE],
    group: 'ORGANIZATION',
    description: 'ভূমিকা সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.SKILL]: {
    entity: CHATBOT_ENTITY.SKILL,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.SKILL],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.SKILL],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.SKILL],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.SKILL],
    group: 'PERSONAL',
    description: 'দক্ষতা সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.LANGUAGE]: {
    entity: CHATBOT_ENTITY.LANGUAGE,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.LANGUAGE],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.LANGUAGE],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.LANGUAGE],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.LANGUAGE],
    group: 'PERSONAL',
    description: 'ভাষা সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.COUNTRY]: {
    entity: CHATBOT_ENTITY.COUNTRY,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.COUNTRY],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.COUNTRY],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.COUNTRY],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.COUNTRY],
    group: 'LOCATION',
    description: 'দেশ সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.CITY]: {
    entity: CHATBOT_ENTITY.CITY,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.CITY],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.CITY],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.CITY],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.CITY],
    group: 'LOCATION',
    description: 'শহর সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.POSTAL_CODE]: {
    entity: CHATBOT_ENTITY.POSTAL_CODE,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.POSTAL_CODE],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.POSTAL_CODE],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.POSTAL_CODE],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.POSTAL_CODE],
    group: 'LOCATION',
    description: 'পোস্টাল কোড সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.IP_ADDRESS]: {
    entity: CHATBOT_ENTITY.IP_ADDRESS,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.IP_ADDRESS],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.IP_ADDRESS],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.IP_ADDRESS],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.IP_ADDRESS],
    group: 'TECHNICAL',
    description: 'আইপি ঠিকানা সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.MAC_ADDRESS]: {
    entity: CHATBOT_ENTITY.MAC_ADDRESS,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.MAC_ADDRESS],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.MAC_ADDRESS],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.MAC_ADDRESS],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.MAC_ADDRESS],
    group: 'TECHNICAL',
    description: 'ম্যাক ঠিকানা সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.DEVICE]: {
    entity: CHATBOT_ENTITY.DEVICE,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.DEVICE],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.DEVICE],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.DEVICE],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.DEVICE],
    group: 'TECHNICAL',
    description: 'ডিভাইস সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.OS]: {
    entity: CHATBOT_ENTITY.OS,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.OS],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.OS],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.OS],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.OS],
    group: 'TECHNICAL',
    description: 'অপারেটিং সিস্টেম সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.BROWSER]: {
    entity: CHATBOT_ENTITY.BROWSER,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.BROWSER],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.BROWSER],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.BROWSER],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.BROWSER],
    group: 'TECHNICAL',
    description: 'ব্রাউজার সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.VERSION]: {
    entity: CHATBOT_ENTITY.VERSION,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.VERSION],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.VERSION],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.VERSION],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.VERSION],
    group: 'TECHNICAL',
    description: 'সংস্করণ সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.STATUS]: {
    entity: CHATBOT_ENTITY.STATUS,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.STATUS],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.STATUS],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.STATUS],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.STATUS],
    group: 'SYSTEM',
    description: 'স্ট্যাটাস সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.PRIORITY]: {
    entity: CHATBOT_ENTITY.PRIORITY,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.PRIORITY],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.PRIORITY],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.PRIORITY],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.PRIORITY],
    group: 'SYSTEM',
    description: 'প্রায়োরিটি সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.CATEGORY]: {
    entity: CHATBOT_ENTITY.CATEGORY,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.CATEGORY],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.CATEGORY],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.CATEGORY],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.CATEGORY],
    group: 'SYSTEM',
    description: 'ক্যাটাগরি সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.TAGS]: {
    entity: CHATBOT_ENTITY.TAGS,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.TAGS],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.TAGS],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.TAGS],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.TAGS],
    group: 'SYSTEM',
    description: 'ট্যাগ সম্পর্কিত এন্টিটি',
  },
  [CHATBOT_ENTITY.KEYWORDS]: {
    entity: CHATBOT_ENTITY.KEYWORDS,
    displayName: CHATBOT_ENTITY_DISPLAY_NAMES[CHATBOT_ENTITY.KEYWORDS],
    icon: CHATBOT_ENTITY_ICONS[CHATBOT_ENTITY.KEYWORDS],
    color: CHATBOT_ENTITY_COLORS[CHATBOT_ENTITY.KEYWORDS],
    category: CHATBOT_ENTITY_CATEGORIES[CHATBOT_ENTITY.KEYWORDS],
    group: 'SYSTEM',
    description: 'কীওয়ার্ড সম্পর্কিত এন্টিটি',
  },
};

/**
 * চ্যাটবট এন্টিটি গ্রুপ কনফিগারেশন
 */
export const CHATBOT_ENTITY_GROUP_CONFIGS: Record<
  ChatbotEntityGroup,
  {
    group: ChatbotEntityGroup;
    displayName: string;
    icon: string;
    color: string;
    entities: readonly ChatbotEntity[];
    description?: string;
  }
> = {
  TEMPORAL: {
    group: 'TEMPORAL',
    displayName: 'সময় সংক্রান্ত',
    icon: 'calendar',
    color: '#3498db',
    entities: ['date', 'time'] as const,
    description: 'তারিখ ও সময় সম্পর্কিত এন্টিটি',
  },
  NUMERIC: {
    group: 'NUMERIC',
    displayName: 'সংখ্যা সংক্রান্ত',
    icon: 'hash',
    color: '#f39c12',
    entities: ['number', 'quantity', 'percentage'] as const,
    description: 'সংখ্যা, পরিমাণ ও শতাংশ সম্পর্কিত এন্টিটি',
  },
  CONTACT: {
    group: 'CONTACT',
    displayName: 'যোগাযোগ সংক্রান্ত',
    icon: 'mail',
    color: '#e74c3c',
    entities: ['email', 'phone'] as const,
    description: 'ইমেইল ও ফোন নম্বর সম্পর্কিত এন্টিটি',
  },
  PERSONAL: {
    group: 'PERSONAL',
    displayName: 'ব্যক্তিগত',
    icon: 'user',
    color: '#1abc9c',
    entities: ['name', 'username', 'skill', 'language'] as const,
    description: 'ব্যক্তিগত তথ্য সম্পর্কিত এন্টিটি',
  },
  LOCATION: {
    group: 'LOCATION',
    displayName: 'অবস্থান সংক্রান্ত',
    icon: 'map-pin',
    color: '#e67e22',
    entities: ['address', 'location', 'country', 'city', 'postal_code'] as const,
    description: 'ঠিকানা ও অবস্থান সম্পর্কিত এন্টিটি',
  },
  IDENTIFIER: {
    group: 'IDENTIFIER',
    displayName: 'আইডি সংক্রান্ত',
    icon: 'hash',
    color: '#2980b9',
    entities: ['order_id', 'product_id'] as const,
    description: 'অর্ডার ও পণ্য আইডি সম্পর্কিত এন্টিটি',
  },
  FINANCIAL: {
    group: 'FINANCIAL',
    displayName: 'আর্থিক',
    icon: 'dollar-sign',
    color: '#27ae60',
    entities: ['price', 'currency', 'card_number', 'expiry_date'] as const,
    description: 'আর্থিক তথ্য সম্পর্কিত এন্টিটি',
  },
  SECURITY: {
    group: 'SECURITY',
    displayName: 'সিকিউরিটি',
    icon: 'shield',
    color: '#c0392b',
    entities: ['password', 'otp', 'cvv'] as const,
    description: 'সিকিউরিটি সম্পর্কিত এন্টিটি',
  },
  ORGANIZATION: {
    group: 'ORGANIZATION',
    displayName: 'প্রতিষ্ঠান',
    icon: 'building',
    color: '#2c3e50',
    entities: ['company', 'department', 'role'] as const,
    description: 'প্রতিষ্ঠান ও ভূমিকা সম্পর্কিত এন্টিটি',
  },
  TECHNICAL: {
    group: 'TECHNICAL',
    displayName: 'প্রযুক্তিগত',
    icon: 'cpu',
    color: '#e74c3c',
    entities: ['ip_address', 'mac_address', 'device', 'os', 'browser', 'version'] as const,
    description: 'প্রযুক্তিগত তথ্য সম্পর্কিত এন্টিটি',
  },
  WEB: {
    group: 'WEB',
    displayName: 'ওয়েব',
    icon: 'globe',
    color: '#3498db',
    entities: ['url'] as const,
    description: 'ওয়েব সম্পর্কিত এন্টিটি',
  },
  MEASUREMENT: {
    group: 'MEASUREMENT',
    displayName: 'পরিমাপ',
    icon: 'ruler',
    color: '#95a5a6',
    entities: ['unit'] as const,
    description: 'পরিমাপের ইউনিট সম্পর্কিত এন্টিটি',
  },
  SYSTEM: {
    group: 'SYSTEM',
    displayName: 'সিস্টেম',
    icon: 'settings',
    color: '#7f8c8d',
    entities: ['status', 'priority', 'category', 'tags', 'keywords'] as const,
    description: 'সিস্টেম সম্পর্কিত এন্টিটি',
  },
};

/**
 * চ্যাটবট এন্টিটি স্ট্যাটাস
 */
export const CHATBOT_ENTITY_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  TRAINING: 'training',
  DEPRECATED: 'deprecated',
} as const;

export type ChatbotEntityStatus =
  (typeof CHATBOT_ENTITY_STATUS)[keyof typeof CHATBOT_ENTITY_STATUS];
