/**
 * কনভারসেশনের বিভিন্ন স্ট্যাটাস সংক্রান্ত কনস্ট্যান্টসমূহ
 */

/**
 * কনভারসেশন স্ট্যাটাস
 */
export const CONVERSATION_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  ARCHIVED: 'archived',
  CLOSED: 'closed',
  WAITING: 'waiting',
  TRANSFERRED: 'transferred',
  RESOLVED: 'resolved',
  PENDING: 'pending',
  ON_HOLD: 'on_hold',
  ESCALATED: 'escalated',
  REOPENED: 'reopened',
  LOCKED: 'locked',
  DELETED: 'deleted',
} as const;

/**
 * কনভারসেশন স্ট্যাটাসের ডিসপ্লে নাম
 */
export const CONVERSATION_STATUS_DISPLAY_NAMES = {
  [CONVERSATION_STATUS.ACTIVE]: 'সক্রিয়',
  [CONVERSATION_STATUS.INACTIVE]: 'নিষ্ক্রিয়',
  [CONVERSATION_STATUS.ARCHIVED]: 'আর্কাইভকৃত',
  [CONVERSATION_STATUS.CLOSED]: 'বন্ধ',
  [CONVERSATION_STATUS.WAITING]: 'অপেক্ষমান',
  [CONVERSATION_STATUS.TRANSFERRED]: 'স্থানান্তরিত',
  [CONVERSATION_STATUS.RESOLVED]: 'সমাধানকৃত',
  [CONVERSATION_STATUS.PENDING]: 'মুলতুবি',
  [CONVERSATION_STATUS.ON_HOLD]: 'হোল্ডে',
  [CONVERSATION_STATUS.ESCALATED]: 'এস্কেলেটেড',
  [CONVERSATION_STATUS.REOPENED]: 'পুনরায় খোলা',
  [CONVERSATION_STATUS.LOCKED]: 'লকড',
  [CONVERSATION_STATUS.DELETED]: 'ডিলিটেড',
} as const;

/**
 * কনভারসেশন স্ট্যাটাসের রঙের কোড (হেক্স)
 */
export const CONVERSATION_STATUS_COLORS = {
  [CONVERSATION_STATUS.ACTIVE]: '#2ecc71',
  [CONVERSATION_STATUS.INACTIVE]: '#95a5a6',
  [CONVERSATION_STATUS.ARCHIVED]: '#7f8c8d',
  [CONVERSATION_STATUS.CLOSED]: '#34495e',
  [CONVERSATION_STATUS.WAITING]: '#f39c12',
  [CONVERSATION_STATUS.TRANSFERRED]: '#9b59b6',
  [CONVERSATION_STATUS.RESOLVED]: '#27ae60',
  [CONVERSATION_STATUS.PENDING]: '#e67e22',
  [CONVERSATION_STATUS.ON_HOLD]: '#f1c40f',
  [CONVERSATION_STATUS.ESCALATED]: '#e74c3c',
  [CONVERSATION_STATUS.REOPENED]: '#e74c3c',
  [CONVERSATION_STATUS.LOCKED]: '#c0392b',
  [CONVERSATION_STATUS.DELETED]: '#2c3e50',
} as const;

/**
 * কনভারসেশন স্ট্যাটাসের আইকন (অনুষঙ্গিক নাম)
 */
export const CONVERSATION_STATUS_ICONS = {
  [CONVERSATION_STATUS.ACTIVE]: 'check-circle',
  [CONVERSATION_STATUS.INACTIVE]: 'minus-circle',
  [CONVERSATION_STATUS.ARCHIVED]: 'archive',
  [CONVERSATION_STATUS.CLOSED]: 'x-circle',
  [CONVERSATION_STATUS.WAITING]: 'clock',
  [CONVERSATION_STATUS.TRANSFERRED]: 'arrow-right-circle',
  [CONVERSATION_STATUS.RESOLVED]: 'check-circle',
  [CONVERSATION_STATUS.PENDING]: 'alert-circle',
  [CONVERSATION_STATUS.ON_HOLD]: 'pause-circle',
  [CONVERSATION_STATUS.ESCALATED]: 'alert-triangle',
  [CONVERSATION_STATUS.REOPENED]: 'refresh-cw',
  [CONVERSATION_STATUS.LOCKED]: 'lock',
  [CONVERSATION_STATUS.DELETED]: 'trash-2',
} as const;

/**
 * কনভারসেশন স্ট্যাটাসের বিবরণ
 */
export const CONVERSATION_STATUS_DESCRIPTIONS = {
  [CONVERSATION_STATUS.ACTIVE]: 'কনভারসেশন সক্রিয় এবং চলমান',
  [CONVERSATION_STATUS.INACTIVE]: 'কনভারসেশন নিষ্ক্রিয় কিন্তু এখনও উপলব্ধ',
  [CONVERSATION_STATUS.ARCHIVED]: 'কনভারসেশন আর্কাইভ করা হয়েছে',
  [CONVERSATION_STATUS.CLOSED]: 'কনভারসেশন বন্ধ করা হয়েছে',
  [CONVERSATION_STATUS.WAITING]: 'কনভারসেশন ব্যবহারকারীর প্রতিক্রিয়ার জন্য অপেক্ষা করছে',
  [CONVERSATION_STATUS.TRANSFERRED]: 'কনভারসেশন অন্য এজেন্টে স্থানান্তরিত হয়েছে',
  [CONVERSATION_STATUS.RESOLVED]: 'কনভারসেশন সমাধান করা হয়েছে',
  [CONVERSATION_STATUS.PENDING]: 'কনভারসেশন প্রক্রিয়াকরণের অপেক্ষায়',
  [CONVERSATION_STATUS.ON_HOLD]: 'কনভারসেশন সাময়িকভাবে হোল্ডে রাখা হয়েছে',
  [CONVERSATION_STATUS.ESCALATED]: 'কনভারসেশন উচ্চতর স্তরে পাঠানো হয়েছে',
  [CONVERSATION_STATUS.REOPENED]: 'কনভারসেশন পুনরায় খোলা হয়েছে',
  [CONVERSATION_STATUS.LOCKED]: 'কনভারসেশন লক করা হয়েছে (শুধুমাত্র পড়ার যোগ্য)',
  [CONVERSATION_STATUS.DELETED]: 'কনভারসেশন মুছে ফেলা হয়েছে',
} as const;

/**
 * কনভারসেশন স্ট্যাটাস গ্রুপ
 */
export const CONVERSATION_STATUS_GROUPS = {
  OPEN: ['active', 'waiting', 'pending', 'transferred', 'escalated'] as const,
  RESOLVED: ['resolved', 'closed', 'reopened'] as const,
  PAUSED: ['on_hold', 'inactive', 'locked'] as const,
  CLOSED: ['archived', 'deleted', 'closed'] as const,
} as const;

/**
 * কনভারসেশন স্ট্যাটাস ট্রানজিশন রুলস
 */
export const CONVERSATION_STATUS_TRANSITIONS = {
  [CONVERSATION_STATUS.ACTIVE]: [
    'inactive',
    'archived',
    'closed',
    'waiting',
    'transferred',
    'pending',
    'on_hold',
    'escalated',
    'locked',
  ] as const,
  [CONVERSATION_STATUS.INACTIVE]: ['active', 'archived', 'closed', 'deleted'] as const,
  [CONVERSATION_STATUS.ARCHIVED]: ['active', 'deleted'] as const,
  [CONVERSATION_STATUS.CLOSED]: ['reopened', 'archived'] as const,
  [CONVERSATION_STATUS.WAITING]: ['active', 'closed', 'transferred', 'escalated'] as const,
  [CONVERSATION_STATUS.TRANSFERRED]: ['active', 'waiting', 'pending', 'closed'] as const,
  [CONVERSATION_STATUS.RESOLVED]: ['closed', 'reopened', 'archived'] as const,
  [CONVERSATION_STATUS.PENDING]: ['active', 'waiting', 'transferred', 'closed'] as const,
  [CONVERSATION_STATUS.ON_HOLD]: ['active', 'waiting', 'transferred', 'closed'] as const,
  [CONVERSATION_STATUS.ESCALATED]: ['active', 'transferred', 'closed'] as const,
  [CONVERSATION_STATUS.REOPENED]: [
    'active',
    'waiting',
    'pending',
    'on_hold',
    'resolved',
    'closed',
  ] as const,
  [CONVERSATION_STATUS.LOCKED]: ['active', 'inactive', 'archived'] as const,
  [CONVERSATION_STATUS.DELETED]: [] as const,
} as const;

/**
 * কনভারসেশন স্ট্যাটাসের সময়সীমা (ঘন্টায়)
 */
export const CONVERSATION_STATUS_TIME_LIMITS = {
  [CONVERSATION_STATUS.ACTIVE]: 48,
  [CONVERSATION_STATUS.INACTIVE]: 168,
  [CONVERSATION_STATUS.ARCHIVED]: 0,
  [CONVERSATION_STATUS.CLOSED]: 0,
  [CONVERSATION_STATUS.WAITING]: 24,
  [CONVERSATION_STATUS.TRANSFERRED]: 12,
  [CONVERSATION_STATUS.RESOLVED]: 72,
  [CONVERSATION_STATUS.PENDING]: 4,
  [CONVERSATION_STATUS.ON_HOLD]: 168,
  [CONVERSATION_STATUS.ESCALATED]: 12,
  [CONVERSATION_STATUS.REOPENED]: 48,
  [CONVERSATION_STATUS.LOCKED]: 0,
  [CONVERSATION_STATUS.DELETED]: 0,
} as const;

/**
 * কনভারসেশন স্ট্যাটাসের অটো-ট্রানজিশন
 */
export const CONVERSATION_STATUS_AUTO_TRANSITIONS = {
  [CONVERSATION_STATUS.ACTIVE]: {
    after: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.ACTIVE],
    to: CONVERSATION_STATUS.INACTIVE,
  },
  [CONVERSATION_STATUS.WAITING]: {
    after: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.WAITING],
    to: CONVERSATION_STATUS.INACTIVE,
  },
  [CONVERSATION_STATUS.PENDING]: {
    after: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.PENDING],
    to: CONVERSATION_STATUS.ESCALATED,
  },
  [CONVERSATION_STATUS.ON_HOLD]: {
    after: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.ON_HOLD],
    to: CONVERSATION_STATUS.ARCHIVED,
  },
  [CONVERSATION_STATUS.RESOLVED]: {
    after: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.RESOLVED],
    to: CONVERSATION_STATUS.CLOSED,
  },
} as const;

/**
 * কনভারসেশন স্ট্যাটাসের নোটিফিকেশন সেটিংস (মিউটেবল অ্যারে হিসেবে)
 */
export const CONVERSATION_STATUS_NOTIFICATIONS = {
  [CONVERSATION_STATUS.ACTIVE]: {
    enabled: true,
    channels: ['email', 'push', 'slack'] as string[],
    template: 'conversation_active',
  },
  [CONVERSATION_STATUS.INACTIVE]: {
    enabled: false,
    channels: [] as string[],
    template: '',
  },
  [CONVERSATION_STATUS.ARCHIVED]: {
    enabled: false,
    channels: [] as string[],
    template: '',
  },
  [CONVERSATION_STATUS.CLOSED]: {
    enabled: true,
    channels: ['email', 'push'] as string[],
    template: 'conversation_closed',
  },
  [CONVERSATION_STATUS.WAITING]: {
    enabled: true,
    channels: ['email', 'push'] as string[],
    template: 'conversation_waiting',
  },
  [CONVERSATION_STATUS.TRANSFERRED]: {
    enabled: true,
    channels: ['email', 'push', 'slack'] as string[],
    template: 'conversation_transferred',
  },
  [CONVERSATION_STATUS.RESOLVED]: {
    enabled: true,
    channels: ['email', 'push'] as string[],
    template: 'conversation_resolved',
  },
  [CONVERSATION_STATUS.PENDING]: {
    enabled: true,
    channels: ['email', 'slack'] as string[],
    template: 'conversation_pending',
  },
  [CONVERSATION_STATUS.ON_HOLD]: {
    enabled: true,
    channels: ['email', 'push'] as string[],
    template: 'conversation_on_hold',
  },
  [CONVERSATION_STATUS.ESCALATED]: {
    enabled: true,
    channels: ['email', 'push', 'slack'] as string[],
    template: 'conversation_escalated',
  },
  [CONVERSATION_STATUS.REOPENED]: {
    enabled: true,
    channels: ['email', 'push', 'slack'] as string[],
    template: 'conversation_reopened',
  },
  [CONVERSATION_STATUS.LOCKED]: {
    enabled: true,
    channels: ['email'] as string[],
    template: 'conversation_locked',
  },
  [CONVERSATION_STATUS.DELETED]: {
    enabled: false,
    channels: [] as string[],
    template: '',
  },
} as const;

/**
 * কনভারসেশন স্ট্যাটাসের ডিফল্ট অ্যাকশন
 */
export const CONVERSATION_STATUS_DEFAULT_ACTIONS = {
  [CONVERSATION_STATUS.ACTIVE]: 'কনভারসেশন সক্রিয়, প্রতিক্রিয়া জানান',
  [CONVERSATION_STATUS.INACTIVE]: 'কনভারসেশন নিষ্ক্রিয়, প্রয়োজন হলে পুনরায় সক্রিয় করুন',
  [CONVERSATION_STATUS.ARCHIVED]: 'কনভারসেশন আর্কাইভ করা হয়েছে, প্রয়োজনে পুনরুদ্ধার করুন',
  [CONVERSATION_STATUS.CLOSED]: 'কনভারসেশন বন্ধ, প্রয়োজনে পুনরায় খুলুন',
  [CONVERSATION_STATUS.WAITING]: 'গ্রাহকের প্রতিক্রিয়ার জন্য অপেক্ষা করছে',
  [CONVERSATION_STATUS.TRANSFERRED]: 'কনভারসেশন স্থানান্তরিত, নতুন এজেন্ট মনিটর করুন',
  [CONVERSATION_STATUS.RESOLVED]: 'সমাধান করা হয়েছে, গ্রাহক নোটিফাই করুন',
  [CONVERSATION_STATUS.PENDING]: 'প্রক্রিয়াকরণের অপেক্ষায়, মনিটর করুন',
  [CONVERSATION_STATUS.ON_HOLD]: 'হোল্ডে রাখা হয়েছে, প্রয়োজনীয় তথ্য সংগ্রহ করুন',
  [CONVERSATION_STATUS.ESCALATED]: 'এস্কেলেটেড, মনিটর করুন',
  [CONVERSATION_STATUS.REOPENED]: 'পুনরায় খোলা হয়েছে, পর্যালোচনা করুন',
  [CONVERSATION_STATUS.LOCKED]: 'লক করা হয়েছে, শুধুমাত্র পড়ার যোগ্য',
  [CONVERSATION_STATUS.DELETED]: 'মুছে ফেলা হয়েছে, পুনরুদ্ধার সম্ভব নয়',
} as const;

/**
 * কনভারসেশন স্ট্যাটাসের ওয়ার্কফ্লো অর্ডার
 */
export const CONVERSATION_STATUS_WORKFLOW_ORDER = [
  CONVERSATION_STATUS.ACTIVE,
  CONVERSATION_STATUS.PENDING,
  CONVERSATION_STATUS.WAITING,
  CONVERSATION_STATUS.ON_HOLD,
  CONVERSATION_STATUS.TRANSFERRED,
  CONVERSATION_STATUS.ESCALATED,
  CONVERSATION_STATUS.RESOLVED,
  CONVERSATION_STATUS.REOPENED,
  CONVERSATION_STATUS.CLOSED,
  CONVERSATION_STATUS.INACTIVE,
  CONVERSATION_STATUS.ARCHIVED,
  CONVERSATION_STATUS.LOCKED,
  CONVERSATION_STATUS.DELETED,
] as const;

export type ConversationStatus = (typeof CONVERSATION_STATUS)[keyof typeof CONVERSATION_STATUS];
export type ConversationStatusDisplayNames = typeof CONVERSATION_STATUS_DISPLAY_NAMES;
export type ConversationStatusColors = typeof CONVERSATION_STATUS_COLORS;
export type ConversationStatusIcons = typeof CONVERSATION_STATUS_ICONS;
export type ConversationStatusDescriptions = typeof CONVERSATION_STATUS_DESCRIPTIONS;
export type ConversationStatusGroups = typeof CONVERSATION_STATUS_GROUPS;
export type ConversationStatusTransitions = typeof CONVERSATION_STATUS_TRANSITIONS;
export type ConversationStatusTimeLimits = typeof CONVERSATION_STATUS_TIME_LIMITS;
export type ConversationStatusAutoTransitions = typeof CONVERSATION_STATUS_AUTO_TRANSITIONS;
export type ConversationStatusNotifications = typeof CONVERSATION_STATUS_NOTIFICATIONS;
export type ConversationStatusDefaultActions = typeof CONVERSATION_STATUS_DEFAULT_ACTIONS;
export type ConversationStatusWorkflowOrder = typeof CONVERSATION_STATUS_WORKFLOW_ORDER;

export interface ConversationStatusConfig {
  status: ConversationStatus;
  displayName: string;
  color: string;
  icon: string;
  description: string;
  timeLimitHours: number;
  defaultAction: string;
  notification: {
    enabled: boolean;
    channels: string[];
    template: string;
  };
  autoTransition?: {
    after: number;
    to: ConversationStatus;
  };
}

/**
 * কনভারসেশন স্ট্যাটাস কনফিগারেশন অবজেক্ট
 */
export const CONVERSATION_STATUS_CONFIGS: Record<ConversationStatus, ConversationStatusConfig> = {
  [CONVERSATION_STATUS.ACTIVE]: {
    status: CONVERSATION_STATUS.ACTIVE,
    displayName: CONVERSATION_STATUS_DISPLAY_NAMES[CONVERSATION_STATUS.ACTIVE],
    color: CONVERSATION_STATUS_COLORS[CONVERSATION_STATUS.ACTIVE],
    icon: CONVERSATION_STATUS_ICONS[CONVERSATION_STATUS.ACTIVE],
    description: CONVERSATION_STATUS_DESCRIPTIONS[CONVERSATION_STATUS.ACTIVE],
    timeLimitHours: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.ACTIVE],
    defaultAction: CONVERSATION_STATUS_DEFAULT_ACTIONS[CONVERSATION_STATUS.ACTIVE],
    notification: CONVERSATION_STATUS_NOTIFICATIONS[CONVERSATION_STATUS.ACTIVE],
    autoTransition: CONVERSATION_STATUS_AUTO_TRANSITIONS[CONVERSATION_STATUS.ACTIVE],
  },
  [CONVERSATION_STATUS.INACTIVE]: {
    status: CONVERSATION_STATUS.INACTIVE,
    displayName: CONVERSATION_STATUS_DISPLAY_NAMES[CONVERSATION_STATUS.INACTIVE],
    color: CONVERSATION_STATUS_COLORS[CONVERSATION_STATUS.INACTIVE],
    icon: CONVERSATION_STATUS_ICONS[CONVERSATION_STATUS.INACTIVE],
    description: CONVERSATION_STATUS_DESCRIPTIONS[CONVERSATION_STATUS.INACTIVE],
    timeLimitHours: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.INACTIVE],
    defaultAction: CONVERSATION_STATUS_DEFAULT_ACTIONS[CONVERSATION_STATUS.INACTIVE],
    notification: CONVERSATION_STATUS_NOTIFICATIONS[CONVERSATION_STATUS.INACTIVE],
  },
  [CONVERSATION_STATUS.ARCHIVED]: {
    status: CONVERSATION_STATUS.ARCHIVED,
    displayName: CONVERSATION_STATUS_DISPLAY_NAMES[CONVERSATION_STATUS.ARCHIVED],
    color: CONVERSATION_STATUS_COLORS[CONVERSATION_STATUS.ARCHIVED],
    icon: CONVERSATION_STATUS_ICONS[CONVERSATION_STATUS.ARCHIVED],
    description: CONVERSATION_STATUS_DESCRIPTIONS[CONVERSATION_STATUS.ARCHIVED],
    timeLimitHours: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.ARCHIVED],
    defaultAction: CONVERSATION_STATUS_DEFAULT_ACTIONS[CONVERSATION_STATUS.ARCHIVED],
    notification: CONVERSATION_STATUS_NOTIFICATIONS[CONVERSATION_STATUS.ARCHIVED],
  },
  [CONVERSATION_STATUS.CLOSED]: {
    status: CONVERSATION_STATUS.CLOSED,
    displayName: CONVERSATION_STATUS_DISPLAY_NAMES[CONVERSATION_STATUS.CLOSED],
    color: CONVERSATION_STATUS_COLORS[CONVERSATION_STATUS.CLOSED],
    icon: CONVERSATION_STATUS_ICONS[CONVERSATION_STATUS.CLOSED],
    description: CONVERSATION_STATUS_DESCRIPTIONS[CONVERSATION_STATUS.CLOSED],
    timeLimitHours: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.CLOSED],
    defaultAction: CONVERSATION_STATUS_DEFAULT_ACTIONS[CONVERSATION_STATUS.CLOSED],
    notification: CONVERSATION_STATUS_NOTIFICATIONS[CONVERSATION_STATUS.CLOSED],
  },
  [CONVERSATION_STATUS.WAITING]: {
    status: CONVERSATION_STATUS.WAITING,
    displayName: CONVERSATION_STATUS_DISPLAY_NAMES[CONVERSATION_STATUS.WAITING],
    color: CONVERSATION_STATUS_COLORS[CONVERSATION_STATUS.WAITING],
    icon: CONVERSATION_STATUS_ICONS[CONVERSATION_STATUS.WAITING],
    description: CONVERSATION_STATUS_DESCRIPTIONS[CONVERSATION_STATUS.WAITING],
    timeLimitHours: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.WAITING],
    defaultAction: CONVERSATION_STATUS_DEFAULT_ACTIONS[CONVERSATION_STATUS.WAITING],
    notification: CONVERSATION_STATUS_NOTIFICATIONS[CONVERSATION_STATUS.WAITING],
    autoTransition: CONVERSATION_STATUS_AUTO_TRANSITIONS[CONVERSATION_STATUS.WAITING],
  },
  [CONVERSATION_STATUS.TRANSFERRED]: {
    status: CONVERSATION_STATUS.TRANSFERRED,
    displayName: CONVERSATION_STATUS_DISPLAY_NAMES[CONVERSATION_STATUS.TRANSFERRED],
    color: CONVERSATION_STATUS_COLORS[CONVERSATION_STATUS.TRANSFERRED],
    icon: CONVERSATION_STATUS_ICONS[CONVERSATION_STATUS.TRANSFERRED],
    description: CONVERSATION_STATUS_DESCRIPTIONS[CONVERSATION_STATUS.TRANSFERRED],
    timeLimitHours: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.TRANSFERRED],
    defaultAction: CONVERSATION_STATUS_DEFAULT_ACTIONS[CONVERSATION_STATUS.TRANSFERRED],
    notification: CONVERSATION_STATUS_NOTIFICATIONS[CONVERSATION_STATUS.TRANSFERRED],
  },
  [CONVERSATION_STATUS.RESOLVED]: {
    status: CONVERSATION_STATUS.RESOLVED,
    displayName: CONVERSATION_STATUS_DISPLAY_NAMES[CONVERSATION_STATUS.RESOLVED],
    color: CONVERSATION_STATUS_COLORS[CONVERSATION_STATUS.RESOLVED],
    icon: CONVERSATION_STATUS_ICONS[CONVERSATION_STATUS.RESOLVED],
    description: CONVERSATION_STATUS_DESCRIPTIONS[CONVERSATION_STATUS.RESOLVED],
    timeLimitHours: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.RESOLVED],
    defaultAction: CONVERSATION_STATUS_DEFAULT_ACTIONS[CONVERSATION_STATUS.RESOLVED],
    notification: CONVERSATION_STATUS_NOTIFICATIONS[CONVERSATION_STATUS.RESOLVED],
    autoTransition: CONVERSATION_STATUS_AUTO_TRANSITIONS[CONVERSATION_STATUS.RESOLVED],
  },
  [CONVERSATION_STATUS.PENDING]: {
    status: CONVERSATION_STATUS.PENDING,
    displayName: CONVERSATION_STATUS_DISPLAY_NAMES[CONVERSATION_STATUS.PENDING],
    color: CONVERSATION_STATUS_COLORS[CONVERSATION_STATUS.PENDING],
    icon: CONVERSATION_STATUS_ICONS[CONVERSATION_STATUS.PENDING],
    description: CONVERSATION_STATUS_DESCRIPTIONS[CONVERSATION_STATUS.PENDING],
    timeLimitHours: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.PENDING],
    defaultAction: CONVERSATION_STATUS_DEFAULT_ACTIONS[CONVERSATION_STATUS.PENDING],
    notification: CONVERSATION_STATUS_NOTIFICATIONS[CONVERSATION_STATUS.PENDING],
    autoTransition: CONVERSATION_STATUS_AUTO_TRANSITIONS[CONVERSATION_STATUS.PENDING],
  },
  [CONVERSATION_STATUS.ON_HOLD]: {
    status: CONVERSATION_STATUS.ON_HOLD,
    displayName: CONVERSATION_STATUS_DISPLAY_NAMES[CONVERSATION_STATUS.ON_HOLD],
    color: CONVERSATION_STATUS_COLORS[CONVERSATION_STATUS.ON_HOLD],
    icon: CONVERSATION_STATUS_ICONS[CONVERSATION_STATUS.ON_HOLD],
    description: CONVERSATION_STATUS_DESCRIPTIONS[CONVERSATION_STATUS.ON_HOLD],
    timeLimitHours: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.ON_HOLD],
    defaultAction: CONVERSATION_STATUS_DEFAULT_ACTIONS[CONVERSATION_STATUS.ON_HOLD],
    notification: CONVERSATION_STATUS_NOTIFICATIONS[CONVERSATION_STATUS.ON_HOLD],
    autoTransition: CONVERSATION_STATUS_AUTO_TRANSITIONS[CONVERSATION_STATUS.ON_HOLD],
  },
  [CONVERSATION_STATUS.ESCALATED]: {
    status: CONVERSATION_STATUS.ESCALATED,
    displayName: CONVERSATION_STATUS_DISPLAY_NAMES[CONVERSATION_STATUS.ESCALATED],
    color: CONVERSATION_STATUS_COLORS[CONVERSATION_STATUS.ESCALATED],
    icon: CONVERSATION_STATUS_ICONS[CONVERSATION_STATUS.ESCALATED],
    description: CONVERSATION_STATUS_DESCRIPTIONS[CONVERSATION_STATUS.ESCALATED],
    timeLimitHours: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.ESCALATED],
    defaultAction: CONVERSATION_STATUS_DEFAULT_ACTIONS[CONVERSATION_STATUS.ESCALATED],
    notification: CONVERSATION_STATUS_NOTIFICATIONS[CONVERSATION_STATUS.ESCALATED],
  },
  [CONVERSATION_STATUS.REOPENED]: {
    status: CONVERSATION_STATUS.REOPENED,
    displayName: CONVERSATION_STATUS_DISPLAY_NAMES[CONVERSATION_STATUS.REOPENED],
    color: CONVERSATION_STATUS_COLORS[CONVERSATION_STATUS.REOPENED],
    icon: CONVERSATION_STATUS_ICONS[CONVERSATION_STATUS.REOPENED],
    description: CONVERSATION_STATUS_DESCRIPTIONS[CONVERSATION_STATUS.REOPENED],
    timeLimitHours: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.REOPENED],
    defaultAction: CONVERSATION_STATUS_DEFAULT_ACTIONS[CONVERSATION_STATUS.REOPENED],
    notification: CONVERSATION_STATUS_NOTIFICATIONS[CONVERSATION_STATUS.REOPENED],
  },
  [CONVERSATION_STATUS.LOCKED]: {
    status: CONVERSATION_STATUS.LOCKED,
    displayName: CONVERSATION_STATUS_DISPLAY_NAMES[CONVERSATION_STATUS.LOCKED],
    color: CONVERSATION_STATUS_COLORS[CONVERSATION_STATUS.LOCKED],
    icon: CONVERSATION_STATUS_ICONS[CONVERSATION_STATUS.LOCKED],
    description: CONVERSATION_STATUS_DESCRIPTIONS[CONVERSATION_STATUS.LOCKED],
    timeLimitHours: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.LOCKED],
    defaultAction: CONVERSATION_STATUS_DEFAULT_ACTIONS[CONVERSATION_STATUS.LOCKED],
    notification: CONVERSATION_STATUS_NOTIFICATIONS[CONVERSATION_STATUS.LOCKED],
  },
  [CONVERSATION_STATUS.DELETED]: {
    status: CONVERSATION_STATUS.DELETED,
    displayName: CONVERSATION_STATUS_DISPLAY_NAMES[CONVERSATION_STATUS.DELETED],
    color: CONVERSATION_STATUS_COLORS[CONVERSATION_STATUS.DELETED],
    icon: CONVERSATION_STATUS_ICONS[CONVERSATION_STATUS.DELETED],
    description: CONVERSATION_STATUS_DESCRIPTIONS[CONVERSATION_STATUS.DELETED],
    timeLimitHours: CONVERSATION_STATUS_TIME_LIMITS[CONVERSATION_STATUS.DELETED],
    defaultAction: CONVERSATION_STATUS_DEFAULT_ACTIONS[CONVERSATION_STATUS.DELETED],
    notification: CONVERSATION_STATUS_NOTIFICATIONS[CONVERSATION_STATUS.DELETED],
  },
};
