/**
 * মেসেজের বিভিন্ন ডেলিভারি স্ট্যাটাস সংক্রান্ত কনস্ট্যান্টসমূহ
 */

/**
 * মেসেজ স্ট্যাটাস
 */
export const MESSAGE_STATUS = {
  SENT: 'sent',
  DELIVERED: 'delivered',
  READ: 'read',
  FAILED: 'failed',
  PENDING: 'pending',
  RETRY: 'retry',
  BLOCKED: 'blocked',
  SPAM: 'spam',
  DELETED: 'deleted',
  REJECTED: 'rejected',
  RECEIVED: 'received',
  SEEN: 'seen',
  PLAYED: 'played',
  EXPIRED: 'expired',
  SCHEDULED: 'scheduled',
  DRAFT: 'draft',
  ARCHIVED: 'archived',
  BOUNCED: 'bounced',
  UNSUBSCRIBED: 'unsubscribed',
  FILTERED: 'filtered',
} as const;

/**
 * মেসেজ স্ট্যাটাসের ডিসপ্লে নাম
 */
export const MESSAGE_STATUS_DISPLAY_NAMES = {
  [MESSAGE_STATUS.SENT]: 'প্রেরিত',
  [MESSAGE_STATUS.DELIVERED]: 'প্রাপ্ত',
  [MESSAGE_STATUS.READ]: 'পঠিত',
  [MESSAGE_STATUS.FAILED]: 'ব্যর্থ',
  [MESSAGE_STATUS.PENDING]: 'মুলতুবি',
  [MESSAGE_STATUS.RETRY]: 'পুনরায় চেষ্টা',
  [MESSAGE_STATUS.BLOCKED]: 'ব্লকড',
  [MESSAGE_STATUS.SPAM]: 'স্প্যাম',
  [MESSAGE_STATUS.DELETED]: 'মুছে ফেলা',
  [MESSAGE_STATUS.REJECTED]: 'প্রত্যাখ্যাত',
  [MESSAGE_STATUS.RECEIVED]: 'গৃহীত',
  [MESSAGE_STATUS.SEEN]: 'দেখা',
  [MESSAGE_STATUS.PLAYED]: 'চালানো হয়েছে',
  [MESSAGE_STATUS.EXPIRED]: 'মেয়াদোত্তীর্ণ',
  [MESSAGE_STATUS.SCHEDULED]: 'নির্ধারিত',
  [MESSAGE_STATUS.DRAFT]: 'খসড়া',
  [MESSAGE_STATUS.ARCHIVED]: 'আর্কাইভড',
  [MESSAGE_STATUS.BOUNCED]: 'ফিরে এসেছে',
  [MESSAGE_STATUS.UNSUBSCRIBED]: 'আনসাবস্ক্রাইবড',
  [MESSAGE_STATUS.FILTERED]: 'ফিল্টারড',
} as const;

/**
 * মেসেজ স্ট্যাটাসের রঙের কোড (হেক্স)
 */
export const MESSAGE_STATUS_COLORS = {
  [MESSAGE_STATUS.SENT]: '#3498db',
  [MESSAGE_STATUS.DELIVERED]: '#2ecc71',
  [MESSAGE_STATUS.READ]: '#27ae60',
  [MESSAGE_STATUS.FAILED]: '#e74c3c',
  [MESSAGE_STATUS.PENDING]: '#f39c12',
  [MESSAGE_STATUS.RETRY]: '#e67e22',
  [MESSAGE_STATUS.BLOCKED]: '#c0392b',
  [MESSAGE_STATUS.SPAM]: '#7f8c8d',
  [MESSAGE_STATUS.DELETED]: '#95a5a6',
  [MESSAGE_STATUS.REJECTED]: '#e74c3c',
  [MESSAGE_STATUS.RECEIVED]: '#2ecc71',
  [MESSAGE_STATUS.SEEN]: '#27ae60',
  [MESSAGE_STATUS.PLAYED]: '#1abc9c',
  [MESSAGE_STATUS.EXPIRED]: '#95a5a6',
  [MESSAGE_STATUS.SCHEDULED]: '#9b59b6',
  [MESSAGE_STATUS.DRAFT]: '#7f8c8d',
  [MESSAGE_STATUS.ARCHIVED]: '#34495e',
  [MESSAGE_STATUS.BOUNCED]: '#e67e22',
  [MESSAGE_STATUS.UNSUBSCRIBED]: '#95a5a6',
  [MESSAGE_STATUS.FILTERED]: '#7f8c8d',
} as const;

/**
 * মেসেজ স্ট্যাটাসের আইকন (অনুষঙ্গিক নাম)
 */
export const MESSAGE_STATUS_ICONS = {
  [MESSAGE_STATUS.SENT]: 'send',
  [MESSAGE_STATUS.DELIVERED]: 'check',
  [MESSAGE_STATUS.READ]: 'eye',
  [MESSAGE_STATUS.FAILED]: 'x-circle',
  [MESSAGE_STATUS.PENDING]: 'clock',
  [MESSAGE_STATUS.RETRY]: 'refresh-cw',
  [MESSAGE_STATUS.BLOCKED]: 'slash',
  [MESSAGE_STATUS.SPAM]: 'alert-octagon',
  [MESSAGE_STATUS.DELETED]: 'trash-2',
  [MESSAGE_STATUS.REJECTED]: 'x-circle',
  [MESSAGE_STATUS.RECEIVED]: 'inbox',
  [MESSAGE_STATUS.SEEN]: 'eye',
  [MESSAGE_STATUS.PLAYED]: 'play-circle',
  [MESSAGE_STATUS.EXPIRED]: 'clock',
  [MESSAGE_STATUS.SCHEDULED]: 'calendar',
  [MESSAGE_STATUS.DRAFT]: 'file',
  [MESSAGE_STATUS.ARCHIVED]: 'archive',
  [MESSAGE_STATUS.BOUNCED]: 'rotate-ccw',
  [MESSAGE_STATUS.UNSUBSCRIBED]: 'user-x',
  [MESSAGE_STATUS.FILTERED]: 'filter',
} as const;

/**
 * মেসেজ স্ট্যাটাসের ক্যাটাগরি
 */
export const MESSAGE_STATUS_CATEGORIES = {
  [MESSAGE_STATUS.SENT]: 'progress',
  [MESSAGE_STATUS.DELIVERED]: 'success',
  [MESSAGE_STATUS.READ]: 'success',
  [MESSAGE_STATUS.FAILED]: 'error',
  [MESSAGE_STATUS.PENDING]: 'progress',
  [MESSAGE_STATUS.RETRY]: 'progress',
  [MESSAGE_STATUS.BLOCKED]: 'error',
  [MESSAGE_STATUS.SPAM]: 'error',
  [MESSAGE_STATUS.DELETED]: 'inactive',
  [MESSAGE_STATUS.REJECTED]: 'error',
  [MESSAGE_STATUS.RECEIVED]: 'success',
  [MESSAGE_STATUS.SEEN]: 'success',
  [MESSAGE_STATUS.PLAYED]: 'success',
  [MESSAGE_STATUS.EXPIRED]: 'inactive',
  [MESSAGE_STATUS.SCHEDULED]: 'progress',
  [MESSAGE_STATUS.DRAFT]: 'inactive',
  [MESSAGE_STATUS.ARCHIVED]: 'inactive',
  [MESSAGE_STATUS.BOUNCED]: 'error',
  [MESSAGE_STATUS.UNSUBSCRIBED]: 'inactive',
  [MESSAGE_STATUS.FILTERED]: 'inactive',
} as const;

/**
 * মেসেজ স্ট্যাটাসের গ্রুপ
 */
export const MESSAGE_STATUS_GROUPS = {
  SUCCESS: ['sent', 'delivered', 'read', 'received', 'seen', 'played'],
  PENDING: ['pending', 'retry', 'scheduled'],
  FAILED: ['failed', 'rejected', 'bounced', 'blocked', 'spam', 'expired'],
  INACTIVE: ['deleted', 'archived', 'draft', 'unsubscribed', 'filtered'],
} as const;

/**
 * মেসেজ স্ট্যাটাস ট্রানজিশন রুলস
 */
export const MESSAGE_STATUS_TRANSITIONS = {
  [MESSAGE_STATUS.DRAFT]: ['sent', 'scheduled', 'deleted'],
  [MESSAGE_STATUS.SCHEDULED]: ['sent', 'pending', 'deleted'],
  [MESSAGE_STATUS.PENDING]: ['sent', 'failed', 'retry', 'expired'],
  [MESSAGE_STATUS.SENT]: ['delivered', 'failed', 'rejected', 'bounced', 'blocked', 'expired'],
  [MESSAGE_STATUS.DELIVERED]: ['read', 'seen', 'played', 'deleted', 'archived'],
  [MESSAGE_STATUS.READ]: ['seen', 'deleted', 'archived'],
  [MESSAGE_STATUS.SEEN]: ['deleted', 'archived'],
  [MESSAGE_STATUS.PLAYED]: ['deleted', 'archived'],
  [MESSAGE_STATUS.RECEIVED]: ['read', 'seen', 'played', 'deleted'],
  [MESSAGE_STATUS.RETRY]: ['sent', 'failed', 'expired'],
  [MESSAGE_STATUS.FAILED]: ['retry', 'deleted', 'archived'],
  [MESSAGE_STATUS.REJECTED]: ['deleted', 'archived'],
  [MESSAGE_STATUS.BOUNCED]: ['deleted', 'archived'],
  [MESSAGE_STATUS.BLOCKED]: ['deleted', 'archived'],
  [MESSAGE_STATUS.SPAM]: ['deleted'],
  [MESSAGE_STATUS.EXPIRED]: ['deleted'],
  [MESSAGE_STATUS.DELETED]: [],
  [MESSAGE_STATUS.ARCHIVED]: ['deleted'],
  [MESSAGE_STATUS.UNSUBSCRIBED]: ['deleted'],
  [MESSAGE_STATUS.FILTERED]: ['deleted'],
} as const;

/**
 * মেসেজ স্ট্যাটাসের সময়সীমা (সেকেন্ডে)
 */
export const MESSAGE_STATUS_TIME_LIMITS = {
  [MESSAGE_STATUS.SENT]: 300,
  [MESSAGE_STATUS.DELIVERED]: 300,
  [MESSAGE_STATUS.READ]: 0,
  [MESSAGE_STATUS.FAILED]: 0,
  [MESSAGE_STATUS.PENDING]: 60,
  [MESSAGE_STATUS.RETRY]: 60,
  [MESSAGE_STATUS.BLOCKED]: 0,
  [MESSAGE_STATUS.SPAM]: 0,
  [MESSAGE_STATUS.DELETED]: 0,
  [MESSAGE_STATUS.REJECTED]: 0,
  [MESSAGE_STATUS.RECEIVED]: 300,
  [MESSAGE_STATUS.SEEN]: 0,
  [MESSAGE_STATUS.PLAYED]: 0,
  [MESSAGE_STATUS.EXPIRED]: 0,
  [MESSAGE_STATUS.SCHEDULED]: 0,
  [MESSAGE_STATUS.DRAFT]: 0,
  [MESSAGE_STATUS.ARCHIVED]: 0,
  [MESSAGE_STATUS.BOUNCED]: 0,
  [MESSAGE_STATUS.UNSUBSCRIBED]: 0,
  [MESSAGE_STATUS.FILTERED]: 0,
} as const;

/**
 * মেসেজ স্ট্যাটাসের অটো-ট্রানজিশন
 */
export const MESSAGE_STATUS_AUTO_TRANSITIONS = {
  [MESSAGE_STATUS.SENT]: {
    after: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.SENT],
    to: MESSAGE_STATUS.DELIVERED,
  },
  [MESSAGE_STATUS.PENDING]: {
    after: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.PENDING],
    to: MESSAGE_STATUS.FAILED,
  },
  [MESSAGE_STATUS.RETRY]: {
    after: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.RETRY],
    to: MESSAGE_STATUS.FAILED,
  },
} as const;

/**
 * মেসেজ স্ট্যাটাসের ডিফল্ট অ্যাকশন
 */
export const MESSAGE_STATUS_DEFAULT_ACTIONS = {
  [MESSAGE_STATUS.SENT]: 'মেসেজ প্রেরিত হয়েছে, ডেলিভারির অপেক্ষায়',
  [MESSAGE_STATUS.DELIVERED]: 'মেসেজ প্রাপ্ত হয়েছে',
  [MESSAGE_STATUS.READ]: 'মেসেজ পঠিত হয়েছে',
  [MESSAGE_STATUS.FAILED]: 'মেসেজ প্রেরণ ব্যর্থ হয়েছে, পুনরায় চেষ্টা করুন',
  [MESSAGE_STATUS.PENDING]: 'মেসেজ প্রক্রিয়াকরণের অপেক্ষায়',
  [MESSAGE_STATUS.RETRY]: 'মেসেজ পুনরায় প্রেরণের চেষ্টা চলছে',
  [MESSAGE_STATUS.BLOCKED]: 'মেসেজ ব্লক করা হয়েছে',
  [MESSAGE_STATUS.SPAM]: 'মেসেজ স্প্যাম হিসেবে চিহ্নিত',
  [MESSAGE_STATUS.DELETED]: 'মেসেজ মুছে ফেলা হয়েছে',
  [MESSAGE_STATUS.REJECTED]: 'মেসেজ প্রত্যাখ্যাত হয়েছে',
  [MESSAGE_STATUS.RECEIVED]: 'মেসেজ গৃহীত হয়েছে',
  [MESSAGE_STATUS.SEEN]: 'মেসেজ দেখা হয়েছে',
  [MESSAGE_STATUS.PLAYED]: 'মেসেজ চালানো হয়েছে',
  [MESSAGE_STATUS.EXPIRED]: 'মেসেজের মেয়াদ শেষ হয়েছে',
  [MESSAGE_STATUS.SCHEDULED]: 'মেসেজ প্রেরণের জন্য নির্ধারিত',
  [MESSAGE_STATUS.DRAFT]: 'মেসেজ খসড়া সংরক্ষিত',
  [MESSAGE_STATUS.ARCHIVED]: 'মেসেজ আর্কাইভ করা হয়েছে',
  [MESSAGE_STATUS.BOUNCED]: 'মেসেজ ফিরে এসেছে',
  [MESSAGE_STATUS.UNSUBSCRIBED]: 'গ্রাহক আনসাবস্ক্রাইব করেছেন',
  [MESSAGE_STATUS.FILTERED]: 'মেসেজ ফিল্টার করা হয়েছে',
} as const;

/**
 * মেসেজ স্ট্যাটাসের ডেলিভারি কনফার্মেশন টাইপ
 */
export const DELIVERY_CONFIRMATION_TYPES = {
  NONE: 'none',
  READ_RECEIPT: 'read_receipt',
  DELIVERY_RECEIPT: 'delivery_receipt',
  FULL: 'full',
} as const;

export type MessageStatus = (typeof MESSAGE_STATUS)[keyof typeof MESSAGE_STATUS];
export type MessageStatusDisplayNames = typeof MESSAGE_STATUS_DISPLAY_NAMES;
export type MessageStatusColors = typeof MESSAGE_STATUS_COLORS;
export type MessageStatusIcons = typeof MESSAGE_STATUS_ICONS;
export type MessageStatusCategories = typeof MESSAGE_STATUS_CATEGORIES;
export type MessageStatusGroups = typeof MESSAGE_STATUS_GROUPS;
export type MessageStatusTransitions = typeof MESSAGE_STATUS_TRANSITIONS;
export type MessageStatusTimeLimits = typeof MESSAGE_STATUS_TIME_LIMITS;
export type MessageStatusAutoTransitions = typeof MESSAGE_STATUS_AUTO_TRANSITIONS;
export type MessageStatusDefaultActions = typeof MESSAGE_STATUS_DEFAULT_ACTIONS;
export type DeliveryConfirmationType =
  (typeof DELIVERY_CONFIRMATION_TYPES)[keyof typeof DELIVERY_CONFIRMATION_TYPES];

export interface MessageStatusConfig {
  status: MessageStatus;
  displayName: string;
  color: string;
  icon: string;
  category: string;
  timeLimitSeconds: number;
  defaultAction: string;
  autoTransition?: {
    after: number;
    to: MessageStatus;
  };
}

/**
 * মেসেজ স্ট্যাটাস কনফিগারেশন অবজেক্ট
 */
export const MESSAGE_STATUS_CONFIGS: Record<MessageStatus, MessageStatusConfig> = {
  [MESSAGE_STATUS.SENT]: {
    status: MESSAGE_STATUS.SENT,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.SENT],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.SENT],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.SENT],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.SENT],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.SENT],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.SENT],
    autoTransition: MESSAGE_STATUS_AUTO_TRANSITIONS[MESSAGE_STATUS.SENT],
  },
  [MESSAGE_STATUS.DELIVERED]: {
    status: MESSAGE_STATUS.DELIVERED,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.DELIVERED],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.DELIVERED],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.DELIVERED],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.DELIVERED],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.DELIVERED],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.DELIVERED],
  },
  [MESSAGE_STATUS.READ]: {
    status: MESSAGE_STATUS.READ,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.READ],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.READ],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.READ],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.READ],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.READ],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.READ],
  },
  [MESSAGE_STATUS.FAILED]: {
    status: MESSAGE_STATUS.FAILED,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.FAILED],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.FAILED],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.FAILED],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.FAILED],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.FAILED],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.FAILED],
  },
  [MESSAGE_STATUS.PENDING]: {
    status: MESSAGE_STATUS.PENDING,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.PENDING],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.PENDING],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.PENDING],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.PENDING],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.PENDING],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.PENDING],
    autoTransition: MESSAGE_STATUS_AUTO_TRANSITIONS[MESSAGE_STATUS.PENDING],
  },
  [MESSAGE_STATUS.RETRY]: {
    status: MESSAGE_STATUS.RETRY,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.RETRY],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.RETRY],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.RETRY],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.RETRY],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.RETRY],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.RETRY],
    autoTransition: MESSAGE_STATUS_AUTO_TRANSITIONS[MESSAGE_STATUS.RETRY],
  },
  [MESSAGE_STATUS.BLOCKED]: {
    status: MESSAGE_STATUS.BLOCKED,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.BLOCKED],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.BLOCKED],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.BLOCKED],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.BLOCKED],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.BLOCKED],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.BLOCKED],
  },
  [MESSAGE_STATUS.SPAM]: {
    status: MESSAGE_STATUS.SPAM,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.SPAM],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.SPAM],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.SPAM],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.SPAM],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.SPAM],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.SPAM],
  },
  [MESSAGE_STATUS.DELETED]: {
    status: MESSAGE_STATUS.DELETED,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.DELETED],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.DELETED],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.DELETED],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.DELETED],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.DELETED],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.DELETED],
  },
  [MESSAGE_STATUS.REJECTED]: {
    status: MESSAGE_STATUS.REJECTED,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.REJECTED],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.REJECTED],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.REJECTED],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.REJECTED],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.REJECTED],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.REJECTED],
  },
  [MESSAGE_STATUS.RECEIVED]: {
    status: MESSAGE_STATUS.RECEIVED,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.RECEIVED],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.RECEIVED],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.RECEIVED],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.RECEIVED],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.RECEIVED],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.RECEIVED],
  },
  [MESSAGE_STATUS.SEEN]: {
    status: MESSAGE_STATUS.SEEN,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.SEEN],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.SEEN],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.SEEN],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.SEEN],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.SEEN],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.SEEN],
  },
  [MESSAGE_STATUS.PLAYED]: {
    status: MESSAGE_STATUS.PLAYED,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.PLAYED],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.PLAYED],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.PLAYED],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.PLAYED],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.PLAYED],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.PLAYED],
  },
  [MESSAGE_STATUS.EXPIRED]: {
    status: MESSAGE_STATUS.EXPIRED,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.EXPIRED],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.EXPIRED],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.EXPIRED],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.EXPIRED],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.EXPIRED],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.EXPIRED],
  },
  [MESSAGE_STATUS.SCHEDULED]: {
    status: MESSAGE_STATUS.SCHEDULED,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.SCHEDULED],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.SCHEDULED],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.SCHEDULED],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.SCHEDULED],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.SCHEDULED],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.SCHEDULED],
  },
  [MESSAGE_STATUS.DRAFT]: {
    status: MESSAGE_STATUS.DRAFT,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.DRAFT],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.DRAFT],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.DRAFT],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.DRAFT],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.DRAFT],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.DRAFT],
  },
  [MESSAGE_STATUS.ARCHIVED]: {
    status: MESSAGE_STATUS.ARCHIVED,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.ARCHIVED],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.ARCHIVED],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.ARCHIVED],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.ARCHIVED],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.ARCHIVED],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.ARCHIVED],
  },
  [MESSAGE_STATUS.BOUNCED]: {
    status: MESSAGE_STATUS.BOUNCED,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.BOUNCED],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.BOUNCED],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.BOUNCED],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.BOUNCED],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.BOUNCED],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.BOUNCED],
  },
  [MESSAGE_STATUS.UNSUBSCRIBED]: {
    status: MESSAGE_STATUS.UNSUBSCRIBED,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.UNSUBSCRIBED],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.UNSUBSCRIBED],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.UNSUBSCRIBED],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.UNSUBSCRIBED],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.UNSUBSCRIBED],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.UNSUBSCRIBED],
  },
  [MESSAGE_STATUS.FILTERED]: {
    status: MESSAGE_STATUS.FILTERED,
    displayName: MESSAGE_STATUS_DISPLAY_NAMES[MESSAGE_STATUS.FILTERED],
    color: MESSAGE_STATUS_COLORS[MESSAGE_STATUS.FILTERED],
    icon: MESSAGE_STATUS_ICONS[MESSAGE_STATUS.FILTERED],
    category: MESSAGE_STATUS_CATEGORIES[MESSAGE_STATUS.FILTERED],
    timeLimitSeconds: MESSAGE_STATUS_TIME_LIMITS[MESSAGE_STATUS.FILTERED],
    defaultAction: MESSAGE_STATUS_DEFAULT_ACTIONS[MESSAGE_STATUS.FILTERED],
  },
};
