/**
 * সাপোর্ট টেমপ্লেটের বিভিন্ন টাইপ সংক্রান্ত কনস্ট্যান্টসমূহ
 */

/**
 * টেমপ্লেট টাইপ
 */
export const TEMPLATE_TYPE = {
  EMAIL_TEMPLATE: 'email_template',
  SMS_TEMPLATE: 'sms_template',
  PUSH_TEMPLATE: 'push_template',
  TICKET_TEMPLATE: 'ticket_template',
  RESPONSE_TEMPLATE: 'response_template',
  SURVEY_TEMPLATE: 'survey_template',
  REPORT_TEMPLATE: 'report_template',
  CHATBOT_TEMPLATE: 'chatbot_template',
  SCRIPT_TEMPLATE: 'script_template',
  DOCUMENT_TEMPLATE: 'document_template',
  NOTIFICATION_TEMPLATE: 'notification_template',
  AUTOMATION_TEMPLATE: 'automation_template',
  WORKFLOW_TEMPLATE: 'workflow_template',
  FORM_TEMPLATE: 'form_template',
  ARTICLE_TEMPLATE: 'article_template',
  SLACK_TEMPLATE: 'slack_template',
  TEAMS_TEMPLATE: 'teams_template',
  WHATSAPP_TEMPLATE: 'whatsapp_template',
  MESSENGER_TEMPLATE: 'messenger_template',
  WEBHOOK_TEMPLATE: 'webhook_template',
  API_TEMPLATE: 'api_template',
  SIGNATURE_TEMPLATE: 'signature_template',
  FOOTER_TEMPLATE: 'footer_template',
  HEADER_TEMPLATE: 'header_template',
  LAYOUT_TEMPLATE: 'layout_template',
  LANDING_PAGE_TEMPLATE: 'landing_page_template',
  KB_ARTICLE_TEMPLATE: 'kb_article_template',
  FAQ_TEMPLATE: 'faq_template',
  TUTORIAL_TEMPLATE: 'tutorial_template',
  ONBOARDING_TEMPLATE: 'onboarding_template',
  WELCOME_TEMPLATE: 'welcome_template',
  FEEDBACK_TEMPLATE: 'feedback_template',
  COMPLAINT_TEMPLATE: 'complaint_template',
  ESCALATION_TEMPLATE: 'escalation_template',
  FOLLOW_UP_TEMPLATE: 'follow_up_template',
  REMINDER_TEMPLATE: 'reminder_template',
  THANK_YOU_TEMPLATE: 'thank_you_template',
  APOLOGY_TEMPLATE: 'apology_template',
  CONFIRMATION_TEMPLATE: 'confirmation_template',
  INVOICE_TEMPLATE: 'invoice_template',
  RECEIPT_TEMPLATE: 'receipt_template',
} as const;

/**
 * টেমপ্লেট টাইপের ডিসপ্লে নাম
 */
export const TEMPLATE_TYPE_DISPLAY_NAMES = {
  [TEMPLATE_TYPE.EMAIL_TEMPLATE]: 'ইমেইল টেমপ্লেট',
  [TEMPLATE_TYPE.SMS_TEMPLATE]: 'এসএমএস টেমপ্লেট',
  [TEMPLATE_TYPE.PUSH_TEMPLATE]: 'পুশ টেমপ্লেট',
  [TEMPLATE_TYPE.TICKET_TEMPLATE]: 'টিকেট টেমপ্লেট',
  [TEMPLATE_TYPE.RESPONSE_TEMPLATE]: 'রেসপন্স টেমপ্লেট',
  [TEMPLATE_TYPE.SURVEY_TEMPLATE]: 'জরিপ টেমপ্লেট',
  [TEMPLATE_TYPE.REPORT_TEMPLATE]: 'রিপোর্ট টেমপ্লেট',
  [TEMPLATE_TYPE.CHATBOT_TEMPLATE]: 'চ্যাটবট টেমপ্লেট',
  [TEMPLATE_TYPE.SCRIPT_TEMPLATE]: 'স্ক্রিপ্ট টেমপ্লেট',
  [TEMPLATE_TYPE.DOCUMENT_TEMPLATE]: 'ডকুমেন্ট টেমপ্লেট',
  [TEMPLATE_TYPE.NOTIFICATION_TEMPLATE]: 'নোটিফিকেশন টেমপ্লেট',
  [TEMPLATE_TYPE.AUTOMATION_TEMPLATE]: 'অটোমেশন টেমপ্লেট',
  [TEMPLATE_TYPE.WORKFLOW_TEMPLATE]: 'ওয়ার্কফ্লো টেমপ্লেট',
  [TEMPLATE_TYPE.FORM_TEMPLATE]: 'ফর্ম টেমপ্লেট',
  [TEMPLATE_TYPE.ARTICLE_TEMPLATE]: 'আর্টিকেল টেমপ্লেট',
  [TEMPLATE_TYPE.SLACK_TEMPLATE]: 'স্ল্যাক টেমপ্লেট',
  [TEMPLATE_TYPE.TEAMS_TEMPLATE]: 'টিমস টেমপ্লেট',
  [TEMPLATE_TYPE.WHATSAPP_TEMPLATE]: 'হোয়াটসঅ্যাপ টেমপ্লেট',
  [TEMPLATE_TYPE.MESSENGER_TEMPLATE]: 'মেসেঞ্জার টেমপ্লেট',
  [TEMPLATE_TYPE.WEBHOOK_TEMPLATE]: 'ওয়েবহুক টেমপ্লেট',
  [TEMPLATE_TYPE.API_TEMPLATE]: 'এপিআই টেমপ্লেট',
  [TEMPLATE_TYPE.SIGNATURE_TEMPLATE]: 'সিগনেচার টেমপ্লেট',
  [TEMPLATE_TYPE.FOOTER_TEMPLATE]: 'ফুটার টেমপ্লেট',
  [TEMPLATE_TYPE.HEADER_TEMPLATE]: 'হেডার টেমপ্লেট',
  [TEMPLATE_TYPE.LAYOUT_TEMPLATE]: 'লেআউট টেমপ্লেট',
  [TEMPLATE_TYPE.LANDING_PAGE_TEMPLATE]: 'ল্যান্ডিং পেজ টেমপ্লেট',
  [TEMPLATE_TYPE.KB_ARTICLE_TEMPLATE]: 'নলেজ বেস আর্টিকেল টেমপ্লেট',
  [TEMPLATE_TYPE.FAQ_TEMPLATE]: 'এফএকিউ টেমপ্লেট',
  [TEMPLATE_TYPE.TUTORIAL_TEMPLATE]: 'টিউটোরিয়াল টেমপ্লেট',
  [TEMPLATE_TYPE.ONBOARDING_TEMPLATE]: 'অনবোর্ডিং টেমপ্লেট',
  [TEMPLATE_TYPE.WELCOME_TEMPLATE]: 'স্বাগতম টেমপ্লেট',
  [TEMPLATE_TYPE.FEEDBACK_TEMPLATE]: 'ফিডব্যাক টেমপ্লেট',
  [TEMPLATE_TYPE.COMPLAINT_TEMPLATE]: 'অভিযোগ টেমপ্লেট',
  [TEMPLATE_TYPE.ESCALATION_TEMPLATE]: 'এস্কেলেশন টেমপ্লেট',
  [TEMPLATE_TYPE.FOLLOW_UP_TEMPLATE]: 'ফলো-আপ টেমপ্লেট',
  [TEMPLATE_TYPE.REMINDER_TEMPLATE]: 'রিমাইন্ডার টেমপ্লেট',
  [TEMPLATE_TYPE.THANK_YOU_TEMPLATE]: 'ধন্যবাদ টেমপ্লেট',
  [TEMPLATE_TYPE.APOLOGY_TEMPLATE]: 'ক্ষমা প্রার্থনা টেমপ্লেট',
  [TEMPLATE_TYPE.CONFIRMATION_TEMPLATE]: 'নিশ্চিতকরণ টেমপ্লেট',
  [TEMPLATE_TYPE.INVOICE_TEMPLATE]: 'ইনভয়েস টেমপ্লেট',
  [TEMPLATE_TYPE.RECEIPT_TEMPLATE]: 'রসিদ টেমপ্লেট',
} as const;

/**
 * টেমপ্লেট টাইপের আইকন (অনুষঙ্গিক নাম)
 */
export const TEMPLATE_TYPE_ICONS = {
  [TEMPLATE_TYPE.EMAIL_TEMPLATE]: 'mail',
  [TEMPLATE_TYPE.SMS_TEMPLATE]: 'message-circle',
  [TEMPLATE_TYPE.PUSH_TEMPLATE]: 'bell',
  [TEMPLATE_TYPE.TICKET_TEMPLATE]: 'ticket',
  [TEMPLATE_TYPE.RESPONSE_TEMPLATE]: 'message-square',
  [TEMPLATE_TYPE.SURVEY_TEMPLATE]: 'clipboard',
  [TEMPLATE_TYPE.REPORT_TEMPLATE]: 'file-text',
  [TEMPLATE_TYPE.CHATBOT_TEMPLATE]: 'bot',
  [TEMPLATE_TYPE.SCRIPT_TEMPLATE]: 'code',
  [TEMPLATE_TYPE.DOCUMENT_TEMPLATE]: 'file',
  [TEMPLATE_TYPE.NOTIFICATION_TEMPLATE]: 'bell',
  [TEMPLATE_TYPE.AUTOMATION_TEMPLATE]: 'zap',
  [TEMPLATE_TYPE.WORKFLOW_TEMPLATE]: 'workflow',
  [TEMPLATE_TYPE.FORM_TEMPLATE]: 'form-input',
  [TEMPLATE_TYPE.ARTICLE_TEMPLATE]: 'book',
  [TEMPLATE_TYPE.SLACK_TEMPLATE]: 'slack',
  [TEMPLATE_TYPE.TEAMS_TEMPLATE]: 'users',
  [TEMPLATE_TYPE.WHATSAPP_TEMPLATE]: 'message-circle',
  [TEMPLATE_TYPE.MESSENGER_TEMPLATE]: 'facebook',
  [TEMPLATE_TYPE.WEBHOOK_TEMPLATE]: 'link',
  [TEMPLATE_TYPE.API_TEMPLATE]: 'code',
  [TEMPLATE_TYPE.SIGNATURE_TEMPLATE]: 'pen-tool',
  [TEMPLATE_TYPE.FOOTER_TEMPLATE]: 'align-bottom',
  [TEMPLATE_TYPE.HEADER_TEMPLATE]: 'align-top',
  [TEMPLATE_TYPE.LAYOUT_TEMPLATE]: 'layout',
  [TEMPLATE_TYPE.LANDING_PAGE_TEMPLATE]: 'globe',
  [TEMPLATE_TYPE.KB_ARTICLE_TEMPLATE]: 'book-open',
  [TEMPLATE_TYPE.FAQ_TEMPLATE]: 'help-circle',
  [TEMPLATE_TYPE.TUTORIAL_TEMPLATE]: 'book',
  [TEMPLATE_TYPE.ONBOARDING_TEMPLATE]: 'user-plus',
  [TEMPLATE_TYPE.WELCOME_TEMPLATE]: 'smile',
  [TEMPLATE_TYPE.FEEDBACK_TEMPLATE]: 'message-square',
  [TEMPLATE_TYPE.COMPLAINT_TEMPLATE]: 'alert-triangle',
  [TEMPLATE_TYPE.ESCALATION_TEMPLATE]: 'arrow-up-circle',
  [TEMPLATE_TYPE.FOLLOW_UP_TEMPLATE]: 'refresh-cw',
  [TEMPLATE_TYPE.REMINDER_TEMPLATE]: 'clock',
  [TEMPLATE_TYPE.THANK_YOU_TEMPLATE]: 'thumbs-up',
  [TEMPLATE_TYPE.APOLOGY_TEMPLATE]: 'frown',
  [TEMPLATE_TYPE.CONFIRMATION_TEMPLATE]: 'check-circle',
  [TEMPLATE_TYPE.INVOICE_TEMPLATE]: 'file-text',
  [TEMPLATE_TYPE.RECEIPT_TEMPLATE]: 'receipt',
} as const;

/**
 * টেমপ্লেট টাইপের রঙের কোড (হেক্স)
 */
export const TEMPLATE_TYPE_COLORS = {
  [TEMPLATE_TYPE.EMAIL_TEMPLATE]: '#3498db',
  [TEMPLATE_TYPE.SMS_TEMPLATE]: '#2ecc71',
  [TEMPLATE_TYPE.PUSH_TEMPLATE]: '#9b59b6',
  [TEMPLATE_TYPE.TICKET_TEMPLATE]: '#e67e22',
  [TEMPLATE_TYPE.RESPONSE_TEMPLATE]: '#1abc9c',
  [TEMPLATE_TYPE.SURVEY_TEMPLATE]: '#2980b9',
  [TEMPLATE_TYPE.REPORT_TEMPLATE]: '#e74c3c',
  [TEMPLATE_TYPE.CHATBOT_TEMPLATE]: '#3498db',
  [TEMPLATE_TYPE.SCRIPT_TEMPLATE]: '#2c3e50',
  [TEMPLATE_TYPE.DOCUMENT_TEMPLATE]: '#95a5a6',
  [TEMPLATE_TYPE.NOTIFICATION_TEMPLATE]: '#f39c12',
  [TEMPLATE_TYPE.AUTOMATION_TEMPLATE]: '#2ecc71',
  [TEMPLATE_TYPE.WORKFLOW_TEMPLATE]: '#1abc9c',
  [TEMPLATE_TYPE.FORM_TEMPLATE]: '#9b59b6',
  [TEMPLATE_TYPE.ARTICLE_TEMPLATE]: '#3498db',
  [TEMPLATE_TYPE.SLACK_TEMPLATE]: '#4a154b',
  [TEMPLATE_TYPE.TEAMS_TEMPLATE]: '#464eb8',
  [TEMPLATE_TYPE.WHATSAPP_TEMPLATE]: '#25d366',
  [TEMPLATE_TYPE.MESSENGER_TEMPLATE]: '#0084ff',
  [TEMPLATE_TYPE.WEBHOOK_TEMPLATE]: '#8e44ad',
  [TEMPLATE_TYPE.API_TEMPLATE]: '#2980b9',
  [TEMPLATE_TYPE.SIGNATURE_TEMPLATE]: '#34495e',
  [TEMPLATE_TYPE.FOOTER_TEMPLATE]: '#7f8c8d',
  [TEMPLATE_TYPE.HEADER_TEMPLATE]: '#7f8c8d',
  [TEMPLATE_TYPE.LAYOUT_TEMPLATE]: '#2c3e50',
  [TEMPLATE_TYPE.LANDING_PAGE_TEMPLATE]: '#e67e22',
  [TEMPLATE_TYPE.KB_ARTICLE_TEMPLATE]: '#2980b9',
  [TEMPLATE_TYPE.FAQ_TEMPLATE]: '#9b59b6',
  [TEMPLATE_TYPE.TUTORIAL_TEMPLATE]: '#2ecc71',
  [TEMPLATE_TYPE.ONBOARDING_TEMPLATE]: '#1abc9c',
  [TEMPLATE_TYPE.WELCOME_TEMPLATE]: '#27ae60',
  [TEMPLATE_TYPE.FEEDBACK_TEMPLATE]: '#8e44ad',
  [TEMPLATE_TYPE.COMPLAINT_TEMPLATE]: '#c0392b',
  [TEMPLATE_TYPE.ESCALATION_TEMPLATE]: '#e74c3c',
  [TEMPLATE_TYPE.FOLLOW_UP_TEMPLATE]: '#3498db',
  [TEMPLATE_TYPE.REMINDER_TEMPLATE]: '#f39c12',
  [TEMPLATE_TYPE.THANK_YOU_TEMPLATE]: '#2ecc71',
  [TEMPLATE_TYPE.APOLOGY_TEMPLATE]: '#e67e22',
  [TEMPLATE_TYPE.CONFIRMATION_TEMPLATE]: '#27ae60',
  [TEMPLATE_TYPE.INVOICE_TEMPLATE]: '#34495e',
  [TEMPLATE_TYPE.RECEIPT_TEMPLATE]: '#2c3e50',
} as const;

/**
 * টেমপ্লেট টাইপের ক্যাটাগরি
 */
export const TEMPLATE_TYPE_CATEGORIES = {
  [TEMPLATE_TYPE.EMAIL_TEMPLATE]: 'communication',
  [TEMPLATE_TYPE.SMS_TEMPLATE]: 'communication',
  [TEMPLATE_TYPE.PUSH_TEMPLATE]: 'communication',
  [TEMPLATE_TYPE.TICKET_TEMPLATE]: 'ticket',
  [TEMPLATE_TYPE.RESPONSE_TEMPLATE]: 'response',
  [TEMPLATE_TYPE.SURVEY_TEMPLATE]: 'survey',
  [TEMPLATE_TYPE.REPORT_TEMPLATE]: 'reporting',
  [TEMPLATE_TYPE.CHATBOT_TEMPLATE]: 'chatbot',
  [TEMPLATE_TYPE.SCRIPT_TEMPLATE]: 'script',
  [TEMPLATE_TYPE.DOCUMENT_TEMPLATE]: 'document',
  [TEMPLATE_TYPE.NOTIFICATION_TEMPLATE]: 'notification',
  [TEMPLATE_TYPE.AUTOMATION_TEMPLATE]: 'automation',
  [TEMPLATE_TYPE.WORKFLOW_TEMPLATE]: 'workflow',
  [TEMPLATE_TYPE.FORM_TEMPLATE]: 'form',
  [TEMPLATE_TYPE.ARTICLE_TEMPLATE]: 'knowledge',
  [TEMPLATE_TYPE.SLACK_TEMPLATE]: 'communication',
  [TEMPLATE_TYPE.TEAMS_TEMPLATE]: 'communication',
  [TEMPLATE_TYPE.WHATSAPP_TEMPLATE]: 'communication',
  [TEMPLATE_TYPE.MESSENGER_TEMPLATE]: 'communication',
  [TEMPLATE_TYPE.WEBHOOK_TEMPLATE]: 'integration',
  [TEMPLATE_TYPE.API_TEMPLATE]: 'integration',
  [TEMPLATE_TYPE.SIGNATURE_TEMPLATE]: 'design',
  [TEMPLATE_TYPE.FOOTER_TEMPLATE]: 'design',
  [TEMPLATE_TYPE.HEADER_TEMPLATE]: 'design',
  [TEMPLATE_TYPE.LAYOUT_TEMPLATE]: 'design',
  [TEMPLATE_TYPE.LANDING_PAGE_TEMPLATE]: 'design',
  [TEMPLATE_TYPE.KB_ARTICLE_TEMPLATE]: 'knowledge',
  [TEMPLATE_TYPE.FAQ_TEMPLATE]: 'knowledge',
  [TEMPLATE_TYPE.TUTORIAL_TEMPLATE]: 'knowledge',
  [TEMPLATE_TYPE.ONBOARDING_TEMPLATE]: 'process',
  [TEMPLATE_TYPE.WELCOME_TEMPLATE]: 'process',
  [TEMPLATE_TYPE.FEEDBACK_TEMPLATE]: 'feedback',
  [TEMPLATE_TYPE.COMPLAINT_TEMPLATE]: 'feedback',
  [TEMPLATE_TYPE.ESCALATION_TEMPLATE]: 'process',
  [TEMPLATE_TYPE.FOLLOW_UP_TEMPLATE]: 'process',
  [TEMPLATE_TYPE.REMINDER_TEMPLATE]: 'process',
  [TEMPLATE_TYPE.THANK_YOU_TEMPLATE]: 'communication',
  [TEMPLATE_TYPE.APOLOGY_TEMPLATE]: 'communication',
  [TEMPLATE_TYPE.CONFIRMATION_TEMPLATE]: 'communication',
  [TEMPLATE_TYPE.INVOICE_TEMPLATE]: 'financial',
  [TEMPLATE_TYPE.RECEIPT_TEMPLATE]: 'financial',
} as const;

/**
 * টেমপ্লেট টাইপ গ্রুপ
 */
export const TEMPLATE_TYPE_GROUPS = {
  COMMUNICATION: [
    'email_template',
    'sms_template',
    'push_template',
    'slack_template',
    'teams_template',
    'whatsapp_template',
    'messenger_template',
    'thank_you_template',
    'apology_template',
    'confirmation_template',
  ],
  TICKET: ['ticket_template'],
  RESPONSE: ['response_template'],
  SURVEY: ['survey_template'],
  REPORTING: ['report_template'],
  CHATBOT: ['chatbot_template'],
  SCRIPT: ['script_template'],
  DOCUMENT: ['document_template'],
  NOTIFICATION: ['notification_template'],
  AUTOMATION: ['automation_template'],
  WORKFLOW: ['workflow_template'],
  FORM: ['form_template'],
  KNOWLEDGE: ['article_template', 'kb_article_template', 'faq_template', 'tutorial_template'],
  INTEGRATION: ['webhook_template', 'api_template'],
  DESIGN: [
    'signature_template',
    'footer_template',
    'header_template',
    'layout_template',
    'landing_page_template',
  ],
  PROCESS: [
    'onboarding_template',
    'welcome_template',
    'escalation_template',
    'follow_up_template',
    'reminder_template',
  ],
  FEEDBACK: ['feedback_template', 'complaint_template'],
  FINANCIAL: ['invoice_template', 'receipt_template'],
} as const;

export type TemplateType = (typeof TEMPLATE_TYPE)[keyof typeof TEMPLATE_TYPE];
export type TemplateTypeDisplayNames = typeof TEMPLATE_TYPE_DISPLAY_NAMES;
export type TemplateTypeIcons = typeof TEMPLATE_TYPE_ICONS;
export type TemplateTypeColors = typeof TEMPLATE_TYPE_COLORS;
export type TemplateTypeCategories = typeof TEMPLATE_TYPE_CATEGORIES;
export type TemplateTypeGroups = typeof TEMPLATE_TYPE_GROUPS;

export type TemplateTypeGroup = keyof typeof TEMPLATE_TYPE_GROUPS;

export interface TemplateTypeConfig {
  type: TemplateType;
  displayName: string;
  icon: string;
  color: string;
  category: string;
  group: TemplateTypeGroup;
  description?: string;
}

/**
 * টেমপ্লেট টাইপ কনফিগারেশন অবজেক্ট
 */
export const TEMPLATE_TYPE_CONFIGS: Record<TemplateType, TemplateTypeConfig> = {
  [TEMPLATE_TYPE.EMAIL_TEMPLATE]: {
    type: TEMPLATE_TYPE.EMAIL_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.EMAIL_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.EMAIL_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.EMAIL_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.EMAIL_TEMPLATE],
    group: 'COMMUNICATION',
    description: 'ইমেইল পাঠানোর জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.SMS_TEMPLATE]: {
    type: TEMPLATE_TYPE.SMS_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.SMS_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.SMS_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.SMS_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.SMS_TEMPLATE],
    group: 'COMMUNICATION',
    description: 'এসএমএস পাঠানোর জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.PUSH_TEMPLATE]: {
    type: TEMPLATE_TYPE.PUSH_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.PUSH_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.PUSH_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.PUSH_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.PUSH_TEMPLATE],
    group: 'COMMUNICATION',
    description: 'পুশ নোটিফিকেশন পাঠানোর জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.TICKET_TEMPLATE]: {
    type: TEMPLATE_TYPE.TICKET_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.TICKET_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.TICKET_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.TICKET_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.TICKET_TEMPLATE],
    group: 'TICKET',
    description: 'টিকেট তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.RESPONSE_TEMPLATE]: {
    type: TEMPLATE_TYPE.RESPONSE_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.RESPONSE_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.RESPONSE_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.RESPONSE_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.RESPONSE_TEMPLATE],
    group: 'RESPONSE',
    description: 'রেসপন্স পাঠানোর জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.SURVEY_TEMPLATE]: {
    type: TEMPLATE_TYPE.SURVEY_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.SURVEY_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.SURVEY_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.SURVEY_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.SURVEY_TEMPLATE],
    group: 'SURVEY',
    description: 'জরিপ তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.REPORT_TEMPLATE]: {
    type: TEMPLATE_TYPE.REPORT_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.REPORT_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.REPORT_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.REPORT_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.REPORT_TEMPLATE],
    group: 'REPORTING',
    description: 'রিপোর্ট তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.CHATBOT_TEMPLATE]: {
    type: TEMPLATE_TYPE.CHATBOT_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.CHATBOT_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.CHATBOT_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.CHATBOT_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.CHATBOT_TEMPLATE],
    group: 'CHATBOT',
    description: 'চ্যাটবট রেসপন্সের জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.SCRIPT_TEMPLATE]: {
    type: TEMPLATE_TYPE.SCRIPT_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.SCRIPT_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.SCRIPT_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.SCRIPT_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.SCRIPT_TEMPLATE],
    group: 'SCRIPT',
    description: 'স্ক্রিপ্ট তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.DOCUMENT_TEMPLATE]: {
    type: TEMPLATE_TYPE.DOCUMENT_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.DOCUMENT_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.DOCUMENT_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.DOCUMENT_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.DOCUMENT_TEMPLATE],
    group: 'DOCUMENT',
    description: 'ডকুমেন্ট তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.NOTIFICATION_TEMPLATE]: {
    type: TEMPLATE_TYPE.NOTIFICATION_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.NOTIFICATION_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.NOTIFICATION_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.NOTIFICATION_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.NOTIFICATION_TEMPLATE],
    group: 'NOTIFICATION',
    description: 'নোটিফিকেশন তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.AUTOMATION_TEMPLATE]: {
    type: TEMPLATE_TYPE.AUTOMATION_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.AUTOMATION_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.AUTOMATION_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.AUTOMATION_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.AUTOMATION_TEMPLATE],
    group: 'AUTOMATION',
    description: 'অটোমেশন তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.WORKFLOW_TEMPLATE]: {
    type: TEMPLATE_TYPE.WORKFLOW_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.WORKFLOW_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.WORKFLOW_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.WORKFLOW_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.WORKFLOW_TEMPLATE],
    group: 'WORKFLOW',
    description: 'ওয়ার্কফ্লো তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.FORM_TEMPLATE]: {
    type: TEMPLATE_TYPE.FORM_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.FORM_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.FORM_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.FORM_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.FORM_TEMPLATE],
    group: 'FORM',
    description: 'ফর্ম তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.ARTICLE_TEMPLATE]: {
    type: TEMPLATE_TYPE.ARTICLE_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.ARTICLE_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.ARTICLE_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.ARTICLE_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.ARTICLE_TEMPLATE],
    group: 'KNOWLEDGE',
    description: 'আর্টিকেল তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.SLACK_TEMPLATE]: {
    type: TEMPLATE_TYPE.SLACK_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.SLACK_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.SLACK_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.SLACK_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.SLACK_TEMPLATE],
    group: 'COMMUNICATION',
    description: 'স্ল্যাক বার্তা পাঠানোর জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.TEAMS_TEMPLATE]: {
    type: TEMPLATE_TYPE.TEAMS_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.TEAMS_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.TEAMS_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.TEAMS_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.TEAMS_TEMPLATE],
    group: 'COMMUNICATION',
    description: 'টিমস বার্তা পাঠানোর জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.WHATSAPP_TEMPLATE]: {
    type: TEMPLATE_TYPE.WHATSAPP_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.WHATSAPP_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.WHATSAPP_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.WHATSAPP_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.WHATSAPP_TEMPLATE],
    group: 'COMMUNICATION',
    description: 'হোয়াটসঅ্যাপ বার্তা পাঠানোর জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.MESSENGER_TEMPLATE]: {
    type: TEMPLATE_TYPE.MESSENGER_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.MESSENGER_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.MESSENGER_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.MESSENGER_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.MESSENGER_TEMPLATE],
    group: 'COMMUNICATION',
    description: 'মেসেঞ্জার বার্তা পাঠানোর জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.WEBHOOK_TEMPLATE]: {
    type: TEMPLATE_TYPE.WEBHOOK_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.WEBHOOK_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.WEBHOOK_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.WEBHOOK_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.WEBHOOK_TEMPLATE],
    group: 'INTEGRATION',
    description: 'ওয়েবহুক পাঠানোর জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.API_TEMPLATE]: {
    type: TEMPLATE_TYPE.API_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.API_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.API_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.API_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.API_TEMPLATE],
    group: 'INTEGRATION',
    description: 'এপিআই কলের জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.SIGNATURE_TEMPLATE]: {
    type: TEMPLATE_TYPE.SIGNATURE_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.SIGNATURE_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.SIGNATURE_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.SIGNATURE_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.SIGNATURE_TEMPLATE],
    group: 'DESIGN',
    description: 'সিগনেচার তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.FOOTER_TEMPLATE]: {
    type: TEMPLATE_TYPE.FOOTER_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.FOOTER_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.FOOTER_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.FOOTER_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.FOOTER_TEMPLATE],
    group: 'DESIGN',
    description: 'ফুটার তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.HEADER_TEMPLATE]: {
    type: TEMPLATE_TYPE.HEADER_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.HEADER_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.HEADER_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.HEADER_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.HEADER_TEMPLATE],
    group: 'DESIGN',
    description: 'হেডার তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.LAYOUT_TEMPLATE]: {
    type: TEMPLATE_TYPE.LAYOUT_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.LAYOUT_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.LAYOUT_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.LAYOUT_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.LAYOUT_TEMPLATE],
    group: 'DESIGN',
    description: 'লেআউট তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.LANDING_PAGE_TEMPLATE]: {
    type: TEMPLATE_TYPE.LANDING_PAGE_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.LANDING_PAGE_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.LANDING_PAGE_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.LANDING_PAGE_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.LANDING_PAGE_TEMPLATE],
    group: 'DESIGN',
    description: 'ল্যান্ডিং পেজ তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.KB_ARTICLE_TEMPLATE]: {
    type: TEMPLATE_TYPE.KB_ARTICLE_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.KB_ARTICLE_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.KB_ARTICLE_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.KB_ARTICLE_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.KB_ARTICLE_TEMPLATE],
    group: 'KNOWLEDGE',
    description: 'নলেজ বেস আর্টিকেল তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.FAQ_TEMPLATE]: {
    type: TEMPLATE_TYPE.FAQ_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.FAQ_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.FAQ_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.FAQ_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.FAQ_TEMPLATE],
    group: 'KNOWLEDGE',
    description: 'এফএকিউ তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.TUTORIAL_TEMPLATE]: {
    type: TEMPLATE_TYPE.TUTORIAL_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.TUTORIAL_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.TUTORIAL_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.TUTORIAL_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.TUTORIAL_TEMPLATE],
    group: 'KNOWLEDGE',
    description: 'টিউটোরিয়াল তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.ONBOARDING_TEMPLATE]: {
    type: TEMPLATE_TYPE.ONBOARDING_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.ONBOARDING_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.ONBOARDING_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.ONBOARDING_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.ONBOARDING_TEMPLATE],
    group: 'PROCESS',
    description: 'অনবোর্ডিং প্রক্রিয়ার জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.WELCOME_TEMPLATE]: {
    type: TEMPLATE_TYPE.WELCOME_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.WELCOME_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.WELCOME_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.WELCOME_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.WELCOME_TEMPLATE],
    group: 'PROCESS',
    description: 'স্বাগতম বার্তার জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.FEEDBACK_TEMPLATE]: {
    type: TEMPLATE_TYPE.FEEDBACK_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.FEEDBACK_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.FEEDBACK_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.FEEDBACK_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.FEEDBACK_TEMPLATE],
    group: 'FEEDBACK',
    description: 'ফিডব্যাক সংগ্রহের জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.COMPLAINT_TEMPLATE]: {
    type: TEMPLATE_TYPE.COMPLAINT_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.COMPLAINT_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.COMPLAINT_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.COMPLAINT_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.COMPLAINT_TEMPLATE],
    group: 'FEEDBACK',
    description: 'অভিযোগ সংগ্রহের জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.ESCALATION_TEMPLATE]: {
    type: TEMPLATE_TYPE.ESCALATION_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.ESCALATION_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.ESCALATION_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.ESCALATION_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.ESCALATION_TEMPLATE],
    group: 'PROCESS',
    description: 'এস্কেলেশন প্রক্রিয়ার জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.FOLLOW_UP_TEMPLATE]: {
    type: TEMPLATE_TYPE.FOLLOW_UP_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.FOLLOW_UP_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.FOLLOW_UP_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.FOLLOW_UP_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.FOLLOW_UP_TEMPLATE],
    group: 'PROCESS',
    description: 'ফলো-আপ প্রক্রিয়ার জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.REMINDER_TEMPLATE]: {
    type: TEMPLATE_TYPE.REMINDER_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.REMINDER_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.REMINDER_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.REMINDER_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.REMINDER_TEMPLATE],
    group: 'PROCESS',
    description: 'রিমাইন্ডার প্রক্রিয়ার জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.THANK_YOU_TEMPLATE]: {
    type: TEMPLATE_TYPE.THANK_YOU_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.THANK_YOU_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.THANK_YOU_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.THANK_YOU_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.THANK_YOU_TEMPLATE],
    group: 'COMMUNICATION',
    description: 'ধন্যবাদ বার্তার জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.APOLOGY_TEMPLATE]: {
    type: TEMPLATE_TYPE.APOLOGY_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.APOLOGY_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.APOLOGY_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.APOLOGY_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.APOLOGY_TEMPLATE],
    group: 'COMMUNICATION',
    description: 'ক্ষমা প্রার্থনা বার্তার জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.CONFIRMATION_TEMPLATE]: {
    type: TEMPLATE_TYPE.CONFIRMATION_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.CONFIRMATION_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.CONFIRMATION_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.CONFIRMATION_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.CONFIRMATION_TEMPLATE],
    group: 'COMMUNICATION',
    description: 'নিশ্চিতকরণ বার্তার জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.INVOICE_TEMPLATE]: {
    type: TEMPLATE_TYPE.INVOICE_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.INVOICE_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.INVOICE_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.INVOICE_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.INVOICE_TEMPLATE],
    group: 'FINANCIAL',
    description: 'ইনভয়েস তৈরির জন্য টেমপ্লেট',
  },
  [TEMPLATE_TYPE.RECEIPT_TEMPLATE]: {
    type: TEMPLATE_TYPE.RECEIPT_TEMPLATE,
    displayName: TEMPLATE_TYPE_DISPLAY_NAMES[TEMPLATE_TYPE.RECEIPT_TEMPLATE],
    icon: TEMPLATE_TYPE_ICONS[TEMPLATE_TYPE.RECEIPT_TEMPLATE],
    color: TEMPLATE_TYPE_COLORS[TEMPLATE_TYPE.RECEIPT_TEMPLATE],
    category: TEMPLATE_TYPE_CATEGORIES[TEMPLATE_TYPE.RECEIPT_TEMPLATE],
    group: 'FINANCIAL',
    description: 'রসিদ তৈরির জন্য টেমপ্লেট',
  },
};

/**
 * টেমপ্লেট টাইপ গ্রুপ কনফিগারেশন
 */
export const TEMPLATE_TYPE_GROUP_CONFIGS: Record<
  TemplateTypeGroup,
  {
    group: TemplateTypeGroup;
    displayName: string;
    icon: string;
    color: string;
    types: readonly TemplateType[];
    description?: string;
  }
> = {
  COMMUNICATION: {
    group: 'COMMUNICATION',
    displayName: 'যোগাযোগ',
    icon: 'message-circle',
    color: '#3498db',
    types: [
      'email_template',
      'sms_template',
      'push_template',
      'slack_template',
      'teams_template',
      'whatsapp_template',
      'messenger_template',
      'thank_you_template',
      'apology_template',
      'confirmation_template',
    ] as const,
    description: 'যোগাযোগ সম্পর্কিত টেমপ্লেট',
  },
  TICKET: {
    group: 'TICKET',
    displayName: 'টিকেট',
    icon: 'ticket',
    color: '#e67e22',
    types: ['ticket_template'] as const,
    description: 'টিকেট সম্পর্কিত টেমপ্লেট',
  },
  RESPONSE: {
    group: 'RESPONSE',
    displayName: 'রেসপন্স',
    icon: 'message-square',
    color: '#1abc9c',
    types: ['response_template'] as const,
    description: 'রেসপন্স সম্পর্কিত টেমপ্লেট',
  },
  SURVEY: {
    group: 'SURVEY',
    displayName: 'জরিপ',
    icon: 'clipboard',
    color: '#2980b9',
    types: ['survey_template'] as const,
    description: 'জরিপ সম্পর্কিত টেমপ্লেট',
  },
  REPORTING: {
    group: 'REPORTING',
    displayName: 'রিপোর্টিং',
    icon: 'file-text',
    color: '#e74c3c',
    types: ['report_template'] as const,
    description: 'রিপোর্ট সম্পর্কিত টেমপ্লেট',
  },
  CHATBOT: {
    group: 'CHATBOT',
    displayName: 'চ্যাটবট',
    icon: 'bot',
    color: '#3498db',
    types: ['chatbot_template'] as const,
    description: 'চ্যাটবট সম্পর্কিত টেমপ্লেট',
  },
  SCRIPT: {
    group: 'SCRIPT',
    displayName: 'স্ক্রিপ্ট',
    icon: 'code',
    color: '#2c3e50',
    types: ['script_template'] as const,
    description: 'স্ক্রিপ্ট সম্পর্কিত টেমপ্লেট',
  },
  DOCUMENT: {
    group: 'DOCUMENT',
    displayName: 'ডকুমেন্ট',
    icon: 'file',
    color: '#95a5a6',
    types: ['document_template'] as const,
    description: 'ডকুমেন্ট সম্পর্কিত টেমপ্লেট',
  },
  NOTIFICATION: {
    group: 'NOTIFICATION',
    displayName: 'নোটিফিকেশন',
    icon: 'bell',
    color: '#f39c12',
    types: ['notification_template'] as const,
    description: 'নোটিফিকেশন সম্পর্কিত টেমপ্লেট',
  },
  AUTOMATION: {
    group: 'AUTOMATION',
    displayName: 'অটোমেশন',
    icon: 'zap',
    color: '#2ecc71',
    types: ['automation_template'] as const,
    description: 'অটোমেশন সম্পর্কিত টেমপ্লেট',
  },
  WORKFLOW: {
    group: 'WORKFLOW',
    displayName: 'ওয়ার্কফ্লো',
    icon: 'workflow',
    color: '#1abc9c',
    types: ['workflow_template'] as const,
    description: 'ওয়ার্কফ্লো সম্পর্কিত টেমপ্লেট',
  },
  FORM: {
    group: 'FORM',
    displayName: 'ফর্ম',
    icon: 'form-input',
    color: '#9b59b6',
    types: ['form_template'] as const,
    description: 'ফর্ম সম্পর্কিত টেমপ্লেট',
  },
  KNOWLEDGE: {
    group: 'KNOWLEDGE',
    displayName: 'নলেজ',
    icon: 'book',
    color: '#3498db',
    types: [
      'article_template',
      'kb_article_template',
      'faq_template',
      'tutorial_template',
    ] as const,
    description: 'নলেজ বেস সম্পর্কিত টেমপ্লেট',
  },
  INTEGRATION: {
    group: 'INTEGRATION',
    displayName: 'ইন্টিগ্রেশন',
    icon: 'link',
    color: '#8e44ad',
    types: ['webhook_template', 'api_template'] as const,
    description: 'ইন্টিগ্রেশন সম্পর্কিত টেমপ্লেট',
  },
  DESIGN: {
    group: 'DESIGN',
    displayName: 'ডিজাইন',
    icon: 'pen-tool',
    color: '#34495e',
    types: [
      'signature_template',
      'footer_template',
      'header_template',
      'layout_template',
      'landing_page_template',
    ] as const,
    description: 'ডিজাইন সম্পর্কিত টেমপ্লেট',
  },
  PROCESS: {
    group: 'PROCESS',
    displayName: 'প্রক্রিয়া',
    icon: 'refresh-cw',
    color: '#1abc9c',
    types: [
      'onboarding_template',
      'welcome_template',
      'escalation_template',
      'follow_up_template',
      'reminder_template',
    ] as const,
    description: 'প্রক্রিয়া সম্পর্কিত টেমপ্লেট',
  },
  FEEDBACK: {
    group: 'FEEDBACK',
    displayName: 'ফিডব্যাক',
    icon: 'message-square',
    color: '#8e44ad',
    types: ['feedback_template', 'complaint_template'] as const,
    description: 'ফিডব্যাক সম্পর্কিত টেমপ্লেট',
  },
  FINANCIAL: {
    group: 'FINANCIAL',
    displayName: 'আর্থিক',
    icon: 'dollar-sign',
    color: '#2c3e50',
    types: ['invoice_template', 'receipt_template'] as const,
    description: 'আর্থিক সম্পর্কিত টেমপ্লেট',
  },
};

/**
 * টেমপ্লেট টাইপ স্ট্যাটাস
 */
export const TEMPLATE_TYPE_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  DEPRECATED: 'deprecated',
  BETA: 'beta',
} as const;

export type TemplateTypeStatus = (typeof TEMPLATE_TYPE_STATUS)[keyof typeof TEMPLATE_TYPE_STATUS];
