/**
 * সাপোর্ট এজেন্টের বিভিন্ন রোল সংক্রান্ত কনস্ট্যান্টসমূহ
 */

/**
 * এজেন্ট রোল
 */
export const AGENT_ROLE = {
  TIER_1_AGENT: 'tier_1_agent',
  TIER_2_AGENT: 'tier_2_agent',
  TIER_3_AGENT: 'tier_3_agent',
  TEAM_LEAD: 'team_lead',
  SUPERVISOR: 'supervisor',
  MANAGER: 'manager',
  ADMIN: 'admin',
  TRAINER: 'trainer',
  QUALITY_ANALYST: 'quality_analyst',
  ESCALATION_SPECIALIST: 'escalation_specialist',
  JUNIOR_AGENT: 'junior_agent',
  SENIOR_AGENT: 'senior_agent',
  EXPERT_AGENT: 'expert_agent',
  SHIFT_LEAD: 'shift_lead',
  OPERATIONS_MANAGER: 'operations_manager',
  DIRECTOR: 'director',
  VP: 'vp',
  CTO: 'cto',
  CEO: 'ceo',
} as const;

/**
 * এজেন্ট রোলের ডিসপ্লে নাম
 */
export const AGENT_ROLE_DISPLAY_NAMES = {
  [AGENT_ROLE.TIER_1_AGENT]: 'টায়ার ১ এজেন্ট',
  [AGENT_ROLE.TIER_2_AGENT]: 'টায়ার ২ এজেন্ট',
  [AGENT_ROLE.TIER_3_AGENT]: 'টায়ার ৩ এজেন্ট',
  [AGENT_ROLE.TEAM_LEAD]: 'টিম লিড',
  [AGENT_ROLE.SUPERVISOR]: 'সুপারভাইজার',
  [AGENT_ROLE.MANAGER]: 'ম্যানেজার',
  [AGENT_ROLE.ADMIN]: 'অ্যাডমিন',
  [AGENT_ROLE.TRAINER]: 'ট্রেইনার',
  [AGENT_ROLE.QUALITY_ANALYST]: 'কোয়ালিটি অ্যানালিস্ট',
  [AGENT_ROLE.ESCALATION_SPECIALIST]: 'এস্কেলেশন স্পেশালিস্ট',
  [AGENT_ROLE.JUNIOR_AGENT]: 'জুনিয়র এজেন্ট',
  [AGENT_ROLE.SENIOR_AGENT]: 'সিনিয়র এজেন্ট',
  [AGENT_ROLE.EXPERT_AGENT]: 'এক্সপার্ট এজেন্ট',
  [AGENT_ROLE.SHIFT_LEAD]: 'শিফট লিড',
  [AGENT_ROLE.OPERATIONS_MANAGER]: 'অপারেশনস ম্যানেজার',
  [AGENT_ROLE.DIRECTOR]: 'ডিরেক্টর',
  [AGENT_ROLE.VP]: 'ভিপি',
  [AGENT_ROLE.CTO]: 'সিটিও',
  [AGENT_ROLE.CEO]: 'সিইও',
} as const;

/**
 * এজেন্ট রোলের আইকন (অনুষঙ্গিক নাম)
 */
export const AGENT_ROLE_ICONS = {
  [AGENT_ROLE.TIER_1_AGENT]: 'user',
  [AGENT_ROLE.TIER_2_AGENT]: 'user-check',
  [AGENT_ROLE.TIER_3_AGENT]: 'user-star',
  [AGENT_ROLE.TEAM_LEAD]: 'users',
  [AGENT_ROLE.SUPERVISOR]: 'user-plus',
  [AGENT_ROLE.MANAGER]: 'user-cog',
  [AGENT_ROLE.ADMIN]: 'shield',
  [AGENT_ROLE.TRAINER]: 'book',
  [AGENT_ROLE.QUALITY_ANALYST]: 'clipboard',
  [AGENT_ROLE.ESCALATION_SPECIALIST]: 'arrow-up-circle',
  [AGENT_ROLE.JUNIOR_AGENT]: 'user',
  [AGENT_ROLE.SENIOR_AGENT]: 'user-check',
  [AGENT_ROLE.EXPERT_AGENT]: 'user-star',
  [AGENT_ROLE.SHIFT_LEAD]: 'clock',
  [AGENT_ROLE.OPERATIONS_MANAGER]: 'briefcase',
  [AGENT_ROLE.DIRECTOR]: 'briefcase',
  [AGENT_ROLE.VP]: 'briefcase',
  [AGENT_ROLE.CTO]: 'cpu',
  [AGENT_ROLE.CEO]: 'briefcase',
} as const;

/**
 * এজেন্ট রোলের রঙের কোড (হেক্স)
 */
export const AGENT_ROLE_COLORS = {
  [AGENT_ROLE.TIER_1_AGENT]: '#3498db',
  [AGENT_ROLE.TIER_2_AGENT]: '#2ecc71',
  [AGENT_ROLE.TIER_3_AGENT]: '#9b59b6',
  [AGENT_ROLE.TEAM_LEAD]: '#f39c12',
  [AGENT_ROLE.SUPERVISOR]: '#e67e22',
  [AGENT_ROLE.MANAGER]: '#1abc9c',
  [AGENT_ROLE.ADMIN]: '#e74c3c',
  [AGENT_ROLE.TRAINER]: '#2980b9',
  [AGENT_ROLE.QUALITY_ANALYST]: '#8e44ad',
  [AGENT_ROLE.ESCALATION_SPECIALIST]: '#c0392b',
  [AGENT_ROLE.JUNIOR_AGENT]: '#3498db',
  [AGENT_ROLE.SENIOR_AGENT]: '#27ae60',
  [AGENT_ROLE.EXPERT_AGENT]: '#8e44ad',
  [AGENT_ROLE.SHIFT_LEAD]: '#f39c12',
  [AGENT_ROLE.OPERATIONS_MANAGER]: '#1abc9c',
  [AGENT_ROLE.DIRECTOR]: '#2c3e50',
  [AGENT_ROLE.VP]: '#34495e',
  [AGENT_ROLE.CTO]: '#e74c3c',
  [AGENT_ROLE.CEO]: '#2c3e50',
} as const;

/**
 * এজেন্ট রোলের টায়ার লেভেল
 */
export const AGENT_ROLE_TIER_LEVEL = {
  [AGENT_ROLE.TIER_1_AGENT]: 1,
  [AGENT_ROLE.TIER_2_AGENT]: 2,
  [AGENT_ROLE.TIER_3_AGENT]: 3,
  [AGENT_ROLE.JUNIOR_AGENT]: 1,
  [AGENT_ROLE.SENIOR_AGENT]: 2,
  [AGENT_ROLE.EXPERT_AGENT]: 3,
  [AGENT_ROLE.TEAM_LEAD]: 4,
  [AGENT_ROLE.SHIFT_LEAD]: 4,
  [AGENT_ROLE.SUPERVISOR]: 5,
  [AGENT_ROLE.MANAGER]: 6,
  [AGENT_ROLE.OPERATIONS_MANAGER]: 7,
  [AGENT_ROLE.ADMIN]: 8,
  [AGENT_ROLE.TRAINER]: 4,
  [AGENT_ROLE.QUALITY_ANALYST]: 4,
  [AGENT_ROLE.ESCALATION_SPECIALIST]: 5,
  [AGENT_ROLE.DIRECTOR]: 8,
  [AGENT_ROLE.VP]: 9,
  [AGENT_ROLE.CTO]: 10,
  [AGENT_ROLE.CEO]: 10,
} as const;

/**
 * এজেন্ট রোলের ডিফল্ট পারমিশন সেট
 */
export const AGENT_ROLE_PERMISSIONS = {
  [AGENT_ROLE.TIER_1_AGENT]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
  ] as const,
  [AGENT_ROLE.TIER_2_AGENT]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
    'create_knowledge_base',
    'escalate_tickets',
    'view_analytics',
  ] as const,
  [AGENT_ROLE.TIER_3_AGENT]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
    'create_knowledge_base',
    'escalate_tickets',
    'view_analytics',
    'assign_tickets',
    'manage_sla',
    'view_reports',
  ] as const,
  [AGENT_ROLE.TEAM_LEAD]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
    'create_knowledge_base',
    'escalate_tickets',
    'view_analytics',
    'assign_tickets',
    'manage_sla',
    'view_reports',
    'manage_team',
    'generate_reports',
  ] as const,
  [AGENT_ROLE.SUPERVISOR]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
    'create_knowledge_base',
    'escalate_tickets',
    'view_analytics',
    'assign_tickets',
    'manage_sla',
    'view_reports',
    'manage_team',
    'generate_reports',
    'manage_shift',
    'approve_leave',
  ] as const,
  [AGENT_ROLE.MANAGER]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
    'create_knowledge_base',
    'escalate_tickets',
    'view_analytics',
    'assign_tickets',
    'manage_sla',
    'view_reports',
    'manage_team',
    'generate_reports',
    'manage_shift',
    'approve_leave',
    'manage_budget',
    'manage_performance',
  ] as const,
  [AGENT_ROLE.ADMIN]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
    'create_knowledge_base',
    'escalate_tickets',
    'view_analytics',
    'assign_tickets',
    'manage_sla',
    'view_reports',
    'manage_team',
    'generate_reports',
    'manage_shift',
    'approve_leave',
    'manage_budget',
    'manage_performance',
    'manage_users',
    'manage_roles',
    'manage_system',
  ] as const,
  [AGENT_ROLE.TRAINER]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
    'create_knowledge_base',
    'manage_training',
    'view_training_analytics',
    'create_training_materials',
  ] as const,
  [AGENT_ROLE.QUALITY_ANALYST]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
    'view_analytics',
    'view_reports',
    'quality_assurance',
    'view_qa_scores',
    'manage_qa',
  ] as const,
  [AGENT_ROLE.ESCALATION_SPECIALIST]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
    'create_knowledge_base',
    'escalate_tickets',
    'view_analytics',
    'assign_tickets',
    'manage_sla',
    'expert_access',
  ] as const,
  [AGENT_ROLE.JUNIOR_AGENT]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
  ] as const,
  [AGENT_ROLE.SENIOR_AGENT]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
    'create_knowledge_base',
    'escalate_tickets',
    'view_analytics',
  ] as const,
  [AGENT_ROLE.EXPERT_AGENT]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
    'create_knowledge_base',
    'escalate_tickets',
    'view_analytics',
    'assign_tickets',
    'manage_sla',
    'view_reports',
  ] as const,
  [AGENT_ROLE.SHIFT_LEAD]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
    'create_knowledge_base',
    'escalate_tickets',
    'view_analytics',
    'assign_tickets',
    'manage_sla',
    'view_reports',
    'manage_shift',
  ] as const,
  [AGENT_ROLE.OPERATIONS_MANAGER]: [
    'view_tickets',
    'reply_tickets',
    'view_knowledge_base',
    'search_knowledge_base',
    'create_knowledge_base',
    'escalate_tickets',
    'view_analytics',
    'assign_tickets',
    'manage_sla',
    'view_reports',
    'manage_team',
    'generate_reports',
    'manage_shift',
    'approve_leave',
    'manage_budget',
    'manage_performance',
    'manage_operations',
  ] as const,
  [AGENT_ROLE.DIRECTOR]: [
    'view_tickets',
    'view_knowledge_base',
    'view_analytics',
    'view_reports',
    'generate_reports',
    'manage_budget',
    'manage_performance',
    'manage_operations',
    'strategic_planning',
  ] as const,
  [AGENT_ROLE.VP]: [
    'view_tickets',
    'view_knowledge_base',
    'view_analytics',
    'view_reports',
    'generate_reports',
    'manage_budget',
    'manage_performance',
    'manage_operations',
    'strategic_planning',
    'manage_department',
  ] as const,
  [AGENT_ROLE.CTO]: [
    'view_tickets',
    'view_knowledge_base',
    'view_analytics',
    'view_reports',
    'generate_reports',
    'manage_budget',
    'manage_performance',
    'manage_operations',
    'strategic_planning',
    'manage_technology',
  ] as const,
  [AGENT_ROLE.CEO]: [
    'view_tickets',
    'view_knowledge_base',
    'view_analytics',
    'view_reports',
    'generate_reports',
    'manage_budget',
    'manage_performance',
    'manage_operations',
    'strategic_planning',
    'manage_company',
  ] as const,
} as const;

/**
 * এজেন্ট রোল গ্রুপ
 */
export const AGENT_ROLE_GROUPS = {
  AGENT: [
    'tier_1_agent',
    'tier_2_agent',
    'tier_3_agent',
    'junior_agent',
    'senior_agent',
    'expert_agent',
  ],
  LEADERSHIP: [
    'team_lead',
    'shift_lead',
    'supervisor',
    'manager',
    'operations_manager',
    'director',
    'vp',
  ],
  EXECUTIVE: ['cto', 'ceo'],
  SPECIALIZED: ['trainer', 'quality_analyst', 'escalation_specialist'],
  ADMIN: ['admin'],
} as const;

export type AgentRole = (typeof AGENT_ROLE)[keyof typeof AGENT_ROLE];
export type AgentRoleDisplayNames = typeof AGENT_ROLE_DISPLAY_NAMES;
export type AgentRoleIcons = typeof AGENT_ROLE_ICONS;
export type AgentRoleColors = typeof AGENT_ROLE_COLORS;
export type AgentRoleTierLevel = typeof AGENT_ROLE_TIER_LEVEL;
export type AgentRolePermissions = typeof AGENT_ROLE_PERMISSIONS;
export type AgentRoleGroups = typeof AGENT_ROLE_GROUPS;

export type AgentRoleGroup = keyof typeof AGENT_ROLE_GROUPS;

export interface AgentRoleConfig {
  role: AgentRole;
  displayName: string;
  icon: string;
  color: string;
  tierLevel: number;
  permissions: readonly string[];
  group: AgentRoleGroup;
  description?: string;
  maxTickets?: number;
  escalationLevel?: number;
}

/**
 * এজেন্ট রোল কনফিগারেশন অবজেক্ট
 */
export const AGENT_ROLE_CONFIGS: Record<AgentRole, AgentRoleConfig> = {
  [AGENT_ROLE.TIER_1_AGENT]: {
    role: AGENT_ROLE.TIER_1_AGENT,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.TIER_1_AGENT],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.TIER_1_AGENT],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.TIER_1_AGENT],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.TIER_1_AGENT],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.TIER_1_AGENT],
    group: 'AGENT',
    description: 'বেসিক সাপোর্ট এজেন্ট',
    maxTickets: 10,
    escalationLevel: 1,
  },
  [AGENT_ROLE.TIER_2_AGENT]: {
    role: AGENT_ROLE.TIER_2_AGENT,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.TIER_2_AGENT],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.TIER_2_AGENT],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.TIER_2_AGENT],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.TIER_2_AGENT],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.TIER_2_AGENT],
    group: 'AGENT',
    description: 'অ্যাডভান্সড সাপোর্ট এজেন্ট',
    maxTickets: 8,
    escalationLevel: 2,
  },
  [AGENT_ROLE.TIER_3_AGENT]: {
    role: AGENT_ROLE.TIER_3_AGENT,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.TIER_3_AGENT],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.TIER_3_AGENT],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.TIER_3_AGENT],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.TIER_3_AGENT],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.TIER_3_AGENT],
    group: 'AGENT',
    description: 'এক্সপার্ট সাপোর্ট এজেন্ট',
    maxTickets: 6,
    escalationLevel: 3,
  },
  [AGENT_ROLE.TEAM_LEAD]: {
    role: AGENT_ROLE.TEAM_LEAD,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.TEAM_LEAD],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.TEAM_LEAD],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.TEAM_LEAD],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.TEAM_LEAD],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.TEAM_LEAD],
    group: 'LEADERSHIP',
    description: 'টিম লিডার',
    maxTickets: 5,
    escalationLevel: 4,
  },
  [AGENT_ROLE.SUPERVISOR]: {
    role: AGENT_ROLE.SUPERVISOR,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.SUPERVISOR],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.SUPERVISOR],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.SUPERVISOR],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.SUPERVISOR],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.SUPERVISOR],
    group: 'LEADERSHIP',
    description: 'সুপারভাইজার',
    maxTickets: 3,
    escalationLevel: 5,
  },
  [AGENT_ROLE.MANAGER]: {
    role: AGENT_ROLE.MANAGER,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.MANAGER],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.MANAGER],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.MANAGER],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.MANAGER],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.MANAGER],
    group: 'LEADERSHIP',
    description: 'ম্যানেজার',
    maxTickets: 2,
    escalationLevel: 6,
  },
  [AGENT_ROLE.ADMIN]: {
    role: AGENT_ROLE.ADMIN,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.ADMIN],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.ADMIN],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.ADMIN],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.ADMIN],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.ADMIN],
    group: 'ADMIN',
    description: 'সিস্টেম অ্যাডমিনিস্ট্রেটর',
    maxTickets: 0,
    escalationLevel: 8,
  },
  [AGENT_ROLE.TRAINER]: {
    role: AGENT_ROLE.TRAINER,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.TRAINER],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.TRAINER],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.TRAINER],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.TRAINER],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.TRAINER],
    group: 'SPECIALIZED',
    description: 'প্রশিক্ষক',
    maxTickets: 5,
    escalationLevel: 4,
  },
  [AGENT_ROLE.QUALITY_ANALYST]: {
    role: AGENT_ROLE.QUALITY_ANALYST,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.QUALITY_ANALYST],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.QUALITY_ANALYST],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.QUALITY_ANALYST],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.QUALITY_ANALYST],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.QUALITY_ANALYST],
    group: 'SPECIALIZED',
    description: 'গুণমান বিশ্লেষক',
    maxTickets: 0,
    escalationLevel: 4,
  },
  [AGENT_ROLE.ESCALATION_SPECIALIST]: {
    role: AGENT_ROLE.ESCALATION_SPECIALIST,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.ESCALATION_SPECIALIST],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.ESCALATION_SPECIALIST],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.ESCALATION_SPECIALIST],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.ESCALATION_SPECIALIST],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.ESCALATION_SPECIALIST],
    group: 'SPECIALIZED',
    description: 'এস্কেলেশন বিশেষজ্ঞ',
    maxTickets: 3,
    escalationLevel: 5,
  },
  [AGENT_ROLE.JUNIOR_AGENT]: {
    role: AGENT_ROLE.JUNIOR_AGENT,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.JUNIOR_AGENT],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.JUNIOR_AGENT],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.JUNIOR_AGENT],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.JUNIOR_AGENT],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.JUNIOR_AGENT],
    group: 'AGENT',
    description: 'জুনিয়র এজেন্ট',
    maxTickets: 12,
    escalationLevel: 1,
  },
  [AGENT_ROLE.SENIOR_AGENT]: {
    role: AGENT_ROLE.SENIOR_AGENT,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.SENIOR_AGENT],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.SENIOR_AGENT],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.SENIOR_AGENT],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.SENIOR_AGENT],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.SENIOR_AGENT],
    group: 'AGENT',
    description: 'সিনিয়র এজেন্ট',
    maxTickets: 8,
    escalationLevel: 2,
  },
  [AGENT_ROLE.EXPERT_AGENT]: {
    role: AGENT_ROLE.EXPERT_AGENT,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.EXPERT_AGENT],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.EXPERT_AGENT],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.EXPERT_AGENT],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.EXPERT_AGENT],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.EXPERT_AGENT],
    group: 'AGENT',
    description: 'এক্সপার্ট এজেন্ট',
    maxTickets: 6,
    escalationLevel: 3,
  },
  [AGENT_ROLE.SHIFT_LEAD]: {
    role: AGENT_ROLE.SHIFT_LEAD,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.SHIFT_LEAD],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.SHIFT_LEAD],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.SHIFT_LEAD],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.SHIFT_LEAD],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.SHIFT_LEAD],
    group: 'LEADERSHIP',
    description: 'শিফট লিড',
    maxTickets: 4,
    escalationLevel: 4,
  },
  [AGENT_ROLE.OPERATIONS_MANAGER]: {
    role: AGENT_ROLE.OPERATIONS_MANAGER,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.OPERATIONS_MANAGER],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.OPERATIONS_MANAGER],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.OPERATIONS_MANAGER],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.OPERATIONS_MANAGER],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.OPERATIONS_MANAGER],
    group: 'LEADERSHIP',
    description: 'অপারেশনস ম্যানেজার',
    maxTickets: 1,
    escalationLevel: 7,
  },
  [AGENT_ROLE.DIRECTOR]: {
    role: AGENT_ROLE.DIRECTOR,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.DIRECTOR],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.DIRECTOR],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.DIRECTOR],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.DIRECTOR],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.DIRECTOR],
    group: 'LEADERSHIP',
    description: 'ডিরেক্টর',
    maxTickets: 0,
    escalationLevel: 8,
  },
  [AGENT_ROLE.VP]: {
    role: AGENT_ROLE.VP,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.VP],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.VP],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.VP],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.VP],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.VP],
    group: 'LEADERSHIP',
    description: 'ভাইস প্রেসিডেন্ট',
    maxTickets: 0,
    escalationLevel: 9,
  },
  [AGENT_ROLE.CTO]: {
    role: AGENT_ROLE.CTO,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.CTO],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.CTO],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.CTO],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.CTO],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.CTO],
    group: 'EXECUTIVE',
    description: 'প্রধান প্রযুক্তি কর্মকর্তা',
    maxTickets: 0,
    escalationLevel: 10,
  },
  [AGENT_ROLE.CEO]: {
    role: AGENT_ROLE.CEO,
    displayName: AGENT_ROLE_DISPLAY_NAMES[AGENT_ROLE.CEO],
    icon: AGENT_ROLE_ICONS[AGENT_ROLE.CEO],
    color: AGENT_ROLE_COLORS[AGENT_ROLE.CEO],
    tierLevel: AGENT_ROLE_TIER_LEVEL[AGENT_ROLE.CEO],
    permissions: AGENT_ROLE_PERMISSIONS[AGENT_ROLE.CEO],
    group: 'EXECUTIVE',
    description: 'প্রধান নির্বাহী কর্মকর্তা',
    maxTickets: 0,
    escalationLevel: 10,
  },
};

/**
 * এজেন্ট রোল গ্রুপ কনফিগারেশন
 */
export const AGENT_ROLE_GROUP_CONFIGS: Record<
  AgentRoleGroup,
  {
    group: AgentRoleGroup;
    displayName: string;
    icon: string;
    color: string;
    roles: readonly AgentRole[];
    description?: string;
  }
> = {
  AGENT: {
    group: 'AGENT',
    displayName: 'এজেন্ট',
    icon: 'user',
    color: '#3498db',
    roles: [
      'tier_1_agent',
      'tier_2_agent',
      'tier_3_agent',
      'junior_agent',
      'senior_agent',
      'expert_agent',
    ] as const,
    description: 'সাপোর্ট এজেন্ট রোলসমূহ',
  },
  LEADERSHIP: {
    group: 'LEADERSHIP',
    displayName: 'নেতৃত্ব',
    icon: 'users',
    color: '#f39c12',
    roles: [
      'team_lead',
      'shift_lead',
      'supervisor',
      'manager',
      'operations_manager',
      'director',
      'vp',
    ] as const,
    description: 'নেতৃত্বের রোলসমূহ',
  },
  EXECUTIVE: {
    group: 'EXECUTIVE',
    displayName: 'নির্বাহী',
    icon: 'briefcase',
    color: '#2c3e50',
    roles: ['cto', 'ceo'] as const,
    description: 'নির্বাহী রোলসমূহ',
  },
  SPECIALIZED: {
    group: 'SPECIALIZED',
    displayName: 'বিশেষায়িত',
    icon: 'star',
    color: '#8e44ad',
    roles: ['trainer', 'quality_analyst', 'escalation_specialist'] as const,
    description: 'বিশেষায়িত রোলসমূহ',
  },
  ADMIN: {
    group: 'ADMIN',
    displayName: 'অ্যাডমিন',
    icon: 'shield',
    color: '#e74c3c',
    roles: ['admin'] as const,
    description: 'অ্যাডমিনিস্ট্রেটর রোল',
  },
};

/**
 * এজেন্ট রোল স্ট্যাটাস
 */
export const AGENT_ROLE_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  DEPRECATED: 'deprecated',
  BETA: 'beta',
} as const;

export type AgentRoleStatus = (typeof AGENT_ROLE_STATUS)[keyof typeof AGENT_ROLE_STATUS];
