/**
 * সাপোর্ট অটোমেশন ট্রিগার সংক্রান্ত কনস্ট্যান্টসমূহ
 */

/**
 * অটোমেশন ট্রিগার টাইপ
 */
export const AUTOMATION_TRIGGER = {
  TICKET_CREATED: 'ticket_created',
  TICKET_UPDATED: 'ticket_updated',
  TICKET_ASSIGNED: 'ticket_assigned',
  TICKET_RESOLVED: 'ticket_resolved',
  TICKET_CLOSED: 'ticket_closed',
  TICKET_ESCALATED: 'ticket_escalated',
  TIME_BASED: 'time_based',
  EVENT_BASED: 'event_based',
  CUSTOM_TRIGGER: 'custom_trigger',
  CONDITION_MET: 'condition_met',
  SCHEDULED: 'scheduled',
  API_CALL: 'api_call',
  SLA_BREACH: 'sla_breach',
  PRIORITY_CHANGED: 'priority_changed',
  STATUS_CHANGED: 'status_changed',
  CATEGORY_CHANGED: 'category_changed',
  TAG_ADDED: 'tag_added',
  TAG_REMOVED: 'tag_removed',
  COMMENT_ADDED: 'comment_added',
  ATTACHMENT_ADDED: 'attachment_added',
  USER_RESPONDED: 'user_responded',
  AGENT_RESPONDED: 'agent_responded',
  ESCALATION_PENDING: 'escalation_pending',
  FOLLOW_UP_REQUIRED: 'follow_up_required',
  SATISFACTION_RECEIVED: 'satisfaction_received',
  BATCH_PROCESS: 'batch_process',
  MANUAL_TRIGGER: 'manual_trigger',
  WEBHOOK: 'webhook',
} as const;

/**
 * অটোমেশন ট্রিগারের ডিসপ্লে নাম
 */
export const AUTOMATION_TRIGGER_DISPLAY_NAMES = {
  [AUTOMATION_TRIGGER.TICKET_CREATED]: 'টিকেট তৈরি',
  [AUTOMATION_TRIGGER.TICKET_UPDATED]: 'টিকেট আপডেট',
  [AUTOMATION_TRIGGER.TICKET_ASSIGNED]: 'টিকেট অ্যাসাইন',
  [AUTOMATION_TRIGGER.TICKET_RESOLVED]: 'টিকেট সমাধান',
  [AUTOMATION_TRIGGER.TICKET_CLOSED]: 'টিকেট বন্ধ',
  [AUTOMATION_TRIGGER.TICKET_ESCALATED]: 'টিকেট এস্কেলেট',
  [AUTOMATION_TRIGGER.TIME_BASED]: 'সময়ভিত্তিক',
  [AUTOMATION_TRIGGER.EVENT_BASED]: 'ইভেন্টভিত্তিক',
  [AUTOMATION_TRIGGER.CUSTOM_TRIGGER]: 'কাস্টম ট্রিগার',
  [AUTOMATION_TRIGGER.CONDITION_MET]: 'শর্ত পূরণ',
  [AUTOMATION_TRIGGER.SCHEDULED]: 'নির্ধারিত',
  [AUTOMATION_TRIGGER.API_CALL]: 'এপিআই কল',
  [AUTOMATION_TRIGGER.SLA_BREACH]: 'এসএলএ লঙ্ঘন',
  [AUTOMATION_TRIGGER.PRIORITY_CHANGED]: 'প্রায়োরিটি পরিবর্তন',
  [AUTOMATION_TRIGGER.STATUS_CHANGED]: 'স্ট্যাটাস পরিবর্তন',
  [AUTOMATION_TRIGGER.CATEGORY_CHANGED]: 'ক্যাটাগরি পরিবর্তন',
  [AUTOMATION_TRIGGER.TAG_ADDED]: 'ট্যাগ যোগ',
  [AUTOMATION_TRIGGER.TAG_REMOVED]: 'ট্যাগ সরানো',
  [AUTOMATION_TRIGGER.COMMENT_ADDED]: 'কমেন্ট যোগ',
  [AUTOMATION_TRIGGER.ATTACHMENT_ADDED]: 'অ্যাটাচমেন্ট যোগ',
  [AUTOMATION_TRIGGER.USER_RESPONDED]: 'ব্যবহারকারী রেসপন্স',
  [AUTOMATION_TRIGGER.AGENT_RESPONDED]: 'এজেন্ট রেসপন্স',
  [AUTOMATION_TRIGGER.ESCALATION_PENDING]: 'এস্কেলেশন মুলতুবি',
  [AUTOMATION_TRIGGER.FOLLOW_UP_REQUIRED]: 'ফলো-আপ প্রয়োজন',
  [AUTOMATION_TRIGGER.SATISFACTION_RECEIVED]: 'সন্তুষ্টি প্রাপ্ত',
  [AUTOMATION_TRIGGER.BATCH_PROCESS]: 'ব্যাচ প্রসেস',
  [AUTOMATION_TRIGGER.MANUAL_TRIGGER]: 'ম্যানুয়াল ট্রিগার',
  [AUTOMATION_TRIGGER.WEBHOOK]: 'ওয়েবহুক',
} as const;

/**
 * অটোমেশন ট্রিগারের আইকন (অনুষঙ্গিক নাম)
 */
export const AUTOMATION_TRIGGER_ICONS = {
  [AUTOMATION_TRIGGER.TICKET_CREATED]: 'plus-circle',
  [AUTOMATION_TRIGGER.TICKET_UPDATED]: 'edit',
  [AUTOMATION_TRIGGER.TICKET_ASSIGNED]: 'user-check',
  [AUTOMATION_TRIGGER.TICKET_RESOLVED]: 'check-circle',
  [AUTOMATION_TRIGGER.TICKET_CLOSED]: 'x-circle',
  [AUTOMATION_TRIGGER.TICKET_ESCALATED]: 'arrow-up-circle',
  [AUTOMATION_TRIGGER.TIME_BASED]: 'clock',
  [AUTOMATION_TRIGGER.EVENT_BASED]: 'zap',
  [AUTOMATION_TRIGGER.CUSTOM_TRIGGER]: 'settings',
  [AUTOMATION_TRIGGER.CONDITION_MET]: 'check',
  [AUTOMATION_TRIGGER.SCHEDULED]: 'calendar',
  [AUTOMATION_TRIGGER.API_CALL]: 'code',
  [AUTOMATION_TRIGGER.SLA_BREACH]: 'alert-circle',
  [AUTOMATION_TRIGGER.PRIORITY_CHANGED]: 'flag',
  [AUTOMATION_TRIGGER.STATUS_CHANGED]: 'circle',
  [AUTOMATION_TRIGGER.CATEGORY_CHANGED]: 'folder',
  [AUTOMATION_TRIGGER.TAG_ADDED]: 'tag',
  [AUTOMATION_TRIGGER.TAG_REMOVED]: 'tag',
  [AUTOMATION_TRIGGER.COMMENT_ADDED]: 'message-square',
  [AUTOMATION_TRIGGER.ATTACHMENT_ADDED]: 'paperclip',
  [AUTOMATION_TRIGGER.USER_RESPONDED]: 'user',
  [AUTOMATION_TRIGGER.AGENT_RESPONDED]: 'headphones',
  [AUTOMATION_TRIGGER.ESCALATION_PENDING]: 'alert-triangle',
  [AUTOMATION_TRIGGER.FOLLOW_UP_REQUIRED]: 'refresh-cw',
  [AUTOMATION_TRIGGER.SATISFACTION_RECEIVED]: 'smile',
  [AUTOMATION_TRIGGER.BATCH_PROCESS]: 'layers',
  [AUTOMATION_TRIGGER.MANUAL_TRIGGER]: 'mouse-pointer',
  [AUTOMATION_TRIGGER.WEBHOOK]: 'link',
} as const;

/**
 * অটোমেশন ট্রিগারের রঙের কোড (হেক্স)
 */
export const AUTOMATION_TRIGGER_COLORS = {
  [AUTOMATION_TRIGGER.TICKET_CREATED]: '#2ecc71',
  [AUTOMATION_TRIGGER.TICKET_UPDATED]: '#3498db',
  [AUTOMATION_TRIGGER.TICKET_ASSIGNED]: '#9b59b6',
  [AUTOMATION_TRIGGER.TICKET_RESOLVED]: '#27ae60',
  [AUTOMATION_TRIGGER.TICKET_CLOSED]: '#95a5a6',
  [AUTOMATION_TRIGGER.TICKET_ESCALATED]: '#e74c3c',
  [AUTOMATION_TRIGGER.TIME_BASED]: '#f39c12',
  [AUTOMATION_TRIGGER.EVENT_BASED]: '#1abc9c',
  [AUTOMATION_TRIGGER.CUSTOM_TRIGGER]: '#34495e',
  [AUTOMATION_TRIGGER.CONDITION_MET]: '#2ecc71',
  [AUTOMATION_TRIGGER.SCHEDULED]: '#9b59b6',
  [AUTOMATION_TRIGGER.API_CALL]: '#2980b9',
  [AUTOMATION_TRIGGER.SLA_BREACH]: '#c0392b',
  [AUTOMATION_TRIGGER.PRIORITY_CHANGED]: '#e67e22',
  [AUTOMATION_TRIGGER.STATUS_CHANGED]: '#95a5a6',
  [AUTOMATION_TRIGGER.CATEGORY_CHANGED]: '#8e44ad',
  [AUTOMATION_TRIGGER.TAG_ADDED]: '#f39c12',
  [AUTOMATION_TRIGGER.TAG_REMOVED]: '#e74c3c',
  [AUTOMATION_TRIGGER.COMMENT_ADDED]: '#3498db',
  [AUTOMATION_TRIGGER.ATTACHMENT_ADDED]: '#1abc9c',
  [AUTOMATION_TRIGGER.USER_RESPONDED]: '#2ecc71',
  [AUTOMATION_TRIGGER.AGENT_RESPONDED]: '#2980b9',
  [AUTOMATION_TRIGGER.ESCALATION_PENDING]: '#e67e22',
  [AUTOMATION_TRIGGER.FOLLOW_UP_REQUIRED]: '#3498db',
  [AUTOMATION_TRIGGER.SATISFACTION_RECEIVED]: '#2ecc71',
  [AUTOMATION_TRIGGER.BATCH_PROCESS]: '#34495e',
  [AUTOMATION_TRIGGER.MANUAL_TRIGGER]: '#7f8c8d',
  [AUTOMATION_TRIGGER.WEBHOOK]: '#8e44ad',
} as const;

/**
 * অটোমেশন ট্রিগারের ক্যাটাগরি
 */
export const AUTOMATION_TRIGGER_CATEGORIES = {
  [AUTOMATION_TRIGGER.TICKET_CREATED]: 'ticket',
  [AUTOMATION_TRIGGER.TICKET_UPDATED]: 'ticket',
  [AUTOMATION_TRIGGER.TICKET_ASSIGNED]: 'ticket',
  [AUTOMATION_TRIGGER.TICKET_RESOLVED]: 'ticket',
  [AUTOMATION_TRIGGER.TICKET_CLOSED]: 'ticket',
  [AUTOMATION_TRIGGER.TICKET_ESCALATED]: 'ticket',
  [AUTOMATION_TRIGGER.TIME_BASED]: 'time',
  [AUTOMATION_TRIGGER.EVENT_BASED]: 'event',
  [AUTOMATION_TRIGGER.CUSTOM_TRIGGER]: 'custom',
  [AUTOMATION_TRIGGER.CONDITION_MET]: 'condition',
  [AUTOMATION_TRIGGER.SCHEDULED]: 'time',
  [AUTOMATION_TRIGGER.API_CALL]: 'api',
  [AUTOMATION_TRIGGER.SLA_BREACH]: 'sla',
  [AUTOMATION_TRIGGER.PRIORITY_CHANGED]: 'update',
  [AUTOMATION_TRIGGER.STATUS_CHANGED]: 'update',
  [AUTOMATION_TRIGGER.CATEGORY_CHANGED]: 'update',
  [AUTOMATION_TRIGGER.TAG_ADDED]: 'update',
  [AUTOMATION_TRIGGER.TAG_REMOVED]: 'update',
  [AUTOMATION_TRIGGER.COMMENT_ADDED]: 'interaction',
  [AUTOMATION_TRIGGER.ATTACHMENT_ADDED]: 'interaction',
  [AUTOMATION_TRIGGER.USER_RESPONDED]: 'interaction',
  [AUTOMATION_TRIGGER.AGENT_RESPONDED]: 'interaction',
  [AUTOMATION_TRIGGER.ESCALATION_PENDING]: 'escalation',
  [AUTOMATION_TRIGGER.FOLLOW_UP_REQUIRED]: 'follow_up',
  [AUTOMATION_TRIGGER.SATISFACTION_RECEIVED]: 'satisfaction',
  [AUTOMATION_TRIGGER.BATCH_PROCESS]: 'batch',
  [AUTOMATION_TRIGGER.MANUAL_TRIGGER]: 'manual',
  [AUTOMATION_TRIGGER.WEBHOOK]: 'webhook',
} as const;

/**
 * অটোমেশন ট্রিগারের ডিফল্ট প্রায়োরিটি
 */
export const AUTOMATION_TRIGGER_DEFAULT_PRIORITY = {
  [AUTOMATION_TRIGGER.TICKET_CREATED]: 100,
  [AUTOMATION_TRIGGER.TICKET_UPDATED]: 80,
  [AUTOMATION_TRIGGER.TICKET_ASSIGNED]: 90,
  [AUTOMATION_TRIGGER.TICKET_RESOLVED]: 70,
  [AUTOMATION_TRIGGER.TICKET_CLOSED]: 60,
  [AUTOMATION_TRIGGER.TICKET_ESCALATED]: 95,
  [AUTOMATION_TRIGGER.TIME_BASED]: 50,
  [AUTOMATION_TRIGGER.EVENT_BASED]: 75,
  [AUTOMATION_TRIGGER.CUSTOM_TRIGGER]: 85,
  [AUTOMATION_TRIGGER.CONDITION_MET]: 80,
  [AUTOMATION_TRIGGER.SCHEDULED]: 40,
  [AUTOMATION_TRIGGER.API_CALL]: 70,
  [AUTOMATION_TRIGGER.SLA_BREACH]: 100,
  [AUTOMATION_TRIGGER.PRIORITY_CHANGED]: 75,
  [AUTOMATION_TRIGGER.STATUS_CHANGED]: 70,
  [AUTOMATION_TRIGGER.CATEGORY_CHANGED]: 65,
  [AUTOMATION_TRIGGER.TAG_ADDED]: 55,
  [AUTOMATION_TRIGGER.TAG_REMOVED]: 55,
  [AUTOMATION_TRIGGER.COMMENT_ADDED]: 60,
  [AUTOMATION_TRIGGER.ATTACHMENT_ADDED]: 50,
  [AUTOMATION_TRIGGER.USER_RESPONDED]: 65,
  [AUTOMATION_TRIGGER.AGENT_RESPONDED]: 65,
  [AUTOMATION_TRIGGER.ESCALATION_PENDING]: 90,
  [AUTOMATION_TRIGGER.FOLLOW_UP_REQUIRED]: 70,
  [AUTOMATION_TRIGGER.SATISFACTION_RECEIVED]: 50,
  [AUTOMATION_TRIGGER.BATCH_PROCESS]: 30,
  [AUTOMATION_TRIGGER.MANUAL_TRIGGER]: 100,
  [AUTOMATION_TRIGGER.WEBHOOK]: 80,
} as const;

/**
 * অটোমেশন ট্রিগার গ্রুপ
 */
export const AUTOMATION_TRIGGER_GROUPS = {
  TICKET: [
    'ticket_created',
    'ticket_updated',
    'ticket_assigned',
    'ticket_resolved',
    'ticket_closed',
    'ticket_escalated',
  ],
  TIME: ['time_based', 'scheduled'],
  EVENT: ['event_based'],
  CUSTOM: ['custom_trigger'],
  CONDITION: ['condition_met'],
  API: ['api_call', 'webhook'],
  SLA: ['sla_breach'],
  UPDATE: ['priority_changed', 'status_changed', 'category_changed', 'tag_added', 'tag_removed'],
  INTERACTION: ['comment_added', 'attachment_added', 'user_responded', 'agent_responded'],
  ESCALATION: ['escalation_pending'],
  FOLLOW_UP: ['follow_up_required'],
  SATISFACTION: ['satisfaction_received'],
  BATCH: ['batch_process'],
  MANUAL: ['manual_trigger'],
} as const;

export type AutomationTrigger = (typeof AUTOMATION_TRIGGER)[keyof typeof AUTOMATION_TRIGGER];
export type AutomationTriggerDisplayNames = typeof AUTOMATION_TRIGGER_DISPLAY_NAMES;
export type AutomationTriggerIcons = typeof AUTOMATION_TRIGGER_ICONS;
export type AutomationTriggerColors = typeof AUTOMATION_TRIGGER_COLORS;
export type AutomationTriggerCategories = typeof AUTOMATION_TRIGGER_CATEGORIES;
export type AutomationTriggerDefaultPriority = typeof AUTOMATION_TRIGGER_DEFAULT_PRIORITY;
export type AutomationTriggerGroups = typeof AUTOMATION_TRIGGER_GROUPS;

export type AutomationTriggerGroup = keyof typeof AUTOMATION_TRIGGER_GROUPS;

export interface AutomationTriggerConfig {
  trigger: AutomationTrigger;
  displayName: string;
  icon: string;
  color: string;
  category: string;
  defaultPriority: number;
  group: AutomationTriggerGroup;
  description?: string;
}

/**
 * অটোমেশন ট্রিগার কনফিগারেশন অবজেক্ট
 */
export const AUTOMATION_TRIGGER_CONFIGS: Record<AutomationTrigger, AutomationTriggerConfig> = {
  [AUTOMATION_TRIGGER.TICKET_CREATED]: {
    trigger: AUTOMATION_TRIGGER.TICKET_CREATED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.TICKET_CREATED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.TICKET_CREATED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.TICKET_CREATED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.TICKET_CREATED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.TICKET_CREATED],
    group: 'TICKET',
    description: 'টিকেট তৈরি হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.TICKET_UPDATED]: {
    trigger: AUTOMATION_TRIGGER.TICKET_UPDATED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.TICKET_UPDATED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.TICKET_UPDATED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.TICKET_UPDATED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.TICKET_UPDATED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.TICKET_UPDATED],
    group: 'TICKET',
    description: 'টিকেট আপডেট হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.TICKET_ASSIGNED]: {
    trigger: AUTOMATION_TRIGGER.TICKET_ASSIGNED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.TICKET_ASSIGNED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.TICKET_ASSIGNED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.TICKET_ASSIGNED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.TICKET_ASSIGNED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.TICKET_ASSIGNED],
    group: 'TICKET',
    description: 'টিকেট অ্যাসাইন হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.TICKET_RESOLVED]: {
    trigger: AUTOMATION_TRIGGER.TICKET_RESOLVED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.TICKET_RESOLVED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.TICKET_RESOLVED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.TICKET_RESOLVED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.TICKET_RESOLVED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.TICKET_RESOLVED],
    group: 'TICKET',
    description: 'টিকেট সমাধান হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.TICKET_CLOSED]: {
    trigger: AUTOMATION_TRIGGER.TICKET_CLOSED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.TICKET_CLOSED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.TICKET_CLOSED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.TICKET_CLOSED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.TICKET_CLOSED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.TICKET_CLOSED],
    group: 'TICKET',
    description: 'টিকেট বন্ধ হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.TICKET_ESCALATED]: {
    trigger: AUTOMATION_TRIGGER.TICKET_ESCALATED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.TICKET_ESCALATED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.TICKET_ESCALATED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.TICKET_ESCALATED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.TICKET_ESCALATED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.TICKET_ESCALATED],
    group: 'TICKET',
    description: 'টিকেট এস্কেলেট হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.TIME_BASED]: {
    trigger: AUTOMATION_TRIGGER.TIME_BASED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.TIME_BASED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.TIME_BASED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.TIME_BASED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.TIME_BASED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.TIME_BASED],
    group: 'TIME',
    description: 'নির্দিষ্ট সময়ে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.EVENT_BASED]: {
    trigger: AUTOMATION_TRIGGER.EVENT_BASED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.EVENT_BASED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.EVENT_BASED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.EVENT_BASED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.EVENT_BASED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.EVENT_BASED],
    group: 'EVENT',
    description: 'কাস্টম ইভেন্টে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.CUSTOM_TRIGGER]: {
    trigger: AUTOMATION_TRIGGER.CUSTOM_TRIGGER,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.CUSTOM_TRIGGER],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.CUSTOM_TRIGGER],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.CUSTOM_TRIGGER],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.CUSTOM_TRIGGER],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.CUSTOM_TRIGGER],
    group: 'CUSTOM',
    description: 'কাস্টম শর্তে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.CONDITION_MET]: {
    trigger: AUTOMATION_TRIGGER.CONDITION_MET,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.CONDITION_MET],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.CONDITION_MET],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.CONDITION_MET],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.CONDITION_MET],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.CONDITION_MET],
    group: 'CONDITION',
    description: 'শর্ত পূরণ হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.SCHEDULED]: {
    trigger: AUTOMATION_TRIGGER.SCHEDULED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.SCHEDULED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.SCHEDULED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.SCHEDULED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.SCHEDULED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.SCHEDULED],
    group: 'TIME',
    description: 'নির্ধারিত সময়সূচিতে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.API_CALL]: {
    trigger: AUTOMATION_TRIGGER.API_CALL,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.API_CALL],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.API_CALL],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.API_CALL],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.API_CALL],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.API_CALL],
    group: 'API',
    description: 'এপিআই কল দ্বারা ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.SLA_BREACH]: {
    trigger: AUTOMATION_TRIGGER.SLA_BREACH,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.SLA_BREACH],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.SLA_BREACH],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.SLA_BREACH],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.SLA_BREACH],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.SLA_BREACH],
    group: 'SLA',
    description: 'এসএলএ লঙ্ঘন হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.PRIORITY_CHANGED]: {
    trigger: AUTOMATION_TRIGGER.PRIORITY_CHANGED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.PRIORITY_CHANGED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.PRIORITY_CHANGED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.PRIORITY_CHANGED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.PRIORITY_CHANGED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.PRIORITY_CHANGED],
    group: 'UPDATE',
    description: 'প্রায়োরিটি পরিবর্তন হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.STATUS_CHANGED]: {
    trigger: AUTOMATION_TRIGGER.STATUS_CHANGED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.STATUS_CHANGED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.STATUS_CHANGED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.STATUS_CHANGED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.STATUS_CHANGED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.STATUS_CHANGED],
    group: 'UPDATE',
    description: 'স্ট্যাটাস পরিবর্তন হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.CATEGORY_CHANGED]: {
    trigger: AUTOMATION_TRIGGER.CATEGORY_CHANGED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.CATEGORY_CHANGED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.CATEGORY_CHANGED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.CATEGORY_CHANGED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.CATEGORY_CHANGED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.CATEGORY_CHANGED],
    group: 'UPDATE',
    description: 'ক্যাটাগরি পরিবর্তন হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.TAG_ADDED]: {
    trigger: AUTOMATION_TRIGGER.TAG_ADDED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.TAG_ADDED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.TAG_ADDED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.TAG_ADDED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.TAG_ADDED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.TAG_ADDED],
    group: 'UPDATE',
    description: 'ট্যাগ যোগ হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.TAG_REMOVED]: {
    trigger: AUTOMATION_TRIGGER.TAG_REMOVED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.TAG_REMOVED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.TAG_REMOVED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.TAG_REMOVED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.TAG_REMOVED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.TAG_REMOVED],
    group: 'UPDATE',
    description: 'ট্যাগ সরানো হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.COMMENT_ADDED]: {
    trigger: AUTOMATION_TRIGGER.COMMENT_ADDED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.COMMENT_ADDED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.COMMENT_ADDED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.COMMENT_ADDED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.COMMENT_ADDED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.COMMENT_ADDED],
    group: 'INTERACTION',
    description: 'কমেন্ট যোগ হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.ATTACHMENT_ADDED]: {
    trigger: AUTOMATION_TRIGGER.ATTACHMENT_ADDED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.ATTACHMENT_ADDED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.ATTACHMENT_ADDED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.ATTACHMENT_ADDED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.ATTACHMENT_ADDED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.ATTACHMENT_ADDED],
    group: 'INTERACTION',
    description: 'অ্যাটাচমেন্ট যোগ হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.USER_RESPONDED]: {
    trigger: AUTOMATION_TRIGGER.USER_RESPONDED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.USER_RESPONDED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.USER_RESPONDED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.USER_RESPONDED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.USER_RESPONDED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.USER_RESPONDED],
    group: 'INTERACTION',
    description: 'ব্যবহারকারী রেসপন্স দিলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.AGENT_RESPONDED]: {
    trigger: AUTOMATION_TRIGGER.AGENT_RESPONDED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.AGENT_RESPONDED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.AGENT_RESPONDED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.AGENT_RESPONDED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.AGENT_RESPONDED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.AGENT_RESPONDED],
    group: 'INTERACTION',
    description: 'এজেন্ট রেসপন্স দিলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.ESCALATION_PENDING]: {
    trigger: AUTOMATION_TRIGGER.ESCALATION_PENDING,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.ESCALATION_PENDING],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.ESCALATION_PENDING],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.ESCALATION_PENDING],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.ESCALATION_PENDING],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.ESCALATION_PENDING],
    group: 'ESCALATION',
    description: 'এস্কেলেশন মুলতুবি থাকলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.FOLLOW_UP_REQUIRED]: {
    trigger: AUTOMATION_TRIGGER.FOLLOW_UP_REQUIRED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.FOLLOW_UP_REQUIRED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.FOLLOW_UP_REQUIRED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.FOLLOW_UP_REQUIRED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.FOLLOW_UP_REQUIRED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.FOLLOW_UP_REQUIRED],
    group: 'FOLLOW_UP',
    description: 'ফলো-আপ প্রয়োজন হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.SATISFACTION_RECEIVED]: {
    trigger: AUTOMATION_TRIGGER.SATISFACTION_RECEIVED,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.SATISFACTION_RECEIVED],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.SATISFACTION_RECEIVED],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.SATISFACTION_RECEIVED],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.SATISFACTION_RECEIVED],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.SATISFACTION_RECEIVED],
    group: 'SATISFACTION',
    description: 'সন্তুষ্টি প্রাপ্ত হলে ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.BATCH_PROCESS]: {
    trigger: AUTOMATION_TRIGGER.BATCH_PROCESS,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.BATCH_PROCESS],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.BATCH_PROCESS],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.BATCH_PROCESS],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.BATCH_PROCESS],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.BATCH_PROCESS],
    group: 'BATCH',
    description: 'ব্যাচ প্রসেস চলাকালীন ট্রিগার হবে',
  },
  [AUTOMATION_TRIGGER.MANUAL_TRIGGER]: {
    trigger: AUTOMATION_TRIGGER.MANUAL_TRIGGER,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.MANUAL_TRIGGER],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.MANUAL_TRIGGER],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.MANUAL_TRIGGER],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.MANUAL_TRIGGER],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.MANUAL_TRIGGER],
    group: 'MANUAL',
    description: 'ম্যানুয়ালি ট্রিগার করা হবে',
  },
  [AUTOMATION_TRIGGER.WEBHOOK]: {
    trigger: AUTOMATION_TRIGGER.WEBHOOK,
    displayName: AUTOMATION_TRIGGER_DISPLAY_NAMES[AUTOMATION_TRIGGER.WEBHOOK],
    icon: AUTOMATION_TRIGGER_ICONS[AUTOMATION_TRIGGER.WEBHOOK],
    color: AUTOMATION_TRIGGER_COLORS[AUTOMATION_TRIGGER.WEBHOOK],
    category: AUTOMATION_TRIGGER_CATEGORIES[AUTOMATION_TRIGGER.WEBHOOK],
    defaultPriority: AUTOMATION_TRIGGER_DEFAULT_PRIORITY[AUTOMATION_TRIGGER.WEBHOOK],
    group: 'API',
    description: 'ওয়েবহুক দ্বারা ট্রিগার হবে',
  },
};

/**
 * অটোমেশন ট্রিগার গ্রুপ কনফিগারেশন
 */
export const AUTOMATION_TRIGGER_GROUP_CONFIGS: Record<
  AutomationTriggerGroup,
  {
    group: AutomationTriggerGroup;
    displayName: string;
    icon: string;
    color: string;
    triggers: readonly AutomationTrigger[];
    description?: string;
  }
> = {
  TICKET: {
    group: 'TICKET',
    displayName: 'টিকেট ট্রিগার',
    icon: 'ticket',
    color: '#3498db',
    triggers: [
      'ticket_created',
      'ticket_updated',
      'ticket_assigned',
      'ticket_resolved',
      'ticket_closed',
      'ticket_escalated',
    ] as const,
    description: 'টিকেট সম্পর্কিত ট্রিগার',
  },
  TIME: {
    group: 'TIME',
    displayName: 'সময় ট্রিগার',
    icon: 'clock',
    color: '#f39c12',
    triggers: ['time_based', 'scheduled'] as const,
    description: 'সময়ভিত্তিক ট্রিগার',
  },
  EVENT: {
    group: 'EVENT',
    displayName: 'ইভেন্ট ট্রিগার',
    icon: 'zap',
    color: '#1abc9c',
    triggers: ['event_based'] as const,
    description: 'ইভেন্টভিত্তিক ট্রিগার',
  },
  CUSTOM: {
    group: 'CUSTOM',
    displayName: 'কাস্টম ট্রিগার',
    icon: 'settings',
    color: '#34495e',
    triggers: ['custom_trigger'] as const,
    description: 'কাস্টম ট্রিগার',
  },
  CONDITION: {
    group: 'CONDITION',
    displayName: 'শর্ত ট্রিগার',
    icon: 'check',
    color: '#2ecc71',
    triggers: ['condition_met'] as const,
    description: 'শর্ত পূরণ হলে ট্রিগার',
  },
  API: {
    group: 'API',
    displayName: 'এপিআই ট্রিগার',
    icon: 'code',
    color: '#2980b9',
    triggers: ['api_call', 'webhook'] as const,
    description: 'এপিআই ও ওয়েবহুক ট্রিগার',
  },
  SLA: {
    group: 'SLA',
    displayName: 'এসএলএ ট্রিগার',
    icon: 'clock',
    color: '#c0392b',
    triggers: ['sla_breach'] as const,
    description: 'এসএলএ সম্পর্কিত ট্রিগার',
  },
  UPDATE: {
    group: 'UPDATE',
    displayName: 'আপডেট ট্রিগার',
    icon: 'refresh-cw',
    color: '#2980b9',
    triggers: [
      'priority_changed',
      'status_changed',
      'category_changed',
      'tag_added',
      'tag_removed',
    ] as const,
    description: 'আপডেট সম্পর্কিত ট্রিগার',
  },
  INTERACTION: {
    group: 'INTERACTION',
    displayName: 'ইন্টারঅ্যাকশন ট্রিগার',
    icon: 'message-square',
    color: '#8e44ad',
    triggers: ['comment_added', 'attachment_added', 'user_responded', 'agent_responded'] as const,
    description: 'ইন্টারঅ্যাকশন সম্পর্কিত ট্রিগার',
  },
  ESCALATION: {
    group: 'ESCALATION',
    displayName: 'এস্কেলেশন ট্রিগার',
    icon: 'alert-triangle',
    color: '#e67e22',
    triggers: ['escalation_pending'] as const,
    description: 'এস্কেলেশন সম্পর্কিত ট্রিগার',
  },
  FOLLOW_UP: {
    group: 'FOLLOW_UP',
    displayName: 'ফলো-আপ ট্রিগার',
    icon: 'refresh-cw',
    color: '#3498db',
    triggers: ['follow_up_required'] as const,
    description: 'ফলো-আপ সম্পর্কিত ট্রিগার',
  },
  SATISFACTION: {
    group: 'SATISFACTION',
    displayName: 'সন্তুষ্টি ট্রিগার',
    icon: 'smile',
    color: '#2ecc71',
    triggers: ['satisfaction_received'] as const,
    description: 'সন্তুষ্টি সম্পর্কিত ট্রিগার',
  },
  BATCH: {
    group: 'BATCH',
    displayName: 'ব্যাচ ট্রিগার',
    icon: 'layers',
    color: '#34495e',
    triggers: ['batch_process'] as const,
    description: 'ব্যাচ প্রসেস ট্রিগার',
  },
  MANUAL: {
    group: 'MANUAL',
    displayName: 'ম্যানুয়াল ট্রিগার',
    icon: 'mouse-pointer',
    color: '#7f8c8d',
    triggers: ['manual_trigger'] as const,
    description: 'ম্যানুয়াল ট্রিগার',
  },
};

/**
 * অটোমেশন ট্রিগার স্ট্যাটাস
 */
export const AUTOMATION_TRIGGER_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  DEPRECATED: 'deprecated',
  BETA: 'beta',
} as const;

export type AutomationTriggerStatus =
  (typeof AUTOMATION_TRIGGER_STATUS)[keyof typeof AUTOMATION_TRIGGER_STATUS];
