/**
 * সাপোর্ট অ্যানালিটিক্সের বিভিন্ন টাইপ সংক্রান্ত কনস্ট্যান্টসমূহ
 */

/**
 * অ্যানালিটিক্স টাইপ
 */
export const ANALYTICS_TYPE = {
  TICKET_VOLUME: 'ticket_volume',
  RESPONSE_TIME: 'response_time',
  RESOLUTION_TIME: 'resolution_time',
  CUSTOMER_SATISFACTION: 'customer_satisfaction',
  AGENT_PERFORMANCE: 'agent_performance',
  CHANNEL_EFFECTIVENESS: 'channel_effectiveness',
  CATEGORY_DISTRIBUTION: 'category_distribution',
  PRIORITY_DISTRIBUTION: 'priority_distribution',
  ESCALATION_RATE: 'escalation_rate',
  CHATBOT_EFFECTIVENESS: 'chatbot_effectiveness',
  FIRST_CONTACT_RESOLUTION: 'first_contact_resolution',
  ABANDON_RATE: 'abandon_rate',
  PEAK_HOUR_ANALYSIS: 'peak_hour_analysis',
  TREND_ANALYSIS: 'trend_analysis',
  FORECASTING: 'forecasting',
  COMPARATIVE_ANALYSIS: 'comparative_analysis',
  BOTTLENECK_DETECTION: 'bottleneck_detection',
  WORKLOAD_DISTRIBUTION: 'workload_distribution',
  QUALITY_ASSURANCE: 'quality_assurance',
  TRAINING_GAP_ANALYSIS: 'training_gap_analysis',
  CUSTOMER_JOURNEY: 'customer_journey',
  FEEDBACK_SENTIMENT: 'feedback_sentiment',
  COMPLAINT_ANALYSIS: 'complaint_analysis',
  SATISFACTION_TREND: 'satisfaction_trend',
  PERFORMANCE_BENCHMARK: 'performance_benchmark',
  TEAM_PRODUCTIVITY: 'team_productivity',
  SEASONAL_ANALYSIS: 'seasonal_analysis',
  CORRELATION_ANALYSIS: 'correlation_analysis',
} as const;

/**
 * অ্যানালিটিক্স টাইপের ডিসপ্লে নাম
 */
export const ANALYTICS_TYPE_DISPLAY_NAMES = {
  [ANALYTICS_TYPE.TICKET_VOLUME]: 'টিকেট ভলিউম',
  [ANALYTICS_TYPE.RESPONSE_TIME]: 'রেসপন্স টাইম',
  [ANALYTICS_TYPE.RESOLUTION_TIME]: 'রেজোলিউশন টাইম',
  [ANALYTICS_TYPE.CUSTOMER_SATISFACTION]: 'গ্রাহক সন্তুষ্টি',
  [ANALYTICS_TYPE.AGENT_PERFORMANCE]: 'এজেন্ট পারফরম্যান্স',
  [ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS]: 'চ্যানেল কার্যকারিতা',
  [ANALYTICS_TYPE.CATEGORY_DISTRIBUTION]: 'ক্যাটাগরি ডিস্ট্রিবিউশন',
  [ANALYTICS_TYPE.PRIORITY_DISTRIBUTION]: 'প্রায়োরিটি ডিস্ট্রিবিউশন',
  [ANALYTICS_TYPE.ESCALATION_RATE]: 'এস্কেলেশন রেট',
  [ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS]: 'চ্যাটবট কার্যকারিতা',
  [ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION]: 'প্রথম যোগাযোগে সমাধান',
  [ANALYTICS_TYPE.ABANDON_RATE]: 'অ্যাব্যান্ডন রেট',
  [ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS]: 'পিক আওয়ার অ্যানালাইসিস',
  [ANALYTICS_TYPE.TREND_ANALYSIS]: 'ট্রেন্ড অ্যানালাইসিস',
  [ANALYTICS_TYPE.FORECASTING]: 'ফোরকাস্টিং',
  [ANALYTICS_TYPE.COMPARATIVE_ANALYSIS]: 'তুলনামূলক অ্যানালাইসিস',
  [ANALYTICS_TYPE.BOTTLENECK_DETECTION]: 'বটলনেক ডিটেকশন',
  [ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION]: 'ওয়ার্কলোড ডিস্ট্রিবিউশন',
  [ANALYTICS_TYPE.QUALITY_ASSURANCE]: 'গুণমান নিশ্চয়তা',
  [ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS]: 'প্রশিক্ষণ ফাঁক বিশ্লেষণ',
  [ANALYTICS_TYPE.CUSTOMER_JOURNEY]: 'গ্রাহক যাত্রা',
  [ANALYTICS_TYPE.FEEDBACK_SENTIMENT]: 'ফিডব্যাক সেন্টিমেন্ট',
  [ANALYTICS_TYPE.COMPLAINT_ANALYSIS]: 'অভিযোগ বিশ্লেষণ',
  [ANALYTICS_TYPE.SATISFACTION_TREND]: 'সন্তুষ্টি ট্রেন্ড',
  [ANALYTICS_TYPE.PERFORMANCE_BENCHMARK]: 'পারফরম্যান্স বেঞ্চমার্ক',
  [ANALYTICS_TYPE.TEAM_PRODUCTIVITY]: 'টিম উৎপাদনশীলতা',
  [ANALYTICS_TYPE.SEASONAL_ANALYSIS]: 'ঋতুভিত্তিক বিশ্লেষণ',
  [ANALYTICS_TYPE.CORRELATION_ANALYSIS]: 'সম্পর্ক বিশ্লেষণ',
} as const;

/**
 * অ্যানালিটিক্স টাইপের আইকন (অনুষঙ্গিক নাম)
 */
export const ANALYTICS_TYPE_ICONS = {
  [ANALYTICS_TYPE.TICKET_VOLUME]: 'bar-chart',
  [ANALYTICS_TYPE.RESPONSE_TIME]: 'clock',
  [ANALYTICS_TYPE.RESOLUTION_TIME]: 'check-circle',
  [ANALYTICS_TYPE.CUSTOMER_SATISFACTION]: 'smile',
  [ANALYTICS_TYPE.AGENT_PERFORMANCE]: 'user',
  [ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS]: 'link',
  [ANALYTICS_TYPE.CATEGORY_DISTRIBUTION]: 'folder',
  [ANALYTICS_TYPE.PRIORITY_DISTRIBUTION]: 'flag',
  [ANALYTICS_TYPE.ESCALATION_RATE]: 'arrow-up-circle',
  [ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS]: 'bot',
  [ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION]: 'thumbs-up',
  [ANALYTICS_TYPE.ABANDON_RATE]: 'x-circle',
  [ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS]: 'sun',
  [ANALYTICS_TYPE.TREND_ANALYSIS]: 'trending-up',
  [ANALYTICS_TYPE.FORECASTING]: 'crystal-ball',
  [ANALYTICS_TYPE.COMPARATIVE_ANALYSIS]: 'git-compare',
  [ANALYTICS_TYPE.BOTTLENECK_DETECTION]: 'alert-circle',
  [ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION]: 'users',
  [ANALYTICS_TYPE.QUALITY_ASSURANCE]: 'shield-check',
  [ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS]: 'book',
  [ANALYTICS_TYPE.CUSTOMER_JOURNEY]: 'map',
  [ANALYTICS_TYPE.FEEDBACK_SENTIMENT]: 'message-square',
  [ANALYTICS_TYPE.COMPLAINT_ANALYSIS]: 'alert-triangle',
  [ANALYTICS_TYPE.SATISFACTION_TREND]: 'trending-up',
  [ANALYTICS_TYPE.PERFORMANCE_BENCHMARK]: 'target',
  [ANALYTICS_TYPE.TEAM_PRODUCTIVITY]: 'briefcase',
  [ANALYTICS_TYPE.SEASONAL_ANALYSIS]: 'calendar',
  [ANALYTICS_TYPE.CORRELATION_ANALYSIS]: 'scatter-chart',
} as const;

/**
 * অ্যানালিটিক্স টাইপের রঙের কোড (হেক্স)
 */
export const ANALYTICS_TYPE_COLORS = {
  [ANALYTICS_TYPE.TICKET_VOLUME]: '#3498db',
  [ANALYTICS_TYPE.RESPONSE_TIME]: '#f39c12',
  [ANALYTICS_TYPE.RESOLUTION_TIME]: '#2ecc71',
  [ANALYTICS_TYPE.CUSTOMER_SATISFACTION]: '#9b59b6',
  [ANALYTICS_TYPE.AGENT_PERFORMANCE]: '#1abc9c',
  [ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS]: '#e67e22',
  [ANALYTICS_TYPE.CATEGORY_DISTRIBUTION]: '#95a5a6',
  [ANALYTICS_TYPE.PRIORITY_DISTRIBUTION]: '#e74c3c',
  [ANALYTICS_TYPE.ESCALATION_RATE]: '#c0392b',
  [ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS]: '#2980b9',
  [ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION]: '#27ae60',
  [ANALYTICS_TYPE.ABANDON_RATE]: '#e74c3c',
  [ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS]: '#f1c40f',
  [ANALYTICS_TYPE.TREND_ANALYSIS]: '#3498db',
  [ANALYTICS_TYPE.FORECASTING]: '#8e44ad',
  [ANALYTICS_TYPE.COMPARATIVE_ANALYSIS]: '#16a085',
  [ANALYTICS_TYPE.BOTTLENECK_DETECTION]: '#e67e22',
  [ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION]: '#2c3e50',
  [ANALYTICS_TYPE.QUALITY_ASSURANCE]: '#27ae60',
  [ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS]: '#2980b9',
  [ANALYTICS_TYPE.CUSTOMER_JOURNEY]: '#9b59b6',
  [ANALYTICS_TYPE.FEEDBACK_SENTIMENT]: '#8e44ad',
  [ANALYTICS_TYPE.COMPLAINT_ANALYSIS]: '#c0392b',
  [ANALYTICS_TYPE.SATISFACTION_TREND]: '#2ecc71',
  [ANALYTICS_TYPE.PERFORMANCE_BENCHMARK]: '#f39c12',
  [ANALYTICS_TYPE.TEAM_PRODUCTIVITY]: '#1abc9c',
  [ANALYTICS_TYPE.SEASONAL_ANALYSIS]: '#3498db',
  [ANALYTICS_TYPE.CORRELATION_ANALYSIS]: '#9b59b6',
} as const;

/**
 * অ্যানালিটিক্স টাইপের ক্যাটাগরি
 */
export const ANALYTICS_TYPE_CATEGORIES = {
  [ANALYTICS_TYPE.TICKET_VOLUME]: 'volume',
  [ANALYTICS_TYPE.RESPONSE_TIME]: 'performance',
  [ANALYTICS_TYPE.RESOLUTION_TIME]: 'performance',
  [ANALYTICS_TYPE.CUSTOMER_SATISFACTION]: 'satisfaction',
  [ANALYTICS_TYPE.AGENT_PERFORMANCE]: 'agent',
  [ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS]: 'channel',
  [ANALYTICS_TYPE.CATEGORY_DISTRIBUTION]: 'distribution',
  [ANALYTICS_TYPE.PRIORITY_DISTRIBUTION]: 'distribution',
  [ANALYTICS_TYPE.ESCALATION_RATE]: 'efficiency',
  [ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS]: 'automation',
  [ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION]: 'efficiency',
  [ANALYTICS_TYPE.ABANDON_RATE]: 'operational',
  [ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS]: 'operational',
  [ANALYTICS_TYPE.TREND_ANALYSIS]: 'analytical',
  [ANALYTICS_TYPE.FORECASTING]: 'analytical',
  [ANALYTICS_TYPE.COMPARATIVE_ANALYSIS]: 'analytical',
  [ANALYTICS_TYPE.BOTTLENECK_DETECTION]: 'operational',
  [ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION]: 'operational',
  [ANALYTICS_TYPE.QUALITY_ASSURANCE]: 'quality',
  [ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS]: 'quality',
  [ANALYTICS_TYPE.CUSTOMER_JOURNEY]: 'customer',
  [ANALYTICS_TYPE.FEEDBACK_SENTIMENT]: 'feedback',
  [ANALYTICS_TYPE.COMPLAINT_ANALYSIS]: 'feedback',
  [ANALYTICS_TYPE.SATISFACTION_TREND]: 'satisfaction',
  [ANALYTICS_TYPE.PERFORMANCE_BENCHMARK]: 'performance',
  [ANALYTICS_TYPE.TEAM_PRODUCTIVITY]: 'team',
  [ANALYTICS_TYPE.SEASONAL_ANALYSIS]: 'analytical',
  [ANALYTICS_TYPE.CORRELATION_ANALYSIS]: 'analytical',
} as const;

/**
 * অ্যানালিটিক্স টাইপের ডিফল্ট চার্ট টাইপ
 */
export const ANALYTICS_TYPE_DEFAULT_CHART = {
  [ANALYTICS_TYPE.TICKET_VOLUME]: 'bar',
  [ANALYTICS_TYPE.RESPONSE_TIME]: 'line',
  [ANALYTICS_TYPE.RESOLUTION_TIME]: 'line',
  [ANALYTICS_TYPE.CUSTOMER_SATISFACTION]: 'gauge',
  [ANALYTICS_TYPE.AGENT_PERFORMANCE]: 'bar',
  [ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS]: 'bar',
  [ANALYTICS_TYPE.CATEGORY_DISTRIBUTION]: 'pie',
  [ANALYTICS_TYPE.PRIORITY_DISTRIBUTION]: 'pie',
  [ANALYTICS_TYPE.ESCALATION_RATE]: 'line',
  [ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS]: 'bar',
  [ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION]: 'gauge',
  [ANALYTICS_TYPE.ABANDON_RATE]: 'line',
  [ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS]: 'heatmap',
  [ANALYTICS_TYPE.TREND_ANALYSIS]: 'line',
  [ANALYTICS_TYPE.FORECASTING]: 'area',
  [ANALYTICS_TYPE.COMPARATIVE_ANALYSIS]: 'bar',
  [ANALYTICS_TYPE.BOTTLENECK_DETECTION]: 'scatter',
  [ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION]: 'bar',
  [ANALYTICS_TYPE.QUALITY_ASSURANCE]: 'table',
  [ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS]: 'bar',
  [ANALYTICS_TYPE.CUSTOMER_JOURNEY]: 'funnel',
  [ANALYTICS_TYPE.FEEDBACK_SENTIMENT]: 'pie',
  [ANALYTICS_TYPE.COMPLAINT_ANALYSIS]: 'bar',
  [ANALYTICS_TYPE.SATISFACTION_TREND]: 'line',
  [ANALYTICS_TYPE.PERFORMANCE_BENCHMARK]: 'bar',
  [ANALYTICS_TYPE.TEAM_PRODUCTIVITY]: 'bar',
  [ANALYTICS_TYPE.SEASONAL_ANALYSIS]: 'area',
  [ANALYTICS_TYPE.CORRELATION_ANALYSIS]: 'scatter',
} as const;

/**
 * অ্যানালিটিক্স টাইপের ডিফল্ট টাইম ফ্রেম
 */
export const ANALYTICS_TYPE_DEFAULT_TIME_FRAME = {
  [ANALYTICS_TYPE.TICKET_VOLUME]: 'month',
  [ANALYTICS_TYPE.RESPONSE_TIME]: 'week',
  [ANALYTICS_TYPE.RESOLUTION_TIME]: 'week',
  [ANALYTICS_TYPE.CUSTOMER_SATISFACTION]: 'month',
  [ANALYTICS_TYPE.AGENT_PERFORMANCE]: 'month',
  [ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS]: 'month',
  [ANALYTICS_TYPE.CATEGORY_DISTRIBUTION]: 'month',
  [ANALYTICS_TYPE.PRIORITY_DISTRIBUTION]: 'month',
  [ANALYTICS_TYPE.ESCALATION_RATE]: 'week',
  [ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS]: 'month',
  [ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION]: 'month',
  [ANALYTICS_TYPE.ABANDON_RATE]: 'week',
  [ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS]: 'today',
  [ANALYTICS_TYPE.TREND_ANALYSIS]: 'quarter',
  [ANALYTICS_TYPE.FORECASTING]: 'quarter',
  [ANALYTICS_TYPE.COMPARATIVE_ANALYSIS]: 'month',
  [ANALYTICS_TYPE.BOTTLENECK_DETECTION]: 'week',
  [ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION]: 'week',
  [ANALYTICS_TYPE.QUALITY_ASSURANCE]: 'month',
  [ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS]: 'quarter',
  [ANALYTICS_TYPE.CUSTOMER_JOURNEY]: 'month',
  [ANALYTICS_TYPE.FEEDBACK_SENTIMENT]: 'month',
  [ANALYTICS_TYPE.COMPLAINT_ANALYSIS]: 'month',
  [ANALYTICS_TYPE.SATISFACTION_TREND]: 'quarter',
  [ANALYTICS_TYPE.PERFORMANCE_BENCHMARK]: 'month',
  [ANALYTICS_TYPE.TEAM_PRODUCTIVITY]: 'month',
  [ANALYTICS_TYPE.SEASONAL_ANALYSIS]: 'year',
  [ANALYTICS_TYPE.CORRELATION_ANALYSIS]: 'month',
} as const;

/**
 * অ্যানালিটিক্স টাইপের ডিফল্ট মেট্রিক্স (মিউটেবল অ্যারে হিসেবে)
 */
export const ANALYTICS_TYPE_DEFAULT_METRICS = {
  [ANALYTICS_TYPE.TICKET_VOLUME]: ['total_tickets', 'open_tickets', 'closed_tickets'] as string[],
  [ANALYTICS_TYPE.RESPONSE_TIME]: [
    'avg_response_time',
    'max_response_time',
    'min_response_time',
  ] as string[],
  [ANALYTICS_TYPE.RESOLUTION_TIME]: [
    'avg_resolution_time',
    'max_resolution_time',
    'min_resolution_time',
  ] as string[],
  [ANALYTICS_TYPE.CUSTOMER_SATISFACTION]: [
    'satisfaction_score',
    'response_rate',
    'average_rating',
  ] as string[],
  [ANALYTICS_TYPE.AGENT_PERFORMANCE]: [
    'tickets_resolved',
    'avg_response_time',
    'avg_resolution_time',
    'satisfaction_score',
  ] as string[],
  [ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS]: [
    'channel_volume',
    'response_time',
    'resolution_time',
    'satisfaction_score',
  ] as string[],
  [ANALYTICS_TYPE.CATEGORY_DISTRIBUTION]: [
    'category_volume',
    'resolution_time',
    'escalation_rate',
  ] as string[],
  [ANALYTICS_TYPE.PRIORITY_DISTRIBUTION]: [
    'priority_volume',
    'resolution_time',
    'escalation_rate',
  ] as string[],
  [ANALYTICS_TYPE.ESCALATION_RATE]: [
    'escalation_count',
    'total_tickets',
    'escalation_rate',
  ] as string[],
  [ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS]: [
    'chatbot_conversations',
    'handoff_rate',
    'resolution_rate',
    'satisfaction_score',
  ] as string[],
  [ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION]: ['fcr_count', 'total_tickets', 'fcr_rate'] as string[],
  [ANALYTICS_TYPE.ABANDON_RATE]: ['abandoned_tickets', 'total_tickets', 'abandon_rate'] as string[],
  [ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS]: [
    'ticket_volume',
    'response_time',
    'resolution_time',
  ] as string[],
  [ANALYTICS_TYPE.TREND_ANALYSIS]: [
    'ticket_volume',
    'response_time',
    'satisfaction_score',
  ] as string[],
  [ANALYTICS_TYPE.FORECASTING]: ['ticket_volume', 'response_time', 'resolution_time'] as string[],
  [ANALYTICS_TYPE.COMPARATIVE_ANALYSIS]: [
    'ticket_volume',
    'response_time',
    'resolution_time',
    'satisfaction_score',
  ] as string[],
  [ANALYTICS_TYPE.BOTTLENECK_DETECTION]: [
    'response_time',
    'resolution_time',
    'escalation_rate',
  ] as string[],
  [ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION]: [
    'tickets_per_agent',
    'avg_response_time',
    'avg_resolution_time',
  ] as string[],
  [ANALYTICS_TYPE.QUALITY_ASSURANCE]: [
    'qa_score',
    'compliance_rate',
    'satisfaction_score',
  ] as string[],
  [ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS]: [
    'qa_score',
    'resolution_time',
    'escalation_rate',
  ] as string[],
  [ANALYTICS_TYPE.CUSTOMER_JOURNEY]: [
    'touchpoints',
    'resolution_time',
    'satisfaction_score',
  ] as string[],
  [ANALYTICS_TYPE.FEEDBACK_SENTIMENT]: [
    'positive_feedback',
    'negative_feedback',
    'neutral_feedback',
  ] as string[],
  [ANALYTICS_TYPE.COMPLAINT_ANALYSIS]: [
    'complaint_count',
    'resolution_time',
    'satisfaction_score',
  ] as string[],
  [ANALYTICS_TYPE.SATISFACTION_TREND]: [
    'satisfaction_score',
    'response_rate',
    'average_rating',
  ] as string[],
  [ANALYTICS_TYPE.PERFORMANCE_BENCHMARK]: [
    'tickets_resolved',
    'avg_response_time',
    'avg_resolution_time',
  ] as string[],
  [ANALYTICS_TYPE.TEAM_PRODUCTIVITY]: [
    'tickets_resolved',
    'avg_response_time',
    'satisfaction_score',
  ] as string[],
  [ANALYTICS_TYPE.SEASONAL_ANALYSIS]: [
    'ticket_volume',
    'response_time',
    'resolution_time',
  ] as string[],
  [ANALYTICS_TYPE.CORRELATION_ANALYSIS]: [
    'response_time',
    'resolution_time',
    'satisfaction_score',
  ] as string[],
} as const;

/**
 * অ্যানালিটিক্স টাইপ গ্রুপ
 */
export const ANALYTICS_TYPE_GROUPS = {
  PERFORMANCE: [
    'response_time',
    'resolution_time',
    'first_contact_resolution',
    'agent_performance',
  ] as const,
  VOLUME: [
    'ticket_volume',
    'category_distribution',
    'priority_distribution',
    'peak_hour_analysis',
  ] as const,
  SATISFACTION: [
    'customer_satisfaction',
    'satisfaction_trend',
    'feedback_sentiment',
    'customer_journey',
  ] as const,
  EFFICIENCY: [
    'escalation_rate',
    'abandon_rate',
    'bottleneck_detection',
    'workload_distribution',
  ] as const,
  QUALITY: ['quality_assurance', 'training_gap_analysis', 'complaint_analysis'] as const,
  AUTOMATION: ['chatbot_effectiveness'] as const,
  ANALYTICAL: [
    'trend_analysis',
    'forecasting',
    'comparative_analysis',
    'seasonal_analysis',
    'correlation_analysis',
  ] as const,
  TEAM: ['team_productivity', 'performance_benchmark'] as const,
  CHANNEL: ['channel_effectiveness'] as const,
} as const;

export type AnalyticsType = (typeof ANALYTICS_TYPE)[keyof typeof ANALYTICS_TYPE];
export type AnalyticsTypeDisplayNames = typeof ANALYTICS_TYPE_DISPLAY_NAMES;
export type AnalyticsTypeIcons = typeof ANALYTICS_TYPE_ICONS;
export type AnalyticsTypeColors = typeof ANALYTICS_TYPE_COLORS;
export type AnalyticsTypeCategories = typeof ANALYTICS_TYPE_CATEGORIES;
export type AnalyticsTypeDefaultChart = typeof ANALYTICS_TYPE_DEFAULT_CHART;
export type AnalyticsTypeDefaultTimeFrame = typeof ANALYTICS_TYPE_DEFAULT_TIME_FRAME;
export type AnalyticsTypeDefaultMetrics = typeof ANALYTICS_TYPE_DEFAULT_METRICS;
export type AnalyticsTypeGroups = typeof ANALYTICS_TYPE_GROUPS;

export type AnalyticsTypeGroup = keyof typeof ANALYTICS_TYPE_GROUPS;

export interface AnalyticsTypeConfig {
  type: AnalyticsType;
  displayName: string;
  icon: string;
  color: string;
  category: string;
  defaultChart: string;
  defaultTimeFrame: string;
  defaultMetrics: string[];
  group: AnalyticsTypeGroup;
  description?: string;
}

/**
 * অ্যানালিটিক্স টাইপ কনফিগারেশন অবজেক্ট
 */
export const ANALYTICS_TYPE_CONFIGS: Record<AnalyticsType, AnalyticsTypeConfig> = {
  [ANALYTICS_TYPE.TICKET_VOLUME]: {
    type: ANALYTICS_TYPE.TICKET_VOLUME,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.TICKET_VOLUME],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.TICKET_VOLUME],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.TICKET_VOLUME],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.TICKET_VOLUME],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.TICKET_VOLUME],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.TICKET_VOLUME],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.TICKET_VOLUME],
    group: 'VOLUME',
    description: 'টিকেটের পরিমাণ এবং প্রবাহ বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.RESPONSE_TIME]: {
    type: ANALYTICS_TYPE.RESPONSE_TIME,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.RESPONSE_TIME],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.RESPONSE_TIME],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.RESPONSE_TIME],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.RESPONSE_TIME],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.RESPONSE_TIME],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.RESPONSE_TIME],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.RESPONSE_TIME],
    group: 'PERFORMANCE',
    description: 'রেসপন্স টাইম বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.RESOLUTION_TIME]: {
    type: ANALYTICS_TYPE.RESOLUTION_TIME,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.RESOLUTION_TIME],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.RESOLUTION_TIME],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.RESOLUTION_TIME],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.RESOLUTION_TIME],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.RESOLUTION_TIME],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.RESOLUTION_TIME],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.RESOLUTION_TIME],
    group: 'PERFORMANCE',
    description: 'রেজোলিউশন টাইম বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.CUSTOMER_SATISFACTION]: {
    type: ANALYTICS_TYPE.CUSTOMER_SATISFACTION,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.CUSTOMER_SATISFACTION],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.CUSTOMER_SATISFACTION],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.CUSTOMER_SATISFACTION],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.CUSTOMER_SATISFACTION],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.CUSTOMER_SATISFACTION],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.CUSTOMER_SATISFACTION],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.CUSTOMER_SATISFACTION],
    group: 'SATISFACTION',
    description: 'গ্রাহক সন্তুষ্টি বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.AGENT_PERFORMANCE]: {
    type: ANALYTICS_TYPE.AGENT_PERFORMANCE,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.AGENT_PERFORMANCE],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.AGENT_PERFORMANCE],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.AGENT_PERFORMANCE],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.AGENT_PERFORMANCE],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.AGENT_PERFORMANCE],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.AGENT_PERFORMANCE],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.AGENT_PERFORMANCE],
    group: 'PERFORMANCE',
    description: 'এজেন্ট পারফরম্যান্স বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS]: {
    type: ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.CHANNEL_EFFECTIVENESS],
    group: 'CHANNEL',
    description: 'চ্যানেল কার্যকারিতা বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.CATEGORY_DISTRIBUTION]: {
    type: ANALYTICS_TYPE.CATEGORY_DISTRIBUTION,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.CATEGORY_DISTRIBUTION],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.CATEGORY_DISTRIBUTION],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.CATEGORY_DISTRIBUTION],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.CATEGORY_DISTRIBUTION],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.CATEGORY_DISTRIBUTION],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.CATEGORY_DISTRIBUTION],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.CATEGORY_DISTRIBUTION],
    group: 'VOLUME',
    description: 'ক্যাটাগরি ডিস্ট্রিবিউশন বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.PRIORITY_DISTRIBUTION]: {
    type: ANALYTICS_TYPE.PRIORITY_DISTRIBUTION,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.PRIORITY_DISTRIBUTION],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.PRIORITY_DISTRIBUTION],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.PRIORITY_DISTRIBUTION],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.PRIORITY_DISTRIBUTION],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.PRIORITY_DISTRIBUTION],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.PRIORITY_DISTRIBUTION],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.PRIORITY_DISTRIBUTION],
    group: 'VOLUME',
    description: 'প্রায়োরিটি ডিস্ট্রিবিউশন বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.ESCALATION_RATE]: {
    type: ANALYTICS_TYPE.ESCALATION_RATE,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.ESCALATION_RATE],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.ESCALATION_RATE],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.ESCALATION_RATE],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.ESCALATION_RATE],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.ESCALATION_RATE],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.ESCALATION_RATE],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.ESCALATION_RATE],
    group: 'EFFICIENCY',
    description: 'এস্কেলেশন রেট বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS]: {
    type: ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.CHATBOT_EFFECTIVENESS],
    group: 'AUTOMATION',
    description: 'চ্যাটবট কার্যকারিতা বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION]: {
    type: ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.FIRST_CONTACT_RESOLUTION],
    group: 'PERFORMANCE',
    description: 'প্রথম যোগাযোগে সমাধানের হার বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.ABANDON_RATE]: {
    type: ANALYTICS_TYPE.ABANDON_RATE,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.ABANDON_RATE],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.ABANDON_RATE],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.ABANDON_RATE],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.ABANDON_RATE],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.ABANDON_RATE],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.ABANDON_RATE],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.ABANDON_RATE],
    group: 'EFFICIENCY',
    description: 'অ্যাব্যান্ডন রেট বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS]: {
    type: ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.PEAK_HOUR_ANALYSIS],
    group: 'VOLUME',
    description: 'পিক আওয়ার বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.TREND_ANALYSIS]: {
    type: ANALYTICS_TYPE.TREND_ANALYSIS,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.TREND_ANALYSIS],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.TREND_ANALYSIS],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.TREND_ANALYSIS],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.TREND_ANALYSIS],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.TREND_ANALYSIS],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.TREND_ANALYSIS],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.TREND_ANALYSIS],
    group: 'ANALYTICAL',
    description: 'ট্রেন্ড বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.FORECASTING]: {
    type: ANALYTICS_TYPE.FORECASTING,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.FORECASTING],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.FORECASTING],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.FORECASTING],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.FORECASTING],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.FORECASTING],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.FORECASTING],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.FORECASTING],
    group: 'ANALYTICAL',
    description: 'ফোরকাস্টিং বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.COMPARATIVE_ANALYSIS]: {
    type: ANALYTICS_TYPE.COMPARATIVE_ANALYSIS,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.COMPARATIVE_ANALYSIS],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.COMPARATIVE_ANALYSIS],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.COMPARATIVE_ANALYSIS],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.COMPARATIVE_ANALYSIS],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.COMPARATIVE_ANALYSIS],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.COMPARATIVE_ANALYSIS],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.COMPARATIVE_ANALYSIS],
    group: 'ANALYTICAL',
    description: 'তুলনামূলক বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.BOTTLENECK_DETECTION]: {
    type: ANALYTICS_TYPE.BOTTLENECK_DETECTION,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.BOTTLENECK_DETECTION],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.BOTTLENECK_DETECTION],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.BOTTLENECK_DETECTION],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.BOTTLENECK_DETECTION],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.BOTTLENECK_DETECTION],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.BOTTLENECK_DETECTION],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.BOTTLENECK_DETECTION],
    group: 'EFFICIENCY',
    description: 'বটলনেক ডিটেকশন বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION]: {
    type: ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.WORKLOAD_DISTRIBUTION],
    group: 'EFFICIENCY',
    description: 'ওয়ার্কলোড ডিস্ট্রিবিউশন বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.QUALITY_ASSURANCE]: {
    type: ANALYTICS_TYPE.QUALITY_ASSURANCE,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.QUALITY_ASSURANCE],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.QUALITY_ASSURANCE],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.QUALITY_ASSURANCE],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.QUALITY_ASSURANCE],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.QUALITY_ASSURANCE],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.QUALITY_ASSURANCE],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.QUALITY_ASSURANCE],
    group: 'QUALITY',
    description: 'গুণমান নিশ্চয়তা বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS]: {
    type: ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.TRAINING_GAP_ANALYSIS],
    group: 'QUALITY',
    description: 'প্রশিক্ষণ ফাঁক বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.CUSTOMER_JOURNEY]: {
    type: ANALYTICS_TYPE.CUSTOMER_JOURNEY,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.CUSTOMER_JOURNEY],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.CUSTOMER_JOURNEY],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.CUSTOMER_JOURNEY],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.CUSTOMER_JOURNEY],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.CUSTOMER_JOURNEY],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.CUSTOMER_JOURNEY],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.CUSTOMER_JOURNEY],
    group: 'SATISFACTION',
    description: 'গ্রাহক যাত্রা বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.FEEDBACK_SENTIMENT]: {
    type: ANALYTICS_TYPE.FEEDBACK_SENTIMENT,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.FEEDBACK_SENTIMENT],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.FEEDBACK_SENTIMENT],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.FEEDBACK_SENTIMENT],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.FEEDBACK_SENTIMENT],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.FEEDBACK_SENTIMENT],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.FEEDBACK_SENTIMENT],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.FEEDBACK_SENTIMENT],
    group: 'SATISFACTION',
    description: 'ফিডব্যাক সেন্টিমেন্ট বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.COMPLAINT_ANALYSIS]: {
    type: ANALYTICS_TYPE.COMPLAINT_ANALYSIS,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.COMPLAINT_ANALYSIS],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.COMPLAINT_ANALYSIS],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.COMPLAINT_ANALYSIS],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.COMPLAINT_ANALYSIS],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.COMPLAINT_ANALYSIS],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.COMPLAINT_ANALYSIS],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.COMPLAINT_ANALYSIS],
    group: 'QUALITY',
    description: 'অভিযোগ বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.SATISFACTION_TREND]: {
    type: ANALYTICS_TYPE.SATISFACTION_TREND,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.SATISFACTION_TREND],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.SATISFACTION_TREND],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.SATISFACTION_TREND],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.SATISFACTION_TREND],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.SATISFACTION_TREND],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.SATISFACTION_TREND],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.SATISFACTION_TREND],
    group: 'SATISFACTION',
    description: 'সন্তুষ্টি ট্রেন্ড বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.PERFORMANCE_BENCHMARK]: {
    type: ANALYTICS_TYPE.PERFORMANCE_BENCHMARK,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.PERFORMANCE_BENCHMARK],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.PERFORMANCE_BENCHMARK],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.PERFORMANCE_BENCHMARK],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.PERFORMANCE_BENCHMARK],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.PERFORMANCE_BENCHMARK],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.PERFORMANCE_BENCHMARK],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.PERFORMANCE_BENCHMARK],
    group: 'TEAM',
    description: 'পারফরম্যান্স বেঞ্চমার্ক বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.TEAM_PRODUCTIVITY]: {
    type: ANALYTICS_TYPE.TEAM_PRODUCTIVITY,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.TEAM_PRODUCTIVITY],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.TEAM_PRODUCTIVITY],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.TEAM_PRODUCTIVITY],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.TEAM_PRODUCTIVITY],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.TEAM_PRODUCTIVITY],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.TEAM_PRODUCTIVITY],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.TEAM_PRODUCTIVITY],
    group: 'TEAM',
    description: 'টিম উৎপাদনশীলতা বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.SEASONAL_ANALYSIS]: {
    type: ANALYTICS_TYPE.SEASONAL_ANALYSIS,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.SEASONAL_ANALYSIS],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.SEASONAL_ANALYSIS],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.SEASONAL_ANALYSIS],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.SEASONAL_ANALYSIS],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.SEASONAL_ANALYSIS],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.SEASONAL_ANALYSIS],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.SEASONAL_ANALYSIS],
    group: 'ANALYTICAL',
    description: 'ঋতুভিত্তিক বিশ্লেষণ',
  },
  [ANALYTICS_TYPE.CORRELATION_ANALYSIS]: {
    type: ANALYTICS_TYPE.CORRELATION_ANALYSIS,
    displayName: ANALYTICS_TYPE_DISPLAY_NAMES[ANALYTICS_TYPE.CORRELATION_ANALYSIS],
    icon: ANALYTICS_TYPE_ICONS[ANALYTICS_TYPE.CORRELATION_ANALYSIS],
    color: ANALYTICS_TYPE_COLORS[ANALYTICS_TYPE.CORRELATION_ANALYSIS],
    category: ANALYTICS_TYPE_CATEGORIES[ANALYTICS_TYPE.CORRELATION_ANALYSIS],
    defaultChart: ANALYTICS_TYPE_DEFAULT_CHART[ANALYTICS_TYPE.CORRELATION_ANALYSIS],
    defaultTimeFrame: ANALYTICS_TYPE_DEFAULT_TIME_FRAME[ANALYTICS_TYPE.CORRELATION_ANALYSIS],
    defaultMetrics: ANALYTICS_TYPE_DEFAULT_METRICS[ANALYTICS_TYPE.CORRELATION_ANALYSIS],
    group: 'ANALYTICAL',
    description: 'সম্পর্ক বিশ্লেষণ',
  },
};

/**
 * অ্যানালিটিক্স টাইপ গ্রুপ কনফিগারেশন
 */
export const ANALYTICS_TYPE_GROUP_CONFIGS: Record<
  AnalyticsTypeGroup,
  {
    group: AnalyticsTypeGroup;
    displayName: string;
    icon: string;
    color: string;
    types: readonly AnalyticsType[];
    description?: string;
  }
> = {
  PERFORMANCE: {
    group: 'PERFORMANCE',
    displayName: 'পারফরম্যান্স',
    icon: 'zap',
    color: '#3498db',
    types: [
      'response_time',
      'resolution_time',
      'first_contact_resolution',
      'agent_performance',
    ] as const,
    description: 'পারফরম্যান্স সম্পর্কিত অ্যানালিটিক্স',
  },
  VOLUME: {
    group: 'VOLUME',
    displayName: 'ভলিউম',
    icon: 'bar-chart',
    color: '#2ecc71',
    types: [
      'ticket_volume',
      'category_distribution',
      'priority_distribution',
      'peak_hour_analysis',
    ] as const,
    description: 'ভলিউম সম্পর্কিত অ্যানালিটিক্স',
  },
  SATISFACTION: {
    group: 'SATISFACTION',
    displayName: 'সন্তুষ্টি',
    icon: 'smile',
    color: '#9b59b6',
    types: [
      'customer_satisfaction',
      'satisfaction_trend',
      'feedback_sentiment',
      'customer_journey',
    ] as const,
    description: 'সন্তুষ্টি সম্পর্কিত অ্যানালিটিক্স',
  },
  EFFICIENCY: {
    group: 'EFFICIENCY',
    displayName: 'দক্ষতা',
    icon: 'trending-up',
    color: '#f39c12',
    types: [
      'escalation_rate',
      'abandon_rate',
      'bottleneck_detection',
      'workload_distribution',
    ] as const,
    description: 'দক্ষতা সম্পর্কিত অ্যানালিটিক্স',
  },
  QUALITY: {
    group: 'QUALITY',
    displayName: 'গুণমান',
    icon: 'shield-check',
    color: '#27ae60',
    types: ['quality_assurance', 'training_gap_analysis', 'complaint_analysis'] as const,
    description: 'গুণমান সম্পর্কিত অ্যানালিটিক্স',
  },
  AUTOMATION: {
    group: 'AUTOMATION',
    displayName: 'অটোমেশন',
    icon: 'bot',
    color: '#2980b9',
    types: ['chatbot_effectiveness'] as const,
    description: 'অটোমেশন সম্পর্কিত অ্যানালিটিক্স',
  },
  ANALYTICAL: {
    group: 'ANALYTICAL',
    displayName: 'বিশ্লেষণমূলক',
    icon: 'scatter-chart',
    color: '#8e44ad',
    types: [
      'trend_analysis',
      'forecasting',
      'comparative_analysis',
      'seasonal_analysis',
      'correlation_analysis',
    ] as const,
    description: 'বিশ্লেষণমূলক অ্যানালিটিক্স',
  },
  TEAM: {
    group: 'TEAM',
    displayName: 'টিম',
    icon: 'users',
    color: '#1abc9c',
    types: ['team_productivity', 'performance_benchmark'] as const,
    description: 'টিম সম্পর্কিত অ্যানালিটিক্স',
  },
  CHANNEL: {
    group: 'CHANNEL',
    displayName: 'চ্যানেল',
    icon: 'link',
    color: '#e67e22',
    types: ['channel_effectiveness'] as const,
    description: 'চ্যানেল সম্পর্কিত অ্যানালিটিক্স',
  },
};

/**
 * অ্যানালিটিক্স টাইপ স্ট্যাটাস
 */
export const ANALYTICS_TYPE_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  DEPRECATED: 'deprecated',
  BETA: 'beta',
} as const;

export type AnalyticsTypeStatus =
  (typeof ANALYTICS_TYPE_STATUS)[keyof typeof ANALYTICS_TYPE_STATUS];
