/**
 * সাপোর্ট অটোমেশনের বিভিন্ন টাইপ সংক্রান্ত কনস্ট্যান্টসমূহ
 */

/**
 * অটোমেশন টাইপ
 */
export const AUTOMATION_TYPE = {
  TICKET_CREATION: 'ticket_creation',
  TICKET_ASSIGNMENT: 'ticket_assignment',
  TICKET_ESCALATION: 'ticket_escalation',
  EMAIL_SENDING: 'email_sending',
  SMS_SENDING: 'sms_sending',
  PUSH_NOTIFICATION: 'push_notification',
  DATA_UPDATE: 'data_update',
  CLEANUP: 'cleanup',
  REPORT_GENERATION: 'report_generation',
  ANALYTICS_UPDATE: 'analytics_update',
  CHATBOT_TRIGGER: 'chatbot_trigger',
  RULE_EXECUTION: 'rule_execution',
  WORKFLOW_TRIGGER: 'workflow_trigger',
  SLA_CHECK: 'sla_check',
  PRIORITY_UPDATE: 'priority_update',
  STATUS_UPDATE: 'status_update',
  CATEGORY_UPDATE: 'category_update',
  TAG_UPDATE: 'tag_update',
  AUTO_RESPONSE: 'auto_response',
  FOLLOW_UP: 'follow_up',
  REMINDER: 'reminder',
  SURVEY_TRIGGER: 'survey_trigger',
  BACKUP: 'backup',
  ARCHIVE: 'archive',
  RESTORE: 'restore',
  SYNC: 'sync',
  IMPORT: 'import',
  EXPORT: 'export',
  VALIDATION: 'validation',
  DUPLICATE_CHECK: 'duplicate_check',
  SPAM_CHECK: 'spam_check',
  SATISFACTION_CHECK: 'satisfaction_check',
} as const;

/**
 * অটোমেশন টাইপের ডিসপ্লে নাম
 */
export const AUTOMATION_TYPE_DISPLAY_NAMES = {
  [AUTOMATION_TYPE.TICKET_CREATION]: 'টিকেট তৈরি',
  [AUTOMATION_TYPE.TICKET_ASSIGNMENT]: 'টিকেট অ্যাসাইনমেন্ট',
  [AUTOMATION_TYPE.TICKET_ESCALATION]: 'টিকেট এস্কেলেশন',
  [AUTOMATION_TYPE.EMAIL_SENDING]: 'ইমেইল পাঠানো',
  [AUTOMATION_TYPE.SMS_SENDING]: 'এসএমএস পাঠানো',
  [AUTOMATION_TYPE.PUSH_NOTIFICATION]: 'পুশ নোটিফিকেশন',
  [AUTOMATION_TYPE.DATA_UPDATE]: 'ডেটা আপডেট',
  [AUTOMATION_TYPE.CLEANUP]: 'ক্লিনআপ',
  [AUTOMATION_TYPE.REPORT_GENERATION]: 'রিপোর্ট তৈরি',
  [AUTOMATION_TYPE.ANALYTICS_UPDATE]: 'অ্যানালিটিক্স আপডেট',
  [AUTOMATION_TYPE.CHATBOT_TRIGGER]: 'চ্যাটবট ট্রিগার',
  [AUTOMATION_TYPE.RULE_EXECUTION]: 'রুল এক্সিকিউশন',
  [AUTOMATION_TYPE.WORKFLOW_TRIGGER]: 'ওয়ার্কফ্লো ট্রিগার',
  [AUTOMATION_TYPE.SLA_CHECK]: 'এসএলএ চেক',
  [AUTOMATION_TYPE.PRIORITY_UPDATE]: 'প্রায়োরিটি আপডেট',
  [AUTOMATION_TYPE.STATUS_UPDATE]: 'স্ট্যাটাস আপডেট',
  [AUTOMATION_TYPE.CATEGORY_UPDATE]: 'ক্যাটাগরি আপডেট',
  [AUTOMATION_TYPE.TAG_UPDATE]: 'ট্যাগ আপডেট',
  [AUTOMATION_TYPE.AUTO_RESPONSE]: 'অটো-রেসপন্স',
  [AUTOMATION_TYPE.FOLLOW_UP]: 'ফলো-আপ',
  [AUTOMATION_TYPE.REMINDER]: 'রিমাইন্ডার',
  [AUTOMATION_TYPE.SURVEY_TRIGGER]: 'জরিপ ট্রিগার',
  [AUTOMATION_TYPE.BACKUP]: 'ব্যাকআপ',
  [AUTOMATION_TYPE.ARCHIVE]: 'আর্কাইভ',
  [AUTOMATION_TYPE.RESTORE]: 'পুনরুদ্ধার',
  [AUTOMATION_TYPE.SYNC]: 'সিঙ্ক',
  [AUTOMATION_TYPE.IMPORT]: 'ইমপোর্ট',
  [AUTOMATION_TYPE.EXPORT]: 'এক্সপোর্ট',
  [AUTOMATION_TYPE.VALIDATION]: 'ভ্যালিডেশন',
  [AUTOMATION_TYPE.DUPLICATE_CHECK]: 'ডুপ্লিকেট চেক',
  [AUTOMATION_TYPE.SPAM_CHECK]: 'স্প্যাম চেক',
  [AUTOMATION_TYPE.SATISFACTION_CHECK]: 'সন্তুষ্টি চেক',
} as const;

/**
 * অটোমেশন টাইপের আইকন (অনুষঙ্গিক নাম)
 */
export const AUTOMATION_TYPE_ICONS = {
  [AUTOMATION_TYPE.TICKET_CREATION]: 'plus-circle',
  [AUTOMATION_TYPE.TICKET_ASSIGNMENT]: 'user-check',
  [AUTOMATION_TYPE.TICKET_ESCALATION]: 'arrow-up-circle',
  [AUTOMATION_TYPE.EMAIL_SENDING]: 'mail',
  [AUTOMATION_TYPE.SMS_SENDING]: 'message-circle',
  [AUTOMATION_TYPE.PUSH_NOTIFICATION]: 'bell',
  [AUTOMATION_TYPE.DATA_UPDATE]: 'refresh-cw',
  [AUTOMATION_TYPE.CLEANUP]: 'trash-2',
  [AUTOMATION_TYPE.REPORT_GENERATION]: 'file-text',
  [AUTOMATION_TYPE.ANALYTICS_UPDATE]: 'bar-chart',
  [AUTOMATION_TYPE.CHATBOT_TRIGGER]: 'bot',
  [AUTOMATION_TYPE.RULE_EXECUTION]: 'zap',
  [AUTOMATION_TYPE.WORKFLOW_TRIGGER]: 'workflow',
  [AUTOMATION_TYPE.SLA_CHECK]: 'clock',
  [AUTOMATION_TYPE.PRIORITY_UPDATE]: 'flag',
  [AUTOMATION_TYPE.STATUS_UPDATE]: 'circle',
  [AUTOMATION_TYPE.CATEGORY_UPDATE]: 'folder',
  [AUTOMATION_TYPE.TAG_UPDATE]: 'tag',
  [AUTOMATION_TYPE.AUTO_RESPONSE]: 'message-square',
  [AUTOMATION_TYPE.FOLLOW_UP]: 'refresh-cw',
  [AUTOMATION_TYPE.REMINDER]: 'clock',
  [AUTOMATION_TYPE.SURVEY_TRIGGER]: 'clipboard',
  [AUTOMATION_TYPE.BACKUP]: 'hard-drive',
  [AUTOMATION_TYPE.ARCHIVE]: 'archive',
  [AUTOMATION_TYPE.RESTORE]: 'rotate-ccw',
  [AUTOMATION_TYPE.SYNC]: 'refresh-cw',
  [AUTOMATION_TYPE.IMPORT]: 'download',
  [AUTOMATION_TYPE.EXPORT]: 'upload',
  [AUTOMATION_TYPE.VALIDATION]: 'check-circle',
  [AUTOMATION_TYPE.DUPLICATE_CHECK]: 'copy',
  [AUTOMATION_TYPE.SPAM_CHECK]: 'shield-off',
  [AUTOMATION_TYPE.SATISFACTION_CHECK]: 'smile',
} as const;

/**
 * অটোমেশন টাইপের রঙের কোড (হেক্স)
 */
export const AUTOMATION_TYPE_COLORS = {
  [AUTOMATION_TYPE.TICKET_CREATION]: '#2ecc71',
  [AUTOMATION_TYPE.TICKET_ASSIGNMENT]: '#3498db',
  [AUTOMATION_TYPE.TICKET_ESCALATION]: '#e74c3c',
  [AUTOMATION_TYPE.EMAIL_SENDING]: '#9b59b6',
  [AUTOMATION_TYPE.SMS_SENDING]: '#f39c12',
  [AUTOMATION_TYPE.PUSH_NOTIFICATION]: '#1abc9c',
  [AUTOMATION_TYPE.DATA_UPDATE]: '#2980b9',
  [AUTOMATION_TYPE.CLEANUP]: '#95a5a6',
  [AUTOMATION_TYPE.REPORT_GENERATION]: '#e67e22',
  [AUTOMATION_TYPE.ANALYTICS_UPDATE]: '#8e44ad',
  [AUTOMATION_TYPE.CHATBOT_TRIGGER]: '#3498db',
  [AUTOMATION_TYPE.RULE_EXECUTION]: '#2ecc71',
  [AUTOMATION_TYPE.WORKFLOW_TRIGGER]: '#1abc9c',
  [AUTOMATION_TYPE.SLA_CHECK]: '#c0392b',
  [AUTOMATION_TYPE.PRIORITY_UPDATE]: '#e67e22',
  [AUTOMATION_TYPE.STATUS_UPDATE]: '#95a5a6',
  [AUTOMATION_TYPE.CATEGORY_UPDATE]: '#9b59b6',
  [AUTOMATION_TYPE.TAG_UPDATE]: '#f39c12',
  [AUTOMATION_TYPE.AUTO_RESPONSE]: '#2980b9',
  [AUTOMATION_TYPE.FOLLOW_UP]: '#3498db',
  [AUTOMATION_TYPE.REMINDER]: '#f39c12',
  [AUTOMATION_TYPE.SURVEY_TRIGGER]: '#27ae60',
  [AUTOMATION_TYPE.BACKUP]: '#2c3e50',
  [AUTOMATION_TYPE.ARCHIVE]: '#7f8c8d',
  [AUTOMATION_TYPE.RESTORE]: '#2ecc71',
  [AUTOMATION_TYPE.SYNC]: '#3498db',
  [AUTOMATION_TYPE.IMPORT]: '#27ae60',
  [AUTOMATION_TYPE.EXPORT]: '#e67e22',
  [AUTOMATION_TYPE.VALIDATION]: '#2ecc71',
  [AUTOMATION_TYPE.DUPLICATE_CHECK]: '#7f8c8d',
  [AUTOMATION_TYPE.SPAM_CHECK]: '#e74c3c',
  [AUTOMATION_TYPE.SATISFACTION_CHECK]: '#9b59b6',
} as const;

/**
 * অটোমেশন টাইপের ক্যাটাগরি
 */
export const AUTOMATION_TYPE_CATEGORIES = {
  [AUTOMATION_TYPE.TICKET_CREATION]: 'ticket',
  [AUTOMATION_TYPE.TICKET_ASSIGNMENT]: 'ticket',
  [AUTOMATION_TYPE.TICKET_ESCALATION]: 'ticket',
  [AUTOMATION_TYPE.EMAIL_SENDING]: 'communication',
  [AUTOMATION_TYPE.SMS_SENDING]: 'communication',
  [AUTOMATION_TYPE.PUSH_NOTIFICATION]: 'communication',
  [AUTOMATION_TYPE.DATA_UPDATE]: 'data',
  [AUTOMATION_TYPE.CLEANUP]: 'maintenance',
  [AUTOMATION_TYPE.REPORT_GENERATION]: 'reporting',
  [AUTOMATION_TYPE.ANALYTICS_UPDATE]: 'analytics',
  [AUTOMATION_TYPE.CHATBOT_TRIGGER]: 'chatbot',
  [AUTOMATION_TYPE.RULE_EXECUTION]: 'rule',
  [AUTOMATION_TYPE.WORKFLOW_TRIGGER]: 'workflow',
  [AUTOMATION_TYPE.SLA_CHECK]: 'sla',
  [AUTOMATION_TYPE.PRIORITY_UPDATE]: 'update',
  [AUTOMATION_TYPE.STATUS_UPDATE]: 'update',
  [AUTOMATION_TYPE.CATEGORY_UPDATE]: 'update',
  [AUTOMATION_TYPE.TAG_UPDATE]: 'update',
  [AUTOMATION_TYPE.AUTO_RESPONSE]: 'response',
  [AUTOMATION_TYPE.FOLLOW_UP]: 'follow_up',
  [AUTOMATION_TYPE.REMINDER]: 'reminder',
  [AUTOMATION_TYPE.SURVEY_TRIGGER]: 'survey',
  [AUTOMATION_TYPE.BACKUP]: 'maintenance',
  [AUTOMATION_TYPE.ARCHIVE]: 'maintenance',
  [AUTOMATION_TYPE.RESTORE]: 'maintenance',
  [AUTOMATION_TYPE.SYNC]: 'integration',
  [AUTOMATION_TYPE.IMPORT]: 'integration',
  [AUTOMATION_TYPE.EXPORT]: 'integration',
  [AUTOMATION_TYPE.VALIDATION]: 'validation',
  [AUTOMATION_TYPE.DUPLICATE_CHECK]: 'validation',
  [AUTOMATION_TYPE.SPAM_CHECK]: 'validation',
  [AUTOMATION_TYPE.SATISFACTION_CHECK]: 'validation',
} as const;

/**
 * অটোমেশন টাইপের ডিফল্ট প্রায়োরিটি
 */
export const AUTOMATION_TYPE_DEFAULT_PRIORITY = {
  [AUTOMATION_TYPE.TICKET_CREATION]: 100,
  [AUTOMATION_TYPE.TICKET_ASSIGNMENT]: 90,
  [AUTOMATION_TYPE.TICKET_ESCALATION]: 95,
  [AUTOMATION_TYPE.EMAIL_SENDING]: 50,
  [AUTOMATION_TYPE.SMS_SENDING]: 55,
  [AUTOMATION_TYPE.PUSH_NOTIFICATION]: 45,
  [AUTOMATION_TYPE.DATA_UPDATE]: 70,
  [AUTOMATION_TYPE.CLEANUP]: 30,
  [AUTOMATION_TYPE.REPORT_GENERATION]: 40,
  [AUTOMATION_TYPE.ANALYTICS_UPDATE]: 60,
  [AUTOMATION_TYPE.CHATBOT_TRIGGER]: 80,
  [AUTOMATION_TYPE.RULE_EXECUTION]: 85,
  [AUTOMATION_TYPE.WORKFLOW_TRIGGER]: 75,
  [AUTOMATION_TYPE.SLA_CHECK]: 90,
  [AUTOMATION_TYPE.PRIORITY_UPDATE]: 70,
  [AUTOMATION_TYPE.STATUS_UPDATE]: 70,
  [AUTOMATION_TYPE.CATEGORY_UPDATE]: 65,
  [AUTOMATION_TYPE.TAG_UPDATE]: 60,
  [AUTOMATION_TYPE.AUTO_RESPONSE]: 85,
  [AUTOMATION_TYPE.FOLLOW_UP]: 65,
  [AUTOMATION_TYPE.REMINDER]: 60,
  [AUTOMATION_TYPE.SURVEY_TRIGGER]: 50,
  [AUTOMATION_TYPE.BACKUP]: 40,
  [AUTOMATION_TYPE.ARCHIVE]: 35,
  [AUTOMATION_TYPE.RESTORE]: 45,
  [AUTOMATION_TYPE.SYNC]: 70,
  [AUTOMATION_TYPE.IMPORT]: 60,
  [AUTOMATION_TYPE.EXPORT]: 55,
  [AUTOMATION_TYPE.VALIDATION]: 80,
  [AUTOMATION_TYPE.DUPLICATE_CHECK]: 75,
  [AUTOMATION_TYPE.SPAM_CHECK]: 80,
  [AUTOMATION_TYPE.SATISFACTION_CHECK]: 65,
} as const;

/**
 * অটোমেশন টাইপ গ্রুপ
 */
export const AUTOMATION_TYPE_GROUPS = {
  TICKET: ['ticket_creation', 'ticket_assignment', 'ticket_escalation'],
  COMMUNICATION: ['email_sending', 'sms_sending', 'push_notification'],
  DATA: ['data_update', 'cleanup', 'backup', 'archive', 'restore'],
  REPORTING: ['report_generation', 'analytics_update'],
  CHATBOT: ['chatbot_trigger'],
  RULE: ['rule_execution'],
  WORKFLOW: ['workflow_trigger'],
  SLA: ['sla_check'],
  UPDATE: ['priority_update', 'status_update', 'category_update', 'tag_update'],
  RESPONSE: ['auto_response', 'follow_up', 'reminder'],
  SURVEY: ['survey_trigger'],
  INTEGRATION: ['sync', 'import', 'export'],
  VALIDATION: ['validation', 'duplicate_check', 'spam_check', 'satisfaction_check'],
} as const;

export type AutomationType = (typeof AUTOMATION_TYPE)[keyof typeof AUTOMATION_TYPE];
export type AutomationTypeDisplayNames = typeof AUTOMATION_TYPE_DISPLAY_NAMES;
export type AutomationTypeIcons = typeof AUTOMATION_TYPE_ICONS;
export type AutomationTypeColors = typeof AUTOMATION_TYPE_COLORS;
export type AutomationTypeCategories = typeof AUTOMATION_TYPE_CATEGORIES;
export type AutomationTypeDefaultPriority = typeof AUTOMATION_TYPE_DEFAULT_PRIORITY;
export type AutomationTypeGroups = typeof AUTOMATION_TYPE_GROUPS;

export type AutomationTypeGroup = keyof typeof AUTOMATION_TYPE_GROUPS;

export interface AutomationTypeConfig {
  type: AutomationType;
  displayName: string;
  icon: string;
  color: string;
  category: string;
  defaultPriority: number;
  group: AutomationTypeGroup;
  description?: string;
}

/**
 * অটোমেশন টাইপ কনফিগারেশন অবজেক্ট
 */
export const AUTOMATION_TYPE_CONFIGS: Record<AutomationType, AutomationTypeConfig> = {
  [AUTOMATION_TYPE.TICKET_CREATION]: {
    type: AUTOMATION_TYPE.TICKET_CREATION,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.TICKET_CREATION],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.TICKET_CREATION],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.TICKET_CREATION],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.TICKET_CREATION],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.TICKET_CREATION],
    group: 'TICKET',
    description: 'স্বয়ংক্রিয়ভাবে টিকেট তৈরি করা',
  },
  [AUTOMATION_TYPE.TICKET_ASSIGNMENT]: {
    type: AUTOMATION_TYPE.TICKET_ASSIGNMENT,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.TICKET_ASSIGNMENT],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.TICKET_ASSIGNMENT],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.TICKET_ASSIGNMENT],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.TICKET_ASSIGNMENT],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.TICKET_ASSIGNMENT],
    group: 'TICKET',
    description: 'স্বয়ংক্রিয়ভাবে টিকেট অ্যাসাইন করা',
  },
  [AUTOMATION_TYPE.TICKET_ESCALATION]: {
    type: AUTOMATION_TYPE.TICKET_ESCALATION,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.TICKET_ESCALATION],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.TICKET_ESCALATION],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.TICKET_ESCALATION],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.TICKET_ESCALATION],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.TICKET_ESCALATION],
    group: 'TICKET',
    description: 'স্বয়ংক্রিয়ভাবে টিকেট এস্কেলেট করা',
  },
  [AUTOMATION_TYPE.EMAIL_SENDING]: {
    type: AUTOMATION_TYPE.EMAIL_SENDING,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.EMAIL_SENDING],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.EMAIL_SENDING],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.EMAIL_SENDING],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.EMAIL_SENDING],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.EMAIL_SENDING],
    group: 'COMMUNICATION',
    description: 'স্বয়ংক্রিয়ভাবে ইমেইল পাঠানো',
  },
  [AUTOMATION_TYPE.SMS_SENDING]: {
    type: AUTOMATION_TYPE.SMS_SENDING,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.SMS_SENDING],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.SMS_SENDING],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.SMS_SENDING],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.SMS_SENDING],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.SMS_SENDING],
    group: 'COMMUNICATION',
    description: 'স্বয়ংক্রিয়ভাবে এসএমএস পাঠানো',
  },
  [AUTOMATION_TYPE.PUSH_NOTIFICATION]: {
    type: AUTOMATION_TYPE.PUSH_NOTIFICATION,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.PUSH_NOTIFICATION],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.PUSH_NOTIFICATION],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.PUSH_NOTIFICATION],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.PUSH_NOTIFICATION],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.PUSH_NOTIFICATION],
    group: 'COMMUNICATION',
    description: 'স্বয়ংক্রিয়ভাবে পুশ নোটিফিকেশন পাঠানো',
  },
  [AUTOMATION_TYPE.DATA_UPDATE]: {
    type: AUTOMATION_TYPE.DATA_UPDATE,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.DATA_UPDATE],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.DATA_UPDATE],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.DATA_UPDATE],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.DATA_UPDATE],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.DATA_UPDATE],
    group: 'DATA',
    description: 'স্বয়ংক্রিয়ভাবে ডেটা আপডেট করা',
  },
  [AUTOMATION_TYPE.CLEANUP]: {
    type: AUTOMATION_TYPE.CLEANUP,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.CLEANUP],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.CLEANUP],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.CLEANUP],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.CLEANUP],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.CLEANUP],
    group: 'DATA',
    description: 'স্বয়ংক্রিয়ভাবে ক্লিনআপ করা',
  },
  [AUTOMATION_TYPE.REPORT_GENERATION]: {
    type: AUTOMATION_TYPE.REPORT_GENERATION,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.REPORT_GENERATION],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.REPORT_GENERATION],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.REPORT_GENERATION],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.REPORT_GENERATION],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.REPORT_GENERATION],
    group: 'REPORTING',
    description: 'স্বয়ংক্রিয়ভাবে রিপোর্ট তৈরি করা',
  },
  [AUTOMATION_TYPE.ANALYTICS_UPDATE]: {
    type: AUTOMATION_TYPE.ANALYTICS_UPDATE,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.ANALYTICS_UPDATE],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.ANALYTICS_UPDATE],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.ANALYTICS_UPDATE],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.ANALYTICS_UPDATE],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.ANALYTICS_UPDATE],
    group: 'REPORTING',
    description: 'স্বয়ংক্রিয়ভাবে অ্যানালিটিক্স আপডেট করা',
  },
  [AUTOMATION_TYPE.CHATBOT_TRIGGER]: {
    type: AUTOMATION_TYPE.CHATBOT_TRIGGER,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.CHATBOT_TRIGGER],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.CHATBOT_TRIGGER],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.CHATBOT_TRIGGER],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.CHATBOT_TRIGGER],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.CHATBOT_TRIGGER],
    group: 'CHATBOT',
    description: 'স্বয়ংক্রিয়ভাবে চ্যাটবট ট্রিগার করা',
  },
  [AUTOMATION_TYPE.RULE_EXECUTION]: {
    type: AUTOMATION_TYPE.RULE_EXECUTION,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.RULE_EXECUTION],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.RULE_EXECUTION],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.RULE_EXECUTION],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.RULE_EXECUTION],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.RULE_EXECUTION],
    group: 'RULE',
    description: 'স্বয়ংক্রিয়ভাবে রুল এক্সিকিউট করা',
  },
  [AUTOMATION_TYPE.WORKFLOW_TRIGGER]: {
    type: AUTOMATION_TYPE.WORKFLOW_TRIGGER,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.WORKFLOW_TRIGGER],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.WORKFLOW_TRIGGER],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.WORKFLOW_TRIGGER],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.WORKFLOW_TRIGGER],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.WORKFLOW_TRIGGER],
    group: 'WORKFLOW',
    description: 'স্বয়ংক্রিয়ভাবে ওয়ার্কফ্লো ট্রিগার করা',
  },
  [AUTOMATION_TYPE.SLA_CHECK]: {
    type: AUTOMATION_TYPE.SLA_CHECK,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.SLA_CHECK],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.SLA_CHECK],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.SLA_CHECK],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.SLA_CHECK],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.SLA_CHECK],
    group: 'SLA',
    description: 'স্বয়ংক্রিয়ভাবে এসএলএ চেক করা',
  },
  [AUTOMATION_TYPE.PRIORITY_UPDATE]: {
    type: AUTOMATION_TYPE.PRIORITY_UPDATE,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.PRIORITY_UPDATE],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.PRIORITY_UPDATE],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.PRIORITY_UPDATE],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.PRIORITY_UPDATE],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.PRIORITY_UPDATE],
    group: 'UPDATE',
    description: 'স্বয়ংক্রিয়ভাবে প্রায়োরিটি আপডেট করা',
  },
  [AUTOMATION_TYPE.STATUS_UPDATE]: {
    type: AUTOMATION_TYPE.STATUS_UPDATE,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.STATUS_UPDATE],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.STATUS_UPDATE],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.STATUS_UPDATE],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.STATUS_UPDATE],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.STATUS_UPDATE],
    group: 'UPDATE',
    description: 'স্বয়ংক্রিয়ভাবে স্ট্যাটাস আপডেট করা',
  },
  [AUTOMATION_TYPE.CATEGORY_UPDATE]: {
    type: AUTOMATION_TYPE.CATEGORY_UPDATE,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.CATEGORY_UPDATE],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.CATEGORY_UPDATE],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.CATEGORY_UPDATE],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.CATEGORY_UPDATE],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.CATEGORY_UPDATE],
    group: 'UPDATE',
    description: 'স্বয়ংক্রিয়ভাবে ক্যাটাগরি আপডেট করা',
  },
  [AUTOMATION_TYPE.TAG_UPDATE]: {
    type: AUTOMATION_TYPE.TAG_UPDATE,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.TAG_UPDATE],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.TAG_UPDATE],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.TAG_UPDATE],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.TAG_UPDATE],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.TAG_UPDATE],
    group: 'UPDATE',
    description: 'স্বয়ংক্রিয়ভাবে ট্যাগ আপডেট করা',
  },
  [AUTOMATION_TYPE.AUTO_RESPONSE]: {
    type: AUTOMATION_TYPE.AUTO_RESPONSE,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.AUTO_RESPONSE],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.AUTO_RESPONSE],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.AUTO_RESPONSE],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.AUTO_RESPONSE],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.AUTO_RESPONSE],
    group: 'RESPONSE',
    description: 'স্বয়ংক্রিয়ভাবে অটো-রেসপন্স পাঠানো',
  },
  [AUTOMATION_TYPE.FOLLOW_UP]: {
    type: AUTOMATION_TYPE.FOLLOW_UP,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.FOLLOW_UP],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.FOLLOW_UP],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.FOLLOW_UP],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.FOLLOW_UP],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.FOLLOW_UP],
    group: 'RESPONSE',
    description: 'স্বয়ংক্রিয়ভাবে ফলো-আপ করা',
  },
  [AUTOMATION_TYPE.REMINDER]: {
    type: AUTOMATION_TYPE.REMINDER,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.REMINDER],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.REMINDER],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.REMINDER],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.REMINDER],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.REMINDER],
    group: 'RESPONSE',
    description: 'স্বয়ংক্রিয়ভাবে রিমাইন্ডার পাঠানো',
  },
  [AUTOMATION_TYPE.SURVEY_TRIGGER]: {
    type: AUTOMATION_TYPE.SURVEY_TRIGGER,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.SURVEY_TRIGGER],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.SURVEY_TRIGGER],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.SURVEY_TRIGGER],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.SURVEY_TRIGGER],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.SURVEY_TRIGGER],
    group: 'SURVEY',
    description: 'স্বয়ংক্রিয়ভাবে জরিপ ট্রিগার করা',
  },
  [AUTOMATION_TYPE.BACKUP]: {
    type: AUTOMATION_TYPE.BACKUP,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.BACKUP],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.BACKUP],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.BACKUP],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.BACKUP],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.BACKUP],
    group: 'DATA',
    description: 'স্বয়ংক্রিয়ভাবে ব্যাকআপ নেওয়া',
  },
  [AUTOMATION_TYPE.ARCHIVE]: {
    type: AUTOMATION_TYPE.ARCHIVE,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.ARCHIVE],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.ARCHIVE],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.ARCHIVE],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.ARCHIVE],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.ARCHIVE],
    group: 'DATA',
    description: 'স্বয়ংক্রিয়ভাবে আর্কাইভ করা',
  },
  [AUTOMATION_TYPE.RESTORE]: {
    type: AUTOMATION_TYPE.RESTORE,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.RESTORE],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.RESTORE],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.RESTORE],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.RESTORE],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.RESTORE],
    group: 'DATA',
    description: 'স্বয়ংক্রিয়ভাবে পুনরুদ্ধার করা',
  },
  [AUTOMATION_TYPE.SYNC]: {
    type: AUTOMATION_TYPE.SYNC,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.SYNC],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.SYNC],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.SYNC],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.SYNC],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.SYNC],
    group: 'INTEGRATION',
    description: 'স্বয়ংক্রিয়ভাবে সিঙ্ক করা',
  },
  [AUTOMATION_TYPE.IMPORT]: {
    type: AUTOMATION_TYPE.IMPORT,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.IMPORT],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.IMPORT],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.IMPORT],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.IMPORT],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.IMPORT],
    group: 'INTEGRATION',
    description: 'স্বয়ংক্রিয়ভাবে ইমপোর্ট করা',
  },
  [AUTOMATION_TYPE.EXPORT]: {
    type: AUTOMATION_TYPE.EXPORT,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.EXPORT],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.EXPORT],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.EXPORT],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.EXPORT],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.EXPORT],
    group: 'INTEGRATION',
    description: 'স্বয়ংক্রিয়ভাবে এক্সপোর্ট করা',
  },
  [AUTOMATION_TYPE.VALIDATION]: {
    type: AUTOMATION_TYPE.VALIDATION,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.VALIDATION],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.VALIDATION],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.VALIDATION],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.VALIDATION],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.VALIDATION],
    group: 'VALIDATION',
    description: 'স্বয়ংক্রিয়ভাবে ভ্যালিডেশন করা',
  },
  [AUTOMATION_TYPE.DUPLICATE_CHECK]: {
    type: AUTOMATION_TYPE.DUPLICATE_CHECK,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.DUPLICATE_CHECK],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.DUPLICATE_CHECK],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.DUPLICATE_CHECK],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.DUPLICATE_CHECK],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.DUPLICATE_CHECK],
    group: 'VALIDATION',
    description: 'স্বয়ংক্রিয়ভাবে ডুপ্লিকেট চেক করা',
  },
  [AUTOMATION_TYPE.SPAM_CHECK]: {
    type: AUTOMATION_TYPE.SPAM_CHECK,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.SPAM_CHECK],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.SPAM_CHECK],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.SPAM_CHECK],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.SPAM_CHECK],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.SPAM_CHECK],
    group: 'VALIDATION',
    description: 'স্বয়ংক্রিয়ভাবে স্প্যাম চেক করা',
  },
  [AUTOMATION_TYPE.SATISFACTION_CHECK]: {
    type: AUTOMATION_TYPE.SATISFACTION_CHECK,
    displayName: AUTOMATION_TYPE_DISPLAY_NAMES[AUTOMATION_TYPE.SATISFACTION_CHECK],
    icon: AUTOMATION_TYPE_ICONS[AUTOMATION_TYPE.SATISFACTION_CHECK],
    color: AUTOMATION_TYPE_COLORS[AUTOMATION_TYPE.SATISFACTION_CHECK],
    category: AUTOMATION_TYPE_CATEGORIES[AUTOMATION_TYPE.SATISFACTION_CHECK],
    defaultPriority: AUTOMATION_TYPE_DEFAULT_PRIORITY[AUTOMATION_TYPE.SATISFACTION_CHECK],
    group: 'VALIDATION',
    description: 'স্বয়ংক্রিয়ভাবে সন্তুষ্টি চেক করা',
  },
};

/**
 * অটোমেশন টাইপ গ্রুপ কনফিগারেশন
 */
export const AUTOMATION_TYPE_GROUP_CONFIGS: Record<
  AutomationTypeGroup,
  {
    group: AutomationTypeGroup;
    displayName: string;
    icon: string;
    color: string;
    types: readonly AutomationType[];
    description?: string;
  }
> = {
  TICKET: {
    group: 'TICKET',
    displayName: 'টিকেট অটোমেশন',
    icon: 'ticket',
    color: '#3498db',
    types: ['ticket_creation', 'ticket_assignment', 'ticket_escalation'] as const,
    description: 'টিকেট সম্পর্কিত অটোমেশন',
  },
  COMMUNICATION: {
    group: 'COMMUNICATION',
    displayName: 'যোগাযোগ অটোমেশন',
    icon: 'message-circle',
    color: '#9b59b6',
    types: ['email_sending', 'sms_sending', 'push_notification'] as const,
    description: 'যোগাযোগ সম্পর্কিত অটোমেশন',
  },
  DATA: {
    group: 'DATA',
    displayName: 'ডেটা অটোমেশন',
    icon: 'database',
    color: '#2c3e50',
    types: ['data_update', 'cleanup', 'backup', 'archive', 'restore'] as const,
    description: 'ডেটা সম্পর্কিত অটোমেশন',
  },
  REPORTING: {
    group: 'REPORTING',
    displayName: 'রিপোর্টিং অটোমেশন',
    icon: 'file-text',
    color: '#e67e22',
    types: ['report_generation', 'analytics_update'] as const,
    description: 'রিপোর্ট ও অ্যানালিটিক্স অটোমেশন',
  },
  CHATBOT: {
    group: 'CHATBOT',
    displayName: 'চ্যাটবট অটোমেশন',
    icon: 'bot',
    color: '#3498db',
    types: ['chatbot_trigger'] as const,
    description: 'চ্যাটবট সম্পর্কিত অটোমেশন',
  },
  RULE: {
    group: 'RULE',
    displayName: 'রুল অটোমেশন',
    icon: 'zap',
    color: '#2ecc71',
    types: ['rule_execution'] as const,
    description: 'রুল সম্পর্কিত অটোমেশন',
  },
  WORKFLOW: {
    group: 'WORKFLOW',
    displayName: 'ওয়ার্কফ্লো অটোমেশন',
    icon: 'workflow',
    color: '#1abc9c',
    types: ['workflow_trigger'] as const,
    description: 'ওয়ার্কফ্লো সম্পর্কিত অটোমেশন',
  },
  SLA: {
    group: 'SLA',
    displayName: 'এসএলএ অটোমেশন',
    icon: 'clock',
    color: '#c0392b',
    types: ['sla_check'] as const,
    description: 'এসএলএ সম্পর্কিত অটোমেশন',
  },
  UPDATE: {
    group: 'UPDATE',
    displayName: 'আপডেট অটোমেশন',
    icon: 'refresh-cw',
    color: '#2980b9',
    types: ['priority_update', 'status_update', 'category_update', 'tag_update'] as const,
    description: 'আপডেট সম্পর্কিত অটোমেশন',
  },
  RESPONSE: {
    group: 'RESPONSE',
    displayName: 'রেসপন্স অটোমেশন',
    icon: 'message-square',
    color: '#2980b9',
    types: ['auto_response', 'follow_up', 'reminder'] as const,
    description: 'রেসপন্স সম্পর্কিত অটোমেশন',
  },
  SURVEY: {
    group: 'SURVEY',
    displayName: 'জরিপ অটোমেশন',
    icon: 'clipboard',
    color: '#27ae60',
    types: ['survey_trigger'] as const,
    description: 'জরিপ সম্পর্কিত অটোমেশন',
  },
  INTEGRATION: {
    group: 'INTEGRATION',
    displayName: 'ইন্টিগ্রেশন অটোমেশন',
    icon: 'link',
    color: '#8e44ad',
    types: ['sync', 'import', 'export'] as const,
    description: 'ইন্টিগ্রেশন সম্পর্কিত অটোমেশন',
  },
  VALIDATION: {
    group: 'VALIDATION',
    displayName: 'ভ্যালিডেশন অটোমেশন',
    icon: 'check-circle',
    color: '#2ecc71',
    types: ['validation', 'duplicate_check', 'spam_check', 'satisfaction_check'] as const,
    description: 'ভ্যালিডেশন সম্পর্কিত অটোমেশন',
  },
};

/**
 * অটোমেশন টাইপ স্ট্যাটাস
 */
export const AUTOMATION_TYPE_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  DEPRECATED: 'deprecated',
  BETA: 'beta',
} as const;

export type AutomationTypeStatus =
  (typeof AUTOMATION_TYPE_STATUS)[keyof typeof AUTOMATION_TYPE_STATUS];
