/**
 * সাপোর্ট ইমেইলের বিভিন্ন টাইপ সংক্রান্ত কনস্ট্যান্টসমূহ
 */

/**
 * ইমেইল টাইপ
 */
export const EMAIL_TYPE = {
  TICKET_CREATION: 'ticket_creation',
  TICKET_UPDATE: 'ticket_update',
  TICKET_RESOLUTION: 'ticket_resolution',
  TICKET_CLOSURE: 'ticket_closure',
  TICKET_ESCALATION: 'ticket_escalation',
  ASSIGNMENT: 'assignment',
  SATISFACTION_SURVEY: 'satisfaction_survey',
  FEEDBACK_REQUEST: 'feedback_request',
  COMPLAINT_ACKNOWLEDGMENT: 'complaint_acknowledgment',
  NEWSLETTER: 'newsletter',
  ALERT: 'alert',
  REPORT: 'report',
  NOTIFICATION: 'notification',
  WELCOME: 'welcome',
  PASSWORD_RESET: 'password_reset',
  VERIFICATION: 'verification',
  FOLLOW_UP: 'follow_up',
  REMINDER: 'reminder',
  THANK_YOU: 'thank_you',
  APOLOGY: 'apology',
  CONFIRMATION: 'confirmation',
  INVOICE: 'invoice',
  RECEIPT: 'receipt',
  MAINTENANCE: 'maintenance',
  SECURITY_ALERT: 'security_alert',
  SYSTEM_NOTIFICATION: 'system_notification',
  TEAM_UPDATE: 'team_update',
  TRAINING: 'training',
  ONBOARDING: 'onboarding',
  OFFBOARDING: 'offboarding',
  BILLING: 'billing',
  PAYMENT_CONFIRMATION: 'payment_confirmation',
  REFUND: 'refund',
  CANCELLATION: 'cancellation',
  RENEWAL: 'renewal',
  UPGRADE: 'upgrade',
  DOWNGRADE: 'downgrade',
} as const;

/**
 * ইমেইল টাইপের ডিসপ্লে নাম
 */
export const EMAIL_TYPE_DISPLAY_NAMES = {
  [EMAIL_TYPE.TICKET_CREATION]: 'টিকেট তৈরি',
  [EMAIL_TYPE.TICKET_UPDATE]: 'টিকেট আপডেট',
  [EMAIL_TYPE.TICKET_RESOLUTION]: 'টিকেট সমাধান',
  [EMAIL_TYPE.TICKET_CLOSURE]: 'টিকেট বন্ধ',
  [EMAIL_TYPE.TICKET_ESCALATION]: 'টিকেট এস্কেলেশন',
  [EMAIL_TYPE.ASSIGNMENT]: 'অ্যাসাইনমেন্ট',
  [EMAIL_TYPE.SATISFACTION_SURVEY]: 'সন্তুষ্টি জরিপ',
  [EMAIL_TYPE.FEEDBACK_REQUEST]: 'ফিডব্যাক অনুরোধ',
  [EMAIL_TYPE.COMPLAINT_ACKNOWLEDGMENT]: 'অভিযোগ স্বীকৃতি',
  [EMAIL_TYPE.NEWSLETTER]: 'নিউজলেটার',
  [EMAIL_TYPE.ALERT]: 'অ্যালার্ট',
  [EMAIL_TYPE.REPORT]: 'রিপোর্ট',
  [EMAIL_TYPE.NOTIFICATION]: 'নোটিফিকেশন',
  [EMAIL_TYPE.WELCOME]: 'স্বাগতম',
  [EMAIL_TYPE.PASSWORD_RESET]: 'পাসওয়ার্ড রিসেট',
  [EMAIL_TYPE.VERIFICATION]: 'যাচাইকরণ',
  [EMAIL_TYPE.FOLLOW_UP]: 'ফলো-আপ',
  [EMAIL_TYPE.REMINDER]: 'রিমাইন্ডার',
  [EMAIL_TYPE.THANK_YOU]: 'ধন্যবাদ',
  [EMAIL_TYPE.APOLOGY]: 'ক্ষমা প্রার্থনা',
  [EMAIL_TYPE.CONFIRMATION]: 'নিশ্চিতকরণ',
  [EMAIL_TYPE.INVOICE]: 'ইনভয়েস',
  [EMAIL_TYPE.RECEIPT]: 'রসিদ',
  [EMAIL_TYPE.MAINTENANCE]: 'মেইনটেন্যান্স',
  [EMAIL_TYPE.SECURITY_ALERT]: 'সিকিউরিটি অ্যালার্ট',
  [EMAIL_TYPE.SYSTEM_NOTIFICATION]: 'সিস্টেম নোটিফিকেশন',
  [EMAIL_TYPE.TEAM_UPDATE]: 'টিম আপডেট',
  [EMAIL_TYPE.TRAINING]: 'প্রশিক্ষণ',
  [EMAIL_TYPE.ONBOARDING]: 'অনবোর্ডিং',
  [EMAIL_TYPE.OFFBOARDING]: 'অফবোর্ডিং',
  [EMAIL_TYPE.BILLING]: 'বিলিং',
  [EMAIL_TYPE.PAYMENT_CONFIRMATION]: 'পেমেন্ট নিশ্চিতকরণ',
  [EMAIL_TYPE.REFUND]: 'রিফান্ড',
  [EMAIL_TYPE.CANCELLATION]: 'বাতিলকরণ',
  [EMAIL_TYPE.RENEWAL]: 'রিনিউয়াল',
  [EMAIL_TYPE.UPGRADE]: 'আপগ্রেড',
  [EMAIL_TYPE.DOWNGRADE]: 'ডাউনগ্রেড',
} as const;

/**
 * ইমেইল টাইপের আইকন (অনুষঙ্গিক নাম)
 */
export const EMAIL_TYPE_ICONS = {
  [EMAIL_TYPE.TICKET_CREATION]: 'plus-circle',
  [EMAIL_TYPE.TICKET_UPDATE]: 'edit',
  [EMAIL_TYPE.TICKET_RESOLUTION]: 'check-circle',
  [EMAIL_TYPE.TICKET_CLOSURE]: 'x-circle',
  [EMAIL_TYPE.TICKET_ESCALATION]: 'arrow-up-circle',
  [EMAIL_TYPE.ASSIGNMENT]: 'user-check',
  [EMAIL_TYPE.SATISFACTION_SURVEY]: 'smile',
  [EMAIL_TYPE.FEEDBACK_REQUEST]: 'message-square',
  [EMAIL_TYPE.COMPLAINT_ACKNOWLEDGMENT]: 'alert-triangle',
  [EMAIL_TYPE.NEWSLETTER]: 'mail',
  [EMAIL_TYPE.ALERT]: 'alert-circle',
  [EMAIL_TYPE.REPORT]: 'file-text',
  [EMAIL_TYPE.NOTIFICATION]: 'bell',
  [EMAIL_TYPE.WELCOME]: 'smile',
  [EMAIL_TYPE.PASSWORD_RESET]: 'key',
  [EMAIL_TYPE.VERIFICATION]: 'shield-check',
  [EMAIL_TYPE.FOLLOW_UP]: 'refresh-cw',
  [EMAIL_TYPE.REMINDER]: 'clock',
  [EMAIL_TYPE.THANK_YOU]: 'thumbs-up',
  [EMAIL_TYPE.APOLOGY]: 'frown',
  [EMAIL_TYPE.CONFIRMATION]: 'check-circle',
  [EMAIL_TYPE.INVOICE]: 'file-text',
  [EMAIL_TYPE.RECEIPT]: 'receipt',
  [EMAIL_TYPE.MAINTENANCE]: 'wrench',
  [EMAIL_TYPE.SECURITY_ALERT]: 'shield',
  [EMAIL_TYPE.SYSTEM_NOTIFICATION]: 'cpu',
  [EMAIL_TYPE.TEAM_UPDATE]: 'users',
  [EMAIL_TYPE.TRAINING]: 'book',
  [EMAIL_TYPE.ONBOARDING]: 'user-plus',
  [EMAIL_TYPE.OFFBOARDING]: 'user-minus',
  [EMAIL_TYPE.BILLING]: 'credit-card',
  [EMAIL_TYPE.PAYMENT_CONFIRMATION]: 'check-circle',
  [EMAIL_TYPE.REFUND]: 'dollar-sign',
  [EMAIL_TYPE.CANCELLATION]: 'x-circle',
  [EMAIL_TYPE.RENEWAL]: 'refresh-cw',
  [EMAIL_TYPE.UPGRADE]: 'arrow-up',
  [EMAIL_TYPE.DOWNGRADE]: 'arrow-down',
} as const;

/**
 * ইমেইল টাইপের রঙের কোড (হেক্স)
 */
export const EMAIL_TYPE_COLORS = {
  [EMAIL_TYPE.TICKET_CREATION]: '#2ecc71',
  [EMAIL_TYPE.TICKET_UPDATE]: '#3498db',
  [EMAIL_TYPE.TICKET_RESOLUTION]: '#27ae60',
  [EMAIL_TYPE.TICKET_CLOSURE]: '#95a5a6',
  [EMAIL_TYPE.TICKET_ESCALATION]: '#e74c3c',
  [EMAIL_TYPE.ASSIGNMENT]: '#9b59b6',
  [EMAIL_TYPE.SATISFACTION_SURVEY]: '#2ecc71',
  [EMAIL_TYPE.FEEDBACK_REQUEST]: '#8e44ad',
  [EMAIL_TYPE.COMPLAINT_ACKNOWLEDGMENT]: '#e67e22',
  [EMAIL_TYPE.NEWSLETTER]: '#3498db',
  [EMAIL_TYPE.ALERT]: '#e74c3c',
  [EMAIL_TYPE.REPORT]: '#f39c12',
  [EMAIL_TYPE.NOTIFICATION]: '#1abc9c',
  [EMAIL_TYPE.WELCOME]: '#2ecc71',
  [EMAIL_TYPE.PASSWORD_RESET]: '#e67e22',
  [EMAIL_TYPE.VERIFICATION]: '#3498db',
  [EMAIL_TYPE.FOLLOW_UP]: '#2980b9',
  [EMAIL_TYPE.REMINDER]: '#f39c12',
  [EMAIL_TYPE.THANK_YOU]: '#2ecc71',
  [EMAIL_TYPE.APOLOGY]: '#e67e22',
  [EMAIL_TYPE.CONFIRMATION]: '#27ae60',
  [EMAIL_TYPE.INVOICE]: '#34495e',
  [EMAIL_TYPE.RECEIPT]: '#2c3e50',
  [EMAIL_TYPE.MAINTENANCE]: '#e67e22',
  [EMAIL_TYPE.SECURITY_ALERT]: '#c0392b',
  [EMAIL_TYPE.SYSTEM_NOTIFICATION]: '#2c3e50',
  [EMAIL_TYPE.TEAM_UPDATE]: '#1abc9c',
  [EMAIL_TYPE.TRAINING]: '#3498db',
  [EMAIL_TYPE.ONBOARDING]: '#2ecc71',
  [EMAIL_TYPE.OFFBOARDING]: '#e74c3c',
  [EMAIL_TYPE.BILLING]: '#27ae60',
  [EMAIL_TYPE.PAYMENT_CONFIRMATION]: '#2ecc71',
  [EMAIL_TYPE.REFUND]: '#e67e22',
  [EMAIL_TYPE.CANCELLATION]: '#e74c3c',
  [EMAIL_TYPE.RENEWAL]: '#3498db',
  [EMAIL_TYPE.UPGRADE]: '#2ecc71',
  [EMAIL_TYPE.DOWNGRADE]: '#e74c3c',
} as const;

/**
 * ইমেইল টাইপের ক্যাটাগরি
 */
export const EMAIL_TYPE_CATEGORIES = {
  [EMAIL_TYPE.TICKET_CREATION]: 'ticket',
  [EMAIL_TYPE.TICKET_UPDATE]: 'ticket',
  [EMAIL_TYPE.TICKET_RESOLUTION]: 'ticket',
  [EMAIL_TYPE.TICKET_CLOSURE]: 'ticket',
  [EMAIL_TYPE.TICKET_ESCALATION]: 'ticket',
  [EMAIL_TYPE.ASSIGNMENT]: 'assignment',
  [EMAIL_TYPE.SATISFACTION_SURVEY]: 'survey',
  [EMAIL_TYPE.FEEDBACK_REQUEST]: 'feedback',
  [EMAIL_TYPE.COMPLAINT_ACKNOWLEDGMENT]: 'complaint',
  [EMAIL_TYPE.NEWSLETTER]: 'marketing',
  [EMAIL_TYPE.ALERT]: 'alert',
  [EMAIL_TYPE.REPORT]: 'reporting',
  [EMAIL_TYPE.NOTIFICATION]: 'notification',
  [EMAIL_TYPE.WELCOME]: 'onboarding',
  [EMAIL_TYPE.PASSWORD_RESET]: 'security',
  [EMAIL_TYPE.VERIFICATION]: 'security',
  [EMAIL_TYPE.FOLLOW_UP]: 'follow_up',
  [EMAIL_TYPE.REMINDER]: 'reminder',
  [EMAIL_TYPE.THANK_YOU]: 'communication',
  [EMAIL_TYPE.APOLOGY]: 'communication',
  [EMAIL_TYPE.CONFIRMATION]: 'communication',
  [EMAIL_TYPE.INVOICE]: 'financial',
  [EMAIL_TYPE.RECEIPT]: 'financial',
  [EMAIL_TYPE.MAINTENANCE]: 'maintenance',
  [EMAIL_TYPE.SECURITY_ALERT]: 'security',
  [EMAIL_TYPE.SYSTEM_NOTIFICATION]: 'system',
  [EMAIL_TYPE.TEAM_UPDATE]: 'team',
  [EMAIL_TYPE.TRAINING]: 'training',
  [EMAIL_TYPE.ONBOARDING]: 'onboarding',
  [EMAIL_TYPE.OFFBOARDING]: 'offboarding',
  [EMAIL_TYPE.BILLING]: 'financial',
  [EMAIL_TYPE.PAYMENT_CONFIRMATION]: 'financial',
  [EMAIL_TYPE.REFUND]: 'financial',
  [EMAIL_TYPE.CANCELLATION]: 'order',
  [EMAIL_TYPE.RENEWAL]: 'subscription',
  [EMAIL_TYPE.UPGRADE]: 'subscription',
  [EMAIL_TYPE.DOWNGRADE]: 'subscription',
} as const;

/**
 * ইমেইল টাইপ গ্রুপ
 */
export const EMAIL_TYPE_GROUPS = {
  TICKET: [
    'ticket_creation',
    'ticket_update',
    'ticket_resolution',
    'ticket_closure',
    'ticket_escalation',
  ],
  COMMUNICATION: ['assignment', 'follow_up', 'reminder', 'thank_you', 'apology', 'confirmation'],
  SECURITY: ['password_reset', 'verification', 'security_alert'],
  NOTIFICATION: ['notification', 'alert', 'system_notification'],
  FINANCIAL: ['invoice', 'receipt', 'billing', 'payment_confirmation', 'refund'],
  SURVEY: ['satisfaction_survey', 'feedback_request'],
  ONBOARDING: ['welcome', 'onboarding', 'offboarding'],
  TEAM: ['team_update', 'training'],
  REPORTING: ['report'],
  MARKETING: ['newsletter'],
  COMPLAINT: ['complaint_acknowledgment'],
  MAINTENANCE: ['maintenance'],
  SUBSCRIPTION: ['renewal', 'upgrade', 'downgrade'],
  ORDER: ['cancellation'],
} as const;

export type EmailType = (typeof EMAIL_TYPE)[keyof typeof EMAIL_TYPE];
export type EmailTypeDisplayNames = typeof EMAIL_TYPE_DISPLAY_NAMES;
export type EmailTypeIcons = typeof EMAIL_TYPE_ICONS;
export type EmailTypeColors = typeof EMAIL_TYPE_COLORS;
export type EmailTypeCategories = typeof EMAIL_TYPE_CATEGORIES;
export type EmailTypeGroups = typeof EMAIL_TYPE_GROUPS;

export type EmailTypeGroup = keyof typeof EMAIL_TYPE_GROUPS;

export interface EmailTypeConfig {
  type: EmailType;
  displayName: string;
  icon: string;
  color: string;
  category: string;
  group: EmailTypeGroup;
  description?: string;
}

/**
 * ইমেইল টাইপ কনফিগারেশন অবজেক্ট
 */
export const EMAIL_TYPE_CONFIGS: Record<EmailType, EmailTypeConfig> = {
  [EMAIL_TYPE.TICKET_CREATION]: {
    type: EMAIL_TYPE.TICKET_CREATION,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.TICKET_CREATION],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.TICKET_CREATION],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.TICKET_CREATION],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.TICKET_CREATION],
    group: 'TICKET',
    description: 'টিকেট তৈরি হলে প্রেরিত ইমেইল',
  },
  [EMAIL_TYPE.TICKET_UPDATE]: {
    type: EMAIL_TYPE.TICKET_UPDATE,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.TICKET_UPDATE],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.TICKET_UPDATE],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.TICKET_UPDATE],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.TICKET_UPDATE],
    group: 'TICKET',
    description: 'টিকেট আপডেট হলে প্রেরিত ইমেইল',
  },
  [EMAIL_TYPE.TICKET_RESOLUTION]: {
    type: EMAIL_TYPE.TICKET_RESOLUTION,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.TICKET_RESOLUTION],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.TICKET_RESOLUTION],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.TICKET_RESOLUTION],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.TICKET_RESOLUTION],
    group: 'TICKET',
    description: 'টিকেট সমাধান হলে প্রেরিত ইমেইল',
  },
  [EMAIL_TYPE.TICKET_CLOSURE]: {
    type: EMAIL_TYPE.TICKET_CLOSURE,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.TICKET_CLOSURE],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.TICKET_CLOSURE],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.TICKET_CLOSURE],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.TICKET_CLOSURE],
    group: 'TICKET',
    description: 'টিকেট বন্ধ হলে প্রেরিত ইমেইল',
  },
  [EMAIL_TYPE.TICKET_ESCALATION]: {
    type: EMAIL_TYPE.TICKET_ESCALATION,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.TICKET_ESCALATION],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.TICKET_ESCALATION],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.TICKET_ESCALATION],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.TICKET_ESCALATION],
    group: 'TICKET',
    description: 'টিকেট এস্কেলেট হলে প্রেরিত ইমেইল',
  },
  [EMAIL_TYPE.ASSIGNMENT]: {
    type: EMAIL_TYPE.ASSIGNMENT,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.ASSIGNMENT],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.ASSIGNMENT],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.ASSIGNMENT],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.ASSIGNMENT],
    group: 'COMMUNICATION',
    description: 'টিকেট অ্যাসাইন হলে প্রেরিত ইমেইল',
  },
  [EMAIL_TYPE.SATISFACTION_SURVEY]: {
    type: EMAIL_TYPE.SATISFACTION_SURVEY,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.SATISFACTION_SURVEY],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.SATISFACTION_SURVEY],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.SATISFACTION_SURVEY],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.SATISFACTION_SURVEY],
    group: 'SURVEY',
    description: 'সন্তুষ্টি জরিপের জন্য প্রেরিত ইমেইল',
  },
  [EMAIL_TYPE.FEEDBACK_REQUEST]: {
    type: EMAIL_TYPE.FEEDBACK_REQUEST,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.FEEDBACK_REQUEST],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.FEEDBACK_REQUEST],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.FEEDBACK_REQUEST],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.FEEDBACK_REQUEST],
    group: 'SURVEY',
    description: 'ফিডব্যাক অনুরোধের ইমেইল',
  },
  [EMAIL_TYPE.COMPLAINT_ACKNOWLEDGMENT]: {
    type: EMAIL_TYPE.COMPLAINT_ACKNOWLEDGMENT,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.COMPLAINT_ACKNOWLEDGMENT],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.COMPLAINT_ACKNOWLEDGMENT],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.COMPLAINT_ACKNOWLEDGMENT],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.COMPLAINT_ACKNOWLEDGMENT],
    group: 'COMPLAINT',
    description: 'অভিযোগ স্বীকারের ইমেইল',
  },
  [EMAIL_TYPE.NEWSLETTER]: {
    type: EMAIL_TYPE.NEWSLETTER,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.NEWSLETTER],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.NEWSLETTER],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.NEWSLETTER],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.NEWSLETTER],
    group: 'MARKETING',
    description: 'নিউজলেটার ইমেইল',
  },
  [EMAIL_TYPE.ALERT]: {
    type: EMAIL_TYPE.ALERT,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.ALERT],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.ALERT],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.ALERT],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.ALERT],
    group: 'NOTIFICATION',
    description: 'অ্যালার্ট ইমেইল',
  },
  [EMAIL_TYPE.REPORT]: {
    type: EMAIL_TYPE.REPORT,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.REPORT],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.REPORT],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.REPORT],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.REPORT],
    group: 'REPORTING',
    description: 'রিপোর্ট ইমেইল',
  },
  [EMAIL_TYPE.NOTIFICATION]: {
    type: EMAIL_TYPE.NOTIFICATION,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.NOTIFICATION],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.NOTIFICATION],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.NOTIFICATION],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.NOTIFICATION],
    group: 'NOTIFICATION',
    description: 'সাধারণ নোটিফিকেশন ইমেইল',
  },
  [EMAIL_TYPE.WELCOME]: {
    type: EMAIL_TYPE.WELCOME,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.WELCOME],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.WELCOME],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.WELCOME],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.WELCOME],
    group: 'ONBOARDING',
    description: 'স্বাগতম ইমেইল',
  },
  [EMAIL_TYPE.PASSWORD_RESET]: {
    type: EMAIL_TYPE.PASSWORD_RESET,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.PASSWORD_RESET],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.PASSWORD_RESET],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.PASSWORD_RESET],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.PASSWORD_RESET],
    group: 'SECURITY',
    description: 'পাসওয়ার্ড রিসেট ইমেইল',
  },
  [EMAIL_TYPE.VERIFICATION]: {
    type: EMAIL_TYPE.VERIFICATION,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.VERIFICATION],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.VERIFICATION],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.VERIFICATION],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.VERIFICATION],
    group: 'SECURITY',
    description: 'যাচাইকরণ ইমেইল',
  },
  [EMAIL_TYPE.FOLLOW_UP]: {
    type: EMAIL_TYPE.FOLLOW_UP,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.FOLLOW_UP],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.FOLLOW_UP],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.FOLLOW_UP],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.FOLLOW_UP],
    group: 'COMMUNICATION',
    description: 'ফলো-আপ ইমেইল',
  },
  [EMAIL_TYPE.REMINDER]: {
    type: EMAIL_TYPE.REMINDER,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.REMINDER],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.REMINDER],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.REMINDER],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.REMINDER],
    group: 'COMMUNICATION',
    description: 'রিমাইন্ডার ইমেইল',
  },
  [EMAIL_TYPE.THANK_YOU]: {
    type: EMAIL_TYPE.THANK_YOU,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.THANK_YOU],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.THANK_YOU],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.THANK_YOU],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.THANK_YOU],
    group: 'COMMUNICATION',
    description: 'ধন্যবাদ ইমেইল',
  },
  [EMAIL_TYPE.APOLOGY]: {
    type: EMAIL_TYPE.APOLOGY,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.APOLOGY],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.APOLOGY],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.APOLOGY],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.APOLOGY],
    group: 'COMMUNICATION',
    description: 'ক্ষমা প্রার্থনা ইমেইল',
  },
  [EMAIL_TYPE.CONFIRMATION]: {
    type: EMAIL_TYPE.CONFIRMATION,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.CONFIRMATION],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.CONFIRMATION],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.CONFIRMATION],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.CONFIRMATION],
    group: 'COMMUNICATION',
    description: 'নিশ্চিতকরণ ইমেইল',
  },
  [EMAIL_TYPE.INVOICE]: {
    type: EMAIL_TYPE.INVOICE,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.INVOICE],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.INVOICE],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.INVOICE],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.INVOICE],
    group: 'FINANCIAL',
    description: 'ইনভয়েস ইমেইল',
  },
  [EMAIL_TYPE.RECEIPT]: {
    type: EMAIL_TYPE.RECEIPT,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.RECEIPT],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.RECEIPT],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.RECEIPT],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.RECEIPT],
    group: 'FINANCIAL',
    description: 'রসিদ ইমেইল',
  },
  [EMAIL_TYPE.MAINTENANCE]: {
    type: EMAIL_TYPE.MAINTENANCE,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.MAINTENANCE],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.MAINTENANCE],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.MAINTENANCE],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.MAINTENANCE],
    group: 'MAINTENANCE',
    description: 'মেইনটেন্যান্স ইমেইল',
  },
  [EMAIL_TYPE.SECURITY_ALERT]: {
    type: EMAIL_TYPE.SECURITY_ALERT,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.SECURITY_ALERT],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.SECURITY_ALERT],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.SECURITY_ALERT],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.SECURITY_ALERT],
    group: 'SECURITY',
    description: 'সিকিউরিটি অ্যালার্ট ইমেইল',
  },
  [EMAIL_TYPE.SYSTEM_NOTIFICATION]: {
    type: EMAIL_TYPE.SYSTEM_NOTIFICATION,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.SYSTEM_NOTIFICATION],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.SYSTEM_NOTIFICATION],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.SYSTEM_NOTIFICATION],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.SYSTEM_NOTIFICATION],
    group: 'NOTIFICATION',
    description: 'সিস্টেম নোটিফিকেশন ইমেইল',
  },
  [EMAIL_TYPE.TEAM_UPDATE]: {
    type: EMAIL_TYPE.TEAM_UPDATE,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.TEAM_UPDATE],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.TEAM_UPDATE],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.TEAM_UPDATE],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.TEAM_UPDATE],
    group: 'TEAM',
    description: 'টিম আপডেট ইমেইল',
  },
  [EMAIL_TYPE.TRAINING]: {
    type: EMAIL_TYPE.TRAINING,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.TRAINING],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.TRAINING],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.TRAINING],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.TRAINING],
    group: 'TEAM',
    description: 'প্রশিক্ষণ ইমেইল',
  },
  [EMAIL_TYPE.ONBOARDING]: {
    type: EMAIL_TYPE.ONBOARDING,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.ONBOARDING],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.ONBOARDING],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.ONBOARDING],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.ONBOARDING],
    group: 'ONBOARDING',
    description: 'অনবোর্ডিং ইমেইল',
  },
  [EMAIL_TYPE.OFFBOARDING]: {
    type: EMAIL_TYPE.OFFBOARDING,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.OFFBOARDING],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.OFFBOARDING],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.OFFBOARDING],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.OFFBOARDING],
    group: 'ONBOARDING',
    description: 'অফবোর্ডিং ইমেইল',
  },
  [EMAIL_TYPE.BILLING]: {
    type: EMAIL_TYPE.BILLING,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.BILLING],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.BILLING],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.BILLING],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.BILLING],
    group: 'FINANCIAL',
    description: 'বিলিং ইমেইল',
  },
  [EMAIL_TYPE.PAYMENT_CONFIRMATION]: {
    type: EMAIL_TYPE.PAYMENT_CONFIRMATION,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.PAYMENT_CONFIRMATION],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.PAYMENT_CONFIRMATION],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.PAYMENT_CONFIRMATION],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.PAYMENT_CONFIRMATION],
    group: 'FINANCIAL',
    description: 'পেমেন্ট নিশ্চিতকরণ ইমেইল',
  },
  [EMAIL_TYPE.REFUND]: {
    type: EMAIL_TYPE.REFUND,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.REFUND],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.REFUND],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.REFUND],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.REFUND],
    group: 'FINANCIAL',
    description: 'রিফান্ড ইমেইল',
  },
  [EMAIL_TYPE.CANCELLATION]: {
    type: EMAIL_TYPE.CANCELLATION,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.CANCELLATION],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.CANCELLATION],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.CANCELLATION],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.CANCELLATION],
    group: 'ORDER',
    description: 'বাতিলকরণ ইমেইল',
  },
  [EMAIL_TYPE.RENEWAL]: {
    type: EMAIL_TYPE.RENEWAL,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.RENEWAL],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.RENEWAL],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.RENEWAL],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.RENEWAL],
    group: 'SUBSCRIPTION',
    description: 'রিনিউয়াল ইমেইল',
  },
  [EMAIL_TYPE.UPGRADE]: {
    type: EMAIL_TYPE.UPGRADE,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.UPGRADE],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.UPGRADE],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.UPGRADE],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.UPGRADE],
    group: 'SUBSCRIPTION',
    description: 'আপগ্রেড ইমেইল',
  },
  [EMAIL_TYPE.DOWNGRADE]: {
    type: EMAIL_TYPE.DOWNGRADE,
    displayName: EMAIL_TYPE_DISPLAY_NAMES[EMAIL_TYPE.DOWNGRADE],
    icon: EMAIL_TYPE_ICONS[EMAIL_TYPE.DOWNGRADE],
    color: EMAIL_TYPE_COLORS[EMAIL_TYPE.DOWNGRADE],
    category: EMAIL_TYPE_CATEGORIES[EMAIL_TYPE.DOWNGRADE],
    group: 'SUBSCRIPTION',
    description: 'ডাউনগ্রেড ইমেইল',
  },
};

/**
 * ইমেইল টাইপ গ্রুপ কনফিগারেশন
 */
export const EMAIL_TYPE_GROUP_CONFIGS: Record<
  EmailTypeGroup,
  {
    group: EmailTypeGroup;
    displayName: string;
    icon: string;
    color: string;
    types: readonly EmailType[];
    description?: string;
  }
> = {
  TICKET: {
    group: 'TICKET',
    displayName: 'টিকেট',
    icon: 'ticket',
    color: '#e67e22',
    types: [
      'ticket_creation',
      'ticket_update',
      'ticket_resolution',
      'ticket_closure',
      'ticket_escalation',
    ] as const,
    description: 'টিকেট সম্পর্কিত ইমেইল',
  },
  COMMUNICATION: {
    group: 'COMMUNICATION',
    displayName: 'যোগাযোগ',
    icon: 'message-circle',
    color: '#3498db',
    types: ['assignment', 'follow_up', 'reminder', 'thank_you', 'apology', 'confirmation'] as const,
    description: 'যোগাযোগ সম্পর্কিত ইমেইল',
  },
  SECURITY: {
    group: 'SECURITY',
    displayName: 'সিকিউরিটি',
    icon: 'shield',
    color: '#e74c3c',
    types: ['password_reset', 'verification', 'security_alert'] as const,
    description: 'সিকিউরিটি সম্পর্কিত ইমেইল',
  },
  NOTIFICATION: {
    group: 'NOTIFICATION',
    displayName: 'নোটিফিকেশন',
    icon: 'bell',
    color: '#f39c12',
    types: ['notification', 'alert', 'system_notification'] as const,
    description: 'নোটিফিকেশন সম্পর্কিত ইমেইল',
  },
  FINANCIAL: {
    group: 'FINANCIAL',
    displayName: 'আর্থিক',
    icon: 'dollar-sign',
    color: '#27ae60',
    types: ['invoice', 'receipt', 'billing', 'payment_confirmation', 'refund'] as const,
    description: 'আর্থিক সম্পর্কিত ইমেইল',
  },
  SURVEY: {
    group: 'SURVEY',
    displayName: 'জরিপ',
    icon: 'clipboard',
    color: '#9b59b6',
    types: ['satisfaction_survey', 'feedback_request'] as const,
    description: 'জরিপ সম্পর্কিত ইমেইল',
  },
  ONBOARDING: {
    group: 'ONBOARDING',
    displayName: 'অনবোর্ডিং',
    icon: 'user-plus',
    color: '#2ecc71',
    types: ['welcome', 'onboarding', 'offboarding'] as const,
    description: 'অনবোর্ডিং সম্পর্কিত ইমেইল',
  },
  TEAM: {
    group: 'TEAM',
    displayName: 'টিম',
    icon: 'users',
    color: '#1abc9c',
    types: ['team_update', 'training'] as const,
    description: 'টিম সম্পর্কিত ইমেইল',
  },
  REPORTING: {
    group: 'REPORTING',
    displayName: 'রিপোর্টিং',
    icon: 'file-text',
    color: '#f39c12',
    types: ['report'] as const,
    description: 'রিপোর্ট সম্পর্কিত ইমেইল',
  },
  MARKETING: {
    group: 'MARKETING',
    displayName: 'মার্কেটিং',
    icon: 'mail',
    color: '#3498db',
    types: ['newsletter'] as const,
    description: 'মার্কেটিং সম্পর্কিত ইমেইল',
  },
  COMPLAINT: {
    group: 'COMPLAINT',
    displayName: 'অভিযোগ',
    icon: 'alert-triangle',
    color: '#e74c3c',
    types: ['complaint_acknowledgment'] as const,
    description: 'অভিযোগ সম্পর্কিত ইমেইল',
  },
  MAINTENANCE: {
    group: 'MAINTENANCE',
    displayName: 'মেইনটেন্যান্স',
    icon: 'wrench',
    color: '#e67e22',
    types: ['maintenance'] as const,
    description: 'মেইনটেন্যান্স সম্পর্কিত ইমেইল',
  },
  SUBSCRIPTION: {
    group: 'SUBSCRIPTION',
    displayName: 'সাবস্ক্রিপশন',
    icon: 'repeat',
    color: '#8e44ad',
    types: ['renewal', 'upgrade', 'downgrade'] as const,
    description: 'সাবস্ক্রিপশন সম্পর্কিত ইমেইল',
  },
  ORDER: {
    group: 'ORDER',
    displayName: 'অর্ডার',
    icon: 'shopping-bag',
    color: '#e67e22',
    types: ['cancellation'] as const,
    description: 'অর্ডার সম্পর্কিত ইমেইল',
  },
};

/**
 * ইমেইল টাইপ স্ট্যাটাস
 */
export const EMAIL_TYPE_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  DEPRECATED: 'deprecated',
} as const;

export type EmailTypeStatus = (typeof EMAIL_TYPE_STATUS)[keyof typeof EMAIL_TYPE_STATUS];
