/**
 * সাপোর্ট SMS এর বিভিন্ন টাইপ সংক্রান্ত কনস্ট্যান্টসমূহ
 */

/**
 * SMS টাইপ
 */
export const SMS_TYPE = {
  OTP: 'otp',
  NOTIFICATION: 'notification',
  ALERT: 'alert',
  TICKET_UPDATE: 'ticket_update',
  REMINDER: 'reminder',
  SURVEY: 'survey',
  MARKETING: 'marketing',
  TRANSACTIONAL: 'transactional',
  PROMOTIONAL: 'promotional',
  SERVICE_UPDATE: 'service_update',
  EMERGENCY: 'emergency',
  CUSTOMER_FEEDBACK: 'customer_feedback',
  APPOINTMENT_REMINDER: 'appointment_reminder',
  VERIFICATION: 'verification',
  WELCOME: 'welcome',
  PASSWORD_RESET: 'password_reset',
  ORDER_CONFIRMATION: 'order_confirmation',
  DELIVERY_UPDATE: 'delivery_update',
  PAYMENT_CONFIRMATION: 'payment_confirmation',
  REFUND_UPDATE: 'refund_update',
  SUPPORT_ESCALATION: 'support_escalation',
  FOLLOW_UP: 'follow_up',
  THANK_YOU: 'thank_you',
  APOLOGY: 'apology',
  MAINTENANCE: 'maintenance',
  SECURITY_ALERT: 'security_alert',
  SYSTEM_NOTIFICATION: 'system_notification',
  TEAM_UPDATE: 'team_update',
  TRAINING: 'training',
  ONBOARDING: 'onboarding',
  OFFBOARDING: 'offboarding',
  BILLING: 'billing',
  RENEWAL: 'renewal',
  UPGRADE: 'upgrade',
  DOWNGRADE: 'downgrade',
  CANCELLATION: 'cancellation',
} as const;

/**
 * SMS টাইপের ডিসপ্লে নাম
 */
export const SMS_TYPE_DISPLAY_NAMES = {
  [SMS_TYPE.OTP]: 'ওটিপি',
  [SMS_TYPE.NOTIFICATION]: 'নোটিফিকেশন',
  [SMS_TYPE.ALERT]: 'অ্যালার্ট',
  [SMS_TYPE.TICKET_UPDATE]: 'টিকেট আপডেট',
  [SMS_TYPE.REMINDER]: 'রিমাইন্ডার',
  [SMS_TYPE.SURVEY]: 'জরিপ',
  [SMS_TYPE.MARKETING]: 'মার্কেটিং',
  [SMS_TYPE.TRANSACTIONAL]: 'ট্রানজেকশনাল',
  [SMS_TYPE.PROMOTIONAL]: 'প্রমোশনাল',
  [SMS_TYPE.SERVICE_UPDATE]: 'সার্ভিস আপডেট',
  [SMS_TYPE.EMERGENCY]: 'জরুরি',
  [SMS_TYPE.CUSTOMER_FEEDBACK]: 'গ্রাহক ফিডব্যাক',
  [SMS_TYPE.APPOINTMENT_REMINDER]: 'অ্যাপয়েন্টমেন্ট রিমাইন্ডার',
  [SMS_TYPE.VERIFICATION]: 'যাচাইকরণ',
  [SMS_TYPE.WELCOME]: 'স্বাগতম',
  [SMS_TYPE.PASSWORD_RESET]: 'পাসওয়ার্ড রিসেট',
  [SMS_TYPE.ORDER_CONFIRMATION]: 'অর্ডার নিশ্চিতকরণ',
  [SMS_TYPE.DELIVERY_UPDATE]: 'ডেলিভারি আপডেট',
  [SMS_TYPE.PAYMENT_CONFIRMATION]: 'পেমেন্ট নিশ্চিতকরণ',
  [SMS_TYPE.REFUND_UPDATE]: 'রিফান্ড আপডেট',
  [SMS_TYPE.SUPPORT_ESCALATION]: 'সাপোর্ট এস্কেলেশন',
  [SMS_TYPE.FOLLOW_UP]: 'ফলো-আপ',
  [SMS_TYPE.THANK_YOU]: 'ধন্যবাদ',
  [SMS_TYPE.APOLOGY]: 'ক্ষমা প্রার্থনা',
  [SMS_TYPE.MAINTENANCE]: 'মেইনটেন্যান্স',
  [SMS_TYPE.SECURITY_ALERT]: 'সিকিউরিটি অ্যালার্ট',
  [SMS_TYPE.SYSTEM_NOTIFICATION]: 'সিস্টেম নোটিফিকেশন',
  [SMS_TYPE.TEAM_UPDATE]: 'টিম আপডেট',
  [SMS_TYPE.TRAINING]: 'প্রশিক্ষণ',
  [SMS_TYPE.ONBOARDING]: 'অনবোর্ডিং',
  [SMS_TYPE.OFFBOARDING]: 'অফবোর্ডিং',
  [SMS_TYPE.BILLING]: 'বিলিং',
  [SMS_TYPE.RENEWAL]: 'রিনিউয়াল',
  [SMS_TYPE.UPGRADE]: 'আপগ্রেড',
  [SMS_TYPE.DOWNGRADE]: 'ডাউনগ্রেড',
  [SMS_TYPE.CANCELLATION]: 'বাতিলকরণ',
} as const;

/**
 * SMS টাইপের আইকন (অনুষঙ্গিক নাম)
 */
export const SMS_TYPE_ICONS = {
  [SMS_TYPE.OTP]: 'shield',
  [SMS_TYPE.NOTIFICATION]: 'bell',
  [SMS_TYPE.ALERT]: 'alert-circle',
  [SMS_TYPE.TICKET_UPDATE]: 'ticket',
  [SMS_TYPE.REMINDER]: 'clock',
  [SMS_TYPE.SURVEY]: 'clipboard',
  [SMS_TYPE.MARKETING]: 'mail',
  [SMS_TYPE.TRANSACTIONAL]: 'credit-card',
  [SMS_TYPE.PROMOTIONAL]: 'megaphone',
  [SMS_TYPE.SERVICE_UPDATE]: 'refresh-cw',
  [SMS_TYPE.EMERGENCY]: 'alert-triangle',
  [SMS_TYPE.CUSTOMER_FEEDBACK]: 'message-square',
  [SMS_TYPE.APPOINTMENT_REMINDER]: 'calendar',
  [SMS_TYPE.VERIFICATION]: 'check-circle',
  [SMS_TYPE.WELCOME]: 'smile',
  [SMS_TYPE.PASSWORD_RESET]: 'key',
  [SMS_TYPE.ORDER_CONFIRMATION]: 'shopping-bag',
  [SMS_TYPE.DELIVERY_UPDATE]: 'truck',
  [SMS_TYPE.PAYMENT_CONFIRMATION]: 'dollar-sign',
  [SMS_TYPE.REFUND_UPDATE]: 'rotate-ccw',
  [SMS_TYPE.SUPPORT_ESCALATION]: 'arrow-up-circle',
  [SMS_TYPE.FOLLOW_UP]: 'refresh-cw',
  [SMS_TYPE.THANK_YOU]: 'thumbs-up',
  [SMS_TYPE.APOLOGY]: 'frown',
  [SMS_TYPE.MAINTENANCE]: 'wrench',
  [SMS_TYPE.SECURITY_ALERT]: 'shield',
  [SMS_TYPE.SYSTEM_NOTIFICATION]: 'cpu',
  [SMS_TYPE.TEAM_UPDATE]: 'users',
  [SMS_TYPE.TRAINING]: 'book',
  [SMS_TYPE.ONBOARDING]: 'user-plus',
  [SMS_TYPE.OFFBOARDING]: 'user-minus',
  [SMS_TYPE.BILLING]: 'file-text',
  [SMS_TYPE.RENEWAL]: 'refresh-cw',
  [SMS_TYPE.UPGRADE]: 'arrow-up',
  [SMS_TYPE.DOWNGRADE]: 'arrow-down',
  [SMS_TYPE.CANCELLATION]: 'x-circle',
} as const;

/**
 * SMS টাইপের রঙের কোড (হেক্স)
 */
export const SMS_TYPE_COLORS = {
  [SMS_TYPE.OTP]: '#3498db',
  [SMS_TYPE.NOTIFICATION]: '#1abc9c',
  [SMS_TYPE.ALERT]: '#e74c3c',
  [SMS_TYPE.TICKET_UPDATE]: '#e67e22',
  [SMS_TYPE.REMINDER]: '#f39c12',
  [SMS_TYPE.SURVEY]: '#9b59b6',
  [SMS_TYPE.MARKETING]: '#2ecc71',
  [SMS_TYPE.TRANSACTIONAL]: '#27ae60',
  [SMS_TYPE.PROMOTIONAL]: '#f1c40f',
  [SMS_TYPE.SERVICE_UPDATE]: '#3498db',
  [SMS_TYPE.EMERGENCY]: '#c0392b',
  [SMS_TYPE.CUSTOMER_FEEDBACK]: '#8e44ad',
  [SMS_TYPE.APPOINTMENT_REMINDER]: '#2980b9',
  [SMS_TYPE.VERIFICATION]: '#2ecc71',
  [SMS_TYPE.WELCOME]: '#27ae60',
  [SMS_TYPE.PASSWORD_RESET]: '#e67e22',
  [SMS_TYPE.ORDER_CONFIRMATION]: '#3498db',
  [SMS_TYPE.DELIVERY_UPDATE]: '#f39c12',
  [SMS_TYPE.PAYMENT_CONFIRMATION]: '#2ecc71',
  [SMS_TYPE.REFUND_UPDATE]: '#e67e22',
  [SMS_TYPE.SUPPORT_ESCALATION]: '#e74c3c',
  [SMS_TYPE.FOLLOW_UP]: '#3498db',
  [SMS_TYPE.THANK_YOU]: '#2ecc71',
  [SMS_TYPE.APOLOGY]: '#e67e22',
  [SMS_TYPE.MAINTENANCE]: '#e67e22',
  [SMS_TYPE.SECURITY_ALERT]: '#c0392b',
  [SMS_TYPE.SYSTEM_NOTIFICATION]: '#2c3e50',
  [SMS_TYPE.TEAM_UPDATE]: '#1abc9c',
  [SMS_TYPE.TRAINING]: '#3498db',
  [SMS_TYPE.ONBOARDING]: '#2ecc71',
  [SMS_TYPE.OFFBOARDING]: '#e74c3c',
  [SMS_TYPE.BILLING]: '#27ae60',
  [SMS_TYPE.RENEWAL]: '#3498db',
  [SMS_TYPE.UPGRADE]: '#2ecc71',
  [SMS_TYPE.DOWNGRADE]: '#e74c3c',
  [SMS_TYPE.CANCELLATION]: '#e74c3c',
} as const;

/**
 * SMS টাইপের ক্যাটাগরি
 */
export const SMS_TYPE_CATEGORIES = {
  [SMS_TYPE.OTP]: 'security',
  [SMS_TYPE.NOTIFICATION]: 'communication',
  [SMS_TYPE.ALERT]: 'alert',
  [SMS_TYPE.TICKET_UPDATE]: 'ticket',
  [SMS_TYPE.REMINDER]: 'reminder',
  [SMS_TYPE.SURVEY]: 'survey',
  [SMS_TYPE.MARKETING]: 'marketing',
  [SMS_TYPE.TRANSACTIONAL]: 'transactional',
  [SMS_TYPE.PROMOTIONAL]: 'marketing',
  [SMS_TYPE.SERVICE_UPDATE]: 'service',
  [SMS_TYPE.EMERGENCY]: 'emergency',
  [SMS_TYPE.CUSTOMER_FEEDBACK]: 'feedback',
  [SMS_TYPE.APPOINTMENT_REMINDER]: 'reminder',
  [SMS_TYPE.VERIFICATION]: 'security',
  [SMS_TYPE.WELCOME]: 'onboarding',
  [SMS_TYPE.PASSWORD_RESET]: 'security',
  [SMS_TYPE.ORDER_CONFIRMATION]: 'order',
  [SMS_TYPE.DELIVERY_UPDATE]: 'order',
  [SMS_TYPE.PAYMENT_CONFIRMATION]: 'financial',
  [SMS_TYPE.REFUND_UPDATE]: 'financial',
  [SMS_TYPE.SUPPORT_ESCALATION]: 'support',
  [SMS_TYPE.FOLLOW_UP]: 'communication',
  [SMS_TYPE.THANK_YOU]: 'communication',
  [SMS_TYPE.APOLOGY]: 'communication',
  [SMS_TYPE.MAINTENANCE]: 'maintenance',
  [SMS_TYPE.SECURITY_ALERT]: 'security',
  [SMS_TYPE.SYSTEM_NOTIFICATION]: 'system',
  [SMS_TYPE.TEAM_UPDATE]: 'team',
  [SMS_TYPE.TRAINING]: 'training',
  [SMS_TYPE.ONBOARDING]: 'onboarding',
  [SMS_TYPE.OFFBOARDING]: 'offboarding',
  [SMS_TYPE.BILLING]: 'financial',
  [SMS_TYPE.RENEWAL]: 'subscription',
  [SMS_TYPE.UPGRADE]: 'subscription',
  [SMS_TYPE.DOWNGRADE]: 'subscription',
  [SMS_TYPE.CANCELLATION]: 'order',
} as const;

/**
 * SMS টাইপের ডিফল্ট প্রায়োরিটি
 */
export const SMS_TYPE_DEFAULT_PRIORITY = {
  [SMS_TYPE.OTP]: 'high',
  [SMS_TYPE.NOTIFICATION]: 'normal',
  [SMS_TYPE.ALERT]: 'high',
  [SMS_TYPE.TICKET_UPDATE]: 'normal',
  [SMS_TYPE.REMINDER]: 'normal',
  [SMS_TYPE.SURVEY]: 'low',
  [SMS_TYPE.MARKETING]: 'low',
  [SMS_TYPE.TRANSACTIONAL]: 'normal',
  [SMS_TYPE.PROMOTIONAL]: 'low',
  [SMS_TYPE.SERVICE_UPDATE]: 'normal',
  [SMS_TYPE.EMERGENCY]: 'urgent',
  [SMS_TYPE.CUSTOMER_FEEDBACK]: 'low',
  [SMS_TYPE.APPOINTMENT_REMINDER]: 'normal',
  [SMS_TYPE.VERIFICATION]: 'high',
  [SMS_TYPE.WELCOME]: 'normal',
  [SMS_TYPE.PASSWORD_RESET]: 'high',
  [SMS_TYPE.ORDER_CONFIRMATION]: 'high',
  [SMS_TYPE.DELIVERY_UPDATE]: 'normal',
  [SMS_TYPE.PAYMENT_CONFIRMATION]: 'high',
  [SMS_TYPE.REFUND_UPDATE]: 'normal',
  [SMS_TYPE.SUPPORT_ESCALATION]: 'high',
  [SMS_TYPE.FOLLOW_UP]: 'normal',
  [SMS_TYPE.THANK_YOU]: 'low',
  [SMS_TYPE.APOLOGY]: 'normal',
  [SMS_TYPE.MAINTENANCE]: 'normal',
  [SMS_TYPE.SECURITY_ALERT]: 'urgent',
  [SMS_TYPE.SYSTEM_NOTIFICATION]: 'normal',
  [SMS_TYPE.TEAM_UPDATE]: 'normal',
  [SMS_TYPE.TRAINING]: 'low',
  [SMS_TYPE.ONBOARDING]: 'normal',
  [SMS_TYPE.OFFBOARDING]: 'normal',
  [SMS_TYPE.BILLING]: 'normal',
  [SMS_TYPE.RENEWAL]: 'normal',
  [SMS_TYPE.UPGRADE]: 'normal',
  [SMS_TYPE.DOWNGRADE]: 'normal',
  [SMS_TYPE.CANCELLATION]: 'high',
} as const;

/**
 * SMS টাইপ গ্রুপ
 */
export const SMS_TYPE_GROUPS = {
  SECURITY: ['otp', 'verification', 'password_reset', 'security_alert'],
  COMMUNICATION: ['notification', 'follow_up', 'thank_you', 'apology'],
  TICKET: ['ticket_update', 'support_escalation'],
  REMINDER: ['reminder', 'appointment_reminder'],
  SURVEY: ['survey', 'customer_feedback'],
  MARKETING: ['marketing', 'promotional'],
  TRANSACTIONAL: ['transactional', 'payment_confirmation', 'refund_update'],
  ORDER: ['order_confirmation', 'delivery_update', 'cancellation'],
  SERVICE: ['service_update', 'maintenance'],
  EMERGENCY: ['emergency', 'alert'],
  FINANCIAL: ['billing'],
  SUBSCRIPTION: ['renewal', 'upgrade', 'downgrade'],
  ONBOARDING: ['welcome', 'onboarding', 'offboarding'],
  TEAM: ['team_update', 'training'],
  SYSTEM: ['system_notification'],
} as const;

export type SmsType = (typeof SMS_TYPE)[keyof typeof SMS_TYPE];
export type SmsTypeDisplayNames = typeof SMS_TYPE_DISPLAY_NAMES;
export type SmsTypeIcons = typeof SMS_TYPE_ICONS;
export type SmsTypeColors = typeof SMS_TYPE_COLORS;
export type SmsTypeCategories = typeof SMS_TYPE_CATEGORIES;
export type SmsTypeDefaultPriority = typeof SMS_TYPE_DEFAULT_PRIORITY;
export type SmsTypeGroups = typeof SMS_TYPE_GROUPS;

export type SmsTypeGroup = keyof typeof SMS_TYPE_GROUPS;

export interface SmsTypeConfig {
  type: SmsType;
  displayName: string;
  icon: string;
  color: string;
  category: string;
  defaultPriority: 'low' | 'normal' | 'high' | 'urgent';
  group: SmsTypeGroup;
  description?: string;
}

/**
 * SMS টাইপ কনফিগারেশন অবজেক্ট
 */
export const SMS_TYPE_CONFIGS: Record<SmsType, SmsTypeConfig> = {
  [SMS_TYPE.OTP]: {
    type: SMS_TYPE.OTP,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.OTP],
    icon: SMS_TYPE_ICONS[SMS_TYPE.OTP],
    color: SMS_TYPE_COLORS[SMS_TYPE.OTP],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.OTP],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.OTP] as 'high',
    group: 'SECURITY',
    description: 'একবার ব্যবহারযোগ্য পাসওয়ার্ড',
  },
  [SMS_TYPE.NOTIFICATION]: {
    type: SMS_TYPE.NOTIFICATION,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.NOTIFICATION],
    icon: SMS_TYPE_ICONS[SMS_TYPE.NOTIFICATION],
    color: SMS_TYPE_COLORS[SMS_TYPE.NOTIFICATION],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.NOTIFICATION],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.NOTIFICATION] as 'normal',
    group: 'COMMUNICATION',
    description: 'সাধারণ নোটিফিকেশন',
  },
  [SMS_TYPE.ALERT]: {
    type: SMS_TYPE.ALERT,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.ALERT],
    icon: SMS_TYPE_ICONS[SMS_TYPE.ALERT],
    color: SMS_TYPE_COLORS[SMS_TYPE.ALERT],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.ALERT],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.ALERT] as 'high',
    group: 'EMERGENCY',
    description: 'জরুরি সতর্কতা',
  },
  [SMS_TYPE.TICKET_UPDATE]: {
    type: SMS_TYPE.TICKET_UPDATE,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.TICKET_UPDATE],
    icon: SMS_TYPE_ICONS[SMS_TYPE.TICKET_UPDATE],
    color: SMS_TYPE_COLORS[SMS_TYPE.TICKET_UPDATE],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.TICKET_UPDATE],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.TICKET_UPDATE] as 'normal',
    group: 'TICKET',
    description: 'টিকেট আপডেট সম্পর্কিত SMS',
  },
  [SMS_TYPE.REMINDER]: {
    type: SMS_TYPE.REMINDER,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.REMINDER],
    icon: SMS_TYPE_ICONS[SMS_TYPE.REMINDER],
    color: SMS_TYPE_COLORS[SMS_TYPE.REMINDER],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.REMINDER],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.REMINDER] as 'normal',
    group: 'REMINDER',
    description: 'রিমাইন্ডার SMS',
  },
  [SMS_TYPE.SURVEY]: {
    type: SMS_TYPE.SURVEY,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.SURVEY],
    icon: SMS_TYPE_ICONS[SMS_TYPE.SURVEY],
    color: SMS_TYPE_COLORS[SMS_TYPE.SURVEY],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.SURVEY],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.SURVEY] as 'low',
    group: 'SURVEY',
    description: 'জরিপ সম্পর্কিত SMS',
  },
  [SMS_TYPE.MARKETING]: {
    type: SMS_TYPE.MARKETING,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.MARKETING],
    icon: SMS_TYPE_ICONS[SMS_TYPE.MARKETING],
    color: SMS_TYPE_COLORS[SMS_TYPE.MARKETING],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.MARKETING],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.MARKETING] as 'low',
    group: 'MARKETING',
    description: 'মার্কেটিং প্রচারণার SMS',
  },
  [SMS_TYPE.TRANSACTIONAL]: {
    type: SMS_TYPE.TRANSACTIONAL,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.TRANSACTIONAL],
    icon: SMS_TYPE_ICONS[SMS_TYPE.TRANSACTIONAL],
    color: SMS_TYPE_COLORS[SMS_TYPE.TRANSACTIONAL],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.TRANSACTIONAL],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.TRANSACTIONAL] as 'normal',
    group: 'TRANSACTIONAL',
    description: 'ট্রানজেকশন সম্পর্কিত SMS',
  },
  [SMS_TYPE.PROMOTIONAL]: {
    type: SMS_TYPE.PROMOTIONAL,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.PROMOTIONAL],
    icon: SMS_TYPE_ICONS[SMS_TYPE.PROMOTIONAL],
    color: SMS_TYPE_COLORS[SMS_TYPE.PROMOTIONAL],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.PROMOTIONAL],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.PROMOTIONAL] as 'low',
    group: 'MARKETING',
    description: 'প্রমোশনাল SMS',
  },
  [SMS_TYPE.SERVICE_UPDATE]: {
    type: SMS_TYPE.SERVICE_UPDATE,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.SERVICE_UPDATE],
    icon: SMS_TYPE_ICONS[SMS_TYPE.SERVICE_UPDATE],
    color: SMS_TYPE_COLORS[SMS_TYPE.SERVICE_UPDATE],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.SERVICE_UPDATE],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.SERVICE_UPDATE] as 'normal',
    group: 'SERVICE',
    description: 'সার্ভিস আপডেট সম্পর্কিত SMS',
  },
  [SMS_TYPE.EMERGENCY]: {
    type: SMS_TYPE.EMERGENCY,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.EMERGENCY],
    icon: SMS_TYPE_ICONS[SMS_TYPE.EMERGENCY],
    color: SMS_TYPE_COLORS[SMS_TYPE.EMERGENCY],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.EMERGENCY],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.EMERGENCY] as 'urgent',
    group: 'EMERGENCY',
    description: 'জরুরি পরিস্থিতির SMS',
  },
  [SMS_TYPE.CUSTOMER_FEEDBACK]: {
    type: SMS_TYPE.CUSTOMER_FEEDBACK,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.CUSTOMER_FEEDBACK],
    icon: SMS_TYPE_ICONS[SMS_TYPE.CUSTOMER_FEEDBACK],
    color: SMS_TYPE_COLORS[SMS_TYPE.CUSTOMER_FEEDBACK],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.CUSTOMER_FEEDBACK],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.CUSTOMER_FEEDBACK] as 'low',
    group: 'SURVEY',
    description: 'গ্রাহক ফিডব্যাক সংগ্রহ',
  },
  [SMS_TYPE.APPOINTMENT_REMINDER]: {
    type: SMS_TYPE.APPOINTMENT_REMINDER,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.APPOINTMENT_REMINDER],
    icon: SMS_TYPE_ICONS[SMS_TYPE.APPOINTMENT_REMINDER],
    color: SMS_TYPE_COLORS[SMS_TYPE.APPOINTMENT_REMINDER],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.APPOINTMENT_REMINDER],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.APPOINTMENT_REMINDER] as 'normal',
    group: 'REMINDER',
    description: 'অ্যাপয়েন্টমেন্ট রিমাইন্ডার',
  },
  [SMS_TYPE.VERIFICATION]: {
    type: SMS_TYPE.VERIFICATION,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.VERIFICATION],
    icon: SMS_TYPE_ICONS[SMS_TYPE.VERIFICATION],
    color: SMS_TYPE_COLORS[SMS_TYPE.VERIFICATION],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.VERIFICATION],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.VERIFICATION] as 'high',
    group: 'SECURITY',
    description: 'যাচাইকরণ SMS',
  },
  [SMS_TYPE.WELCOME]: {
    type: SMS_TYPE.WELCOME,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.WELCOME],
    icon: SMS_TYPE_ICONS[SMS_TYPE.WELCOME],
    color: SMS_TYPE_COLORS[SMS_TYPE.WELCOME],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.WELCOME],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.WELCOME] as 'normal',
    group: 'ONBOARDING',
    description: 'স্বাগতম SMS',
  },
  [SMS_TYPE.PASSWORD_RESET]: {
    type: SMS_TYPE.PASSWORD_RESET,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.PASSWORD_RESET],
    icon: SMS_TYPE_ICONS[SMS_TYPE.PASSWORD_RESET],
    color: SMS_TYPE_COLORS[SMS_TYPE.PASSWORD_RESET],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.PASSWORD_RESET],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.PASSWORD_RESET] as 'high',
    group: 'SECURITY',
    description: 'পাসওয়ার্ড রিসেট SMS',
  },
  [SMS_TYPE.ORDER_CONFIRMATION]: {
    type: SMS_TYPE.ORDER_CONFIRMATION,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.ORDER_CONFIRMATION],
    icon: SMS_TYPE_ICONS[SMS_TYPE.ORDER_CONFIRMATION],
    color: SMS_TYPE_COLORS[SMS_TYPE.ORDER_CONFIRMATION],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.ORDER_CONFIRMATION],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.ORDER_CONFIRMATION] as 'high',
    group: 'ORDER',
    description: 'অর্ডার নিশ্চিতকরণ SMS',
  },
  [SMS_TYPE.DELIVERY_UPDATE]: {
    type: SMS_TYPE.DELIVERY_UPDATE,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.DELIVERY_UPDATE],
    icon: SMS_TYPE_ICONS[SMS_TYPE.DELIVERY_UPDATE],
    color: SMS_TYPE_COLORS[SMS_TYPE.DELIVERY_UPDATE],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.DELIVERY_UPDATE],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.DELIVERY_UPDATE] as 'normal',
    group: 'ORDER',
    description: 'ডেলিভারি আপডেট SMS',
  },
  [SMS_TYPE.PAYMENT_CONFIRMATION]: {
    type: SMS_TYPE.PAYMENT_CONFIRMATION,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.PAYMENT_CONFIRMATION],
    icon: SMS_TYPE_ICONS[SMS_TYPE.PAYMENT_CONFIRMATION],
    color: SMS_TYPE_COLORS[SMS_TYPE.PAYMENT_CONFIRMATION],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.PAYMENT_CONFIRMATION],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.PAYMENT_CONFIRMATION] as 'high',
    group: 'TRANSACTIONAL',
    description: 'পেমেন্ট নিশ্চিতকরণ SMS',
  },
  [SMS_TYPE.REFUND_UPDATE]: {
    type: SMS_TYPE.REFUND_UPDATE,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.REFUND_UPDATE],
    icon: SMS_TYPE_ICONS[SMS_TYPE.REFUND_UPDATE],
    color: SMS_TYPE_COLORS[SMS_TYPE.REFUND_UPDATE],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.REFUND_UPDATE],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.REFUND_UPDATE] as 'normal',
    group: 'TRANSACTIONAL',
    description: 'রিফান্ড আপডেট SMS',
  },
  [SMS_TYPE.SUPPORT_ESCALATION]: {
    type: SMS_TYPE.SUPPORT_ESCALATION,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.SUPPORT_ESCALATION],
    icon: SMS_TYPE_ICONS[SMS_TYPE.SUPPORT_ESCALATION],
    color: SMS_TYPE_COLORS[SMS_TYPE.SUPPORT_ESCALATION],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.SUPPORT_ESCALATION],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.SUPPORT_ESCALATION] as 'high',
    group: 'TICKET',
    description: 'সাপোর্ট এস্কেলেশন SMS',
  },
  [SMS_TYPE.FOLLOW_UP]: {
    type: SMS_TYPE.FOLLOW_UP,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.FOLLOW_UP],
    icon: SMS_TYPE_ICONS[SMS_TYPE.FOLLOW_UP],
    color: SMS_TYPE_COLORS[SMS_TYPE.FOLLOW_UP],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.FOLLOW_UP],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.FOLLOW_UP] as 'normal',
    group: 'COMMUNICATION',
    description: 'ফলো-আপ SMS',
  },
  [SMS_TYPE.THANK_YOU]: {
    type: SMS_TYPE.THANK_YOU,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.THANK_YOU],
    icon: SMS_TYPE_ICONS[SMS_TYPE.THANK_YOU],
    color: SMS_TYPE_COLORS[SMS_TYPE.THANK_YOU],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.THANK_YOU],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.THANK_YOU] as 'low',
    group: 'COMMUNICATION',
    description: 'ধন্যবাদ SMS',
  },
  [SMS_TYPE.APOLOGY]: {
    type: SMS_TYPE.APOLOGY,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.APOLOGY],
    icon: SMS_TYPE_ICONS[SMS_TYPE.APOLOGY],
    color: SMS_TYPE_COLORS[SMS_TYPE.APOLOGY],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.APOLOGY],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.APOLOGY] as 'normal',
    group: 'COMMUNICATION',
    description: 'ক্ষমা প্রার্থনা SMS',
  },
  [SMS_TYPE.MAINTENANCE]: {
    type: SMS_TYPE.MAINTENANCE,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.MAINTENANCE],
    icon: SMS_TYPE_ICONS[SMS_TYPE.MAINTENANCE],
    color: SMS_TYPE_COLORS[SMS_TYPE.MAINTENANCE],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.MAINTENANCE],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.MAINTENANCE] as 'normal',
    group: 'SERVICE',
    description: 'মেইনটেন্যান্স সম্পর্কিত SMS',
  },
  [SMS_TYPE.SECURITY_ALERT]: {
    type: SMS_TYPE.SECURITY_ALERT,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.SECURITY_ALERT],
    icon: SMS_TYPE_ICONS[SMS_TYPE.SECURITY_ALERT],
    color: SMS_TYPE_COLORS[SMS_TYPE.SECURITY_ALERT],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.SECURITY_ALERT],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.SECURITY_ALERT] as 'urgent',
    group: 'SECURITY',
    description: 'সিকিউরিটি অ্যালার্ট SMS',
  },
  [SMS_TYPE.SYSTEM_NOTIFICATION]: {
    type: SMS_TYPE.SYSTEM_NOTIFICATION,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.SYSTEM_NOTIFICATION],
    icon: SMS_TYPE_ICONS[SMS_TYPE.SYSTEM_NOTIFICATION],
    color: SMS_TYPE_COLORS[SMS_TYPE.SYSTEM_NOTIFICATION],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.SYSTEM_NOTIFICATION],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.SYSTEM_NOTIFICATION] as 'normal',
    group: 'SYSTEM',
    description: 'সিস্টেম নোটিফিকেশন SMS',
  },
  [SMS_TYPE.TEAM_UPDATE]: {
    type: SMS_TYPE.TEAM_UPDATE,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.TEAM_UPDATE],
    icon: SMS_TYPE_ICONS[SMS_TYPE.TEAM_UPDATE],
    color: SMS_TYPE_COLORS[SMS_TYPE.TEAM_UPDATE],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.TEAM_UPDATE],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.TEAM_UPDATE] as 'normal',
    group: 'TEAM',
    description: 'টিম আপডেট SMS',
  },
  [SMS_TYPE.TRAINING]: {
    type: SMS_TYPE.TRAINING,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.TRAINING],
    icon: SMS_TYPE_ICONS[SMS_TYPE.TRAINING],
    color: SMS_TYPE_COLORS[SMS_TYPE.TRAINING],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.TRAINING],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.TRAINING] as 'low',
    group: 'TEAM',
    description: 'প্রশিক্ষণ সম্পর্কিত SMS',
  },
  [SMS_TYPE.ONBOARDING]: {
    type: SMS_TYPE.ONBOARDING,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.ONBOARDING],
    icon: SMS_TYPE_ICONS[SMS_TYPE.ONBOARDING],
    color: SMS_TYPE_COLORS[SMS_TYPE.ONBOARDING],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.ONBOARDING],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.ONBOARDING] as 'normal',
    group: 'ONBOARDING',
    description: 'অনবোর্ডিং সম্পর্কিত SMS',
  },
  [SMS_TYPE.OFFBOARDING]: {
    type: SMS_TYPE.OFFBOARDING,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.OFFBOARDING],
    icon: SMS_TYPE_ICONS[SMS_TYPE.OFFBOARDING],
    color: SMS_TYPE_COLORS[SMS_TYPE.OFFBOARDING],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.OFFBOARDING],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.OFFBOARDING] as 'normal',
    group: 'ONBOARDING',
    description: 'অফবোর্ডিং সম্পর্কিত SMS',
  },
  [SMS_TYPE.BILLING]: {
    type: SMS_TYPE.BILLING,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.BILLING],
    icon: SMS_TYPE_ICONS[SMS_TYPE.BILLING],
    color: SMS_TYPE_COLORS[SMS_TYPE.BILLING],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.BILLING],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.BILLING] as 'normal',
    group: 'FINANCIAL',
    description: 'বিলিং সম্পর্কিত SMS',
  },
  [SMS_TYPE.RENEWAL]: {
    type: SMS_TYPE.RENEWAL,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.RENEWAL],
    icon: SMS_TYPE_ICONS[SMS_TYPE.RENEWAL],
    color: SMS_TYPE_COLORS[SMS_TYPE.RENEWAL],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.RENEWAL],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.RENEWAL] as 'normal',
    group: 'SUBSCRIPTION',
    description: 'রিনিউয়াল সম্পর্কিত SMS',
  },
  [SMS_TYPE.UPGRADE]: {
    type: SMS_TYPE.UPGRADE,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.UPGRADE],
    icon: SMS_TYPE_ICONS[SMS_TYPE.UPGRADE],
    color: SMS_TYPE_COLORS[SMS_TYPE.UPGRADE],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.UPGRADE],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.UPGRADE] as 'normal',
    group: 'SUBSCRIPTION',
    description: 'আপগ্রেড সম্পর্কিত SMS',
  },
  [SMS_TYPE.DOWNGRADE]: {
    type: SMS_TYPE.DOWNGRADE,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.DOWNGRADE],
    icon: SMS_TYPE_ICONS[SMS_TYPE.DOWNGRADE],
    color: SMS_TYPE_COLORS[SMS_TYPE.DOWNGRADE],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.DOWNGRADE],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.DOWNGRADE] as 'normal',
    group: 'SUBSCRIPTION',
    description: 'ডাউনগ্রেড সম্পর্কিত SMS',
  },
  [SMS_TYPE.CANCELLATION]: {
    type: SMS_TYPE.CANCELLATION,
    displayName: SMS_TYPE_DISPLAY_NAMES[SMS_TYPE.CANCELLATION],
    icon: SMS_TYPE_ICONS[SMS_TYPE.CANCELLATION],
    color: SMS_TYPE_COLORS[SMS_TYPE.CANCELLATION],
    category: SMS_TYPE_CATEGORIES[SMS_TYPE.CANCELLATION],
    defaultPriority: SMS_TYPE_DEFAULT_PRIORITY[SMS_TYPE.CANCELLATION] as 'high',
    group: 'ORDER',
    description: 'বাতিলকরণ সম্পর্কিত SMS',
  },
};

/**
 * SMS টাইপ গ্রুপ কনফিগারেশন
 */
export const SMS_TYPE_GROUP_CONFIGS: Record<
  SmsTypeGroup,
  {
    group: SmsTypeGroup;
    displayName: string;
    icon: string;
    color: string;
    types: readonly SmsType[];
    description?: string;
  }
> = {
  SECURITY: {
    group: 'SECURITY',
    displayName: 'সিকিউরিটি',
    icon: 'shield',
    color: '#3498db',
    types: ['otp', 'verification', 'password_reset', 'security_alert'] as const,
    description: 'সিকিউরিটি সম্পর্কিত SMS',
  },
  COMMUNICATION: {
    group: 'COMMUNICATION',
    displayName: 'যোগাযোগ',
    icon: 'message-circle',
    color: '#1abc9c',
    types: ['notification', 'follow_up', 'thank_you', 'apology'] as const,
    description: 'যোগাযোগ সম্পর্কিত SMS',
  },
  TICKET: {
    group: 'TICKET',
    displayName: 'টিকেট',
    icon: 'ticket',
    color: '#e67e22',
    types: ['ticket_update', 'support_escalation'] as const,
    description: 'টিকেট সম্পর্কিত SMS',
  },
  REMINDER: {
    group: 'REMINDER',
    displayName: 'রিমাইন্ডার',
    icon: 'clock',
    color: '#f39c12',
    types: ['reminder', 'appointment_reminder'] as const,
    description: 'রিমাইন্ডার SMS',
  },
  SURVEY: {
    group: 'SURVEY',
    displayName: 'জরিপ',
    icon: 'clipboard',
    color: '#9b59b6',
    types: ['survey', 'customer_feedback'] as const,
    description: 'জরিপ সম্পর্কিত SMS',
  },
  MARKETING: {
    group: 'MARKETING',
    displayName: 'মার্কেটিং',
    icon: 'megaphone',
    color: '#2ecc71',
    types: ['marketing', 'promotional'] as const,
    description: 'মার্কেটিং সম্পর্কিত SMS',
  },
  TRANSACTIONAL: {
    group: 'TRANSACTIONAL',
    displayName: 'ট্রানজেকশনাল',
    icon: 'credit-card',
    color: '#27ae60',
    types: ['transactional', 'payment_confirmation', 'refund_update'] as const,
    description: 'ট্রানজেকশন সম্পর্কিত SMS',
  },
  ORDER: {
    group: 'ORDER',
    displayName: 'অর্ডার',
    icon: 'shopping-bag',
    color: '#3498db',
    types: ['order_confirmation', 'delivery_update', 'cancellation'] as const,
    description: 'অর্ডার সম্পর্কিত SMS',
  },
  SERVICE: {
    group: 'SERVICE',
    displayName: 'সার্ভিস',
    icon: 'refresh-cw',
    color: '#2980b9',
    types: ['service_update', 'maintenance'] as const,
    description: 'সার্ভিস সম্পর্কিত SMS',
  },
  EMERGENCY: {
    group: 'EMERGENCY',
    displayName: 'জরুরি',
    icon: 'alert-triangle',
    color: '#e74c3c',
    types: ['emergency', 'alert'] as const,
    description: 'জরুরি SMS',
  },
  FINANCIAL: {
    group: 'FINANCIAL',
    displayName: 'আর্থিক',
    icon: 'file-text',
    color: '#27ae60',
    types: ['billing'] as const,
    description: 'আর্থিক সম্পর্কিত SMS',
  },
  SUBSCRIPTION: {
    group: 'SUBSCRIPTION',
    displayName: 'সাবস্ক্রিপশন',
    icon: 'repeat',
    color: '#8e44ad',
    types: ['renewal', 'upgrade', 'downgrade'] as const,
    description: 'সাবস্ক্রিপশন সম্পর্কিত SMS',
  },
  ONBOARDING: {
    group: 'ONBOARDING',
    displayName: 'অনবোর্ডিং',
    icon: 'user-plus',
    color: '#2ecc71',
    types: ['welcome', 'onboarding', 'offboarding'] as const,
    description: 'অনবোর্ডিং সম্পর্কিত SMS',
  },
  TEAM: {
    group: 'TEAM',
    displayName: 'টিম',
    icon: 'users',
    color: '#1abc9c',
    types: ['team_update', 'training'] as const,
    description: 'টিম সম্পর্কিত SMS',
  },
  SYSTEM: {
    group: 'SYSTEM',
    displayName: 'সিস্টেম',
    icon: 'cpu',
    color: '#2c3e50',
    types: ['system_notification'] as const,
    description: 'সিস্টেম সম্পর্কিত SMS',
  },
};

/**
 * SMS টাইপ স্ট্যাটাস
 */
export const SMS_TYPE_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  DEPRECATED: 'deprecated',
} as const;

export type SmsTypeStatus = (typeof SMS_TYPE_STATUS)[keyof typeof SMS_TYPE_STATUS];
