import {
  TICKET_STATUS,
  TICKET_PRIORITY,
  TICKET_PRIORITY_WEIGHT,
  TICKET_TYPE,
  TICKET_CHANNEL,
  TICKET_CATEGORY,
  TICKET,
} from './ticket.constants';
import { CONVERSATION_STATUS, CONVERSATION_TYPE, CONVERSATION } from './conversation.constants';
import {
  MESSAGE_TYPE,
  MESSAGE_STATUS,
  MESSAGE_SENDER_TYPE,
  MESSAGE,
  SUPPORT_MESSAGE_TEMPLATE,
} from './message.constants';
import { FAQ_STATUS, FAQ_CATEGORY, FAQ } from './faq.constants';
import {
  KNOWLEDGE_BASE_STATUS,
  KNOWLEDGE_BASE_TYPE,
  KNOWLEDGE_BASE_VISIBILITY,
  KNOWLEDGE_BASE,
} from './knowledge-base.constants';
import { FEEDBACK_TYPE, FEEDBACK_STATUS, FEEDBACK_RATING, FEEDBACK } from './feedback.constants';
import {
  COMPLAINT_TYPE,
  COMPLAINT_STATUS,
  COMPLAINT_SEVERITY,
  COMPLAINT,
} from './complaint.constants';
import { SURVEY_TYPE, SURVEY_STATUS, SURVEY_QUESTION_TYPE, SURVEY } from './survey.constants';
import {
  LIVE_CHAT_STATUS,
  LIVE_CHAT_SESSION_STATUS,
  LIVE_CHAT_TRIGGER,
  LIVE_CHAT,
} from './live-chat.constants';
import { CHATBOT_TYPE, CHATBOT_STATUS, CHATBOT_INTENT, CHATBOT } from './chatbot.constants';
import {
  SUPPORT_ANALYTICS_METRIC,
  SUPPORT_ANALYTICS_PERIOD,
  SUPPORT_ANALYTICS,
} from './support-analytics.constants';
import {
  SUPPORT_SLA_STATUS,
  SUPPORT_SLA_METRIC,
  SUPPORT_SLA_TARGET,
  SUPPORT_SLA,
} from './support-sla.constants';
import {
  SUPPORT_AGENT_STATUS,
  SUPPORT_AGENT_LEVEL,
  SUPPORT_AGENT_SKILL,
  SUPPORT_AGENT,
} from './support-agent.constants';
import {
  SUPPORT_TEAM_TYPE,
  SUPPORT_TEAM_STATUS,
  SUPPORT_TEAM_ROUTING,
  SUPPORT_TEAM,
} from './support-team.constants';
import {
  SUPPORT_RULE_TYPE,
  SUPPORT_RULE_CONDITION,
  SUPPORT_RULE_ACTION,
  SUPPORT_RULE_STATUS,
  SUPPORT_RULE,
} from './support-rule.constants';
import {
  SUPPORT_AUTOMATION_TYPE,
  SUPPORT_AUTOMATION_TRIGGER,
  SUPPORT_AUTOMATION_STATUS,
  SUPPORT_AUTOMATION,
} from './support-automation.constants';
import { SUPPORT_PERMISSION } from './support-permission.constants';

export const SUPPORT_LIMIT = {
  MAX_TICKETS_PER_USER: 20,
  MAX_OPEN_TICKETS: 10000,
  MAX_AGENTS: 500,
  MAX_TEAMS: 100,
  MAX_FAQ: 5000,
  MAX_KB_ARTICLES: 10000,
  MAX_AUTOMATIONS: 200,
  MAX_RULES: 500,
  MAX_ATTACHMENT_SIZE_MB: 25,
  RETENTION_DAYS: 730,
} as const;

export const SUPPORT = {
  LIMIT: SUPPORT_LIMIT,

  TICKET: {
    STATUS: TICKET_STATUS,
    PRIORITY: TICKET_PRIORITY,
    PRIORITY_WEIGHT: TICKET_PRIORITY_WEIGHT,
    TYPE: TICKET_TYPE,
    CHANNEL: TICKET_CHANNEL,
    CATEGORY: TICKET_CATEGORY,
    LIMIT: TICKET,
  },

  CONVERSATION: {
    STATUS: CONVERSATION_STATUS,
    TYPE: CONVERSATION_TYPE,
    LIMIT: CONVERSATION,
  },

  MESSAGE: {
    TYPE: MESSAGE_TYPE,
    STATUS: MESSAGE_STATUS,
    SENDER_TYPE: MESSAGE_SENDER_TYPE,
    TEMPLATE: SUPPORT_MESSAGE_TEMPLATE,
    LIMIT: MESSAGE,
  },

  FAQ: {
    STATUS: FAQ_STATUS,
    CATEGORY: FAQ_CATEGORY,
    LIMIT: FAQ,
  },

  KNOWLEDGE_BASE: {
    STATUS: KNOWLEDGE_BASE_STATUS,
    TYPE: KNOWLEDGE_BASE_TYPE,
    VISIBILITY: KNOWLEDGE_BASE_VISIBILITY,
    LIMIT: KNOWLEDGE_BASE,
  },

  FEEDBACK: {
    TYPE: FEEDBACK_TYPE,
    STATUS: FEEDBACK_STATUS,
    RATING: FEEDBACK_RATING,
    LIMIT: FEEDBACK,
  },

  COMPLAINT: {
    TYPE: COMPLAINT_TYPE,
    STATUS: COMPLAINT_STATUS,
    SEVERITY: COMPLAINT_SEVERITY,
    LIMIT: COMPLAINT,
  },

  SURVEY: {
    TYPE: SURVEY_TYPE,
    STATUS: SURVEY_STATUS,
    QUESTION_TYPE: SURVEY_QUESTION_TYPE,
    LIMIT: SURVEY,
  },

  LIVE_CHAT: {
    STATUS: LIVE_CHAT_STATUS,
    SESSION_STATUS: LIVE_CHAT_SESSION_STATUS,
    TRIGGER: LIVE_CHAT_TRIGGER,
    LIMIT: LIVE_CHAT,
  },

  CHATBOT: {
    TYPE: CHATBOT_TYPE,
    STATUS: CHATBOT_STATUS,
    INTENT: CHATBOT_INTENT,
    LIMIT: CHATBOT,
  },

  SLA: {
    STATUS: SUPPORT_SLA_STATUS,
    METRIC: SUPPORT_SLA_METRIC,
    TARGET: SUPPORT_SLA_TARGET,
    LIMIT: SUPPORT_SLA,
  },

  AGENT: {
    STATUS: SUPPORT_AGENT_STATUS,
    LEVEL: SUPPORT_AGENT_LEVEL,
    SKILL: SUPPORT_AGENT_SKILL,
    LIMIT: SUPPORT_AGENT,
  },

  TEAM: {
    TYPE: SUPPORT_TEAM_TYPE,
    STATUS: SUPPORT_TEAM_STATUS,
    ROUTING: SUPPORT_TEAM_ROUTING,
    LIMIT: SUPPORT_TEAM,
  },

  RULE: {
    TYPE: SUPPORT_RULE_TYPE,
    CONDITION: SUPPORT_RULE_CONDITION,
    ACTION: SUPPORT_RULE_ACTION,
    STATUS: SUPPORT_RULE_STATUS,
    LIMIT: SUPPORT_RULE,
  },

  AUTOMATION: {
    TYPE: SUPPORT_AUTOMATION_TYPE,
    TRIGGER: SUPPORT_AUTOMATION_TRIGGER,
    STATUS: SUPPORT_AUTOMATION_STATUS,
    LIMIT: SUPPORT_AUTOMATION,
  },

  ANALYTICS: {
    METRIC: SUPPORT_ANALYTICS_METRIC,
    PERIOD: SUPPORT_ANALYTICS_PERIOD,
    LIMIT: SUPPORT_ANALYTICS,
  },

  PERMISSION: SUPPORT_PERMISSION,
} as const;

export type SupportType = typeof SUPPORT;
