/**
 * সাপোর্ট পুশ নোটিফিকেশনের বিভিন্ন টাইপ সংক্রান্ত কনস্ট্যান্টসমূহ
 */

/**
 * পুশ টাইপ
 */
export const PUSH_TYPE = {
  TICKET_UPDATE: 'ticket_update',
  ASSIGNMENT: 'assignment',
  RESOLUTION: 'resolution',
  ESCALATION: 'escalation',
  NEW_MESSAGE: 'new_message',
  SURVEY_REQUEST: 'survey_request',
  FEEDBACK_REQUEST: 'feedback_request',
  ALERT: 'alert',
  REMINDER: 'reminder',
  STATUS_CHANGE: 'status_change',
  SLA_BREACH: 'sla_breach',
  SYSTEM_NOTIFICATION: 'system_notification',
  PROMOTIONAL: 'promotional',
  TRANSACTIONAL: 'transactional',
  WELCOME: 'welcome',
  MAINTENANCE: 'maintenance',
  SECURITY_ALERT: 'security_alert',
  TEAM_UPDATE: 'team_update',
  TRAINING: 'training',
  ONBOARDING: 'onboarding',
  OFFBOARDING: 'offboarding',
  BILLING: 'billing',
  PAYMENT_CONFIRMATION: 'payment_confirmation',
  REFUND_UPDATE: 'refund_update',
  CANCELLATION: 'cancellation',
  RENEWAL: 'renewal',
  UPGRADE: 'upgrade',
  DOWNGRADE: 'downgrade',
  ORDER_CONFIRMATION: 'order_confirmation',
  DELIVERY_UPDATE: 'delivery_update',
  APPOINTMENT_REMINDER: 'appointment_reminder',
  CUSTOMER_FEEDBACK: 'customer_feedback',
  SUPPORT_ESCALATION: 'support_escalation',
  FOLLOW_UP: 'follow_up',
  THANK_YOU: 'thank_you',
  APOLOGY: 'apology',
} as const;

/**
 * পুশ টাইপের ডিসপ্লে নাম
 */
export const PUSH_TYPE_DISPLAY_NAMES = {
  [PUSH_TYPE.TICKET_UPDATE]: 'টিকেট আপডেট',
  [PUSH_TYPE.ASSIGNMENT]: 'অ্যাসাইনমেন্ট',
  [PUSH_TYPE.RESOLUTION]: 'সমাধান',
  [PUSH_TYPE.ESCALATION]: 'এস্কেলেশন',
  [PUSH_TYPE.NEW_MESSAGE]: 'নতুন মেসেজ',
  [PUSH_TYPE.SURVEY_REQUEST]: 'জরিপ অনুরোধ',
  [PUSH_TYPE.FEEDBACK_REQUEST]: 'ফিডব্যাক অনুরোধ',
  [PUSH_TYPE.ALERT]: 'অ্যালার্ট',
  [PUSH_TYPE.REMINDER]: 'রিমাইন্ডার',
  [PUSH_TYPE.STATUS_CHANGE]: 'স্ট্যাটাস পরিবর্তন',
  [PUSH_TYPE.SLA_BREACH]: 'এসএলএ লঙ্ঘন',
  [PUSH_TYPE.SYSTEM_NOTIFICATION]: 'সিস্টেম নোটিফিকেশন',
  [PUSH_TYPE.PROMOTIONAL]: 'প্রমোশনাল',
  [PUSH_TYPE.TRANSACTIONAL]: 'ট্রানজেকশনাল',
  [PUSH_TYPE.WELCOME]: 'স্বাগতম',
  [PUSH_TYPE.MAINTENANCE]: 'মেইনটেন্যান্স',
  [PUSH_TYPE.SECURITY_ALERT]: 'সিকিউরিটি অ্যালার্ট',
  [PUSH_TYPE.TEAM_UPDATE]: 'টিম আপডেট',
  [PUSH_TYPE.TRAINING]: 'প্রশিক্ষণ',
  [PUSH_TYPE.ONBOARDING]: 'অনবোর্ডিং',
  [PUSH_TYPE.OFFBOARDING]: 'অফবোর্ডিং',
  [PUSH_TYPE.BILLING]: 'বিলিং',
  [PUSH_TYPE.PAYMENT_CONFIRMATION]: 'পেমেন্ট নিশ্চিতকরণ',
  [PUSH_TYPE.REFUND_UPDATE]: 'রিফান্ড আপডেট',
  [PUSH_TYPE.CANCELLATION]: 'বাতিলকরণ',
  [PUSH_TYPE.RENEWAL]: 'রিনিউয়াল',
  [PUSH_TYPE.UPGRADE]: 'আপগ্রেড',
  [PUSH_TYPE.DOWNGRADE]: 'ডাউনগ্রেড',
  [PUSH_TYPE.ORDER_CONFIRMATION]: 'অর্ডার নিশ্চিতকরণ',
  [PUSH_TYPE.DELIVERY_UPDATE]: 'ডেলিভারি আপডেট',
  [PUSH_TYPE.APPOINTMENT_REMINDER]: 'অ্যাপয়েন্টমেন্ট রিমাইন্ডার',
  [PUSH_TYPE.CUSTOMER_FEEDBACK]: 'গ্রাহক ফিডব্যাক',
  [PUSH_TYPE.SUPPORT_ESCALATION]: 'সাপোর্ট এস্কেলেশন',
  [PUSH_TYPE.FOLLOW_UP]: 'ফলো-আপ',
  [PUSH_TYPE.THANK_YOU]: 'ধন্যবাদ',
  [PUSH_TYPE.APOLOGY]: 'ক্ষমা প্রার্থনা',
} as const;

/**
 * পুশ টাইপের আইকন (অনুষঙ্গিক নাম)
 */
export const PUSH_TYPE_ICONS = {
  [PUSH_TYPE.TICKET_UPDATE]: 'ticket',
  [PUSH_TYPE.ASSIGNMENT]: 'user-check',
  [PUSH_TYPE.RESOLUTION]: 'check-circle',
  [PUSH_TYPE.ESCALATION]: 'arrow-up-circle',
  [PUSH_TYPE.NEW_MESSAGE]: 'message-circle',
  [PUSH_TYPE.SURVEY_REQUEST]: 'clipboard',
  [PUSH_TYPE.FEEDBACK_REQUEST]: 'message-square',
  [PUSH_TYPE.ALERT]: 'alert-circle',
  [PUSH_TYPE.REMINDER]: 'clock',
  [PUSH_TYPE.STATUS_CHANGE]: 'circle',
  [PUSH_TYPE.SLA_BREACH]: 'clock',
  [PUSH_TYPE.SYSTEM_NOTIFICATION]: 'cpu',
  [PUSH_TYPE.PROMOTIONAL]: 'megaphone',
  [PUSH_TYPE.TRANSACTIONAL]: 'credit-card',
  [PUSH_TYPE.WELCOME]: 'smile',
  [PUSH_TYPE.MAINTENANCE]: 'wrench',
  [PUSH_TYPE.SECURITY_ALERT]: 'shield',
  [PUSH_TYPE.TEAM_UPDATE]: 'users',
  [PUSH_TYPE.TRAINING]: 'book',
  [PUSH_TYPE.ONBOARDING]: 'user-plus',
  [PUSH_TYPE.OFFBOARDING]: 'user-minus',
  [PUSH_TYPE.BILLING]: 'file-text',
  [PUSH_TYPE.PAYMENT_CONFIRMATION]: 'check-circle',
  [PUSH_TYPE.REFUND_UPDATE]: 'rotate-ccw',
  [PUSH_TYPE.CANCELLATION]: 'x-circle',
  [PUSH_TYPE.RENEWAL]: 'refresh-cw',
  [PUSH_TYPE.UPGRADE]: 'arrow-up',
  [PUSH_TYPE.DOWNGRADE]: 'arrow-down',
  [PUSH_TYPE.ORDER_CONFIRMATION]: 'shopping-bag',
  [PUSH_TYPE.DELIVERY_UPDATE]: 'truck',
  [PUSH_TYPE.APPOINTMENT_REMINDER]: 'calendar',
  [PUSH_TYPE.CUSTOMER_FEEDBACK]: 'message-square',
  [PUSH_TYPE.SUPPORT_ESCALATION]: 'arrow-up-circle',
  [PUSH_TYPE.FOLLOW_UP]: 'refresh-cw',
  [PUSH_TYPE.THANK_YOU]: 'thumbs-up',
  [PUSH_TYPE.APOLOGY]: 'frown',
} as const;

/**
 * পুশ টাইপের রঙের কোড (হেক্স)
 */
export const PUSH_TYPE_COLORS = {
  [PUSH_TYPE.TICKET_UPDATE]: '#e67e22',
  [PUSH_TYPE.ASSIGNMENT]: '#1abc9c',
  [PUSH_TYPE.RESOLUTION]: '#2ecc71',
  [PUSH_TYPE.ESCALATION]: '#e74c3c',
  [PUSH_TYPE.NEW_MESSAGE]: '#3498db',
  [PUSH_TYPE.SURVEY_REQUEST]: '#9b59b6',
  [PUSH_TYPE.FEEDBACK_REQUEST]: '#8e44ad',
  [PUSH_TYPE.ALERT]: '#e74c3c',
  [PUSH_TYPE.REMINDER]: '#f39c12',
  [PUSH_TYPE.STATUS_CHANGE]: '#95a5a6',
  [PUSH_TYPE.SLA_BREACH]: '#c0392b',
  [PUSH_TYPE.SYSTEM_NOTIFICATION]: '#2c3e50',
  [PUSH_TYPE.PROMOTIONAL]: '#2ecc71',
  [PUSH_TYPE.TRANSACTIONAL]: '#27ae60',
  [PUSH_TYPE.WELCOME]: '#2ecc71',
  [PUSH_TYPE.MAINTENANCE]: '#e67e22',
  [PUSH_TYPE.SECURITY_ALERT]: '#c0392b',
  [PUSH_TYPE.TEAM_UPDATE]: '#1abc9c',
  [PUSH_TYPE.TRAINING]: '#3498db',
  [PUSH_TYPE.ONBOARDING]: '#2ecc71',
  [PUSH_TYPE.OFFBOARDING]: '#e74c3c',
  [PUSH_TYPE.BILLING]: '#27ae60',
  [PUSH_TYPE.PAYMENT_CONFIRMATION]: '#2ecc71',
  [PUSH_TYPE.REFUND_UPDATE]: '#e67e22',
  [PUSH_TYPE.CANCELLATION]: '#e74c3c',
  [PUSH_TYPE.RENEWAL]: '#3498db',
  [PUSH_TYPE.UPGRADE]: '#2ecc71',
  [PUSH_TYPE.DOWNGRADE]: '#e74c3c',
  [PUSH_TYPE.ORDER_CONFIRMATION]: '#3498db',
  [PUSH_TYPE.DELIVERY_UPDATE]: '#f39c12',
  [PUSH_TYPE.APPOINTMENT_REMINDER]: '#2980b9',
  [PUSH_TYPE.CUSTOMER_FEEDBACK]: '#8e44ad',
  [PUSH_TYPE.SUPPORT_ESCALATION]: '#e74c3c',
  [PUSH_TYPE.FOLLOW_UP]: '#3498db',
  [PUSH_TYPE.THANK_YOU]: '#2ecc71',
  [PUSH_TYPE.APOLOGY]: '#e67e22',
} as const;

/**
 * পুশ টাইপের ডিফল্ট প্রায়োরিটি
 */
export const PUSH_TYPE_DEFAULT_PRIORITY = {
  [PUSH_TYPE.TICKET_UPDATE]: 'normal',
  [PUSH_TYPE.ASSIGNMENT]: 'high',
  [PUSH_TYPE.RESOLUTION]: 'normal',
  [PUSH_TYPE.ESCALATION]: 'high',
  [PUSH_TYPE.NEW_MESSAGE]: 'normal',
  [PUSH_TYPE.SURVEY_REQUEST]: 'low',
  [PUSH_TYPE.FEEDBACK_REQUEST]: 'low',
  [PUSH_TYPE.ALERT]: 'high',
  [PUSH_TYPE.REMINDER]: 'normal',
  [PUSH_TYPE.STATUS_CHANGE]: 'normal',
  [PUSH_TYPE.SLA_BREACH]: 'critical',
  [PUSH_TYPE.SYSTEM_NOTIFICATION]: 'normal',
  [PUSH_TYPE.PROMOTIONAL]: 'low',
  [PUSH_TYPE.TRANSACTIONAL]: 'normal',
  [PUSH_TYPE.WELCOME]: 'normal',
  [PUSH_TYPE.MAINTENANCE]: 'normal',
  [PUSH_TYPE.SECURITY_ALERT]: 'critical',
  [PUSH_TYPE.TEAM_UPDATE]: 'normal',
  [PUSH_TYPE.TRAINING]: 'low',
  [PUSH_TYPE.ONBOARDING]: 'normal',
  [PUSH_TYPE.OFFBOARDING]: 'normal',
  [PUSH_TYPE.BILLING]: 'normal',
  [PUSH_TYPE.PAYMENT_CONFIRMATION]: 'high',
  [PUSH_TYPE.REFUND_UPDATE]: 'normal',
  [PUSH_TYPE.CANCELLATION]: 'high',
  [PUSH_TYPE.RENEWAL]: 'normal',
  [PUSH_TYPE.UPGRADE]: 'normal',
  [PUSH_TYPE.DOWNGRADE]: 'normal',
  [PUSH_TYPE.ORDER_CONFIRMATION]: 'high',
  [PUSH_TYPE.DELIVERY_UPDATE]: 'normal',
  [PUSH_TYPE.APPOINTMENT_REMINDER]: 'normal',
  [PUSH_TYPE.CUSTOMER_FEEDBACK]: 'low',
  [PUSH_TYPE.SUPPORT_ESCALATION]: 'high',
  [PUSH_TYPE.FOLLOW_UP]: 'normal',
  [PUSH_TYPE.THANK_YOU]: 'low',
  [PUSH_TYPE.APOLOGY]: 'normal',
} as const;

/**
 * পুশ টাইপ গ্রুপ
 */
export const PUSH_TYPE_GROUPS = {
  TICKET: ['ticket_update', 'assignment', 'resolution', 'escalation', 'support_escalation'],
  COMMUNICATION: ['new_message', 'follow_up', 'thank_you', 'apology'],
  REMINDER: ['reminder', 'appointment_reminder'],
  SURVEY: ['survey_request', 'feedback_request', 'customer_feedback'],
  ALERT: ['alert', 'security_alert', 'sla_breach'],
  STATUS: ['status_change'],
  SYSTEM: ['system_notification', 'maintenance'],
  MARKETING: ['promotional'],
  TRANSACTIONAL: ['transactional', 'billing', 'payment_confirmation', 'refund_update'],
  ONBOARDING: ['welcome', 'onboarding', 'offboarding'],
  TEAM: ['team_update', 'training'],
  ORDER: ['order_confirmation', 'delivery_update', 'cancellation'],
  SUBSCRIPTION: ['renewal', 'upgrade', 'downgrade'],
} as const;

export type PushType = (typeof PUSH_TYPE)[keyof typeof PUSH_TYPE];
export type PushTypeDisplayNames = typeof PUSH_TYPE_DISPLAY_NAMES;
export type PushTypeIcons = typeof PUSH_TYPE_ICONS;
export type PushTypeColors = typeof PUSH_TYPE_COLORS;
export type PushTypeDefaultPriority = typeof PUSH_TYPE_DEFAULT_PRIORITY;
export type PushTypeGroups = typeof PUSH_TYPE_GROUPS;

export type PushTypeGroup = keyof typeof PUSH_TYPE_GROUPS;

export interface PushTypeConfig {
  type: PushType;
  displayName: string;
  icon: string;
  color: string;
  defaultPriority: 'low' | 'normal' | 'high' | 'critical';
  group: PushTypeGroup;
  description?: string;
}

/**
 * পুশ টাইপ কনফিগারেশন অবজেক্ট
 */
export const PUSH_TYPE_CONFIGS: Record<PushType, PushTypeConfig> = {
  [PUSH_TYPE.TICKET_UPDATE]: {
    type: PUSH_TYPE.TICKET_UPDATE,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.TICKET_UPDATE],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.TICKET_UPDATE],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.TICKET_UPDATE],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.TICKET_UPDATE] as 'normal',
    group: 'TICKET',
    description: 'টিকেট আপডেট সম্পর্কিত পুশ',
  },
  [PUSH_TYPE.ASSIGNMENT]: {
    type: PUSH_TYPE.ASSIGNMENT,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.ASSIGNMENT],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.ASSIGNMENT],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.ASSIGNMENT],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.ASSIGNMENT] as 'high',
    group: 'TICKET',
    description: 'টিকেট অ্যাসাইনমেন্ট সম্পর্কিত পুশ',
  },
  [PUSH_TYPE.RESOLUTION]: {
    type: PUSH_TYPE.RESOLUTION,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.RESOLUTION],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.RESOLUTION],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.RESOLUTION],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.RESOLUTION] as 'normal',
    group: 'TICKET',
    description: 'টিকেট সমাধান সম্পর্কিত পুশ',
  },
  [PUSH_TYPE.ESCALATION]: {
    type: PUSH_TYPE.ESCALATION,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.ESCALATION],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.ESCALATION],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.ESCALATION],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.ESCALATION] as 'high',
    group: 'TICKET',
    description: 'টিকেট এস্কেলেশন সম্পর্কিত পুশ',
  },
  [PUSH_TYPE.NEW_MESSAGE]: {
    type: PUSH_TYPE.NEW_MESSAGE,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.NEW_MESSAGE],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.NEW_MESSAGE],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.NEW_MESSAGE],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.NEW_MESSAGE] as 'normal',
    group: 'COMMUNICATION',
    description: 'নতুন মেসেজ সম্পর্কিত পুশ',
  },
  [PUSH_TYPE.SURVEY_REQUEST]: {
    type: PUSH_TYPE.SURVEY_REQUEST,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.SURVEY_REQUEST],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.SURVEY_REQUEST],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.SURVEY_REQUEST],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.SURVEY_REQUEST] as 'low',
    group: 'SURVEY',
    description: 'জরিপ অনুরোধ পুশ',
  },
  [PUSH_TYPE.FEEDBACK_REQUEST]: {
    type: PUSH_TYPE.FEEDBACK_REQUEST,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.FEEDBACK_REQUEST],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.FEEDBACK_REQUEST],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.FEEDBACK_REQUEST],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.FEEDBACK_REQUEST] as 'low',
    group: 'SURVEY',
    description: 'ফিডব্যাক অনুরোধ পুশ',
  },
  [PUSH_TYPE.ALERT]: {
    type: PUSH_TYPE.ALERT,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.ALERT],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.ALERT],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.ALERT],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.ALERT] as 'high',
    group: 'ALERT',
    description: 'অ্যালার্ট পুশ',
  },
  [PUSH_TYPE.REMINDER]: {
    type: PUSH_TYPE.REMINDER,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.REMINDER],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.REMINDER],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.REMINDER],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.REMINDER] as 'normal',
    group: 'REMINDER',
    description: 'রিমাইন্ডার পুশ',
  },
  [PUSH_TYPE.STATUS_CHANGE]: {
    type: PUSH_TYPE.STATUS_CHANGE,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.STATUS_CHANGE],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.STATUS_CHANGE],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.STATUS_CHANGE],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.STATUS_CHANGE] as 'normal',
    group: 'STATUS',
    description: 'স্ট্যাটাস পরিবর্তন পুশ',
  },
  [PUSH_TYPE.SLA_BREACH]: {
    type: PUSH_TYPE.SLA_BREACH,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.SLA_BREACH],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.SLA_BREACH],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.SLA_BREACH],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.SLA_BREACH] as 'critical',
    group: 'ALERT',
    description: 'এসএলএ লঙ্ঘন পুশ',
  },
  [PUSH_TYPE.SYSTEM_NOTIFICATION]: {
    type: PUSH_TYPE.SYSTEM_NOTIFICATION,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.SYSTEM_NOTIFICATION],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.SYSTEM_NOTIFICATION],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.SYSTEM_NOTIFICATION],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.SYSTEM_NOTIFICATION] as 'normal',
    group: 'SYSTEM',
    description: 'সিস্টেম নোটিফিকেশন পুশ',
  },
  [PUSH_TYPE.PROMOTIONAL]: {
    type: PUSH_TYPE.PROMOTIONAL,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.PROMOTIONAL],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.PROMOTIONAL],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.PROMOTIONAL],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.PROMOTIONAL] as 'low',
    group: 'MARKETING',
    description: 'প্রমোশনাল পুশ',
  },
  [PUSH_TYPE.TRANSACTIONAL]: {
    type: PUSH_TYPE.TRANSACTIONAL,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.TRANSACTIONAL],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.TRANSACTIONAL],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.TRANSACTIONAL],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.TRANSACTIONAL] as 'normal',
    group: 'TRANSACTIONAL',
    description: 'ট্রানজেকশনাল পুশ',
  },
  [PUSH_TYPE.WELCOME]: {
    type: PUSH_TYPE.WELCOME,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.WELCOME],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.WELCOME],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.WELCOME],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.WELCOME] as 'normal',
    group: 'ONBOARDING',
    description: 'স্বাগতম পুশ',
  },
  [PUSH_TYPE.MAINTENANCE]: {
    type: PUSH_TYPE.MAINTENANCE,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.MAINTENANCE],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.MAINTENANCE],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.MAINTENANCE],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.MAINTENANCE] as 'normal',
    group: 'SYSTEM',
    description: 'মেইনটেন্যান্স পুশ',
  },
  [PUSH_TYPE.SECURITY_ALERT]: {
    type: PUSH_TYPE.SECURITY_ALERT,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.SECURITY_ALERT],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.SECURITY_ALERT],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.SECURITY_ALERT],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.SECURITY_ALERT] as 'critical',
    group: 'ALERT',
    description: 'সিকিউরিটি অ্যালার্ট পুশ',
  },
  [PUSH_TYPE.TEAM_UPDATE]: {
    type: PUSH_TYPE.TEAM_UPDATE,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.TEAM_UPDATE],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.TEAM_UPDATE],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.TEAM_UPDATE],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.TEAM_UPDATE] as 'normal',
    group: 'TEAM',
    description: 'টিম আপডেট পুশ',
  },
  [PUSH_TYPE.TRAINING]: {
    type: PUSH_TYPE.TRAINING,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.TRAINING],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.TRAINING],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.TRAINING],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.TRAINING] as 'low',
    group: 'TEAM',
    description: 'প্রশিক্ষণ সম্পর্কিত পুশ',
  },
  [PUSH_TYPE.ONBOARDING]: {
    type: PUSH_TYPE.ONBOARDING,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.ONBOARDING],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.ONBOARDING],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.ONBOARDING],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.ONBOARDING] as 'normal',
    group: 'ONBOARDING',
    description: 'অনবোর্ডিং পুশ',
  },
  [PUSH_TYPE.OFFBOARDING]: {
    type: PUSH_TYPE.OFFBOARDING,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.OFFBOARDING],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.OFFBOARDING],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.OFFBOARDING],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.OFFBOARDING] as 'normal',
    group: 'ONBOARDING',
    description: 'অফবোর্ডিং পুশ',
  },
  [PUSH_TYPE.BILLING]: {
    type: PUSH_TYPE.BILLING,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.BILLING],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.BILLING],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.BILLING],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.BILLING] as 'normal',
    group: 'TRANSACTIONAL',
    description: 'বিলিং সম্পর্কিত পুশ',
  },
  [PUSH_TYPE.PAYMENT_CONFIRMATION]: {
    type: PUSH_TYPE.PAYMENT_CONFIRMATION,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.PAYMENT_CONFIRMATION],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.PAYMENT_CONFIRMATION],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.PAYMENT_CONFIRMATION],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.PAYMENT_CONFIRMATION] as 'high',
    group: 'TRANSACTIONAL',
    description: 'পেমেন্ট নিশ্চিতকরণ পুশ',
  },
  [PUSH_TYPE.REFUND_UPDATE]: {
    type: PUSH_TYPE.REFUND_UPDATE,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.REFUND_UPDATE],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.REFUND_UPDATE],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.REFUND_UPDATE],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.REFUND_UPDATE] as 'normal',
    group: 'TRANSACTIONAL',
    description: 'রিফান্ড আপডেট পুশ',
  },
  [PUSH_TYPE.CANCELLATION]: {
    type: PUSH_TYPE.CANCELLATION,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.CANCELLATION],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.CANCELLATION],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.CANCELLATION],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.CANCELLATION] as 'high',
    group: 'ORDER',
    description: 'বাতিলকরণ পুশ',
  },
  [PUSH_TYPE.RENEWAL]: {
    type: PUSH_TYPE.RENEWAL,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.RENEWAL],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.RENEWAL],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.RENEWAL],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.RENEWAL] as 'normal',
    group: 'SUBSCRIPTION',
    description: 'রিনিউয়াল পুশ',
  },
  [PUSH_TYPE.UPGRADE]: {
    type: PUSH_TYPE.UPGRADE,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.UPGRADE],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.UPGRADE],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.UPGRADE],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.UPGRADE] as 'normal',
    group: 'SUBSCRIPTION',
    description: 'আপগ্রেড পুশ',
  },
  [PUSH_TYPE.DOWNGRADE]: {
    type: PUSH_TYPE.DOWNGRADE,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.DOWNGRADE],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.DOWNGRADE],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.DOWNGRADE],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.DOWNGRADE] as 'normal',
    group: 'SUBSCRIPTION',
    description: 'ডাউনগ্রেড পুশ',
  },
  [PUSH_TYPE.ORDER_CONFIRMATION]: {
    type: PUSH_TYPE.ORDER_CONFIRMATION,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.ORDER_CONFIRMATION],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.ORDER_CONFIRMATION],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.ORDER_CONFIRMATION],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.ORDER_CONFIRMATION] as 'high',
    group: 'ORDER',
    description: 'অর্ডার নিশ্চিতকরণ পুশ',
  },
  [PUSH_TYPE.DELIVERY_UPDATE]: {
    type: PUSH_TYPE.DELIVERY_UPDATE,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.DELIVERY_UPDATE],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.DELIVERY_UPDATE],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.DELIVERY_UPDATE],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.DELIVERY_UPDATE] as 'normal',
    group: 'ORDER',
    description: 'ডেলিভারি আপডেট পুশ',
  },
  [PUSH_TYPE.APPOINTMENT_REMINDER]: {
    type: PUSH_TYPE.APPOINTMENT_REMINDER,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.APPOINTMENT_REMINDER],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.APPOINTMENT_REMINDER],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.APPOINTMENT_REMINDER],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.APPOINTMENT_REMINDER] as 'normal',
    group: 'REMINDER',
    description: 'অ্যাপয়েন্টমেন্ট রিমাইন্ডার পুশ',
  },
  [PUSH_TYPE.CUSTOMER_FEEDBACK]: {
    type: PUSH_TYPE.CUSTOMER_FEEDBACK,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.CUSTOMER_FEEDBACK],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.CUSTOMER_FEEDBACK],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.CUSTOMER_FEEDBACK],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.CUSTOMER_FEEDBACK] as 'low',
    group: 'SURVEY',
    description: 'গ্রাহক ফিডব্যাক পুশ',
  },
  [PUSH_TYPE.SUPPORT_ESCALATION]: {
    type: PUSH_TYPE.SUPPORT_ESCALATION,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.SUPPORT_ESCALATION],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.SUPPORT_ESCALATION],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.SUPPORT_ESCALATION],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.SUPPORT_ESCALATION] as 'high',
    group: 'TICKET',
    description: 'সাপোর্ট এস্কেলেশন পুশ',
  },
  [PUSH_TYPE.FOLLOW_UP]: {
    type: PUSH_TYPE.FOLLOW_UP,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.FOLLOW_UP],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.FOLLOW_UP],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.FOLLOW_UP],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.FOLLOW_UP] as 'normal',
    group: 'COMMUNICATION',
    description: 'ফলো-আপ পুশ',
  },
  [PUSH_TYPE.THANK_YOU]: {
    type: PUSH_TYPE.THANK_YOU,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.THANK_YOU],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.THANK_YOU],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.THANK_YOU],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.THANK_YOU] as 'low',
    group: 'COMMUNICATION',
    description: 'ধন্যবাদ পুশ',
  },
  [PUSH_TYPE.APOLOGY]: {
    type: PUSH_TYPE.APOLOGY,
    displayName: PUSH_TYPE_DISPLAY_NAMES[PUSH_TYPE.APOLOGY],
    icon: PUSH_TYPE_ICONS[PUSH_TYPE.APOLOGY],
    color: PUSH_TYPE_COLORS[PUSH_TYPE.APOLOGY],
    defaultPriority: PUSH_TYPE_DEFAULT_PRIORITY[PUSH_TYPE.APOLOGY] as 'normal',
    group: 'COMMUNICATION',
    description: 'ক্ষমা প্রার্থনা পুশ',
  },
};

/**
 * পুশ টাইপ গ্রুপ কনফিগারেশন
 */
export const PUSH_TYPE_GROUP_CONFIGS: Record<
  PushTypeGroup,
  {
    group: PushTypeGroup;
    displayName: string;
    icon: string;
    color: string;
    types: readonly PushType[];
    description?: string;
  }
> = {
  TICKET: {
    group: 'TICKET',
    displayName: 'টিকেট',
    icon: 'ticket',
    color: '#e67e22',
    types: [
      'ticket_update',
      'assignment',
      'resolution',
      'escalation',
      'support_escalation',
    ] as const,
    description: 'টিকেট সম্পর্কিত পুশ',
  },
  COMMUNICATION: {
    group: 'COMMUNICATION',
    displayName: 'যোগাযোগ',
    icon: 'message-circle',
    color: '#3498db',
    types: ['new_message', 'follow_up', 'thank_you', 'apology'] as const,
    description: 'যোগাযোগ সম্পর্কিত পুশ',
  },
  REMINDER: {
    group: 'REMINDER',
    displayName: 'রিমাইন্ডার',
    icon: 'clock',
    color: '#f39c12',
    types: ['reminder', 'appointment_reminder'] as const,
    description: 'রিমাইন্ডার পুশ',
  },
  SURVEY: {
    group: 'SURVEY',
    displayName: 'জরিপ',
    icon: 'clipboard',
    color: '#9b59b6',
    types: ['survey_request', 'feedback_request', 'customer_feedback'] as const,
    description: 'জরিপ সম্পর্কিত পুশ',
  },
  ALERT: {
    group: 'ALERT',
    displayName: 'অ্যালার্ট',
    icon: 'alert-circle',
    color: '#e74c3c',
    types: ['alert', 'security_alert', 'sla_breach'] as const,
    description: 'অ্যালার্ট পুশ',
  },
  STATUS: {
    group: 'STATUS',
    displayName: 'স্ট্যাটাস',
    icon: 'circle',
    color: '#95a5a6',
    types: ['status_change'] as const,
    description: 'স্ট্যাটাস পরিবর্তন পুশ',
  },
  SYSTEM: {
    group: 'SYSTEM',
    displayName: 'সিস্টেম',
    icon: 'cpu',
    color: '#2c3e50',
    types: ['system_notification', 'maintenance'] as const,
    description: 'সিস্টেম সম্পর্কিত পুশ',
  },
  MARKETING: {
    group: 'MARKETING',
    displayName: 'মার্কেটিং',
    icon: 'megaphone',
    color: '#2ecc71',
    types: ['promotional'] as const,
    description: 'প্রমোশনাল পুশ',
  },
  TRANSACTIONAL: {
    group: 'TRANSACTIONAL',
    displayName: 'ট্রানজেকশনাল',
    icon: 'credit-card',
    color: '#27ae60',
    types: ['transactional', 'billing', 'payment_confirmation', 'refund_update'] as const,
    description: 'ট্রানজেকশনাল পুশ',
  },
  ONBOARDING: {
    group: 'ONBOARDING',
    displayName: 'অনবোর্ডিং',
    icon: 'user-plus',
    color: '#2ecc71',
    types: ['welcome', 'onboarding', 'offboarding'] as const,
    description: 'অনবোর্ডিং সম্পর্কিত পুশ',
  },
  TEAM: {
    group: 'TEAM',
    displayName: 'টিম',
    icon: 'users',
    color: '#1abc9c',
    types: ['team_update', 'training'] as const,
    description: 'টিম সম্পর্কিত পুশ',
  },
  ORDER: {
    group: 'ORDER',
    displayName: 'অর্ডার',
    icon: 'shopping-bag',
    color: '#3498db',
    types: ['order_confirmation', 'delivery_update', 'cancellation'] as const,
    description: 'অর্ডার সম্পর্কিত পুশ',
  },
  SUBSCRIPTION: {
    group: 'SUBSCRIPTION',
    displayName: 'সাবস্ক্রিপশন',
    icon: 'repeat',
    color: '#8e44ad',
    types: ['renewal', 'upgrade', 'downgrade'] as const,
    description: 'সাবস্ক্রিপশন সম্পর্কিত পুশ',
  },
};

/**
 * পুশ টাইপ স্ট্যাটাস
 */
export const PUSH_TYPE_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  DEPRECATED: 'deprecated',
} as const;

export type PushTypeStatus = (typeof PUSH_TYPE_STATUS)[keyof typeof PUSH_TYPE_STATUS];
