/**
 * AI Search Status Constants
 * Status tracking for search lifecycle
 */

// First define the status types
export const AI_SEARCH_STATUS_TYPES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Processing States
  INITIALIZING: 'initializing',
  PROCESSING: 'processing',
  INDEXING: 'indexing',
  ANALYZING: 'analyzing',
  SEARCHING: 'searching',
  RANKING: 'ranking',
  FILTERING: 'filtering',

  // Intermediate States
  ANALYZED: 'analyzed',
  INDEXED: 'indexed',
  SEARCHED: 'searched',
  RANKED: 'ranked',
  FILTERED: 'filtered',
  OPTIMIZED: 'optimized',

  // Delivery States
  DELIVERING: 'delivering',
  DELIVERED: 'delivered',
  CACHED: 'cached',

  // User Interaction States
  DISPLAYED: 'displayed',
  VIEWED: 'viewed',
  CLICKED: 'clicked',

  // Terminal States
  COMPLETED: 'completed',
  FAILED: 'failed',
  EXPIRED: 'expired',
  ARCHIVED: 'archived',
  RETIRED: 'retired',
} as const;

export type AISearchStatusType =
  (typeof AI_SEARCH_STATUS_TYPES)[keyof typeof AI_SEARCH_STATUS_TYPES];

export const AI_SEARCH_STATUS = {
  // Status Types
  STATUSES: AI_SEARCH_STATUS_TYPES,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    DELIVERED: 'delivered',
    ENGAGED: 'engaged',
    COMPLETED: 'completed',
    FAILED: 'failed',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_SEARCH_STATUS_TYPES.CREATED]: '#gray',
    [AI_SEARCH_STATUS_TYPES.QUEUED]: '#gray',
    [AI_SEARCH_STATUS_TYPES.PENDING]: '#yellow',
    [AI_SEARCH_STATUS_TYPES.INITIALIZING]: '#blue',
    [AI_SEARCH_STATUS_TYPES.PROCESSING]: '#blue',
    [AI_SEARCH_STATUS_TYPES.INDEXING]: '#blue',
    [AI_SEARCH_STATUS_TYPES.ANALYZING]: '#blue',
    [AI_SEARCH_STATUS_TYPES.SEARCHING]: '#blue',
    [AI_SEARCH_STATUS_TYPES.RANKING]: '#blue',
    [AI_SEARCH_STATUS_TYPES.FILTERING]: '#blue',
    [AI_SEARCH_STATUS_TYPES.ANALYZED]: '#green',
    [AI_SEARCH_STATUS_TYPES.INDEXED]: '#green',
    [AI_SEARCH_STATUS_TYPES.SEARCHED]: '#green',
    [AI_SEARCH_STATUS_TYPES.RANKED]: '#green',
    [AI_SEARCH_STATUS_TYPES.FILTERED]: '#green',
    [AI_SEARCH_STATUS_TYPES.OPTIMIZED]: '#green',
    [AI_SEARCH_STATUS_TYPES.DELIVERING]: '#orange',
    [AI_SEARCH_STATUS_TYPES.DELIVERED]: '#green',
    [AI_SEARCH_STATUS_TYPES.CACHED]: '#green',
    [AI_SEARCH_STATUS_TYPES.DISPLAYED]: '#green',
    [AI_SEARCH_STATUS_TYPES.VIEWED]: '#green',
    [AI_SEARCH_STATUS_TYPES.CLICKED]: '#green',
    [AI_SEARCH_STATUS_TYPES.COMPLETED]: '#green',
    [AI_SEARCH_STATUS_TYPES.FAILED]: '#red',
    [AI_SEARCH_STATUS_TYPES.EXPIRED]: '#gray',
    [AI_SEARCH_STATUS_TYPES.ARCHIVED]: '#gray',
    [AI_SEARCH_STATUS_TYPES.RETIRED]: '#gray',
  } as const,
} as const;

// Status Categories
export type AISearchStatusCategory =
  (typeof AI_SEARCH_STATUS.CATEGORIES)[keyof typeof AI_SEARCH_STATUS.CATEGORIES];

// Status Severity
export type AISearchStatusSeverity =
  (typeof AI_SEARCH_STATUS.SEVERITY)[keyof typeof AI_SEARCH_STATUS.SEVERITY];

// Status Colors
export type AISearchStatusColor =
  (typeof AI_SEARCH_STATUS.COLORS)[keyof typeof AI_SEARCH_STATUS.COLORS];

// Utility Functions
export function getSearchStatusLabel(status: AISearchStatusType): string {
  const labels: Record<AISearchStatusType, string> = {
    [AI_SEARCH_STATUS_TYPES.CREATED]: 'Created',
    [AI_SEARCH_STATUS_TYPES.QUEUED]: 'Queued',
    [AI_SEARCH_STATUS_TYPES.PENDING]: 'Pending',
    [AI_SEARCH_STATUS_TYPES.INITIALIZING]: 'Initializing',
    [AI_SEARCH_STATUS_TYPES.PROCESSING]: 'Processing',
    [AI_SEARCH_STATUS_TYPES.INDEXING]: 'Indexing',
    [AI_SEARCH_STATUS_TYPES.ANALYZING]: 'Analyzing',
    [AI_SEARCH_STATUS_TYPES.SEARCHING]: 'Searching',
    [AI_SEARCH_STATUS_TYPES.RANKING]: 'Ranking',
    [AI_SEARCH_STATUS_TYPES.FILTERING]: 'Filtering',
    [AI_SEARCH_STATUS_TYPES.ANALYZED]: 'Analyzed',
    [AI_SEARCH_STATUS_TYPES.INDEXED]: 'Indexed',
    [AI_SEARCH_STATUS_TYPES.SEARCHED]: 'Searched',
    [AI_SEARCH_STATUS_TYPES.RANKED]: 'Ranked',
    [AI_SEARCH_STATUS_TYPES.FILTERED]: 'Filtered',
    [AI_SEARCH_STATUS_TYPES.OPTIMIZED]: 'Optimized',
    [AI_SEARCH_STATUS_TYPES.DELIVERING]: 'Delivering',
    [AI_SEARCH_STATUS_TYPES.DELIVERED]: 'Delivered',
    [AI_SEARCH_STATUS_TYPES.CACHED]: 'Cached',
    [AI_SEARCH_STATUS_TYPES.DISPLAYED]: 'Displayed',
    [AI_SEARCH_STATUS_TYPES.VIEWED]: 'Viewed',
    [AI_SEARCH_STATUS_TYPES.CLICKED]: 'Clicked',
    [AI_SEARCH_STATUS_TYPES.COMPLETED]: 'Completed',
    [AI_SEARCH_STATUS_TYPES.FAILED]: 'Failed',
    [AI_SEARCH_STATUS_TYPES.EXPIRED]: 'Expired',
    [AI_SEARCH_STATUS_TYPES.ARCHIVED]: 'Archived',
    [AI_SEARCH_STATUS_TYPES.RETIRED]: 'Retired',
  };
  return labels[status] || 'Unknown';
}

export function getSearchStatusCategory(status: AISearchStatusType): AISearchStatusCategory {
  const categories: Record<AISearchStatusType, AISearchStatusCategory> = {
    [AI_SEARCH_STATUS_TYPES.CREATED]: AI_SEARCH_STATUS.CATEGORIES.PENDING,
    [AI_SEARCH_STATUS_TYPES.QUEUED]: AI_SEARCH_STATUS.CATEGORIES.PENDING,
    [AI_SEARCH_STATUS_TYPES.PENDING]: AI_SEARCH_STATUS.CATEGORIES.PENDING,
    [AI_SEARCH_STATUS_TYPES.INITIALIZING]: AI_SEARCH_STATUS.CATEGORIES.PROCESSING,
    [AI_SEARCH_STATUS_TYPES.PROCESSING]: AI_SEARCH_STATUS.CATEGORIES.PROCESSING,
    [AI_SEARCH_STATUS_TYPES.INDEXING]: AI_SEARCH_STATUS.CATEGORIES.PROCESSING,
    [AI_SEARCH_STATUS_TYPES.ANALYZING]: AI_SEARCH_STATUS.CATEGORIES.PROCESSING,
    [AI_SEARCH_STATUS_TYPES.SEARCHING]: AI_SEARCH_STATUS.CATEGORIES.PROCESSING,
    [AI_SEARCH_STATUS_TYPES.RANKING]: AI_SEARCH_STATUS.CATEGORIES.PROCESSING,
    [AI_SEARCH_STATUS_TYPES.FILTERING]: AI_SEARCH_STATUS.CATEGORIES.PROCESSING,
    [AI_SEARCH_STATUS_TYPES.ANALYZED]: AI_SEARCH_STATUS.CATEGORIES.PROCESSING,
    [AI_SEARCH_STATUS_TYPES.INDEXED]: AI_SEARCH_STATUS.CATEGORIES.PROCESSING,
    [AI_SEARCH_STATUS_TYPES.SEARCHED]: AI_SEARCH_STATUS.CATEGORIES.PROCESSING,
    [AI_SEARCH_STATUS_TYPES.RANKED]: AI_SEARCH_STATUS.CATEGORIES.PROCESSING,
    [AI_SEARCH_STATUS_TYPES.FILTERED]: AI_SEARCH_STATUS.CATEGORIES.PROCESSING,
    [AI_SEARCH_STATUS_TYPES.OPTIMIZED]: AI_SEARCH_STATUS.CATEGORIES.PROCESSING,
    [AI_SEARCH_STATUS_TYPES.DELIVERING]: AI_SEARCH_STATUS.CATEGORIES.DELIVERED,
    [AI_SEARCH_STATUS_TYPES.DELIVERED]: AI_SEARCH_STATUS.CATEGORIES.DELIVERED,
    [AI_SEARCH_STATUS_TYPES.CACHED]: AI_SEARCH_STATUS.CATEGORIES.DELIVERED,
    [AI_SEARCH_STATUS_TYPES.DISPLAYED]: AI_SEARCH_STATUS.CATEGORIES.ENGAGED,
    [AI_SEARCH_STATUS_TYPES.VIEWED]: AI_SEARCH_STATUS.CATEGORIES.ENGAGED,
    [AI_SEARCH_STATUS_TYPES.CLICKED]: AI_SEARCH_STATUS.CATEGORIES.ENGAGED,
    [AI_SEARCH_STATUS_TYPES.COMPLETED]: AI_SEARCH_STATUS.CATEGORIES.COMPLETED,
    [AI_SEARCH_STATUS_TYPES.FAILED]: AI_SEARCH_STATUS.CATEGORIES.FAILED,
    [AI_SEARCH_STATUS_TYPES.EXPIRED]: AI_SEARCH_STATUS.CATEGORIES.FAILED,
    [AI_SEARCH_STATUS_TYPES.ARCHIVED]: AI_SEARCH_STATUS.CATEGORIES.COMPLETED,
    [AI_SEARCH_STATUS_TYPES.RETIRED]: AI_SEARCH_STATUS.CATEGORIES.COMPLETED,
  };
  return categories[status] || AI_SEARCH_STATUS.CATEGORIES.PENDING;
}

export function getSearchStatusSeverity(status: AISearchStatusType): AISearchStatusSeverity {
  const severities: Record<AISearchStatusType, AISearchStatusSeverity> = {
    [AI_SEARCH_STATUS_TYPES.CREATED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.QUEUED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.PENDING]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.INITIALIZING]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.PROCESSING]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.INDEXING]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.ANALYZING]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.SEARCHING]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.RANKING]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.FILTERING]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.ANALYZED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.INDEXED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.SEARCHED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.RANKED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.FILTERED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.OPTIMIZED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.DELIVERING]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.DELIVERED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.CACHED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.DISPLAYED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.VIEWED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.CLICKED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.COMPLETED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.FAILED]: AI_SEARCH_STATUS.SEVERITY.ERROR,
    [AI_SEARCH_STATUS_TYPES.EXPIRED]: AI_SEARCH_STATUS.SEVERITY.WARNING,
    [AI_SEARCH_STATUS_TYPES.ARCHIVED]: AI_SEARCH_STATUS.SEVERITY.INFO,
    [AI_SEARCH_STATUS_TYPES.RETIRED]: AI_SEARCH_STATUS.SEVERITY.INFO,
  };
  return severities[status] || AI_SEARCH_STATUS.SEVERITY.INFO;
}

export function getSearchStatusColor(status: AISearchStatusType): AISearchStatusColor {
  return AI_SEARCH_STATUS.COLORS[status] || '#gray';
}

export function isSearchActive(status: AISearchStatusType): boolean {
  const activeStatuses: AISearchStatusType[] = [
    AI_SEARCH_STATUS_TYPES.CREATED,
    AI_SEARCH_STATUS_TYPES.QUEUED,
    AI_SEARCH_STATUS_TYPES.PENDING,
    AI_SEARCH_STATUS_TYPES.INITIALIZING,
    AI_SEARCH_STATUS_TYPES.PROCESSING,
    AI_SEARCH_STATUS_TYPES.INDEXING,
    AI_SEARCH_STATUS_TYPES.ANALYZING,
    AI_SEARCH_STATUS_TYPES.SEARCHING,
    AI_SEARCH_STATUS_TYPES.RANKING,
    AI_SEARCH_STATUS_TYPES.FILTERING,
    AI_SEARCH_STATUS_TYPES.ANALYZED,
    AI_SEARCH_STATUS_TYPES.INDEXED,
    AI_SEARCH_STATUS_TYPES.SEARCHED,
    AI_SEARCH_STATUS_TYPES.RANKED,
    AI_SEARCH_STATUS_TYPES.FILTERED,
    AI_SEARCH_STATUS_TYPES.OPTIMIZED,
    AI_SEARCH_STATUS_TYPES.DELIVERING,
  ];
  return activeStatuses.includes(status);
}

export function isSearchDelivered(status: AISearchStatusType): boolean {
  const deliveredStatuses: AISearchStatusType[] = [
    AI_SEARCH_STATUS_TYPES.DELIVERED,
    AI_SEARCH_STATUS_TYPES.CACHED,
    AI_SEARCH_STATUS_TYPES.DISPLAYED,
    AI_SEARCH_STATUS_TYPES.VIEWED,
    AI_SEARCH_STATUS_TYPES.CLICKED,
  ];
  return deliveredStatuses.includes(status);
}

export function isSearchComplete(status: AISearchStatusType): boolean {
  const completeStatuses: AISearchStatusType[] = [
    AI_SEARCH_STATUS_TYPES.COMPLETED,
    AI_SEARCH_STATUS_TYPES.ARCHIVED,
    AI_SEARCH_STATUS_TYPES.RETIRED,
  ];
  return completeStatuses.includes(status);
}

export function isSearchFailed(status: AISearchStatusType): boolean {
  const failedStatuses: AISearchStatusType[] = [
    AI_SEARCH_STATUS_TYPES.FAILED,
    AI_SEARCH_STATUS_TYPES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}
