/**
 * Shipment Type Constants
 * Types of shipments
 */

export const LOGISTICS_SHIPMENT_TYPE = {
  // Type Types
  TYPES: {
    DOCUMENT: 'document',
    PACKAGE: 'package',
    CARGO: 'cargo',
    PALLET: 'pallet',
    CONTAINER: 'container',
    FRAGILE: 'fragile',
    LIQUID: 'liquid',
    PERISHABLE: 'perishable',
    HAZARDOUS: 'hazardous',
  } as const,

  // Type Categories
  CATEGORIES: {
    DOCUMENT: 'document',
    PARCEL: 'parcel',
    CARGO: 'cargo',
    SPECIAL: 'special',
  } as const,

  // Type Icons (for UI)
  ICONS: {
    DOCUMENT: '📄',
    PACKAGE: '📦',
    CARGO: '🚛',
    PALLET: '📋',
    CONTAINER: '📦',
    FRAGILE: '⚠️',
    LIQUID: '💧',
    PERISHABLE: '🌡️',
    HAZARDOUS: '☣️',
  } as const,

  // Type Colors (for UI)
  COLORS: {
    DOCUMENT: '#blue-400',
    PACKAGE: '#green-500',
    CARGO: '#orange-500',
    PALLET: '#purple-500',
    CONTAINER: '#gray-500',
    FRAGILE: '#red-500',
    LIQUID: '#blue-400',
    PERISHABLE: '#yellow-500',
    HAZARDOUS: '#red-600',
  } as const,

  // Weight Limits (in kg)
  WEIGHT_LIMITS: {
    DOCUMENT: 0.5,
    PACKAGE: 50,
    CARGO: 500,
    PALLET: 1000,
    CONTAINER: 5000,
    FRAGILE: 50,
    LIQUID: 50,
    PERISHABLE: 50,
    HAZARDOUS: 50,
  } as const,

  // Size Limits (in cm)
  SIZE_LIMITS: {
    DOCUMENT: { length: 35, width: 25, height: 5 },
    PACKAGE: { length: 100, width: 100, height: 100 },
    CARGO: { length: 300, width: 300, height: 300 },
    PALLET: { length: 120, width: 100, height: 150 },
    CONTAINER: { length: 600, width: 240, height: 240 },
    FRAGILE: { length: 100, width: 100, height: 100 },
    LIQUID: { length: 100, width: 100, height: 100 },
    PERISHABLE: { length: 100, width: 100, height: 100 },
    HAZARDOUS: { length: 100, width: 100, height: 100 },
  } as const,
} as const;

// Type Types
export type LogisticsShipmentTypeType =
  (typeof LOGISTICS_SHIPMENT_TYPE.TYPES)[keyof typeof LOGISTICS_SHIPMENT_TYPE.TYPES];

// Type Categories
export type LogisticsShipmentTypeCategory =
  (typeof LOGISTICS_SHIPMENT_TYPE.CATEGORIES)[keyof typeof LOGISTICS_SHIPMENT_TYPE.CATEGORIES];

// Type Icons
export type LogisticsShipmentTypeIcon =
  (typeof LOGISTICS_SHIPMENT_TYPE.ICONS)[keyof typeof LOGISTICS_SHIPMENT_TYPE.ICONS];

// Type Colors
export type LogisticsShipmentTypeColor =
  (typeof LOGISTICS_SHIPMENT_TYPE.COLORS)[keyof typeof LOGISTICS_SHIPMENT_TYPE.COLORS];

// Utility Functions
export function logisticsShipmentTypeGetLabel(type: LogisticsShipmentTypeType): string {
  const labels: Record<LogisticsShipmentTypeType, string> = {
    [LOGISTICS_SHIPMENT_TYPE.TYPES.DOCUMENT]: 'Document',
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PACKAGE]: 'Package',
    [LOGISTICS_SHIPMENT_TYPE.TYPES.CARGO]: 'Cargo',
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PALLET]: 'Pallet',
    [LOGISTICS_SHIPMENT_TYPE.TYPES.CONTAINER]: 'Container',
    [LOGISTICS_SHIPMENT_TYPE.TYPES.FRAGILE]: 'Fragile',
    [LOGISTICS_SHIPMENT_TYPE.TYPES.LIQUID]: 'Liquid',
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PERISHABLE]: 'Perishable',
    [LOGISTICS_SHIPMENT_TYPE.TYPES.HAZARDOUS]: 'Hazardous',
  };
  return labels[type] || 'Unknown';
}

export function logisticsShipmentTypeGetCategory(
  type: LogisticsShipmentTypeType
): LogisticsShipmentTypeCategory {
  const categories: Record<LogisticsShipmentTypeType, LogisticsShipmentTypeCategory> = {
    [LOGISTICS_SHIPMENT_TYPE.TYPES.DOCUMENT]: LOGISTICS_SHIPMENT_TYPE.CATEGORIES.DOCUMENT,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PACKAGE]: LOGISTICS_SHIPMENT_TYPE.CATEGORIES.PARCEL,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.CARGO]: LOGISTICS_SHIPMENT_TYPE.CATEGORIES.CARGO,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PALLET]: LOGISTICS_SHIPMENT_TYPE.CATEGORIES.CARGO,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.CONTAINER]: LOGISTICS_SHIPMENT_TYPE.CATEGORIES.CARGO,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.FRAGILE]: LOGISTICS_SHIPMENT_TYPE.CATEGORIES.SPECIAL,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.LIQUID]: LOGISTICS_SHIPMENT_TYPE.CATEGORIES.SPECIAL,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PERISHABLE]: LOGISTICS_SHIPMENT_TYPE.CATEGORIES.SPECIAL,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.HAZARDOUS]: LOGISTICS_SHIPMENT_TYPE.CATEGORIES.SPECIAL,
  };
  return categories[type] || LOGISTICS_SHIPMENT_TYPE.CATEGORIES.PARCEL;
}

export function logisticsShipmentTypeGetIcon(
  type: LogisticsShipmentTypeType
): LogisticsShipmentTypeIcon {
  const icons: Record<LogisticsShipmentTypeType, LogisticsShipmentTypeIcon> = {
    [LOGISTICS_SHIPMENT_TYPE.TYPES.DOCUMENT]: LOGISTICS_SHIPMENT_TYPE.ICONS.DOCUMENT,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PACKAGE]: LOGISTICS_SHIPMENT_TYPE.ICONS.PACKAGE,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.CARGO]: LOGISTICS_SHIPMENT_TYPE.ICONS.CARGO,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PALLET]: LOGISTICS_SHIPMENT_TYPE.ICONS.PALLET,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.CONTAINER]: LOGISTICS_SHIPMENT_TYPE.ICONS.CONTAINER,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.FRAGILE]: LOGISTICS_SHIPMENT_TYPE.ICONS.FRAGILE,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.LIQUID]: LOGISTICS_SHIPMENT_TYPE.ICONS.LIQUID,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PERISHABLE]: LOGISTICS_SHIPMENT_TYPE.ICONS.PERISHABLE,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.HAZARDOUS]: LOGISTICS_SHIPMENT_TYPE.ICONS.HAZARDOUS,
  };
  return icons[type] || '📦';
}

export function logisticsShipmentTypeGetWeightLimit(type: LogisticsShipmentTypeType): number {
  const limits: Record<LogisticsShipmentTypeType, number> = {
    [LOGISTICS_SHIPMENT_TYPE.TYPES.DOCUMENT]: LOGISTICS_SHIPMENT_TYPE.WEIGHT_LIMITS.DOCUMENT,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PACKAGE]: LOGISTICS_SHIPMENT_TYPE.WEIGHT_LIMITS.PACKAGE,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.CARGO]: LOGISTICS_SHIPMENT_TYPE.WEIGHT_LIMITS.CARGO,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PALLET]: LOGISTICS_SHIPMENT_TYPE.WEIGHT_LIMITS.PALLET,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.CONTAINER]: LOGISTICS_SHIPMENT_TYPE.WEIGHT_LIMITS.CONTAINER,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.FRAGILE]: LOGISTICS_SHIPMENT_TYPE.WEIGHT_LIMITS.FRAGILE,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.LIQUID]: LOGISTICS_SHIPMENT_TYPE.WEIGHT_LIMITS.LIQUID,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PERISHABLE]: LOGISTICS_SHIPMENT_TYPE.WEIGHT_LIMITS.PERISHABLE,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.HAZARDOUS]: LOGISTICS_SHIPMENT_TYPE.WEIGHT_LIMITS.HAZARDOUS,
  };
  return limits[type] || LOGISTICS_SHIPMENT_TYPE.WEIGHT_LIMITS.PACKAGE;
}

export function logisticsShipmentTypeGetSizeLimit(type: LogisticsShipmentTypeType): {
  length: number;
  width: number;
  height: number;
} {
  const limits: Record<
    LogisticsShipmentTypeType,
    { length: number; width: number; height: number }
  > = {
    [LOGISTICS_SHIPMENT_TYPE.TYPES.DOCUMENT]: LOGISTICS_SHIPMENT_TYPE.SIZE_LIMITS.DOCUMENT,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PACKAGE]: LOGISTICS_SHIPMENT_TYPE.SIZE_LIMITS.PACKAGE,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.CARGO]: LOGISTICS_SHIPMENT_TYPE.SIZE_LIMITS.CARGO,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PALLET]: LOGISTICS_SHIPMENT_TYPE.SIZE_LIMITS.PALLET,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.CONTAINER]: LOGISTICS_SHIPMENT_TYPE.SIZE_LIMITS.CONTAINER,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.FRAGILE]: LOGISTICS_SHIPMENT_TYPE.SIZE_LIMITS.FRAGILE,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.LIQUID]: LOGISTICS_SHIPMENT_TYPE.SIZE_LIMITS.LIQUID,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.PERISHABLE]: LOGISTICS_SHIPMENT_TYPE.SIZE_LIMITS.PERISHABLE,
    [LOGISTICS_SHIPMENT_TYPE.TYPES.HAZARDOUS]: LOGISTICS_SHIPMENT_TYPE.SIZE_LIMITS.HAZARDOUS,
  };
  return limits[type] || LOGISTICS_SHIPMENT_TYPE.SIZE_LIMITS.PACKAGE;
}
