/**
 * Affiliate Status Constants
 * Status definitions for affiliate lifecycle
 */

export const MARKETINGAFFILIATE_STATUS = {
  // Affiliate Statuses
  STATUSES: {
    PENDING_APPLICATION: 'pending_application',
    UNDER_REVIEW: 'under_review',
    APPROVED: 'approved',
    REJECTED: 'rejected',
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    SUSPENDED: 'suspended',
    TERMINATED: 'terminated',
    PAUSED: 'paused',
    ON_HOLD: 'on_hold',
    COMPLETED: 'completed',
    ARCHIVED: 'archived',
    FRAUD_SUSPECTED: 'fraud_suspected',
    UNDER_INVESTIGATION: 'under_investigation',
    WARNING: 'warning',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    PENDING_APPLICATION: '#F59E0B',
    UNDER_REVIEW: '#8B5CF6',
    APPROVED: '#10B981',
    REJECTED: '#EF4444',
    ACTIVE: '#10B981',
    INACTIVE: '#6B7280',
    SUSPENDED: '#EF4444',
    TERMINATED: '#6B7280',
    PAUSED: '#F59E0B',
    ON_HOLD: '#F59E0B',
    COMPLETED: '#10B981',
    ARCHIVED: '#6B7280',
    FRAUD_SUSPECTED: '#EF4444',
    UNDER_INVESTIGATION: '#F59E0B',
    WARNING: '#F59E0B',
  } as const,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    ACTIVE: 'active',
    SUSPENDED: 'suspended',
    TERMINATED: 'terminated',
    COMPLETED: 'completed',
    ARCHIVED: 'archived',
    FRAUD: 'fraud',
  } as const,

  // Status Priority Order
  ORDER: {
    PENDING_APPLICATION: 0,
    UNDER_REVIEW: 1,
    APPROVED: 2,
    REJECTED: 3,
    ACTIVE: 4,
    INACTIVE: 5,
    SUSPENDED: 6,
    TERMINATED: 7,
    PAUSED: 8,
    ON_HOLD: 9,
    COMPLETED: 10,
    ARCHIVED: 11,
    FRAUD_SUSPECTED: 12,
    UNDER_INVESTIGATION: 13,
    WARNING: 14,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    PENDING_TO_UNDER_REVIEW: 'pending_to_under_review',
    PENDING_TO_REJECTED: 'pending_to_rejected',
    UNDER_REVIEW_TO_APPROVED: 'under_review_to_approved',
    UNDER_REVIEW_TO_REJECTED: 'under_review_to_rejected',
    APPROVED_TO_ACTIVE: 'approved_to_active',
    APPROVED_TO_REJECTED: 'approved_to_rejected',
    ACTIVE_TO_INACTIVE: 'active_to_inactive',
    ACTIVE_TO_SUSPENDED: 'active_to_suspended',
    ACTIVE_TO_PAUSED: 'active_to_paused',
    ACTIVE_TO_ON_HOLD: 'active_to_on_hold',
    ACTIVE_TO_COMPLETED: 'active_to_completed',
    ACTIVE_TO_FRAUD_SUSPECTED: 'active_to_fraud_suspected',
    INACTIVE_TO_ACTIVE: 'inactive_to_active',
    SUSPENDED_TO_ACTIVE: 'suspended_to_active',
    SUSPENDED_TO_TERMINATED: 'suspended_to_terminated',
    SUSPENDED_TO_UNDER_INVESTIGATION: 'suspended_to_under_investigation',
    PAUSED_TO_ACTIVE: 'paused_to_active',
    PAUSED_TO_SUSPENDED: 'paused_to_suspended',
    ON_HOLD_TO_ACTIVE: 'on_hold_to_active',
    ON_HOLD_TO_SUSPENDED: 'on_hold_to_suspended',
    COMPLETED_TO_ARCHIVED: 'completed_to_archived',
    TERMINATED_TO_ARCHIVED: 'terminated_to_archived',
    FRAUD_SUSPECTED_TO_UNDER_INVESTIGATION: 'fraud_suspected_to_under_investigation',
    FRAUD_SUSPECTED_TO_TERMINATED: 'fraud_suspected_to_terminated',
    UNDER_INVESTIGATION_TO_ACTIVE: 'under_investigation_to_active',
    UNDER_INVESTIGATION_TO_SUSPENDED: 'under_investigation_to_suspended',
    UNDER_INVESTIGATION_TO_TERMINATED: 'under_investigation_to_terminated',
    WARNING_TO_ACTIVE: 'warning_to_active',
    WARNING_TO_SUSPENDED: 'warning_to_suspended',
    WARNING_TO_TERMINATED: 'warning_to_terminated',
  } as const,
} as const;

// Affiliate Statuses
export type MarketingAffiliateStatusType =
  (typeof MARKETINGAFFILIATE_STATUS.STATUSES)[keyof typeof MARKETINGAFFILIATE_STATUS.STATUSES];

// Status Colors
export type MarketingAffiliateStatusColor =
  (typeof MARKETINGAFFILIATE_STATUS.COLORS)[keyof typeof MARKETINGAFFILIATE_STATUS.COLORS];

// Status Categories
export type MarketingAffiliateStatusCategory =
  (typeof MARKETINGAFFILIATE_STATUS.CATEGORIES)[keyof typeof MARKETINGAFFILIATE_STATUS.CATEGORIES];

// Status Priority Order
export type MarketingAffiliateStatusOrder =
  (typeof MARKETINGAFFILIATE_STATUS.ORDER)[keyof typeof MARKETINGAFFILIATE_STATUS.ORDER];

// Status Transitions
export type MarketingAffiliateStatusTransition =
  (typeof MARKETINGAFFILIATE_STATUS.TRANSITIONS)[keyof typeof MARKETINGAFFILIATE_STATUS.TRANSITIONS];

// Utility Functions
export function marketingaffiliateGetStatusLabel(status: MarketingAffiliateStatusType): string {
  const labels: Record<MarketingAffiliateStatusType, string> = {
    [MARKETINGAFFILIATE_STATUS.STATUSES.PENDING_APPLICATION]: 'Pending Application',
    [MARKETINGAFFILIATE_STATUS.STATUSES.UNDER_REVIEW]: 'Under Review',
    [MARKETINGAFFILIATE_STATUS.STATUSES.APPROVED]: 'Approved',
    [MARKETINGAFFILIATE_STATUS.STATUSES.REJECTED]: 'Rejected',
    [MARKETINGAFFILIATE_STATUS.STATUSES.ACTIVE]: 'Active',
    [MARKETINGAFFILIATE_STATUS.STATUSES.INACTIVE]: 'Inactive',
    [MARKETINGAFFILIATE_STATUS.STATUSES.SUSPENDED]: 'Suspended',
    [MARKETINGAFFILIATE_STATUS.STATUSES.TERMINATED]: 'Terminated',
    [MARKETINGAFFILIATE_STATUS.STATUSES.PAUSED]: 'Paused',
    [MARKETINGAFFILIATE_STATUS.STATUSES.ON_HOLD]: 'On Hold',
    [MARKETINGAFFILIATE_STATUS.STATUSES.COMPLETED]: 'Completed',
    [MARKETINGAFFILIATE_STATUS.STATUSES.ARCHIVED]: 'Archived',
    [MARKETINGAFFILIATE_STATUS.STATUSES.FRAUD_SUSPECTED]: 'Fraud Suspected',
    [MARKETINGAFFILIATE_STATUS.STATUSES.UNDER_INVESTIGATION]: 'Under Investigation',
    [MARKETINGAFFILIATE_STATUS.STATUSES.WARNING]: 'Warning',
  };
  return labels[status] || 'Unknown Status';
}

export function marketingaffiliateGetStatusColor(
  status: MarketingAffiliateStatusType
): MarketingAffiliateStatusColor {
  const colors: Record<MarketingAffiliateStatusType, MarketingAffiliateStatusColor> = {
    [MARKETINGAFFILIATE_STATUS.STATUSES.PENDING_APPLICATION]:
      MARKETINGAFFILIATE_STATUS.COLORS.PENDING_APPLICATION,
    [MARKETINGAFFILIATE_STATUS.STATUSES.UNDER_REVIEW]:
      MARKETINGAFFILIATE_STATUS.COLORS.UNDER_REVIEW,
    [MARKETINGAFFILIATE_STATUS.STATUSES.APPROVED]: MARKETINGAFFILIATE_STATUS.COLORS.APPROVED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.REJECTED]: MARKETINGAFFILIATE_STATUS.COLORS.REJECTED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.ACTIVE]: MARKETINGAFFILIATE_STATUS.COLORS.ACTIVE,
    [MARKETINGAFFILIATE_STATUS.STATUSES.INACTIVE]: MARKETINGAFFILIATE_STATUS.COLORS.INACTIVE,
    [MARKETINGAFFILIATE_STATUS.STATUSES.SUSPENDED]: MARKETINGAFFILIATE_STATUS.COLORS.SUSPENDED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.TERMINATED]: MARKETINGAFFILIATE_STATUS.COLORS.TERMINATED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.PAUSED]: MARKETINGAFFILIATE_STATUS.COLORS.PAUSED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.ON_HOLD]: MARKETINGAFFILIATE_STATUS.COLORS.ON_HOLD,
    [MARKETINGAFFILIATE_STATUS.STATUSES.COMPLETED]: MARKETINGAFFILIATE_STATUS.COLORS.COMPLETED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.ARCHIVED]: MARKETINGAFFILIATE_STATUS.COLORS.ARCHIVED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.FRAUD_SUSPECTED]:
      MARKETINGAFFILIATE_STATUS.COLORS.FRAUD_SUSPECTED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.UNDER_INVESTIGATION]:
      MARKETINGAFFILIATE_STATUS.COLORS.UNDER_INVESTIGATION,
    [MARKETINGAFFILIATE_STATUS.STATUSES.WARNING]: MARKETINGAFFILIATE_STATUS.COLORS.WARNING,
  };
  return colors[status] || MARKETINGAFFILIATE_STATUS.COLORS.PENDING_APPLICATION;
}

export function marketingaffiliateGetStatusCategory(
  status: MarketingAffiliateStatusType
): MarketingAffiliateStatusCategory {
  const categories: Record<MarketingAffiliateStatusType, MarketingAffiliateStatusCategory> = {
    [MARKETINGAFFILIATE_STATUS.STATUSES.PENDING_APPLICATION]:
      MARKETINGAFFILIATE_STATUS.CATEGORIES.PENDING,
    [MARKETINGAFFILIATE_STATUS.STATUSES.UNDER_REVIEW]: MARKETINGAFFILIATE_STATUS.CATEGORIES.PENDING,
    [MARKETINGAFFILIATE_STATUS.STATUSES.APPROVED]: MARKETINGAFFILIATE_STATUS.CATEGORIES.PENDING,
    [MARKETINGAFFILIATE_STATUS.STATUSES.REJECTED]: MARKETINGAFFILIATE_STATUS.CATEGORIES.TERMINATED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.ACTIVE]: MARKETINGAFFILIATE_STATUS.CATEGORIES.ACTIVE,
    [MARKETINGAFFILIATE_STATUS.STATUSES.INACTIVE]: MARKETINGAFFILIATE_STATUS.CATEGORIES.SUSPENDED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.SUSPENDED]: MARKETINGAFFILIATE_STATUS.CATEGORIES.SUSPENDED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.TERMINATED]:
      MARKETINGAFFILIATE_STATUS.CATEGORIES.TERMINATED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.PAUSED]: MARKETINGAFFILIATE_STATUS.CATEGORIES.SUSPENDED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.ON_HOLD]: MARKETINGAFFILIATE_STATUS.CATEGORIES.SUSPENDED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.COMPLETED]: MARKETINGAFFILIATE_STATUS.CATEGORIES.COMPLETED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.ARCHIVED]: MARKETINGAFFILIATE_STATUS.CATEGORIES.ARCHIVED,
    [MARKETINGAFFILIATE_STATUS.STATUSES.FRAUD_SUSPECTED]:
      MARKETINGAFFILIATE_STATUS.CATEGORIES.FRAUD,
    [MARKETINGAFFILIATE_STATUS.STATUSES.UNDER_INVESTIGATION]:
      MARKETINGAFFILIATE_STATUS.CATEGORIES.FRAUD,
    [MARKETINGAFFILIATE_STATUS.STATUSES.WARNING]: MARKETINGAFFILIATE_STATUS.CATEGORIES.SUSPENDED,
  };
  return categories[status] || MARKETINGAFFILIATE_STATUS.CATEGORIES.PENDING;
}

export function marketingaffiliateIsActiveStatus(status: MarketingAffiliateStatusType): boolean {
  const activeStatuses: MarketingAffiliateStatusType[] = [
    MARKETINGAFFILIATE_STATUS.STATUSES.ACTIVE,
    MARKETINGAFFILIATE_STATUS.STATUSES.APPROVED,
  ];
  return activeStatuses.includes(status);
}

export function marketingaffiliateIsSuspendedStatus(status: MarketingAffiliateStatusType): boolean {
  const suspendedStatuses: MarketingAffiliateStatusType[] = [
    MARKETINGAFFILIATE_STATUS.STATUSES.SUSPENDED,
    MARKETINGAFFILIATE_STATUS.STATUSES.PAUSED,
    MARKETINGAFFILIATE_STATUS.STATUSES.ON_HOLD,
    MARKETINGAFFILIATE_STATUS.STATUSES.WARNING,
  ];
  return suspendedStatuses.includes(status);
}

export function marketingaffiliateIsTerminatedStatus(
  status: MarketingAffiliateStatusType
): boolean {
  const terminatedStatuses: MarketingAffiliateStatusType[] = [
    MARKETINGAFFILIATE_STATUS.STATUSES.TERMINATED,
    MARKETINGAFFILIATE_STATUS.STATUSES.REJECTED,
  ];
  return terminatedStatuses.includes(status);
}

export function marketingaffiliateIsFraudStatus(status: MarketingAffiliateStatusType): boolean {
  const fraudStatuses: MarketingAffiliateStatusType[] = [
    MARKETINGAFFILIATE_STATUS.STATUSES.FRAUD_SUSPECTED,
    MARKETINGAFFILIATE_STATUS.STATUSES.UNDER_INVESTIGATION,
  ];
  return fraudStatuses.includes(status);
}

export function marketingaffiliateCanTransition(
  currentStatus: MarketingAffiliateStatusType,
  targetStatus: MarketingAffiliateStatusType
): boolean {
  const validTransitions: Record<MarketingAffiliateStatusType, MarketingAffiliateStatusType[]> = {
    [MARKETINGAFFILIATE_STATUS.STATUSES.PENDING_APPLICATION]: [
      MARKETINGAFFILIATE_STATUS.STATUSES.UNDER_REVIEW,
      MARKETINGAFFILIATE_STATUS.STATUSES.REJECTED,
    ],
    [MARKETINGAFFILIATE_STATUS.STATUSES.UNDER_REVIEW]: [
      MARKETINGAFFILIATE_STATUS.STATUSES.APPROVED,
      MARKETINGAFFILIATE_STATUS.STATUSES.REJECTED,
    ],
    [MARKETINGAFFILIATE_STATUS.STATUSES.APPROVED]: [
      MARKETINGAFFILIATE_STATUS.STATUSES.ACTIVE,
      MARKETINGAFFILIATE_STATUS.STATUSES.REJECTED,
    ],
    [MARKETINGAFFILIATE_STATUS.STATUSES.ACTIVE]: [
      MARKETINGAFFILIATE_STATUS.STATUSES.INACTIVE,
      MARKETINGAFFILIATE_STATUS.STATUSES.SUSPENDED,
      MARKETINGAFFILIATE_STATUS.STATUSES.PAUSED,
      MARKETINGAFFILIATE_STATUS.STATUSES.ON_HOLD,
      MARKETINGAFFILIATE_STATUS.STATUSES.COMPLETED,
      MARKETINGAFFILIATE_STATUS.STATUSES.FRAUD_SUSPECTED,
    ],
    [MARKETINGAFFILIATE_STATUS.STATUSES.INACTIVE]: [
      MARKETINGAFFILIATE_STATUS.STATUSES.ACTIVE,
      MARKETINGAFFILIATE_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGAFFILIATE_STATUS.STATUSES.SUSPENDED]: [
      MARKETINGAFFILIATE_STATUS.STATUSES.ACTIVE,
      MARKETINGAFFILIATE_STATUS.STATUSES.TERMINATED,
      MARKETINGAFFILIATE_STATUS.STATUSES.UNDER_INVESTIGATION,
    ],
    [MARKETINGAFFILIATE_STATUS.STATUSES.REJECTED]: [MARKETINGAFFILIATE_STATUS.STATUSES.ARCHIVED],
    [MARKETINGAFFILIATE_STATUS.STATUSES.PAUSED]: [
      MARKETINGAFFILIATE_STATUS.STATUSES.ACTIVE,
      MARKETINGAFFILIATE_STATUS.STATUSES.SUSPENDED,
    ],
    [MARKETINGAFFILIATE_STATUS.STATUSES.ON_HOLD]: [
      MARKETINGAFFILIATE_STATUS.STATUSES.ACTIVE,
      MARKETINGAFFILIATE_STATUS.STATUSES.SUSPENDED,
    ],
    [MARKETINGAFFILIATE_STATUS.STATUSES.COMPLETED]: [MARKETINGAFFILIATE_STATUS.STATUSES.ARCHIVED],
    [MARKETINGAFFILIATE_STATUS.STATUSES.TERMINATED]: [MARKETINGAFFILIATE_STATUS.STATUSES.ARCHIVED],
    [MARKETINGAFFILIATE_STATUS.STATUSES.FRAUD_SUSPECTED]: [
      MARKETINGAFFILIATE_STATUS.STATUSES.UNDER_INVESTIGATION,
      MARKETINGAFFILIATE_STATUS.STATUSES.TERMINATED,
    ],
    [MARKETINGAFFILIATE_STATUS.STATUSES.UNDER_INVESTIGATION]: [
      MARKETINGAFFILIATE_STATUS.STATUSES.ACTIVE,
      MARKETINGAFFILIATE_STATUS.STATUSES.SUSPENDED,
      MARKETINGAFFILIATE_STATUS.STATUSES.TERMINATED,
    ],
    [MARKETINGAFFILIATE_STATUS.STATUSES.WARNING]: [
      MARKETINGAFFILIATE_STATUS.STATUSES.ACTIVE,
      MARKETINGAFFILIATE_STATUS.STATUSES.SUSPENDED,
      MARKETINGAFFILIATE_STATUS.STATUSES.TERMINATED,
    ],
    [MARKETINGAFFILIATE_STATUS.STATUSES.ARCHIVED]: [],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
