/**
 * Affiliate Payout Status Constants
 * Status definitions for affiliate payouts
 */

export const MARKETINGAFFILIATE_PAYOUT_STATUS = {
  // Payout Statuses
  STATUSES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    ON_HOLD: 'on_hold',
    REJECTED: 'rejected',
    PARTIAL: 'partial',
    REVERSED: 'reversed',
    APPROVED: 'approved',
    SCHEDULED: 'scheduled',
    IN_TRANSIT: 'in_transit',
    DELIVERED: 'delivered',
    RETURNED: 'returned',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    PENDING: '#F59E0B',
    PROCESSING: '#3B82F6',
    COMPLETED: '#10B981',
    FAILED: '#EF4444',
    CANCELLED: '#6B7280',
    ON_HOLD: '#F59E0B',
    REJECTED: '#EF4444',
    PARTIAL: '#F59E0B',
    REVERSED: '#6B7280',
    APPROVED: '#10B981',
    SCHEDULED: '#8B5CF6',
    IN_TRANSIT: '#3B82F6',
    DELIVERED: '#10B981',
    RETURNED: '#6B7280',
  } as const,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    HOLD: 'hold',
    REVERSED: 'reversed',
  } as const,

  // Status Priority Order
  ORDER: {
    PENDING: 0,
    APPROVED: 1,
    SCHEDULED: 2,
    PROCESSING: 3,
    IN_TRANSIT: 4,
    COMPLETED: 5,
    DELIVERED: 6,
    PARTIAL: 7,
    ON_HOLD: 8,
    REJECTED: 9,
    FAILED: 10,
    CANCELLED: 11,
    REVERSED: 12,
    RETURNED: 13,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    PENDING_TO_APPROVED: 'pending_to_approved',
    PENDING_TO_REJECTED: 'pending_to_rejected',
    PENDING_TO_CANCELLED: 'pending_to_cancelled',
    APPROVED_TO_SCHEDULED: 'approved_to_scheduled',
    APPROVED_TO_CANCELLED: 'approved_to_cancelled',
    SCHEDULED_TO_PROCESSING: 'scheduled_to_processing',
    SCHEDULED_TO_CANCELLED: 'scheduled_to_cancelled',
    PROCESSING_TO_IN_TRANSIT: 'processing_to_in_transit',
    PROCESSING_TO_COMPLETED: 'processing_to_completed',
    PROCESSING_TO_FAILED: 'processing_to_failed',
    PROCESSING_TO_ON_HOLD: 'processing_to_on_hold',
    PROCESSING_TO_CANCELLED: 'processing_to_cancelled',
    IN_TRANSIT_TO_DELIVERED: 'in_transit_to_delivered',
    IN_TRANSIT_TO_RETURNED: 'in_transit_to_returned',
    IN_TRANSIT_TO_FAILED: 'in_transit_to_failed',
    COMPLETED_TO_REVERSED: 'completed_to_reversed',
    DELIVERED_TO_COMPLETED: 'delivered_to_completed',
    ON_HOLD_TO_PROCESSING: 'on_hold_to_processing',
    ON_HOLD_TO_CANCELLED: 'on_hold_to_cancelled',
    FAILED_TO_PENDING: 'failed_to_pending',
    FAILED_TO_CANCELLED: 'failed_to_cancelled',
    PARTIAL_TO_COMPLETED: 'partial_to_completed',
    PARTIAL_TO_CANCELLED: 'partial_to_cancelled',
    REJECTED_TO_PENDING: 'rejected_to_pending',
    REJECTED_TO_CANCELLED: 'rejected_to_cancelled',
    RETURNED_TO_PENDING: 'returned_to_pending',
    RETURNED_TO_CANCELLED: 'returned_to_cancelled',
    REVERSED_TO_PENDING: 'reversed_to_pending',
  } as const,
} as const;

// Payout Statuses
export type MarketingAffiliatePayoutStatusType =
  (typeof MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES)[keyof typeof MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES];

// Status Colors
export type MarketingAffiliatePayoutStatusColor =
  (typeof MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS)[keyof typeof MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS];

// Status Categories
export type MarketingAffiliatePayoutStatusCategory =
  (typeof MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES)[keyof typeof MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES];

// Status Priority Order
export type MarketingAffiliatePayoutStatusOrder =
  (typeof MARKETINGAFFILIATE_PAYOUT_STATUS.ORDER)[keyof typeof MARKETINGAFFILIATE_PAYOUT_STATUS.ORDER];

// Status Transitions
export type MarketingAffiliatePayoutStatusTransition =
  (typeof MARKETINGAFFILIATE_PAYOUT_STATUS.TRANSITIONS)[keyof typeof MARKETINGAFFILIATE_PAYOUT_STATUS.TRANSITIONS];

// Utility Functions
export function marketingaffiliateGetPayoutStatusLabel(
  status: MarketingAffiliatePayoutStatusType
): string {
  const labels: Record<MarketingAffiliatePayoutStatusType, string> = {
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PENDING]: 'Pending',
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PROCESSING]: 'Processing',
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.COMPLETED]: 'Completed',
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.FAILED]: 'Failed',
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.CANCELLED]: 'Cancelled',
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.ON_HOLD]: 'On Hold',
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.REJECTED]: 'Rejected',
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PARTIAL]: 'Partial',
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.REVERSED]: 'Reversed',
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.APPROVED]: 'Approved',
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.SCHEDULED]: 'Scheduled',
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.IN_TRANSIT]: 'In Transit',
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.DELIVERED]: 'Delivered',
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.RETURNED]: 'Returned',
  };
  return labels[status] || 'Unknown Status';
}

export function marketingaffiliateGetPayoutStatusColor(
  status: MarketingAffiliatePayoutStatusType
): MarketingAffiliatePayoutStatusColor {
  const colors: Record<MarketingAffiliatePayoutStatusType, MarketingAffiliatePayoutStatusColor> = {
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PENDING]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.PENDING,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PROCESSING]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.PROCESSING,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.COMPLETED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.COMPLETED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.FAILED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.FAILED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.CANCELLED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.CANCELLED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.ON_HOLD]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.ON_HOLD,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.REJECTED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.REJECTED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PARTIAL]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.PARTIAL,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.REVERSED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.REVERSED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.APPROVED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.APPROVED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.SCHEDULED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.SCHEDULED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.IN_TRANSIT]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.IN_TRANSIT,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.DELIVERED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.DELIVERED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.RETURNED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.RETURNED,
  };
  return colors[status] || MARKETINGAFFILIATE_PAYOUT_STATUS.COLORS.PENDING;
}

export function marketingaffiliateGetPayoutStatusCategory(
  status: MarketingAffiliatePayoutStatusType
): MarketingAffiliatePayoutStatusCategory {
  const categories: Record<
    MarketingAffiliatePayoutStatusType,
    MarketingAffiliatePayoutStatusCategory
  > = {
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PENDING]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.PENDING,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.APPROVED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.PENDING,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.SCHEDULED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.PENDING,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PROCESSING]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.PROCESSING,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.IN_TRANSIT]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.PROCESSING,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.COMPLETED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.COMPLETED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.DELIVERED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.COMPLETED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PARTIAL]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.COMPLETED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.ON_HOLD]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.HOLD,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.REJECTED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.FAILED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.FAILED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.FAILED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.CANCELLED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.CANCELLED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.REVERSED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.REVERSED,
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.RETURNED]:
      MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.REVERSED,
  };
  return categories[status] || MARKETINGAFFILIATE_PAYOUT_STATUS.CATEGORIES.PENDING;
}

export function marketingaffiliateIsPayoutCompleted(
  status: MarketingAffiliatePayoutStatusType
): boolean {
  const completedStatuses: MarketingAffiliatePayoutStatusType[] = [
    MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.COMPLETED,
    MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.DELIVERED,
    MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PARTIAL,
  ];
  return completedStatuses.includes(status);
}

export function marketingaffiliateIsPayoutInProgress(
  status: MarketingAffiliatePayoutStatusType
): boolean {
  const inProgressStatuses: MarketingAffiliatePayoutStatusType[] = [
    MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PROCESSING,
    MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.IN_TRANSIT,
    MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.APPROVED,
    MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.SCHEDULED,
  ];
  return inProgressStatuses.includes(status);
}

export function marketingaffiliateCanTransitionPayout(
  currentStatus: MarketingAffiliatePayoutStatusType,
  targetStatus: MarketingAffiliatePayoutStatusType
): boolean {
  const validTransitions: Record<
    MarketingAffiliatePayoutStatusType,
    MarketingAffiliatePayoutStatusType[]
  > = {
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PENDING]: [
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.APPROVED,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.REJECTED,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.APPROVED]: [
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.SCHEDULED,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.SCHEDULED]: [
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PROCESSING,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PROCESSING]: [
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.IN_TRANSIT,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.COMPLETED,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.FAILED,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.ON_HOLD,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.IN_TRANSIT]: [
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.DELIVERED,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.RETURNED,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.FAILED,
    ],
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.COMPLETED]: [
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.REVERSED,
    ],
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.DELIVERED]: [
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.COMPLETED,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.RETURNED,
    ],
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PARTIAL]: [
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.COMPLETED,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.ON_HOLD]: [
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PROCESSING,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.REJECTED]: [
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PENDING,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.FAILED]: [
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PENDING,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.CANCELLED]: [],
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.REVERSED]: [
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PENDING,
    ],
    [MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.RETURNED]: [
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.PENDING,
      MARKETINGAFFILIATE_PAYOUT_STATUS.STATUSES.CANCELLED,
    ],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
