/**
 * Loyalty Status Constants
 * Status definitions for loyalty lifecycle
 */

export const MARKETINGLOYALTY_STATUS = {
  // Loyalty Statuses
  STATUSES: {
    PENDING_ACTIVATION: 'pending_activation',
    ACTIVE: 'active',
    REINSTATED: 'reinstated',
    INACTIVE: 'inactive',
    SUSPENDED: 'suspended',
    TERMINATED: 'terminated',
    EXPIRED: 'expired',
    DORMANT: 'dormant',
    FROZEN: 'frozen',
    UNDER_REVIEW: 'under_review',
    PENDING_UPGRADE: 'pending_upgrade',
    PENDING_DOWNGRADE: 'pending_downgrade',
    PENDING_VERIFICATION: 'pending_verification',
    PENDING_APPROVAL: 'pending_approval',
    ARCHIVED: 'archived',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    PENDING_ACTIVATION: '#F59E0B',
    ACTIVE: '#10B981',
    REINSTATED: '#10B981',
    INACTIVE: '#6B7280',
    SUSPENDED: '#EF4444',
    TERMINATED: '#6B7280',
    EXPIRED: '#6B7280',
    DORMANT: '#F59E0B',
    FROZEN: '#F59E0B',
    UNDER_REVIEW: '#8B5CF6',
    PENDING_UPGRADE: '#3B82F6',
    PENDING_DOWNGRADE: '#F59E0B',
    PENDING_VERIFICATION: '#8B5CF6',
    PENDING_APPROVAL: '#F59E0B',
    ARCHIVED: '#6B7280',
  } as const,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    SUSPENDED: 'suspended',
    TERMINATED: 'terminated',
    ARCHIVED: 'archived',
  } as const,

  // Status Priority Order
  ORDER: {
    PENDING_ACTIVATION: 0,
    PENDING_APPROVAL: 1,
    PENDING_VERIFICATION: 2,
    PENDING_UPGRADE: 3,
    PENDING_DOWNGRADE: 4,
    UNDER_REVIEW: 5,
    ACTIVE: 6,
    REINSTATED: 7,
    DORMANT: 8,
    FROZEN: 9,
    INACTIVE: 10,
    SUSPENDED: 11,
    EXPIRED: 12,
    TERMINATED: 13,
    ARCHIVED: 14,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    PENDING_ACTIVATION_TO_ACTIVE: 'pending_activation_to_active',
    PENDING_ACTIVATION_TO_REJECTED: 'pending_activation_to_rejected',
    ACTIVE_TO_INACTIVE: 'active_to_inactive',
    ACTIVE_TO_SUSPENDED: 'active_to_suspended',
    ACTIVE_TO_DORMANT: 'active_to_dormant',
    ACTIVE_TO_FROZEN: 'active_to_frozen',
    ACTIVE_TO_PENDING_UPGRADE: 'active_to_pending_upgrade',
    ACTIVE_TO_PENDING_DOWNGRADE: 'active_to_pending_downgrade',
    ACTIVE_TO_UNDER_REVIEW: 'active_to_under_review',
    ACTIVE_TO_EXPIRED: 'active_to_expired',
    INACTIVE_TO_ACTIVE: 'inactive_to_active',
    INACTIVE_TO_REINSTATED: 'inactive_to_reinstated',
    SUSPENDED_TO_ACTIVE: 'suspended_to_active',
    SUSPENDED_TO_UNDER_REVIEW: 'suspended_to_under_review',
    SUSPENDED_TO_TERMINATED: 'suspended_to_terminated',
    DORMANT_TO_ACTIVE: 'dormant_to_active',
    DORMANT_TO_INACTIVE: 'dormant_to_inactive',
    FROZEN_TO_ACTIVE: 'frozen_to_active',
    FROZEN_TO_SUSPENDED: 'frozen_to_suspended',
    UNDER_REVIEW_TO_ACTIVE: 'under_review_to_active',
    UNDER_REVIEW_TO_SUSPENDED: 'under_review_to_suspended',
    UNDER_REVIEW_TO_TERMINATED: 'under_review_to_terminated',
    PENDING_UPGRADE_TO_ACTIVE: 'pending_upgrade_to_active',
    PENDING_UPGRADE_TO_CANCELLED: 'pending_upgrade_to_cancelled',
    PENDING_DOWNGRADE_TO_ACTIVE: 'pending_downgrade_to_active',
    PENDING_DOWNGRADE_TO_CANCELLED: 'pending_downgrade_to_cancelled',
    EXPIRED_TO_ARCHIVED: 'expired_to_archived',
    TERMINATED_TO_ARCHIVED: 'terminated_to_archived',
    REINSTATED_TO_ACTIVE: 'reinstated_to_active',
  } as const,
} as const;

// Loyalty Statuses
export type MarketingLoyaltyStatusType =
  (typeof MARKETINGLOYALTY_STATUS.STATUSES)[keyof typeof MARKETINGLOYALTY_STATUS.STATUSES];

// Status Colors
export type MarketingLoyaltyStatusColor =
  (typeof MARKETINGLOYALTY_STATUS.COLORS)[keyof typeof MARKETINGLOYALTY_STATUS.COLORS];

// Status Categories
export type MarketingLoyaltyStatusCategory =
  (typeof MARKETINGLOYALTY_STATUS.CATEGORIES)[keyof typeof MARKETINGLOYALTY_STATUS.CATEGORIES];

// Status Priority Order
export type MarketingLoyaltyStatusOrder =
  (typeof MARKETINGLOYALTY_STATUS.ORDER)[keyof typeof MARKETINGLOYALTY_STATUS.ORDER];

// Status Transitions
export type MarketingLoyaltyStatusTransition =
  (typeof MARKETINGLOYALTY_STATUS.TRANSITIONS)[keyof typeof MARKETINGLOYALTY_STATUS.TRANSITIONS];

// Utility Functions
export function marketingloyaltyGetStatusLabel(status: MarketingLoyaltyStatusType): string {
  const labels: Record<MarketingLoyaltyStatusType, string> = {
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_ACTIVATION]: 'Pending Activation',
    [MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE]: 'Active',
    [MARKETINGLOYALTY_STATUS.STATUSES.REINSTATED]: 'Reinstated',
    [MARKETINGLOYALTY_STATUS.STATUSES.INACTIVE]: 'Inactive',
    [MARKETINGLOYALTY_STATUS.STATUSES.SUSPENDED]: 'Suspended',
    [MARKETINGLOYALTY_STATUS.STATUSES.TERMINATED]: 'Terminated',
    [MARKETINGLOYALTY_STATUS.STATUSES.EXPIRED]: 'Expired',
    [MARKETINGLOYALTY_STATUS.STATUSES.DORMANT]: 'Dormant',
    [MARKETINGLOYALTY_STATUS.STATUSES.FROZEN]: 'Frozen',
    [MARKETINGLOYALTY_STATUS.STATUSES.UNDER_REVIEW]: 'Under Review',
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_UPGRADE]: 'Pending Upgrade',
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_DOWNGRADE]: 'Pending Downgrade',
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_VERIFICATION]: 'Pending Verification',
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_APPROVAL]: 'Pending Approval',
    [MARKETINGLOYALTY_STATUS.STATUSES.ARCHIVED]: 'Archived',
  };
  return labels[status] || 'Unknown Status';
}

export function marketingloyaltyGetStatusColor(
  status: MarketingLoyaltyStatusType
): MarketingLoyaltyStatusColor {
  const colors: Record<MarketingLoyaltyStatusType, MarketingLoyaltyStatusColor> = {
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_ACTIVATION]:
      MARKETINGLOYALTY_STATUS.COLORS.PENDING_ACTIVATION,
    [MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE]: MARKETINGLOYALTY_STATUS.COLORS.ACTIVE,
    [MARKETINGLOYALTY_STATUS.STATUSES.REINSTATED]: MARKETINGLOYALTY_STATUS.COLORS.REINSTATED,
    [MARKETINGLOYALTY_STATUS.STATUSES.INACTIVE]: MARKETINGLOYALTY_STATUS.COLORS.INACTIVE,
    [MARKETINGLOYALTY_STATUS.STATUSES.SUSPENDED]: MARKETINGLOYALTY_STATUS.COLORS.SUSPENDED,
    [MARKETINGLOYALTY_STATUS.STATUSES.TERMINATED]: MARKETINGLOYALTY_STATUS.COLORS.TERMINATED,
    [MARKETINGLOYALTY_STATUS.STATUSES.EXPIRED]: MARKETINGLOYALTY_STATUS.COLORS.EXPIRED,
    [MARKETINGLOYALTY_STATUS.STATUSES.DORMANT]: MARKETINGLOYALTY_STATUS.COLORS.DORMANT,
    [MARKETINGLOYALTY_STATUS.STATUSES.FROZEN]: MARKETINGLOYALTY_STATUS.COLORS.FROZEN,
    [MARKETINGLOYALTY_STATUS.STATUSES.UNDER_REVIEW]: MARKETINGLOYALTY_STATUS.COLORS.UNDER_REVIEW,
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_UPGRADE]:
      MARKETINGLOYALTY_STATUS.COLORS.PENDING_UPGRADE,
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_DOWNGRADE]:
      MARKETINGLOYALTY_STATUS.COLORS.PENDING_DOWNGRADE,
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_VERIFICATION]:
      MARKETINGLOYALTY_STATUS.COLORS.PENDING_VERIFICATION,
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_APPROVAL]:
      MARKETINGLOYALTY_STATUS.COLORS.PENDING_APPROVAL,
    [MARKETINGLOYALTY_STATUS.STATUSES.ARCHIVED]: MARKETINGLOYALTY_STATUS.COLORS.ARCHIVED,
  };
  return colors[status] || MARKETINGLOYALTY_STATUS.COLORS.PENDING_ACTIVATION;
}

export function marketingloyaltyGetStatusCategory(
  status: MarketingLoyaltyStatusType
): MarketingLoyaltyStatusCategory {
  const categories: Record<MarketingLoyaltyStatusType, MarketingLoyaltyStatusCategory> = {
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_ACTIVATION]:
      MARKETINGLOYALTY_STATUS.CATEGORIES.PENDING,
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_UPGRADE]: MARKETINGLOYALTY_STATUS.CATEGORIES.PENDING,
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_DOWNGRADE]:
      MARKETINGLOYALTY_STATUS.CATEGORIES.PENDING,
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_VERIFICATION]:
      MARKETINGLOYALTY_STATUS.CATEGORIES.PENDING,
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_APPROVAL]: MARKETINGLOYALTY_STATUS.CATEGORIES.PENDING,
    [MARKETINGLOYALTY_STATUS.STATUSES.UNDER_REVIEW]: MARKETINGLOYALTY_STATUS.CATEGORIES.PENDING,
    [MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE]: MARKETINGLOYALTY_STATUS.CATEGORIES.ACTIVE,
    [MARKETINGLOYALTY_STATUS.STATUSES.REINSTATED]: MARKETINGLOYALTY_STATUS.CATEGORIES.ACTIVE,
    [MARKETINGLOYALTY_STATUS.STATUSES.INACTIVE]: MARKETINGLOYALTY_STATUS.CATEGORIES.INACTIVE,
    [MARKETINGLOYALTY_STATUS.STATUSES.DORMANT]: MARKETINGLOYALTY_STATUS.CATEGORIES.INACTIVE,
    [MARKETINGLOYALTY_STATUS.STATUSES.FROZEN]: MARKETINGLOYALTY_STATUS.CATEGORIES.INACTIVE,
    [MARKETINGLOYALTY_STATUS.STATUSES.SUSPENDED]: MARKETINGLOYALTY_STATUS.CATEGORIES.SUSPENDED,
    [MARKETINGLOYALTY_STATUS.STATUSES.TERMINATED]: MARKETINGLOYALTY_STATUS.CATEGORIES.TERMINATED,
    [MARKETINGLOYALTY_STATUS.STATUSES.EXPIRED]: MARKETINGLOYALTY_STATUS.CATEGORIES.TERMINATED,
    [MARKETINGLOYALTY_STATUS.STATUSES.ARCHIVED]: MARKETINGLOYALTY_STATUS.CATEGORIES.ARCHIVED,
  };
  return categories[status] || MARKETINGLOYALTY_STATUS.CATEGORIES.PENDING;
}

export function marketingloyaltyIsActiveStatus(status: MarketingLoyaltyStatusType): boolean {
  const activeStatuses: MarketingLoyaltyStatusType[] = [
    MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE,
    MARKETINGLOYALTY_STATUS.STATUSES.REINSTATED,
  ];
  return activeStatuses.includes(status);
}

export function marketingloyaltyIsPendingStatus(status: MarketingLoyaltyStatusType): boolean {
  const pendingStatuses: MarketingLoyaltyStatusType[] = [
    MARKETINGLOYALTY_STATUS.STATUSES.PENDING_ACTIVATION,
    MARKETINGLOYALTY_STATUS.STATUSES.PENDING_UPGRADE,
    MARKETINGLOYALTY_STATUS.STATUSES.PENDING_DOWNGRADE,
    MARKETINGLOYALTY_STATUS.STATUSES.PENDING_VERIFICATION,
    MARKETINGLOYALTY_STATUS.STATUSES.PENDING_APPROVAL,
    MARKETINGLOYALTY_STATUS.STATUSES.UNDER_REVIEW,
  ];
  return pendingStatuses.includes(status);
}

export function marketingloyaltyIsTerminatedStatus(status: MarketingLoyaltyStatusType): boolean {
  const terminatedStatuses: MarketingLoyaltyStatusType[] = [
    MARKETINGLOYALTY_STATUS.STATUSES.TERMINATED,
    MARKETINGLOYALTY_STATUS.STATUSES.EXPIRED,
    MARKETINGLOYALTY_STATUS.STATUSES.ARCHIVED,
  ];
  return terminatedStatuses.includes(status);
}

export function marketingloyaltyCanTransition(
  currentStatus: MarketingLoyaltyStatusType,
  targetStatus: MarketingLoyaltyStatusType
): boolean {
  const validTransitions: Record<MarketingLoyaltyStatusType, MarketingLoyaltyStatusType[]> = {
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_ACTIVATION]: [
      MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE,
      MARKETINGLOYALTY_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_APPROVAL]: [
      MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE,
      MARKETINGLOYALTY_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_VERIFICATION]: [
      MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE,
      MARKETINGLOYALTY_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE]: [
      MARKETINGLOYALTY_STATUS.STATUSES.INACTIVE,
      MARKETINGLOYALTY_STATUS.STATUSES.SUSPENDED,
      MARKETINGLOYALTY_STATUS.STATUSES.DORMANT,
      MARKETINGLOYALTY_STATUS.STATUSES.FROZEN,
      MARKETINGLOYALTY_STATUS.STATUSES.PENDING_UPGRADE,
      MARKETINGLOYALTY_STATUS.STATUSES.PENDING_DOWNGRADE,
      MARKETINGLOYALTY_STATUS.STATUSES.UNDER_REVIEW,
      MARKETINGLOYALTY_STATUS.STATUSES.EXPIRED,
    ],
    [MARKETINGLOYALTY_STATUS.STATUSES.REINSTATED]: [MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE],
    [MARKETINGLOYALTY_STATUS.STATUSES.INACTIVE]: [
      MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE,
      MARKETINGLOYALTY_STATUS.STATUSES.REINSTATED,
      MARKETINGLOYALTY_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGLOYALTY_STATUS.STATUSES.DORMANT]: [
      MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE,
      MARKETINGLOYALTY_STATUS.STATUSES.INACTIVE,
    ],
    [MARKETINGLOYALTY_STATUS.STATUSES.FROZEN]: [
      MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE,
      MARKETINGLOYALTY_STATUS.STATUSES.SUSPENDED,
    ],
    [MARKETINGLOYALTY_STATUS.STATUSES.SUSPENDED]: [
      MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE,
      MARKETINGLOYALTY_STATUS.STATUSES.UNDER_REVIEW,
      MARKETINGLOYALTY_STATUS.STATUSES.TERMINATED,
    ],
    [MARKETINGLOYALTY_STATUS.STATUSES.UNDER_REVIEW]: [
      MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE,
      MARKETINGLOYALTY_STATUS.STATUSES.SUSPENDED,
      MARKETINGLOYALTY_STATUS.STATUSES.TERMINATED,
    ],
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_UPGRADE]: [
      MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE,
      MARKETINGLOYALTY_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGLOYALTY_STATUS.STATUSES.PENDING_DOWNGRADE]: [
      MARKETINGLOYALTY_STATUS.STATUSES.ACTIVE,
      MARKETINGLOYALTY_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGLOYALTY_STATUS.STATUSES.EXPIRED]: [MARKETINGLOYALTY_STATUS.STATUSES.ARCHIVED],
    [MARKETINGLOYALTY_STATUS.STATUSES.TERMINATED]: [MARKETINGLOYALTY_STATUS.STATUSES.ARCHIVED],
    [MARKETINGLOYALTY_STATUS.STATUSES.ARCHIVED]: [],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
