/**
 * AI Forecast Status Constants
 * Status tracking for forecasting operations
 */

// First define the status types
export const AI_FORECAST_STATUS_TYPES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Processing States
  INITIALIZING: 'initializing',
  PROCESSING: 'processing',
  ANALYZING: 'analyzing',
  GENERATING: 'generating',
  VALIDATING: 'validating',

  // Intermediate States
  ANALYZED: 'analyzed',
  GENERATED: 'generated',
  VALIDATED: 'validated',
  OPTIMIZED: 'optimized',

  // Storage States
  STORING: 'storing',
  STORED: 'stored',
  CACHING: 'caching',
  CACHED: 'cached',

  // Terminal States
  COMPLETED: 'completed',
  FAILED: 'failed',
  EXPIRED: 'expired',
  ARCHIVED: 'archived',
} as const;

export type AIForecastStatusType =
  (typeof AI_FORECAST_STATUS_TYPES)[keyof typeof AI_FORECAST_STATUS_TYPES];

export const AI_FORECAST_STATUS = {
  // Status Types
  STATUSES: AI_FORECAST_STATUS_TYPES,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CACHED: 'cached',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_FORECAST_STATUS_TYPES.CREATED]: '#gray',
    [AI_FORECAST_STATUS_TYPES.QUEUED]: '#gray',
    [AI_FORECAST_STATUS_TYPES.PENDING]: '#yellow',
    [AI_FORECAST_STATUS_TYPES.INITIALIZING]: '#blue',
    [AI_FORECAST_STATUS_TYPES.PROCESSING]: '#blue',
    [AI_FORECAST_STATUS_TYPES.ANALYZING]: '#blue',
    [AI_FORECAST_STATUS_TYPES.GENERATING]: '#blue',
    [AI_FORECAST_STATUS_TYPES.VALIDATING]: '#purple',
    [AI_FORECAST_STATUS_TYPES.ANALYZED]: '#green',
    [AI_FORECAST_STATUS_TYPES.GENERATED]: '#green',
    [AI_FORECAST_STATUS_TYPES.VALIDATED]: '#green',
    [AI_FORECAST_STATUS_TYPES.OPTIMIZED]: '#green',
    [AI_FORECAST_STATUS_TYPES.STORING]: '#orange',
    [AI_FORECAST_STATUS_TYPES.STORED]: '#green',
    [AI_FORECAST_STATUS_TYPES.CACHING]: '#orange',
    [AI_FORECAST_STATUS_TYPES.CACHED]: '#green',
    [AI_FORECAST_STATUS_TYPES.COMPLETED]: '#green',
    [AI_FORECAST_STATUS_TYPES.FAILED]: '#red',
    [AI_FORECAST_STATUS_TYPES.EXPIRED]: '#gray',
    [AI_FORECAST_STATUS_TYPES.ARCHIVED]: '#gray',
  } as const,
} as const;

export type AIForecastStatusCategory =
  (typeof AI_FORECAST_STATUS.CATEGORIES)[keyof typeof AI_FORECAST_STATUS.CATEGORIES];
export type AIForecastStatusSeverity =
  (typeof AI_FORECAST_STATUS.SEVERITY)[keyof typeof AI_FORECAST_STATUS.SEVERITY];
export type AIForecastStatusColor =
  (typeof AI_FORECAST_STATUS.COLORS)[keyof typeof AI_FORECAST_STATUS.COLORS];

export function getAiForecastStatusLabel(status: AIForecastStatusType): string {
  const labels: Record<AIForecastStatusType, string> = {
    [AI_FORECAST_STATUS_TYPES.CREATED]: 'Created',
    [AI_FORECAST_STATUS_TYPES.QUEUED]: 'Queued',
    [AI_FORECAST_STATUS_TYPES.PENDING]: 'Pending',
    [AI_FORECAST_STATUS_TYPES.INITIALIZING]: 'Initializing',
    [AI_FORECAST_STATUS_TYPES.PROCESSING]: 'Processing',
    [AI_FORECAST_STATUS_TYPES.ANALYZING]: 'Analyzing',
    [AI_FORECAST_STATUS_TYPES.GENERATING]: 'Generating',
    [AI_FORECAST_STATUS_TYPES.VALIDATING]: 'Validating',
    [AI_FORECAST_STATUS_TYPES.ANALYZED]: 'Analyzed',
    [AI_FORECAST_STATUS_TYPES.GENERATED]: 'Generated',
    [AI_FORECAST_STATUS_TYPES.VALIDATED]: 'Validated',
    [AI_FORECAST_STATUS_TYPES.OPTIMIZED]: 'Optimized',
    [AI_FORECAST_STATUS_TYPES.STORING]: 'Storing',
    [AI_FORECAST_STATUS_TYPES.STORED]: 'Stored',
    [AI_FORECAST_STATUS_TYPES.CACHING]: 'Caching',
    [AI_FORECAST_STATUS_TYPES.CACHED]: 'Cached',
    [AI_FORECAST_STATUS_TYPES.COMPLETED]: 'Completed',
    [AI_FORECAST_STATUS_TYPES.FAILED]: 'Failed',
    [AI_FORECAST_STATUS_TYPES.EXPIRED]: 'Expired',
    [AI_FORECAST_STATUS_TYPES.ARCHIVED]: 'Archived',
  };
  return labels[status] || 'Unknown';
}

export function getAiForecastStatusCategory(
  status: AIForecastStatusType
): AIForecastStatusCategory {
  const categories: Record<AIForecastStatusType, AIForecastStatusCategory> = {
    [AI_FORECAST_STATUS_TYPES.CREATED]: AI_FORECAST_STATUS.CATEGORIES.PENDING,
    [AI_FORECAST_STATUS_TYPES.QUEUED]: AI_FORECAST_STATUS.CATEGORIES.PENDING,
    [AI_FORECAST_STATUS_TYPES.PENDING]: AI_FORECAST_STATUS.CATEGORIES.PENDING,
    [AI_FORECAST_STATUS_TYPES.INITIALIZING]: AI_FORECAST_STATUS.CATEGORIES.PROCESSING,
    [AI_FORECAST_STATUS_TYPES.PROCESSING]: AI_FORECAST_STATUS.CATEGORIES.PROCESSING,
    [AI_FORECAST_STATUS_TYPES.ANALYZING]: AI_FORECAST_STATUS.CATEGORIES.PROCESSING,
    [AI_FORECAST_STATUS_TYPES.GENERATING]: AI_FORECAST_STATUS.CATEGORIES.PROCESSING,
    [AI_FORECAST_STATUS_TYPES.VALIDATING]: AI_FORECAST_STATUS.CATEGORIES.PROCESSING,
    [AI_FORECAST_STATUS_TYPES.ANALYZED]: AI_FORECAST_STATUS.CATEGORIES.PROCESSING,
    [AI_FORECAST_STATUS_TYPES.GENERATED]: AI_FORECAST_STATUS.CATEGORIES.PROCESSING,
    [AI_FORECAST_STATUS_TYPES.VALIDATED]: AI_FORECAST_STATUS.CATEGORIES.PROCESSING,
    [AI_FORECAST_STATUS_TYPES.OPTIMIZED]: AI_FORECAST_STATUS.CATEGORIES.PROCESSING,
    [AI_FORECAST_STATUS_TYPES.STORING]: AI_FORECAST_STATUS.CATEGORIES.PROCESSING,
    [AI_FORECAST_STATUS_TYPES.STORED]: AI_FORECAST_STATUS.CATEGORIES.COMPLETED,
    [AI_FORECAST_STATUS_TYPES.CACHING]: AI_FORECAST_STATUS.CATEGORIES.PROCESSING,
    [AI_FORECAST_STATUS_TYPES.CACHED]: AI_FORECAST_STATUS.CATEGORIES.CACHED,
    [AI_FORECAST_STATUS_TYPES.COMPLETED]: AI_FORECAST_STATUS.CATEGORIES.COMPLETED,
    [AI_FORECAST_STATUS_TYPES.FAILED]: AI_FORECAST_STATUS.CATEGORIES.FAILED,
    [AI_FORECAST_STATUS_TYPES.EXPIRED]: AI_FORECAST_STATUS.CATEGORIES.FAILED,
    [AI_FORECAST_STATUS_TYPES.ARCHIVED]: AI_FORECAST_STATUS.CATEGORIES.COMPLETED,
  };
  return categories[status] || AI_FORECAST_STATUS.CATEGORIES.PENDING;
}

export function getAiForecastStatusSeverity(
  status: AIForecastStatusType
): AIForecastStatusSeverity {
  const severities: Record<AIForecastStatusType, AIForecastStatusSeverity> = {
    [AI_FORECAST_STATUS_TYPES.CREATED]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.QUEUED]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.PENDING]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.INITIALIZING]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.PROCESSING]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.ANALYZING]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.GENERATING]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.VALIDATING]: AI_FORECAST_STATUS.SEVERITY.WARNING,
    [AI_FORECAST_STATUS_TYPES.ANALYZED]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.GENERATED]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.VALIDATED]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.OPTIMIZED]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.STORING]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.STORED]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.CACHING]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.CACHED]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.COMPLETED]: AI_FORECAST_STATUS.SEVERITY.INFO,
    [AI_FORECAST_STATUS_TYPES.FAILED]: AI_FORECAST_STATUS.SEVERITY.ERROR,
    [AI_FORECAST_STATUS_TYPES.EXPIRED]: AI_FORECAST_STATUS.SEVERITY.WARNING,
    [AI_FORECAST_STATUS_TYPES.ARCHIVED]: AI_FORECAST_STATUS.SEVERITY.INFO,
  };
  return severities[status] || AI_FORECAST_STATUS.SEVERITY.INFO;
}

export function getAiForecastStatusColor(status: AIForecastStatusType): AIForecastStatusColor {
  return AI_FORECAST_STATUS.COLORS[status] || '#gray';
}

export function isAiForecastActiveStatus(status: AIForecastStatusType): boolean {
  const activeStatuses: AIForecastStatusType[] = [
    AI_FORECAST_STATUS_TYPES.CREATED,
    AI_FORECAST_STATUS_TYPES.QUEUED,
    AI_FORECAST_STATUS_TYPES.PENDING,
    AI_FORECAST_STATUS_TYPES.INITIALIZING,
    AI_FORECAST_STATUS_TYPES.PROCESSING,
    AI_FORECAST_STATUS_TYPES.ANALYZING,
    AI_FORECAST_STATUS_TYPES.GENERATING,
    AI_FORECAST_STATUS_TYPES.VALIDATING,
    AI_FORECAST_STATUS_TYPES.ANALYZED,
    AI_FORECAST_STATUS_TYPES.GENERATED,
    AI_FORECAST_STATUS_TYPES.VALIDATED,
    AI_FORECAST_STATUS_TYPES.OPTIMIZED,
    AI_FORECAST_STATUS_TYPES.STORING,
    AI_FORECAST_STATUS_TYPES.CACHING,
  ];
  return activeStatuses.includes(status);
}

export function isAiForecastCompleted(status: AIForecastStatusType): boolean {
  const completedStatuses: AIForecastStatusType[] = [
    AI_FORECAST_STATUS_TYPES.COMPLETED,
    AI_FORECAST_STATUS_TYPES.STORED,
    AI_FORECAST_STATUS_TYPES.CACHED,
    AI_FORECAST_STATUS_TYPES.ARCHIVED,
  ];
  return completedStatuses.includes(status);
}

export function isAiForecastFailedStatus(status: AIForecastStatusType): boolean {
  const failedStatuses: AIForecastStatusType[] = [
    AI_FORECAST_STATUS_TYPES.FAILED,
    AI_FORECAST_STATUS_TYPES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}

export function getAiForecastStatusProgress(status: AIForecastStatusType): number {
  const progress: Record<AIForecastStatusType, number> = {
    [AI_FORECAST_STATUS_TYPES.CREATED]: 0,
    [AI_FORECAST_STATUS_TYPES.QUEUED]: 5,
    [AI_FORECAST_STATUS_TYPES.PENDING]: 10,
    [AI_FORECAST_STATUS_TYPES.INITIALIZING]: 20,
    [AI_FORECAST_STATUS_TYPES.PROCESSING]: 35,
    [AI_FORECAST_STATUS_TYPES.ANALYZING]: 50,
    [AI_FORECAST_STATUS_TYPES.GENERATING]: 65,
    [AI_FORECAST_STATUS_TYPES.VALIDATING]: 75,
    [AI_FORECAST_STATUS_TYPES.ANALYZED]: 55,
    [AI_FORECAST_STATUS_TYPES.GENERATED]: 70,
    [AI_FORECAST_STATUS_TYPES.VALIDATED]: 80,
    [AI_FORECAST_STATUS_TYPES.OPTIMIZED]: 85,
    [AI_FORECAST_STATUS_TYPES.STORING]: 88,
    [AI_FORECAST_STATUS_TYPES.STORED]: 92,
    [AI_FORECAST_STATUS_TYPES.CACHING]: 94,
    [AI_FORECAST_STATUS_TYPES.CACHED]: 96,
    [AI_FORECAST_STATUS_TYPES.COMPLETED]: 100,
    [AI_FORECAST_STATUS_TYPES.FAILED]: 0,
    [AI_FORECAST_STATUS_TYPES.EXPIRED]: 0,
    [AI_FORECAST_STATUS_TYPES.ARCHIVED]: 100,
  };
  return progress[status] || 0;
}
