/**
 * Email Marketing Status Constants
 * Status definitions for email lifecycle
 */

export const MARKETINGEMAIL_STATUS = {
  // Email Statuses
  STATUSES: {
    DRAFT: 'draft',
    PENDING_APPROVAL: 'pending_approval',
    APPROVED: 'approved',
    REJECTED: 'rejected',
    SCHEDULED: 'scheduled',
    QUEUED: 'queued',
    PROCESSING: 'processing',
    SENT: 'sent',
    DELIVERED: 'delivered',
    FAILED: 'failed',
    BOUNCED: 'bounced',
    OPENED: 'opened',
    CLICKED: 'clicked',
    UNSUBSCRIBED: 'unsubscribed',
    SPAM: 'spam',
    COMPLAINED: 'complained',
    DEFERRED: 'deferred',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    PAUSED: 'paused',
    EXPIRED: 'expired',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    DRAFT: '#6B7280',
    PENDING_APPROVAL: '#F59E0B',
    APPROVED: '#10B981',
    REJECTED: '#EF4444',
    SCHEDULED: '#3B82F6',
    QUEUED: '#8B5CF6',
    PROCESSING: '#3B82F6',
    SENT: '#10B981',
    DELIVERED: '#10B981',
    FAILED: '#EF4444',
    BOUNCED: '#EF4444',
    OPENED: '#10B981',
    CLICKED: '#10B981',
    UNSUBSCRIBED: '#6B7280',
    SPAM: '#EF4444',
    COMPLAINED: '#EF4444',
    DEFERRED: '#F59E0B',
    CANCELLED: '#6B7280',
    ARCHIVED: '#6B7280',
    PAUSED: '#F59E0B',
    EXPIRED: '#6B7280',
  } as const,

  // Status Categories
  CATEGORIES: {
    DRAFT: 'draft',
    PENDING: 'pending',
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    ENGAGED: 'engaged',
  } as const,

  // Status Priority Order
  ORDER: {
    DRAFT: 0,
    PENDING_APPROVAL: 1,
    APPROVED: 2,
    REJECTED: 3,
    SCHEDULED: 4,
    QUEUED: 5,
    PROCESSING: 6,
    SENT: 7,
    DELIVERED: 8,
    OPENED: 9,
    CLICKED: 10,
    UNSUBSCRIBED: 11,
    SPAM: 12,
    COMPLAINED: 13,
    BOUNCED: 14,
    DEFERRED: 15,
    FAILED: 16,
    PAUSED: 17,
    EXPIRED: 18,
    CANCELLED: 19,
    ARCHIVED: 20,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    DRAFT_TO_PENDING: 'draft_to_pending',
    DRAFT_TO_CANCELLED: 'draft_to_cancelled',
    DRAFT_TO_ARCHIVED: 'draft_to_archived',
    PENDING_TO_APPROVED: 'pending_to_approved',
    PENDING_TO_REJECTED: 'pending_to_rejected',
    PENDING_TO_CANCELLED: 'pending_to_cancelled',
    APPROVED_TO_SCHEDULED: 'approved_to_scheduled',
    APPROVED_TO_REJECTED: 'approved_to_rejected',
    SCHEDULED_TO_QUEUED: 'scheduled_to_queued',
    SCHEDULED_TO_CANCELLED: 'scheduled_to_cancelled',
    QUEUED_TO_PROCESSING: 'queued_to_processing',
    QUEUED_TO_CANCELLED: 'queued_to_cancelled',
    PROCESSING_TO_SENT: 'processing_to_sent',
    PROCESSING_TO_FAILED: 'processing_to_failed',
    PROCESSING_TO_CANCELLED: 'processing_to_cancelled',
    SENT_TO_DELIVERED: 'sent_to_delivered',
    SENT_TO_BOUNCED: 'sent_to_bounced',
    SENT_TO_FAILED: 'sent_to_failed',
    SENT_TO_DEFERRED: 'sent_to_deferred',
    DELIVERED_TO_OPENED: 'delivered_to_opened',
    DELIVERED_TO_UNSUBSCRIBED: 'delivered_to_unsubscribed',
    DELIVERED_TO_SPAM: 'delivered_to_spam',
    DELIVERED_TO_COMPLAINED: 'delivered_to_complained',
    OPENED_TO_CLICKED: 'opened_to_clicked',
    OPENED_TO_UNSUBSCRIBED: 'opened_to_unsubscribed',
    CLICKED_TO_UNSUBSCRIBED: 'clicked_to_unsubscribed',
    CLICKED_TO_COMPLAINED: 'clicked_to_complained',
    BOUNCED_TO_ARCHIVED: 'bounced_to_archived',
    FAILED_TO_ARCHIVED: 'failed_to_archived',
    DEFERRED_TO_SENT: 'deferred_to_sent',
    DEFERRED_TO_FAILED: 'deferred_to_failed',
    DEFERRED_TO_CANCELLED: 'deferred_to_cancelled',
    UNSUBSCRIBED_TO_ARCHIVED: 'unsubscribed_to_archived',
    SPAM_TO_ARCHIVED: 'spam_to_archived',
    COMPLAINED_TO_ARCHIVED: 'complained_to_archived',
    PAUSED_TO_PROCESSING: 'paused_to_processing',
    PAUSED_TO_CANCELLED: 'paused_to_cancelled',
    EXPIRED_TO_ARCHIVED: 'expired_to_archived',
    REJECTED_TO_DRAFT: 'rejected_to_draft',
    REJECTED_TO_ARCHIVED: 'rejected_to_archived',
    CANCELLED_TO_ARCHIVED: 'cancelled_to_archived',
  } as const,
} as const;

// Email Statuses
export type MarketingEmailStatusType =
  (typeof MARKETINGEMAIL_STATUS.STATUSES)[keyof typeof MARKETINGEMAIL_STATUS.STATUSES];

// Status Colors
export type MarketingEmailStatusColor =
  (typeof MARKETINGEMAIL_STATUS.COLORS)[keyof typeof MARKETINGEMAIL_STATUS.COLORS];

// Status Categories
export type MarketingEmailStatusCategory =
  (typeof MARKETINGEMAIL_STATUS.CATEGORIES)[keyof typeof MARKETINGEMAIL_STATUS.CATEGORIES];

// Status Priority Order
export type MarketingEmailStatusOrder =
  (typeof MARKETINGEMAIL_STATUS.ORDER)[keyof typeof MARKETINGEMAIL_STATUS.ORDER];

// Status Transitions
export type MarketingEmailStatusTransition =
  (typeof MARKETINGEMAIL_STATUS.TRANSITIONS)[keyof typeof MARKETINGEMAIL_STATUS.TRANSITIONS];

// Utility Functions
export function marketingemailGetStatusLabel(status: MarketingEmailStatusType): string {
  const labels: Record<MarketingEmailStatusType, string> = {
    [MARKETINGEMAIL_STATUS.STATUSES.DRAFT]: 'Draft',
    [MARKETINGEMAIL_STATUS.STATUSES.PENDING_APPROVAL]: 'Pending Approval',
    [MARKETINGEMAIL_STATUS.STATUSES.APPROVED]: 'Approved',
    [MARKETINGEMAIL_STATUS.STATUSES.REJECTED]: 'Rejected',
    [MARKETINGEMAIL_STATUS.STATUSES.SCHEDULED]: 'Scheduled',
    [MARKETINGEMAIL_STATUS.STATUSES.QUEUED]: 'Queued',
    [MARKETINGEMAIL_STATUS.STATUSES.PROCESSING]: 'Processing',
    [MARKETINGEMAIL_STATUS.STATUSES.SENT]: 'Sent',
    [MARKETINGEMAIL_STATUS.STATUSES.DELIVERED]: 'Delivered',
    [MARKETINGEMAIL_STATUS.STATUSES.FAILED]: 'Failed',
    [MARKETINGEMAIL_STATUS.STATUSES.BOUNCED]: 'Bounced',
    [MARKETINGEMAIL_STATUS.STATUSES.OPENED]: 'Opened',
    [MARKETINGEMAIL_STATUS.STATUSES.CLICKED]: 'Clicked',
    [MARKETINGEMAIL_STATUS.STATUSES.UNSUBSCRIBED]: 'Unsubscribed',
    [MARKETINGEMAIL_STATUS.STATUSES.SPAM]: 'Spam',
    [MARKETINGEMAIL_STATUS.STATUSES.COMPLAINED]: 'Complained',
    [MARKETINGEMAIL_STATUS.STATUSES.DEFERRED]: 'Deferred',
    [MARKETINGEMAIL_STATUS.STATUSES.CANCELLED]: 'Cancelled',
    [MARKETINGEMAIL_STATUS.STATUSES.ARCHIVED]: 'Archived',
    [MARKETINGEMAIL_STATUS.STATUSES.PAUSED]: 'Paused',
    [MARKETINGEMAIL_STATUS.STATUSES.EXPIRED]: 'Expired',
  };
  return labels[status] || 'Unknown Status';
}

export function marketingemailGetStatusColor(
  status: MarketingEmailStatusType
): MarketingEmailStatusColor {
  const colors: Record<MarketingEmailStatusType, MarketingEmailStatusColor> = {
    [MARKETINGEMAIL_STATUS.STATUSES.DRAFT]: MARKETINGEMAIL_STATUS.COLORS.DRAFT,
    [MARKETINGEMAIL_STATUS.STATUSES.PENDING_APPROVAL]:
      MARKETINGEMAIL_STATUS.COLORS.PENDING_APPROVAL,
    [MARKETINGEMAIL_STATUS.STATUSES.APPROVED]: MARKETINGEMAIL_STATUS.COLORS.APPROVED,
    [MARKETINGEMAIL_STATUS.STATUSES.REJECTED]: MARKETINGEMAIL_STATUS.COLORS.REJECTED,
    [MARKETINGEMAIL_STATUS.STATUSES.SCHEDULED]: MARKETINGEMAIL_STATUS.COLORS.SCHEDULED,
    [MARKETINGEMAIL_STATUS.STATUSES.QUEUED]: MARKETINGEMAIL_STATUS.COLORS.QUEUED,
    [MARKETINGEMAIL_STATUS.STATUSES.PROCESSING]: MARKETINGEMAIL_STATUS.COLORS.PROCESSING,
    [MARKETINGEMAIL_STATUS.STATUSES.SENT]: MARKETINGEMAIL_STATUS.COLORS.SENT,
    [MARKETINGEMAIL_STATUS.STATUSES.DELIVERED]: MARKETINGEMAIL_STATUS.COLORS.DELIVERED,
    [MARKETINGEMAIL_STATUS.STATUSES.FAILED]: MARKETINGEMAIL_STATUS.COLORS.FAILED,
    [MARKETINGEMAIL_STATUS.STATUSES.BOUNCED]: MARKETINGEMAIL_STATUS.COLORS.BOUNCED,
    [MARKETINGEMAIL_STATUS.STATUSES.OPENED]: MARKETINGEMAIL_STATUS.COLORS.OPENED,
    [MARKETINGEMAIL_STATUS.STATUSES.CLICKED]: MARKETINGEMAIL_STATUS.COLORS.CLICKED,
    [MARKETINGEMAIL_STATUS.STATUSES.UNSUBSCRIBED]: MARKETINGEMAIL_STATUS.COLORS.UNSUBSCRIBED,
    [MARKETINGEMAIL_STATUS.STATUSES.SPAM]: MARKETINGEMAIL_STATUS.COLORS.SPAM,
    [MARKETINGEMAIL_STATUS.STATUSES.COMPLAINED]: MARKETINGEMAIL_STATUS.COLORS.COMPLAINED,
    [MARKETINGEMAIL_STATUS.STATUSES.DEFERRED]: MARKETINGEMAIL_STATUS.COLORS.DEFERRED,
    [MARKETINGEMAIL_STATUS.STATUSES.CANCELLED]: MARKETINGEMAIL_STATUS.COLORS.CANCELLED,
    [MARKETINGEMAIL_STATUS.STATUSES.ARCHIVED]: MARKETINGEMAIL_STATUS.COLORS.ARCHIVED,
    [MARKETINGEMAIL_STATUS.STATUSES.PAUSED]: MARKETINGEMAIL_STATUS.COLORS.PAUSED,
    [MARKETINGEMAIL_STATUS.STATUSES.EXPIRED]: MARKETINGEMAIL_STATUS.COLORS.EXPIRED,
  };
  return colors[status] || MARKETINGEMAIL_STATUS.COLORS.DRAFT;
}

export function marketingemailGetStatusCategory(
  status: MarketingEmailStatusType
): MarketingEmailStatusCategory {
  const categories: Record<MarketingEmailStatusType, MarketingEmailStatusCategory> = {
    [MARKETINGEMAIL_STATUS.STATUSES.DRAFT]: MARKETINGEMAIL_STATUS.CATEGORIES.DRAFT,
    [MARKETINGEMAIL_STATUS.STATUSES.PENDING_APPROVAL]: MARKETINGEMAIL_STATUS.CATEGORIES.PENDING,
    [MARKETINGEMAIL_STATUS.STATUSES.APPROVED]: MARKETINGEMAIL_STATUS.CATEGORIES.PENDING,
    [MARKETINGEMAIL_STATUS.STATUSES.REJECTED]: MARKETINGEMAIL_STATUS.CATEGORIES.FAILED,
    [MARKETINGEMAIL_STATUS.STATUSES.SCHEDULED]: MARKETINGEMAIL_STATUS.CATEGORIES.PENDING,
    [MARKETINGEMAIL_STATUS.STATUSES.QUEUED]: MARKETINGEMAIL_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGEMAIL_STATUS.STATUSES.PROCESSING]: MARKETINGEMAIL_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGEMAIL_STATUS.STATUSES.SENT]: MARKETINGEMAIL_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGEMAIL_STATUS.STATUSES.DELIVERED]: MARKETINGEMAIL_STATUS.CATEGORIES.COMPLETED,
    [MARKETINGEMAIL_STATUS.STATUSES.OPENED]: MARKETINGEMAIL_STATUS.CATEGORIES.ENGAGED,
    [MARKETINGEMAIL_STATUS.STATUSES.CLICKED]: MARKETINGEMAIL_STATUS.CATEGORIES.ENGAGED,
    [MARKETINGEMAIL_STATUS.STATUSES.UNSUBSCRIBED]: MARKETINGEMAIL_STATUS.CATEGORIES.COMPLETED,
    [MARKETINGEMAIL_STATUS.STATUSES.SPAM]: MARKETINGEMAIL_STATUS.CATEGORIES.FAILED,
    [MARKETINGEMAIL_STATUS.STATUSES.COMPLAINED]: MARKETINGEMAIL_STATUS.CATEGORIES.FAILED,
    [MARKETINGEMAIL_STATUS.STATUSES.BOUNCED]: MARKETINGEMAIL_STATUS.CATEGORIES.FAILED,
    [MARKETINGEMAIL_STATUS.STATUSES.DEFERRED]: MARKETINGEMAIL_STATUS.CATEGORIES.IN_PROGRESS,
    [MARKETINGEMAIL_STATUS.STATUSES.FAILED]: MARKETINGEMAIL_STATUS.CATEGORIES.FAILED,
    [MARKETINGEMAIL_STATUS.STATUSES.PAUSED]: MARKETINGEMAIL_STATUS.CATEGORIES.PENDING,
    [MARKETINGEMAIL_STATUS.STATUSES.EXPIRED]: MARKETINGEMAIL_STATUS.CATEGORIES.FAILED,
    [MARKETINGEMAIL_STATUS.STATUSES.CANCELLED]: MARKETINGEMAIL_STATUS.CATEGORIES.CANCELLED,
    [MARKETINGEMAIL_STATUS.STATUSES.ARCHIVED]: MARKETINGEMAIL_STATUS.CATEGORIES.ARCHIVED,
  };
  return categories[status] || MARKETINGEMAIL_STATUS.CATEGORIES.DRAFT;
}

export function marketingemailIsDelivered(status: MarketingEmailStatusType): boolean {
  const deliveredStatuses: MarketingEmailStatusType[] = [
    MARKETINGEMAIL_STATUS.STATUSES.DELIVERED,
    MARKETINGEMAIL_STATUS.STATUSES.OPENED,
    MARKETINGEMAIL_STATUS.STATUSES.CLICKED,
    MARKETINGEMAIL_STATUS.STATUSES.UNSUBSCRIBED,
  ];
  return deliveredStatuses.includes(status);
}

export function marketingemailIsEngaged(status: MarketingEmailStatusType): boolean {
  const engagedStatuses: MarketingEmailStatusType[] = [
    MARKETINGEMAIL_STATUS.STATUSES.OPENED,
    MARKETINGEMAIL_STATUS.STATUSES.CLICKED,
  ];
  return engagedStatuses.includes(status);
}

export function marketingemailIsFailed(status: MarketingEmailStatusType): boolean {
  const failedStatuses: MarketingEmailStatusType[] = [
    MARKETINGEMAIL_STATUS.STATUSES.FAILED,
    MARKETINGEMAIL_STATUS.STATUSES.BOUNCED,
    MARKETINGEMAIL_STATUS.STATUSES.SPAM,
    MARKETINGEMAIL_STATUS.STATUSES.COMPLAINED,
    MARKETINGEMAIL_STATUS.STATUSES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}

export function marketingemailIsPending(status: MarketingEmailStatusType): boolean {
  const pendingStatuses: MarketingEmailStatusType[] = [
    MARKETINGEMAIL_STATUS.STATUSES.PENDING_APPROVAL,
    MARKETINGEMAIL_STATUS.STATUSES.APPROVED,
    MARKETINGEMAIL_STATUS.STATUSES.SCHEDULED,
    MARKETINGEMAIL_STATUS.STATUSES.QUEUED,
    MARKETINGEMAIL_STATUS.STATUSES.PROCESSING,
    MARKETINGEMAIL_STATUS.STATUSES.SENT,
    MARKETINGEMAIL_STATUS.STATUSES.DEFERRED,
  ];
  return pendingStatuses.includes(status);
}

export function marketingemailIsTerminal(status: MarketingEmailStatusType): boolean {
  const terminalStatuses: MarketingEmailStatusType[] = [
    MARKETINGEMAIL_STATUS.STATUSES.DELIVERED,
    MARKETINGEMAIL_STATUS.STATUSES.OPENED,
    MARKETINGEMAIL_STATUS.STATUSES.CLICKED,
    MARKETINGEMAIL_STATUS.STATUSES.UNSUBSCRIBED,
    MARKETINGEMAIL_STATUS.STATUSES.FAILED,
    MARKETINGEMAIL_STATUS.STATUSES.BOUNCED,
    MARKETINGEMAIL_STATUS.STATUSES.SPAM,
    MARKETINGEMAIL_STATUS.STATUSES.COMPLAINED,
    MARKETINGEMAIL_STATUS.STATUSES.ARCHIVED,
    MARKETINGEMAIL_STATUS.STATUSES.CANCELLED,
  ];
  return terminalStatuses.includes(status);
}

export function marketingemailCanTransition(
  currentStatus: MarketingEmailStatusType,
  targetStatus: MarketingEmailStatusType
): boolean {
  const validTransitions: Record<MarketingEmailStatusType, MarketingEmailStatusType[]> = {
    [MARKETINGEMAIL_STATUS.STATUSES.DRAFT]: [
      MARKETINGEMAIL_STATUS.STATUSES.PENDING_APPROVAL,
      MARKETINGEMAIL_STATUS.STATUSES.CANCELLED,
      MARKETINGEMAIL_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGEMAIL_STATUS.STATUSES.PENDING_APPROVAL]: [
      MARKETINGEMAIL_STATUS.STATUSES.APPROVED,
      MARKETINGEMAIL_STATUS.STATUSES.REJECTED,
      MARKETINGEMAIL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGEMAIL_STATUS.STATUSES.APPROVED]: [
      MARKETINGEMAIL_STATUS.STATUSES.SCHEDULED,
      MARKETINGEMAIL_STATUS.STATUSES.REJECTED,
      MARKETINGEMAIL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGEMAIL_STATUS.STATUSES.REJECTED]: [
      MARKETINGEMAIL_STATUS.STATUSES.DRAFT,
      MARKETINGEMAIL_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGEMAIL_STATUS.STATUSES.SCHEDULED]: [
      MARKETINGEMAIL_STATUS.STATUSES.QUEUED,
      MARKETINGEMAIL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGEMAIL_STATUS.STATUSES.QUEUED]: [
      MARKETINGEMAIL_STATUS.STATUSES.PROCESSING,
      MARKETINGEMAIL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGEMAIL_STATUS.STATUSES.PROCESSING]: [
      MARKETINGEMAIL_STATUS.STATUSES.SENT,
      MARKETINGEMAIL_STATUS.STATUSES.FAILED,
      MARKETINGEMAIL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGEMAIL_STATUS.STATUSES.SENT]: [
      MARKETINGEMAIL_STATUS.STATUSES.DELIVERED,
      MARKETINGEMAIL_STATUS.STATUSES.BOUNCED,
      MARKETINGEMAIL_STATUS.STATUSES.FAILED,
      MARKETINGEMAIL_STATUS.STATUSES.DEFERRED,
    ],
    [MARKETINGEMAIL_STATUS.STATUSES.DELIVERED]: [
      MARKETINGEMAIL_STATUS.STATUSES.OPENED,
      MARKETINGEMAIL_STATUS.STATUSES.UNSUBSCRIBED,
      MARKETINGEMAIL_STATUS.STATUSES.SPAM,
      MARKETINGEMAIL_STATUS.STATUSES.COMPLAINED,
    ],
    [MARKETINGEMAIL_STATUS.STATUSES.OPENED]: [
      MARKETINGEMAIL_STATUS.STATUSES.CLICKED,
      MARKETINGEMAIL_STATUS.STATUSES.UNSUBSCRIBED,
    ],
    [MARKETINGEMAIL_STATUS.STATUSES.CLICKED]: [
      MARKETINGEMAIL_STATUS.STATUSES.UNSUBSCRIBED,
      MARKETINGEMAIL_STATUS.STATUSES.COMPLAINED,
    ],
    [MARKETINGEMAIL_STATUS.STATUSES.DEFERRED]: [
      MARKETINGEMAIL_STATUS.STATUSES.SENT,
      MARKETINGEMAIL_STATUS.STATUSES.FAILED,
      MARKETINGEMAIL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGEMAIL_STATUS.STATUSES.BOUNCED]: [MARKETINGEMAIL_STATUS.STATUSES.ARCHIVED],
    [MARKETINGEMAIL_STATUS.STATUSES.FAILED]: [MARKETINGEMAIL_STATUS.STATUSES.ARCHIVED],
    [MARKETINGEMAIL_STATUS.STATUSES.UNSUBSCRIBED]: [MARKETINGEMAIL_STATUS.STATUSES.ARCHIVED],
    [MARKETINGEMAIL_STATUS.STATUSES.SPAM]: [MARKETINGEMAIL_STATUS.STATUSES.ARCHIVED],
    [MARKETINGEMAIL_STATUS.STATUSES.COMPLAINED]: [MARKETINGEMAIL_STATUS.STATUSES.ARCHIVED],
    [MARKETINGEMAIL_STATUS.STATUSES.PAUSED]: [
      MARKETINGEMAIL_STATUS.STATUSES.PROCESSING,
      MARKETINGEMAIL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGEMAIL_STATUS.STATUSES.EXPIRED]: [MARKETINGEMAIL_STATUS.STATUSES.ARCHIVED],
    [MARKETINGEMAIL_STATUS.STATUSES.CANCELLED]: [MARKETINGEMAIL_STATUS.STATUSES.ARCHIVED],
    [MARKETINGEMAIL_STATUS.STATUSES.ARCHIVED]: [],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
