/**
 * AI Personalization Status Constants
 * Status tracking for personalization lifecycle
 */

// First define the status types
export const AI_PERSONALIZATION_STATUS_TYPES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Processing States
  INITIALIZING: 'initializing',
  PROCESSING: 'processing',
  GENERATING: 'generating',
  VALIDATING: 'validating',

  // Intermediate States
  GENERATED: 'generated',
  VALIDATED: 'validated',
  PERSONALIZED: 'personalized',
  OPTIMIZED: 'optimized',

  // Storage States
  STORING: 'storing',
  STORED: 'stored',
  CACHING: 'caching',
  CACHED: 'cached',

  // Terminal States
  COMPLETED: 'completed',
  DELIVERED: 'delivered',
  FAILED: 'failed',
  EXPIRED: 'expired',
  ARCHIVED: 'archived',
} as const;

export type AIPersonalizationStatusType =
  (typeof AI_PERSONALIZATION_STATUS_TYPES)[keyof typeof AI_PERSONALIZATION_STATUS_TYPES];

export const AI_PERSONALIZATION_STATUS = {
  // Status Types
  STATUSES: AI_PERSONALIZATION_STATUS_TYPES,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    COMPLETED: 'completed',
    DELIVERED: 'delivered',
    FAILED: 'failed',
    CACHED: 'cached',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_PERSONALIZATION_STATUS_TYPES.CREATED]: '#gray',
    [AI_PERSONALIZATION_STATUS_TYPES.QUEUED]: '#gray',
    [AI_PERSONALIZATION_STATUS_TYPES.PENDING]: '#yellow',
    [AI_PERSONALIZATION_STATUS_TYPES.INITIALIZING]: '#blue',
    [AI_PERSONALIZATION_STATUS_TYPES.PROCESSING]: '#blue',
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATING]: '#blue',
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATING]: '#purple',
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.PERSONALIZED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.OPTIMIZED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.STORING]: '#orange',
    [AI_PERSONALIZATION_STATUS_TYPES.STORED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.CACHING]: '#orange',
    [AI_PERSONALIZATION_STATUS_TYPES.CACHED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.COMPLETED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.DELIVERED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.FAILED]: '#red',
    [AI_PERSONALIZATION_STATUS_TYPES.EXPIRED]: '#gray',
    [AI_PERSONALIZATION_STATUS_TYPES.ARCHIVED]: '#gray',
  } as const,
} as const;

export type AIPersonalizationStatusCategory =
  (typeof AI_PERSONALIZATION_STATUS.CATEGORIES)[keyof typeof AI_PERSONALIZATION_STATUS.CATEGORIES];
export type AIPersonalizationStatusSeverity =
  (typeof AI_PERSONALIZATION_STATUS.SEVERITY)[keyof typeof AI_PERSONALIZATION_STATUS.SEVERITY];
export type AIPersonalizationStatusColor =
  (typeof AI_PERSONALIZATION_STATUS.COLORS)[keyof typeof AI_PERSONALIZATION_STATUS.COLORS];

export function getAiPersonalizationStatusLabel(status: AIPersonalizationStatusType): string {
  const labels: Record<AIPersonalizationStatusType, string> = {
    [AI_PERSONALIZATION_STATUS_TYPES.CREATED]: 'Created',
    [AI_PERSONALIZATION_STATUS_TYPES.QUEUED]: 'Queued',
    [AI_PERSONALIZATION_STATUS_TYPES.PENDING]: 'Pending',
    [AI_PERSONALIZATION_STATUS_TYPES.INITIALIZING]: 'Initializing',
    [AI_PERSONALIZATION_STATUS_TYPES.PROCESSING]: 'Processing',
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATING]: 'Generating',
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATING]: 'Validating',
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATED]: 'Generated',
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATED]: 'Validated',
    [AI_PERSONALIZATION_STATUS_TYPES.PERSONALIZED]: 'Personalized',
    [AI_PERSONALIZATION_STATUS_TYPES.OPTIMIZED]: 'Optimized',
    [AI_PERSONALIZATION_STATUS_TYPES.STORING]: 'Storing',
    [AI_PERSONALIZATION_STATUS_TYPES.STORED]: 'Stored',
    [AI_PERSONALIZATION_STATUS_TYPES.CACHING]: 'Caching',
    [AI_PERSONALIZATION_STATUS_TYPES.CACHED]: 'Cached',
    [AI_PERSONALIZATION_STATUS_TYPES.COMPLETED]: 'Completed',
    [AI_PERSONALIZATION_STATUS_TYPES.DELIVERED]: 'Delivered',
    [AI_PERSONALIZATION_STATUS_TYPES.FAILED]: 'Failed',
    [AI_PERSONALIZATION_STATUS_TYPES.EXPIRED]: 'Expired',
    [AI_PERSONALIZATION_STATUS_TYPES.ARCHIVED]: 'Archived',
  };
  return labels[status] || 'Unknown';
}

export function getAiPersonalizationStatusCategory(
  status: AIPersonalizationStatusType
): AIPersonalizationStatusCategory {
  const categories: Record<AIPersonalizationStatusType, AIPersonalizationStatusCategory> = {
    [AI_PERSONALIZATION_STATUS_TYPES.CREATED]: AI_PERSONALIZATION_STATUS.CATEGORIES.PENDING,
    [AI_PERSONALIZATION_STATUS_TYPES.QUEUED]: AI_PERSONALIZATION_STATUS.CATEGORIES.PENDING,
    [AI_PERSONALIZATION_STATUS_TYPES.PENDING]: AI_PERSONALIZATION_STATUS.CATEGORIES.PENDING,
    [AI_PERSONALIZATION_STATUS_TYPES.INITIALIZING]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.PROCESSING]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATING]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATING]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATED]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATED]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.PERSONALIZED]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.OPTIMIZED]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.STORING]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.STORED]: AI_PERSONALIZATION_STATUS.CATEGORIES.COMPLETED,
    [AI_PERSONALIZATION_STATUS_TYPES.CACHING]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.CACHED]: AI_PERSONALIZATION_STATUS.CATEGORIES.CACHED,
    [AI_PERSONALIZATION_STATUS_TYPES.COMPLETED]: AI_PERSONALIZATION_STATUS.CATEGORIES.COMPLETED,
    [AI_PERSONALIZATION_STATUS_TYPES.DELIVERED]: AI_PERSONALIZATION_STATUS.CATEGORIES.DELIVERED,
    [AI_PERSONALIZATION_STATUS_TYPES.FAILED]: AI_PERSONALIZATION_STATUS.CATEGORIES.FAILED,
    [AI_PERSONALIZATION_STATUS_TYPES.EXPIRED]: AI_PERSONALIZATION_STATUS.CATEGORIES.FAILED,
    [AI_PERSONALIZATION_STATUS_TYPES.ARCHIVED]: AI_PERSONALIZATION_STATUS.CATEGORIES.COMPLETED,
  };
  return categories[status] || AI_PERSONALIZATION_STATUS.CATEGORIES.PENDING;
}

export function getAiPersonalizationStatusSeverity(
  status: AIPersonalizationStatusType
): AIPersonalizationStatusSeverity {
  const severities: Record<AIPersonalizationStatusType, AIPersonalizationStatusSeverity> = {
    [AI_PERSONALIZATION_STATUS_TYPES.CREATED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.QUEUED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.PENDING]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.INITIALIZING]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.PROCESSING]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATING]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATING]: AI_PERSONALIZATION_STATUS.SEVERITY.WARNING,
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.PERSONALIZED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.OPTIMIZED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.STORING]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.STORED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.CACHING]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.CACHED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.COMPLETED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.DELIVERED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.FAILED]: AI_PERSONALIZATION_STATUS.SEVERITY.ERROR,
    [AI_PERSONALIZATION_STATUS_TYPES.EXPIRED]: AI_PERSONALIZATION_STATUS.SEVERITY.WARNING,
    [AI_PERSONALIZATION_STATUS_TYPES.ARCHIVED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
  };
  return severities[status] || AI_PERSONALIZATION_STATUS.SEVERITY.INFO;
}

export function getAiPersonalizationStatusColor(
  status: AIPersonalizationStatusType
): AIPersonalizationStatusColor {
  return AI_PERSONALIZATION_STATUS.COLORS[status] || '#gray';
}

export function isAiPersonalizationActiveStatus(status: AIPersonalizationStatusType): boolean {
  const activeStatuses: AIPersonalizationStatusType[] = [
    AI_PERSONALIZATION_STATUS_TYPES.CREATED,
    AI_PERSONALIZATION_STATUS_TYPES.QUEUED,
    AI_PERSONALIZATION_STATUS_TYPES.PENDING,
    AI_PERSONALIZATION_STATUS_TYPES.INITIALIZING,
    AI_PERSONALIZATION_STATUS_TYPES.PROCESSING,
    AI_PERSONALIZATION_STATUS_TYPES.GENERATING,
    AI_PERSONALIZATION_STATUS_TYPES.VALIDATING,
    AI_PERSONALIZATION_STATUS_TYPES.GENERATED,
    AI_PERSONALIZATION_STATUS_TYPES.VALIDATED,
    AI_PERSONALIZATION_STATUS_TYPES.PERSONALIZED,
    AI_PERSONALIZATION_STATUS_TYPES.OPTIMIZED,
    AI_PERSONALIZATION_STATUS_TYPES.STORING,
    AI_PERSONALIZATION_STATUS_TYPES.CACHING,
  ];
  return activeStatuses.includes(status);
}

export function isAiPersonalizationCompletedStatus(status: AIPersonalizationStatusType): boolean {
  const completedStatuses: AIPersonalizationStatusType[] = [
    AI_PERSONALIZATION_STATUS_TYPES.COMPLETED,
    AI_PERSONALIZATION_STATUS_TYPES.DELIVERED,
    AI_PERSONALIZATION_STATUS_TYPES.STORED,
    AI_PERSONALIZATION_STATUS_TYPES.CACHED,
    AI_PERSONALIZATION_STATUS_TYPES.ARCHIVED,
  ];
  return completedStatuses.includes(status);
}

export function isAiPersonalizationFailedStatus(status: AIPersonalizationStatusType): boolean {
  const failedStatuses: AIPersonalizationStatusType[] = [
    AI_PERSONALIZATION_STATUS_TYPES.FAILED,
    AI_PERSONALIZATION_STATUS_TYPES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}

export function getAiPersonalizationStatusProgress(status: AIPersonalizationStatusType): number {
  const progress: Record<AIPersonalizationStatusType, number> = {
    [AI_PERSONALIZATION_STATUS_TYPES.CREATED]: 0,
    [AI_PERSONALIZATION_STATUS_TYPES.QUEUED]: 5,
    [AI_PERSONALIZATION_STATUS_TYPES.PENDING]: 10,
    [AI_PERSONALIZATION_STATUS_TYPES.INITIALIZING]: 20,
    [AI_PERSONALIZATION_STATUS_TYPES.PROCESSING]: 35,
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATING]: 55,
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATING]: 70,
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATED]: 60,
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATED]: 75,
    [AI_PERSONALIZATION_STATUS_TYPES.PERSONALIZED]: 80,
    [AI_PERSONALIZATION_STATUS_TYPES.OPTIMIZED]: 85,
    [AI_PERSONALIZATION_STATUS_TYPES.STORING]: 88,
    [AI_PERSONALIZATION_STATUS_TYPES.STORED]: 92,
    [AI_PERSONALIZATION_STATUS_TYPES.CACHING]: 94,
    [AI_PERSONALIZATION_STATUS_TYPES.CACHED]: 96,
    [AI_PERSONALIZATION_STATUS_TYPES.COMPLETED]: 100,
    [AI_PERSONALIZATION_STATUS_TYPES.DELIVERED]: 100,
    [AI_PERSONALIZATION_STATUS_TYPES.FAILED]: 0,
    [AI_PERSONALIZATION_STATUS_TYPES.EXPIRED]: 0,
    [AI_PERSONALIZATION_STATUS_TYPES.ARCHIVED]: 100,
  };
  return progress[status] || 0;
}
