/**
 * AI Personalization Status Constants
 * Status tracking for personalization lifecycle
 */

// First define the status types
export const AI_PERSONALIZATION_STATUS_TYPES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Processing States
  INITIALIZING: 'initializing',
  PROCESSING: 'processing',
  ANALYZING: 'analyzing',
  GENERATING: 'generating',
  VALIDATING: 'validating',

  // Intermediate States
  ANALYZED: 'analyzed',
  GENERATED: 'generated',
  VALIDATED: 'validated',
  OPTIMIZED: 'optimized',

  // Delivery States
  DELIVERING: 'delivering',
  DELIVERED: 'delivered',
  CACHED: 'cached',

  // User Interaction States
  DISPLAYED: 'displayed',
  VIEWED: 'viewed',
  CLICKED: 'clicked',
  ENGAGED: 'engaged',

  // Terminal States
  COMPLETED: 'completed',
  FAILED: 'failed',
  EXPIRED: 'expired',
  ARCHIVED: 'archived',
  RETIRED: 'retired',
} as const;

export type AIPersonalizationStatusType =
  (typeof AI_PERSONALIZATION_STATUS_TYPES)[keyof typeof AI_PERSONALIZATION_STATUS_TYPES];

export const AI_PERSONALIZATION_STATUS = {
  // Status Types
  STATUSES: AI_PERSONALIZATION_STATUS_TYPES,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    DELIVERED: 'delivered',
    ENGAGED: 'engaged',
    COMPLETED: 'completed',
    FAILED: 'failed',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_PERSONALIZATION_STATUS_TYPES.CREATED]: '#gray',
    [AI_PERSONALIZATION_STATUS_TYPES.QUEUED]: '#gray',
    [AI_PERSONALIZATION_STATUS_TYPES.PENDING]: '#yellow',
    [AI_PERSONALIZATION_STATUS_TYPES.INITIALIZING]: '#blue',
    [AI_PERSONALIZATION_STATUS_TYPES.PROCESSING]: '#blue',
    [AI_PERSONALIZATION_STATUS_TYPES.ANALYZING]: '#blue',
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATING]: '#blue',
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATING]: '#purple',
    [AI_PERSONALIZATION_STATUS_TYPES.ANALYZED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.OPTIMIZED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.DELIVERING]: '#orange',
    [AI_PERSONALIZATION_STATUS_TYPES.DELIVERED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.CACHED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.DISPLAYED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.VIEWED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.CLICKED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.ENGAGED]: '#gold',
    [AI_PERSONALIZATION_STATUS_TYPES.COMPLETED]: '#green',
    [AI_PERSONALIZATION_STATUS_TYPES.FAILED]: '#red',
    [AI_PERSONALIZATION_STATUS_TYPES.EXPIRED]: '#gray',
    [AI_PERSONALIZATION_STATUS_TYPES.ARCHIVED]: '#gray',
    [AI_PERSONALIZATION_STATUS_TYPES.RETIRED]: '#gray',
  } as const,
} as const;

// Status Categories
export type AIPersonalizationStatusCategory =
  (typeof AI_PERSONALIZATION_STATUS.CATEGORIES)[keyof typeof AI_PERSONALIZATION_STATUS.CATEGORIES];

// Status Severity
export type AIPersonalizationStatusSeverity =
  (typeof AI_PERSONALIZATION_STATUS.SEVERITY)[keyof typeof AI_PERSONALIZATION_STATUS.SEVERITY];

// Status Colors
export type AIPersonalizationStatusColor =
  (typeof AI_PERSONALIZATION_STATUS.COLORS)[keyof typeof AI_PERSONALIZATION_STATUS.COLORS];

// Utility Functions
export function getPersonalizationStatusLabel(status: AIPersonalizationStatusType): string {
  const labels: Record<AIPersonalizationStatusType, string> = {
    [AI_PERSONALIZATION_STATUS_TYPES.CREATED]: 'Created',
    [AI_PERSONALIZATION_STATUS_TYPES.QUEUED]: 'Queued',
    [AI_PERSONALIZATION_STATUS_TYPES.PENDING]: 'Pending',
    [AI_PERSONALIZATION_STATUS_TYPES.INITIALIZING]: 'Initializing',
    [AI_PERSONALIZATION_STATUS_TYPES.PROCESSING]: 'Processing',
    [AI_PERSONALIZATION_STATUS_TYPES.ANALYZING]: 'Analyzing',
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATING]: 'Generating',
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATING]: 'Validating',
    [AI_PERSONALIZATION_STATUS_TYPES.ANALYZED]: 'Analyzed',
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATED]: 'Generated',
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATED]: 'Validated',
    [AI_PERSONALIZATION_STATUS_TYPES.OPTIMIZED]: 'Optimized',
    [AI_PERSONALIZATION_STATUS_TYPES.DELIVERING]: 'Delivering',
    [AI_PERSONALIZATION_STATUS_TYPES.DELIVERED]: 'Delivered',
    [AI_PERSONALIZATION_STATUS_TYPES.CACHED]: 'Cached',
    [AI_PERSONALIZATION_STATUS_TYPES.DISPLAYED]: 'Displayed',
    [AI_PERSONALIZATION_STATUS_TYPES.VIEWED]: 'Viewed',
    [AI_PERSONALIZATION_STATUS_TYPES.CLICKED]: 'Clicked',
    [AI_PERSONALIZATION_STATUS_TYPES.ENGAGED]: 'Engaged',
    [AI_PERSONALIZATION_STATUS_TYPES.COMPLETED]: 'Completed',
    [AI_PERSONALIZATION_STATUS_TYPES.FAILED]: 'Failed',
    [AI_PERSONALIZATION_STATUS_TYPES.EXPIRED]: 'Expired',
    [AI_PERSONALIZATION_STATUS_TYPES.ARCHIVED]: 'Archived',
    [AI_PERSONALIZATION_STATUS_TYPES.RETIRED]: 'Retired',
  };
  return labels[status] || 'Unknown';
}

export function getPersonalizationStatusCategory(
  status: AIPersonalizationStatusType
): AIPersonalizationStatusCategory {
  const categories: Record<AIPersonalizationStatusType, AIPersonalizationStatusCategory> = {
    [AI_PERSONALIZATION_STATUS_TYPES.CREATED]: AI_PERSONALIZATION_STATUS.CATEGORIES.PENDING,
    [AI_PERSONALIZATION_STATUS_TYPES.QUEUED]: AI_PERSONALIZATION_STATUS.CATEGORIES.PENDING,
    [AI_PERSONALIZATION_STATUS_TYPES.PENDING]: AI_PERSONALIZATION_STATUS.CATEGORIES.PENDING,
    [AI_PERSONALIZATION_STATUS_TYPES.INITIALIZING]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.PROCESSING]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.ANALYZING]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATING]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATING]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.ANALYZED]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATED]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATED]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.OPTIMIZED]: AI_PERSONALIZATION_STATUS.CATEGORIES.PROCESSING,
    [AI_PERSONALIZATION_STATUS_TYPES.DELIVERING]: AI_PERSONALIZATION_STATUS.CATEGORIES.DELIVERED,
    [AI_PERSONALIZATION_STATUS_TYPES.DELIVERED]: AI_PERSONALIZATION_STATUS.CATEGORIES.DELIVERED,
    [AI_PERSONALIZATION_STATUS_TYPES.CACHED]: AI_PERSONALIZATION_STATUS.CATEGORIES.DELIVERED,
    [AI_PERSONALIZATION_STATUS_TYPES.DISPLAYED]: AI_PERSONALIZATION_STATUS.CATEGORIES.ENGAGED,
    [AI_PERSONALIZATION_STATUS_TYPES.VIEWED]: AI_PERSONALIZATION_STATUS.CATEGORIES.ENGAGED,
    [AI_PERSONALIZATION_STATUS_TYPES.CLICKED]: AI_PERSONALIZATION_STATUS.CATEGORIES.ENGAGED,
    [AI_PERSONALIZATION_STATUS_TYPES.ENGAGED]: AI_PERSONALIZATION_STATUS.CATEGORIES.ENGAGED,
    [AI_PERSONALIZATION_STATUS_TYPES.COMPLETED]: AI_PERSONALIZATION_STATUS.CATEGORIES.COMPLETED,
    [AI_PERSONALIZATION_STATUS_TYPES.FAILED]: AI_PERSONALIZATION_STATUS.CATEGORIES.FAILED,
    [AI_PERSONALIZATION_STATUS_TYPES.EXPIRED]: AI_PERSONALIZATION_STATUS.CATEGORIES.FAILED,
    [AI_PERSONALIZATION_STATUS_TYPES.ARCHIVED]: AI_PERSONALIZATION_STATUS.CATEGORIES.COMPLETED,
    [AI_PERSONALIZATION_STATUS_TYPES.RETIRED]: AI_PERSONALIZATION_STATUS.CATEGORIES.COMPLETED,
  };
  return categories[status] || AI_PERSONALIZATION_STATUS.CATEGORIES.PENDING;
}

export function getPersonalizationStatusSeverity(
  status: AIPersonalizationStatusType
): AIPersonalizationStatusSeverity {
  const severities: Record<AIPersonalizationStatusType, AIPersonalizationStatusSeverity> = {
    [AI_PERSONALIZATION_STATUS_TYPES.CREATED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.QUEUED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.PENDING]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.INITIALIZING]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.PROCESSING]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.ANALYZING]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATING]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATING]: AI_PERSONALIZATION_STATUS.SEVERITY.WARNING,
    [AI_PERSONALIZATION_STATUS_TYPES.ANALYZED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.GENERATED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.VALIDATED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.OPTIMIZED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.DELIVERING]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.DELIVERED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.CACHED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.DISPLAYED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.VIEWED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.CLICKED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.ENGAGED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.COMPLETED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.FAILED]: AI_PERSONALIZATION_STATUS.SEVERITY.ERROR,
    [AI_PERSONALIZATION_STATUS_TYPES.EXPIRED]: AI_PERSONALIZATION_STATUS.SEVERITY.WARNING,
    [AI_PERSONALIZATION_STATUS_TYPES.ARCHIVED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
    [AI_PERSONALIZATION_STATUS_TYPES.RETIRED]: AI_PERSONALIZATION_STATUS.SEVERITY.INFO,
  };
  return severities[status] || AI_PERSONALIZATION_STATUS.SEVERITY.INFO;
}

export function getPersonalizationStatusColor(
  status: AIPersonalizationStatusType
): AIPersonalizationStatusColor {
  return AI_PERSONALIZATION_STATUS.COLORS[status] || '#gray';
}

export function isPersonalizationActive(status: AIPersonalizationStatusType): boolean {
  const activeStatuses: AIPersonalizationStatusType[] = [
    AI_PERSONALIZATION_STATUS_TYPES.CREATED,
    AI_PERSONALIZATION_STATUS_TYPES.QUEUED,
    AI_PERSONALIZATION_STATUS_TYPES.PENDING,
    AI_PERSONALIZATION_STATUS_TYPES.INITIALIZING,
    AI_PERSONALIZATION_STATUS_TYPES.PROCESSING,
    AI_PERSONALIZATION_STATUS_TYPES.ANALYZING,
    AI_PERSONALIZATION_STATUS_TYPES.GENERATING,
    AI_PERSONALIZATION_STATUS_TYPES.VALIDATING,
    AI_PERSONALIZATION_STATUS_TYPES.ANALYZED,
    AI_PERSONALIZATION_STATUS_TYPES.GENERATED,
    AI_PERSONALIZATION_STATUS_TYPES.VALIDATED,
    AI_PERSONALIZATION_STATUS_TYPES.OPTIMIZED,
    AI_PERSONALIZATION_STATUS_TYPES.DELIVERING,
  ];
  return activeStatuses.includes(status);
}

export function isPersonalizationDelivered(status: AIPersonalizationStatusType): boolean {
  const deliveredStatuses: AIPersonalizationStatusType[] = [
    AI_PERSONALIZATION_STATUS_TYPES.DELIVERED,
    AI_PERSONALIZATION_STATUS_TYPES.CACHED,
    AI_PERSONALIZATION_STATUS_TYPES.DISPLAYED,
    AI_PERSONALIZATION_STATUS_TYPES.VIEWED,
    AI_PERSONALIZATION_STATUS_TYPES.CLICKED,
    AI_PERSONALIZATION_STATUS_TYPES.ENGAGED,
  ];
  return deliveredStatuses.includes(status);
}

export function isPersonalizationComplete(status: AIPersonalizationStatusType): boolean {
  const completeStatuses: AIPersonalizationStatusType[] = [
    AI_PERSONALIZATION_STATUS_TYPES.COMPLETED,
    AI_PERSONALIZATION_STATUS_TYPES.ARCHIVED,
    AI_PERSONALIZATION_STATUS_TYPES.RETIRED,
  ];
  return completeStatuses.includes(status);
}

export function isPersonalizationFailed(status: AIPersonalizationStatusType): boolean {
  const failedStatuses: AIPersonalizationStatusType[] = [
    AI_PERSONALIZATION_STATUS_TYPES.FAILED,
    AI_PERSONALIZATION_STATUS_TYPES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}
