/**
 * AI Personalization Scope Constants
 * Scope definitions for personalization targeting
 */

export const AI_PERSONALIZATION_SCOPE = {
  // Scope Levels
  LEVELS: {
    GLOBAL: 'global',
    SITE_WIDE: 'site_wide',
    PAGE: 'page',
    SECTION: 'section',
    COMPONENT: 'component',
  } as const,

  // Scope Contexts
  CONTEXTS: {
    // User Context
    USER: 'user',
    USER_SEGMENT: 'user_segment',
    USER_GROUP: 'user_group',
    USER_JOURNEY: 'user_journey',

    // Product Context
    PRODUCT: 'product',
    CATEGORY: 'category',
    BRAND: 'brand',
    COLLECTION: 'collection',

    // Shopping Context
    BROWSE: 'browse',
    SEARCH: 'search',
    CART: 'cart',
    CHECKOUT: 'checkout',
    WISHLIST: 'wishlist',

    // Location Context
    COUNTRY: 'country',
    REGION: 'region',
    CITY: 'city',
    STORE: 'store',

    // Time Context
    TIME_OF_DAY: 'time_of_day',
    DAY_OF_WEEK: 'day_of_week',
    WEEK_OF_YEAR: 'week_of_year',
    MONTH: 'month',
    SEASON: 'season',

    // Device Context
    DEVICE_TYPE: 'device_type',
    PLATFORM: 'platform',
    BROWSER: 'browser',
    OS: 'os',

    // Channel Context
    EMAIL: 'email',
    PUSH: 'push',
    SMS: 'sms',
    WEB: 'web',
    APP: 'app',
    SOCIAL: 'social',
  } as const,

  // Scope Types
  TYPES: {
    PERSONALIZED: 'personalized',
    SEGMENTED: 'segmented',
    GROUPED: 'grouped',
    GENERAL: 'general',
    DYNAMIC: 'dynamic',
    STATIC: 'static',
    ADAPTIVE: 'adaptive',
  } as const,

  // Scope Rules
  RULES: {
    INCLUDE: 'include',
    EXCLUDE: 'exclude',
    PRIORITIZE: 'prioritize',
    DEPRIORITIZE: 'deprioritize',
    BOOST: 'boost',
    SUPPRESS: 'suppress',
    FILTER: 'filter',
  } as const,

  // Scope Weights
  WEIGHTS: {
    USER: 0.4,
    SESSION: 0.3,
    CONTEXT: 0.15,
    DEVICE: 0.05,
    LOCATION: 0.05,
    TIME: 0.05,
  } as const,

  // Scope Priorities
  PRIORITIES: {
    CRITICAL: 10,
    HIGH: 8,
    MEDIUM: 5,
    LOW: 3,
    MINIMAL: 1,
  } as const,
} as const;

// Scope Levels
export type AIPersonalizationScopeLevel =
  (typeof AI_PERSONALIZATION_SCOPE.LEVELS)[keyof typeof AI_PERSONALIZATION_SCOPE.LEVELS];

// Scope Contexts
export type AIPersonalizationScopeContext =
  (typeof AI_PERSONALIZATION_SCOPE.CONTEXTS)[keyof typeof AI_PERSONALIZATION_SCOPE.CONTEXTS];

// Scope Types
export type AIPersonalizationScopeType =
  (typeof AI_PERSONALIZATION_SCOPE.TYPES)[keyof typeof AI_PERSONALIZATION_SCOPE.TYPES];

// Scope Rules
export type AIPersonalizationScopeRule =
  (typeof AI_PERSONALIZATION_SCOPE.RULES)[keyof typeof AI_PERSONALIZATION_SCOPE.RULES];

// Scope Weights
export type AIPersonalizationScopeWeight =
  (typeof AI_PERSONALIZATION_SCOPE.WEIGHTS)[keyof typeof AI_PERSONALIZATION_SCOPE.WEIGHTS];

// Scope Priorities
export type AIPersonalizationScopePriority =
  (typeof AI_PERSONALIZATION_SCOPE.PRIORITIES)[keyof typeof AI_PERSONALIZATION_SCOPE.PRIORITIES];

// Utility Functions
export function getPersonalizationScopeLevelLabel(level: AIPersonalizationScopeLevel): string {
  const labels: Record<AIPersonalizationScopeLevel, string> = {
    [AI_PERSONALIZATION_SCOPE.LEVELS.GLOBAL]: 'Global',
    [AI_PERSONALIZATION_SCOPE.LEVELS.SITE_WIDE]: 'Site Wide',
    [AI_PERSONALIZATION_SCOPE.LEVELS.PAGE]: 'Page',
    [AI_PERSONALIZATION_SCOPE.LEVELS.SECTION]: 'Section',
    [AI_PERSONALIZATION_SCOPE.LEVELS.COMPONENT]: 'Component',
  };
  return labels[level] || 'Unknown';
}

export function getPersonalizationScopeContextLabel(
  context: AIPersonalizationScopeContext
): string {
  const labels: Record<AIPersonalizationScopeContext, string> = {
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.USER]: 'User',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.USER_SEGMENT]: 'User Segment',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.USER_GROUP]: 'User Group',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.USER_JOURNEY]: 'User Journey',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.PRODUCT]: 'Product',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.CATEGORY]: 'Category',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.BRAND]: 'Brand',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.COLLECTION]: 'Collection',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.BROWSE]: 'Browse',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.SEARCH]: 'Search',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.CART]: 'Cart',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.CHECKOUT]: 'Checkout',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.WISHLIST]: 'Wishlist',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.COUNTRY]: 'Country',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.REGION]: 'Region',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.CITY]: 'City',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.STORE]: 'Store',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.TIME_OF_DAY]: 'Time of Day',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.DAY_OF_WEEK]: 'Day of Week',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.WEEK_OF_YEAR]: 'Week of Year',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.MONTH]: 'Month',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.SEASON]: 'Season',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.DEVICE_TYPE]: 'Device Type',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.PLATFORM]: 'Platform',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.BROWSER]: 'Browser',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.OS]: 'OS',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.EMAIL]: 'Email',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.PUSH]: 'Push',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.SMS]: 'SMS',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.WEB]: 'Web',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.APP]: 'App',
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.SOCIAL]: 'Social',
  };
  return labels[context] || 'Unknown';
}

export function getPersonalizationScopeTypeLabel(type: AIPersonalizationScopeType): string {
  const labels: Record<AIPersonalizationScopeType, string> = {
    [AI_PERSONALIZATION_SCOPE.TYPES.PERSONALIZED]: 'Personalized',
    [AI_PERSONALIZATION_SCOPE.TYPES.SEGMENTED]: 'Segmented',
    [AI_PERSONALIZATION_SCOPE.TYPES.GROUPED]: 'Grouped',
    [AI_PERSONALIZATION_SCOPE.TYPES.GENERAL]: 'General',
    [AI_PERSONALIZATION_SCOPE.TYPES.DYNAMIC]: 'Dynamic',
    [AI_PERSONALIZATION_SCOPE.TYPES.STATIC]: 'Static',
    [AI_PERSONALIZATION_SCOPE.TYPES.ADAPTIVE]: 'Adaptive',
  };
  return labels[type] || 'Unknown';
}

export function getPersonalizationScopeRuleLabel(rule: AIPersonalizationScopeRule): string {
  const labels: Record<AIPersonalizationScopeRule, string> = {
    [AI_PERSONALIZATION_SCOPE.RULES.INCLUDE]: 'Include',
    [AI_PERSONALIZATION_SCOPE.RULES.EXCLUDE]: 'Exclude',
    [AI_PERSONALIZATION_SCOPE.RULES.PRIORITIZE]: 'Prioritize',
    [AI_PERSONALIZATION_SCOPE.RULES.DEPRIORITIZE]: 'Deprioritize',
    [AI_PERSONALIZATION_SCOPE.RULES.BOOST]: 'Boost',
    [AI_PERSONALIZATION_SCOPE.RULES.SUPPRESS]: 'Suppress',
    [AI_PERSONALIZATION_SCOPE.RULES.FILTER]: 'Filter',
  };
  return labels[rule] || 'Unknown';
}

export function getPersonalizationScopeWeight(context: AIPersonalizationScopeContext): number {
  const weights: Record<AIPersonalizationScopeContext, number> = {
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.USER]: AI_PERSONALIZATION_SCOPE.WEIGHTS.USER,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.USER_SEGMENT]: AI_PERSONALIZATION_SCOPE.WEIGHTS.USER * 0.8,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.USER_GROUP]: AI_PERSONALIZATION_SCOPE.WEIGHTS.USER * 0.6,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.USER_JOURNEY]: AI_PERSONALIZATION_SCOPE.WEIGHTS.USER * 0.9,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.PRODUCT]: AI_PERSONALIZATION_SCOPE.WEIGHTS.CONTEXT * 0.8,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.CATEGORY]: AI_PERSONALIZATION_SCOPE.WEIGHTS.CONTEXT * 0.7,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.BRAND]: AI_PERSONALIZATION_SCOPE.WEIGHTS.CONTEXT * 0.6,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.COLLECTION]: AI_PERSONALIZATION_SCOPE.WEIGHTS.CONTEXT * 0.7,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.BROWSE]: AI_PERSONALIZATION_SCOPE.WEIGHTS.SESSION * 0.8,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.SEARCH]: AI_PERSONALIZATION_SCOPE.WEIGHTS.SESSION * 0.9,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.CART]: AI_PERSONALIZATION_SCOPE.WEIGHTS.SESSION * 1.0,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.CHECKOUT]: AI_PERSONALIZATION_SCOPE.WEIGHTS.SESSION * 1.0,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.WISHLIST]: AI_PERSONALIZATION_SCOPE.WEIGHTS.SESSION * 0.9,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.COUNTRY]: AI_PERSONALIZATION_SCOPE.WEIGHTS.LOCATION * 0.8,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.REGION]: AI_PERSONALIZATION_SCOPE.WEIGHTS.LOCATION * 0.7,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.CITY]: AI_PERSONALIZATION_SCOPE.WEIGHTS.LOCATION * 1.0,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.STORE]: AI_PERSONALIZATION_SCOPE.WEIGHTS.LOCATION * 0.9,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.TIME_OF_DAY]: AI_PERSONALIZATION_SCOPE.WEIGHTS.TIME * 0.8,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.DAY_OF_WEEK]: AI_PERSONALIZATION_SCOPE.WEIGHTS.TIME * 0.9,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.WEEK_OF_YEAR]: AI_PERSONALIZATION_SCOPE.WEIGHTS.TIME * 0.7,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.MONTH]: AI_PERSONALIZATION_SCOPE.WEIGHTS.TIME * 0.8,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.SEASON]: AI_PERSONALIZATION_SCOPE.WEIGHTS.TIME * 0.9,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.DEVICE_TYPE]: AI_PERSONALIZATION_SCOPE.WEIGHTS.DEVICE,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.PLATFORM]: AI_PERSONALIZATION_SCOPE.WEIGHTS.DEVICE * 0.8,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.BROWSER]: AI_PERSONALIZATION_SCOPE.WEIGHTS.DEVICE * 0.6,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.OS]: AI_PERSONALIZATION_SCOPE.WEIGHTS.DEVICE * 0.7,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.EMAIL]: AI_PERSONALIZATION_SCOPE.WEIGHTS.CONTEXT * 0.5,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.PUSH]: AI_PERSONALIZATION_SCOPE.WEIGHTS.CONTEXT * 0.5,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.SMS]: AI_PERSONALIZATION_SCOPE.WEIGHTS.CONTEXT * 0.4,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.WEB]: AI_PERSONALIZATION_SCOPE.WEIGHTS.CONTEXT * 0.6,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.APP]: AI_PERSONALIZATION_SCOPE.WEIGHTS.CONTEXT * 0.6,
    [AI_PERSONALIZATION_SCOPE.CONTEXTS.SOCIAL]: AI_PERSONALIZATION_SCOPE.WEIGHTS.CONTEXT * 0.5,
  };
  return weights[context] || 0.1;
}

export function getPersonalizationScopePriority(
  level: AIPersonalizationScopeLevel
): AIPersonalizationScopePriority {
  const priorities: Record<AIPersonalizationScopeLevel, AIPersonalizationScopePriority> = {
    [AI_PERSONALIZATION_SCOPE.LEVELS.GLOBAL]: AI_PERSONALIZATION_SCOPE.PRIORITIES.HIGH,
    [AI_PERSONALIZATION_SCOPE.LEVELS.SITE_WIDE]: AI_PERSONALIZATION_SCOPE.PRIORITIES.MEDIUM,
    [AI_PERSONALIZATION_SCOPE.LEVELS.PAGE]: AI_PERSONALIZATION_SCOPE.PRIORITIES.MEDIUM,
    [AI_PERSONALIZATION_SCOPE.LEVELS.SECTION]: AI_PERSONALIZATION_SCOPE.PRIORITIES.LOW,
    [AI_PERSONALIZATION_SCOPE.LEVELS.COMPONENT]: AI_PERSONALIZATION_SCOPE.PRIORITIES.MINIMAL,
  };
  return priorities[level] || AI_PERSONALIZATION_SCOPE.PRIORITIES.MEDIUM;
}
