[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter @vubon/order-service build"]

[start]
cmd = "node apps/order-service/dist/main.js"

[variables]
NODE_ENV = "production"
PORT = "4004"
