/**
 * AI Ranking Status Constants
 * Status tracking for ranking lifecycle
 */

// First define the status types
export const AI_RANKING_STATUS_TYPES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Processing States
  INITIALIZING: 'initializing',
  PROCESSING: 'processing',
  RANKING: 'ranking',
  SCORING: 'scoring',
  SORTING: 'sorting',
  FILTERING: 'filtering',

  // Intermediate States
  RANKED: 'ranked',
  SCORED: 'scored',
  SORTED: 'sorted',
  FILTERED: 'filtered',
  OPTIMIZED: 'optimized',

  // Delivery States
  DELIVERING: 'delivering',
  DELIVERED: 'delivered',
  CACHED: 'cached',

  // Terminal States
  COMPLETED: 'completed',
  FAILED: 'failed',
  EXPIRED: 'expired',
  ARCHIVED: 'archived',
  RETIRED: 'retired',
} as const;

export type AIRankingStatusType =
  (typeof AI_RANKING_STATUS_TYPES)[keyof typeof AI_RANKING_STATUS_TYPES];

export const AI_RANKING_STATUS = {
  // Status Types
  STATUSES: AI_RANKING_STATUS_TYPES,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    DELIVERED: 'delivered',
    COMPLETED: 'completed',
    FAILED: 'failed',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_RANKING_STATUS_TYPES.CREATED]: '#gray',
    [AI_RANKING_STATUS_TYPES.QUEUED]: '#gray',
    [AI_RANKING_STATUS_TYPES.PENDING]: '#yellow',
    [AI_RANKING_STATUS_TYPES.INITIALIZING]: '#blue',
    [AI_RANKING_STATUS_TYPES.PROCESSING]: '#blue',
    [AI_RANKING_STATUS_TYPES.RANKING]: '#blue',
    [AI_RANKING_STATUS_TYPES.SCORING]: '#blue',
    [AI_RANKING_STATUS_TYPES.SORTING]: '#blue',
    [AI_RANKING_STATUS_TYPES.FILTERING]: '#blue',
    [AI_RANKING_STATUS_TYPES.RANKED]: '#green',
    [AI_RANKING_STATUS_TYPES.SCORED]: '#green',
    [AI_RANKING_STATUS_TYPES.SORTED]: '#green',
    [AI_RANKING_STATUS_TYPES.FILTERED]: '#green',
    [AI_RANKING_STATUS_TYPES.OPTIMIZED]: '#green',
    [AI_RANKING_STATUS_TYPES.DELIVERING]: '#orange',
    [AI_RANKING_STATUS_TYPES.DELIVERED]: '#green',
    [AI_RANKING_STATUS_TYPES.CACHED]: '#green',
    [AI_RANKING_STATUS_TYPES.COMPLETED]: '#green',
    [AI_RANKING_STATUS_TYPES.FAILED]: '#red',
    [AI_RANKING_STATUS_TYPES.EXPIRED]: '#gray',
    [AI_RANKING_STATUS_TYPES.ARCHIVED]: '#gray',
    [AI_RANKING_STATUS_TYPES.RETIRED]: '#gray',
  } as const,
} as const;

// Status Categories
export type AIRankingStatusCategory =
  (typeof AI_RANKING_STATUS.CATEGORIES)[keyof typeof AI_RANKING_STATUS.CATEGORIES];

// Status Severity
export type AIRankingStatusSeverity =
  (typeof AI_RANKING_STATUS.SEVERITY)[keyof typeof AI_RANKING_STATUS.SEVERITY];

// Status Colors
export type AIRankingStatusColor =
  (typeof AI_RANKING_STATUS.COLORS)[keyof typeof AI_RANKING_STATUS.COLORS];

// Utility Functions
export function getRankingStatusLabel(status: AIRankingStatusType): string {
  const labels: Record<AIRankingStatusType, string> = {
    [AI_RANKING_STATUS_TYPES.CREATED]: 'Created',
    [AI_RANKING_STATUS_TYPES.QUEUED]: 'Queued',
    [AI_RANKING_STATUS_TYPES.PENDING]: 'Pending',
    [AI_RANKING_STATUS_TYPES.INITIALIZING]: 'Initializing',
    [AI_RANKING_STATUS_TYPES.PROCESSING]: 'Processing',
    [AI_RANKING_STATUS_TYPES.RANKING]: 'Ranking',
    [AI_RANKING_STATUS_TYPES.SCORING]: 'Scoring',
    [AI_RANKING_STATUS_TYPES.SORTING]: 'Sorting',
    [AI_RANKING_STATUS_TYPES.FILTERING]: 'Filtering',
    [AI_RANKING_STATUS_TYPES.RANKED]: 'Ranked',
    [AI_RANKING_STATUS_TYPES.SCORED]: 'Scored',
    [AI_RANKING_STATUS_TYPES.SORTED]: 'Sorted',
    [AI_RANKING_STATUS_TYPES.FILTERED]: 'Filtered',
    [AI_RANKING_STATUS_TYPES.OPTIMIZED]: 'Optimized',
    [AI_RANKING_STATUS_TYPES.DELIVERING]: 'Delivering',
    [AI_RANKING_STATUS_TYPES.DELIVERED]: 'Delivered',
    [AI_RANKING_STATUS_TYPES.CACHED]: 'Cached',
    [AI_RANKING_STATUS_TYPES.COMPLETED]: 'Completed',
    [AI_RANKING_STATUS_TYPES.FAILED]: 'Failed',
    [AI_RANKING_STATUS_TYPES.EXPIRED]: 'Expired',
    [AI_RANKING_STATUS_TYPES.ARCHIVED]: 'Archived',
    [AI_RANKING_STATUS_TYPES.RETIRED]: 'Retired',
  };
  return labels[status] || 'Unknown';
}

export function getRankingStatusCategory(status: AIRankingStatusType): AIRankingStatusCategory {
  const categories: Record<AIRankingStatusType, AIRankingStatusCategory> = {
    [AI_RANKING_STATUS_TYPES.CREATED]: AI_RANKING_STATUS.CATEGORIES.PENDING,
    [AI_RANKING_STATUS_TYPES.QUEUED]: AI_RANKING_STATUS.CATEGORIES.PENDING,
    [AI_RANKING_STATUS_TYPES.PENDING]: AI_RANKING_STATUS.CATEGORIES.PENDING,
    [AI_RANKING_STATUS_TYPES.INITIALIZING]: AI_RANKING_STATUS.CATEGORIES.PROCESSING,
    [AI_RANKING_STATUS_TYPES.PROCESSING]: AI_RANKING_STATUS.CATEGORIES.PROCESSING,
    [AI_RANKING_STATUS_TYPES.RANKING]: AI_RANKING_STATUS.CATEGORIES.PROCESSING,
    [AI_RANKING_STATUS_TYPES.SCORING]: AI_RANKING_STATUS.CATEGORIES.PROCESSING,
    [AI_RANKING_STATUS_TYPES.SORTING]: AI_RANKING_STATUS.CATEGORIES.PROCESSING,
    [AI_RANKING_STATUS_TYPES.FILTERING]: AI_RANKING_STATUS.CATEGORIES.PROCESSING,
    [AI_RANKING_STATUS_TYPES.RANKED]: AI_RANKING_STATUS.CATEGORIES.PROCESSING,
    [AI_RANKING_STATUS_TYPES.SCORED]: AI_RANKING_STATUS.CATEGORIES.PROCESSING,
    [AI_RANKING_STATUS_TYPES.SORTED]: AI_RANKING_STATUS.CATEGORIES.PROCESSING,
    [AI_RANKING_STATUS_TYPES.FILTERED]: AI_RANKING_STATUS.CATEGORIES.PROCESSING,
    [AI_RANKING_STATUS_TYPES.OPTIMIZED]: AI_RANKING_STATUS.CATEGORIES.PROCESSING,
    [AI_RANKING_STATUS_TYPES.DELIVERING]: AI_RANKING_STATUS.CATEGORIES.DELIVERED,
    [AI_RANKING_STATUS_TYPES.DELIVERED]: AI_RANKING_STATUS.CATEGORIES.DELIVERED,
    [AI_RANKING_STATUS_TYPES.CACHED]: AI_RANKING_STATUS.CATEGORIES.DELIVERED,
    [AI_RANKING_STATUS_TYPES.COMPLETED]: AI_RANKING_STATUS.CATEGORIES.COMPLETED,
    [AI_RANKING_STATUS_TYPES.FAILED]: AI_RANKING_STATUS.CATEGORIES.FAILED,
    [AI_RANKING_STATUS_TYPES.EXPIRED]: AI_RANKING_STATUS.CATEGORIES.FAILED,
    [AI_RANKING_STATUS_TYPES.ARCHIVED]: AI_RANKING_STATUS.CATEGORIES.COMPLETED,
    [AI_RANKING_STATUS_TYPES.RETIRED]: AI_RANKING_STATUS.CATEGORIES.COMPLETED,
  };
  return categories[status] || AI_RANKING_STATUS.CATEGORIES.PENDING;
}

export function getRankingStatusSeverity(status: AIRankingStatusType): AIRankingStatusSeverity {
  const severities: Record<AIRankingStatusType, AIRankingStatusSeverity> = {
    [AI_RANKING_STATUS_TYPES.CREATED]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.QUEUED]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.PENDING]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.INITIALIZING]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.PROCESSING]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.RANKING]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.SCORING]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.SORTING]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.FILTERING]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.RANKED]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.SCORED]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.SORTED]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.FILTERED]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.OPTIMIZED]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.DELIVERING]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.DELIVERED]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.CACHED]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.COMPLETED]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.FAILED]: AI_RANKING_STATUS.SEVERITY.ERROR,
    [AI_RANKING_STATUS_TYPES.EXPIRED]: AI_RANKING_STATUS.SEVERITY.WARNING,
    [AI_RANKING_STATUS_TYPES.ARCHIVED]: AI_RANKING_STATUS.SEVERITY.INFO,
    [AI_RANKING_STATUS_TYPES.RETIRED]: AI_RANKING_STATUS.SEVERITY.INFO,
  };
  return severities[status] || AI_RANKING_STATUS.SEVERITY.INFO;
}

export function getRankingStatusColor(status: AIRankingStatusType): AIRankingStatusColor {
  return AI_RANKING_STATUS.COLORS[status] || '#gray';
}

export function isRankingActive(status: AIRankingStatusType): boolean {
  const activeStatuses: AIRankingStatusType[] = [
    AI_RANKING_STATUS_TYPES.CREATED,
    AI_RANKING_STATUS_TYPES.QUEUED,
    AI_RANKING_STATUS_TYPES.PENDING,
    AI_RANKING_STATUS_TYPES.INITIALIZING,
    AI_RANKING_STATUS_TYPES.PROCESSING,
    AI_RANKING_STATUS_TYPES.RANKING,
    AI_RANKING_STATUS_TYPES.SCORING,
    AI_RANKING_STATUS_TYPES.SORTING,
    AI_RANKING_STATUS_TYPES.FILTERING,
    AI_RANKING_STATUS_TYPES.RANKED,
    AI_RANKING_STATUS_TYPES.SCORED,
    AI_RANKING_STATUS_TYPES.SORTED,
    AI_RANKING_STATUS_TYPES.FILTERED,
    AI_RANKING_STATUS_TYPES.OPTIMIZED,
    AI_RANKING_STATUS_TYPES.DELIVERING,
  ];
  return activeStatuses.includes(status);
}

export function isRankingDelivered(status: AIRankingStatusType): boolean {
  const deliveredStatuses: AIRankingStatusType[] = [
    AI_RANKING_STATUS_TYPES.DELIVERED,
    AI_RANKING_STATUS_TYPES.CACHED,
  ];
  return deliveredStatuses.includes(status);
}

export function isRankingComplete(status: AIRankingStatusType): boolean {
  const completeStatuses: AIRankingStatusType[] = [
    AI_RANKING_STATUS_TYPES.COMPLETED,
    AI_RANKING_STATUS_TYPES.ARCHIVED,
    AI_RANKING_STATUS_TYPES.RETIRED,
  ];
  return completeStatuses.includes(status);
}

export function isRankingFailed(status: AIRankingStatusType): boolean {
  const failedStatuses: AIRankingStatusType[] = [
    AI_RANKING_STATUS_TYPES.FAILED,
    AI_RANKING_STATUS_TYPES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}
