export const BASE_TOKENS = {
  // Repository tokens
  REPOSITORY: 'REPOSITORY',
  USER_REPOSITORY: 'USER_REPOSITORY',
  ORDER_REPOSITORY: 'ORDER_REPOSITORY',
  PRODUCT_REPOSITORY: 'PRODUCT_REPOSITORY',

  // Service tokens
  SERVICE: 'SERVICE',
  USER_SERVICE: 'USER_SERVICE',
  ORDER_SERVICE: 'ORDER_SERVICE',
  PRODUCT_SERVICE: 'PRODUCT_SERVICE',

  // Command tokens
  COMMAND_HANDLER: 'COMMAND_HANDLER',
  QUERY_HANDLER: 'QUERY_HANDLER',

  // Event tokens
  EVENT_HANDLER: 'EVENT_HANDLER',
  EVENT_STORE: 'EVENT_STORE',

  // Infrastructure tokens
  PRISMA_SERVICE: 'PRISMA_SERVICE',
  REDIS_SERVICE: 'REDIS_SERVICE',
  QUEUE_SERVICE: 'QUEUE_SERVICE',
  EMAIL_SERVICE: 'EMAIL_SERVICE',
  SMS_SERVICE: 'SMS_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',

  // Cache tokens
  CACHE_SERVICE: 'CACHE_SERVICE',
  CACHE_MANAGER: 'CACHE_MANAGER',

  // Logger
  LOGGER: 'LOGGER',
} as const;

export type BaseToken = (typeof BASE_TOKENS)[keyof typeof BASE_TOKENS];
