/**
 * Return Shipment Status Constants
 * Status definitions for return shipments
 */

export const LOGISTICS_RETURN_SHIPMENT_STATUS = {
  // Status Types
  TYPES: {
    REQUESTED: 'requested',
    APPROVED: 'approved',
    REJECTED: 'rejected',
    PENDING_PICKUP: 'pending_pickup',
    PICKED_UP: 'picked_up',
    IN_TRANSIT: 'in_transit',
    RECEIVED: 'received',
    INSPECTING: 'inspecting',
    PROCESSING: 'processing',
    REFUNDED: 'refunded',
    EXCHANGED: 'exchanged',
    COMPLETED: 'completed',
    CANCELLED: 'cancelled',
  } as const,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    ACTIVE: 'active',
    COMPLETED: 'completed',
    FAILED: 'failed',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    REQUESTED: '#yellow-500',
    APPROVED: '#green-400',
    REJECTED: '#red-500',
    PENDING_PICKUP: '#orange-400',
    PICKED_UP: '#blue-400',
    IN_TRANSIT: '#blue-500',
    RECEIVED: '#purple-400',
    INSPECTING: '#purple-500',
    PROCESSING: '#indigo-500',
    REFUNDED: '#green-500',
    EXCHANGED: '#teal-500',
    COMPLETED: '#green-600',
    CANCELLED: '#gray-500',
  } as const,

  // Status Icons (for UI)
  ICONS: {
    REQUESTED: '📝',
    APPROVED: '✅',
    REJECTED: '❌',
    PENDING_PICKUP: '📋',
    PICKED_UP: '📦',
    IN_TRANSIT: '🚚',
    RECEIVED: '📍',
    INSPECTING: '🔍',
    PROCESSING: '⚙️',
    REFUNDED: '💰',
    EXCHANGED: '🔄',
    COMPLETED: '🎯',
    CANCELLED: '🚫',
  } as const,

  // Status Transitions
  TRANSITIONS: {
    REQUESTED_TO_APPROVED: 'requested_to_approved',
    REQUESTED_TO_REJECTED: 'requested_to_rejected',
    APPROVED_TO_PENDING_PICKUP: 'approved_to_pending_pickup',
    PENDING_PICKUP_TO_PICKED_UP: 'pending_pickup_to_picked_up',
    PICKED_UP_TO_IN_TRANSIT: 'picked_up_to_in_transit',
    IN_TRANSIT_TO_RECEIVED: 'in_transit_to_received',
    RECEIVED_TO_INSPECTING: 'received_to_inspecting',
    INSPECTING_TO_PROCESSING: 'inspecting_to_processing',
    PROCESSING_TO_REFUNDED: 'processing_to_refunded',
    PROCESSING_TO_EXCHANGED: 'processing_to_exchanged',
    REFUNDED_TO_COMPLETED: 'refunded_to_completed',
    EXCHANGED_TO_COMPLETED: 'exchanged_to_completed',
    ANY_TO_CANCELLED: 'any_to_cancelled',
  } as const,
} as const;

// Status Types
export type LogisticsReturnShipmentStatusType =
  (typeof LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES)[keyof typeof LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES];

// Status Categories
export type LogisticsReturnShipmentStatusCategory =
  (typeof LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES)[keyof typeof LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES];

// Status Colors
export type LogisticsReturnShipmentStatusColor =
  (typeof LOGISTICS_RETURN_SHIPMENT_STATUS.COLORS)[keyof typeof LOGISTICS_RETURN_SHIPMENT_STATUS.COLORS];

// Status Icons
export type LogisticsReturnShipmentStatusIcon =
  (typeof LOGISTICS_RETURN_SHIPMENT_STATUS.ICONS)[keyof typeof LOGISTICS_RETURN_SHIPMENT_STATUS.ICONS];

// Status Transitions
export type LogisticsReturnShipmentStatusTransition =
  (typeof LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS)[keyof typeof LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS];

// Utility Functions
export function logisticsReturnShipmentStatusGetLabel(
  status: LogisticsReturnShipmentStatusType
): string {
  const labels: Record<LogisticsReturnShipmentStatusType, string> = {
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.REQUESTED]: 'Requested',
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.APPROVED]: 'Approved',
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.REJECTED]: 'Rejected',
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.PENDING_PICKUP]: 'Pending Pickup',
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.PICKED_UP]: 'Picked Up',
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.IN_TRANSIT]: 'In Transit',
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.RECEIVED]: 'Received',
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.INSPECTING]: 'Inspecting',
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.PROCESSING]: 'Processing',
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.REFUNDED]: 'Refunded',
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.EXCHANGED]: 'Exchanged',
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.COMPLETED]: 'Completed',
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.CANCELLED]: 'Cancelled',
  };
  return labels[status] || 'Unknown';
}

export function logisticsReturnShipmentStatusGetCategory(
  status: LogisticsReturnShipmentStatusType
): LogisticsReturnShipmentStatusCategory {
  const categories: Record<
    LogisticsReturnShipmentStatusType,
    LogisticsReturnShipmentStatusCategory
  > = {
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.REQUESTED]:
      LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES.PENDING,
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.APPROVED]:
      LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES.ACTIVE,
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.REJECTED]:
      LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES.FAILED,
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.PENDING_PICKUP]:
      LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES.ACTIVE,
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.PICKED_UP]:
      LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES.ACTIVE,
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.IN_TRANSIT]:
      LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES.ACTIVE,
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.RECEIVED]:
      LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES.ACTIVE,
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.INSPECTING]:
      LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES.ACTIVE,
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.PROCESSING]:
      LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES.ACTIVE,
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.REFUNDED]:
      LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES.COMPLETED,
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.EXCHANGED]:
      LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES.COMPLETED,
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.COMPLETED]:
      LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES.COMPLETED,
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.CANCELLED]:
      LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES.FAILED,
  };
  return categories[status] || LOGISTICS_RETURN_SHIPMENT_STATUS.CATEGORIES.PENDING;
}

export function logisticsReturnShipmentStatusIsComplete(
  status: LogisticsReturnShipmentStatusType
): boolean {
  const completeStatuses: LogisticsReturnShipmentStatusType[] = [
    LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.REFUNDED,
    LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.EXCHANGED,
    LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.COMPLETED,
    LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.CANCELLED,
    LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.REJECTED,
  ];
  return completeStatuses.includes(status);
}

export function logisticsReturnShipmentStatusIsActive(
  status: LogisticsReturnShipmentStatusType
): boolean {
  const activeStatuses: LogisticsReturnShipmentStatusType[] = [
    LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.APPROVED,
    LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.PENDING_PICKUP,
    LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.PICKED_UP,
    LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.IN_TRANSIT,
    LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.RECEIVED,
    LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.INSPECTING,
    LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.PROCESSING,
  ];
  return activeStatuses.includes(status);
}

export function logisticsReturnShipmentStatusCanTransition(
  status: LogisticsReturnShipmentStatusType,
  transition: LogisticsReturnShipmentStatusTransition
): boolean {
  const allowedTransitions: Record<
    LogisticsReturnShipmentStatusType,
    LogisticsReturnShipmentStatusTransition[]
  > = {
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.REQUESTED]: [
      LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS.REQUESTED_TO_APPROVED,
      LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS.REQUESTED_TO_REJECTED,
      LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS.ANY_TO_CANCELLED,
    ],
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.APPROVED]: [
      LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS.APPROVED_TO_PENDING_PICKUP,
      LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS.ANY_TO_CANCELLED,
    ],
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.PENDING_PICKUP]: [
      LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS.PENDING_PICKUP_TO_PICKED_UP,
    ],
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.PICKED_UP]: [
      LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS.PICKED_UP_TO_IN_TRANSIT,
    ],
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.IN_TRANSIT]: [
      LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS.IN_TRANSIT_TO_RECEIVED,
    ],
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.RECEIVED]: [
      LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS.RECEIVED_TO_INSPECTING,
    ],
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.INSPECTING]: [
      LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS.INSPECTING_TO_PROCESSING,
    ],
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.PROCESSING]: [
      LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS.PROCESSING_TO_REFUNDED,
      LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS.PROCESSING_TO_EXCHANGED,
    ],
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.REFUNDED]: [
      LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS.REFUNDED_TO_COMPLETED,
    ],
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.EXCHANGED]: [
      LOGISTICS_RETURN_SHIPMENT_STATUS.TRANSITIONS.EXCHANGED_TO_COMPLETED,
    ],
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.REJECTED]: [],
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.COMPLETED]: [],
    [LOGISTICS_RETURN_SHIPMENT_STATUS.TYPES.CANCELLED]: [],
  };
  return allowedTransitions[status]?.includes(transition) || false;
}
