/**
 * Return Reason Type Constants
 * Types of return reasons
 */

export const LOGISTICS_RETURN_REASON_TYPE = {
  // Reason Categories
  CATEGORIES: {
    PRODUCT_ISSUE: 'product_issue',
    DELIVERY_ISSUE: 'delivery_issue',
    CUSTOMER_REQUEST: 'customer_request',
    WARRANTY: 'warranty',
    OTHER: 'other',
  } as const,

  // Reason Icons (for UI)
  ICONS: {
    PRODUCT_ISSUE: '🛍️',
    DELIVERY_ISSUE: '🚚',
    CUSTOMER_REQUEST: '👤',
    WARRANTY: '🛡️',
    OTHER: '📋',
  } as const,

  // Reason Colors (for UI)
  COLORS: {
    PRODUCT_ISSUE: '#red-500',
    DELIVERY_ISSUE: '#orange-500',
    CUSTOMER_REQUEST: '#blue-500',
    WARRANTY: '#green-500',
    OTHER: '#gray-500',
  } as const,

  // Complexity Levels
  COMPLEXITY: {
    PRODUCT_ISSUE: 3,
    DELIVERY_ISSUE: 2,
    CUSTOMER_REQUEST: 1,
    WARRANTY: 4,
    OTHER: 2,
  } as const,

  // Resolution Time (in days)
  RESOLUTION_TIME: {
    PRODUCT_ISSUE: 5,
    DELIVERY_ISSUE: 3,
    CUSTOMER_REQUEST: 2,
    WARRANTY: 7,
    OTHER: 5,
  } as const,

  // Approval Required
  APPROVAL_REQUIRED: {
    PRODUCT_ISSUE: true,
    DELIVERY_ISSUE: false,
    CUSTOMER_REQUEST: false,
    WARRANTY: true,
    OTHER: false,
  } as const,
} as const;

// Reason Categories
export type LogisticsReturnReasonTypeCategory =
  (typeof LOGISTICS_RETURN_REASON_TYPE.CATEGORIES)[keyof typeof LOGISTICS_RETURN_REASON_TYPE.CATEGORIES];

// Reason Icons
export type LogisticsReturnReasonTypeIcon =
  (typeof LOGISTICS_RETURN_REASON_TYPE.ICONS)[keyof typeof LOGISTICS_RETURN_REASON_TYPE.ICONS];

// Reason Colors
export type LogisticsReturnReasonTypeColor =
  (typeof LOGISTICS_RETURN_REASON_TYPE.COLORS)[keyof typeof LOGISTICS_RETURN_REASON_TYPE.COLORS];

// Utility Functions
export function logisticsReturnReasonTypeGetLabel(
  category: LogisticsReturnReasonTypeCategory
): string {
  const labels: Record<LogisticsReturnReasonTypeCategory, string> = {
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.PRODUCT_ISSUE]: 'Product Issue',
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.DELIVERY_ISSUE]: 'Delivery Issue',
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.CUSTOMER_REQUEST]: 'Customer Request',
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.WARRANTY]: 'Warranty',
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.OTHER]: 'Other',
  };
  return labels[category] || 'Unknown';
}

export function logisticsReturnReasonTypeGetIcon(
  category: LogisticsReturnReasonTypeCategory
): LogisticsReturnReasonTypeIcon {
  const icons: Record<LogisticsReturnReasonTypeCategory, LogisticsReturnReasonTypeIcon> = {
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.PRODUCT_ISSUE]:
      LOGISTICS_RETURN_REASON_TYPE.ICONS.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.DELIVERY_ISSUE]:
      LOGISTICS_RETURN_REASON_TYPE.ICONS.DELIVERY_ISSUE,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.CUSTOMER_REQUEST]:
      LOGISTICS_RETURN_REASON_TYPE.ICONS.CUSTOMER_REQUEST,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.WARRANTY]: LOGISTICS_RETURN_REASON_TYPE.ICONS.WARRANTY,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.OTHER]: LOGISTICS_RETURN_REASON_TYPE.ICONS.OTHER,
  };
  return icons[category] || '📋';
}

export function logisticsReturnReasonTypeGetColor(
  category: LogisticsReturnReasonTypeCategory
): LogisticsReturnReasonTypeColor {
  const colors: Record<LogisticsReturnReasonTypeCategory, LogisticsReturnReasonTypeColor> = {
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.PRODUCT_ISSUE]:
      LOGISTICS_RETURN_REASON_TYPE.COLORS.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.DELIVERY_ISSUE]:
      LOGISTICS_RETURN_REASON_TYPE.COLORS.DELIVERY_ISSUE,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.CUSTOMER_REQUEST]:
      LOGISTICS_RETURN_REASON_TYPE.COLORS.CUSTOMER_REQUEST,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.WARRANTY]:
      LOGISTICS_RETURN_REASON_TYPE.COLORS.WARRANTY,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.OTHER]: LOGISTICS_RETURN_REASON_TYPE.COLORS.OTHER,
  };
  return colors[category] || '#gray-500';
}

export function logisticsReturnReasonTypeGetComplexity(
  category: LogisticsReturnReasonTypeCategory
): number {
  const complexity: Record<LogisticsReturnReasonTypeCategory, number> = {
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.PRODUCT_ISSUE]:
      LOGISTICS_RETURN_REASON_TYPE.COMPLEXITY.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.DELIVERY_ISSUE]:
      LOGISTICS_RETURN_REASON_TYPE.COMPLEXITY.DELIVERY_ISSUE,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.CUSTOMER_REQUEST]:
      LOGISTICS_RETURN_REASON_TYPE.COMPLEXITY.CUSTOMER_REQUEST,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.WARRANTY]:
      LOGISTICS_RETURN_REASON_TYPE.COMPLEXITY.WARRANTY,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.OTHER]: LOGISTICS_RETURN_REASON_TYPE.COMPLEXITY.OTHER,
  };
  return complexity[category] || 2;
}

export function logisticsReturnReasonTypeGetResolutionTime(
  category: LogisticsReturnReasonTypeCategory
): number {
  const times: Record<LogisticsReturnReasonTypeCategory, number> = {
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.PRODUCT_ISSUE]:
      LOGISTICS_RETURN_REASON_TYPE.RESOLUTION_TIME.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.DELIVERY_ISSUE]:
      LOGISTICS_RETURN_REASON_TYPE.RESOLUTION_TIME.DELIVERY_ISSUE,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.CUSTOMER_REQUEST]:
      LOGISTICS_RETURN_REASON_TYPE.RESOLUTION_TIME.CUSTOMER_REQUEST,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.WARRANTY]:
      LOGISTICS_RETURN_REASON_TYPE.RESOLUTION_TIME.WARRANTY,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.OTHER]:
      LOGISTICS_RETURN_REASON_TYPE.RESOLUTION_TIME.OTHER,
  };
  return times[category] || 5;
}

export function logisticsReturnReasonTypeNeedsApproval(
  category: LogisticsReturnReasonTypeCategory
): boolean {
  const approval: Record<LogisticsReturnReasonTypeCategory, boolean> = {
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.PRODUCT_ISSUE]:
      LOGISTICS_RETURN_REASON_TYPE.APPROVAL_REQUIRED.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.DELIVERY_ISSUE]:
      LOGISTICS_RETURN_REASON_TYPE.APPROVAL_REQUIRED.DELIVERY_ISSUE,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.CUSTOMER_REQUEST]:
      LOGISTICS_RETURN_REASON_TYPE.APPROVAL_REQUIRED.CUSTOMER_REQUEST,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.WARRANTY]:
      LOGISTICS_RETURN_REASON_TYPE.APPROVAL_REQUIRED.WARRANTY,
    [LOGISTICS_RETURN_REASON_TYPE.CATEGORIES.OTHER]:
      LOGISTICS_RETURN_REASON_TYPE.APPROVAL_REQUIRED.OTHER,
  };
  return approval[category] || false;
}
