/**
 * Return Reason Constants
 * Reasons for return shipments - Bangladesh based
 */

export const LOGISTICS_RETURN_REASON = {
  // Return Reasons
  REASONS: {
    DAMAGED: 'damaged',
    WRONG_ITEM: 'wrong_item',
    QUALITY_ISSUE: 'quality_issue',
    SIZE_ISSUE: 'size_issue',
    COLOR_ISSUE: 'color_issue',
    NOT_AS_DESCRIBED: 'not_as_described',
    DEFECTIVE: 'defective',
    EXPIRED: 'expired',
    FAKE_PRODUCT: 'fake_product',
    WRONG_SIZE: 'wrong_size',
    WRONG_COLOR: 'wrong_color',
    DELIVERY_FAILED: 'delivery_failed',
    CUSTOMER_CANCELLED: 'customer_cancelled',
    EXCHANGE: 'exchange',
    WARRANTY: 'warranty',
    OTHER: 'other',
  } as const,

  // Reason Categories
  CATEGORIES: {
    PRODUCT_ISSUE: 'product_issue',
    DELIVERY_ISSUE: 'delivery_issue',
    CUSTOMER_REQUEST: 'customer_request',
    WARRANTY: 'warranty',
    OTHER: 'other',
  } as const,

  // Reason Types
  TYPES: {
    CUSTOMER_INITIATED: 'customer_initiated',
    VENDOR_INITIATED: 'vendor_initiated',
    SYSTEM_INITIATED: 'system_initiated',
  } as const,

  // Reason Severities
  SEVERITIES: {
    CRITICAL: 'critical',
    HIGH: 'high',
    MEDIUM: 'medium',
    LOW: 'low',
  } as const,

  // Reason Priorities
  PRIORITIES: {
    CRITICAL: 5,
    HIGH: 4,
    MEDIUM: 3,
    LOW: 2,
  } as const,

  // Reason Labels (Bangla)
  BANGLA_LABELS: {
    DAMAGED: 'পণ্য নষ্ট',
    WRONG_ITEM: 'ভুল পণ্য',
    QUALITY_ISSUE: 'গুণগত মান সমস্যা',
    SIZE_ISSUE: 'সাইজ সমস্যা',
    COLOR_ISSUE: 'রঙ সমস্যা',
    NOT_AS_DESCRIBED: 'বর্ণনা অনুযায়ী নয়',
    DEFECTIVE: 'ত্রুটিপূর্ণ',
    EXPIRED: 'মেয়াদোত্তীর্ণ',
    FAKE_PRODUCT: 'নকল পণ্য',
    WRONG_SIZE: 'ভুল সাইজ',
    WRONG_COLOR: 'ভুল রঙ',
    DELIVERY_FAILED: 'ডেলিভারি ব্যর্থ',
    CUSTOMER_CANCELLED: 'গ্রাহক বাতিল',
    EXCHANGE: 'বিনিময়',
    WARRANTY: 'ওয়ারেন্টি',
    OTHER: 'অন্যান্য',
  } as const,
} as const;

// Return Reasons
export type LogisticsReturnReason =
  (typeof LOGISTICS_RETURN_REASON.REASONS)[keyof typeof LOGISTICS_RETURN_REASON.REASONS];

// Reason Categories
export type LogisticsReturnReasonCategory =
  (typeof LOGISTICS_RETURN_REASON.CATEGORIES)[keyof typeof LOGISTICS_RETURN_REASON.CATEGORIES];

// Reason Types
export type LogisticsReturnReasonType =
  (typeof LOGISTICS_RETURN_REASON.TYPES)[keyof typeof LOGISTICS_RETURN_REASON.TYPES];

// Reason Severities
export type LogisticsReturnReasonSeverity =
  (typeof LOGISTICS_RETURN_REASON.SEVERITIES)[keyof typeof LOGISTICS_RETURN_REASON.SEVERITIES];

// Utility Functions
export function logisticsReturnReasonGetLabel(reason: LogisticsReturnReason): string {
  const labels: Record<LogisticsReturnReason, string> = {
    [LOGISTICS_RETURN_REASON.REASONS.DAMAGED]: 'Damaged',
    [LOGISTICS_RETURN_REASON.REASONS.WRONG_ITEM]: 'Wrong Item',
    [LOGISTICS_RETURN_REASON.REASONS.QUALITY_ISSUE]: 'Quality Issue',
    [LOGISTICS_RETURN_REASON.REASONS.SIZE_ISSUE]: 'Size Issue',
    [LOGISTICS_RETURN_REASON.REASONS.COLOR_ISSUE]: 'Color Issue',
    [LOGISTICS_RETURN_REASON.REASONS.NOT_AS_DESCRIBED]: 'Not as Described',
    [LOGISTICS_RETURN_REASON.REASONS.DEFECTIVE]: 'Defective',
    [LOGISTICS_RETURN_REASON.REASONS.EXPIRED]: 'Expired',
    [LOGISTICS_RETURN_REASON.REASONS.FAKE_PRODUCT]: 'Fake Product',
    [LOGISTICS_RETURN_REASON.REASONS.WRONG_SIZE]: 'Wrong Size',
    [LOGISTICS_RETURN_REASON.REASONS.WRONG_COLOR]: 'Wrong Color',
    [LOGISTICS_RETURN_REASON.REASONS.DELIVERY_FAILED]: 'Delivery Failed',
    [LOGISTICS_RETURN_REASON.REASONS.CUSTOMER_CANCELLED]: 'Customer Cancelled',
    [LOGISTICS_RETURN_REASON.REASONS.EXCHANGE]: 'Exchange',
    [LOGISTICS_RETURN_REASON.REASONS.WARRANTY]: 'Warranty',
    [LOGISTICS_RETURN_REASON.REASONS.OTHER]: 'Other',
  };
  return labels[reason] || 'Unknown';
}

export function logisticsReturnReasonGetBanglaLabel(reason: LogisticsReturnReason): string {
  const labels: Record<LogisticsReturnReason, string> = {
    [LOGISTICS_RETURN_REASON.REASONS.DAMAGED]: LOGISTICS_RETURN_REASON.BANGLA_LABELS.DAMAGED,
    [LOGISTICS_RETURN_REASON.REASONS.WRONG_ITEM]: LOGISTICS_RETURN_REASON.BANGLA_LABELS.WRONG_ITEM,
    [LOGISTICS_RETURN_REASON.REASONS.QUALITY_ISSUE]:
      LOGISTICS_RETURN_REASON.BANGLA_LABELS.QUALITY_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.SIZE_ISSUE]: LOGISTICS_RETURN_REASON.BANGLA_LABELS.SIZE_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.COLOR_ISSUE]:
      LOGISTICS_RETURN_REASON.BANGLA_LABELS.COLOR_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.NOT_AS_DESCRIBED]:
      LOGISTICS_RETURN_REASON.BANGLA_LABELS.NOT_AS_DESCRIBED,
    [LOGISTICS_RETURN_REASON.REASONS.DEFECTIVE]: LOGISTICS_RETURN_REASON.BANGLA_LABELS.DEFECTIVE,
    [LOGISTICS_RETURN_REASON.REASONS.EXPIRED]: LOGISTICS_RETURN_REASON.BANGLA_LABELS.EXPIRED,
    [LOGISTICS_RETURN_REASON.REASONS.FAKE_PRODUCT]:
      LOGISTICS_RETURN_REASON.BANGLA_LABELS.FAKE_PRODUCT,
    [LOGISTICS_RETURN_REASON.REASONS.WRONG_SIZE]: LOGISTICS_RETURN_REASON.BANGLA_LABELS.WRONG_SIZE,
    [LOGISTICS_RETURN_REASON.REASONS.WRONG_COLOR]:
      LOGISTICS_RETURN_REASON.BANGLA_LABELS.WRONG_COLOR,
    [LOGISTICS_RETURN_REASON.REASONS.DELIVERY_FAILED]:
      LOGISTICS_RETURN_REASON.BANGLA_LABELS.DELIVERY_FAILED,
    [LOGISTICS_RETURN_REASON.REASONS.CUSTOMER_CANCELLED]:
      LOGISTICS_RETURN_REASON.BANGLA_LABELS.CUSTOMER_CANCELLED,
    [LOGISTICS_RETURN_REASON.REASONS.EXCHANGE]: LOGISTICS_RETURN_REASON.BANGLA_LABELS.EXCHANGE,
    [LOGISTICS_RETURN_REASON.REASONS.WARRANTY]: LOGISTICS_RETURN_REASON.BANGLA_LABELS.WARRANTY,
    [LOGISTICS_RETURN_REASON.REASONS.OTHER]: LOGISTICS_RETURN_REASON.BANGLA_LABELS.OTHER,
  };
  return labels[reason] || 'Unknown';
}

export function logisticsReturnReasonGetCategory(
  reason: LogisticsReturnReason
): LogisticsReturnReasonCategory {
  const categories: Record<LogisticsReturnReason, LogisticsReturnReasonCategory> = {
    [LOGISTICS_RETURN_REASON.REASONS.DAMAGED]: LOGISTICS_RETURN_REASON.CATEGORIES.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.WRONG_ITEM]: LOGISTICS_RETURN_REASON.CATEGORIES.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.QUALITY_ISSUE]:
      LOGISTICS_RETURN_REASON.CATEGORIES.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.SIZE_ISSUE]: LOGISTICS_RETURN_REASON.CATEGORIES.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.COLOR_ISSUE]: LOGISTICS_RETURN_REASON.CATEGORIES.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.NOT_AS_DESCRIBED]:
      LOGISTICS_RETURN_REASON.CATEGORIES.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.DEFECTIVE]: LOGISTICS_RETURN_REASON.CATEGORIES.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.EXPIRED]: LOGISTICS_RETURN_REASON.CATEGORIES.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.FAKE_PRODUCT]:
      LOGISTICS_RETURN_REASON.CATEGORIES.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.WRONG_SIZE]: LOGISTICS_RETURN_REASON.CATEGORIES.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.WRONG_COLOR]: LOGISTICS_RETURN_REASON.CATEGORIES.PRODUCT_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.DELIVERY_FAILED]:
      LOGISTICS_RETURN_REASON.CATEGORIES.DELIVERY_ISSUE,
    [LOGISTICS_RETURN_REASON.REASONS.CUSTOMER_CANCELLED]:
      LOGISTICS_RETURN_REASON.CATEGORIES.CUSTOMER_REQUEST,
    [LOGISTICS_RETURN_REASON.REASONS.EXCHANGE]: LOGISTICS_RETURN_REASON.CATEGORIES.CUSTOMER_REQUEST,
    [LOGISTICS_RETURN_REASON.REASONS.WARRANTY]: LOGISTICS_RETURN_REASON.CATEGORIES.WARRANTY,
    [LOGISTICS_RETURN_REASON.REASONS.OTHER]: LOGISTICS_RETURN_REASON.CATEGORIES.OTHER,
  };
  return categories[reason] || LOGISTICS_RETURN_REASON.CATEGORIES.OTHER;
}

export function logisticsReturnReasonGetPriority(reason: LogisticsReturnReason): number {
  const priorities: Record<LogisticsReturnReason, number> = {
    [LOGISTICS_RETURN_REASON.REASONS.DAMAGED]: LOGISTICS_RETURN_REASON.PRIORITIES.HIGH,
    [LOGISTICS_RETURN_REASON.REASONS.WRONG_ITEM]: LOGISTICS_RETURN_REASON.PRIORITIES.MEDIUM,
    [LOGISTICS_RETURN_REASON.REASONS.QUALITY_ISSUE]: LOGISTICS_RETURN_REASON.PRIORITIES.HIGH,
    [LOGISTICS_RETURN_REASON.REASONS.SIZE_ISSUE]: LOGISTICS_RETURN_REASON.PRIORITIES.LOW,
    [LOGISTICS_RETURN_REASON.REASONS.COLOR_ISSUE]: LOGISTICS_RETURN_REASON.PRIORITIES.LOW,
    [LOGISTICS_RETURN_REASON.REASONS.NOT_AS_DESCRIBED]: LOGISTICS_RETURN_REASON.PRIORITIES.MEDIUM,
    [LOGISTICS_RETURN_REASON.REASONS.DEFECTIVE]: LOGISTICS_RETURN_REASON.PRIORITIES.CRITICAL,
    [LOGISTICS_RETURN_REASON.REASONS.EXPIRED]: LOGISTICS_RETURN_REASON.PRIORITIES.CRITICAL,
    [LOGISTICS_RETURN_REASON.REASONS.FAKE_PRODUCT]: LOGISTICS_RETURN_REASON.PRIORITIES.CRITICAL,
    [LOGISTICS_RETURN_REASON.REASONS.WRONG_SIZE]: LOGISTICS_RETURN_REASON.PRIORITIES.MEDIUM,
    [LOGISTICS_RETURN_REASON.REASONS.WRONG_COLOR]: LOGISTICS_RETURN_REASON.PRIORITIES.MEDIUM,
    [LOGISTICS_RETURN_REASON.REASONS.DELIVERY_FAILED]: LOGISTICS_RETURN_REASON.PRIORITIES.HIGH,
    [LOGISTICS_RETURN_REASON.REASONS.CUSTOMER_CANCELLED]: LOGISTICS_RETURN_REASON.PRIORITIES.LOW,
    [LOGISTICS_RETURN_REASON.REASONS.EXCHANGE]: LOGISTICS_RETURN_REASON.PRIORITIES.MEDIUM,
    [LOGISTICS_RETURN_REASON.REASONS.WARRANTY]: LOGISTICS_RETURN_REASON.PRIORITIES.MEDIUM,
    [LOGISTICS_RETURN_REASON.REASONS.OTHER]: LOGISTICS_RETURN_REASON.PRIORITIES.LOW,
  };
  return priorities[reason] || LOGISTICS_RETURN_REASON.PRIORITIES.MEDIUM;
}

export function logisticsReturnReasonIsProductIssue(reason: LogisticsReturnReason): boolean {
  const productIssues: LogisticsReturnReason[] = [
    LOGISTICS_RETURN_REASON.REASONS.DAMAGED,
    LOGISTICS_RETURN_REASON.REASONS.WRONG_ITEM,
    LOGISTICS_RETURN_REASON.REASONS.QUALITY_ISSUE,
    LOGISTICS_RETURN_REASON.REASONS.SIZE_ISSUE,
    LOGISTICS_RETURN_REASON.REASONS.COLOR_ISSUE,
    LOGISTICS_RETURN_REASON.REASONS.NOT_AS_DESCRIBED,
    LOGISTICS_RETURN_REASON.REASONS.DEFECTIVE,
    LOGISTICS_RETURN_REASON.REASONS.EXPIRED,
    LOGISTICS_RETURN_REASON.REASONS.FAKE_PRODUCT,
    LOGISTICS_RETURN_REASON.REASONS.WRONG_SIZE,
    LOGISTICS_RETURN_REASON.REASONS.WRONG_COLOR,
  ];
  return productIssues.includes(reason);
}
