/**
 * FAQ Category Constants
 * Categories for frequently asked questions
 */

export const SUPPORT_FAQ_CATEGORY = {
  // Category Types
  TYPES: {
    GENERAL: 'general',
    ACCOUNT: 'account',
    PAYMENT: 'payment',
    ORDER: 'order',
    SHIPPING: 'shipping',
    PRODUCT: 'product',
    TECHNICAL: 'technical',
    BILLING: 'billing',
    SECURITY: 'security',
    PRIVACY: 'privacy',
    LEGAL: 'legal',
    RETURN: 'return',
    REFUND: 'refund',
    WARRANTY: 'warranty',
    COMPLAINT: 'complaint',
    FEEDBACK: 'feedback',
  } as const,

  // Category Icons (for UI)
  ICONS: {
    GENERAL: '📋',
    ACCOUNT: '👤',
    PAYMENT: '💳',
    ORDER: '📦',
    SHIPPING: '🚚',
    PRODUCT: '🛍️',
    TECHNICAL: '🔧',
    BILLING: '💰',
    SECURITY: '🔒',
    PRIVACY: '🔐',
    LEGAL: '⚖️',
    RETURN: '↩️',
    REFUND: '💸',
    WARRANTY: '🛡️',
    COMPLAINT: '😤',
    FEEDBACK: '💬',
  } as const,

  // Category Colors (for UI)
  COLORS: {
    GENERAL: '#gray-500',
    ACCOUNT: '#blue-500',
    PAYMENT: '#green-500',
    ORDER: '#purple-500',
    SHIPPING: '#orange-500',
    PRODUCT: '#pink-500',
    TECHNICAL: '#red-500',
    BILLING: '#yellow-500',
    SECURITY: '#red-600',
    PRIVACY: '#purple-600',
    LEGAL: '#gray-700',
    RETURN: '#blue-400',
    REFUND: '#green-400',
    WARRANTY: '#teal-500',
    COMPLAINT: '#red-700',
    FEEDBACK: '#indigo-500',
  } as const,

  // Category Priorities
  PRIORITIES: {
    GENERAL: 'low',
    ACCOUNT: 'high',
    PAYMENT: 'high',
    ORDER: 'medium',
    SHIPPING: 'medium',
    PRODUCT: 'medium',
    TECHNICAL: 'high',
    BILLING: 'high',
    SECURITY: 'critical',
    PRIVACY: 'high',
    LEGAL: 'high',
    RETURN: 'medium',
    REFUND: 'high',
    WARRANTY: 'medium',
    COMPLAINT: 'high',
    FEEDBACK: 'low',
  } as const,
} as const;

// Category Types
export type SupportFaqCategoryType =
  (typeof SUPPORT_FAQ_CATEGORY.TYPES)[keyof typeof SUPPORT_FAQ_CATEGORY.TYPES];

// Category Icons
export type SupportFaqCategoryIcon =
  (typeof SUPPORT_FAQ_CATEGORY.ICONS)[keyof typeof SUPPORT_FAQ_CATEGORY.ICONS];

// Category Colors
export type SupportFaqCategoryColor =
  (typeof SUPPORT_FAQ_CATEGORY.COLORS)[keyof typeof SUPPORT_FAQ_CATEGORY.COLORS];

// Utility Functions
export function supportFaqCategoryGetLabel(category: SupportFaqCategoryType): string {
  const labels: Record<SupportFaqCategoryType, string> = {
    [SUPPORT_FAQ_CATEGORY.TYPES.GENERAL]: 'General',
    [SUPPORT_FAQ_CATEGORY.TYPES.ACCOUNT]: 'Account',
    [SUPPORT_FAQ_CATEGORY.TYPES.PAYMENT]: 'Payment',
    [SUPPORT_FAQ_CATEGORY.TYPES.ORDER]: 'Order',
    [SUPPORT_FAQ_CATEGORY.TYPES.SHIPPING]: 'Shipping',
    [SUPPORT_FAQ_CATEGORY.TYPES.PRODUCT]: 'Product',
    [SUPPORT_FAQ_CATEGORY.TYPES.TECHNICAL]: 'Technical',
    [SUPPORT_FAQ_CATEGORY.TYPES.BILLING]: 'Billing',
    [SUPPORT_FAQ_CATEGORY.TYPES.SECURITY]: 'Security',
    [SUPPORT_FAQ_CATEGORY.TYPES.PRIVACY]: 'Privacy',
    [SUPPORT_FAQ_CATEGORY.TYPES.LEGAL]: 'Legal',
    [SUPPORT_FAQ_CATEGORY.TYPES.RETURN]: 'Return',
    [SUPPORT_FAQ_CATEGORY.TYPES.REFUND]: 'Refund',
    [SUPPORT_FAQ_CATEGORY.TYPES.WARRANTY]: 'Warranty',
    [SUPPORT_FAQ_CATEGORY.TYPES.COMPLAINT]: 'Complaint',
    [SUPPORT_FAQ_CATEGORY.TYPES.FEEDBACK]: 'Feedback',
  };
  return labels[category] || 'Unknown';
}

export function supportFaqCategoryGetIcon(
  category: SupportFaqCategoryType
): SupportFaqCategoryIcon {
  const icons: Record<SupportFaqCategoryType, SupportFaqCategoryIcon> = {
    [SUPPORT_FAQ_CATEGORY.TYPES.GENERAL]: SUPPORT_FAQ_CATEGORY.ICONS.GENERAL,
    [SUPPORT_FAQ_CATEGORY.TYPES.ACCOUNT]: SUPPORT_FAQ_CATEGORY.ICONS.ACCOUNT,
    [SUPPORT_FAQ_CATEGORY.TYPES.PAYMENT]: SUPPORT_FAQ_CATEGORY.ICONS.PAYMENT,
    [SUPPORT_FAQ_CATEGORY.TYPES.ORDER]: SUPPORT_FAQ_CATEGORY.ICONS.ORDER,
    [SUPPORT_FAQ_CATEGORY.TYPES.SHIPPING]: SUPPORT_FAQ_CATEGORY.ICONS.SHIPPING,
    [SUPPORT_FAQ_CATEGORY.TYPES.PRODUCT]: SUPPORT_FAQ_CATEGORY.ICONS.PRODUCT,
    [SUPPORT_FAQ_CATEGORY.TYPES.TECHNICAL]: SUPPORT_FAQ_CATEGORY.ICONS.TECHNICAL,
    [SUPPORT_FAQ_CATEGORY.TYPES.BILLING]: SUPPORT_FAQ_CATEGORY.ICONS.BILLING,
    [SUPPORT_FAQ_CATEGORY.TYPES.SECURITY]: SUPPORT_FAQ_CATEGORY.ICONS.SECURITY,
    [SUPPORT_FAQ_CATEGORY.TYPES.PRIVACY]: SUPPORT_FAQ_CATEGORY.ICONS.PRIVACY,
    [SUPPORT_FAQ_CATEGORY.TYPES.LEGAL]: SUPPORT_FAQ_CATEGORY.ICONS.LEGAL,
    [SUPPORT_FAQ_CATEGORY.TYPES.RETURN]: SUPPORT_FAQ_CATEGORY.ICONS.RETURN,
    [SUPPORT_FAQ_CATEGORY.TYPES.REFUND]: SUPPORT_FAQ_CATEGORY.ICONS.REFUND,
    [SUPPORT_FAQ_CATEGORY.TYPES.WARRANTY]: SUPPORT_FAQ_CATEGORY.ICONS.WARRANTY,
    [SUPPORT_FAQ_CATEGORY.TYPES.COMPLAINT]: SUPPORT_FAQ_CATEGORY.ICONS.COMPLAINT,
    [SUPPORT_FAQ_CATEGORY.TYPES.FEEDBACK]: SUPPORT_FAQ_CATEGORY.ICONS.FEEDBACK,
  };
  return icons[category] || '📋';
}

export function supportFaqCategoryGetColor(
  category: SupportFaqCategoryType
): SupportFaqCategoryColor {
  const colors: Record<SupportFaqCategoryType, SupportFaqCategoryColor> = {
    [SUPPORT_FAQ_CATEGORY.TYPES.GENERAL]: SUPPORT_FAQ_CATEGORY.COLORS.GENERAL,
    [SUPPORT_FAQ_CATEGORY.TYPES.ACCOUNT]: SUPPORT_FAQ_CATEGORY.COLORS.ACCOUNT,
    [SUPPORT_FAQ_CATEGORY.TYPES.PAYMENT]: SUPPORT_FAQ_CATEGORY.COLORS.PAYMENT,
    [SUPPORT_FAQ_CATEGORY.TYPES.ORDER]: SUPPORT_FAQ_CATEGORY.COLORS.ORDER,
    [SUPPORT_FAQ_CATEGORY.TYPES.SHIPPING]: SUPPORT_FAQ_CATEGORY.COLORS.SHIPPING,
    [SUPPORT_FAQ_CATEGORY.TYPES.PRODUCT]: SUPPORT_FAQ_CATEGORY.COLORS.PRODUCT,
    [SUPPORT_FAQ_CATEGORY.TYPES.TECHNICAL]: SUPPORT_FAQ_CATEGORY.COLORS.TECHNICAL,
    [SUPPORT_FAQ_CATEGORY.TYPES.BILLING]: SUPPORT_FAQ_CATEGORY.COLORS.BILLING,
    [SUPPORT_FAQ_CATEGORY.TYPES.SECURITY]: SUPPORT_FAQ_CATEGORY.COLORS.SECURITY,
    [SUPPORT_FAQ_CATEGORY.TYPES.PRIVACY]: SUPPORT_FAQ_CATEGORY.COLORS.PRIVACY,
    [SUPPORT_FAQ_CATEGORY.TYPES.LEGAL]: SUPPORT_FAQ_CATEGORY.COLORS.LEGAL,
    [SUPPORT_FAQ_CATEGORY.TYPES.RETURN]: SUPPORT_FAQ_CATEGORY.COLORS.RETURN,
    [SUPPORT_FAQ_CATEGORY.TYPES.REFUND]: SUPPORT_FAQ_CATEGORY.COLORS.REFUND,
    [SUPPORT_FAQ_CATEGORY.TYPES.WARRANTY]: SUPPORT_FAQ_CATEGORY.COLORS.WARRANTY,
    [SUPPORT_FAQ_CATEGORY.TYPES.COMPLAINT]: SUPPORT_FAQ_CATEGORY.COLORS.COMPLAINT,
    [SUPPORT_FAQ_CATEGORY.TYPES.FEEDBACK]: SUPPORT_FAQ_CATEGORY.COLORS.FEEDBACK,
  };
  return colors[category] || '#gray-400';
}

export function supportFaqCategoryGetPriority(category: SupportFaqCategoryType): string {
  const priorities: Record<SupportFaqCategoryType, string> = {
    [SUPPORT_FAQ_CATEGORY.TYPES.GENERAL]: SUPPORT_FAQ_CATEGORY.PRIORITIES.GENERAL,
    [SUPPORT_FAQ_CATEGORY.TYPES.ACCOUNT]: SUPPORT_FAQ_CATEGORY.PRIORITIES.ACCOUNT,
    [SUPPORT_FAQ_CATEGORY.TYPES.PAYMENT]: SUPPORT_FAQ_CATEGORY.PRIORITIES.PAYMENT,
    [SUPPORT_FAQ_CATEGORY.TYPES.ORDER]: SUPPORT_FAQ_CATEGORY.PRIORITIES.ORDER,
    [SUPPORT_FAQ_CATEGORY.TYPES.SHIPPING]: SUPPORT_FAQ_CATEGORY.PRIORITIES.SHIPPING,
    [SUPPORT_FAQ_CATEGORY.TYPES.PRODUCT]: SUPPORT_FAQ_CATEGORY.PRIORITIES.PRODUCT,
    [SUPPORT_FAQ_CATEGORY.TYPES.TECHNICAL]: SUPPORT_FAQ_CATEGORY.PRIORITIES.TECHNICAL,
    [SUPPORT_FAQ_CATEGORY.TYPES.BILLING]: SUPPORT_FAQ_CATEGORY.PRIORITIES.BILLING,
    [SUPPORT_FAQ_CATEGORY.TYPES.SECURITY]: SUPPORT_FAQ_CATEGORY.PRIORITIES.SECURITY,
    [SUPPORT_FAQ_CATEGORY.TYPES.PRIVACY]: SUPPORT_FAQ_CATEGORY.PRIORITIES.PRIVACY,
    [SUPPORT_FAQ_CATEGORY.TYPES.LEGAL]: SUPPORT_FAQ_CATEGORY.PRIORITIES.LEGAL,
    [SUPPORT_FAQ_CATEGORY.TYPES.RETURN]: SUPPORT_FAQ_CATEGORY.PRIORITIES.RETURN,
    [SUPPORT_FAQ_CATEGORY.TYPES.REFUND]: SUPPORT_FAQ_CATEGORY.PRIORITIES.REFUND,
    [SUPPORT_FAQ_CATEGORY.TYPES.WARRANTY]: SUPPORT_FAQ_CATEGORY.PRIORITIES.WARRANTY,
    [SUPPORT_FAQ_CATEGORY.TYPES.COMPLAINT]: SUPPORT_FAQ_CATEGORY.PRIORITIES.COMPLAINT,
    [SUPPORT_FAQ_CATEGORY.TYPES.FEEDBACK]: SUPPORT_FAQ_CATEGORY.PRIORITIES.FEEDBACK,
  };
  return priorities[category] || 'medium';
}
