import { REPORT_STATUS } from './report-status.constants';
import { REPORT_TYPE } from './report-type.constants';
import { REPORT_FORMAT, REPORT_FORMAT_MIME, REPORT_FORMAT_LIMIT } from './report-format.constants';
import {
  REPORT_PRIORITY,
  REPORT_PRIORITY_WEIGHT,
  REPORT_PRIORITY_SLA_SECONDS,
} from './report-priority.constants';
import {
  REPORT_SCHEDULE_TYPE,
  REPORT_SCHEDULE_FREQUENCY,
  REPORT_SCHEDULE_STATUS,
  REPORT_SCHEDULE,
} from './report-schedule.constants';
import {
  REPORT_TEMPLATE_TYPE,
  REPORT_TEMPLATE_CATEGORY,
  REPORT_TEMPLATE_STATUS,
  REPORT_TEMPLATE,
} from './report-template.constants';
import {
  REPORT_DASHBOARD_TYPE,
  REPORT_DASHBOARD_STATUS,
  REPORT_DASHBOARD_LAYOUT,
  REPORT_DASHBOARD,
} from './report-dashboard.constants';
import {
  REPORT_WIDGET_TYPE,
  REPORT_WIDGET_SIZE,
  REPORT_WIDGET_STATUS,
  REPORT_WIDGET,
} from './report-widget.constants';
import {
  REPORT_FILTER_OPERATOR,
  REPORT_FILTER_LOGIC,
  REPORT_FILTER_TYPE,
  REPORT_FILTER,
} from './report-filter.constants';
import {
  REPORT_EXPORT_TYPE,
  REPORT_EXPORT_STATUS,
  REPORT_EXPORT_DESTINATION,
  REPORT_EXPORT,
} from './report-export.constants';
import {
  REPORT_EMAIL_TYPE,
  REPORT_EMAIL_STATUS,
  REPORT_EMAIL_FORMAT,
  REPORT_EMAIL,
} from './report-email.constants';
import { REPORT_PERMISSION } from './report-permission.constants';

export const REPORTING_LIMIT = {
  MAX_REPORTS: 10000,
  MAX_DASHBOARDS: 1000,
  MAX_WIDGETS_PER_DASHBOARD: 50,
  MAX_TEMPLATES: 1000,
  MAX_SCHEDULES: 5000,
  MAX_EXPORTS_PER_DAY: 1000,
  MAX_ROWS_PER_REPORT: 1000000,
  MAX_DATE_RANGE_DAYS: 730,
  QUERY_TIMEOUT_SECONDS: 60,
  CACHE_TTL_SECONDS: 300,
  RETENTION_DAYS: 365,
} as const;

export const REPORTING = {
  TYPE: REPORT_TYPE,
  STATUS: REPORT_STATUS,
  LIMIT: REPORTING_LIMIT,

  FORMAT: {
    TYPE: REPORT_FORMAT,
    MIME: REPORT_FORMAT_MIME,
    LIMIT: REPORT_FORMAT_LIMIT,
  },

  PRIORITY: {
    TYPE: REPORT_PRIORITY,
    WEIGHT: REPORT_PRIORITY_WEIGHT,
    SLA_SECONDS: REPORT_PRIORITY_SLA_SECONDS,
  },

  SCHEDULE: {
    TYPE: REPORT_SCHEDULE_TYPE,
    FREQUENCY: REPORT_SCHEDULE_FREQUENCY,
    STATUS: REPORT_SCHEDULE_STATUS,
    LIMIT: REPORT_SCHEDULE,
  },

  TEMPLATE: {
    TYPE: REPORT_TEMPLATE_TYPE,
    CATEGORY: REPORT_TEMPLATE_CATEGORY,
    STATUS: REPORT_TEMPLATE_STATUS,
    LIMIT: REPORT_TEMPLATE,
  },

  DASHBOARD: {
    TYPE: REPORT_DASHBOARD_TYPE,
    STATUS: REPORT_DASHBOARD_STATUS,
    LAYOUT: REPORT_DASHBOARD_LAYOUT,
    LIMIT: REPORT_DASHBOARD,
  },

  WIDGET: {
    TYPE: REPORT_WIDGET_TYPE,
    SIZE: REPORT_WIDGET_SIZE,
    STATUS: REPORT_WIDGET_STATUS,
    LIMIT: REPORT_WIDGET,
  },

  FILTER: {
    OPERATOR: REPORT_FILTER_OPERATOR,
    LOGIC: REPORT_FILTER_LOGIC,
    TYPE: REPORT_FILTER_TYPE,
    LIMIT: REPORT_FILTER,
  },

  EXPORT: {
    TYPE: REPORT_EXPORT_TYPE,
    STATUS: REPORT_EXPORT_STATUS,
    DESTINATION: REPORT_EXPORT_DESTINATION,
    LIMIT: REPORT_EXPORT,
  },

  EMAIL: {
    TYPE: REPORT_EMAIL_TYPE,
    STATUS: REPORT_EMAIL_STATUS,
    FORMAT: REPORT_EMAIL_FORMAT,
    LIMIT: REPORT_EMAIL,
  },

  PERMISSION: REPORT_PERMISSION,
} as const;

export type ReportingType = typeof REPORTING;
