/**
 * AI Recommendation Scope Constants
 * Scope definitions for recommendation targeting
 */

export const AI_RECOMMENDATION_SCOPE = {
  // Scope Levels
  LEVELS: {
    GLOBAL: 'global',
    SITE_WIDE: 'site_wide',
    PAGE: 'page',
    SECTION: 'section',
    WIDGET: 'widget',
  } as const,

  // Scope Contexts
  CONTEXTS: {
    // User Context
    USER: 'user',
    USER_SEGMENT: 'user_segment',
    USER_GROUP: 'user_group',

    // Product Context
    PRODUCT: 'product',
    PRODUCT_CATEGORY: 'product_category',
    PRODUCT_BRAND: 'product_brand',

    // Shopping Context
    BROWSE: 'browse',
    SEARCH: 'search',
    CART: 'cart',
    CHECKOUT: 'checkout',
    WISHLIST: 'wishlist',

    // Location Context
    GEOGRAPHIC: 'geographic',
    REGIONAL: 'regional',
    LOCAL: 'local',
    STORE: 'store',

    // Time Context
    TIME_BASED: 'time_based',
    SEASONAL: 'seasonal',
    TEMPORAL: 'temporal',

    // Device Context
    DEVICE: 'device',
    PLATFORM: 'platform',
    BROWSER: 'browser',

    // Marketing Context
    CAMPAIGN: 'campaign',
    CHANNEL: 'channel',
    SOURCE: 'source',
  } as const,

  // Scope Types
  TYPES: {
    // Personalization Scopes
    PERSONALIZED: 'personalized',
    SEGMENTED: 'segmented',
    GROUPED: 'grouped',
    GENERAL: 'general',

    // Targeting Scopes
    CROSS_SELL: 'cross_sell',
    UP_SELL: 'up_sell',
    COMPLEMENTARY: 'complementary',
    SUBSTITUTE: 'substitute',

    // Behavior Scopes
    RECENT_VIEWS: 'recent_views',
    FREQUENT_PURCHASES: 'frequent_purchases',
    BROWSE_HISTORY: 'browse_history',
    SEARCH_HISTORY: 'search_history',
    CART_HISTORY: 'cart_history',

    // Social Scopes
    SOCIAL_TRENDS: 'social_trends',
    COMMUNITY_FAVORITES: 'community_favorites',
    FRIEND_ACTIVITY: 'friend_activity',

    // Content Scopes
    CATEGORY_BASED: 'category_based',
    TAG_BASED: 'tag_based',
    TOPIC_BASED: 'topic_based',
    THEME_BASED: 'theme_based',

    // Timing Scopes
    REAL_TIME: 'real_time',
    RECENT: 'recent',
    HISTORICAL: 'historical',
    FUTURE_PREDICTED: 'future_predicted',

    // Contextual Scopes
    MOMENT_BASED: 'moment_based',
    LOCATION_BASED: 'location_based',
    WEATHER_BASED: 'weather_based',
    EVENT_BASED: 'event_based',
  } as const,

  // Scope Rules
  RULES: {
    INCLUDE_ALL: 'include_all',
    INCLUDE_ANY: 'include_any',
    EXCLUDE_ALL: 'exclude_all',
    EXCLUDE_ANY: 'exclude_any',
    PRIORITIZE: 'prioritize',
    DEPRIORITIZE: 'deprioritize',
    BOOST: 'boost',
    SUPPRESS: 'suppress',
  } as const,

  // Scope Priorities
  PRIORITIES: {
    CRITICAL: 10,
    HIGH: 8,
    MEDIUM: 5,
    LOW: 3,
    MINIMAL: 1,
  } as const,

  // Scope Weights
  WEIGHTS: {
    USER: 0.4,
    SESSION: 0.3,
    CONTEXT: 0.2,
    DEVICE: 0.05,
    LOCATION: 0.05,
  } as const,
} as const;

export type AIRecommendationScopeLevel =
  (typeof AI_RECOMMENDATION_SCOPE.LEVELS)[keyof typeof AI_RECOMMENDATION_SCOPE.LEVELS];
export type AIRecommendationScopeContext =
  (typeof AI_RECOMMENDATION_SCOPE.CONTEXTS)[keyof typeof AI_RECOMMENDATION_SCOPE.CONTEXTS];
export type AIRecommendationScopeType =
  (typeof AI_RECOMMENDATION_SCOPE.TYPES)[keyof typeof AI_RECOMMENDATION_SCOPE.TYPES];
export type AIRecommendationScopeRule =
  (typeof AI_RECOMMENDATION_SCOPE.RULES)[keyof typeof AI_RECOMMENDATION_SCOPE.RULES];
export type AIRecommendationScopePriority =
  (typeof AI_RECOMMENDATION_SCOPE.PRIORITIES)[keyof typeof AI_RECOMMENDATION_SCOPE.PRIORITIES];
export type AIRecommendationScopeWeight =
  (typeof AI_RECOMMENDATION_SCOPE.WEIGHTS)[keyof typeof AI_RECOMMENDATION_SCOPE.WEIGHTS];

export function getAiRecommendationScopeLevelLabel(level: AIRecommendationScopeLevel): string {
  const labels: Record<AIRecommendationScopeLevel, string> = {
    [AI_RECOMMENDATION_SCOPE.LEVELS.GLOBAL]: 'Global',
    [AI_RECOMMENDATION_SCOPE.LEVELS.SITE_WIDE]: 'Site Wide',
    [AI_RECOMMENDATION_SCOPE.LEVELS.PAGE]: 'Page',
    [AI_RECOMMENDATION_SCOPE.LEVELS.SECTION]: 'Section',
    [AI_RECOMMENDATION_SCOPE.LEVELS.WIDGET]: 'Widget',
  };
  return labels[level] || 'Unknown';
}

export function getAiRecommendationScopeContextLabel(
  context: AIRecommendationScopeContext
): string {
  const labels: Record<AIRecommendationScopeContext, string> = {
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.USER]: 'User',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.USER_SEGMENT]: 'User Segment',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.USER_GROUP]: 'User Group',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.PRODUCT]: 'Product',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.PRODUCT_CATEGORY]: 'Product Category',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.PRODUCT_BRAND]: 'Product Brand',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.BROWSE]: 'Browse',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.SEARCH]: 'Search',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.CART]: 'Cart',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.CHECKOUT]: 'Checkout',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.WISHLIST]: 'Wishlist',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.GEOGRAPHIC]: 'Geographic',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.REGIONAL]: 'Regional',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.LOCAL]: 'Local',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.STORE]: 'Store',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.TIME_BASED]: 'Time Based',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.SEASONAL]: 'Seasonal',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.TEMPORAL]: 'Temporal',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.DEVICE]: 'Device',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.PLATFORM]: 'Platform',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.BROWSER]: 'Browser',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.CAMPAIGN]: 'Campaign',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.CHANNEL]: 'Channel',
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.SOURCE]: 'Source',
  };
  return labels[context] || 'Unknown';
}

export function getAiRecommendationScopeTypeLabel(type: AIRecommendationScopeType): string {
  const labels: Record<AIRecommendationScopeType, string> = {
    [AI_RECOMMENDATION_SCOPE.TYPES.PERSONALIZED]: 'Personalized',
    [AI_RECOMMENDATION_SCOPE.TYPES.SEGMENTED]: 'Segmented',
    [AI_RECOMMENDATION_SCOPE.TYPES.GROUPED]: 'Grouped',
    [AI_RECOMMENDATION_SCOPE.TYPES.GENERAL]: 'General',
    [AI_RECOMMENDATION_SCOPE.TYPES.CROSS_SELL]: 'Cross Sell',
    [AI_RECOMMENDATION_SCOPE.TYPES.UP_SELL]: 'Up Sell',
    [AI_RECOMMENDATION_SCOPE.TYPES.COMPLEMENTARY]: 'Complementary',
    [AI_RECOMMENDATION_SCOPE.TYPES.SUBSTITUTE]: 'Substitute',
    [AI_RECOMMENDATION_SCOPE.TYPES.RECENT_VIEWS]: 'Recent Views',
    [AI_RECOMMENDATION_SCOPE.TYPES.FREQUENT_PURCHASES]: 'Frequent Purchases',
    [AI_RECOMMENDATION_SCOPE.TYPES.BROWSE_HISTORY]: 'Browse History',
    [AI_RECOMMENDATION_SCOPE.TYPES.SEARCH_HISTORY]: 'Search History',
    [AI_RECOMMENDATION_SCOPE.TYPES.CART_HISTORY]: 'Cart History',
    [AI_RECOMMENDATION_SCOPE.TYPES.SOCIAL_TRENDS]: 'Social Trends',
    [AI_RECOMMENDATION_SCOPE.TYPES.COMMUNITY_FAVORITES]: 'Community Favorites',
    [AI_RECOMMENDATION_SCOPE.TYPES.FRIEND_ACTIVITY]: 'Friend Activity',
    [AI_RECOMMENDATION_SCOPE.TYPES.CATEGORY_BASED]: 'Category Based',
    [AI_RECOMMENDATION_SCOPE.TYPES.TAG_BASED]: 'Tag Based',
    [AI_RECOMMENDATION_SCOPE.TYPES.TOPIC_BASED]: 'Topic Based',
    [AI_RECOMMENDATION_SCOPE.TYPES.THEME_BASED]: 'Theme Based',
    [AI_RECOMMENDATION_SCOPE.TYPES.REAL_TIME]: 'Real Time',
    [AI_RECOMMENDATION_SCOPE.TYPES.RECENT]: 'Recent',
    [AI_RECOMMENDATION_SCOPE.TYPES.HISTORICAL]: 'Historical',
    [AI_RECOMMENDATION_SCOPE.TYPES.FUTURE_PREDICTED]: 'Future Predicted',
    [AI_RECOMMENDATION_SCOPE.TYPES.MOMENT_BASED]: 'Moment Based',
    [AI_RECOMMENDATION_SCOPE.TYPES.LOCATION_BASED]: 'Location Based',
    [AI_RECOMMENDATION_SCOPE.TYPES.WEATHER_BASED]: 'Weather Based',
    [AI_RECOMMENDATION_SCOPE.TYPES.EVENT_BASED]: 'Event Based',
  };
  return labels[type] || 'Unknown';
}

export function getAiRecommendationScopeRuleLabel(rule: AIRecommendationScopeRule): string {
  const labels: Record<AIRecommendationScopeRule, string> = {
    [AI_RECOMMENDATION_SCOPE.RULES.INCLUDE_ALL]: 'Include All',
    [AI_RECOMMENDATION_SCOPE.RULES.INCLUDE_ANY]: 'Include Any',
    [AI_RECOMMENDATION_SCOPE.RULES.EXCLUDE_ALL]: 'Exclude All',
    [AI_RECOMMENDATION_SCOPE.RULES.EXCLUDE_ANY]: 'Exclude Any',
    [AI_RECOMMENDATION_SCOPE.RULES.PRIORITIZE]: 'Prioritize',
    [AI_RECOMMENDATION_SCOPE.RULES.DEPRIORITIZE]: 'Deprioritize',
    [AI_RECOMMENDATION_SCOPE.RULES.BOOST]: 'Boost',
    [AI_RECOMMENDATION_SCOPE.RULES.SUPPRESS]: 'Suppress',
  };
  return labels[rule] || 'Unknown';
}

export function getAiRecommendationScopePriorityValue(
  level: AIRecommendationScopeLevel
): AIRecommendationScopePriority {
  const priorities: Record<AIRecommendationScopeLevel, AIRecommendationScopePriority> = {
    [AI_RECOMMENDATION_SCOPE.LEVELS.GLOBAL]: AI_RECOMMENDATION_SCOPE.PRIORITIES.HIGH,
    [AI_RECOMMENDATION_SCOPE.LEVELS.SITE_WIDE]: AI_RECOMMENDATION_SCOPE.PRIORITIES.MEDIUM,
    [AI_RECOMMENDATION_SCOPE.LEVELS.PAGE]: AI_RECOMMENDATION_SCOPE.PRIORITIES.MEDIUM,
    [AI_RECOMMENDATION_SCOPE.LEVELS.SECTION]: AI_RECOMMENDATION_SCOPE.PRIORITIES.LOW,
    [AI_RECOMMENDATION_SCOPE.LEVELS.WIDGET]: AI_RECOMMENDATION_SCOPE.PRIORITIES.MINIMAL,
  };
  return priorities[level] || AI_RECOMMENDATION_SCOPE.PRIORITIES.MEDIUM;
}

export function getAiRecommendationScopeWeight(context: AIRecommendationScopeContext): number {
  const weights: Record<AIRecommendationScopeContext, number> = {
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.USER]: AI_RECOMMENDATION_SCOPE.WEIGHTS.USER,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.USER_SEGMENT]: AI_RECOMMENDATION_SCOPE.WEIGHTS.USER * 0.8,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.USER_GROUP]: AI_RECOMMENDATION_SCOPE.WEIGHTS.USER * 0.6,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.PRODUCT]: AI_RECOMMENDATION_SCOPE.WEIGHTS.CONTEXT * 0.8,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.PRODUCT_CATEGORY]:
      AI_RECOMMENDATION_SCOPE.WEIGHTS.CONTEXT * 0.7,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.PRODUCT_BRAND]: AI_RECOMMENDATION_SCOPE.WEIGHTS.CONTEXT * 0.6,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.BROWSE]: AI_RECOMMENDATION_SCOPE.WEIGHTS.SESSION * 0.8,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.SEARCH]: AI_RECOMMENDATION_SCOPE.WEIGHTS.SESSION * 0.9,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.CART]: AI_RECOMMENDATION_SCOPE.WEIGHTS.SESSION * 1.0,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.CHECKOUT]: AI_RECOMMENDATION_SCOPE.WEIGHTS.SESSION * 1.0,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.WISHLIST]: AI_RECOMMENDATION_SCOPE.WEIGHTS.SESSION * 0.9,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.GEOGRAPHIC]: AI_RECOMMENDATION_SCOPE.WEIGHTS.LOCATION * 0.8,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.REGIONAL]: AI_RECOMMENDATION_SCOPE.WEIGHTS.LOCATION * 0.7,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.LOCAL]: AI_RECOMMENDATION_SCOPE.WEIGHTS.LOCATION * 1.0,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.STORE]: AI_RECOMMENDATION_SCOPE.WEIGHTS.LOCATION * 0.9,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.TIME_BASED]: AI_RECOMMENDATION_SCOPE.WEIGHTS.CONTEXT * 0.5,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.SEASONAL]: AI_RECOMMENDATION_SCOPE.WEIGHTS.CONTEXT * 0.6,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.TEMPORAL]: AI_RECOMMENDATION_SCOPE.WEIGHTS.CONTEXT * 0.4,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.DEVICE]: AI_RECOMMENDATION_SCOPE.WEIGHTS.DEVICE,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.PLATFORM]: AI_RECOMMENDATION_SCOPE.WEIGHTS.DEVICE * 0.8,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.BROWSER]: AI_RECOMMENDATION_SCOPE.WEIGHTS.DEVICE * 0.6,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.CAMPAIGN]: AI_RECOMMENDATION_SCOPE.WEIGHTS.CONTEXT * 0.5,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.CHANNEL]: AI_RECOMMENDATION_SCOPE.WEIGHTS.CONTEXT * 0.4,
    [AI_RECOMMENDATION_SCOPE.CONTEXTS.SOURCE]: AI_RECOMMENDATION_SCOPE.WEIGHTS.CONTEXT * 0.3,
  };
  return weights[context] || 0.1;
}

export function getAiRecommendationDefaultCountByScopeType(
  scope: AIRecommendationScopeType
): number {
  const counts: Record<AIRecommendationScopeType, number> = {
    [AI_RECOMMENDATION_SCOPE.TYPES.PERSONALIZED]: 20,
    [AI_RECOMMENDATION_SCOPE.TYPES.SEGMENTED]: 15,
    [AI_RECOMMENDATION_SCOPE.TYPES.GROUPED]: 12,
    [AI_RECOMMENDATION_SCOPE.TYPES.GENERAL]: 10,
    [AI_RECOMMENDATION_SCOPE.TYPES.CROSS_SELL]: 4,
    [AI_RECOMMENDATION_SCOPE.TYPES.UP_SELL]: 3,
    [AI_RECOMMENDATION_SCOPE.TYPES.COMPLEMENTARY]: 5,
    [AI_RECOMMENDATION_SCOPE.TYPES.SUBSTITUTE]: 4,
    [AI_RECOMMENDATION_SCOPE.TYPES.RECENT_VIEWS]: 12,
    [AI_RECOMMENDATION_SCOPE.TYPES.FREQUENT_PURCHASES]: 10,
    [AI_RECOMMENDATION_SCOPE.TYPES.BROWSE_HISTORY]: 12,
    [AI_RECOMMENDATION_SCOPE.TYPES.SEARCH_HISTORY]: 10,
    [AI_RECOMMENDATION_SCOPE.TYPES.CART_HISTORY]: 8,
    [AI_RECOMMENDATION_SCOPE.TYPES.SOCIAL_TRENDS]: 10,
    [AI_RECOMMENDATION_SCOPE.TYPES.COMMUNITY_FAVORITES]: 8,
    [AI_RECOMMENDATION_SCOPE.TYPES.FRIEND_ACTIVITY]: 6,
    [AI_RECOMMENDATION_SCOPE.TYPES.CATEGORY_BASED]: 15,
    [AI_RECOMMENDATION_SCOPE.TYPES.TAG_BASED]: 12,
    [AI_RECOMMENDATION_SCOPE.TYPES.TOPIC_BASED]: 10,
    [AI_RECOMMENDATION_SCOPE.TYPES.THEME_BASED]: 8,
    [AI_RECOMMENDATION_SCOPE.TYPES.REAL_TIME]: 8,
    [AI_RECOMMENDATION_SCOPE.TYPES.RECENT]: 10,
    [AI_RECOMMENDATION_SCOPE.TYPES.HISTORICAL]: 12,
    [AI_RECOMMENDATION_SCOPE.TYPES.FUTURE_PREDICTED]: 6,
    [AI_RECOMMENDATION_SCOPE.TYPES.MOMENT_BASED]: 8,
    [AI_RECOMMENDATION_SCOPE.TYPES.LOCATION_BASED]: 10,
    [AI_RECOMMENDATION_SCOPE.TYPES.WEATHER_BASED]: 6,
    [AI_RECOMMENDATION_SCOPE.TYPES.EVENT_BASED]: 8,
  };
  return counts[scope] || 10;
}
