/**
 * AI Recommendation Status Constants
 * Status tracking for recommendation lifecycle
 */

// First define the statuses
export const AI_RECOMMENDATION_STATUS_TYPES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Processing States
  PROCESSING: 'processing',
  GENERATING: 'generating',
  RANKING: 'ranking',
  FILTERING: 'filtering',
  SCORING: 'scoring',
  VALIDATING: 'validating',

  // Intermediate States
  GENERATED: 'generated',
  RANKED: 'ranked',
  FILTERED: 'filtered',
  SCORED: 'scored',
  VALIDATED: 'validated',

  // Delivery States
  DELIVERING: 'delivering',
  DELIVERED: 'delivered',
  CACHED: 'cached',

  // User Interaction States
  DISPLAYED: 'displayed',
  VIEWED: 'viewed',
  CLICKED: 'clicked',
  ADDED_TO_CART: 'added_to_cart',
  PURCHASED: 'purchased',
  CONVERTED: 'converted',

  // Feedback States
  RATED: 'rated',
  REVIEWED: 'reviewed',
  LIKED: 'liked',
  DISLIKED: 'disliked',

  // Optimization States
  OPTIMIZING: 'optimizing',
  OPTIMIZED: 'optimized',
  PERSONALIZING: 'personalizing',
  PERSONALIZED: 'personalized',

  // Terminal States
  COMPLETED: 'completed',
  FAILED: 'failed',
  EXPIRED: 'expired',
  ARCHIVED: 'archived',
  REJECTED: 'rejected',
  RETIRED: 'retired',
} as const;

export type AIRecommendationStatusType =
  (typeof AI_RECOMMENDATION_STATUS_TYPES)[keyof typeof AI_RECOMMENDATION_STATUS_TYPES];

export const AI_RECOMMENDATION_STATUS = {
  // Status Types
  STATUSES: AI_RECOMMENDATION_STATUS_TYPES,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    DELIVERED: 'delivered',
    ENGAGED: 'engaged',
    CONVERTED: 'converted',
    OPTIMIZED: 'optimized',
    COMPLETED: 'completed',
    FAILED: 'failed',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_RECOMMENDATION_STATUS_TYPES.CREATED]: '#gray',
    [AI_RECOMMENDATION_STATUS_TYPES.QUEUED]: '#gray',
    [AI_RECOMMENDATION_STATUS_TYPES.PENDING]: '#yellow',
    [AI_RECOMMENDATION_STATUS_TYPES.PROCESSING]: '#blue',
    [AI_RECOMMENDATION_STATUS_TYPES.GENERATING]: '#blue',
    [AI_RECOMMENDATION_STATUS_TYPES.RANKING]: '#blue',
    [AI_RECOMMENDATION_STATUS_TYPES.FILTERING]: '#blue',
    [AI_RECOMMENDATION_STATUS_TYPES.SCORING]: '#blue',
    [AI_RECOMMENDATION_STATUS_TYPES.VALIDATING]: '#purple',
    [AI_RECOMMENDATION_STATUS_TYPES.GENERATED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.RANKED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.FILTERED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.SCORED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.VALIDATED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.DELIVERING]: '#orange',
    [AI_RECOMMENDATION_STATUS_TYPES.DELIVERED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.CACHED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.DISPLAYED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.VIEWED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.CLICKED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.ADDED_TO_CART]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.PURCHASED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.CONVERTED]: '#gold',
    [AI_RECOMMENDATION_STATUS_TYPES.RATED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.REVIEWED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.LIKED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.DISLIKED]: '#red',
    [AI_RECOMMENDATION_STATUS_TYPES.OPTIMIZING]: '#orange',
    [AI_RECOMMENDATION_STATUS_TYPES.OPTIMIZED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.PERSONALIZING]: '#orange',
    [AI_RECOMMENDATION_STATUS_TYPES.PERSONALIZED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.COMPLETED]: '#green',
    [AI_RECOMMENDATION_STATUS_TYPES.FAILED]: '#red',
    [AI_RECOMMENDATION_STATUS_TYPES.EXPIRED]: '#gray',
    [AI_RECOMMENDATION_STATUS_TYPES.ARCHIVED]: '#gray',
    [AI_RECOMMENDATION_STATUS_TYPES.REJECTED]: '#red',
    [AI_RECOMMENDATION_STATUS_TYPES.RETIRED]: '#gray',
  } as const,
} as const;

// Status Categories
export type AIRecommendationStatusCategory =
  (typeof AI_RECOMMENDATION_STATUS.CATEGORIES)[keyof typeof AI_RECOMMENDATION_STATUS.CATEGORIES];

// Status Severity
export type AIRecommendationStatusSeverity =
  (typeof AI_RECOMMENDATION_STATUS.SEVERITY)[keyof typeof AI_RECOMMENDATION_STATUS.SEVERITY];

// Status Colors
export type AIRecommendationStatusColor =
  (typeof AI_RECOMMENDATION_STATUS.COLORS)[keyof typeof AI_RECOMMENDATION_STATUS.COLORS];

// Utility Functions
export function getRecommendationStatusLabel(status: AIRecommendationStatusType): string {
  const labels: Record<AIRecommendationStatusType, string> = {
    [AI_RECOMMENDATION_STATUS_TYPES.CREATED]: 'Created',
    [AI_RECOMMENDATION_STATUS_TYPES.QUEUED]: 'Queued',
    [AI_RECOMMENDATION_STATUS_TYPES.PENDING]: 'Pending',
    [AI_RECOMMENDATION_STATUS_TYPES.PROCESSING]: 'Processing',
    [AI_RECOMMENDATION_STATUS_TYPES.GENERATING]: 'Generating',
    [AI_RECOMMENDATION_STATUS_TYPES.RANKING]: 'Ranking',
    [AI_RECOMMENDATION_STATUS_TYPES.FILTERING]: 'Filtering',
    [AI_RECOMMENDATION_STATUS_TYPES.SCORING]: 'Scoring',
    [AI_RECOMMENDATION_STATUS_TYPES.VALIDATING]: 'Validating',
    [AI_RECOMMENDATION_STATUS_TYPES.GENERATED]: 'Generated',
    [AI_RECOMMENDATION_STATUS_TYPES.RANKED]: 'Ranked',
    [AI_RECOMMENDATION_STATUS_TYPES.FILTERED]: 'Filtered',
    [AI_RECOMMENDATION_STATUS_TYPES.SCORED]: 'Scored',
    [AI_RECOMMENDATION_STATUS_TYPES.VALIDATED]: 'Validated',
    [AI_RECOMMENDATION_STATUS_TYPES.DELIVERING]: 'Delivering',
    [AI_RECOMMENDATION_STATUS_TYPES.DELIVERED]: 'Delivered',
    [AI_RECOMMENDATION_STATUS_TYPES.CACHED]: 'Cached',
    [AI_RECOMMENDATION_STATUS_TYPES.DISPLAYED]: 'Displayed',
    [AI_RECOMMENDATION_STATUS_TYPES.VIEWED]: 'Viewed',
    [AI_RECOMMENDATION_STATUS_TYPES.CLICKED]: 'Clicked',
    [AI_RECOMMENDATION_STATUS_TYPES.ADDED_TO_CART]: 'Added to Cart',
    [AI_RECOMMENDATION_STATUS_TYPES.PURCHASED]: 'Purchased',
    [AI_RECOMMENDATION_STATUS_TYPES.CONVERTED]: 'Converted',
    [AI_RECOMMENDATION_STATUS_TYPES.RATED]: 'Rated',
    [AI_RECOMMENDATION_STATUS_TYPES.REVIEWED]: 'Reviewed',
    [AI_RECOMMENDATION_STATUS_TYPES.LIKED]: 'Liked',
    [AI_RECOMMENDATION_STATUS_TYPES.DISLIKED]: 'Disliked',
    [AI_RECOMMENDATION_STATUS_TYPES.OPTIMIZING]: 'Optimizing',
    [AI_RECOMMENDATION_STATUS_TYPES.OPTIMIZED]: 'Optimized',
    [AI_RECOMMENDATION_STATUS_TYPES.PERSONALIZING]: 'Personalizing',
    [AI_RECOMMENDATION_STATUS_TYPES.PERSONALIZED]: 'Personalized',
    [AI_RECOMMENDATION_STATUS_TYPES.COMPLETED]: 'Completed',
    [AI_RECOMMENDATION_STATUS_TYPES.FAILED]: 'Failed',
    [AI_RECOMMENDATION_STATUS_TYPES.EXPIRED]: 'Expired',
    [AI_RECOMMENDATION_STATUS_TYPES.ARCHIVED]: 'Archived',
    [AI_RECOMMENDATION_STATUS_TYPES.REJECTED]: 'Rejected',
    [AI_RECOMMENDATION_STATUS_TYPES.RETIRED]: 'Retired',
  };
  return labels[status] || 'Unknown';
}

export function getRecommendationStatusCategory(
  status: AIRecommendationStatusType
): AIRecommendationStatusCategory {
  const categories: Record<AIRecommendationStatusType, AIRecommendationStatusCategory> = {
    [AI_RECOMMENDATION_STATUS_TYPES.CREATED]: AI_RECOMMENDATION_STATUS.CATEGORIES.PENDING,
    [AI_RECOMMENDATION_STATUS_TYPES.QUEUED]: AI_RECOMMENDATION_STATUS.CATEGORIES.PENDING,
    [AI_RECOMMENDATION_STATUS_TYPES.PENDING]: AI_RECOMMENDATION_STATUS.CATEGORIES.PENDING,
    [AI_RECOMMENDATION_STATUS_TYPES.PROCESSING]: AI_RECOMMENDATION_STATUS.CATEGORIES.PROCESSING,
    [AI_RECOMMENDATION_STATUS_TYPES.GENERATING]: AI_RECOMMENDATION_STATUS.CATEGORIES.PROCESSING,
    [AI_RECOMMENDATION_STATUS_TYPES.RANKING]: AI_RECOMMENDATION_STATUS.CATEGORIES.PROCESSING,
    [AI_RECOMMENDATION_STATUS_TYPES.FILTERING]: AI_RECOMMENDATION_STATUS.CATEGORIES.PROCESSING,
    [AI_RECOMMENDATION_STATUS_TYPES.SCORING]: AI_RECOMMENDATION_STATUS.CATEGORIES.PROCESSING,
    [AI_RECOMMENDATION_STATUS_TYPES.VALIDATING]: AI_RECOMMENDATION_STATUS.CATEGORIES.PROCESSING,
    [AI_RECOMMENDATION_STATUS_TYPES.GENERATED]: AI_RECOMMENDATION_STATUS.CATEGORIES.PROCESSING,
    [AI_RECOMMENDATION_STATUS_TYPES.RANKED]: AI_RECOMMENDATION_STATUS.CATEGORIES.PROCESSING,
    [AI_RECOMMENDATION_STATUS_TYPES.FILTERED]: AI_RECOMMENDATION_STATUS.CATEGORIES.PROCESSING,
    [AI_RECOMMENDATION_STATUS_TYPES.SCORED]: AI_RECOMMENDATION_STATUS.CATEGORIES.PROCESSING,
    [AI_RECOMMENDATION_STATUS_TYPES.VALIDATED]: AI_RECOMMENDATION_STATUS.CATEGORIES.PROCESSING,
    [AI_RECOMMENDATION_STATUS_TYPES.DELIVERING]: AI_RECOMMENDATION_STATUS.CATEGORIES.DELIVERED,
    [AI_RECOMMENDATION_STATUS_TYPES.DELIVERED]: AI_RECOMMENDATION_STATUS.CATEGORIES.DELIVERED,
    [AI_RECOMMENDATION_STATUS_TYPES.CACHED]: AI_RECOMMENDATION_STATUS.CATEGORIES.DELIVERED,
    [AI_RECOMMENDATION_STATUS_TYPES.DISPLAYED]: AI_RECOMMENDATION_STATUS.CATEGORIES.ENGAGED,
    [AI_RECOMMENDATION_STATUS_TYPES.VIEWED]: AI_RECOMMENDATION_STATUS.CATEGORIES.ENGAGED,
    [AI_RECOMMENDATION_STATUS_TYPES.CLICKED]: AI_RECOMMENDATION_STATUS.CATEGORIES.ENGAGED,
    [AI_RECOMMENDATION_STATUS_TYPES.ADDED_TO_CART]: AI_RECOMMENDATION_STATUS.CATEGORIES.CONVERTED,
    [AI_RECOMMENDATION_STATUS_TYPES.PURCHASED]: AI_RECOMMENDATION_STATUS.CATEGORIES.CONVERTED,
    [AI_RECOMMENDATION_STATUS_TYPES.CONVERTED]: AI_RECOMMENDATION_STATUS.CATEGORIES.CONVERTED,
    [AI_RECOMMENDATION_STATUS_TYPES.RATED]: AI_RECOMMENDATION_STATUS.CATEGORIES.ENGAGED,
    [AI_RECOMMENDATION_STATUS_TYPES.REVIEWED]: AI_RECOMMENDATION_STATUS.CATEGORIES.ENGAGED,
    [AI_RECOMMENDATION_STATUS_TYPES.LIKED]: AI_RECOMMENDATION_STATUS.CATEGORIES.ENGAGED,
    [AI_RECOMMENDATION_STATUS_TYPES.DISLIKED]: AI_RECOMMENDATION_STATUS.CATEGORIES.ENGAGED,
    [AI_RECOMMENDATION_STATUS_TYPES.OPTIMIZING]: AI_RECOMMENDATION_STATUS.CATEGORIES.OPTIMIZED,
    [AI_RECOMMENDATION_STATUS_TYPES.OPTIMIZED]: AI_RECOMMENDATION_STATUS.CATEGORIES.OPTIMIZED,
    [AI_RECOMMENDATION_STATUS_TYPES.PERSONALIZING]: AI_RECOMMENDATION_STATUS.CATEGORIES.OPTIMIZED,
    [AI_RECOMMENDATION_STATUS_TYPES.PERSONALIZED]: AI_RECOMMENDATION_STATUS.CATEGORIES.OPTIMIZED,
    [AI_RECOMMENDATION_STATUS_TYPES.COMPLETED]: AI_RECOMMENDATION_STATUS.CATEGORIES.COMPLETED,
    [AI_RECOMMENDATION_STATUS_TYPES.FAILED]: AI_RECOMMENDATION_STATUS.CATEGORIES.FAILED,
    [AI_RECOMMENDATION_STATUS_TYPES.EXPIRED]: AI_RECOMMENDATION_STATUS.CATEGORIES.FAILED,
    [AI_RECOMMENDATION_STATUS_TYPES.ARCHIVED]: AI_RECOMMENDATION_STATUS.CATEGORIES.COMPLETED,
    [AI_RECOMMENDATION_STATUS_TYPES.REJECTED]: AI_RECOMMENDATION_STATUS.CATEGORIES.FAILED,
    [AI_RECOMMENDATION_STATUS_TYPES.RETIRED]: AI_RECOMMENDATION_STATUS.CATEGORIES.COMPLETED,
  };
  return categories[status] || AI_RECOMMENDATION_STATUS.CATEGORIES.PENDING;
}

export function getRecommendationStatusSeverity(
  status: AIRecommendationStatusType
): AIRecommendationStatusSeverity {
  const severities: Record<AIRecommendationStatusType, AIRecommendationStatusSeverity> = {
    [AI_RECOMMENDATION_STATUS_TYPES.CREATED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.QUEUED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.PENDING]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.PROCESSING]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.GENERATING]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.RANKING]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.FILTERING]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.SCORING]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.VALIDATING]: AI_RECOMMENDATION_STATUS.SEVERITY.WARNING,
    [AI_RECOMMENDATION_STATUS_TYPES.GENERATED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.RANKED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.FILTERED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.SCORED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.VALIDATED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.DELIVERING]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.DELIVERED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.CACHED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.DISPLAYED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.VIEWED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.CLICKED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.ADDED_TO_CART]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.PURCHASED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.CONVERTED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.RATED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.REVIEWED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.LIKED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.DISLIKED]: AI_RECOMMENDATION_STATUS.SEVERITY.WARNING,
    [AI_RECOMMENDATION_STATUS_TYPES.OPTIMIZING]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.OPTIMIZED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.PERSONALIZING]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.PERSONALIZED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.COMPLETED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.FAILED]: AI_RECOMMENDATION_STATUS.SEVERITY.ERROR,
    [AI_RECOMMENDATION_STATUS_TYPES.EXPIRED]: AI_RECOMMENDATION_STATUS.SEVERITY.WARNING,
    [AI_RECOMMENDATION_STATUS_TYPES.ARCHIVED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
    [AI_RECOMMENDATION_STATUS_TYPES.REJECTED]: AI_RECOMMENDATION_STATUS.SEVERITY.WARNING,
    [AI_RECOMMENDATION_STATUS_TYPES.RETIRED]: AI_RECOMMENDATION_STATUS.SEVERITY.INFO,
  };
  return severities[status] || AI_RECOMMENDATION_STATUS.SEVERITY.INFO;
}

export function getRecommendationStatusColor(
  status: AIRecommendationStatusType
): AIRecommendationStatusColor {
  return AI_RECOMMENDATION_STATUS.COLORS[status] || '#gray';
}

export function isRecommendationActive(status: AIRecommendationStatusType): boolean {
  const activeStatuses: AIRecommendationStatusType[] = [
    AI_RECOMMENDATION_STATUS_TYPES.CREATED,
    AI_RECOMMENDATION_STATUS_TYPES.QUEUED,
    AI_RECOMMENDATION_STATUS_TYPES.PENDING,
    AI_RECOMMENDATION_STATUS_TYPES.PROCESSING,
    AI_RECOMMENDATION_STATUS_TYPES.GENERATING,
    AI_RECOMMENDATION_STATUS_TYPES.RANKING,
    AI_RECOMMENDATION_STATUS_TYPES.FILTERING,
    AI_RECOMMENDATION_STATUS_TYPES.SCORING,
    AI_RECOMMENDATION_STATUS_TYPES.VALIDATING,
    AI_RECOMMENDATION_STATUS_TYPES.GENERATED,
    AI_RECOMMENDATION_STATUS_TYPES.RANKED,
    AI_RECOMMENDATION_STATUS_TYPES.FILTERED,
    AI_RECOMMENDATION_STATUS_TYPES.SCORED,
    AI_RECOMMENDATION_STATUS_TYPES.VALIDATED,
    AI_RECOMMENDATION_STATUS_TYPES.DELIVERING,
  ];
  return activeStatuses.includes(status);
}

export function isRecommendationDelivered(status: AIRecommendationStatusType): boolean {
  const deliveredStatuses: AIRecommendationStatusType[] = [
    AI_RECOMMENDATION_STATUS_TYPES.DELIVERED,
    AI_RECOMMENDATION_STATUS_TYPES.CACHED,
    AI_RECOMMENDATION_STATUS_TYPES.DISPLAYED,
    AI_RECOMMENDATION_STATUS_TYPES.VIEWED,
    AI_RECOMMENDATION_STATUS_TYPES.CLICKED,
  ];
  return deliveredStatuses.includes(status);
}

export function isRecommendationConverted(status: AIRecommendationStatusType): boolean {
  const convertedStatuses: AIRecommendationStatusType[] = [
    AI_RECOMMENDATION_STATUS_TYPES.ADDED_TO_CART,
    AI_RECOMMENDATION_STATUS_TYPES.PURCHASED,
    AI_RECOMMENDATION_STATUS_TYPES.CONVERTED,
  ];
  return convertedStatuses.includes(status);
}

export function isRecommendationFailed(status: AIRecommendationStatusType): boolean {
  const failedStatuses: AIRecommendationStatusType[] = [
    AI_RECOMMENDATION_STATUS_TYPES.FAILED,
    AI_RECOMMENDATION_STATUS_TYPES.REJECTED,
  ];
  return failedStatuses.includes(status);
}

export function isRecommendationComplete(status: AIRecommendationStatusType): boolean {
  const completeStatuses: AIRecommendationStatusType[] = [
    AI_RECOMMENDATION_STATUS_TYPES.COMPLETED,
    AI_RECOMMENDATION_STATUS_TYPES.ARCHIVED,
    AI_RECOMMENDATION_STATUS_TYPES.RETIRED,
  ];
  return completeStatuses.includes(status);
}
