/**
 * Admin Error Constants
 * Admin error and exception definitions
 */

export const ADMIN_ERROR = {
  // Error categories
  CATEGORIES: {
    SYSTEM: 'system',
    NETWORK: 'network',
    DATABASE: 'database',
    AUTHENTICATION: 'authentication',
    AUTHORIZATION: 'authorization',
    VALIDATION: 'validation',
    BUSINESS: 'business',
    INTEGRATION: 'integration',
    CONFIGURATION: 'configuration',
    RESOURCE: 'resource',
    RATE_LIMIT: 'rate_limit',
    TIMEOUT: 'timeout',
    UNKNOWN: 'unknown',
  },

  // Error severities
  SEVERITIES: {
    DEBUG: 'debug',
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
    FATAL: 'fatal',
  },

  // Error types
  TYPES: {
    VALIDATION_ERROR: 'validation_error',
    AUTHENTICATION_ERROR: 'authentication_error',
    AUTHORIZATION_ERROR: 'authorization_error',
    NOT_FOUND_ERROR: 'not_found_error',
    CONFLICT_ERROR: 'conflict_error',
    RATE_LIMIT_ERROR: 'rate_limit_error',
    TIMEOUT_ERROR: 'timeout_error',
    CONNECTION_ERROR: 'connection_error',
    DATABASE_ERROR: 'database_error',
    INTEGRATION_ERROR: 'integration_error',
    CONFIGURATION_ERROR: 'configuration_error',
    RESOURCE_ERROR: 'resource_error',
    BUSINESS_ERROR: 'business_error',
    SYSTEM_ERROR: 'system_error',
    UNKNOWN_ERROR: 'unknown_error',
  },

  // Error codes
  CODES: {
    // System errors (1000-1999)
    SYSTEM_UNKNOWN: 1000,
    SYSTEM_CONFIGURATION: 1001,
    SYSTEM_MAINTENANCE: 1002,
    SYSTEM_OVERLOAD: 1003,
    SYSTEM_UPGRADE: 1004,

    // Network errors (2000-2999)
    NETWORK_CONNECTION: 2000,
    NETWORK_TIMEOUT: 2001,
    NETWORK_DNS: 2002,
    NETWORK_SSL: 2003,
    NETWORK_PROXY: 2004,

    // Database errors (3000-3999)
    DATABASE_CONNECTION: 3000,
    DATABASE_QUERY: 3001,
    DATABASE_CONSTRAINT: 3002,
    DATABASE_DUPLICATE: 3003,
    DATABASE_NOT_FOUND: 3004,
    DATABASE_TRANSACTION: 3005,

    // Authentication errors (4000-4999)
    AUTH_INVALID_CREDENTIALS: 4000,
    AUTH_TOKEN_EXPIRED: 4001,
    AUTH_TOKEN_INVALID: 4002,
    AUTH_INSUFFICIENT_PERMISSIONS: 4003,
    AUTH_ACCOUNT_LOCKED: 4004,
    AUTH_ACCOUNT_SUSPENDED: 4005,
    AUTH_ACCOUNT_BANNED: 4006,
    AUTH_TWO_FA_REQUIRED: 4007,
    AUTH_TWO_FA_INVALID: 4008,

    // Authorization errors (5000-5999)
    AUTHZ_INSUFFICIENT_PERMISSIONS: 5000,
    AUTHZ_RESOURCE_ACCESS: 5001,
    AUTHZ_ROLE_INVALID: 5002,
    AUTHZ_PERMISSION_DENIED: 5003,

    // Validation errors (6000-6999)
    VALIDATION_INVALID_INPUT: 6000,
    VALIDATION_MISSING_FIELD: 6001,
    VALIDATION_INVALID_FORMAT: 6002,
    VALIDATION_INVALID_LENGTH: 6003,
    VALIDATION_INVALID_RANGE: 6004,
    VALIDATION_INVALID_EMAIL: 6005,
    VALIDATION_INVALID_PHONE: 6006,
    VALIDATION_INVALID_URL: 6007,

    // Business errors (7000-7999)
    BUSINESS_INVALID_OPERATION: 7000,
    BUSINESS_INSUFFICIENT_FUNDS: 7001,
    BUSINESS_INVENTORY_ERROR: 7002,
    BUSINESS_ORDER_ERROR: 7003,
    BUSINESS_PAYMENT_ERROR: 7004,
    BUSINESS_SHIPPING_ERROR: 7005,

    // Integration errors (8000-8999)
    INTEGRATION_API_ERROR: 8000,
    INTEGRATION_WEBHOOK_ERROR: 8001,
    INTEGRATION_THIRD_PARTY: 8002,
    INTEGRATION_SERVICE_UNAVAILABLE: 8003,

    // Resource errors (9000-9999)
    RESOURCE_NOT_FOUND: 9000,
    RESOURCE_UNAVAILABLE: 9001,
    RESOURCE_EXHAUSTED: 9002,
    RESOURCE_CONFLICT: 9003,

    // Rate limit errors (10000-10999)
    RATE_LIMIT_EXCEEDED: 10000,
    RATE_LIMIT_BURST: 10001,
    RATE_LIMIT_DAILY: 10002,

    // Timeout errors (11000-11999)
    TIMEOUT_REQUEST: 11000,
    TIMEOUT_RESPONSE: 11001,
    TIMEOUT_CONNECTION: 11002,
    TIMEOUT_READ: 11003,
    TIMEOUT_WRITE: 11004,
  },

  // Error sources
  SOURCES: {
    CLIENT: 'client',
    SERVER: 'server',
    DATABASE: 'database',
    CACHE: 'cache',
    QUEUE: 'queue',
    API: 'api',
    INTEGRATION: 'integration',
    SYSTEM: 'system',
  },

  // Error actions
  ACTIONS: {
    RETRY: 'retry',
    BACKOFF: 'backoff',
    ABORT: 'abort',
    ESCALATE: 'escalate',
    NOTIFY: 'notify',
    LOG: 'log',
    IGNORE: 'ignore',
    FALLBACK: 'fallback',
  },
} as const;

export type AdminErrorCategory =
  (typeof ADMIN_ERROR.CATEGORIES)[keyof typeof ADMIN_ERROR.CATEGORIES];
export type AdminErrorSeverity =
  (typeof ADMIN_ERROR.SEVERITIES)[keyof typeof ADMIN_ERROR.SEVERITIES];
export type AdminErrorType = (typeof ADMIN_ERROR.TYPES)[keyof typeof ADMIN_ERROR.TYPES];
export type AdminErrorCode = (typeof ADMIN_ERROR.CODES)[keyof typeof ADMIN_ERROR.CODES];
export type AdminErrorSource = (typeof ADMIN_ERROR.SOURCES)[keyof typeof ADMIN_ERROR.SOURCES];
export type AdminErrorAction = (typeof ADMIN_ERROR.ACTIONS)[keyof typeof ADMIN_ERROR.ACTIONS];

export const ADMIN_ERROR_CATEGORY_LABELS: Record<AdminErrorCategory, string> = {
  [ADMIN_ERROR.CATEGORIES.SYSTEM]: 'System',
  [ADMIN_ERROR.CATEGORIES.NETWORK]: 'Network',
  [ADMIN_ERROR.CATEGORIES.DATABASE]: 'Database',
  [ADMIN_ERROR.CATEGORIES.AUTHENTICATION]: 'Authentication',
  [ADMIN_ERROR.CATEGORIES.AUTHORIZATION]: 'Authorization',
  [ADMIN_ERROR.CATEGORIES.VALIDATION]: 'Validation',
  [ADMIN_ERROR.CATEGORIES.BUSINESS]: 'Business',
  [ADMIN_ERROR.CATEGORIES.INTEGRATION]: 'Integration',
  [ADMIN_ERROR.CATEGORIES.CONFIGURATION]: 'Configuration',
  [ADMIN_ERROR.CATEGORIES.RESOURCE]: 'Resource',
  [ADMIN_ERROR.CATEGORIES.RATE_LIMIT]: 'Rate Limit',
  [ADMIN_ERROR.CATEGORIES.TIMEOUT]: 'Timeout',
  [ADMIN_ERROR.CATEGORIES.UNKNOWN]: 'Unknown',
};

export const ADMIN_ERROR_SEVERITY_LABELS: Record<AdminErrorSeverity, string> = {
  [ADMIN_ERROR.SEVERITIES.DEBUG]: 'Debug',
  [ADMIN_ERROR.SEVERITIES.INFO]: 'Info',
  [ADMIN_ERROR.SEVERITIES.WARNING]: 'Warning',
  [ADMIN_ERROR.SEVERITIES.ERROR]: 'Error',
  [ADMIN_ERROR.SEVERITIES.CRITICAL]: 'Critical',
  [ADMIN_ERROR.SEVERITIES.FATAL]: 'Fatal',
};

export const ADMIN_ERROR_SEVERITY_COLORS: Record<AdminErrorSeverity, string> = {
  [ADMIN_ERROR.SEVERITIES.DEBUG]: '#6B7280',
  [ADMIN_ERROR.SEVERITIES.INFO]: '#3B82F6',
  [ADMIN_ERROR.SEVERITIES.WARNING]: '#F59E0B',
  [ADMIN_ERROR.SEVERITIES.ERROR]: '#EF4444',
  [ADMIN_ERROR.SEVERITIES.CRITICAL]: '#DC2626',
  [ADMIN_ERROR.SEVERITIES.FATAL]: '#8B0000',
};

export const ADMIN_ERROR_TYPE_LABELS: Record<AdminErrorType, string> = {
  [ADMIN_ERROR.TYPES.VALIDATION_ERROR]: 'Validation Error',
  [ADMIN_ERROR.TYPES.AUTHENTICATION_ERROR]: 'Authentication Error',
  [ADMIN_ERROR.TYPES.AUTHORIZATION_ERROR]: 'Authorization Error',
  [ADMIN_ERROR.TYPES.NOT_FOUND_ERROR]: 'Not Found Error',
  [ADMIN_ERROR.TYPES.CONFLICT_ERROR]: 'Conflict Error',
  [ADMIN_ERROR.TYPES.RATE_LIMIT_ERROR]: 'Rate Limit Error',
  [ADMIN_ERROR.TYPES.TIMEOUT_ERROR]: 'Timeout Error',
  [ADMIN_ERROR.TYPES.CONNECTION_ERROR]: 'Connection Error',
  [ADMIN_ERROR.TYPES.DATABASE_ERROR]: 'Database Error',
  [ADMIN_ERROR.TYPES.INTEGRATION_ERROR]: 'Integration Error',
  [ADMIN_ERROR.TYPES.CONFIGURATION_ERROR]: 'Configuration Error',
  [ADMIN_ERROR.TYPES.RESOURCE_ERROR]: 'Resource Error',
  [ADMIN_ERROR.TYPES.BUSINESS_ERROR]: 'Business Error',
  [ADMIN_ERROR.TYPES.SYSTEM_ERROR]: 'System Error',
  [ADMIN_ERROR.TYPES.UNKNOWN_ERROR]: 'Unknown Error',
};

export const ADMIN_ERROR_SOURCE_LABELS: Record<AdminErrorSource, string> = {
  [ADMIN_ERROR.SOURCES.CLIENT]: 'Client',
  [ADMIN_ERROR.SOURCES.SERVER]: 'Server',
  [ADMIN_ERROR.SOURCES.DATABASE]: 'Database',
  [ADMIN_ERROR.SOURCES.CACHE]: 'Cache',
  [ADMIN_ERROR.SOURCES.QUEUE]: 'Queue',
  [ADMIN_ERROR.SOURCES.API]: 'API',
  [ADMIN_ERROR.SOURCES.INTEGRATION]: 'Integration',
  [ADMIN_ERROR.SOURCES.SYSTEM]: 'System',
};

export const ADMIN_ERROR_ACTION_LABELS: Record<AdminErrorAction, string> = {
  [ADMIN_ERROR.ACTIONS.RETRY]: 'Retry',
  [ADMIN_ERROR.ACTIONS.BACKOFF]: 'Backoff',
  [ADMIN_ERROR.ACTIONS.ABORT]: 'Abort',
  [ADMIN_ERROR.ACTIONS.ESCALATE]: 'Escalate',
  [ADMIN_ERROR.ACTIONS.NOTIFY]: 'Notify',
  [ADMIN_ERROR.ACTIONS.LOG]: 'Log',
  [ADMIN_ERROR.ACTIONS.IGNORE]: 'Ignore',
  [ADMIN_ERROR.ACTIONS.FALLBACK]: 'Fallback',
};

export function getAdminErrorCategoryLabel(category: AdminErrorCategory): string {
  return ADMIN_ERROR_CATEGORY_LABELS[category] || 'Unknown Category';
}

export function getAdminErrorSeverityLabel(severity: AdminErrorSeverity): string {
  return ADMIN_ERROR_SEVERITY_LABELS[severity] || 'Unknown Severity';
}

export function getAdminErrorSeverityColor(severity: AdminErrorSeverity): string {
  return ADMIN_ERROR_SEVERITY_COLORS[severity] || '#6B7280';
}

export function getAdminErrorTypeLabel(type: AdminErrorType): string {
  return ADMIN_ERROR_TYPE_LABELS[type] || 'Unknown Type';
}

export function getAdminErrorSourceLabel(source: AdminErrorSource): string {
  return ADMIN_ERROR_SOURCE_LABELS[source] || 'Unknown Source';
}

export function getAdminErrorActionLabel(action: AdminErrorAction): string {
  return ADMIN_ERROR_ACTION_LABELS[action] || 'Unknown Action';
}

export function isCriticalError(severity: AdminErrorSeverity): boolean {
  return severity === ADMIN_ERROR.SEVERITIES.CRITICAL || severity === ADMIN_ERROR.SEVERITIES.FATAL;
}

export function isRecoverableError(type: AdminErrorType): boolean {
  return (
    type !== ADMIN_ERROR.TYPES.SYSTEM_ERROR &&
    type !== ADMIN_ERROR.TYPES.UNKNOWN_ERROR &&
    type !== ADMIN_ERROR.TYPES.CONFIGURATION_ERROR
  );
}

export function shouldRetryError(error: AdminErrorType): boolean {
  return (
    error === ADMIN_ERROR.TYPES.TIMEOUT_ERROR ||
    error === ADMIN_ERROR.TYPES.CONNECTION_ERROR ||
    error === ADMIN_ERROR.TYPES.RATE_LIMIT_ERROR ||
    error === ADMIN_ERROR.TYPES.INTEGRATION_ERROR
  );
}

export function getErrorCodeCategory(code: AdminErrorCode): AdminErrorCategory {
  if (code >= 1000 && code < 2000) return ADMIN_ERROR.CATEGORIES.SYSTEM;
  if (code >= 2000 && code < 3000) return ADMIN_ERROR.CATEGORIES.NETWORK;
  if (code >= 3000 && code < 4000) return ADMIN_ERROR.CATEGORIES.DATABASE;
  if (code >= 4000 && code < 5000) return ADMIN_ERROR.CATEGORIES.AUTHENTICATION;
  if (code >= 5000 && code < 6000) return ADMIN_ERROR.CATEGORIES.AUTHORIZATION;
  if (code >= 6000 && code < 7000) return ADMIN_ERROR.CATEGORIES.VALIDATION;
  if (code >= 7000 && code < 8000) return ADMIN_ERROR.CATEGORIES.BUSINESS;
  if (code >= 8000 && code < 9000) return ADMIN_ERROR.CATEGORIES.INTEGRATION;
  if (code >= 9000 && code < 10000) return ADMIN_ERROR.CATEGORIES.RESOURCE;
  if (code >= 10000 && code < 11000) return ADMIN_ERROR.CATEGORIES.RATE_LIMIT;
  if (code >= 11000 && code < 12000) return ADMIN_ERROR.CATEGORIES.TIMEOUT;
  return ADMIN_ERROR.CATEGORIES.UNKNOWN;
}

export function getErrorTypeFromCode(code: AdminErrorCode): AdminErrorType {
  const typeMap: Record<AdminErrorCode, AdminErrorType> = {
    [ADMIN_ERROR.CODES.SYSTEM_UNKNOWN]: ADMIN_ERROR.TYPES.SYSTEM_ERROR,
    [ADMIN_ERROR.CODES.SYSTEM_CONFIGURATION]: ADMIN_ERROR.TYPES.CONFIGURATION_ERROR,
    [ADMIN_ERROR.CODES.SYSTEM_MAINTENANCE]: ADMIN_ERROR.TYPES.SYSTEM_ERROR,
    [ADMIN_ERROR.CODES.SYSTEM_OVERLOAD]: ADMIN_ERROR.TYPES.SYSTEM_ERROR,
    [ADMIN_ERROR.CODES.SYSTEM_UPGRADE]: ADMIN_ERROR.TYPES.SYSTEM_ERROR,
    [ADMIN_ERROR.CODES.NETWORK_CONNECTION]: ADMIN_ERROR.TYPES.CONNECTION_ERROR,
    [ADMIN_ERROR.CODES.NETWORK_TIMEOUT]: ADMIN_ERROR.TYPES.TIMEOUT_ERROR,
    [ADMIN_ERROR.CODES.NETWORK_DNS]: ADMIN_ERROR.TYPES.CONNECTION_ERROR,
    [ADMIN_ERROR.CODES.NETWORK_SSL]: ADMIN_ERROR.TYPES.CONNECTION_ERROR,
    [ADMIN_ERROR.CODES.NETWORK_PROXY]: ADMIN_ERROR.TYPES.CONNECTION_ERROR,
    [ADMIN_ERROR.CODES.DATABASE_CONNECTION]: ADMIN_ERROR.TYPES.DATABASE_ERROR,
    [ADMIN_ERROR.CODES.DATABASE_QUERY]: ADMIN_ERROR.TYPES.DATABASE_ERROR,
    [ADMIN_ERROR.CODES.DATABASE_CONSTRAINT]: ADMIN_ERROR.TYPES.DATABASE_ERROR,
    [ADMIN_ERROR.CODES.DATABASE_DUPLICATE]: ADMIN_ERROR.TYPES.DATABASE_ERROR,
    [ADMIN_ERROR.CODES.DATABASE_NOT_FOUND]: ADMIN_ERROR.TYPES.DATABASE_ERROR,
    [ADMIN_ERROR.CODES.DATABASE_TRANSACTION]: ADMIN_ERROR.TYPES.DATABASE_ERROR,
    [ADMIN_ERROR.CODES.AUTH_INVALID_CREDENTIALS]: ADMIN_ERROR.TYPES.AUTHENTICATION_ERROR,
    [ADMIN_ERROR.CODES.AUTH_TOKEN_EXPIRED]: ADMIN_ERROR.TYPES.AUTHENTICATION_ERROR,
    [ADMIN_ERROR.CODES.AUTH_TOKEN_INVALID]: ADMIN_ERROR.TYPES.AUTHENTICATION_ERROR,
    [ADMIN_ERROR.CODES.AUTH_INSUFFICIENT_PERMISSIONS]: ADMIN_ERROR.TYPES.AUTHORIZATION_ERROR,
    [ADMIN_ERROR.CODES.AUTH_ACCOUNT_LOCKED]: ADMIN_ERROR.TYPES.AUTHENTICATION_ERROR,
    [ADMIN_ERROR.CODES.AUTH_ACCOUNT_SUSPENDED]: ADMIN_ERROR.TYPES.AUTHENTICATION_ERROR,
    [ADMIN_ERROR.CODES.AUTH_ACCOUNT_BANNED]: ADMIN_ERROR.TYPES.AUTHENTICATION_ERROR,
    [ADMIN_ERROR.CODES.AUTH_TWO_FA_REQUIRED]: ADMIN_ERROR.TYPES.AUTHENTICATION_ERROR,
    [ADMIN_ERROR.CODES.AUTH_TWO_FA_INVALID]: ADMIN_ERROR.TYPES.AUTHENTICATION_ERROR,
    [ADMIN_ERROR.CODES.AUTHZ_INSUFFICIENT_PERMISSIONS]: ADMIN_ERROR.TYPES.AUTHORIZATION_ERROR,
    [ADMIN_ERROR.CODES.AUTHZ_RESOURCE_ACCESS]: ADMIN_ERROR.TYPES.AUTHORIZATION_ERROR,
    [ADMIN_ERROR.CODES.AUTHZ_ROLE_INVALID]: ADMIN_ERROR.TYPES.AUTHORIZATION_ERROR,
    [ADMIN_ERROR.CODES.AUTHZ_PERMISSION_DENIED]: ADMIN_ERROR.TYPES.AUTHORIZATION_ERROR,
    [ADMIN_ERROR.CODES.VALIDATION_INVALID_INPUT]: ADMIN_ERROR.TYPES.VALIDATION_ERROR,
    [ADMIN_ERROR.CODES.VALIDATION_MISSING_FIELD]: ADMIN_ERROR.TYPES.VALIDATION_ERROR,
    [ADMIN_ERROR.CODES.VALIDATION_INVALID_FORMAT]: ADMIN_ERROR.TYPES.VALIDATION_ERROR,
    [ADMIN_ERROR.CODES.VALIDATION_INVALID_LENGTH]: ADMIN_ERROR.TYPES.VALIDATION_ERROR,
    [ADMIN_ERROR.CODES.VALIDATION_INVALID_RANGE]: ADMIN_ERROR.TYPES.VALIDATION_ERROR,
    [ADMIN_ERROR.CODES.VALIDATION_INVALID_EMAIL]: ADMIN_ERROR.TYPES.VALIDATION_ERROR,
    [ADMIN_ERROR.CODES.VALIDATION_INVALID_PHONE]: ADMIN_ERROR.TYPES.VALIDATION_ERROR,
    [ADMIN_ERROR.CODES.VALIDATION_INVALID_URL]: ADMIN_ERROR.TYPES.VALIDATION_ERROR,
    [ADMIN_ERROR.CODES.BUSINESS_INVALID_OPERATION]: ADMIN_ERROR.TYPES.BUSINESS_ERROR,
    [ADMIN_ERROR.CODES.BUSINESS_INSUFFICIENT_FUNDS]: ADMIN_ERROR.TYPES.BUSINESS_ERROR,
    [ADMIN_ERROR.CODES.BUSINESS_INVENTORY_ERROR]: ADMIN_ERROR.TYPES.BUSINESS_ERROR,
    [ADMIN_ERROR.CODES.BUSINESS_ORDER_ERROR]: ADMIN_ERROR.TYPES.BUSINESS_ERROR,
    [ADMIN_ERROR.CODES.BUSINESS_PAYMENT_ERROR]: ADMIN_ERROR.TYPES.BUSINESS_ERROR,
    [ADMIN_ERROR.CODES.BUSINESS_SHIPPING_ERROR]: ADMIN_ERROR.TYPES.BUSINESS_ERROR,
    [ADMIN_ERROR.CODES.INTEGRATION_API_ERROR]: ADMIN_ERROR.TYPES.INTEGRATION_ERROR,
    [ADMIN_ERROR.CODES.INTEGRATION_WEBHOOK_ERROR]: ADMIN_ERROR.TYPES.INTEGRATION_ERROR,
    [ADMIN_ERROR.CODES.INTEGRATION_THIRD_PARTY]: ADMIN_ERROR.TYPES.INTEGRATION_ERROR,
    [ADMIN_ERROR.CODES.INTEGRATION_SERVICE_UNAVAILABLE]: ADMIN_ERROR.TYPES.INTEGRATION_ERROR,
    [ADMIN_ERROR.CODES.RESOURCE_NOT_FOUND]: ADMIN_ERROR.TYPES.NOT_FOUND_ERROR,
    [ADMIN_ERROR.CODES.RESOURCE_UNAVAILABLE]: ADMIN_ERROR.TYPES.RESOURCE_ERROR,
    [ADMIN_ERROR.CODES.RESOURCE_EXHAUSTED]: ADMIN_ERROR.TYPES.RESOURCE_ERROR,
    [ADMIN_ERROR.CODES.RESOURCE_CONFLICT]: ADMIN_ERROR.TYPES.CONFLICT_ERROR,
    [ADMIN_ERROR.CODES.RATE_LIMIT_EXCEEDED]: ADMIN_ERROR.TYPES.RATE_LIMIT_ERROR,
    [ADMIN_ERROR.CODES.RATE_LIMIT_BURST]: ADMIN_ERROR.TYPES.RATE_LIMIT_ERROR,
    [ADMIN_ERROR.CODES.RATE_LIMIT_DAILY]: ADMIN_ERROR.TYPES.RATE_LIMIT_ERROR,
    [ADMIN_ERROR.CODES.TIMEOUT_REQUEST]: ADMIN_ERROR.TYPES.TIMEOUT_ERROR,
    [ADMIN_ERROR.CODES.TIMEOUT_RESPONSE]: ADMIN_ERROR.TYPES.TIMEOUT_ERROR,
    [ADMIN_ERROR.CODES.TIMEOUT_CONNECTION]: ADMIN_ERROR.TYPES.TIMEOUT_ERROR,
    [ADMIN_ERROR.CODES.TIMEOUT_READ]: ADMIN_ERROR.TYPES.TIMEOUT_ERROR,
    [ADMIN_ERROR.CODES.TIMEOUT_WRITE]: ADMIN_ERROR.TYPES.TIMEOUT_ERROR,
  };
  return typeMap[code] || ADMIN_ERROR.TYPES.UNKNOWN_ERROR;
}
