/**
 * Logistics HTTP Status Codes Constants
 * Contains all HTTP status codes used in logistics management
 */

export const LogisticsHttpStatus = {
  // 2xx Success
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,

  // 3xx Redirection
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,

  // 4xx Client Errors
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,

  // 5xx Server Errors
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,

  // Custom Logistics Business Codes (6xx range)
  SHIPMENT_NOT_FOUND: 6001,
  DELIVERY_FAILED: 6002,
  TRACKING_INVALID: 6003,
  SHIPMENT_DELAYED: 6004,
  SHIPMENT_CANCELLED: 6005,
  SHIPMENT_LOST: 6006,
  DELIVERY_ADDRESS_INVALID: 6007,
  CARRIER_UNAVAILABLE: 6008,
  WEIGHT_LIMIT_EXCEEDED: 6009,
  DIMENSION_LIMIT_EXCEEDED: 6010,
} as const;

export type LogisticsHttpStatusCode =
  (typeof LogisticsHttpStatus)[keyof typeof LogisticsHttpStatus];

export const LogisticsHttpStatusMessages: Record<LogisticsHttpStatusCode, string> = {
  [LogisticsHttpStatus.OK]: 'Success',
  [LogisticsHttpStatus.CREATED]: 'Shipment created successfully',
  [LogisticsHttpStatus.ACCEPTED]: 'Shipment request accepted',
  [LogisticsHttpStatus.NON_AUTHORITATIVE_INFORMATION]: 'Non-authoritative information',
  [LogisticsHttpStatus.NO_CONTENT]: 'No content',
  [LogisticsHttpStatus.RESET_CONTENT]: 'Reset content',
  [LogisticsHttpStatus.PARTIAL_CONTENT]: 'Partial content',

  [LogisticsHttpStatus.MULTIPLE_CHOICES]: 'Multiple choices',
  [LogisticsHttpStatus.MOVED_PERMANENTLY]: 'Moved permanently',
  [LogisticsHttpStatus.FOUND]: 'Found',
  [LogisticsHttpStatus.SEE_OTHER]: 'See other',
  [LogisticsHttpStatus.NOT_MODIFIED]: 'Not modified',
  [LogisticsHttpStatus.USE_PROXY]: 'Use proxy',
  [LogisticsHttpStatus.TEMPORARY_REDIRECT]: 'Temporary redirect',
  [LogisticsHttpStatus.PERMANENT_REDIRECT]: 'Permanent redirect',

  [LogisticsHttpStatus.BAD_REQUEST]: 'Bad request',
  [LogisticsHttpStatus.UNAUTHORIZED]: 'Unauthorized',
  [LogisticsHttpStatus.PAYMENT_REQUIRED]: 'Payment required',
  [LogisticsHttpStatus.FORBIDDEN]: 'Forbidden',
  [LogisticsHttpStatus.NOT_FOUND]: 'Logistics resource not found',
  [LogisticsHttpStatus.METHOD_NOT_ALLOWED]: 'Method not allowed',
  [LogisticsHttpStatus.NOT_ACCEPTABLE]: 'Not acceptable',
  [LogisticsHttpStatus.PROXY_AUTHENTICATION_REQUIRED]: 'Proxy authentication required',
  [LogisticsHttpStatus.REQUEST_TIMEOUT]: 'Request timeout',
  [LogisticsHttpStatus.CONFLICT]: 'Conflict',
  [LogisticsHttpStatus.GONE]: 'Gone',
  [LogisticsHttpStatus.LENGTH_REQUIRED]: 'Length required',
  [LogisticsHttpStatus.PRECONDITION_FAILED]: 'Precondition failed',
  [LogisticsHttpStatus.PAYLOAD_TOO_LARGE]: 'Payload too large',
  [LogisticsHttpStatus.URI_TOO_LONG]: 'URI too long',
  [LogisticsHttpStatus.UNSUPPORTED_MEDIA_TYPE]: 'Unsupported media type',
  [LogisticsHttpStatus.RANGE_NOT_SATISFIABLE]: 'Range not satisfiable',
  [LogisticsHttpStatus.EXPECTATION_FAILED]: 'Expectation failed',
  [LogisticsHttpStatus.IM_A_TEAPOT]: 'Im a teapot',
  [LogisticsHttpStatus.MISDIRECTED_REQUEST]: 'Misdirected request',
  [LogisticsHttpStatus.UNPROCESSABLE_ENTITY]: 'Unprocessable entity',
  [LogisticsHttpStatus.LOCKED]: 'Locked',
  [LogisticsHttpStatus.FAILED_DEPENDENCY]: 'Failed dependency',
  [LogisticsHttpStatus.TOO_EARLY]: 'Too early',
  [LogisticsHttpStatus.UPGRADE_REQUIRED]: 'Upgrade required',
  [LogisticsHttpStatus.PRECONDITION_REQUIRED]: 'Precondition required',
  [LogisticsHttpStatus.TOO_MANY_REQUESTS]: 'Too many requests',
  [LogisticsHttpStatus.REQUEST_HEADER_FIELDS_TOO_LARGE]: 'Request header fields too large',
  [LogisticsHttpStatus.UNAVAILABLE_FOR_LEGAL_REASONS]: 'Unavailable for legal reasons',

  [LogisticsHttpStatus.INTERNAL_SERVER_ERROR]: 'Internal server error',
  [LogisticsHttpStatus.NOT_IMPLEMENTED]: 'Not implemented',
  [LogisticsHttpStatus.BAD_GATEWAY]: 'Bad gateway',
  [LogisticsHttpStatus.SERVICE_UNAVAILABLE]: 'Service unavailable',
  [LogisticsHttpStatus.GATEWAY_TIMEOUT]: 'Gateway timeout',
  [LogisticsHttpStatus.HTTP_VERSION_NOT_SUPPORTED]: 'HTTP version not supported',
  [LogisticsHttpStatus.VARIANT_ALSO_NEGOTIATES]: 'Variant also negotiates',
  [LogisticsHttpStatus.INSUFFICIENT_STORAGE]: 'Insufficient storage',
  [LogisticsHttpStatus.LOOP_DETECTED]: 'Loop detected',
  [LogisticsHttpStatus.NOT_EXTENDED]: 'Not extended',
  [LogisticsHttpStatus.NETWORK_AUTHENTICATION_REQUIRED]: 'Network authentication required',

  // Custom logistics messages
  [LogisticsHttpStatus.SHIPMENT_NOT_FOUND]: 'Shipment not found',
  [LogisticsHttpStatus.DELIVERY_FAILED]: 'Delivery failed',
  [LogisticsHttpStatus.TRACKING_INVALID]: 'Invalid tracking number',
  [LogisticsHttpStatus.SHIPMENT_DELAYED]: 'Shipment is delayed',
  [LogisticsHttpStatus.SHIPMENT_CANCELLED]: 'Shipment has been cancelled',
  [LogisticsHttpStatus.SHIPMENT_LOST]: 'Shipment has been lost',
  [LogisticsHttpStatus.DELIVERY_ADDRESS_INVALID]: 'Invalid delivery address',
  [LogisticsHttpStatus.CARRIER_UNAVAILABLE]: 'Carrier is unavailable',
  [LogisticsHttpStatus.WEIGHT_LIMIT_EXCEEDED]: 'Weight limit exceeded',
  [LogisticsHttpStatus.DIMENSION_LIMIT_EXCEEDED]: 'Dimension limit exceeded',
};

export const LogisticsHttpStatusCategories = {
  SUCCESS: [200, 201, 202, 203, 204, 205, 206],
  REDIRECTION: [300, 301, 302, 303, 304, 305, 307, 308],
  CLIENT_ERROR: [
    400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418,
    421, 422, 423, 424, 425, 426, 428, 429, 431, 451,
  ],
  SERVER_ERROR: [500, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511],
  LOGISTICS_ERROR: [6001, 6002, 6003, 6004, 6005, 6006, 6007, 6008, 6009, 6010],
} as const;
