/**
 * Shipping Rate Type Constants
 * Types of shipping rates
 */

import { LOGISTICS_SHIPPING_RATE } from './shipping-rate.constants';
import type { LogisticsShippingRateType } from './shipping-rate.constants';

export const LOGISTICS_SHIPPING_RATE_TYPE = {
  // Rate Categories
  CATEGORIES: {
    FLAT: 'flat',
    WEIGHT_BASED: 'weight_based',
    DISTANCE_BASED: 'distance_based',
    VOLUME_BASED: 'volume_based',
    ITEM_BASED: 'item_based',
    TIERED: 'tiered',
    DYNAMIC: 'dynamic',
  } as const,

  // Rate Icons (for UI)
  ICONS: {
    FLAT: '📋',
    WEIGHT_BASED: '⚖️',
    DISTANCE_BASED: '📏',
    VOLUME_BASED: '📦',
    ITEM_BASED: '🛍️',
    TIERED: '📊',
    DYNAMIC: '🔄',
  } as const,

  // Rate Colors (for UI)
  COLORS: {
    FLAT: '#blue-500',
    WEIGHT_BASED: '#green-500',
    DISTANCE_BASED: '#orange-500',
    VOLUME_BASED: '#purple-500',
    ITEM_BASED: '#red-500',
    TIERED: '#yellow-500',
    DYNAMIC: '#teal-500',
  } as const,

  // Complexity Levels
  COMPLEXITY: {
    FLAT: 1,
    WEIGHT_BASED: 2,
    DISTANCE_BASED: 2,
    VOLUME_BASED: 2,
    ITEM_BASED: 2,
    TIERED: 3,
    DYNAMIC: 4,
  } as const,

  // Accuracy Levels
  ACCURACY: {
    FLAT: 30,
    WEIGHT_BASED: 70,
    DISTANCE_BASED: 60,
    VOLUME_BASED: 65,
    ITEM_BASED: 75,
    TIERED: 85,
    DYNAMIC: 90,
  } as const,
} as const;

// Rate Categories
export type LogisticsShippingRateTypeCategory =
  (typeof LOGISTICS_SHIPPING_RATE_TYPE.CATEGORIES)[keyof typeof LOGISTICS_SHIPPING_RATE_TYPE.CATEGORIES];

// Rate Icons
export type LogisticsShippingRateTypeIcon =
  (typeof LOGISTICS_SHIPPING_RATE_TYPE.ICONS)[keyof typeof LOGISTICS_SHIPPING_RATE_TYPE.ICONS];

// Rate Colors
export type LogisticsShippingRateTypeColor =
  (typeof LOGISTICS_SHIPPING_RATE_TYPE.COLORS)[keyof typeof LOGISTICS_SHIPPING_RATE_TYPE.COLORS];

// Utility Functions
export function logisticsShippingRateTypeGetLabel(type: LogisticsShippingRateType): string {
  const labels: Record<LogisticsShippingRateType, string> = {
    [LOGISTICS_SHIPPING_RATE.TYPES.FLAT]: 'Flat Rate',
    [LOGISTICS_SHIPPING_RATE.TYPES.WEIGHT_BASED]: 'Weight Based',
    [LOGISTICS_SHIPPING_RATE.TYPES.DISTANCE_BASED]: 'Distance Based',
    [LOGISTICS_SHIPPING_RATE.TYPES.VOLUME_BASED]: 'Volume Based',
    [LOGISTICS_SHIPPING_RATE.TYPES.ITEM_BASED]: 'Item Based',
    [LOGISTICS_SHIPPING_RATE.TYPES.TIERED]: 'Tiered Rate',
    [LOGISTICS_SHIPPING_RATE.TYPES.DYNAMIC]: 'Dynamic Rate',
  };
  return labels[type] || 'Unknown';
}

export function logisticsShippingRateTypeGetIcon(
  type: LogisticsShippingRateType
): LogisticsShippingRateTypeIcon {
  const icons: Record<LogisticsShippingRateType, LogisticsShippingRateTypeIcon> = {
    [LOGISTICS_SHIPPING_RATE.TYPES.FLAT]: LOGISTICS_SHIPPING_RATE_TYPE.ICONS.FLAT,
    [LOGISTICS_SHIPPING_RATE.TYPES.WEIGHT_BASED]: LOGISTICS_SHIPPING_RATE_TYPE.ICONS.WEIGHT_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.DISTANCE_BASED]:
      LOGISTICS_SHIPPING_RATE_TYPE.ICONS.DISTANCE_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.VOLUME_BASED]: LOGISTICS_SHIPPING_RATE_TYPE.ICONS.VOLUME_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.ITEM_BASED]: LOGISTICS_SHIPPING_RATE_TYPE.ICONS.ITEM_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.TIERED]: LOGISTICS_SHIPPING_RATE_TYPE.ICONS.TIERED,
    [LOGISTICS_SHIPPING_RATE.TYPES.DYNAMIC]: LOGISTICS_SHIPPING_RATE_TYPE.ICONS.DYNAMIC,
  };
  return icons[type] || '📋';
}

export function logisticsShippingRateTypeGetColor(
  type: LogisticsShippingRateType
): LogisticsShippingRateTypeColor {
  const colors: Record<LogisticsShippingRateType, LogisticsShippingRateTypeColor> = {
    [LOGISTICS_SHIPPING_RATE.TYPES.FLAT]: LOGISTICS_SHIPPING_RATE_TYPE.COLORS.FLAT,
    [LOGISTICS_SHIPPING_RATE.TYPES.WEIGHT_BASED]: LOGISTICS_SHIPPING_RATE_TYPE.COLORS.WEIGHT_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.DISTANCE_BASED]:
      LOGISTICS_SHIPPING_RATE_TYPE.COLORS.DISTANCE_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.VOLUME_BASED]: LOGISTICS_SHIPPING_RATE_TYPE.COLORS.VOLUME_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.ITEM_BASED]: LOGISTICS_SHIPPING_RATE_TYPE.COLORS.ITEM_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.TIERED]: LOGISTICS_SHIPPING_RATE_TYPE.COLORS.TIERED,
    [LOGISTICS_SHIPPING_RATE.TYPES.DYNAMIC]: LOGISTICS_SHIPPING_RATE_TYPE.COLORS.DYNAMIC,
  };
  return colors[type] || '#blue-500';
}

export function logisticsShippingRateTypeGetComplexity(type: LogisticsShippingRateType): number {
  const complexity: Record<LogisticsShippingRateType, number> = {
    [LOGISTICS_SHIPPING_RATE.TYPES.FLAT]: LOGISTICS_SHIPPING_RATE_TYPE.COMPLEXITY.FLAT,
    [LOGISTICS_SHIPPING_RATE.TYPES.WEIGHT_BASED]:
      LOGISTICS_SHIPPING_RATE_TYPE.COMPLEXITY.WEIGHT_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.DISTANCE_BASED]:
      LOGISTICS_SHIPPING_RATE_TYPE.COMPLEXITY.DISTANCE_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.VOLUME_BASED]:
      LOGISTICS_SHIPPING_RATE_TYPE.COMPLEXITY.VOLUME_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.ITEM_BASED]: LOGISTICS_SHIPPING_RATE_TYPE.COMPLEXITY.ITEM_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.TIERED]: LOGISTICS_SHIPPING_RATE_TYPE.COMPLEXITY.TIERED,
    [LOGISTICS_SHIPPING_RATE.TYPES.DYNAMIC]: LOGISTICS_SHIPPING_RATE_TYPE.COMPLEXITY.DYNAMIC,
  };
  return complexity[type] || 2;
}

export function logisticsShippingRateTypeGetAccuracy(type: LogisticsShippingRateType): number {
  const accuracy: Record<LogisticsShippingRateType, number> = {
    [LOGISTICS_SHIPPING_RATE.TYPES.FLAT]: LOGISTICS_SHIPPING_RATE_TYPE.ACCURACY.FLAT,
    [LOGISTICS_SHIPPING_RATE.TYPES.WEIGHT_BASED]:
      LOGISTICS_SHIPPING_RATE_TYPE.ACCURACY.WEIGHT_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.DISTANCE_BASED]:
      LOGISTICS_SHIPPING_RATE_TYPE.ACCURACY.DISTANCE_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.VOLUME_BASED]:
      LOGISTICS_SHIPPING_RATE_TYPE.ACCURACY.VOLUME_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.ITEM_BASED]: LOGISTICS_SHIPPING_RATE_TYPE.ACCURACY.ITEM_BASED,
    [LOGISTICS_SHIPPING_RATE.TYPES.TIERED]: LOGISTICS_SHIPPING_RATE_TYPE.ACCURACY.TIERED,
    [LOGISTICS_SHIPPING_RATE.TYPES.DYNAMIC]: LOGISTICS_SHIPPING_RATE_TYPE.ACCURACY.DYNAMIC,
  };
  return accuracy[type] || 50;
}
