// ============================================
// নোটিফিকেশন টেমপ্লেট স্ট্যাটাস সংক্রান্ত কনস্ট্যান্টসমূহ
// ============================================

// ============================================
// ১. টেমপ্লেট স্ট্যাটাস
// ============================================

/**
 * নোটিফিকেশন টেমপ্লেট স্ট্যাটাস
 * টেমপ্লেটের বর্তমান অবস্থা নির্দেশ করে
 */
export type NotificationTemplateStatus =
  | typeof NOTIFICATION_TEMPLATE_STATUS_DRAFT
  | typeof NOTIFICATION_TEMPLATE_STATUS_ACTIVE
  | typeof NOTIFICATION_TEMPLATE_STATUS_INACTIVE
  | typeof NOTIFICATION_TEMPLATE_STATUS_ARCHIVED
  | typeof NOTIFICATION_TEMPLATE_STATUS_DELETED
  | typeof NOTIFICATION_TEMPLATE_STATUS_PENDING_APPROVAL
  | typeof NOTIFICATION_TEMPLATE_STATUS_REJECTED
  | typeof NOTIFICATION_TEMPLATE_STATUS_PUBLISHED
  | typeof NOTIFICATION_TEMPLATE_STATUS_DEPRECATED
  | typeof NOTIFICATION_TEMPLATE_STATUS_REVIEW
  | typeof NOTIFICATION_TEMPLATE_STATUS_APPROVED
  | typeof NOTIFICATION_TEMPLATE_STATUS_SCHEDULED
  | typeof NOTIFICATION_TEMPLATE_STATUS_EXPIRED
  | typeof NOTIFICATION_TEMPLATE_STATUS_SUSPENDED
  | typeof NOTIFICATION_TEMPLATE_STATUS_RESTORED;

/**
 * ড্রাফট স্ট্যাটাস
 * @description টেমপ্লেট খসড়া হিসেবে সংরক্ষিত
 */
export const NOTIFICATION_TEMPLATE_STATUS_DRAFT = 'DRAFT';

/**
 * অ্যাক্টিভ স্ট্যাটাস
 * @description টেমপ্লেট সক্রিয় এবং ব্যবহারযোগ্য
 */
export const NOTIFICATION_TEMPLATE_STATUS_ACTIVE = 'ACTIVE';

/**
 * ইনঅ্যাক্টিভ স্ট্যাটাস
 * @description টেমপ্লেট নিষ্ক্রিয়
 */
export const NOTIFICATION_TEMPLATE_STATUS_INACTIVE = 'INACTIVE';

/**
 * আর্কাইভড স্ট্যাটাস
 * @description টেমপ্লেট আর্কাইভ করা হয়েছে
 */
export const NOTIFICATION_TEMPLATE_STATUS_ARCHIVED = 'ARCHIVED';

/**
 * ডিলিটেড স্ট্যাটাস
 * @description টেমপ্লেট মুছে ফেলা হয়েছে
 */
export const NOTIFICATION_TEMPLATE_STATUS_DELETED = 'DELETED';

/**
 * পেন্ডিং অ্যাপ্রুভাল স্ট্যাটাস
 * @description টেমপ্লেট অনুমোদনের অপেক্ষায়
 */
export const NOTIFICATION_TEMPLATE_STATUS_PENDING_APPROVAL = 'PENDING_APPROVAL';

/**
 * রিজেক্টেড স্ট্যাটাস
 * @description টেমপ্লেট বাতিল করা হয়েছে
 */
export const NOTIFICATION_TEMPLATE_STATUS_REJECTED = 'REJECTED';

/**
 * পাবলিশড স্ট্যাটাস
 * @description টেমপ্লেট প্রকাশিত হয়েছে
 */
export const NOTIFICATION_TEMPLATE_STATUS_PUBLISHED = 'PUBLISHED';

/**
 * ডিপ্রিকেটেড স্ট্যাটাস
 * @description টেমপ্লেট অপ্রচলিত
 */
export const NOTIFICATION_TEMPLATE_STATUS_DEPRECATED = 'DEPRECATED';

/**
 * রিভিউ স্ট্যাটাস
 * @description টেমপ্লেট পর্যালোচনাধীন
 */
export const NOTIFICATION_TEMPLATE_STATUS_REVIEW = 'REVIEW';

/**
 * অ্যাপ্রুভড স্ট্যাটাস
 * @description টেমপ্লেট অনুমোদিত
 */
export const NOTIFICATION_TEMPLATE_STATUS_APPROVED = 'APPROVED';

/**
 * স্কেডিউলড স্ট্যাটাস
 * @description টেমপ্লেট নির্ধারিত সময়ে সক্রিয় হবে
 */
export const NOTIFICATION_TEMPLATE_STATUS_SCHEDULED = 'SCHEDULED';

/**
 * এক্সপাইরড স্ট্যাটাস
 * @description টেমপ্লেটের মেয়াদ শেষ
 */
export const NOTIFICATION_TEMPLATE_STATUS_EXPIRED = 'EXPIRED';

/**
 * সাসপেন্ডেড স্ট্যাটাস
 * @description টেমপ্লেট স্থগিত করা হয়েছে
 */
export const NOTIFICATION_TEMPLATE_STATUS_SUSPENDED = 'SUSPENDED';

/**
 * রিস্টোরড স্ট্যাটাস
 * @description টেমপ্লেট পুনরুদ্ধার করা হয়েছে
 */
export const NOTIFICATION_TEMPLATE_STATUS_RESTORED = 'RESTORED';

// ============================================
// ২. টেমপ্লেট স্ট্যাটাস গ্রুপ
// ============================================

/**
 * টেমপ্লেট স্ট্যাটাস গ্রুপ
 */
export type NotificationTemplateStatusGroup =
  | typeof NOTIFICATION_TEMPLATE_STATUS_GROUP_ACTIVE
  | typeof NOTIFICATION_TEMPLATE_STATUS_GROUP_INACTIVE
  | typeof NOTIFICATION_TEMPLATE_STATUS_GROUP_DRAFT
  | typeof NOTIFICATION_TEMPLATE_STATUS_GROUP_PENDING
  | typeof NOTIFICATION_TEMPLATE_STATUS_GROUP_TERMINAL
  | typeof NOTIFICATION_TEMPLATE_STATUS_GROUP_TRANSIENT;

/**
 * অ্যাক্টিভ গ্রুপ
 * @description সক্রিয় স্ট্যাটাস
 */
export const NOTIFICATION_TEMPLATE_STATUS_GROUP_ACTIVE = 'ACTIVE';

/**
 * ইনঅ্যাক্টিভ গ্রুপ
 * @description নিষ্ক্রিয় স্ট্যাটাস
 */
export const NOTIFICATION_TEMPLATE_STATUS_GROUP_INACTIVE = 'INACTIVE';

/**
 * ড্রাফট গ্রুপ
 * @description খসড়া স্ট্যাটাস
 */
export const NOTIFICATION_TEMPLATE_STATUS_GROUP_DRAFT = 'DRAFT';

/**
 * পেন্ডিং গ্রুপ
 * @description অপেক্ষমান স্ট্যাটাস
 */
export const NOTIFICATION_TEMPLATE_STATUS_GROUP_PENDING = 'PENDING';

/**
 * টার্মিনাল গ্রুপ
 * @description চূড়ান্ত অবস্থা
 */
export const NOTIFICATION_TEMPLATE_STATUS_GROUP_TERMINAL = 'TERMINAL';

/**
 * ট্রানজিয়েন্ট গ্রুপ
 * @description ক্ষণস্থায়ী অবস্থা
 */
export const NOTIFICATION_TEMPLATE_STATUS_GROUP_TRANSIENT = 'TRANSIENT';

// ============================================
// ৩. টেমপ্লেট স্ট্যাটাস থেকে গ্রুপ ম্যাপিং
// ============================================

/**
 * টেমপ্লেট স্ট্যাটাস থেকে গ্রুপ ম্যাপিং
 */
export const NOTIFICATION_TEMPLATE_STATUS_TO_GROUP: Record<
  NotificationTemplateStatus,
  NotificationTemplateStatusGroup
> = {
  [NOTIFICATION_TEMPLATE_STATUS_DRAFT]: NOTIFICATION_TEMPLATE_STATUS_GROUP_DRAFT,
  [NOTIFICATION_TEMPLATE_STATUS_ACTIVE]: NOTIFICATION_TEMPLATE_STATUS_GROUP_ACTIVE,
  [NOTIFICATION_TEMPLATE_STATUS_INACTIVE]: NOTIFICATION_TEMPLATE_STATUS_GROUP_INACTIVE,
  [NOTIFICATION_TEMPLATE_STATUS_ARCHIVED]: NOTIFICATION_TEMPLATE_STATUS_GROUP_TERMINAL,
  [NOTIFICATION_TEMPLATE_STATUS_DELETED]: NOTIFICATION_TEMPLATE_STATUS_GROUP_TERMINAL,
  [NOTIFICATION_TEMPLATE_STATUS_PENDING_APPROVAL]: NOTIFICATION_TEMPLATE_STATUS_GROUP_PENDING,
  [NOTIFICATION_TEMPLATE_STATUS_REJECTED]: NOTIFICATION_TEMPLATE_STATUS_GROUP_TERMINAL,
  [NOTIFICATION_TEMPLATE_STATUS_PUBLISHED]: NOTIFICATION_TEMPLATE_STATUS_GROUP_ACTIVE,
  [NOTIFICATION_TEMPLATE_STATUS_DEPRECATED]: NOTIFICATION_TEMPLATE_STATUS_GROUP_INACTIVE,
  [NOTIFICATION_TEMPLATE_STATUS_REVIEW]: NOTIFICATION_TEMPLATE_STATUS_GROUP_PENDING,
  [NOTIFICATION_TEMPLATE_STATUS_APPROVED]: NOTIFICATION_TEMPLATE_STATUS_GROUP_TRANSIENT,
  [NOTIFICATION_TEMPLATE_STATUS_SCHEDULED]: NOTIFICATION_TEMPLATE_STATUS_GROUP_PENDING,
  [NOTIFICATION_TEMPLATE_STATUS_EXPIRED]: NOTIFICATION_TEMPLATE_STATUS_GROUP_TERMINAL,
  [NOTIFICATION_TEMPLATE_STATUS_SUSPENDED]: NOTIFICATION_TEMPLATE_STATUS_GROUP_INACTIVE,
  [NOTIFICATION_TEMPLATE_STATUS_RESTORED]: NOTIFICATION_TEMPLATE_STATUS_GROUP_TRANSIENT,
};

// ============================================
// ৪. টেমপ্লেট স্ট্যাটাস লেবেল
// ============================================

/**
 * টেমপ্লেট স্ট্যাটাস লেবেল
 */
export const NOTIFICATION_TEMPLATE_STATUS_LABELS: Record<NotificationTemplateStatus, string> = {
  [NOTIFICATION_TEMPLATE_STATUS_DRAFT]: 'খসড়া',
  [NOTIFICATION_TEMPLATE_STATUS_ACTIVE]: 'সক্রিয়',
  [NOTIFICATION_TEMPLATE_STATUS_INACTIVE]: 'নিষ্ক্রিয়',
  [NOTIFICATION_TEMPLATE_STATUS_ARCHIVED]: 'আর্কাইভ',
  [NOTIFICATION_TEMPLATE_STATUS_DELETED]: 'মুছে ফেলা',
  [NOTIFICATION_TEMPLATE_STATUS_PENDING_APPROVAL]: 'অনুমোদনের অপেক্ষায়',
  [NOTIFICATION_TEMPLATE_STATUS_REJECTED]: 'বাতিল',
  [NOTIFICATION_TEMPLATE_STATUS_PUBLISHED]: 'প্রকাশিত',
  [NOTIFICATION_TEMPLATE_STATUS_DEPRECATED]: 'অপ্রচলিত',
  [NOTIFICATION_TEMPLATE_STATUS_REVIEW]: 'পর্যালোচনাধীন',
  [NOTIFICATION_TEMPLATE_STATUS_APPROVED]: 'অনুমোদিত',
  [NOTIFICATION_TEMPLATE_STATUS_SCHEDULED]: 'নির্ধারিত',
  [NOTIFICATION_TEMPLATE_STATUS_EXPIRED]: 'মেয়াদোত্তীর্ণ',
  [NOTIFICATION_TEMPLATE_STATUS_SUSPENDED]: 'স্থগিত',
  [NOTIFICATION_TEMPLATE_STATUS_RESTORED]: 'পুনরুদ্ধার',
};

// ============================================
// ৫. টেমপ্লেট স্ট্যাটাস আইকন
// ============================================

/**
 * টেমপ্লেট স্ট্যাটাস আইকন
 */
export const NOTIFICATION_TEMPLATE_STATUS_ICONS: Record<NotificationTemplateStatus, string> = {
  [NOTIFICATION_TEMPLATE_STATUS_DRAFT]: 'draft',
  [NOTIFICATION_TEMPLATE_STATUS_ACTIVE]: 'check_circle',
  [NOTIFICATION_TEMPLATE_STATUS_INACTIVE]: 'cancel',
  [NOTIFICATION_TEMPLATE_STATUS_ARCHIVED]: 'archive',
  [NOTIFICATION_TEMPLATE_STATUS_DELETED]: 'delete',
  [NOTIFICATION_TEMPLATE_STATUS_PENDING_APPROVAL]: 'pending',
  [NOTIFICATION_TEMPLATE_STATUS_REJECTED]: 'block',
  [NOTIFICATION_TEMPLATE_STATUS_PUBLISHED]: 'publish',
  [NOTIFICATION_TEMPLATE_STATUS_DEPRECATED]: 'warning',
  [NOTIFICATION_TEMPLATE_STATUS_REVIEW]: 'rate_review',
  [NOTIFICATION_TEMPLATE_STATUS_APPROVED]: 'thumb_up',
  [NOTIFICATION_TEMPLATE_STATUS_SCHEDULED]: 'schedule',
  [NOTIFICATION_TEMPLATE_STATUS_EXPIRED]: 'timer',
  [NOTIFICATION_TEMPLATE_STATUS_SUSPENDED]: 'pause_circle',
  [NOTIFICATION_TEMPLATE_STATUS_RESTORED]: 'restore',
};

// ============================================
// ৬. টেমপ্লেট স্ট্যাটাস কালার
// ============================================

/**
 * টেমপ্লেট স্ট্যাটাস কালার
 */
export const NOTIFICATION_TEMPLATE_STATUS_COLORS: Record<NotificationTemplateStatus, string> = {
  [NOTIFICATION_TEMPLATE_STATUS_DRAFT]: '#9E9E9E', // Grey
  [NOTIFICATION_TEMPLATE_STATUS_ACTIVE]: '#4CAF50', // Green
  [NOTIFICATION_TEMPLATE_STATUS_INACTIVE]: '#FF9800', // Orange
  [NOTIFICATION_TEMPLATE_STATUS_ARCHIVED]: '#607D8B', // Blue Grey
  [NOTIFICATION_TEMPLATE_STATUS_DELETED]: '#757575', // Dark Grey
  [NOTIFICATION_TEMPLATE_STATUS_PENDING_APPROVAL]: '#FFC107', // Amber
  [NOTIFICATION_TEMPLATE_STATUS_REJECTED]: '#F44336', // Red
  [NOTIFICATION_TEMPLATE_STATUS_PUBLISHED]: '#2196F3', // Blue
  [NOTIFICATION_TEMPLATE_STATUS_DEPRECATED]: '#FF5722', // Deep Orange
  [NOTIFICATION_TEMPLATE_STATUS_REVIEW]: '#9C27B0', // Purple
  [NOTIFICATION_TEMPLATE_STATUS_APPROVED]: '#8BC34A', // Light Green
  [NOTIFICATION_TEMPLATE_STATUS_SCHEDULED]: '#00BCD4', // Cyan
  [NOTIFICATION_TEMPLATE_STATUS_EXPIRED]: '#795548', // Brown
  [NOTIFICATION_TEMPLATE_STATUS_SUSPENDED]: '#FF6F00', // Dark Amber
  [NOTIFICATION_TEMPLATE_STATUS_RESTORED]: '#3F51B5', // Indigo
};

// ============================================
// ৭. টার্মিনাল টেমপ্লেট স্ট্যাটাসসমূহ
// ============================================

/**
 * টার্মিনাল টেমপ্লেট স্ট্যাটাসসমূহ
 * যে স্ট্যাটাসগুলো চূড়ান্ত এবং আর পরিবর্তন হয় না
 */
export const NOTIFICATION_TEMPLATE_TERMINAL_STATUSES: NotificationTemplateStatus[] = [
  NOTIFICATION_TEMPLATE_STATUS_ARCHIVED,
  NOTIFICATION_TEMPLATE_STATUS_DELETED,
  NOTIFICATION_TEMPLATE_STATUS_REJECTED,
  NOTIFICATION_TEMPLATE_STATUS_EXPIRED,
];

// ============================================
// ৮. অ্যাক্টিভ টেমপ্লেট স্ট্যাটাসসমূহ
// ============================================

/**
 * অ্যাক্টিভ টেমপ্লেট স্ট্যাটাসসমূহ
 * যে স্ট্যাটাসগুলো সক্রিয়
 */
export const NOTIFICATION_TEMPLATE_ACTIVE_STATUSES: NotificationTemplateStatus[] = [
  NOTIFICATION_TEMPLATE_STATUS_ACTIVE,
  NOTIFICATION_TEMPLATE_STATUS_PUBLISHED,
];

// ============================================
// ৯. পেন্ডিং টেমপ্লেট স্ট্যাটাসসমূহ
// ============================================

/**
 * পেন্ডিং টেমপ্লেট স্ট্যাটাসসমূহ
 * যে স্ট্যাটাসগুলো অপেক্ষমান
 */
export const NOTIFICATION_TEMPLATE_PENDING_STATUSES: NotificationTemplateStatus[] = [
  NOTIFICATION_TEMPLATE_STATUS_PENDING_APPROVAL,
  NOTIFICATION_TEMPLATE_STATUS_REVIEW,
  NOTIFICATION_TEMPLATE_STATUS_SCHEDULED,
];

// ============================================
// ১০. টেমপ্লেট স্ট্যাটাস কনফিগারেশন
// ============================================

/**
 * টেমপ্লেট স্ট্যাটাস কনফিগারেশন
 */
export interface NotificationTemplateStatusConfig {
  /** স্ট্যাটাসের নাম */
  status: NotificationTemplateStatus;
  /** স্ট্যাটাসের লেবেল */
  label: string;
  /** স্ট্যাটাসের আইকন */
  icon: string;
  /** স্ট্যাটাসের কালার */
  color: string;
  /** স্ট্যাটাসের গ্রুপ */
  group: NotificationTemplateStatusGroup;
  /** টার্মিনাল স্ট্যাটাস কিনা */
  isTerminal: boolean;
  /** অ্যাক্টিভ স্ট্যাটাস কিনা */
  isActive: boolean;
  /** পেন্ডিং স্ট্যাটাস কিনা */
  isPending: boolean;
}

/**
 * সব টেমপ্লেট স্ট্যাটাসের কনফিগারেশন
 */
export const NOTIFICATION_TEMPLATE_STATUS_CONFIGS: NotificationTemplateStatusConfig[] = [
  {
    status: NOTIFICATION_TEMPLATE_STATUS_DRAFT,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_DRAFT],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_DRAFT],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_DRAFT],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_DRAFT],
    isTerminal: false,
    isActive: false,
    isPending: false,
  },
  {
    status: NOTIFICATION_TEMPLATE_STATUS_ACTIVE,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_ACTIVE],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_ACTIVE],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_ACTIVE],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_ACTIVE],
    isTerminal: false,
    isActive: true,
    isPending: false,
  },
  {
    status: NOTIFICATION_TEMPLATE_STATUS_INACTIVE,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_INACTIVE],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_INACTIVE],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_INACTIVE],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_INACTIVE],
    isTerminal: false,
    isActive: false,
    isPending: false,
  },
  {
    status: NOTIFICATION_TEMPLATE_STATUS_ARCHIVED,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_ARCHIVED],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_ARCHIVED],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_ARCHIVED],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_ARCHIVED],
    isTerminal: true,
    isActive: false,
    isPending: false,
  },
  {
    status: NOTIFICATION_TEMPLATE_STATUS_DELETED,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_DELETED],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_DELETED],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_DELETED],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_DELETED],
    isTerminal: true,
    isActive: false,
    isPending: false,
  },
  {
    status: NOTIFICATION_TEMPLATE_STATUS_PENDING_APPROVAL,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_PENDING_APPROVAL],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_PENDING_APPROVAL],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_PENDING_APPROVAL],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_PENDING_APPROVAL],
    isTerminal: false,
    isActive: false,
    isPending: true,
  },
  {
    status: NOTIFICATION_TEMPLATE_STATUS_REJECTED,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_REJECTED],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_REJECTED],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_REJECTED],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_REJECTED],
    isTerminal: true,
    isActive: false,
    isPending: false,
  },
  {
    status: NOTIFICATION_TEMPLATE_STATUS_PUBLISHED,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_PUBLISHED],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_PUBLISHED],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_PUBLISHED],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_PUBLISHED],
    isTerminal: false,
    isActive: true,
    isPending: false,
  },
  {
    status: NOTIFICATION_TEMPLATE_STATUS_DEPRECATED,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_DEPRECATED],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_DEPRECATED],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_DEPRECATED],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_DEPRECATED],
    isTerminal: false,
    isActive: false,
    isPending: false,
  },
  {
    status: NOTIFICATION_TEMPLATE_STATUS_REVIEW,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_REVIEW],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_REVIEW],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_REVIEW],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_REVIEW],
    isTerminal: false,
    isActive: false,
    isPending: true,
  },
  {
    status: NOTIFICATION_TEMPLATE_STATUS_APPROVED,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_APPROVED],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_APPROVED],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_APPROVED],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_APPROVED],
    isTerminal: false,
    isActive: false,
    isPending: false,
  },
  {
    status: NOTIFICATION_TEMPLATE_STATUS_SCHEDULED,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_SCHEDULED],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_SCHEDULED],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_SCHEDULED],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_SCHEDULED],
    isTerminal: false,
    isActive: false,
    isPending: true,
  },
  {
    status: NOTIFICATION_TEMPLATE_STATUS_EXPIRED,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_EXPIRED],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_EXPIRED],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_EXPIRED],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_EXPIRED],
    isTerminal: true,
    isActive: false,
    isPending: false,
  },
  {
    status: NOTIFICATION_TEMPLATE_STATUS_SUSPENDED,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_SUSPENDED],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_SUSPENDED],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_SUSPENDED],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_SUSPENDED],
    isTerminal: false,
    isActive: false,
    isPending: false,
  },
  {
    status: NOTIFICATION_TEMPLATE_STATUS_RESTORED,
    label: NOTIFICATION_TEMPLATE_STATUS_LABELS[NOTIFICATION_TEMPLATE_STATUS_RESTORED],
    icon: NOTIFICATION_TEMPLATE_STATUS_ICONS[NOTIFICATION_TEMPLATE_STATUS_RESTORED],
    color: NOTIFICATION_TEMPLATE_STATUS_COLORS[NOTIFICATION_TEMPLATE_STATUS_RESTORED],
    group: NOTIFICATION_TEMPLATE_STATUS_TO_GROUP[NOTIFICATION_TEMPLATE_STATUS_RESTORED],
    isTerminal: false,
    isActive: false,
    isPending: false,
  },
];
