// ============================================
// নোটিফিকেশন সিস্টেমের এরর কোড এবং মেসেজ সংক্রান্ত কনস্ট্যান্টসমূহ
// ============================================

// ============================================
// ১. এরর ক্যাটাগরি
// ============================================

/**
 * এরর ক্যাটাগরি
 * ত্রুটির ধরন ও উৎস নির্দেশ করে
 */
export type NotificationErrorCategory =
  | typeof NOTIFICATION_ERROR_CATEGORY_VALIDATION
  | typeof NOTIFICATION_ERROR_CATEGORY_AUTHENTICATION
  | typeof NOTIFICATION_ERROR_CATEGORY_AUTHORIZATION
  | typeof NOTIFICATION_ERROR_CATEGORY_NOT_FOUND
  | typeof NOTIFICATION_ERROR_CATEGORY_RATE_LIMIT
  | typeof NOTIFICATION_ERROR_CATEGORY_INTERNAL_ERROR
  | typeof NOTIFICATION_ERROR_CATEGORY_PROVIDER_ERROR
  | typeof NOTIFICATION_ERROR_CATEGORY_NETWORK_ERROR
  | typeof NOTIFICATION_ERROR_CATEGORY_TIMEOUT
  | typeof NOTIFICATION_ERROR_CATEGORY_BUSINESS_LOGIC
  | typeof NOTIFICATION_ERROR_CATEGORY_DATA_ERROR
  | typeof NOTIFICATION_ERROR_CATEGORY_CONFIG_ERROR;

/**
 * ভ্যালিডেশন ক্যাটাগরি
 * @description ইনপুট ভ্যালিডেশন ত্রুটি
 */
export const NOTIFICATION_ERROR_CATEGORY_VALIDATION = 'VALIDATION';

/**
 * অথেনটিকেশন ক্যাটাগরি
 * @description প্রমাণীকরণ ত্রুটি
 */
export const NOTIFICATION_ERROR_CATEGORY_AUTHENTICATION = 'AUTHENTICATION';

/**
 * অথরাইজেশন ক্যাটাগরি
 * @description অনুমোদন ত্রুটি
 */
export const NOTIFICATION_ERROR_CATEGORY_AUTHORIZATION = 'AUTHORIZATION';

/**
 * নট ফাউন্ড ক্যাটাগরি
 * @description রিসোর্স খুঁজে না পাওয়া
 */
export const NOTIFICATION_ERROR_CATEGORY_NOT_FOUND = 'NOT_FOUND';

/**
 * রেট লিমিট ক্যাটাগরি
 * @description রেট লিমিট অতিক্রম
 */
export const NOTIFICATION_ERROR_CATEGORY_RATE_LIMIT = 'RATE_LIMIT';

/**
 * ইন্টারনাল এরর ক্যাটাগরি
 * @description অভ্যন্তরীণ সার্ভার ত্রুটি
 */
export const NOTIFICATION_ERROR_CATEGORY_INTERNAL_ERROR = 'INTERNAL_ERROR';

/**
 * প্রোভাইডার এরর ক্যাটাগরি
 * @description থার্ড-পার্টি প্রোভাইডার ত্রুটি
 */
export const NOTIFICATION_ERROR_CATEGORY_PROVIDER_ERROR = 'PROVIDER_ERROR';

/**
 * নেটওয়ার্ক এরর ক্যাটাগরি
 * @description নেটওয়ার্ক সংক্রান্ত ত্রুটি
 */
export const NOTIFICATION_ERROR_CATEGORY_NETWORK_ERROR = 'NETWORK_ERROR';

/**
 * টাইমআউট ক্যাটাগরি
 * @description টাইমআউট ত্রুটি
 */
export const NOTIFICATION_ERROR_CATEGORY_TIMEOUT = 'TIMEOUT';

/**
 * বিজনেস লজিক ক্যাটাগরি
 * @description ব্যবসায়িক লজিক ত্রুটি
 */
export const NOTIFICATION_ERROR_CATEGORY_BUSINESS_LOGIC = 'BUSINESS_LOGIC';

/**
 * ডেটা এরর ক্যাটাগরি
 * @description ডেটা সংক্রান্ত ত্রুটি
 */
export const NOTIFICATION_ERROR_CATEGORY_DATA_ERROR = 'DATA_ERROR';

/**
 * কনফিগ এরর ক্যাটাগরি
 * @description কনফিগারেশন ত্রুটি
 */
export const NOTIFICATION_ERROR_CATEGORY_CONFIG_ERROR = 'CONFIG_ERROR';

// ============================================
// ২. এরর কোড
// ============================================

/**
 * এরর কোড টাইপ
 */
export type NotificationErrorCode =
  // Validation Errors (1000-1999)
  | typeof NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_INPUT
  | typeof NOTIFICATION_ERROR_CODE_VALIDATION_MISSING_FIELD
  | typeof NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_FORMAT
  | typeof NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_LENGTH
  | typeof NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_TYPE
  // Authentication Errors (2000-2999)
  | typeof NOTIFICATION_ERROR_CODE_AUTH_INVALID_TOKEN
  | typeof NOTIFICATION_ERROR_CODE_AUTH_EXPIRED_TOKEN
  | typeof NOTIFICATION_ERROR_CODE_AUTH_INVALID_CREDENTIALS
  | typeof NOTIFICATION_ERROR_CODE_AUTH_UNAUTHORIZED
  // Authorization Errors (3000-3999)
  | typeof NOTIFICATION_ERROR_CODE_AUTHZ_FORBIDDEN
  | typeof NOTIFICATION_ERROR_CODE_AUTHZ_INSUFFICIENT_PERMISSIONS
  | typeof NOTIFICATION_ERROR_CODE_AUTHZ_INVALID_ROLE
  // Not Found Errors (4000-4999)
  | typeof NOTIFICATION_ERROR_CODE_NOT_FOUND_USER
  | typeof NOTIFICATION_ERROR_CODE_NOT_FOUND_DEVICE
  | typeof NOTIFICATION_ERROR_CODE_NOT_FOUND_TEMPLATE
  | typeof NOTIFICATION_ERROR_CODE_NOT_FOUND_NOTIFICATION
  | typeof NOTIFICATION_ERROR_CODE_NOT_FOUND_PREFERENCE
  | typeof NOTIFICATION_ERROR_CODE_NOT_FOUND_RULE
  // Rate Limit Errors (5000-5999)
  | typeof NOTIFICATION_ERROR_CODE_RATE_LIMIT_EXCEEDED
  | typeof NOTIFICATION_ERROR_CODE_RATE_LIMIT_USER_EXCEEDED
  | typeof NOTIFICATION_ERROR_CODE_RATE_LIMIT_IP_EXCEEDED
  // Internal Errors (6000-6999)
  | typeof NOTIFICATION_ERROR_CODE_INTERNAL_SERVER_ERROR
  | typeof NOTIFICATION_ERROR_CODE_INTERNAL_DATABASE_ERROR
  | typeof NOTIFICATION_ERROR_CODE_INTERNAL_CACHE_ERROR
  | typeof NOTIFICATION_ERROR_CODE_INTERNAL_QUEUE_ERROR
  // Provider Errors (7000-7999)
  | typeof NOTIFICATION_ERROR_CODE_PROVIDER_UNAVAILABLE
  | typeof NOTIFICATION_ERROR_CODE_PROVIDER_AUTH_FAILED
  | typeof NOTIFICATION_ERROR_CODE_PROVIDER_INVALID_RESPONSE
  | typeof NOTIFICATION_ERROR_CODE_PROVIDER_RATE_LIMIT
  | typeof NOTIFICATION_ERROR_CODE_PROVIDER_TIMEOUT
  // Network Errors (8000-8999)
  | typeof NOTIFICATION_ERROR_CODE_NETWORK_CONNECTION_FAILED
  | typeof NOTIFICATION_ERROR_CODE_NETWORK_DNS_FAILED
  | typeof NOTIFICATION_ERROR_CODE_NETWORK_SSL_FAILED
  // Timeout Errors (9000-9999)
  | typeof NOTIFICATION_ERROR_CODE_TIMEOUT_REQUEST
  | typeof NOTIFICATION_ERROR_CODE_TIMEOUT_CONNECTION
  | typeof NOTIFICATION_ERROR_CODE_TIMEOUT_READ
  // Business Logic Errors (10000-10999)
  | typeof NOTIFICATION_ERROR_CODE_BUSINESS_DUPLICATE
  | typeof NOTIFICATION_ERROR_CODE_BUSINESS_INVALID_STATE
  | typeof NOTIFICATION_ERROR_CODE_BUSINESS_INVALID_OPERATION
  // Data Errors (11000-11999)
  | typeof NOTIFICATION_ERROR_CODE_DATA_INTEGRITY_VIOLATION
  | typeof NOTIFICATION_ERROR_CODE_DATA_CONCURRENT_MODIFICATION
  | typeof NOTIFICATION_ERROR_CODE_DATA_INCONSISTENT
  // Config Errors (12000-12999)
  | typeof NOTIFICATION_ERROR_CODE_CONFIG_MISSING
  | typeof NOTIFICATION_ERROR_CODE_CONFIG_INVALID
  | typeof NOTIFICATION_ERROR_CODE_CONFIG_UNSUPPORTED;

// Validation Errors
export const NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_INPUT = 'VAL_1001';
export const NOTIFICATION_ERROR_CODE_VALIDATION_MISSING_FIELD = 'VAL_1002';
export const NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_FORMAT = 'VAL_1003';
export const NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_LENGTH = 'VAL_1004';
export const NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_TYPE = 'VAL_1005';

// Authentication Errors
export const NOTIFICATION_ERROR_CODE_AUTH_INVALID_TOKEN = 'AUTH_2001';
export const NOTIFICATION_ERROR_CODE_AUTH_EXPIRED_TOKEN = 'AUTH_2002';
export const NOTIFICATION_ERROR_CODE_AUTH_INVALID_CREDENTIALS = 'AUTH_2003';
export const NOTIFICATION_ERROR_CODE_AUTH_UNAUTHORIZED = 'AUTH_2004';

// Authorization Errors
export const NOTIFICATION_ERROR_CODE_AUTHZ_FORBIDDEN = 'AUTHZ_3001';
export const NOTIFICATION_ERROR_CODE_AUTHZ_INSUFFICIENT_PERMISSIONS = 'AUTHZ_3002';
export const NOTIFICATION_ERROR_CODE_AUTHZ_INVALID_ROLE = 'AUTHZ_3003';

// Not Found Errors
export const NOTIFICATION_ERROR_CODE_NOT_FOUND_USER = 'NF_4001';
export const NOTIFICATION_ERROR_CODE_NOT_FOUND_DEVICE = 'NF_4002';
export const NOTIFICATION_ERROR_CODE_NOT_FOUND_TEMPLATE = 'NF_4003';
export const NOTIFICATION_ERROR_CODE_NOT_FOUND_NOTIFICATION = 'NF_4004';
export const NOTIFICATION_ERROR_CODE_NOT_FOUND_PREFERENCE = 'NF_4005';
export const NOTIFICATION_ERROR_CODE_NOT_FOUND_RULE = 'NF_4006';

// Rate Limit Errors
export const NOTIFICATION_ERROR_CODE_RATE_LIMIT_EXCEEDED = 'RL_5001';
export const NOTIFICATION_ERROR_CODE_RATE_LIMIT_USER_EXCEEDED = 'RL_5002';
export const NOTIFICATION_ERROR_CODE_RATE_LIMIT_IP_EXCEEDED = 'RL_5003';

// Internal Errors
export const NOTIFICATION_ERROR_CODE_INTERNAL_SERVER_ERROR = 'INT_6001';
export const NOTIFICATION_ERROR_CODE_INTERNAL_DATABASE_ERROR = 'INT_6002';
export const NOTIFICATION_ERROR_CODE_INTERNAL_CACHE_ERROR = 'INT_6003';
export const NOTIFICATION_ERROR_CODE_INTERNAL_QUEUE_ERROR = 'INT_6004';

// Provider Errors
export const NOTIFICATION_ERROR_CODE_PROVIDER_UNAVAILABLE = 'PROV_7001';
export const NOTIFICATION_ERROR_CODE_PROVIDER_AUTH_FAILED = 'PROV_7002';
export const NOTIFICATION_ERROR_CODE_PROVIDER_INVALID_RESPONSE = 'PROV_7003';
export const NOTIFICATION_ERROR_CODE_PROVIDER_RATE_LIMIT = 'PROV_7004';
export const NOTIFICATION_ERROR_CODE_PROVIDER_TIMEOUT = 'PROV_7005';

// Network Errors
export const NOTIFICATION_ERROR_CODE_NETWORK_CONNECTION_FAILED = 'NET_8001';
export const NOTIFICATION_ERROR_CODE_NETWORK_DNS_FAILED = 'NET_8002';
export const NOTIFICATION_ERROR_CODE_NETWORK_SSL_FAILED = 'NET_8003';

// Timeout Errors
export const NOTIFICATION_ERROR_CODE_TIMEOUT_REQUEST = 'TO_9001';
export const NOTIFICATION_ERROR_CODE_TIMEOUT_CONNECTION = 'TO_9002';
export const NOTIFICATION_ERROR_CODE_TIMEOUT_READ = 'TO_9003';

// Business Logic Errors
export const NOTIFICATION_ERROR_CODE_BUSINESS_DUPLICATE = 'BIZ_10001';
export const NOTIFICATION_ERROR_CODE_BUSINESS_INVALID_STATE = 'BIZ_10002';
export const NOTIFICATION_ERROR_CODE_BUSINESS_INVALID_OPERATION = 'BIZ_10003';

// Data Errors
export const NOTIFICATION_ERROR_CODE_DATA_INTEGRITY_VIOLATION = 'DATA_11001';
export const NOTIFICATION_ERROR_CODE_DATA_CONCURRENT_MODIFICATION = 'DATA_11002';
export const NOTIFICATION_ERROR_CODE_DATA_INCONSISTENT = 'DATA_11003';

// Config Errors
export const NOTIFICATION_ERROR_CODE_CONFIG_MISSING = 'CONFIG_12001';
export const NOTIFICATION_ERROR_CODE_CONFIG_INVALID = 'CONFIG_12002';
export const NOTIFICATION_ERROR_CODE_CONFIG_UNSUPPORTED = 'CONFIG_12003';

// ============================================
// ৩. এরর মেসেজ
// ============================================

/**
 * এরর মেসেজ
 */
export const NOTIFICATION_ERROR_MESSAGES: Record<NotificationErrorCode, string> = {
  // Validation Errors
  [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_INPUT]: 'Invalid input provided',
  [NOTIFICATION_ERROR_CODE_VALIDATION_MISSING_FIELD]: 'Required field is missing',
  [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_FORMAT]: 'Invalid format',
  [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_LENGTH]: 'Invalid length',
  [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_TYPE]: 'Invalid type',

  // Authentication Errors
  [NOTIFICATION_ERROR_CODE_AUTH_INVALID_TOKEN]: 'Invalid token',
  [NOTIFICATION_ERROR_CODE_AUTH_EXPIRED_TOKEN]: 'Token has expired',
  [NOTIFICATION_ERROR_CODE_AUTH_INVALID_CREDENTIALS]: 'Invalid credentials',
  [NOTIFICATION_ERROR_CODE_AUTH_UNAUTHORIZED]: 'Unauthorized',

  // Authorization Errors
  [NOTIFICATION_ERROR_CODE_AUTHZ_FORBIDDEN]: 'Forbidden',
  [NOTIFICATION_ERROR_CODE_AUTHZ_INSUFFICIENT_PERMISSIONS]: 'Insufficient permissions',
  [NOTIFICATION_ERROR_CODE_AUTHZ_INVALID_ROLE]: 'Invalid role',

  // Not Found Errors
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_USER]: 'User not found',
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_DEVICE]: 'Device not found',
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_TEMPLATE]: 'Template not found',
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_NOTIFICATION]: 'Notification not found',
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_PREFERENCE]: 'Preference not found',
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_RULE]: 'Rule not found',

  // Rate Limit Errors
  [NOTIFICATION_ERROR_CODE_RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded',
  [NOTIFICATION_ERROR_CODE_RATE_LIMIT_USER_EXCEEDED]: 'User rate limit exceeded',
  [NOTIFICATION_ERROR_CODE_RATE_LIMIT_IP_EXCEEDED]: 'IP rate limit exceeded',

  // Internal Errors
  [NOTIFICATION_ERROR_CODE_INTERNAL_SERVER_ERROR]: 'Internal server error',
  [NOTIFICATION_ERROR_CODE_INTERNAL_DATABASE_ERROR]: 'Database error',
  [NOTIFICATION_ERROR_CODE_INTERNAL_CACHE_ERROR]: 'Cache error',
  [NOTIFICATION_ERROR_CODE_INTERNAL_QUEUE_ERROR]: 'Queue error',

  // Provider Errors
  [NOTIFICATION_ERROR_CODE_PROVIDER_UNAVAILABLE]: 'Provider unavailable',
  [NOTIFICATION_ERROR_CODE_PROVIDER_AUTH_FAILED]: 'Provider authentication failed',
  [NOTIFICATION_ERROR_CODE_PROVIDER_INVALID_RESPONSE]: 'Provider invalid response',
  [NOTIFICATION_ERROR_CODE_PROVIDER_RATE_LIMIT]: 'Provider rate limit exceeded',
  [NOTIFICATION_ERROR_CODE_PROVIDER_TIMEOUT]: 'Provider timeout',

  // Network Errors
  [NOTIFICATION_ERROR_CODE_NETWORK_CONNECTION_FAILED]: 'Network connection failed',
  [NOTIFICATION_ERROR_CODE_NETWORK_DNS_FAILED]: 'DNS resolution failed',
  [NOTIFICATION_ERROR_CODE_NETWORK_SSL_FAILED]: 'SSL handshake failed',

  // Timeout Errors
  [NOTIFICATION_ERROR_CODE_TIMEOUT_REQUEST]: 'Request timeout',
  [NOTIFICATION_ERROR_CODE_TIMEOUT_CONNECTION]: 'Connection timeout',
  [NOTIFICATION_ERROR_CODE_TIMEOUT_READ]: 'Read timeout',

  // Business Logic Errors
  [NOTIFICATION_ERROR_CODE_BUSINESS_DUPLICATE]: 'Duplicate entry',
  [NOTIFICATION_ERROR_CODE_BUSINESS_INVALID_STATE]: 'Invalid state',
  [NOTIFICATION_ERROR_CODE_BUSINESS_INVALID_OPERATION]: 'Invalid operation',

  // Data Errors
  [NOTIFICATION_ERROR_CODE_DATA_INTEGRITY_VIOLATION]: 'Data integrity violation',
  [NOTIFICATION_ERROR_CODE_DATA_CONCURRENT_MODIFICATION]: 'Concurrent modification',
  [NOTIFICATION_ERROR_CODE_DATA_INCONSISTENT]: 'Inconsistent data',

  // Config Errors
  [NOTIFICATION_ERROR_CODE_CONFIG_MISSING]: 'Configuration missing',
  [NOTIFICATION_ERROR_CODE_CONFIG_INVALID]: 'Invalid configuration',
  [NOTIFICATION_ERROR_CODE_CONFIG_UNSUPPORTED]: 'Unsupported configuration',
};

// ============================================
// ৪. HTTP স্ট্যাটাস ম্যাপিং
// ============================================

/**
 * HTTP স্ট্যাটাস কোড
 */
export const NOTIFICATION_ERROR_HTTP_STATUS: Record<NotificationErrorCode, number> = {
  // Validation Errors
  [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_INPUT]: 400,
  [NOTIFICATION_ERROR_CODE_VALIDATION_MISSING_FIELD]: 400,
  [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_FORMAT]: 400,
  [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_LENGTH]: 400,
  [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_TYPE]: 400,

  // Authentication Errors
  [NOTIFICATION_ERROR_CODE_AUTH_INVALID_TOKEN]: 401,
  [NOTIFICATION_ERROR_CODE_AUTH_EXPIRED_TOKEN]: 401,
  [NOTIFICATION_ERROR_CODE_AUTH_INVALID_CREDENTIALS]: 401,
  [NOTIFICATION_ERROR_CODE_AUTH_UNAUTHORIZED]: 401,

  // Authorization Errors
  [NOTIFICATION_ERROR_CODE_AUTHZ_FORBIDDEN]: 403,
  [NOTIFICATION_ERROR_CODE_AUTHZ_INSUFFICIENT_PERMISSIONS]: 403,
  [NOTIFICATION_ERROR_CODE_AUTHZ_INVALID_ROLE]: 403,

  // Not Found Errors
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_USER]: 404,
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_DEVICE]: 404,
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_TEMPLATE]: 404,
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_NOTIFICATION]: 404,
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_PREFERENCE]: 404,
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_RULE]: 404,

  // Rate Limit Errors
  [NOTIFICATION_ERROR_CODE_RATE_LIMIT_EXCEEDED]: 429,
  [NOTIFICATION_ERROR_CODE_RATE_LIMIT_USER_EXCEEDED]: 429,
  [NOTIFICATION_ERROR_CODE_RATE_LIMIT_IP_EXCEEDED]: 429,

  // Internal Errors
  [NOTIFICATION_ERROR_CODE_INTERNAL_SERVER_ERROR]: 500,
  [NOTIFICATION_ERROR_CODE_INTERNAL_DATABASE_ERROR]: 500,
  [NOTIFICATION_ERROR_CODE_INTERNAL_CACHE_ERROR]: 500,
  [NOTIFICATION_ERROR_CODE_INTERNAL_QUEUE_ERROR]: 500,

  // Provider Errors
  [NOTIFICATION_ERROR_CODE_PROVIDER_UNAVAILABLE]: 503,
  [NOTIFICATION_ERROR_CODE_PROVIDER_AUTH_FAILED]: 401,
  [NOTIFICATION_ERROR_CODE_PROVIDER_INVALID_RESPONSE]: 500,
  [NOTIFICATION_ERROR_CODE_PROVIDER_RATE_LIMIT]: 429,
  [NOTIFICATION_ERROR_CODE_PROVIDER_TIMEOUT]: 504,

  // Network Errors
  [NOTIFICATION_ERROR_CODE_NETWORK_CONNECTION_FAILED]: 503,
  [NOTIFICATION_ERROR_CODE_NETWORK_DNS_FAILED]: 503,
  [NOTIFICATION_ERROR_CODE_NETWORK_SSL_FAILED]: 500,

  // Timeout Errors
  [NOTIFICATION_ERROR_CODE_TIMEOUT_REQUEST]: 408,
  [NOTIFICATION_ERROR_CODE_TIMEOUT_CONNECTION]: 408,
  [NOTIFICATION_ERROR_CODE_TIMEOUT_READ]: 408,

  // Business Logic Errors
  [NOTIFICATION_ERROR_CODE_BUSINESS_DUPLICATE]: 409,
  [NOTIFICATION_ERROR_CODE_BUSINESS_INVALID_STATE]: 409,
  [NOTIFICATION_ERROR_CODE_BUSINESS_INVALID_OPERATION]: 400,

  // Data Errors
  [NOTIFICATION_ERROR_CODE_DATA_INTEGRITY_VIOLATION]: 409,
  [NOTIFICATION_ERROR_CODE_DATA_CONCURRENT_MODIFICATION]: 409,
  [NOTIFICATION_ERROR_CODE_DATA_INCONSISTENT]: 500,

  // Config Errors
  [NOTIFICATION_ERROR_CODE_CONFIG_MISSING]: 500,
  [NOTIFICATION_ERROR_CODE_CONFIG_INVALID]: 500,
  [NOTIFICATION_ERROR_CODE_CONFIG_UNSUPPORTED]: 400,
};

// ============================================
// ৫. এরর সিভারিটি
// ============================================

/**
 * এরর সিভারিটি লেভেল
 */
export type NotificationErrorSeverity =
  | typeof NOTIFICATION_ERROR_SEVERITY_LOW
  | typeof NOTIFICATION_ERROR_SEVERITY_MEDIUM
  | typeof NOTIFICATION_ERROR_SEVERITY_HIGH
  | typeof NOTIFICATION_ERROR_SEVERITY_CRITICAL;

export const NOTIFICATION_ERROR_SEVERITY_LOW = 'LOW';
export const NOTIFICATION_ERROR_SEVERITY_MEDIUM = 'MEDIUM';
export const NOTIFICATION_ERROR_SEVERITY_HIGH = 'HIGH';
export const NOTIFICATION_ERROR_SEVERITY_CRITICAL = 'CRITICAL';

/**
 * এরর সিভারিটি ম্যাপিং
 */
export const NOTIFICATION_ERROR_SEVERITY: Record<NotificationErrorCode, NotificationErrorSeverity> =
  {
    // Validation Errors - Low
    [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_INPUT]: NOTIFICATION_ERROR_SEVERITY_LOW,
    [NOTIFICATION_ERROR_CODE_VALIDATION_MISSING_FIELD]: NOTIFICATION_ERROR_SEVERITY_LOW,
    [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_FORMAT]: NOTIFICATION_ERROR_SEVERITY_LOW,
    [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_LENGTH]: NOTIFICATION_ERROR_SEVERITY_LOW,
    [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_TYPE]: NOTIFICATION_ERROR_SEVERITY_LOW,

    // Authentication Errors - Medium
    [NOTIFICATION_ERROR_CODE_AUTH_INVALID_TOKEN]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,
    [NOTIFICATION_ERROR_CODE_AUTH_EXPIRED_TOKEN]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,
    [NOTIFICATION_ERROR_CODE_AUTH_INVALID_CREDENTIALS]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,
    [NOTIFICATION_ERROR_CODE_AUTH_UNAUTHORIZED]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,

    // Authorization Errors - Medium
    [NOTIFICATION_ERROR_CODE_AUTHZ_FORBIDDEN]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,
    [NOTIFICATION_ERROR_CODE_AUTHZ_INSUFFICIENT_PERMISSIONS]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,
    [NOTIFICATION_ERROR_CODE_AUTHZ_INVALID_ROLE]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,

    // Not Found Errors - Low
    [NOTIFICATION_ERROR_CODE_NOT_FOUND_USER]: NOTIFICATION_ERROR_SEVERITY_LOW,
    [NOTIFICATION_ERROR_CODE_NOT_FOUND_DEVICE]: NOTIFICATION_ERROR_SEVERITY_LOW,
    [NOTIFICATION_ERROR_CODE_NOT_FOUND_TEMPLATE]: NOTIFICATION_ERROR_SEVERITY_LOW,
    [NOTIFICATION_ERROR_CODE_NOT_FOUND_NOTIFICATION]: NOTIFICATION_ERROR_SEVERITY_LOW,
    [NOTIFICATION_ERROR_CODE_NOT_FOUND_PREFERENCE]: NOTIFICATION_ERROR_SEVERITY_LOW,
    [NOTIFICATION_ERROR_CODE_NOT_FOUND_RULE]: NOTIFICATION_ERROR_SEVERITY_LOW,

    // Rate Limit Errors - Medium
    [NOTIFICATION_ERROR_CODE_RATE_LIMIT_EXCEEDED]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,
    [NOTIFICATION_ERROR_CODE_RATE_LIMIT_USER_EXCEEDED]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,
    [NOTIFICATION_ERROR_CODE_RATE_LIMIT_IP_EXCEEDED]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,

    // Internal Errors - Critical
    [NOTIFICATION_ERROR_CODE_INTERNAL_SERVER_ERROR]: NOTIFICATION_ERROR_SEVERITY_CRITICAL,
    [NOTIFICATION_ERROR_CODE_INTERNAL_DATABASE_ERROR]: NOTIFICATION_ERROR_SEVERITY_CRITICAL,
    [NOTIFICATION_ERROR_CODE_INTERNAL_CACHE_ERROR]: NOTIFICATION_ERROR_SEVERITY_HIGH,
    [NOTIFICATION_ERROR_CODE_INTERNAL_QUEUE_ERROR]: NOTIFICATION_ERROR_SEVERITY_HIGH,

    // Provider Errors - High
    [NOTIFICATION_ERROR_CODE_PROVIDER_UNAVAILABLE]: NOTIFICATION_ERROR_SEVERITY_HIGH,
    [NOTIFICATION_ERROR_CODE_PROVIDER_AUTH_FAILED]: NOTIFICATION_ERROR_SEVERITY_HIGH,
    [NOTIFICATION_ERROR_CODE_PROVIDER_INVALID_RESPONSE]: NOTIFICATION_ERROR_SEVERITY_HIGH,
    [NOTIFICATION_ERROR_CODE_PROVIDER_RATE_LIMIT]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,
    [NOTIFICATION_ERROR_CODE_PROVIDER_TIMEOUT]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,

    // Network Errors - Medium
    [NOTIFICATION_ERROR_CODE_NETWORK_CONNECTION_FAILED]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,
    [NOTIFICATION_ERROR_CODE_NETWORK_DNS_FAILED]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,
    [NOTIFICATION_ERROR_CODE_NETWORK_SSL_FAILED]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,

    // Timeout Errors - Medium
    [NOTIFICATION_ERROR_CODE_TIMEOUT_REQUEST]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,
    [NOTIFICATION_ERROR_CODE_TIMEOUT_CONNECTION]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,
    [NOTIFICATION_ERROR_CODE_TIMEOUT_READ]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,

    // Business Logic Errors - Medium
    [NOTIFICATION_ERROR_CODE_BUSINESS_DUPLICATE]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,
    [NOTIFICATION_ERROR_CODE_BUSINESS_INVALID_STATE]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,
    [NOTIFICATION_ERROR_CODE_BUSINESS_INVALID_OPERATION]: NOTIFICATION_ERROR_SEVERITY_MEDIUM,

    // Data Errors - High
    [NOTIFICATION_ERROR_CODE_DATA_INTEGRITY_VIOLATION]: NOTIFICATION_ERROR_SEVERITY_HIGH,
    [NOTIFICATION_ERROR_CODE_DATA_CONCURRENT_MODIFICATION]: NOTIFICATION_ERROR_SEVERITY_HIGH,
    [NOTIFICATION_ERROR_CODE_DATA_INCONSISTENT]: NOTIFICATION_ERROR_SEVERITY_HIGH,

    // Config Errors - Critical
    [NOTIFICATION_ERROR_CODE_CONFIG_MISSING]: NOTIFICATION_ERROR_SEVERITY_CRITICAL,
    [NOTIFICATION_ERROR_CODE_CONFIG_INVALID]: NOTIFICATION_ERROR_SEVERITY_CRITICAL,
    [NOTIFICATION_ERROR_CODE_CONFIG_UNSUPPORTED]: NOTIFICATION_ERROR_SEVERITY_HIGH,
  };

// ============================================
// ৬. এরর টু ক্যাটাগরি ম্যাপিং
// ============================================

/**
 * এরর কোড থেকে ক্যাটাগরি ম্যাপিং
 */
export const NOTIFICATION_ERROR_CODE_TO_CATEGORY: Record<
  NotificationErrorCode,
  NotificationErrorCategory
> = {
  // Validation Errors
  [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_INPUT]: NOTIFICATION_ERROR_CATEGORY_VALIDATION,
  [NOTIFICATION_ERROR_CODE_VALIDATION_MISSING_FIELD]: NOTIFICATION_ERROR_CATEGORY_VALIDATION,
  [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_FORMAT]: NOTIFICATION_ERROR_CATEGORY_VALIDATION,
  [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_LENGTH]: NOTIFICATION_ERROR_CATEGORY_VALIDATION,
  [NOTIFICATION_ERROR_CODE_VALIDATION_INVALID_TYPE]: NOTIFICATION_ERROR_CATEGORY_VALIDATION,

  // Authentication Errors
  [NOTIFICATION_ERROR_CODE_AUTH_INVALID_TOKEN]: NOTIFICATION_ERROR_CATEGORY_AUTHENTICATION,
  [NOTIFICATION_ERROR_CODE_AUTH_EXPIRED_TOKEN]: NOTIFICATION_ERROR_CATEGORY_AUTHENTICATION,
  [NOTIFICATION_ERROR_CODE_AUTH_INVALID_CREDENTIALS]: NOTIFICATION_ERROR_CATEGORY_AUTHENTICATION,
  [NOTIFICATION_ERROR_CODE_AUTH_UNAUTHORIZED]: NOTIFICATION_ERROR_CATEGORY_AUTHENTICATION,

  // Authorization Errors
  [NOTIFICATION_ERROR_CODE_AUTHZ_FORBIDDEN]: NOTIFICATION_ERROR_CATEGORY_AUTHORIZATION,
  [NOTIFICATION_ERROR_CODE_AUTHZ_INSUFFICIENT_PERMISSIONS]:
    NOTIFICATION_ERROR_CATEGORY_AUTHORIZATION,
  [NOTIFICATION_ERROR_CODE_AUTHZ_INVALID_ROLE]: NOTIFICATION_ERROR_CATEGORY_AUTHORIZATION,

  // Not Found Errors
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_USER]: NOTIFICATION_ERROR_CATEGORY_NOT_FOUND,
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_DEVICE]: NOTIFICATION_ERROR_CATEGORY_NOT_FOUND,
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_TEMPLATE]: NOTIFICATION_ERROR_CATEGORY_NOT_FOUND,
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_NOTIFICATION]: NOTIFICATION_ERROR_CATEGORY_NOT_FOUND,
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_PREFERENCE]: NOTIFICATION_ERROR_CATEGORY_NOT_FOUND,
  [NOTIFICATION_ERROR_CODE_NOT_FOUND_RULE]: NOTIFICATION_ERROR_CATEGORY_NOT_FOUND,

  // Rate Limit Errors
  [NOTIFICATION_ERROR_CODE_RATE_LIMIT_EXCEEDED]: NOTIFICATION_ERROR_CATEGORY_RATE_LIMIT,
  [NOTIFICATION_ERROR_CODE_RATE_LIMIT_USER_EXCEEDED]: NOTIFICATION_ERROR_CATEGORY_RATE_LIMIT,
  [NOTIFICATION_ERROR_CODE_RATE_LIMIT_IP_EXCEEDED]: NOTIFICATION_ERROR_CATEGORY_RATE_LIMIT,

  // Internal Errors
  [NOTIFICATION_ERROR_CODE_INTERNAL_SERVER_ERROR]: NOTIFICATION_ERROR_CATEGORY_INTERNAL_ERROR,
  [NOTIFICATION_ERROR_CODE_INTERNAL_DATABASE_ERROR]: NOTIFICATION_ERROR_CATEGORY_INTERNAL_ERROR,
  [NOTIFICATION_ERROR_CODE_INTERNAL_CACHE_ERROR]: NOTIFICATION_ERROR_CATEGORY_INTERNAL_ERROR,
  [NOTIFICATION_ERROR_CODE_INTERNAL_QUEUE_ERROR]: NOTIFICATION_ERROR_CATEGORY_INTERNAL_ERROR,

  // Provider Errors
  [NOTIFICATION_ERROR_CODE_PROVIDER_UNAVAILABLE]: NOTIFICATION_ERROR_CATEGORY_PROVIDER_ERROR,
  [NOTIFICATION_ERROR_CODE_PROVIDER_AUTH_FAILED]: NOTIFICATION_ERROR_CATEGORY_PROVIDER_ERROR,
  [NOTIFICATION_ERROR_CODE_PROVIDER_INVALID_RESPONSE]: NOTIFICATION_ERROR_CATEGORY_PROVIDER_ERROR,
  [NOTIFICATION_ERROR_CODE_PROVIDER_RATE_LIMIT]: NOTIFICATION_ERROR_CATEGORY_PROVIDER_ERROR,
  [NOTIFICATION_ERROR_CODE_PROVIDER_TIMEOUT]: NOTIFICATION_ERROR_CATEGORY_PROVIDER_ERROR,

  // Network Errors
  [NOTIFICATION_ERROR_CODE_NETWORK_CONNECTION_FAILED]: NOTIFICATION_ERROR_CATEGORY_NETWORK_ERROR,
  [NOTIFICATION_ERROR_CODE_NETWORK_DNS_FAILED]: NOTIFICATION_ERROR_CATEGORY_NETWORK_ERROR,
  [NOTIFICATION_ERROR_CODE_NETWORK_SSL_FAILED]: NOTIFICATION_ERROR_CATEGORY_NETWORK_ERROR,

  // Timeout Errors
  [NOTIFICATION_ERROR_CODE_TIMEOUT_REQUEST]: NOTIFICATION_ERROR_CATEGORY_TIMEOUT,
  [NOTIFICATION_ERROR_CODE_TIMEOUT_CONNECTION]: NOTIFICATION_ERROR_CATEGORY_TIMEOUT,
  [NOTIFICATION_ERROR_CODE_TIMEOUT_READ]: NOTIFICATION_ERROR_CATEGORY_TIMEOUT,

  // Business Logic Errors
  [NOTIFICATION_ERROR_CODE_BUSINESS_DUPLICATE]: NOTIFICATION_ERROR_CATEGORY_BUSINESS_LOGIC,
  [NOTIFICATION_ERROR_CODE_BUSINESS_INVALID_STATE]: NOTIFICATION_ERROR_CATEGORY_BUSINESS_LOGIC,
  [NOTIFICATION_ERROR_CODE_BUSINESS_INVALID_OPERATION]: NOTIFICATION_ERROR_CATEGORY_BUSINESS_LOGIC,

  // Data Errors
  [NOTIFICATION_ERROR_CODE_DATA_INTEGRITY_VIOLATION]: NOTIFICATION_ERROR_CATEGORY_DATA_ERROR,
  [NOTIFICATION_ERROR_CODE_DATA_CONCURRENT_MODIFICATION]: NOTIFICATION_ERROR_CATEGORY_DATA_ERROR,
  [NOTIFICATION_ERROR_CODE_DATA_INCONSISTENT]: NOTIFICATION_ERROR_CATEGORY_DATA_ERROR,

  // Config Errors
  [NOTIFICATION_ERROR_CODE_CONFIG_MISSING]: NOTIFICATION_ERROR_CATEGORY_CONFIG_ERROR,
  [NOTIFICATION_ERROR_CODE_CONFIG_INVALID]: NOTIFICATION_ERROR_CATEGORY_CONFIG_ERROR,
  [NOTIFICATION_ERROR_CODE_CONFIG_UNSUPPORTED]: NOTIFICATION_ERROR_CATEGORY_CONFIG_ERROR,
};

// ============================================
// ৭. রেট্রাই পলিসি
// ============================================

/**
 * রেট্রাই পলিসি কনফিগারেশন
 */
export interface RetryPolicy {
  /** সর্বোচ্চ রেট্রাই সংখ্যা */
  maxRetries: number;
  /** ডিফল্ট ডিলে (মিলিসেকেন্ডে) */
  defaultDelay: number;
  /** ব্যাকঅফ ফ্যাক্টর */
  backoffFactor: number;
  /** রেট্রাই করা যাবে কিনা */
  retryable: boolean;
}

/**
 * এরর কোড অনুযায়ী রেট্রাই পলিসি
 */
export const NOTIFICATION_ERROR_RETRY_POLICIES: Record<NotificationErrorCategory, RetryPolicy> = {
  [NOTIFICATION_ERROR_CATEGORY_VALIDATION]: {
    maxRetries: 0,
    defaultDelay: 0,
    backoffFactor: 1,
    retryable: false,
  },
  [NOTIFICATION_ERROR_CATEGORY_AUTHENTICATION]: {
    maxRetries: 1,
    defaultDelay: 1000,
    backoffFactor: 2,
    retryable: true,
  },
  [NOTIFICATION_ERROR_CATEGORY_AUTHORIZATION]: {
    maxRetries: 0,
    defaultDelay: 0,
    backoffFactor: 1,
    retryable: false,
  },
  [NOTIFICATION_ERROR_CATEGORY_NOT_FOUND]: {
    maxRetries: 0,
    defaultDelay: 0,
    backoffFactor: 1,
    retryable: false,
  },
  [NOTIFICATION_ERROR_CATEGORY_RATE_LIMIT]: {
    maxRetries: 3,
    defaultDelay: 60000,
    backoffFactor: 2,
    retryable: true,
  },
  [NOTIFICATION_ERROR_CATEGORY_INTERNAL_ERROR]: {
    maxRetries: 3,
    defaultDelay: 1000,
    backoffFactor: 2,
    retryable: true,
  },
  [NOTIFICATION_ERROR_CATEGORY_PROVIDER_ERROR]: {
    maxRetries: 3,
    defaultDelay: 5000,
    backoffFactor: 2,
    retryable: true,
  },
  [NOTIFICATION_ERROR_CATEGORY_NETWORK_ERROR]: {
    maxRetries: 3,
    defaultDelay: 1000,
    backoffFactor: 2,
    retryable: true,
  },
  [NOTIFICATION_ERROR_CATEGORY_TIMEOUT]: {
    maxRetries: 2,
    defaultDelay: 5000,
    backoffFactor: 2,
    retryable: true,
  },
  [NOTIFICATION_ERROR_CATEGORY_BUSINESS_LOGIC]: {
    maxRetries: 1,
    defaultDelay: 1000,
    backoffFactor: 2,
    retryable: false,
  },
  [NOTIFICATION_ERROR_CATEGORY_DATA_ERROR]: {
    maxRetries: 1,
    defaultDelay: 1000,
    backoffFactor: 2,
    retryable: false,
  },
  [NOTIFICATION_ERROR_CATEGORY_CONFIG_ERROR]: {
    maxRetries: 0,
    defaultDelay: 0,
    backoffFactor: 1,
    retryable: false,
  },
};

// ============================================
// ৮. ক্যাটাগরি লেবেল
// ============================================

/**
 * ক্যাটাগরি লেবেল
 */
export const NOTIFICATION_ERROR_CATEGORY_LABELS: Record<NotificationErrorCategory, string> = {
  [NOTIFICATION_ERROR_CATEGORY_VALIDATION]: 'ভ্যালিডেশন',
  [NOTIFICATION_ERROR_CATEGORY_AUTHENTICATION]: 'প্রমাণীকরণ',
  [NOTIFICATION_ERROR_CATEGORY_AUTHORIZATION]: 'অনুমোদন',
  [NOTIFICATION_ERROR_CATEGORY_NOT_FOUND]: 'পাওয়া যায়নি',
  [NOTIFICATION_ERROR_CATEGORY_RATE_LIMIT]: 'রেট লিমিট',
  [NOTIFICATION_ERROR_CATEGORY_INTERNAL_ERROR]: 'অভ্যন্তরীণ ত্রুটি',
  [NOTIFICATION_ERROR_CATEGORY_PROVIDER_ERROR]: 'প্রোভাইডার ত্রুটি',
  [NOTIFICATION_ERROR_CATEGORY_NETWORK_ERROR]: 'নেটওয়ার্ক ত্রুটি',
  [NOTIFICATION_ERROR_CATEGORY_TIMEOUT]: 'টাইমআউট',
  [NOTIFICATION_ERROR_CATEGORY_BUSINESS_LOGIC]: 'ব্যবসায়িক লজিক',
  [NOTIFICATION_ERROR_CATEGORY_DATA_ERROR]: 'ডেটা ত্রুটি',
  [NOTIFICATION_ERROR_CATEGORY_CONFIG_ERROR]: 'কনফিগারেশন ত্রুটি',
};
