/**
 * Notification Status Constants
 * Status definitions for notification lifecycle
 */

export const NOTIFICATION_STATUS = {
  // Notification Statuses
  STATUSES: {
    DRAFT: 'draft',
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected',
    SCHEDULED: 'scheduled',
    QUEUED: 'queued',
    PROCESSING: 'processing',
    SENT: 'sent',
    DELIVERED: 'delivered',
    FAILED: 'failed',
    BOUNCED: 'bounced',
    OPENED: 'opened',
    CLICKED: 'clicked',
    UNSUBSCRIBED: 'unsubscribed',
    SPAM: 'spam',
    COMPLAINED: 'complained',
    DEFERRED: 'deferred',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    PAUSED: 'paused',
    EXPIRED: 'expired',
    READ: 'read',
    UNREAD: 'unread',
    DELETED: 'deleted',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    DRAFT: '#6B7280',
    PENDING: '#F59E0B',
    APPROVED: '#10B981',
    REJECTED: '#EF4444',
    SCHEDULED: '#3B82F6',
    QUEUED: '#8B5CF6',
    PROCESSING: '#3B82F6',
    SENT: '#10B981',
    DELIVERED: '#10B981',
    FAILED: '#EF4444',
    BOUNCED: '#EF4444',
    OPENED: '#10B981',
    CLICKED: '#10B981',
    UNSUBSCRIBED: '#6B7280',
    SPAM: '#EF4444',
    COMPLAINED: '#EF4444',
    DEFERRED: '#F59E0B',
    CANCELLED: '#6B7280',
    ARCHIVED: '#6B7280',
    PAUSED: '#F59E0B',
    EXPIRED: '#6B7280',
    READ: '#10B981',
    UNREAD: '#3B82F6',
    DELETED: '#6B7280',
  } as const,

  // Status Categories
  CATEGORIES: {
    DRAFT: 'draft',
    PENDING: 'pending',
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    ENGAGED: 'engaged',
  } as const,

  // Status Priority Order
  ORDER: {
    DRAFT: 0,
    PENDING: 1,
    APPROVED: 2,
    REJECTED: 3,
    SCHEDULED: 4,
    QUEUED: 5,
    PROCESSING: 6,
    SENT: 7,
    DELIVERED: 8,
    OPENED: 9,
    CLICKED: 10,
    UNSUBSCRIBED: 11,
    SPAM: 12,
    COMPLAINED: 13,
    BOUNCED: 14,
    DEFERRED: 15,
    FAILED: 16,
    PAUSED: 17,
    EXPIRED: 18,
    CANCELLED: 19,
    ARCHIVED: 20,
    READ: 21,
    UNREAD: 22,
    DELETED: 23,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    DRAFT_TO_PENDING: 'draft_to_pending',
    DRAFT_TO_CANCELLED: 'draft_to_cancelled',
    DRAFT_TO_ARCHIVED: 'draft_to_archived',
    PENDING_TO_APPROVED: 'pending_to_approved',
    PENDING_TO_REJECTED: 'pending_to_rejected',
    PENDING_TO_CANCELLED: 'pending_to_cancelled',
    APPROVED_TO_SCHEDULED: 'approved_to_scheduled',
    APPROVED_TO_REJECTED: 'approved_to_rejected',
    APPROVED_TO_CANCELLED: 'approved_to_cancelled',
    REJECTED_TO_DRAFT: 'rejected_to_draft',
    REJECTED_TO_ARCHIVED: 'rejected_to_archived',
    SCHEDULED_TO_QUEUED: 'scheduled_to_queued',
    SCHEDULED_TO_CANCELLED: 'scheduled_to_cancelled',
    QUEUED_TO_PROCESSING: 'queued_to_processing',
    QUEUED_TO_CANCELLED: 'queued_to_cancelled',
    PROCESSING_TO_SENT: 'processing_to_sent',
    PROCESSING_TO_FAILED: 'processing_to_failed',
    PROCESSING_TO_CANCELLED: 'processing_to_cancelled',
    SENT_TO_DELIVERED: 'sent_to_delivered',
    SENT_TO_BOUNCED: 'sent_to_bounced',
    SENT_TO_FAILED: 'sent_to_failed',
    SENT_TO_DEFERRED: 'sent_to_deferred',
    DELIVERED_TO_OPENED: 'delivered_to_opened',
    DELIVERED_TO_UNSUBSCRIBED: 'delivered_to_unsubscribed',
    DELIVERED_TO_SPAM: 'delivered_to_spam',
    DELIVERED_TO_COMPLAINED: 'delivered_to_complained',
    OPENED_TO_CLICKED: 'opened_to_clicked',
    OPENED_TO_UNSUBSCRIBED: 'opened_to_unsubscribed',
    CLICKED_TO_UNSUBSCRIBED: 'clicked_to_unsubscribed',
    CLICKED_TO_COMPLAINED: 'clicked_to_complained',
    BOUNCED_TO_ARCHIVED: 'bounced_to_archived',
    FAILED_TO_ARCHIVED: 'failed_to_archived',
    DEFERRED_TO_SENT: 'deferred_to_sent',
    DEFERRED_TO_FAILED: 'deferred_to_failed',
    DEFERRED_TO_CANCELLED: 'deferred_to_cancelled',
    UNSUBSCRIBED_TO_ARCHIVED: 'unsubscribed_to_archived',
    SPAM_TO_ARCHIVED: 'spam_to_archived',
    COMPLAINED_TO_ARCHIVED: 'complained_to_archived',
    PAUSED_TO_PROCESSING: 'paused_to_processing',
    PAUSED_TO_CANCELLED: 'paused_to_cancelled',
    EXPIRED_TO_ARCHIVED: 'expired_to_archived',
    READ_TO_UNREAD: 'read_to_unread',
    READ_TO_ARCHIVED: 'read_to_archived',
    READ_TO_DELETED: 'read_to_deleted',
    UNREAD_TO_READ: 'unread_to_read',
    UNREAD_TO_ARCHIVED: 'unread_to_archived',
    UNREAD_TO_DELETED: 'unread_to_deleted',
    DELETED_TO_ARCHIVED: 'deleted_to_archived',
  } as const,
} as const;

// Notification Statuses
export type NotificationStatusType =
  (typeof NOTIFICATION_STATUS.STATUSES)[keyof typeof NOTIFICATION_STATUS.STATUSES];

// Status Colors
export type NotificationStatusColor =
  (typeof NOTIFICATION_STATUS.COLORS)[keyof typeof NOTIFICATION_STATUS.COLORS];

// Status Categories
export type NotificationStatusCategory =
  (typeof NOTIFICATION_STATUS.CATEGORIES)[keyof typeof NOTIFICATION_STATUS.CATEGORIES];

// Status Priority Order
export type NotificationStatusOrder =
  (typeof NOTIFICATION_STATUS.ORDER)[keyof typeof NOTIFICATION_STATUS.ORDER];

// Status Transitions
export type NotificationStatusTransition =
  (typeof NOTIFICATION_STATUS.TRANSITIONS)[keyof typeof NOTIFICATION_STATUS.TRANSITIONS];

// Utility Functions
export function notificationGetStatusLabel(status: NotificationStatusType): string {
  const labels: Record<NotificationStatusType, string> = {
    [NOTIFICATION_STATUS.STATUSES.DRAFT]: 'Draft',
    [NOTIFICATION_STATUS.STATUSES.PENDING]: 'Pending',
    [NOTIFICATION_STATUS.STATUSES.APPROVED]: 'Approved',
    [NOTIFICATION_STATUS.STATUSES.REJECTED]: 'Rejected',
    [NOTIFICATION_STATUS.STATUSES.SCHEDULED]: 'Scheduled',
    [NOTIFICATION_STATUS.STATUSES.QUEUED]: 'Queued',
    [NOTIFICATION_STATUS.STATUSES.PROCESSING]: 'Processing',
    [NOTIFICATION_STATUS.STATUSES.SENT]: 'Sent',
    [NOTIFICATION_STATUS.STATUSES.DELIVERED]: 'Delivered',
    [NOTIFICATION_STATUS.STATUSES.FAILED]: 'Failed',
    [NOTIFICATION_STATUS.STATUSES.BOUNCED]: 'Bounced',
    [NOTIFICATION_STATUS.STATUSES.OPENED]: 'Opened',
    [NOTIFICATION_STATUS.STATUSES.CLICKED]: 'Clicked',
    [NOTIFICATION_STATUS.STATUSES.UNSUBSCRIBED]: 'Unsubscribed',
    [NOTIFICATION_STATUS.STATUSES.SPAM]: 'Spam',
    [NOTIFICATION_STATUS.STATUSES.COMPLAINED]: 'Complained',
    [NOTIFICATION_STATUS.STATUSES.DEFERRED]: 'Deferred',
    [NOTIFICATION_STATUS.STATUSES.CANCELLED]: 'Cancelled',
    [NOTIFICATION_STATUS.STATUSES.ARCHIVED]: 'Archived',
    [NOTIFICATION_STATUS.STATUSES.PAUSED]: 'Paused',
    [NOTIFICATION_STATUS.STATUSES.EXPIRED]: 'Expired',
    [NOTIFICATION_STATUS.STATUSES.READ]: 'Read',
    [NOTIFICATION_STATUS.STATUSES.UNREAD]: 'Unread',
    [NOTIFICATION_STATUS.STATUSES.DELETED]: 'Deleted',
  };
  return labels[status] || 'Unknown Status';
}

export function notificationGetStatusColor(
  status: NotificationStatusType
): NotificationStatusColor {
  const colors: Record<NotificationStatusType, NotificationStatusColor> = {
    [NOTIFICATION_STATUS.STATUSES.DRAFT]: NOTIFICATION_STATUS.COLORS.DRAFT,
    [NOTIFICATION_STATUS.STATUSES.PENDING]: NOTIFICATION_STATUS.COLORS.PENDING,
    [NOTIFICATION_STATUS.STATUSES.APPROVED]: NOTIFICATION_STATUS.COLORS.APPROVED,
    [NOTIFICATION_STATUS.STATUSES.REJECTED]: NOTIFICATION_STATUS.COLORS.REJECTED,
    [NOTIFICATION_STATUS.STATUSES.SCHEDULED]: NOTIFICATION_STATUS.COLORS.SCHEDULED,
    [NOTIFICATION_STATUS.STATUSES.QUEUED]: NOTIFICATION_STATUS.COLORS.QUEUED,
    [NOTIFICATION_STATUS.STATUSES.PROCESSING]: NOTIFICATION_STATUS.COLORS.PROCESSING,
    [NOTIFICATION_STATUS.STATUSES.SENT]: NOTIFICATION_STATUS.COLORS.SENT,
    [NOTIFICATION_STATUS.STATUSES.DELIVERED]: NOTIFICATION_STATUS.COLORS.DELIVERED,
    [NOTIFICATION_STATUS.STATUSES.FAILED]: NOTIFICATION_STATUS.COLORS.FAILED,
    [NOTIFICATION_STATUS.STATUSES.BOUNCED]: NOTIFICATION_STATUS.COLORS.BOUNCED,
    [NOTIFICATION_STATUS.STATUSES.OPENED]: NOTIFICATION_STATUS.COLORS.OPENED,
    [NOTIFICATION_STATUS.STATUSES.CLICKED]: NOTIFICATION_STATUS.COLORS.CLICKED,
    [NOTIFICATION_STATUS.STATUSES.UNSUBSCRIBED]: NOTIFICATION_STATUS.COLORS.UNSUBSCRIBED,
    [NOTIFICATION_STATUS.STATUSES.SPAM]: NOTIFICATION_STATUS.COLORS.SPAM,
    [NOTIFICATION_STATUS.STATUSES.COMPLAINED]: NOTIFICATION_STATUS.COLORS.COMPLAINED,
    [NOTIFICATION_STATUS.STATUSES.DEFERRED]: NOTIFICATION_STATUS.COLORS.DEFERRED,
    [NOTIFICATION_STATUS.STATUSES.CANCELLED]: NOTIFICATION_STATUS.COLORS.CANCELLED,
    [NOTIFICATION_STATUS.STATUSES.ARCHIVED]: NOTIFICATION_STATUS.COLORS.ARCHIVED,
    [NOTIFICATION_STATUS.STATUSES.PAUSED]: NOTIFICATION_STATUS.COLORS.PAUSED,
    [NOTIFICATION_STATUS.STATUSES.EXPIRED]: NOTIFICATION_STATUS.COLORS.EXPIRED,
    [NOTIFICATION_STATUS.STATUSES.READ]: NOTIFICATION_STATUS.COLORS.READ,
    [NOTIFICATION_STATUS.STATUSES.UNREAD]: NOTIFICATION_STATUS.COLORS.UNREAD,
    [NOTIFICATION_STATUS.STATUSES.DELETED]: NOTIFICATION_STATUS.COLORS.DELETED,
  };
  return colors[status] || NOTIFICATION_STATUS.COLORS.DRAFT;
}

export function notificationGetStatusCategory(
  status: NotificationStatusType
): NotificationStatusCategory {
  const categories: Record<NotificationStatusType, NotificationStatusCategory> = {
    [NOTIFICATION_STATUS.STATUSES.DRAFT]: NOTIFICATION_STATUS.CATEGORIES.DRAFT,
    [NOTIFICATION_STATUS.STATUSES.PENDING]: NOTIFICATION_STATUS.CATEGORIES.PENDING,
    [NOTIFICATION_STATUS.STATUSES.APPROVED]: NOTIFICATION_STATUS.CATEGORIES.PENDING,
    [NOTIFICATION_STATUS.STATUSES.REJECTED]: NOTIFICATION_STATUS.CATEGORIES.FAILED,
    [NOTIFICATION_STATUS.STATUSES.SCHEDULED]: NOTIFICATION_STATUS.CATEGORIES.PENDING,
    [NOTIFICATION_STATUS.STATUSES.QUEUED]: NOTIFICATION_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATION_STATUS.STATUSES.PROCESSING]: NOTIFICATION_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATION_STATUS.STATUSES.SENT]: NOTIFICATION_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATION_STATUS.STATUSES.DELIVERED]: NOTIFICATION_STATUS.CATEGORIES.COMPLETED,
    [NOTIFICATION_STATUS.STATUSES.OPENED]: NOTIFICATION_STATUS.CATEGORIES.ENGAGED,
    [NOTIFICATION_STATUS.STATUSES.CLICKED]: NOTIFICATION_STATUS.CATEGORIES.ENGAGED,
    [NOTIFICATION_STATUS.STATUSES.UNSUBSCRIBED]: NOTIFICATION_STATUS.CATEGORIES.COMPLETED,
    [NOTIFICATION_STATUS.STATUSES.SPAM]: NOTIFICATION_STATUS.CATEGORIES.FAILED,
    [NOTIFICATION_STATUS.STATUSES.COMPLAINED]: NOTIFICATION_STATUS.CATEGORIES.FAILED,
    [NOTIFICATION_STATUS.STATUSES.BOUNCED]: NOTIFICATION_STATUS.CATEGORIES.FAILED,
    [NOTIFICATION_STATUS.STATUSES.DEFERRED]: NOTIFICATION_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATION_STATUS.STATUSES.FAILED]: NOTIFICATION_STATUS.CATEGORIES.FAILED,
    [NOTIFICATION_STATUS.STATUSES.PAUSED]: NOTIFICATION_STATUS.CATEGORIES.PENDING,
    [NOTIFICATION_STATUS.STATUSES.EXPIRED]: NOTIFICATION_STATUS.CATEGORIES.FAILED,
    [NOTIFICATION_STATUS.STATUSES.CANCELLED]: NOTIFICATION_STATUS.CATEGORIES.CANCELLED,
    [NOTIFICATION_STATUS.STATUSES.ARCHIVED]: NOTIFICATION_STATUS.CATEGORIES.ARCHIVED,
    [NOTIFICATION_STATUS.STATUSES.READ]: NOTIFICATION_STATUS.CATEGORIES.COMPLETED,
    [NOTIFICATION_STATUS.STATUSES.UNREAD]: NOTIFICATION_STATUS.CATEGORIES.PENDING,
    [NOTIFICATION_STATUS.STATUSES.DELETED]: NOTIFICATION_STATUS.CATEGORIES.CANCELLED,
  };
  return categories[status] || NOTIFICATION_STATUS.CATEGORIES.DRAFT;
}

export function notificationIsDelivered(status: NotificationStatusType): boolean {
  const deliveredStatuses: NotificationStatusType[] = [
    NOTIFICATION_STATUS.STATUSES.DELIVERED,
    NOTIFICATION_STATUS.STATUSES.OPENED,
    NOTIFICATION_STATUS.STATUSES.CLICKED,
    NOTIFICATION_STATUS.STATUSES.READ,
  ];
  return deliveredStatuses.includes(status);
}

export function notificationIsEngaged(status: NotificationStatusType): boolean {
  const engagedStatuses: NotificationStatusType[] = [
    NOTIFICATION_STATUS.STATUSES.OPENED,
    NOTIFICATION_STATUS.STATUSES.CLICKED,
    NOTIFICATION_STATUS.STATUSES.READ,
  ];
  return engagedStatuses.includes(status);
}

export function notificationIsFailed(status: NotificationStatusType): boolean {
  const failedStatuses: NotificationStatusType[] = [
    NOTIFICATION_STATUS.STATUSES.FAILED,
    NOTIFICATION_STATUS.STATUSES.BOUNCED,
    NOTIFICATION_STATUS.STATUSES.SPAM,
    NOTIFICATION_STATUS.STATUSES.COMPLAINED,
    NOTIFICATION_STATUS.STATUSES.EXPIRED,
    NOTIFICATION_STATUS.STATUSES.REJECTED,
  ];
  return failedStatuses.includes(status);
}

export function notificationIsPending(status: NotificationStatusType): boolean {
  const pendingStatuses: NotificationStatusType[] = [
    NOTIFICATION_STATUS.STATUSES.PENDING,
    NOTIFICATION_STATUS.STATUSES.APPROVED,
    NOTIFICATION_STATUS.STATUSES.SCHEDULED,
    NOTIFICATION_STATUS.STATUSES.QUEUED,
    NOTIFICATION_STATUS.STATUSES.PROCESSING,
    NOTIFICATION_STATUS.STATUSES.SENT,
    NOTIFICATION_STATUS.STATUSES.DEFERRED,
    NOTIFICATION_STATUS.STATUSES.UNREAD,
  ];
  return pendingStatuses.includes(status);
}

export function notificationIsRead(status: NotificationStatusType): boolean {
  const readStatuses: NotificationStatusType[] = [
    NOTIFICATION_STATUS.STATUSES.READ,
    NOTIFICATION_STATUS.STATUSES.OPENED,
    NOTIFICATION_STATUS.STATUSES.CLICKED,
  ];
  return readStatuses.includes(status);
}

export function notificationIsTerminal(status: NotificationStatusType): boolean {
  const terminalStatuses: NotificationStatusType[] = [
    NOTIFICATION_STATUS.STATUSES.DELIVERED,
    NOTIFICATION_STATUS.STATUSES.OPENED,
    NOTIFICATION_STATUS.STATUSES.CLICKED,
    NOTIFICATION_STATUS.STATUSES.UNSUBSCRIBED,
    NOTIFICATION_STATUS.STATUSES.FAILED,
    NOTIFICATION_STATUS.STATUSES.BOUNCED,
    NOTIFICATION_STATUS.STATUSES.SPAM,
    NOTIFICATION_STATUS.STATUSES.COMPLAINED,
    NOTIFICATION_STATUS.STATUSES.ARCHIVED,
    NOTIFICATION_STATUS.STATUSES.CANCELLED,
    NOTIFICATION_STATUS.STATUSES.DELETED,
    NOTIFICATION_STATUS.STATUSES.READ,
  ];
  return terminalStatuses.includes(status);
}

export function notificationCanTransition(
  currentStatus: NotificationStatusType,
  targetStatus: NotificationStatusType
): boolean {
  const validTransitions: Record<NotificationStatusType, NotificationStatusType[]> = {
    [NOTIFICATION_STATUS.STATUSES.DRAFT]: [
      NOTIFICATION_STATUS.STATUSES.PENDING,
      NOTIFICATION_STATUS.STATUSES.CANCELLED,
      NOTIFICATION_STATUS.STATUSES.ARCHIVED,
    ],
    [NOTIFICATION_STATUS.STATUSES.PENDING]: [
      NOTIFICATION_STATUS.STATUSES.APPROVED,
      NOTIFICATION_STATUS.STATUSES.REJECTED,
      NOTIFICATION_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATION_STATUS.STATUSES.APPROVED]: [
      NOTIFICATION_STATUS.STATUSES.SCHEDULED,
      NOTIFICATION_STATUS.STATUSES.REJECTED,
      NOTIFICATION_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATION_STATUS.STATUSES.REJECTED]: [
      NOTIFICATION_STATUS.STATUSES.DRAFT,
      NOTIFICATION_STATUS.STATUSES.ARCHIVED,
    ],
    [NOTIFICATION_STATUS.STATUSES.SCHEDULED]: [
      NOTIFICATION_STATUS.STATUSES.QUEUED,
      NOTIFICATION_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATION_STATUS.STATUSES.QUEUED]: [
      NOTIFICATION_STATUS.STATUSES.PROCESSING,
      NOTIFICATION_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATION_STATUS.STATUSES.PROCESSING]: [
      NOTIFICATION_STATUS.STATUSES.SENT,
      NOTIFICATION_STATUS.STATUSES.FAILED,
      NOTIFICATION_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATION_STATUS.STATUSES.SENT]: [
      NOTIFICATION_STATUS.STATUSES.DELIVERED,
      NOTIFICATION_STATUS.STATUSES.BOUNCED,
      NOTIFICATION_STATUS.STATUSES.FAILED,
      NOTIFICATION_STATUS.STATUSES.DEFERRED,
    ],
    [NOTIFICATION_STATUS.STATUSES.DELIVERED]: [
      NOTIFICATION_STATUS.STATUSES.OPENED,
      NOTIFICATION_STATUS.STATUSES.UNSUBSCRIBED,
      NOTIFICATION_STATUS.STATUSES.SPAM,
      NOTIFICATION_STATUS.STATUSES.COMPLAINED,
    ],
    [NOTIFICATION_STATUS.STATUSES.OPENED]: [
      NOTIFICATION_STATUS.STATUSES.CLICKED,
      NOTIFICATION_STATUS.STATUSES.UNSUBSCRIBED,
    ],
    [NOTIFICATION_STATUS.STATUSES.CLICKED]: [
      NOTIFICATION_STATUS.STATUSES.UNSUBSCRIBED,
      NOTIFICATION_STATUS.STATUSES.COMPLAINED,
    ],
    [NOTIFICATION_STATUS.STATUSES.DEFERRED]: [
      NOTIFICATION_STATUS.STATUSES.SENT,
      NOTIFICATION_STATUS.STATUSES.FAILED,
      NOTIFICATION_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATION_STATUS.STATUSES.BOUNCED]: [NOTIFICATION_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATION_STATUS.STATUSES.FAILED]: [NOTIFICATION_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATION_STATUS.STATUSES.UNSUBSCRIBED]: [NOTIFICATION_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATION_STATUS.STATUSES.SPAM]: [NOTIFICATION_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATION_STATUS.STATUSES.COMPLAINED]: [NOTIFICATION_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATION_STATUS.STATUSES.PAUSED]: [
      NOTIFICATION_STATUS.STATUSES.PROCESSING,
      NOTIFICATION_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATION_STATUS.STATUSES.EXPIRED]: [NOTIFICATION_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATION_STATUS.STATUSES.CANCELLED]: [NOTIFICATION_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATION_STATUS.STATUSES.READ]: [
      NOTIFICATION_STATUS.STATUSES.UNREAD,
      NOTIFICATION_STATUS.STATUSES.ARCHIVED,
      NOTIFICATION_STATUS.STATUSES.DELETED,
    ],
    [NOTIFICATION_STATUS.STATUSES.UNREAD]: [
      NOTIFICATION_STATUS.STATUSES.READ,
      NOTIFICATION_STATUS.STATUSES.ARCHIVED,
      NOTIFICATION_STATUS.STATUSES.DELETED,
    ],
    [NOTIFICATION_STATUS.STATUSES.DELETED]: [NOTIFICATION_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATION_STATUS.STATUSES.ARCHIVED]: [],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
