// ============================================
// নোটিফিকেশন শিডিউল টাইপ সংক্রান্ত কনস্ট্যান্টসমূহ
// ============================================

// ============================================
// ১. শিডিউল টাইপ
// ============================================

/**
 * নোটিফিকেশন শিডিউল টাইপ
 * শিডিউলটি কোন ধরনের সময়সূচী অনুসরণ করে
 */
export type NotificationScheduleType =
  | typeof NOTIFICATION_SCHEDULE_TYPE_ONE_TIME
  | typeof NOTIFICATION_SCHEDULE_TYPE_RECURRING_DAILY
  | typeof NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKLY
  | typeof NOTIFICATION_SCHEDULE_TYPE_RECURRING_MONTHLY
  | typeof NOTIFICATION_SCHEDULE_TYPE_RECURRING_YEARLY
  | typeof NOTIFICATION_SCHEDULE_TYPE_CUSTOM_CRON
  | typeof NOTIFICATION_SCHEDULE_TYPE_EVENT_DRIVEN
  | typeof NOTIFICATION_SCHEDULE_TYPE_DELAYED
  | typeof NOTIFICATION_SCHEDULE_TYPE_RECURRING_HOURLY
  | typeof NOTIFICATION_SCHEDULE_TYPE_RECURRING_MINUTELY
  | typeof NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKDAY
  | typeof NOTIFICATION_SCHEDULE_TYPE_INTERVAL
  | typeof NOTIFICATION_SCHEDULE_TYPE_FIXED_TIME
  | typeof NOTIFICATION_SCHEDULE_TYPE_SMART;

/**
 * ওয়ান টাইম টাইপ
 * @description নির্দিষ্ট সময়ে একবার
 */
export const NOTIFICATION_SCHEDULE_TYPE_ONE_TIME = 'ONE_TIME';

/**
 * রিকারিং ডেইলি টাইপ
 * @description প্রতিদিন নির্দিষ্ট সময়ে
 */
export const NOTIFICATION_SCHEDULE_TYPE_RECURRING_DAILY = 'RECURRING_DAILY';

/**
 * রিকারিং উইকলি টাইপ
 * @description প্রতি সপ্তাহে নির্দিষ্ট দিনে
 */
export const NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKLY = 'RECURRING_WEEKLY';

/**
 * রিকারিং মান্থলি টাইপ
 * @description প্রতি মাসে নির্দিষ্ট তারিখে
 */
export const NOTIFICATION_SCHEDULE_TYPE_RECURRING_MONTHLY = 'RECURRING_MONTHLY';

/**
 * রিকারিং ইয়ারলি টাইপ
 * @description প্রতি বছরে নির্দিষ্ট তারিখে
 */
export const NOTIFICATION_SCHEDULE_TYPE_RECURRING_YEARLY = 'RECURRING_YEARLY';

/**
 * কাস্টম ক্রন টাইপ
 * @description কাস্টম ক্রন এক্সপ্রেশন
 */
export const NOTIFICATION_SCHEDULE_TYPE_CUSTOM_CRON = 'CUSTOM_CRON';

/**
 * ইভেন্ট ড্রিভেন টাইপ
 * @description ইভেন্টের উপর ভিত্তি করে
 */
export const NOTIFICATION_SCHEDULE_TYPE_EVENT_DRIVEN = 'EVENT_DRIVEN';

/**
 * ডিলেড টাইপ
 * @description নির্দিষ্ট সময় পর
 */
export const NOTIFICATION_SCHEDULE_TYPE_DELAYED = 'DELAYED';

/**
 * রিকারিং আওয়ারলি টাইপ
 * @description প্রতি ঘন্টায়
 */
export const NOTIFICATION_SCHEDULE_TYPE_RECURRING_HOURLY = 'RECURRING_HOURLY';

/**
 * রিকারিং মিনিটলি টাইপ
 * @description প্রতি মিনিটে
 */
export const NOTIFICATION_SCHEDULE_TYPE_RECURRING_MINUTELY = 'RECURRING_MINUTELY';

/**
 * রিকারিং উইকডে টাইপ
 * @description শুধুমাত্র কর্মদিবসে
 */
export const NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKDAY = 'RECURRING_WEEKDAY';

/**
 * ইন্টারভাল টাইপ
 * @description নির্দিষ্ট সময় ব্যবধানে
 */
export const NOTIFICATION_SCHEDULE_TYPE_INTERVAL = 'INTERVAL';

/**
 * ফিক্সড টাইম টাইপ
 * @description নির্দিষ্ট সময়ে
 */
export const NOTIFICATION_SCHEDULE_TYPE_FIXED_TIME = 'FIXED_TIME';

/**
 * স্মার্ট টাইপ
 * @description AI-ভিত্তিক স্মার্ট শিডিউল
 */
export const NOTIFICATION_SCHEDULE_TYPE_SMART = 'SMART';

// ============================================
// ২. শিডিউল টাইপ গ্রুপ
// ============================================

/**
 * শিডিউল টাইপ গ্রুপ
 */
export type NotificationScheduleTypeGroup =
  | typeof NOTIFICATION_SCHEDULE_TYPE_GROUP_ONE_TIME
  | typeof NOTIFICATION_SCHEDULE_TYPE_GROUP_RECURRING
  | typeof NOTIFICATION_SCHEDULE_TYPE_GROUP_DYNAMIC
  | typeof NOTIFICATION_SCHEDULE_TYPE_GROUP_ADVANCED;

/**
 * ওয়ান টাইম গ্রুপ
 * @description একবারের শিডিউল
 */
export const NOTIFICATION_SCHEDULE_TYPE_GROUP_ONE_TIME = 'ONE_TIME';

/**
 * রিকারিং গ্রুপ
 * @description পুনরাবৃত্ত শিডিউল
 */
export const NOTIFICATION_SCHEDULE_TYPE_GROUP_RECURRING = 'RECURRING';

/**
 * ডায়নামিক গ্রুপ
 * @description গতিশীল শিডিউল
 */
export const NOTIFICATION_SCHEDULE_TYPE_GROUP_DYNAMIC = 'DYNAMIC';

/**
 * অ্যাডভান্সড গ্রুপ
 * @description উন্নত শিডিউল
 */
export const NOTIFICATION_SCHEDULE_TYPE_GROUP_ADVANCED = 'ADVANCED';

// ============================================
// ৩. শিডিউল টাইপ থেকে গ্রুপ ম্যাপিং
// ============================================

/**
 * শিডিউল টাইপ থেকে গ্রুপ ম্যাপিং
 */
export const NOTIFICATION_SCHEDULE_TYPE_TO_GROUP: Record<
  NotificationScheduleType,
  NotificationScheduleTypeGroup
> = {
  [NOTIFICATION_SCHEDULE_TYPE_ONE_TIME]: NOTIFICATION_SCHEDULE_TYPE_GROUP_ONE_TIME,
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_DAILY]: NOTIFICATION_SCHEDULE_TYPE_GROUP_RECURRING,
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKLY]: NOTIFICATION_SCHEDULE_TYPE_GROUP_RECURRING,
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_MONTHLY]: NOTIFICATION_SCHEDULE_TYPE_GROUP_RECURRING,
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_YEARLY]: NOTIFICATION_SCHEDULE_TYPE_GROUP_RECURRING,
  [NOTIFICATION_SCHEDULE_TYPE_CUSTOM_CRON]: NOTIFICATION_SCHEDULE_TYPE_GROUP_ADVANCED,
  [NOTIFICATION_SCHEDULE_TYPE_EVENT_DRIVEN]: NOTIFICATION_SCHEDULE_TYPE_GROUP_DYNAMIC,
  [NOTIFICATION_SCHEDULE_TYPE_DELAYED]: NOTIFICATION_SCHEDULE_TYPE_GROUP_DYNAMIC,
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_HOURLY]: NOTIFICATION_SCHEDULE_TYPE_GROUP_RECURRING,
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_MINUTELY]: NOTIFICATION_SCHEDULE_TYPE_GROUP_RECURRING,
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKDAY]: NOTIFICATION_SCHEDULE_TYPE_GROUP_RECURRING,
  [NOTIFICATION_SCHEDULE_TYPE_INTERVAL]: NOTIFICATION_SCHEDULE_TYPE_GROUP_DYNAMIC,
  [NOTIFICATION_SCHEDULE_TYPE_FIXED_TIME]: NOTIFICATION_SCHEDULE_TYPE_GROUP_ONE_TIME,
  [NOTIFICATION_SCHEDULE_TYPE_SMART]: NOTIFICATION_SCHEDULE_TYPE_GROUP_ADVANCED,
};

// ============================================
// ৪. শিডিউল টাইপ লেবেল
// ============================================

/**
 * শিডিউল টাইপ লেবেল
 */
export const NOTIFICATION_SCHEDULE_TYPE_LABELS: Record<NotificationScheduleType, string> = {
  [NOTIFICATION_SCHEDULE_TYPE_ONE_TIME]: 'একবার',
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_DAILY]: 'দৈনিক (পুনরাবৃত্ত)',
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKLY]: 'সাপ্তাহিক (পুনরাবৃত্ত)',
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_MONTHLY]: 'মাসিক (পুনরাবৃত্ত)',
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_YEARLY]: 'বার্ষিক (পুনরাবৃত্ত)',
  [NOTIFICATION_SCHEDULE_TYPE_CUSTOM_CRON]: 'কাস্টম ক্রন',
  [NOTIFICATION_SCHEDULE_TYPE_EVENT_DRIVEN]: 'ইভেন্ট-চালিত',
  [NOTIFICATION_SCHEDULE_TYPE_DELAYED]: 'বিলম্বিত',
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_HOURLY]: 'প্রতি ঘন্টায় (পুনরাবৃত্ত)',
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_MINUTELY]: 'প্রতি মিনিটে (পুনরাবৃত্ত)',
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKDAY]: 'কর্মদিবসে (পুনরাবৃত্ত)',
  [NOTIFICATION_SCHEDULE_TYPE_INTERVAL]: 'ব্যবধানভিত্তিক',
  [NOTIFICATION_SCHEDULE_TYPE_FIXED_TIME]: 'নির্দিষ্ট সময়',
  [NOTIFICATION_SCHEDULE_TYPE_SMART]: 'স্মার্ট (AI)',
};

// ============================================
// ৫. শিডিউল টাইপ আইকন
// ============================================

/**
 * শিডিউল টাইপ আইকন
 */
export const NOTIFICATION_SCHEDULE_TYPE_ICONS: Record<NotificationScheduleType, string> = {
  [NOTIFICATION_SCHEDULE_TYPE_ONE_TIME]: 'event',
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_DAILY]: 'today',
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKLY]: 'date_range',
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_MONTHLY]: 'calendar_month',
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_YEARLY]: 'calendar_year',
  [NOTIFICATION_SCHEDULE_TYPE_CUSTOM_CRON]: 'cron',
  [NOTIFICATION_SCHEDULE_TYPE_EVENT_DRIVEN]: 'bolt',
  [NOTIFICATION_SCHEDULE_TYPE_DELAYED]: 'timer',
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_HOURLY]: 'hourglass',
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_MINUTELY]: 'schedule',
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKDAY]: 'work',
  [NOTIFICATION_SCHEDULE_TYPE_INTERVAL]: 'swap_horiz',
  [NOTIFICATION_SCHEDULE_TYPE_FIXED_TIME]: 'schedule',
  [NOTIFICATION_SCHEDULE_TYPE_SMART]: 'smart_toy',
};

// ============================================
// ৬. শিডিউল টাইপ কালার
// ============================================

/**
 * শিডিউল টাইপ কালার
 */
export const NOTIFICATION_SCHEDULE_TYPE_COLORS: Record<NotificationScheduleType, string> = {
  [NOTIFICATION_SCHEDULE_TYPE_ONE_TIME]: '#2196F3', // Blue
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_DAILY]: '#4CAF50', // Green
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKLY]: '#FF9800', // Orange
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_MONTHLY]: '#9C27B0', // Purple
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_YEARLY]: '#E91E63', // Pink
  [NOTIFICATION_SCHEDULE_TYPE_CUSTOM_CRON]: '#607D8B', // Blue Grey
  [NOTIFICATION_SCHEDULE_TYPE_EVENT_DRIVEN]: '#F44336', // Red
  [NOTIFICATION_SCHEDULE_TYPE_DELAYED]: '#FFC107', // Amber
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_HOURLY]: '#00BCD4', // Cyan
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_MINUTELY]: '#8BC34A', // Light Green
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKDAY]: '#3F51B5', // Indigo
  [NOTIFICATION_SCHEDULE_TYPE_INTERVAL]: '#795548', // Brown
  [NOTIFICATION_SCHEDULE_TYPE_FIXED_TIME]: '#009688', // Teal
  [NOTIFICATION_SCHEDULE_TYPE_SMART]: '#FF6F00', // Dark Amber
};

// ============================================
// ৭. শিডিউল টাইপ প্রায়োরিটি
// ============================================

/**
 * শিডিউল টাইপ প্রায়োরিটি (১-১০)
 */
export const NOTIFICATION_SCHEDULE_TYPE_PRIORITY: Record<NotificationScheduleType, number> = {
  [NOTIFICATION_SCHEDULE_TYPE_ONE_TIME]: 5,
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_DAILY]: 7,
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKLY]: 6,
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_MONTHLY]: 5,
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_YEARLY]: 4,
  [NOTIFICATION_SCHEDULE_TYPE_CUSTOM_CRON]: 8,
  [NOTIFICATION_SCHEDULE_TYPE_EVENT_DRIVEN]: 9,
  [NOTIFICATION_SCHEDULE_TYPE_DELAYED]: 6,
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_HOURLY]: 8,
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_MINUTELY]: 9,
  [NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKDAY]: 7,
  [NOTIFICATION_SCHEDULE_TYPE_INTERVAL]: 6,
  [NOTIFICATION_SCHEDULE_TYPE_FIXED_TIME]: 5,
  [NOTIFICATION_SCHEDULE_TYPE_SMART]: 10,
};

// ============================================
// ৮. শিডিউল টাইপ কনফিগারেশন
// ============================================

/**
 * শিডিউল টাইপ কনফিগারেশন
 */
export interface NotificationScheduleTypeConfig {
  /** টাইপের নাম */
  type: NotificationScheduleType;
  /** টাইপের লেবেল */
  label: string;
  /** টাইপের আইকন */
  icon: string;
  /** টাইপের কালার */
  color: string;
  /** টাইপের প্রায়োরিটি */
  priority: number;
  /** টাইপের গ্রুপ */
  group: NotificationScheduleTypeGroup;
  /** ক্রন ফরম্যাট প্রয়োজন কিনা */
  requiresCron: boolean;
  /** স্টার্ট ডেট প্রয়োজন কিনা */
  requiresStartDate: boolean;
  /** এন্ড ডেট প্রয়োজন কিনা */
  requiresEndDate: boolean;
  /** রিকারিং কিনা */
  isRecurring: boolean;
}

/**
 * সব শিডিউল টাইপের কনফিগারেশন
 */
export const NOTIFICATION_SCHEDULE_TYPE_CONFIGS: NotificationScheduleTypeConfig[] = [
  {
    type: NOTIFICATION_SCHEDULE_TYPE_ONE_TIME,
    label: NOTIFICATION_SCHEDULE_TYPE_LABELS[NOTIFICATION_SCHEDULE_TYPE_ONE_TIME],
    icon: NOTIFICATION_SCHEDULE_TYPE_ICONS[NOTIFICATION_SCHEDULE_TYPE_ONE_TIME],
    color: NOTIFICATION_SCHEDULE_TYPE_COLORS[NOTIFICATION_SCHEDULE_TYPE_ONE_TIME],
    priority: NOTIFICATION_SCHEDULE_TYPE_PRIORITY[NOTIFICATION_SCHEDULE_TYPE_ONE_TIME],
    group: NOTIFICATION_SCHEDULE_TYPE_TO_GROUP[NOTIFICATION_SCHEDULE_TYPE_ONE_TIME],
    requiresCron: false,
    requiresStartDate: true,
    requiresEndDate: false,
    isRecurring: false,
  },
  {
    type: NOTIFICATION_SCHEDULE_TYPE_RECURRING_DAILY,
    label: NOTIFICATION_SCHEDULE_TYPE_LABELS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_DAILY],
    icon: NOTIFICATION_SCHEDULE_TYPE_ICONS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_DAILY],
    color: NOTIFICATION_SCHEDULE_TYPE_COLORS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_DAILY],
    priority: NOTIFICATION_SCHEDULE_TYPE_PRIORITY[NOTIFICATION_SCHEDULE_TYPE_RECURRING_DAILY],
    group: NOTIFICATION_SCHEDULE_TYPE_TO_GROUP[NOTIFICATION_SCHEDULE_TYPE_RECURRING_DAILY],
    requiresCron: false,
    requiresStartDate: true,
    requiresEndDate: true,
    isRecurring: true,
  },
  {
    type: NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKLY,
    label: NOTIFICATION_SCHEDULE_TYPE_LABELS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKLY],
    icon: NOTIFICATION_SCHEDULE_TYPE_ICONS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKLY],
    color: NOTIFICATION_SCHEDULE_TYPE_COLORS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKLY],
    priority: NOTIFICATION_SCHEDULE_TYPE_PRIORITY[NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKLY],
    group: NOTIFICATION_SCHEDULE_TYPE_TO_GROUP[NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKLY],
    requiresCron: false,
    requiresStartDate: true,
    requiresEndDate: true,
    isRecurring: true,
  },
  {
    type: NOTIFICATION_SCHEDULE_TYPE_RECURRING_MONTHLY,
    label: NOTIFICATION_SCHEDULE_TYPE_LABELS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_MONTHLY],
    icon: NOTIFICATION_SCHEDULE_TYPE_ICONS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_MONTHLY],
    color: NOTIFICATION_SCHEDULE_TYPE_COLORS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_MONTHLY],
    priority: NOTIFICATION_SCHEDULE_TYPE_PRIORITY[NOTIFICATION_SCHEDULE_TYPE_RECURRING_MONTHLY],
    group: NOTIFICATION_SCHEDULE_TYPE_TO_GROUP[NOTIFICATION_SCHEDULE_TYPE_RECURRING_MONTHLY],
    requiresCron: false,
    requiresStartDate: true,
    requiresEndDate: true,
    isRecurring: true,
  },
  {
    type: NOTIFICATION_SCHEDULE_TYPE_RECURRING_YEARLY,
    label: NOTIFICATION_SCHEDULE_TYPE_LABELS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_YEARLY],
    icon: NOTIFICATION_SCHEDULE_TYPE_ICONS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_YEARLY],
    color: NOTIFICATION_SCHEDULE_TYPE_COLORS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_YEARLY],
    priority: NOTIFICATION_SCHEDULE_TYPE_PRIORITY[NOTIFICATION_SCHEDULE_TYPE_RECURRING_YEARLY],
    group: NOTIFICATION_SCHEDULE_TYPE_TO_GROUP[NOTIFICATION_SCHEDULE_TYPE_RECURRING_YEARLY],
    requiresCron: false,
    requiresStartDate: true,
    requiresEndDate: true,
    isRecurring: true,
  },
  {
    type: NOTIFICATION_SCHEDULE_TYPE_CUSTOM_CRON,
    label: NOTIFICATION_SCHEDULE_TYPE_LABELS[NOTIFICATION_SCHEDULE_TYPE_CUSTOM_CRON],
    icon: NOTIFICATION_SCHEDULE_TYPE_ICONS[NOTIFICATION_SCHEDULE_TYPE_CUSTOM_CRON],
    color: NOTIFICATION_SCHEDULE_TYPE_COLORS[NOTIFICATION_SCHEDULE_TYPE_CUSTOM_CRON],
    priority: NOTIFICATION_SCHEDULE_TYPE_PRIORITY[NOTIFICATION_SCHEDULE_TYPE_CUSTOM_CRON],
    group: NOTIFICATION_SCHEDULE_TYPE_TO_GROUP[NOTIFICATION_SCHEDULE_TYPE_CUSTOM_CRON],
    requiresCron: true,
    requiresStartDate: false,
    requiresEndDate: false,
    isRecurring: true,
  },
  {
    type: NOTIFICATION_SCHEDULE_TYPE_EVENT_DRIVEN,
    label: NOTIFICATION_SCHEDULE_TYPE_LABELS[NOTIFICATION_SCHEDULE_TYPE_EVENT_DRIVEN],
    icon: NOTIFICATION_SCHEDULE_TYPE_ICONS[NOTIFICATION_SCHEDULE_TYPE_EVENT_DRIVEN],
    color: NOTIFICATION_SCHEDULE_TYPE_COLORS[NOTIFICATION_SCHEDULE_TYPE_EVENT_DRIVEN],
    priority: NOTIFICATION_SCHEDULE_TYPE_PRIORITY[NOTIFICATION_SCHEDULE_TYPE_EVENT_DRIVEN],
    group: NOTIFICATION_SCHEDULE_TYPE_TO_GROUP[NOTIFICATION_SCHEDULE_TYPE_EVENT_DRIVEN],
    requiresCron: false,
    requiresStartDate: false,
    requiresEndDate: false,
    isRecurring: false,
  },
  {
    type: NOTIFICATION_SCHEDULE_TYPE_DELAYED,
    label: NOTIFICATION_SCHEDULE_TYPE_LABELS[NOTIFICATION_SCHEDULE_TYPE_DELAYED],
    icon: NOTIFICATION_SCHEDULE_TYPE_ICONS[NOTIFICATION_SCHEDULE_TYPE_DELAYED],
    color: NOTIFICATION_SCHEDULE_TYPE_COLORS[NOTIFICATION_SCHEDULE_TYPE_DELAYED],
    priority: NOTIFICATION_SCHEDULE_TYPE_PRIORITY[NOTIFICATION_SCHEDULE_TYPE_DELAYED],
    group: NOTIFICATION_SCHEDULE_TYPE_TO_GROUP[NOTIFICATION_SCHEDULE_TYPE_DELAYED],
    requiresCron: false,
    requiresStartDate: true,
    requiresEndDate: false,
    isRecurring: false,
  },
  {
    type: NOTIFICATION_SCHEDULE_TYPE_RECURRING_HOURLY,
    label: NOTIFICATION_SCHEDULE_TYPE_LABELS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_HOURLY],
    icon: NOTIFICATION_SCHEDULE_TYPE_ICONS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_HOURLY],
    color: NOTIFICATION_SCHEDULE_TYPE_COLORS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_HOURLY],
    priority: NOTIFICATION_SCHEDULE_TYPE_PRIORITY[NOTIFICATION_SCHEDULE_TYPE_RECURRING_HOURLY],
    group: NOTIFICATION_SCHEDULE_TYPE_TO_GROUP[NOTIFICATION_SCHEDULE_TYPE_RECURRING_HOURLY],
    requiresCron: false,
    requiresStartDate: true,
    requiresEndDate: true,
    isRecurring: true,
  },
  {
    type: NOTIFICATION_SCHEDULE_TYPE_RECURRING_MINUTELY,
    label: NOTIFICATION_SCHEDULE_TYPE_LABELS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_MINUTELY],
    icon: NOTIFICATION_SCHEDULE_TYPE_ICONS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_MINUTELY],
    color: NOTIFICATION_SCHEDULE_TYPE_COLORS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_MINUTELY],
    priority: NOTIFICATION_SCHEDULE_TYPE_PRIORITY[NOTIFICATION_SCHEDULE_TYPE_RECURRING_MINUTELY],
    group: NOTIFICATION_SCHEDULE_TYPE_TO_GROUP[NOTIFICATION_SCHEDULE_TYPE_RECURRING_MINUTELY],
    requiresCron: false,
    requiresStartDate: true,
    requiresEndDate: true,
    isRecurring: true,
  },
  {
    type: NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKDAY,
    label: NOTIFICATION_SCHEDULE_TYPE_LABELS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKDAY],
    icon: NOTIFICATION_SCHEDULE_TYPE_ICONS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKDAY],
    color: NOTIFICATION_SCHEDULE_TYPE_COLORS[NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKDAY],
    priority: NOTIFICATION_SCHEDULE_TYPE_PRIORITY[NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKDAY],
    group: NOTIFICATION_SCHEDULE_TYPE_TO_GROUP[NOTIFICATION_SCHEDULE_TYPE_RECURRING_WEEKDAY],
    requiresCron: false,
    requiresStartDate: true,
    requiresEndDate: true,
    isRecurring: true,
  },
  {
    type: NOTIFICATION_SCHEDULE_TYPE_INTERVAL,
    label: NOTIFICATION_SCHEDULE_TYPE_LABELS[NOTIFICATION_SCHEDULE_TYPE_INTERVAL],
    icon: NOTIFICATION_SCHEDULE_TYPE_ICONS[NOTIFICATION_SCHEDULE_TYPE_INTERVAL],
    color: NOTIFICATION_SCHEDULE_TYPE_COLORS[NOTIFICATION_SCHEDULE_TYPE_INTERVAL],
    priority: NOTIFICATION_SCHEDULE_TYPE_PRIORITY[NOTIFICATION_SCHEDULE_TYPE_INTERVAL],
    group: NOTIFICATION_SCHEDULE_TYPE_TO_GROUP[NOTIFICATION_SCHEDULE_TYPE_INTERVAL],
    requiresCron: false,
    requiresStartDate: true,
    requiresEndDate: true,
    isRecurring: true,
  },
  {
    type: NOTIFICATION_SCHEDULE_TYPE_FIXED_TIME,
    label: NOTIFICATION_SCHEDULE_TYPE_LABELS[NOTIFICATION_SCHEDULE_TYPE_FIXED_TIME],
    icon: NOTIFICATION_SCHEDULE_TYPE_ICONS[NOTIFICATION_SCHEDULE_TYPE_FIXED_TIME],
    color: NOTIFICATION_SCHEDULE_TYPE_COLORS[NOTIFICATION_SCHEDULE_TYPE_FIXED_TIME],
    priority: NOTIFICATION_SCHEDULE_TYPE_PRIORITY[NOTIFICATION_SCHEDULE_TYPE_FIXED_TIME],
    group: NOTIFICATION_SCHEDULE_TYPE_TO_GROUP[NOTIFICATION_SCHEDULE_TYPE_FIXED_TIME],
    requiresCron: false,
    requiresStartDate: true,
    requiresEndDate: false,
    isRecurring: false,
  },
  {
    type: NOTIFICATION_SCHEDULE_TYPE_SMART,
    label: NOTIFICATION_SCHEDULE_TYPE_LABELS[NOTIFICATION_SCHEDULE_TYPE_SMART],
    icon: NOTIFICATION_SCHEDULE_TYPE_ICONS[NOTIFICATION_SCHEDULE_TYPE_SMART],
    color: NOTIFICATION_SCHEDULE_TYPE_COLORS[NOTIFICATION_SCHEDULE_TYPE_SMART],
    priority: NOTIFICATION_SCHEDULE_TYPE_PRIORITY[NOTIFICATION_SCHEDULE_TYPE_SMART],
    group: NOTIFICATION_SCHEDULE_TYPE_TO_GROUP[NOTIFICATION_SCHEDULE_TYPE_SMART],
    requiresCron: false,
    requiresStartDate: true,
    requiresEndDate: false,
    isRecurring: false,
  },
];
