/**
 * Notification Action Constants
 * Action definitions for notifications
 */

export const NOTIFICATION_ACTION = {
  // Action Types
  TYPES: {
    VIEW: 'view',
    CLICK: 'click',
    DISMISS: 'dismiss',
    SNOOZE: 'snooze',
    REPLY: 'reply',
    FORWARD: 'forward',
    DELETE: 'delete',
    ARCHIVE: 'archive',
    MARK_READ: 'mark_read',
    MARK_UNREAD: 'mark_unread',
    FOLLOW: 'follow',
    UNFOLLOW: 'unfollow',
    LIKE: 'like',
    SHARE: 'share',
    SAVE: 'save',
    REPORT: 'report',
    BLOCK: 'block',
    UNSUBSCRIBE: 'unsubscribe',
    RESUBSCRIBE: 'resubscribe',
    CUSTOM: 'custom',
  } as const,

  // Action Categories
  CATEGORIES: {
    VIEW: 'view',
    INTERACT: 'interact',
    MODIFY: 'modify',
    SOCIAL: 'social',
    SETTINGS: 'settings',
    CUSTOM: 'custom',
  } as const,

  // Action Statuses
  STATUSES: {
    PENDING: 'pending',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
  } as const,

  // Action Icons (for UI)
  ICONS: {
    VIEW: '👁️',
    CLICK: '👆',
    DISMISS: '✖️',
    SNOOZE: '⏰',
    REPLY: '↩️',
    FORWARD: '➡️',
    DELETE: '🗑️',
    ARCHIVE: '📁',
    MARK_READ: '✅',
    MARK_UNREAD: '🔵',
    FOLLOW: '➕',
    UNFOLLOW: '➖',
    LIKE: '❤️',
    SHARE: '↗️',
    SAVE: '💾',
    REPORT: '🚨',
    BLOCK: '🚫',
    UNSUBSCRIBE: '📧',
    RESUBSCRIBE: '📨',
    CUSTOM: '⚙️',
  } as const,

  // Action Colors (for UI)
  COLORS: {
    VIEW: '#3B82F6',
    CLICK: '#10B981',
    DISMISS: '#6B7280',
    SNOOZE: '#F59E0B',
    REPLY: '#8B5CF6',
    FORWARD: '#3B82F6',
    DELETE: '#EF4444',
    ARCHIVE: '#6B7280',
    MARK_READ: '#10B981',
    MARK_UNREAD: '#3B82F6',
    FOLLOW: '#10B981',
    UNFOLLOW: '#EF4444',
    LIKE: '#EC4899',
    SHARE: '#3B82F6',
    SAVE: '#F59E0B',
    REPORT: '#EF4444',
    BLOCK: '#EF4444',
    UNSUBSCRIBE: '#6B7280',
    RESUBSCRIBE: '#10B981',
    CUSTOM: '#8B5CF6',
  } as const,

  // Action Defaults
  DEFAULTS: {
    DEFAULT_TYPE: 'view',
    DEFAULT_CATEGORY: 'view',
    DEFAULT_STATUS: 'pending',
    DEFAULT_ICON: '👁️',
    DEFAULT_COLOR: '#3B82F6',
  } as const,
} as const;

// Action Types
export type NotificationActionType =
  (typeof NOTIFICATION_ACTION.TYPES)[keyof typeof NOTIFICATION_ACTION.TYPES];

// Action Categories
export type NotificationActionCategory =
  (typeof NOTIFICATION_ACTION.CATEGORIES)[keyof typeof NOTIFICATION_ACTION.CATEGORIES];

// Action Statuses
export type NotificationActionStatus =
  (typeof NOTIFICATION_ACTION.STATUSES)[keyof typeof NOTIFICATION_ACTION.STATUSES];

// Action Icons
export type NotificationActionIcon =
  (typeof NOTIFICATION_ACTION.ICONS)[keyof typeof NOTIFICATION_ACTION.ICONS];

// Action Colors
export type NotificationActionColor =
  (typeof NOTIFICATION_ACTION.COLORS)[keyof typeof NOTIFICATION_ACTION.COLORS];

// Action Defaults
export type NotificationActionDefault =
  (typeof NOTIFICATION_ACTION.DEFAULTS)[keyof typeof NOTIFICATION_ACTION.DEFAULTS];

// Utility Functions
export function notificationGetActionLabel(action: NotificationActionType): string {
  const labels: Record<NotificationActionType, string> = {
    [NOTIFICATION_ACTION.TYPES.VIEW]: 'View',
    [NOTIFICATION_ACTION.TYPES.CLICK]: 'Click',
    [NOTIFICATION_ACTION.TYPES.DISMISS]: 'Dismiss',
    [NOTIFICATION_ACTION.TYPES.SNOOZE]: 'Snooze',
    [NOTIFICATION_ACTION.TYPES.REPLY]: 'Reply',
    [NOTIFICATION_ACTION.TYPES.FORWARD]: 'Forward',
    [NOTIFICATION_ACTION.TYPES.DELETE]: 'Delete',
    [NOTIFICATION_ACTION.TYPES.ARCHIVE]: 'Archive',
    [NOTIFICATION_ACTION.TYPES.MARK_READ]: 'Mark as Read',
    [NOTIFICATION_ACTION.TYPES.MARK_UNREAD]: 'Mark as Unread',
    [NOTIFICATION_ACTION.TYPES.FOLLOW]: 'Follow',
    [NOTIFICATION_ACTION.TYPES.UNFOLLOW]: 'Unfollow',
    [NOTIFICATION_ACTION.TYPES.LIKE]: 'Like',
    [NOTIFICATION_ACTION.TYPES.SHARE]: 'Share',
    [NOTIFICATION_ACTION.TYPES.SAVE]: 'Save',
    [NOTIFICATION_ACTION.TYPES.REPORT]: 'Report',
    [NOTIFICATION_ACTION.TYPES.BLOCK]: 'Block',
    [NOTIFICATION_ACTION.TYPES.UNSUBSCRIBE]: 'Unsubscribe',
    [NOTIFICATION_ACTION.TYPES.RESUBSCRIBE]: 'Resubscribe',
    [NOTIFICATION_ACTION.TYPES.CUSTOM]: 'Custom Action',
  };
  return labels[action] || 'Unknown Action';
}

export function notificationGetActionCategory(
  action: NotificationActionType
): NotificationActionCategory {
  const categories: Record<NotificationActionType, NotificationActionCategory> = {
    [NOTIFICATION_ACTION.TYPES.VIEW]: NOTIFICATION_ACTION.CATEGORIES.VIEW,
    [NOTIFICATION_ACTION.TYPES.CLICK]: NOTIFICATION_ACTION.CATEGORIES.VIEW,
    [NOTIFICATION_ACTION.TYPES.DISMISS]: NOTIFICATION_ACTION.CATEGORIES.VIEW,
    [NOTIFICATION_ACTION.TYPES.SNOOZE]: NOTIFICATION_ACTION.CATEGORIES.VIEW,
    [NOTIFICATION_ACTION.TYPES.REPLY]: NOTIFICATION_ACTION.CATEGORIES.INTERACT,
    [NOTIFICATION_ACTION.TYPES.FORWARD]: NOTIFICATION_ACTION.CATEGORIES.INTERACT,
    [NOTIFICATION_ACTION.TYPES.DELETE]: NOTIFICATION_ACTION.CATEGORIES.MODIFY,
    [NOTIFICATION_ACTION.TYPES.ARCHIVE]: NOTIFICATION_ACTION.CATEGORIES.MODIFY,
    [NOTIFICATION_ACTION.TYPES.MARK_READ]: NOTIFICATION_ACTION.CATEGORIES.MODIFY,
    [NOTIFICATION_ACTION.TYPES.MARK_UNREAD]: NOTIFICATION_ACTION.CATEGORIES.MODIFY,
    [NOTIFICATION_ACTION.TYPES.FOLLOW]: NOTIFICATION_ACTION.CATEGORIES.SOCIAL,
    [NOTIFICATION_ACTION.TYPES.UNFOLLOW]: NOTIFICATION_ACTION.CATEGORIES.SOCIAL,
    [NOTIFICATION_ACTION.TYPES.LIKE]: NOTIFICATION_ACTION.CATEGORIES.SOCIAL,
    [NOTIFICATION_ACTION.TYPES.SHARE]: NOTIFICATION_ACTION.CATEGORIES.SOCIAL,
    [NOTIFICATION_ACTION.TYPES.SAVE]: NOTIFICATION_ACTION.CATEGORIES.MODIFY,
    [NOTIFICATION_ACTION.TYPES.REPORT]: NOTIFICATION_ACTION.CATEGORIES.MODIFY,
    [NOTIFICATION_ACTION.TYPES.BLOCK]: NOTIFICATION_ACTION.CATEGORIES.MODIFY,
    [NOTIFICATION_ACTION.TYPES.UNSUBSCRIBE]: NOTIFICATION_ACTION.CATEGORIES.SETTINGS,
    [NOTIFICATION_ACTION.TYPES.RESUBSCRIBE]: NOTIFICATION_ACTION.CATEGORIES.SETTINGS,
    [NOTIFICATION_ACTION.TYPES.CUSTOM]: NOTIFICATION_ACTION.CATEGORIES.CUSTOM,
  };
  return categories[action] || NOTIFICATION_ACTION.CATEGORIES.VIEW;
}

export function notificationGetActionIcon(action: NotificationActionType): NotificationActionIcon {
  const icons: Record<NotificationActionType, NotificationActionIcon> = {
    [NOTIFICATION_ACTION.TYPES.VIEW]: NOTIFICATION_ACTION.ICONS.VIEW,
    [NOTIFICATION_ACTION.TYPES.CLICK]: NOTIFICATION_ACTION.ICONS.CLICK,
    [NOTIFICATION_ACTION.TYPES.DISMISS]: NOTIFICATION_ACTION.ICONS.DISMISS,
    [NOTIFICATION_ACTION.TYPES.SNOOZE]: NOTIFICATION_ACTION.ICONS.SNOOZE,
    [NOTIFICATION_ACTION.TYPES.REPLY]: NOTIFICATION_ACTION.ICONS.REPLY,
    [NOTIFICATION_ACTION.TYPES.FORWARD]: NOTIFICATION_ACTION.ICONS.FORWARD,
    [NOTIFICATION_ACTION.TYPES.DELETE]: NOTIFICATION_ACTION.ICONS.DELETE,
    [NOTIFICATION_ACTION.TYPES.ARCHIVE]: NOTIFICATION_ACTION.ICONS.ARCHIVE,
    [NOTIFICATION_ACTION.TYPES.MARK_READ]: NOTIFICATION_ACTION.ICONS.MARK_READ,
    [NOTIFICATION_ACTION.TYPES.MARK_UNREAD]: NOTIFICATION_ACTION.ICONS.MARK_UNREAD,
    [NOTIFICATION_ACTION.TYPES.FOLLOW]: NOTIFICATION_ACTION.ICONS.FOLLOW,
    [NOTIFICATION_ACTION.TYPES.UNFOLLOW]: NOTIFICATION_ACTION.ICONS.UNFOLLOW,
    [NOTIFICATION_ACTION.TYPES.LIKE]: NOTIFICATION_ACTION.ICONS.LIKE,
    [NOTIFICATION_ACTION.TYPES.SHARE]: NOTIFICATION_ACTION.ICONS.SHARE,
    [NOTIFICATION_ACTION.TYPES.SAVE]: NOTIFICATION_ACTION.ICONS.SAVE,
    [NOTIFICATION_ACTION.TYPES.REPORT]: NOTIFICATION_ACTION.ICONS.REPORT,
    [NOTIFICATION_ACTION.TYPES.BLOCK]: NOTIFICATION_ACTION.ICONS.BLOCK,
    [NOTIFICATION_ACTION.TYPES.UNSUBSCRIBE]: NOTIFICATION_ACTION.ICONS.UNSUBSCRIBE,
    [NOTIFICATION_ACTION.TYPES.RESUBSCRIBE]: NOTIFICATION_ACTION.ICONS.RESUBSCRIBE,
    [NOTIFICATION_ACTION.TYPES.CUSTOM]: NOTIFICATION_ACTION.ICONS.CUSTOM,
  };
  return icons[action] || NOTIFICATION_ACTION.ICONS.VIEW;
}

export function notificationGetActionColor(
  action: NotificationActionType
): NotificationActionColor {
  const colors: Record<NotificationActionType, NotificationActionColor> = {
    [NOTIFICATION_ACTION.TYPES.VIEW]: NOTIFICATION_ACTION.COLORS.VIEW,
    [NOTIFICATION_ACTION.TYPES.CLICK]: NOTIFICATION_ACTION.COLORS.CLICK,
    [NOTIFICATION_ACTION.TYPES.DISMISS]: NOTIFICATION_ACTION.COLORS.DISMISS,
    [NOTIFICATION_ACTION.TYPES.SNOOZE]: NOTIFICATION_ACTION.COLORS.SNOOZE,
    [NOTIFICATION_ACTION.TYPES.REPLY]: NOTIFICATION_ACTION.COLORS.REPLY,
    [NOTIFICATION_ACTION.TYPES.FORWARD]: NOTIFICATION_ACTION.COLORS.FORWARD,
    [NOTIFICATION_ACTION.TYPES.DELETE]: NOTIFICATION_ACTION.COLORS.DELETE,
    [NOTIFICATION_ACTION.TYPES.ARCHIVE]: NOTIFICATION_ACTION.COLORS.ARCHIVE,
    [NOTIFICATION_ACTION.TYPES.MARK_READ]: NOTIFICATION_ACTION.COLORS.MARK_READ,
    [NOTIFICATION_ACTION.TYPES.MARK_UNREAD]: NOTIFICATION_ACTION.COLORS.MARK_UNREAD,
    [NOTIFICATION_ACTION.TYPES.FOLLOW]: NOTIFICATION_ACTION.COLORS.FOLLOW,
    [NOTIFICATION_ACTION.TYPES.UNFOLLOW]: NOTIFICATION_ACTION.COLORS.UNFOLLOW,
    [NOTIFICATION_ACTION.TYPES.LIKE]: NOTIFICATION_ACTION.COLORS.LIKE,
    [NOTIFICATION_ACTION.TYPES.SHARE]: NOTIFICATION_ACTION.COLORS.SHARE,
    [NOTIFICATION_ACTION.TYPES.SAVE]: NOTIFICATION_ACTION.COLORS.SAVE,
    [NOTIFICATION_ACTION.TYPES.REPORT]: NOTIFICATION_ACTION.COLORS.REPORT,
    [NOTIFICATION_ACTION.TYPES.BLOCK]: NOTIFICATION_ACTION.COLORS.BLOCK,
    [NOTIFICATION_ACTION.TYPES.UNSUBSCRIBE]: NOTIFICATION_ACTION.COLORS.UNSUBSCRIBE,
    [NOTIFICATION_ACTION.TYPES.RESUBSCRIBE]: NOTIFICATION_ACTION.COLORS.RESUBSCRIBE,
    [NOTIFICATION_ACTION.TYPES.CUSTOM]: NOTIFICATION_ACTION.COLORS.CUSTOM,
  };
  return colors[action] || NOTIFICATION_ACTION.COLORS.VIEW;
}

export function notificationIsViewAction(action: NotificationActionType): boolean {
  const viewActions: NotificationActionType[] = [
    NOTIFICATION_ACTION.TYPES.VIEW,
    NOTIFICATION_ACTION.TYPES.CLICK,
  ];
  return viewActions.includes(action);
}

export function notificationIsInteractAction(action: NotificationActionType): boolean {
  const interactActions: NotificationActionType[] = [
    NOTIFICATION_ACTION.TYPES.REPLY,
    NOTIFICATION_ACTION.TYPES.FORWARD,
    NOTIFICATION_ACTION.TYPES.LIKE,
    NOTIFICATION_ACTION.TYPES.SHARE,
  ];
  return interactActions.includes(action);
}

export function notificationIsModifyAction(action: NotificationActionType): boolean {
  const modifyActions: NotificationActionType[] = [
    NOTIFICATION_ACTION.TYPES.DELETE,
    NOTIFICATION_ACTION.TYPES.ARCHIVE,
    NOTIFICATION_ACTION.TYPES.MARK_READ,
    NOTIFICATION_ACTION.TYPES.MARK_UNREAD,
    NOTIFICATION_ACTION.TYPES.SAVE,
    NOTIFICATION_ACTION.TYPES.REPORT,
    NOTIFICATION_ACTION.TYPES.BLOCK,
  ];
  return modifyActions.includes(action);
}

export function notificationIsSocialAction(action: NotificationActionType): boolean {
  const socialActions: NotificationActionType[] = [
    NOTIFICATION_ACTION.TYPES.FOLLOW,
    NOTIFICATION_ACTION.TYPES.UNFOLLOW,
  ];
  return socialActions.includes(action);
}

export function notificationGetDefaultAction(): NotificationActionType {
  return NOTIFICATION_ACTION.DEFAULTS.DEFAULT_TYPE;
}
