// ============================================
// নোটিফিকেশন ক্যাটেগরি সংক্রান্ত কনস্ট্যান্টসমূহ
// ============================================

// ============================================
// ১. নোটিফিকেশন ক্যাটেগরি
// ============================================

/**
 * নোটিফিকেশন ক্যাটেগরি
 * নোটিফিকেশনের বিষয়বস্তু বা প্রসঙ্গ নির্দেশ করে
 */
export type NotificationCategory =
  | typeof NOTIFICATION_CATEGORY_ORDER
  | typeof NOTIFICATION_CATEGORY_PAYMENT
  | typeof NOTIFICATION_CATEGORY_SHIPPING
  | typeof NOTIFICATION_CATEGORY_DELIVERY
  | typeof NOTIFICATION_CATEGORY_RETURN
  | typeof NOTIFICATION_CATEGORY_REFUND
  | typeof NOTIFICATION_CATEGORY_SUPPORT
  | typeof NOTIFICATION_CATEGORY_FEEDBACK
  | typeof NOTIFICATION_CATEGORY_REVIEW
  | typeof NOTIFICATION_CATEGORY_SECURITY
  | typeof NOTIFICATION_CATEGORY_ACCOUNT
  | typeof NOTIFICATION_CATEGORY_SYSTEM
  | typeof NOTIFICATION_CATEGORY_PROMOTION
  | typeof NOTIFICATION_CATEGORY_SOCIAL
  | typeof NOTIFICATION_CATEGORY_UPDATE
  | typeof NOTIFICATION_CATEGORY_MAINTENANCE
  | typeof NOTIFICATION_CATEGORY_PRODUCT
  | typeof NOTIFICATION_CATEGORY_INVENTORY
  | typeof NOTIFICATION_CATEGORY_SUBSCRIPTION
  | typeof NOTIFICATION_CATEGORY_ANALYTICS;

/**
 * অর্ডার ক্যাটেগরি
 * @description অর্ডার সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_ORDER = 'ORDER';

/**
 * পেমেন্ট ক্যাটেগরি
 * @description পেমেন্ট সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_PAYMENT = 'PAYMENT';

/**
 * শিপিং ক্যাটেগরি
 * @description শিপিং সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_SHIPPING = 'SHIPPING';

/**
 * ডেলিভারি ক্যাটেগরি
 * @description ডেলিভারি সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_DELIVERY = 'DELIVERY';

/**
 * রিটার্ন ক্যাটেগরি
 * @description রিটার্ন সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_RETURN = 'RETURN';

/**
 * রিফান্ড ক্যাটেগরি
 * @description রিফান্ড সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_REFUND = 'REFUND';

/**
 * সাপোর্ট ক্যাটেগরি
 * @description সাপোর্ট সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_SUPPORT = 'SUPPORT';

/**
 * ফিডব্যাক ক্যাটেগরি
 * @description ফিডব্যাক সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_FEEDBACK = 'FEEDBACK';

/**
 * রিভিউ ক্যাটেগরি
 * @description রিভিউ সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_REVIEW = 'REVIEW';

/**
 * সিকিউরিটি ক্যাটেগরি
 * @description সিকিউরিটি সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_SECURITY = 'SECURITY';

/**
 * অ্যাকাউন্ট ক্যাটেগরি
 * @description অ্যাকাউন্ট সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_ACCOUNT = 'ACCOUNT';

/**
 * সিস্টেম ক্যাটেগরি
 * @description সিস্টেম সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_SYSTEM = 'SYSTEM';

/**
 * প্রমোশন ক্যাটেগরি
 * @description প্রচারমূলক নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_PROMOTION = 'PROMOTION';

/**
 * সোশ্যাল ক্যাটেগরি
 * @description সোশ্যাল মিডিয়া সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_SOCIAL = 'SOCIAL';

/**
 * আপডেট ক্যাটেগরি
 * @description আপডেট সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_UPDATE = 'UPDATE';

/**
 * মেইনটেন্যান্স ক্যাটেগরি
 * @description মেইনটেন্যান্স সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_MAINTENANCE = 'MAINTENANCE';

/**
 * প্রোডাক্ট ক্যাটেগরি
 * @description প্রোডাক্ট সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_PRODUCT = 'PRODUCT';

/**
 * ইনভেন্টরি ক্যাটেগরি
 * @description ইনভেন্টরি সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_INVENTORY = 'INVENTORY';

/**
 * সাবস্ক্রিপশন ক্যাটেগরি
 * @description সাবস্ক্রিপশন সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_SUBSCRIPTION = 'SUBSCRIPTION';

/**
 * অ্যানালিটিক্স ক্যাটেগরি
 * @description অ্যানালিটিক্স সংক্রান্ত নোটিফিকেশন
 */
export const NOTIFICATION_CATEGORY_ANALYTICS = 'ANALYTICS';

// ============================================
// ২. ক্যাটেগরি গ্রুপ
// ============================================

/**
 * ক্যাটেগরি গ্রুপ
 */
export type NotificationCategoryGroup =
  | typeof NOTIFICATION_CATEGORY_GROUP_ECOMMERCE
  | typeof NOTIFICATION_CATEGORY_GROUP_SYSTEM
  | typeof NOTIFICATION_CATEGORY_GROUP_USER
  | typeof NOTIFICATION_CATEGORY_GROUP_BUSINESS
  | typeof NOTIFICATION_CATEGORY_GROUP_COMMUNICATION;

/**
 * ইকমার্স গ্রুপ
 * @description ইকমার্স সংক্রান্ত ক্যাটেগরি
 */
export const NOTIFICATION_CATEGORY_GROUP_ECOMMERCE = 'ECOMMERCE';

/**
 * সিস্টেম গ্রুপ
 * @description সিস্টেম সংক্রান্ত ক্যাটেগরি
 */
export const NOTIFICATION_CATEGORY_GROUP_SYSTEM = 'SYSTEM';

/**
 * ইউজার গ্রুপ
 * @description ইউজার সংক্রান্ত ক্যাটেগরি
 */
export const NOTIFICATION_CATEGORY_GROUP_USER = 'USER';

/**
 * বিজনেস গ্রুপ
 * @description ব্যবসায়িক ক্যাটেগরি
 */
export const NOTIFICATION_CATEGORY_GROUP_BUSINESS = 'BUSINESS';

/**
 * কমিউনিকেশন গ্রুপ
 * @description যোগাযোগ সংক্রান্ত ক্যাটেগরি
 */
export const NOTIFICATION_CATEGORY_GROUP_COMMUNICATION = 'COMMUNICATION';

// ============================================
// ৩. ক্যাটেগরি থেকে গ্রুপ ম্যাপিং
// ============================================

/**
 * ক্যাটেগরি থেকে গ্রুপ ম্যাপিং
 */
export const NOTIFICATION_CATEGORY_TO_GROUP: Record<
  NotificationCategory,
  NotificationCategoryGroup
> = {
  [NOTIFICATION_CATEGORY_ORDER]: NOTIFICATION_CATEGORY_GROUP_ECOMMERCE,
  [NOTIFICATION_CATEGORY_PAYMENT]: NOTIFICATION_CATEGORY_GROUP_ECOMMERCE,
  [NOTIFICATION_CATEGORY_SHIPPING]: NOTIFICATION_CATEGORY_GROUP_ECOMMERCE,
  [NOTIFICATION_CATEGORY_DELIVERY]: NOTIFICATION_CATEGORY_GROUP_ECOMMERCE,
  [NOTIFICATION_CATEGORY_RETURN]: NOTIFICATION_CATEGORY_GROUP_ECOMMERCE,
  [NOTIFICATION_CATEGORY_REFUND]: NOTIFICATION_CATEGORY_GROUP_ECOMMERCE,
  [NOTIFICATION_CATEGORY_SUPPORT]: NOTIFICATION_CATEGORY_GROUP_COMMUNICATION,
  [NOTIFICATION_CATEGORY_FEEDBACK]: NOTIFICATION_CATEGORY_GROUP_COMMUNICATION,
  [NOTIFICATION_CATEGORY_REVIEW]: NOTIFICATION_CATEGORY_GROUP_COMMUNICATION,
  [NOTIFICATION_CATEGORY_SECURITY]: NOTIFICATION_CATEGORY_GROUP_SYSTEM,
  [NOTIFICATION_CATEGORY_ACCOUNT]: NOTIFICATION_CATEGORY_GROUP_USER,
  [NOTIFICATION_CATEGORY_SYSTEM]: NOTIFICATION_CATEGORY_GROUP_SYSTEM,
  [NOTIFICATION_CATEGORY_PROMOTION]: NOTIFICATION_CATEGORY_GROUP_BUSINESS,
  [NOTIFICATION_CATEGORY_SOCIAL]: NOTIFICATION_CATEGORY_GROUP_COMMUNICATION,
  [NOTIFICATION_CATEGORY_UPDATE]: NOTIFICATION_CATEGORY_GROUP_SYSTEM,
  [NOTIFICATION_CATEGORY_MAINTENANCE]: NOTIFICATION_CATEGORY_GROUP_SYSTEM,
  [NOTIFICATION_CATEGORY_PRODUCT]: NOTIFICATION_CATEGORY_GROUP_ECOMMERCE,
  [NOTIFICATION_CATEGORY_INVENTORY]: NOTIFICATION_CATEGORY_GROUP_ECOMMERCE,
  [NOTIFICATION_CATEGORY_SUBSCRIPTION]: NOTIFICATION_CATEGORY_GROUP_BUSINESS,
  [NOTIFICATION_CATEGORY_ANALYTICS]: NOTIFICATION_CATEGORY_GROUP_BUSINESS,
};

// ============================================
// ৪. ক্যাটেগরি লেবেল
// ============================================

/**
 * ক্যাটেগরি লেবেল
 */
export const NOTIFICATION_CATEGORY_LABELS: Record<NotificationCategory, string> = {
  [NOTIFICATION_CATEGORY_ORDER]: 'অর্ডার',
  [NOTIFICATION_CATEGORY_PAYMENT]: 'পেমেন্ট',
  [NOTIFICATION_CATEGORY_SHIPPING]: 'শিপিং',
  [NOTIFICATION_CATEGORY_DELIVERY]: 'ডেলিভারি',
  [NOTIFICATION_CATEGORY_RETURN]: 'রিটার্ন',
  [NOTIFICATION_CATEGORY_REFUND]: 'রিফান্ড',
  [NOTIFICATION_CATEGORY_SUPPORT]: 'সাপোর্ট',
  [NOTIFICATION_CATEGORY_FEEDBACK]: 'ফিডব্যাক',
  [NOTIFICATION_CATEGORY_REVIEW]: 'রিভিউ',
  [NOTIFICATION_CATEGORY_SECURITY]: 'সিকিউরিটি',
  [NOTIFICATION_CATEGORY_ACCOUNT]: 'অ্যাকাউন্ট',
  [NOTIFICATION_CATEGORY_SYSTEM]: 'সিস্টেম',
  [NOTIFICATION_CATEGORY_PROMOTION]: 'প্রমোশন',
  [NOTIFICATION_CATEGORY_SOCIAL]: 'সোশ্যাল',
  [NOTIFICATION_CATEGORY_UPDATE]: 'আপডেট',
  [NOTIFICATION_CATEGORY_MAINTENANCE]: 'মেইনটেন্যান্স',
  [NOTIFICATION_CATEGORY_PRODUCT]: 'প্রোডাক্ট',
  [NOTIFICATION_CATEGORY_INVENTORY]: 'ইনভেন্টরি',
  [NOTIFICATION_CATEGORY_SUBSCRIPTION]: 'সাবস্ক্রিপশন',
  [NOTIFICATION_CATEGORY_ANALYTICS]: 'অ্যানালিটিক্স',
};

// ============================================
// ৫. ক্যাটেগরি আইকন
// ============================================

/**
 * ক্যাটেগরি আইকন
 */
export const NOTIFICATION_CATEGORY_ICONS: Record<NotificationCategory, string> = {
  [NOTIFICATION_CATEGORY_ORDER]: 'shopping-cart',
  [NOTIFICATION_CATEGORY_PAYMENT]: 'payment',
  [NOTIFICATION_CATEGORY_SHIPPING]: 'local-shipping',
  [NOTIFICATION_CATEGORY_DELIVERY]: 'delivery',
  [NOTIFICATION_CATEGORY_RETURN]: 'return',
  [NOTIFICATION_CATEGORY_REFUND]: 'refund',
  [NOTIFICATION_CATEGORY_SUPPORT]: 'support',
  [NOTIFICATION_CATEGORY_FEEDBACK]: 'feedback',
  [NOTIFICATION_CATEGORY_REVIEW]: 'rate-review',
  [NOTIFICATION_CATEGORY_SECURITY]: 'security',
  [NOTIFICATION_CATEGORY_ACCOUNT]: 'account-circle',
  [NOTIFICATION_CATEGORY_SYSTEM]: 'system-update',
  [NOTIFICATION_CATEGORY_PROMOTION]: 'campaign',
  [NOTIFICATION_CATEGORY_SOCIAL]: 'share',
  [NOTIFICATION_CATEGORY_UPDATE]: 'update',
  [NOTIFICATION_CATEGORY_MAINTENANCE]: 'build',
  [NOTIFICATION_CATEGORY_PRODUCT]: 'inventory',
  [NOTIFICATION_CATEGORY_INVENTORY]: 'warehouse',
  [NOTIFICATION_CATEGORY_SUBSCRIPTION]: 'subscription',
  [NOTIFICATION_CATEGORY_ANALYTICS]: 'analytics',
};

// ============================================
// ৬. ক্যাটেগরি কালার
// ============================================

/**
 * ক্যাটেগরি কালার
 */
export const NOTIFICATION_CATEGORY_COLORS: Record<NotificationCategory, string> = {
  [NOTIFICATION_CATEGORY_ORDER]: '#2196F3', // Blue
  [NOTIFICATION_CATEGORY_PAYMENT]: '#4CAF50', // Green
  [NOTIFICATION_CATEGORY_SHIPPING]: '#FF9800', // Orange
  [NOTIFICATION_CATEGORY_DELIVERY]: '#00BCD4', // Cyan
  [NOTIFICATION_CATEGORY_RETURN]: '#9C27B0', // Purple
  [NOTIFICATION_CATEGORY_REFUND]: '#E91E63', // Pink
  [NOTIFICATION_CATEGORY_SUPPORT]: '#607D8B', // Blue Grey
  [NOTIFICATION_CATEGORY_FEEDBACK]: '#8BC34A', // Light Green
  [NOTIFICATION_CATEGORY_REVIEW]: '#FFC107', // Amber
  [NOTIFICATION_CATEGORY_SECURITY]: '#F44336', // Red
  [NOTIFICATION_CATEGORY_ACCOUNT]: '#3F51B5', // Indigo
  [NOTIFICATION_CATEGORY_SYSTEM]: '#795548', // Brown
  [NOTIFICATION_CATEGORY_PROMOTION]: '#FF5722', // Deep Orange
  [NOTIFICATION_CATEGORY_SOCIAL]: '#E91E63', // Pink
  [NOTIFICATION_CATEGORY_UPDATE]: '#009688', // Teal
  [NOTIFICATION_CATEGORY_MAINTENANCE]: '#9E9E9E', // Grey
  [NOTIFICATION_CATEGORY_PRODUCT]: '#673AB7', // Deep Purple
  [NOTIFICATION_CATEGORY_INVENTORY]: '#CDDC39', // Lime
  [NOTIFICATION_CATEGORY_SUBSCRIPTION]: '#3F51B5', // Indigo
  [NOTIFICATION_CATEGORY_ANALYTICS]: '#00BCD4', // Cyan
};

// ============================================
// ৭. ক্যাটেগরি প্রায়োরিটি
// ============================================

/**
 * ক্যাটেগরি প্রায়োরিটি (১-১০)
 */
export const NOTIFICATION_CATEGORY_PRIORITY: Record<NotificationCategory, number> = {
  [NOTIFICATION_CATEGORY_ORDER]: 7,
  [NOTIFICATION_CATEGORY_PAYMENT]: 8,
  [NOTIFICATION_CATEGORY_SHIPPING]: 6,
  [NOTIFICATION_CATEGORY_DELIVERY]: 7,
  [NOTIFICATION_CATEGORY_RETURN]: 5,
  [NOTIFICATION_CATEGORY_REFUND]: 6,
  [NOTIFICATION_CATEGORY_SUPPORT]: 5,
  [NOTIFICATION_CATEGORY_FEEDBACK]: 4,
  [NOTIFICATION_CATEGORY_REVIEW]: 4,
  [NOTIFICATION_CATEGORY_SECURITY]: 9,
  [NOTIFICATION_CATEGORY_ACCOUNT]: 7,
  [NOTIFICATION_CATEGORY_SYSTEM]: 8,
  [NOTIFICATION_CATEGORY_PROMOTION]: 3,
  [NOTIFICATION_CATEGORY_SOCIAL]: 3,
  [NOTIFICATION_CATEGORY_UPDATE]: 5,
  [NOTIFICATION_CATEGORY_MAINTENANCE]: 6,
  [NOTIFICATION_CATEGORY_PRODUCT]: 5,
  [NOTIFICATION_CATEGORY_INVENTORY]: 4,
  [NOTIFICATION_CATEGORY_SUBSCRIPTION]: 6,
  [NOTIFICATION_CATEGORY_ANALYTICS]: 4,
};

// ============================================
// ৮. ক্যাটেগরি কনফিগারেশন
// ============================================

/**
 * নোটিফিকেশন ক্যাটেগরি কনফিগারেশন
 */
export interface NotificationCategoryConfig {
  /** ক্যাটেগরির নাম */
  category: NotificationCategory;
  /** ক্যাটেগরির লেবেল */
  label: string;
  /** ক্যাটেগরির আইকন */
  icon: string;
  /** ক্যাটেগরির কালার */
  color: string;
  /** ক্যাটেগরির প্রায়োরিটি */
  priority: number;
  /** ক্যাটেগরির গ্রুপ */
  group: NotificationCategoryGroup;
}

/**
 * সব নোটিফিকেশন ক্যাটেগরির কনফিগারেশন
 */
export const NOTIFICATION_CATEGORY_CONFIGS: NotificationCategoryConfig[] = [
  {
    category: NOTIFICATION_CATEGORY_ORDER,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_ORDER],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_ORDER],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_ORDER],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_ORDER],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_ORDER],
  },
  {
    category: NOTIFICATION_CATEGORY_PAYMENT,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_PAYMENT],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_PAYMENT],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_PAYMENT],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_PAYMENT],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_PAYMENT],
  },
  {
    category: NOTIFICATION_CATEGORY_SHIPPING,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_SHIPPING],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_SHIPPING],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_SHIPPING],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_SHIPPING],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_SHIPPING],
  },
  {
    category: NOTIFICATION_CATEGORY_DELIVERY,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_DELIVERY],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_DELIVERY],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_DELIVERY],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_DELIVERY],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_DELIVERY],
  },
  {
    category: NOTIFICATION_CATEGORY_RETURN,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_RETURN],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_RETURN],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_RETURN],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_RETURN],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_RETURN],
  },
  {
    category: NOTIFICATION_CATEGORY_REFUND,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_REFUND],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_REFUND],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_REFUND],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_REFUND],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_REFUND],
  },
  {
    category: NOTIFICATION_CATEGORY_SUPPORT,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_SUPPORT],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_SUPPORT],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_SUPPORT],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_SUPPORT],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_SUPPORT],
  },
  {
    category: NOTIFICATION_CATEGORY_FEEDBACK,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_FEEDBACK],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_FEEDBACK],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_FEEDBACK],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_FEEDBACK],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_FEEDBACK],
  },
  {
    category: NOTIFICATION_CATEGORY_REVIEW,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_REVIEW],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_REVIEW],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_REVIEW],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_REVIEW],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_REVIEW],
  },
  {
    category: NOTIFICATION_CATEGORY_SECURITY,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_SECURITY],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_SECURITY],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_SECURITY],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_SECURITY],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_SECURITY],
  },
  {
    category: NOTIFICATION_CATEGORY_ACCOUNT,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_ACCOUNT],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_ACCOUNT],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_ACCOUNT],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_ACCOUNT],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_ACCOUNT],
  },
  {
    category: NOTIFICATION_CATEGORY_SYSTEM,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_SYSTEM],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_SYSTEM],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_SYSTEM],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_SYSTEM],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_SYSTEM],
  },
  {
    category: NOTIFICATION_CATEGORY_PROMOTION,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_PROMOTION],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_PROMOTION],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_PROMOTION],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_PROMOTION],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_PROMOTION],
  },
  {
    category: NOTIFICATION_CATEGORY_SOCIAL,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_SOCIAL],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_SOCIAL],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_SOCIAL],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_SOCIAL],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_SOCIAL],
  },
  {
    category: NOTIFICATION_CATEGORY_UPDATE,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_UPDATE],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_UPDATE],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_UPDATE],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_UPDATE],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_UPDATE],
  },
  {
    category: NOTIFICATION_CATEGORY_MAINTENANCE,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_MAINTENANCE],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_MAINTENANCE],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_MAINTENANCE],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_MAINTENANCE],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_MAINTENANCE],
  },
  {
    category: NOTIFICATION_CATEGORY_PRODUCT,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_PRODUCT],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_PRODUCT],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_PRODUCT],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_PRODUCT],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_PRODUCT],
  },
  {
    category: NOTIFICATION_CATEGORY_INVENTORY,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_INVENTORY],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_INVENTORY],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_INVENTORY],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_INVENTORY],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_INVENTORY],
  },
  {
    category: NOTIFICATION_CATEGORY_SUBSCRIPTION,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_SUBSCRIPTION],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_SUBSCRIPTION],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_SUBSCRIPTION],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_SUBSCRIPTION],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_SUBSCRIPTION],
  },
  {
    category: NOTIFICATION_CATEGORY_ANALYTICS,
    label: NOTIFICATION_CATEGORY_LABELS[NOTIFICATION_CATEGORY_ANALYTICS],
    icon: NOTIFICATION_CATEGORY_ICONS[NOTIFICATION_CATEGORY_ANALYTICS],
    color: NOTIFICATION_CATEGORY_COLORS[NOTIFICATION_CATEGORY_ANALYTICS],
    priority: NOTIFICATION_CATEGORY_PRIORITY[NOTIFICATION_CATEGORY_ANALYTICS],
    group: NOTIFICATION_CATEGORY_TO_GROUP[NOTIFICATION_CATEGORY_ANALYTICS],
  },
];
