// ============================================
// ডাইজেস্ট নোটিফিকেশন টাইপ সংক্রান্ত কনস্ট্যান্টসমূহ
// ============================================

// ============================================
// ১. ডাইজেস্ট টাইপ
// ============================================

/**
 * ডাইজেস্ট নোটিফিকেশন টাইপ
 * ডাইজেস্টের সংক্ষিপ্তকরণের ধরন ও ফ্রিকোয়েন্সি নির্দেশ করে
 */
export type NotificationDigestType =
  | typeof NOTIFICATION_DIGEST_TYPE_DAILY
  | typeof NOTIFICATION_DIGEST_TYPE_WEEKLY
  | typeof NOTIFICATION_DIGEST_TYPE_MONTHLY
  | typeof NOTIFICATION_DIGEST_TYPE_QUARTERLY
  | typeof NOTIFICATION_DIGEST_TYPE_CUSTOM
  | typeof NOTIFICATION_DIGEST_TYPE_SUMMARY
  | typeof NOTIFICATION_DIGEST_TYPE_DETAILED
  | typeof NOTIFICATION_DIGEST_TYPE_CONDENSED
  | typeof NOTIFICATION_DIGEST_TYPE_HOURLY
  | typeof NOTIFICATION_DIGEST_TYPE_REAL_TIME
  | typeof NOTIFICATION_DIGEST_TYPE_SMART
  | typeof NOTIFICATION_DIGEST_TYPE_PRIORITY_FILTER
  | typeof NOTIFICATION_DIGEST_TYPE_COMPREHENSIVE
  | typeof NOTIFICATION_DIGEST_TYPE_EXECUTIVE;

/**
 * ডেইলি ডাইজেস্ট
 * @description প্রতিদিনের সংক্ষিপ্তসার
 */
export const NOTIFICATION_DIGEST_TYPE_DAILY = 'DAILY';

/**
 * উইকলি ডাইজেস্ট
 * @description সাপ্তাহিক সংক্ষিপ্তসার
 */
export const NOTIFICATION_DIGEST_TYPE_WEEKLY = 'WEEKLY';

/**
 * মান্থলি ডাইজেস্ট
 * @description মাসিক সংক্ষিপ্তসার
 */
export const NOTIFICATION_DIGEST_TYPE_MONTHLY = 'MONTHLY';

/**
 * কোয়ার্টারলি ডাইজেস্ট
 * @description ত্রৈমাসিক সংক্ষিপ্তসার
 */
export const NOTIFICATION_DIGEST_TYPE_QUARTERLY = 'QUARTERLY';

/**
 * কাস্টম ডাইজেস্ট
 * @description কাস্টম সময়সূচীতে সংক্ষিপ্তসার
 */
export const NOTIFICATION_DIGEST_TYPE_CUSTOM = 'CUSTOM';

/**
 * সামারি ডাইজেস্ট
 * @description সংক্ষিপ্ত সারাংশ
 */
export const NOTIFICATION_DIGEST_TYPE_SUMMARY = 'SUMMARY';

/**
 * ডিটেইলড ডাইজেস্ট
 * @description বিস্তারিত সংক্ষিপ্তসার
 */
export const NOTIFICATION_DIGEST_TYPE_DETAILED = 'DETAILED';

/**
 * কনডেন্সড ডাইজেস্ট
 * @description অতি সংক্ষিপ্ত সারাংশ
 */
export const NOTIFICATION_DIGEST_TYPE_CONDENSED = 'CONDENSED';

/**
 * আওয়ারলি ডাইজেস্ট
 * @description প্রতি ঘন্টায় সংক্ষিপ্তসার
 */
export const NOTIFICATION_DIGEST_TYPE_HOURLY = 'HOURLY';

/**
 * রিয়েল-টাইম ডাইজেস্ট
 * @description তাৎক্ষণিক সংক্ষিপ্তসার
 */
export const NOTIFICATION_DIGEST_TYPE_REAL_TIME = 'REAL_TIME';

/**
 * স্মার্ট ডাইজেস্ট
 * @description AI-ভিত্তিক স্মার্ট সংক্ষিপ্তসার
 */
export const NOTIFICATION_DIGEST_TYPE_SMART = 'SMART';

/**
 * প্রায়োরিটি ফিল্টার ডাইজেস্ট
 * @description শুধুমাত্র গুরুত্বপূর্ণ সংক্ষিপ্তসার
 */
export const NOTIFICATION_DIGEST_TYPE_PRIORITY_FILTER = 'PRIORITY_FILTER';

/**
 * কমপ্রিহেন্সিভ ডাইজেস্ট
 * @description সম্পূর্ণ বিস্তারিত সংক্ষিপ্তসার
 */
export const NOTIFICATION_DIGEST_TYPE_COMPREHENSIVE = 'COMPREHENSIVE';

/**
 * এক্সিকিউটিভ ডাইজেস্ট
 * @description নির্বাহীদের জন্য সংক্ষিপ্তসার
 */
export const NOTIFICATION_DIGEST_TYPE_EXECUTIVE = 'EXECUTIVE';

// ============================================
// ২. ডাইজেস্ট টাইপ গ্রুপ
// ============================================

/**
 * ডাইজেস্ট টাইপ গ্রুপ
 */
export type NotificationDigestTypeGroup =
  | typeof NOTIFICATION_DIGEST_TYPE_GROUP_FREQUENCY
  | typeof NOTIFICATION_DIGEST_TYPE_GROUP_FORMAT
  | typeof NOTIFICATION_DIGEST_TYPE_GROUP_INTELLIGENCE
  | typeof NOTIFICATION_DIGEST_TYPE_GROUP_SPECIAL;

/**
 * ফ্রিকোয়েন্সি গ্রুপ
 * @description সময়সূচীভিত্তিক ডাইজেস্ট
 */
export const NOTIFICATION_DIGEST_TYPE_GROUP_FREQUENCY = 'FREQUENCY';

/**
 * ফরম্যাট গ্রুপ
 * @description ফরম্যাটভিত্তিক ডাইজেস্ট
 */
export const NOTIFICATION_DIGEST_TYPE_GROUP_FORMAT = 'FORMAT';

/**
 * ইন্টেলিজেন্স গ্রুপ
 * @description স্মার্ট ও বুদ্ধিমান ডাইজেস্ট
 */
export const NOTIFICATION_DIGEST_TYPE_GROUP_INTELLIGENCE = 'INTELLIGENCE';

/**
 * স্পেশাল গ্রুপ
 * @description বিশেষ উদ্দেশ্যে ডাইজেস্ট
 */
export const NOTIFICATION_DIGEST_TYPE_GROUP_SPECIAL = 'SPECIAL';

// ============================================
// ৩. ডাইজেস্ট টাইপ থেকে গ্রুপ ম্যাপিং
// ============================================

/**
 * ডাইজেস্ট টাইপ থেকে গ্রুপ ম্যাপিং
 */
export const NOTIFICATION_DIGEST_TYPE_TO_GROUP: Record<
  NotificationDigestType,
  NotificationDigestTypeGroup
> = {
  [NOTIFICATION_DIGEST_TYPE_DAILY]: NOTIFICATION_DIGEST_TYPE_GROUP_FREQUENCY,
  [NOTIFICATION_DIGEST_TYPE_WEEKLY]: NOTIFICATION_DIGEST_TYPE_GROUP_FREQUENCY,
  [NOTIFICATION_DIGEST_TYPE_MONTHLY]: NOTIFICATION_DIGEST_TYPE_GROUP_FREQUENCY,
  [NOTIFICATION_DIGEST_TYPE_QUARTERLY]: NOTIFICATION_DIGEST_TYPE_GROUP_FREQUENCY,
  [NOTIFICATION_DIGEST_TYPE_CUSTOM]: NOTIFICATION_DIGEST_TYPE_GROUP_FREQUENCY,
  [NOTIFICATION_DIGEST_TYPE_SUMMARY]: NOTIFICATION_DIGEST_TYPE_GROUP_FORMAT,
  [NOTIFICATION_DIGEST_TYPE_DETAILED]: NOTIFICATION_DIGEST_TYPE_GROUP_FORMAT,
  [NOTIFICATION_DIGEST_TYPE_CONDENSED]: NOTIFICATION_DIGEST_TYPE_GROUP_FORMAT,
  [NOTIFICATION_DIGEST_TYPE_HOURLY]: NOTIFICATION_DIGEST_TYPE_GROUP_FREQUENCY,
  [NOTIFICATION_DIGEST_TYPE_REAL_TIME]: NOTIFICATION_DIGEST_TYPE_GROUP_FREQUENCY,
  [NOTIFICATION_DIGEST_TYPE_SMART]: NOTIFICATION_DIGEST_TYPE_GROUP_INTELLIGENCE,
  [NOTIFICATION_DIGEST_TYPE_PRIORITY_FILTER]: NOTIFICATION_DIGEST_TYPE_GROUP_INTELLIGENCE,
  [NOTIFICATION_DIGEST_TYPE_COMPREHENSIVE]: NOTIFICATION_DIGEST_TYPE_GROUP_SPECIAL,
  [NOTIFICATION_DIGEST_TYPE_EXECUTIVE]: NOTIFICATION_DIGEST_TYPE_GROUP_SPECIAL,
};

// ============================================
// ৪. ডাইজেস্ট টাইপ লেবেল
// ============================================

/**
 * ডাইজেস্ট টাইপ লেবেল
 */
export const NOTIFICATION_DIGEST_TYPE_LABELS: Record<NotificationDigestType, string> = {
  [NOTIFICATION_DIGEST_TYPE_DAILY]: 'দৈনিক',
  [NOTIFICATION_DIGEST_TYPE_WEEKLY]: 'সাপ্তাহিক',
  [NOTIFICATION_DIGEST_TYPE_MONTHLY]: 'মাসিক',
  [NOTIFICATION_DIGEST_TYPE_QUARTERLY]: 'ত্রৈমাসিক',
  [NOTIFICATION_DIGEST_TYPE_CUSTOM]: 'কাস্টম',
  [NOTIFICATION_DIGEST_TYPE_SUMMARY]: 'সারাংশ',
  [NOTIFICATION_DIGEST_TYPE_DETAILED]: 'বিস্তারিত',
  [NOTIFICATION_DIGEST_TYPE_CONDENSED]: 'সংক্ষিপ্ত',
  [NOTIFICATION_DIGEST_TYPE_HOURLY]: 'প্রতি ঘন্টায়',
  [NOTIFICATION_DIGEST_TYPE_REAL_TIME]: 'রিয়েল-টাইম',
  [NOTIFICATION_DIGEST_TYPE_SMART]: 'স্মার্ট (AI)',
  [NOTIFICATION_DIGEST_TYPE_PRIORITY_FILTER]: 'গুরুত্বপূর্ণ',
  [NOTIFICATION_DIGEST_TYPE_COMPREHENSIVE]: 'সম্পূর্ণ',
  [NOTIFICATION_DIGEST_TYPE_EXECUTIVE]: 'নির্বাহী',
};

// ============================================
// ৫. ডাইজেস্ট টাইপ আইকন
// ============================================

/**
 * ডাইজেস্ট টাইপ আইকন
 */
export const NOTIFICATION_DIGEST_TYPE_ICONS: Record<NotificationDigestType, string> = {
  [NOTIFICATION_DIGEST_TYPE_DAILY]: 'today',
  [NOTIFICATION_DIGEST_TYPE_WEEKLY]: 'date_range',
  [NOTIFICATION_DIGEST_TYPE_MONTHLY]: 'calendar_month',
  [NOTIFICATION_DIGEST_TYPE_QUARTERLY]: 'calendar_year',
  [NOTIFICATION_DIGEST_TYPE_CUSTOM]: 'settings',
  [NOTIFICATION_DIGEST_TYPE_SUMMARY]: 'summarize',
  [NOTIFICATION_DIGEST_TYPE_DETAILED]: 'description',
  [NOTIFICATION_DIGEST_TYPE_CONDENSED]: 'compress',
  [NOTIFICATION_DIGEST_TYPE_HOURLY]: 'hourglass',
  [NOTIFICATION_DIGEST_TYPE_REAL_TIME]: 'bolt',
  [NOTIFICATION_DIGEST_TYPE_SMART]: 'smart_toy',
  [NOTIFICATION_DIGEST_TYPE_PRIORITY_FILTER]: 'priority_high',
  [NOTIFICATION_DIGEST_TYPE_COMPREHENSIVE]: 'view_list',
  [NOTIFICATION_DIGEST_TYPE_EXECUTIVE]: 'dashboard',
};

// ============================================
// ৬. ডাইজেস্ট টাইপ কালার
// ============================================

/**
 * ডাইজেস্ট টাইপ কালার
 */
export const NOTIFICATION_DIGEST_TYPE_COLORS: Record<NotificationDigestType, string> = {
  [NOTIFICATION_DIGEST_TYPE_DAILY]: '#4CAF50', // Green
  [NOTIFICATION_DIGEST_TYPE_WEEKLY]: '#2196F3', // Blue
  [NOTIFICATION_DIGEST_TYPE_MONTHLY]: '#9C27B0', // Purple
  [NOTIFICATION_DIGEST_TYPE_QUARTERLY]: '#3F51B5', // Indigo
  [NOTIFICATION_DIGEST_TYPE_CUSTOM]: '#607D8B', // Blue Grey
  [NOTIFICATION_DIGEST_TYPE_SUMMARY]: '#00BCD4', // Cyan
  [NOTIFICATION_DIGEST_TYPE_DETAILED]: '#795548', // Brown
  [NOTIFICATION_DIGEST_TYPE_CONDENSED]: '#FF9800', // Orange
  [NOTIFICATION_DIGEST_TYPE_HOURLY]: '#8BC34A', // Light Green
  [NOTIFICATION_DIGEST_TYPE_REAL_TIME]: '#FF6F00', // Dark Amber
  [NOTIFICATION_DIGEST_TYPE_SMART]: '#E91E63', // Pink
  [NOTIFICATION_DIGEST_TYPE_PRIORITY_FILTER]: '#F44336', // Red
  [NOTIFICATION_DIGEST_TYPE_COMPREHENSIVE]: '#009688', // Teal
  [NOTIFICATION_DIGEST_TYPE_EXECUTIVE]: '#1A237E', // Dark Indigo
};

// ============================================
// ৭. ডাইজেস্ট টাইপ প্রায়োরিটি
// ============================================

/**
 * ডাইজেস্ট টাইপ প্রায়োরিটি (১-১০)
 */
export const NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES: Record<NotificationDigestType, number> = {
  [NOTIFICATION_DIGEST_TYPE_DAILY]: 6,
  [NOTIFICATION_DIGEST_TYPE_WEEKLY]: 5,
  [NOTIFICATION_DIGEST_TYPE_MONTHLY]: 4,
  [NOTIFICATION_DIGEST_TYPE_QUARTERLY]: 3,
  [NOTIFICATION_DIGEST_TYPE_CUSTOM]: 5,
  [NOTIFICATION_DIGEST_TYPE_SUMMARY]: 7,
  [NOTIFICATION_DIGEST_TYPE_DETAILED]: 6,
  [NOTIFICATION_DIGEST_TYPE_CONDENSED]: 8,
  [NOTIFICATION_DIGEST_TYPE_HOURLY]: 7,
  [NOTIFICATION_DIGEST_TYPE_REAL_TIME]: 9,
  [NOTIFICATION_DIGEST_TYPE_SMART]: 8,
  [NOTIFICATION_DIGEST_TYPE_PRIORITY_FILTER]: 9,
  [NOTIFICATION_DIGEST_TYPE_COMPREHENSIVE]: 5,
  [NOTIFICATION_DIGEST_TYPE_EXECUTIVE]: 6,
};

// ============================================
// ৮. ডাইজেস্ট টাইপ কনফিগারেশন
// ============================================

/**
 * ডাইজেস্ট টাইপ কনফিগারেশন
 */
export interface NotificationDigestTypeConfig {
  /** টাইপের নাম */
  type: NotificationDigestType;
  /** টাইপের লেবেল */
  label: string;
  /** টাইপের আইকন */
  icon: string;
  /** টাইপের কালার */
  color: string;
  /** টাইপের প্রায়োরিটি */
  priority: number;
  /** টাইপের গ্রুপ */
  group: NotificationDigestTypeGroup;
  /** ফ্রিকোয়েন্সি-ভিত্তিক টাইপ কিনা */
  isFrequencyBased: boolean;
  /** ফরম্যাট-ভিত্তিক টাইপ কিনা */
  isFormatBased: boolean;
  /** স্মার্ট টাইপ কিনা */
  isSmart: boolean;
}

/**
 * সব ডাইজেস্ট টাইপের কনফিগারেশন
 */
export const NOTIFICATION_DIGEST_TYPE_CONFIGS: NotificationDigestTypeConfig[] = [
  {
    type: NOTIFICATION_DIGEST_TYPE_DAILY,
    label: NOTIFICATION_DIGEST_TYPE_LABELS[NOTIFICATION_DIGEST_TYPE_DAILY],
    icon: NOTIFICATION_DIGEST_TYPE_ICONS[NOTIFICATION_DIGEST_TYPE_DAILY],
    color: NOTIFICATION_DIGEST_TYPE_COLORS[NOTIFICATION_DIGEST_TYPE_DAILY],
    priority: NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES[NOTIFICATION_DIGEST_TYPE_DAILY],
    group: NOTIFICATION_DIGEST_TYPE_TO_GROUP[NOTIFICATION_DIGEST_TYPE_DAILY],
    isFrequencyBased: true,
    isFormatBased: false,
    isSmart: false,
  },
  {
    type: NOTIFICATION_DIGEST_TYPE_WEEKLY,
    label: NOTIFICATION_DIGEST_TYPE_LABELS[NOTIFICATION_DIGEST_TYPE_WEEKLY],
    icon: NOTIFICATION_DIGEST_TYPE_ICONS[NOTIFICATION_DIGEST_TYPE_WEEKLY],
    color: NOTIFICATION_DIGEST_TYPE_COLORS[NOTIFICATION_DIGEST_TYPE_WEEKLY],
    priority: NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES[NOTIFICATION_DIGEST_TYPE_WEEKLY],
    group: NOTIFICATION_DIGEST_TYPE_TO_GROUP[NOTIFICATION_DIGEST_TYPE_WEEKLY],
    isFrequencyBased: true,
    isFormatBased: false,
    isSmart: false,
  },
  {
    type: NOTIFICATION_DIGEST_TYPE_MONTHLY,
    label: NOTIFICATION_DIGEST_TYPE_LABELS[NOTIFICATION_DIGEST_TYPE_MONTHLY],
    icon: NOTIFICATION_DIGEST_TYPE_ICONS[NOTIFICATION_DIGEST_TYPE_MONTHLY],
    color: NOTIFICATION_DIGEST_TYPE_COLORS[NOTIFICATION_DIGEST_TYPE_MONTHLY],
    priority: NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES[NOTIFICATION_DIGEST_TYPE_MONTHLY],
    group: NOTIFICATION_DIGEST_TYPE_TO_GROUP[NOTIFICATION_DIGEST_TYPE_MONTHLY],
    isFrequencyBased: true,
    isFormatBased: false,
    isSmart: false,
  },
  {
    type: NOTIFICATION_DIGEST_TYPE_QUARTERLY,
    label: NOTIFICATION_DIGEST_TYPE_LABELS[NOTIFICATION_DIGEST_TYPE_QUARTERLY],
    icon: NOTIFICATION_DIGEST_TYPE_ICONS[NOTIFICATION_DIGEST_TYPE_QUARTERLY],
    color: NOTIFICATION_DIGEST_TYPE_COLORS[NOTIFICATION_DIGEST_TYPE_QUARTERLY],
    priority: NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES[NOTIFICATION_DIGEST_TYPE_QUARTERLY],
    group: NOTIFICATION_DIGEST_TYPE_TO_GROUP[NOTIFICATION_DIGEST_TYPE_QUARTERLY],
    isFrequencyBased: true,
    isFormatBased: false,
    isSmart: false,
  },
  {
    type: NOTIFICATION_DIGEST_TYPE_CUSTOM,
    label: NOTIFICATION_DIGEST_TYPE_LABELS[NOTIFICATION_DIGEST_TYPE_CUSTOM],
    icon: NOTIFICATION_DIGEST_TYPE_ICONS[NOTIFICATION_DIGEST_TYPE_CUSTOM],
    color: NOTIFICATION_DIGEST_TYPE_COLORS[NOTIFICATION_DIGEST_TYPE_CUSTOM],
    priority: NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES[NOTIFICATION_DIGEST_TYPE_CUSTOM],
    group: NOTIFICATION_DIGEST_TYPE_TO_GROUP[NOTIFICATION_DIGEST_TYPE_CUSTOM],
    isFrequencyBased: true,
    isFormatBased: false,
    isSmart: false,
  },
  {
    type: NOTIFICATION_DIGEST_TYPE_SUMMARY,
    label: NOTIFICATION_DIGEST_TYPE_LABELS[NOTIFICATION_DIGEST_TYPE_SUMMARY],
    icon: NOTIFICATION_DIGEST_TYPE_ICONS[NOTIFICATION_DIGEST_TYPE_SUMMARY],
    color: NOTIFICATION_DIGEST_TYPE_COLORS[NOTIFICATION_DIGEST_TYPE_SUMMARY],
    priority: NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES[NOTIFICATION_DIGEST_TYPE_SUMMARY],
    group: NOTIFICATION_DIGEST_TYPE_TO_GROUP[NOTIFICATION_DIGEST_TYPE_SUMMARY],
    isFrequencyBased: false,
    isFormatBased: true,
    isSmart: false,
  },
  {
    type: NOTIFICATION_DIGEST_TYPE_DETAILED,
    label: NOTIFICATION_DIGEST_TYPE_LABELS[NOTIFICATION_DIGEST_TYPE_DETAILED],
    icon: NOTIFICATION_DIGEST_TYPE_ICONS[NOTIFICATION_DIGEST_TYPE_DETAILED],
    color: NOTIFICATION_DIGEST_TYPE_COLORS[NOTIFICATION_DIGEST_TYPE_DETAILED],
    priority: NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES[NOTIFICATION_DIGEST_TYPE_DETAILED],
    group: NOTIFICATION_DIGEST_TYPE_TO_GROUP[NOTIFICATION_DIGEST_TYPE_DETAILED],
    isFrequencyBased: false,
    isFormatBased: true,
    isSmart: false,
  },
  {
    type: NOTIFICATION_DIGEST_TYPE_CONDENSED,
    label: NOTIFICATION_DIGEST_TYPE_LABELS[NOTIFICATION_DIGEST_TYPE_CONDENSED],
    icon: NOTIFICATION_DIGEST_TYPE_ICONS[NOTIFICATION_DIGEST_TYPE_CONDENSED],
    color: NOTIFICATION_DIGEST_TYPE_COLORS[NOTIFICATION_DIGEST_TYPE_CONDENSED],
    priority: NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES[NOTIFICATION_DIGEST_TYPE_CONDENSED],
    group: NOTIFICATION_DIGEST_TYPE_TO_GROUP[NOTIFICATION_DIGEST_TYPE_CONDENSED],
    isFrequencyBased: false,
    isFormatBased: true,
    isSmart: false,
  },
  {
    type: NOTIFICATION_DIGEST_TYPE_HOURLY,
    label: NOTIFICATION_DIGEST_TYPE_LABELS[NOTIFICATION_DIGEST_TYPE_HOURLY],
    icon: NOTIFICATION_DIGEST_TYPE_ICONS[NOTIFICATION_DIGEST_TYPE_HOURLY],
    color: NOTIFICATION_DIGEST_TYPE_COLORS[NOTIFICATION_DIGEST_TYPE_HOURLY],
    priority: NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES[NOTIFICATION_DIGEST_TYPE_HOURLY],
    group: NOTIFICATION_DIGEST_TYPE_TO_GROUP[NOTIFICATION_DIGEST_TYPE_HOURLY],
    isFrequencyBased: true,
    isFormatBased: false,
    isSmart: false,
  },
  {
    type: NOTIFICATION_DIGEST_TYPE_REAL_TIME,
    label: NOTIFICATION_DIGEST_TYPE_LABELS[NOTIFICATION_DIGEST_TYPE_REAL_TIME],
    icon: NOTIFICATION_DIGEST_TYPE_ICONS[NOTIFICATION_DIGEST_TYPE_REAL_TIME],
    color: NOTIFICATION_DIGEST_TYPE_COLORS[NOTIFICATION_DIGEST_TYPE_REAL_TIME],
    priority: NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES[NOTIFICATION_DIGEST_TYPE_REAL_TIME],
    group: NOTIFICATION_DIGEST_TYPE_TO_GROUP[NOTIFICATION_DIGEST_TYPE_REAL_TIME],
    isFrequencyBased: true,
    isFormatBased: false,
    isSmart: false,
  },
  {
    type: NOTIFICATION_DIGEST_TYPE_SMART,
    label: NOTIFICATION_DIGEST_TYPE_LABELS[NOTIFICATION_DIGEST_TYPE_SMART],
    icon: NOTIFICATION_DIGEST_TYPE_ICONS[NOTIFICATION_DIGEST_TYPE_SMART],
    color: NOTIFICATION_DIGEST_TYPE_COLORS[NOTIFICATION_DIGEST_TYPE_SMART],
    priority: NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES[NOTIFICATION_DIGEST_TYPE_SMART],
    group: NOTIFICATION_DIGEST_TYPE_TO_GROUP[NOTIFICATION_DIGEST_TYPE_SMART],
    isFrequencyBased: false,
    isFormatBased: false,
    isSmart: true,
  },
  {
    type: NOTIFICATION_DIGEST_TYPE_PRIORITY_FILTER,
    label: NOTIFICATION_DIGEST_TYPE_LABELS[NOTIFICATION_DIGEST_TYPE_PRIORITY_FILTER],
    icon: NOTIFICATION_DIGEST_TYPE_ICONS[NOTIFICATION_DIGEST_TYPE_PRIORITY_FILTER],
    color: NOTIFICATION_DIGEST_TYPE_COLORS[NOTIFICATION_DIGEST_TYPE_PRIORITY_FILTER],
    priority: NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES[NOTIFICATION_DIGEST_TYPE_PRIORITY_FILTER],
    group: NOTIFICATION_DIGEST_TYPE_TO_GROUP[NOTIFICATION_DIGEST_TYPE_PRIORITY_FILTER],
    isFrequencyBased: false,
    isFormatBased: false,
    isSmart: true,
  },
  {
    type: NOTIFICATION_DIGEST_TYPE_COMPREHENSIVE,
    label: NOTIFICATION_DIGEST_TYPE_LABELS[NOTIFICATION_DIGEST_TYPE_COMPREHENSIVE],
    icon: NOTIFICATION_DIGEST_TYPE_ICONS[NOTIFICATION_DIGEST_TYPE_COMPREHENSIVE],
    color: NOTIFICATION_DIGEST_TYPE_COLORS[NOTIFICATION_DIGEST_TYPE_COMPREHENSIVE],
    priority: NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES[NOTIFICATION_DIGEST_TYPE_COMPREHENSIVE],
    group: NOTIFICATION_DIGEST_TYPE_TO_GROUP[NOTIFICATION_DIGEST_TYPE_COMPREHENSIVE],
    isFrequencyBased: false,
    isFormatBased: false,
    isSmart: false,
  },
  {
    type: NOTIFICATION_DIGEST_TYPE_EXECUTIVE,
    label: NOTIFICATION_DIGEST_TYPE_LABELS[NOTIFICATION_DIGEST_TYPE_EXECUTIVE],
    icon: NOTIFICATION_DIGEST_TYPE_ICONS[NOTIFICATION_DIGEST_TYPE_EXECUTIVE],
    color: NOTIFICATION_DIGEST_TYPE_COLORS[NOTIFICATION_DIGEST_TYPE_EXECUTIVE],
    priority: NOTIFICATION_DIGEST_TYPE_PRIORITY_VALUES[NOTIFICATION_DIGEST_TYPE_EXECUTIVE],
    group: NOTIFICATION_DIGEST_TYPE_TO_GROUP[NOTIFICATION_DIGEST_TYPE_EXECUTIVE],
    isFrequencyBased: false,
    isFormatBased: false,
    isSmart: false,
  },
];
