// ============================================
// নোটিফিকেশন টেমপ্লেট টাইপ সংক্রান্ত কনস্ট্যান্টসমূহ
// ============================================

// ============================================
// ১. টেমপ্লেট টাইপ
// ============================================

/**
 * নোটিফিকেশন টেমপ্লেট টাইপ
 * টেমপ্লেটটি কোন চ্যানেলের জন্য তৈরি
 */
export type NotificationTemplateType =
  | typeof NOTIFICATION_TEMPLATE_TYPE_EMAIL
  | typeof NOTIFICATION_TEMPLATE_TYPE_SMS
  | typeof NOTIFICATION_TEMPLATE_TYPE_PUSH
  | typeof NOTIFICATION_TEMPLATE_TYPE_IN_APP
  | typeof NOTIFICATION_TEMPLATE_TYPE_WEBHOOK
  | typeof NOTIFICATION_TEMPLATE_TYPE_SLACK
  | typeof NOTIFICATION_TEMPLATE_TYPE_TELEGRAM
  | typeof NOTIFICATION_TEMPLATE_TYPE_WHATSAPP
  | typeof NOTIFICATION_TEMPLATE_TYPE_SYSTEM
  | typeof NOTIFICATION_TEMPLATE_TYPE_CUSTOM
  | typeof NOTIFICATION_TEMPLATE_TYPE_VOICE
  | typeof NOTIFICATION_TEMPLATE_TYPE_DISCORD
  | typeof NOTIFICATION_TEMPLATE_TYPE_MESSENGER
  | typeof NOTIFICATION_TEMPLATE_TYPE_DATABASE;

/**
 * ইমেইল টেমপ্লেট
 * @description ইমেইল চ্যানেলের জন্য টেমপ্লেট
 */
export const NOTIFICATION_TEMPLATE_TYPE_EMAIL = 'EMAIL';

/**
 * এসএমএস টেমপ্লেট
 * @description এসএমএস চ্যানেলের জন্য টেমপ্লেট
 */
export const NOTIFICATION_TEMPLATE_TYPE_SMS = 'SMS';

/**
 * পুশ টেমপ্লেট
 * @description পুশ নোটিফিকেশন চ্যানেলের জন্য টেমপ্লেট
 */
export const NOTIFICATION_TEMPLATE_TYPE_PUSH = 'PUSH';

/**
 * ইন-অ্যাপ টেমপ্লেট
 * @description ইন-অ্যাপ নোটিফিকেশন চ্যানেলের জন্য টেমপ্লেট
 */
export const NOTIFICATION_TEMPLATE_TYPE_IN_APP = 'IN_APP';

/**
 * ওয়েবহুক টেমপ্লেট
 * @description ওয়েবহুক চ্যানেলের জন্য টেমপ্লেট
 */
export const NOTIFICATION_TEMPLATE_TYPE_WEBHOOK = 'WEBHOOK';

/**
 * স্ল্যাক টেমপ্লেট
 * @description স্ল্যাক চ্যানেলের জন্য টেমপ্লেট
 */
export const NOTIFICATION_TEMPLATE_TYPE_SLACK = 'SLACK';

/**
 * টেলিগ্রাম টেমপ্লেট
 * @description টেলিগ্রাম চ্যানেলের জন্য টেমপ্লেট
 */
export const NOTIFICATION_TEMPLATE_TYPE_TELEGRAM = 'TELEGRAM';

/**
 * হোয়াটসঅ্যাপ টেমপ্লেট
 * @description হোয়াটসঅ্যাপ চ্যানেলের জন্য টেমপ্লেট
 */
export const NOTIFICATION_TEMPLATE_TYPE_WHATSAPP = 'WHATSAPP';

/**
 * সিস্টেম টেমপ্লেট
 * @description সিস্টেম নোটিফিকেশনের জন্য টেমপ্লেট
 */
export const NOTIFICATION_TEMPLATE_TYPE_SYSTEM = 'SYSTEM';

/**
 * কাস্টম টেমপ্লেট
 * @description কাস্টমাইজড টেমপ্লেট
 */
export const NOTIFICATION_TEMPLATE_TYPE_CUSTOM = 'CUSTOM';

/**
 * ভয়েস টেমপ্লেট
 * @description ভয়েস কল চ্যানেলের জন্য টেমপ্লেট
 */
export const NOTIFICATION_TEMPLATE_TYPE_VOICE = 'VOICE';

/**
 * ডিসকর্ড টেমপ্লেট
 * @description ডিসকর্ড চ্যানেলের জন্য টেমপ্লেট
 */
export const NOTIFICATION_TEMPLATE_TYPE_DISCORD = 'DISCORD';

/**
 * মেসেঞ্জার টেমপ্লেট
 * @description মেসেঞ্জার চ্যানেলের জন্য টেমপ্লেট
 */
export const NOTIFICATION_TEMPLATE_TYPE_MESSENGER = 'MESSENGER';

/**
 * ডেটাবেস টেমপ্লেট
 * @description ডেটাবেস চ্যানেলের জন্য টেমপ্লেট
 */
export const NOTIFICATION_TEMPLATE_TYPE_DATABASE = 'DATABASE';

// ============================================
// ২. টেমপ্লেট টাইপ গ্রুপ
// ============================================

/**
 * টেমপ্লেট টাইপ গ্রুপ
 */
export type NotificationTemplateTypeGroup =
  | typeof NOTIFICATION_TEMPLATE_TYPE_GROUP_COMMUNICATION
  | typeof NOTIFICATION_TEMPLATE_TYPE_GROUP_MESSAGING
  | typeof NOTIFICATION_TEMPLATE_TYPE_GROUP_SYSTEM
  | typeof NOTIFICATION_TEMPLATE_TYPE_GROUP_SOCIAL
  | typeof NOTIFICATION_TEMPLATE_TYPE_GROUP_STORAGE;

/**
 * কমিউনিকেশন গ্রুপ
 * @description ঐতিহ্যবাহী যোগাযোগ মাধ্যম
 */
export const NOTIFICATION_TEMPLATE_TYPE_GROUP_COMMUNICATION = 'COMMUNICATION';

/**
 * মেসেজিং গ্রুপ
 * @description ইনস্ট্যান্ট মেসেজিং মাধ্যম
 */
export const NOTIFICATION_TEMPLATE_TYPE_GROUP_MESSAGING = 'MESSAGING';

/**
 * সিস্টেম গ্রুপ
 * @description সিস্টেম সংক্রান্ত টাইপ
 */
export const NOTIFICATION_TEMPLATE_TYPE_GROUP_SYSTEM = 'SYSTEM';

/**
 * সোশ্যাল গ্রুপ
 * @description সোশ্যাল মিডিয়া মাধ্যম
 */
export const NOTIFICATION_TEMPLATE_TYPE_GROUP_SOCIAL = 'SOCIAL';

/**
 * স্টোরেজ গ্রুপ
 * @description সংরক্ষণ মাধ্যম
 */
export const NOTIFICATION_TEMPLATE_TYPE_GROUP_STORAGE = 'STORAGE';

// ============================================
// ৩. টেমপ্লেট টাইপ থেকে গ্রুপ ম্যাপিং
// ============================================

/**
 * টেমপ্লেট টাইপ থেকে গ্রুপ ম্যাপিং
 */
export const NOTIFICATION_TEMPLATE_TYPE_TO_GROUP: Record<
  NotificationTemplateType,
  NotificationTemplateTypeGroup
> = {
  [NOTIFICATION_TEMPLATE_TYPE_EMAIL]: NOTIFICATION_TEMPLATE_TYPE_GROUP_COMMUNICATION,
  [NOTIFICATION_TEMPLATE_TYPE_SMS]: NOTIFICATION_TEMPLATE_TYPE_GROUP_COMMUNICATION,
  [NOTIFICATION_TEMPLATE_TYPE_PUSH]: NOTIFICATION_TEMPLATE_TYPE_GROUP_COMMUNICATION,
  [NOTIFICATION_TEMPLATE_TYPE_IN_APP]: NOTIFICATION_TEMPLATE_TYPE_GROUP_COMMUNICATION,
  [NOTIFICATION_TEMPLATE_TYPE_WEBHOOK]: NOTIFICATION_TEMPLATE_TYPE_GROUP_COMMUNICATION,
  [NOTIFICATION_TEMPLATE_TYPE_SLACK]: NOTIFICATION_TEMPLATE_TYPE_GROUP_MESSAGING,
  [NOTIFICATION_TEMPLATE_TYPE_TELEGRAM]: NOTIFICATION_TEMPLATE_TYPE_GROUP_MESSAGING,
  [NOTIFICATION_TEMPLATE_TYPE_WHATSAPP]: NOTIFICATION_TEMPLATE_TYPE_GROUP_MESSAGING,
  [NOTIFICATION_TEMPLATE_TYPE_SYSTEM]: NOTIFICATION_TEMPLATE_TYPE_GROUP_SYSTEM,
  [NOTIFICATION_TEMPLATE_TYPE_CUSTOM]: NOTIFICATION_TEMPLATE_TYPE_GROUP_SYSTEM,
  [NOTIFICATION_TEMPLATE_TYPE_VOICE]: NOTIFICATION_TEMPLATE_TYPE_GROUP_COMMUNICATION,
  [NOTIFICATION_TEMPLATE_TYPE_DISCORD]: NOTIFICATION_TEMPLATE_TYPE_GROUP_SOCIAL,
  [NOTIFICATION_TEMPLATE_TYPE_MESSENGER]: NOTIFICATION_TEMPLATE_TYPE_GROUP_SOCIAL,
  [NOTIFICATION_TEMPLATE_TYPE_DATABASE]: NOTIFICATION_TEMPLATE_TYPE_GROUP_STORAGE,
};

// ============================================
// ৪. টেমপ্লেট টাইপ লেবেল
// ============================================

/**
 * টেমপ্লেট টাইপ লেবেল
 */
export const NOTIFICATION_TEMPLATE_TYPE_LABELS: Record<NotificationTemplateType, string> = {
  [NOTIFICATION_TEMPLATE_TYPE_EMAIL]: 'ইমেইল',
  [NOTIFICATION_TEMPLATE_TYPE_SMS]: 'এসএমএস',
  [NOTIFICATION_TEMPLATE_TYPE_PUSH]: 'পুশ নোটিফিকেশন',
  [NOTIFICATION_TEMPLATE_TYPE_IN_APP]: 'ইন-অ্যাপ',
  [NOTIFICATION_TEMPLATE_TYPE_WEBHOOK]: 'ওয়েবহুক',
  [NOTIFICATION_TEMPLATE_TYPE_SLACK]: 'স্ল্যাক',
  [NOTIFICATION_TEMPLATE_TYPE_TELEGRAM]: 'টেলিগ্রাম',
  [NOTIFICATION_TEMPLATE_TYPE_WHATSAPP]: 'হোয়াটসঅ্যাপ',
  [NOTIFICATION_TEMPLATE_TYPE_SYSTEM]: 'সিস্টেম',
  [NOTIFICATION_TEMPLATE_TYPE_CUSTOM]: 'কাস্টম',
  [NOTIFICATION_TEMPLATE_TYPE_VOICE]: 'ভয়েস',
  [NOTIFICATION_TEMPLATE_TYPE_DISCORD]: 'ডিসকর্ড',
  [NOTIFICATION_TEMPLATE_TYPE_MESSENGER]: 'মেসেঞ্জার',
  [NOTIFICATION_TEMPLATE_TYPE_DATABASE]: 'ডেটাবেস',
};

// ============================================
// ৫. টেমপ্লেট টাইপ আইকন
// ============================================

/**
 * টেমপ্লেট টাইপ আইকন
 */
export const NOTIFICATION_TEMPLATE_TYPE_ICONS: Record<NotificationTemplateType, string> = {
  [NOTIFICATION_TEMPLATE_TYPE_EMAIL]: 'email',
  [NOTIFICATION_TEMPLATE_TYPE_SMS]: 'sms',
  [NOTIFICATION_TEMPLATE_TYPE_PUSH]: 'notifications',
  [NOTIFICATION_TEMPLATE_TYPE_IN_APP]: 'inbox',
  [NOTIFICATION_TEMPLATE_TYPE_WEBHOOK]: 'webhook',
  [NOTIFICATION_TEMPLATE_TYPE_SLACK]: 'slack',
  [NOTIFICATION_TEMPLATE_TYPE_TELEGRAM]: 'telegram',
  [NOTIFICATION_TEMPLATE_TYPE_WHATSAPP]: 'whatsapp',
  [NOTIFICATION_TEMPLATE_TYPE_SYSTEM]: 'system_update',
  [NOTIFICATION_TEMPLATE_TYPE_CUSTOM]: 'custom',
  [NOTIFICATION_TEMPLATE_TYPE_VOICE]: 'phone',
  [NOTIFICATION_TEMPLATE_TYPE_DISCORD]: 'discord',
  [NOTIFICATION_TEMPLATE_TYPE_MESSENGER]: 'messenger',
  [NOTIFICATION_TEMPLATE_TYPE_DATABASE]: 'database',
};

// ============================================
// ৬. টেমপ্লেট টাইপ কালার
// ============================================

/**
 * টেমপ্লেট টাইপ কালার
 */
export const NOTIFICATION_TEMPLATE_TYPE_COLORS: Record<NotificationTemplateType, string> = {
  [NOTIFICATION_TEMPLATE_TYPE_EMAIL]: '#D44638', // Gmail Red
  [NOTIFICATION_TEMPLATE_TYPE_SMS]: '#34B7F1', // SMS Blue
  [NOTIFICATION_TEMPLATE_TYPE_PUSH]: '#FF6B6B', // Push Red
  [NOTIFICATION_TEMPLATE_TYPE_IN_APP]: '#4CAF50', // Green
  [NOTIFICATION_TEMPLATE_TYPE_WEBHOOK]: '#FF9800', // Orange
  [NOTIFICATION_TEMPLATE_TYPE_SLACK]: '#4A154B', // Slack Purple
  [NOTIFICATION_TEMPLATE_TYPE_TELEGRAM]: '#0088CC', // Telegram Blue
  [NOTIFICATION_TEMPLATE_TYPE_WHATSAPP]: '#25D366', // WhatsApp Green
  [NOTIFICATION_TEMPLATE_TYPE_SYSTEM]: '#2196F3', // Blue
  [NOTIFICATION_TEMPLATE_TYPE_CUSTOM]: '#9C27B0', // Purple
  [NOTIFICATION_TEMPLATE_TYPE_VOICE]: '#9C27B0', // Purple
  [NOTIFICATION_TEMPLATE_TYPE_DISCORD]: '#5865F2', // Discord Blue
  [NOTIFICATION_TEMPLATE_TYPE_MESSENGER]: '#00B2FF', // Messenger Blue
  [NOTIFICATION_TEMPLATE_TYPE_DATABASE]: '#607D8B', // Blue Grey
};

// ============================================
// ৭. টেমপ্লেট টাইপ প্রায়োরিটি
// ============================================

/**
 * টেমপ্লেট টাইপ প্রায়োরিটি (১-১০)
 */
export const NOTIFICATION_TEMPLATE_TYPE_PRIORITY: Record<NotificationTemplateType, number> = {
  [NOTIFICATION_TEMPLATE_TYPE_EMAIL]: 5,
  [NOTIFICATION_TEMPLATE_TYPE_SMS]: 8,
  [NOTIFICATION_TEMPLATE_TYPE_PUSH]: 7,
  [NOTIFICATION_TEMPLATE_TYPE_IN_APP]: 6,
  [NOTIFICATION_TEMPLATE_TYPE_WEBHOOK]: 4,
  [NOTIFICATION_TEMPLATE_TYPE_SLACK]: 5,
  [NOTIFICATION_TEMPLATE_TYPE_TELEGRAM]: 5,
  [NOTIFICATION_TEMPLATE_TYPE_WHATSAPP]: 7,
  [NOTIFICATION_TEMPLATE_TYPE_SYSTEM]: 9,
  [NOTIFICATION_TEMPLATE_TYPE_CUSTOM]: 5,
  [NOTIFICATION_TEMPLATE_TYPE_VOICE]: 8,
  [NOTIFICATION_TEMPLATE_TYPE_DISCORD]: 4,
  [NOTIFICATION_TEMPLATE_TYPE_MESSENGER]: 6,
  [NOTIFICATION_TEMPLATE_TYPE_DATABASE]: 3,
};

// ============================================
// ৮. টেমপ্লেট টাইপ কনফিগারেশন
// ============================================

/**
 * টেমপ্লেট টাইপ কনফিগারেশন
 */
export interface NotificationTemplateTypeConfig {
  /** টাইপের নাম */
  type: NotificationTemplateType;
  /** টাইপের লেবেল */
  label: string;
  /** টাইপের আইকন */
  icon: string;
  /** টাইপের কালার */
  color: string;
  /** টাইপের প্রায়োরিটি */
  priority: number;
  /** টাইপের গ্রুপ */
  group: NotificationTemplateTypeGroup;
}

/**
 * সব টেমপ্লেট টাইপের কনফিগারেশন
 */
export const NOTIFICATION_TEMPLATE_TYPE_CONFIGS: NotificationTemplateTypeConfig[] = [
  {
    type: NOTIFICATION_TEMPLATE_TYPE_EMAIL,
    label: NOTIFICATION_TEMPLATE_TYPE_LABELS[NOTIFICATION_TEMPLATE_TYPE_EMAIL],
    icon: NOTIFICATION_TEMPLATE_TYPE_ICONS[NOTIFICATION_TEMPLATE_TYPE_EMAIL],
    color: NOTIFICATION_TEMPLATE_TYPE_COLORS[NOTIFICATION_TEMPLATE_TYPE_EMAIL],
    priority: NOTIFICATION_TEMPLATE_TYPE_PRIORITY[NOTIFICATION_TEMPLATE_TYPE_EMAIL],
    group: NOTIFICATION_TEMPLATE_TYPE_TO_GROUP[NOTIFICATION_TEMPLATE_TYPE_EMAIL],
  },
  {
    type: NOTIFICATION_TEMPLATE_TYPE_SMS,
    label: NOTIFICATION_TEMPLATE_TYPE_LABELS[NOTIFICATION_TEMPLATE_TYPE_SMS],
    icon: NOTIFICATION_TEMPLATE_TYPE_ICONS[NOTIFICATION_TEMPLATE_TYPE_SMS],
    color: NOTIFICATION_TEMPLATE_TYPE_COLORS[NOTIFICATION_TEMPLATE_TYPE_SMS],
    priority: NOTIFICATION_TEMPLATE_TYPE_PRIORITY[NOTIFICATION_TEMPLATE_TYPE_SMS],
    group: NOTIFICATION_TEMPLATE_TYPE_TO_GROUP[NOTIFICATION_TEMPLATE_TYPE_SMS],
  },
  {
    type: NOTIFICATION_TEMPLATE_TYPE_PUSH,
    label: NOTIFICATION_TEMPLATE_TYPE_LABELS[NOTIFICATION_TEMPLATE_TYPE_PUSH],
    icon: NOTIFICATION_TEMPLATE_TYPE_ICONS[NOTIFICATION_TEMPLATE_TYPE_PUSH],
    color: NOTIFICATION_TEMPLATE_TYPE_COLORS[NOTIFICATION_TEMPLATE_TYPE_PUSH],
    priority: NOTIFICATION_TEMPLATE_TYPE_PRIORITY[NOTIFICATION_TEMPLATE_TYPE_PUSH],
    group: NOTIFICATION_TEMPLATE_TYPE_TO_GROUP[NOTIFICATION_TEMPLATE_TYPE_PUSH],
  },
  {
    type: NOTIFICATION_TEMPLATE_TYPE_IN_APP,
    label: NOTIFICATION_TEMPLATE_TYPE_LABELS[NOTIFICATION_TEMPLATE_TYPE_IN_APP],
    icon: NOTIFICATION_TEMPLATE_TYPE_ICONS[NOTIFICATION_TEMPLATE_TYPE_IN_APP],
    color: NOTIFICATION_TEMPLATE_TYPE_COLORS[NOTIFICATION_TEMPLATE_TYPE_IN_APP],
    priority: NOTIFICATION_TEMPLATE_TYPE_PRIORITY[NOTIFICATION_TEMPLATE_TYPE_IN_APP],
    group: NOTIFICATION_TEMPLATE_TYPE_TO_GROUP[NOTIFICATION_TEMPLATE_TYPE_IN_APP],
  },
  {
    type: NOTIFICATION_TEMPLATE_TYPE_WEBHOOK,
    label: NOTIFICATION_TEMPLATE_TYPE_LABELS[NOTIFICATION_TEMPLATE_TYPE_WEBHOOK],
    icon: NOTIFICATION_TEMPLATE_TYPE_ICONS[NOTIFICATION_TEMPLATE_TYPE_WEBHOOK],
    color: NOTIFICATION_TEMPLATE_TYPE_COLORS[NOTIFICATION_TEMPLATE_TYPE_WEBHOOK],
    priority: NOTIFICATION_TEMPLATE_TYPE_PRIORITY[NOTIFICATION_TEMPLATE_TYPE_WEBHOOK],
    group: NOTIFICATION_TEMPLATE_TYPE_TO_GROUP[NOTIFICATION_TEMPLATE_TYPE_WEBHOOK],
  },
  {
    type: NOTIFICATION_TEMPLATE_TYPE_SLACK,
    label: NOTIFICATION_TEMPLATE_TYPE_LABELS[NOTIFICATION_TEMPLATE_TYPE_SLACK],
    icon: NOTIFICATION_TEMPLATE_TYPE_ICONS[NOTIFICATION_TEMPLATE_TYPE_SLACK],
    color: NOTIFICATION_TEMPLATE_TYPE_COLORS[NOTIFICATION_TEMPLATE_TYPE_SLACK],
    priority: NOTIFICATION_TEMPLATE_TYPE_PRIORITY[NOTIFICATION_TEMPLATE_TYPE_SLACK],
    group: NOTIFICATION_TEMPLATE_TYPE_TO_GROUP[NOTIFICATION_TEMPLATE_TYPE_SLACK],
  },
  {
    type: NOTIFICATION_TEMPLATE_TYPE_TELEGRAM,
    label: NOTIFICATION_TEMPLATE_TYPE_LABELS[NOTIFICATION_TEMPLATE_TYPE_TELEGRAM],
    icon: NOTIFICATION_TEMPLATE_TYPE_ICONS[NOTIFICATION_TEMPLATE_TYPE_TELEGRAM],
    color: NOTIFICATION_TEMPLATE_TYPE_COLORS[NOTIFICATION_TEMPLATE_TYPE_TELEGRAM],
    priority: NOTIFICATION_TEMPLATE_TYPE_PRIORITY[NOTIFICATION_TEMPLATE_TYPE_TELEGRAM],
    group: NOTIFICATION_TEMPLATE_TYPE_TO_GROUP[NOTIFICATION_TEMPLATE_TYPE_TELEGRAM],
  },
  {
    type: NOTIFICATION_TEMPLATE_TYPE_WHATSAPP,
    label: NOTIFICATION_TEMPLATE_TYPE_LABELS[NOTIFICATION_TEMPLATE_TYPE_WHATSAPP],
    icon: NOTIFICATION_TEMPLATE_TYPE_ICONS[NOTIFICATION_TEMPLATE_TYPE_WHATSAPP],
    color: NOTIFICATION_TEMPLATE_TYPE_COLORS[NOTIFICATION_TEMPLATE_TYPE_WHATSAPP],
    priority: NOTIFICATION_TEMPLATE_TYPE_PRIORITY[NOTIFICATION_TEMPLATE_TYPE_WHATSAPP],
    group: NOTIFICATION_TEMPLATE_TYPE_TO_GROUP[NOTIFICATION_TEMPLATE_TYPE_WHATSAPP],
  },
  {
    type: NOTIFICATION_TEMPLATE_TYPE_SYSTEM,
    label: NOTIFICATION_TEMPLATE_TYPE_LABELS[NOTIFICATION_TEMPLATE_TYPE_SYSTEM],
    icon: NOTIFICATION_TEMPLATE_TYPE_ICONS[NOTIFICATION_TEMPLATE_TYPE_SYSTEM],
    color: NOTIFICATION_TEMPLATE_TYPE_COLORS[NOTIFICATION_TEMPLATE_TYPE_SYSTEM],
    priority: NOTIFICATION_TEMPLATE_TYPE_PRIORITY[NOTIFICATION_TEMPLATE_TYPE_SYSTEM],
    group: NOTIFICATION_TEMPLATE_TYPE_TO_GROUP[NOTIFICATION_TEMPLATE_TYPE_SYSTEM],
  },
  {
    type: NOTIFICATION_TEMPLATE_TYPE_CUSTOM,
    label: NOTIFICATION_TEMPLATE_TYPE_LABELS[NOTIFICATION_TEMPLATE_TYPE_CUSTOM],
    icon: NOTIFICATION_TEMPLATE_TYPE_ICONS[NOTIFICATION_TEMPLATE_TYPE_CUSTOM],
    color: NOTIFICATION_TEMPLATE_TYPE_COLORS[NOTIFICATION_TEMPLATE_TYPE_CUSTOM],
    priority: NOTIFICATION_TEMPLATE_TYPE_PRIORITY[NOTIFICATION_TEMPLATE_TYPE_CUSTOM],
    group: NOTIFICATION_TEMPLATE_TYPE_TO_GROUP[NOTIFICATION_TEMPLATE_TYPE_CUSTOM],
  },
  {
    type: NOTIFICATION_TEMPLATE_TYPE_VOICE,
    label: NOTIFICATION_TEMPLATE_TYPE_LABELS[NOTIFICATION_TEMPLATE_TYPE_VOICE],
    icon: NOTIFICATION_TEMPLATE_TYPE_ICONS[NOTIFICATION_TEMPLATE_TYPE_VOICE],
    color: NOTIFICATION_TEMPLATE_TYPE_COLORS[NOTIFICATION_TEMPLATE_TYPE_VOICE],
    priority: NOTIFICATION_TEMPLATE_TYPE_PRIORITY[NOTIFICATION_TEMPLATE_TYPE_VOICE],
    group: NOTIFICATION_TEMPLATE_TYPE_TO_GROUP[NOTIFICATION_TEMPLATE_TYPE_VOICE],
  },
  {
    type: NOTIFICATION_TEMPLATE_TYPE_DISCORD,
    label: NOTIFICATION_TEMPLATE_TYPE_LABELS[NOTIFICATION_TEMPLATE_TYPE_DISCORD],
    icon: NOTIFICATION_TEMPLATE_TYPE_ICONS[NOTIFICATION_TEMPLATE_TYPE_DISCORD],
    color: NOTIFICATION_TEMPLATE_TYPE_COLORS[NOTIFICATION_TEMPLATE_TYPE_DISCORD],
    priority: NOTIFICATION_TEMPLATE_TYPE_PRIORITY[NOTIFICATION_TEMPLATE_TYPE_DISCORD],
    group: NOTIFICATION_TEMPLATE_TYPE_TO_GROUP[NOTIFICATION_TEMPLATE_TYPE_DISCORD],
  },
  {
    type: NOTIFICATION_TEMPLATE_TYPE_MESSENGER,
    label: NOTIFICATION_TEMPLATE_TYPE_LABELS[NOTIFICATION_TEMPLATE_TYPE_MESSENGER],
    icon: NOTIFICATION_TEMPLATE_TYPE_ICONS[NOTIFICATION_TEMPLATE_TYPE_MESSENGER],
    color: NOTIFICATION_TEMPLATE_TYPE_COLORS[NOTIFICATION_TEMPLATE_TYPE_MESSENGER],
    priority: NOTIFICATION_TEMPLATE_TYPE_PRIORITY[NOTIFICATION_TEMPLATE_TYPE_MESSENGER],
    group: NOTIFICATION_TEMPLATE_TYPE_TO_GROUP[NOTIFICATION_TEMPLATE_TYPE_MESSENGER],
  },
  {
    type: NOTIFICATION_TEMPLATE_TYPE_DATABASE,
    label: NOTIFICATION_TEMPLATE_TYPE_LABELS[NOTIFICATION_TEMPLATE_TYPE_DATABASE],
    icon: NOTIFICATION_TEMPLATE_TYPE_ICONS[NOTIFICATION_TEMPLATE_TYPE_DATABASE],
    color: NOTIFICATION_TEMPLATE_TYPE_COLORS[NOTIFICATION_TEMPLATE_TYPE_DATABASE],
    priority: NOTIFICATION_TEMPLATE_TYPE_PRIORITY[NOTIFICATION_TEMPLATE_TYPE_DATABASE],
    group: NOTIFICATION_TEMPLATE_TYPE_TO_GROUP[NOTIFICATION_TEMPLATE_TYPE_DATABASE],
  },
];
