/**
 * AI Model Constants
 * Configuration for AI models, versions, and capabilities
 */

export const AI_MODEL = {
  // Model Versions
  VERSIONS: {
    GPT_3_5: 'gpt-3.5-turbo',
    GPT_3_5_16K: 'gpt-3.5-turbo-16k',
    GPT_4: 'gpt-4',
    GPT_4_32K: 'gpt-4-32k',
    GPT_4_TURBO: 'gpt-4-turbo-preview',
    GPT_4_VISION: 'gpt-4-vision-preview',
    GPT_4O: 'gpt-4o',
    GPT_4O_MINI: 'gpt-4o-mini',
    CLAUDE_3_OPUS: 'claude-3-opus-20240229',
    CLAUDE_3_SONNET: 'claude-3-sonnet-20240229',
    CLAUDE_3_HAIKU: 'claude-3-haiku-20240307',
    CLAUDE_3_5_SONNET: 'claude-3-5-sonnet-20240620',
    LLAMA_2_7B: 'llama-2-7b',
    LLAMA_2_13B: 'llama-2-13b',
    LLAMA_2_70B: 'llama-2-70b',
    LLAMA_3_8B: 'llama-3-8b',
    LLAMA_3_70B: 'llama-3-70b',
    MISTRAL_7B: 'mistral-7b',
    MISTRAL_8X7B: 'mistral-8x7b',
    MISTRAL_LARGE: 'mistral-large',
    GEMINI_PRO: 'gemini-pro',
    GEMINI_PRO_VISION: 'gemini-pro-vision',
    GEMINI_ULTRA: 'gemini-ultra',
    BERT_BASE: 'bert-base-uncased',
    BERT_LARGE: 'bert-large-uncased',
    PALM_2: 'palm-2',
    PALM_2_CHAT: 'palm-2-chat',
    DEEPSEEK_V2: 'deepseek-v2',
    DEEPSEEK_V3: 'deepseek-v3',
    GROQ_LLAMA_3_70B: 'groq-llama-3-70b',
    GROQ_LLAMA_3_8B: 'groq-llama-3-8b',
    GROQ_MIXTRAL_8X7B: 'groq-mixtral-8x7b',
  } as const,

  // Model Capabilities
  CAPABILITIES: {
    TEXT_GENERATION: 'text_generation',
    CHAT: 'chat',
    VISION: 'vision',
    EMBEDDINGS: 'embeddings',
    MODERATION: 'moderation',
    IMAGE_GENERATION: 'image_generation',
    SPEECH_TO_TEXT: 'speech_to_text',
    TEXT_TO_SPEECH: 'text_to_speech',
    TRANSLATION: 'translation',
    SUMMARIZATION: 'summarization',
    QUESTION_ANSWERING: 'question_answering',
    CODE_GENERATION: 'code_generation',
    LOGIC_REASONING: 'logic_reasoning',
    MATH: 'math',
    AGENT: 'agent',
    TOOL_USE: 'tool_use',
    FUNCTION_CALLING: 'function_calling',
    JSON_MODE: 'json_mode',
    STREAMING: 'streaming',
  } as const,

  // Model Size Categories
  SIZES: {
    TINY: 'tiny',
    SMALL: 'small',
    MEDIUM: 'medium',
    LARGE: 'large',
    XLARGE: 'xlarge',
    XXLARGE: 'xxlarge',
  } as const,

  // Model Performance Tiers
  PERFORMANCE_TIERS: {
    FREE: 'free',
    BASIC: 'basic',
    STANDARD: 'standard',
    PREMIUM: 'premium',
    ENTERPRISE: 'enterprise',
  } as const,

  // Model Context Windows (in tokens)
  CONTEXT_WINDOWS: {
    GPT_3_5: 4096,
    GPT_3_5_16K: 16384,
    GPT_4: 8192,
    GPT_4_32K: 32768,
    GPT_4_TURBO: 128000,
    GPT_4O: 128000,
    GPT_4O_MINI: 128000,
    CLAUDE_3_OPUS: 200000,
    CLAUDE_3_SONNET: 200000,
    CLAUDE_3_HAIKU: 200000,
    CLAUDE_3_5_SONNET: 200000,
    LLAMA_2_7B: 4096,
    LLAMA_2_13B: 4096,
    LLAMA_2_70B: 4096,
    LLAMA_3_8B: 8192,
    LLAMA_3_70B: 8192,
    MISTRAL_7B: 8192,
    MISTRAL_8X7B: 32768,
    MISTRAL_LARGE: 32768,
    GEMINI_PRO: 32768,
    GEMINI_PRO_VISION: 32768,
    GEMINI_ULTRA: 32768,
    BERT_BASE: 512,
    BERT_LARGE: 512,
    PALM_2: 8192,
    PALM_2_CHAT: 8192,
    DEEPSEEK_V2: 32768,
    DEEPSEEK_V3: 32768,
    GROQ_LLAMA_3_70B: 8192,
    GROQ_LLAMA_3_8B: 8192,
    GROQ_MIXTRAL_8X7B: 32768,
  } as const,

  // Model Costs (per 1000 tokens)
  COSTS: {
    GPT_3_5: {
      input: 0.0015,
      output: 0.002,
    },
    GPT_3_5_16K: {
      input: 0.003,
      output: 0.004,
    },
    GPT_4: {
      input: 0.03,
      output: 0.06,
    },
    GPT_4_32K: {
      input: 0.06,
      output: 0.12,
    },
    GPT_4_TURBO: {
      input: 0.01,
      output: 0.03,
    },
    GPT_4O: {
      input: 0.005,
      output: 0.015,
    },
    GPT_4O_MINI: {
      input: 0.00015,
      output: 0.0006,
    },
    CLAUDE_3_OPUS: {
      input: 0.015,
      output: 0.075,
    },
    CLAUDE_3_SONNET: {
      input: 0.003,
      output: 0.015,
    },
    CLAUDE_3_HAIKU: {
      input: 0.00025,
      output: 0.00125,
    },
    CLAUDE_3_5_SONNET: {
      input: 0.003,
      output: 0.015,
    },
    LLAMA_2_7B: {
      input: 0.0002,
      output: 0.0006,
    },
    LLAMA_2_13B: {
      input: 0.0004,
      output: 0.0012,
    },
    LLAMA_2_70B: {
      input: 0.001,
      output: 0.003,
    },
    LLAMA_3_8B: {
      input: 0.0002,
      output: 0.0006,
    },
    LLAMA_3_70B: {
      input: 0.001,
      output: 0.003,
    },
    MISTRAL_7B: {
      input: 0.0002,
      output: 0.0006,
    },
    MISTRAL_8X7B: {
      input: 0.0007,
      output: 0.0021,
    },
    MISTRAL_LARGE: {
      input: 0.008,
      output: 0.024,
    },
    GEMINI_PRO: {
      input: 0.0005,
      output: 0.0015,
    },
    GEMINI_PRO_VISION: {
      input: 0.0005,
      output: 0.0015,
    },
    GEMINI_ULTRA: {
      input: 0.005,
      output: 0.015,
    },
    DEEPSEEK_V2: {
      input: 0.00014,
      output: 0.00028,
    },
    DEEPSEEK_V3: {
      input: 0.00014,
      output: 0.00028,
    },
    GROQ_LLAMA_3_70B: {
      input: 0.00059,
      output: 0.00079,
    },
    GROQ_LLAMA_3_8B: {
      input: 0.00009,
      output: 0.00009,
    },
    GROQ_MIXTRAL_8X7B: {
      input: 0.00024,
      output: 0.00024,
    },
  } as const,

  // Model Limits
  LIMITS: {
    MAX_TOKENS: {
      GPT_3_5: 4096,
      GPT_4: 8192,
      GPT_4_TURBO: 4096,
      GPT_4O: 4096,
      CLAUDE_3: 4096,
      LLAMA_2: 4096,
      LLAMA_3: 4096,
      MISTRAL: 4096,
      GEMINI: 4096,
      DEFAULT: 2048,
    },
    MAX_REQUESTS_PER_MINUTE: 60,
    MAX_REQUESTS_PER_DAY: 10000,
    MAX_BATCH_SIZE: 100,
    MAX_RETRIES: 3,
  } as const,

  // Model Quality Levels
  QUALITY: {
    FAST: 'fast',
    BALANCED: 'balanced',
    ACCURATE: 'accurate',
    PREMIUM: 'premium',
  } as const,
} as const;

// Model Versions
export type AIModelVersion = (typeof AI_MODEL.VERSIONS)[keyof typeof AI_MODEL.VERSIONS];

// Model Capabilities
export type AIModelCapability = (typeof AI_MODEL.CAPABILITIES)[keyof typeof AI_MODEL.CAPABILITIES];

// Model Sizes
export type AIModelSize = (typeof AI_MODEL.SIZES)[keyof typeof AI_MODEL.SIZES];

// Performance Tiers
export type AIPerformanceTier =
  (typeof AI_MODEL.PERFORMANCE_TIERS)[keyof typeof AI_MODEL.PERFORMANCE_TIERS];

// Context Windows
export type AIContextWindow =
  (typeof AI_MODEL.CONTEXT_WINDOWS)[keyof typeof AI_MODEL.CONTEXT_WINDOWS];

// Model Costs
export type AIModelCost = (typeof AI_MODEL.COSTS)[keyof typeof AI_MODEL.COSTS];

// Quality Levels
export type AIModelQuality = (typeof AI_MODEL.QUALITY)[keyof typeof AI_MODEL.QUALITY];

// Utility Functions
export function getContextWindow(modelVersion: AIModelVersion): number {
  const windows: Partial<Record<AIModelVersion, number>> = {
    [AI_MODEL.VERSIONS.GPT_3_5]: AI_MODEL.CONTEXT_WINDOWS.GPT_3_5,
    [AI_MODEL.VERSIONS.GPT_3_5_16K]: AI_MODEL.CONTEXT_WINDOWS.GPT_3_5_16K,
    [AI_MODEL.VERSIONS.GPT_4]: AI_MODEL.CONTEXT_WINDOWS.GPT_4,
    [AI_MODEL.VERSIONS.GPT_4_32K]: AI_MODEL.CONTEXT_WINDOWS.GPT_4_32K,
    [AI_MODEL.VERSIONS.GPT_4_TURBO]: AI_MODEL.CONTEXT_WINDOWS.GPT_4_TURBO,
    [AI_MODEL.VERSIONS.GPT_4O]: AI_MODEL.CONTEXT_WINDOWS.GPT_4O,
    [AI_MODEL.VERSIONS.GPT_4O_MINI]: AI_MODEL.CONTEXT_WINDOWS.GPT_4O_MINI,
    [AI_MODEL.VERSIONS.CLAUDE_3_OPUS]: AI_MODEL.CONTEXT_WINDOWS.CLAUDE_3_OPUS,
    [AI_MODEL.VERSIONS.CLAUDE_3_SONNET]: AI_MODEL.CONTEXT_WINDOWS.CLAUDE_3_SONNET,
    [AI_MODEL.VERSIONS.CLAUDE_3_HAIKU]: AI_MODEL.CONTEXT_WINDOWS.CLAUDE_3_HAIKU,
    [AI_MODEL.VERSIONS.CLAUDE_3_5_SONNET]: AI_MODEL.CONTEXT_WINDOWS.CLAUDE_3_5_SONNET,
    [AI_MODEL.VERSIONS.LLAMA_2_7B]: AI_MODEL.CONTEXT_WINDOWS.LLAMA_2_7B,
    [AI_MODEL.VERSIONS.LLAMA_2_13B]: AI_MODEL.CONTEXT_WINDOWS.LLAMA_2_13B,
    [AI_MODEL.VERSIONS.LLAMA_2_70B]: AI_MODEL.CONTEXT_WINDOWS.LLAMA_2_70B,
    [AI_MODEL.VERSIONS.LLAMA_3_8B]: AI_MODEL.CONTEXT_WINDOWS.LLAMA_3_8B,
    [AI_MODEL.VERSIONS.LLAMA_3_70B]: AI_MODEL.CONTEXT_WINDOWS.LLAMA_3_70B,
    [AI_MODEL.VERSIONS.MISTRAL_7B]: AI_MODEL.CONTEXT_WINDOWS.MISTRAL_7B,
    [AI_MODEL.VERSIONS.MISTRAL_8X7B]: AI_MODEL.CONTEXT_WINDOWS.MISTRAL_8X7B,
    [AI_MODEL.VERSIONS.MISTRAL_LARGE]: AI_MODEL.CONTEXT_WINDOWS.MISTRAL_LARGE,
    [AI_MODEL.VERSIONS.GEMINI_PRO]: AI_MODEL.CONTEXT_WINDOWS.GEMINI_PRO,
    [AI_MODEL.VERSIONS.GEMINI_PRO_VISION]: AI_MODEL.CONTEXT_WINDOWS.GEMINI_PRO_VISION,
    [AI_MODEL.VERSIONS.GEMINI_ULTRA]: AI_MODEL.CONTEXT_WINDOWS.GEMINI_ULTRA,
    [AI_MODEL.VERSIONS.BERT_BASE]: AI_MODEL.CONTEXT_WINDOWS.BERT_BASE,
    [AI_MODEL.VERSIONS.BERT_LARGE]: AI_MODEL.CONTEXT_WINDOWS.BERT_LARGE,
    [AI_MODEL.VERSIONS.PALM_2]: AI_MODEL.CONTEXT_WINDOWS.PALM_2,
    [AI_MODEL.VERSIONS.PALM_2_CHAT]: AI_MODEL.CONTEXT_WINDOWS.PALM_2_CHAT,
    [AI_MODEL.VERSIONS.DEEPSEEK_V2]: AI_MODEL.CONTEXT_WINDOWS.DEEPSEEK_V2,
    [AI_MODEL.VERSIONS.DEEPSEEK_V3]: AI_MODEL.CONTEXT_WINDOWS.DEEPSEEK_V3,
    [AI_MODEL.VERSIONS.GROQ_LLAMA_3_70B]: AI_MODEL.CONTEXT_WINDOWS.GROQ_LLAMA_3_70B,
    [AI_MODEL.VERSIONS.GROQ_LLAMA_3_8B]: AI_MODEL.CONTEXT_WINDOWS.GROQ_LLAMA_3_8B,
    [AI_MODEL.VERSIONS.GROQ_MIXTRAL_8X7B]: AI_MODEL.CONTEXT_WINDOWS.GROQ_MIXTRAL_8X7B,
  };
  return windows[modelVersion] || AI_MODEL.LIMITS.MAX_TOKENS.DEFAULT;
}

export function getModelCost(
  modelVersion: AIModelVersion
): (typeof AI_MODEL.COSTS)[keyof typeof AI_MODEL.COSTS] {
  const costs: Partial<
    Record<AIModelVersion, (typeof AI_MODEL.COSTS)[keyof typeof AI_MODEL.COSTS]>
  > = {
    [AI_MODEL.VERSIONS.GPT_3_5]: AI_MODEL.COSTS.GPT_3_5,
    [AI_MODEL.VERSIONS.GPT_3_5_16K]: AI_MODEL.COSTS.GPT_3_5_16K,
    [AI_MODEL.VERSIONS.GPT_4]: AI_MODEL.COSTS.GPT_4,
    [AI_MODEL.VERSIONS.GPT_4_32K]: AI_MODEL.COSTS.GPT_4_32K,
    [AI_MODEL.VERSIONS.GPT_4_TURBO]: AI_MODEL.COSTS.GPT_4_TURBO,
    [AI_MODEL.VERSIONS.GPT_4O]: AI_MODEL.COSTS.GPT_4O,
    [AI_MODEL.VERSIONS.GPT_4O_MINI]: AI_MODEL.COSTS.GPT_4O_MINI,
    [AI_MODEL.VERSIONS.CLAUDE_3_OPUS]: AI_MODEL.COSTS.CLAUDE_3_OPUS,
    [AI_MODEL.VERSIONS.CLAUDE_3_SONNET]: AI_MODEL.COSTS.CLAUDE_3_SONNET,
    [AI_MODEL.VERSIONS.CLAUDE_3_HAIKU]: AI_MODEL.COSTS.CLAUDE_3_HAIKU,
    [AI_MODEL.VERSIONS.CLAUDE_3_5_SONNET]: AI_MODEL.COSTS.CLAUDE_3_5_SONNET,
    [AI_MODEL.VERSIONS.LLAMA_2_7B]: AI_MODEL.COSTS.LLAMA_2_7B,
    [AI_MODEL.VERSIONS.LLAMA_2_13B]: AI_MODEL.COSTS.LLAMA_2_13B,
    [AI_MODEL.VERSIONS.LLAMA_2_70B]: AI_MODEL.COSTS.LLAMA_2_70B,
    [AI_MODEL.VERSIONS.LLAMA_3_8B]: AI_MODEL.COSTS.LLAMA_3_8B,
    [AI_MODEL.VERSIONS.LLAMA_3_70B]: AI_MODEL.COSTS.LLAMA_3_70B,
    [AI_MODEL.VERSIONS.MISTRAL_7B]: AI_MODEL.COSTS.MISTRAL_7B,
    [AI_MODEL.VERSIONS.MISTRAL_8X7B]: AI_MODEL.COSTS.MISTRAL_8X7B,
    [AI_MODEL.VERSIONS.MISTRAL_LARGE]: AI_MODEL.COSTS.MISTRAL_LARGE,
    [AI_MODEL.VERSIONS.GEMINI_PRO]: AI_MODEL.COSTS.GEMINI_PRO,
    [AI_MODEL.VERSIONS.GEMINI_PRO_VISION]: AI_MODEL.COSTS.GEMINI_PRO_VISION,
    [AI_MODEL.VERSIONS.GEMINI_ULTRA]: AI_MODEL.COSTS.GEMINI_ULTRA,
    [AI_MODEL.VERSIONS.DEEPSEEK_V2]: AI_MODEL.COSTS.DEEPSEEK_V2,
    [AI_MODEL.VERSIONS.DEEPSEEK_V3]: AI_MODEL.COSTS.DEEPSEEK_V3,
    [AI_MODEL.VERSIONS.GROQ_LLAMA_3_70B]: AI_MODEL.COSTS.GROQ_LLAMA_3_70B,
    [AI_MODEL.VERSIONS.GROQ_LLAMA_3_8B]: AI_MODEL.COSTS.GROQ_LLAMA_3_8B,
    [AI_MODEL.VERSIONS.GROQ_MIXTRAL_8X7B]: AI_MODEL.COSTS.GROQ_MIXTRAL_8X7B,
  };
  return costs[modelVersion] || AI_MODEL.COSTS.GPT_3_5;
}

export function calculateCost(
  modelVersion: AIModelVersion,
  inputTokens: number,
  outputTokens: number
): number {
  const cost = getModelCost(modelVersion);
  const inputCost = (inputTokens / 1000) * cost.input;
  const outputCost = (outputTokens / 1000) * cost.output;
  return inputCost + outputCost;
}

export function getMaxTokens(modelVersion: AIModelVersion): number {
  const maxTokensMap: Partial<Record<AIModelVersion, number>> = {
    [AI_MODEL.VERSIONS.GPT_3_5]: AI_MODEL.LIMITS.MAX_TOKENS.GPT_3_5,
    [AI_MODEL.VERSIONS.GPT_4]: AI_MODEL.LIMITS.MAX_TOKENS.GPT_4,
    [AI_MODEL.VERSIONS.GPT_4_TURBO]: AI_MODEL.LIMITS.MAX_TOKENS.GPT_4_TURBO,
    [AI_MODEL.VERSIONS.GPT_4O]: AI_MODEL.LIMITS.MAX_TOKENS.GPT_4O,
    [AI_MODEL.VERSIONS.CLAUDE_3_OPUS]: AI_MODEL.LIMITS.MAX_TOKENS.CLAUDE_3,
    [AI_MODEL.VERSIONS.CLAUDE_3_SONNET]: AI_MODEL.LIMITS.MAX_TOKENS.CLAUDE_3,
    [AI_MODEL.VERSIONS.CLAUDE_3_HAIKU]: AI_MODEL.LIMITS.MAX_TOKENS.CLAUDE_3,
    [AI_MODEL.VERSIONS.CLAUDE_3_5_SONNET]: AI_MODEL.LIMITS.MAX_TOKENS.CLAUDE_3,
    [AI_MODEL.VERSIONS.LLAMA_2_7B]: AI_MODEL.LIMITS.MAX_TOKENS.LLAMA_2,
    [AI_MODEL.VERSIONS.LLAMA_2_13B]: AI_MODEL.LIMITS.MAX_TOKENS.LLAMA_2,
    [AI_MODEL.VERSIONS.LLAMA_2_70B]: AI_MODEL.LIMITS.MAX_TOKENS.LLAMA_2,
    [AI_MODEL.VERSIONS.LLAMA_3_8B]: AI_MODEL.LIMITS.MAX_TOKENS.LLAMA_3,
    [AI_MODEL.VERSIONS.LLAMA_3_70B]: AI_MODEL.LIMITS.MAX_TOKENS.LLAMA_3,
    [AI_MODEL.VERSIONS.MISTRAL_7B]: AI_MODEL.LIMITS.MAX_TOKENS.MISTRAL,
    [AI_MODEL.VERSIONS.MISTRAL_8X7B]: AI_MODEL.LIMITS.MAX_TOKENS.MISTRAL,
    [AI_MODEL.VERSIONS.MISTRAL_LARGE]: AI_MODEL.LIMITS.MAX_TOKENS.MISTRAL,
    [AI_MODEL.VERSIONS.GEMINI_PRO]: AI_MODEL.LIMITS.MAX_TOKENS.GEMINI,
    [AI_MODEL.VERSIONS.GEMINI_PRO_VISION]: AI_MODEL.LIMITS.MAX_TOKENS.GEMINI,
    [AI_MODEL.VERSIONS.GEMINI_ULTRA]: AI_MODEL.LIMITS.MAX_TOKENS.GEMINI,
  };
  return maxTokensMap[modelVersion] || AI_MODEL.LIMITS.MAX_TOKENS.DEFAULT;
}

export function isVisionCapable(modelVersion: AIModelVersion): boolean {
  const visionModels: AIModelVersion[] = [
    AI_MODEL.VERSIONS.GPT_4_VISION,
    AI_MODEL.VERSIONS.GPT_4O,
    AI_MODEL.VERSIONS.GPT_4O_MINI,
    AI_MODEL.VERSIONS.GEMINI_PRO_VISION,
  ];
  return visionModels.includes(modelVersion);
}

export function isChatModel(modelVersion: AIModelVersion): boolean {
  const chatModels: AIModelVersion[] = [
    AI_MODEL.VERSIONS.GPT_3_5,
    AI_MODEL.VERSIONS.GPT_3_5_16K,
    AI_MODEL.VERSIONS.GPT_4,
    AI_MODEL.VERSIONS.GPT_4_32K,
    AI_MODEL.VERSIONS.GPT_4_TURBO,
    AI_MODEL.VERSIONS.GPT_4O,
    AI_MODEL.VERSIONS.GPT_4O_MINI,
    AI_MODEL.VERSIONS.CLAUDE_3_OPUS,
    AI_MODEL.VERSIONS.CLAUDE_3_SONNET,
    AI_MODEL.VERSIONS.CLAUDE_3_HAIKU,
    AI_MODEL.VERSIONS.CLAUDE_3_5_SONNET,
    AI_MODEL.VERSIONS.LLAMA_2_7B,
    AI_MODEL.VERSIONS.LLAMA_2_13B,
    AI_MODEL.VERSIONS.LLAMA_2_70B,
    AI_MODEL.VERSIONS.LLAMA_3_8B,
    AI_MODEL.VERSIONS.LLAMA_3_70B,
    AI_MODEL.VERSIONS.MISTRAL_7B,
    AI_MODEL.VERSIONS.MISTRAL_8X7B,
    AI_MODEL.VERSIONS.MISTRAL_LARGE,
    AI_MODEL.VERSIONS.GEMINI_PRO,
    AI_MODEL.VERSIONS.GEMINI_ULTRA,
    AI_MODEL.VERSIONS.PALM_2_CHAT,
    AI_MODEL.VERSIONS.DEEPSEEK_V2,
    AI_MODEL.VERSIONS.DEEPSEEK_V3,
    AI_MODEL.VERSIONS.GROQ_LLAMA_3_70B,
    AI_MODEL.VERSIONS.GROQ_LLAMA_3_8B,
    AI_MODEL.VERSIONS.GROQ_MIXTRAL_8X7B,
  ];
  return chatModels.includes(modelVersion);
}

export function getModelSize(modelVersion: AIModelVersion): AIModelSize {
  const sizeMap: Partial<Record<AIModelVersion, AIModelSize>> = {
    [AI_MODEL.VERSIONS.GPT_3_5]: AI_MODEL.SIZES.MEDIUM,
    [AI_MODEL.VERSIONS.GPT_4]: AI_MODEL.SIZES.LARGE,
    [AI_MODEL.VERSIONS.GPT_4_TURBO]: AI_MODEL.SIZES.LARGE,
    [AI_MODEL.VERSIONS.GPT_4O]: AI_MODEL.SIZES.XLARGE,
    [AI_MODEL.VERSIONS.LLAMA_2_7B]: AI_MODEL.SIZES.MEDIUM,
    [AI_MODEL.VERSIONS.LLAMA_2_70B]: AI_MODEL.SIZES.XLARGE,
    [AI_MODEL.VERSIONS.LLAMA_3_8B]: AI_MODEL.SIZES.MEDIUM,
    [AI_MODEL.VERSIONS.LLAMA_3_70B]: AI_MODEL.SIZES.XLARGE,
    [AI_MODEL.VERSIONS.MISTRAL_7B]: AI_MODEL.SIZES.MEDIUM,
    [AI_MODEL.VERSIONS.MISTRAL_8X7B]: AI_MODEL.SIZES.LARGE,
    [AI_MODEL.VERSIONS.MISTRAL_LARGE]: AI_MODEL.SIZES.XLARGE,
    [AI_MODEL.VERSIONS.CLAUDE_3_OPUS]: AI_MODEL.SIZES.XLARGE,
    [AI_MODEL.VERSIONS.CLAUDE_3_SONNET]: AI_MODEL.SIZES.LARGE,
    [AI_MODEL.VERSIONS.CLAUDE_3_HAIKU]: AI_MODEL.SIZES.MEDIUM,
    [AI_MODEL.VERSIONS.GEMINI_PRO]: AI_MODEL.SIZES.LARGE,
    [AI_MODEL.VERSIONS.GEMINI_ULTRA]: AI_MODEL.SIZES.XLARGE,
    [AI_MODEL.VERSIONS.BERT_BASE]: AI_MODEL.SIZES.MEDIUM,
    [AI_MODEL.VERSIONS.BERT_LARGE]: AI_MODEL.SIZES.LARGE,
  };
  return sizeMap[modelVersion] || AI_MODEL.SIZES.MEDIUM;
}
