/**
 * AI Model Provider Constants
 * Configuration for AI service providers
 */

export const AI_MODEL_PROVIDER = {
  // Providers
  PROVIDERS: {
    OPENAI: 'openai',
    GOOGLE: 'google',
    ANTHROPIC: 'anthropic',
    COHERE: 'cohere',
    HUGGINGFACE: 'huggingface',
    AZURE: 'azure',
    AWS: 'aws',
    DEEPSEEK: 'deepseek',
    GROQ: 'groq',
    MISTRAL: 'mistral',
    REPLICATE: 'replicate',
    TOGETHER: 'together',
    PERPLEXITY: 'perplexity',
    FIREWORKS: 'fireworks',
    LEONARDO: 'leonardo',
    STABILITY_AI: 'stability_ai',
    ELEVENLABS: 'elevenlabs',
  } as const,

  // Provider Regions
  REGIONS: {
    US_EAST: 'us-east',
    US_WEST: 'us-west',
    EU_WEST: 'eu-west',
    EU_CENTRAL: 'eu-central',
    ASIA_EAST: 'asia-east',
    ASIA_SOUTH: 'asia-south',
    ASIA_SOUTHEAST: 'asia-southeast',
  } as const,

  // Provider Environments
  ENVIRONMENTS: {
    PRODUCTION: 'production',
    STAGING: 'staging',
    DEVELOPMENT: 'development',
    TESTING: 'testing',
  } as const,

  // Provider Authentication Types
  AUTH_TYPES: {
    API_KEY: 'api_key',
    OAUTH: 'oauth',
    JWT: 'jwt',
    IAM: 'iam',
    SERVICE_ACCOUNT: 'service_account',
  } as const,

  // Provider Pricing Models
  PRICING_MODELS: {
    PAY_PER_TOKEN: 'pay_per_token',
    PAY_PER_REQUEST: 'pay_per_request',
    SUBSCRIPTION: 'subscription',
    FREE_TIER: 'free_tier',
    CUSTOM: 'custom',
  } as const,

  // Provider Defaults
  DEFAULTS: {
    OPENAI: {
      model: 'gpt-4o-mini',
      temperature: 0.7,
      maxTokens: 2048,
      timeout: 30000,
    },
    GOOGLE: {
      model: 'gemini-pro',
      temperature: 0.7,
      maxTokens: 2048,
      timeout: 30000,
    },
    ANTHROPIC: {
      model: 'claude-3-haiku-20240307',
      temperature: 0.7,
      maxTokens: 2048,
      timeout: 30000,
    },
    DEEPSEEK: {
      model: 'deepseek-v3',
      temperature: 0.7,
      maxTokens: 2048,
      timeout: 30000,
    },
    GROQ: {
      model: 'llama-3-70b',
      temperature: 0.7,
      maxTokens: 2048,
      timeout: 30000,
    },
    MISTRAL: {
      model: 'mistral-large',
      temperature: 0.7,
      maxTokens: 2048,
      timeout: 30000,
    },
  } as const,
} as const;

// Providers
export type AIProviderType =
  (typeof AI_MODEL_PROVIDER.PROVIDERS)[keyof typeof AI_MODEL_PROVIDER.PROVIDERS];

// Regions
export type AIProviderRegion =
  (typeof AI_MODEL_PROVIDER.REGIONS)[keyof typeof AI_MODEL_PROVIDER.REGIONS];

// Environments
export type AIProviderEnvironment =
  (typeof AI_MODEL_PROVIDER.ENVIRONMENTS)[keyof typeof AI_MODEL_PROVIDER.ENVIRONMENTS];

// Auth Types
export type AIProviderAuthType =
  (typeof AI_MODEL_PROVIDER.AUTH_TYPES)[keyof typeof AI_MODEL_PROVIDER.AUTH_TYPES];

// Pricing Models
export type AIProviderPricingModel =
  (typeof AI_MODEL_PROVIDER.PRICING_MODELS)[keyof typeof AI_MODEL_PROVIDER.PRICING_MODELS];

// Provider Default Config
export type AIProviderDefault =
  (typeof AI_MODEL_PROVIDER.DEFAULTS)[keyof typeof AI_MODEL_PROVIDER.DEFAULTS];

// Utility Functions
export function getProviderEndpoint(provider: AIProviderType): string {
  const endpoints: Record<AIProviderType, string> = {
    [AI_MODEL_PROVIDER.PROVIDERS.OPENAI]: 'https://api.openai.com/v1',
    [AI_MODEL_PROVIDER.PROVIDERS.GOOGLE]: 'https://generativelanguage.googleapis.com/v1beta',
    [AI_MODEL_PROVIDER.PROVIDERS.ANTHROPIC]: 'https://api.anthropic.com/v1',
    [AI_MODEL_PROVIDER.PROVIDERS.COHERE]: 'https://api.cohere.ai/v1',
    [AI_MODEL_PROVIDER.PROVIDERS.HUGGINGFACE]: 'https://api-inference.huggingface.co',
    [AI_MODEL_PROVIDER.PROVIDERS.AZURE]: 'https://your-azure-endpoint.com',
    [AI_MODEL_PROVIDER.PROVIDERS.AWS]: 'https://your-aws-endpoint.com',
    [AI_MODEL_PROVIDER.PROVIDERS.DEEPSEEK]: 'https://api.deepseek.com/v1',
    [AI_MODEL_PROVIDER.PROVIDERS.GROQ]: 'https://api.groq.com/openai/v1',
    [AI_MODEL_PROVIDER.PROVIDERS.MISTRAL]: 'https://api.mistral.ai/v1',
    [AI_MODEL_PROVIDER.PROVIDERS.REPLICATE]: 'https://api.replicate.com/v1',
    [AI_MODEL_PROVIDER.PROVIDERS.TOGETHER]: 'https://api.together.xyz/v1',
    [AI_MODEL_PROVIDER.PROVIDERS.PERPLEXITY]: 'https://api.perplexity.ai',
    [AI_MODEL_PROVIDER.PROVIDERS.FIREWORKS]: 'https://api.fireworks.ai/v1',
    [AI_MODEL_PROVIDER.PROVIDERS.LEONARDO]: 'https://api.leonardo.ai/v1',
    [AI_MODEL_PROVIDER.PROVIDERS.STABILITY_AI]: 'https://api.stability.ai/v1',
    [AI_MODEL_PROVIDER.PROVIDERS.ELEVENLABS]: 'https://api.elevenlabs.io/v1',
  };
  return endpoints[provider] || '';
}

export function getProviderDefault(provider: AIProviderType): AIProviderDefault {
  const defaults: Record<AIProviderType, AIProviderDefault> = {
    [AI_MODEL_PROVIDER.PROVIDERS.OPENAI]: AI_MODEL_PROVIDER.DEFAULTS.OPENAI,
    [AI_MODEL_PROVIDER.PROVIDERS.GOOGLE]: AI_MODEL_PROVIDER.DEFAULTS.GOOGLE,
    [AI_MODEL_PROVIDER.PROVIDERS.ANTHROPIC]: AI_MODEL_PROVIDER.DEFAULTS.ANTHROPIC,
    [AI_MODEL_PROVIDER.PROVIDERS.COHERE]: AI_MODEL_PROVIDER.DEFAULTS.OPENAI,
    [AI_MODEL_PROVIDER.PROVIDERS.HUGGINGFACE]: AI_MODEL_PROVIDER.DEFAULTS.OPENAI,
    [AI_MODEL_PROVIDER.PROVIDERS.AZURE]: AI_MODEL_PROVIDER.DEFAULTS.OPENAI,
    [AI_MODEL_PROVIDER.PROVIDERS.AWS]: AI_MODEL_PROVIDER.DEFAULTS.OPENAI,
    [AI_MODEL_PROVIDER.PROVIDERS.DEEPSEEK]: AI_MODEL_PROVIDER.DEFAULTS.DEEPSEEK,
    [AI_MODEL_PROVIDER.PROVIDERS.GROQ]: AI_MODEL_PROVIDER.DEFAULTS.GROQ,
    [AI_MODEL_PROVIDER.PROVIDERS.MISTRAL]: AI_MODEL_PROVIDER.DEFAULTS.MISTRAL,
    [AI_MODEL_PROVIDER.PROVIDERS.REPLICATE]: AI_MODEL_PROVIDER.DEFAULTS.OPENAI,
    [AI_MODEL_PROVIDER.PROVIDERS.TOGETHER]: AI_MODEL_PROVIDER.DEFAULTS.OPENAI,
    [AI_MODEL_PROVIDER.PROVIDERS.PERPLEXITY]: AI_MODEL_PROVIDER.DEFAULTS.OPENAI,
    [AI_MODEL_PROVIDER.PROVIDERS.FIREWORKS]: AI_MODEL_PROVIDER.DEFAULTS.OPENAI,
    [AI_MODEL_PROVIDER.PROVIDERS.LEONARDO]: AI_MODEL_PROVIDER.DEFAULTS.OPENAI,
    [AI_MODEL_PROVIDER.PROVIDERS.STABILITY_AI]: AI_MODEL_PROVIDER.DEFAULTS.OPENAI,
    [AI_MODEL_PROVIDER.PROVIDERS.ELEVENLABS]: AI_MODEL_PROVIDER.DEFAULTS.OPENAI,
  };
  return defaults[provider] || AI_MODEL_PROVIDER.DEFAULTS.OPENAI;
}

export function getProviderAuthType(provider: AIProviderType): AIProviderAuthType {
  const authTypes: Record<AIProviderType, AIProviderAuthType> = {
    [AI_MODEL_PROVIDER.PROVIDERS.OPENAI]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.GOOGLE]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.ANTHROPIC]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.COHERE]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.HUGGINGFACE]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.AZURE]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.AWS]: AI_MODEL_PROVIDER.AUTH_TYPES.IAM,
    [AI_MODEL_PROVIDER.PROVIDERS.DEEPSEEK]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.GROQ]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.MISTRAL]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.REPLICATE]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.TOGETHER]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.PERPLEXITY]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.FIREWORKS]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.LEONARDO]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.STABILITY_AI]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
    [AI_MODEL_PROVIDER.PROVIDERS.ELEVENLABS]: AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY,
  };
  return authTypes[provider] || AI_MODEL_PROVIDER.AUTH_TYPES.API_KEY;
}

export function getProviderPricingModel(provider: AIProviderType): AIProviderPricingModel {
  const pricingModels: Record<AIProviderType, AIProviderPricingModel> = {
    [AI_MODEL_PROVIDER.PROVIDERS.OPENAI]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_TOKEN,
    [AI_MODEL_PROVIDER.PROVIDERS.GOOGLE]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_TOKEN,
    [AI_MODEL_PROVIDER.PROVIDERS.ANTHROPIC]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_TOKEN,
    [AI_MODEL_PROVIDER.PROVIDERS.COHERE]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_TOKEN,
    [AI_MODEL_PROVIDER.PROVIDERS.HUGGINGFACE]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_REQUEST,
    [AI_MODEL_PROVIDER.PROVIDERS.AZURE]: AI_MODEL_PROVIDER.PRICING_MODELS.SUBSCRIPTION,
    [AI_MODEL_PROVIDER.PROVIDERS.AWS]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_REQUEST,
    [AI_MODEL_PROVIDER.PROVIDERS.DEEPSEEK]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_TOKEN,
    [AI_MODEL_PROVIDER.PROVIDERS.GROQ]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_TOKEN,
    [AI_MODEL_PROVIDER.PROVIDERS.MISTRAL]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_TOKEN,
    [AI_MODEL_PROVIDER.PROVIDERS.REPLICATE]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_REQUEST,
    [AI_MODEL_PROVIDER.PROVIDERS.TOGETHER]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_TOKEN,
    [AI_MODEL_PROVIDER.PROVIDERS.PERPLEXITY]: AI_MODEL_PROVIDER.PRICING_MODELS.SUBSCRIPTION,
    [AI_MODEL_PROVIDER.PROVIDERS.FIREWORKS]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_TOKEN,
    [AI_MODEL_PROVIDER.PROVIDERS.LEONARDO]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_REQUEST,
    [AI_MODEL_PROVIDER.PROVIDERS.STABILITY_AI]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_REQUEST,
    [AI_MODEL_PROVIDER.PROVIDERS.ELEVENLABS]: AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_REQUEST,
  };
  return pricingModels[provider] || AI_MODEL_PROVIDER.PRICING_MODELS.PAY_PER_TOKEN;
}

export function getProviderRegion(provider: AIProviderType): AIProviderRegion {
  const regions: Record<AIProviderType, AIProviderRegion> = {
    [AI_MODEL_PROVIDER.PROVIDERS.OPENAI]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.GOOGLE]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.ANTHROPIC]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.COHERE]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.HUGGINGFACE]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.AZURE]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.AWS]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.DEEPSEEK]: AI_MODEL_PROVIDER.REGIONS.ASIA_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.GROQ]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.MISTRAL]: AI_MODEL_PROVIDER.REGIONS.EU_WEST,
    [AI_MODEL_PROVIDER.PROVIDERS.REPLICATE]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.TOGETHER]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.PERPLEXITY]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.FIREWORKS]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.LEONARDO]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.STABILITY_AI]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
    [AI_MODEL_PROVIDER.PROVIDERS.ELEVENLABS]: AI_MODEL_PROVIDER.REGIONS.US_EAST,
  };
  return regions[provider] || AI_MODEL_PROVIDER.REGIONS.US_EAST;
}
