/**
 * AI Model Status Constants
 * Detailed model status definitions for AI models
 */

// First define the status types
export const AI_MODEL_STATUSES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Development States
  DESIGNING: 'designing',
  DEVELOPING: 'developing',
  REVIEWING: 'reviewing',
  APPROVING: 'approving',

  // Training States
  TRAINING: 'training',
  EPOCH_COMPLETE: 'epoch_complete',
  BATCH_COMPLETE: 'batch_complete',
  CHECKPOINT_SAVED: 'checkpoint_saved',

  // Validation States
  VALIDATING: 'validating',
  VALIDATION_COMPLETE: 'validation_complete',

  // Testing States
  TESTING: 'testing',
  QA: 'qa',
  UAT: 'uat',
  PERFORMANCE_TESTING: 'performance_testing',
  SECURITY_TESTING: 'security_testing',

  // Staging States
  STAGING: 'staging',
  PRE_PRODUCTION: 'pre_production',

  // Production States
  PRODUCTION: 'production',
  BETA: 'beta',
  EARLY_ACCESS: 'early_access',
  PUBLIC: 'public',
  PRIVATE: 'private',
  DEPLOYED: 'deployed',

  // Maintenance States
  MONITORING: 'monitoring',
  OPTIMIZING: 'optimizing',
  UPDATING: 'updating',
  SCALING: 'scaling',

  // Terminal States
  DEPRECATED: 'deprecated',
  RETIRED: 'retired',
  ARCHIVED: 'archived',
  CANCELLED: 'cancelled',
  FAILED: 'failed',
} as const;

export type AIModelStatusType = (typeof AI_MODEL_STATUSES)[keyof typeof AI_MODEL_STATUSES];

export const AI_MODEL_STATUS = {
  // Status Types
  STATUSES: AI_MODEL_STATUSES,

  // Status Categories
  CATEGORIES: {
    PLANNING: 'planning',
    DEVELOPMENT: 'development',
    TRAINING: 'training',
    VALIDATION: 'validation',
    TESTING: 'testing',
    STAGING: 'staging',
    PRODUCTION: 'production',
    MAINTENANCE: 'maintenance',
    DEPRECATED: 'deprecated',
  } as const,

  // Status Priority
  PRIORITY: {
    CRITICAL: 'critical',
    HIGH: 'high',
    MEDIUM: 'medium',
    LOW: 'low',
    BACKGROUND: 'background',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_MODEL_STATUSES.CREATED]: '#gray',
    [AI_MODEL_STATUSES.QUEUED]: '#gray',
    [AI_MODEL_STATUSES.PENDING]: '#yellow',
    [AI_MODEL_STATUSES.DESIGNING]: '#blue',
    [AI_MODEL_STATUSES.DEVELOPING]: '#blue',
    [AI_MODEL_STATUSES.REVIEWING]: '#blue',
    [AI_MODEL_STATUSES.APPROVING]: '#blue',
    [AI_MODEL_STATUSES.TRAINING]: '#blue',
    [AI_MODEL_STATUSES.EPOCH_COMPLETE]: '#green',
    [AI_MODEL_STATUSES.BATCH_COMPLETE]: '#green',
    [AI_MODEL_STATUSES.CHECKPOINT_SAVED]: '#green',
    [AI_MODEL_STATUSES.VALIDATING]: '#purple',
    [AI_MODEL_STATUSES.VALIDATION_COMPLETE]: '#green',
    [AI_MODEL_STATUSES.TESTING]: '#orange',
    [AI_MODEL_STATUSES.QA]: '#orange',
    [AI_MODEL_STATUSES.UAT]: '#orange',
    [AI_MODEL_STATUSES.PERFORMANCE_TESTING]: '#orange',
    [AI_MODEL_STATUSES.SECURITY_TESTING]: '#red',
    [AI_MODEL_STATUSES.STAGING]: '#purple',
    [AI_MODEL_STATUSES.PRE_PRODUCTION]: '#purple',
    [AI_MODEL_STATUSES.PRODUCTION]: '#green',
    [AI_MODEL_STATUSES.BETA]: '#green',
    [AI_MODEL_STATUSES.EARLY_ACCESS]: '#green',
    [AI_MODEL_STATUSES.PUBLIC]: '#green',
    [AI_MODEL_STATUSES.PRIVATE]: '#gray',
    [AI_MODEL_STATUSES.DEPLOYED]: '#green',
    [AI_MODEL_STATUSES.MONITORING]: '#green',
    [AI_MODEL_STATUSES.OPTIMIZING]: '#green',
    [AI_MODEL_STATUSES.UPDATING]: '#orange',
    [AI_MODEL_STATUSES.SCALING]: '#orange',
    [AI_MODEL_STATUSES.DEPRECATED]: '#gray',
    [AI_MODEL_STATUSES.RETIRED]: '#gray',
    [AI_MODEL_STATUSES.ARCHIVED]: '#gray',
    [AI_MODEL_STATUSES.CANCELLED]: '#red',
    [AI_MODEL_STATUSES.FAILED]: '#red',
  } as const,
} as const;

export type AIModelStatusCategory =
  (typeof AI_MODEL_STATUS.CATEGORIES)[keyof typeof AI_MODEL_STATUS.CATEGORIES];

export type AIModelStatusPriority =
  (typeof AI_MODEL_STATUS.PRIORITY)[keyof typeof AI_MODEL_STATUS.PRIORITY];

export type AIModelStatusSeverity =
  (typeof AI_MODEL_STATUS.SEVERITY)[keyof typeof AI_MODEL_STATUS.SEVERITY];

export type AIModelStatusColor =
  (typeof AI_MODEL_STATUS.COLORS)[keyof typeof AI_MODEL_STATUS.COLORS];

export function getAimodelstatusLabel(status: AIModelStatusType): string {
  const labels: Record<AIModelStatusType, string> = {
    [AI_MODEL_STATUSES.CREATED]: 'Created',
    [AI_MODEL_STATUSES.QUEUED]: 'Queued',
    [AI_MODEL_STATUSES.PENDING]: 'Pending',
    [AI_MODEL_STATUSES.DESIGNING]: 'Designing',
    [AI_MODEL_STATUSES.DEVELOPING]: 'Developing',
    [AI_MODEL_STATUSES.REVIEWING]: 'Reviewing',
    [AI_MODEL_STATUSES.APPROVING]: 'Approving',
    [AI_MODEL_STATUSES.TRAINING]: 'Training',
    [AI_MODEL_STATUSES.EPOCH_COMPLETE]: 'Epoch Complete',
    [AI_MODEL_STATUSES.BATCH_COMPLETE]: 'Batch Complete',
    [AI_MODEL_STATUSES.CHECKPOINT_SAVED]: 'Checkpoint Saved',
    [AI_MODEL_STATUSES.VALIDATING]: 'Validating',
    [AI_MODEL_STATUSES.VALIDATION_COMPLETE]: 'Validation Complete',
    [AI_MODEL_STATUSES.TESTING]: 'Testing',
    [AI_MODEL_STATUSES.QA]: 'QA',
    [AI_MODEL_STATUSES.UAT]: 'UAT',
    [AI_MODEL_STATUSES.PERFORMANCE_TESTING]: 'Performance Testing',
    [AI_MODEL_STATUSES.SECURITY_TESTING]: 'Security Testing',
    [AI_MODEL_STATUSES.STAGING]: 'Staging',
    [AI_MODEL_STATUSES.PRE_PRODUCTION]: 'Pre-Production',
    [AI_MODEL_STATUSES.PRODUCTION]: 'Production',
    [AI_MODEL_STATUSES.BETA]: 'Beta',
    [AI_MODEL_STATUSES.EARLY_ACCESS]: 'Early Access',
    [AI_MODEL_STATUSES.PUBLIC]: 'Public',
    [AI_MODEL_STATUSES.PRIVATE]: 'Private',
    [AI_MODEL_STATUSES.DEPLOYED]: 'Deployed',
    [AI_MODEL_STATUSES.MONITORING]: 'Monitoring',
    [AI_MODEL_STATUSES.OPTIMIZING]: 'Optimizing',
    [AI_MODEL_STATUSES.UPDATING]: 'Updating',
    [AI_MODEL_STATUSES.SCALING]: 'Scaling',
    [AI_MODEL_STATUSES.DEPRECATED]: 'Deprecated',
    [AI_MODEL_STATUSES.RETIRED]: 'Retired',
    [AI_MODEL_STATUSES.ARCHIVED]: 'Archived',
    [AI_MODEL_STATUSES.CANCELLED]: 'Cancelled',
    [AI_MODEL_STATUSES.FAILED]: 'Failed',
  };
  return labels[status] || 'Unknown';
}

export function getAimodelstatusCategory(status: AIModelStatusType): AIModelStatusCategory {
  const categories: Record<AIModelStatusType, AIModelStatusCategory> = {
    [AI_MODEL_STATUSES.CREATED]: AI_MODEL_STATUS.CATEGORIES.PLANNING,
    [AI_MODEL_STATUSES.QUEUED]: AI_MODEL_STATUS.CATEGORIES.PLANNING,
    [AI_MODEL_STATUSES.PENDING]: AI_MODEL_STATUS.CATEGORIES.PLANNING,
    [AI_MODEL_STATUSES.DESIGNING]: AI_MODEL_STATUS.CATEGORIES.DEVELOPMENT,
    [AI_MODEL_STATUSES.DEVELOPING]: AI_MODEL_STATUS.CATEGORIES.DEVELOPMENT,
    [AI_MODEL_STATUSES.REVIEWING]: AI_MODEL_STATUS.CATEGORIES.DEVELOPMENT,
    [AI_MODEL_STATUSES.APPROVING]: AI_MODEL_STATUS.CATEGORIES.DEVELOPMENT,
    [AI_MODEL_STATUSES.TRAINING]: AI_MODEL_STATUS.CATEGORIES.TRAINING,
    [AI_MODEL_STATUSES.EPOCH_COMPLETE]: AI_MODEL_STATUS.CATEGORIES.TRAINING,
    [AI_MODEL_STATUSES.BATCH_COMPLETE]: AI_MODEL_STATUS.CATEGORIES.TRAINING,
    [AI_MODEL_STATUSES.CHECKPOINT_SAVED]: AI_MODEL_STATUS.CATEGORIES.TRAINING,
    [AI_MODEL_STATUSES.VALIDATING]: AI_MODEL_STATUS.CATEGORIES.VALIDATION,
    [AI_MODEL_STATUSES.VALIDATION_COMPLETE]: AI_MODEL_STATUS.CATEGORIES.VALIDATION,
    [AI_MODEL_STATUSES.TESTING]: AI_MODEL_STATUS.CATEGORIES.TESTING,
    [AI_MODEL_STATUSES.QA]: AI_MODEL_STATUS.CATEGORIES.TESTING,
    [AI_MODEL_STATUSES.UAT]: AI_MODEL_STATUS.CATEGORIES.TESTING,
    [AI_MODEL_STATUSES.PERFORMANCE_TESTING]: AI_MODEL_STATUS.CATEGORIES.TESTING,
    [AI_MODEL_STATUSES.SECURITY_TESTING]: AI_MODEL_STATUS.CATEGORIES.TESTING,
    [AI_MODEL_STATUSES.STAGING]: AI_MODEL_STATUS.CATEGORIES.STAGING,
    [AI_MODEL_STATUSES.PRE_PRODUCTION]: AI_MODEL_STATUS.CATEGORIES.STAGING,
    [AI_MODEL_STATUSES.PRODUCTION]: AI_MODEL_STATUS.CATEGORIES.PRODUCTION,
    [AI_MODEL_STATUSES.BETA]: AI_MODEL_STATUS.CATEGORIES.PRODUCTION,
    [AI_MODEL_STATUSES.EARLY_ACCESS]: AI_MODEL_STATUS.CATEGORIES.PRODUCTION,
    [AI_MODEL_STATUSES.PUBLIC]: AI_MODEL_STATUS.CATEGORIES.PRODUCTION,
    [AI_MODEL_STATUSES.PRIVATE]: AI_MODEL_STATUS.CATEGORIES.PRODUCTION,
    [AI_MODEL_STATUSES.DEPLOYED]: AI_MODEL_STATUS.CATEGORIES.PRODUCTION,
    [AI_MODEL_STATUSES.MONITORING]: AI_MODEL_STATUS.CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.OPTIMIZING]: AI_MODEL_STATUS.CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.UPDATING]: AI_MODEL_STATUS.CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.SCALING]: AI_MODEL_STATUS.CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.DEPRECATED]: AI_MODEL_STATUS.CATEGORIES.DEPRECATED,
    [AI_MODEL_STATUSES.RETIRED]: AI_MODEL_STATUS.CATEGORIES.DEPRECATED,
    [AI_MODEL_STATUSES.ARCHIVED]: AI_MODEL_STATUS.CATEGORIES.DEPRECATED,
    [AI_MODEL_STATUSES.CANCELLED]: AI_MODEL_STATUS.CATEGORIES.PLANNING,
    [AI_MODEL_STATUSES.FAILED]: AI_MODEL_STATUS.CATEGORIES.PLANNING,
  };
  return categories[status] || AI_MODEL_STATUS.CATEGORIES.PLANNING;
}

export function getAimodelstatusSeverity(status: AIModelStatusType): AIModelStatusSeverity {
  const severities: Record<AIModelStatusType, AIModelStatusSeverity> = {
    [AI_MODEL_STATUSES.CREATED]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.QUEUED]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.PENDING]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.DESIGNING]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.DEVELOPING]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.REVIEWING]: AI_MODEL_STATUS.SEVERITY.WARNING,
    [AI_MODEL_STATUSES.APPROVING]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.TRAINING]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.EPOCH_COMPLETE]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.BATCH_COMPLETE]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.CHECKPOINT_SAVED]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.VALIDATING]: AI_MODEL_STATUS.SEVERITY.WARNING,
    [AI_MODEL_STATUSES.VALIDATION_COMPLETE]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.TESTING]: AI_MODEL_STATUS.SEVERITY.WARNING,
    [AI_MODEL_STATUSES.QA]: AI_MODEL_STATUS.SEVERITY.WARNING,
    [AI_MODEL_STATUSES.UAT]: AI_MODEL_STATUS.SEVERITY.WARNING,
    [AI_MODEL_STATUSES.PERFORMANCE_TESTING]: AI_MODEL_STATUS.SEVERITY.WARNING,
    [AI_MODEL_STATUSES.SECURITY_TESTING]: AI_MODEL_STATUS.SEVERITY.CRITICAL,
    [AI_MODEL_STATUSES.STAGING]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.PRE_PRODUCTION]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.PRODUCTION]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.BETA]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.EARLY_ACCESS]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.PUBLIC]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.PRIVATE]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.DEPLOYED]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.MONITORING]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.OPTIMIZING]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.UPDATING]: AI_MODEL_STATUS.SEVERITY.WARNING,
    [AI_MODEL_STATUSES.SCALING]: AI_MODEL_STATUS.SEVERITY.WARNING,
    [AI_MODEL_STATUSES.DEPRECATED]: AI_MODEL_STATUS.SEVERITY.WARNING,
    [AI_MODEL_STATUSES.RETIRED]: AI_MODEL_STATUS.SEVERITY.WARNING,
    [AI_MODEL_STATUSES.ARCHIVED]: AI_MODEL_STATUS.SEVERITY.INFO,
    [AI_MODEL_STATUSES.CANCELLED]: AI_MODEL_STATUS.SEVERITY.ERROR,
    [AI_MODEL_STATUSES.FAILED]: AI_MODEL_STATUS.SEVERITY.ERROR,
  };
  return severities[status] || AI_MODEL_STATUS.SEVERITY.INFO;
}

export function getAimodelstatusColor(status: AIModelStatusType): AIModelStatusColor {
  return AI_MODEL_STATUS.COLORS[status] || '#gray';
}

export function isAimodelstatusDeployed(status: AIModelStatusType): boolean {
  return status === AI_MODEL_STATUSES.DEPLOYED || status === AI_MODEL_STATUSES.PRODUCTION;
}

export function isAimodelstatusActive(status: AIModelStatusType): boolean {
  const activeStatuses: AIModelStatusType[] = [
    AI_MODEL_STATUSES.STAGING,
    AI_MODEL_STATUSES.PRE_PRODUCTION,
    AI_MODEL_STATUSES.PRODUCTION,
    AI_MODEL_STATUSES.BETA,
    AI_MODEL_STATUSES.EARLY_ACCESS,
    AI_MODEL_STATUSES.PUBLIC,
    AI_MODEL_STATUSES.PRIVATE,
    AI_MODEL_STATUSES.DEPLOYED,
    AI_MODEL_STATUSES.MONITORING,
    AI_MODEL_STATUSES.OPTIMIZING,
  ];
  return activeStatuses.includes(status);
}

export function isAimodelstatusError(status: AIModelStatusType): boolean {
  const errorStatuses: AIModelStatusType[] = [
    AI_MODEL_STATUSES.CANCELLED,
    AI_MODEL_STATUSES.FAILED,
    AI_MODEL_STATUSES.SECURITY_TESTING,
  ];
  return errorStatuses.includes(status);
}

export function getAimodelstatusProgress(status: AIModelStatusType): number {
  const progress: Record<AIModelStatusType, number> = {
    [AI_MODEL_STATUSES.CREATED]: 0,
    [AI_MODEL_STATUSES.QUEUED]: 5,
    [AI_MODEL_STATUSES.PENDING]: 10,
    [AI_MODEL_STATUSES.DESIGNING]: 15,
    [AI_MODEL_STATUSES.DEVELOPING]: 25,
    [AI_MODEL_STATUSES.REVIEWING]: 35,
    [AI_MODEL_STATUSES.APPROVING]: 40,
    [AI_MODEL_STATUSES.TRAINING]: 50,
    [AI_MODEL_STATUSES.EPOCH_COMPLETE]: 55,
    [AI_MODEL_STATUSES.BATCH_COMPLETE]: 60,
    [AI_MODEL_STATUSES.CHECKPOINT_SAVED]: 65,
    [AI_MODEL_STATUSES.VALIDATING]: 70,
    [AI_MODEL_STATUSES.VALIDATION_COMPLETE]: 75,
    [AI_MODEL_STATUSES.TESTING]: 80,
    [AI_MODEL_STATUSES.QA]: 82,
    [AI_MODEL_STATUSES.UAT]: 85,
    [AI_MODEL_STATUSES.PERFORMANCE_TESTING]: 87,
    [AI_MODEL_STATUSES.SECURITY_TESTING]: 90,
    [AI_MODEL_STATUSES.STAGING]: 92,
    [AI_MODEL_STATUSES.PRE_PRODUCTION]: 95,
    [AI_MODEL_STATUSES.PRODUCTION]: 100,
    [AI_MODEL_STATUSES.BETA]: 100,
    [AI_MODEL_STATUSES.EARLY_ACCESS]: 100,
    [AI_MODEL_STATUSES.PUBLIC]: 100,
    [AI_MODEL_STATUSES.PRIVATE]: 100,
    [AI_MODEL_STATUSES.DEPLOYED]: 100,
    [AI_MODEL_STATUSES.MONITORING]: 100,
    [AI_MODEL_STATUSES.OPTIMIZING]: 100,
    [AI_MODEL_STATUSES.UPDATING]: 95,
    [AI_MODEL_STATUSES.SCALING]: 95,
    [AI_MODEL_STATUSES.DEPRECATED]: 100,
    [AI_MODEL_STATUSES.RETIRED]: 100,
    [AI_MODEL_STATUSES.ARCHIVED]: 100,
    [AI_MODEL_STATUSES.CANCELLED]: 0,
    [AI_MODEL_STATUSES.FAILED]: 0,
  };
  return progress[status] || 0;
}
