/**
 * AI Model Status Constants
 * Status definitions for AI models throughout their lifecycle
 */

// First define STATUSES
export const AI_MODEL_STATUSES = {
  CREATED: 'created',
  INITIALIZING: 'initializing',
  INITIALIZED: 'initialized',
  TRAINING: 'training',
  TRAINING_PAUSED: 'training_paused',
  TRAINING_COMPLETED: 'training_completed',
  VALIDATING: 'validating',
  VALIDATED: 'validated',
  VALIDATION_FAILED: 'validation_failed',
  DEPLOYING: 'deploying',
  DEPLOYED: 'deployed',
  DEPLOYMENT_FAILED: 'deployment_failed',
  UPDATING: 'updating',
  UPDATED: 'updated',
  UPDATE_FAILED: 'update_failed',
  PERFORMANCE_TESTING: 'performance_testing',
  PERFORMANCE_OPTIMIZED: 'performance_optimized',
  SCALING: 'scaling',
  SCALED: 'scaled',
  MONITORING: 'monitoring',
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  DEGRADED: 'degraded',
  UNHEALTHY: 'unhealthy',
  ERROR: 'error',
  FAILED: 'failed',
  ARCHIVED: 'archived',
  RETIRED: 'retired',
  DELETED: 'deleted',
} as const;

// Status Categories
export const AI_MODEL_STATUS_CATEGORIES = {
  DEVELOPMENT: 'development',
  TRAINING: 'training',
  VALIDATION: 'validation',
  DEPLOYMENT: 'deployment',
  PRODUCTION: 'production',
  MAINTENANCE: 'maintenance',
  RETIRED: 'retired',
} as const;

// Status Priority
export const AI_MODEL_STATUS_PRIORITY = {
  CRITICAL: 'critical',
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low',
} as const;

// Status Colors (for UI)
export const AI_MODEL_STATUS_COLORS = {
  [AI_MODEL_STATUSES.CREATED]: '#gray',
  [AI_MODEL_STATUSES.INITIALIZING]: '#blue',
  [AI_MODEL_STATUSES.INITIALIZED]: '#blue',
  [AI_MODEL_STATUSES.TRAINING]: '#orange',
  [AI_MODEL_STATUSES.TRAINING_PAUSED]: '#yellow',
  [AI_MODEL_STATUSES.TRAINING_COMPLETED]: '#green',
  [AI_MODEL_STATUSES.VALIDATING]: '#purple',
  [AI_MODEL_STATUSES.VALIDATED]: '#green',
  [AI_MODEL_STATUSES.VALIDATION_FAILED]: '#red',
  [AI_MODEL_STATUSES.DEPLOYING]: '#blue',
  [AI_MODEL_STATUSES.DEPLOYED]: '#green',
  [AI_MODEL_STATUSES.DEPLOYMENT_FAILED]: '#red',
  [AI_MODEL_STATUSES.UPDATING]: '#orange',
  [AI_MODEL_STATUSES.UPDATED]: '#green',
  [AI_MODEL_STATUSES.UPDATE_FAILED]: '#red',
  [AI_MODEL_STATUSES.PERFORMANCE_TESTING]: '#purple',
  [AI_MODEL_STATUSES.PERFORMANCE_OPTIMIZED]: '#green',
  [AI_MODEL_STATUSES.SCALING]: '#orange',
  [AI_MODEL_STATUSES.SCALED]: '#green',
  [AI_MODEL_STATUSES.MONITORING]: '#blue',
  [AI_MODEL_STATUSES.ACTIVE]: '#green',
  [AI_MODEL_STATUSES.INACTIVE]: '#gray',
  [AI_MODEL_STATUSES.DEGRADED]: '#yellow',
  [AI_MODEL_STATUSES.UNHEALTHY]: '#red',
  [AI_MODEL_STATUSES.ERROR]: '#red',
  [AI_MODEL_STATUSES.FAILED]: '#red',
  [AI_MODEL_STATUSES.ARCHIVED]: '#gray',
  [AI_MODEL_STATUSES.RETIRED]: '#gray',
  [AI_MODEL_STATUSES.DELETED]: '#darkred',
} as const;

// Combined export for backward compatibility
export const AI_MODEL_STATUS = {
  STATUSES: AI_MODEL_STATUSES,
  CATEGORIES: AI_MODEL_STATUS_CATEGORIES,
  PRIORITY: AI_MODEL_STATUS_PRIORITY,
  COLORS: AI_MODEL_STATUS_COLORS,
} as const;

// Model Statuses
export type AIModelStatusType = (typeof AI_MODEL_STATUSES)[keyof typeof AI_MODEL_STATUSES];

// Status Categories
export type AIModelStatusCategory =
  (typeof AI_MODEL_STATUS_CATEGORIES)[keyof typeof AI_MODEL_STATUS_CATEGORIES];

// Status Priority
export type AIModelStatusPriority =
  (typeof AI_MODEL_STATUS_PRIORITY)[keyof typeof AI_MODEL_STATUS_PRIORITY];

// Status Colors
export type AIModelStatusColor =
  (typeof AI_MODEL_STATUS_COLORS)[keyof typeof AI_MODEL_STATUS_COLORS];

// Utility Functions
export function getStatusCategory(status: AIModelStatusType): AIModelStatusCategory {
  const categories: Record<AIModelStatusType, AIModelStatusCategory> = {
    [AI_MODEL_STATUSES.CREATED]: AI_MODEL_STATUS_CATEGORIES.DEVELOPMENT,
    [AI_MODEL_STATUSES.INITIALIZING]: AI_MODEL_STATUS_CATEGORIES.DEVELOPMENT,
    [AI_MODEL_STATUSES.INITIALIZED]: AI_MODEL_STATUS_CATEGORIES.DEVELOPMENT,
    [AI_MODEL_STATUSES.TRAINING]: AI_MODEL_STATUS_CATEGORIES.TRAINING,
    [AI_MODEL_STATUSES.TRAINING_PAUSED]: AI_MODEL_STATUS_CATEGORIES.TRAINING,
    [AI_MODEL_STATUSES.TRAINING_COMPLETED]: AI_MODEL_STATUS_CATEGORIES.VALIDATION,
    [AI_MODEL_STATUSES.VALIDATING]: AI_MODEL_STATUS_CATEGORIES.VALIDATION,
    [AI_MODEL_STATUSES.VALIDATED]: AI_MODEL_STATUS_CATEGORIES.VALIDATION,
    [AI_MODEL_STATUSES.VALIDATION_FAILED]: AI_MODEL_STATUS_CATEGORIES.VALIDATION,
    [AI_MODEL_STATUSES.DEPLOYING]: AI_MODEL_STATUS_CATEGORIES.DEPLOYMENT,
    [AI_MODEL_STATUSES.DEPLOYED]: AI_MODEL_STATUS_CATEGORIES.PRODUCTION,
    [AI_MODEL_STATUSES.DEPLOYMENT_FAILED]: AI_MODEL_STATUS_CATEGORIES.DEPLOYMENT,
    [AI_MODEL_STATUSES.UPDATING]: AI_MODEL_STATUS_CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.UPDATED]: AI_MODEL_STATUS_CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.UPDATE_FAILED]: AI_MODEL_STATUS_CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.PERFORMANCE_TESTING]: AI_MODEL_STATUS_CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.PERFORMANCE_OPTIMIZED]: AI_MODEL_STATUS_CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.SCALING]: AI_MODEL_STATUS_CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.SCALED]: AI_MODEL_STATUS_CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.MONITORING]: AI_MODEL_STATUS_CATEGORIES.PRODUCTION,
    [AI_MODEL_STATUSES.ACTIVE]: AI_MODEL_STATUS_CATEGORIES.PRODUCTION,
    [AI_MODEL_STATUSES.INACTIVE]: AI_MODEL_STATUS_CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.DEGRADED]: AI_MODEL_STATUS_CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.UNHEALTHY]: AI_MODEL_STATUS_CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.ERROR]: AI_MODEL_STATUS_CATEGORIES.MAINTENANCE,
    [AI_MODEL_STATUSES.FAILED]: AI_MODEL_STATUS_CATEGORIES.RETIRED,
    [AI_MODEL_STATUSES.ARCHIVED]: AI_MODEL_STATUS_CATEGORIES.RETIRED,
    [AI_MODEL_STATUSES.RETIRED]: AI_MODEL_STATUS_CATEGORIES.RETIRED,
    [AI_MODEL_STATUSES.DELETED]: AI_MODEL_STATUS_CATEGORIES.RETIRED,
  };
  return categories[status] || AI_MODEL_STATUS_CATEGORIES.DEVELOPMENT;
}

export function getStatusColor(status: AIModelStatusType): AIModelStatusColor {
  return AI_MODEL_STATUS_COLORS[status] || '#gray';
}

export function getStatusPriority(status: AIModelStatusType): AIModelStatusPriority {
  const priorities: Record<AIModelStatusType, AIModelStatusPriority> = {
    [AI_MODEL_STATUSES.CREATED]: AI_MODEL_STATUS_PRIORITY.LOW,
    [AI_MODEL_STATUSES.INITIALIZING]: AI_MODEL_STATUS_PRIORITY.MEDIUM,
    [AI_MODEL_STATUSES.INITIALIZED]: AI_MODEL_STATUS_PRIORITY.MEDIUM,
    [AI_MODEL_STATUSES.TRAINING]: AI_MODEL_STATUS_PRIORITY.HIGH,
    [AI_MODEL_STATUSES.TRAINING_PAUSED]: AI_MODEL_STATUS_PRIORITY.MEDIUM,
    [AI_MODEL_STATUSES.TRAINING_COMPLETED]: AI_MODEL_STATUS_PRIORITY.HIGH,
    [AI_MODEL_STATUSES.VALIDATING]: AI_MODEL_STATUS_PRIORITY.HIGH,
    [AI_MODEL_STATUSES.VALIDATED]: AI_MODEL_STATUS_PRIORITY.HIGH,
    [AI_MODEL_STATUSES.VALIDATION_FAILED]: AI_MODEL_STATUS_PRIORITY.CRITICAL,
    [AI_MODEL_STATUSES.DEPLOYING]: AI_MODEL_STATUS_PRIORITY.HIGH,
    [AI_MODEL_STATUSES.DEPLOYED]: AI_MODEL_STATUS_PRIORITY.HIGH,
    [AI_MODEL_STATUSES.DEPLOYMENT_FAILED]: AI_MODEL_STATUS_PRIORITY.CRITICAL,
    [AI_MODEL_STATUSES.UPDATING]: AI_MODEL_STATUS_PRIORITY.HIGH,
    [AI_MODEL_STATUSES.UPDATED]: AI_MODEL_STATUS_PRIORITY.MEDIUM,
    [AI_MODEL_STATUSES.UPDATE_FAILED]: AI_MODEL_STATUS_PRIORITY.HIGH,
    [AI_MODEL_STATUSES.PERFORMANCE_TESTING]: AI_MODEL_STATUS_PRIORITY.MEDIUM,
    [AI_MODEL_STATUSES.PERFORMANCE_OPTIMIZED]: AI_MODEL_STATUS_PRIORITY.MEDIUM,
    [AI_MODEL_STATUSES.SCALING]: AI_MODEL_STATUS_PRIORITY.MEDIUM,
    [AI_MODEL_STATUSES.SCALED]: AI_MODEL_STATUS_PRIORITY.MEDIUM,
    [AI_MODEL_STATUSES.MONITORING]: AI_MODEL_STATUS_PRIORITY.MEDIUM,
    [AI_MODEL_STATUSES.ACTIVE]: AI_MODEL_STATUS_PRIORITY.HIGH,
    [AI_MODEL_STATUSES.INACTIVE]: AI_MODEL_STATUS_PRIORITY.LOW,
    [AI_MODEL_STATUSES.DEGRADED]: AI_MODEL_STATUS_PRIORITY.HIGH,
    [AI_MODEL_STATUSES.UNHEALTHY]: AI_MODEL_STATUS_PRIORITY.CRITICAL,
    [AI_MODEL_STATUSES.ERROR]: AI_MODEL_STATUS_PRIORITY.CRITICAL,
    [AI_MODEL_STATUSES.FAILED]: AI_MODEL_STATUS_PRIORITY.CRITICAL,
    [AI_MODEL_STATUSES.ARCHIVED]: AI_MODEL_STATUS_PRIORITY.LOW,
    [AI_MODEL_STATUSES.RETIRED]: AI_MODEL_STATUS_PRIORITY.LOW,
    [AI_MODEL_STATUSES.DELETED]: AI_MODEL_STATUS_PRIORITY.LOW,
  };
  return priorities[status] || AI_MODEL_STATUS_PRIORITY.MEDIUM;
}

export function isDeployedStatus(status: AIModelStatusType): boolean {
  const deployedStatuses: AIModelStatusType[] = [
    AI_MODEL_STATUSES.DEPLOYED,
    AI_MODEL_STATUSES.ACTIVE,
    AI_MODEL_STATUSES.MONITORING,
  ];
  return deployedStatuses.includes(status);
}

export function isActiveStatus(status: AIModelStatusType): boolean {
  const activeStatuses: AIModelStatusType[] = [
    AI_MODEL_STATUSES.ACTIVE,
    AI_MODEL_STATUSES.DEPLOYED,
    AI_MODEL_STATUSES.MONITORING,
    AI_MODEL_STATUSES.UPDATED,
    AI_MODEL_STATUSES.SCALED,
    AI_MODEL_STATUSES.PERFORMANCE_OPTIMIZED,
  ];
  return activeStatuses.includes(status);
}

export function isErrorStatus(status: AIModelStatusType): boolean {
  const errorStatuses: AIModelStatusType[] = [
    AI_MODEL_STATUSES.ERROR,
    AI_MODEL_STATUSES.FAILED,
    AI_MODEL_STATUSES.DEPLOYMENT_FAILED,
    AI_MODEL_STATUSES.UPDATE_FAILED,
    AI_MODEL_STATUSES.VALIDATION_FAILED,
    AI_MODEL_STATUSES.UNHEALTHY,
    AI_MODEL_STATUSES.DEGRADED,
  ];
  return errorStatuses.includes(status);
}

export function getStatusLabel(status: AIModelStatusType): string {
  const labels: Record<AIModelStatusType, string> = {
    [AI_MODEL_STATUSES.CREATED]: 'Created',
    [AI_MODEL_STATUSES.INITIALIZING]: 'Initializing',
    [AI_MODEL_STATUSES.INITIALIZED]: 'Initialized',
    [AI_MODEL_STATUSES.TRAINING]: 'Training',
    [AI_MODEL_STATUSES.TRAINING_PAUSED]: 'Training Paused',
    [AI_MODEL_STATUSES.TRAINING_COMPLETED]: 'Training Completed',
    [AI_MODEL_STATUSES.VALIDATING]: 'Validating',
    [AI_MODEL_STATUSES.VALIDATED]: 'Validated',
    [AI_MODEL_STATUSES.VALIDATION_FAILED]: 'Validation Failed',
    [AI_MODEL_STATUSES.DEPLOYING]: 'Deploying',
    [AI_MODEL_STATUSES.DEPLOYED]: 'Deployed',
    [AI_MODEL_STATUSES.DEPLOYMENT_FAILED]: 'Deployment Failed',
    [AI_MODEL_STATUSES.UPDATING]: 'Updating',
    [AI_MODEL_STATUSES.UPDATED]: 'Updated',
    [AI_MODEL_STATUSES.UPDATE_FAILED]: 'Update Failed',
    [AI_MODEL_STATUSES.PERFORMANCE_TESTING]: 'Performance Testing',
    [AI_MODEL_STATUSES.PERFORMANCE_OPTIMIZED]: 'Performance Optimized',
    [AI_MODEL_STATUSES.SCALING]: 'Scaling',
    [AI_MODEL_STATUSES.SCALED]: 'Scaled',
    [AI_MODEL_STATUSES.MONITORING]: 'Monitoring',
    [AI_MODEL_STATUSES.ACTIVE]: 'Active',
    [AI_MODEL_STATUSES.INACTIVE]: 'Inactive',
    [AI_MODEL_STATUSES.DEGRADED]: 'Degraded',
    [AI_MODEL_STATUSES.UNHEALTHY]: 'Unhealthy',
    [AI_MODEL_STATUSES.ERROR]: 'Error',
    [AI_MODEL_STATUSES.FAILED]: 'Failed',
    [AI_MODEL_STATUSES.ARCHIVED]: 'Archived',
    [AI_MODEL_STATUSES.RETIRED]: 'Retired',
    [AI_MODEL_STATUSES.DELETED]: 'Deleted',
  };
  return labels[status] || 'Unknown';
}
