/**
 * Survey Type Constants
 * Types of surveys
 */

export const SURVEY_TYPE = {
  // Type Types
  TYPES: {
    CUSTOMER_SATISFACTION: 'customer_satisfaction',
    NET_PROMOTER_SCORE: 'net_promoter_score',
    PRODUCT_FEEDBACK: 'product_feedback',
    SERVICE_QUALITY: 'service_quality',
    EMPLOYEE_SATISFACTION: 'employee_satisfaction',
    MARKET_RESEARCH: 'market_research',
    EVENT_FEEDBACK: 'event_feedback',
    WEBSITE_EXPERIENCE: 'website_experience',
    APP_EXPERIENCE: 'app_experience',
    DEMOGRAPHIC: 'demographic',
    GENERAL: 'general',
  } as const,

  // Type Categories
  CATEGORIES: {
    SATISFACTION: 'satisfaction',
    FEEDBACK: 'feedback',
    RESEARCH: 'research',
    EXPERIENCE: 'experience',
  } as const,

  // Type Icons (for UI)
  ICONS: {
    CUSTOMER_SATISFACTION: '😊',
    NET_PROMOTER_SCORE: '⭐',
    PRODUCT_FEEDBACK: '🛍️',
    SERVICE_QUALITY: '🛠️',
    EMPLOYEE_SATISFACTION: '👤',
    MARKET_RESEARCH: '📊',
    EVENT_FEEDBACK: '🎪',
    WEBSITE_EXPERIENCE: '🌐',
    APP_EXPERIENCE: '📱',
    DEMOGRAPHIC: '👥',
    GENERAL: '📋',
  } as const,

  // Type Colors (for UI)
  COLORS: {
    CUSTOMER_SATISFACTION: '#green-500',
    NET_PROMOTER_SCORE: '#yellow-500',
    PRODUCT_FEEDBACK: '#blue-500',
    SERVICE_QUALITY: '#purple-500',
    EMPLOYEE_SATISFACTION: '#orange-500',
    MARKET_RESEARCH: '#teal-500',
    EVENT_FEEDBACK: '#pink-500',
    WEBSITE_EXPERIENCE: '#indigo-500',
    APP_EXPERIENCE: '#cyan-500',
    DEMOGRAPHIC: '#gray-500',
    GENERAL: '#gray-400',
  } as const,

  // Default Durations (in minutes)
  DURATIONS: {
    CUSTOMER_SATISFACTION: 5,
    NET_PROMOTER_SCORE: 3,
    PRODUCT_FEEDBACK: 10,
    SERVICE_QUALITY: 8,
    EMPLOYEE_SATISFACTION: 15,
    MARKET_RESEARCH: 20,
    EVENT_FEEDBACK: 5,
    WEBSITE_EXPERIENCE: 7,
    APP_EXPERIENCE: 7,
    DEMOGRAPHIC: 3,
    GENERAL: 5,
  } as const,
} as const;

// Type Types
export type SurveyTypeType = (typeof SURVEY_TYPE.TYPES)[keyof typeof SURVEY_TYPE.TYPES];

// Type Categories
export type SurveyTypeCategory =
  (typeof SURVEY_TYPE.CATEGORIES)[keyof typeof SURVEY_TYPE.CATEGORIES];

// Type Icons
export type SurveyTypeIcon = (typeof SURVEY_TYPE.ICONS)[keyof typeof SURVEY_TYPE.ICONS];

// Type Colors
export type SurveyTypeColor = (typeof SURVEY_TYPE.COLORS)[keyof typeof SURVEY_TYPE.COLORS];

// Utility Functions
export function surveyTypeGetLabel(type: SurveyTypeType): string {
  const labels: Record<SurveyTypeType, string> = {
    [SURVEY_TYPE.TYPES.CUSTOMER_SATISFACTION]: 'Customer Satisfaction',
    [SURVEY_TYPE.TYPES.NET_PROMOTER_SCORE]: 'Net Promoter Score',
    [SURVEY_TYPE.TYPES.PRODUCT_FEEDBACK]: 'Product Feedback',
    [SURVEY_TYPE.TYPES.SERVICE_QUALITY]: 'Service Quality',
    [SURVEY_TYPE.TYPES.EMPLOYEE_SATISFACTION]: 'Employee Satisfaction',
    [SURVEY_TYPE.TYPES.MARKET_RESEARCH]: 'Market Research',
    [SURVEY_TYPE.TYPES.EVENT_FEEDBACK]: 'Event Feedback',
    [SURVEY_TYPE.TYPES.WEBSITE_EXPERIENCE]: 'Website Experience',
    [SURVEY_TYPE.TYPES.APP_EXPERIENCE]: 'App Experience',
    [SURVEY_TYPE.TYPES.DEMOGRAPHIC]: 'Demographic',
    [SURVEY_TYPE.TYPES.GENERAL]: 'General',
  };
  return labels[type] || 'Unknown';
}

export function surveyTypeGetIcon(type: SurveyTypeType): SurveyTypeIcon {
  const icons: Record<SurveyTypeType, SurveyTypeIcon> = {
    [SURVEY_TYPE.TYPES.CUSTOMER_SATISFACTION]: SURVEY_TYPE.ICONS.CUSTOMER_SATISFACTION,
    [SURVEY_TYPE.TYPES.NET_PROMOTER_SCORE]: SURVEY_TYPE.ICONS.NET_PROMOTER_SCORE,
    [SURVEY_TYPE.TYPES.PRODUCT_FEEDBACK]: SURVEY_TYPE.ICONS.PRODUCT_FEEDBACK,
    [SURVEY_TYPE.TYPES.SERVICE_QUALITY]: SURVEY_TYPE.ICONS.SERVICE_QUALITY,
    [SURVEY_TYPE.TYPES.EMPLOYEE_SATISFACTION]: SURVEY_TYPE.ICONS.EMPLOYEE_SATISFACTION,
    [SURVEY_TYPE.TYPES.MARKET_RESEARCH]: SURVEY_TYPE.ICONS.MARKET_RESEARCH,
    [SURVEY_TYPE.TYPES.EVENT_FEEDBACK]: SURVEY_TYPE.ICONS.EVENT_FEEDBACK,
    [SURVEY_TYPE.TYPES.WEBSITE_EXPERIENCE]: SURVEY_TYPE.ICONS.WEBSITE_EXPERIENCE,
    [SURVEY_TYPE.TYPES.APP_EXPERIENCE]: SURVEY_TYPE.ICONS.APP_EXPERIENCE,
    [SURVEY_TYPE.TYPES.DEMOGRAPHIC]: SURVEY_TYPE.ICONS.DEMOGRAPHIC,
    [SURVEY_TYPE.TYPES.GENERAL]: SURVEY_TYPE.ICONS.GENERAL,
  };
  return icons[type] || '📋';
}

export function surveyTypeGetColor(type: SurveyTypeType): SurveyTypeColor {
  const colors: Record<SurveyTypeType, SurveyTypeColor> = {
    [SURVEY_TYPE.TYPES.CUSTOMER_SATISFACTION]: SURVEY_TYPE.COLORS.CUSTOMER_SATISFACTION,
    [SURVEY_TYPE.TYPES.NET_PROMOTER_SCORE]: SURVEY_TYPE.COLORS.NET_PROMOTER_SCORE,
    [SURVEY_TYPE.TYPES.PRODUCT_FEEDBACK]: SURVEY_TYPE.COLORS.PRODUCT_FEEDBACK,
    [SURVEY_TYPE.TYPES.SERVICE_QUALITY]: SURVEY_TYPE.COLORS.SERVICE_QUALITY,
    [SURVEY_TYPE.TYPES.EMPLOYEE_SATISFACTION]: SURVEY_TYPE.COLORS.EMPLOYEE_SATISFACTION,
    [SURVEY_TYPE.TYPES.MARKET_RESEARCH]: SURVEY_TYPE.COLORS.MARKET_RESEARCH,
    [SURVEY_TYPE.TYPES.EVENT_FEEDBACK]: SURVEY_TYPE.COLORS.EVENT_FEEDBACK,
    [SURVEY_TYPE.TYPES.WEBSITE_EXPERIENCE]: SURVEY_TYPE.COLORS.WEBSITE_EXPERIENCE,
    [SURVEY_TYPE.TYPES.APP_EXPERIENCE]: SURVEY_TYPE.COLORS.APP_EXPERIENCE,
    [SURVEY_TYPE.TYPES.DEMOGRAPHIC]: SURVEY_TYPE.COLORS.DEMOGRAPHIC,
    [SURVEY_TYPE.TYPES.GENERAL]: SURVEY_TYPE.COLORS.GENERAL,
  };
  return colors[type] || '#gray-400';
}

export function surveyTypeGetDuration(type: SurveyTypeType): number {
  const durations: Record<SurveyTypeType, number> = {
    [SURVEY_TYPE.TYPES.CUSTOMER_SATISFACTION]: SURVEY_TYPE.DURATIONS.CUSTOMER_SATISFACTION,
    [SURVEY_TYPE.TYPES.NET_PROMOTER_SCORE]: SURVEY_TYPE.DURATIONS.NET_PROMOTER_SCORE,
    [SURVEY_TYPE.TYPES.PRODUCT_FEEDBACK]: SURVEY_TYPE.DURATIONS.PRODUCT_FEEDBACK,
    [SURVEY_TYPE.TYPES.SERVICE_QUALITY]: SURVEY_TYPE.DURATIONS.SERVICE_QUALITY,
    [SURVEY_TYPE.TYPES.EMPLOYEE_SATISFACTION]: SURVEY_TYPE.DURATIONS.EMPLOYEE_SATISFACTION,
    [SURVEY_TYPE.TYPES.MARKET_RESEARCH]: SURVEY_TYPE.DURATIONS.MARKET_RESEARCH,
    [SURVEY_TYPE.TYPES.EVENT_FEEDBACK]: SURVEY_TYPE.DURATIONS.EVENT_FEEDBACK,
    [SURVEY_TYPE.TYPES.WEBSITE_EXPERIENCE]: SURVEY_TYPE.DURATIONS.WEBSITE_EXPERIENCE,
    [SURVEY_TYPE.TYPES.APP_EXPERIENCE]: SURVEY_TYPE.DURATIONS.APP_EXPERIENCE,
    [SURVEY_TYPE.TYPES.DEMOGRAPHIC]: SURVEY_TYPE.DURATIONS.DEMOGRAPHIC,
    [SURVEY_TYPE.TYPES.GENERAL]: SURVEY_TYPE.DURATIONS.GENERAL,
  };
  return durations[type] || 5;
}

export function surveyTypeGetCategory(type: SurveyTypeType): SurveyTypeCategory {
  const categories: Record<SurveyTypeType, SurveyTypeCategory> = {
    [SURVEY_TYPE.TYPES.CUSTOMER_SATISFACTION]: SURVEY_TYPE.CATEGORIES.SATISFACTION,
    [SURVEY_TYPE.TYPES.NET_PROMOTER_SCORE]: SURVEY_TYPE.CATEGORIES.SATISFACTION,
    [SURVEY_TYPE.TYPES.PRODUCT_FEEDBACK]: SURVEY_TYPE.CATEGORIES.FEEDBACK,
    [SURVEY_TYPE.TYPES.SERVICE_QUALITY]: SURVEY_TYPE.CATEGORIES.SATISFACTION,
    [SURVEY_TYPE.TYPES.EMPLOYEE_SATISFACTION]: SURVEY_TYPE.CATEGORIES.SATISFACTION,
    [SURVEY_TYPE.TYPES.MARKET_RESEARCH]: SURVEY_TYPE.CATEGORIES.RESEARCH,
    [SURVEY_TYPE.TYPES.EVENT_FEEDBACK]: SURVEY_TYPE.CATEGORIES.FEEDBACK,
    [SURVEY_TYPE.TYPES.WEBSITE_EXPERIENCE]: SURVEY_TYPE.CATEGORIES.EXPERIENCE,
    [SURVEY_TYPE.TYPES.APP_EXPERIENCE]: SURVEY_TYPE.CATEGORIES.EXPERIENCE,
    [SURVEY_TYPE.TYPES.DEMOGRAPHIC]: SURVEY_TYPE.CATEGORIES.RESEARCH,
    [SURVEY_TYPE.TYPES.GENERAL]: SURVEY_TYPE.CATEGORIES.FEEDBACK,
  };
  return categories[type] || SURVEY_TYPE.CATEGORIES.FEEDBACK;
}
