/**
 * Permission Constants - Pure immutable permission keys
 * Enterprise Grade for vubon.com.bd - Bangladesh's #1 E-commerce
 *
 * @module shared-constants/permission.constants
 *
 * RULES:
 * ✅ NO permission resolver, authorization logic
 * ✅ NO functions (Object.values, etc.)
 * ✅ NO imports from other layers
 * ✅ ONLY pure readonly constants
 */

// ============================================================
// Type Utilities
// ============================================================
export type ValueOf<T> = T[keyof T];
export type ReadonlyDeep<T> = {
  readonly [P in keyof T]: ReadonlyDeep<T[P]>;
};

// ============================================================
// Core Permissions (Resource:action format)
// ============================================================
export const PERMISSIONS = {
  // ========== User Management ==========
  USER_CREATE: 'user:create',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  USER_LIST: 'user:list',
  USER_SUSPEND: 'user:suspend',
  USER_ACTIVATE: 'user:activate',
  USER_IMPERSONATE: 'user:impersonate',
  USER_EXPORT: 'user:export',

  // ========== Role Management ==========
  ROLE_CREATE: 'role:create',
  ROLE_READ: 'role:read',
  ROLE_UPDATE: 'role:update',
  ROLE_DELETE: 'role:delete',
  ROLE_ASSIGN: 'role:assign',
  ROLE_REVOKE: 'role:revoke',

  // ========== Permission Management ==========
  PERMISSION_CREATE: 'permission:create',
  PERMISSION_READ: 'permission:read',
  PERMISSION_UPDATE: 'permission:update',
  PERMISSION_DELETE: 'permission:delete',
  PERMISSION_ASSIGN: 'permission:assign',
  PERMISSION_REVOKE: 'permission:revoke',

  // ========== Product Management ==========
  PRODUCT_CREATE: 'product:create',
  PRODUCT_READ: 'product:read',
  PRODUCT_UPDATE: 'product:update',
  PRODUCT_DELETE: 'product:delete',
  PRODUCT_LIST: 'product:list',
  PRODUCT_PUBLISH: 'product:publish',
  PRODUCT_UNPUBLISH: 'product:unpublish',
  PRODUCT_APPROVE: 'product:approve',
  PRODUCT_REJECT: 'product:reject',
  PRODUCT_FEATURE: 'product:feature',
  PRODUCT_EXPORT: 'product:export',
  PRODUCT_IMPORT: 'product:import',
  PRODUCT_BULK_UPDATE: 'product:bulk_update',

  // ========== Category Management ==========
  CATEGORY_CREATE: 'category:create',
  CATEGORY_READ: 'category:read',
  CATEGORY_UPDATE: 'category:update',
  CATEGORY_DELETE: 'category:delete',
  CATEGORY_SORT: 'category:sort',

  // ========== Brand Management ==========
  BRAND_CREATE: 'brand:create',
  BRAND_READ: 'brand:read',
  BRAND_UPDATE: 'brand:update',
  BRAND_DELETE: 'brand:delete',

  // ========== Order Management ==========
  ORDER_CREATE: 'order:create',
  ORDER_READ: 'order:read',
  ORDER_UPDATE: 'order:update',
  ORDER_DELETE: 'order:delete',
  ORDER_LIST: 'order:list',
  ORDER_CANCEL: 'order:cancel',
  ORDER_REFUND: 'order:refund',
  ORDER_APPROVE: 'order:approve',
  ORDER_SHIP: 'order:ship',
  ORDER_DELIVER: 'order:deliver',
  ORDER_EXPORT: 'order:export',
  ORDER_BULK_STATUS: 'order:bulk_status',

  // ========== Payment Management ==========
  PAYMENT_CREATE: 'payment:create',
  PAYMENT_READ: 'payment:read',
  PAYMENT_UPDATE: 'payment:update',
  PAYMENT_REFUND: 'payment:refund',
  PAYMENT_VOID: 'payment:void',
  PAYMENT_CAPTURE: 'payment:capture',
  PAYMENT_VERIFY: 'payment:verify',

  // ========== Inventory Management ==========
  INVENTORY_READ: 'inventory:read',
  INVENTORY_UPDATE: 'inventory:update',
  INVENTORY_ADJUST: 'inventory:adjust',
  INVENTORY_LOW_STOCK_ALERT: 'inventory:low_stock_alert',
  INVENTORY_BULK_UPDATE: 'inventory:bulk_update',

  // ========== Review Management ==========
  REVIEW_CREATE: 'review:create',
  REVIEW_READ: 'review:read',
  REVIEW_UPDATE: 'review:update',
  REVIEW_DELETE: 'review:delete',
  REVIEW_MODERATE: 'review:moderate',
  REVIEW_REPORT: 'review:report',

  // ========== Coupon Management ==========
  COUPON_CREATE: 'coupon:create',
  COUPON_READ: 'coupon:read',
  COUPON_UPDATE: 'coupon:update',
  COUPON_DELETE: 'coupon:delete',
  COUPON_APPLY: 'coupon:apply',

  // ========== Offer Management ==========
  OFFER_CREATE: 'offer:create',
  OFFER_READ: 'offer:read',
  OFFER_UPDATE: 'offer:update',
  OFFER_DELETE: 'offer:delete',
  FLASH_SALE_MANAGE: 'flash_sale:manage',

  // ========== Cart & Wishlist ==========
  CART_READ: 'cart:read',
  CART_UPDATE: 'cart:update',
  CART_CLEAR: 'cart:clear',
  WISHLIST_READ: 'wishlist:read',
  WISHLIST_UPDATE: 'wishlist:update',

  // ========== Shipping Management ==========
  SHIPPING_ZONE_READ: 'shipping_zone:read',
  SHIPPING_ZONE_CREATE: 'shipping_zone:create',
  SHIPPING_ZONE_UPDATE: 'shipping_zone:update',
  SHIPPING_ZONE_DELETE: 'shipping_zone:delete',
  SHIPPING_COST_MANAGE: 'shipping_cost:manage',
  SHIPPING_TRACK: 'shipping:track',

  // ========== Analytics & Reports ==========
  ANALYTICS_READ: 'analytics:read',
  ANALYTICS_SALES: 'analytics:sales',
  ANALYTICS_VISITORS: 'analytics:visitors',
  ANALYTICS_CONVERSION: 'analytics:conversion',
  REPORTS_GENERATE: 'reports:generate',
  EXPORT_DATA: 'export:data',
  IMPORT_DATA: 'import:data',

  // ========== System Management ==========
  SYSTEM_CONFIG_READ: 'system:config:read',
  SYSTEM_CONFIG_UPDATE: 'system:config:update',
  SYSTEM_LOGS_READ: 'system:logs:read',
  SYSTEM_CACHE_CLEAR: 'system:cache:clear',
  SYSTEM_QUEUE_MANAGE: 'system:queue:manage',
  SYSTEM_BACKUP: 'system:backup',
  SYSTEM_RESTORE: 'system:restore',
  SYSTEM_MONITOR: 'system:monitor',

  // ========== Shop/Seller Management ==========
  SHOP_CREATE: 'shop:create',
  SHOP_READ: 'shop:read',
  SHOP_UPDATE: 'shop:update',
  SHOP_DELETE: 'shop:delete',
  SHOP_SETTINGS: 'shop:settings',
  SHOP_VERIFY: 'shop:verify',
  SHOP_SUSPEND: 'shop:suspend',

  // ========== Vendor Management ==========
  VENDOR_READ: 'vendor:read',
  VENDOR_UPDATE: 'vendor:update',
  VENDOR_VERIFY: 'vendor:verify',
  VENDOR_PAYOUT: 'vendor:payout',
  VENDOR_COMMISSION_UPDATE: 'vendor:commission:update',

  // ========== Bangladesh Specific ==========
  MFS_PAYMENT_MANAGE: 'mfs:payment:manage',
  DISTRICT_MANAGE: 'district:manage',
  LOCAL_DELIVERY_MANAGE: 'local_delivery:manage',

  // ========== Support & Ticket ==========
  TICKET_CREATE: 'ticket:create',
  TICKET_READ: 'ticket:read',
  TICKET_UPDATE: 'ticket:update',
  TICKET_RESOLVE: 'ticket:resolve',
  TICKET_ASSIGN: 'ticket:assign',

  // ========== Notification Management ==========
  NOTIFICATION_SEND: 'notification:send',
  NOTIFICATION_BROADCAST: 'notification:broadcast',
  NOTIFICATION_READ: 'notification:read',

  // ========== Audit & Compliance ==========
  AUDIT_LOG_READ: 'audit:log:read',
  AUDIT_LOG_EXPORT: 'audit:log:export',
  COMPLIANCE_REVIEW: 'compliance:review',
} as const;

export type Permission = ValueOf<typeof PERMISSIONS>;

// ============================================================
// Permission Groups (Pure arrays - NO Object.values)
// ============================================================
export const PERMISSION_GROUPS = {
  USER_MANAGEMENT: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_LIST,
    PERMISSIONS.USER_SUSPEND,
    PERMISSIONS.USER_ACTIVATE,
    PERMISSIONS.USER_IMPERSONATE,
    PERMISSIONS.USER_EXPORT,
  ] as const,

  ROLE_MANAGEMENT: [
    PERMISSIONS.ROLE_CREATE,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.ROLE_UPDATE,
    PERMISSIONS.ROLE_DELETE,
    PERMISSIONS.ROLE_ASSIGN,
    PERMISSIONS.ROLE_REVOKE,
  ] as const,

  PERMISSION_MANAGEMENT: [
    PERMISSIONS.PERMISSION_CREATE,
    PERMISSIONS.PERMISSION_READ,
    PERMISSIONS.PERMISSION_UPDATE,
    PERMISSIONS.PERMISSION_DELETE,
    PERMISSIONS.PERMISSION_ASSIGN,
    PERMISSIONS.PERMISSION_REVOKE,
  ] as const,

  PRODUCT_MANAGEMENT: [
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.PRODUCT_LIST,
    PERMISSIONS.PRODUCT_PUBLISH,
    PERMISSIONS.PRODUCT_UNPUBLISH,
    PERMISSIONS.PRODUCT_APPROVE,
    PERMISSIONS.PRODUCT_REJECT,
    PERMISSIONS.PRODUCT_FEATURE,
    PERMISSIONS.PRODUCT_EXPORT,
    PERMISSIONS.PRODUCT_IMPORT,
    PERMISSIONS.PRODUCT_BULK_UPDATE,
  ] as const,

  CATEGORY_MANAGEMENT: [
    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CATEGORY_UPDATE,
    PERMISSIONS.CATEGORY_DELETE,
    PERMISSIONS.CATEGORY_SORT,
  ] as const,

  BRAND_MANAGEMENT: [
    PERMISSIONS.BRAND_CREATE,
    PERMISSIONS.BRAND_READ,
    PERMISSIONS.BRAND_UPDATE,
    PERMISSIONS.BRAND_DELETE,
  ] as const,

  ORDER_MANAGEMENT: [
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.ORDER_DELETE,
    PERMISSIONS.ORDER_LIST,
    PERMISSIONS.ORDER_CANCEL,
    PERMISSIONS.ORDER_REFUND,
    PERMISSIONS.ORDER_APPROVE,
    PERMISSIONS.ORDER_SHIP,
    PERMISSIONS.ORDER_DELIVER,
    PERMISSIONS.ORDER_EXPORT,
    PERMISSIONS.ORDER_BULK_STATUS,
  ] as const,

  PAYMENT_MANAGEMENT: [
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_UPDATE,
    PERMISSIONS.PAYMENT_REFUND,
    PERMISSIONS.PAYMENT_VOID,
    PERMISSIONS.PAYMENT_CAPTURE,
    PERMISSIONS.PAYMENT_VERIFY,
  ] as const,

  INVENTORY_MANAGEMENT: [
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_LOW_STOCK_ALERT,
    PERMISSIONS.INVENTORY_BULK_UPDATE,
  ] as const,

  REVIEW_MANAGEMENT: [
    PERMISSIONS.REVIEW_CREATE,
    PERMISSIONS.REVIEW_READ,
    PERMISSIONS.REVIEW_UPDATE,
    PERMISSIONS.REVIEW_DELETE,
    PERMISSIONS.REVIEW_MODERATE,
    PERMISSIONS.REVIEW_REPORT,
  ] as const,

  COUPON_MANAGEMENT: [
    PERMISSIONS.COUPON_CREATE,
    PERMISSIONS.COUPON_READ,
    PERMISSIONS.COUPON_UPDATE,
    PERMISSIONS.COUPON_DELETE,
    PERMISSIONS.COUPON_APPLY,
  ] as const,

  OFFER_MANAGEMENT: [
    PERMISSIONS.OFFER_CREATE,
    PERMISSIONS.OFFER_READ,
    PERMISSIONS.OFFER_UPDATE,
    PERMISSIONS.OFFER_DELETE,
    PERMISSIONS.FLASH_SALE_MANAGE,
  ] as const,

  CART_MANAGEMENT: [
    PERMISSIONS.CART_READ,
    PERMISSIONS.CART_UPDATE,
    PERMISSIONS.CART_CLEAR,
  ] as const,

  WISHLIST_MANAGEMENT: [
    PERMISSIONS.WISHLIST_READ,
    PERMISSIONS.WISHLIST_UPDATE,
  ] as const,

  SHIPPING_MANAGEMENT: [
    PERMISSIONS.SHIPPING_ZONE_READ,
    PERMISSIONS.SHIPPING_ZONE_CREATE,
    PERMISSIONS.SHIPPING_ZONE_UPDATE,
    PERMISSIONS.SHIPPING_ZONE_DELETE,
    PERMISSIONS.SHIPPING_COST_MANAGE,
    PERMISSIONS.SHIPPING_TRACK,
  ] as const,

  ANALYTICS_AND_REPORTS: [
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ANALYTICS_SALES,
    PERMISSIONS.ANALYTICS_VISITORS,
    PERMISSIONS.ANALYTICS_CONVERSION,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.EXPORT_DATA,
    PERMISSIONS.IMPORT_DATA,
  ] as const,

  SYSTEM_MANAGEMENT: [
    PERMISSIONS.SYSTEM_CONFIG_READ,
    PERMISSIONS.SYSTEM_CONFIG_UPDATE,
    PERMISSIONS.SYSTEM_LOGS_READ,
    PERMISSIONS.SYSTEM_CACHE_CLEAR,
    PERMISSIONS.SYSTEM_QUEUE_MANAGE,
    PERMISSIONS.SYSTEM_BACKUP,
    PERMISSIONS.SYSTEM_RESTORE,
    PERMISSIONS.SYSTEM_MONITOR,
  ] as const,

  SHOP_MANAGEMENT: [
    PERMISSIONS.SHOP_CREATE,
    PERMISSIONS.SHOP_READ,
    PERMISSIONS.SHOP_UPDATE,
    PERMISSIONS.SHOP_DELETE,
    PERMISSIONS.SHOP_SETTINGS,
    PERMISSIONS.SHOP_VERIFY,
    PERMISSIONS.SHOP_SUSPEND,
  ] as const,

  VENDOR_MANAGEMENT: [
    PERMISSIONS.VENDOR_READ,
    PERMISSIONS.VENDOR_UPDATE,
    PERMISSIONS.VENDOR_VERIFY,
    PERMISSIONS.VENDOR_PAYOUT,
    PERMISSIONS.VENDOR_COMMISSION_UPDATE,
  ] as const,

  BANGLADESH_SPECIFIC: [
    PERMISSIONS.MFS_PAYMENT_MANAGE,
    PERMISSIONS.DISTRICT_MANAGE,
    PERMISSIONS.LOCAL_DELIVERY_MANAGE,
  ] as const,

  SUPPORT_MANAGEMENT: [
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_READ,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_RESOLVE,
    PERMISSIONS.TICKET_ASSIGN,
  ] as const,

  NOTIFICATION_MANAGEMENT: [
    PERMISSIONS.NOTIFICATION_SEND,
    PERMISSIONS.NOTIFICATION_BROADCAST,
    PERMISSIONS.NOTIFICATION_READ,
  ] as const,

  AUDIT_MANAGEMENT: [
    PERMISSIONS.AUDIT_LOG_READ,
    PERMISSIONS.AUDIT_LOG_EXPORT,
    PERMISSIONS.COMPLIANCE_REVIEW,
  ] as const,
} as const;

export type PermissionGroup = ValueOf<typeof PERMISSION_GROUPS>;

// ============================================================
// All Permissions List (Pure array - Pre-computed, NO functions)
// ============================================================
export const ALL_PERMISSIONS = [
  ...PERMISSION_GROUPS.USER_MANAGEMENT,
  ...PERMISSION_GROUPS.ROLE_MANAGEMENT,
  ...PERMISSION_GROUPS.PERMISSION_MANAGEMENT,
  ...PERMISSION_GROUPS.PRODUCT_MANAGEMENT,
  ...PERMISSION_GROUPS.CATEGORY_MANAGEMENT,
  ...PERMISSION_GROUPS.BRAND_MANAGEMENT,
  ...PERMISSION_GROUPS.ORDER_MANAGEMENT,
  ...PERMISSION_GROUPS.PAYMENT_MANAGEMENT,
  ...PERMISSION_GROUPS.INVENTORY_MANAGEMENT,
  ...PERMISSION_GROUPS.REVIEW_MANAGEMENT,
  ...PERMISSION_GROUPS.COUPON_MANAGEMENT,
  ...PERMISSION_GROUPS.OFFER_MANAGEMENT,
  ...PERMISSION_GROUPS.CART_MANAGEMENT,
  ...PERMISSION_GROUPS.WISHLIST_MANAGEMENT,
  ...PERMISSION_GROUPS.SHIPPING_MANAGEMENT,
  ...PERMISSION_GROUPS.ANALYTICS_AND_REPORTS,
  ...PERMISSION_GROUPS.SYSTEM_MANAGEMENT,
  ...PERMISSION_GROUPS.SHOP_MANAGEMENT,
  ...PERMISSION_GROUPS.VENDOR_MANAGEMENT,
  ...PERMISSION_GROUPS.BANGLADESH_SPECIFIC,
  ...PERMISSION_GROUPS.SUPPORT_MANAGEMENT,
  ...PERMISSION_GROUPS.NOTIFICATION_MANAGEMENT,
  ...PERMISSION_GROUPS.AUDIT_MANAGEMENT,
] as const;

export type AllPermissions = typeof ALL_PERMISSIONS;

// ============================================================
// Permission Categories (For UI grouping)
// ============================================================
export const PERMISSION_CATEGORIES = {
  USER: 'User Management',
  ROLE: 'Role Management',
  PERMISSION: 'Permission Management',
  PRODUCT: 'Product Management',
  CATEGORY: 'Category Management',
  BRAND: 'Brand Management',
  ORDER: 'Order Management',
  PAYMENT: 'Payment Management',
  INVENTORY: 'Inventory Management',
  REVIEW: 'Review Management',
  COUPON: 'Coupon Management',
  OFFER: 'Offer Management',
  CART: 'Cart Management',
  WISHLIST: 'Wishlist Management',
  SHIPPING: 'Shipping Management',
  ANALYTICS: 'Analytics & Reports',
  SYSTEM: 'System Management',
  SHOP: 'Shop Management',
  VENDOR: 'Vendor Management',
  BANGLADESH: 'Bangladesh Specific',
  SUPPORT: 'Support & Tickets',
  NOTIFICATION: 'Notification Management',
  AUDIT: 'Audit & Compliance',
} as const;

export type PermissionCategory = ValueOf<typeof PERMISSION_CATEGORIES>;

// ============================================================
// Permission to Category Mapping
// ============================================================
export const PERMISSION_TO_CATEGORY = {
  // User Management
  [PERMISSIONS.USER_CREATE]: PERMISSION_CATEGORIES.USER,
  [PERMISSIONS.USER_READ]: PERMISSION_CATEGORIES.USER,
  [PERMISSIONS.USER_UPDATE]: PERMISSION_CATEGORIES.USER,
  [PERMISSIONS.USER_DELETE]: PERMISSION_CATEGORIES.USER,
  [PERMISSIONS.USER_LIST]: PERMISSION_CATEGORIES.USER,
  [PERMISSIONS.USER_SUSPEND]: PERMISSION_CATEGORIES.USER,
  [PERMISSIONS.USER_ACTIVATE]: PERMISSION_CATEGORIES.USER,
  [PERMISSIONS.USER_IMPERSONATE]: PERMISSION_CATEGORIES.USER,
  [PERMISSIONS.USER_EXPORT]: PERMISSION_CATEGORIES.USER,

  // Role Management
  [PERMISSIONS.ROLE_CREATE]: PERMISSION_CATEGORIES.ROLE,
  [PERMISSIONS.ROLE_READ]: PERMISSION_CATEGORIES.ROLE,
  [PERMISSIONS.ROLE_UPDATE]: PERMISSION_CATEGORIES.ROLE,
  [PERMISSIONS.ROLE_DELETE]: PERMISSION_CATEGORIES.ROLE,
  [PERMISSIONS.ROLE_ASSIGN]: PERMISSION_CATEGORIES.ROLE,
  [PERMISSIONS.ROLE_REVOKE]: PERMISSION_CATEGORIES.ROLE,

  // Permission Management
  [PERMISSIONS.PERMISSION_CREATE]: PERMISSION_CATEGORIES.PERMISSION,
  [PERMISSIONS.PERMISSION_READ]: PERMISSION_CATEGORIES.PERMISSION,
  [PERMISSIONS.PERMISSION_UPDATE]: PERMISSION_CATEGORIES.PERMISSION,
  [PERMISSIONS.PERMISSION_DELETE]: PERMISSION_CATEGORIES.PERMISSION,
  [PERMISSIONS.PERMISSION_ASSIGN]: PERMISSION_CATEGORIES.PERMISSION,
  [PERMISSIONS.PERMISSION_REVOKE]: PERMISSION_CATEGORIES.PERMISSION,

  // Product Management
  [PERMISSIONS.PRODUCT_CREATE]: PERMISSION_CATEGORIES.PRODUCT,
  [PERMISSIONS.PRODUCT_READ]: PERMISSION_CATEGORIES.PRODUCT,
  [PERMISSIONS.PRODUCT_UPDATE]: PERMISSION_CATEGORIES.PRODUCT,
  [PERMISSIONS.PRODUCT_DELETE]: PERMISSION_CATEGORIES.PRODUCT,
  [PERMISSIONS.PRODUCT_LIST]: PERMISSION_CATEGORIES.PRODUCT,
  [PERMISSIONS.PRODUCT_PUBLISH]: PERMISSION_CATEGORIES.PRODUCT,
  [PERMISSIONS.PRODUCT_UNPUBLISH]: PERMISSION_CATEGORIES.PRODUCT,
  [PERMISSIONS.PRODUCT_APPROVE]: PERMISSION_CATEGORIES.PRODUCT,
  [PERMISSIONS.PRODUCT_REJECT]: PERMISSION_CATEGORIES.PRODUCT,
  [PERMISSIONS.PRODUCT_FEATURE]: PERMISSION_CATEGORIES.PRODUCT,
  [PERMISSIONS.PRODUCT_EXPORT]: PERMISSION_CATEGORIES.PRODUCT,
  [PERMISSIONS.PRODUCT_IMPORT]: PERMISSION_CATEGORIES.PRODUCT,
  [PERMISSIONS.PRODUCT_BULK_UPDATE]: PERMISSION_CATEGORIES.PRODUCT,

  // Category Management
  [PERMISSIONS.CATEGORY_CREATE]: PERMISSION_CATEGORIES.CATEGORY,
  [PERMISSIONS.CATEGORY_READ]: PERMISSION_CATEGORIES.CATEGORY,
  [PERMISSIONS.CATEGORY_UPDATE]: PERMISSION_CATEGORIES.CATEGORY,
  [PERMISSIONS.CATEGORY_DELETE]: PERMISSION_CATEGORIES.CATEGORY,
  [PERMISSIONS.CATEGORY_SORT]: PERMISSION_CATEGORIES.CATEGORY,

  // Brand Management
  [PERMISSIONS.BRAND_CREATE]: PERMISSION_CATEGORIES.BRAND,
  [PERMISSIONS.BRAND_READ]: PERMISSION_CATEGORIES.BRAND,
  [PERMISSIONS.BRAND_UPDATE]: PERMISSION_CATEGORIES.BRAND,
  [PERMISSIONS.BRAND_DELETE]: PERMISSION_CATEGORIES.BRAND,

  // Order Management
  [PERMISSIONS.ORDER_CREATE]: PERMISSION_CATEGORIES.ORDER,
  [PERMISSIONS.ORDER_READ]: PERMISSION_CATEGORIES.ORDER,
  [PERMISSIONS.ORDER_UPDATE]: PERMISSION_CATEGORIES.ORDER,
  [PERMISSIONS.ORDER_DELETE]: PERMISSION_CATEGORIES.ORDER,
  [PERMISSIONS.ORDER_LIST]: PERMISSION_CATEGORIES.ORDER,
  [PERMISSIONS.ORDER_CANCEL]: PERMISSION_CATEGORIES.ORDER,
  [PERMISSIONS.ORDER_REFUND]: PERMISSION_CATEGORIES.ORDER,
  [PERMISSIONS.ORDER_APPROVE]: PERMISSION_CATEGORIES.ORDER,
  [PERMISSIONS.ORDER_SHIP]: PERMISSION_CATEGORIES.ORDER,
  [PERMISSIONS.ORDER_DELIVER]: PERMISSION_CATEGORIES.ORDER,
  [PERMISSIONS.ORDER_EXPORT]: PERMISSION_CATEGORIES.ORDER,
  [PERMISSIONS.ORDER_BULK_STATUS]: PERMISSION_CATEGORIES.ORDER,

  // Payment Management
  [PERMISSIONS.PAYMENT_CREATE]: PERMISSION_CATEGORIES.PAYMENT,
  [PERMISSIONS.PAYMENT_READ]: PERMISSION_CATEGORIES.PAYMENT,
  [PERMISSIONS.PAYMENT_UPDATE]: PERMISSION_CATEGORIES.PAYMENT,
  [PERMISSIONS.PAYMENT_REFUND]: PERMISSION_CATEGORIES.PAYMENT,
  [PERMISSIONS.PAYMENT_VOID]: PERMISSION_CATEGORIES.PAYMENT,
  [PERMISSIONS.PAYMENT_CAPTURE]: PERMISSION_CATEGORIES.PAYMENT,
  [PERMISSIONS.PAYMENT_VERIFY]: PERMISSION_CATEGORIES.PAYMENT,

  // Inventory Management
  [PERMISSIONS.INVENTORY_READ]: PERMISSION_CATEGORIES.INVENTORY,
  [PERMISSIONS.INVENTORY_UPDATE]: PERMISSION_CATEGORIES.INVENTORY,
  [PERMISSIONS.INVENTORY_ADJUST]: PERMISSION_CATEGORIES.INVENTORY,
  [PERMISSIONS.INVENTORY_LOW_STOCK_ALERT]: PERMISSION_CATEGORIES.INVENTORY,
  [PERMISSIONS.INVENTORY_BULK_UPDATE]: PERMISSION_CATEGORIES.INVENTORY,

  // Review Management
  [PERMISSIONS.REVIEW_CREATE]: PERMISSION_CATEGORIES.REVIEW,
  [PERMISSIONS.REVIEW_READ]: PERMISSION_CATEGORIES.REVIEW,
  [PERMISSIONS.REVIEW_UPDATE]: PERMISSION_CATEGORIES.REVIEW,
  [PERMISSIONS.REVIEW_DELETE]: PERMISSION_CATEGORIES.REVIEW,
  [PERMISSIONS.REVIEW_MODERATE]: PERMISSION_CATEGORIES.REVIEW,
  [PERMISSIONS.REVIEW_REPORT]: PERMISSION_CATEGORIES.REVIEW,

  // Coupon Management
  [PERMISSIONS.COUPON_CREATE]: PERMISSION_CATEGORIES.COUPON,
  [PERMISSIONS.COUPON_READ]: PERMISSION_CATEGORIES.COUPON,
  [PERMISSIONS.COUPON_UPDATE]: PERMISSION_CATEGORIES.COUPON,
  [PERMISSIONS.COUPON_DELETE]: PERMISSION_CATEGORIES.COUPON,
  [PERMISSIONS.COUPON_APPLY]: PERMISSION_CATEGORIES.COUPON,

  // Offer Management
  [PERMISSIONS.OFFER_CREATE]: PERMISSION_CATEGORIES.OFFER,
  [PERMISSIONS.OFFER_READ]: PERMISSION_CATEGORIES.OFFER,
  [PERMISSIONS.OFFER_UPDATE]: PERMISSION_CATEGORIES.OFFER,
  [PERMISSIONS.OFFER_DELETE]: PERMISSION_CATEGORIES.OFFER,
  [PERMISSIONS.FLASH_SALE_MANAGE]: PERMISSION_CATEGORIES.OFFER,

  // Cart & Wishlist
  [PERMISSIONS.CART_READ]: PERMISSION_CATEGORIES.CART,
  [PERMISSIONS.CART_UPDATE]: PERMISSION_CATEGORIES.CART,
  [PERMISSIONS.CART_CLEAR]: PERMISSION_CATEGORIES.CART,
  [PERMISSIONS.WISHLIST_READ]: PERMISSION_CATEGORIES.WISHLIST,
  [PERMISSIONS.WISHLIST_UPDATE]: PERMISSION_CATEGORIES.WISHLIST,

  // Shipping Management
  [PERMISSIONS.SHIPPING_ZONE_READ]: PERMISSION_CATEGORIES.SHIPPING,
  [PERMISSIONS.SHIPPING_ZONE_CREATE]: PERMISSION_CATEGORIES.SHIPPING,
  [PERMISSIONS.SHIPPING_ZONE_UPDATE]: PERMISSION_CATEGORIES.SHIPPING,
  [PERMISSIONS.SHIPPING_ZONE_DELETE]: PERMISSION_CATEGORIES.SHIPPING,
  [PERMISSIONS.SHIPPING_COST_MANAGE]: PERMISSION_CATEGORIES.SHIPPING,
  [PERMISSIONS.SHIPPING_TRACK]: PERMISSION_CATEGORIES.SHIPPING,

  // Analytics & Reports
  [PERMISSIONS.ANALYTICS_READ]: PERMISSION_CATEGORIES.ANALYTICS,
  [PERMISSIONS.ANALYTICS_SALES]: PERMISSION_CATEGORIES.ANALYTICS,
  [PERMISSIONS.ANALYTICS_VISITORS]: PERMISSION_CATEGORIES.ANALYTICS,
  [PERMISSIONS.ANALYTICS_CONVERSION]: PERMISSION_CATEGORIES.ANALYTICS,
  [PERMISSIONS.REPORTS_GENERATE]: PERMISSION_CATEGORIES.ANALYTICS,
  [PERMISSIONS.EXPORT_DATA]: PERMISSION_CATEGORIES.ANALYTICS,
  [PERMISSIONS.IMPORT_DATA]: PERMISSION_CATEGORIES.ANALYTICS,

  // System Management
  [PERMISSIONS.SYSTEM_CONFIG_READ]: PERMISSION_CATEGORIES.SYSTEM,
  [PERMISSIONS.SYSTEM_CONFIG_UPDATE]: PERMISSION_CATEGORIES.SYSTEM,
  [PERMISSIONS.SYSTEM_LOGS_READ]: PERMISSION_CATEGORIES.SYSTEM,
  [PERMISSIONS.SYSTEM_CACHE_CLEAR]: PERMISSION_CATEGORIES.SYSTEM,
  [PERMISSIONS.SYSTEM_QUEUE_MANAGE]: PERMISSION_CATEGORIES.SYSTEM,
  [PERMISSIONS.SYSTEM_BACKUP]: PERMISSION_CATEGORIES.SYSTEM,
  [PERMISSIONS.SYSTEM_RESTORE]: PERMISSION_CATEGORIES.SYSTEM,
  [PERMISSIONS.SYSTEM_MONITOR]: PERMISSION_CATEGORIES.SYSTEM,

  // Shop Management
  [PERMISSIONS.SHOP_CREATE]: PERMISSION_CATEGORIES.SHOP,
  [PERMISSIONS.SHOP_READ]: PERMISSION_CATEGORIES.SHOP,
  [PERMISSIONS.SHOP_UPDATE]: PERMISSION_CATEGORIES.SHOP,
  [PERMISSIONS.SHOP_DELETE]: PERMISSION_CATEGORIES.SHOP,
  [PERMISSIONS.SHOP_SETTINGS]: PERMISSION_CATEGORIES.SHOP,
  [PERMISSIONS.SHOP_VERIFY]: PERMISSION_CATEGORIES.SHOP,
  [PERMISSIONS.SHOP_SUSPEND]: PERMISSION_CATEGORIES.SHOP,

  // Vendor Management
  [PERMISSIONS.VENDOR_READ]: PERMISSION_CATEGORIES.VENDOR,
  [PERMISSIONS.VENDOR_UPDATE]: PERMISSION_CATEGORIES.VENDOR,
  [PERMISSIONS.VENDOR_VERIFY]: PERMISSION_CATEGORIES.VENDOR,
  [PERMISSIONS.VENDOR_PAYOUT]: PERMISSION_CATEGORIES.VENDOR,
  [PERMISSIONS.VENDOR_COMMISSION_UPDATE]: PERMISSION_CATEGORIES.VENDOR,

  // Bangladesh Specific
  [PERMISSIONS.MFS_PAYMENT_MANAGE]: PERMISSION_CATEGORIES.BANGLADESH,
  [PERMISSIONS.DISTRICT_MANAGE]: PERMISSION_CATEGORIES.BANGLADESH,
  [PERMISSIONS.LOCAL_DELIVERY_MANAGE]: PERMISSION_CATEGORIES.BANGLADESH,

  // Support & Ticket
  [PERMISSIONS.TICKET_CREATE]: PERMISSION_CATEGORIES.SUPPORT,
  [PERMISSIONS.TICKET_READ]: PERMISSION_CATEGORIES.SUPPORT,
  [PERMISSIONS.TICKET_UPDATE]: PERMISSION_CATEGORIES.SUPPORT,
  [PERMISSIONS.TICKET_RESOLVE]: PERMISSION_CATEGORIES.SUPPORT,
  [PERMISSIONS.TICKET_ASSIGN]: PERMISSION_CATEGORIES.SUPPORT,

  // Notification Management
  [PERMISSIONS.NOTIFICATION_SEND]: PERMISSION_CATEGORIES.NOTIFICATION,
  [PERMISSIONS.NOTIFICATION_BROADCAST]: PERMISSION_CATEGORIES.NOTIFICATION,
  [PERMISSIONS.NOTIFICATION_READ]: PERMISSION_CATEGORIES.NOTIFICATION,

  // Audit & Compliance
  [PERMISSIONS.AUDIT_LOG_READ]: PERMISSION_CATEGORIES.AUDIT,
  [PERMISSIONS.AUDIT_LOG_EXPORT]: PERMISSION_CATEGORIES.AUDIT,
  [PERMISSIONS.COMPLIANCE_REVIEW]: PERMISSION_CATEGORIES.AUDIT,
} as const;

// ============================================================
// Resource Types (For permission checking)
// ============================================================
export const PERMISSION_RESOURCES = {
  USER: 'user',
  ROLE: 'role',
  PERMISSION: 'permission',
  PRODUCT: 'product',
  CATEGORY: 'category',
  BRAND: 'brand',
  ORDER: 'order',
  PAYMENT: 'payment',
  INVENTORY: 'inventory',
  REVIEW: 'review',
  COUPON: 'coupon',
  OFFER: 'offer',
  CART: 'cart',
  WISHLIST: 'wishlist',
  SHIPPING: 'shipping',
  ANALYTICS: 'analytics',
  SYSTEM: 'system',
  SHOP: 'shop',
  VENDOR: 'vendor',
  TICKET: 'ticket',
  NOTIFICATION: 'notification',
  AUDIT: 'audit',
} as const;

export type PermissionResource = ValueOf<typeof PERMISSION_RESOURCES>;

// ============================================================
// Actions (CRUD + custom)
// ============================================================
export const PERMISSION_ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  LIST: 'list',
  SUSPEND: 'suspend',
  ACTIVATE: 'activate',
  APPROVE: 'approve',
  REJECT: 'reject',
  PUBLISH: 'publish',
  UNPUBLISH: 'unpublish',
  FEATURE: 'feature',
  CANCEL: 'cancel',
  REFUND: 'refund',
  SHIP: 'ship',
  DELIVER: 'deliver',
  EXPORT: 'export',
  IMPORT: 'import',
  BULK_UPDATE: 'bulk_update',
  ADJUST: 'adjust',
  MODERATE: 'moderate',
  RESOLVE: 'resolve',
  ASSIGN: 'assign',
  SEND: 'send',
  BROADCAST: 'broadcast',
  VERIFY: 'verify',
  CAPTURE: 'capture',
  VOID: 'void',
  SORT: 'sort',
  IMPERSONATE: 'impersonate',
  PAYOUT: 'payout',
  COMMISSION_UPDATE: 'commission_update',
  SETTINGS: 'settings',
  REVIEW: 'review',
  LOG_READ: 'log_read',
  LOG_EXPORT: 'log_export',
} as const;

export type PermissionAction = ValueOf<typeof PERMISSION_ACTIONS>;

// ============================================================
// Type Exports
// ============================================================
export type PermissionValue = typeof PERMISSIONS;
export type PermissionGroupsValue = typeof PERMISSION_GROUPS;
export type PermissionCategoriesValue = typeof PERMISSION_CATEGORIES;
export type PermissionToCategoryValue = typeof PERMISSION_TO_CATEGORY;
export type PermissionResourcesValue = typeof PERMISSION_RESOURCES;
export type PermissionActionsValue = typeof PERMISSION_ACTIONS;
