/**
 * AI Analytics Status Constants
 * Status tracking for analytics lifecycle
 */

// First define the status types
export const AI_ANALYTICS_STATUS_TYPES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Processing States
  INITIALIZING: 'initializing',
  COLLECTING: 'collecting',
  PROCESSING: 'processing',
  ANALYZING: 'analyzing',
  GENERATING: 'generating',
  VALIDATING: 'validating',

  // Intermediate States
  COLLECTED: 'collected',
  PROCESSED: 'processed',
  ANALYZED: 'analyzed',
  GENERATED: 'generated',
  VALIDATED: 'validated',
  OPTIMIZED: 'optimized',

  // Delivery States
  DELIVERING: 'delivering',
  DELIVERED: 'delivered',
  CACHED: 'cached',

  // Terminal States
  COMPLETED: 'completed',
  FAILED: 'failed',
  EXPIRED: 'expired',
  ARCHIVED: 'archived',
  RETIRED: 'retired',
} as const;

export type AIAnalyticsStatusType =
  (typeof AI_ANALYTICS_STATUS_TYPES)[keyof typeof AI_ANALYTICS_STATUS_TYPES];

export const AI_ANALYTICS_STATUS = {
  // Status Types
  STATUSES: AI_ANALYTICS_STATUS_TYPES,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    DELIVERED: 'delivered',
    COMPLETED: 'completed',
    FAILED: 'failed',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_ANALYTICS_STATUS_TYPES.CREATED]: '#gray',
    [AI_ANALYTICS_STATUS_TYPES.QUEUED]: '#gray',
    [AI_ANALYTICS_STATUS_TYPES.PENDING]: '#yellow',
    [AI_ANALYTICS_STATUS_TYPES.INITIALIZING]: '#blue',
    [AI_ANALYTICS_STATUS_TYPES.COLLECTING]: '#blue',
    [AI_ANALYTICS_STATUS_TYPES.PROCESSING]: '#blue',
    [AI_ANALYTICS_STATUS_TYPES.ANALYZING]: '#blue',
    [AI_ANALYTICS_STATUS_TYPES.GENERATING]: '#blue',
    [AI_ANALYTICS_STATUS_TYPES.VALIDATING]: '#purple',
    [AI_ANALYTICS_STATUS_TYPES.COLLECTED]: '#green',
    [AI_ANALYTICS_STATUS_TYPES.PROCESSED]: '#green',
    [AI_ANALYTICS_STATUS_TYPES.ANALYZED]: '#green',
    [AI_ANALYTICS_STATUS_TYPES.GENERATED]: '#green',
    [AI_ANALYTICS_STATUS_TYPES.VALIDATED]: '#green',
    [AI_ANALYTICS_STATUS_TYPES.OPTIMIZED]: '#green',
    [AI_ANALYTICS_STATUS_TYPES.DELIVERING]: '#orange',
    [AI_ANALYTICS_STATUS_TYPES.DELIVERED]: '#green',
    [AI_ANALYTICS_STATUS_TYPES.CACHED]: '#green',
    [AI_ANALYTICS_STATUS_TYPES.COMPLETED]: '#green',
    [AI_ANALYTICS_STATUS_TYPES.FAILED]: '#red',
    [AI_ANALYTICS_STATUS_TYPES.EXPIRED]: '#gray',
    [AI_ANALYTICS_STATUS_TYPES.ARCHIVED]: '#gray',
    [AI_ANALYTICS_STATUS_TYPES.RETIRED]: '#gray',
  } as const,
} as const;

// Status Categories
export type AIAnalyticsStatusCategory =
  (typeof AI_ANALYTICS_STATUS.CATEGORIES)[keyof typeof AI_ANALYTICS_STATUS.CATEGORIES];

// Status Severity
export type AIAnalyticsStatusSeverity =
  (typeof AI_ANALYTICS_STATUS.SEVERITY)[keyof typeof AI_ANALYTICS_STATUS.SEVERITY];

// Status Colors
export type AIAnalyticsStatusColor =
  (typeof AI_ANALYTICS_STATUS.COLORS)[keyof typeof AI_ANALYTICS_STATUS.COLORS];

// Utility Functions - সব নামে AI যোগ করা হয়েছে
export function getAIAnalyticsStatusLabel(status: AIAnalyticsStatusType): string {
  const labels: Record<AIAnalyticsStatusType, string> = {
    [AI_ANALYTICS_STATUS_TYPES.CREATED]: 'Created',
    [AI_ANALYTICS_STATUS_TYPES.QUEUED]: 'Queued',
    [AI_ANALYTICS_STATUS_TYPES.PENDING]: 'Pending',
    [AI_ANALYTICS_STATUS_TYPES.INITIALIZING]: 'Initializing',
    [AI_ANALYTICS_STATUS_TYPES.COLLECTING]: 'Collecting',
    [AI_ANALYTICS_STATUS_TYPES.PROCESSING]: 'Processing',
    [AI_ANALYTICS_STATUS_TYPES.ANALYZING]: 'Analyzing',
    [AI_ANALYTICS_STATUS_TYPES.GENERATING]: 'Generating',
    [AI_ANALYTICS_STATUS_TYPES.VALIDATING]: 'Validating',
    [AI_ANALYTICS_STATUS_TYPES.COLLECTED]: 'Collected',
    [AI_ANALYTICS_STATUS_TYPES.PROCESSED]: 'Processed',
    [AI_ANALYTICS_STATUS_TYPES.ANALYZED]: 'Analyzed',
    [AI_ANALYTICS_STATUS_TYPES.GENERATED]: 'Generated',
    [AI_ANALYTICS_STATUS_TYPES.VALIDATED]: 'Validated',
    [AI_ANALYTICS_STATUS_TYPES.OPTIMIZED]: 'Optimized',
    [AI_ANALYTICS_STATUS_TYPES.DELIVERING]: 'Delivering',
    [AI_ANALYTICS_STATUS_TYPES.DELIVERED]: 'Delivered',
    [AI_ANALYTICS_STATUS_TYPES.CACHED]: 'Cached',
    [AI_ANALYTICS_STATUS_TYPES.COMPLETED]: 'Completed',
    [AI_ANALYTICS_STATUS_TYPES.FAILED]: 'Failed',
    [AI_ANALYTICS_STATUS_TYPES.EXPIRED]: 'Expired',
    [AI_ANALYTICS_STATUS_TYPES.ARCHIVED]: 'Archived',
    [AI_ANALYTICS_STATUS_TYPES.RETIRED]: 'Retired',
  };
  return labels[status] || 'Unknown';
}

export function getAIAnalyticsStatusCategory(
  status: AIAnalyticsStatusType
): AIAnalyticsStatusCategory {
  const categories: Record<AIAnalyticsStatusType, AIAnalyticsStatusCategory> = {
    [AI_ANALYTICS_STATUS_TYPES.CREATED]: AI_ANALYTICS_STATUS.CATEGORIES.PENDING,
    [AI_ANALYTICS_STATUS_TYPES.QUEUED]: AI_ANALYTICS_STATUS.CATEGORIES.PENDING,
    [AI_ANALYTICS_STATUS_TYPES.PENDING]: AI_ANALYTICS_STATUS.CATEGORIES.PENDING,
    [AI_ANALYTICS_STATUS_TYPES.INITIALIZING]: AI_ANALYTICS_STATUS.CATEGORIES.PROCESSING,
    [AI_ANALYTICS_STATUS_TYPES.COLLECTING]: AI_ANALYTICS_STATUS.CATEGORIES.PROCESSING,
    [AI_ANALYTICS_STATUS_TYPES.PROCESSING]: AI_ANALYTICS_STATUS.CATEGORIES.PROCESSING,
    [AI_ANALYTICS_STATUS_TYPES.ANALYZING]: AI_ANALYTICS_STATUS.CATEGORIES.PROCESSING,
    [AI_ANALYTICS_STATUS_TYPES.GENERATING]: AI_ANALYTICS_STATUS.CATEGORIES.PROCESSING,
    [AI_ANALYTICS_STATUS_TYPES.VALIDATING]: AI_ANALYTICS_STATUS.CATEGORIES.PROCESSING,
    [AI_ANALYTICS_STATUS_TYPES.COLLECTED]: AI_ANALYTICS_STATUS.CATEGORIES.PROCESSING,
    [AI_ANALYTICS_STATUS_TYPES.PROCESSED]: AI_ANALYTICS_STATUS.CATEGORIES.PROCESSING,
    [AI_ANALYTICS_STATUS_TYPES.ANALYZED]: AI_ANALYTICS_STATUS.CATEGORIES.PROCESSING,
    [AI_ANALYTICS_STATUS_TYPES.GENERATED]: AI_ANALYTICS_STATUS.CATEGORIES.PROCESSING,
    [AI_ANALYTICS_STATUS_TYPES.VALIDATED]: AI_ANALYTICS_STATUS.CATEGORIES.PROCESSING,
    [AI_ANALYTICS_STATUS_TYPES.OPTIMIZED]: AI_ANALYTICS_STATUS.CATEGORIES.PROCESSING,
    [AI_ANALYTICS_STATUS_TYPES.DELIVERING]: AI_ANALYTICS_STATUS.CATEGORIES.DELIVERED,
    [AI_ANALYTICS_STATUS_TYPES.DELIVERED]: AI_ANALYTICS_STATUS.CATEGORIES.DELIVERED,
    [AI_ANALYTICS_STATUS_TYPES.CACHED]: AI_ANALYTICS_STATUS.CATEGORIES.DELIVERED,
    [AI_ANALYTICS_STATUS_TYPES.COMPLETED]: AI_ANALYTICS_STATUS.CATEGORIES.COMPLETED,
    [AI_ANALYTICS_STATUS_TYPES.FAILED]: AI_ANALYTICS_STATUS.CATEGORIES.FAILED,
    [AI_ANALYTICS_STATUS_TYPES.EXPIRED]: AI_ANALYTICS_STATUS.CATEGORIES.FAILED,
    [AI_ANALYTICS_STATUS_TYPES.ARCHIVED]: AI_ANALYTICS_STATUS.CATEGORIES.COMPLETED,
    [AI_ANALYTICS_STATUS_TYPES.RETIRED]: AI_ANALYTICS_STATUS.CATEGORIES.COMPLETED,
  };
  return categories[status] || AI_ANALYTICS_STATUS.CATEGORIES.PENDING;
}

export function getAIAnalyticsStatusSeverity(
  status: AIAnalyticsStatusType
): AIAnalyticsStatusSeverity {
  const severities: Record<AIAnalyticsStatusType, AIAnalyticsStatusSeverity> = {
    [AI_ANALYTICS_STATUS_TYPES.CREATED]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.QUEUED]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.PENDING]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.INITIALIZING]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.COLLECTING]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.PROCESSING]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.ANALYZING]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.GENERATING]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.VALIDATING]: AI_ANALYTICS_STATUS.SEVERITY.WARNING,
    [AI_ANALYTICS_STATUS_TYPES.COLLECTED]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.PROCESSED]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.ANALYZED]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.GENERATED]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.VALIDATED]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.OPTIMIZED]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.DELIVERING]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.DELIVERED]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.CACHED]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.COMPLETED]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.FAILED]: AI_ANALYTICS_STATUS.SEVERITY.ERROR,
    [AI_ANALYTICS_STATUS_TYPES.EXPIRED]: AI_ANALYTICS_STATUS.SEVERITY.WARNING,
    [AI_ANALYTICS_STATUS_TYPES.ARCHIVED]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
    [AI_ANALYTICS_STATUS_TYPES.RETIRED]: AI_ANALYTICS_STATUS.SEVERITY.INFO,
  };
  return severities[status] || AI_ANALYTICS_STATUS.SEVERITY.INFO;
}

export function getAIAnalyticsStatusColor(status: AIAnalyticsStatusType): AIAnalyticsStatusColor {
  return AI_ANALYTICS_STATUS.COLORS[status] || '#gray';
}

export function isAIAnalyticsActive(status: AIAnalyticsStatusType): boolean {
  const activeStatuses: AIAnalyticsStatusType[] = [
    AI_ANALYTICS_STATUS_TYPES.CREATED,
    AI_ANALYTICS_STATUS_TYPES.QUEUED,
    AI_ANALYTICS_STATUS_TYPES.PENDING,
    AI_ANALYTICS_STATUS_TYPES.INITIALIZING,
    AI_ANALYTICS_STATUS_TYPES.COLLECTING,
    AI_ANALYTICS_STATUS_TYPES.PROCESSING,
    AI_ANALYTICS_STATUS_TYPES.ANALYZING,
    AI_ANALYTICS_STATUS_TYPES.GENERATING,
    AI_ANALYTICS_STATUS_TYPES.VALIDATING,
    AI_ANALYTICS_STATUS_TYPES.COLLECTED,
    AI_ANALYTICS_STATUS_TYPES.PROCESSED,
    AI_ANALYTICS_STATUS_TYPES.ANALYZED,
    AI_ANALYTICS_STATUS_TYPES.GENERATED,
    AI_ANALYTICS_STATUS_TYPES.VALIDATED,
    AI_ANALYTICS_STATUS_TYPES.OPTIMIZED,
    AI_ANALYTICS_STATUS_TYPES.DELIVERING,
  ];
  return activeStatuses.includes(status);
}

export function isAIAnalyticsDelivered(status: AIAnalyticsStatusType): boolean {
  const deliveredStatuses: AIAnalyticsStatusType[] = [
    AI_ANALYTICS_STATUS_TYPES.DELIVERED,
    AI_ANALYTICS_STATUS_TYPES.CACHED,
  ];
  return deliveredStatuses.includes(status);
}

export function isAIAnalyticsComplete(status: AIAnalyticsStatusType): boolean {
  const completeStatuses: AIAnalyticsStatusType[] = [
    AI_ANALYTICS_STATUS_TYPES.COMPLETED,
    AI_ANALYTICS_STATUS_TYPES.ARCHIVED,
    AI_ANALYTICS_STATUS_TYPES.RETIRED,
  ];
  return completeStatuses.includes(status);
}

export function isAIAnalyticsFailed(status: AIAnalyticsStatusType): boolean {
  const failedStatuses: AIAnalyticsStatusType[] = [
    AI_ANALYTICS_STATUS_TYPES.FAILED,
    AI_ANALYTICS_STATUS_TYPES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}
