/**
 * SEO & AI HTTP Status Codes Constants
 * Contains all HTTP status codes used in SEO and AI management
 */

export const SeoAiHttpStatus = {
  // 2xx Success
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,

  // 3xx Redirection
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,

  // 4xx Client Errors
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,

  // 5xx Server Errors
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,

  // Custom SEO & AI Business Codes
  AI_MODEL_NOT_FOUND: 15001,
  AI_MODEL_TRAINING_FAILED: 15002,
  AI_MODEL_INVALID: 15003,
  AI_RECOMMENDATION_FAILED: 15004,
  SEO_AUDIT_FAILED: 15005,
  SEO_CONTENT_GENERATION_FAILED: 15006,
  SEO_KEYWORD_ANALYSIS_FAILED: 15007,
  AI_QUOTA_EXCEEDED: 15008,
  AI_RATE_LIMIT_EXCEEDED: 15009,
  SEO_CRAWL_FAILED: 15010,
} as const;

export type SeoAiHttpStatusCode = (typeof SeoAiHttpStatus)[keyof typeof SeoAiHttpStatus];

export const SeoAiHttpStatusMessage: Record<SeoAiHttpStatusCode, string> = {
  [SeoAiHttpStatus.OK]: 'Success',
  [SeoAiHttpStatus.CREATED]: 'SEO/AI resource created successfully',
  [SeoAiHttpStatus.ACCEPTED]: 'SEO/AI request accepted',
  [SeoAiHttpStatus.NON_AUTHORITATIVE_INFORMATION]: 'Non-authoritative information',
  [SeoAiHttpStatus.NO_CONTENT]: 'No content',
  [SeoAiHttpStatus.RESET_CONTENT]: 'Reset content',
  [SeoAiHttpStatus.PARTIAL_CONTENT]: 'Partial content',

  [SeoAiHttpStatus.MULTIPLE_CHOICES]: 'Multiple choices',
  [SeoAiHttpStatus.MOVED_PERMANENTLY]: 'Moved permanently',
  [SeoAiHttpStatus.FOUND]: 'Found',
  [SeoAiHttpStatus.SEE_OTHER]: 'See other',
  [SeoAiHttpStatus.NOT_MODIFIED]: 'Not modified',
  [SeoAiHttpStatus.USE_PROXY]: 'Use proxy',
  [SeoAiHttpStatus.TEMPORARY_REDIRECT]: 'Temporary redirect',
  [SeoAiHttpStatus.PERMANENT_REDIRECT]: 'Permanent redirect',

  [SeoAiHttpStatus.BAD_REQUEST]: 'Bad request',
  [SeoAiHttpStatus.UNAUTHORIZED]: 'Unauthorized',
  [SeoAiHttpStatus.PAYMENT_REQUIRED]: 'Payment required',
  [SeoAiHttpStatus.FORBIDDEN]: 'Forbidden',
  [SeoAiHttpStatus.NOT_FOUND]: 'SEO/AI resource not found',
  [SeoAiHttpStatus.METHOD_NOT_ALLOWED]: 'Method not allowed',
  [SeoAiHttpStatus.NOT_ACCEPTABLE]: 'Not acceptable',
  [SeoAiHttpStatus.PROXY_AUTHENTICATION_REQUIRED]: 'Proxy authentication required',
  [SeoAiHttpStatus.REQUEST_TIMEOUT]: 'Request timeout',
  [SeoAiHttpStatus.CONFLICT]: 'Conflict',
  [SeoAiHttpStatus.GONE]: 'Gone',
  [SeoAiHttpStatus.LENGTH_REQUIRED]: 'Length required',
  [SeoAiHttpStatus.PRECONDITION_FAILED]: 'Precondition failed',
  [SeoAiHttpStatus.PAYLOAD_TOO_LARGE]: 'Payload too large',
  [SeoAiHttpStatus.URI_TOO_LONG]: 'URI too long',
  [SeoAiHttpStatus.UNSUPPORTED_MEDIA_TYPE]: 'Unsupported media type',
  [SeoAiHttpStatus.RANGE_NOT_SATISFIABLE]: 'Range not satisfiable',
  [SeoAiHttpStatus.EXPECTATION_FAILED]: 'Expectation failed',
  [SeoAiHttpStatus.IM_A_TEAPOT]: 'Im a teapot',
  [SeoAiHttpStatus.MISDIRECTED_REQUEST]: 'Misdirected request',
  [SeoAiHttpStatus.UNPROCESSABLE_ENTITY]: 'Unprocessable entity',
  [SeoAiHttpStatus.LOCKED]: 'Locked',
  [SeoAiHttpStatus.FAILED_DEPENDENCY]: 'Failed dependency',
  [SeoAiHttpStatus.TOO_EARLY]: 'Too early',
  [SeoAiHttpStatus.UPGRADE_REQUIRED]: 'Upgrade required',
  [SeoAiHttpStatus.PRECONDITION_REQUIRED]: 'Precondition required',
  [SeoAiHttpStatus.TOO_MANY_REQUESTS]: 'Too many requests',
  [SeoAiHttpStatus.REQUEST_HEADER_FIELDS_TOO_LARGE]: 'Request header fields too large',
  [SeoAiHttpStatus.UNAVAILABLE_FOR_LEGAL_REASONS]: 'Unavailable for legal reasons',

  [SeoAiHttpStatus.INTERNAL_SERVER_ERROR]: 'Internal server error',
  [SeoAiHttpStatus.NOT_IMPLEMENTED]: 'Not implemented',
  [SeoAiHttpStatus.BAD_GATEWAY]: 'Bad gateway',
  [SeoAiHttpStatus.SERVICE_UNAVAILABLE]: 'Service unavailable',
  [SeoAiHttpStatus.GATEWAY_TIMEOUT]: 'Gateway timeout',
  [SeoAiHttpStatus.HTTP_VERSION_NOT_SUPPORTED]: 'HTTP version not supported',
  [SeoAiHttpStatus.VARIANT_ALSO_NEGOTIATES]: 'Variant also negotiates',
  [SeoAiHttpStatus.INSUFFICIENT_STORAGE]: 'Insufficient storage',
  [SeoAiHttpStatus.LOOP_DETECTED]: 'Loop detected',
  [SeoAiHttpStatus.NOT_EXTENDED]: 'Not extended',
  [SeoAiHttpStatus.NETWORK_AUTHENTICATION_REQUIRED]: 'Network authentication required',

  // Custom SEO & AI messages
  [SeoAiHttpStatus.AI_MODEL_NOT_FOUND]: 'AI model not found',
  [SeoAiHttpStatus.AI_MODEL_TRAINING_FAILED]: 'AI model training failed',
  [SeoAiHttpStatus.AI_MODEL_INVALID]: 'Invalid AI model',
  [SeoAiHttpStatus.AI_RECOMMENDATION_FAILED]: 'AI recommendation failed',
  [SeoAiHttpStatus.SEO_AUDIT_FAILED]: 'SEO audit failed',
  [SeoAiHttpStatus.SEO_CONTENT_GENERATION_FAILED]: 'SEO content generation failed',
  [SeoAiHttpStatus.SEO_KEYWORD_ANALYSIS_FAILED]: 'SEO keyword analysis failed',
  [SeoAiHttpStatus.AI_QUOTA_EXCEEDED]: 'AI quota exceeded',
  [SeoAiHttpStatus.AI_RATE_LIMIT_EXCEEDED]: 'AI rate limit exceeded',
  [SeoAiHttpStatus.SEO_CRAWL_FAILED]: 'SEO crawl failed',
};

export const SeoAiHttpStatusGroup = {
  SUCCESS: [200, 201, 202, 203, 204, 205, 206],
  REDIRECTION: [300, 301, 302, 303, 304, 305, 307, 308],
  CLIENT_ERROR: [
    400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418,
    421, 422, 423, 424, 425, 426, 428, 429, 431, 451,
  ],
  SERVER_ERROR: [500, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511],
  SEO_AI_ERROR: [15001, 15002, 15003, 15004, 15005, 15006, 15007, 15008, 15009, 15010],
} as const;
