/**
 * AI Training Phase Constants
 * Phases and stages of AI model training
 */

// First define the phase types
export const AI_TRAINING_PHASE_TYPES = {
  // Preparation Phase
  DATA_COLLECTION: 'data_collection',
  DATA_CLEANING: 'data_cleaning',
  DATA_PREPROCESSING: 'data_preprocessing',
  DATA_AUGMENTATION: 'data_augmentation',
  DATA_SPLITTING: 'data_splitting',

  // Feature Engineering Phase
  FEATURE_EXTRACTION: 'feature_extraction',
  FEATURE_SELECTION: 'feature_selection',
  FEATURE_TRANSFORMATION: 'feature_transformation',
  FEATURE_SCALING: 'feature_scaling',

  // Model Building Phase
  MODEL_SELECTION: 'model_selection',
  MODEL_INITIALIZATION: 'model_initialization',
  HYPERPARAMETER_TUNING: 'hyperparameter_tuning',

  // Training Phase
  TRAINING_START: 'training_start',
  TRAINING_EPOCH: 'training_epoch',
  TRAINING_BATCH: 'training_batch',
  TRAINING_UPDATE: 'training_update',

  // Validation Phase
  VALIDATION: 'validation',
  CROSS_VALIDATION: 'cross_validation',
  PERFORMANCE_EVALUATION: 'performance_evaluation',

  // Optimization Phase
  OPTIMIZATION: 'optimization',
  REGULARIZATION: 'regularization',
  PRUNING: 'pruning',
  QUANTIZATION: 'quantization',

  // Finalization Phase
  MODEL_SAVING: 'model_saving',
  MODEL_EXPORT: 'model_export',
  MODEL_DEPLOYMENT: 'model_deployment',
  MODEL_MONITORING: 'model_monitoring',
} as const;

export type AITrainingPhaseType =
  (typeof AI_TRAINING_PHASE_TYPES)[keyof typeof AI_TRAINING_PHASE_TYPES];

export const AI_TRAINING_PHASE = {
  // Phase Types
  TYPES: AI_TRAINING_PHASE_TYPES,

  // Phase Status
  STATUSES: {
    NOT_STARTED: 'not_started',
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
    FAILED: 'failed',
    SKIPPED: 'skipped',
  } as const,

  // Phase Priorities
  PRIORITIES: {
    CRITICAL: 'critical',
    HIGH: 'high',
    MEDIUM: 'medium',
    LOW: 'low',
  } as const,

  // Phase Dependencies
  DEPENDENCIES: {
    [AI_TRAINING_PHASE_TYPES.DATA_COLLECTION]: [],
    [AI_TRAINING_PHASE_TYPES.DATA_CLEANING]: [AI_TRAINING_PHASE_TYPES.DATA_COLLECTION],
    [AI_TRAINING_PHASE_TYPES.DATA_PREPROCESSING]: [AI_TRAINING_PHASE_TYPES.DATA_CLEANING],
    [AI_TRAINING_PHASE_TYPES.DATA_AUGMENTATION]: [AI_TRAINING_PHASE_TYPES.DATA_PREPROCESSING],
    [AI_TRAINING_PHASE_TYPES.DATA_SPLITTING]: [AI_TRAINING_PHASE_TYPES.DATA_AUGMENTATION],
    [AI_TRAINING_PHASE_TYPES.FEATURE_EXTRACTION]: [AI_TRAINING_PHASE_TYPES.DATA_SPLITTING],
    [AI_TRAINING_PHASE_TYPES.FEATURE_SELECTION]: [AI_TRAINING_PHASE_TYPES.FEATURE_EXTRACTION],
    [AI_TRAINING_PHASE_TYPES.FEATURE_TRANSFORMATION]: [AI_TRAINING_PHASE_TYPES.FEATURE_SELECTION],
    [AI_TRAINING_PHASE_TYPES.FEATURE_SCALING]: [AI_TRAINING_PHASE_TYPES.FEATURE_TRANSFORMATION],
    [AI_TRAINING_PHASE_TYPES.MODEL_SELECTION]: [AI_TRAINING_PHASE_TYPES.FEATURE_SCALING],
    [AI_TRAINING_PHASE_TYPES.MODEL_INITIALIZATION]: [AI_TRAINING_PHASE_TYPES.MODEL_SELECTION],
    [AI_TRAINING_PHASE_TYPES.HYPERPARAMETER_TUNING]: [AI_TRAINING_PHASE_TYPES.MODEL_INITIALIZATION],
    [AI_TRAINING_PHASE_TYPES.TRAINING_START]: [AI_TRAINING_PHASE_TYPES.HYPERPARAMETER_TUNING],
    [AI_TRAINING_PHASE_TYPES.TRAINING_EPOCH]: [AI_TRAINING_PHASE_TYPES.TRAINING_START],
    [AI_TRAINING_PHASE_TYPES.TRAINING_BATCH]: [AI_TRAINING_PHASE_TYPES.TRAINING_EPOCH],
    [AI_TRAINING_PHASE_TYPES.TRAINING_UPDATE]: [AI_TRAINING_PHASE_TYPES.TRAINING_BATCH],
    [AI_TRAINING_PHASE_TYPES.VALIDATION]: [AI_TRAINING_PHASE_TYPES.TRAINING_UPDATE],
    [AI_TRAINING_PHASE_TYPES.CROSS_VALIDATION]: [AI_TRAINING_PHASE_TYPES.VALIDATION],
    [AI_TRAINING_PHASE_TYPES.PERFORMANCE_EVALUATION]: [AI_TRAINING_PHASE_TYPES.CROSS_VALIDATION],
    [AI_TRAINING_PHASE_TYPES.OPTIMIZATION]: [AI_TRAINING_PHASE_TYPES.PERFORMANCE_EVALUATION],
    [AI_TRAINING_PHASE_TYPES.REGULARIZATION]: [AI_TRAINING_PHASE_TYPES.OPTIMIZATION],
    [AI_TRAINING_PHASE_TYPES.PRUNING]: [AI_TRAINING_PHASE_TYPES.REGULARIZATION],
    [AI_TRAINING_PHASE_TYPES.QUANTIZATION]: [AI_TRAINING_PHASE_TYPES.PRUNING],
    [AI_TRAINING_PHASE_TYPES.MODEL_SAVING]: [AI_TRAINING_PHASE_TYPES.QUANTIZATION],
    [AI_TRAINING_PHASE_TYPES.MODEL_EXPORT]: [AI_TRAINING_PHASE_TYPES.MODEL_SAVING],
    [AI_TRAINING_PHASE_TYPES.MODEL_DEPLOYMENT]: [AI_TRAINING_PHASE_TYPES.MODEL_EXPORT],
    [AI_TRAINING_PHASE_TYPES.MODEL_MONITORING]: [AI_TRAINING_PHASE_TYPES.MODEL_DEPLOYMENT],
  } as const,

  // Phase Durations (in seconds)
  DURATIONS: {
    [AI_TRAINING_PHASE_TYPES.DATA_COLLECTION]: 3600,
    [AI_TRAINING_PHASE_TYPES.DATA_CLEANING]: 1800,
    [AI_TRAINING_PHASE_TYPES.DATA_PREPROCESSING]: 1200,
    [AI_TRAINING_PHASE_TYPES.DATA_AUGMENTATION]: 900,
    [AI_TRAINING_PHASE_TYPES.DATA_SPLITTING]: 300,
    [AI_TRAINING_PHASE_TYPES.FEATURE_EXTRACTION]: 600,
    [AI_TRAINING_PHASE_TYPES.FEATURE_SELECTION]: 300,
    [AI_TRAINING_PHASE_TYPES.FEATURE_TRANSFORMATION]: 300,
    [AI_TRAINING_PHASE_TYPES.FEATURE_SCALING]: 180,
    [AI_TRAINING_PHASE_TYPES.MODEL_SELECTION]: 600,
    [AI_TRAINING_PHASE_TYPES.MODEL_INITIALIZATION]: 120,
    [AI_TRAINING_PHASE_TYPES.HYPERPARAMETER_TUNING]: 3600,
    [AI_TRAINING_PHASE_TYPES.TRAINING_START]: 60,
    [AI_TRAINING_PHASE_TYPES.TRAINING_EPOCH]: 1800,
    [AI_TRAINING_PHASE_TYPES.TRAINING_BATCH]: 60,
    [AI_TRAINING_PHASE_TYPES.TRAINING_UPDATE]: 30,
    [AI_TRAINING_PHASE_TYPES.VALIDATION]: 600,
    [AI_TRAINING_PHASE_TYPES.CROSS_VALIDATION]: 1800,
    [AI_TRAINING_PHASE_TYPES.PERFORMANCE_EVALUATION]: 300,
    [AI_TRAINING_PHASE_TYPES.OPTIMIZATION]: 1200,
    [AI_TRAINING_PHASE_TYPES.REGULARIZATION]: 600,
    [AI_TRAINING_PHASE_TYPES.PRUNING]: 300,
    [AI_TRAINING_PHASE_TYPES.QUANTIZATION]: 300,
    [AI_TRAINING_PHASE_TYPES.MODEL_SAVING]: 120,
    [AI_TRAINING_PHASE_TYPES.MODEL_EXPORT]: 180,
    [AI_TRAINING_PHASE_TYPES.MODEL_DEPLOYMENT]: 600,
    [AI_TRAINING_PHASE_TYPES.MODEL_MONITORING]: 3600,
  } as const,
} as const;

// Phase Status
export type AITrainingPhaseStatus =
  (typeof AI_TRAINING_PHASE.STATUSES)[keyof typeof AI_TRAINING_PHASE.STATUSES];

// Phase Priorities
export type AITrainingPhasePriority =
  (typeof AI_TRAINING_PHASE.PRIORITIES)[keyof typeof AI_TRAINING_PHASE.PRIORITIES];

// Phase Dependencies
export type AITrainingPhaseDependency =
  (typeof AI_TRAINING_PHASE.DEPENDENCIES)[keyof typeof AI_TRAINING_PHASE.DEPENDENCIES];

// Phase Durations
export type AITrainingPhaseDuration =
  (typeof AI_TRAINING_PHASE.DURATIONS)[keyof typeof AI_TRAINING_PHASE.DURATIONS];

// Utility Functions
export function getTrainingPhaseTypeLabel(phase: AITrainingPhaseType): string {
  const labels: Record<AITrainingPhaseType, string> = {
    [AI_TRAINING_PHASE_TYPES.DATA_COLLECTION]: 'Data Collection',
    [AI_TRAINING_PHASE_TYPES.DATA_CLEANING]: 'Data Cleaning',
    [AI_TRAINING_PHASE_TYPES.DATA_PREPROCESSING]: 'Data Preprocessing',
    [AI_TRAINING_PHASE_TYPES.DATA_AUGMENTATION]: 'Data Augmentation',
    [AI_TRAINING_PHASE_TYPES.DATA_SPLITTING]: 'Data Splitting',
    [AI_TRAINING_PHASE_TYPES.FEATURE_EXTRACTION]: 'Feature Extraction',
    [AI_TRAINING_PHASE_TYPES.FEATURE_SELECTION]: 'Feature Selection',
    [AI_TRAINING_PHASE_TYPES.FEATURE_TRANSFORMATION]: 'Feature Transformation',
    [AI_TRAINING_PHASE_TYPES.FEATURE_SCALING]: 'Feature Scaling',
    [AI_TRAINING_PHASE_TYPES.MODEL_SELECTION]: 'Model Selection',
    [AI_TRAINING_PHASE_TYPES.MODEL_INITIALIZATION]: 'Model Initialization',
    [AI_TRAINING_PHASE_TYPES.HYPERPARAMETER_TUNING]: 'Hyperparameter Tuning',
    [AI_TRAINING_PHASE_TYPES.TRAINING_START]: 'Training Start',
    [AI_TRAINING_PHASE_TYPES.TRAINING_EPOCH]: 'Training Epoch',
    [AI_TRAINING_PHASE_TYPES.TRAINING_BATCH]: 'Training Batch',
    [AI_TRAINING_PHASE_TYPES.TRAINING_UPDATE]: 'Training Update',
    [AI_TRAINING_PHASE_TYPES.VALIDATION]: 'Validation',
    [AI_TRAINING_PHASE_TYPES.CROSS_VALIDATION]: 'Cross Validation',
    [AI_TRAINING_PHASE_TYPES.PERFORMANCE_EVALUATION]: 'Performance Evaluation',
    [AI_TRAINING_PHASE_TYPES.OPTIMIZATION]: 'Optimization',
    [AI_TRAINING_PHASE_TYPES.REGULARIZATION]: 'Regularization',
    [AI_TRAINING_PHASE_TYPES.PRUNING]: 'Pruning',
    [AI_TRAINING_PHASE_TYPES.QUANTIZATION]: 'Quantization',
    [AI_TRAINING_PHASE_TYPES.MODEL_SAVING]: 'Model Saving',
    [AI_TRAINING_PHASE_TYPES.MODEL_EXPORT]: 'Model Export',
    [AI_TRAINING_PHASE_TYPES.MODEL_DEPLOYMENT]: 'Model Deployment',
    [AI_TRAINING_PHASE_TYPES.MODEL_MONITORING]: 'Model Monitoring',
  };
  return labels[phase] || 'Unknown';
}

export function getTrainingPhaseStatusLabel(status: AITrainingPhaseStatus): string {
  const labels: Record<AITrainingPhaseStatus, string> = {
    [AI_TRAINING_PHASE.STATUSES.NOT_STARTED]: 'Not Started',
    [AI_TRAINING_PHASE.STATUSES.IN_PROGRESS]: 'In Progress',
    [AI_TRAINING_PHASE.STATUSES.COMPLETED]: 'Completed',
    [AI_TRAINING_PHASE.STATUSES.FAILED]: 'Failed',
    [AI_TRAINING_PHASE.STATUSES.SKIPPED]: 'Skipped',
  };
  return labels[status] || 'Unknown';
}

export function getTrainingPhasePriorityLabel(priority: AITrainingPhasePriority): string {
  const labels: Record<AITrainingPhasePriority, string> = {
    [AI_TRAINING_PHASE.PRIORITIES.CRITICAL]: 'Critical',
    [AI_TRAINING_PHASE.PRIORITIES.HIGH]: 'High',
    [AI_TRAINING_PHASE.PRIORITIES.MEDIUM]: 'Medium',
    [AI_TRAINING_PHASE.PRIORITIES.LOW]: 'Low',
  };
  return labels[priority] || 'Unknown';
}

export function getPhaseDependencies(phase: AITrainingPhaseType): readonly AITrainingPhaseType[] {
  return AI_TRAINING_PHASE.DEPENDENCIES[phase] || [];
}

export function getPhaseDuration(phase: AITrainingPhaseType): number {
  return AI_TRAINING_PHASE.DURATIONS[phase] || 600;
}

export function getPhaseStatusColor(status: AITrainingPhaseStatus): string {
  const colors: Record<AITrainingPhaseStatus, string> = {
    [AI_TRAINING_PHASE.STATUSES.NOT_STARTED]: '#gray',
    [AI_TRAINING_PHASE.STATUSES.IN_PROGRESS]: '#blue',
    [AI_TRAINING_PHASE.STATUSES.COMPLETED]: '#green',
    [AI_TRAINING_PHASE.STATUSES.FAILED]: '#red',
    [AI_TRAINING_PHASE.STATUSES.SKIPPED]: '#orange',
  };
  return colors[status] || '#gray';
}

export function getPhaseOrder(phase: AITrainingPhaseType): number {
  const order: Record<AITrainingPhaseType, number> = {
    [AI_TRAINING_PHASE_TYPES.DATA_COLLECTION]: 1,
    [AI_TRAINING_PHASE_TYPES.DATA_CLEANING]: 2,
    [AI_TRAINING_PHASE_TYPES.DATA_PREPROCESSING]: 3,
    [AI_TRAINING_PHASE_TYPES.DATA_AUGMENTATION]: 4,
    [AI_TRAINING_PHASE_TYPES.DATA_SPLITTING]: 5,
    [AI_TRAINING_PHASE_TYPES.FEATURE_EXTRACTION]: 6,
    [AI_TRAINING_PHASE_TYPES.FEATURE_SELECTION]: 7,
    [AI_TRAINING_PHASE_TYPES.FEATURE_TRANSFORMATION]: 8,
    [AI_TRAINING_PHASE_TYPES.FEATURE_SCALING]: 9,
    [AI_TRAINING_PHASE_TYPES.MODEL_SELECTION]: 10,
    [AI_TRAINING_PHASE_TYPES.MODEL_INITIALIZATION]: 11,
    [AI_TRAINING_PHASE_TYPES.HYPERPARAMETER_TUNING]: 12,
    [AI_TRAINING_PHASE_TYPES.TRAINING_START]: 13,
    [AI_TRAINING_PHASE_TYPES.TRAINING_EPOCH]: 14,
    [AI_TRAINING_PHASE_TYPES.TRAINING_BATCH]: 15,
    [AI_TRAINING_PHASE_TYPES.TRAINING_UPDATE]: 16,
    [AI_TRAINING_PHASE_TYPES.VALIDATION]: 17,
    [AI_TRAINING_PHASE_TYPES.CROSS_VALIDATION]: 18,
    [AI_TRAINING_PHASE_TYPES.PERFORMANCE_EVALUATION]: 19,
    [AI_TRAINING_PHASE_TYPES.OPTIMIZATION]: 20,
    [AI_TRAINING_PHASE_TYPES.REGULARIZATION]: 21,
    [AI_TRAINING_PHASE_TYPES.PRUNING]: 22,
    [AI_TRAINING_PHASE_TYPES.QUANTIZATION]: 23,
    [AI_TRAINING_PHASE_TYPES.MODEL_SAVING]: 24,
    [AI_TRAINING_PHASE_TYPES.MODEL_EXPORT]: 25,
    [AI_TRAINING_PHASE_TYPES.MODEL_DEPLOYMENT]: 26,
    [AI_TRAINING_PHASE_TYPES.MODEL_MONITORING]: 27,
  };
  return order[phase] || 0;
}

export function getNextPhases(currentPhase: AITrainingPhaseType): AITrainingPhaseType[] {
  const allPhases = Object.values(AI_TRAINING_PHASE_TYPES);
  const currentIndex = allPhases.indexOf(currentPhase);
  if (currentIndex === -1) return [];
  return allPhases.slice(currentIndex + 1);
}

export function getPreviousPhases(currentPhase: AITrainingPhaseType): AITrainingPhaseType[] {
  const allPhases = Object.values(AI_TRAINING_PHASE_TYPES);
  const currentIndex = allPhases.indexOf(currentPhase);
  if (currentIndex === -1) return [];
  return allPhases.slice(0, currentIndex);
}
