/**
 * AI Training Status Constants
 * Status tracking for training lifecycle
 */

// First define the status types
export const AI_TRAINING_STATUS_TYPES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Preparation States
  PREPARING: 'preparing',
  INITIALIZING: 'initializing',
  LOADING_DATA: 'loading_data',

  // Training States
  TRAINING: 'training',
  EPOCH_COMPLETE: 'epoch_complete',
  BATCH_COMPLETE: 'batch_complete',
  CHECKPOINT_SAVED: 'checkpoint_saved',

  // Validation States
  VALIDATING: 'validating',
  VALIDATION_COMPLETE: 'validation_complete',

  // Optimization States
  OPTIMIZING: 'optimizing',
  TUNING: 'tuning',

  // Evaluation States
  EVALUATING: 'evaluating',
  EVALUATION_COMPLETE: 'evaluation_complete',

  // Storage States
  SAVING: 'saving',
  SAVED: 'saved',
  EXPORTING: 'exporting',
  EXPORTED: 'exported',

  // Terminal States
  COMPLETED: 'completed',
  DEPLOYED: 'deployed',
  FAILED: 'failed',
  PAUSED: 'paused',
  CANCELLED: 'cancelled',
  ARCHIVED: 'archived',
} as const;

export type AITrainingStatusType =
  (typeof AI_TRAINING_STATUS_TYPES)[keyof typeof AI_TRAINING_STATUS_TYPES];

export const AI_TRAINING_STATUS = {
  // Status Types
  STATUSES: AI_TRAINING_STATUS_TYPES,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PREPARATION: 'preparation',
    TRAINING: 'training',
    VALIDATION: 'validation',
    OPTIMIZATION: 'optimization',
    EVALUATION: 'evaluation',
    COMPLETED: 'completed',
    FAILED: 'failed',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_TRAINING_STATUS_TYPES.CREATED]: '#gray',
    [AI_TRAINING_STATUS_TYPES.QUEUED]: '#gray',
    [AI_TRAINING_STATUS_TYPES.PENDING]: '#yellow',
    [AI_TRAINING_STATUS_TYPES.PREPARING]: '#blue',
    [AI_TRAINING_STATUS_TYPES.INITIALIZING]: '#blue',
    [AI_TRAINING_STATUS_TYPES.LOADING_DATA]: '#blue',
    [AI_TRAINING_STATUS_TYPES.TRAINING]: '#blue',
    [AI_TRAINING_STATUS_TYPES.EPOCH_COMPLETE]: '#green',
    [AI_TRAINING_STATUS_TYPES.BATCH_COMPLETE]: '#green',
    [AI_TRAINING_STATUS_TYPES.CHECKPOINT_SAVED]: '#green',
    [AI_TRAINING_STATUS_TYPES.VALIDATING]: '#purple',
    [AI_TRAINING_STATUS_TYPES.VALIDATION_COMPLETE]: '#green',
    [AI_TRAINING_STATUS_TYPES.OPTIMIZING]: '#orange',
    [AI_TRAINING_STATUS_TYPES.TUNING]: '#orange',
    [AI_TRAINING_STATUS_TYPES.EVALUATING]: '#purple',
    [AI_TRAINING_STATUS_TYPES.EVALUATION_COMPLETE]: '#green',
    [AI_TRAINING_STATUS_TYPES.SAVING]: '#orange',
    [AI_TRAINING_STATUS_TYPES.SAVED]: '#green',
    [AI_TRAINING_STATUS_TYPES.EXPORTING]: '#orange',
    [AI_TRAINING_STATUS_TYPES.EXPORTED]: '#green',
    [AI_TRAINING_STATUS_TYPES.COMPLETED]: '#green',
    [AI_TRAINING_STATUS_TYPES.DEPLOYED]: '#green',
    [AI_TRAINING_STATUS_TYPES.FAILED]: '#red',
    [AI_TRAINING_STATUS_TYPES.PAUSED]: '#orange',
    [AI_TRAINING_STATUS_TYPES.CANCELLED]: '#red',
    [AI_TRAINING_STATUS_TYPES.ARCHIVED]: '#gray',
  } as const,
} as const;

export type AITrainingStatusCategory =
  (typeof AI_TRAINING_STATUS.CATEGORIES)[keyof typeof AI_TRAINING_STATUS.CATEGORIES];
export type AITrainingStatusSeverity =
  (typeof AI_TRAINING_STATUS.SEVERITY)[keyof typeof AI_TRAINING_STATUS.SEVERITY];
export type AITrainingStatusColor =
  (typeof AI_TRAINING_STATUS.COLORS)[keyof typeof AI_TRAINING_STATUS.COLORS];

export function getAiTrainingStatusLabel(status: AITrainingStatusType): string {
  const labels: Record<AITrainingStatusType, string> = {
    [AI_TRAINING_STATUS_TYPES.CREATED]: 'Created',
    [AI_TRAINING_STATUS_TYPES.QUEUED]: 'Queued',
    [AI_TRAINING_STATUS_TYPES.PENDING]: 'Pending',
    [AI_TRAINING_STATUS_TYPES.PREPARING]: 'Preparing',
    [AI_TRAINING_STATUS_TYPES.INITIALIZING]: 'Initializing',
    [AI_TRAINING_STATUS_TYPES.LOADING_DATA]: 'Loading Data',
    [AI_TRAINING_STATUS_TYPES.TRAINING]: 'Training',
    [AI_TRAINING_STATUS_TYPES.EPOCH_COMPLETE]: 'Epoch Complete',
    [AI_TRAINING_STATUS_TYPES.BATCH_COMPLETE]: 'Batch Complete',
    [AI_TRAINING_STATUS_TYPES.CHECKPOINT_SAVED]: 'Checkpoint Saved',
    [AI_TRAINING_STATUS_TYPES.VALIDATING]: 'Validating',
    [AI_TRAINING_STATUS_TYPES.VALIDATION_COMPLETE]: 'Validation Complete',
    [AI_TRAINING_STATUS_TYPES.OPTIMIZING]: 'Optimizing',
    [AI_TRAINING_STATUS_TYPES.TUNING]: 'Tuning',
    [AI_TRAINING_STATUS_TYPES.EVALUATING]: 'Evaluating',
    [AI_TRAINING_STATUS_TYPES.EVALUATION_COMPLETE]: 'Evaluation Complete',
    [AI_TRAINING_STATUS_TYPES.SAVING]: 'Saving',
    [AI_TRAINING_STATUS_TYPES.SAVED]: 'Saved',
    [AI_TRAINING_STATUS_TYPES.EXPORTING]: 'Exporting',
    [AI_TRAINING_STATUS_TYPES.EXPORTED]: 'Exported',
    [AI_TRAINING_STATUS_TYPES.COMPLETED]: 'Completed',
    [AI_TRAINING_STATUS_TYPES.DEPLOYED]: 'Deployed',
    [AI_TRAINING_STATUS_TYPES.FAILED]: 'Failed',
    [AI_TRAINING_STATUS_TYPES.PAUSED]: 'Paused',
    [AI_TRAINING_STATUS_TYPES.CANCELLED]: 'Cancelled',
    [AI_TRAINING_STATUS_TYPES.ARCHIVED]: 'Archived',
  };
  return labels[status] || 'Unknown';
}

export function getAiTrainingStatusCategory(
  status: AITrainingStatusType
): AITrainingStatusCategory {
  const categories: Record<AITrainingStatusType, AITrainingStatusCategory> = {
    [AI_TRAINING_STATUS_TYPES.CREATED]: AI_TRAINING_STATUS.CATEGORIES.PENDING,
    [AI_TRAINING_STATUS_TYPES.QUEUED]: AI_TRAINING_STATUS.CATEGORIES.PENDING,
    [AI_TRAINING_STATUS_TYPES.PENDING]: AI_TRAINING_STATUS.CATEGORIES.PENDING,
    [AI_TRAINING_STATUS_TYPES.PREPARING]: AI_TRAINING_STATUS.CATEGORIES.PREPARATION,
    [AI_TRAINING_STATUS_TYPES.INITIALIZING]: AI_TRAINING_STATUS.CATEGORIES.PREPARATION,
    [AI_TRAINING_STATUS_TYPES.LOADING_DATA]: AI_TRAINING_STATUS.CATEGORIES.PREPARATION,
    [AI_TRAINING_STATUS_TYPES.TRAINING]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.EPOCH_COMPLETE]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.BATCH_COMPLETE]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.CHECKPOINT_SAVED]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.VALIDATING]: AI_TRAINING_STATUS.CATEGORIES.VALIDATION,
    [AI_TRAINING_STATUS_TYPES.VALIDATION_COMPLETE]: AI_TRAINING_STATUS.CATEGORIES.VALIDATION,
    [AI_TRAINING_STATUS_TYPES.OPTIMIZING]: AI_TRAINING_STATUS.CATEGORIES.OPTIMIZATION,
    [AI_TRAINING_STATUS_TYPES.TUNING]: AI_TRAINING_STATUS.CATEGORIES.OPTIMIZATION,
    [AI_TRAINING_STATUS_TYPES.EVALUATING]: AI_TRAINING_STATUS.CATEGORIES.EVALUATION,
    [AI_TRAINING_STATUS_TYPES.EVALUATION_COMPLETE]: AI_TRAINING_STATUS.CATEGORIES.EVALUATION,
    [AI_TRAINING_STATUS_TYPES.SAVING]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.SAVED]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.EXPORTING]: AI_TRAINING_STATUS.CATEGORIES.COMPLETED,
    [AI_TRAINING_STATUS_TYPES.EXPORTED]: AI_TRAINING_STATUS.CATEGORIES.COMPLETED,
    [AI_TRAINING_STATUS_TYPES.COMPLETED]: AI_TRAINING_STATUS.CATEGORIES.COMPLETED,
    [AI_TRAINING_STATUS_TYPES.DEPLOYED]: AI_TRAINING_STATUS.CATEGORIES.COMPLETED,
    [AI_TRAINING_STATUS_TYPES.FAILED]: AI_TRAINING_STATUS.CATEGORIES.FAILED,
    [AI_TRAINING_STATUS_TYPES.PAUSED]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.CANCELLED]: AI_TRAINING_STATUS.CATEGORIES.FAILED,
    [AI_TRAINING_STATUS_TYPES.ARCHIVED]: AI_TRAINING_STATUS.CATEGORIES.COMPLETED,
  };
  return categories[status] || AI_TRAINING_STATUS.CATEGORIES.PENDING;
}

export function getAiTrainingStatusSeverity(
  status: AITrainingStatusType
): AITrainingStatusSeverity {
  const severities: Record<AITrainingStatusType, AITrainingStatusSeverity> = {
    [AI_TRAINING_STATUS_TYPES.CREATED]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.QUEUED]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.PENDING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.PREPARING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.INITIALIZING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.LOADING_DATA]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.TRAINING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.EPOCH_COMPLETE]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.BATCH_COMPLETE]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.CHECKPOINT_SAVED]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.VALIDATING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.VALIDATION_COMPLETE]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.OPTIMIZING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.TUNING]: AI_TRAINING_STATUS.SEVERITY.WARNING,
    [AI_TRAINING_STATUS_TYPES.EVALUATING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.EVALUATION_COMPLETE]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.SAVING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.SAVED]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.EXPORTING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.EXPORTED]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.COMPLETED]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.DEPLOYED]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.FAILED]: AI_TRAINING_STATUS.SEVERITY.ERROR,
    [AI_TRAINING_STATUS_TYPES.PAUSED]: AI_TRAINING_STATUS.SEVERITY.WARNING,
    [AI_TRAINING_STATUS_TYPES.CANCELLED]: AI_TRAINING_STATUS.SEVERITY.ERROR,
    [AI_TRAINING_STATUS_TYPES.ARCHIVED]: AI_TRAINING_STATUS.SEVERITY.INFO,
  };
  return severities[status] || AI_TRAINING_STATUS.SEVERITY.INFO;
}

export function getAiTrainingStatusColor(status: AITrainingStatusType): AITrainingStatusColor {
  return AI_TRAINING_STATUS.COLORS[status] || '#gray';
}

export function isAiTrainingActiveStatus(status: AITrainingStatusType): boolean {
  const activeStatuses: AITrainingStatusType[] = [
    AI_TRAINING_STATUS_TYPES.CREATED,
    AI_TRAINING_STATUS_TYPES.QUEUED,
    AI_TRAINING_STATUS_TYPES.PENDING,
    AI_TRAINING_STATUS_TYPES.PREPARING,
    AI_TRAINING_STATUS_TYPES.INITIALIZING,
    AI_TRAINING_STATUS_TYPES.LOADING_DATA,
    AI_TRAINING_STATUS_TYPES.TRAINING,
    AI_TRAINING_STATUS_TYPES.EPOCH_COMPLETE,
    AI_TRAINING_STATUS_TYPES.BATCH_COMPLETE,
    AI_TRAINING_STATUS_TYPES.CHECKPOINT_SAVED,
    AI_TRAINING_STATUS_TYPES.VALIDATING,
    AI_TRAINING_STATUS_TYPES.VALIDATION_COMPLETE,
    AI_TRAINING_STATUS_TYPES.OPTIMIZING,
    AI_TRAINING_STATUS_TYPES.TUNING,
    AI_TRAINING_STATUS_TYPES.EVALUATING,
    AI_TRAINING_STATUS_TYPES.EVALUATION_COMPLETE,
    AI_TRAINING_STATUS_TYPES.SAVING,
    AI_TRAINING_STATUS_TYPES.EXPORTING,
  ];
  return activeStatuses.includes(status);
}

export function isAiTrainingCompletedStatus(status: AITrainingStatusType): boolean {
  const completedStatuses: AITrainingStatusType[] = [
    AI_TRAINING_STATUS_TYPES.COMPLETED,
    AI_TRAINING_STATUS_TYPES.DEPLOYED,
    AI_TRAINING_STATUS_TYPES.SAVED,
    AI_TRAINING_STATUS_TYPES.EXPORTED,
    AI_TRAINING_STATUS_TYPES.ARCHIVED,
  ];
  return completedStatuses.includes(status);
}

export function isAiTrainingFailedStatus(status: AITrainingStatusType): boolean {
  const failedStatuses: AITrainingStatusType[] = [
    AI_TRAINING_STATUS_TYPES.FAILED,
    AI_TRAINING_STATUS_TYPES.CANCELLED,
  ];
  return failedStatuses.includes(status);
}

export function getAiTrainingStatusProgress(status: AITrainingStatusType): number {
  const progress: Record<AITrainingStatusType, number> = {
    [AI_TRAINING_STATUS_TYPES.CREATED]: 0,
    [AI_TRAINING_STATUS_TYPES.QUEUED]: 5,
    [AI_TRAINING_STATUS_TYPES.PENDING]: 10,
    [AI_TRAINING_STATUS_TYPES.PREPARING]: 15,
    [AI_TRAINING_STATUS_TYPES.INITIALIZING]: 20,
    [AI_TRAINING_STATUS_TYPES.LOADING_DATA]: 25,
    [AI_TRAINING_STATUS_TYPES.TRAINING]: 30,
    [AI_TRAINING_STATUS_TYPES.EPOCH_COMPLETE]: 40,
    [AI_TRAINING_STATUS_TYPES.BATCH_COMPLETE]: 50,
    [AI_TRAINING_STATUS_TYPES.CHECKPOINT_SAVED]: 55,
    [AI_TRAINING_STATUS_TYPES.VALIDATING]: 60,
    [AI_TRAINING_STATUS_TYPES.VALIDATION_COMPLETE]: 65,
    [AI_TRAINING_STATUS_TYPES.OPTIMIZING]: 70,
    [AI_TRAINING_STATUS_TYPES.TUNING]: 75,
    [AI_TRAINING_STATUS_TYPES.EVALUATING]: 80,
    [AI_TRAINING_STATUS_TYPES.EVALUATION_COMPLETE]: 85,
    [AI_TRAINING_STATUS_TYPES.SAVING]: 88,
    [AI_TRAINING_STATUS_TYPES.SAVED]: 90,
    [AI_TRAINING_STATUS_TYPES.EXPORTING]: 92,
    [AI_TRAINING_STATUS_TYPES.EXPORTED]: 95,
    [AI_TRAINING_STATUS_TYPES.COMPLETED]: 100,
    [AI_TRAINING_STATUS_TYPES.DEPLOYED]: 100,
    [AI_TRAINING_STATUS_TYPES.FAILED]: 0,
    [AI_TRAINING_STATUS_TYPES.PAUSED]: 45,
    [AI_TRAINING_STATUS_TYPES.CANCELLED]: 0,
    [AI_TRAINING_STATUS_TYPES.ARCHIVED]: 100,
  };
  return progress[status] || 0;
}
