/**
 * AI Training Status Constants
 * Status tracking for training lifecycle
 */

// First define the status types
export const AI_TRAINING_STATUS_TYPES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Preparation States
  INITIALIZING: 'initializing',
  PREPARING: 'preparing',
  LOADING: 'loading',
  VALIDATING_DATA: 'validating_data',

  // Training States
  TRAINING: 'training',
  EPOCH_TRAINING: 'epoch_training',
  BATCH_TRAINING: 'batch_training',
  FORWARD_PASS: 'forward_pass',
  BACKWARD_PASS: 'backward_pass',
  OPTIMIZING: 'optimizing',

  // Validation States
  VALIDATING: 'validating',
  EVALUATING: 'evaluating',
  TESTING: 'testing',

  // Intermediate States
  CHECKPOINT: 'checkpoint',
  SAVING: 'saving',
  RESUMING: 'resuming',

  // Terminal States
  COMPLETED: 'completed',
  FAILED: 'failed',
  PAUSED: 'paused',
  CANCELLED: 'cancelled',
  ARCHIVED: 'archived',
  DEPLOYED: 'deployed',
} as const;

export type AITrainingStatusType =
  (typeof AI_TRAINING_STATUS_TYPES)[keyof typeof AI_TRAINING_STATUS_TYPES];

export const AI_TRAINING_STATUS = {
  // Status Types
  STATUSES: AI_TRAINING_STATUS_TYPES,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PREPARING: 'preparing',
    TRAINING: 'training',
    VALIDATING: 'validating',
    COMPLETED: 'completed',
    FAILED: 'failed',
    PAUSED: 'paused',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_TRAINING_STATUS_TYPES.CREATED]: '#gray',
    [AI_TRAINING_STATUS_TYPES.QUEUED]: '#gray',
    [AI_TRAINING_STATUS_TYPES.PENDING]: '#yellow',
    [AI_TRAINING_STATUS_TYPES.INITIALIZING]: '#blue',
    [AI_TRAINING_STATUS_TYPES.PREPARING]: '#blue',
    [AI_TRAINING_STATUS_TYPES.LOADING]: '#blue',
    [AI_TRAINING_STATUS_TYPES.VALIDATING_DATA]: '#purple',
    [AI_TRAINING_STATUS_TYPES.TRAINING]: '#blue',
    [AI_TRAINING_STATUS_TYPES.EPOCH_TRAINING]: '#blue',
    [AI_TRAINING_STATUS_TYPES.BATCH_TRAINING]: '#blue',
    [AI_TRAINING_STATUS_TYPES.FORWARD_PASS]: '#blue',
    [AI_TRAINING_STATUS_TYPES.BACKWARD_PASS]: '#blue',
    [AI_TRAINING_STATUS_TYPES.OPTIMIZING]: '#blue',
    [AI_TRAINING_STATUS_TYPES.VALIDATING]: '#purple',
    [AI_TRAINING_STATUS_TYPES.EVALUATING]: '#purple',
    [AI_TRAINING_STATUS_TYPES.TESTING]: '#purple',
    [AI_TRAINING_STATUS_TYPES.CHECKPOINT]: '#orange',
    [AI_TRAINING_STATUS_TYPES.SAVING]: '#orange',
    [AI_TRAINING_STATUS_TYPES.RESUMING]: '#orange',
    [AI_TRAINING_STATUS_TYPES.COMPLETED]: '#green',
    [AI_TRAINING_STATUS_TYPES.FAILED]: '#red',
    [AI_TRAINING_STATUS_TYPES.PAUSED]: '#yellow',
    [AI_TRAINING_STATUS_TYPES.CANCELLED]: '#red',
    [AI_TRAINING_STATUS_TYPES.ARCHIVED]: '#gray',
    [AI_TRAINING_STATUS_TYPES.DEPLOYED]: '#green',
  } as const,
} as const;

// Status Categories
export type AITrainingStatusCategory =
  (typeof AI_TRAINING_STATUS.CATEGORIES)[keyof typeof AI_TRAINING_STATUS.CATEGORIES];

// Status Severity
export type AITrainingStatusSeverity =
  (typeof AI_TRAINING_STATUS.SEVERITY)[keyof typeof AI_TRAINING_STATUS.SEVERITY];

// Status Colors
export type AITrainingStatusColor =
  (typeof AI_TRAINING_STATUS.COLORS)[keyof typeof AI_TRAINING_STATUS.COLORS];

// Utility Functions
export function getTrainingStatusLabel(status: AITrainingStatusType): string {
  const labels: Record<AITrainingStatusType, string> = {
    [AI_TRAINING_STATUS_TYPES.CREATED]: 'Created',
    [AI_TRAINING_STATUS_TYPES.QUEUED]: 'Queued',
    [AI_TRAINING_STATUS_TYPES.PENDING]: 'Pending',
    [AI_TRAINING_STATUS_TYPES.INITIALIZING]: 'Initializing',
    [AI_TRAINING_STATUS_TYPES.PREPARING]: 'Preparing',
    [AI_TRAINING_STATUS_TYPES.LOADING]: 'Loading',
    [AI_TRAINING_STATUS_TYPES.VALIDATING_DATA]: 'Validating Data',
    [AI_TRAINING_STATUS_TYPES.TRAINING]: 'Training',
    [AI_TRAINING_STATUS_TYPES.EPOCH_TRAINING]: 'Epoch Training',
    [AI_TRAINING_STATUS_TYPES.BATCH_TRAINING]: 'Batch Training',
    [AI_TRAINING_STATUS_TYPES.FORWARD_PASS]: 'Forward Pass',
    [AI_TRAINING_STATUS_TYPES.BACKWARD_PASS]: 'Backward Pass',
    [AI_TRAINING_STATUS_TYPES.OPTIMIZING]: 'Optimizing',
    [AI_TRAINING_STATUS_TYPES.VALIDATING]: 'Validating',
    [AI_TRAINING_STATUS_TYPES.EVALUATING]: 'Evaluating',
    [AI_TRAINING_STATUS_TYPES.TESTING]: 'Testing',
    [AI_TRAINING_STATUS_TYPES.CHECKPOINT]: 'Checkpoint',
    [AI_TRAINING_STATUS_TYPES.SAVING]: 'Saving',
    [AI_TRAINING_STATUS_TYPES.RESUMING]: 'Resuming',
    [AI_TRAINING_STATUS_TYPES.COMPLETED]: 'Completed',
    [AI_TRAINING_STATUS_TYPES.FAILED]: 'Failed',
    [AI_TRAINING_STATUS_TYPES.PAUSED]: 'Paused',
    [AI_TRAINING_STATUS_TYPES.CANCELLED]: 'Cancelled',
    [AI_TRAINING_STATUS_TYPES.ARCHIVED]: 'Archived',
    [AI_TRAINING_STATUS_TYPES.DEPLOYED]: 'Deployed',
  };
  return labels[status] || 'Unknown';
}

export function getTrainingStatusCategory(status: AITrainingStatusType): AITrainingStatusCategory {
  const categories: Record<AITrainingStatusType, AITrainingStatusCategory> = {
    [AI_TRAINING_STATUS_TYPES.CREATED]: AI_TRAINING_STATUS.CATEGORIES.PENDING,
    [AI_TRAINING_STATUS_TYPES.QUEUED]: AI_TRAINING_STATUS.CATEGORIES.PENDING,
    [AI_TRAINING_STATUS_TYPES.PENDING]: AI_TRAINING_STATUS.CATEGORIES.PENDING,
    [AI_TRAINING_STATUS_TYPES.INITIALIZING]: AI_TRAINING_STATUS.CATEGORIES.PREPARING,
    [AI_TRAINING_STATUS_TYPES.PREPARING]: AI_TRAINING_STATUS.CATEGORIES.PREPARING,
    [AI_TRAINING_STATUS_TYPES.LOADING]: AI_TRAINING_STATUS.CATEGORIES.PREPARING,
    [AI_TRAINING_STATUS_TYPES.VALIDATING_DATA]: AI_TRAINING_STATUS.CATEGORIES.PREPARING,
    [AI_TRAINING_STATUS_TYPES.TRAINING]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.EPOCH_TRAINING]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.BATCH_TRAINING]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.FORWARD_PASS]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.BACKWARD_PASS]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.OPTIMIZING]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.VALIDATING]: AI_TRAINING_STATUS.CATEGORIES.VALIDATING,
    [AI_TRAINING_STATUS_TYPES.EVALUATING]: AI_TRAINING_STATUS.CATEGORIES.VALIDATING,
    [AI_TRAINING_STATUS_TYPES.TESTING]: AI_TRAINING_STATUS.CATEGORIES.VALIDATING,
    [AI_TRAINING_STATUS_TYPES.CHECKPOINT]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.SAVING]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.RESUMING]: AI_TRAINING_STATUS.CATEGORIES.TRAINING,
    [AI_TRAINING_STATUS_TYPES.COMPLETED]: AI_TRAINING_STATUS.CATEGORIES.COMPLETED,
    [AI_TRAINING_STATUS_TYPES.FAILED]: AI_TRAINING_STATUS.CATEGORIES.FAILED,
    [AI_TRAINING_STATUS_TYPES.PAUSED]: AI_TRAINING_STATUS.CATEGORIES.PAUSED,
    [AI_TRAINING_STATUS_TYPES.CANCELLED]: AI_TRAINING_STATUS.CATEGORIES.FAILED,
    [AI_TRAINING_STATUS_TYPES.ARCHIVED]: AI_TRAINING_STATUS.CATEGORIES.COMPLETED,
    [AI_TRAINING_STATUS_TYPES.DEPLOYED]: AI_TRAINING_STATUS.CATEGORIES.COMPLETED,
  };
  return categories[status] || AI_TRAINING_STATUS.CATEGORIES.PENDING;
}

export function getTrainingStatusSeverity(status: AITrainingStatusType): AITrainingStatusSeverity {
  const severities: Record<AITrainingStatusType, AITrainingStatusSeverity> = {
    [AI_TRAINING_STATUS_TYPES.CREATED]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.QUEUED]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.PENDING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.INITIALIZING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.PREPARING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.LOADING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.VALIDATING_DATA]: AI_TRAINING_STATUS.SEVERITY.WARNING,
    [AI_TRAINING_STATUS_TYPES.TRAINING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.EPOCH_TRAINING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.BATCH_TRAINING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.FORWARD_PASS]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.BACKWARD_PASS]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.OPTIMIZING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.VALIDATING]: AI_TRAINING_STATUS.SEVERITY.WARNING,
    [AI_TRAINING_STATUS_TYPES.EVALUATING]: AI_TRAINING_STATUS.SEVERITY.WARNING,
    [AI_TRAINING_STATUS_TYPES.TESTING]: AI_TRAINING_STATUS.SEVERITY.WARNING,
    [AI_TRAINING_STATUS_TYPES.CHECKPOINT]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.SAVING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.RESUMING]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.COMPLETED]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.FAILED]: AI_TRAINING_STATUS.SEVERITY.ERROR,
    [AI_TRAINING_STATUS_TYPES.PAUSED]: AI_TRAINING_STATUS.SEVERITY.WARNING,
    [AI_TRAINING_STATUS_TYPES.CANCELLED]: AI_TRAINING_STATUS.SEVERITY.ERROR,
    [AI_TRAINING_STATUS_TYPES.ARCHIVED]: AI_TRAINING_STATUS.SEVERITY.INFO,
    [AI_TRAINING_STATUS_TYPES.DEPLOYED]: AI_TRAINING_STATUS.SEVERITY.INFO,
  };
  return severities[status] || AI_TRAINING_STATUS.SEVERITY.INFO;
}

export function getTrainingStatusColor(status: AITrainingStatusType): AITrainingStatusColor {
  return AI_TRAINING_STATUS.COLORS[status] || '#gray';
}

export function isTrainingActive(status: AITrainingStatusType): boolean {
  const activeStatuses: AITrainingStatusType[] = [
    AI_TRAINING_STATUS_TYPES.CREATED,
    AI_TRAINING_STATUS_TYPES.QUEUED,
    AI_TRAINING_STATUS_TYPES.PENDING,
    AI_TRAINING_STATUS_TYPES.INITIALIZING,
    AI_TRAINING_STATUS_TYPES.PREPARING,
    AI_TRAINING_STATUS_TYPES.LOADING,
    AI_TRAINING_STATUS_TYPES.VALIDATING_DATA,
    AI_TRAINING_STATUS_TYPES.TRAINING,
    AI_TRAINING_STATUS_TYPES.EPOCH_TRAINING,
    AI_TRAINING_STATUS_TYPES.BATCH_TRAINING,
    AI_TRAINING_STATUS_TYPES.FORWARD_PASS,
    AI_TRAINING_STATUS_TYPES.BACKWARD_PASS,
    AI_TRAINING_STATUS_TYPES.OPTIMIZING,
    AI_TRAINING_STATUS_TYPES.VALIDATING,
    AI_TRAINING_STATUS_TYPES.EVALUATING,
    AI_TRAINING_STATUS_TYPES.TESTING,
    AI_TRAINING_STATUS_TYPES.CHECKPOINT,
    AI_TRAINING_STATUS_TYPES.SAVING,
    AI_TRAINING_STATUS_TYPES.RESUMING,
  ];
  return activeStatuses.includes(status);
}

export function isTrainingComplete(status: AITrainingStatusType): boolean {
  const completeStatuses: AITrainingStatusType[] = [
    AI_TRAINING_STATUS_TYPES.COMPLETED,
    AI_TRAINING_STATUS_TYPES.DEPLOYED,
    AI_TRAINING_STATUS_TYPES.ARCHIVED,
  ];
  return completeStatuses.includes(status);
}

export function isTrainingFailed(status: AITrainingStatusType): boolean {
  const failedStatuses: AITrainingStatusType[] = [
    AI_TRAINING_STATUS_TYPES.FAILED,
    AI_TRAINING_STATUS_TYPES.CANCELLED,
  ];
  return failedStatuses.includes(status);
}

export function isTrainingPaused(status: AITrainingStatusType): boolean {
  return status === AI_TRAINING_STATUS_TYPES.PAUSED;
}
