/**
 * AI Vector Status Constants
 * Status tracking for vector lifecycle
 */

// First define the status types
export const AI_VECTOR_STATUS_TYPES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Processing States
  INITIALIZING: 'initializing',
  GENERATING: 'generating',
  PROCESSING: 'processing',
  NORMALIZING: 'normalizing',
  VALIDATING: 'validating',

  // Indexing States
  INDEXING: 'indexing',
  REINDEXING: 'reindexing',
  OPTIMIZING: 'optimizing',

  // Intermediate States
  GENERATED: 'generated',
  PROCESSED: 'processed',
  NORMALIZED: 'normalized',
  VALIDATED: 'validated',
  INDEXED: 'indexed',
  OPTIMIZED: 'optimized',

  // Storage States
  STORING: 'storing',
  STORED: 'stored',
  CACHING: 'caching',
  CACHED: 'cached',

  // Terminal States
  COMPLETED: 'completed',
  FAILED: 'failed',
  EXPIRED: 'expired',
  ARCHIVED: 'archived',
} as const;

export type AIVectorStatusType =
  (typeof AI_VECTOR_STATUS_TYPES)[keyof typeof AI_VECTOR_STATUS_TYPES];

export const AI_VECTOR_STATUS = {
  // Status Types
  STATUSES: AI_VECTOR_STATUS_TYPES,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    INDEXING: 'indexing',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CACHED: 'cached',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_VECTOR_STATUS_TYPES.CREATED]: '#gray',
    [AI_VECTOR_STATUS_TYPES.QUEUED]: '#gray',
    [AI_VECTOR_STATUS_TYPES.PENDING]: '#yellow',
    [AI_VECTOR_STATUS_TYPES.INITIALIZING]: '#blue',
    [AI_VECTOR_STATUS_TYPES.GENERATING]: '#blue',
    [AI_VECTOR_STATUS_TYPES.PROCESSING]: '#blue',
    [AI_VECTOR_STATUS_TYPES.NORMALIZING]: '#blue',
    [AI_VECTOR_STATUS_TYPES.VALIDATING]: '#purple',
    [AI_VECTOR_STATUS_TYPES.INDEXING]: '#blue',
    [AI_VECTOR_STATUS_TYPES.REINDEXING]: '#orange',
    [AI_VECTOR_STATUS_TYPES.OPTIMIZING]: '#orange',
    [AI_VECTOR_STATUS_TYPES.GENERATED]: '#green',
    [AI_VECTOR_STATUS_TYPES.PROCESSED]: '#green',
    [AI_VECTOR_STATUS_TYPES.NORMALIZED]: '#green',
    [AI_VECTOR_STATUS_TYPES.VALIDATED]: '#green',
    [AI_VECTOR_STATUS_TYPES.INDEXED]: '#green',
    [AI_VECTOR_STATUS_TYPES.OPTIMIZED]: '#green',
    [AI_VECTOR_STATUS_TYPES.STORING]: '#orange',
    [AI_VECTOR_STATUS_TYPES.STORED]: '#green',
    [AI_VECTOR_STATUS_TYPES.CACHING]: '#orange',
    [AI_VECTOR_STATUS_TYPES.CACHED]: '#green',
    [AI_VECTOR_STATUS_TYPES.COMPLETED]: '#green',
    [AI_VECTOR_STATUS_TYPES.FAILED]: '#red',
    [AI_VECTOR_STATUS_TYPES.EXPIRED]: '#gray',
    [AI_VECTOR_STATUS_TYPES.ARCHIVED]: '#gray',
  } as const,
} as const;

export type AIVectorStatusCategory =
  (typeof AI_VECTOR_STATUS.CATEGORIES)[keyof typeof AI_VECTOR_STATUS.CATEGORIES];
export type AIVectorStatusSeverity =
  (typeof AI_VECTOR_STATUS.SEVERITY)[keyof typeof AI_VECTOR_STATUS.SEVERITY];
export type AIVectorStatusColor =
  (typeof AI_VECTOR_STATUS.COLORS)[keyof typeof AI_VECTOR_STATUS.COLORS];

export function getAiVectorStatusLabel(status: AIVectorStatusType): string {
  const labels: Record<AIVectorStatusType, string> = {
    [AI_VECTOR_STATUS_TYPES.CREATED]: 'Created',
    [AI_VECTOR_STATUS_TYPES.QUEUED]: 'Queued',
    [AI_VECTOR_STATUS_TYPES.PENDING]: 'Pending',
    [AI_VECTOR_STATUS_TYPES.INITIALIZING]: 'Initializing',
    [AI_VECTOR_STATUS_TYPES.GENERATING]: 'Generating',
    [AI_VECTOR_STATUS_TYPES.PROCESSING]: 'Processing',
    [AI_VECTOR_STATUS_TYPES.NORMALIZING]: 'Normalizing',
    [AI_VECTOR_STATUS_TYPES.VALIDATING]: 'Validating',
    [AI_VECTOR_STATUS_TYPES.INDEXING]: 'Indexing',
    [AI_VECTOR_STATUS_TYPES.REINDEXING]: 'Reindexing',
    [AI_VECTOR_STATUS_TYPES.OPTIMIZING]: 'Optimizing',
    [AI_VECTOR_STATUS_TYPES.GENERATED]: 'Generated',
    [AI_VECTOR_STATUS_TYPES.PROCESSED]: 'Processed',
    [AI_VECTOR_STATUS_TYPES.NORMALIZED]: 'Normalized',
    [AI_VECTOR_STATUS_TYPES.VALIDATED]: 'Validated',
    [AI_VECTOR_STATUS_TYPES.INDEXED]: 'Indexed',
    [AI_VECTOR_STATUS_TYPES.OPTIMIZED]: 'Optimized',
    [AI_VECTOR_STATUS_TYPES.STORING]: 'Storing',
    [AI_VECTOR_STATUS_TYPES.STORED]: 'Stored',
    [AI_VECTOR_STATUS_TYPES.CACHING]: 'Caching',
    [AI_VECTOR_STATUS_TYPES.CACHED]: 'Cached',
    [AI_VECTOR_STATUS_TYPES.COMPLETED]: 'Completed',
    [AI_VECTOR_STATUS_TYPES.FAILED]: 'Failed',
    [AI_VECTOR_STATUS_TYPES.EXPIRED]: 'Expired',
    [AI_VECTOR_STATUS_TYPES.ARCHIVED]: 'Archived',
  };
  return labels[status] || 'Unknown';
}

export function getAiVectorStatusCategory(status: AIVectorStatusType): AIVectorStatusCategory {
  const categories: Record<AIVectorStatusType, AIVectorStatusCategory> = {
    [AI_VECTOR_STATUS_TYPES.CREATED]: AI_VECTOR_STATUS.CATEGORIES.PENDING,
    [AI_VECTOR_STATUS_TYPES.QUEUED]: AI_VECTOR_STATUS.CATEGORIES.PENDING,
    [AI_VECTOR_STATUS_TYPES.PENDING]: AI_VECTOR_STATUS.CATEGORIES.PENDING,
    [AI_VECTOR_STATUS_TYPES.INITIALIZING]: AI_VECTOR_STATUS.CATEGORIES.PROCESSING,
    [AI_VECTOR_STATUS_TYPES.GENERATING]: AI_VECTOR_STATUS.CATEGORIES.PROCESSING,
    [AI_VECTOR_STATUS_TYPES.PROCESSING]: AI_VECTOR_STATUS.CATEGORIES.PROCESSING,
    [AI_VECTOR_STATUS_TYPES.NORMALIZING]: AI_VECTOR_STATUS.CATEGORIES.PROCESSING,
    [AI_VECTOR_STATUS_TYPES.VALIDATING]: AI_VECTOR_STATUS.CATEGORIES.PROCESSING,
    [AI_VECTOR_STATUS_TYPES.INDEXING]: AI_VECTOR_STATUS.CATEGORIES.INDEXING,
    [AI_VECTOR_STATUS_TYPES.REINDEXING]: AI_VECTOR_STATUS.CATEGORIES.INDEXING,
    [AI_VECTOR_STATUS_TYPES.OPTIMIZING]: AI_VECTOR_STATUS.CATEGORIES.INDEXING,
    [AI_VECTOR_STATUS_TYPES.GENERATED]: AI_VECTOR_STATUS.CATEGORIES.PROCESSING,
    [AI_VECTOR_STATUS_TYPES.PROCESSED]: AI_VECTOR_STATUS.CATEGORIES.PROCESSING,
    [AI_VECTOR_STATUS_TYPES.NORMALIZED]: AI_VECTOR_STATUS.CATEGORIES.PROCESSING,
    [AI_VECTOR_STATUS_TYPES.VALIDATED]: AI_VECTOR_STATUS.CATEGORIES.PROCESSING,
    [AI_VECTOR_STATUS_TYPES.INDEXED]: AI_VECTOR_STATUS.CATEGORIES.INDEXING,
    [AI_VECTOR_STATUS_TYPES.OPTIMIZED]: AI_VECTOR_STATUS.CATEGORIES.INDEXING,
    [AI_VECTOR_STATUS_TYPES.STORING]: AI_VECTOR_STATUS.CATEGORIES.PROCESSING,
    [AI_VECTOR_STATUS_TYPES.STORED]: AI_VECTOR_STATUS.CATEGORIES.COMPLETED,
    [AI_VECTOR_STATUS_TYPES.CACHING]: AI_VECTOR_STATUS.CATEGORIES.PROCESSING,
    [AI_VECTOR_STATUS_TYPES.CACHED]: AI_VECTOR_STATUS.CATEGORIES.CACHED,
    [AI_VECTOR_STATUS_TYPES.COMPLETED]: AI_VECTOR_STATUS.CATEGORIES.COMPLETED,
    [AI_VECTOR_STATUS_TYPES.FAILED]: AI_VECTOR_STATUS.CATEGORIES.FAILED,
    [AI_VECTOR_STATUS_TYPES.EXPIRED]: AI_VECTOR_STATUS.CATEGORIES.FAILED,
    [AI_VECTOR_STATUS_TYPES.ARCHIVED]: AI_VECTOR_STATUS.CATEGORIES.COMPLETED,
  };
  return categories[status] || AI_VECTOR_STATUS.CATEGORIES.PENDING;
}

export function getAiVectorStatusSeverity(status: AIVectorStatusType): AIVectorStatusSeverity {
  const severities: Record<AIVectorStatusType, AIVectorStatusSeverity> = {
    [AI_VECTOR_STATUS_TYPES.CREATED]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.QUEUED]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.PENDING]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.INITIALIZING]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.GENERATING]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.PROCESSING]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.NORMALIZING]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.VALIDATING]: AI_VECTOR_STATUS.SEVERITY.WARNING,
    [AI_VECTOR_STATUS_TYPES.INDEXING]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.REINDEXING]: AI_VECTOR_STATUS.SEVERITY.WARNING,
    [AI_VECTOR_STATUS_TYPES.OPTIMIZING]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.GENERATED]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.PROCESSED]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.NORMALIZED]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.VALIDATED]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.INDEXED]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.OPTIMIZED]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.STORING]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.STORED]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.CACHING]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.CACHED]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.COMPLETED]: AI_VECTOR_STATUS.SEVERITY.INFO,
    [AI_VECTOR_STATUS_TYPES.FAILED]: AI_VECTOR_STATUS.SEVERITY.ERROR,
    [AI_VECTOR_STATUS_TYPES.EXPIRED]: AI_VECTOR_STATUS.SEVERITY.WARNING,
    [AI_VECTOR_STATUS_TYPES.ARCHIVED]: AI_VECTOR_STATUS.SEVERITY.INFO,
  };
  return severities[status] || AI_VECTOR_STATUS.SEVERITY.INFO;
}

export function getAiVectorStatusColor(status: AIVectorStatusType): AIVectorStatusColor {
  return AI_VECTOR_STATUS.COLORS[status] || '#gray';
}

export function isAiVectorActiveStatus(status: AIVectorStatusType): boolean {
  const activeStatuses: AIVectorStatusType[] = [
    AI_VECTOR_STATUS_TYPES.CREATED,
    AI_VECTOR_STATUS_TYPES.QUEUED,
    AI_VECTOR_STATUS_TYPES.PENDING,
    AI_VECTOR_STATUS_TYPES.INITIALIZING,
    AI_VECTOR_STATUS_TYPES.GENERATING,
    AI_VECTOR_STATUS_TYPES.PROCESSING,
    AI_VECTOR_STATUS_TYPES.NORMALIZING,
    AI_VECTOR_STATUS_TYPES.VALIDATING,
    AI_VECTOR_STATUS_TYPES.INDEXING,
    AI_VECTOR_STATUS_TYPES.REINDEXING,
    AI_VECTOR_STATUS_TYPES.OPTIMIZING,
    AI_VECTOR_STATUS_TYPES.GENERATED,
    AI_VECTOR_STATUS_TYPES.PROCESSED,
    AI_VECTOR_STATUS_TYPES.NORMALIZED,
    AI_VECTOR_STATUS_TYPES.VALIDATED,
    AI_VECTOR_STATUS_TYPES.INDEXED,
    AI_VECTOR_STATUS_TYPES.OPTIMIZED,
    AI_VECTOR_STATUS_TYPES.STORING,
    AI_VECTOR_STATUS_TYPES.CACHING,
  ];
  return activeStatuses.includes(status);
}

export function isAiVectorGenerated(status: AIVectorStatusType): boolean {
  const generatedStatuses: AIVectorStatusType[] = [
    AI_VECTOR_STATUS_TYPES.GENERATED,
    AI_VECTOR_STATUS_TYPES.PROCESSED,
    AI_VECTOR_STATUS_TYPES.NORMALIZED,
    AI_VECTOR_STATUS_TYPES.VALIDATED,
    AI_VECTOR_STATUS_TYPES.INDEXED,
    AI_VECTOR_STATUS_TYPES.OPTIMIZED,
    AI_VECTOR_STATUS_TYPES.STORED,
    AI_VECTOR_STATUS_TYPES.CACHED,
    AI_VECTOR_STATUS_TYPES.COMPLETED,
  ];
  return generatedStatuses.includes(status);
}

export function isAiVectorCompleted(status: AIVectorStatusType): boolean {
  const completedStatuses: AIVectorStatusType[] = [
    AI_VECTOR_STATUS_TYPES.COMPLETED,
    AI_VECTOR_STATUS_TYPES.STORED,
    AI_VECTOR_STATUS_TYPES.CACHED,
    AI_VECTOR_STATUS_TYPES.ARCHIVED,
  ];
  return completedStatuses.includes(status);
}

export function isAiVectorFailedStatus(status: AIVectorStatusType): boolean {
  const failedStatuses: AIVectorStatusType[] = [
    AI_VECTOR_STATUS_TYPES.FAILED,
    AI_VECTOR_STATUS_TYPES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}

export function getAiVectorStatusProgress(status: AIVectorStatusType): number {
  const progress: Record<AIVectorStatusType, number> = {
    [AI_VECTOR_STATUS_TYPES.CREATED]: 0,
    [AI_VECTOR_STATUS_TYPES.QUEUED]: 5,
    [AI_VECTOR_STATUS_TYPES.PENDING]: 10,
    [AI_VECTOR_STATUS_TYPES.INITIALIZING]: 15,
    [AI_VECTOR_STATUS_TYPES.GENERATING]: 25,
    [AI_VECTOR_STATUS_TYPES.PROCESSING]: 35,
    [AI_VECTOR_STATUS_TYPES.NORMALIZING]: 45,
    [AI_VECTOR_STATUS_TYPES.VALIDATING]: 50,
    [AI_VECTOR_STATUS_TYPES.INDEXING]: 60,
    [AI_VECTOR_STATUS_TYPES.REINDEXING]: 55,
    [AI_VECTOR_STATUS_TYPES.OPTIMIZING]: 70,
    [AI_VECTOR_STATUS_TYPES.GENERATED]: 40,
    [AI_VECTOR_STATUS_TYPES.PROCESSED]: 45,
    [AI_VECTOR_STATUS_TYPES.NORMALIZED]: 50,
    [AI_VECTOR_STATUS_TYPES.VALIDATED]: 55,
    [AI_VECTOR_STATUS_TYPES.INDEXED]: 65,
    [AI_VECTOR_STATUS_TYPES.OPTIMIZED]: 75,
    [AI_VECTOR_STATUS_TYPES.STORING]: 80,
    [AI_VECTOR_STATUS_TYPES.STORED]: 85,
    [AI_VECTOR_STATUS_TYPES.CACHING]: 88,
    [AI_VECTOR_STATUS_TYPES.CACHED]: 92,
    [AI_VECTOR_STATUS_TYPES.COMPLETED]: 100,
    [AI_VECTOR_STATUS_TYPES.FAILED]: 0,
    [AI_VECTOR_STATUS_TYPES.EXPIRED]: 0,
    [AI_VECTOR_STATUS_TYPES.ARCHIVED]: 100,
  };
  return progress[status] || 0;
}
