/**
 * Courier Type Constants
 * Types of courier services
 */

export const LOGISTICS_COURIER_TYPE = {
  // Type Types
  TYPES: {
    LOCAL: 'local',
    NATIONAL: 'national',
    INTERNATIONAL: 'international',
    EXPRESS: 'express',
    STANDARD: 'standard',
    ECONOMY: 'economy',
  } as const,

  // Type Categories
  CATEGORIES: {
    DOMESTIC: 'domestic',
    INTERNATIONAL: 'international',
    PREMIUM: 'premium',
    REGULAR: 'regular',
  } as const,

  // Type Icons (for UI)
  ICONS: {
    LOCAL: '🏠',
    NATIONAL: '🇧🇩',
    INTERNATIONAL: '✈️',
    EXPRESS: '🚀',
    STANDARD: '📦',
    ECONOMY: '💰',
  } as const,

  // Type Colors (for UI)
  COLORS: {
    LOCAL: '#green-500',
    NATIONAL: '#blue-500',
    INTERNATIONAL: '#purple-500',
    EXPRESS: '#orange-500',
    STANDARD: '#blue-400',
    ECONOMY: '#gray-500',
  } as const,

  // Delivery Time (in days)
  DELIVERY_TIME: {
    LOCAL: 1,
    NATIONAL: 3,
    INTERNATIONAL: 7,
    EXPRESS: 1,
    STANDARD: 3,
    ECONOMY: 5,
  } as const,

  // Price Multiplier
  PRICE_MULTIPLIER: {
    LOCAL: 1.0,
    NATIONAL: 1.5,
    INTERNATIONAL: 5.0,
    EXPRESS: 2.0,
    STANDARD: 1.0,
    ECONOMY: 0.8,
  } as const,

  // Coverage
  COVERAGE: {
    LOCAL: 'Local Area',
    NATIONAL: 'Bangladesh',
    INTERNATIONAL: 'Worldwide',
    EXPRESS: 'Major Cities',
    STANDARD: 'All Areas',
    ECONOMY: 'All Areas',
  } as const,
} as const;

// Type Types
export type LogisticsCourierTypeType =
  (typeof LOGISTICS_COURIER_TYPE.TYPES)[keyof typeof LOGISTICS_COURIER_TYPE.TYPES];

// Type Categories
export type LogisticsCourierTypeCategory =
  (typeof LOGISTICS_COURIER_TYPE.CATEGORIES)[keyof typeof LOGISTICS_COURIER_TYPE.CATEGORIES];

// Type Icons
export type LogisticsCourierTypeIcon =
  (typeof LOGISTICS_COURIER_TYPE.ICONS)[keyof typeof LOGISTICS_COURIER_TYPE.ICONS];

// Type Colors
export type LogisticsCourierTypeColor =
  (typeof LOGISTICS_COURIER_TYPE.COLORS)[keyof typeof LOGISTICS_COURIER_TYPE.COLORS];

// Utility Functions
export function logisticsCourierTypeGetLabel(type: LogisticsCourierTypeType): string {
  const labels: Record<LogisticsCourierTypeType, string> = {
    [LOGISTICS_COURIER_TYPE.TYPES.LOCAL]: 'Local',
    [LOGISTICS_COURIER_TYPE.TYPES.NATIONAL]: 'National',
    [LOGISTICS_COURIER_TYPE.TYPES.INTERNATIONAL]: 'International',
    [LOGISTICS_COURIER_TYPE.TYPES.EXPRESS]: 'Express',
    [LOGISTICS_COURIER_TYPE.TYPES.STANDARD]: 'Standard',
    [LOGISTICS_COURIER_TYPE.TYPES.ECONOMY]: 'Economy',
  };
  return labels[type] || 'Unknown';
}

export function logisticsCourierTypeGetCategory(
  type: LogisticsCourierTypeType
): LogisticsCourierTypeCategory {
  const categories: Record<LogisticsCourierTypeType, LogisticsCourierTypeCategory> = {
    [LOGISTICS_COURIER_TYPE.TYPES.LOCAL]: LOGISTICS_COURIER_TYPE.CATEGORIES.DOMESTIC,
    [LOGISTICS_COURIER_TYPE.TYPES.NATIONAL]: LOGISTICS_COURIER_TYPE.CATEGORIES.DOMESTIC,
    [LOGISTICS_COURIER_TYPE.TYPES.INTERNATIONAL]: LOGISTICS_COURIER_TYPE.CATEGORIES.INTERNATIONAL,
    [LOGISTICS_COURIER_TYPE.TYPES.EXPRESS]: LOGISTICS_COURIER_TYPE.CATEGORIES.PREMIUM,
    [LOGISTICS_COURIER_TYPE.TYPES.STANDARD]: LOGISTICS_COURIER_TYPE.CATEGORIES.REGULAR,
    [LOGISTICS_COURIER_TYPE.TYPES.ECONOMY]: LOGISTICS_COURIER_TYPE.CATEGORIES.REGULAR,
  };
  return categories[type] || LOGISTICS_COURIER_TYPE.CATEGORIES.REGULAR;
}

export function logisticsCourierTypeGetIcon(
  type: LogisticsCourierTypeType
): LogisticsCourierTypeIcon {
  const icons: Record<LogisticsCourierTypeType, LogisticsCourierTypeIcon> = {
    [LOGISTICS_COURIER_TYPE.TYPES.LOCAL]: LOGISTICS_COURIER_TYPE.ICONS.LOCAL,
    [LOGISTICS_COURIER_TYPE.TYPES.NATIONAL]: LOGISTICS_COURIER_TYPE.ICONS.NATIONAL,
    [LOGISTICS_COURIER_TYPE.TYPES.INTERNATIONAL]: LOGISTICS_COURIER_TYPE.ICONS.INTERNATIONAL,
    [LOGISTICS_COURIER_TYPE.TYPES.EXPRESS]: LOGISTICS_COURIER_TYPE.ICONS.EXPRESS,
    [LOGISTICS_COURIER_TYPE.TYPES.STANDARD]: LOGISTICS_COURIER_TYPE.ICONS.STANDARD,
    [LOGISTICS_COURIER_TYPE.TYPES.ECONOMY]: LOGISTICS_COURIER_TYPE.ICONS.ECONOMY,
  };
  return icons[type] || '📦';
}

export function logisticsCourierTypeGetColor(
  type: LogisticsCourierTypeType
): LogisticsCourierTypeColor {
  const colors: Record<LogisticsCourierTypeType, LogisticsCourierTypeColor> = {
    [LOGISTICS_COURIER_TYPE.TYPES.LOCAL]: LOGISTICS_COURIER_TYPE.COLORS.LOCAL,
    [LOGISTICS_COURIER_TYPE.TYPES.NATIONAL]: LOGISTICS_COURIER_TYPE.COLORS.NATIONAL,
    [LOGISTICS_COURIER_TYPE.TYPES.INTERNATIONAL]: LOGISTICS_COURIER_TYPE.COLORS.INTERNATIONAL,
    [LOGISTICS_COURIER_TYPE.TYPES.EXPRESS]: LOGISTICS_COURIER_TYPE.COLORS.EXPRESS,
    [LOGISTICS_COURIER_TYPE.TYPES.STANDARD]: LOGISTICS_COURIER_TYPE.COLORS.STANDARD,
    [LOGISTICS_COURIER_TYPE.TYPES.ECONOMY]: LOGISTICS_COURIER_TYPE.COLORS.ECONOMY,
  };
  return colors[type] || '#blue-400';
}

export function logisticsCourierTypeGetDeliveryTime(type: LogisticsCourierTypeType): number {
  const times: Record<LogisticsCourierTypeType, number> = {
    [LOGISTICS_COURIER_TYPE.TYPES.LOCAL]: LOGISTICS_COURIER_TYPE.DELIVERY_TIME.LOCAL,
    [LOGISTICS_COURIER_TYPE.TYPES.NATIONAL]: LOGISTICS_COURIER_TYPE.DELIVERY_TIME.NATIONAL,
    [LOGISTICS_COURIER_TYPE.TYPES.INTERNATIONAL]:
      LOGISTICS_COURIER_TYPE.DELIVERY_TIME.INTERNATIONAL,
    [LOGISTICS_COURIER_TYPE.TYPES.EXPRESS]: LOGISTICS_COURIER_TYPE.DELIVERY_TIME.EXPRESS,
    [LOGISTICS_COURIER_TYPE.TYPES.STANDARD]: LOGISTICS_COURIER_TYPE.DELIVERY_TIME.STANDARD,
    [LOGISTICS_COURIER_TYPE.TYPES.ECONOMY]: LOGISTICS_COURIER_TYPE.DELIVERY_TIME.ECONOMY,
  };
  return times[type] || LOGISTICS_COURIER_TYPE.DELIVERY_TIME.STANDARD;
}

export function logisticsCourierTypeGetPriceMultiplier(type: LogisticsCourierTypeType): number {
  const multipliers: Record<LogisticsCourierTypeType, number> = {
    [LOGISTICS_COURIER_TYPE.TYPES.LOCAL]: LOGISTICS_COURIER_TYPE.PRICE_MULTIPLIER.LOCAL,
    [LOGISTICS_COURIER_TYPE.TYPES.NATIONAL]: LOGISTICS_COURIER_TYPE.PRICE_MULTIPLIER.NATIONAL,
    [LOGISTICS_COURIER_TYPE.TYPES.INTERNATIONAL]:
      LOGISTICS_COURIER_TYPE.PRICE_MULTIPLIER.INTERNATIONAL,
    [LOGISTICS_COURIER_TYPE.TYPES.EXPRESS]: LOGISTICS_COURIER_TYPE.PRICE_MULTIPLIER.EXPRESS,
    [LOGISTICS_COURIER_TYPE.TYPES.STANDARD]: LOGISTICS_COURIER_TYPE.PRICE_MULTIPLIER.STANDARD,
    [LOGISTICS_COURIER_TYPE.TYPES.ECONOMY]: LOGISTICS_COURIER_TYPE.PRICE_MULTIPLIER.ECONOMY,
  };
  return multipliers[type] || 1.0;
}

export function logisticsCourierTypeGetCoverage(type: LogisticsCourierTypeType): string {
  const coverage: Record<LogisticsCourierTypeType, string> = {
    [LOGISTICS_COURIER_TYPE.TYPES.LOCAL]: LOGISTICS_COURIER_TYPE.COVERAGE.LOCAL,
    [LOGISTICS_COURIER_TYPE.TYPES.NATIONAL]: LOGISTICS_COURIER_TYPE.COVERAGE.NATIONAL,
    [LOGISTICS_COURIER_TYPE.TYPES.INTERNATIONAL]: LOGISTICS_COURIER_TYPE.COVERAGE.INTERNATIONAL,
    [LOGISTICS_COURIER_TYPE.TYPES.EXPRESS]: LOGISTICS_COURIER_TYPE.COVERAGE.EXPRESS,
    [LOGISTICS_COURIER_TYPE.TYPES.STANDARD]: LOGISTICS_COURIER_TYPE.COVERAGE.STANDARD,
    [LOGISTICS_COURIER_TYPE.TYPES.ECONOMY]: LOGISTICS_COURIER_TYPE.COVERAGE.ECONOMY,
  };
  return coverage[type] || LOGISTICS_COURIER_TYPE.COVERAGE.STANDARD;
}
