/**
 * AI পারমিশন এনাম
 */
export const AI_PERMISSION = {
  MANAGE_MODELS: 'manage-models',
  VIEW_MODELS: 'view-models',
  TRAIN_MODELS: 'train-models',
  GENERATE_RECOMMENDATIONS: 'generate-recommendations',
  MANAGE_RECOMMENDATIONS: 'manage-recommendations',
  MANAGE_PERSONALIZATION: 'manage-personalization',
  MANAGE_SEARCH: 'manage-search',
  MANAGE_RANKING: 'manage-ranking',
  VIEW_ANALYTICS: 'view-analytics',
  MANAGE_TRAINING: 'manage-training',
  MANAGE_FEATURES: 'manage-features',
  MANAGE_PROMPTS: 'manage-prompts',
  MANAGE_EMBEDDINGS: 'manage-embeddings',
  MANAGE_VECTORS: 'manage-vectors',
  VIEW_INSIGHTS: 'view-insights',
} as const;

/**
 * AI_PERMISSION থেকে টাইপ
 */
export type AIPermissionType = (typeof AI_PERMISSION)[keyof typeof AI_PERMISSION];

/**
 * AI পারমিশন লেবেল
 */
export const AI_PERMISSION_LABELS: Record<AIPermissionType, string> = {
  [AI_PERMISSION.MANAGE_MODELS]: 'Manage Models',
  [AI_PERMISSION.VIEW_MODELS]: 'View Models',
  [AI_PERMISSION.TRAIN_MODELS]: 'Train Models',
  [AI_PERMISSION.GENERATE_RECOMMENDATIONS]: 'Generate Recommendations',
  [AI_PERMISSION.MANAGE_RECOMMENDATIONS]: 'Manage Recommendations',
  [AI_PERMISSION.MANAGE_PERSONALIZATION]: 'Manage Personalization',
  [AI_PERMISSION.MANAGE_SEARCH]: 'Manage Search',
  [AI_PERMISSION.MANAGE_RANKING]: 'Manage Ranking',
  [AI_PERMISSION.VIEW_ANALYTICS]: 'View Analytics',
  [AI_PERMISSION.MANAGE_TRAINING]: 'Manage Training',
  [AI_PERMISSION.MANAGE_FEATURES]: 'Manage Features',
  [AI_PERMISSION.MANAGE_PROMPTS]: 'Manage Prompts',
  [AI_PERMISSION.MANAGE_EMBEDDINGS]: 'Manage Embeddings',
  [AI_PERMISSION.MANAGE_VECTORS]: 'Manage Vectors',
  [AI_PERMISSION.VIEW_INSIGHTS]: 'View Insights',
} as const;

/**
 * AI পারমিশন বিবরণ
 */
export const AI_PERMISSION_DESCRIPTIONS: Record<AIPermissionType, string> = {
  [AI_PERMISSION.MANAGE_MODELS]:
    'Full control over AI models including creation, update, and deletion',
  [AI_PERMISSION.VIEW_MODELS]: 'View AI models and their configurations',
  [AI_PERMISSION.TRAIN_MODELS]: 'Train and fine-tune AI models',
  [AI_PERMISSION.GENERATE_RECOMMENDATIONS]: 'Generate recommendations using AI models',
  [AI_PERMISSION.MANAGE_RECOMMENDATIONS]: 'Manage recommendation configurations and rules',
  [AI_PERMISSION.MANAGE_PERSONALIZATION]: 'Manage personalization settings and strategies',
  [AI_PERMISSION.MANAGE_SEARCH]: 'Manage search configurations and indexing',
  [AI_PERMISSION.MANAGE_RANKING]: 'Manage ranking algorithms and strategies',
  [AI_PERMISSION.VIEW_ANALYTICS]: 'View analytics and insights from AI systems',
  [AI_PERMISSION.MANAGE_TRAINING]: 'Manage training pipelines and datasets',
  [AI_PERMISSION.MANAGE_FEATURES]: 'Manage AI features and feature flags',
  [AI_PERMISSION.MANAGE_PROMPTS]: 'Manage AI prompts and templates',
  [AI_PERMISSION.MANAGE_EMBEDDINGS]: 'Manage embedding models and generation',
  [AI_PERMISSION.MANAGE_VECTORS]: 'Manage vector databases and operations',
  [AI_PERMISSION.VIEW_INSIGHTS]: 'View AI-generated insights and analysis',
} as const;

/**
 * AI পারমিশন আইকন
 */
export const AI_PERMISSION_ICONS: Record<AIPermissionType, string> = {
  [AI_PERMISSION.MANAGE_MODELS]: '🧠',
  [AI_PERMISSION.VIEW_MODELS]: '👁️',
  [AI_PERMISSION.TRAIN_MODELS]: '🎓',
  [AI_PERMISSION.GENERATE_RECOMMENDATIONS]: '💡',
  [AI_PERMISSION.MANAGE_RECOMMENDATIONS]: '⚙️',
  [AI_PERMISSION.MANAGE_PERSONALIZATION]: '👤',
  [AI_PERMISSION.MANAGE_SEARCH]: '🔍',
  [AI_PERMISSION.MANAGE_RANKING]: '📊',
  [AI_PERMISSION.VIEW_ANALYTICS]: '📈',
  [AI_PERMISSION.MANAGE_TRAINING]: '🏋️',
  [AI_PERMISSION.MANAGE_FEATURES]: '🚩',
  [AI_PERMISSION.MANAGE_PROMPTS]: '📝',
  [AI_PERMISSION.MANAGE_EMBEDDINGS]: '🌀',
  [AI_PERMISSION.MANAGE_VECTORS]: '📐',
  [AI_PERMISSION.VIEW_INSIGHTS]: '💎',
} as const;

/**
 * AI পারমিশন গ্রুপ
 */
export const AI_PERMISSION_GROUP = {
  MODEL: 'model',
  RECOMMENDATION: 'recommendation',
  SEARCH: 'search',
  ANALYTICS: 'analytics',
  TRAINING: 'training',
  MANAGEMENT: 'management',
} as const;

/**
 * AI_PERMISSION_GROUP থেকে টাইপ
 */
export type AIPermissionGroupType = (typeof AI_PERMISSION_GROUP)[keyof typeof AI_PERMISSION_GROUP];

/**
 * AI পারমিশন গ্রুপ লেবেল
 */
export const AI_PERMISSION_GROUP_LABELS: Record<AIPermissionGroupType, string> = {
  [AI_PERMISSION_GROUP.MODEL]: 'Model Management',
  [AI_PERMISSION_GROUP.RECOMMENDATION]: 'Recommendation',
  [AI_PERMISSION_GROUP.SEARCH]: 'Search & Ranking',
  [AI_PERMISSION_GROUP.ANALYTICS]: 'Analytics & Insights',
  [AI_PERMISSION_GROUP.TRAINING]: 'Training',
  [AI_PERMISSION_GROUP.MANAGEMENT]: 'System Management',
} as const;

/**
 * পারমিশন গ্রুপ ম্যাপিং
 */
export const AI_PERMISSION_GROUP_MAP: Record<AIPermissionType, AIPermissionGroupType> = {
  [AI_PERMISSION.MANAGE_MODELS]: AI_PERMISSION_GROUP.MODEL,
  [AI_PERMISSION.VIEW_MODELS]: AI_PERMISSION_GROUP.MODEL,
  [AI_PERMISSION.TRAIN_MODELS]: AI_PERMISSION_GROUP.MODEL,
  [AI_PERMISSION.GENERATE_RECOMMENDATIONS]: AI_PERMISSION_GROUP.RECOMMENDATION,
  [AI_PERMISSION.MANAGE_RECOMMENDATIONS]: AI_PERMISSION_GROUP.RECOMMENDATION,
  [AI_PERMISSION.MANAGE_PERSONALIZATION]: AI_PERMISSION_GROUP.RECOMMENDATION,
  [AI_PERMISSION.MANAGE_SEARCH]: AI_PERMISSION_GROUP.SEARCH,
  [AI_PERMISSION.MANAGE_RANKING]: AI_PERMISSION_GROUP.SEARCH,
  [AI_PERMISSION.VIEW_ANALYTICS]: AI_PERMISSION_GROUP.ANALYTICS,
  [AI_PERMISSION.MANAGE_TRAINING]: AI_PERMISSION_GROUP.TRAINING,
  [AI_PERMISSION.MANAGE_FEATURES]: AI_PERMISSION_GROUP.MANAGEMENT,
  [AI_PERMISSION.MANAGE_PROMPTS]: AI_PERMISSION_GROUP.MANAGEMENT,
  [AI_PERMISSION.MANAGE_EMBEDDINGS]: AI_PERMISSION_GROUP.MANAGEMENT,
  [AI_PERMISSION.MANAGE_VECTORS]: AI_PERMISSION_GROUP.MANAGEMENT,
  [AI_PERMISSION.VIEW_INSIGHTS]: AI_PERMISSION_GROUP.ANALYTICS,
} as const;

/**
 * AI পারমিশন ক্যাটাগরি
 */
export const AI_PERMISSION_CATEGORY = {
  ADMIN: 'admin',
  MANAGER: 'manager',
  VIEWER: 'viewer',
} as const;

/**
 * AI_PERMISSION_CATEGORY থেকে টাইপ
 */
export type AIPermissionCategoryType =
  (typeof AI_PERMISSION_CATEGORY)[keyof typeof AI_PERMISSION_CATEGORY];

/**
 * AI পারমিশন ক্যাটাগরি লেবেল
 */
export const AI_PERMISSION_CATEGORY_LABELS: Record<AIPermissionCategoryType, string> = {
  [AI_PERMISSION_CATEGORY.ADMIN]: 'Admin',
  [AI_PERMISSION_CATEGORY.MANAGER]: 'Manager',
  [AI_PERMISSION_CATEGORY.VIEWER]: 'Viewer',
} as const;

/**
 * পারমিশন ক্যাটাগরি ম্যাপিং
 */
export const AI_PERMISSION_CATEGORY_MAP: Record<AIPermissionType, AIPermissionCategoryType> = {
  [AI_PERMISSION.MANAGE_MODELS]: AI_PERMISSION_CATEGORY.ADMIN,
  [AI_PERMISSION.VIEW_MODELS]: AI_PERMISSION_CATEGORY.VIEWER,
  [AI_PERMISSION.TRAIN_MODELS]: AI_PERMISSION_CATEGORY.MANAGER,
  [AI_PERMISSION.GENERATE_RECOMMENDATIONS]: AI_PERMISSION_CATEGORY.MANAGER,
  [AI_PERMISSION.MANAGE_RECOMMENDATIONS]: AI_PERMISSION_CATEGORY.ADMIN,
  [AI_PERMISSION.MANAGE_PERSONALIZATION]: AI_PERMISSION_CATEGORY.ADMIN,
  [AI_PERMISSION.MANAGE_SEARCH]: AI_PERMISSION_CATEGORY.ADMIN,
  [AI_PERMISSION.MANAGE_RANKING]: AI_PERMISSION_CATEGORY.ADMIN,
  [AI_PERMISSION.VIEW_ANALYTICS]: AI_PERMISSION_CATEGORY.VIEWER,
  [AI_PERMISSION.MANAGE_TRAINING]: AI_PERMISSION_CATEGORY.MANAGER,
  [AI_PERMISSION.MANAGE_FEATURES]: AI_PERMISSION_CATEGORY.ADMIN,
  [AI_PERMISSION.MANAGE_PROMPTS]: AI_PERMISSION_CATEGORY.MANAGER,
  [AI_PERMISSION.MANAGE_EMBEDDINGS]: AI_PERMISSION_CATEGORY.MANAGER,
  [AI_PERMISSION.MANAGE_VECTORS]: AI_PERMISSION_CATEGORY.MANAGER,
  [AI_PERMISSION.VIEW_INSIGHTS]: AI_PERMISSION_CATEGORY.VIEWER,
} as const;

/**
 * AI পারমিশন কনফিগারেশন
 */
export interface AIPermissionConfig {
  permission: AIPermissionType;
  label: string;
  description: string;
  icon: string;
  group: AIPermissionGroupType;
  category: AIPermissionCategoryType;
  isSensitive: boolean;
  requiresApproval: boolean;
}

/**
 * AI পারমিশন মেটাডেটা
 */
export const AI_PERMISSION_METADATA: Record<AIPermissionType, AIPermissionConfig> = {
  [AI_PERMISSION.MANAGE_MODELS]: {
    permission: AI_PERMISSION.MANAGE_MODELS,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.MANAGE_MODELS],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.MANAGE_MODELS],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.MANAGE_MODELS],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.MANAGE_MODELS],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.MANAGE_MODELS],
    isSensitive: true,
    requiresApproval: true,
  },
  [AI_PERMISSION.VIEW_MODELS]: {
    permission: AI_PERMISSION.VIEW_MODELS,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.VIEW_MODELS],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.VIEW_MODELS],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.VIEW_MODELS],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.VIEW_MODELS],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.VIEW_MODELS],
    isSensitive: false,
    requiresApproval: false,
  },
  [AI_PERMISSION.TRAIN_MODELS]: {
    permission: AI_PERMISSION.TRAIN_MODELS,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.TRAIN_MODELS],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.TRAIN_MODELS],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.TRAIN_MODELS],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.TRAIN_MODELS],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.TRAIN_MODELS],
    isSensitive: true,
    requiresApproval: true,
  },
  [AI_PERMISSION.GENERATE_RECOMMENDATIONS]: {
    permission: AI_PERMISSION.GENERATE_RECOMMENDATIONS,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.GENERATE_RECOMMENDATIONS],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.GENERATE_RECOMMENDATIONS],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.GENERATE_RECOMMENDATIONS],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.GENERATE_RECOMMENDATIONS],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.GENERATE_RECOMMENDATIONS],
    isSensitive: false,
    requiresApproval: false,
  },
  [AI_PERMISSION.MANAGE_RECOMMENDATIONS]: {
    permission: AI_PERMISSION.MANAGE_RECOMMENDATIONS,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.MANAGE_RECOMMENDATIONS],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.MANAGE_RECOMMENDATIONS],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.MANAGE_RECOMMENDATIONS],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.MANAGE_RECOMMENDATIONS],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.MANAGE_RECOMMENDATIONS],
    isSensitive: true,
    requiresApproval: true,
  },
  [AI_PERMISSION.MANAGE_PERSONALIZATION]: {
    permission: AI_PERMISSION.MANAGE_PERSONALIZATION,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.MANAGE_PERSONALIZATION],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.MANAGE_PERSONALIZATION],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.MANAGE_PERSONALIZATION],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.MANAGE_PERSONALIZATION],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.MANAGE_PERSONALIZATION],
    isSensitive: true,
    requiresApproval: true,
  },
  [AI_PERMISSION.MANAGE_SEARCH]: {
    permission: AI_PERMISSION.MANAGE_SEARCH,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.MANAGE_SEARCH],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.MANAGE_SEARCH],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.MANAGE_SEARCH],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.MANAGE_SEARCH],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.MANAGE_SEARCH],
    isSensitive: true,
    requiresApproval: true,
  },
  [AI_PERMISSION.MANAGE_RANKING]: {
    permission: AI_PERMISSION.MANAGE_RANKING,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.MANAGE_RANKING],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.MANAGE_RANKING],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.MANAGE_RANKING],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.MANAGE_RANKING],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.MANAGE_RANKING],
    isSensitive: true,
    requiresApproval: true,
  },
  [AI_PERMISSION.VIEW_ANALYTICS]: {
    permission: AI_PERMISSION.VIEW_ANALYTICS,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.VIEW_ANALYTICS],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.VIEW_ANALYTICS],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.VIEW_ANALYTICS],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.VIEW_ANALYTICS],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.VIEW_ANALYTICS],
    isSensitive: false,
    requiresApproval: false,
  },
  [AI_PERMISSION.MANAGE_TRAINING]: {
    permission: AI_PERMISSION.MANAGE_TRAINING,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.MANAGE_TRAINING],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.MANAGE_TRAINING],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.MANAGE_TRAINING],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.MANAGE_TRAINING],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.MANAGE_TRAINING],
    isSensitive: true,
    requiresApproval: true,
  },
  [AI_PERMISSION.MANAGE_FEATURES]: {
    permission: AI_PERMISSION.MANAGE_FEATURES,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.MANAGE_FEATURES],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.MANAGE_FEATURES],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.MANAGE_FEATURES],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.MANAGE_FEATURES],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.MANAGE_FEATURES],
    isSensitive: true,
    requiresApproval: true,
  },
  [AI_PERMISSION.MANAGE_PROMPTS]: {
    permission: AI_PERMISSION.MANAGE_PROMPTS,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.MANAGE_PROMPTS],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.MANAGE_PROMPTS],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.MANAGE_PROMPTS],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.MANAGE_PROMPTS],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.MANAGE_PROMPTS],
    isSensitive: true,
    requiresApproval: true,
  },
  [AI_PERMISSION.MANAGE_EMBEDDINGS]: {
    permission: AI_PERMISSION.MANAGE_EMBEDDINGS,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.MANAGE_EMBEDDINGS],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.MANAGE_EMBEDDINGS],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.MANAGE_EMBEDDINGS],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.MANAGE_EMBEDDINGS],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.MANAGE_EMBEDDINGS],
    isSensitive: true,
    requiresApproval: true,
  },
  [AI_PERMISSION.MANAGE_VECTORS]: {
    permission: AI_PERMISSION.MANAGE_VECTORS,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.MANAGE_VECTORS],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.MANAGE_VECTORS],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.MANAGE_VECTORS],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.MANAGE_VECTORS],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.MANAGE_VECTORS],
    isSensitive: true,
    requiresApproval: true,
  },
  [AI_PERMISSION.VIEW_INSIGHTS]: {
    permission: AI_PERMISSION.VIEW_INSIGHTS,
    label: AI_PERMISSION_LABELS[AI_PERMISSION.VIEW_INSIGHTS],
    description: AI_PERMISSION_DESCRIPTIONS[AI_PERMISSION.VIEW_INSIGHTS],
    icon: AI_PERMISSION_ICONS[AI_PERMISSION.VIEW_INSIGHTS],
    group: AI_PERMISSION_GROUP_MAP[AI_PERMISSION.VIEW_INSIGHTS],
    category: AI_PERMISSION_CATEGORY_MAP[AI_PERMISSION.VIEW_INSIGHTS],
    isSensitive: false,
    requiresApproval: false,
  },
} as const;

/**
 * পারমিশন গ্রুপে পারমিশন তালিকা
 */
export const AI_PERMISSION_GROUP_LIST: Record<AIPermissionGroupType, AIPermissionType[]> = {
  [AI_PERMISSION_GROUP.MODEL]: [
    AI_PERMISSION.MANAGE_MODELS,
    AI_PERMISSION.VIEW_MODELS,
    AI_PERMISSION.TRAIN_MODELS,
  ],
  [AI_PERMISSION_GROUP.RECOMMENDATION]: [
    AI_PERMISSION.GENERATE_RECOMMENDATIONS,
    AI_PERMISSION.MANAGE_RECOMMENDATIONS,
    AI_PERMISSION.MANAGE_PERSONALIZATION,
  ],
  [AI_PERMISSION_GROUP.SEARCH]: [AI_PERMISSION.MANAGE_SEARCH, AI_PERMISSION.MANAGE_RANKING],
  [AI_PERMISSION_GROUP.ANALYTICS]: [AI_PERMISSION.VIEW_ANALYTICS, AI_PERMISSION.VIEW_INSIGHTS],
  [AI_PERMISSION_GROUP.TRAINING]: [AI_PERMISSION.MANAGE_TRAINING],
  [AI_PERMISSION_GROUP.MANAGEMENT]: [
    AI_PERMISSION.MANAGE_FEATURES,
    AI_PERMISSION.MANAGE_PROMPTS,
    AI_PERMISSION.MANAGE_EMBEDDINGS,
    AI_PERMISSION.MANAGE_VECTORS,
  ],
} as const;
