/**
 * AI রেকমেন্ডেশন স্ট্যাটাস এনাম
 */
export const AI_RECOMMENDATION_STATUS = {
  PENDING: 'pending',
  PROCESSING: 'processing',
  GENERATED: 'generated',
  CACHED: 'cached',
  EXPIRED: 'expired',
  FAILED: 'failed',
  DISMISSED: 'dismissed',
  CLICKED: 'clicked',
  CONVERTED: 'converted',
} as const;

/**
 * AI_RECOMMENDATION_STATUS থেকে টাইপ
 */
export type AIRecommendationStatus =
  (typeof AI_RECOMMENDATION_STATUS)[keyof typeof AI_RECOMMENDATION_STATUS];

/**
 * রেকমেন্ডেশন স্ট্যাটাস লেবেল
 */
export const AI_RECOMMENDATION_STATUS_LABELS: Record<AIRecommendationStatus, string> = {
  [AI_RECOMMENDATION_STATUS.PENDING]: 'Pending',
  [AI_RECOMMENDATION_STATUS.PROCESSING]: 'Processing',
  [AI_RECOMMENDATION_STATUS.GENERATED]: 'Generated',
  [AI_RECOMMENDATION_STATUS.CACHED]: 'Cached',
  [AI_RECOMMENDATION_STATUS.EXPIRED]: 'Expired',
  [AI_RECOMMENDATION_STATUS.FAILED]: 'Failed',
  [AI_RECOMMENDATION_STATUS.DISMISSED]: 'Dismissed',
  [AI_RECOMMENDATION_STATUS.CLICKED]: 'Clicked',
  [AI_RECOMMENDATION_STATUS.CONVERTED]: 'Converted',
} as const;

/**
 * রেকমেন্ডেশন স্ট্যাটাস বিবরণ
 */
export const AI_RECOMMENDATION_STATUS_DESCRIPTIONS: Record<AIRecommendationStatus, string> = {
  [AI_RECOMMENDATION_STATUS.PENDING]: 'Recommendation request is waiting to be processed',
  [AI_RECOMMENDATION_STATUS.PROCESSING]: 'Recommendation is currently being generated',
  [AI_RECOMMENDATION_STATUS.GENERATED]: 'Recommendation has been successfully generated',
  [AI_RECOMMENDATION_STATUS.CACHED]: 'Recommendation is cached and ready for quick retrieval',
  [AI_RECOMMENDATION_STATUS.EXPIRED]: 'Recommendation has expired and is no longer valid',
  [AI_RECOMMENDATION_STATUS.FAILED]: 'Recommendation generation has failed',
  [AI_RECOMMENDATION_STATUS.DISMISSED]: 'Recommendation was dismissed by the user',
  [AI_RECOMMENDATION_STATUS.CLICKED]: 'Recommendation was clicked by the user',
  [AI_RECOMMENDATION_STATUS.CONVERTED]: 'Recommendation led to a conversion',
} as const;

/**
 * রেকমেন্ডেশন স্ট্যাটাস আইকন
 */
export const AI_RECOMMENDATION_STATUS_ICONS: Record<AIRecommendationStatus, string> = {
  [AI_RECOMMENDATION_STATUS.PENDING]: '⏳',
  [AI_RECOMMENDATION_STATUS.PROCESSING]: '🔄',
  [AI_RECOMMENDATION_STATUS.GENERATED]: '✅',
  [AI_RECOMMENDATION_STATUS.CACHED]: '💾',
  [AI_RECOMMENDATION_STATUS.EXPIRED]: '⌛',
  [AI_RECOMMENDATION_STATUS.FAILED]: '❌',
  [AI_RECOMMENDATION_STATUS.DISMISSED]: '👎',
  [AI_RECOMMENDATION_STATUS.CLICKED]: '👆',
  [AI_RECOMMENDATION_STATUS.CONVERTED]: '🎯',
} as const;

/**
 * রেকমেন্ডেশন স্ট্যাটাস কালার (হেক্স কোড)
 */
export const AI_RECOMMENDATION_STATUS_COLORS: Record<AIRecommendationStatus, string> = {
  [AI_RECOMMENDATION_STATUS.PENDING]: '#f59e0b', // Amber-500
  [AI_RECOMMENDATION_STATUS.PROCESSING]: '#3b82f6', // Blue-500
  [AI_RECOMMENDATION_STATUS.GENERATED]: '#22c55e', // Green-500
  [AI_RECOMMENDATION_STATUS.CACHED]: '#8b5cf6', // Violet-500
  [AI_RECOMMENDATION_STATUS.EXPIRED]: '#64748b', // Slate-500
  [AI_RECOMMENDATION_STATUS.FAILED]: '#dc2626', // Red-600
  [AI_RECOMMENDATION_STATUS.DISMISSED]: '#94a3b8', // Slate-400
  [AI_RECOMMENDATION_STATUS.CLICKED]: '#06b6d4', // Cyan-500
  [AI_RECOMMENDATION_STATUS.CONVERTED]: '#f472b6', // Pink-500
} as const;

/**
 * রেকমেন্ডেশন স্ট্যাটাস ট্রানজিশন রুলস
 * প্রতিটি স্ট্যাটাস থেকে কোন স্ট্যাটাসে যাওয়া যায় তা নির্ধারণ করে
 */
export const AI_RECOMMENDATION_STATUS_TRANSITIONS: Record<
  AIRecommendationStatus,
  AIRecommendationStatus[]
> = {
  [AI_RECOMMENDATION_STATUS.PENDING]: [
    AI_RECOMMENDATION_STATUS.PROCESSING,
    AI_RECOMMENDATION_STATUS.FAILED,
  ],
  [AI_RECOMMENDATION_STATUS.PROCESSING]: [
    AI_RECOMMENDATION_STATUS.GENERATED,
    AI_RECOMMENDATION_STATUS.FAILED,
  ],
  [AI_RECOMMENDATION_STATUS.GENERATED]: [
    AI_RECOMMENDATION_STATUS.CACHED,
    AI_RECOMMENDATION_STATUS.CLICKED,
    AI_RECOMMENDATION_STATUS.DISMISSED,
    AI_RECOMMENDATION_STATUS.EXPIRED,
  ],
  [AI_RECOMMENDATION_STATUS.CACHED]: [
    AI_RECOMMENDATION_STATUS.CLICKED,
    AI_RECOMMENDATION_STATUS.DISMISSED,
    AI_RECOMMENDATION_STATUS.EXPIRED,
  ],
  [AI_RECOMMENDATION_STATUS.EXPIRED]: [AI_RECOMMENDATION_STATUS.GENERATED],
  [AI_RECOMMENDATION_STATUS.FAILED]: [AI_RECOMMENDATION_STATUS.PENDING],
  [AI_RECOMMENDATION_STATUS.DISMISSED]: [AI_RECOMMENDATION_STATUS.GENERATED],
  [AI_RECOMMENDATION_STATUS.CLICKED]: [
    AI_RECOMMENDATION_STATUS.CONVERTED,
    AI_RECOMMENDATION_STATUS.DISMISSED,
  ],
  [AI_RECOMMENDATION_STATUS.CONVERTED]: [],
} as const;

/**
 * রেকমেন্ডেশন স্ট্যাটাস কনফিগারেশন
 */
export interface AIRecommendationStatusConfig {
  status: AIRecommendationStatus;
  label: string;
  description: string;
  icon: string;
  color: string;
  isTerminal: boolean;
  isError: boolean;
  isSuccess: boolean;
  order: number;
}

/**
 * রেকমেন্ডেশন স্ট্যাটাস মেটাডেটা
 */
export const AI_RECOMMENDATION_STATUS_METADATA: Record<
  AIRecommendationStatus,
  AIRecommendationStatusConfig
> = {
  [AI_RECOMMENDATION_STATUS.PENDING]: {
    status: AI_RECOMMENDATION_STATUS.PENDING,
    label: AI_RECOMMENDATION_STATUS_LABELS[AI_RECOMMENDATION_STATUS.PENDING],
    description: AI_RECOMMENDATION_STATUS_DESCRIPTIONS[AI_RECOMMENDATION_STATUS.PENDING],
    icon: AI_RECOMMENDATION_STATUS_ICONS[AI_RECOMMENDATION_STATUS.PENDING],
    color: AI_RECOMMENDATION_STATUS_COLORS[AI_RECOMMENDATION_STATUS.PENDING],
    isTerminal: false,
    isError: false,
    isSuccess: false,
    order: 0,
  },
  [AI_RECOMMENDATION_STATUS.PROCESSING]: {
    status: AI_RECOMMENDATION_STATUS.PROCESSING,
    label: AI_RECOMMENDATION_STATUS_LABELS[AI_RECOMMENDATION_STATUS.PROCESSING],
    description: AI_RECOMMENDATION_STATUS_DESCRIPTIONS[AI_RECOMMENDATION_STATUS.PROCESSING],
    icon: AI_RECOMMENDATION_STATUS_ICONS[AI_RECOMMENDATION_STATUS.PROCESSING],
    color: AI_RECOMMENDATION_STATUS_COLORS[AI_RECOMMENDATION_STATUS.PROCESSING],
    isTerminal: false,
    isError: false,
    isSuccess: false,
    order: 1,
  },
  [AI_RECOMMENDATION_STATUS.GENERATED]: {
    status: AI_RECOMMENDATION_STATUS.GENERATED,
    label: AI_RECOMMENDATION_STATUS_LABELS[AI_RECOMMENDATION_STATUS.GENERATED],
    description: AI_RECOMMENDATION_STATUS_DESCRIPTIONS[AI_RECOMMENDATION_STATUS.GENERATED],
    icon: AI_RECOMMENDATION_STATUS_ICONS[AI_RECOMMENDATION_STATUS.GENERATED],
    color: AI_RECOMMENDATION_STATUS_COLORS[AI_RECOMMENDATION_STATUS.GENERATED],
    isTerminal: false,
    isError: false,
    isSuccess: true,
    order: 2,
  },
  [AI_RECOMMENDATION_STATUS.CACHED]: {
    status: AI_RECOMMENDATION_STATUS.CACHED,
    label: AI_RECOMMENDATION_STATUS_LABELS[AI_RECOMMENDATION_STATUS.CACHED],
    description: AI_RECOMMENDATION_STATUS_DESCRIPTIONS[AI_RECOMMENDATION_STATUS.CACHED],
    icon: AI_RECOMMENDATION_STATUS_ICONS[AI_RECOMMENDATION_STATUS.CACHED],
    color: AI_RECOMMENDATION_STATUS_COLORS[AI_RECOMMENDATION_STATUS.CACHED],
    isTerminal: false,
    isError: false,
    isSuccess: true,
    order: 3,
  },
  [AI_RECOMMENDATION_STATUS.EXPIRED]: {
    status: AI_RECOMMENDATION_STATUS.EXPIRED,
    label: AI_RECOMMENDATION_STATUS_LABELS[AI_RECOMMENDATION_STATUS.EXPIRED],
    description: AI_RECOMMENDATION_STATUS_DESCRIPTIONS[AI_RECOMMENDATION_STATUS.EXPIRED],
    icon: AI_RECOMMENDATION_STATUS_ICONS[AI_RECOMMENDATION_STATUS.EXPIRED],
    color: AI_RECOMMENDATION_STATUS_COLORS[AI_RECOMMENDATION_STATUS.EXPIRED],
    isTerminal: true,
    isError: false,
    isSuccess: false,
    order: 4,
  },
  [AI_RECOMMENDATION_STATUS.FAILED]: {
    status: AI_RECOMMENDATION_STATUS.FAILED,
    label: AI_RECOMMENDATION_STATUS_LABELS[AI_RECOMMENDATION_STATUS.FAILED],
    description: AI_RECOMMENDATION_STATUS_DESCRIPTIONS[AI_RECOMMENDATION_STATUS.FAILED],
    icon: AI_RECOMMENDATION_STATUS_ICONS[AI_RECOMMENDATION_STATUS.FAILED],
    color: AI_RECOMMENDATION_STATUS_COLORS[AI_RECOMMENDATION_STATUS.FAILED],
    isTerminal: true,
    isError: true,
    isSuccess: false,
    order: 5,
  },
  [AI_RECOMMENDATION_STATUS.DISMISSED]: {
    status: AI_RECOMMENDATION_STATUS.DISMISSED,
    label: AI_RECOMMENDATION_STATUS_LABELS[AI_RECOMMENDATION_STATUS.DISMISSED],
    description: AI_RECOMMENDATION_STATUS_DESCRIPTIONS[AI_RECOMMENDATION_STATUS.DISMISSED],
    icon: AI_RECOMMENDATION_STATUS_ICONS[AI_RECOMMENDATION_STATUS.DISMISSED],
    color: AI_RECOMMENDATION_STATUS_COLORS[AI_RECOMMENDATION_STATUS.DISMISSED],
    isTerminal: true,
    isError: false,
    isSuccess: false,
    order: 6,
  },
  [AI_RECOMMENDATION_STATUS.CLICKED]: {
    status: AI_RECOMMENDATION_STATUS.CLICKED,
    label: AI_RECOMMENDATION_STATUS_LABELS[AI_RECOMMENDATION_STATUS.CLICKED],
    description: AI_RECOMMENDATION_STATUS_DESCRIPTIONS[AI_RECOMMENDATION_STATUS.CLICKED],
    icon: AI_RECOMMENDATION_STATUS_ICONS[AI_RECOMMENDATION_STATUS.CLICKED],
    color: AI_RECOMMENDATION_STATUS_COLORS[AI_RECOMMENDATION_STATUS.CLICKED],
    isTerminal: false,
    isError: false,
    isSuccess: true,
    order: 7,
  },
  [AI_RECOMMENDATION_STATUS.CONVERTED]: {
    status: AI_RECOMMENDATION_STATUS.CONVERTED,
    label: AI_RECOMMENDATION_STATUS_LABELS[AI_RECOMMENDATION_STATUS.CONVERTED],
    description: AI_RECOMMENDATION_STATUS_DESCRIPTIONS[AI_RECOMMENDATION_STATUS.CONVERTED],
    icon: AI_RECOMMENDATION_STATUS_ICONS[AI_RECOMMENDATION_STATUS.CONVERTED],
    color: AI_RECOMMENDATION_STATUS_COLORS[AI_RECOMMENDATION_STATUS.CONVERTED],
    isTerminal: true,
    isError: false,
    isSuccess: true,
    order: 8,
  },
} as const;

/**
 * টার্মিনাল স্ট্যাটাসের তালিকা
 */
export const AI_RECOMMENDATION_TERMINAL_STATUSES = [
  AI_RECOMMENDATION_STATUS.EXPIRED,
  AI_RECOMMENDATION_STATUS.FAILED,
  AI_RECOMMENDATION_STATUS.DISMISSED,
  AI_RECOMMENDATION_STATUS.CONVERTED,
] as const;

/**
 * সাফল্যের স্ট্যাটাসের তালিকা
 */
export const AI_RECOMMENDATION_SUCCESS_STATUSES = [
  AI_RECOMMENDATION_STATUS.GENERATED,
  AI_RECOMMENDATION_STATUS.CACHED,
  AI_RECOMMENDATION_STATUS.CLICKED,
  AI_RECOMMENDATION_STATUS.CONVERTED,
] as const;

/**
 * ত্রুটির স্ট্যাটাসের তালিকা
 */
export const AI_RECOMMENDATION_ERROR_STATUSES = [AI_RECOMMENDATION_STATUS.FAILED] as const;

/**
 * অ্যাক্টিভ স্ট্যাটাসের তালিকা (যে স্ট্যাটাসগুলোতে রেকমেন্ডেশন এখনও লাইভ)
 */
export const AI_RECOMMENDATION_ACTIVE_STATUSES = [
  AI_RECOMMENDATION_STATUS.PENDING,
  AI_RECOMMENDATION_STATUS.PROCESSING,
  AI_RECOMMENDATION_STATUS.GENERATED,
  AI_RECOMMENDATION_STATUS.CACHED,
] as const;
