/**
 * Webhook Status Constants
 * Status definitions for webhook notifications
 */

export const NOTIFICATIONWEBHOOK_STATUS = {
  // Webhook Statuses
  STATUSES: {
    PENDING: 'pending',
    QUEUED: 'queued',
    PROCESSING: 'processing',
    SENT: 'sent',
    DELIVERED: 'delivered',
    FAILED: 'failed',
    RETRY: 'retry',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    EXPIRED: 'expired',
    DRAFT: 'draft',
    APPROVED: 'approved',
    REJECTED: 'rejected',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    DRAFT: '#6B7280',
    PENDING: '#F59E0B',
    QUEUED: '#8B5CF6',
    PROCESSING: '#3B82F6',
    SENT: '#3B82F6',
    DELIVERED: '#10B981',
    FAILED: '#EF4444',
    RETRY: '#F59E0B',
    CANCELLED: '#6B7280',
    ARCHIVED: '#6B7280',
    EXPIRED: '#6B7280',
    APPROVED: '#10B981',
    REJECTED: '#EF4444',
  } as const,

  // Status Categories
  CATEGORIES: {
    DRAFT: 'draft',
    PENDING: 'pending',
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
  } as const,

  // Status Priority Order
  ORDER: {
    DRAFT: 0,
    PENDING: 1,
    APPROVED: 2,
    REJECTED: 3,
    QUEUED: 4,
    PROCESSING: 5,
    SENT: 6,
    DELIVERED: 7,
    RETRY: 8,
    FAILED: 9,
    EXPIRED: 10,
    CANCELLED: 11,
    ARCHIVED: 12,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    DRAFT_TO_PENDING: 'draft_to_pending',
    DRAFT_TO_CANCELLED: 'draft_to_cancelled',
    DRAFT_TO_ARCHIVED: 'draft_to_archived',
    PENDING_TO_APPROVED: 'pending_to_approved',
    PENDING_TO_REJECTED: 'pending_to_rejected',
    PENDING_TO_CANCELLED: 'pending_to_cancelled',
    APPROVED_TO_QUEUED: 'approved_to_queued',
    APPROVED_TO_CANCELLED: 'approved_to_cancelled',
    REJECTED_TO_DRAFT: 'rejected_to_draft',
    REJECTED_TO_ARCHIVED: 'rejected_to_archived',
    QUEUED_TO_PROCESSING: 'queued_to_processing',
    QUEUED_TO_CANCELLED: 'queued_to_cancelled',
    PROCESSING_TO_SENT: 'processing_to_sent',
    PROCESSING_TO_FAILED: 'processing_to_failed',
    PROCESSING_TO_CANCELLED: 'processing_to_cancelled',
    SENT_TO_DELIVERED: 'sent_to_delivered',
    SENT_TO_FAILED: 'sent_to_failed',
    SENT_TO_RETRY: 'sent_to_retry',
    DELIVERED_TO_ARCHIVED: 'delivered_to_archived',
    RETRY_TO_QUEUED: 'retry_to_queued',
    RETRY_TO_FAILED: 'retry_to_failed',
    RETRY_TO_CANCELLED: 'retry_to_cancelled',
    FAILED_TO_ARCHIVED: 'failed_to_archived',
    EXPIRED_TO_ARCHIVED: 'expired_to_archived',
    CANCELLED_TO_ARCHIVED: 'cancelled_to_archived',
  } as const,
} as const;

// Webhook Statuses
export type NotificationWebhookStatusType =
  (typeof NOTIFICATIONWEBHOOK_STATUS.STATUSES)[keyof typeof NOTIFICATIONWEBHOOK_STATUS.STATUSES];

// Status Colors
export type NotificationWebhookStatusColor =
  (typeof NOTIFICATIONWEBHOOK_STATUS.COLORS)[keyof typeof NOTIFICATIONWEBHOOK_STATUS.COLORS];

// Status Categories
export type NotificationWebhookStatusCategory =
  (typeof NOTIFICATIONWEBHOOK_STATUS.CATEGORIES)[keyof typeof NOTIFICATIONWEBHOOK_STATUS.CATEGORIES];

// Status Priority Order
export type NotificationWebhookStatusOrder =
  (typeof NOTIFICATIONWEBHOOK_STATUS.ORDER)[keyof typeof NOTIFICATIONWEBHOOK_STATUS.ORDER];

// Status Transitions
export type NotificationWebhookStatusTransition =
  (typeof NOTIFICATIONWEBHOOK_STATUS.TRANSITIONS)[keyof typeof NOTIFICATIONWEBHOOK_STATUS.TRANSITIONS];

// Utility Functions
export function notificationwebhookGetStatusLabel(status: NotificationWebhookStatusType): string {
  const labels: Record<NotificationWebhookStatusType, string> = {
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.DRAFT]: 'Draft',
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.PENDING]: 'Pending',
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.QUEUED]: 'Queued',
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.PROCESSING]: 'Processing',
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.SENT]: 'Sent',
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.DELIVERED]: 'Delivered',
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.FAILED]: 'Failed',
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.RETRY]: 'Retry',
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.CANCELLED]: 'Cancelled',
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.ARCHIVED]: 'Archived',
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.EXPIRED]: 'Expired',
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.APPROVED]: 'Approved',
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.REJECTED]: 'Rejected',
  };
  return labels[status] || 'Unknown Status';
}

export function notificationwebhookGetStatusColor(
  status: NotificationWebhookStatusType
): NotificationWebhookStatusColor {
  const colors: Record<NotificationWebhookStatusType, NotificationWebhookStatusColor> = {
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.DRAFT]: NOTIFICATIONWEBHOOK_STATUS.COLORS.DRAFT,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.PENDING]: NOTIFICATIONWEBHOOK_STATUS.COLORS.PENDING,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.QUEUED]: NOTIFICATIONWEBHOOK_STATUS.COLORS.QUEUED,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.PROCESSING]: NOTIFICATIONWEBHOOK_STATUS.COLORS.PROCESSING,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.SENT]: NOTIFICATIONWEBHOOK_STATUS.COLORS.SENT,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.DELIVERED]: NOTIFICATIONWEBHOOK_STATUS.COLORS.DELIVERED,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.FAILED]: NOTIFICATIONWEBHOOK_STATUS.COLORS.FAILED,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.RETRY]: NOTIFICATIONWEBHOOK_STATUS.COLORS.RETRY,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.CANCELLED]: NOTIFICATIONWEBHOOK_STATUS.COLORS.CANCELLED,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.ARCHIVED]: NOTIFICATIONWEBHOOK_STATUS.COLORS.ARCHIVED,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.EXPIRED]: NOTIFICATIONWEBHOOK_STATUS.COLORS.EXPIRED,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.APPROVED]: NOTIFICATIONWEBHOOK_STATUS.COLORS.APPROVED,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.REJECTED]: NOTIFICATIONWEBHOOK_STATUS.COLORS.REJECTED,
  };
  return colors[status] || NOTIFICATIONWEBHOOK_STATUS.COLORS.PENDING;
}

export function notificationwebhookGetStatusCategory(
  status: NotificationWebhookStatusType
): NotificationWebhookStatusCategory {
  const categories: Record<NotificationWebhookStatusType, NotificationWebhookStatusCategory> = {
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.DRAFT]: NOTIFICATIONWEBHOOK_STATUS.CATEGORIES.DRAFT,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.PENDING]: NOTIFICATIONWEBHOOK_STATUS.CATEGORIES.PENDING,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.APPROVED]: NOTIFICATIONWEBHOOK_STATUS.CATEGORIES.PENDING,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.REJECTED]: NOTIFICATIONWEBHOOK_STATUS.CATEGORIES.FAILED,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.QUEUED]: NOTIFICATIONWEBHOOK_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.PROCESSING]:
      NOTIFICATIONWEBHOOK_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.SENT]: NOTIFICATIONWEBHOOK_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.RETRY]: NOTIFICATIONWEBHOOK_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.DELIVERED]:
      NOTIFICATIONWEBHOOK_STATUS.CATEGORIES.COMPLETED,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.FAILED]: NOTIFICATIONWEBHOOK_STATUS.CATEGORIES.FAILED,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.EXPIRED]: NOTIFICATIONWEBHOOK_STATUS.CATEGORIES.FAILED,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.CANCELLED]:
      NOTIFICATIONWEBHOOK_STATUS.CATEGORIES.CANCELLED,
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.ARCHIVED]: NOTIFICATIONWEBHOOK_STATUS.CATEGORIES.ARCHIVED,
  };
  return categories[status] || NOTIFICATIONWEBHOOK_STATUS.CATEGORIES.PENDING;
}

export function notificationwebhookIsDelivered(status: NotificationWebhookStatusType): boolean {
  return status === NOTIFICATIONWEBHOOK_STATUS.STATUSES.DELIVERED;
}

export function notificationwebhookIsSent(status: NotificationWebhookStatusType): boolean {
  const sentStatuses: NotificationWebhookStatusType[] = [
    NOTIFICATIONWEBHOOK_STATUS.STATUSES.SENT,
    NOTIFICATIONWEBHOOK_STATUS.STATUSES.DELIVERED,
  ];
  return sentStatuses.includes(status);
}

export function notificationwebhookIsFailed(status: NotificationWebhookStatusType): boolean {
  const failedStatuses: NotificationWebhookStatusType[] = [
    NOTIFICATIONWEBHOOK_STATUS.STATUSES.FAILED,
    NOTIFICATIONWEBHOOK_STATUS.STATUSES.REJECTED,
    NOTIFICATIONWEBHOOK_STATUS.STATUSES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}

export function notificationwebhookIsPending(status: NotificationWebhookStatusType): boolean {
  const pendingStatuses: NotificationWebhookStatusType[] = [
    NOTIFICATIONWEBHOOK_STATUS.STATUSES.PENDING,
    NOTIFICATIONWEBHOOK_STATUS.STATUSES.QUEUED,
    NOTIFICATIONWEBHOOK_STATUS.STATUSES.PROCESSING,
    NOTIFICATIONWEBHOOK_STATUS.STATUSES.SENT,
    NOTIFICATIONWEBHOOK_STATUS.STATUSES.RETRY,
    NOTIFICATIONWEBHOOK_STATUS.STATUSES.APPROVED,
  ];
  return pendingStatuses.includes(status);
}

export function notificationwebhookCanTransition(
  currentStatus: NotificationWebhookStatusType,
  targetStatus: NotificationWebhookStatusType
): boolean {
  const validTransitions: Record<NotificationWebhookStatusType, NotificationWebhookStatusType[]> = {
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.DRAFT]: [
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.PENDING,
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.CANCELLED,
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.ARCHIVED,
    ],
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.PENDING]: [
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.APPROVED,
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.REJECTED,
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.APPROVED]: [
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.QUEUED,
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.REJECTED]: [
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.DRAFT,
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.ARCHIVED,
    ],
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.QUEUED]: [
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.PROCESSING,
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.PROCESSING]: [
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.SENT,
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.FAILED,
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.SENT]: [
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.DELIVERED,
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.FAILED,
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.RETRY,
    ],
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.DELIVERED]: [NOTIFICATIONWEBHOOK_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.RETRY]: [
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.QUEUED,
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.FAILED,
      NOTIFICATIONWEBHOOK_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.FAILED]: [NOTIFICATIONWEBHOOK_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.EXPIRED]: [NOTIFICATIONWEBHOOK_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.CANCELLED]: [NOTIFICATIONWEBHOOK_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONWEBHOOK_STATUS.STATUSES.ARCHIVED]: [],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
