/**
 * Notification Broadcast Status Constants
 * Status definitions for notification broadcasts
 */

export const NOTIFICATIONBROADCAST_STATUS = {
  // Broadcast Statuses
  STATUSES: {
    DRAFT: 'draft',
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected',
    SCHEDULED: 'scheduled',
    PROCESSING: 'processing',
    SENDING: 'sending',
    COMPLETED: 'completed',
    PAUSED: 'paused',
    CANCELLED: 'cancelled',
    FAILED: 'failed',
    ARCHIVED: 'archived',
    ON_HOLD: 'on_hold',
    PARTIAL: 'partial',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    DRAFT: '#6B7280',
    PENDING: '#F59E0B',
    APPROVED: '#10B981',
    REJECTED: '#EF4444',
    SCHEDULED: '#3B82F6',
    PROCESSING: '#3B82F6',
    SENDING: '#3B82F6',
    COMPLETED: '#10B981',
    PAUSED: '#F59E0B',
    CANCELLED: '#6B7280',
    FAILED: '#EF4444',
    ARCHIVED: '#6B7280',
    ON_HOLD: '#F59E0B',
    PARTIAL: '#F59E0B',
  } as const,

  // Status Categories
  CATEGORIES: {
    DRAFT: 'draft',
    PENDING: 'pending',
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    PAUSED: 'paused',
  } as const,

  // Status Priority Order
  ORDER: {
    DRAFT: 0,
    PENDING: 1,
    APPROVED: 2,
    REJECTED: 3,
    SCHEDULED: 4,
    PROCESSING: 5,
    SENDING: 6,
    PAUSED: 7,
    ON_HOLD: 8,
    PARTIAL: 9,
    COMPLETED: 10,
    FAILED: 11,
    CANCELLED: 12,
    ARCHIVED: 13,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    DRAFT_TO_PENDING: 'draft_to_pending',
    DRAFT_TO_ARCHIVED: 'draft_to_archived',
    DRAFT_TO_CANCELLED: 'draft_to_cancelled',
    PENDING_TO_APPROVED: 'pending_to_approved',
    PENDING_TO_REJECTED: 'pending_to_rejected',
    PENDING_TO_CANCELLED: 'pending_to_cancelled',
    APPROVED_TO_SCHEDULED: 'approved_to_scheduled',
    APPROVED_TO_PROCESSING: 'approved_to_processing',
    APPROVED_TO_CANCELLED: 'approved_to_cancelled',
    REJECTED_TO_DRAFT: 'rejected_to_draft',
    REJECTED_TO_ARCHIVED: 'rejected_to_archived',
    SCHEDULED_TO_PROCESSING: 'scheduled_to_processing',
    SCHEDULED_TO_CANCELLED: 'scheduled_to_cancelled',
    PROCESSING_TO_SENDING: 'processing_to_sending',
    PROCESSING_TO_PAUSED: 'processing_to_paused',
    PROCESSING_TO_FAILED: 'processing_to_failed',
    PROCESSING_TO_CANCELLED: 'processing_to_cancelled',
    SENDING_TO_COMPLETED: 'sending_to_completed',
    SENDING_TO_PARTIAL: 'sending_to_partial',
    SENDING_TO_PAUSED: 'sending_to_paused',
    SENDING_TO_FAILED: 'sending_to_failed',
    SENDING_TO_CANCELLED: 'sending_to_cancelled',
    PAUSED_TO_PROCESSING: 'paused_to_processing',
    PAUSED_TO_SENDING: 'paused_to_sending',
    PAUSED_TO_CANCELLED: 'paused_to_cancelled',
    PAUSED_TO_ON_HOLD: 'paused_to_on_hold',
    ON_HOLD_TO_PROCESSING: 'on_hold_to_processing',
    ON_HOLD_TO_SENDING: 'on_hold_to_sending',
    ON_HOLD_TO_CANCELLED: 'on_hold_to_cancelled',
    PARTIAL_TO_SENDING: 'partial_to_sending',
    PARTIAL_TO_COMPLETED: 'partial_to_completed',
    PARTIAL_TO_CANCELLED: 'partial_to_cancelled',
    COMPLETED_TO_ARCHIVED: 'completed_to_archived',
    FAILED_TO_DRAFT: 'failed_to_draft',
    FAILED_TO_ARCHIVED: 'failed_to_archived',
    CANCELLED_TO_ARCHIVED: 'cancelled_to_archived',
  } as const,
} as const;

// Broadcast Statuses
export type NotificationBroadcastStatusType =
  (typeof NOTIFICATIONBROADCAST_STATUS.STATUSES)[keyof typeof NOTIFICATIONBROADCAST_STATUS.STATUSES];

// Status Colors
export type NotificationBroadcastStatusColor =
  (typeof NOTIFICATIONBROADCAST_STATUS.COLORS)[keyof typeof NOTIFICATIONBROADCAST_STATUS.COLORS];

// Status Categories
export type NotificationBroadcastStatusCategory =
  (typeof NOTIFICATIONBROADCAST_STATUS.CATEGORIES)[keyof typeof NOTIFICATIONBROADCAST_STATUS.CATEGORIES];

// Status Priority Order
export type NotificationBroadcastStatusOrder =
  (typeof NOTIFICATIONBROADCAST_STATUS.ORDER)[keyof typeof NOTIFICATIONBROADCAST_STATUS.ORDER];

// Status Transitions
export type NotificationBroadcastStatusTransition =
  (typeof NOTIFICATIONBROADCAST_STATUS.TRANSITIONS)[keyof typeof NOTIFICATIONBROADCAST_STATUS.TRANSITIONS];

// Utility Functions
export function notificationbroadcastGetStatusLabel(
  status: NotificationBroadcastStatusType
): string {
  const labels: Record<NotificationBroadcastStatusType, string> = {
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.DRAFT]: 'Draft',
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PENDING]: 'Pending',
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.APPROVED]: 'Approved',
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.REJECTED]: 'Rejected',
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.SCHEDULED]: 'Scheduled',
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PROCESSING]: 'Processing',
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.SENDING]: 'Sending',
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.COMPLETED]: 'Completed',
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PAUSED]: 'Paused',
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.CANCELLED]: 'Cancelled',
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.FAILED]: 'Failed',
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.ARCHIVED]: 'Archived',
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.ON_HOLD]: 'On Hold',
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PARTIAL]: 'Partial',
  };
  return labels[status] || 'Unknown Status';
}

export function notificationbroadcastGetStatusColor(
  status: NotificationBroadcastStatusType
): NotificationBroadcastStatusColor {
  const colors: Record<NotificationBroadcastStatusType, NotificationBroadcastStatusColor> = {
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.DRAFT]: NOTIFICATIONBROADCAST_STATUS.COLORS.DRAFT,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PENDING]: NOTIFICATIONBROADCAST_STATUS.COLORS.PENDING,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.APPROVED]: NOTIFICATIONBROADCAST_STATUS.COLORS.APPROVED,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.REJECTED]: NOTIFICATIONBROADCAST_STATUS.COLORS.REJECTED,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.SCHEDULED]:
      NOTIFICATIONBROADCAST_STATUS.COLORS.SCHEDULED,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PROCESSING]:
      NOTIFICATIONBROADCAST_STATUS.COLORS.PROCESSING,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.SENDING]: NOTIFICATIONBROADCAST_STATUS.COLORS.SENDING,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.COMPLETED]:
      NOTIFICATIONBROADCAST_STATUS.COLORS.COMPLETED,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PAUSED]: NOTIFICATIONBROADCAST_STATUS.COLORS.PAUSED,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.CANCELLED]:
      NOTIFICATIONBROADCAST_STATUS.COLORS.CANCELLED,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.FAILED]: NOTIFICATIONBROADCAST_STATUS.COLORS.FAILED,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.ARCHIVED]: NOTIFICATIONBROADCAST_STATUS.COLORS.ARCHIVED,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.ON_HOLD]: NOTIFICATIONBROADCAST_STATUS.COLORS.ON_HOLD,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PARTIAL]: NOTIFICATIONBROADCAST_STATUS.COLORS.PARTIAL,
  };
  return colors[status] || NOTIFICATIONBROADCAST_STATUS.COLORS.PENDING;
}

export function notificationbroadcastGetStatusCategory(
  status: NotificationBroadcastStatusType
): NotificationBroadcastStatusCategory {
  const categories: Record<NotificationBroadcastStatusType, NotificationBroadcastStatusCategory> = {
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.DRAFT]: NOTIFICATIONBROADCAST_STATUS.CATEGORIES.DRAFT,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PENDING]:
      NOTIFICATIONBROADCAST_STATUS.CATEGORIES.PENDING,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.APPROVED]:
      NOTIFICATIONBROADCAST_STATUS.CATEGORIES.PENDING,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.REJECTED]:
      NOTIFICATIONBROADCAST_STATUS.CATEGORIES.FAILED,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.SCHEDULED]:
      NOTIFICATIONBROADCAST_STATUS.CATEGORIES.PENDING,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PROCESSING]:
      NOTIFICATIONBROADCAST_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.SENDING]:
      NOTIFICATIONBROADCAST_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PAUSED]: NOTIFICATIONBROADCAST_STATUS.CATEGORIES.PAUSED,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.ON_HOLD]: NOTIFICATIONBROADCAST_STATUS.CATEGORIES.PAUSED,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PARTIAL]:
      NOTIFICATIONBROADCAST_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.COMPLETED]:
      NOTIFICATIONBROADCAST_STATUS.CATEGORIES.COMPLETED,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.FAILED]: NOTIFICATIONBROADCAST_STATUS.CATEGORIES.FAILED,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.CANCELLED]:
      NOTIFICATIONBROADCAST_STATUS.CATEGORIES.CANCELLED,
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.ARCHIVED]:
      NOTIFICATIONBROADCAST_STATUS.CATEGORIES.ARCHIVED,
  };
  return categories[status] || NOTIFICATIONBROADCAST_STATUS.CATEGORIES.PENDING;
}

export function notificationbroadcastIsActive(status: NotificationBroadcastStatusType): boolean {
  const activeStatuses: NotificationBroadcastStatusType[] = [
    NOTIFICATIONBROADCAST_STATUS.STATUSES.PROCESSING,
    NOTIFICATIONBROADCAST_STATUS.STATUSES.SENDING,
    NOTIFICATIONBROADCAST_STATUS.STATUSES.PARTIAL,
  ];
  return activeStatuses.includes(status);
}

export function notificationbroadcastIsCompleted(status: NotificationBroadcastStatusType): boolean {
  const completedStatuses: NotificationBroadcastStatusType[] = [
    NOTIFICATIONBROADCAST_STATUS.STATUSES.COMPLETED,
    NOTIFICATIONBROADCAST_STATUS.STATUSES.ARCHIVED,
    NOTIFICATIONBROADCAST_STATUS.STATUSES.CANCELLED,
  ];
  return completedStatuses.includes(status);
}

export function notificationbroadcastIsFailed(status: NotificationBroadcastStatusType): boolean {
  const failedStatuses: NotificationBroadcastStatusType[] = [
    NOTIFICATIONBROADCAST_STATUS.STATUSES.FAILED,
    NOTIFICATIONBROADCAST_STATUS.STATUSES.REJECTED,
  ];
  return failedStatuses.includes(status);
}

export function notificationbroadcastIsEditable(status: NotificationBroadcastStatusType): boolean {
  const editableStatuses: NotificationBroadcastStatusType[] = [
    NOTIFICATIONBROADCAST_STATUS.STATUSES.DRAFT,
    NOTIFICATIONBROADCAST_STATUS.STATUSES.PENDING,
    NOTIFICATIONBROADCAST_STATUS.STATUSES.REJECTED,
    NOTIFICATIONBROADCAST_STATUS.STATUSES.PAUSED,
    NOTIFICATIONBROADCAST_STATUS.STATUSES.ON_HOLD,
  ];
  return editableStatuses.includes(status);
}

export function notificationbroadcastCanTransition(
  currentStatus: NotificationBroadcastStatusType,
  targetStatus: NotificationBroadcastStatusType
): boolean {
  const validTransitions: Record<
    NotificationBroadcastStatusType,
    NotificationBroadcastStatusType[]
  > = {
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.DRAFT]: [
      NOTIFICATIONBROADCAST_STATUS.STATUSES.PENDING,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.ARCHIVED,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PENDING]: [
      NOTIFICATIONBROADCAST_STATUS.STATUSES.APPROVED,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.REJECTED,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.APPROVED]: [
      NOTIFICATIONBROADCAST_STATUS.STATUSES.SCHEDULED,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.PROCESSING,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.REJECTED]: [
      NOTIFICATIONBROADCAST_STATUS.STATUSES.DRAFT,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.ARCHIVED,
    ],
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.SCHEDULED]: [
      NOTIFICATIONBROADCAST_STATUS.STATUSES.PROCESSING,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PROCESSING]: [
      NOTIFICATIONBROADCAST_STATUS.STATUSES.SENDING,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.PAUSED,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.FAILED,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.SENDING]: [
      NOTIFICATIONBROADCAST_STATUS.STATUSES.COMPLETED,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.PARTIAL,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.PAUSED,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.FAILED,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PAUSED]: [
      NOTIFICATIONBROADCAST_STATUS.STATUSES.PROCESSING,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.SENDING,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.ON_HOLD,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.ON_HOLD]: [
      NOTIFICATIONBROADCAST_STATUS.STATUSES.PROCESSING,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.SENDING,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.PARTIAL]: [
      NOTIFICATIONBROADCAST_STATUS.STATUSES.SENDING,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.COMPLETED,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.COMPLETED]: [
      NOTIFICATIONBROADCAST_STATUS.STATUSES.ARCHIVED,
    ],
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.FAILED]: [
      NOTIFICATIONBROADCAST_STATUS.STATUSES.DRAFT,
      NOTIFICATIONBROADCAST_STATUS.STATUSES.ARCHIVED,
    ],
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.CANCELLED]: [
      NOTIFICATIONBROADCAST_STATUS.STATUSES.ARCHIVED,
    ],
    [NOTIFICATIONBROADCAST_STATUS.STATUSES.ARCHIVED]: [],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
