/**
 * Vehicle Type Constants
 * Types of vehicles
 */

import { LOGISTICS_VEHICLE } from './vehicle.constants';
import type { LogisticsVehicleType } from './vehicle.constants';

// License Requirements (as mutable arrays - without as const)
const LICENSE_TYPES = {
  BIKE: ['motorcycle'],
  CAR: ['light_vehicle'],
  VAN: ['light_vehicle'],
  TRUCK: ['heavy_vehicle'],
  PICKUP: ['light_vehicle'],
  BUS: ['heavy_vehicle', 'passenger'],
  TEMPO: ['light_vehicle'],
  CNG: ['light_vehicle'],
  SHIP: ['marine'],
  PLANE: ['aviation'],
};

export const LOGISTICS_VEHICLE_TYPE = {
  // Type Categories
  CATEGORIES: {
    TWO_WHEELER: 'two_wheeler',
    FOUR_WHEELER: 'four_wheeler',
    HEAVY: 'heavy',
    WATER: 'water',
    AIR: 'air',
  } as const,

  // Type Icons (for UI)
  ICONS: {
    BIKE: '🏍️',
    CAR: '🚗',
    VAN: '🚐',
    TRUCK: '🚛',
    PICKUP: '🛻',
    BUS: '🚌',
    TEMPO: '🚜',
    CNG: '🚕',
    SHIP: '🚢',
    PLANE: '✈️',
  } as const,

  // Type Colors (for UI)
  COLORS: {
    BIKE: '#orange-500',
    CAR: '#blue-500',
    VAN: '#purple-500',
    TRUCK: '#red-500',
    PICKUP: '#green-500',
    BUS: '#yellow-500',
    TEMPO: '#teal-500',
    CNG: '#cyan-500',
    SHIP: '#indigo-500',
    PLANE: '#gray-500',
  } as const,

  // License Requirements
  LICENSE_TYPES: LICENSE_TYPES,

  // Bangladesh Road Permit Types
  PERMIT_TYPES: {
    BIKE: 'none',
    CAR: 'private',
    VAN: 'commercial',
    TRUCK: 'commercial',
    PICKUP: 'commercial',
    BUS: 'commercial',
    TEMPO: 'commercial',
    CNG: 'commercial',
    SHIP: 'marine',
    PLANE: 'aviation',
  } as const,
} as const;

// Type Categories
export type LogisticsVehicleTypeCategory =
  (typeof LOGISTICS_VEHICLE_TYPE.CATEGORIES)[keyof typeof LOGISTICS_VEHICLE_TYPE.CATEGORIES];

// Type Icons
export type LogisticsVehicleTypeIcon =
  (typeof LOGISTICS_VEHICLE_TYPE.ICONS)[keyof typeof LOGISTICS_VEHICLE_TYPE.ICONS];

// Type Colors
export type LogisticsVehicleTypeColor =
  (typeof LOGISTICS_VEHICLE_TYPE.COLORS)[keyof typeof LOGISTICS_VEHICLE_TYPE.COLORS];

// Utility Functions
export function logisticsVehicleTypeGetCategory(
  type: LogisticsVehicleType
): LogisticsVehicleTypeCategory {
  const categories: Record<LogisticsVehicleType, LogisticsVehicleTypeCategory> = {
    [LOGISTICS_VEHICLE.TYPES.BIKE]: LOGISTICS_VEHICLE_TYPE.CATEGORIES.TWO_WHEELER,
    [LOGISTICS_VEHICLE.TYPES.CAR]: LOGISTICS_VEHICLE_TYPE.CATEGORIES.FOUR_WHEELER,
    [LOGISTICS_VEHICLE.TYPES.VAN]: LOGISTICS_VEHICLE_TYPE.CATEGORIES.FOUR_WHEELER,
    [LOGISTICS_VEHICLE.TYPES.TRUCK]: LOGISTICS_VEHICLE_TYPE.CATEGORIES.HEAVY,
    [LOGISTICS_VEHICLE.TYPES.PICKUP]: LOGISTICS_VEHICLE_TYPE.CATEGORIES.FOUR_WHEELER,
    [LOGISTICS_VEHICLE.TYPES.BUS]: LOGISTICS_VEHICLE_TYPE.CATEGORIES.HEAVY,
    [LOGISTICS_VEHICLE.TYPES.TEMPO]: LOGISTICS_VEHICLE_TYPE.CATEGORIES.FOUR_WHEELER,
    [LOGISTICS_VEHICLE.TYPES.CNG]: LOGISTICS_VEHICLE_TYPE.CATEGORIES.FOUR_WHEELER,
    [LOGISTICS_VEHICLE.TYPES.SHIP]: LOGISTICS_VEHICLE_TYPE.CATEGORIES.WATER,
    [LOGISTICS_VEHICLE.TYPES.PLANE]: LOGISTICS_VEHICLE_TYPE.CATEGORIES.AIR,
  };
  return categories[type] || LOGISTICS_VEHICLE_TYPE.CATEGORIES.FOUR_WHEELER;
}

export function logisticsVehicleTypeGetIcon(type: LogisticsVehicleType): LogisticsVehicleTypeIcon {
  const icons: Record<LogisticsVehicleType, LogisticsVehicleTypeIcon> = {
    [LOGISTICS_VEHICLE.TYPES.BIKE]: LOGISTICS_VEHICLE_TYPE.ICONS.BIKE,
    [LOGISTICS_VEHICLE.TYPES.CAR]: LOGISTICS_VEHICLE_TYPE.ICONS.CAR,
    [LOGISTICS_VEHICLE.TYPES.VAN]: LOGISTICS_VEHICLE_TYPE.ICONS.VAN,
    [LOGISTICS_VEHICLE.TYPES.TRUCK]: LOGISTICS_VEHICLE_TYPE.ICONS.TRUCK,
    [LOGISTICS_VEHICLE.TYPES.PICKUP]: LOGISTICS_VEHICLE_TYPE.ICONS.PICKUP,
    [LOGISTICS_VEHICLE.TYPES.BUS]: LOGISTICS_VEHICLE_TYPE.ICONS.BUS,
    [LOGISTICS_VEHICLE.TYPES.TEMPO]: LOGISTICS_VEHICLE_TYPE.ICONS.TEMPO,
    [LOGISTICS_VEHICLE.TYPES.CNG]: LOGISTICS_VEHICLE_TYPE.ICONS.CNG,
    [LOGISTICS_VEHICLE.TYPES.SHIP]: LOGISTICS_VEHICLE_TYPE.ICONS.SHIP,
    [LOGISTICS_VEHICLE.TYPES.PLANE]: LOGISTICS_VEHICLE_TYPE.ICONS.PLANE,
  };
  return icons[type] || '🚗';
}

export function logisticsVehicleTypeGetColor(
  type: LogisticsVehicleType
): LogisticsVehicleTypeColor {
  const colors: Record<LogisticsVehicleType, LogisticsVehicleTypeColor> = {
    [LOGISTICS_VEHICLE.TYPES.BIKE]: LOGISTICS_VEHICLE_TYPE.COLORS.BIKE,
    [LOGISTICS_VEHICLE.TYPES.CAR]: LOGISTICS_VEHICLE_TYPE.COLORS.CAR,
    [LOGISTICS_VEHICLE.TYPES.VAN]: LOGISTICS_VEHICLE_TYPE.COLORS.VAN,
    [LOGISTICS_VEHICLE.TYPES.TRUCK]: LOGISTICS_VEHICLE_TYPE.COLORS.TRUCK,
    [LOGISTICS_VEHICLE.TYPES.PICKUP]: LOGISTICS_VEHICLE_TYPE.COLORS.PICKUP,
    [LOGISTICS_VEHICLE.TYPES.BUS]: LOGISTICS_VEHICLE_TYPE.COLORS.BUS,
    [LOGISTICS_VEHICLE.TYPES.TEMPO]: LOGISTICS_VEHICLE_TYPE.COLORS.TEMPO,
    [LOGISTICS_VEHICLE.TYPES.CNG]: LOGISTICS_VEHICLE_TYPE.COLORS.CNG,
    [LOGISTICS_VEHICLE.TYPES.SHIP]: LOGISTICS_VEHICLE_TYPE.COLORS.SHIP,
    [LOGISTICS_VEHICLE.TYPES.PLANE]: LOGISTICS_VEHICLE_TYPE.COLORS.PLANE,
  };
  return colors[type] || '#blue-500';
}

export function logisticsVehicleTypeGetLicenseTypes(type: LogisticsVehicleType): string[] {
  const licenseTypes: Record<LogisticsVehicleType, string[]> = {
    [LOGISTICS_VEHICLE.TYPES.BIKE]: LOGISTICS_VEHICLE_TYPE.LICENSE_TYPES.BIKE,
    [LOGISTICS_VEHICLE.TYPES.CAR]: LOGISTICS_VEHICLE_TYPE.LICENSE_TYPES.CAR,
    [LOGISTICS_VEHICLE.TYPES.VAN]: LOGISTICS_VEHICLE_TYPE.LICENSE_TYPES.VAN,
    [LOGISTICS_VEHICLE.TYPES.TRUCK]: LOGISTICS_VEHICLE_TYPE.LICENSE_TYPES.TRUCK,
    [LOGISTICS_VEHICLE.TYPES.PICKUP]: LOGISTICS_VEHICLE_TYPE.LICENSE_TYPES.PICKUP,
    [LOGISTICS_VEHICLE.TYPES.BUS]: LOGISTICS_VEHICLE_TYPE.LICENSE_TYPES.BUS,
    [LOGISTICS_VEHICLE.TYPES.TEMPO]: LOGISTICS_VEHICLE_TYPE.LICENSE_TYPES.TEMPO,
    [LOGISTICS_VEHICLE.TYPES.CNG]: LOGISTICS_VEHICLE_TYPE.LICENSE_TYPES.CNG,
    [LOGISTICS_VEHICLE.TYPES.SHIP]: LOGISTICS_VEHICLE_TYPE.LICENSE_TYPES.SHIP,
    [LOGISTICS_VEHICLE.TYPES.PLANE]: LOGISTICS_VEHICLE_TYPE.LICENSE_TYPES.PLANE,
  };
  return licenseTypes[type] || ['light_vehicle'];
}

export function logisticsVehicleTypeGetPermitType(type: LogisticsVehicleType): string {
  const permitTypes: Record<LogisticsVehicleType, string> = {
    [LOGISTICS_VEHICLE.TYPES.BIKE]: LOGISTICS_VEHICLE_TYPE.PERMIT_TYPES.BIKE,
    [LOGISTICS_VEHICLE.TYPES.CAR]: LOGISTICS_VEHICLE_TYPE.PERMIT_TYPES.CAR,
    [LOGISTICS_VEHICLE.TYPES.VAN]: LOGISTICS_VEHICLE_TYPE.PERMIT_TYPES.VAN,
    [LOGISTICS_VEHICLE.TYPES.TRUCK]: LOGISTICS_VEHICLE_TYPE.PERMIT_TYPES.TRUCK,
    [LOGISTICS_VEHICLE.TYPES.PICKUP]: LOGISTICS_VEHICLE_TYPE.PERMIT_TYPES.PICKUP,
    [LOGISTICS_VEHICLE.TYPES.BUS]: LOGISTICS_VEHICLE_TYPE.PERMIT_TYPES.BUS,
    [LOGISTICS_VEHICLE.TYPES.TEMPO]: LOGISTICS_VEHICLE_TYPE.PERMIT_TYPES.TEMPO,
    [LOGISTICS_VEHICLE.TYPES.CNG]: LOGISTICS_VEHICLE_TYPE.PERMIT_TYPES.CNG,
    [LOGISTICS_VEHICLE.TYPES.SHIP]: LOGISTICS_VEHICLE_TYPE.PERMIT_TYPES.SHIP,
    [LOGISTICS_VEHICLE.TYPES.PLANE]: LOGISTICS_VEHICLE_TYPE.PERMIT_TYPES.PLANE,
  };
  return permitTypes[type] || 'private';
}
