/**
 * In-App Status Constants
 * Status definitions for in-app notifications
 */

export const NOTIFICATIONINAPP_STATUS = {
  // In-App Statuses
  STATUSES: {
    PENDING: 'pending',
    QUEUED: 'queued',
    DISPLAYED: 'displayed',
    DISMISSED: 'dismissed',
    CLICKED: 'clicked',
    FAILED: 'failed',
    EXPIRED: 'expired',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    DRAFT: 'draft',
    SCHEDULED: 'scheduled',
    READ: 'read',
    UNREAD: 'unread',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    DRAFT: '#6B7280',
    PENDING: '#F59E0B',
    QUEUED: '#8B5CF6',
    SCHEDULED: '#3B82F6',
    DISPLAYED: '#3B82F6',
    READ: '#10B981',
    UNREAD: '#3B82F6',
    CLICKED: '#10B981',
    DISMISSED: '#6B7280',
    FAILED: '#EF4444',
    EXPIRED: '#6B7280',
    CANCELLED: '#6B7280',
    ARCHIVED: '#6B7280',
  } as const,

  // Status Categories
  CATEGORIES: {
    DRAFT: 'draft',
    PENDING: 'pending',
    ACTIVE: 'active',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
  } as const,

  // Status Priority Order
  ORDER: {
    DRAFT: 0,
    PENDING: 1,
    SCHEDULED: 2,
    QUEUED: 3,
    DISPLAYED: 4,
    READ: 5,
    UNREAD: 6,
    CLICKED: 7,
    DISMISSED: 8,
    FAILED: 9,
    EXPIRED: 10,
    CANCELLED: 11,
    ARCHIVED: 12,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    DRAFT_TO_PENDING: 'draft_to_pending',
    DRAFT_TO_CANCELLED: 'draft_to_cancelled',
    DRAFT_TO_ARCHIVED: 'draft_to_archived',
    PENDING_TO_SCHEDULED: 'pending_to_scheduled',
    PENDING_TO_QUEUED: 'pending_to_queued',
    PENDING_TO_CANCELLED: 'pending_to_cancelled',
    SCHEDULED_TO_QUEUED: 'scheduled_to_queued',
    SCHEDULED_TO_CANCELLED: 'scheduled_to_cancelled',
    QUEUED_TO_DISPLAYED: 'queued_to_displayed',
    QUEUED_TO_FAILED: 'queued_to_failed',
    QUEUED_TO_CANCELLED: 'queued_to_cancelled',
    DISPLAYED_TO_READ: 'displayed_to_read',
    DISPLAYED_TO_UNREAD: 'displayed_to_unread',
    DISPLAYED_TO_DISMISSED: 'displayed_to_dismissed',
    DISPLAYED_TO_CLICKED: 'displayed_to_clicked',
    DISPLAYED_TO_FAILED: 'displayed_to_failed',
    READ_TO_CLICKED: 'read_to_clicked',
    READ_TO_DISMISSED: 'read_to_dismissed',
    UNREAD_TO_READ: 'unread_to_read',
    UNREAD_TO_DISMISSED: 'unread_to_dismissed',
    UNREAD_TO_CLICKED: 'unread_to_clicked',
    CLICKED_TO_ARCHIVED: 'clicked_to_archived',
    DISMISSED_TO_ARCHIVED: 'dismissed_to_archived',
    FAILED_TO_ARCHIVED: 'failed_to_archived',
    EXPIRED_TO_ARCHIVED: 'expired_to_archived',
    CANCELLED_TO_ARCHIVED: 'cancelled_to_archived',
  } as const,
} as const;

// In-App Statuses
export type NotificationInAppStatusType =
  (typeof NOTIFICATIONINAPP_STATUS.STATUSES)[keyof typeof NOTIFICATIONINAPP_STATUS.STATUSES];

// Status Colors
export type NotificationInAppStatusColor =
  (typeof NOTIFICATIONINAPP_STATUS.COLORS)[keyof typeof NOTIFICATIONINAPP_STATUS.COLORS];

// Status Categories
export type NotificationInAppStatusCategory =
  (typeof NOTIFICATIONINAPP_STATUS.CATEGORIES)[keyof typeof NOTIFICATIONINAPP_STATUS.CATEGORIES];

// Status Priority Order
export type NotificationInAppStatusOrder =
  (typeof NOTIFICATIONINAPP_STATUS.ORDER)[keyof typeof NOTIFICATIONINAPP_STATUS.ORDER];

// Status Transitions
export type NotificationInAppStatusTransition =
  (typeof NOTIFICATIONINAPP_STATUS.TRANSITIONS)[keyof typeof NOTIFICATIONINAPP_STATUS.TRANSITIONS];

// Utility Functions
export function notificationinappGetStatusLabel(status: NotificationInAppStatusType): string {
  const labels: Record<NotificationInAppStatusType, string> = {
    [NOTIFICATIONINAPP_STATUS.STATUSES.DRAFT]: 'Draft',
    [NOTIFICATIONINAPP_STATUS.STATUSES.PENDING]: 'Pending',
    [NOTIFICATIONINAPP_STATUS.STATUSES.QUEUED]: 'Queued',
    [NOTIFICATIONINAPP_STATUS.STATUSES.SCHEDULED]: 'Scheduled',
    [NOTIFICATIONINAPP_STATUS.STATUSES.DISPLAYED]: 'Displayed',
    [NOTIFICATIONINAPP_STATUS.STATUSES.READ]: 'Read',
    [NOTIFICATIONINAPP_STATUS.STATUSES.UNREAD]: 'Unread',
    [NOTIFICATIONINAPP_STATUS.STATUSES.CLICKED]: 'Clicked',
    [NOTIFICATIONINAPP_STATUS.STATUSES.DISMISSED]: 'Dismissed',
    [NOTIFICATIONINAPP_STATUS.STATUSES.FAILED]: 'Failed',
    [NOTIFICATIONINAPP_STATUS.STATUSES.EXPIRED]: 'Expired',
    [NOTIFICATIONINAPP_STATUS.STATUSES.CANCELLED]: 'Cancelled',
    [NOTIFICATIONINAPP_STATUS.STATUSES.ARCHIVED]: 'Archived',
  };
  return labels[status] || 'Unknown Status';
}

export function notificationinappGetStatusColor(
  status: NotificationInAppStatusType
): NotificationInAppStatusColor {
  const colors: Record<NotificationInAppStatusType, NotificationInAppStatusColor> = {
    [NOTIFICATIONINAPP_STATUS.STATUSES.DRAFT]: NOTIFICATIONINAPP_STATUS.COLORS.DRAFT,
    [NOTIFICATIONINAPP_STATUS.STATUSES.PENDING]: NOTIFICATIONINAPP_STATUS.COLORS.PENDING,
    [NOTIFICATIONINAPP_STATUS.STATUSES.QUEUED]: NOTIFICATIONINAPP_STATUS.COLORS.QUEUED,
    [NOTIFICATIONINAPP_STATUS.STATUSES.SCHEDULED]: NOTIFICATIONINAPP_STATUS.COLORS.SCHEDULED,
    [NOTIFICATIONINAPP_STATUS.STATUSES.DISPLAYED]: NOTIFICATIONINAPP_STATUS.COLORS.DISPLAYED,
    [NOTIFICATIONINAPP_STATUS.STATUSES.READ]: NOTIFICATIONINAPP_STATUS.COLORS.READ,
    [NOTIFICATIONINAPP_STATUS.STATUSES.UNREAD]: NOTIFICATIONINAPP_STATUS.COLORS.UNREAD,
    [NOTIFICATIONINAPP_STATUS.STATUSES.CLICKED]: NOTIFICATIONINAPP_STATUS.COLORS.CLICKED,
    [NOTIFICATIONINAPP_STATUS.STATUSES.DISMISSED]: NOTIFICATIONINAPP_STATUS.COLORS.DISMISSED,
    [NOTIFICATIONINAPP_STATUS.STATUSES.FAILED]: NOTIFICATIONINAPP_STATUS.COLORS.FAILED,
    [NOTIFICATIONINAPP_STATUS.STATUSES.EXPIRED]: NOTIFICATIONINAPP_STATUS.COLORS.EXPIRED,
    [NOTIFICATIONINAPP_STATUS.STATUSES.CANCELLED]: NOTIFICATIONINAPP_STATUS.COLORS.CANCELLED,
    [NOTIFICATIONINAPP_STATUS.STATUSES.ARCHIVED]: NOTIFICATIONINAPP_STATUS.COLORS.ARCHIVED,
  };
  return colors[status] || NOTIFICATIONINAPP_STATUS.COLORS.PENDING;
}

export function notificationinappGetStatusCategory(
  status: NotificationInAppStatusType
): NotificationInAppStatusCategory {
  const categories: Record<NotificationInAppStatusType, NotificationInAppStatusCategory> = {
    [NOTIFICATIONINAPP_STATUS.STATUSES.DRAFT]: NOTIFICATIONINAPP_STATUS.CATEGORIES.DRAFT,
    [NOTIFICATIONINAPP_STATUS.STATUSES.PENDING]: NOTIFICATIONINAPP_STATUS.CATEGORIES.PENDING,
    [NOTIFICATIONINAPP_STATUS.STATUSES.SCHEDULED]: NOTIFICATIONINAPP_STATUS.CATEGORIES.PENDING,
    [NOTIFICATIONINAPP_STATUS.STATUSES.QUEUED]: NOTIFICATIONINAPP_STATUS.CATEGORIES.PENDING,
    [NOTIFICATIONINAPP_STATUS.STATUSES.DISPLAYED]: NOTIFICATIONINAPP_STATUS.CATEGORIES.ACTIVE,
    [NOTIFICATIONINAPP_STATUS.STATUSES.READ]: NOTIFICATIONINAPP_STATUS.CATEGORIES.ACTIVE,
    [NOTIFICATIONINAPP_STATUS.STATUSES.UNREAD]: NOTIFICATIONINAPP_STATUS.CATEGORIES.ACTIVE,
    [NOTIFICATIONINAPP_STATUS.STATUSES.CLICKED]: NOTIFICATIONINAPP_STATUS.CATEGORIES.COMPLETED,
    [NOTIFICATIONINAPP_STATUS.STATUSES.DISMISSED]: NOTIFICATIONINAPP_STATUS.CATEGORIES.COMPLETED,
    [NOTIFICATIONINAPP_STATUS.STATUSES.FAILED]: NOTIFICATIONINAPP_STATUS.CATEGORIES.FAILED,
    [NOTIFICATIONINAPP_STATUS.STATUSES.EXPIRED]: NOTIFICATIONINAPP_STATUS.CATEGORIES.FAILED,
    [NOTIFICATIONINAPP_STATUS.STATUSES.CANCELLED]: NOTIFICATIONINAPP_STATUS.CATEGORIES.CANCELLED,
    [NOTIFICATIONINAPP_STATUS.STATUSES.ARCHIVED]: NOTIFICATIONINAPP_STATUS.CATEGORIES.ARCHIVED,
  };
  return categories[status] || NOTIFICATIONINAPP_STATUS.CATEGORIES.PENDING;
}

export function notificationinappIsDisplayed(status: NotificationInAppStatusType): boolean {
  const displayedStatuses: NotificationInAppStatusType[] = [
    NOTIFICATIONINAPP_STATUS.STATUSES.DISPLAYED,
    NOTIFICATIONINAPP_STATUS.STATUSES.READ,
    NOTIFICATIONINAPP_STATUS.STATUSES.UNREAD,
    NOTIFICATIONINAPP_STATUS.STATUSES.CLICKED,
  ];
  return displayedStatuses.includes(status);
}

export function notificationinappIsEngaged(status: NotificationInAppStatusType): boolean {
  const engagedStatuses: NotificationInAppStatusType[] = [
    NOTIFICATIONINAPP_STATUS.STATUSES.CLICKED,
    NOTIFICATIONINAPP_STATUS.STATUSES.READ,
  ];
  return engagedStatuses.includes(status);
}

export function notificationinappIsFailed(status: NotificationInAppStatusType): boolean {
  const failedStatuses: NotificationInAppStatusType[] = [
    NOTIFICATIONINAPP_STATUS.STATUSES.FAILED,
    NOTIFICATIONINAPP_STATUS.STATUSES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}

export function notificationinappIsPending(status: NotificationInAppStatusType): boolean {
  const pendingStatuses: NotificationInAppStatusType[] = [
    NOTIFICATIONINAPP_STATUS.STATUSES.PENDING,
    NOTIFICATIONINAPP_STATUS.STATUSES.QUEUED,
    NOTIFICATIONINAPP_STATUS.STATUSES.SCHEDULED,
  ];
  return pendingStatuses.includes(status);
}

export function notificationinappCanTransition(
  currentStatus: NotificationInAppStatusType,
  targetStatus: NotificationInAppStatusType
): boolean {
  const validTransitions: Record<NotificationInAppStatusType, NotificationInAppStatusType[]> = {
    [NOTIFICATIONINAPP_STATUS.STATUSES.DRAFT]: [
      NOTIFICATIONINAPP_STATUS.STATUSES.PENDING,
      NOTIFICATIONINAPP_STATUS.STATUSES.CANCELLED,
      NOTIFICATIONINAPP_STATUS.STATUSES.ARCHIVED,
    ],
    [NOTIFICATIONINAPP_STATUS.STATUSES.PENDING]: [
      NOTIFICATIONINAPP_STATUS.STATUSES.SCHEDULED,
      NOTIFICATIONINAPP_STATUS.STATUSES.QUEUED,
      NOTIFICATIONINAPP_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONINAPP_STATUS.STATUSES.SCHEDULED]: [
      NOTIFICATIONINAPP_STATUS.STATUSES.QUEUED,
      NOTIFICATIONINAPP_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONINAPP_STATUS.STATUSES.QUEUED]: [
      NOTIFICATIONINAPP_STATUS.STATUSES.DISPLAYED,
      NOTIFICATIONINAPP_STATUS.STATUSES.FAILED,
      NOTIFICATIONINAPP_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONINAPP_STATUS.STATUSES.DISPLAYED]: [
      NOTIFICATIONINAPP_STATUS.STATUSES.READ,
      NOTIFICATIONINAPP_STATUS.STATUSES.UNREAD,
      NOTIFICATIONINAPP_STATUS.STATUSES.DISMISSED,
      NOTIFICATIONINAPP_STATUS.STATUSES.CLICKED,
      NOTIFICATIONINAPP_STATUS.STATUSES.FAILED,
    ],
    [NOTIFICATIONINAPP_STATUS.STATUSES.READ]: [
      NOTIFICATIONINAPP_STATUS.STATUSES.CLICKED,
      NOTIFICATIONINAPP_STATUS.STATUSES.DISMISSED,
      NOTIFICATIONINAPP_STATUS.STATUSES.ARCHIVED,
    ],
    [NOTIFICATIONINAPP_STATUS.STATUSES.UNREAD]: [
      NOTIFICATIONINAPP_STATUS.STATUSES.READ,
      NOTIFICATIONINAPP_STATUS.STATUSES.DISMISSED,
      NOTIFICATIONINAPP_STATUS.STATUSES.CLICKED,
    ],
    [NOTIFICATIONINAPP_STATUS.STATUSES.CLICKED]: [NOTIFICATIONINAPP_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONINAPP_STATUS.STATUSES.DISMISSED]: [NOTIFICATIONINAPP_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONINAPP_STATUS.STATUSES.FAILED]: [NOTIFICATIONINAPP_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONINAPP_STATUS.STATUSES.EXPIRED]: [NOTIFICATIONINAPP_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONINAPP_STATUS.STATUSES.CANCELLED]: [NOTIFICATIONINAPP_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONINAPP_STATUS.STATUSES.ARCHIVED]: [],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
