/**
 * Content License Constants
 * License types and usage rights
 */

export const CONTENT_LICENSE = {
  // License Types
  TYPES: {
    ALL_RIGHTS_RESERVED: 'all_rights_reserved',
    CC_BY: 'cc_by',
    CC_BY_SA: 'cc_by_sa',
    CC_BY_ND: 'cc_by_nd',
    CC_BY_NC: 'cc_by_nc',
    CC_BY_NC_SA: 'cc_by_nc_sa',
    CC_BY_NC_ND: 'cc_by_nc_nd',
    CC0: 'cc0',
    MIT: 'mit',
    APACHE: 'apache',
    GPL: 'gpl',
    LGPL: 'lgpl',
    AGPL: 'agpl',
    BSD: 'bsd',
    ISC: 'isc',
    MPL: 'mpl',
    EPL: 'epl',
    CDDL: 'cddl',
    UNLICENSE: 'unlicense',
    PUBLIC_DOMAIN: 'public_domain',
    PROPRIETARY: 'proprietary',
    CUSTOM: 'custom',
  } as const,

  // License Categories
  CATEGORIES: {
    OPEN_SOURCE: 'open_source',
    CREATIVE_COMMONS: 'creative_commons',
    PROPRIETARY: 'proprietary',
    PUBLIC_DOMAIN: 'public_domain',
    FREE: 'free',
    COMMERCIAL: 'commercial',
  } as const,

  // License Permissions
  PERMISSIONS: {
    COMMERCIAL_USE: 'commercial_use',
    MODIFICATION: 'modification',
    DISTRIBUTION: 'distribution',
    PRIVATE_USE: 'private_use',
    SUBLICENSING: 'sublicensing',
    PATENT_USE: 'patent_use',
    TRADEMARK_USE: 'trademark_use',
  } as const,

  // License Restrictions
  RESTRICTIONS: {
    ATTRIBUTION: 'attribution',
    SHARE_ALIKE: 'share_alike',
    NON_COMMERCIAL: 'non_commercial',
    NO_DERIVATIVES: 'no_derivatives',
    NO_WARRANTY: 'no_warranty',
    LIABILITY: 'liability',
  } as const,

  // License Conditions
  CONDITIONS: {
    ATTRIBUTION: 'attribution',
    SHARE_ALIKE: 'share_alike',
    NOTICE: 'notice',
    DISCLOSE_SOURCE: 'disclose_source',
    SAME_LICENSE: 'same_license',
    NO_ADDITIONAL_RESTRICTIONS: 'no_additional_restrictions',
  } as const,

  // License Versions
  VERSIONS: {
    CC_1_0: '1.0',
    CC_2_0: '2.0',
    CC_2_5: '2.5',
    CC_3_0: '3.0',
    CC_4_0: '4.0',
    GPL_2: '2.0',
    GPL_3: '3.0',
    LGPL_2_1: '2.1',
    LGPL_3: '3.0',
    AGPL_3: '3.0',
    BSD_2: '2-clause',
    BSD_3: '3-clause',
    APACHE_2: '2.0',
    MPL_2: '2.0',
    EPL_1: '1.0',
    EPL_2: '2.0',
  } as const,

  // License URLs
  URLS: {
    CC_BY: 'https://creativecommons.org/licenses/by/4.0/',
    CC_BY_SA: 'https://creativecommons.org/licenses/by-sa/4.0/',
    CC_BY_ND: 'https://creativecommons.org/licenses/by-nd/4.0/',
    CC_BY_NC: 'https://creativecommons.org/licenses/by-nc/4.0/',
    CC_BY_NC_SA: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
    CC_BY_NC_ND: 'https://creativecommons.org/licenses/by-nc-nd/4.0/',
    CC0: 'https://creativecommons.org/publicdomain/zero/1.0/',
    MIT: 'https://opensource.org/licenses/MIT',
    APACHE: 'https://www.apache.org/licenses/LICENSE-2.0',
    GPL: 'https://www.gnu.org/licenses/gpl-3.0.html',
    LGPL: 'https://www.gnu.org/licenses/lgpl-3.0.html',
    AGPL: 'https://www.gnu.org/licenses/agpl-3.0.html',
    BSD: 'https://opensource.org/licenses/BSD-3-Clause',
    ISC: 'https://opensource.org/licenses/ISC',
    MPL: 'https://www.mozilla.org/en-US/MPL/2.0/',
    EPL: 'https://www.eclipse.org/legal/epl-2.0/',
    CDDL: 'https://opensource.org/licenses/CDDL-1.0',
    UNLICENSE: 'https://unlicense.org/',
  } as const,
} as const;

// License Types
export type ContentLicenseType = (typeof CONTENT_LICENSE.TYPES)[keyof typeof CONTENT_LICENSE.TYPES];

// License Categories
export type ContentLicenseCategory =
  (typeof CONTENT_LICENSE.CATEGORIES)[keyof typeof CONTENT_LICENSE.CATEGORIES];

// License Permissions
export type ContentLicensePermission =
  (typeof CONTENT_LICENSE.PERMISSIONS)[keyof typeof CONTENT_LICENSE.PERMISSIONS];

// License Restrictions
export type ContentLicenseRestriction =
  (typeof CONTENT_LICENSE.RESTRICTIONS)[keyof typeof CONTENT_LICENSE.RESTRICTIONS];

// License Conditions
export type ContentLicenseCondition =
  (typeof CONTENT_LICENSE.CONDITIONS)[keyof typeof CONTENT_LICENSE.CONDITIONS];

// License Versions
export type ContentLicenseVersion =
  (typeof CONTENT_LICENSE.VERSIONS)[keyof typeof CONTENT_LICENSE.VERSIONS];

// License URLs
export type ContentLicenseURL = (typeof CONTENT_LICENSE.URLS)[keyof typeof CONTENT_LICENSE.URLS];

// License Compatibility Map
export const CONTENT_LICENSE_COMPATIBILITY: Record<ContentLicenseType, readonly string[]> = {
  all_rights_reserved: [],
  cc_by: ['cc_by_sa', 'cc_by_nc', 'cc_by_nc_sa'],
  cc_by_sa: ['cc_by_sa', 'cc_by_nc_sa'],
  cc_by_nd: ['cc_by', 'cc_by_sa', 'cc_by_nc', 'cc_by_nc_sa'],
  cc_by_nc: ['cc_by_nc', 'cc_by_nc_sa', 'cc_by_nc_nd'],
  cc_by_nc_sa: ['cc_by_nc_sa'],
  cc_by_nc_nd: ['cc_by_nc', 'cc_by_nc_sa'],
  cc0: ['*'],
  mit: ['mit', 'bsd', 'isc', 'apache'],
  apache: ['apache', 'mit', 'bsd', 'isc'],
  gpl: ['gpl'],
  lgpl: ['lgpl', 'gpl'],
  agpl: ['agpl', 'gpl'],
  bsd: ['bsd', 'mit', 'isc'],
  isc: ['isc', 'mit', 'bsd'],
  mpl: ['mpl', 'gpl', 'lgpl', 'agpl'],
  epl: ['epl'],
  cddl: ['cddl', 'gpl'],
  unlicense: ['*'],
  public_domain: ['*'],
  proprietary: ['proprietary'],
  custom: ['custom'],
};

// Utility Functions
export function contentLicenseGetLabel(license: ContentLicenseType): string {
  const labels: Record<ContentLicenseType, string> = {
    [CONTENT_LICENSE.TYPES.ALL_RIGHTS_RESERVED]: 'All Rights Reserved',
    [CONTENT_LICENSE.TYPES.CC_BY]: 'Creative Commons Attribution',
    [CONTENT_LICENSE.TYPES.CC_BY_SA]: 'Creative Commons Attribution-ShareAlike',
    [CONTENT_LICENSE.TYPES.CC_BY_ND]: 'Creative Commons Attribution-NoDerivatives',
    [CONTENT_LICENSE.TYPES.CC_BY_NC]: 'Creative Commons Attribution-NonCommercial',
    [CONTENT_LICENSE.TYPES.CC_BY_NC_SA]: 'Creative Commons Attribution-NonCommercial-ShareAlike',
    [CONTENT_LICENSE.TYPES.CC_BY_NC_ND]: 'Creative Commons Attribution-NonCommercial-NoDerivatives',
    [CONTENT_LICENSE.TYPES.CC0]: 'Creative Commons Zero (Public Domain)',
    [CONTENT_LICENSE.TYPES.MIT]: 'MIT License',
    [CONTENT_LICENSE.TYPES.APACHE]: 'Apache License',
    [CONTENT_LICENSE.TYPES.GPL]: 'GNU General Public License',
    [CONTENT_LICENSE.TYPES.LGPL]: 'GNU Lesser General Public License',
    [CONTENT_LICENSE.TYPES.AGPL]: 'GNU Affero General Public License',
    [CONTENT_LICENSE.TYPES.BSD]: 'BSD License',
    [CONTENT_LICENSE.TYPES.ISC]: 'ISC License',
    [CONTENT_LICENSE.TYPES.MPL]: 'Mozilla Public License',
    [CONTENT_LICENSE.TYPES.EPL]: 'Eclipse Public License',
    [CONTENT_LICENSE.TYPES.CDDL]: 'Common Development and Distribution License',
    [CONTENT_LICENSE.TYPES.UNLICENSE]: 'The Unlicense',
    [CONTENT_LICENSE.TYPES.PUBLIC_DOMAIN]: 'Public Domain',
    [CONTENT_LICENSE.TYPES.PROPRIETARY]: 'Proprietary License',
    [CONTENT_LICENSE.TYPES.CUSTOM]: 'Custom License',
  };
  return labels[license] || 'Unknown License';
}

export function contentLicenseGetCategory(license: ContentLicenseType): ContentLicenseCategory {
  const categoryMap: Record<ContentLicenseType, ContentLicenseCategory> = {
    [CONTENT_LICENSE.TYPES.ALL_RIGHTS_RESERVED]: CONTENT_LICENSE.CATEGORIES.PROPRIETARY,
    [CONTENT_LICENSE.TYPES.CC_BY]: CONTENT_LICENSE.CATEGORIES.CREATIVE_COMMONS,
    [CONTENT_LICENSE.TYPES.CC_BY_SA]: CONTENT_LICENSE.CATEGORIES.CREATIVE_COMMONS,
    [CONTENT_LICENSE.TYPES.CC_BY_ND]: CONTENT_LICENSE.CATEGORIES.CREATIVE_COMMONS,
    [CONTENT_LICENSE.TYPES.CC_BY_NC]: CONTENT_LICENSE.CATEGORIES.CREATIVE_COMMONS,
    [CONTENT_LICENSE.TYPES.CC_BY_NC_SA]: CONTENT_LICENSE.CATEGORIES.CREATIVE_COMMONS,
    [CONTENT_LICENSE.TYPES.CC_BY_NC_ND]: CONTENT_LICENSE.CATEGORIES.CREATIVE_COMMONS,
    [CONTENT_LICENSE.TYPES.CC0]: CONTENT_LICENSE.CATEGORIES.PUBLIC_DOMAIN,
    [CONTENT_LICENSE.TYPES.MIT]: CONTENT_LICENSE.CATEGORIES.OPEN_SOURCE,
    [CONTENT_LICENSE.TYPES.APACHE]: CONTENT_LICENSE.CATEGORIES.OPEN_SOURCE,
    [CONTENT_LICENSE.TYPES.GPL]: CONTENT_LICENSE.CATEGORIES.OPEN_SOURCE,
    [CONTENT_LICENSE.TYPES.LGPL]: CONTENT_LICENSE.CATEGORIES.OPEN_SOURCE,
    [CONTENT_LICENSE.TYPES.AGPL]: CONTENT_LICENSE.CATEGORIES.OPEN_SOURCE,
    [CONTENT_LICENSE.TYPES.BSD]: CONTENT_LICENSE.CATEGORIES.OPEN_SOURCE,
    [CONTENT_LICENSE.TYPES.ISC]: CONTENT_LICENSE.CATEGORIES.OPEN_SOURCE,
    [CONTENT_LICENSE.TYPES.MPL]: CONTENT_LICENSE.CATEGORIES.OPEN_SOURCE,
    [CONTENT_LICENSE.TYPES.EPL]: CONTENT_LICENSE.CATEGORIES.OPEN_SOURCE,
    [CONTENT_LICENSE.TYPES.CDDL]: CONTENT_LICENSE.CATEGORIES.OPEN_SOURCE,
    [CONTENT_LICENSE.TYPES.UNLICENSE]: CONTENT_LICENSE.CATEGORIES.PUBLIC_DOMAIN,
    [CONTENT_LICENSE.TYPES.PUBLIC_DOMAIN]: CONTENT_LICENSE.CATEGORIES.PUBLIC_DOMAIN,
    [CONTENT_LICENSE.TYPES.PROPRIETARY]: CONTENT_LICENSE.CATEGORIES.PROPRIETARY,
    [CONTENT_LICENSE.TYPES.CUSTOM]: CONTENT_LICENSE.CATEGORIES.PROPRIETARY,
  };
  return categoryMap[license] || CONTENT_LICENSE.CATEGORIES.PROPRIETARY;
}

export function contentLicenseGetVersion(
  license: ContentLicenseType
): ContentLicenseVersion | undefined {
  const versionMap: Partial<Record<ContentLicenseType, ContentLicenseVersion>> = {
    [CONTENT_LICENSE.TYPES.CC_BY]: CONTENT_LICENSE.VERSIONS.CC_4_0,
    [CONTENT_LICENSE.TYPES.CC_BY_SA]: CONTENT_LICENSE.VERSIONS.CC_4_0,
    [CONTENT_LICENSE.TYPES.CC_BY_ND]: CONTENT_LICENSE.VERSIONS.CC_4_0,
    [CONTENT_LICENSE.TYPES.CC_BY_NC]: CONTENT_LICENSE.VERSIONS.CC_4_0,
    [CONTENT_LICENSE.TYPES.CC_BY_NC_SA]: CONTENT_LICENSE.VERSIONS.CC_4_0,
    [CONTENT_LICENSE.TYPES.CC_BY_NC_ND]: CONTENT_LICENSE.VERSIONS.CC_4_0,
    [CONTENT_LICENSE.TYPES.CC0]: CONTENT_LICENSE.VERSIONS.CC_4_0,
    [CONTENT_LICENSE.TYPES.APACHE]: CONTENT_LICENSE.VERSIONS.APACHE_2,
    [CONTENT_LICENSE.TYPES.GPL]: CONTENT_LICENSE.VERSIONS.GPL_3,
    [CONTENT_LICENSE.TYPES.LGPL]: CONTENT_LICENSE.VERSIONS.LGPL_3,
    [CONTENT_LICENSE.TYPES.AGPL]: CONTENT_LICENSE.VERSIONS.AGPL_3,
    [CONTENT_LICENSE.TYPES.BSD]: CONTENT_LICENSE.VERSIONS.BSD_3,
    [CONTENT_LICENSE.TYPES.MPL]: CONTENT_LICENSE.VERSIONS.MPL_2,
    [CONTENT_LICENSE.TYPES.EPL]: CONTENT_LICENSE.VERSIONS.EPL_2,
  };
  return versionMap[license];
}

export function contentLicenseGetURL(license: ContentLicenseType): ContentLicenseURL | undefined {
  const urlMap: Partial<Record<ContentLicenseType, ContentLicenseURL>> = {
    [CONTENT_LICENSE.TYPES.CC_BY]: CONTENT_LICENSE.URLS.CC_BY,
    [CONTENT_LICENSE.TYPES.CC_BY_SA]: CONTENT_LICENSE.URLS.CC_BY_SA,
    [CONTENT_LICENSE.TYPES.CC_BY_ND]: CONTENT_LICENSE.URLS.CC_BY_ND,
    [CONTENT_LICENSE.TYPES.CC_BY_NC]: CONTENT_LICENSE.URLS.CC_BY_NC,
    [CONTENT_LICENSE.TYPES.CC_BY_NC_SA]: CONTENT_LICENSE.URLS.CC_BY_NC_SA,
    [CONTENT_LICENSE.TYPES.CC_BY_NC_ND]: CONTENT_LICENSE.URLS.CC_BY_NC_ND,
    [CONTENT_LICENSE.TYPES.CC0]: CONTENT_LICENSE.URLS.CC0,
    [CONTENT_LICENSE.TYPES.MIT]: CONTENT_LICENSE.URLS.MIT,
    [CONTENT_LICENSE.TYPES.APACHE]: CONTENT_LICENSE.URLS.APACHE,
    [CONTENT_LICENSE.TYPES.GPL]: CONTENT_LICENSE.URLS.GPL,
    [CONTENT_LICENSE.TYPES.LGPL]: CONTENT_LICENSE.URLS.LGPL,
    [CONTENT_LICENSE.TYPES.AGPL]: CONTENT_LICENSE.URLS.AGPL,
    [CONTENT_LICENSE.TYPES.BSD]: CONTENT_LICENSE.URLS.BSD,
    [CONTENT_LICENSE.TYPES.ISC]: CONTENT_LICENSE.URLS.ISC,
    [CONTENT_LICENSE.TYPES.MPL]: CONTENT_LICENSE.URLS.MPL,
    [CONTENT_LICENSE.TYPES.EPL]: CONTENT_LICENSE.URLS.EPL,
    [CONTENT_LICENSE.TYPES.CDDL]: CONTENT_LICENSE.URLS.CDDL,
    [CONTENT_LICENSE.TYPES.UNLICENSE]: CONTENT_LICENSE.URLS.UNLICENSE,
  };
  return urlMap[license];
}

export function contentLicenseHasPermission(
  license: ContentLicenseType,
  permission: ContentLicensePermission
): boolean {
  const permissionsMap: Record<ContentLicenseType, ContentLicensePermission[]> = {
    [CONTENT_LICENSE.TYPES.ALL_RIGHTS_RESERVED]: [CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE],
    [CONTENT_LICENSE.TYPES.CC_BY]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.CC_BY_SA]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.CC_BY_ND]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.CC_BY_NC]: [
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.CC_BY_NC_SA]: [
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.CC_BY_NC_ND]: [
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.CC0]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.SUBLICENSING,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
      CONTENT_LICENSE.PERMISSIONS.TRADEMARK_USE,
    ],
    [CONTENT_LICENSE.TYPES.MIT]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.SUBLICENSING,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.APACHE]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.SUBLICENSING,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.GPL]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.LGPL]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.AGPL]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.BSD]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.SUBLICENSING,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.ISC]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.SUBLICENSING,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.MPL]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.EPL]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.CDDL]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
    ],
    [CONTENT_LICENSE.TYPES.UNLICENSE]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.SUBLICENSING,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
      CONTENT_LICENSE.PERMISSIONS.TRADEMARK_USE,
    ],
    [CONTENT_LICENSE.TYPES.PUBLIC_DOMAIN]: [
      CONTENT_LICENSE.PERMISSIONS.COMMERCIAL_USE,
      CONTENT_LICENSE.PERMISSIONS.MODIFICATION,
      CONTENT_LICENSE.PERMISSIONS.DISTRIBUTION,
      CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE,
      CONTENT_LICENSE.PERMISSIONS.SUBLICENSING,
      CONTENT_LICENSE.PERMISSIONS.PATENT_USE,
      CONTENT_LICENSE.PERMISSIONS.TRADEMARK_USE,
    ],
    [CONTENT_LICENSE.TYPES.PROPRIETARY]: [CONTENT_LICENSE.PERMISSIONS.PRIVATE_USE],
    [CONTENT_LICENSE.TYPES.CUSTOM]: [],
  };
  const permissions = permissionsMap[license] || [];
  return permissions.includes(permission);
}

export function contentLicenseHasRestriction(
  license: ContentLicenseType,
  restriction: ContentLicenseRestriction
): boolean {
  const restrictionsMap: Record<ContentLicenseType, ContentLicenseRestriction[]> = {
    [CONTENT_LICENSE.TYPES.ALL_RIGHTS_RESERVED]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.CC_BY]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.CC_BY_SA]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.SHARE_ALIKE,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.CC_BY_ND]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.NO_DERIVATIVES,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.CC_BY_NC]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.NON_COMMERCIAL,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.CC_BY_NC_SA]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.NON_COMMERCIAL,
      CONTENT_LICENSE.RESTRICTIONS.SHARE_ALIKE,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.CC_BY_NC_ND]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.NON_COMMERCIAL,
      CONTENT_LICENSE.RESTRICTIONS.NO_DERIVATIVES,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.CC0]: [
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.MIT]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.APACHE]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.GPL]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.SHARE_ALIKE,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.LGPL]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.SHARE_ALIKE,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.AGPL]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.SHARE_ALIKE,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.BSD]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.ISC]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.MPL]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.EPL]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.CDDL]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.UNLICENSE]: [
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.PUBLIC_DOMAIN]: [
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.PROPRIETARY]: [
      CONTENT_LICENSE.RESTRICTIONS.ATTRIBUTION,
      CONTENT_LICENSE.RESTRICTIONS.NON_COMMERCIAL,
      CONTENT_LICENSE.RESTRICTIONS.NO_DERIVATIVES,
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
    [CONTENT_LICENSE.TYPES.CUSTOM]: [
      CONTENT_LICENSE.RESTRICTIONS.NO_WARRANTY,
      CONTENT_LICENSE.RESTRICTIONS.LIABILITY,
    ],
  };
  const restrictions = restrictionsMap[license] || [];
  return restrictions.includes(restriction);
}

export function contentLicenseIsCompatible(
  license: ContentLicenseType,
  withLicense: ContentLicenseType
): boolean {
  const compatible = CONTENT_LICENSE_COMPATIBILITY[license] || [];
  return compatible.includes('*') || compatible.includes(withLicense);
}

export function contentLicenseIsValid(license: string): license is ContentLicenseType {
  return Object.values(CONTENT_LICENSE.TYPES).includes(license as ContentLicenseType);
}

export function contentLicenseIsOpenSource(license: ContentLicenseType): boolean {
  const openSourceLicenses: ContentLicenseType[] = [
    CONTENT_LICENSE.TYPES.MIT,
    CONTENT_LICENSE.TYPES.APACHE,
    CONTENT_LICENSE.TYPES.GPL,
    CONTENT_LICENSE.TYPES.LGPL,
    CONTENT_LICENSE.TYPES.AGPL,
    CONTENT_LICENSE.TYPES.BSD,
    CONTENT_LICENSE.TYPES.ISC,
    CONTENT_LICENSE.TYPES.MPL,
    CONTENT_LICENSE.TYPES.EPL,
    CONTENT_LICENSE.TYPES.CDDL,
    CONTENT_LICENSE.TYPES.UNLICENSE,
  ];
  return openSourceLicenses.includes(license);
}
