/**
 * Content Format Constants
 * Formats and specifications for content
 */

export const CONTENT_FORMAT = {
  // Formats
  FORMATS: {
    TEXT: 'text',
    HTML: 'html',
    MARKDOWN: 'markdown',
    RICH_TEXT: 'rich_text',
    PLAIN_TEXT: 'plain_text',
    PDF: 'pdf',
    DOC: 'doc',
    DOCX: 'docx',
    XLS: 'xls',
    XLSX: 'xlsx',
    PPT: 'ppt',
    PPTX: 'pptx',
    CSV: 'csv',
    JSON: 'json',
    XML: 'xml',
    YAML: 'yaml',
    TOML: 'toml',
    RTF: 'rtf',
    ODT: 'odt',
    ODS: 'ods',
    ODP: 'odp',
  } as const,

  // MIME Types
  MIME_TYPES: {
    TEXT: 'text/plain',
    HTML: 'text/html',
    MARKDOWN: 'text/markdown',
    RICH_TEXT: 'text/richtext',
    PLAIN_TEXT: 'text/plain',
    PDF: 'application/pdf',
    DOC: 'application/msword',
    DOCX: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    XLS: 'application/vnd.ms-excel',
    XLSX: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    PPT: 'application/vnd.ms-powerpoint',
    PPTX: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    CSV: 'text/csv',
    JSON: 'application/json',
    XML: 'application/xml',
    YAML: 'application/x-yaml',
    TOML: 'application/toml',
    RTF: 'application/rtf',
    ODT: 'application/vnd.oasis.opendocument.text',
    ODS: 'application/vnd.oasis.opendocument.spreadsheet',
    ODP: 'application/vnd.oasis.opendocument.presentation',
  } as const,

  // File Extensions
  EXTENSIONS: {
    TEXT: '.txt',
    HTML: '.html',
    MARKDOWN: '.md',
    RICH_TEXT: '.rtf',
    PLAIN_TEXT: '.txt',
    PDF: '.pdf',
    DOC: '.doc',
    DOCX: '.docx',
    XLS: '.xls',
    XLSX: '.xlsx',
    PPT: '.ppt',
    PPTX: '.pptx',
    CSV: '.csv',
    JSON: '.json',
    XML: '.xml',
    YAML: '.yml',
    TOML: '.toml',
    RTF: '.rtf',
    ODT: '.odt',
    ODS: '.ods',
    ODP: '.odp',
  } as const,

  // Format Categories
  CATEGORIES: {
    TEXT: 'text',
    DOCUMENT: 'document',
    SPREADSHEET: 'spreadsheet',
    PRESENTATION: 'presentation',
    DATA: 'data',
    MARKUP: 'markup',
    EXCHANGE: 'exchange',
  } as const,

  // Format Capabilities
  CAPABILITIES: {
    RICH_TEXT: 'rich_text',
    IMAGES: 'images',
    TABLES: 'tables',
    CHARTS: 'charts',
    FORMULAS: 'formulas',
    HYPERLINKS: 'hyperlinks',
    EMBEDDED: 'embedded',
    ANIMATION: 'animation',
    AUDIO: 'audio',
    VIDEO: 'video',
    INTERACTIVE: 'interactive',
  } as const,
} as const;

// Content Formats
export type ContentFormatType =
  (typeof CONTENT_FORMAT.FORMATS)[keyof typeof CONTENT_FORMAT.FORMATS];

// MIME Types
export type ContentFormatMimeType =
  (typeof CONTENT_FORMAT.MIME_TYPES)[keyof typeof CONTENT_FORMAT.MIME_TYPES];

// File Extensions
export type ContentFormatExtension =
  (typeof CONTENT_FORMAT.EXTENSIONS)[keyof typeof CONTENT_FORMAT.EXTENSIONS];

// Format Categories
export type ContentFormatCategory =
  (typeof CONTENT_FORMAT.CATEGORIES)[keyof typeof CONTENT_FORMAT.CATEGORIES];

// Format Capabilities
export type ContentFormatCapability =
  (typeof CONTENT_FORMAT.CAPABILITIES)[keyof typeof CONTENT_FORMAT.CAPABILITIES];

// Utility Functions
export function contentFormatGetLabel(format: ContentFormatType): string {
  const labels: Record<ContentFormatType, string> = {
    [CONTENT_FORMAT.FORMATS.TEXT]: 'Text',
    [CONTENT_FORMAT.FORMATS.HTML]: 'HTML',
    [CONTENT_FORMAT.FORMATS.MARKDOWN]: 'Markdown',
    [CONTENT_FORMAT.FORMATS.RICH_TEXT]: 'Rich Text',
    [CONTENT_FORMAT.FORMATS.PLAIN_TEXT]: 'Plain Text',
    [CONTENT_FORMAT.FORMATS.PDF]: 'PDF',
    [CONTENT_FORMAT.FORMATS.DOC]: 'DOC',
    [CONTENT_FORMAT.FORMATS.DOCX]: 'DOCX',
    [CONTENT_FORMAT.FORMATS.XLS]: 'XLS',
    [CONTENT_FORMAT.FORMATS.XLSX]: 'XLSX',
    [CONTENT_FORMAT.FORMATS.PPT]: 'PPT',
    [CONTENT_FORMAT.FORMATS.PPTX]: 'PPTX',
    [CONTENT_FORMAT.FORMATS.CSV]: 'CSV',
    [CONTENT_FORMAT.FORMATS.JSON]: 'JSON',
    [CONTENT_FORMAT.FORMATS.XML]: 'XML',
    [CONTENT_FORMAT.FORMATS.YAML]: 'YAML',
    [CONTENT_FORMAT.FORMATS.TOML]: 'TOML',
    [CONTENT_FORMAT.FORMATS.RTF]: 'RTF',
    [CONTENT_FORMAT.FORMATS.ODT]: 'ODT',
    [CONTENT_FORMAT.FORMATS.ODS]: 'ODS',
    [CONTENT_FORMAT.FORMATS.ODP]: 'ODP',
  };
  return labels[format] || 'Unknown Format';
}

export function contentFormatGetMimeType(format: ContentFormatType): ContentFormatMimeType {
  const mimeMap: Record<ContentFormatType, ContentFormatMimeType> = {
    [CONTENT_FORMAT.FORMATS.TEXT]: CONTENT_FORMAT.MIME_TYPES.TEXT,
    [CONTENT_FORMAT.FORMATS.HTML]: CONTENT_FORMAT.MIME_TYPES.HTML,
    [CONTENT_FORMAT.FORMATS.MARKDOWN]: CONTENT_FORMAT.MIME_TYPES.MARKDOWN,
    [CONTENT_FORMAT.FORMATS.RICH_TEXT]: CONTENT_FORMAT.MIME_TYPES.RICH_TEXT,
    [CONTENT_FORMAT.FORMATS.PLAIN_TEXT]: CONTENT_FORMAT.MIME_TYPES.PLAIN_TEXT,
    [CONTENT_FORMAT.FORMATS.PDF]: CONTENT_FORMAT.MIME_TYPES.PDF,
    [CONTENT_FORMAT.FORMATS.DOC]: CONTENT_FORMAT.MIME_TYPES.DOC,
    [CONTENT_FORMAT.FORMATS.DOCX]: CONTENT_FORMAT.MIME_TYPES.DOCX,
    [CONTENT_FORMAT.FORMATS.XLS]: CONTENT_FORMAT.MIME_TYPES.XLS,
    [CONTENT_FORMAT.FORMATS.XLSX]: CONTENT_FORMAT.MIME_TYPES.XLSX,
    [CONTENT_FORMAT.FORMATS.PPT]: CONTENT_FORMAT.MIME_TYPES.PPT,
    [CONTENT_FORMAT.FORMATS.PPTX]: CONTENT_FORMAT.MIME_TYPES.PPTX,
    [CONTENT_FORMAT.FORMATS.CSV]: CONTENT_FORMAT.MIME_TYPES.CSV,
    [CONTENT_FORMAT.FORMATS.JSON]: CONTENT_FORMAT.MIME_TYPES.JSON,
    [CONTENT_FORMAT.FORMATS.XML]: CONTENT_FORMAT.MIME_TYPES.XML,
    [CONTENT_FORMAT.FORMATS.YAML]: CONTENT_FORMAT.MIME_TYPES.YAML,
    [CONTENT_FORMAT.FORMATS.TOML]: CONTENT_FORMAT.MIME_TYPES.TOML,
    [CONTENT_FORMAT.FORMATS.RTF]: CONTENT_FORMAT.MIME_TYPES.RTF,
    [CONTENT_FORMAT.FORMATS.ODT]: CONTENT_FORMAT.MIME_TYPES.ODT,
    [CONTENT_FORMAT.FORMATS.ODS]: CONTENT_FORMAT.MIME_TYPES.ODS,
    [CONTENT_FORMAT.FORMATS.ODP]: CONTENT_FORMAT.MIME_TYPES.ODP,
  };
  return mimeMap[format] || CONTENT_FORMAT.MIME_TYPES.TEXT;
}

export function contentFormatGetExtension(format: ContentFormatType): ContentFormatExtension {
  const extMap: Record<ContentFormatType, ContentFormatExtension> = {
    [CONTENT_FORMAT.FORMATS.TEXT]: CONTENT_FORMAT.EXTENSIONS.TEXT,
    [CONTENT_FORMAT.FORMATS.HTML]: CONTENT_FORMAT.EXTENSIONS.HTML,
    [CONTENT_FORMAT.FORMATS.MARKDOWN]: CONTENT_FORMAT.EXTENSIONS.MARKDOWN,
    [CONTENT_FORMAT.FORMATS.RICH_TEXT]: CONTENT_FORMAT.EXTENSIONS.RICH_TEXT,
    [CONTENT_FORMAT.FORMATS.PLAIN_TEXT]: CONTENT_FORMAT.EXTENSIONS.PLAIN_TEXT,
    [CONTENT_FORMAT.FORMATS.PDF]: CONTENT_FORMAT.EXTENSIONS.PDF,
    [CONTENT_FORMAT.FORMATS.DOC]: CONTENT_FORMAT.EXTENSIONS.DOC,
    [CONTENT_FORMAT.FORMATS.DOCX]: CONTENT_FORMAT.EXTENSIONS.DOCX,
    [CONTENT_FORMAT.FORMATS.XLS]: CONTENT_FORMAT.EXTENSIONS.XLS,
    [CONTENT_FORMAT.FORMATS.XLSX]: CONTENT_FORMAT.EXTENSIONS.XLSX,
    [CONTENT_FORMAT.FORMATS.PPT]: CONTENT_FORMAT.EXTENSIONS.PPT,
    [CONTENT_FORMAT.FORMATS.PPTX]: CONTENT_FORMAT.EXTENSIONS.PPTX,
    [CONTENT_FORMAT.FORMATS.CSV]: CONTENT_FORMAT.EXTENSIONS.CSV,
    [CONTENT_FORMAT.FORMATS.JSON]: CONTENT_FORMAT.EXTENSIONS.JSON,
    [CONTENT_FORMAT.FORMATS.XML]: CONTENT_FORMAT.EXTENSIONS.XML,
    [CONTENT_FORMAT.FORMATS.YAML]: CONTENT_FORMAT.EXTENSIONS.YAML,
    [CONTENT_FORMAT.FORMATS.TOML]: CONTENT_FORMAT.EXTENSIONS.TOML,
    [CONTENT_FORMAT.FORMATS.RTF]: CONTENT_FORMAT.EXTENSIONS.RTF,
    [CONTENT_FORMAT.FORMATS.ODT]: CONTENT_FORMAT.EXTENSIONS.ODT,
    [CONTENT_FORMAT.FORMATS.ODS]: CONTENT_FORMAT.EXTENSIONS.ODS,
    [CONTENT_FORMAT.FORMATS.ODP]: CONTENT_FORMAT.EXTENSIONS.ODP,
  };
  return extMap[format] || CONTENT_FORMAT.EXTENSIONS.TEXT;
}

export function contentFormatGetCategory(format: ContentFormatType): ContentFormatCategory {
  const categoryMap: Record<ContentFormatType, ContentFormatCategory> = {
    [CONTENT_FORMAT.FORMATS.TEXT]: CONTENT_FORMAT.CATEGORIES.TEXT,
    [CONTENT_FORMAT.FORMATS.HTML]: CONTENT_FORMAT.CATEGORIES.TEXT,
    [CONTENT_FORMAT.FORMATS.MARKDOWN]: CONTENT_FORMAT.CATEGORIES.TEXT,
    [CONTENT_FORMAT.FORMATS.RICH_TEXT]: CONTENT_FORMAT.CATEGORIES.TEXT,
    [CONTENT_FORMAT.FORMATS.PLAIN_TEXT]: CONTENT_FORMAT.CATEGORIES.TEXT,
    [CONTENT_FORMAT.FORMATS.PDF]: CONTENT_FORMAT.CATEGORIES.DOCUMENT,
    [CONTENT_FORMAT.FORMATS.DOC]: CONTENT_FORMAT.CATEGORIES.DOCUMENT,
    [CONTENT_FORMAT.FORMATS.DOCX]: CONTENT_FORMAT.CATEGORIES.DOCUMENT,
    [CONTENT_FORMAT.FORMATS.RTF]: CONTENT_FORMAT.CATEGORIES.DOCUMENT,
    [CONTENT_FORMAT.FORMATS.ODT]: CONTENT_FORMAT.CATEGORIES.DOCUMENT,
    [CONTENT_FORMAT.FORMATS.XLS]: CONTENT_FORMAT.CATEGORIES.SPREADSHEET,
    [CONTENT_FORMAT.FORMATS.XLSX]: CONTENT_FORMAT.CATEGORIES.SPREADSHEET,
    [CONTENT_FORMAT.FORMATS.ODS]: CONTENT_FORMAT.CATEGORIES.SPREADSHEET,
    [CONTENT_FORMAT.FORMATS.PPT]: CONTENT_FORMAT.CATEGORIES.PRESENTATION,
    [CONTENT_FORMAT.FORMATS.PPTX]: CONTENT_FORMAT.CATEGORIES.PRESENTATION,
    [CONTENT_FORMAT.FORMATS.ODP]: CONTENT_FORMAT.CATEGORIES.PRESENTATION,
    [CONTENT_FORMAT.FORMATS.CSV]: CONTENT_FORMAT.CATEGORIES.DATA,
    [CONTENT_FORMAT.FORMATS.JSON]: CONTENT_FORMAT.CATEGORIES.DATA,
    [CONTENT_FORMAT.FORMATS.XML]: CONTENT_FORMAT.CATEGORIES.DATA,
    [CONTENT_FORMAT.FORMATS.YAML]: CONTENT_FORMAT.CATEGORIES.DATA,
    [CONTENT_FORMAT.FORMATS.TOML]: CONTENT_FORMAT.CATEGORIES.DATA,
  };
  return categoryMap[format] || CONTENT_FORMAT.CATEGORIES.TEXT;
}

export function contentFormatHasCapability(
  format: ContentFormatType,
  capability: ContentFormatCapability
): boolean {
  const capabilityMap: Record<ContentFormatType, ContentFormatCapability[]> = {
    [CONTENT_FORMAT.FORMATS.TEXT]: [],
    [CONTENT_FORMAT.FORMATS.HTML]: [
      CONTENT_FORMAT.CAPABILITIES.RICH_TEXT,
      CONTENT_FORMAT.CAPABILITIES.IMAGES,
      CONTENT_FORMAT.CAPABILITIES.TABLES,
      CONTENT_FORMAT.CAPABILITIES.HYPERLINKS,
      CONTENT_FORMAT.CAPABILITIES.EMBEDDED,
    ],
    [CONTENT_FORMAT.FORMATS.MARKDOWN]: [
      CONTENT_FORMAT.CAPABILITIES.RICH_TEXT,
      CONTENT_FORMAT.CAPABILITIES.TABLES,
      CONTENT_FORMAT.CAPABILITIES.HYPERLINKS,
      CONTENT_FORMAT.CAPABILITIES.IMAGES,
    ],
    [CONTENT_FORMAT.FORMATS.RICH_TEXT]: [
      CONTENT_FORMAT.CAPABILITIES.RICH_TEXT,
      CONTENT_FORMAT.CAPABILITIES.IMAGES,
      CONTENT_FORMAT.CAPABILITIES.TABLES,
      CONTENT_FORMAT.CAPABILITIES.HYPERLINKS,
    ],
    [CONTENT_FORMAT.FORMATS.PLAIN_TEXT]: [],
    [CONTENT_FORMAT.FORMATS.PDF]: [
      CONTENT_FORMAT.CAPABILITIES.RICH_TEXT,
      CONTENT_FORMAT.CAPABILITIES.IMAGES,
      CONTENT_FORMAT.CAPABILITIES.TABLES,
      CONTENT_FORMAT.CAPABILITIES.HYPERLINKS,
      CONTENT_FORMAT.CAPABILITIES.EMBEDDED,
    ],
    [CONTENT_FORMAT.FORMATS.DOC]: [
      CONTENT_FORMAT.CAPABILITIES.RICH_TEXT,
      CONTENT_FORMAT.CAPABILITIES.IMAGES,
      CONTENT_FORMAT.CAPABILITIES.TABLES,
      CONTENT_FORMAT.CAPABILITIES.CHARTS,
      CONTENT_FORMAT.CAPABILITIES.FORMULAS,
      CONTENT_FORMAT.CAPABILITIES.HYPERLINKS,
    ],
    [CONTENT_FORMAT.FORMATS.DOCX]: [
      CONTENT_FORMAT.CAPABILITIES.RICH_TEXT,
      CONTENT_FORMAT.CAPABILITIES.IMAGES,
      CONTENT_FORMAT.CAPABILITIES.TABLES,
      CONTENT_FORMAT.CAPABILITIES.CHARTS,
      CONTENT_FORMAT.CAPABILITIES.FORMULAS,
      CONTENT_FORMAT.CAPABILITIES.HYPERLINKS,
    ],
    [CONTENT_FORMAT.FORMATS.XLS]: [
      CONTENT_FORMAT.CAPABILITIES.TABLES,
      CONTENT_FORMAT.CAPABILITIES.CHARTS,
      CONTENT_FORMAT.CAPABILITIES.FORMULAS,
    ],
    [CONTENT_FORMAT.FORMATS.XLSX]: [
      CONTENT_FORMAT.CAPABILITIES.TABLES,
      CONTENT_FORMAT.CAPABILITIES.CHARTS,
      CONTENT_FORMAT.CAPABILITIES.FORMULAS,
    ],
    [CONTENT_FORMAT.FORMATS.PPT]: [
      CONTENT_FORMAT.CAPABILITIES.RICH_TEXT,
      CONTENT_FORMAT.CAPABILITIES.IMAGES,
      CONTENT_FORMAT.CAPABILITIES.TABLES,
      CONTENT_FORMAT.CAPABILITIES.CHARTS,
      CONTENT_FORMAT.CAPABILITIES.ANIMATION,
      CONTENT_FORMAT.CAPABILITIES.AUDIO,
      CONTENT_FORMAT.CAPABILITIES.VIDEO,
    ],
    [CONTENT_FORMAT.FORMATS.PPTX]: [
      CONTENT_FORMAT.CAPABILITIES.RICH_TEXT,
      CONTENT_FORMAT.CAPABILITIES.IMAGES,
      CONTENT_FORMAT.CAPABILITIES.TABLES,
      CONTENT_FORMAT.CAPABILITIES.CHARTS,
      CONTENT_FORMAT.CAPABILITIES.ANIMATION,
      CONTENT_FORMAT.CAPABILITIES.AUDIO,
      CONTENT_FORMAT.CAPABILITIES.VIDEO,
    ],
    [CONTENT_FORMAT.FORMATS.CSV]: [CONTENT_FORMAT.CAPABILITIES.TABLES],
    [CONTENT_FORMAT.FORMATS.JSON]: [],
    [CONTENT_FORMAT.FORMATS.XML]: [],
    [CONTENT_FORMAT.FORMATS.YAML]: [],
    [CONTENT_FORMAT.FORMATS.TOML]: [],
    [CONTENT_FORMAT.FORMATS.RTF]: [
      CONTENT_FORMAT.CAPABILITIES.RICH_TEXT,
      CONTENT_FORMAT.CAPABILITIES.IMAGES,
    ],
    [CONTENT_FORMAT.FORMATS.ODT]: [
      CONTENT_FORMAT.CAPABILITIES.RICH_TEXT,
      CONTENT_FORMAT.CAPABILITIES.IMAGES,
      CONTENT_FORMAT.CAPABILITIES.TABLES,
      CONTENT_FORMAT.CAPABILITIES.HYPERLINKS,
    ],
    [CONTENT_FORMAT.FORMATS.ODS]: [
      CONTENT_FORMAT.CAPABILITIES.TABLES,
      CONTENT_FORMAT.CAPABILITIES.CHARTS,
      CONTENT_FORMAT.CAPABILITIES.FORMULAS,
    ],
    [CONTENT_FORMAT.FORMATS.ODP]: [
      CONTENT_FORMAT.CAPABILITIES.RICH_TEXT,
      CONTENT_FORMAT.CAPABILITIES.IMAGES,
      CONTENT_FORMAT.CAPABILITIES.TABLES,
      CONTENT_FORMAT.CAPABILITIES.CHARTS,
      CONTENT_FORMAT.CAPABILITIES.ANIMATION,
    ],
  };

  const capabilities = capabilityMap[format] || [];
  return capabilities.includes(capability);
}

export function contentFormatIsValid(format: string): format is ContentFormatType {
  return Object.values(CONTENT_FORMAT.FORMATS).includes(format as ContentFormatType);
}
