/**
 * Content Error Constants
 * Error codes, messages, and types for content management
 */

export const CONTENT_ERROR = {
  // Error Types
  TYPES: {
    CONTENT_NOT_FOUND: 'content_not_found',
    CONTENT_EXISTS: 'content_exists',
    CONTENT_INVALID: 'content_invalid',
    CONTENT_EXPIRED: 'content_expired',
    CONTENT_UNPUBLISHED: 'content_unpublished',
    CONTENT_ARCHIVED: 'content_archived',
    CONTENT_PENDING: 'content_pending',
    CONTENT_REJECTED: 'content_rejected',
    CONTENT_LOCKED: 'content_locked',
    CONTENT_VERSION_MISMATCH: 'content_version_mismatch',
    CONTENT_VALIDATION_FAILED: 'content_validation_failed',
    CONTENT_PERMISSION_DENIED: 'content_permission_denied',
    CONTENT_QUOTA_EXCEEDED: 'content_quota_exceeded',
    CONTENT_SIZE_EXCEEDED: 'content_size_exceeded',
    CONTENT_TYPE_INVALID: 'content_type_invalid',
    CONTENT_FORMAT_INVALID: 'content_format_invalid',
    CONTENT_LANGUAGE_INVALID: 'content_language_invalid',
    CONTENT_CATEGORY_INVALID: 'content_category_invalid',
    CONTENT_TAG_INVALID: 'content_tag_invalid',
    CONTENT_AUTHOR_INVALID: 'content_author_invalid',
    CONTENT_DATE_INVALID: 'content_date_invalid',
    CONTENT_SLUG_INVALID: 'content_slug_invalid',
    CONTENT_URL_INVALID: 'content_url_invalid',
    CONTENT_IMAGE_INVALID: 'content_image_invalid',
    CONTENT_VIDEO_INVALID: 'content_video_invalid',
    CONTENT_AUDIO_INVALID: 'content_audio_invalid',
    CONTENT_DOCUMENT_INVALID: 'content_document_invalid',
    CONTENT_MEDIA_INVALID: 'content_media_invalid',
    CONTENT_RELATION_INVALID: 'content_relation_invalid',
    CONTENT_DEPENDENCY_MISSING: 'content_dependency_missing',
    CONTENT_CIRCULAR_REFERENCE: 'content_circular_reference',
    CONTENT_TOO_MANY_REVISIONS: 'content_too_many_revisions',
    CONTENT_REVISION_NOT_FOUND: 'content_revision_not_found',
    CONTENT_REVISION_INVALID: 'content_revision_invalid',
    CONTENT_SCHEDULE_INVALID: 'content_schedule_invalid',
    CONTENT_SCHEDULE_PAST: 'content_schedule_past',
    CONTENT_PUBLISH_FAILED: 'content_publish_failed',
    CONTENT_UNPUBLISH_FAILED: 'content_unpublish_failed',
    CONTENT_DELETE_FAILED: 'content_delete_failed',
    CONTENT_RESTORE_FAILED: 'content_restore_failed',
    CONTENT_ARCHIVE_FAILED: 'content_archive_failed',
    CONTENT_IMPORT_FAILED: 'content_import_failed',
    CONTENT_EXPORT_FAILED: 'content_export_failed',
    CONTENT_SEARCH_FAILED: 'content_search_failed',
    CONTENT_SYNC_FAILED: 'content_sync_failed',
    CONTENT_BACKUP_FAILED: 'content_backup_failed',
    CONTENT_RESTORE_BACKUP_FAILED: 'content_restore_backup_failed',
    CONTENT_CACHE_FAILED: 'content_cache_failed',
    CONTENT_INDEX_FAILED: 'content_index_failed',
    CONTENT_RATING_INVALID: 'content_rating_invalid',
    CONTENT_REVIEW_FAILED: 'content_review_failed',
    CONTENT_APPROVAL_FAILED: 'content_approval_failed',
    CONTENT_REJECTION_FAILED: 'content_rejection_failed',
    CONTENT_FEEDBACK_INVALID: 'content_feedback_invalid',
    CONTENT_REPORT_INVALID: 'content_report_invalid',
    CONTENT_ANALYTICS_FAILED: 'content_analytics_failed',
    CONTENT_RECOMMENDATION_FAILED: 'content_recommendation_failed',
    CONTENT_PERSONALIZATION_FAILED: 'content_personalization_failed',
    CONTENT_CUSTOMIZATION_FAILED: 'content_customization_failed',
    CONTENT_LOCALIZATION_FAILED: 'content_localization_failed',
    CONTENT_TRANSLATION_FAILED: 'content_translation_failed',
    CONTENT_TRANSCRIPTION_FAILED: 'content_transcription_failed',
    CONTENT_CAPTION_FAILED: 'content_caption_failed',
    CONTENT_SUBTITLE_FAILED: 'content_subtitle_failed',
    CONTENT_THUMBNAIL_FAILED: 'content_thumbnail_failed',
    CONTENT_PREVIEW_FAILED: 'content_preview_failed',
    CONTENT_RENDER_FAILED: 'content_render_failed',
    CONTENT_TEMPLATE_FAILED: 'content_template_failed',
    CONTENT_LAYOUT_FAILED: 'content_layout_failed',
    CONTENT_STYLE_FAILED: 'content_style_failed',
    CONTENT_SCRIPT_FAILED: 'content_script_failed',
    CONTENT_ASSET_FAILED: 'content_asset_failed',
    CONTENT_RESOURCE_FAILED: 'content_resource_failed',
    CONTENT_NETWORK_FAILED: 'content_network_failed',
    CONTENT_SERVER_FAILED: 'content_server_failed',
    CONTENT_DATABASE_FAILED: 'content_database_failed',
    CONTENT_STORAGE_FAILED: 'content_storage_failed',
    CONTENT_MEMORY_FAILED: 'content_memory_failed',
    CONTENT_TIMEOUT: 'content_timeout',
    CONTENT_RATE_LIMIT: 'content_rate_limit',
    CONTENT_THROTTLED: 'content_throttled',
    CONTENT_BLOCKED: 'content_blocked',
    CONTENT_FLAGGED: 'content_flagged',
    CONTENT_SUSPENDED: 'content_suspended',
    CONTENT_TERMINATED: 'content_terminated',
    CUSTOM: 'custom',
  } as const,

  // Error Severity
  SEVERITY: {
    CRITICAL: 'critical',
    HIGH: 'high',
    MEDIUM: 'medium',
    LOW: 'low',
    INFO: 'info',
  } as const,

  // Error Categories
  CATEGORIES: {
    VALIDATION: 'validation',
    PERMISSION: 'permission',
    NOT_FOUND: 'not_found',
    CONFLICT: 'conflict',
    INTERNAL: 'internal',
    EXTERNAL: 'external',
    NETWORK: 'network',
    SYSTEM: 'system',
    USER: 'user',
    CONTENT: 'content',
    MEDIA: 'media',
    SCHEDULE: 'schedule',
    PUBLISH: 'publish',
    DELETE: 'delete',
    RESTORE: 'restore',
    ARCHIVE: 'archive',
    IMPORT: 'import',
    EXPORT: 'export',
    SEARCH: 'search',
    SYNC: 'sync',
    BACKUP: 'backup',
    CACHE: 'cache',
    INDEX: 'index',
    ANALYTICS: 'analytics',
    RECOMMENDATION: 'recommendation',
    PERSONALIZATION: 'personalization',
    LOCALIZATION: 'localization',
    TRANSLATION: 'translation',
    RENDER: 'render',
    TEMPLATE: 'template',
    LAYOUT: 'layout',
    ASSET: 'asset',
    RESOURCE: 'resource',
    STORAGE: 'storage',
    DATABASE: 'database',
    SERVER: 'server',
    TIMEOUT: 'timeout',
    RATE_LIMIT: 'rate_limit',
    CUSTOM: 'custom',
  } as const,

  // Error HTTP Status Codes
  HTTP_STATUS: {
    CONTENT_NOT_FOUND: 404,
    CONTENT_EXISTS: 409,
    CONTENT_INVALID: 422,
    CONTENT_EXPIRED: 410,
    CONTENT_UNPUBLISHED: 403,
    CONTENT_ARCHIVED: 410,
    CONTENT_PENDING: 403,
    CONTENT_REJECTED: 403,
    CONTENT_LOCKED: 423,
    CONTENT_VERSION_MISMATCH: 409,
    CONTENT_VALIDATION_FAILED: 422,
    CONTENT_PERMISSION_DENIED: 403,
    CONTENT_QUOTA_EXCEEDED: 429,
    CONTENT_SIZE_EXCEEDED: 413,
    CONTENT_TYPE_INVALID: 415,
    CONTENT_FORMAT_INVALID: 415,
    CONTENT_LANGUAGE_INVALID: 422,
    CONTENT_CATEGORY_INVALID: 422,
    CONTENT_TAG_INVALID: 422,
    CONTENT_AUTHOR_INVALID: 422,
    CONTENT_DATE_INVALID: 422,
    CONTENT_SLUG_INVALID: 422,
    CONTENT_URL_INVALID: 422,
    CONTENT_IMAGE_INVALID: 415,
    CONTENT_VIDEO_INVALID: 415,
    CONTENT_AUDIO_INVALID: 415,
    CONTENT_DOCUMENT_INVALID: 415,
    CONTENT_MEDIA_INVALID: 415,
    CONTENT_RELATION_INVALID: 422,
    CONTENT_DEPENDENCY_MISSING: 424,
    CONTENT_CIRCULAR_REFERENCE: 422,
    CONTENT_TOO_MANY_REVISIONS: 429,
    CONTENT_REVISION_NOT_FOUND: 404,
    CONTENT_REVISION_INVALID: 422,
    CONTENT_SCHEDULE_INVALID: 422,
    CONTENT_SCHEDULE_PAST: 422,
    CONTENT_PUBLISH_FAILED: 500,
    CONTENT_UNPUBLISH_FAILED: 500,
    CONTENT_DELETE_FAILED: 500,
    CONTENT_RESTORE_FAILED: 500,
    CONTENT_ARCHIVE_FAILED: 500,
    CONTENT_IMPORT_FAILED: 500,
    CONTENT_EXPORT_FAILED: 500,
    CONTENT_SEARCH_FAILED: 500,
    CONTENT_SYNC_FAILED: 500,
    CONTENT_BACKUP_FAILED: 500,
    CONTENT_RESTORE_BACKUP_FAILED: 500,
    CONTENT_CACHE_FAILED: 500,
    CONTENT_INDEX_FAILED: 500,
    CONTENT_RATING_INVALID: 422,
    CONTENT_REVIEW_FAILED: 500,
    CONTENT_APPROVAL_FAILED: 500,
    CONTENT_REJECTION_FAILED: 500,
    CONTENT_FEEDBACK_INVALID: 422,
    CONTENT_REPORT_INVALID: 422,
    CONTENT_ANALYTICS_FAILED: 500,
    CONTENT_RECOMMENDATION_FAILED: 500,
    CONTENT_PERSONALIZATION_FAILED: 500,
    CONTENT_CUSTOMIZATION_FAILED: 500,
    CONTENT_LOCALIZATION_FAILED: 500,
    CONTENT_TRANSLATION_FAILED: 500,
    CONTENT_TRANSCRIPTION_FAILED: 500,
    CONTENT_CAPTION_FAILED: 500,
    CONTENT_SUBTITLE_FAILED: 500,
    CONTENT_THUMBNAIL_FAILED: 500,
    CONTENT_PREVIEW_FAILED: 500,
    CONTENT_RENDER_FAILED: 500,
    CONTENT_TEMPLATE_FAILED: 500,
    CONTENT_LAYOUT_FAILED: 500,
    CONTENT_STYLE_FAILED: 500,
    CONTENT_SCRIPT_FAILED: 500,
    CONTENT_ASSET_FAILED: 500,
    CONTENT_RESOURCE_FAILED: 500,
    CONTENT_NETWORK_FAILED: 500,
    CONTENT_SERVER_FAILED: 500,
    CONTENT_DATABASE_FAILED: 500,
    CONTENT_STORAGE_FAILED: 500,
    CONTENT_MEMORY_FAILED: 500,
    CONTENT_TIMEOUT: 408,
    CONTENT_RATE_LIMIT: 429,
    CONTENT_THROTTLED: 429,
    CONTENT_BLOCKED: 403,
    CONTENT_FLAGGED: 403,
    CONTENT_SUSPENDED: 403,
    CONTENT_TERMINATED: 403,
  } as const,

  // Error Messages
  MESSAGES: {
    CONTENT_NOT_FOUND: 'Content not found',
    CONTENT_EXISTS: 'Content already exists',
    CONTENT_INVALID: 'Content is invalid',
    CONTENT_EXPIRED: 'Content has expired',
    CONTENT_UNPUBLISHED: 'Content is unpublished',
    CONTENT_ARCHIVED: 'Content is archived',
    CONTENT_PENDING: 'Content is pending review',
    CONTENT_REJECTED: 'Content has been rejected',
    CONTENT_LOCKED: 'Content is locked',
    CONTENT_VERSION_MISMATCH: 'Content version mismatch',
    CONTENT_VALIDATION_FAILED: 'Content validation failed',
    CONTENT_PERMISSION_DENIED: 'Permission denied for content',
    CONTENT_QUOTA_EXCEEDED: 'Content quota exceeded',
    CONTENT_SIZE_EXCEEDED: 'Content size exceeded limit',
    CONTENT_TYPE_INVALID: 'Invalid content type',
    CONTENT_FORMAT_INVALID: 'Invalid content format',
    CONTENT_LANGUAGE_INVALID: 'Invalid content language',
    CONTENT_CATEGORY_INVALID: 'Invalid content category',
    CONTENT_TAG_INVALID: 'Invalid content tag',
    CONTENT_AUTHOR_INVALID: 'Invalid content author',
    CONTENT_DATE_INVALID: 'Invalid content date',
    CONTENT_SLUG_INVALID: 'Invalid content slug',
    CONTENT_URL_INVALID: 'Invalid content URL',
    CONTENT_IMAGE_INVALID: 'Invalid content image',
    CONTENT_VIDEO_INVALID: 'Invalid content video',
    CONTENT_AUDIO_INVALID: 'Invalid content audio',
    CONTENT_DOCUMENT_INVALID: 'Invalid content document',
    CONTENT_MEDIA_INVALID: 'Invalid content media',
    CONTENT_RELATION_INVALID: 'Invalid content relation',
    CONTENT_DEPENDENCY_MISSING: 'Content dependency missing',
    CONTENT_CIRCULAR_REFERENCE: 'Content circular reference detected',
    CONTENT_TOO_MANY_REVISIONS: 'Too many content revisions',
    CONTENT_REVISION_NOT_FOUND: 'Content revision not found',
    CONTENT_REVISION_INVALID: 'Invalid content revision',
    CONTENT_SCHEDULE_INVALID: 'Invalid content schedule',
    CONTENT_SCHEDULE_PAST: 'Content schedule date is in the past',
    CONTENT_PUBLISH_FAILED: 'Failed to publish content',
    CONTENT_UNPUBLISH_FAILED: 'Failed to unpublish content',
    CONTENT_DELETE_FAILED: 'Failed to delete content',
    CONTENT_RESTORE_FAILED: 'Failed to restore content',
    CONTENT_ARCHIVE_FAILED: 'Failed to archive content',
    CONTENT_IMPORT_FAILED: 'Failed to import content',
    CONTENT_EXPORT_FAILED: 'Failed to export content',
    CONTENT_SEARCH_FAILED: 'Failed to search content',
    CONTENT_SYNC_FAILED: 'Failed to sync content',
    CONTENT_BACKUP_FAILED: 'Failed to backup content',
    CONTENT_RESTORE_BACKUP_FAILED: 'Failed to restore from backup',
    CONTENT_CACHE_FAILED: 'Failed to cache content',
    CONTENT_INDEX_FAILED: 'Failed to index content',
    CONTENT_RATING_INVALID: 'Invalid content rating',
    CONTENT_REVIEW_FAILED: 'Failed to review content',
    CONTENT_APPROVAL_FAILED: 'Failed to approve content',
    CONTENT_REJECTION_FAILED: 'Failed to reject content',
    CONTENT_FEEDBACK_INVALID: 'Invalid content feedback',
    CONTENT_REPORT_INVALID: 'Invalid content report',
    CONTENT_ANALYTICS_FAILED: 'Failed to get content analytics',
    CONTENT_RECOMMENDATION_FAILED: 'Failed to generate content recommendations',
    CONTENT_PERSONALIZATION_FAILED: 'Failed to personalize content',
    CONTENT_CUSTOMIZATION_FAILED: 'Failed to customize content',
    CONTENT_LOCALIZATION_FAILED: 'Failed to localize content',
    CONTENT_TRANSLATION_FAILED: 'Failed to translate content',
    CONTENT_TRANSCRIPTION_FAILED: 'Failed to transcribe content',
    CONTENT_CAPTION_FAILED: 'Failed to generate captions',
    CONTENT_SUBTITLE_FAILED: 'Failed to generate subtitles',
    CONTENT_THUMBNAIL_FAILED: 'Failed to generate thumbnail',
    CONTENT_PREVIEW_FAILED: 'Failed to generate preview',
    CONTENT_RENDER_FAILED: 'Failed to render content',
    CONTENT_TEMPLATE_FAILED: 'Failed to apply template',
    CONTENT_LAYOUT_FAILED: 'Failed to apply layout',
    CONTENT_STYLE_FAILED: 'Failed to apply styles',
    CONTENT_SCRIPT_FAILED: 'Failed to execute script',
    CONTENT_ASSET_FAILED: 'Failed to load asset',
    CONTENT_RESOURCE_FAILED: 'Failed to load resource',
    CONTENT_NETWORK_FAILED: 'Network error while loading content',
    CONTENT_SERVER_FAILED: 'Server error while processing content',
    CONTENT_DATABASE_FAILED: 'Database error while processing content',
    CONTENT_STORAGE_FAILED: 'Storage error while processing content',
    CONTENT_MEMORY_FAILED: 'Memory error while processing content',
    CONTENT_TIMEOUT: 'Content operation timed out',
    CONTENT_RATE_LIMIT: 'Content rate limit exceeded',
    CONTENT_THROTTLED: 'Content request throttled',
    CONTENT_BLOCKED: 'Content has been blocked',
    CONTENT_FLAGGED: 'Content has been flagged',
    CONTENT_SUSPENDED: 'Content has been suspended',
    CONTENT_TERMINATED: 'Content has been terminated',
  } as const,
} as const;

// Error Types
export type ContentErrorType = (typeof CONTENT_ERROR.TYPES)[keyof typeof CONTENT_ERROR.TYPES];

// Error Severity
export type ContentErrorSeverity =
  (typeof CONTENT_ERROR.SEVERITY)[keyof typeof CONTENT_ERROR.SEVERITY];

// Error Categories
export type ContentErrorCategory =
  (typeof CONTENT_ERROR.CATEGORIES)[keyof typeof CONTENT_ERROR.CATEGORIES];

// Error HTTP Status Codes
export type ContentErrorHTTPStatus =
  (typeof CONTENT_ERROR.HTTP_STATUS)[keyof typeof CONTENT_ERROR.HTTP_STATUS];

// Utility Functions
export function contentErrorGetMessage(errorType: ContentErrorType): string {
  const messages = CONTENT_ERROR.MESSAGES;
  return messages[errorType as keyof typeof messages] || 'Unknown content error';
}

export function contentErrorGetHTTPStatus(errorType: ContentErrorType): ContentErrorHTTPStatus {
  const statuses = CONTENT_ERROR.HTTP_STATUS;
  return statuses[errorType as keyof typeof statuses] || 500;
}

export function contentErrorGetSeverity(errorType: ContentErrorType): ContentErrorSeverity {
  const severityMap: Record<ContentErrorType, ContentErrorSeverity> = {
    [CONTENT_ERROR.TYPES.CONTENT_NOT_FOUND]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_EXISTS]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_INVALID]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_EXPIRED]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_UNPUBLISHED]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_ARCHIVED]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_PENDING]: 'info',
    [CONTENT_ERROR.TYPES.CONTENT_REJECTED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_LOCKED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_VERSION_MISMATCH]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_VALIDATION_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_PERMISSION_DENIED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_QUOTA_EXCEEDED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_SIZE_EXCEEDED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_TYPE_INVALID]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_FORMAT_INVALID]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_LANGUAGE_INVALID]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_CATEGORY_INVALID]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_TAG_INVALID]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_AUTHOR_INVALID]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_DATE_INVALID]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_SLUG_INVALID]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_URL_INVALID]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_IMAGE_INVALID]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_VIDEO_INVALID]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_AUDIO_INVALID]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_DOCUMENT_INVALID]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_MEDIA_INVALID]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_RELATION_INVALID]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_DEPENDENCY_MISSING]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_CIRCULAR_REFERENCE]: 'critical',
    [CONTENT_ERROR.TYPES.CONTENT_TOO_MANY_REVISIONS]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_REVISION_NOT_FOUND]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_REVISION_INVALID]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_SCHEDULE_INVALID]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_SCHEDULE_PAST]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_PUBLISH_FAILED]: 'critical',
    [CONTENT_ERROR.TYPES.CONTENT_UNPUBLISH_FAILED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_DELETE_FAILED]: 'critical',
    [CONTENT_ERROR.TYPES.CONTENT_RESTORE_FAILED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_ARCHIVE_FAILED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_IMPORT_FAILED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_EXPORT_FAILED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_SEARCH_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_SYNC_FAILED]: 'critical',
    [CONTENT_ERROR.TYPES.CONTENT_BACKUP_FAILED]: 'critical',
    [CONTENT_ERROR.TYPES.CONTENT_RESTORE_BACKUP_FAILED]: 'critical',
    [CONTENT_ERROR.TYPES.CONTENT_CACHE_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_INDEX_FAILED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_RATING_INVALID]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_REVIEW_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_APPROVAL_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_REJECTION_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_FEEDBACK_INVALID]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_REPORT_INVALID]: 'low',
    [CONTENT_ERROR.TYPES.CONTENT_ANALYTICS_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_RECOMMENDATION_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_PERSONALIZATION_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_CUSTOMIZATION_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_LOCALIZATION_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_TRANSLATION_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_TRANSCRIPTION_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_CAPTION_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_SUBTITLE_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_THUMBNAIL_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_PREVIEW_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_RENDER_FAILED]: 'critical',
    [CONTENT_ERROR.TYPES.CONTENT_TEMPLATE_FAILED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_LAYOUT_FAILED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_STYLE_FAILED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_SCRIPT_FAILED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_ASSET_FAILED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_RESOURCE_FAILED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_NETWORK_FAILED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_SERVER_FAILED]: 'critical',
    [CONTENT_ERROR.TYPES.CONTENT_DATABASE_FAILED]: 'critical',
    [CONTENT_ERROR.TYPES.CONTENT_STORAGE_FAILED]: 'critical',
    [CONTENT_ERROR.TYPES.CONTENT_MEMORY_FAILED]: 'critical',
    [CONTENT_ERROR.TYPES.CONTENT_TIMEOUT]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_RATE_LIMIT]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_THROTTLED]: 'medium',
    [CONTENT_ERROR.TYPES.CONTENT_BLOCKED]: 'critical',
    [CONTENT_ERROR.TYPES.CONTENT_FLAGGED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_SUSPENDED]: 'high',
    [CONTENT_ERROR.TYPES.CONTENT_TERMINATED]: 'critical',
    [CONTENT_ERROR.TYPES.CUSTOM]: 'medium',
  };
  return severityMap[errorType] || 'medium';
}

export function contentErrorGetCategory(errorType: ContentErrorType): ContentErrorCategory {
  const categoryMap: Record<ContentErrorType, ContentErrorCategory> = {
    [CONTENT_ERROR.TYPES.CONTENT_NOT_FOUND]: 'not_found',
    [CONTENT_ERROR.TYPES.CONTENT_EXISTS]: 'conflict',
    [CONTENT_ERROR.TYPES.CONTENT_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_EXPIRED]: 'content',
    [CONTENT_ERROR.TYPES.CONTENT_UNPUBLISHED]: 'content',
    [CONTENT_ERROR.TYPES.CONTENT_ARCHIVED]: 'content',
    [CONTENT_ERROR.TYPES.CONTENT_PENDING]: 'content',
    [CONTENT_ERROR.TYPES.CONTENT_REJECTED]: 'content',
    [CONTENT_ERROR.TYPES.CONTENT_LOCKED]: 'permission',
    [CONTENT_ERROR.TYPES.CONTENT_VERSION_MISMATCH]: 'conflict',
    [CONTENT_ERROR.TYPES.CONTENT_VALIDATION_FAILED]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_PERMISSION_DENIED]: 'permission',
    [CONTENT_ERROR.TYPES.CONTENT_QUOTA_EXCEEDED]: 'system',
    [CONTENT_ERROR.TYPES.CONTENT_SIZE_EXCEEDED]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_TYPE_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_FORMAT_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_LANGUAGE_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_CATEGORY_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_TAG_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_AUTHOR_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_DATE_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_SLUG_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_URL_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_IMAGE_INVALID]: 'media',
    [CONTENT_ERROR.TYPES.CONTENT_VIDEO_INVALID]: 'media',
    [CONTENT_ERROR.TYPES.CONTENT_AUDIO_INVALID]: 'media',
    [CONTENT_ERROR.TYPES.CONTENT_DOCUMENT_INVALID]: 'media',
    [CONTENT_ERROR.TYPES.CONTENT_MEDIA_INVALID]: 'media',
    [CONTENT_ERROR.TYPES.CONTENT_RELATION_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_DEPENDENCY_MISSING]: 'content',
    [CONTENT_ERROR.TYPES.CONTENT_CIRCULAR_REFERENCE]: 'content',
    [CONTENT_ERROR.TYPES.CONTENT_TOO_MANY_REVISIONS]: 'system',
    [CONTENT_ERROR.TYPES.CONTENT_REVISION_NOT_FOUND]: 'not_found',
    [CONTENT_ERROR.TYPES.CONTENT_REVISION_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_SCHEDULE_INVALID]: 'schedule',
    [CONTENT_ERROR.TYPES.CONTENT_SCHEDULE_PAST]: 'schedule',
    [CONTENT_ERROR.TYPES.CONTENT_PUBLISH_FAILED]: 'publish',
    [CONTENT_ERROR.TYPES.CONTENT_UNPUBLISH_FAILED]: 'publish',
    [CONTENT_ERROR.TYPES.CONTENT_DELETE_FAILED]: 'delete',
    [CONTENT_ERROR.TYPES.CONTENT_RESTORE_FAILED]: 'restore',
    [CONTENT_ERROR.TYPES.CONTENT_ARCHIVE_FAILED]: 'archive',
    [CONTENT_ERROR.TYPES.CONTENT_IMPORT_FAILED]: 'import',
    [CONTENT_ERROR.TYPES.CONTENT_EXPORT_FAILED]: 'export',
    [CONTENT_ERROR.TYPES.CONTENT_SEARCH_FAILED]: 'search',
    [CONTENT_ERROR.TYPES.CONTENT_SYNC_FAILED]: 'sync',
    [CONTENT_ERROR.TYPES.CONTENT_BACKUP_FAILED]: 'backup',
    [CONTENT_ERROR.TYPES.CONTENT_RESTORE_BACKUP_FAILED]: 'backup',
    [CONTENT_ERROR.TYPES.CONTENT_CACHE_FAILED]: 'cache',
    [CONTENT_ERROR.TYPES.CONTENT_INDEX_FAILED]: 'index',
    [CONTENT_ERROR.TYPES.CONTENT_RATING_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_REVIEW_FAILED]: 'content',
    [CONTENT_ERROR.TYPES.CONTENT_APPROVAL_FAILED]: 'content',
    [CONTENT_ERROR.TYPES.CONTENT_REJECTION_FAILED]: 'content',
    [CONTENT_ERROR.TYPES.CONTENT_FEEDBACK_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_REPORT_INVALID]: 'validation',
    [CONTENT_ERROR.TYPES.CONTENT_ANALYTICS_FAILED]: 'analytics',
    [CONTENT_ERROR.TYPES.CONTENT_RECOMMENDATION_FAILED]: 'recommendation',
    [CONTENT_ERROR.TYPES.CONTENT_PERSONALIZATION_FAILED]: 'personalization',
    [CONTENT_ERROR.TYPES.CONTENT_CUSTOMIZATION_FAILED]: 'content',
    [CONTENT_ERROR.TYPES.CONTENT_LOCALIZATION_FAILED]: 'localization',
    [CONTENT_ERROR.TYPES.CONTENT_TRANSLATION_FAILED]: 'translation',
    [CONTENT_ERROR.TYPES.CONTENT_TRANSCRIPTION_FAILED]: 'translation',
    [CONTENT_ERROR.TYPES.CONTENT_CAPTION_FAILED]: 'translation',
    [CONTENT_ERROR.TYPES.CONTENT_SUBTITLE_FAILED]: 'translation',
    [CONTENT_ERROR.TYPES.CONTENT_THUMBNAIL_FAILED]: 'media',
    [CONTENT_ERROR.TYPES.CONTENT_PREVIEW_FAILED]: 'render',
    [CONTENT_ERROR.TYPES.CONTENT_RENDER_FAILED]: 'render',
    [CONTENT_ERROR.TYPES.CONTENT_TEMPLATE_FAILED]: 'template',
    [CONTENT_ERROR.TYPES.CONTENT_LAYOUT_FAILED]: 'layout',
    [CONTENT_ERROR.TYPES.CONTENT_STYLE_FAILED]: 'render',
    [CONTENT_ERROR.TYPES.CONTENT_SCRIPT_FAILED]: 'render',
    [CONTENT_ERROR.TYPES.CONTENT_ASSET_FAILED]: 'asset',
    [CONTENT_ERROR.TYPES.CONTENT_RESOURCE_FAILED]: 'resource',
    [CONTENT_ERROR.TYPES.CONTENT_NETWORK_FAILED]: 'network',
    [CONTENT_ERROR.TYPES.CONTENT_SERVER_FAILED]: 'server',
    [CONTENT_ERROR.TYPES.CONTENT_DATABASE_FAILED]: 'database',
    [CONTENT_ERROR.TYPES.CONTENT_STORAGE_FAILED]: 'storage',
    [CONTENT_ERROR.TYPES.CONTENT_MEMORY_FAILED]: 'system',
    [CONTENT_ERROR.TYPES.CONTENT_TIMEOUT]: 'timeout',
    [CONTENT_ERROR.TYPES.CONTENT_RATE_LIMIT]: 'rate_limit',
    [CONTENT_ERROR.TYPES.CONTENT_THROTTLED]: 'rate_limit',
    [CONTENT_ERROR.TYPES.CONTENT_BLOCKED]: 'permission',
    [CONTENT_ERROR.TYPES.CONTENT_FLAGGED]: 'permission',
    [CONTENT_ERROR.TYPES.CONTENT_SUSPENDED]: 'permission',
    [CONTENT_ERROR.TYPES.CONTENT_TERMINATED]: 'permission',
    [CONTENT_ERROR.TYPES.CUSTOM]: 'custom',
  };
  return categoryMap[errorType] || 'custom';
}

export function contentErrorIsCritical(errorType: ContentErrorType): boolean {
  const severity = contentErrorGetSeverity(errorType);
  return severity === 'critical';
}

export function contentErrorIsRetryable(errorType: ContentErrorType): boolean {
  const retryableErrors: ContentErrorType[] = [
    CONTENT_ERROR.TYPES.CONTENT_NETWORK_FAILED,
    CONTENT_ERROR.TYPES.CONTENT_SERVER_FAILED,
    CONTENT_ERROR.TYPES.CONTENT_DATABASE_FAILED,
    CONTENT_ERROR.TYPES.CONTENT_STORAGE_FAILED,
    CONTENT_ERROR.TYPES.CONTENT_TIMEOUT,
    CONTENT_ERROR.TYPES.CONTENT_RATE_LIMIT,
    CONTENT_ERROR.TYPES.CONTENT_THROTTLED,
    CONTENT_ERROR.TYPES.CONTENT_SYNC_FAILED,
    CONTENT_ERROR.TYPES.CONTENT_BACKUP_FAILED,
    CONTENT_ERROR.TYPES.CONTENT_CACHE_FAILED,
    CONTENT_ERROR.TYPES.CONTENT_INDEX_FAILED,
    CONTENT_ERROR.TYPES.CONTENT_SEARCH_FAILED,
    CONTENT_ERROR.TYPES.CONTENT_EXPORT_FAILED,
    CONTENT_ERROR.TYPES.CONTENT_IMPORT_FAILED,
  ];
  return retryableErrors.includes(errorType);
}

export function contentErrorIsValidationError(errorType: ContentErrorType): boolean {
  const validationErrors: ContentErrorType[] = [
    CONTENT_ERROR.TYPES.CONTENT_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_VALIDATION_FAILED,
    CONTENT_ERROR.TYPES.CONTENT_TYPE_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_FORMAT_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_LANGUAGE_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_CATEGORY_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_TAG_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_AUTHOR_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_DATE_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_SLUG_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_URL_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_IMAGE_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_VIDEO_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_AUDIO_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_DOCUMENT_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_MEDIA_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_RELATION_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_REVISION_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_RATING_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_FEEDBACK_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_REPORT_INVALID,
    CONTENT_ERROR.TYPES.CONTENT_SIZE_EXCEEDED,
    CONTENT_ERROR.TYPES.CONTENT_SCHEDULE_INVALID,
  ];
  return validationErrors.includes(errorType);
}

export function contentErrorIsPermissionError(errorType: ContentErrorType): boolean {
  const permissionErrors: ContentErrorType[] = [
    CONTENT_ERROR.TYPES.CONTENT_PERMISSION_DENIED,
    CONTENT_ERROR.TYPES.CONTENT_LOCKED,
    CONTENT_ERROR.TYPES.CONTENT_BLOCKED,
    CONTENT_ERROR.TYPES.CONTENT_FLAGGED,
    CONTENT_ERROR.TYPES.CONTENT_SUSPENDED,
    CONTENT_ERROR.TYPES.CONTENT_TERMINATED,
  ];
  return permissionErrors.includes(errorType);
}

export function contentErrorIsNotFound(errorType: ContentErrorType): boolean {
  const notFoundErrors: ContentErrorType[] = [
    CONTENT_ERROR.TYPES.CONTENT_NOT_FOUND,
    CONTENT_ERROR.TYPES.CONTENT_REVISION_NOT_FOUND,
  ];
  return notFoundErrors.includes(errorType);
}

export function contentErrorIsValidType(errorType: string): errorType is ContentErrorType {
  return Object.values(CONTENT_ERROR.TYPES).includes(errorType as ContentErrorType);
}
