/**
 * Authentication Login Attempt Status Constants
 * Status values for login attempts
 */

export const AUTH_LOGIN_ATTEMPT_STATUS = {
  PENDING: 'pending',
  SUCCESS: 'success',
  FAILED: 'failed',
  BLOCKED: 'blocked',
  LOCKED: 'locked',
  TIMEOUT: 'timeout',
  EXPIRED: 'expired',
  REVOKED: 'revoked',

  VERIFIED: 'verified',
  UNVERIFIED: 'unverified',
  VERIFICATION_PENDING: 'verification_pending',
  VERIFICATION_FAILED: 'verification_failed',

  SECURE: 'secure',
  SUSPICIOUS: 'suspicious',
  COMPROMISED: 'compromised',
  INVESTIGATING: 'investigating',

  CAPTCHA_REQUIRED: 'captcha_required',
  CAPTCHA_VERIFIED: 'captcha_verified',
  CAPTCHA_FAILED: 'captcha_failed',

  MFA_REQUIRED: 'mfa_required',
  MFA_VERIFIED: 'mfa_verified',
  MFA_FAILED: 'mfa_failed',

  TWO_FA_REQUIRED: '2fa_required',
  TWO_FA_VERIFIED: '2fa_verified',
  TWO_FA_FAILED: '2fa_failed',
} as const;

export type AuthLoginAttemptStatus =
  (typeof AUTH_LOGIN_ATTEMPT_STATUS)[keyof typeof AUTH_LOGIN_ATTEMPT_STATUS];

export const AUTHLOGIN_SUCCESS_STATUSES: AuthLoginAttemptStatus[] = [
  AUTH_LOGIN_ATTEMPT_STATUS.SUCCESS,
  AUTH_LOGIN_ATTEMPT_STATUS.VERIFIED,
  AUTH_LOGIN_ATTEMPT_STATUS.SECURE,
  AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_VERIFIED,
  AUTH_LOGIN_ATTEMPT_STATUS.MFA_VERIFIED,
  AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_VERIFIED,
];

export const AUTHLOGIN_FAILED_STATUSES: AuthLoginAttemptStatus[] = [
  AUTH_LOGIN_ATTEMPT_STATUS.FAILED,
  AUTH_LOGIN_ATTEMPT_STATUS.UNVERIFIED,
  AUTH_LOGIN_ATTEMPT_STATUS.VERIFICATION_FAILED,
  AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_FAILED,
  AUTH_LOGIN_ATTEMPT_STATUS.MFA_FAILED,
  AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_FAILED,
];

export const AUTHLOGIN_BLOCKED_STATUSES: AuthLoginAttemptStatus[] = [
  AUTH_LOGIN_ATTEMPT_STATUS.BLOCKED,
  AUTH_LOGIN_ATTEMPT_STATUS.LOCKED,
  AUTH_LOGIN_ATTEMPT_STATUS.TIMEOUT,
  AUTH_LOGIN_ATTEMPT_STATUS.EXPIRED,
  AUTH_LOGIN_ATTEMPT_STATUS.REVOKED,
];

export const AUTHLOGIN_PENDING_STATUSES: AuthLoginAttemptStatus[] = [
  AUTH_LOGIN_ATTEMPT_STATUS.PENDING,
  AUTH_LOGIN_ATTEMPT_STATUS.VERIFICATION_PENDING,
  AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_REQUIRED,
  AUTH_LOGIN_ATTEMPT_STATUS.MFA_REQUIRED,
  AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_REQUIRED,
];

export const AUTHLOGIN_SECURITY_STATUSES: AuthLoginAttemptStatus[] = [
  AUTH_LOGIN_ATTEMPT_STATUS.SUSPICIOUS,
  AUTH_LOGIN_ATTEMPT_STATUS.COMPROMISED,
  AUTH_LOGIN_ATTEMPT_STATUS.INVESTIGATING,
];

export const AUTHLOGIN_VERIFICATION_STATUSES: AuthLoginAttemptStatus[] = [
  AUTH_LOGIN_ATTEMPT_STATUS.VERIFIED,
  AUTH_LOGIN_ATTEMPT_STATUS.UNVERIFIED,
  AUTH_LOGIN_ATTEMPT_STATUS.VERIFICATION_PENDING,
  AUTH_LOGIN_ATTEMPT_STATUS.VERIFICATION_FAILED,
];

export const AUTHLOGIN_MFA_STATUSES: AuthLoginAttemptStatus[] = [
  AUTH_LOGIN_ATTEMPT_STATUS.MFA_REQUIRED,
  AUTH_LOGIN_ATTEMPT_STATUS.MFA_VERIFIED,
  AUTH_LOGIN_ATTEMPT_STATUS.MFA_FAILED,
  AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_REQUIRED,
  AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_VERIFIED,
  AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_FAILED,
];

export function isAuthloginSuccess(status: AuthLoginAttemptStatus): boolean {
  return AUTHLOGIN_SUCCESS_STATUSES.includes(status);
}

export function isAuthloginFailed(status: AuthLoginAttemptStatus): boolean {
  return AUTHLOGIN_FAILED_STATUSES.includes(status);
}

export function isAuthloginBlocked(status: AuthLoginAttemptStatus): boolean {
  return AUTHLOGIN_BLOCKED_STATUSES.includes(status);
}

export function isAuthloginPending(status: AuthLoginAttemptStatus): boolean {
  return AUTHLOGIN_PENDING_STATUSES.includes(status);
}

export function isAuthloginSecurityIssue(status: AuthLoginAttemptStatus): boolean {
  return AUTHLOGIN_SECURITY_STATUSES.includes(status);
}

export function isAuthloginVerification(status: AuthLoginAttemptStatus): boolean {
  return AUTHLOGIN_VERIFICATION_STATUSES.includes(status);
}

export function isAuthloginMFA(status: AuthLoginAttemptStatus): boolean {
  return AUTHLOGIN_MFA_STATUSES.includes(status);
}

export function getAuthloginAttemptStatusLabel(status: AuthLoginAttemptStatus): string {
  const labels: Record<AuthLoginAttemptStatus, string> = {
    [AUTH_LOGIN_ATTEMPT_STATUS.PENDING]: 'Pending',
    [AUTH_LOGIN_ATTEMPT_STATUS.SUCCESS]: 'Success',
    [AUTH_LOGIN_ATTEMPT_STATUS.FAILED]: 'Failed',
    [AUTH_LOGIN_ATTEMPT_STATUS.BLOCKED]: 'Blocked',
    [AUTH_LOGIN_ATTEMPT_STATUS.LOCKED]: 'Locked',
    [AUTH_LOGIN_ATTEMPT_STATUS.TIMEOUT]: 'Timeout',
    [AUTH_LOGIN_ATTEMPT_STATUS.EXPIRED]: 'Expired',
    [AUTH_LOGIN_ATTEMPT_STATUS.REVOKED]: 'Revoked',
    [AUTH_LOGIN_ATTEMPT_STATUS.VERIFIED]: 'Verified',
    [AUTH_LOGIN_ATTEMPT_STATUS.UNVERIFIED]: 'Unverified',
    [AUTH_LOGIN_ATTEMPT_STATUS.VERIFICATION_PENDING]: 'Verification Pending',
    [AUTH_LOGIN_ATTEMPT_STATUS.VERIFICATION_FAILED]: 'Verification Failed',
    [AUTH_LOGIN_ATTEMPT_STATUS.SECURE]: 'Secure',
    [AUTH_LOGIN_ATTEMPT_STATUS.SUSPICIOUS]: 'Suspicious',
    [AUTH_LOGIN_ATTEMPT_STATUS.COMPROMISED]: 'Compromised',
    [AUTH_LOGIN_ATTEMPT_STATUS.INVESTIGATING]: 'Investigating',
    [AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_REQUIRED]: 'CAPTCHA Required',
    [AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_VERIFIED]: 'CAPTCHA Verified',
    [AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_FAILED]: 'CAPTCHA Failed',
    [AUTH_LOGIN_ATTEMPT_STATUS.MFA_REQUIRED]: 'MFA Required',
    [AUTH_LOGIN_ATTEMPT_STATUS.MFA_VERIFIED]: 'MFA Verified',
    [AUTH_LOGIN_ATTEMPT_STATUS.MFA_FAILED]: 'MFA Failed',
    [AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_REQUIRED]: '2FA Required',
    [AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_VERIFIED]: '2FA Verified',
    [AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_FAILED]: '2FA Failed',
  };

  return labels[status] || 'Unknown Status';
}

export function getAuthloginAttemptStatusColor(status: AuthLoginAttemptStatus): string {
  const colors: Record<AuthLoginAttemptStatus, string> = {
    [AUTH_LOGIN_ATTEMPT_STATUS.PENDING]: '#F59E0B',
    [AUTH_LOGIN_ATTEMPT_STATUS.SUCCESS]: '#10B981',
    [AUTH_LOGIN_ATTEMPT_STATUS.FAILED]: '#EF4444',
    [AUTH_LOGIN_ATTEMPT_STATUS.BLOCKED]: '#DC2626',
    [AUTH_LOGIN_ATTEMPT_STATUS.LOCKED]: '#991B1B',
    [AUTH_LOGIN_ATTEMPT_STATUS.TIMEOUT]: '#6B7280',
    [AUTH_LOGIN_ATTEMPT_STATUS.EXPIRED]: '#6B7280',
    [AUTH_LOGIN_ATTEMPT_STATUS.REVOKED]: '#6B7280',
    [AUTH_LOGIN_ATTEMPT_STATUS.VERIFIED]: '#10B981',
    [AUTH_LOGIN_ATTEMPT_STATUS.UNVERIFIED]: '#F59E0B',
    [AUTH_LOGIN_ATTEMPT_STATUS.VERIFICATION_PENDING]: '#F59E0B',
    [AUTH_LOGIN_ATTEMPT_STATUS.VERIFICATION_FAILED]: '#EF4444',
    [AUTH_LOGIN_ATTEMPT_STATUS.SECURE]: '#10B981',
    [AUTH_LOGIN_ATTEMPT_STATUS.SUSPICIOUS]: '#F59E0B',
    [AUTH_LOGIN_ATTEMPT_STATUS.COMPROMISED]: '#DC2626',
    [AUTH_LOGIN_ATTEMPT_STATUS.INVESTIGATING]: '#F97316',
    [AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_REQUIRED]: '#F59E0B',
    [AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_VERIFIED]: '#10B981',
    [AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_FAILED]: '#EF4444',
    [AUTH_LOGIN_ATTEMPT_STATUS.MFA_REQUIRED]: '#F59E0B',
    [AUTH_LOGIN_ATTEMPT_STATUS.MFA_VERIFIED]: '#10B981',
    [AUTH_LOGIN_ATTEMPT_STATUS.MFA_FAILED]: '#EF4444',
    [AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_REQUIRED]: '#F59E0B',
    [AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_VERIFIED]: '#10B981',
    [AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_FAILED]: '#EF4444',
  };

  return colors[status] || '#6B7280';
}

export function getAuthloginAttemptStatusPriority(status: AuthLoginAttemptStatus): number {
  const priorities: Record<AuthLoginAttemptStatus, number> = {
    [AUTH_LOGIN_ATTEMPT_STATUS.PENDING]: 5,
    [AUTH_LOGIN_ATTEMPT_STATUS.SUCCESS]: 10,
    [AUTH_LOGIN_ATTEMPT_STATUS.FAILED]: 3,
    [AUTH_LOGIN_ATTEMPT_STATUS.BLOCKED]: 2,
    [AUTH_LOGIN_ATTEMPT_STATUS.LOCKED]: 1,
    [AUTH_LOGIN_ATTEMPT_STATUS.TIMEOUT]: 4,
    [AUTH_LOGIN_ATTEMPT_STATUS.EXPIRED]: 4,
    [AUTH_LOGIN_ATTEMPT_STATUS.REVOKED]: 4,
    [AUTH_LOGIN_ATTEMPT_STATUS.VERIFIED]: 9,
    [AUTH_LOGIN_ATTEMPT_STATUS.UNVERIFIED]: 4,
    [AUTH_LOGIN_ATTEMPT_STATUS.VERIFICATION_PENDING]: 5,
    [AUTH_LOGIN_ATTEMPT_STATUS.VERIFICATION_FAILED]: 3,
    [AUTH_LOGIN_ATTEMPT_STATUS.SECURE]: 10,
    [AUTH_LOGIN_ATTEMPT_STATUS.SUSPICIOUS]: 6,
    [AUTH_LOGIN_ATTEMPT_STATUS.COMPROMISED]: 1,
    [AUTH_LOGIN_ATTEMPT_STATUS.INVESTIGATING]: 5,
    [AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_REQUIRED]: 5,
    [AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_VERIFIED]: 8,
    [AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_FAILED]: 3,
    [AUTH_LOGIN_ATTEMPT_STATUS.MFA_REQUIRED]: 5,
    [AUTH_LOGIN_ATTEMPT_STATUS.MFA_VERIFIED]: 8,
    [AUTH_LOGIN_ATTEMPT_STATUS.MFA_FAILED]: 3,
    [AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_REQUIRED]: 5,
    [AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_VERIFIED]: 8,
    [AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_FAILED]: 3,
  };

  return priorities[status] || 5;
}

export function getAuthloginAttemptStatusBadgeType(
  status: AuthLoginAttemptStatus
): 'success' | 'warning' | 'error' | 'info' | 'default' {
  const types: Record<
    AuthLoginAttemptStatus,
    'success' | 'warning' | 'error' | 'info' | 'default'
  > = {
    [AUTH_LOGIN_ATTEMPT_STATUS.PENDING]: 'warning',
    [AUTH_LOGIN_ATTEMPT_STATUS.SUCCESS]: 'success',
    [AUTH_LOGIN_ATTEMPT_STATUS.FAILED]: 'error',
    [AUTH_LOGIN_ATTEMPT_STATUS.BLOCKED]: 'error',
    [AUTH_LOGIN_ATTEMPT_STATUS.LOCKED]: 'error',
    [AUTH_LOGIN_ATTEMPT_STATUS.TIMEOUT]: 'default',
    [AUTH_LOGIN_ATTEMPT_STATUS.EXPIRED]: 'default',
    [AUTH_LOGIN_ATTEMPT_STATUS.REVOKED]: 'default',
    [AUTH_LOGIN_ATTEMPT_STATUS.VERIFIED]: 'success',
    [AUTH_LOGIN_ATTEMPT_STATUS.UNVERIFIED]: 'warning',
    [AUTH_LOGIN_ATTEMPT_STATUS.VERIFICATION_PENDING]: 'warning',
    [AUTH_LOGIN_ATTEMPT_STATUS.VERIFICATION_FAILED]: 'error',
    [AUTH_LOGIN_ATTEMPT_STATUS.SECURE]: 'success',
    [AUTH_LOGIN_ATTEMPT_STATUS.SUSPICIOUS]: 'warning',
    [AUTH_LOGIN_ATTEMPT_STATUS.COMPROMISED]: 'error',
    [AUTH_LOGIN_ATTEMPT_STATUS.INVESTIGATING]: 'info',
    [AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_REQUIRED]: 'warning',
    [AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_VERIFIED]: 'success',
    [AUTH_LOGIN_ATTEMPT_STATUS.CAPTCHA_FAILED]: 'error',
    [AUTH_LOGIN_ATTEMPT_STATUS.MFA_REQUIRED]: 'warning',
    [AUTH_LOGIN_ATTEMPT_STATUS.MFA_VERIFIED]: 'success',
    [AUTH_LOGIN_ATTEMPT_STATUS.MFA_FAILED]: 'error',
    [AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_REQUIRED]: 'warning',
    [AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_VERIFIED]: 'success',
    [AUTH_LOGIN_ATTEMPT_STATUS.TWO_FA_FAILED]: 'error',
  };

  return types[status] || 'default';
}
