packages:
  - "apps/*"
  - "apps/customer-dashboard/*"
  - "apps/admin-dashboard/*"
  - "apps/seller-dashboard/*"
  - "packages/*"
  - "packages/auth/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
