/**
 * Admin Type Constants (EXTENDS common/types)
 * @module shared-constants/admin/admin-type.constants
 */

import { TYPES } from '../common/types.constants';

export const ADMIN_TYPES = {
  // Base types from common
  ...TYPES,

  // Admin specific types
  ADMIN_SUPER: 'admin_super',
  ADMIN_SYSTEM: 'admin_system',
  ADMIN_BUSINESS: 'admin_business',
  ADMIN_TECHNICAL: 'admin_technical',
  ADMIN_SUPPORT: 'admin_support',
  ADMIN_FINANCE: 'admin_finance',
  ADMIN_OPERATIONS: 'admin_operations',
  ADMIN_HR: 'admin_hr',
  ADMIN_MARKETING: 'admin_marketing',
  ADMIN_CONTENT: 'admin_content',
  ADMIN_SECURITY: 'admin_security',
  ADMIN_COMPLIANCE: 'admin_compliance',
  ADMIN_AUDIT: 'admin_audit',
  ADMIN_DATABASE: 'admin_database',
  ADMIN_NETWORK: 'admin_network',
  ADMIN_DEVELOPER: 'admin_developer',
  ADMIN_ANALYST: 'admin_analyst',
  ADMIN_MANAGER: 'admin_manager',
  ADMIN_COORDINATOR: 'admin_coordinator',
  ADMIN_SPECIALIST: 'admin_specialist',
  ADMIN_CONSULTANT: 'admin_consultant',
  ADMIN_TRAINEE: 'admin_trainee',
  ADMIN_INTERN: 'admin_intern',
  ADMIN_VOLUNTEER: 'admin_volunteer',
  ADMIN_CONTRACT: 'admin_contract',
  ADMIN_PERMANENT: 'admin_permanent',
  ADMIN_TEMPORARY: 'admin_temporary',
  ADMIN_PART_TIME: 'admin_part_time',
  ADMIN_FULL_TIME: 'admin_full_time',
} as const;

export type AdminType = (typeof ADMIN_TYPES)[keyof typeof ADMIN_TYPES];

export const ADMIN_TYPE_LABELS: Record<AdminType, string> = {
  [ADMIN_TYPES.STRING]: 'String',
  [ADMIN_TYPES.NUMBER]: 'Number',
  [ADMIN_TYPES.BOOLEAN]: 'Boolean',
  [ADMIN_TYPES.NULL]: 'Null',
  [ADMIN_TYPES.UNDEFINED]: 'Undefined',
  [ADMIN_TYPES.SYMBOL]: 'Symbol',
  [ADMIN_TYPES.BIGINT]: 'BigInt',
  [ADMIN_TYPES.OBJECT]: 'Object',
  [ADMIN_TYPES.ARRAY]: 'Array',
  [ADMIN_TYPES.DATE]: 'Date',
  [ADMIN_TYPES.REGEXP]: 'RegExp',
  [ADMIN_TYPES.FUNCTION]: 'Function',
  [ADMIN_TYPES.CLASS]: 'Class',
  [ADMIN_TYPES.EMAIL]: 'Email',
  [ADMIN_TYPES.PHONE]: 'Phone',
  [ADMIN_TYPES.URL]: 'URL',
  [ADMIN_TYPES.UUID]: 'UUID',
  [ADMIN_TYPES.SLUG]: 'Slug',
  [ADMIN_TYPES.PASSWORD]: 'Password',
  [ADMIN_TYPES.TOKEN]: 'Token',
  [ADMIN_TYPES.ID]: 'ID',
  [ADMIN_TYPES.MONGODB_ID]: 'MongoDB ID',
  [ADMIN_TYPES.POSTGRES_ID]: 'PostgreSQL ID',
  [ADMIN_TYPES.MYSQL_ID]: 'MySQL ID',
  [ADMIN_TYPES.FILE]: 'File',
  [ADMIN_TYPES.IMAGE]: 'Image',
  [ADMIN_TYPES.VIDEO]: 'Video',
  [ADMIN_TYPES.AUDIO]: 'Audio',
  [ADMIN_TYPES.DOCUMENT]: 'Document',
  [ADMIN_TYPES.MONEY]: 'Money',
  [ADMIN_TYPES.CURRENCY]: 'Currency',
  [ADMIN_TYPES.PRICE]: 'Price',
  [ADMIN_TYPES.TIMESTAMP]: 'Timestamp',
  [ADMIN_TYPES.DATETIME]: 'DateTime',
  [ADMIN_TYPES.TIME]: 'Time',
  [ADMIN_TYPES.STATUS]: 'Status',
  [ADMIN_TYPES.ENUM]: 'Enum',
  [ADMIN_TYPES.UNION]: 'Union',
  [ADMIN_TYPES.ADDRESS]: 'Address',
  [ADMIN_TYPES.LOCATION]: 'Location',
  [ADMIN_TYPES.GEO_POINT]: 'GeoPoint',
  [ADMIN_TYPES.JSON]: 'JSON',
  [ADMIN_TYPES.ANY]: 'Any',
  [ADMIN_TYPES.UNKNOWN]: 'Unknown',
  [ADMIN_TYPES.NEVER]: 'Never',
  [ADMIN_TYPES.VOID]: 'Void',
  [ADMIN_TYPES.ADMIN_SUPER]: 'Super Admin',
  [ADMIN_TYPES.ADMIN_SYSTEM]: 'System Admin',
  [ADMIN_TYPES.ADMIN_BUSINESS]: 'Business Admin',
  [ADMIN_TYPES.ADMIN_TECHNICAL]: 'Technical Admin',
  [ADMIN_TYPES.ADMIN_SUPPORT]: 'Support Admin',
  [ADMIN_TYPES.ADMIN_FINANCE]: 'Finance Admin',
  [ADMIN_TYPES.ADMIN_OPERATIONS]: 'Operations Admin',
  [ADMIN_TYPES.ADMIN_HR]: 'HR Admin',
  [ADMIN_TYPES.ADMIN_MARKETING]: 'Marketing Admin',
  [ADMIN_TYPES.ADMIN_CONTENT]: 'Content Admin',
  [ADMIN_TYPES.ADMIN_SECURITY]: 'Security Admin',
  [ADMIN_TYPES.ADMIN_COMPLIANCE]: 'Compliance Admin',
  [ADMIN_TYPES.ADMIN_AUDIT]: 'Audit Admin',
  [ADMIN_TYPES.ADMIN_DATABASE]: 'Database Admin',
  [ADMIN_TYPES.ADMIN_NETWORK]: 'Network Admin',
  [ADMIN_TYPES.ADMIN_DEVELOPER]: 'Developer Admin',
  [ADMIN_TYPES.ADMIN_ANALYST]: 'Analyst Admin',
  [ADMIN_TYPES.ADMIN_MANAGER]: 'Manager Admin',
  [ADMIN_TYPES.ADMIN_COORDINATOR]: 'Coordinator Admin',
  [ADMIN_TYPES.ADMIN_SPECIALIST]: 'Specialist Admin',
  [ADMIN_TYPES.ADMIN_CONSULTANT]: 'Consultant Admin',
  [ADMIN_TYPES.ADMIN_TRAINEE]: 'Trainee Admin',
  [ADMIN_TYPES.ADMIN_INTERN]: 'Intern Admin',
  [ADMIN_TYPES.ADMIN_VOLUNTEER]: 'Volunteer Admin',
  [ADMIN_TYPES.ADMIN_CONTRACT]: 'Contract Admin',
  [ADMIN_TYPES.ADMIN_PERMANENT]: 'Permanent Admin',
  [ADMIN_TYPES.ADMIN_TEMPORARY]: 'Temporary Admin',
  [ADMIN_TYPES.ADMIN_PART_TIME]: 'Part-time Admin',
  [ADMIN_TYPES.ADMIN_FULL_TIME]: 'Full-time Admin',
};

export const ADMIN_TYPE_GROUPS = {
  SUPER_ADMIN: [ADMIN_TYPES.ADMIN_SUPER] as const,

  SYSTEM_ADMIN: [
    ADMIN_TYPES.ADMIN_SYSTEM,
    ADMIN_TYPES.ADMIN_SECURITY,
    ADMIN_TYPES.ADMIN_COMPLIANCE,
    ADMIN_TYPES.ADMIN_AUDIT,
    ADMIN_TYPES.ADMIN_DATABASE,
    ADMIN_TYPES.ADMIN_NETWORK,
  ] as const,

  BUSINESS_ADMIN: [
    ADMIN_TYPES.ADMIN_BUSINESS,
    ADMIN_TYPES.ADMIN_FINANCE,
    ADMIN_TYPES.ADMIN_OPERATIONS,
    ADMIN_TYPES.ADMIN_HR,
    ADMIN_TYPES.ADMIN_MARKETING,
    ADMIN_TYPES.ADMIN_CONTENT,
  ] as const,

  TECHNICAL_ADMIN: [
    ADMIN_TYPES.ADMIN_TECHNICAL,
    ADMIN_TYPES.ADMIN_DEVELOPER,
    ADMIN_TYPES.ADMIN_ANALYST,
  ] as const,

  SUPPORT_ADMIN: [
    ADMIN_TYPES.ADMIN_SUPPORT,
    ADMIN_TYPES.ADMIN_COORDINATOR,
    ADMIN_TYPES.ADMIN_SPECIALIST,
    ADMIN_TYPES.ADMIN_CONSULTANT,
  ] as const,

  EMPLOYMENT_TYPES: [
    ADMIN_TYPES.ADMIN_PERMANENT,
    ADMIN_TYPES.ADMIN_TEMPORARY,
    ADMIN_TYPES.ADMIN_CONTRACT,
    ADMIN_TYPES.ADMIN_PART_TIME,
    ADMIN_TYPES.ADMIN_FULL_TIME,
    ADMIN_TYPES.ADMIN_TRAINEE,
    ADMIN_TYPES.ADMIN_INTERN,
    ADMIN_TYPES.ADMIN_VOLUNTEER,
  ] as const,
} as const;
