/**
 * Admin Permission Constants
 * অ্যাডমিন পারমিশন সম্পর্কিত কনস্ট্যান্টস
 */

import { PERMISSIONS } from '../common';
import { ADMIN_ROLES } from './admin-role.constants';

export const ADMIN_PERMISSIONS = {
  ...PERMISSIONS,

  // Admin management
  ADMIN_CREATE: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.SYSTEM_ADMIN],
  ADMIN_READ: [
    ADMIN_ROLES.SUPER_ADMIN,
    ADMIN_ROLES.SYSTEM_ADMIN,
    ADMIN_ROLES.ADMIN,
    ADMIN_ROLES.MANAGER,
  ],
  ADMIN_UPDATE: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.SYSTEM_ADMIN, ADMIN_ROLES.ADMIN],
  ADMIN_DELETE: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.SYSTEM_ADMIN],
  ADMIN_SUSPEND: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.SYSTEM_ADMIN, ADMIN_ROLES.ADMIN],
  ADMIN_UNLOCK: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.SYSTEM_ADMIN, ADMIN_ROLES.ADMIN],
  ADMIN_ROLE_ASSIGN: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.SYSTEM_ADMIN],
  ADMIN_ROLE_REVOKE: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.SYSTEM_ADMIN],

  // System management
  SYSTEM_READ: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.SYSTEM_ADMIN, ADMIN_ROLES.ADMIN],
  SYSTEM_UPDATE: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.SYSTEM_ADMIN],
  SYSTEM_DELETE: [ADMIN_ROLES.SUPER_ADMIN],
  SYSTEM_CONFIG: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.SYSTEM_ADMIN],

  // Content management
  CONTENT_CREATE: [
    ADMIN_ROLES.SUPER_ADMIN,
    ADMIN_ROLES.ADMIN,
    ADMIN_ROLES.CONTENT_ADMIN,
    ADMIN_ROLES.MODERATOR,
  ],
  CONTENT_READ: [
    ADMIN_ROLES.SUPER_ADMIN,
    ADMIN_ROLES.ADMIN,
    ADMIN_ROLES.CONTENT_ADMIN,
    ADMIN_ROLES.MODERATOR,
    ADMIN_ROLES.SUPPORT,
  ],
  CONTENT_UPDATE: [
    ADMIN_ROLES.SUPER_ADMIN,
    ADMIN_ROLES.ADMIN,
    ADMIN_ROLES.CONTENT_ADMIN,
    ADMIN_ROLES.MODERATOR,
  ],
  CONTENT_DELETE: [
    ADMIN_ROLES.SUPER_ADMIN,
    ADMIN_ROLES.ADMIN,
    ADMIN_ROLES.CONTENT_ADMIN,
    ADMIN_ROLES.MODERATOR,
  ],
  CONTENT_APPROVE: [
    ADMIN_ROLES.SUPER_ADMIN,
    ADMIN_ROLES.ADMIN,
    ADMIN_ROLES.CONTENT_ADMIN,
    ADMIN_ROLES.MODERATOR,
  ],

  // Finance management
  FINANCE_READ: [
    ADMIN_ROLES.SUPER_ADMIN,
    ADMIN_ROLES.ADMIN,
    ADMIN_ROLES.FINANCE_ADMIN,
    ADMIN_ROLES.REPORT_ADMIN,
  ],
  FINANCE_UPDATE: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.ADMIN, ADMIN_ROLES.FINANCE_ADMIN],
  FINANCE_DELETE: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.ADMIN],
  FINANCE_APPROVE: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.ADMIN, ADMIN_ROLES.FINANCE_ADMIN],

  // Report management
  REPORT_CREATE: [
    ADMIN_ROLES.SUPER_ADMIN,
    ADMIN_ROLES.ADMIN,
    ADMIN_ROLES.REPORT_ADMIN,
    ADMIN_ROLES.MANAGER,
  ],
  REPORT_READ: [
    ADMIN_ROLES.SUPER_ADMIN,
    ADMIN_ROLES.ADMIN,
    ADMIN_ROLES.REPORT_ADMIN,
    ADMIN_ROLES.MANAGER,
    ADMIN_ROLES.SUPPORT,
  ],
  REPORT_UPDATE: [
    ADMIN_ROLES.SUPER_ADMIN,
    ADMIN_ROLES.ADMIN,
    ADMIN_ROLES.REPORT_ADMIN,
    ADMIN_ROLES.MANAGER,
  ],
  REPORT_DELETE: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.ADMIN],

  // Settings management
  SETTINGS_READ: [
    ADMIN_ROLES.SUPER_ADMIN,
    ADMIN_ROLES.SYSTEM_ADMIN,
    ADMIN_ROLES.ADMIN,
    ADMIN_ROLES.SETTINGS_ADMIN,
  ],
  SETTINGS_UPDATE: [
    ADMIN_ROLES.SUPER_ADMIN,
    ADMIN_ROLES.SYSTEM_ADMIN,
    ADMIN_ROLES.ADMIN,
    ADMIN_ROLES.SETTINGS_ADMIN,
  ],
  SETTINGS_RESET: [ADMIN_ROLES.SUPER_ADMIN, ADMIN_ROLES.SYSTEM_ADMIN],
} as const;

export type AdminPermission = keyof typeof ADMIN_PERMISSIONS;
