/**
 * অ্যাডমিন অ্যাক্টিভিটির টাইপ সম্পর্কিত কনস্ট্যান্টসমূহ
 */

// অ্যাক্টিভিটি টাইপ
export const ACTIVITY_TYPES = {
  LOGIN: 'login',
  LOGOUT: 'logout',
  PROFILE_UPDATE: 'profile_update',
  ROLE_CHANGE: 'role_change',
  PERMISSION_CHANGE: 'permission_change',
  SETTINGS_UPDATE: 'settings_update',
  REPORT_GENERATED: 'report_generated',
  AUDIT_VIEW: 'audit_view',
  TEAM_CHANGE: 'team_change',
  DEPARTMENT_CHANGE: 'department_change',
  PASSWORD_CHANGE: 'password_change',
  TWO_FACTOR_ENABLE: 'two_factor_enable',
  TWO_FACTOR_DISABLE: 'two_factor_disable',
  API_ACCESS: 'api_access',
  DATA_EXPORT: 'data_export',
  DATA_IMPORT: 'data_import',
  USER_CREATE: 'user_create',
  USER_UPDATE: 'user_update',
  USER_DELETE: 'user_delete',
  SYSTEM_BACKUP: 'system_backup',
  SYSTEM_RESTORE: 'system_restore',
} as const;

// টাইপের আইকন
export const ACTIVITY_TYPE_ICONS = {
  LOGIN: '🔑',
  LOGOUT: '🚪',
  PROFILE_UPDATE: '👤',
  ROLE_CHANGE: '🎭',
  PERMISSION_CHANGE: '🔐',
  SETTINGS_UPDATE: '⚙️',
  REPORT_GENERATED: '📊',
  AUDIT_VIEW: '📋',
  TEAM_CHANGE: '👥',
  DEPARTMENT_CHANGE: '🏢',
  PASSWORD_CHANGE: '🔒',
  TWO_FACTOR_ENABLE: '✅',
  TWO_FACTOR_DISABLE: '❌',
  API_ACCESS: '🌐',
  DATA_EXPORT: '📤',
  DATA_IMPORT: '📥',
  USER_CREATE: '➕',
  USER_UPDATE: '✏️',
  USER_DELETE: '🗑️',
  SYSTEM_BACKUP: '💾',
  SYSTEM_RESTORE: '🔄',
} as const;

// টাইপের কালার কোড
export const ACTIVITY_TYPE_COLORS = {
  LOGIN: '#22C55E',
  LOGOUT: '#94A3B8',
  PROFILE_UPDATE: '#3B82F6',
  ROLE_CHANGE: '#8B5CF6',
  PERMISSION_CHANGE: '#DC2626',
  SETTINGS_UPDATE: '#F59E0B',
  REPORT_GENERATED: '#EC4899',
  AUDIT_VIEW: '#6366F1',
  TEAM_CHANGE: '#14B8A6',
  DEPARTMENT_CHANGE: '#F472B6',
  PASSWORD_CHANGE: '#F97316',
  TWO_FACTOR_ENABLE: '#22C55E',
  TWO_FACTOR_DISABLE: '#EF4444',
  API_ACCESS: '#06B6D4',
  DATA_EXPORT: '#8B5CF6',
  DATA_IMPORT: '#EC4899',
  USER_CREATE: '#22C55E',
  USER_UPDATE: '#3B82F6',
  USER_DELETE: '#EF4444',
  SYSTEM_BACKUP: '#F59E0B',
  SYSTEM_RESTORE: '#8B5CF6',
} as const;

// টাইপের লগ লেভেল
export const ACTIVITY_TYPE_LOG_LEVEL = {
  LOGIN: 'info',
  LOGOUT: 'info',
  PROFILE_UPDATE: 'info',
  ROLE_CHANGE: 'warning',
  PERMISSION_CHANGE: 'warning',
  SETTINGS_UPDATE: 'warning',
  REPORT_GENERATED: 'info',
  AUDIT_VIEW: 'info',
  TEAM_CHANGE: 'info',
  DEPARTMENT_CHANGE: 'info',
  PASSWORD_CHANGE: 'warning',
  TWO_FACTOR_ENABLE: 'info',
  TWO_FACTOR_DISABLE: 'warning',
  API_ACCESS: 'debug',
  DATA_EXPORT: 'info',
  DATA_IMPORT: 'warning',
  USER_CREATE: 'info',
  USER_UPDATE: 'info',
  USER_DELETE: 'critical',
  SYSTEM_BACKUP: 'info',
  SYSTEM_RESTORE: 'critical',
} as const;

// টাইপের ডেসক্রিপশন
export const ACTIVITY_TYPE_DESCRIPTIONS = {
  LOGIN: 'User logged into the system',
  LOGOUT: 'User logged out of the system',
  PROFILE_UPDATE: 'User updated their profile information',
  ROLE_CHANGE: 'User role was changed',
  PERMISSION_CHANGE: 'User permissions were modified',
  SETTINGS_UPDATE: 'System settings were updated',
  REPORT_GENERATED: 'A report was generated',
  AUDIT_VIEW: 'Audit logs were viewed',
  TEAM_CHANGE: 'Team membership was modified',
  DEPARTMENT_CHANGE: 'Department assignment was changed',
  PASSWORD_CHANGE: 'User password was changed',
  TWO_FACTOR_ENABLE: 'Two-factor authentication was enabled',
  TWO_FACTOR_DISABLE: 'Two-factor authentication was disabled',
  API_ACCESS: 'API access was performed',
  DATA_EXPORT: 'Data was exported from the system',
  DATA_IMPORT: 'Data was imported into the system',
  USER_CREATE: 'A new user was created',
  USER_UPDATE: 'User information was updated',
  USER_DELETE: 'A user was deleted from the system',
  SYSTEM_BACKUP: 'System backup was performed',
  SYSTEM_RESTORE: 'System was restored from backup',
} as const;

// টাইপের প্রায়োরিটি (১ = সর্বোচ্চ)
export const ACTIVITY_TYPE_PRIORITY = {
  LOGIN: 3,
  LOGOUT: 3,
  PROFILE_UPDATE: 4,
  ROLE_CHANGE: 2,
  PERMISSION_CHANGE: 1,
  SETTINGS_UPDATE: 1,
  REPORT_GENERATED: 4,
  AUDIT_VIEW: 3,
  TEAM_CHANGE: 3,
  DEPARTMENT_CHANGE: 3,
  PASSWORD_CHANGE: 2,
  TWO_FACTOR_ENABLE: 2,
  TWO_FACTOR_DISABLE: 2,
  API_ACCESS: 4,
  DATA_EXPORT: 2,
  DATA_IMPORT: 1,
  USER_CREATE: 2,
  USER_UPDATE: 2,
  USER_DELETE: 1,
  SYSTEM_BACKUP: 1,
  SYSTEM_RESTORE: 1,
} as const;

// টাইপ গ্রুপ
export const ACTIVITY_TYPE_GROUPS = {
  AUTHENTICATION: ['login', 'logout'],
  PROFILE: ['profile_update', 'password_change', 'two_factor_enable', 'two_factor_disable'],
  PERMISSION: ['role_change', 'permission_change'],
  SYSTEM: ['settings_update', 'system_backup', 'system_restore'],
  DATA: ['data_export', 'data_import', 'report_generated'],
  USER_MANAGEMENT: ['user_create', 'user_update', 'user_delete'],
  ORGANIZATION: ['team_change', 'department_change'],
  MONITORING: ['audit_view', 'api_access'],
} as const;

// টাইপের লেবেল (বাংলা)
export const ACTIVITY_TYPE_LABELS_BN = {
  LOGIN: 'লগইন',
  LOGOUT: 'লগআউট',
  PROFILE_UPDATE: 'প্রোফাইল আপডেট',
  ROLE_CHANGE: 'রোল পরিবর্তন',
  PERMISSION_CHANGE: 'পারমিশন পরিবর্তন',
  SETTINGS_UPDATE: 'সেটিংস আপডেট',
  REPORT_GENERATED: 'রিপোর্ট তৈরি',
  AUDIT_VIEW: 'অডিট ভিউ',
  TEAM_CHANGE: 'টিম পরিবর্তন',
  DEPARTMENT_CHANGE: 'ডিপার্টমেন্ট পরিবর্তন',
  PASSWORD_CHANGE: 'পাসওয়ার্ড পরিবর্তন',
  TWO_FACTOR_ENABLE: 'টু-ফ্যাক্টর সক্রিয়',
  TWO_FACTOR_DISABLE: 'টু-ফ্যাক্টর নিষ্ক্রিয়',
  API_ACCESS: 'এপিআই অ্যাক্সেস',
  DATA_EXPORT: 'ডেটা এক্সপোর্ট',
  DATA_IMPORT: 'ডেটা ইম্পোর্ট',
  USER_CREATE: 'ইউজার তৈরি',
  USER_UPDATE: 'ইউজার আপডেট',
  USER_DELETE: 'ইউজার মুছে ফেলা',
  SYSTEM_BACKUP: 'সিস্টেম ব্যাকআপ',
  SYSTEM_RESTORE: 'সিস্টেম রিস্টোর',
} as const;

// টাইপের জন্য ইমোজি
export const ACTIVITY_TYPE_EMOJIS = {
  LOGIN: '🔐',
  LOGOUT: '🚶',
  PROFILE_UPDATE: '📝',
  ROLE_CHANGE: '🔄',
  PERMISSION_CHANGE: '🔓',
  SETTINGS_UPDATE: '🛠️',
  REPORT_GENERATED: '📈',
  AUDIT_VIEW: '👁️',
  TEAM_CHANGE: '🤝',
  DEPARTMENT_CHANGE: '🏛️',
  PASSWORD_CHANGE: '🔑',
  TWO_FACTOR_ENABLE: '🛡️',
  TWO_FACTOR_DISABLE: '⚠️',
  API_ACCESS: '🌍',
  DATA_EXPORT: '📤',
  DATA_IMPORT: '📥',
  USER_CREATE: '👤',
  USER_UPDATE: '✍️',
  USER_DELETE: '🗑️',
  SYSTEM_BACKUP: '💿',
  SYSTEM_RESTORE: '⏪',
} as const;
