/**
 * Admin Department Constants
 * Department definitions for admin categorization
 */

/**
 * Admin departments
 */
export const ADMIN_DEPARTMENT = {
  // Core departments
  MANAGEMENT: 'management',
  OPERATIONS: 'operations',
  ADMINISTRATION: 'administration',
  EXECUTIVE: 'executive',

  // Technical departments
  TECHNICAL: 'technical',
  DEVELOPMENT: 'development',
  ENGINEERING: 'engineering',
  IT: 'information_technology',
  DEVOPS: 'devops',
  SECURITY: 'security',

  // Business departments
  BUSINESS: 'business',
  STRATEGY: 'strategy',
  PLANNING: 'planning',
  INNOVATION: 'innovation',

  // Creative departments
  DESIGN: 'design',
  UX: 'user_experience',
  UI: 'user_interface',
  CREATIVE: 'creative',

  // Marketing departments
  MARKETING: 'marketing',
  DIGITAL_MARKETING: 'digital_marketing',
  SOCIAL_MEDIA: 'social_media',
  CONTENT: 'content',
  BRAND: 'brand',

  // Sales departments
  SALES: 'sales',
  RETAIL: 'retail',
  WHOLESALE: 'wholesale',
  B2B: 'b2b',
  B2C: 'b2c',

  // Support departments
  SUPPORT: 'support',
  CUSTOMER_SERVICE: 'customer_service',
  HELP_DESK: 'help_desk',
  TECHNICAL_SUPPORT: 'technical_support',

  // Finance departments
  FINANCE: 'finance',
  ACCOUNTING: 'accounting',
  BUDGET: 'budget',
  TAX: 'tax',
  AUDIT: 'audit',
  COMPLIANCE: 'compliance',

  // HR departments
  HR: 'human_resources',
  RECRUITMENT: 'recruitment',
  TRAINING: 'training',
  DEVELOPMENT_HR: 'development_hr',

  // Operations departments
  LOGISTICS: 'logistics',
  SUPPLY_CHAIN: 'supply_chain',
  PROCUREMENT: 'procurement',
  WAREHOUSE: 'warehouse',
  INVENTORY: 'inventory',

  // Product departments
  PRODUCT: 'product',
  PRODUCT_DEVELOPMENT: 'product_development',
  PRODUCT_MANAGEMENT: 'product_management',
  QUALITY_ASSURANCE: 'quality_assurance',

  // Analytics departments
  ANALYTICS: 'analytics',
  DATA_SCIENCE: 'data_science',
  BUSINESS_INTELLIGENCE: 'business_intelligence',
  RESEARCH: 'research',

  // Legal departments
  LEGAL: 'legal',
  LEGAL_COMPLIANCE: 'legal_compliance',
  REGULATORY: 'regulatory',

  // Special departments
  SPECIAL_PROJECTS: 'special_projects',
  CRISIS_MANAGEMENT: 'crisis_management',
  CHANGE_MANAGEMENT: 'change_management',
  CONTINUITY: 'business_continuity',
} as const;

export type AdminDepartment = (typeof ADMIN_DEPARTMENT)[keyof typeof ADMIN_DEPARTMENT];

/**
 * Department categories
 */
export const DEPARTMENT_CATEGORY = {
  CORE: 'core',
  TECHNICAL: 'technical',
  BUSINESS: 'business',
  CREATIVE: 'creative',
  MARKETING: 'marketing',
  SALES: 'sales',
  SUPPORT: 'support',
  FINANCE: 'finance',
  HR: 'hr',
  OPERATIONS: 'operations',
  PRODUCT: 'product',
  ANALYTICS: 'analytics',
  LEGAL: 'legal',
  SPECIAL: 'special',
} as const;

export type DepartmentCategory = (typeof DEPARTMENT_CATEGORY)[keyof typeof DEPARTMENT_CATEGORY];

/**
 * Department category mapping with proper typing
 */
export const DEPARTMENT_CATEGORY_MAP: Record<AdminDepartment, DepartmentCategory> = {
  [ADMIN_DEPARTMENT.MANAGEMENT]: DEPARTMENT_CATEGORY.CORE,
  [ADMIN_DEPARTMENT.OPERATIONS]: DEPARTMENT_CATEGORY.OPERATIONS,
  [ADMIN_DEPARTMENT.ADMINISTRATION]: DEPARTMENT_CATEGORY.CORE,
  [ADMIN_DEPARTMENT.EXECUTIVE]: DEPARTMENT_CATEGORY.CORE,

  [ADMIN_DEPARTMENT.TECHNICAL]: DEPARTMENT_CATEGORY.TECHNICAL,
  [ADMIN_DEPARTMENT.DEVELOPMENT]: DEPARTMENT_CATEGORY.TECHNICAL,
  [ADMIN_DEPARTMENT.ENGINEERING]: DEPARTMENT_CATEGORY.TECHNICAL,
  [ADMIN_DEPARTMENT.IT]: DEPARTMENT_CATEGORY.TECHNICAL,
  [ADMIN_DEPARTMENT.DEVOPS]: DEPARTMENT_CATEGORY.TECHNICAL,
  [ADMIN_DEPARTMENT.SECURITY]: DEPARTMENT_CATEGORY.TECHNICAL,

  [ADMIN_DEPARTMENT.BUSINESS]: DEPARTMENT_CATEGORY.BUSINESS,
  [ADMIN_DEPARTMENT.STRATEGY]: DEPARTMENT_CATEGORY.BUSINESS,
  [ADMIN_DEPARTMENT.PLANNING]: DEPARTMENT_CATEGORY.BUSINESS,
  [ADMIN_DEPARTMENT.INNOVATION]: DEPARTMENT_CATEGORY.BUSINESS,

  [ADMIN_DEPARTMENT.DESIGN]: DEPARTMENT_CATEGORY.CREATIVE,
  [ADMIN_DEPARTMENT.UX]: DEPARTMENT_CATEGORY.CREATIVE,
  [ADMIN_DEPARTMENT.UI]: DEPARTMENT_CATEGORY.CREATIVE,
  [ADMIN_DEPARTMENT.CREATIVE]: DEPARTMENT_CATEGORY.CREATIVE,

  [ADMIN_DEPARTMENT.MARKETING]: DEPARTMENT_CATEGORY.MARKETING,
  [ADMIN_DEPARTMENT.DIGITAL_MARKETING]: DEPARTMENT_CATEGORY.MARKETING,
  [ADMIN_DEPARTMENT.SOCIAL_MEDIA]: DEPARTMENT_CATEGORY.MARKETING,
  [ADMIN_DEPARTMENT.CONTENT]: DEPARTMENT_CATEGORY.MARKETING,
  [ADMIN_DEPARTMENT.BRAND]: DEPARTMENT_CATEGORY.MARKETING,

  [ADMIN_DEPARTMENT.SALES]: DEPARTMENT_CATEGORY.SALES,
  [ADMIN_DEPARTMENT.RETAIL]: DEPARTMENT_CATEGORY.SALES,
  [ADMIN_DEPARTMENT.WHOLESALE]: DEPARTMENT_CATEGORY.SALES,
  [ADMIN_DEPARTMENT.B2B]: DEPARTMENT_CATEGORY.SALES,
  [ADMIN_DEPARTMENT.B2C]: DEPARTMENT_CATEGORY.SALES,

  [ADMIN_DEPARTMENT.SUPPORT]: DEPARTMENT_CATEGORY.SUPPORT,
  [ADMIN_DEPARTMENT.CUSTOMER_SERVICE]: DEPARTMENT_CATEGORY.SUPPORT,
  [ADMIN_DEPARTMENT.HELP_DESK]: DEPARTMENT_CATEGORY.SUPPORT,
  [ADMIN_DEPARTMENT.TECHNICAL_SUPPORT]: DEPARTMENT_CATEGORY.SUPPORT,

  [ADMIN_DEPARTMENT.FINANCE]: DEPARTMENT_CATEGORY.FINANCE,
  [ADMIN_DEPARTMENT.ACCOUNTING]: DEPARTMENT_CATEGORY.FINANCE,
  [ADMIN_DEPARTMENT.BUDGET]: DEPARTMENT_CATEGORY.FINANCE,
  [ADMIN_DEPARTMENT.TAX]: DEPARTMENT_CATEGORY.FINANCE,
  [ADMIN_DEPARTMENT.AUDIT]: DEPARTMENT_CATEGORY.FINANCE,
  [ADMIN_DEPARTMENT.COMPLIANCE]: DEPARTMENT_CATEGORY.LEGAL,

  [ADMIN_DEPARTMENT.HR]: DEPARTMENT_CATEGORY.HR,
  [ADMIN_DEPARTMENT.RECRUITMENT]: DEPARTMENT_CATEGORY.HR,
  [ADMIN_DEPARTMENT.TRAINING]: DEPARTMENT_CATEGORY.HR,
  [ADMIN_DEPARTMENT.DEVELOPMENT_HR]: DEPARTMENT_CATEGORY.HR,

  [ADMIN_DEPARTMENT.LOGISTICS]: DEPARTMENT_CATEGORY.OPERATIONS,
  [ADMIN_DEPARTMENT.SUPPLY_CHAIN]: DEPARTMENT_CATEGORY.OPERATIONS,
  [ADMIN_DEPARTMENT.PROCUREMENT]: DEPARTMENT_CATEGORY.OPERATIONS,
  [ADMIN_DEPARTMENT.WAREHOUSE]: DEPARTMENT_CATEGORY.OPERATIONS,
  [ADMIN_DEPARTMENT.INVENTORY]: DEPARTMENT_CATEGORY.OPERATIONS,

  [ADMIN_DEPARTMENT.PRODUCT]: DEPARTMENT_CATEGORY.PRODUCT,
  [ADMIN_DEPARTMENT.PRODUCT_DEVELOPMENT]: DEPARTMENT_CATEGORY.PRODUCT,
  [ADMIN_DEPARTMENT.PRODUCT_MANAGEMENT]: DEPARTMENT_CATEGORY.PRODUCT,
  [ADMIN_DEPARTMENT.QUALITY_ASSURANCE]: DEPARTMENT_CATEGORY.PRODUCT,

  [ADMIN_DEPARTMENT.ANALYTICS]: DEPARTMENT_CATEGORY.ANALYTICS,
  [ADMIN_DEPARTMENT.DATA_SCIENCE]: DEPARTMENT_CATEGORY.ANALYTICS,
  [ADMIN_DEPARTMENT.BUSINESS_INTELLIGENCE]: DEPARTMENT_CATEGORY.ANALYTICS,
  [ADMIN_DEPARTMENT.RESEARCH]: DEPARTMENT_CATEGORY.ANALYTICS,

  [ADMIN_DEPARTMENT.LEGAL]: DEPARTMENT_CATEGORY.LEGAL,
  [ADMIN_DEPARTMENT.LEGAL_COMPLIANCE]: DEPARTMENT_CATEGORY.LEGAL,
  [ADMIN_DEPARTMENT.REGULATORY]: DEPARTMENT_CATEGORY.LEGAL,

  [ADMIN_DEPARTMENT.SPECIAL_PROJECTS]: DEPARTMENT_CATEGORY.SPECIAL,
  [ADMIN_DEPARTMENT.CRISIS_MANAGEMENT]: DEPARTMENT_CATEGORY.SPECIAL,
  [ADMIN_DEPARTMENT.CHANGE_MANAGEMENT]: DEPARTMENT_CATEGORY.SPECIAL,
  [ADMIN_DEPARTMENT.CONTINUITY]: DEPARTMENT_CATEGORY.SPECIAL,
};

/**
 * Department labels
 */
export const ADMIN_DEPARTMENT_LABEL: Record<AdminDepartment, string> = {
  [ADMIN_DEPARTMENT.MANAGEMENT]: 'Management',
  [ADMIN_DEPARTMENT.OPERATIONS]: 'Operations',
  [ADMIN_DEPARTMENT.ADMINISTRATION]: 'Administration',
  [ADMIN_DEPARTMENT.EXECUTIVE]: 'Executive',

  [ADMIN_DEPARTMENT.TECHNICAL]: 'Technical',
  [ADMIN_DEPARTMENT.DEVELOPMENT]: 'Development',
  [ADMIN_DEPARTMENT.ENGINEERING]: 'Engineering',
  [ADMIN_DEPARTMENT.IT]: 'Information Technology',
  [ADMIN_DEPARTMENT.DEVOPS]: 'DevOps',
  [ADMIN_DEPARTMENT.SECURITY]: 'Security',

  [ADMIN_DEPARTMENT.BUSINESS]: 'Business',
  [ADMIN_DEPARTMENT.STRATEGY]: 'Strategy',
  [ADMIN_DEPARTMENT.PLANNING]: 'Planning',
  [ADMIN_DEPARTMENT.INNOVATION]: 'Innovation',

  [ADMIN_DEPARTMENT.DESIGN]: 'Design',
  [ADMIN_DEPARTMENT.UX]: 'User Experience',
  [ADMIN_DEPARTMENT.UI]: 'User Interface',
  [ADMIN_DEPARTMENT.CREATIVE]: 'Creative',

  [ADMIN_DEPARTMENT.MARKETING]: 'Marketing',
  [ADMIN_DEPARTMENT.DIGITAL_MARKETING]: 'Digital Marketing',
  [ADMIN_DEPARTMENT.SOCIAL_MEDIA]: 'Social Media',
  [ADMIN_DEPARTMENT.CONTENT]: 'Content',
  [ADMIN_DEPARTMENT.BRAND]: 'Brand',

  [ADMIN_DEPARTMENT.SALES]: 'Sales',
  [ADMIN_DEPARTMENT.RETAIL]: 'Retail',
  [ADMIN_DEPARTMENT.WHOLESALE]: 'Wholesale',
  [ADMIN_DEPARTMENT.B2B]: 'B2B',
  [ADMIN_DEPARTMENT.B2C]: 'B2C',

  [ADMIN_DEPARTMENT.SUPPORT]: 'Support',
  [ADMIN_DEPARTMENT.CUSTOMER_SERVICE]: 'Customer Service',
  [ADMIN_DEPARTMENT.HELP_DESK]: 'Help Desk',
  [ADMIN_DEPARTMENT.TECHNICAL_SUPPORT]: 'Technical Support',

  [ADMIN_DEPARTMENT.FINANCE]: 'Finance',
  [ADMIN_DEPARTMENT.ACCOUNTING]: 'Accounting',
  [ADMIN_DEPARTMENT.BUDGET]: 'Budget',
  [ADMIN_DEPARTMENT.TAX]: 'Tax',
  [ADMIN_DEPARTMENT.AUDIT]: 'Audit',
  [ADMIN_DEPARTMENT.COMPLIANCE]: 'Compliance',

  [ADMIN_DEPARTMENT.HR]: 'Human Resources',
  [ADMIN_DEPARTMENT.RECRUITMENT]: 'Recruitment',
  [ADMIN_DEPARTMENT.TRAINING]: 'Training',
  [ADMIN_DEPARTMENT.DEVELOPMENT_HR]: 'HR Development',

  [ADMIN_DEPARTMENT.LOGISTICS]: 'Logistics',
  [ADMIN_DEPARTMENT.SUPPLY_CHAIN]: 'Supply Chain',
  [ADMIN_DEPARTMENT.PROCUREMENT]: 'Procurement',
  [ADMIN_DEPARTMENT.WAREHOUSE]: 'Warehouse',
  [ADMIN_DEPARTMENT.INVENTORY]: 'Inventory',

  [ADMIN_DEPARTMENT.PRODUCT]: 'Product',
  [ADMIN_DEPARTMENT.PRODUCT_DEVELOPMENT]: 'Product Development',
  [ADMIN_DEPARTMENT.PRODUCT_MANAGEMENT]: 'Product Management',
  [ADMIN_DEPARTMENT.QUALITY_ASSURANCE]: 'Quality Assurance',

  [ADMIN_DEPARTMENT.ANALYTICS]: 'Analytics',
  [ADMIN_DEPARTMENT.DATA_SCIENCE]: 'Data Science',
  [ADMIN_DEPARTMENT.BUSINESS_INTELLIGENCE]: 'Business Intelligence',
  [ADMIN_DEPARTMENT.RESEARCH]: 'Research',

  [ADMIN_DEPARTMENT.LEGAL]: 'Legal',
  [ADMIN_DEPARTMENT.LEGAL_COMPLIANCE]: 'Legal Compliance',
  [ADMIN_DEPARTMENT.REGULATORY]: 'Regulatory',

  [ADMIN_DEPARTMENT.SPECIAL_PROJECTS]: 'Special Projects',
  [ADMIN_DEPARTMENT.CRISIS_MANAGEMENT]: 'Crisis Management',
  [ADMIN_DEPARTMENT.CHANGE_MANAGEMENT]: 'Change Management',
  [ADMIN_DEPARTMENT.CONTINUITY]: 'Business Continuity',
};

/**
 * Department colors
 */
export const ADMIN_DEPARTMENT_COLOR: Record<AdminDepartment, string> = {
  [ADMIN_DEPARTMENT.MANAGEMENT]: '#2C3E50',
  [ADMIN_DEPARTMENT.OPERATIONS]: '#34495E',
  [ADMIN_DEPARTMENT.ADMINISTRATION]: '#4A6A8B',
  [ADMIN_DEPARTMENT.EXECUTIVE]: '#1A237E',

  [ADMIN_DEPARTMENT.TECHNICAL]: '#0D47A1',
  [ADMIN_DEPARTMENT.DEVELOPMENT]: '#1565C0',
  [ADMIN_DEPARTMENT.ENGINEERING]: '#1976D2',
  [ADMIN_DEPARTMENT.IT]: '#1E88E5',
  [ADMIN_DEPARTMENT.DEVOPS]: '#42A5F5',
  [ADMIN_DEPARTMENT.SECURITY]: '#D32F2F',

  [ADMIN_DEPARTMENT.BUSINESS]: '#4E342E',
  [ADMIN_DEPARTMENT.STRATEGY]: '#5D4037',
  [ADMIN_DEPARTMENT.PLANNING]: '#6D4C41',
  [ADMIN_DEPARTMENT.INNOVATION]: '#795548',

  [ADMIN_DEPARTMENT.DESIGN]: '#6A1B9A',
  [ADMIN_DEPARTMENT.UX]: '#7B1FA2',
  [ADMIN_DEPARTMENT.UI]: '#8E24AA',
  [ADMIN_DEPARTMENT.CREATIVE]: '#9C27B0',

  [ADMIN_DEPARTMENT.MARKETING]: '#E65100',
  [ADMIN_DEPARTMENT.DIGITAL_MARKETING]: '#EF6C00',
  [ADMIN_DEPARTMENT.SOCIAL_MEDIA]: '#F57C00',
  [ADMIN_DEPARTMENT.CONTENT]: '#FB8C00',
  [ADMIN_DEPARTMENT.BRAND]: '#FF9800',

  [ADMIN_DEPARTMENT.SALES]: '#1B5E20',
  [ADMIN_DEPARTMENT.RETAIL]: '#2E7D32',
  [ADMIN_DEPARTMENT.WHOLESALE]: '#388E3C',
  [ADMIN_DEPARTMENT.B2B]: '#43A047',
  [ADMIN_DEPARTMENT.B2C]: '#4CAF50',

  [ADMIN_DEPARTMENT.SUPPORT]: '#00695C',
  [ADMIN_DEPARTMENT.CUSTOMER_SERVICE]: '#00796B',
  [ADMIN_DEPARTMENT.HELP_DESK]: '#00897B',
  [ADMIN_DEPARTMENT.TECHNICAL_SUPPORT]: '#009688',

  [ADMIN_DEPARTMENT.FINANCE]: '#4A148C',
  [ADMIN_DEPARTMENT.ACCOUNTING]: '#6A1B9A',
  [ADMIN_DEPARTMENT.BUDGET]: '#7B1FA2',
  [ADMIN_DEPARTMENT.TAX]: '#8E24AA',
  [ADMIN_DEPARTMENT.AUDIT]: '#9C27B0',
  [ADMIN_DEPARTMENT.COMPLIANCE]: '#AB47BC',

  [ADMIN_DEPARTMENT.HR]: '#BF360C',
  [ADMIN_DEPARTMENT.RECRUITMENT]: '#D84315',
  [ADMIN_DEPARTMENT.TRAINING]: '#E64A19',
  [ADMIN_DEPARTMENT.DEVELOPMENT_HR]: '#F4511E',

  [ADMIN_DEPARTMENT.LOGISTICS]: '#1A237E',
  [ADMIN_DEPARTMENT.SUPPLY_CHAIN]: '#283593',
  [ADMIN_DEPARTMENT.PROCUREMENT]: '#303F9F',
  [ADMIN_DEPARTMENT.WAREHOUSE]: '#3949AB',
  [ADMIN_DEPARTMENT.INVENTORY]: '#3F51B5',

  [ADMIN_DEPARTMENT.PRODUCT]: '#004D40',
  [ADMIN_DEPARTMENT.PRODUCT_DEVELOPMENT]: '#00695C',
  [ADMIN_DEPARTMENT.PRODUCT_MANAGEMENT]: '#00796B',
  [ADMIN_DEPARTMENT.QUALITY_ASSURANCE]: '#00897B',

  [ADMIN_DEPARTMENT.ANALYTICS]: '#880E4F',
  [ADMIN_DEPARTMENT.DATA_SCIENCE]: '#AD1457',
  [ADMIN_DEPARTMENT.BUSINESS_INTELLIGENCE]: '#C2185B',
  [ADMIN_DEPARTMENT.RESEARCH]: '#D81B60',

  [ADMIN_DEPARTMENT.LEGAL]: '#1A237E',
  [ADMIN_DEPARTMENT.LEGAL_COMPLIANCE]: '#283593',
  [ADMIN_DEPARTMENT.REGULATORY]: '#303F9F',

  [ADMIN_DEPARTMENT.SPECIAL_PROJECTS]: '#263238',
  [ADMIN_DEPARTMENT.CRISIS_MANAGEMENT]: '#37474F',
  [ADMIN_DEPARTMENT.CHANGE_MANAGEMENT]: '#455A64',
  [ADMIN_DEPARTMENT.CONTINUITY]: '#546E7A',
};

/**
 * Department icons
 */
export const ADMIN_DEPARTMENT_ICON: Record<AdminDepartment, string> = {
  [ADMIN_DEPARTMENT.MANAGEMENT]: 'briefcase',
  [ADMIN_DEPARTMENT.OPERATIONS]: 'cogs',
  [ADMIN_DEPARTMENT.ADMINISTRATION]: 'building',
  [ADMIN_DEPARTMENT.EXECUTIVE]: 'user-tie',

  [ADMIN_DEPARTMENT.TECHNICAL]: 'microchip',
  [ADMIN_DEPARTMENT.DEVELOPMENT]: 'code',
  [ADMIN_DEPARTMENT.ENGINEERING]: 'laptop',
  [ADMIN_DEPARTMENT.IT]: 'server',
  [ADMIN_DEPARTMENT.DEVOPS]: 'cloud',
  [ADMIN_DEPARTMENT.SECURITY]: 'shield',

  [ADMIN_DEPARTMENT.BUSINESS]: 'chart-line',
  [ADMIN_DEPARTMENT.STRATEGY]: 'chess-queen',
  [ADMIN_DEPARTMENT.PLANNING]: 'tasks',
  [ADMIN_DEPARTMENT.INNOVATION]: 'lightbulb',

  [ADMIN_DEPARTMENT.DESIGN]: 'paint-brush',
  [ADMIN_DEPARTMENT.UX]: 'hand-pointer',
  [ADMIN_DEPARTMENT.UI]: 'desktop',
  [ADMIN_DEPARTMENT.CREATIVE]: 'palette',

  [ADMIN_DEPARTMENT.MARKETING]: 'bullhorn',
  [ADMIN_DEPARTMENT.DIGITAL_MARKETING]: 'globe',
  [ADMIN_DEPARTMENT.SOCIAL_MEDIA]: 'share-alt',
  [ADMIN_DEPARTMENT.CONTENT]: 'file-alt',
  [ADMIN_DEPARTMENT.BRAND]: 'trademark',

  [ADMIN_DEPARTMENT.SALES]: 'dollar-sign',
  [ADMIN_DEPARTMENT.RETAIL]: 'store',
  [ADMIN_DEPARTMENT.WHOLESALE]: 'truck',
  [ADMIN_DEPARTMENT.B2B]: 'handshake',
  [ADMIN_DEPARTMENT.B2C]: 'user',

  [ADMIN_DEPARTMENT.SUPPORT]: 'headset',
  [ADMIN_DEPARTMENT.CUSTOMER_SERVICE]: 'phone',
  [ADMIN_DEPARTMENT.HELP_DESK]: 'question-circle',
  [ADMIN_DEPARTMENT.TECHNICAL_SUPPORT]: 'wrench',

  [ADMIN_DEPARTMENT.FINANCE]: 'money-bill',
  [ADMIN_DEPARTMENT.ACCOUNTING]: 'calculator',
  [ADMIN_DEPARTMENT.BUDGET]: 'chart-pie',
  [ADMIN_DEPARTMENT.TAX]: 'receipt',
  [ADMIN_DEPARTMENT.AUDIT]: 'clipboard-check',
  [ADMIN_DEPARTMENT.COMPLIANCE]: 'balance-scale',

  [ADMIN_DEPARTMENT.HR]: 'users',
  [ADMIN_DEPARTMENT.RECRUITMENT]: 'user-plus',
  [ADMIN_DEPARTMENT.TRAINING]: 'graduation-cap',
  [ADMIN_DEPARTMENT.DEVELOPMENT_HR]: 'user-graduate',

  [ADMIN_DEPARTMENT.LOGISTICS]: 'shipping',
  [ADMIN_DEPARTMENT.SUPPLY_CHAIN]: 'link',
  [ADMIN_DEPARTMENT.PROCUREMENT]: 'shopping-cart',
  [ADMIN_DEPARTMENT.WAREHOUSE]: 'warehouse',
  [ADMIN_DEPARTMENT.INVENTORY]: 'boxes',

  [ADMIN_DEPARTMENT.PRODUCT]: 'cube',
  [ADMIN_DEPARTMENT.PRODUCT_DEVELOPMENT]: 'cubes',
  [ADMIN_DEPARTMENT.PRODUCT_MANAGEMENT]: 'tasks',
  [ADMIN_DEPARTMENT.QUALITY_ASSURANCE]: 'check-double',

  [ADMIN_DEPARTMENT.ANALYTICS]: 'chart-bar',
  [ADMIN_DEPARTMENT.DATA_SCIENCE]: 'brain',
  [ADMIN_DEPARTMENT.BUSINESS_INTELLIGENCE]: 'chart-area',
  [ADMIN_DEPARTMENT.RESEARCH]: 'search',

  [ADMIN_DEPARTMENT.LEGAL]: 'gavel',
  [ADMIN_DEPARTMENT.LEGAL_COMPLIANCE]: 'scale',
  [ADMIN_DEPARTMENT.REGULATORY]: 'file-signature',

  [ADMIN_DEPARTMENT.SPECIAL_PROJECTS]: 'rocket',
  [ADMIN_DEPARTMENT.CRISIS_MANAGEMENT]: 'exclamation-triangle',
  [ADMIN_DEPARTMENT.CHANGE_MANAGEMENT]: 'sync',
  [ADMIN_DEPARTMENT.CONTINUITY]: 'infinity',
};

/**
 * Get department label
 */
export function getAdminDepartmentLabel(department: string): string {
  return ADMIN_DEPARTMENT_LABEL[department as AdminDepartment] || department;
}

/**
 * Get department color
 */
export function getAdminDepartmentColorFromDept(department: string): string {
  return ADMIN_DEPARTMENT_COLOR[department as AdminDepartment] || '#6C757D';
}

/**
 * Get department icon
 */
export function getAdminDepartmentIcon(department: string): string {
  return ADMIN_DEPARTMENT_ICON[department as AdminDepartment] || 'building';
}

/**
 * Get department category
 */
export function getDepartmentCategory(department: AdminDepartment): DepartmentCategory {
  return DEPARTMENT_CATEGORY_MAP[department] || DEPARTMENT_CATEGORY.CORE;
}

/**
 * Get all departments in a category
 */
export function getDepartmentsByCategory(category: DepartmentCategory): AdminDepartment[] {
  return (Object.keys(DEPARTMENT_CATEGORY_MAP) as AdminDepartment[]).filter(
    (dept) => DEPARTMENT_CATEGORY_MAP[dept] === category
  );
}

/**
 * Get department options for dropdown
 */
export function getAdminDepartmentOptions(): Array<{
  value: AdminDepartment;
  label: string;
  category: DepartmentCategory;
}> {
  return (Object.values(ADMIN_DEPARTMENT) as AdminDepartment[]).map((dept) => ({
    value: dept,
    label: ADMIN_DEPARTMENT_LABEL[dept] || dept,
    category: DEPARTMENT_CATEGORY_MAP[dept] || DEPARTMENT_CATEGORY.CORE,
  }));
}

/**
 * Get departments by category for dropdown
 */
export function getDepartmentsByCategoryForDropdown(
  category: DepartmentCategory
): Array<{ value: AdminDepartment; label: string }> {
  const departments = getDepartmentsByCategory(category);
  return departments.map((dept) => ({
    value: dept,
    label: ADMIN_DEPARTMENT_LABEL[dept] || dept,
  }));
}
