/**
 * Attachment Type Constants
 * Types of file attachments in support system
 */

export const ATTACHMENT_TYPE = {
  // Type Types
  TYPES: {
    IMAGE: 'image',
    VIDEO: 'video',
    AUDIO: 'audio',
    DOCUMENT: 'document',
    SPREADSHEET: 'spreadsheet',
    PRESENTATION: 'presentation',
    PDF: 'pdf',
    ARCHIVE: 'archive',
    CODE: 'code',
    OTHER: 'other',
  } as const,

  // Type Categories
  CATEGORIES: {
    MEDIA: 'media',
    DOCUMENT: 'document',
    DATA: 'data',
    ARCHIVE: 'archive',
    OTHER: 'other',
  } as const,

  // Type Icons (for UI)
  ICONS: {
    IMAGE: '🖼️',
    VIDEO: '🎬',
    AUDIO: '🎵',
    DOCUMENT: '📄',
    SPREADSHEET: '📊',
    PRESENTATION: '📽️',
    PDF: '📕',
    ARCHIVE: '📦',
    CODE: '💻',
    OTHER: '📎',
  } as const,

  // Type Colors (for UI)
  COLORS: {
    IMAGE: '#green-500',
    VIDEO: '#red-500',
    AUDIO: '#purple-500',
    DOCUMENT: '#blue-500',
    SPREADSHEET: '#green-600',
    PRESENTATION: '#orange-500',
    PDF: '#red-600',
    ARCHIVE: '#gray-500',
    CODE: '#indigo-500',
    OTHER: '#gray-400',
  } as const,

  // Type Size Limits (in bytes)
  SIZE_LIMITS: {
    IMAGE: 5242880, // 5MB
    VIDEO: 10485760, // 10MB
    AUDIO: 10485760, // 10MB
    DOCUMENT: 10485760, // 10MB
    SPREADSHEET: 10485760, // 10MB
    PRESENTATION: 20971520, // 20MB
    PDF: 10485760, // 10MB
    ARCHIVE: 52428800, // 50MB
    CODE: 5242880, // 5MB
    OTHER: 10485760, // 10MB
  } as const,
} as const;

// Type Types
export type AttachmentTypeType = (typeof ATTACHMENT_TYPE.TYPES)[keyof typeof ATTACHMENT_TYPE.TYPES];

// Type Categories
export type AttachmentTypeCategory =
  (typeof ATTACHMENT_TYPE.CATEGORIES)[keyof typeof ATTACHMENT_TYPE.CATEGORIES];

// Type Icons
export type AttachmentTypeIcon = (typeof ATTACHMENT_TYPE.ICONS)[keyof typeof ATTACHMENT_TYPE.ICONS];

// Type Colors
export type AttachmentTypeColor =
  (typeof ATTACHMENT_TYPE.COLORS)[keyof typeof ATTACHMENT_TYPE.COLORS];

// Size Limits
export type AttachmentTypeSizeLimit =
  (typeof ATTACHMENT_TYPE.SIZE_LIMITS)[keyof typeof ATTACHMENT_TYPE.SIZE_LIMITS];

// Utility Functions
export function attachmentTypeGetLabel(type: AttachmentTypeType): string {
  const labels: Record<AttachmentTypeType, string> = {
    [ATTACHMENT_TYPE.TYPES.IMAGE]: 'Image',
    [ATTACHMENT_TYPE.TYPES.VIDEO]: 'Video',
    [ATTACHMENT_TYPE.TYPES.AUDIO]: 'Audio',
    [ATTACHMENT_TYPE.TYPES.DOCUMENT]: 'Document',
    [ATTACHMENT_TYPE.TYPES.SPREADSHEET]: 'Spreadsheet',
    [ATTACHMENT_TYPE.TYPES.PRESENTATION]: 'Presentation',
    [ATTACHMENT_TYPE.TYPES.PDF]: 'PDF',
    [ATTACHMENT_TYPE.TYPES.ARCHIVE]: 'Archive',
    [ATTACHMENT_TYPE.TYPES.CODE]: 'Code',
    [ATTACHMENT_TYPE.TYPES.OTHER]: 'Other',
  };
  return labels[type] || 'Unknown';
}

export function attachmentTypeGetIcon(type: AttachmentTypeType): AttachmentTypeIcon {
  const icons: Record<AttachmentTypeType, AttachmentTypeIcon> = {
    [ATTACHMENT_TYPE.TYPES.IMAGE]: ATTACHMENT_TYPE.ICONS.IMAGE,
    [ATTACHMENT_TYPE.TYPES.VIDEO]: ATTACHMENT_TYPE.ICONS.VIDEO,
    [ATTACHMENT_TYPE.TYPES.AUDIO]: ATTACHMENT_TYPE.ICONS.AUDIO,
    [ATTACHMENT_TYPE.TYPES.DOCUMENT]: ATTACHMENT_TYPE.ICONS.DOCUMENT,
    [ATTACHMENT_TYPE.TYPES.SPREADSHEET]: ATTACHMENT_TYPE.ICONS.SPREADSHEET,
    [ATTACHMENT_TYPE.TYPES.PRESENTATION]: ATTACHMENT_TYPE.ICONS.PRESENTATION,
    [ATTACHMENT_TYPE.TYPES.PDF]: ATTACHMENT_TYPE.ICONS.PDF,
    [ATTACHMENT_TYPE.TYPES.ARCHIVE]: ATTACHMENT_TYPE.ICONS.ARCHIVE,
    [ATTACHMENT_TYPE.TYPES.CODE]: ATTACHMENT_TYPE.ICONS.CODE,
    [ATTACHMENT_TYPE.TYPES.OTHER]: ATTACHMENT_TYPE.ICONS.OTHER,
  };
  return icons[type] || '📎';
}

export function attachmentTypeGetColor(type: AttachmentTypeType): AttachmentTypeColor {
  const colors: Record<AttachmentTypeType, AttachmentTypeColor> = {
    [ATTACHMENT_TYPE.TYPES.IMAGE]: ATTACHMENT_TYPE.COLORS.IMAGE,
    [ATTACHMENT_TYPE.TYPES.VIDEO]: ATTACHMENT_TYPE.COLORS.VIDEO,
    [ATTACHMENT_TYPE.TYPES.AUDIO]: ATTACHMENT_TYPE.COLORS.AUDIO,
    [ATTACHMENT_TYPE.TYPES.DOCUMENT]: ATTACHMENT_TYPE.COLORS.DOCUMENT,
    [ATTACHMENT_TYPE.TYPES.SPREADSHEET]: ATTACHMENT_TYPE.COLORS.SPREADSHEET,
    [ATTACHMENT_TYPE.TYPES.PRESENTATION]: ATTACHMENT_TYPE.COLORS.PRESENTATION,
    [ATTACHMENT_TYPE.TYPES.PDF]: ATTACHMENT_TYPE.COLORS.PDF,
    [ATTACHMENT_TYPE.TYPES.ARCHIVE]: ATTACHMENT_TYPE.COLORS.ARCHIVE,
    [ATTACHMENT_TYPE.TYPES.CODE]: ATTACHMENT_TYPE.COLORS.CODE,
    [ATTACHMENT_TYPE.TYPES.OTHER]: ATTACHMENT_TYPE.COLORS.OTHER,
  };
  return colors[type] || '#gray-400';
}

export function attachmentTypeGetSizeLimit(type: AttachmentTypeType): number {
  const limits: Record<AttachmentTypeType, number> = {
    [ATTACHMENT_TYPE.TYPES.IMAGE]: ATTACHMENT_TYPE.SIZE_LIMITS.IMAGE,
    [ATTACHMENT_TYPE.TYPES.VIDEO]: ATTACHMENT_TYPE.SIZE_LIMITS.VIDEO,
    [ATTACHMENT_TYPE.TYPES.AUDIO]: ATTACHMENT_TYPE.SIZE_LIMITS.AUDIO,
    [ATTACHMENT_TYPE.TYPES.DOCUMENT]: ATTACHMENT_TYPE.SIZE_LIMITS.DOCUMENT,
    [ATTACHMENT_TYPE.TYPES.SPREADSHEET]: ATTACHMENT_TYPE.SIZE_LIMITS.SPREADSHEET,
    [ATTACHMENT_TYPE.TYPES.PRESENTATION]: ATTACHMENT_TYPE.SIZE_LIMITS.PRESENTATION,
    [ATTACHMENT_TYPE.TYPES.PDF]: ATTACHMENT_TYPE.SIZE_LIMITS.PDF,
    [ATTACHMENT_TYPE.TYPES.ARCHIVE]: ATTACHMENT_TYPE.SIZE_LIMITS.ARCHIVE,
    [ATTACHMENT_TYPE.TYPES.CODE]: ATTACHMENT_TYPE.SIZE_LIMITS.CODE,
    [ATTACHMENT_TYPE.TYPES.OTHER]: ATTACHMENT_TYPE.SIZE_LIMITS.OTHER,
  };
  return limits[type] || ATTACHMENT_TYPE.SIZE_LIMITS.OTHER;
}

export function attachmentTypeGetCategory(type: AttachmentTypeType): AttachmentTypeCategory {
  const categories: Record<AttachmentTypeType, AttachmentTypeCategory> = {
    [ATTACHMENT_TYPE.TYPES.IMAGE]: ATTACHMENT_TYPE.CATEGORIES.MEDIA,
    [ATTACHMENT_TYPE.TYPES.VIDEO]: ATTACHMENT_TYPE.CATEGORIES.MEDIA,
    [ATTACHMENT_TYPE.TYPES.AUDIO]: ATTACHMENT_TYPE.CATEGORIES.MEDIA,
    [ATTACHMENT_TYPE.TYPES.DOCUMENT]: ATTACHMENT_TYPE.CATEGORIES.DOCUMENT,
    [ATTACHMENT_TYPE.TYPES.SPREADSHEET]: ATTACHMENT_TYPE.CATEGORIES.DATA,
    [ATTACHMENT_TYPE.TYPES.PRESENTATION]: ATTACHMENT_TYPE.CATEGORIES.DOCUMENT,
    [ATTACHMENT_TYPE.TYPES.PDF]: ATTACHMENT_TYPE.CATEGORIES.DOCUMENT,
    [ATTACHMENT_TYPE.TYPES.ARCHIVE]: ATTACHMENT_TYPE.CATEGORIES.ARCHIVE,
    [ATTACHMENT_TYPE.TYPES.CODE]: ATTACHMENT_TYPE.CATEGORIES.DATA,
    [ATTACHMENT_TYPE.TYPES.OTHER]: ATTACHMENT_TYPE.CATEGORIES.OTHER,
  };
  return categories[type] || ATTACHMENT_TYPE.CATEGORIES.OTHER;
}
