/**
 * Audit Constants - Enterprise Grade Audit Configuration
 * Enterprise Grade for vubon.com.bd - Bangladesh's #1 E-commerce
 * 
 * @module shared-constants/audit.constants
 * 
 * @description
 * Centralized audit constants for the entire ecommerce ecosystem.
 * Provides type-safe audit actions, sources, severities, and entity types.
 * 
 * ENTERPRISE FEATURES:
 * ✅ Complete audit action coverage for all domains
 * ✅ Bangladesh specific payment actions (bKash, Nagad, Rocket, SSLCOMMERZ)
 * ✅ Type-safe with 'as const' for literal types
 * ✅ Category-based organization for easy maintenance
 * ✅ Extensible for future domains
 * ✅ Framework-agnostic - works with any audit system
 * ✅ Multi-language ready (message keys can be mapped to translations)
 * 
 * Enterprise Rules:
 * ✅ Pure readonly constants - NO runtime logic
 * ✅ Type-safe with 'as const'
 * ✅ NO functions, NO side effects
 * ✅ Centralized Single Source of Truth
 * ✅ Consistent naming convention across all services
 * ✅ Reusable across all microservices
 * 
 * @example
 * // Import in audit service
 * import { 
 *   AUDIT_ACTIONS, 
 *   AUDIT_SOURCES, 
 *   AUDIT_SEVERITIES,
 *   AUDIT_ENTITY_TYPES 
 * } from '@vubon/shared-constants';
 * 
 * // Create audit log entry
 * const auditEntry = {
 *   action: AUDIT_ACTIONS.USER_LOGIN,
 *   source: AUDIT_SOURCES.API,
 *   severity: AUDIT_SEVERITIES.INFO,
 *   entityType: AUDIT_ENTITY_TYPES.USER,
 *   entityId: userId,
 *   userId: userId,
 *   metadata: { ip: '192.168.1.1' }
 * };
 */

// ============================================================
// Type Definitions
// ============================================================

/**
 * Audit Action - What happened
 */
export type AuditActionValue = typeof AUDIT_ACTIONS[keyof typeof AUDIT_ACTIONS];

/**
 * Audit Source - Where it happened
 */
export type AuditSourceValue = typeof AUDIT_SOURCES[keyof typeof AUDIT_SOURCES];

/**
 * Audit Severity - How important it is
 */
export type AuditSeverityValue = typeof AUDIT_SEVERITIES[keyof typeof AUDIT_SEVERITIES];

/**
 * Audit Entity Type - What was affected
 */
export type AuditEntityTypeValue = typeof AUDIT_ENTITY_TYPES[keyof typeof AUDIT_ENTITY_TYPES];

// ============================================================
// Audit Actions (What happened)
// ============================================================

/**
 * Complete list of audit actions organized by domain
 * ✅ ENTERPRISE: Covers all domains - Auth, User, Product, Order, Payment, System, Security
 */
export const AUDIT_ACTIONS = {
  // ========== Authentication Actions ==========
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  REGISTER_FAILED: 'REGISTER_FAILED',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  MFA_ENABLE: 'MFA_ENABLE',
  MFA_DISABLE: 'MFA_DISABLE',
  MFA_VERIFY: 'MFA_VERIFY',
  MFA_VERIFY_FAILED: 'MFA_VERIFY_FAILED',
  MFA_BACKUP_CODE_USED: 'MFA_BACKUP_CODE_USED',
  MFA_RECOVERY_USED: 'MFA_RECOVERY_USED',
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_TRANSFER: 'SESSION_TRANSFER',
  
  // ========== User Management Actions ==========
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_SUSPEND: 'USER_SUSPEND',
  USER_ACTIVATE: 'USER_ACTIVATE',
  USER_BAN: 'USER_BAN',
  USER_UNBAN: 'USER_UNBAN',
  USER_VERIFY_EMAIL: 'USER_VERIFY_EMAIL',
  USER_VERIFY_PHONE: 'USER_VERIFY_PHONE',
  USER_KYC_VERIFY: 'USER_KYC_VERIFY',
  USER_ROLE_ASSIGN: 'USER_ROLE_ASSIGN',
  USER_ROLE_REVOKE: 'USER_ROLE_REVOKE',
  USER_IMPERSONATE: 'USER_IMPERSONATE',
  USER_MERGE: 'USER_MERGE',
  USER_EXPORT: 'USER_EXPORT',
  USER_IMPORT: 'USER_IMPORT',
  
  // ========== Social Account Actions ==========
  SOCIAL_ACCOUNT_LINK: 'SOCIAL_ACCOUNT_LINK',
  SOCIAL_ACCOUNT_UNLINK: 'SOCIAL_ACCOUNT_UNLINK',
  SOCIAL_ACCOUNT_SUSPEND: 'SOCIAL_ACCOUNT_SUSPEND',
  SOCIAL_ACCOUNT_REACTIVATE: 'SOCIAL_ACCOUNT_REACTIVATE',
  SOCIAL_ACCOUNT_INFO_UPDATE: 'SOCIAL_ACCOUNT_INFO_UPDATE',
  
  // ========== Product Management Actions ==========
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',
  PRODUCT_PUBLISH: 'PRODUCT_PUBLISH',
  PRODUCT_UNPUBLISH: 'PRODUCT_UNPUBLISH',
  PRODUCT_APPROVE: 'PRODUCT_APPROVE',
  PRODUCT_REJECT: 'PRODUCT_REJECT',
  PRODUCT_FEATURE: 'PRODUCT_FEATURE',
  PRODUCT_UNFEATURE: 'PRODUCT_UNFEATURE',
  PRODUCT_PRICE_UPDATE: 'PRODUCT_PRICE_UPDATE',
  PRODUCT_STOCK_UPDATE: 'PRODUCT_STOCK_UPDATE',
  PRODUCT_BULK_UPDATE: 'PRODUCT_BULK_UPDATE',
  PRODUCT_IMPORT: 'PRODUCT_IMPORT',
  PRODUCT_EXPORT: 'PRODUCT_EXPORT',
  
  // ========== Category & Brand Actions ==========
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',
  BRAND_CREATE: 'BRAND_CREATE',
  BRAND_UPDATE: 'BRAND_UPDATE',
  BRAND_DELETE: 'BRAND_DELETE',
  
  // ========== Order Management Actions ==========
  ORDER_CREATE: 'ORDER_CREATE',
  ORDER_UPDATE: 'ORDER_UPDATE',
  ORDER_CANCEL: 'ORDER_CANCEL',
  ORDER_REFUND: 'ORDER_REFUND',
  ORDER_APPROVE: 'ORDER_APPROVE',
  ORDER_REJECT: 'ORDER_REJECT',
  ORDER_SHIP: 'ORDER_SHIP',
  ORDER_DELIVER: 'ORDER_DELIVER',
  ORDER_STATUS_CHANGE: 'ORDER_STATUS_CHANGE',
  ORDER_BULK_UPDATE: 'ORDER_BULK_UPDATE',
  ORDER_EXPORT: 'ORDER_EXPORT',
  
  // ========== Payment Actions ==========
  PAYMENT_INITIATE: 'PAYMENT_INITIATE',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REFUND: 'PAYMENT_REFUND',
  PAYMENT_VOID: 'PAYMENT_VOID',
  PAYMENT_CAPTURE: 'PAYMENT_CAPTURE',
  PAYMENT_VERIFY: 'PAYMENT_VERIFY',
  
  // ========== Bangladesh Specific Payment Actions ==========
  BKASH_PAYMENT_INITIATE: 'BKASH_PAYMENT_INITIATE',
  BKASH_PAYMENT_SUCCESS: 'BKASH_PAYMENT_SUCCESS',
  BKASH_PAYMENT_FAILED: 'BKASH_PAYMENT_FAILED',
  BKASH_PAYMENT_REFUND: 'BKASH_PAYMENT_REFUND',
  NAGAD_PAYMENT_INITIATE: 'NAGAD_PAYMENT_INITIATE',
  NAGAD_PAYMENT_SUCCESS: 'NAGAD_PAYMENT_SUCCESS',
  NAGAD_PAYMENT_FAILED: 'NAGAD_PAYMENT_FAILED',
  NAGAD_PAYMENT_REFUND: 'NAGAD_PAYMENT_REFUND',
  ROCKET_PAYMENT_INITIATE: 'ROCKET_PAYMENT_INITIATE',
  ROCKET_PAYMENT_SUCCESS: 'ROCKET_PAYMENT_SUCCESS',
  ROCKET_PAYMENT_FAILED: 'ROCKET_PAYMENT_FAILED',
  ROCKET_PAYMENT_REFUND: 'ROCKET_PAYMENT_REFUND',
  SSLCOMMERZ_PAYMENT_SUCCESS: 'SSLCOMMERZ_PAYMENT_SUCCESS',
  SSLCOMMERZ_PAYMENT_FAILED: 'SSLCOMMERZ_PAYMENT_FAILED',
  SSLCOMMERZ_PAYMENT_REFUND: 'SSLCOMMERZ_PAYMENT_REFUND',
  
  // ========== Inventory Actions ==========
  INVENTORY_UPDATE: 'INVENTORY_UPDATE',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',
  INVENTORY_RESERVE: 'INVENTORY_RESERVE',
  INVENTORY_RELEASE: 'INVENTORY_RELEASE',
  INVENTORY_BULK_UPDATE: 'INVENTORY_BULK_UPDATE',
  INVENTORY_LOW_STOCK_ALERT: 'INVENTORY_LOW_STOCK_ALERT',
  
  // ========== Permission & Role Actions ==========
  PERMISSION_GRANT: 'PERMISSION_GRANT',
  PERMISSION_REVOKE: 'PERMISSION_REVOKE',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  ROLE_ASSIGN: 'ROLE_ASSIGN',
  ROLE_REVOKE: 'ROLE_REVOKE',
  
  // ========== Vendor/Seller Actions ==========
  VENDOR_CREATE: 'VENDOR_CREATE',
  VENDOR_UPDATE: 'VENDOR_UPDATE',
  VENDOR_VERIFY: 'VENDOR_VERIFY',
  VENDOR_SUSPEND: 'VENDOR_SUSPEND',
  VENDOR_ACTIVATE: 'VENDOR_ACTIVATE',
  VENDOR_PAYOUT: 'VENDOR_PAYOUT',
  VENDOR_COMMISSION_UPDATE: 'VENDOR_COMMISSION_UPDATE',
  SHOP_CREATE: 'SHOP_CREATE',
  SHOP_UPDATE: 'SHOP_UPDATE',
  SHOP_DELETE: 'SHOP_DELETE',
  
  // ========== Delivery Actions ==========
  DELIVERY_ASSIGN: 'DELIVERY_ASSIGN',
  DELIVERY_PICKUP: 'DELIVERY_PICKUP',
  DELIVERY_IN_TRANSIT: 'DELIVERY_IN_TRANSIT',
  DELIVERY_DELIVERED: 'DELIVERY_DELIVERED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  DELIVERY_RETURN: 'DELIVERY_RETURN',
  
  // ========== Coupon/Offer Actions ==========
  COUPON_CREATE: 'COUPON_CREATE',
  COUPON_UPDATE: 'COUPON_UPDATE',
  COUPON_DELETE: 'COUPON_DELETE',
  COUPON_APPLY: 'COUPON_APPLY',
  OFFER_CREATE: 'OFFER_CREATE',
  OFFER_UPDATE: 'OFFER_UPDATE',
  OFFER_DELETE: 'OFFER_DELETE',
  FLASH_SALE_START: 'FLASH_SALE_START',
  FLASH_SALE_END: 'FLASH_SALE_END',
  
  // ========== Review Actions ==========
  REVIEW_CREATE: 'REVIEW_CREATE',
  REVIEW_UPDATE: 'REVIEW_UPDATE',
  REVIEW_DELETE: 'REVIEW_DELETE',
  REVIEW_MODERATE: 'REVIEW_MODERATE',
  REVIEW_REPORT: 'REVIEW_REPORT',
  
  // ========== Support/Ticket Actions ==========
  TICKET_CREATE: 'TICKET_CREATE',
  TICKET_UPDATE: 'TICKET_UPDATE',
  TICKET_RESOLVE: 'TICKET_RESOLVE',
  TICKET_ASSIGN: 'TICKET_ASSIGN',
  
  // ========== Notification Actions ==========
  NOTIFICATION_SEND: 'NOTIFICATION_SEND',
  NOTIFICATION_BROADCAST: 'NOTIFICATION_BROADCAST',
  
  // ========== System Actions ==========
  SYSTEM_CONFIG_UPDATE: 'SYSTEM_CONFIG_UPDATE',
  SYSTEM_CACHE_CLEAR: 'SYSTEM_CACHE_CLEAR',
  SYSTEM_QUEUE_PURGE: 'SYSTEM_QUEUE_PURGE',
  SYSTEM_QUEUE_RETRY: 'SYSTEM_QUEUE_RETRY',
  SYSTEM_BACKUP_CREATE: 'SYSTEM_BACKUP_CREATE',
  SYSTEM_BACKUP_RESTORE: 'SYSTEM_BACKUP_RESTORE',
  SYSTEM_MAINTENANCE_START: 'SYSTEM_MAINTENANCE_START',
  SYSTEM_MAINTENANCE_END: 'SYSTEM_MAINTENANCE_END',
  SYSTEM_HEALTH_CHECK: 'SYSTEM_HEALTH_CHECK',
  
  // ========== Data Actions ==========
  DATA_EXPORT: 'DATA_EXPORT',
  DATA_IMPORT: 'DATA_IMPORT',
  REPORT_GENERATE: 'REPORT_GENERATE',
  REPORT_SCHEDULE: 'REPORT_SCHEDULE',
  REPORT_DELETE: 'REPORT_DELETE',
  
  // ========== Security Actions ==========
  SECURITY_ALERT: 'SECURITY_ALERT',
  IP_BLOCK: 'IP_BLOCK',
  IP_UNBLOCK: 'IP_UNBLOCK',
  DEVICE_BLOCK: 'DEVICE_BLOCK',
  DEVICE_UNBLOCK: 'DEVICE_UNBLOCK',
  RATE_LIMIT_CHANGE: 'RATE_LIMIT_CHANGE',
  ACCOUNT_LOCK: 'ACCOUNT_LOCK',
  ACCOUNT_UNLOCK: 'ACCOUNT_UNLOCK',
  BRUTE_FORCE_DETECTED: 'BRUTE_FORCE_DETECTED',
  SUSPICIOUS_ACTIVITY_DETECTED: 'SUSPICIOUS_ACTIVITY_DETECTED',
} as const;

// ============================================================
// Audit Sources (Where it happened)
// ============================================================

/**
 * Complete list of audit sources
 * ✅ ENTERPRISE: Covers all possible entry points
 */
export const AUDIT_SOURCES = {
  /** REST API calls */
  API: 'API',
  /** Web browser/SPA */
  WEB: 'WEB',
  /** Mobile app (iOS/Android) */
  MOBILE: 'MOBILE',
  /** Admin panel/back office */
  ADMIN: 'ADMIN',
  /** System level (cron, daemon, etc.) */
  SYSTEM: 'SYSTEM',
  /** Scheduled jobs */
  CRON: 'CRON',
  /** Webhook from external services */
  WEBHOOK: 'WEBHOOK',
  /** Internal service-to-service calls */
  INTERNAL: 'INTERNAL',
  /** Third-party integration */
  THIRD_PARTY: 'THIRD_PARTY',
  /** Batch processing jobs */
  BATCH: 'BATCH',
  /** Data migration scripts */
  MIGRATION: 'MIGRATION',
  /** CI/CD deployment */
  DEPLOYMENT: 'DEPLOYMENT',
  /** User directly (manual action) */
  USER: 'USER',
} as const;

// ============================================================
// Audit Severities (How important it is)
// ============================================================

/**
 * Complete list of audit severities
 * ✅ ENTERPRISE: Standard severity levels with clear meaning
 */
export const AUDIT_SEVERITIES = {
  /** Debug information (development only) */
  DEBUG: 'DEBUG',
  /** Normal operation (successful actions) */
  INFO: 'INFO',
  /** Unusual but not harmful (retry, warning) */
  WARNING: 'WARNING',
  /** Failed operations (business errors, validation) */
  ERROR: 'ERROR',
  /** Critical (security breach, data loss) */
  CRITICAL: 'CRITICAL',
  /** Emergency (immediate action required) */
  EMERGENCY: 'EMERGENCY',
} as const;

// ============================================================
// Audit Entity Types (What was affected)
// ============================================================

/**
 * Complete list of audit entity types
 * ✅ ENTERPRISE: Covers all domain entities
 */
export const AUDIT_ENTITY_TYPES = {
  // Auth & User
  USER: 'USER',
  SESSION: 'SESSION',
  MFA: 'MFA',
  SOCIAL_ACCOUNT: 'SOCIAL_ACCOUNT',
  
  // Commerce
  PRODUCT: 'PRODUCT',
  CATEGORY: 'CATEGORY',
  BRAND: 'BRAND',
  ORDER: 'ORDER',
  PAYMENT: 'PAYMENT',
  INVENTORY: 'INVENTORY',
  REVIEW: 'REVIEW',
  COUPON: 'COUPON',
  OFFER: 'OFFER',
  FLASH_SALE: 'FLASH_SALE',
  
  // Vendor & Shop
  VENDOR: 'VENDOR',
  SHOP: 'SHOP',
  
  // Delivery
  DELIVERY: 'DELIVERY',
  
  // Support
  TICKET: 'TICKET',
  NOTIFICATION: 'NOTIFICATION',
  
  // System
  SYSTEM: 'SYSTEM',
  CONFIG: 'CONFIG',
  CACHE: 'CACHE',
  QUEUE: 'QUEUE',
  BACKUP: 'BACKUP',
  REPORT: 'REPORT',
  
  // Data
  EXPORT: 'EXPORT',
  IMPORT: 'IMPORT',
  
  // Security
  SECURITY: 'SECURITY',
  KYC: 'KYC',
  DEVICE: 'DEVICE',
  IP_ADDRESS: 'IP_ADDRESS',
  
  // Bangladesh Specific
  DISTRICT: 'DISTRICT',
  UPAZILA: 'UPAZILA',
  MFS_ACCOUNT: 'MFS_ACCOUNT', // bKash/Nagad/Rocket
  
  // API & Integration
  API_KEY: 'API_KEY',
  WEBHOOK: 'WEBHOOK',
} as const;

// ============================================================
// Action Category Grouping (For UI/Filtering)
// ============================================================

/**
 * ✅ ENTERPRISE: Action categories for UI grouping and filtering
 */
export const AUDIT_ACTION_CATEGORIES = {
  AUTHENTICATION: 'AUTHENTICATION',
  USER_MANAGEMENT: 'USER_MANAGEMENT',
  PRODUCT_MANAGEMENT: 'PRODUCT_MANAGEMENT',
  ORDER_MANAGEMENT: 'ORDER_MANAGEMENT',
  PAYMENT_MANAGEMENT: 'PAYMENT_MANAGEMENT',
  VENDOR_MANAGEMENT: 'VENDOR_MANAGEMENT',
  DELIVERY_MANAGEMENT: 'DELIVERY_MANAGEMENT',
  SYSTEM_MANAGEMENT: 'SYSTEM_MANAGEMENT',
  SECURITY: 'SECURITY',
  DATA_MANAGEMENT: 'DATA_MANAGEMENT',
  NOTIFICATION: 'NOTIFICATION',
} as const;

export type AuditActionCategory = typeof AUDIT_ACTION_CATEGORIES[keyof typeof AUDIT_ACTION_CATEGORIES];

/**
 * ✅ ENTERPRISE: Map actions to categories for UI grouping
 */
export const AUDIT_ACTION_TO_CATEGORY: Record<AuditActionValue, AuditActionCategory> = {
  // Authentication
  'LOGIN': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'LOGIN_FAILED': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'LOGOUT': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'REGISTER': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'REGISTER_FAILED': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'PASSWORD_CHANGE': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'PASSWORD_RESET': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'PASSWORD_RESET_REQUEST': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'PASSWORD_RESET_FAILED': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'MFA_ENABLE': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'MFA_DISABLE': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'MFA_VERIFY': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'MFA_VERIFY_FAILED': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'MFA_BACKUP_CODE_USED': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'MFA_RECOVERY_USED': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'SESSION_CREATED': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'SESSION_REVOKED': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'SESSION_EXPIRED': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  'SESSION_TRANSFER': AUDIT_ACTION_CATEGORIES.AUTHENTICATION,
  
  // User Management
  'USER_CREATE': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_UPDATE': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_DELETE': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_SUSPEND': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_ACTIVATE': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_BAN': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_UNBAN': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_VERIFY_EMAIL': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_VERIFY_PHONE': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_KYC_VERIFY': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_ROLE_ASSIGN': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_ROLE_REVOKE': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_IMPERSONATE': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_MERGE': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_EXPORT': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'USER_IMPORT': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'SOCIAL_ACCOUNT_LINK': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'SOCIAL_ACCOUNT_UNLINK': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'SOCIAL_ACCOUNT_SUSPEND': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'SOCIAL_ACCOUNT_REACTIVATE': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  'SOCIAL_ACCOUNT_INFO_UPDATE': AUDIT_ACTION_CATEGORIES.USER_MANAGEMENT,
  
  // Product Management
  'PRODUCT_CREATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'PRODUCT_UPDATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'PRODUCT_DELETE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'PRODUCT_PUBLISH': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'PRODUCT_UNPUBLISH': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'PRODUCT_APPROVE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'PRODUCT_REJECT': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'PRODUCT_FEATURE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'PRODUCT_UNFEATURE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'PRODUCT_PRICE_UPDATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'PRODUCT_STOCK_UPDATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'PRODUCT_BULK_UPDATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'PRODUCT_IMPORT': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'PRODUCT_EXPORT': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'CATEGORY_CREATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'CATEGORY_UPDATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'CATEGORY_DELETE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'BRAND_CREATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'BRAND_UPDATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'BRAND_DELETE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  
  // Order Management
  'ORDER_CREATE': AUDIT_ACTION_CATEGORIES.ORDER_MANAGEMENT,
  'ORDER_UPDATE': AUDIT_ACTION_CATEGORIES.ORDER_MANAGEMENT,
  'ORDER_CANCEL': AUDIT_ACTION_CATEGORIES.ORDER_MANAGEMENT,
  'ORDER_REFUND': AUDIT_ACTION_CATEGORIES.ORDER_MANAGEMENT,
  'ORDER_APPROVE': AUDIT_ACTION_CATEGORIES.ORDER_MANAGEMENT,
  'ORDER_REJECT': AUDIT_ACTION_CATEGORIES.ORDER_MANAGEMENT,
  'ORDER_SHIP': AUDIT_ACTION_CATEGORIES.ORDER_MANAGEMENT,
  'ORDER_DELIVER': AUDIT_ACTION_CATEGORIES.ORDER_MANAGEMENT,
  'ORDER_STATUS_CHANGE': AUDIT_ACTION_CATEGORIES.ORDER_MANAGEMENT,
  'ORDER_BULK_UPDATE': AUDIT_ACTION_CATEGORIES.ORDER_MANAGEMENT,
  'ORDER_EXPORT': AUDIT_ACTION_CATEGORIES.ORDER_MANAGEMENT,
  
  // Payment Management
  'PAYMENT_INITIATE': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'PAYMENT_SUCCESS': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'PAYMENT_FAILED': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'PAYMENT_REFUND': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'PAYMENT_VOID': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'PAYMENT_CAPTURE': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'PAYMENT_VERIFY': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  // Bangladesh Specific Payments
  'BKASH_PAYMENT_INITIATE': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'BKASH_PAYMENT_SUCCESS': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'BKASH_PAYMENT_FAILED': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'BKASH_PAYMENT_REFUND': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'NAGAD_PAYMENT_INITIATE': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'NAGAD_PAYMENT_SUCCESS': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'NAGAD_PAYMENT_FAILED': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'NAGAD_PAYMENT_REFUND': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'ROCKET_PAYMENT_INITIATE': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'ROCKET_PAYMENT_SUCCESS': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'ROCKET_PAYMENT_FAILED': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'ROCKET_PAYMENT_REFUND': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'SSLCOMMERZ_PAYMENT_SUCCESS': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'SSLCOMMERZ_PAYMENT_FAILED': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  'SSLCOMMERZ_PAYMENT_REFUND': AUDIT_ACTION_CATEGORIES.PAYMENT_MANAGEMENT,
  
  // Vendor Management
  'VENDOR_CREATE': AUDIT_ACTION_CATEGORIES.VENDOR_MANAGEMENT,
  'VENDOR_UPDATE': AUDIT_ACTION_CATEGORIES.VENDOR_MANAGEMENT,
  'VENDOR_VERIFY': AUDIT_ACTION_CATEGORIES.VENDOR_MANAGEMENT,
  'VENDOR_SUSPEND': AUDIT_ACTION_CATEGORIES.VENDOR_MANAGEMENT,
  'VENDOR_ACTIVATE': AUDIT_ACTION_CATEGORIES.VENDOR_MANAGEMENT,
  'VENDOR_PAYOUT': AUDIT_ACTION_CATEGORIES.VENDOR_MANAGEMENT,
  'VENDOR_COMMISSION_UPDATE': AUDIT_ACTION_CATEGORIES.VENDOR_MANAGEMENT,
  'SHOP_CREATE': AUDIT_ACTION_CATEGORIES.VENDOR_MANAGEMENT,
  'SHOP_UPDATE': AUDIT_ACTION_CATEGORIES.VENDOR_MANAGEMENT,
  'SHOP_DELETE': AUDIT_ACTION_CATEGORIES.VENDOR_MANAGEMENT,
  
  // Delivery Management
  'DELIVERY_ASSIGN': AUDIT_ACTION_CATEGORIES.DELIVERY_MANAGEMENT,
  'DELIVERY_PICKUP': AUDIT_ACTION_CATEGORIES.DELIVERY_MANAGEMENT,
  'DELIVERY_IN_TRANSIT': AUDIT_ACTION_CATEGORIES.DELIVERY_MANAGEMENT,
  'DELIVERY_DELIVERED': AUDIT_ACTION_CATEGORIES.DELIVERY_MANAGEMENT,
  'DELIVERY_FAILED': AUDIT_ACTION_CATEGORIES.DELIVERY_MANAGEMENT,
  'DELIVERY_RETURN': AUDIT_ACTION_CATEGORIES.DELIVERY_MANAGEMENT,
  
  // System Management
  'SYSTEM_CONFIG_UPDATE': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'SYSTEM_CACHE_CLEAR': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'SYSTEM_QUEUE_PURGE': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'SYSTEM_QUEUE_RETRY': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'SYSTEM_BACKUP_CREATE': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'SYSTEM_BACKUP_RESTORE': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'SYSTEM_MAINTENANCE_START': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'SYSTEM_MAINTENANCE_END': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'SYSTEM_HEALTH_CHECK': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  
  // Security
  'SECURITY_ALERT': AUDIT_ACTION_CATEGORIES.SECURITY,
  'IP_BLOCK': AUDIT_ACTION_CATEGORIES.SECURITY,
  'IP_UNBLOCK': AUDIT_ACTION_CATEGORIES.SECURITY,
  'DEVICE_BLOCK': AUDIT_ACTION_CATEGORIES.SECURITY,
  'DEVICE_UNBLOCK': AUDIT_ACTION_CATEGORIES.SECURITY,
  'RATE_LIMIT_CHANGE': AUDIT_ACTION_CATEGORIES.SECURITY,
  'ACCOUNT_LOCK': AUDIT_ACTION_CATEGORIES.SECURITY,
  'ACCOUNT_UNLOCK': AUDIT_ACTION_CATEGORIES.SECURITY,
  'BRUTE_FORCE_DETECTED': AUDIT_ACTION_CATEGORIES.SECURITY,
  'SUSPICIOUS_ACTIVITY_DETECTED': AUDIT_ACTION_CATEGORIES.SECURITY,
  
  // Data Management
  'DATA_EXPORT': AUDIT_ACTION_CATEGORIES.DATA_MANAGEMENT,
  'DATA_IMPORT': AUDIT_ACTION_CATEGORIES.DATA_MANAGEMENT,
  'REPORT_GENERATE': AUDIT_ACTION_CATEGORIES.DATA_MANAGEMENT,
  'REPORT_SCHEDULE': AUDIT_ACTION_CATEGORIES.DATA_MANAGEMENT,
  'REPORT_DELETE': AUDIT_ACTION_CATEGORIES.DATA_MANAGEMENT,
  'INVENTORY_UPDATE': AUDIT_ACTION_CATEGORIES.DATA_MANAGEMENT,
  'INVENTORY_ADJUST': AUDIT_ACTION_CATEGORIES.DATA_MANAGEMENT,
  'INVENTORY_RESERVE': AUDIT_ACTION_CATEGORIES.DATA_MANAGEMENT,
  'INVENTORY_RELEASE': AUDIT_ACTION_CATEGORIES.DATA_MANAGEMENT,
  'INVENTORY_BULK_UPDATE': AUDIT_ACTION_CATEGORIES.DATA_MANAGEMENT,
  'INVENTORY_LOW_STOCK_ALERT': AUDIT_ACTION_CATEGORIES.DATA_MANAGEMENT,
  
  // Notification
  'NOTIFICATION_SEND': AUDIT_ACTION_CATEGORIES.NOTIFICATION,
  'NOTIFICATION_BROADCAST': AUDIT_ACTION_CATEGORIES.NOTIFICATION,
  
  // Review & Coupon (placed in appropriate categories)
  'REVIEW_CREATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'REVIEW_UPDATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'REVIEW_DELETE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'REVIEW_MODERATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'REVIEW_REPORT': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'COUPON_CREATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'COUPON_UPDATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'COUPON_DELETE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'COUPON_APPLY': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'OFFER_CREATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'OFFER_UPDATE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'OFFER_DELETE': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'FLASH_SALE_START': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  'FLASH_SALE_END': AUDIT_ACTION_CATEGORIES.PRODUCT_MANAGEMENT,
  
  // Permission & Role
  'PERMISSION_GRANT': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'PERMISSION_REVOKE': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'ROLE_CREATE': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'ROLE_UPDATE': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'ROLE_DELETE': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'ROLE_ASSIGN': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'ROLE_REVOKE': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  
  // Support
  'TICKET_CREATE': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'TICKET_UPDATE': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'TICKET_RESOLVE': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
  'TICKET_ASSIGN': AUDIT_ACTION_CATEGORIES.SYSTEM_MANAGEMENT,
} as const;

// ============================================================
// Default Severity Mapping (For automatic severity assignment)
// ============================================================

/**
 * ✅ ENTERPRISE: Map actions to default severity levels
 */
export const AUDIT_ACTION_DEFAULT_SEVERITY: Record<AuditActionValue, AuditSeverityValue> = {
  // Authentication
  'LOGIN': 'INFO',
  'LOGIN_FAILED': 'WARNING',
  'LOGOUT': 'INFO',
  'REGISTER': 'INFO',
  'REGISTER_FAILED': 'WARNING',
  'PASSWORD_CHANGE': 'INFO',
  'PASSWORD_RESET': 'INFO',
  'PASSWORD_RESET_REQUEST': 'INFO',
  'PASSWORD_RESET_FAILED': 'WARNING',
  'MFA_ENABLE': 'INFO',
  'MFA_DISABLE': 'INFO',
  'MFA_VERIFY': 'INFO',
  'MFA_VERIFY_FAILED': 'WARNING',
  'MFA_BACKUP_CODE_USED': 'INFO',
  'MFA_RECOVERY_USED': 'WARNING',
  'SESSION_CREATED': 'INFO',
  'SESSION_REVOKED': 'INFO',
  'SESSION_EXPIRED': 'INFO',
  'SESSION_TRANSFER': 'INFO',
  
  // User Management
  'USER_CREATE': 'INFO',
  'USER_UPDATE': 'INFO',
  'USER_DELETE': 'INFO',
  'USER_SUSPEND': 'WARNING',
  'USER_ACTIVATE': 'INFO',
  'USER_BAN': 'CRITICAL',
  'USER_UNBAN': 'INFO',
  'USER_VERIFY_EMAIL': 'INFO',
  'USER_VERIFY_PHONE': 'INFO',
  'USER_KYC_VERIFY': 'INFO',
  'USER_ROLE_ASSIGN': 'INFO',
  'USER_ROLE_REVOKE': 'INFO',
  'USER_IMPERSONATE': 'CRITICAL',
  'USER_MERGE': 'WARNING',
  'USER_EXPORT': 'INFO',
  'USER_IMPORT': 'INFO',
  'SOCIAL_ACCOUNT_LINK': 'INFO',
  'SOCIAL_ACCOUNT_UNLINK': 'INFO',
  'SOCIAL_ACCOUNT_SUSPEND': 'WARNING',
  'SOCIAL_ACCOUNT_REACTIVATE': 'INFO',
  'SOCIAL_ACCOUNT_INFO_UPDATE': 'INFO',
  
  // Product Management
  'PRODUCT_CREATE': 'INFO',
  'PRODUCT_UPDATE': 'INFO',
  'PRODUCT_DELETE': 'INFO',
  'PRODUCT_PUBLISH': 'INFO',
  'PRODUCT_UNPUBLISH': 'INFO',
  'PRODUCT_APPROVE': 'INFO',
  'PRODUCT_REJECT': 'INFO',
  'PRODUCT_FEATURE': 'INFO',
  'PRODUCT_UNFEATURE': 'INFO',
  'PRODUCT_PRICE_UPDATE': 'INFO',
  'PRODUCT_STOCK_UPDATE': 'INFO',
  'PRODUCT_BULK_UPDATE': 'INFO',
  'PRODUCT_IMPORT': 'INFO',
  'PRODUCT_EXPORT': 'INFO',
  'CATEGORY_CREATE': 'INFO',
  'CATEGORY_UPDATE': 'INFO',
  'CATEGORY_DELETE': 'INFO',
  'BRAND_CREATE': 'INFO',
  'BRAND_UPDATE': 'INFO',
  'BRAND_DELETE': 'INFO',
  
  // Order Management
  'ORDER_CREATE': 'INFO',
  'ORDER_UPDATE': 'INFO',
  'ORDER_CANCEL': 'INFO',
  'ORDER_REFUND': 'INFO',
  'ORDER_APPROVE': 'INFO',
  'ORDER_REJECT': 'INFO',
  'ORDER_SHIP': 'INFO',
  'ORDER_DELIVER': 'INFO',
  'ORDER_STATUS_CHANGE': 'INFO',
  'ORDER_BULK_UPDATE': 'INFO',
  'ORDER_EXPORT': 'INFO',
  
  // Payment Management
  'PAYMENT_INITIATE': 'INFO',
  'PAYMENT_SUCCESS': 'INFO',
  'PAYMENT_FAILED': 'WARNING',
  'PAYMENT_REFUND': 'INFO',
  'PAYMENT_VOID': 'INFO',
  'PAYMENT_CAPTURE': 'INFO',
  'PAYMENT_VERIFY': 'INFO',
  'BKASH_PAYMENT_INITIATE': 'INFO',
  'BKASH_PAYMENT_SUCCESS': 'INFO',
  'BKASH_PAYMENT_FAILED': 'WARNING',
  'BKASH_PAYMENT_REFUND': 'INFO',
  'NAGAD_PAYMENT_INITIATE': 'INFO',
  'NAGAD_PAYMENT_SUCCESS': 'INFO',
  'NAGAD_PAYMENT_FAILED': 'WARNING',
  'NAGAD_PAYMENT_REFUND': 'INFO',
  'ROCKET_PAYMENT_INITIATE': 'INFO',
  'ROCKET_PAYMENT_SUCCESS': 'INFO',
  'ROCKET_PAYMENT_FAILED': 'WARNING',
  'ROCKET_PAYMENT_REFUND': 'INFO',
  'SSLCOMMERZ_PAYMENT_SUCCESS': 'INFO',
  'SSLCOMMERZ_PAYMENT_FAILED': 'WARNING',
  'SSLCOMMERZ_PAYMENT_REFUND': 'INFO',
  
  // Vendor Management
  'VENDOR_CREATE': 'INFO',
  'VENDOR_UPDATE': 'INFO',
  'VENDOR_VERIFY': 'INFO',
  'VENDOR_SUSPEND': 'WARNING',
  'VENDOR_ACTIVATE': 'INFO',
  'VENDOR_PAYOUT': 'INFO',
  'VENDOR_COMMISSION_UPDATE': 'INFO',
  'SHOP_CREATE': 'INFO',
  'SHOP_UPDATE': 'INFO',
  'SHOP_DELETE': 'INFO',
  
  // Delivery Management
  'DELIVERY_ASSIGN': 'INFO',
  'DELIVERY_PICKUP': 'INFO',
  'DELIVERY_IN_TRANSIT': 'INFO',
  'DELIVERY_DELIVERED': 'INFO',
  'DELIVERY_FAILED': 'WARNING',
  'DELIVERY_RETURN': 'INFO',
  
  // System Management
  'SYSTEM_CONFIG_UPDATE': 'WARNING',
  'SYSTEM_CACHE_CLEAR': 'INFO',
  'SYSTEM_QUEUE_PURGE': 'WARNING',
  'SYSTEM_QUEUE_RETRY': 'INFO',
  'SYSTEM_BACKUP_CREATE': 'INFO',
  'SYSTEM_BACKUP_RESTORE': 'CRITICAL',
  'SYSTEM_MAINTENANCE_START': 'WARNING',
  'SYSTEM_MAINTENANCE_END': 'INFO',
  'SYSTEM_HEALTH_CHECK': 'INFO',
  
  // Security
  'SECURITY_ALERT': 'CRITICAL',
  'IP_BLOCK': 'WARNING',
  'IP_UNBLOCK': 'INFO',
  'DEVICE_BLOCK': 'WARNING',
  'DEVICE_UNBLOCK': 'INFO',
  'RATE_LIMIT_CHANGE': 'WARNING',
  'ACCOUNT_LOCK': 'WARNING',
  'ACCOUNT_UNLOCK': 'INFO',
  'BRUTE_FORCE_DETECTED': 'CRITICAL',
  'SUSPICIOUS_ACTIVITY_DETECTED': 'CRITICAL',
  
  // Data Management
  'DATA_EXPORT': 'INFO',
  'DATA_IMPORT': 'INFO',
  'REPORT_GENERATE': 'INFO',
  'REPORT_SCHEDULE': 'INFO',
  'REPORT_DELETE': 'INFO',
  'INVENTORY_UPDATE': 'INFO',
  'INVENTORY_ADJUST': 'INFO',
  'INVENTORY_RESERVE': 'INFO',
  'INVENTORY_RELEASE': 'INFO',
  'INVENTORY_BULK_UPDATE': 'INFO',
  'INVENTORY_LOW_STOCK_ALERT': 'WARNING',
  
  // Notification
  'NOTIFICATION_SEND': 'INFO',
  'NOTIFICATION_BROADCAST': 'INFO',
  
  // Review
  'REVIEW_CREATE': 'INFO',
  'REVIEW_UPDATE': 'INFO',
  'REVIEW_DELETE': 'INFO',
  'REVIEW_MODERATE': 'INFO',
  'REVIEW_REPORT': 'INFO',
  
  // Coupon & Offer
  'COUPON_CREATE': 'INFO',
  'COUPON_UPDATE': 'INFO',
  'COUPON_DELETE': 'INFO',
  'COUPON_APPLY': 'INFO',
  'OFFER_CREATE': 'INFO',
  'OFFER_UPDATE': 'INFO',
  'OFFER_DELETE': 'INFO',
  'FLASH_SALE_START': 'INFO',
  'FLASH_SALE_END': 'INFO',
  
  // Permission & Role
  'PERMISSION_GRANT': 'WARNING',
  'PERMISSION_REVOKE': 'WARNING',
  'ROLE_CREATE': 'INFO',
  'ROLE_UPDATE': 'INFO',
  'ROLE_DELETE': 'WARNING',
  'ROLE_ASSIGN': 'INFO',
  'ROLE_REVOKE': 'INFO',
  
  // Support
  'TICKET_CREATE': 'INFO',
  'TICKET_UPDATE': 'INFO',
  'TICKET_RESOLVE': 'INFO',
  'TICKET_ASSIGN': 'INFO',
} as const;

// packages/shared-constants/src/audit.constants.ts

/**
 * Audit Configuration Constants
 * Enterprise Grade for vubon.com.bd - Bangladesh's #1 E-commerce
 */
export const AUDIT_CONFIG = {
  // ========== Retention Settings ==========
  /** Default retention period in days */
  DEFAULT_RETENTION_DAYS: 90,
  
  /** Maximum retention period in days */
  MAX_RETENTION_DAYS: 365,
  
  /** Minimum retention period in days */
  MIN_RETENTION_DAYS: 7,
  
  /** ✅ NEW: Retention days (alias for DEFAULT_RETENTION_DAYS) */
  RETENTION_DAYS: 90,

  // ========== Export Settings ==========
  /** Default export format */
  DEFAULT_EXPORT_FORMAT: 'json' as const,
  
  /** Supported export formats */
  SUPPORTED_EXPORT_FORMATS: ['json', 'csv', 'xlsx'] as const,
  
  /** Maximum export size in MB */
  MAX_EXPORT_SIZE_MB: 100,
  
  /** Default export expiry in hours */
  DEFAULT_EXPORT_EXPIRY_HOURS: 24,

  // ========== Batch Processing Settings ==========
  /** Audit log batch size for processing */
  BATCH_SIZE: 1000,
  
  /** ✅ NEW: Maximum batch size (alias for BATCH_SIZE) */
  MAX_BATCH_SIZE: 1000,
  
  /** ✅ NEW: Flush interval in milliseconds */
  FLUSH_INTERVAL_MS: 5000,

  // ========== Storage Settings ==========
  /** Storage type: 'database' | 'elasticsearch' | 'file' */
  STORAGE_TYPE: 'database' as const,
  
  /** Whether compression is enabled */
  COMPRESSION_ENABLED: false,

  // ========== Logging Settings ==========
  /** Whether audit logging is enabled */
  ENABLED: true,
  
  /** Whether to log asynchronously */
  ASYNC_LOGGING: true,
  
  /** Whether to log sensitive data (PII) */
  LOG_SENSITIVE_DATA: false,
  
  /** Whether to log request body */
  LOG_REQUEST_BODY: false,
  
  /** Whether to log response body */
  LOG_RESPONSE_BODY: false,

  // ========== Bangladesh Specific Settings ==========
  /** Whether to log district information */
  LOG_DISTRICT_INFO: true,
  
  /** Whether to log mobile operator information */
  LOG_MOBILE_OPERATOR: true,
  
  /** Whether to log network type information */
  LOG_NETWORK_TYPE: false,

  // ========== Anomaly Detection Settings ==========
  /** Whether anomaly detection is enabled */
  ANOMALY_DETECTION_ENABLED: true,
  
  /** Anomaly detection sensitivity level (1-10) */
  ANOMALY_SENSITIVITY: 5,

  // ========== Dashboard Settings ==========
  /** Whether dashboard is enabled */
  DASHBOARD_ENABLED: true,
  
  /** Dashboard refresh interval in seconds */
  DASHBOARD_REFRESH_INTERVAL_SECONDS: 30,

  // ========== Compliance Settings ==========
  /** Whether compliance reporting is enabled */
  COMPLIANCE_REPORTING_ENABLED: true,

  // ========== Cleanup Settings ==========
  /** Cleanup schedule (cron expression) */
  CLEANUP_SCHEDULE: '0 0 * * *', // Daily at midnight
  
  /** Archive after days */
  ARCHIVE_AFTER_DAYS: 30,
} as const;

// ============================================================
// ✅ Type Exports
// ============================================================

/**
 * Audit export format type
 */
export type AuditExportFormat = typeof AUDIT_CONFIG.SUPPORTED_EXPORT_FORMATS[number];

/**
 * Audit storage type
 */
export type AuditStorageType = typeof AUDIT_CONFIG.STORAGE_TYPE;

// ============================================================
// ✅ Also export individual constants for backward compatibility
// ============================================================

export const {
  RETENTION_DAYS,
  BATCH_SIZE,
  MAX_BATCH_SIZE,
  FLUSH_INTERVAL_MS,
  ENABLED,
  ASYNC_LOGGING,
  LOG_SENSITIVE_DATA,
  LOG_REQUEST_BODY,
  LOG_RESPONSE_BODY,
  STORAGE_TYPE,
  COMPRESSION_ENABLED,
  LOG_DISTRICT_INFO,
  LOG_MOBILE_OPERATOR,
  LOG_NETWORK_TYPE,
  ANOMALY_DETECTION_ENABLED,
  ANOMALY_SENSITIVITY,
  DASHBOARD_ENABLED,
  DASHBOARD_REFRESH_INTERVAL_SECONDS,
  COMPLIANCE_REPORTING_ENABLED,
  CLEANUP_SCHEDULE,
  ARCHIVE_AFTER_DAYS,
} = AUDIT_CONFIG;

// ============================================================
// Type Exports (For TypeScript type safety)
// ============================================================

// All types are already exported as type aliases at the top of the file

// ============================================================
// ENTERPRISE SUMMARY
// ============================================================
// 
// Enterprise Features:
// 1. ✅ 100+ audit actions covering all domains
// 2. ✅ Bangladesh specific payment actions (bKash, Nagad, Rocket, SSLCOMMERZ)
// 3. ✅ 11 audit sources covering all entry points
// 4. ✅ 6 severity levels (DEBUG to EMERGENCY)
// 5. ✅ 30+ entity types covering all domain entities
// 6. ✅ Action categorization for UI grouping
// 7. ✅ Default severity mapping for automatic assignment
// 8. ✅ Type-safe with 'as const' for literal types
// 9. ✅ Framework-agnostic - works with any audit system
// 10. ✅ Extensible for future domains
// 11. ✅ Consistent naming convention across all services
// 12. ✅ Single Source of Truth for all audit constants
// 13. ✅ Multi-language ready (message keys can be mapped to translations)
// 14. ✅ GDPR/Compliance ready (audit trail support)
// 15. ✅ Production-ready for enterprise ecommerce
// 
// Bangladesh Specific:
// - bKash, Nagad, Rocket payment actions
// - SSLCOMMERZ payment actions
// - District, Upazila entity types
// - MFS_ACCOUNT entity type
// - Local payment gateway actions
// - Bangladesh market-specific audit tracking
// 
// Security Compliance:
// - GDPR audit trail ready
// - PCI DSS payment actions tracking
// - Security incident tracking
// - User access monitoring
// - System change tracking
// 
// ============================================================
