/**
 * Shared constants module entry point
 * Exports all constants from all sub-modules
 */

// Re-export everything from authentication module
export * from './authentication';

// Re-export everything from SEO AI module
export * from './seo-ai';

// Re-export everything from common module
export * from './common';

// Re-export everything from analytics-reporting module
export * from './analytics-reporting';

// Re-export everything from Flash-Sales-Deals module
export * from './Flash-Sales-Deals';

// Content-Marketing থেকে শুধু অনন্য এক্সপোর্ট - export * সরিয়ে দেওয়া হয়েছে
export {
  // Content specific
  CONTENT_MODULE_NAME,
  DEFAULT_CONTENT_STATUS,
  CONTENT_SORT_FIELDS,
  CONTENT_PAGE_SIZE,
  MAX_CONTENT_TITLE_LENGTH,
  MAX_CONTENT_EXCERPT_LENGTH,
  MAX_CONTENT_BODY_LENGTH,
  CONTENT_TYPES,
  CONTENT_TYPE_LABELS,
  CONTENT_STATUSES,
  CONTENT_STATUS_COLORS,
  CONTENT_STATUS_LABELS,
  DEFAULT_CATEGORIES,
  MAX_CATEGORY_NAME_LENGTH,
  MAX_CATEGORY_DESCRIPTION_LENGTH,
  CATEGORY_SORT_FIELDS,
  MAX_TAG_NAME_LENGTH,
  MIN_TAG_NAME_LENGTH,
  MAX_TAGS_PER_CONTENT,
  POPULAR_TAGS_LIMIT,
  TAG_SORT_FIELDS,
  CONTENT_FORMATS,
  DEFAULT_CONTENT_FORMAT,
  SUPPORTED_FORMATS,
  FORMAT_EXTENSIONS,
  FORMAT_MIME_TYPES,
  FORMAT_LABELS,
  SUPPORTED_LANGUAGES,
  LANGUAGE_NAMES,
  DEFAULT_LANGUAGE,
  LANGUAGE_CODES,
  LICENSE_TYPES,
  LICENSE_URLS,
  DEFAULT_LICENSE,
  LICENSE_LABELS,
  LICENSE_DESCRIPTIONS,
  
  // Blog specific
  BLOG_MODULE_NAME,
  DEFAULT_BLOG_STATUS,
  BLOG_SORT_FIELDS,
  BLOG_PAGE_SIZE,
  MAX_BLOG_TITLE_LENGTH,
  MAX_BLOG_EXCERPT_LENGTH,
  MAX_BLOG_BODY_LENGTH,
  BLOG_READING_TIME_WORDS_PER_MINUTE,
  DEFAULT_BLOG_COVER_IMAGE,
  BLOG_STATUSES,
  BLOG_STATUS_COLORS,
  BLOG_STATUS_LABELS,
  PUBLISHABLE_STATUSES,
  DEFAULT_BLOG_CATEGORIES,
  MAX_BLOG_CATEGORY_NAME_LENGTH,
  MAX_BLOG_CATEGORY_DESCRIPTION_LENGTH,
  MAX_BLOG_TAG_NAME_LENGTH,
  MAX_BLOG_TAGS_PER_POST,
  POPULAR_BLOG_TAGS_LIMIT,
  
  // Page specific
  PAGE_MODULE_NAME,
  DEFAULT_PAGE_STATUS,
  DEFAULT_PAGE_TEMPLATE,
  PAGE_SORT_FIELDS,
  MAX_PAGE_TITLE_LENGTH,
  MAX_PAGE_BODY_LENGTH,
  SYSTEM_PAGES,
  PAGE_STATUSES,
  PAGE_STATUS_COLORS,
  PAGE_TEMPLATES,
  PAGE_TEMPLATE_LABELS,
  PAGE_LAYOUTS,
  PAGE_LAYOUT_LABELS,
  
  // SEO specific
  SEO_MODULE_NAME,
  DEFAULT_SEO_TITLE_LENGTH,
  DEFAULT_SEO_DESCRIPTION_LENGTH,
  MAX_SEO_TITLE_LENGTH,
  MAX_SEO_DESCRIPTION_LENGTH,
  MAX_SEO_KEYWORDS,
  DEFAULT_OG_IMAGE,
  
  // Content helper functions
  getContentTypeLabel,
  getAllContentTypes,
  isValidContentType,
  getContentStatusColor,
  getContentStatusLabel,
  getAllContentStatuses,
  isValidContentStatus,
  isPublishedStatus,
  isDeletedStatus,
  isValidCategoryName,
  isValidCategoryDescription,
  generateCategorySlug,
  isValidTagName,
  generateTagSlug,
  isValidFormat,
  isSupportedFormat,
  getFormatExtension,
  getFormatMimeType,
  getFormatLabel,
  isValidLanguage,
  getLanguageName,
  isValidLicense,
  getLicenseUrl,
  getLicenseLabel,
  
  // Blog helper functions
  calculateReadingTime,
  generateBlogSlug,
  isValidBlogTitle,
  isValidBlogExcerpt,
  isValidBlogBody,
  isBlogPublished,
  isBlogEditable,
  getBlogStatusColor,
  getBlogStatusLabel,
  getAllBlogStatuses,
  isValidBlogStatus,
  isPublishableStatus,
  canTransitionTo,
  generateBlogCategorySlug,
  isValidBlogCategoryName,
  isValidBlogCategoryDescription,
  
  // Page helper functions
  generatePageSlug,
  isValidPageTitle,
  isValidPageBody,
  isPagePublished,
  isPageEditable,
  getPageStatusColor,
  getAllPageStatuses,
  isValidPageStatus,
  isValidPageTemplate,
  getPageTemplateLabel,
  getAllPageTemplates,
  isValidPageLayout,
  getPageLayoutLabel,
  getAllPageLayouts,
  
  // SEO helper functions
  isValidSeoTitle,
  isValidSeoDescription,
  isValidSeoKeywords,
  truncateSeoTitle,
  truncateSeoDescription,
  formatSeoTitle,
  generateSeoMetaTags,
  getDefaultSeoData,
  isValidSeoData,
  
  // Type exports
  type ContentStatus,
  type ContentType,
  type ContentSortField,
  type ContentStatusColor,
  type ContentStatusLabel,
  type ContentTypeLabel,
  type ContentFormat,
  type SupportedFormat,
  type Language,
  type LanguageCode,
  type LicenseType,
  type Category,
  type CategorySortField,
  type TagSortField,
  type BlogStatus,
  type BlogSortField,
  type BlogCategory,
  type PageStatus,
  type PageSortField,
  type PageTemplate,
  type PageLayout,
  type SystemPage,
  type SeoData,
  type SeoMetaTags,
} from './Content-Marketing/content';

// Marketing specific exports (যেগুলো analytics-reporting-এ নেই)
export {
  MARKETING_MODULE_NAME,
  DEFAULT_CAMPAIGN_STATUS,
  MARKETING_SORT_FIELDS,
  CAMPAIGN_MODULE_NAME,
  MAX_CAMPAIGN_NAME_LENGTH,
  MAX_CAMPAIGN_DESCRIPTION_LENGTH,
  CAMPAIGN_SORT_FIELDS,
  CAMPAIGN_TYPES,
  CAMPAIGN_TYPE_LABELS,
  CAMPAIGN_STATUSES,
  CAMPAIGN_STATUS_COLORS,
  CAMPAIGN_STATUS_LABELS,
  CAMPAIGN_CHANNELS,
  CAMPAIGN_CHANNEL_LABELS,
  BUDGET_CURRENCIES,
  DEFAULT_CURRENCY,
  MIN_CAMPAIGN_BUDGET,
  MAX_CAMPAIGN_BUDGET,
  TARGET_AUDIENCES,
  TARGET_TYPE_LABELS,
  PROMOTION_MODULE_NAME,
  DEFAULT_PROMOTION_STATUS,
  MAX_PROMOTION_NAME_LENGTH,
  MAX_DISCOUNT_PERCENTAGE,
  MIN_DISCOUNT_AMOUNT,
  PROMOTION_TYPES,
  PROMOTION_TYPE_LABELS,
  PROMOTION_STATUSES,
  PROMOTION_STATUS_COLORS,
  PROMOTION_STATUS_LABELS,
  DISCOUNT_TYPES,
  DISCOUNT_TYPE_LABELS,
  RESTRICTION_TYPES,
  RESTRICTION_LABELS,
  PROMOTION_TARGETS,
  PROMOTION_TARGET_LABELS,
  AFFILIATE_MODULE_NAME,
  DEFAULT_AFFILIATE_STATUS,
  MAX_AFFILIATE_NAME_LENGTH,
  MIN_COMMISSION_RATE,
  MAX_COMMISSION_RATE,
  AFFILIATE_STATUSES,
  AFFILIATE_STATUS_COLORS,
  AFFILIATE_STATUS_LABELS,
  AFFILIATE_TYPES,
  AFFILIATE_TYPE_LABELS,
  COMMISSION_TYPES,
  DEFAULT_COMMISSION_TYPE,
  COMMISSION_PAYOUT_SCHEDULES,
  PAYOUT_METHODS,
  MIN_PAYOUT_AMOUNT,
  MAX_PAYOUT_AMOUNT,
  PAYOUT_STATUSES,
  PAYOUT_STATUS_COLORS,
  PAYOUT_STATUS_LABELS,
  REFERRAL_MODULE_NAME,
  DEFAULT_REFERRAL_STATUS,
  MAX_REFERRAL_CODE_LENGTH,
  MAX_REFERRAL_REWARDS,
  REFERRAL_STATUSES,
  REFERRAL_STATUS_COLORS,
  REFERRAL_STATUS_LABELS,
  REFERRAL_TYPES,
  REFERRAL_TYPE_LABELS,
  REWARD_TYPES,
  REWARD_TYPE_LABELS,
  LOYALTY_MODULE_NAME,
  DEFAULT_LOYALTY_STATUS,
  POINTS_PER_PURCHASE,
  POINTS_REDEMPTION_RATE,
  LOYALTY_STATUSES,
  LOYALTY_STATUS_COLORS,
  LOYALTY_STATUS_LABELS,
  LOYALTY_TYPES,
  LOYALTY_TYPE_LABELS,
  LOYALTY_TIERS,
  TIER_BENEFITS,
  TIER_UPGRADE_REQUIREMENTS,
  TIER_DISCOUNT_RATES,
  POINTS_EARNING_RULES,
  POINTS_EXPIRY_DAYS,
  MIN_POINTS_REDEEM,
  REWARD_CATEGORIES,
  REWARD_AVAILABILITY,
  REWARD_CATEGORY_LABELS,
  REWARD_AVAILABILITY_LABELS,
  EMAIL_MARKETING_MODULE_NAME,
  DEFAULT_EMAIL_STATUS,
  MAX_EMAIL_SUBJECT_LENGTH,
  MAX_EMAIL_BODY_LENGTH,
  MAX_EMAIL_RECIPIENTS,
  EMAIL_TYPES,
  EMAIL_TYPE_LABELS,
  EMAIL_STATUSES,
  EMAIL_STATUS_COLORS,
  EMAIL_STATUS_LABELS,
  SMS_MARKETING_MODULE_NAME,
  DEFAULT_SMS_STATUS,
  MAX_SMS_BODY_LENGTH,
  MAX_SMS_RECIPIENTS,
  SMS_TYPES,
  SMS_TYPE_LABELS,
  SMS_STATUSES,
  SMS_STATUS_COLORS,
  SMS_STATUS_LABELS,
  SOCIAL_MEDIA_MODULE_NAME,
  DEFAULT_SOCIAL_STATUS,
  MAX_POST_LENGTH,
  MAX_HASHTAGS,
  SOCIAL_PLATFORMS,
  PLATFORM_LABELS,
  PLATFORM_ICONS,
  PLATFORM_COLORS,
  SOCIAL_STATUSES,
  SOCIAL_STATUS_COLORS,
  SOCIAL_STATUS_LABELS,
  POST_TYPES,
  POST_TYPE_LABELS,
  SEO_MARKETING_MODULE_NAME,
  DEFAULT_SEO_STATUS,
  SEO_TOOLS,
  SEO_TYPES,
  SEO_TYPE_LABELS,
  SEO_STATUSES,
  SEO_STATUS_COLORS,
  SEO_STATUS_LABELS,
  LEAD_GENERATION_MODULE_NAME,
  DEFAULT_LEAD_STATUS,
  MAX_LEAD_SCORE,
  LEAD_SCORE_THRESHOLDS,
  LEAD_STATUSES,
  LEAD_STATUS_COLORS,
  LEAD_STATUS_LABELS,
  LEAD_SOURCES,
  LEAD_SOURCE_LABELS,
  LEAD_SOURCE_ICONS,
  LEAD_SOURCE_COLORS,
  LEAD_GEN_STATUSES,
  LEAD_GEN_STATUS_COLORS,
  LEAD_GEN_STATUS_LABELS,
  LEAD_GEN_TYPES,
  LEAD_GEN_TYPE_LABELS,
  MARKETING_ANALYTICS_MODULE_NAME,
  AUTOMATION_MODULE_NAME,
  DEFAULT_AUTOMATION_STATUS,
  MAX_WORKFLOW_STEPS,
  AUTOMATION_TYPES,
  AUTOMATION_TYPE_LABELS,
  AUTOMATION_TYPE_ICONS,
  AUTOMATION_TYPE_COLORS,
  TRIGGER_TYPES,
  TRIGGER_EVENTS,
  TRIGGER_TYPE_LABELS,
  TRIGGER_EVENT_LABELS,
  TRIGGER_TYPE_ICONS,
  TRIGGER_EVENT_ICONS,
  TRIGGER_TYPE_COLORS,
  TRIGGER_EVENT_COLORS,
  ACTION_TYPES,
  ACTION_TYPE_LABELS,
  ACTION_TYPE_ICONS,
  ACTION_TYPE_COLORS,
  PERMISSIONS,
  PERMISSION_LABELS,
  PERMISSION_CATEGORIES,
  PERMISSION_ACTIONS,
  PERMISSION_GROUPS,
  
  // Marketing helper functions
  isValidMarketingSortField,
  isValidCampaignStatus,
  isValidCampaignName,
  isValidBudget,
  isCampaignActive,
  isCampaignCompleted,
  calculateRemainingBudget,
  calculateSpentPercentage,
  isCampaignEditable,
  getDefaultCampaignStatus,
  generateCampaignSlug,
  isValidCampaignType,
  getCampaignTypeLabel,
  getAllCampaignTypes,
  getCampaignStatusColor,
  getCampaignStatusLabel,
  getAllCampaignStatuses,
  canCampaignTransitionTo,
  getCampaignChannelLabel,
  getAllCampaignChannels,
  isValidCampaignChannel,
  getCurrencySymbol,
  getCurrencyName,
  getAllCurrencies,
  getDefaultCurrency,
  convertCurrency,
  createBudgetManagement,
  getBudgetStatus,
  formatBudget,
  getBudgetColor,
  getTargetAudienceLabel,
  getAllTargetAudiences,
  isValidTargetAudience,
  getDefaultTargetAudience,
  isValidPromotionStatus,
  isValidPromotionName,
  isValidDiscountPercentage,
  isValidDiscountAmount,
  generatePromotionSlug,
  isPromotionActive,
  isPromotionExpired,
  isPromotionLimitReached,
  calculateDiscount,
  isValidDiscountType,
  getPromotionTypeLabel,
  getAllPromotionTypes,
  isValidPromotionType,
  getPromotionStatusColor,
  getPromotionStatusLabel,
  getAllPromotionStatuses,
  canPromotionTransitionTo,
  getRestrictionLabel,
  getAllRestrictionTypes,
  isValidRestrictionType,
  isValidAffiliateStatus,
  isValidAffiliateType,
  isValidAffiliateName,
  isValidCommissionRate,
  generateReferralCode,
  isAffiliateActive,
  isAffiliateEditable,
  updateAffiliateEarnings,
  getAffiliateStatusColor,
  getAffiliateStatusLabel,
  getAllAffiliateStatuses,
  getAffiliateTypeLabel,
  getAllAffiliateTypes,
  getCommissionTypeLabel,
  isValidCommissionType,
  getPayoutScheduleLabel,
  getDefaultCommissionType,
  calculateCommission,
  getPayoutMethodLabel,
  isValidPayoutMethod,
  getAllPayoutMethods,
  isValidPayoutAmount,
  getPayoutStatusLabel,
  getDefaultPayoutMethod,
  isValidReferralStatus,
  isValidRewardType,
  isValidRewardStatus,
  isReferralActive,
  isRewardClaimable,
  isRewardExpired,
  claimReward,
  getRewardTypeLabel,
  getRewardStatusLabel,
  getDefaultReferralStatus,
  getAllRewardTypes,
  isValidLoyaltyStatus,
  getTierName,
  getTierRequiredPoints,
  getTierDiscountRate,
  getTierIcon,
  addPoints,
  redeemPoints,
  calculateValueFromPoints,
  calculatePointsFromValue,
  isLoyaltyActive,
  isValidPoints,
  getDefaultLoyaltyStatus,
  getAllTiers,
  getLoyaltyStatusColor,
  getLoyaltyStatusLabel,
  getAllLoyaltyStatuses,
  getLoyaltyTypeLabel,
  getAllLoyaltyTypes,
  isValidLoyaltyType,
  getPointsEarningRuleLabel,
  getAllPointsEarningRules,
  isValidPointsEarningRule,
  getPointsEarningValue,
  getPointsEarningMax,
  calculatePointsExpiryDate,
  isPointsExpired,
  isPointsRedeemable,
  getRedeemablePoints,
  getRewardCategoryLabel,
  getRewardAvailabilityLabel,
  getAllRewardCategories,
  getAllRewardAvailabilities,
  isValidRewardCategory,
  isValidRewardAvailability,
  isRewardAvailable,
  redeemReward,
  isValidEmailStatus,
  isValidEmailType,
  isValidEmailPlatform,
  isValidEmailSubject,
  isValidEmailBody,
  isValidEmailRecipients,
  calculateOpenRate,
  calculateClickRate,
  calculateBounceRate,
  isEmailSent,
  isEmailScheduled,
  isEmailDraft,
  getDefaultEmailStatus,
  getAllEmailTypes,
  getAllEmailPlatforms,
  getEmailTypeLabel,
  getEmailPlatformLabel,
  getEmailStatusColor,
  getEmailStatusLabel,
  getAllEmailStatuses,
  canEmailTransitionTo,
  getEmailStatusIcon,
  isValidSmsStatus,
  isValidSmsType,
  isValidSmsProvider,
  isValidSmsBody,
  isValidSmsRecipients,
  isValidPhoneNumber,
  calculateSmsDeliveryRate,
  calculateSmsFailureRate,
  isSmsSent,
  isSmsScheduled,
  isSmsDraft,
  countSmsCharacters,
  countSmsParts,
  getDefaultSmsStatus,
  getAllSmsTypes,
  getAllSmsProviders,
  getSmsTypeLabel,
  getSmsProviderLabel,
  getSmsStatusColor,
  getSmsStatusLabel,
  getAllSmsStatuses,
  canSmsTransitionTo,
  getSmsStatusIcon,
  isValidSocialPlatform,
  isValidSocialStatus,
  isValidPostContent,
  isValidHashtags,
  getPlatformName,
  getPlatformIcon,
  getPlatformColor,
  getPlatformMaxLength,
  calculateEngagementRate,
  calculateViralityScore,
  isPostPublished,
  isPostScheduled,
  isPostDraft,
  getDefaultSocialStatus,
  getAllSocialPlatforms,
  getPlatformMaxHashtags,
  getSocialStatusColor,
  getSocialStatusLabel,
  getAllSocialStatuses,
  canSocialTransitionTo,
  getSocialStatusIcon,
  getPostTypeLabel,
  getAllPostTypes,
  isValidPostType,
  getDefaultPostType,
  isValidSeoStatus,
  isValidSeoTool,
  isValidSeoTaskType,
  isValidSeoPriority,
  getSeoToolLabel,
  getSeoTaskTypeLabel,
  getSeoPriorityLabel,
  getAllSeoTools,
  getAllSeoTaskTypes,
  getAllSeoPriorities,
  isSeoTaskCompleted,
  isSeoTaskDraft,
  calculateSeoProgress,
  getDefaultSeoStatus,
  getSeoToolIcon,
  getSeoTaskTypeIcon,
  getSeoPriorityColor,
  getSeoTypeLabel,
  getAllSeoTypes,
  isValidSeoType,
  getDefaultSeoType,
  getSeoTypeIcon,
  getSeoTypeColor,
  getSeoStatusColor,
  getSeoStatusLabel,
  getAllSeoStatuses,
  canSeoTransitionTo,
  getSeoStatusIcon,
  isValidLeadStatus,
  isValidLeadSource,
  isValidLeadScore,
  getLeadScoreCategory,
  getLeadScoreCategoryLabel,
  getLeadScoreCategoryColor,
  isHotLead,
  isWarmLead,
  isColdLead,
  isLeadConverted,
  convertLead,
  updateLeadScore,
  incrementLeadScore,
  decrementLeadScore,
  getDefaultLeadStatus,
  getAllLeadSources,
  getLeadSourceLabel,
  getLeadSourceIcon,
  getLeadStatusColor,
  getLeadStatusLabel,
  getAllLeadStatuses,
  canLeadTransitionTo,
  getLeadStatusIcon,
  getLeadGenStatusColor,
  getLeadGenStatusLabel,
  getAllLeadGenStatuses,
  isValidLeadGenStatus,
  getDefaultLeadGenStatus,
  getLeadGenTypeLabel,
  getAllLeadGenTypes,
  isValidLeadGenType,
  getDefaultLeadGenType,
  getLeadGenTypeIcon,
  getLeadGenTypeColor,
  isValidAutomationStatus,
  isValidAutomationTrigger,
  getAutomationTriggerLabel,
  getAllAutomationTriggers,
  isAutomationActive,
  isAutomationEditable,
  enableAutomation,
  disableAutomation,
  getDefaultAutomationStatus,
  getAutomationTriggerIcon,
  getAutomationTriggerColor,
  getAutomationTriggerDescription,
  getAutomationTypeLabel,
  getAutomationTypeIcon,
  getAutomationTypeColor,
  getAllAutomationTypes,
  isValidAutomationType,
  getDefaultAutomationType,
  getTriggerTypeLabel,
  getTriggerEventLabel,
  getTriggerTypeIcon,
  getTriggerEventIcon,
  getTriggerTypeColor,
  getTriggerEventColor,
  getAllTriggerTypes,
  getAllTriggerEvents,
  isValidTriggerType,
  isValidTriggerEvent,
  getDefaultTriggerType,
  getDefaultTriggerEvent,
  getActionTypeLabel,
  getActionTypeIcon,
  getActionTypeColor,
  getActionTypeCategory,
  getAllActionTypes,
  isValidActionType,
  getDefaultActionType,
  getPermissionLabel,
  getPermissionCategory,
  getPermissionAction,
  getAllPermissions,
  isValidPermission,
  getPermissionsByCategory,
  getPermissionDescription,
  getPermissionIcon,
  
  // Marketing Type exports
  type MarketingSortField,
  type CampaignStatus,
  type CampaignInterface,
  type CampaignMetadata,
  type CampaignType,
  type CampaignChannel,
  type Currency,
  type BudgetManagement,
  type BudgetStatus,
  type TargetAudience,
  type PromotionStatus,
  type PromotionType,
  type PromotionInterface,
  type PromotionMetadata,
  type DiscountType,
  type RestrictionType,
  type PromotionTarget,
  type AffiliateStatus,
  type AffiliateType,
  type AffiliateInterface,
  type AffiliateMetadata,
  type CommissionType,
  type CommissionPayoutSchedule,
  type CommissionInterface,
  type PayoutMethod,
  type PayoutInterface,
  type PayoutStatus,
  type PayoutMetadata,
  type ReferralStatus,
  type RewardType,
  type ReferralInterface,
  type RewardStatus,
  type LoyaltyStatus,
  type LoyaltyTier,
  type LoyaltyInterface,
  type LoyaltyType,
  type PointsEarningRule,
  type RewardCategory,
  type RewardAvailability,
  type RewardInterface,
  type EmailStatus,
  type EmailType,
  type EmailPlatform,
  type EmailInterface,
  type EmailMetadata,
  type EmailAttachment,
  type SmsStatus,
  type SmsType,
  type SmsProvider,
  type SmsInterface,
  type SmsMetadata,
  type SocialPlatform,
  type SocialStatus,
  type SocialPostInterface,
  type SocialMetadata,
  type PostType,
  type SeoStatus,
  type SeoTool,
  type SeoTaskType,
  type SeoPriority,
  type SeoInterface,
  type SeoMetadata,
  type SeoType,
  type LeadStatus,
  type LeadSource,
  type LeadInterface,
  type LeadMetadata,
  type LeadGenStatus,
  type LeadGenType,
  type AutomationStatus,
  type AutomationTrigger,
  type AutomationInterface,
  type AutomationType,
  type TriggerType,
  type TriggerEvent,
  type ActionType,
  type Permission,
} from './Content-Marketing/marketing';
