/**
/**
 * Shared constants module entry point
 * Exports all constants from all sub-modules
 */

// Export all auth constants
export {
  // Auth constants
  AUTH_COOKIE_NAMES,
  TOKEN_EXPIRY,
  PASSWORD_POLICY,
  USER_STATUS,
  LOGIN_ATTEMPT,
  SESSION_CONFIG,
  REFRESH_TOKEN_CONFIG,
  LOGOUT_SESSION_TYPES,
  LOGOUT_REASONS,
  EMAIL_VERIFICATION_CONFIG,
  PASSWORD_RESET_CONFIG,
  PROFILE_CONFIG,
  REGISTRATION_CONFIG,
  CSRF_CONFIG,
  RATE_LIMIT_CONFIG,
  AUTH_ERROR_MESSAGES,
  AUTH_SUCCESS_MESSAGES,
  AUTH_ROUTES,
  AUTH_STATUS_CODES,
  AUTH_CONFIG_DEFAULTS,
  AUTH_SECURITY_HEADERS,
  AUTH_EVENTS,

  // Role constants
  DEFAULT_ROLES,
  ADMIN_ROLES,
  ROLE_USER_STATUS,
  USER_STATUS_MESSAGES,
  PERMISSION_CATEGORIES,
  PERMISSION_OPERATIONS,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  ROLE_HIERARCHY,
  ROLE_DESCRIPTIONS,
  ROLE_COLORS,
  ROLE_PRIORITY,
  ROLE_VALIDATION,
  ROLE_STATUS,
  PERMISSION_VALIDATION,
  ROLE_EVENTS,
  ROLE_ERROR_MESSAGES,

  // Export regex constants
  EMAIL_REGEX,
  PASSWORD_REGEX,
  USERNAME_REGEX,
  PHONE_REGEX,
  URL_REGEX,
  IP_REGEX,
  DATE_REGEX,
  CREDIT_CARD_REGEX,
  VALIDATION_REGEX,
  SLUG_REGEX,
  FILE_EXTENSION_REGEX,
  SPECIAL_CHARS_REGEX,
  TEXT_REGEX,
  REGEX_UTILS,
  REGEX,
  ALL_REGEX,

  // security constants
  LOGIN_SECURITY,
  PASSWORD_SECURITY,
  TWO_FACTOR_SECURITY,
  CSRF_SECURITY,
  RATE_LIMIT_SECURITY,
  IP_SECURITY,
  SESSION_SECURITY,
  JWT_SECURITY,
  SECURITY_HEADERS,
  SECURITY_EVENTS,
  SECURITY_LEVELS,
  SECURITY_LEVEL_REQUIREMENTS,
  SECURITY_BREACH_RESPONSE,
  ENCRYPTION_SECURITY,
  AUDIT_SECURITY,
  DEFAULT_SECURITY_CONFIG,
  SECURITY_ERROR_MESSAGES,
  SECURITY_WARNING_MESSAGES,
  SECURITY_NOTIFICATIONS,

  // HTTP Status constants
  HTTP_STATUS_INFO,
  HTTP_STATUS_SUCCESS,
  HTTP_STATUS_REDIRECTION,
  HTTP_STATUS_CLIENT_ERROR,
  HTTP_STATUS_SERVER_ERROR,
  HTTP_STATUS,
  HTTP_STATUS_CATEGORIES,
  HTTP_STATUS_MESSAGES,
  AUTH_STATUS_CODES as AUTH_HTTP_STATUS_CODES,
  API_STATUS_CODES,
  HTTP_STATUS_UTILS,
  ALL_STATUS_CODES,
  HTTP_METHODS,
  HTTP_HEADERS,
} from './auth';

// Export all types
export type {
  // Auth types
  UserStatus,
  LogoutSessionType,
  LogoutReason,
  AuthErrorMessage,
  AuthSuccessMessage,
  AuthRoute,
  AuthStatusCode,
  JWTClaims,
  SessionData,
  DeviceInfo,
  LoginAttempt,
  TokenPayload,
  EmailVerificationData,
  PasswordResetData,
  AuthConfig,
  AuthEvent,

  // Role types
  DefaultRole,
  AdminRole,
  RoleUserStatus,
  UserStatusMessage,
  PermissionCategory,
  PermissionOperation,
  Permission,
  Role,
  UserRoleAssignment,
  PermissionCheck,
  RoleStatus,
  RoleEvent,
  RoleErrorMessage,

  // Export regex types
  EmailRegexPattern,
  PasswordRegexPattern,
  UsernameRegexPattern,
  PhoneRegexPattern,
  UrlRegexPattern,
  IpRegexPattern,
  DateRegexPattern,
  CreditCardRegexPattern,
  ValidationRegexPattern,
  SlugRegexPattern,
  FileExtensionRegexPattern,
  SpecialCharsRegexPattern,
  TextRegexPattern,

  // Security types
  SecurityLevel,
  SecurityConfig,
  SecurityErrorMessage,
  SecurityWarningMessage,
  SecurityNotification,

  // HTTP Status types
  HttpStatusCode,
  HttpStatusMessage,
  HttpStatusCategory,
  HttpStatus,
  HttpMethod,
  HttpHeader,
} from './auth';
