/**
 * Notification Digest Status Constants
 * Status definitions for notification digests
 */

export const NOTIFICATIONDIGEST_STATUS = {
  // Digest Statuses
  STATUSES: {
    DRAFT: 'draft',
    PENDING: 'pending',
    GENERATING: 'generating',
    GENERATED: 'generated',
    SENDING: 'sending',
    SENT: 'sent',
    DELIVERED: 'delivered',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    SCHEDULED: 'scheduled',
    PAUSED: 'paused',
    ON_HOLD: 'on_hold',
    PARTIAL: 'partial',
    EXPIRED: 'expired',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    DRAFT: '#6B7280',
    PENDING: '#F59E0B',
    GENERATING: '#3B82F6',
    GENERATED: '#10B981',
    SCHEDULED: '#3B82F6',
    SENDING: '#3B82F6',
    SENT: '#3B82F6',
    DELIVERED: '#10B981',
    FAILED: '#EF4444',
    CANCELLED: '#6B7280',
    ARCHIVED: '#6B7280',
    PAUSED: '#F59E0B',
    ON_HOLD: '#F59E0B',
    PARTIAL: '#F59E0B',
    EXPIRED: '#6B7280',
  } as const,

  // Status Categories
  CATEGORIES: {
    DRAFT: 'draft',
    PENDING: 'pending',
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    PAUSED: 'paused',
  } as const,

  // Status Priority Order
  ORDER: {
    DRAFT: 0,
    PENDING: 1,
    SCHEDULED: 2,
    GENERATING: 3,
    GENERATED: 4,
    SENDING: 5,
    SENT: 6,
    DELIVERED: 7,
    PARTIAL: 8,
    PAUSED: 9,
    ON_HOLD: 10,
    FAILED: 11,
    EXPIRED: 12,
    CANCELLED: 13,
    ARCHIVED: 14,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    DRAFT_TO_PENDING: 'draft_to_pending',
    DRAFT_TO_ARCHIVED: 'draft_to_archived',
    DRAFT_TO_CANCELLED: 'draft_to_cancelled',
    PENDING_TO_SCHEDULED: 'pending_to_scheduled',
    PENDING_TO_GENERATING: 'pending_to_generating',
    PENDING_TO_CANCELLED: 'pending_to_cancelled',
    SCHEDULED_TO_GENERATING: 'scheduled_to_generating',
    SCHEDULED_TO_CANCELLED: 'scheduled_to_cancelled',
    GENERATING_TO_GENERATED: 'generating_to_generated',
    GENERATING_TO_FAILED: 'generating_to_failed',
    GENERATING_TO_CANCELLED: 'generating_to_cancelled',
    GENERATED_TO_SENDING: 'generated_to_sending',
    GENERATED_TO_CANCELLED: 'generated_to_cancelled',
    GENERATED_TO_PAUSED: 'generated_to_paused',
    SENDING_TO_SENT: 'sending_to_sent',
    SENDING_TO_PARTIAL: 'sending_to_partial',
    SENDING_TO_PAUSED: 'sending_to_paused',
    SENDING_TO_FAILED: 'sending_to_failed',
    SENDING_TO_CANCELLED: 'sending_to_cancelled',
    SENT_TO_DELIVERED: 'sent_to_delivered',
    SENT_TO_FAILED: 'sent_to_failed',
    PAUSED_TO_GENERATING: 'paused_to_generating',
    PAUSED_TO_SENDING: 'paused_to_sending',
    PAUSED_TO_ON_HOLD: 'paused_to_on_hold',
    PAUSED_TO_CANCELLED: 'paused_to_cancelled',
    ON_HOLD_TO_GENERATING: 'on_hold_to_generating',
    ON_HOLD_TO_SENDING: 'on_hold_to_sending',
    ON_HOLD_TO_CANCELLED: 'on_hold_to_cancelled',
    PARTIAL_TO_SENDING: 'partial_to_sending',
    PARTIAL_TO_COMPLETED: 'partial_to_completed',
    PARTIAL_TO_CANCELLED: 'partial_to_cancelled',
    DELIVERED_TO_ARCHIVED: 'delivered_to_archived',
    FAILED_TO_DRAFT: 'failed_to_draft',
    FAILED_TO_ARCHIVED: 'failed_to_archived',
    EXPIRED_TO_ARCHIVED: 'expired_to_archived',
    CANCELLED_TO_ARCHIVED: 'cancelled_to_archived',
  } as const,
} as const;

// Digest Statuses
export type NotificationDigestStatusType =
  (typeof NOTIFICATIONDIGEST_STATUS.STATUSES)[keyof typeof NOTIFICATIONDIGEST_STATUS.STATUSES];

// Status Colors
export type NotificationDigestStatusColor =
  (typeof NOTIFICATIONDIGEST_STATUS.COLORS)[keyof typeof NOTIFICATIONDIGEST_STATUS.COLORS];

// Status Categories
export type NotificationDigestStatusCategory =
  (typeof NOTIFICATIONDIGEST_STATUS.CATEGORIES)[keyof typeof NOTIFICATIONDIGEST_STATUS.CATEGORIES];

// Status Priority Order
export type NotificationDigestStatusOrder =
  (typeof NOTIFICATIONDIGEST_STATUS.ORDER)[keyof typeof NOTIFICATIONDIGEST_STATUS.ORDER];

// Status Transitions
export type NotificationDigestStatusTransition =
  (typeof NOTIFICATIONDIGEST_STATUS.TRANSITIONS)[keyof typeof NOTIFICATIONDIGEST_STATUS.TRANSITIONS];

// Utility Functions
export function notificationdigestGetStatusLabel(status: NotificationDigestStatusType): string {
  const labels: Record<NotificationDigestStatusType, string> = {
    [NOTIFICATIONDIGEST_STATUS.STATUSES.DRAFT]: 'Draft',
    [NOTIFICATIONDIGEST_STATUS.STATUSES.PENDING]: 'Pending',
    [NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATING]: 'Generating',
    [NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATED]: 'Generated',
    [NOTIFICATIONDIGEST_STATUS.STATUSES.SENDING]: 'Sending',
    [NOTIFICATIONDIGEST_STATUS.STATUSES.SENT]: 'Sent',
    [NOTIFICATIONDIGEST_STATUS.STATUSES.DELIVERED]: 'Delivered',
    [NOTIFICATIONDIGEST_STATUS.STATUSES.FAILED]: 'Failed',
    [NOTIFICATIONDIGEST_STATUS.STATUSES.CANCELLED]: 'Cancelled',
    [NOTIFICATIONDIGEST_STATUS.STATUSES.ARCHIVED]: 'Archived',
    [NOTIFICATIONDIGEST_STATUS.STATUSES.SCHEDULED]: 'Scheduled',
    [NOTIFICATIONDIGEST_STATUS.STATUSES.PAUSED]: 'Paused',
    [NOTIFICATIONDIGEST_STATUS.STATUSES.ON_HOLD]: 'On Hold',
    [NOTIFICATIONDIGEST_STATUS.STATUSES.PARTIAL]: 'Partial',
    [NOTIFICATIONDIGEST_STATUS.STATUSES.EXPIRED]: 'Expired',
  };
  return labels[status] || 'Unknown Status';
}

export function notificationdigestGetStatusColor(
  status: NotificationDigestStatusType
): NotificationDigestStatusColor {
  const colors: Record<NotificationDigestStatusType, NotificationDigestStatusColor> = {
    [NOTIFICATIONDIGEST_STATUS.STATUSES.DRAFT]: NOTIFICATIONDIGEST_STATUS.COLORS.DRAFT,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.PENDING]: NOTIFICATIONDIGEST_STATUS.COLORS.PENDING,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.SCHEDULED]: NOTIFICATIONDIGEST_STATUS.COLORS.SCHEDULED,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATING]: NOTIFICATIONDIGEST_STATUS.COLORS.GENERATING,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATED]: NOTIFICATIONDIGEST_STATUS.COLORS.GENERATED,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.SENDING]: NOTIFICATIONDIGEST_STATUS.COLORS.SENDING,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.SENT]: NOTIFICATIONDIGEST_STATUS.COLORS.SENT,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.DELIVERED]: NOTIFICATIONDIGEST_STATUS.COLORS.DELIVERED,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.FAILED]: NOTIFICATIONDIGEST_STATUS.COLORS.FAILED,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.CANCELLED]: NOTIFICATIONDIGEST_STATUS.COLORS.CANCELLED,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.ARCHIVED]: NOTIFICATIONDIGEST_STATUS.COLORS.ARCHIVED,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.PAUSED]: NOTIFICATIONDIGEST_STATUS.COLORS.PAUSED,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.ON_HOLD]: NOTIFICATIONDIGEST_STATUS.COLORS.ON_HOLD,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.PARTIAL]: NOTIFICATIONDIGEST_STATUS.COLORS.PARTIAL,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.EXPIRED]: NOTIFICATIONDIGEST_STATUS.COLORS.EXPIRED,
  };
  return colors[status] || NOTIFICATIONDIGEST_STATUS.COLORS.PENDING;
}

export function notificationdigestGetStatusCategory(
  status: NotificationDigestStatusType
): NotificationDigestStatusCategory {
  const categories: Record<NotificationDigestStatusType, NotificationDigestStatusCategory> = {
    [NOTIFICATIONDIGEST_STATUS.STATUSES.DRAFT]: NOTIFICATIONDIGEST_STATUS.CATEGORIES.DRAFT,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.PENDING]: NOTIFICATIONDIGEST_STATUS.CATEGORIES.PENDING,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.SCHEDULED]: NOTIFICATIONDIGEST_STATUS.CATEGORIES.PENDING,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATING]:
      NOTIFICATIONDIGEST_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATED]:
      NOTIFICATIONDIGEST_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.SENDING]: NOTIFICATIONDIGEST_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.SENT]: NOTIFICATIONDIGEST_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.PARTIAL]: NOTIFICATIONDIGEST_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.PAUSED]: NOTIFICATIONDIGEST_STATUS.CATEGORIES.PAUSED,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.ON_HOLD]: NOTIFICATIONDIGEST_STATUS.CATEGORIES.PAUSED,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.DELIVERED]: NOTIFICATIONDIGEST_STATUS.CATEGORIES.COMPLETED,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.FAILED]: NOTIFICATIONDIGEST_STATUS.CATEGORIES.FAILED,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.EXPIRED]: NOTIFICATIONDIGEST_STATUS.CATEGORIES.FAILED,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.CANCELLED]: NOTIFICATIONDIGEST_STATUS.CATEGORIES.CANCELLED,
    [NOTIFICATIONDIGEST_STATUS.STATUSES.ARCHIVED]: NOTIFICATIONDIGEST_STATUS.CATEGORIES.ARCHIVED,
  };
  return categories[status] || NOTIFICATIONDIGEST_STATUS.CATEGORIES.PENDING;
}

export function notificationdigestIsActive(status: NotificationDigestStatusType): boolean {
  const activeStatuses: NotificationDigestStatusType[] = [
    NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATING,
    NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATED,
    NOTIFICATIONDIGEST_STATUS.STATUSES.SENDING,
    NOTIFICATIONDIGEST_STATUS.STATUSES.SENT,
    NOTIFICATIONDIGEST_STATUS.STATUSES.PARTIAL,
  ];
  return activeStatuses.includes(status);
}

export function notificationdigestIsCompleted(status: NotificationDigestStatusType): boolean {
  const completedStatuses: NotificationDigestStatusType[] = [
    NOTIFICATIONDIGEST_STATUS.STATUSES.DELIVERED,
    NOTIFICATIONDIGEST_STATUS.STATUSES.ARCHIVED,
    NOTIFICATIONDIGEST_STATUS.STATUSES.CANCELLED,
  ];
  return completedStatuses.includes(status);
}

export function notificationdigestIsFailed(status: NotificationDigestStatusType): boolean {
  const failedStatuses: NotificationDigestStatusType[] = [
    NOTIFICATIONDIGEST_STATUS.STATUSES.FAILED,
    NOTIFICATIONDIGEST_STATUS.STATUSES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}

export function notificationdigestIsEditable(status: NotificationDigestStatusType): boolean {
  const editableStatuses: NotificationDigestStatusType[] = [
    NOTIFICATIONDIGEST_STATUS.STATUSES.DRAFT,
    NOTIFICATIONDIGEST_STATUS.STATUSES.PENDING,
    NOTIFICATIONDIGEST_STATUS.STATUSES.PAUSED,
    NOTIFICATIONDIGEST_STATUS.STATUSES.ON_HOLD,
  ];
  return editableStatuses.includes(status);
}

export function notificationdigestCanTransition(
  currentStatus: NotificationDigestStatusType,
  targetStatus: NotificationDigestStatusType
): boolean {
  const validTransitions: Record<NotificationDigestStatusType, NotificationDigestStatusType[]> = {
    [NOTIFICATIONDIGEST_STATUS.STATUSES.DRAFT]: [
      NOTIFICATIONDIGEST_STATUS.STATUSES.PENDING,
      NOTIFICATIONDIGEST_STATUS.STATUSES.ARCHIVED,
      NOTIFICATIONDIGEST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONDIGEST_STATUS.STATUSES.PENDING]: [
      NOTIFICATIONDIGEST_STATUS.STATUSES.SCHEDULED,
      NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATING,
      NOTIFICATIONDIGEST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONDIGEST_STATUS.STATUSES.SCHEDULED]: [
      NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATING,
      NOTIFICATIONDIGEST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATING]: [
      NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATED,
      NOTIFICATIONDIGEST_STATUS.STATUSES.FAILED,
      NOTIFICATIONDIGEST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATED]: [
      NOTIFICATIONDIGEST_STATUS.STATUSES.SENDING,
      NOTIFICATIONDIGEST_STATUS.STATUSES.PAUSED,
      NOTIFICATIONDIGEST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONDIGEST_STATUS.STATUSES.SENDING]: [
      NOTIFICATIONDIGEST_STATUS.STATUSES.SENT,
      NOTIFICATIONDIGEST_STATUS.STATUSES.PARTIAL,
      NOTIFICATIONDIGEST_STATUS.STATUSES.PAUSED,
      NOTIFICATIONDIGEST_STATUS.STATUSES.FAILED,
      NOTIFICATIONDIGEST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONDIGEST_STATUS.STATUSES.SENT]: [
      NOTIFICATIONDIGEST_STATUS.STATUSES.DELIVERED,
      NOTIFICATIONDIGEST_STATUS.STATUSES.FAILED,
    ],
    [NOTIFICATIONDIGEST_STATUS.STATUSES.PAUSED]: [
      NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATING,
      NOTIFICATIONDIGEST_STATUS.STATUSES.SENDING,
      NOTIFICATIONDIGEST_STATUS.STATUSES.ON_HOLD,
      NOTIFICATIONDIGEST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONDIGEST_STATUS.STATUSES.ON_HOLD]: [
      NOTIFICATIONDIGEST_STATUS.STATUSES.GENERATING,
      NOTIFICATIONDIGEST_STATUS.STATUSES.SENDING,
      NOTIFICATIONDIGEST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONDIGEST_STATUS.STATUSES.PARTIAL]: [
      NOTIFICATIONDIGEST_STATUS.STATUSES.SENDING,
      NOTIFICATIONDIGEST_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONDIGEST_STATUS.STATUSES.DELIVERED]: [NOTIFICATIONDIGEST_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONDIGEST_STATUS.STATUSES.FAILED]: [
      NOTIFICATIONDIGEST_STATUS.STATUSES.DRAFT,
      NOTIFICATIONDIGEST_STATUS.STATUSES.ARCHIVED,
    ],
    [NOTIFICATIONDIGEST_STATUS.STATUSES.EXPIRED]: [NOTIFICATIONDIGEST_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONDIGEST_STATUS.STATUSES.CANCELLED]: [NOTIFICATIONDIGEST_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONDIGEST_STATUS.STATUSES.ARCHIVED]: [],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
