/**
 * Authentication Types Main Index
 * Central export point for all authentication-related types
 * Includes auth, user, and common types
 */

// Export auth types (excluding duplicates)
export {
  // Core primitive types
  Email,
  Password,
  UserId,
  SessionId,
  Timestamp,
  Token,
  RefreshToken,
  UserRole,
  AuthStatus,
  AuthProvider,
  MfaMethod,
  Permission,
  DeviceInfo,
  ID,
  UUID,
  URL as UrlType,
  PhoneNumber,
  CountryCode,
  CurrencyCode,
  LanguageCode,
  Timezone,
  JSONObject,
  JSONArray,
  JSONValue,
  SortDirection,
  PaginationParams,
  FilterParams,
  APIResponse as CoreAPIResponse,
  APIPaginatedResponse as CoreAPIPaginatedResponse,
  Metadata,
  SoftDelete,
  AuditTrail,
  StatusBase,
  Name,
  Address as CoreAddress,
  ContactInfo,
  SocialLinks,
  Image,
  Money,
  DateTimeRange,
  GeoLocation,
  IPAddress,
  UserAgent,
  DeviceInfo as CoreDeviceInfo,
  AuthError as CoreAuthError,
  AuthEvent as CoreAuthEvent,
  ValidationRule,

  // Auth specific types
  AuthCredentials,
  AuthResponse,
  AuthenticatedUser,
  AuthTokens,
  SessionInfo,
  RegistrationRequest,
  RegistrationResponse,
  PasswordResetRequest,
  PasswordResetConfirmation,
  // EmailVerificationRequest is not exported, using EmailVerificationRequestDTO
  TwoFactorSetup,
  TwoFactorVerification,
  SessionManagement,
  // DeviceSession is not exported, using DeviceSessionInfo
  AuthState,
  LoginHistory,
  AccountLockoutStatus,
  MfaSetupResponse,
  AuthValidationResult,
  AuthValidationError,
  AuthValidationWarning,
  PasswordValidationOptions,
  PasswordValidationResult,
  AuthConfiguration,
  OAuthProviderConfig,
  OAuthAuthResponse,
  AuthModuleConfig,
  AuthErrorCode,
  AuthError,
  AuthEvent,
  type VerificationMethod,
  type ResetMethod,
  type AuthEventType,
  AUTH_STATUS,
  USER_ROLE,
  AUTH_PROVIDER,

  // Auth request DTOs
  LoginRequest,
  LoginResponse,
  AuthTokenData,
  SessionData,
  RegistrationRequestDTO,
  RegistrationResponseDTO,
  RegistrationUserData,
  LogoutRequest,
  LogoutResponse,
  RefreshTokenRequest,
  RefreshTokenResponse,
  PasswordResetRequestDTO,
  PasswordResetResponseDTO,
  PasswordResetConfirmRequestDTO,
  PasswordResetConfirmResponseDTO,
  EmailVerificationRequestDTO,
  EmailVerificationResponseDTO,
  TwoFactorSetupRequestDTO,
  TwoFactorSetupResponseDTO,
  TwoFactorVerifyRequestDTO,
  TwoFactorVerifyResponseDTO,
  SessionListRequest,
  SessionListResponseDTO,
  SessionTerminateRequest,
  SessionTerminateResponseDTO,
  AccountLockStatusRequest,
  AccountLockStatusResponseDTO,
  ChangePasswordRequest,
  ChangePasswordResponseDTO,
  MfaBackupCodesRequest,
  MfaBackupCodesResponseDTO,
  AuthCheckRequest,
  AuthCheckResponseDTO,
  APIErrorResponse,
  APISuccessResponse,
  APIPaginatedRequest,
  AUTH_API_ENDPOINTS,
  type AuthAPIMethod,
  type AuthAPIHeaders,
  type AuthAPIConfig,
  type APIRateLimitInfo,
  type APIRequestMetadata,

  // Auth response types
  BaseAPIResponse,
  APIError as AuthAPIError,
  ValidationError as AuthValidationErrorType,
  AuthResponseData,
  LoginResponseData,
  TokenRefreshResponse,
  TokenRefreshResponseData,
  PasswordResetResponse,
  PasswordResetResponseData,
  PasswordResetConfirmResponse,
  PasswordResetConfirmResponseData,
  EmailVerificationResponseData,
  TwoFactorSetupResponseData,
  TwoFactorVerificationResponseData,
  SessionListResponse,
  SessionListResponseData,
  SessionTerminateResponse,
  SessionTerminateResponseData,
  AccountStatusResponse,
  AccountStatusResponseData,
  SocialLoginResponseData,
  ChangePasswordResponse,
  ChangePasswordResponseData,
  MfaBackupCodesResponse,
  MfaBackupCodesResponseData,
  AuthStatusResponse,
  AuthStatusResponseData,
  BulkOperationResponse,
  BulkOperationResponseData,
  BulkOperationDetail,
  HealthCheckResponse,
  ServiceHealth as AuthServiceHealth,
  RateLimitResponse,
  PaginationResponseMeta,
  PaginatedResponse,
  EmptyResponse,
  RESPONSE_STATUS_CODES,
  RESPONSE_MESSAGES,
  type VerificationMethodType,
  type ResponseStatus,
  type APIResponseBuilder as AuthAPIResponseBuilder,
  type ResponseTypeMap,

  // Session types
  SessionCreationRequest,
  SessionCreationResponse,
  SessionTokens,
  SessionValidationRequest,
  SessionValidationResponse,
  SessionValidationError,
  SessionUserInfo,
  SessionUpdateRequest,
  SessionUpdateResponse,
  SessionTerminateRequestExtended,
  SessionTerminateResponseExtended,
  SessionListRequestExtended,
  SessionPagination,
  SessionListResponseExtended,
  SessionActivityRequest,
  SessionActivityResponse,
  SessionActivityLog,
  SessionStatistics,
  SessionSecurity,
  SessionDevice,
  SessionLocation,
  SessionMetadata,
  SessionExpiry,
  SessionEvent,
  SessionFilter,
  SessionResponseBuilder,
  SessionErrorResponse,
  SessionValidationDetail,
  SessionCleanupResult,
  SessionMigrationRequest,
  SessionMigrationResponse,
  SessionSecurityViolation,
  SESSION_STATUS,
  SESSION_TYPES,
  SESSION_EVENTS,
  DEFAULT_SESSION_CONFIG,
  type SessionStatus,
  type SessionType,
  type SessionSortField,
  type SessionEventType,

  // Token types
  TokenPayload,
  AccessTokenPayload,
  RefreshTokenPayload,
  ResetTokenPayload,
  MFATokenPayload,
  TokenGenerationRequest,
  TokenGenerationResponse,
  TokenValidationRequest,
  TokenValidationResponse,
  TokenValidationError,
  TokenRevocationRequest,
  TokenRevocationResponse,
  TokenRefreshRequestExtended,
  TokenRefreshResponseExtended,
  TokenMetadata,
  TokenStatistics,
  TokenSecurity,
  TokenBlacklist,
  TokenFilter,
  TokenResponseBuilder,
  TokenErrorResponse,
  TokenClaims,
  TokenRotation,
  TokenAuditLog,
  TokenVerification,
  TokenExpiryCheck,
  TokenSigningRequest,
  TokenSigningResponse,
  TokenVerificationRequest,
  TokenVerificationResponse,
  TOKEN_TYPES,
  TOKEN_STATUS,
  TOKEN_ALGORITHMS,
  DEFAULT_TOKEN_CONFIG,
  type TokenType,
  type TokenStatus,
  type TokenAlgorithm,
  type TokenScope,

  // Verification types
  VerificationRequest as AuthVerificationRequest,
  VerificationResponse as AuthVerificationResponse,
  OTPGenerationRequest,
  OTPGenerationResponse,
  OTPVerificationRequest,
  OTPVerificationResponse,
  PhoneVerificationRequest,
  PhoneVerificationResponse,
  IdentityVerificationRequest,
  IdentityVerificationResponse,
  VerificationToken,
  VerificationHistory,
  VerificationSecurity,
  VerificationStatistics as AuthVerificationStatistics,
  VerificationFilter as AuthVerificationFilter,
  VerificationResponseBuilder as AuthVerificationResponseBuilder,
  VerificationErrorResponse as AuthVerificationErrorResponse,
  OTPDeliveryStatus,
  VerificationSession,
  ResendVerificationRequest,
  ResendVerificationResponse,
  VerificationWebhook as AuthVerificationWebhook,
  DocumentVerification as AuthDocumentVerification,
  // VERIFICATION_TYPES is exported from user module, so skipping here
  VERIFICATION_STATUS,
  VERIFICATION_METHODS,
  OTP_DELIVERY_METHODS,
  DEFAULT_VERIFICATION_CONFIG,
  type VerificationType as AuthVerificationType,
  type VerificationStatus as AuthVerificationStatus,
  type OTPType,
  type OTPDeliveryMethod,

  // MFA types
  MFAConfiguration,
  MFASetupRequest,
  MFASetupResponse,
  MFAVerificationRequest,
  MFAVerificationResponse,
  MFARecoveryRequest,
  MFARecoveryResponse,
  MFABackupCodes,
  MFARecoveryCodes,
  MFADevice,
  MFASession,
  MFAAuditLog,
  MFAStatistics,
  MFAPolicy,
  MFARiskAssessment,
  MFAStepUpRequest,
  MFAStepUpResponse,
  MFAResetRequest,
  MFAResetResponse,
  MFADisableRequest,
  MFADisableResponse,
  MFASecurity,
  MFAFilter,
  MFAResponseBuilder,
  MFAErrorResponse,
  MFAWebhook,
  MFAChallenge,
  MFARecoveryStatus,
  MFA_METHODS,
  MFA_STATUS,
  MFA_TYPES,
  AUTHENTICATOR_TYPES,
  DEFAULT_MFA_CONFIG,
  type MFAMethod,
  type MFAStatus,
  type MFAType,
  type AuthenticatorType,

  // Recovery code types
  RecoveryRequest,
  RecoveryResponse,
  RecoveryCodeGenerationRequest,
  RecoveryCodeGenerationResponse,
  RecoveryCodeVerificationRequest,
  RecoveryCodeVerificationResponse,
  AccountRecoveryRequest,
  AccountRecoveryResponse,
  BackupCode,
  RecoveryHistory,
  SecurityQuestions,
  SecurityQuestion as RecoverySecurityQuestion,
  TrustedContact,
  TrustedDevice,
  RecoveryPolicy,
  RecoveryStatistics,
  RecoveryFilter,
  RecoveryResponseBuilder,
  RecoveryErrorResponse,
  RecoveryWebhook,
  RecoverySession,
  RecoveryCodeValidation,
  EmergencyAccessRequest,
  EmergencyAccessResponse,
  RecoveryContact,
  RecoveryCodeUsage,
  AccountRecoveryStatus,
  RECOVERY_CODE_TYPES,
  RECOVERY_CODE_STATUS,
  RECOVERY_METHODS,
  DEFAULT_RECOVERY_CONFIG,
  type RecoveryCodeType,
  type RecoveryCodeStatus,
  type RecoveryMethod,

  // Account lock types
  AccountLock,
  LockRequest,
  LockResponse,
  UnlockRequest,
  UnlockResponse,
  LockStatusRequest,
  LockStatusResponse,
  FailedAttempt,
  LockHistory,
  AccountSecurityPolicy,
  LockStatistics,
  LockFilter,
  LockResponseBuilder,
  LockErrorResponse,
  LockWebhook,
  SecurityThreat,
  SuspiciousActivity,
  AccountLockNotification,
  LockEscalationRequest,
  LockEscalationResponse,
  BulkLockRequest,
  BulkLockResponse,
  LOCK_TYPES,
  LOCK_STATUS,
  LOCK_SEVERITY,
  LOCK_REASONS,
  DEFAULT_LOCK_CONFIG,
  type LockType,
  type LockStatus,
  type LockSeverity,
  type LockReason,

  // Login attempt types
  LoginAttempt,
  LoginAttemptRequest as AuthLoginAttemptRequest,
  LoginAttemptResponse as AuthLoginAttemptResponse,
  LoginAttemptVerification,
  LoginAttemptMonitoring,
  LoginAttemptAnalytics,
  LoginAttemptFilter as AuthLoginAttemptFilter,
  LoginAttemptStatistics as AuthLoginAttemptStatistics,
  LoginAttemptThrottle,
  LoginAttemptSecurity as AuthLoginAttemptSecurity,
  LoginAttemptAnomaly,
  LoginAttemptWebhook,
  LoginAttemptResponseBuilder,
  LoginAttemptErrorResponse,
  LoginAttemptReport,
  LoginAttemptAlert,
  LoginAttemptCleanup,
  LOGIN_ATTEMPT_STATUS,
  LOGIN_ATTEMPT_RESULT,
  LOGIN_ATTEMPT_TYPES,
  DEFAULT_LOGIN_ATTEMPT_CONFIG,
  type LoginAttemptStatus,
  type LoginAttemptResult,
  type LoginAttemptType,

  // Device types
  Device,
  DeviceRegistrationRequest,
  DeviceRegistrationResponse,
  DeviceVerificationRequest,
  DeviceVerificationResponse,
  DeviceTrustRequest,
  DeviceTrustResponse,
  DeviceUpdateRequest,
  DeviceUpdateResponse,
  DeviceRemovalRequest,
  DeviceRemovalResponse,
  DeviceFingerprint,
  DeviceSessionInfo,
  DeviceAnalytics,
  DeviceFilter as AuthDeviceFilter,
  DeviceResponseBuilder,
  DeviceErrorResponse,
  DeviceWebhook,
  DeviceSecurity as AuthDeviceSecurity,
  DeviceStatistics as AuthDeviceStatistics,
  DeviceAuditLog,
  DeviceLimit,
  DeviceBlockRequest,
  DeviceBlockResponse,
  DeviceUnblockRequest,
  DeviceUnblockResponse,
  DEVICE_TYPES,
  DEVICE_STATUSES,
  DEVICE_CONFIG_DEFAULT,
  DEFAULT_DEVICE_CONFIG,
  type DeviceType,
  type DeviceStatus as AuthDeviceStatus,
  type DeviceOS,
  type DeviceBrowser,
  type DeviceTrustLevel,

  // Social types
  SocialAccount,
  SocialLoginRequest as AuthSocialLoginRequest,
  SocialLoginResponse as AuthSocialLoginResponse,
  SocialLoginCallback,
  SocialLoginVerification,
  SocialConnectRequest,
  SocialConnectResponse,
  SocialDisconnectRequest,
  SocialDisconnectResponse,
  OAuthUserInfo,
  SocialLink,
  SocialProviderConfig,
  SocialLoginOptions,
  SocialFilter as AuthSocialFilter,
  SocialResponseBuilder,
  SocialErrorResponse,
  SocialWebhook,
  SocialStatistics as AuthSocialStatistics,
  SocialAccountProfile,
  SocialConnectionStatus,
  SocialAccountLinkRequest,
  SocialAccountLinkResponse,
  SocialAccountUnlinkRequest,
  SocialAccountUnlinkResponse,
  SOCIAL_PROVIDERS,
  SOCIAL_STATUSES,
  SOCIAL_CONFIG_DEFAULT,
  DEFAULT_SOCIAL_CONFIG,
  type SocialProvider,
  type SocialStatus,

  // OAuth types
  OAuthClient,
  OAuthToken as AuthOAuthToken,
  OAuthAuthorizationRequest,
  OAuthAuthorizationResponse,
  OAuthTokenRequest,
  OAuthTokenResponse as AuthOAuthTokenResponse,
  OAuthClientRegistrationRequest,
  OAuthClientRegistrationResponse,
  OAuthAuthorizationCode,
  OAuthRefreshToken,
  OAuthSession,
  OAuthConsent,
  OAuthFilter as AuthOAuthFilter,
  OAuthResponseBuilder,
  OAuthErrorResponse,
  OAuthWebhook,
  OAuthStatistics as AuthOAuthStatistics,
  OAuthClientCredentials,
  OAuthAuthorizationResult,
  OAuthTokenValidation,
  OAuthClientUpdateRequest,
  OAuthClientUpdateResponse,
  OAuthClientDeleteRequest,
  OAuthClientDeleteResponse,
  OAuthTokenRevocationRequest,
  OAuthTokenRevocationResponse,
  OIDCClaims,
  OIDCConfig,
  OAUTH_PROVIDERS,
  OAUTH_STATUSES,
  OAUTH_GRANT_TYPES_LIST,
  OAUTH_SCOPES_LIST,
  OAUTH_CONFIG_DEFAULT,
  DEFAULT_OAUTH_CONFIG,
  type OAuthProvider,
  type OAuthStatus as AuthOAuthStatus,
  type OAuthGrantType,
  type OAuthScope,

  // SSO types
  SsoSession,
  SsoIdentityProvider,
  SsoServiceProvider,
  SsoLoginRequest as AuthSsoLoginRequest,
  SsoLoginResponse as AuthSsoLoginResponse,
  SsoCallback,
  SsoVerification,
  SsoLogoutRequest,
  SsoLogoutResponse,
  SamlAssertion,
  SamlRequest,
  SsoUser,
  SsoProviderConfig,
  SsoFilter as AuthSsoFilter,
  SsoResponseBuilder,
  SsoErrorResponse,
  SsoWebhook,
  SsoStatistics as AuthSsoStatistics,
  SsoConnectionStatus,
  SsoLinkRequest,
  SsoLinkResponse,
  SsoUnlinkRequest,
  SsoUnlinkResponse,
  SamlMetadata,
  SsoSessionData,
  SsoFederation,
  SsoCertificate,
  SSO_PROVIDERS,
  SSO_STATUSES,
  SSO_CONFIG_DEFAULT,
  DEFAULT_SSO_CONFIG,
  type SsoProvider,
  type SsoStatus,

  // 2FA types
  TwoFactorConfig,
  TwoFactorSetupRequest as AuthTwoFactorSetupRequest,
  TwoFactorVerificationRequest as AuthTwoFactorVerificationRequest,
  TwoFactorDisableRequest,
  TwoFactorDisableResponse,
  TwoFactorResetRequest,
  TwoFactorResetResponse,
  TwoFactorBackupCodes,
  TwoFactorRecoveryCodes,
  TwoFactorDevice,
  TwoFactorSession,
  TwoFactorAuditLog,
  TwoFactorStatistics,
  TwoFactorPolicy,
  TwoFactorFilter,
  TwoFactorResponseBuilder,
  TwoFactorErrorResponse,
  TwoFactorWebhook,
  TwoFactorRecoveryStatus,
  TwoFactorChallenge,
  TWO_FACTOR_TYPES,
  TWO_FACTOR_STATUSES,
  TWO_FACTOR_CONFIG_DEFAULT,
  DEFAULT_TWO_FACTOR_CONFIG,
  type TwoFaType,
  type TwoFaStatus,

  // Biometric types
  BiometricConfig,
  BiometricSetupRequest,
  BiometricSetupResponse,
  BiometricVerificationRequest,
  BiometricVerificationResponse,
  BiometricDisableRequest,
  BiometricDisableResponse,
  BiometricDevice,
  BiometricSession,
  BiometricAuditLog,
  BiometricStatistics,
  BiometricPolicy,
  BiometricFilter,
  BiometricResponseBuilder,
  BiometricErrorResponse,
  BiometricWebhook,
  BiometricTemplate,
  BiometricChallenge,
  BiometricVerificationResult,
  BIOMETRIC_TYPES,
  BIOMETRIC_STATUSES,
  BIOMETRIC_CONFIG_DEFAULT,
  DEFAULT_BIOMETRIC_CONFIG,
  type BiometricType,
  type BiometricStatus,

  // Permission types (from auth)
  Permission as AuthPermissionType,
  Role as AuthRoleType,
  UserRoleAssignment,
  UserPermission as AuthUserPermission,
  PermissionPolicy,
  PermissionRule,
  PermissionCondition as AuthPermissionCondition,
  AccessControlEntry,
  PermissionCheckRequest,
  PermissionCheckResponse,
  RoleAssignmentRequest,
  RoleAssignmentResponse,
  PermissionGrantRequest as AuthPermissionGrantRequest,
  PermissionGrantResponse as AuthPermissionGrantResponse,
  PermissionRevokeRequest as AuthPermissionRevokeRequest,
  PermissionRevokeResponse as AuthPermissionRevokeResponse,
  PermissionFilter as AuthPermissionFilter,
  PermissionResponseBuilder as AuthPermissionResponseBuilder,
  PermissionErrorResponse as AuthPermissionErrorResponse,
  PermissionAuditLog as AuthPermissionAuditLog,
  PermissionStatistics as AuthPermissionStatistics,
  AUTH_PERMISSIONS,
  AUTH_ROLES,
  DEFAULT_PERMISSION_CONFIG as AuthDefaultPermissionConfig,
  type AuthPermission,
  type AuthRole,

  // Settings types (from auth)
  AuthSettings,
  SettingsUpdateRequest as AuthSettingsUpdateRequest,
  SettingsUpdateResponse as AuthSettingsUpdateResponse,
  FeatureFlag,
  FeatureFlagCheckRequest,
  FeatureFlagCheckResponse,
  FeatureFlagUpdateRequest,
  FeatureFlagUpdateResponse,
  Configuration,
  ConfigurationUpdateRequest,
  ConfigurationUpdateResponse,
  SettingsFilter as AuthSettingsFilter,
  SettingsResponseBuilder as AuthSettingsResponseBuilder,
  SettingsErrorResponse as AuthSettingsErrorResponse,
  SettingsAuditLog as AuthSettingsAuditLog,
  AUTH_SETTINGS,
  DEFAULT_SETTINGS_CONFIG,

  // Preferences types (from auth)
  UserPreferences as AuthUserPreferences,
  NotificationPreferences as AuthNotificationPreferences,
  PrivacySettings as AuthPrivacySettings,
  CookiePreferences as AuthCookiePreferences,
  SecurityPreferences as AuthSecurityPreferences,
  AccessibilitySettings as AuthAccessibilitySettings,
  ThemePreferences as AuthThemePreferences,
  EmailPreferences as AuthEmailPreferences,
  PreferencesUpdateRequest as AuthPreferencesUpdateRequest,
  PreferencesUpdateResponse as AuthPreferencesUpdateResponse,
  PreferencesGetRequest as AuthPreferencesGetRequest,
  PreferencesGetResponse as AuthPreferencesGetResponse,
  PreferencesFilter as AuthPreferencesFilter,
  PreferencesResponseBuilder as AuthPreferencesResponseBuilder,
  PreferencesErrorResponse as AuthPreferencesErrorResponse,
  PreferencesAuditLog as AuthPreferencesAuditLog,
  PreferencesStatistics as AuthPreferencesStatistics,
  PREFERENCE_DEFAULTS,
  DEFAULT_PREFERENCES,
} from './auth';

// Export user types
export {
  // User core types
  User,
  UserCreateRequest,
  UserCreateResponse,
  UserUpdateRequest,
  UserUpdateResponse,
  UserDeleteRequest,
  UserDeleteResponse,
  UserRestoreRequest,
  UserRestoreResponse,
  UserFilter,
  UserStatistics,
  UserResponseBuilder,
  UserErrorResponse,
  UserAuditLog,
  USER_STATUS,
  USER_ROLES,
  DEFAULT_USER_CONFIG,

  // User profile types
  UserProfile,
  SocialLinks as UserSocialLinks,
  UserAddress,
  ProfileVisibility,
  ProfileUpdateRequest,
  ProfileUpdateResponse,
  ProfileGetRequest,
  ProfileGetResponse,
  ProfileVisibilityUpdateRequest,
  ProfileVisibilityUpdateResponse,
  AddressCreateRequest,
  AddressCreateResponse,
  AddressUpdateRequest,
  AddressUpdateResponse,
  AddressDeleteRequest,
  AddressDeleteResponse,
  AddressFilter,
  ProfileResponseBuilder,
  ProfileErrorResponse,
  DEFAULT_PROFILE_CONFIG,

  // User settings types
  UserSettings,
  SecuritySettings as UserSecuritySettings,
  DisplaySettings,
  SettingsUpdateRequest as UserSettingsUpdateRequest,
  SettingsUpdateResponse as UserSettingsUpdateResponse,
  SettingsGetRequest,
  SettingsGetResponse,
  SettingsFilter as UserSettingsFilter,
  SettingsResponseBuilder as UserSettingsResponseBuilder,
  SettingsErrorResponse as UserSettingsErrorResponse,
  SettingsAuditLog as UserSettingsAuditLog,
  SettingsStatistics as UserSettingsStatistics,
  SETTINGS_DEFAULTS,
  DEFAULT_SETTINGS,

  // User preferences types
  UserPreferences as UserPrefs,
  UserNotificationPreferences,
  UserPrivacySettings,
  UserCookiePreferences,
  UserAccessibilitySettings,
  ThemePreferences as UserThemePreferences,
  UserEmailPreferences,

  // User address types
  UserAddressCreateRequest,
  UserAddressCreateResponse,
  UserAddressUpdateRequest,
  UserAddressUpdateResponse,
  UserAddressDeleteRequest,
  UserAddressDeleteResponse,
  UserAddressGetRequest,
  UserAddressGetResponse,
  UserAddressListRequest,
  UserAddressListResponse,
  UserAddressSetDefaultRequest,
  UserAddressSetDefaultResponse,
  UserAddressVerifyRequest,
  UserAddressVerifyResponse,
  UserAddressFilter,
  UserAddressResponseBuilder,
  UserAddressErrorResponse,
  UserAddressAuditLog,
  UserAddressStatistics,
  ADDRESS_TYPES,
  ADDRESS_STATUS,
  ADDRESS_VERIFICATION_STATUS,
  DEFAULT_ADDRESS_CONFIG,
  type AddressType,
  type AddressStatus,
  type AddressVerificationStatus,

  // User contact types
  Contact,
  EmailContact,
  PhoneContact,
  SocialContact,
  EmergencyContact,
  ContactCreateRequest,
  ContactCreateResponse,
  ContactUpdateRequest,
  ContactUpdateResponse,
  ContactDeleteRequest,
  ContactDeleteResponse,
  ContactVerifyRequest,
  ContactVerifyResponse,
  ContactListRequest,
  ContactListResponse,
  ContactFilter,
  ContactResponseBuilder,
  ContactErrorResponse,
  ContactAuditLog,
  ContactStatistics,
  ContactVerification,
  CONTACT_TYPES,
  CONTACT_STATUS,
  CONTACT_VERIFICATION_STATUS,
  CONTACT_PRIORITY,
  DEFAULT_CONTACT_CONFIG,
  type ContactType,
  type ContactStatus,
  type ContactVerificationStatus,
  type ContactPriority,

  // User verification types
  Verification,
  VerificationRequest as UserVerificationRequest,
  VerificationResponse as UserVerificationResponse,
  VerificationConfirmRequest,
  VerificationConfirmResponse,
  VerificationResendRequest,
  VerificationResendResponse,
  EmailVerification,
  PhoneVerification,
  VerificationFilter as UserVerificationFilter,
  VerificationStatistics as UserVerificationStatistics,
  VerificationResponseBuilder as UserVerificationResponseBuilder,
  VerificationErrorResponse as UserVerificationErrorResponse,
  VerificationAuditLog,
  VerificationWebhook as UserVerificationWebhook,
  VERIFICATION_TYPES,
  VERIFICATION_STATUSES,
  VERIFICATION_CONFIG_DEFAULT,
  DEFAULT_VERIFICATION_CONFIG as UserDefaultVerificationConfig,
  type VerificationType as UserVerificationType,
  type VerificationStatus as UserVerificationStatus,
  type VerificationMethod as UserVerificationMethod,

  // User KYC types
  KYCProfile,
  KYCBasicInfo,
  KYCAddressInfo,
  KYCIncomeInfo,
  KYCDocument,
  KYCSubmitRequest,
  KYCSubmitResponse,
  KYCStatusRequest,
  KYCStatusResponse,
  KYCDocumentSubmitRequest,
  KYCDocumentSubmitResponse,
  KYCUpdateRequest,
  KYCUpdateResponse,
  KYCFilter,
  KYCResponseBuilder,
  KYCErrorResponse,
  KYCAuditLog,
  KYCStatistics,
  KYCWebhook,
  KYC_STATUS,
  KYC_LEVEL,
  DOCUMENT_TYPES,
  DOCUMENT_STATUS,
  DEFAULT_KYC_CONFIG,
  type KYCStatus,
  type KYCLevel,
  type DocumentType,
  type DocumentStatus,

  // User activity types
  UserActivity,
  LoginActivity,
  ActivityCreateRequest,
  ActivityCreateResponse,
  ActivityListRequest,
  ActivityListResponse,
  ActivityFilter,
  ActivityStatistics,
  ActivityResponseBuilder,
  ActivityErrorResponse,
  ActivityAuditLog,
  ActivityAnomaly,
  ACTIVITY_TYPES,
  ACTIVITY_STATUS,
  ACTIVITY_SEVERITY,
  DEFAULT_ACTIVITY_CONFIG,
  type ActivityType,
  type ActivityStatus,
  type ActivitySeverity,

  // User log types
  LogEntry,
  // UserAuditLog is already exported, using UserAuditLog instead
  LogCreateRequest,
  LogCreateResponse,
  AuditLogCreateRequest,
  AuditLogCreateResponse,
  LogListRequest,
  LogListResponse,
  AuditLogListRequest,
  AuditLogListResponse,
  LogFilter,
  LogStatistics,
  LogResponseBuilder,
  LogErrorResponse,
  LogArchive,
  LogRetentionPolicy,
  LOG_LEVELS,
  LOG_CATEGORIES,
  LOG_STATUS,
  DEFAULT_LOG_CONFIG,
  type LogLevel,
  type LogCategory,
  type LogStatus,

  // User permission types
  UserPermission,
  PermissionCondition as UserPermissionCondition,
  PermissionCheck,
  PermissionCheckResult,
  PermissionGrantRequest as UserPermissionGrantRequest,
  PermissionGrantResponse as UserPermissionGrantResponse,
  PermissionRevokeRequest as UserPermissionRevokeRequest,
  PermissionRevokeResponse as UserPermissionRevokeResponse,
  PermissionListRequest,
  PermissionListResponse,
  PermissionFilter as UserPermissionFilter,
  PermissionResponseBuilder as UserPermissionResponseBuilder,
  PermissionErrorResponse as UserPermissionErrorResponse,
  PermissionAuditLog as UserPermissionAuditLog,
  PermissionStatistics as UserPermissionStatistics,
  PERMISSION_RESOURCES,
  PERMISSION_ACTIONS,
  PERMISSION_SCOPES,
  DEFAULT_PERMISSION_CONFIG as UserDefaultPermissionConfig,
  type PermissionResource,
  type PermissionAction,
  type PermissionScope,

  // User role types
  Role as UserRoleType,
  RoleAssignment,
  RoleHierarchy,
  RoleCreateRequest,
  RoleCreateResponse,
  RoleUpdateRequest,
  RoleUpdateResponse,
  RoleDeleteRequest,
  RoleDeleteResponse,
  RoleAssignRequest,
  RoleAssignResponse,
  RoleUnassignRequest,
  RoleUnassignResponse,
  RoleListRequest,
  RoleListResponse,
  RoleFilter,
  RoleResponseBuilder,
  RoleErrorResponse,
  RoleAuditLog,
  RoleStatistics,
  ROLE_LEVELS,
  ROLE_STATUS,
  DEFAULT_ROLE_CONFIG,
  type RoleLevel,
  type RoleStatus,
} from './user';

// Export common types
export {
  // API types
  APIRequest,
  APIResponse as CommonAPIResponse,
  APIError as CommonAPIError,
  ValidationError as CommonValidationError,
  PaginationMeta,
  APIHeaders,
  APIQueryParams,
  APIResponseBuilder as CommonAPIResponseBuilder,
  APIHealthCheck,
  ServiceHealth as CommonServiceHealth,
  APIWebhook,
  APIRateLimit,
  HTTP_STATUS,
  HTTP_STATUS_MESSAGES,
  HTTP_STATUS_CATEGORIES,
  HTTP_STATUS_HELPERS,
  API_STATUS,
  DEFAULT_API_CONFIG,
  type HttpStatusCode,
  type HttpStatusCategory,
  type APIMethod,

  // Pagination types
  PaginationRequest,
  PaginationResponse,
  PaginatedResult,
  FilterRequest,
  FilterCondition,
  DateRange,
  SortRequest,
  SearchRequest,
  CursorPagination,
  PageInfo,
  Edge,
  Connection,
  PaginationBuilder,
  DEFAULT_PAGINATION,
  SORT_ORDERS,
  FILTER_OPERATORS,

  // Audit types
  AuditLog as CommonAuditLog,
  AuditChange,
  AuditQuery,
  AuditStatistics as CommonAuditStatistics,
  AuditReport,
  AuditRetention,
  AuditResponseBuilder,
  AUDIT_ACTIONS,
  AUDIT_RESOURCES,
  AUDIT_SEVERITY,
  DEFAULT_AUDIT_CONFIG,
  type AuditAction,
  type AuditResource,
  type AuditSeverity,

  // SEO types
  SEOMetadata,
  MetaTag,
  StructuredData,
  Hreflang,
  Sitemap,
  SitemapImage,
  SitemapVideo,
  SitemapNews,
  SEOSettings,
  SEOUpdateRequest,
  SEOUpdateResponse,
  SEOAudit,
  SEOIssue,
  SEOResponseBuilder,
  SEO_DEFAULTS,
  SITEMAP_CHANGEFREQ,
  DEFAULT_SEO_CONFIG,
} from './common';
