/**
 * User Constants Index
 * Export all user-related constants and types
 */

// Core User Constants
export {
  USER,
  getUserLevel,
  getNextLevelThreshold,
  getLevelName,
  getUserStatusMessage,
  isActiveUser,
  isEligibleForLevelUpgrade,
} from './user.constants';

export type {
  UserLevel,
  UserVerificationStatus as CoreUserVerificationStatus,
} from './user.constants';

// User Status Constants
export {
  USER_STATUS,
  USER_STATUS_LABELS,
  USER_STATUS_COLORS,
  ACTIVE_USER_STATUSES,
  INACTIVE_USER_STATUSES,
  RESTRICTED_USER_STATUSES,
  VERIFICATION_REQUIRED_STATUSES,
  isUserActive,
  isUserRestricted,
  canUserLogin,
  getUserStatusLabel,
  getUserStatusColor,
} from './user-status.constants';

export type { UserStatus } from './user-status.constants';

// User Type Constants
export {
  USER_TYPE,
  USER_TYPE_LABELS,
  USER_TYPE_DESCRIPTIONS,
  BUSINESS_USER_TYPES,
  CONSUMER_USER_TYPES,
  VERIFICATION_REQUIRED_TYPES,
  isBusinessUser,
  isConsumerUser,
  requiresVerification,
  getUserTypeLabel,
  getUserTypeDescription,
} from './user-type.constants';

export type { UserType } from './user-type.constants';

// User Role Constants
export {
  USER_ROLE,
  USER_ROLE_LABELS,
  USER_ROLE_PRIORITY,
  CUSTOMER_ROLES,
  STAFF_ROLES,
  ADMIN_ROLES,
  VENDOR_ROLES,
  MANAGEMENT_ROLES,
  isCustomer,
  isStaff,
  isAdminRole,
  isVendor,
  isManagement,
  getRolePriority,
  hasHigherPriority,
  getUserRoleLabel,
} from './user-role.constants';

export type { UserRole } from './user-role.constants';

// User Permission Constants
export {
  USER_PERMISSION,
  USER_PERMISSION_CATEGORIES,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
  getCategoryPermissions,
  isSystemPermission,
  isAdminPermission,
  getPermissionResource,
  getPermissionAction,
} from './user-permission.constants';

export type { UserPermission, UserPermissionCategory } from './user-permission.constants';

// User Profile Constants
export {
  USER_PROFILE,
  getProfileCompletionLevel,
  getGenderLabel,
  getMaritalStatusLabel,
  getEducationLabel,
  getEmploymentLabel,
  getSocialPlatformLabel,
  isProfileComplete,
  getMissingRequiredFields,
  getProfileStatusMessage,
  isProfileActive,
  isProfileVisible,
  USER_PROFILE_STATUS,
  USER_PROFILE_STATUS_LABELS,
  USER_PROFILE_STATUS_COLORS,
  ACTIVE_PROFILE_STATUSES,
  INACTIVE_PROFILE_STATUSES,
  RESTRICTED_PROFILE_STATUSES,
  VERIFICATION_REQUIRED_PROFILE_STATUSES,
  isProfileStatusActive,
  isProfileRestricted,
  isProfileStatusVisible,
  getProfileStatusLabel,
  getProfileStatusColor,
} from './profile';

export type {
  ProfileVisibility,
  ProfileGender,
  ProfileMaritalStatus,
  ProfileEducation,
  ProfileEmployment,
  ProfileCompletionLevel,
  SocialPlatform,
  UserProfileStatus,
} from './profile';

// User Settings Constants
export {
  USER_SETTINGS,
  getThemeLabel,
  getFrequencyLabel as getSettingsFrequencyLabel,
  getTwoFactorMethodLabel,
  getSessionTimeoutLabel,
  isTwoFactorEnabled,
  getDefaultNotificationSettings,
  getDefaultPrivacySettings,
  getDefaultSecuritySettings,
  getDefaultCommunicationSettings,
  getSessionTimeoutOptions,
  getTwoFactorMethods,
  getThemeOptions,
  getFrequencyOptions as getSettingsFrequencyOptions,
  isSecurePassword,
  USER_SETTINGS_TYPE,
  USER_SETTINGS_TYPE_LABELS,
  USER_SETTINGS_TYPE_DESCRIPTIONS,
  PUBLIC_SETTINGS_TYPES,
  PRIVATE_SETTINGS_TYPES,
  isPublicSetting,
  isPrivateSetting,
  getSettingsTypeLabel,
  getSettingsTypeDescription,
  getSettingsTypeByCategory,
  USER_SETTINGS_STATUS,
  USER_SETTINGS_STATUS_LABELS,
  USER_SETTINGS_STATUS_COLORS,
  ACTIVE_SETTINGS_STATUSES,
  INACTIVE_SETTINGS_STATUSES,
  RESTRICTED_SETTINGS_STATUSES,
  isSettingsActive,
  isSettingsRestricted,
  canModifySettings,
  getSettingsStatusLabel,
  getSettingsStatusColor,
} from './settings';

export type {
  UserSettingsTheme,
  UserSettingsFrequency,
  TwoFactorMethod,
  SessionTimeout,
  UserSettingsType,
  UserSettingsStatus,
} from './settings';

// User Preferences Constants
export {
  USER_PREFERENCES,
  getLanguageLabel,
  getCurrencySymbol,
  getDateFormatLabel,
  getTimeFormatLabel,
  getWeekStartLabel,
  getFontSizeLabel,
  getFrequencyLabel as getPreferencesFrequencyLabel,
  getDefaultDisplayPreferences,
  getDefaultShoppingPreferences,
  getDefaultPrivacyPreferences,
  getDefaultCommunicationPreferences,
  getDefaultAccessibilityPreferences,
  getDefaultNotificationPreferences,
  getLanguageOptions,
  getCurrencyOptions,
  getDateFormatOptions,
  getTimeFormatOptions,
  getWeekStartOptions,
  getFontSizeOptions,
  getFrequencyOptions as getPreferencesFrequencyOptions,
  isNotificationEnabled,
  getNotificationFrequency,
  getNotificationCategories,
  USER_PREFERENCES_TYPE,
  USER_PREFERENCES_TYPE_LABELS,
  USER_PREFERENCES_TYPE_DESCRIPTIONS,
  PUBLIC_PREFERENCES_TYPES,
  PRIVATE_PREFERENCES_TYPES,
  isPublicPreference,
  isPrivatePreference,
  getPreferencesTypeLabel,
  getPreferencesTypeDescription,
  getPreferencesTypeByCategory,
  USER_PREFERENCES_STATUS,
  USER_PREFERENCES_STATUS_LABELS,
  USER_PREFERENCES_STATUS_COLORS,
  ACTIVE_PREFERENCES_STATUSES,
  INACTIVE_PREFERENCES_STATUSES,
  RESTRICTED_PREFERENCES_STATUSES,
  isPreferencesActive,
  isPreferencesRestricted,
  canModifyPreferences,
  getPreferencesStatusLabel,
  getPreferencesStatusColor,
} from './preferences';

export type {
  UserPreferencesLanguage,
  UserPreferencesCurrency,
  UserPreferencesDateFormat,
  UserPreferencesTimeFormat,
  UserPreferencesWeekStart,
  UserPreferencesFontSize,
  UserPreferencesFrequency,
  UserPreferencesType,
  UserPreferencesStatus,
} from './preferences';

// User Address Constants
export {
  USER_ADDRESS,
  DIVISIONS,
  DISTRICTS,
  getDivisionLabel,
  getDistrictsByDivision,
  getAllDivisions,
  getAllDistricts,
  getDivisionByDistrict,
  getAddressStatusMessage,
  isDefaultAddress,
  getFullAddress,
  validatePostalCode,
  validateAddressLine,
  isValidAddress,
  USER_ADDRESS_TYPE,
  USER_ADDRESS_TYPE_LABELS,
  USER_ADDRESS_TYPE_DESCRIPTIONS,
  SHIPPING_ADDRESS_TYPES,
  BILLING_ADDRESS_TYPES,
  RESIDENTIAL_ADDRESS_TYPES,
  BUSINESS_ADDRESS_TYPES,
  isShippingAddress,
  isBillingAddress,
  isResidentialAddress,
  isBusinessAddress,
  getAddressTypeLabel,
  getAddressTypeDescription,
  getAddressTypeByValue,
  USER_ADDRESS_STATUS,
  USER_ADDRESS_STATUS_LABELS,
  USER_ADDRESS_STATUS_COLORS,
  ACTIVE_ADDRESS_STATUSES,
  INACTIVE_ADDRESS_STATUSES,
  RESTRICTED_ADDRESS_STATUSES,
  VERIFICATION_REQUIRED_ADDRESS_STATUSES,
  isAddressActive,
  isAddressRestricted,
  canUseAddress,
  getAddressStatusLabel,
  getAddressStatusColor,
  validatePhoneNumber as validateAddressPhoneNumber,
} from './address';

export type {
  UserAddressType,
  UserAddressDivision,
  UserAddressDistrict,
  UserAddressStatus,
  Division,
} from './address';

// User Contact Constants
export {
  USER_CONTACT,
  getPhoneTypeLabel,
  getEmailTypeLabel,
  getSocialProviderLabel,
  getVerificationMethodLabel,
  getContactStatusMessage,
  isPrimaryContact,
  isVerifiedContact,
  validateEmail,
  validateWhatsAppNumber,
  getContactDisplayValue,
  isContactTypePhone,
  isContactTypeSocial,
  isContactTypeEmail,
  getContactTypeCategory,
  getVerificationMethodByType,
  USER_CONTACT_TYPE,
  USER_CONTACT_TYPE_LABELS,
  USER_CONTACT_TYPE_DESCRIPTIONS,
  PHONE_CONTACT_TYPES,
  DIGITAL_CONTACT_TYPES,
  EMERGENCY_CONTACT_TYPES,
  LOCATION_CONTACT_TYPES,
  isPhoneContact,
  isDigitalContact,
  isEmergencyContact,
  isLocationContact,
  getContactTypeLabel as getContactTypeLabelFromType,
  getContactTypeDescription,
  getContactTypeByValue,
  USER_CONTACT_STATUS,
  USER_CONTACT_STATUS_LABELS,
  USER_CONTACT_STATUS_COLORS,
  ACTIVE_CONTACT_STATUSES,
  INACTIVE_CONTACT_STATUSES,
  RESTRICTED_CONTACT_STATUSES,
  VERIFICATION_REQUIRED_CONTACT_STATUSES,
  VERIFIED_CONTACT_STATUSES,
  isContactActive,
  isContactRestricted,
  isContactVerified,
  isContactPending,
  canUseContact,
  getContactStatusLabel,
  getContactStatusColor,
  validatePhoneNumber as validateContactPhoneNumber,
} from './contact';

export type {
  UserContactType,
  UserContactPhoneType,
  UserContactEmailType,
  UserContactSocialProvider,
  UserContactVerificationMethod,
  UserContactStatus,
} from './contact';

// User Verification Constants
export {
  USER_VERIFICATION,
  getVerificationPurposeLabel,
  getVerificationChannelLabel,
  getVerificationStatusMessage,
  isVerificationComplete,
  isVerificationPending as isVerificationPendingState,
  isVerificationExpired,
  canResendVerification,
  isVerificationExpiredByTime,
  getRemainingTimeInSeconds,
  getVerificationCode,
  generateVerificationToken,
  getChannelForType,
  getVerificationPurposeForType,
  getVerificationExpiryTime,
  getMaxAttemptsForType,
  USER_VERIFICATION_TYPE,
  USER_VERIFICATION_TYPE_LABELS,
  USER_VERIFICATION_TYPE_DESCRIPTIONS,
  CONTACT_VERIFICATION_TYPES,
  SECURITY_VERIFICATION_TYPES,
  FINANCIAL_VERIFICATION_TYPES,
  ACCOUNT_VERIFICATION_TYPES,
  isContactVerification,
  isSecurityVerification,
  isFinancialVerification,
  isAccountVerification,
  getVerificationTypeLabel,
  getVerificationTypeDescription,
  getVerificationTypeByValue,
  USER_VERIFICATION_STATUS,
  USER_VERIFICATION_STATUS_LABELS,
  USER_VERIFICATION_STATUS_COLORS,
  ACTIVE_VERIFICATION_STATUSES,
  COMPLETED_VERIFICATION_STATUSES,
  FAILED_VERIFICATION_STATUSES,
  VALID_VERIFICATION_STATUSES,
  isVerificationStatusPending,
  isVerificationVerified,
  isVerificationFailed,
  isVerificationStatusComplete,
  canRetryVerification,
  getVerificationStatusLabel,
  getVerificationStatusColor,
} from './verification';

export type {
  UserVerificationPurpose,
  UserVerificationChannel,
  UserVerificationCodeLength,
  UserVerificationType,
  UserVerificationStatus,
} from './verification';

// User KYC Constants
export {
  USER_KYC,
  DOCUMENT_TYPES,
  getKYCLevelLabel,
  getKYCDocumentTypeLabel,
  getKYCStatusMessage,
  isKYCComplete,
  isKYCPending,
  isKYCUnderReview,
  isKYCRejected,
  isKYCExpired,
  canSubmitKYC,
  getRequiredDocumentTypes,
  getKYCLevelFromDocumentCount,
  getKYCLevelRequirements,
  validateKYCFile,
  getDocumentExpiryDays,
  isDocumentExpired,
  getKYCLevelDescription,
  getRequiredDocumentsForLevel,
  isLevelComplete,
  USER_KYC_TYPE,
  USER_KYC_TYPE_LABELS,
  USER_KYC_TYPE_DESCRIPTIONS,
  IDENTITY_KYC_TYPES,
  ADDRESS_KYC_TYPES,
  FINANCIAL_KYC_TYPES,
  BUSINESS_KYC_TYPES,
  isIdentityKYC,
  isAddressKYC,
  isFinancialKYC,
  isBusinessKYC,
  getKYCTypeLabel,
  getKYCTypeDescription,
  getKYCTypeByValue,
  getKYCTypeCategory,
  USER_KYC_STATUS,
  USER_KYC_STATUS_LABELS,
  USER_KYC_STATUS_COLORS,
  PENDING_KYC_STATUSES,
  COMPLETED_KYC_STATUSES,
  FAILED_KYC_STATUSES,
  ACTIONABLE_KYC_STATUSES,
  VERIFIED_KYC_STATUSES,
  isKYCPendingStatus,
  isKYCVerified,
  isKYCFailed,
  isKYCStatusComplete,
  canSubmitKYCStatus,
  isKYCUnderReviewStatus,
  getKYCStatusLabel,
  getKYCStatusColor,
} from './kyc';

export type {
  UserKYCLevel,
  UserKYCDocumentType,
  UserKYCType,
  UserKYCStatus,
  UserKYCValidationFileType,
} from './kyc';

// User Activity Constants
export {
  USER_ACTIVITY,
  getSeverityLabel,
  getSeverityColor,
  getSeverityPriority,
  getActivityStatusMessage,
  isActivityActive,
  isActivityCompleted,
  isActivityFailed,
  isActivityRead,
  isActivityArchived,
  getActivityTimeframeLabel,
  getTimeframeDateRange,
  getActivityMetadataValue,
  hasActivityMetadata,
  getActivityDescription,
  shouldArchiveActivity,
  getActivitySeverityFromType,
  USER_ACTIVITY_TYPE,
  USER_ACTIVITY_TYPE_LABELS,
  USER_ACTIVITY_TYPE_CATEGORIES,
  getActivityTypeLabel,
  getActivityCategory,
  getActivityTypesByCategory,
  isAuthenticationActivity,
  isOrderActivity,
  isPaymentActivity,
  isProductActivity,
  isSocialActivity,
  isSupportActivity,
  USER_ACTIVITY_STATUS,
  USER_ACTIVITY_STATUS_LABELS,
  USER_ACTIVITY_STATUS_COLORS,
  ACTIVE_ACTIVITY_STATUSES,
  COMPLETED_ACTIVITY_STATUSES,
  FAILED_ACTIVITY_STATUSES,
  ARCHIVED_ACTIVITY_STATUSES,
  ALL_ACTIVITY_STATUSES,
  isActivityStatusActive,
  isActivityStatusCompleted,
  isActivityStatusFailed,
  isActivityStatusArchived,
  isActivityFinished,
  getActivityStatusLabel,
  getActivityStatusColor,
} from './activity';

export type {
  UserActivitySeverity,
  UserActivityTimeframe,
  UserActivityMetadataKey,
  UserActivityType,
  UserActivityCategory,
  UserActivityStatus,
} from './activity';

// User Log Constants - শুধু সঠিক নামগুলো এক্সপোর্ট করা হচ্ছে
export {
  USER_LOG,
  getLogSeverityLabel,
  getLogSeverityColor,
  getLogSeverityPriority,
  getLogStatusMessage,
  isLogActive,
  isLogProcessed,
  isLogFailed,
  isLogArchived,
  getLogMetadataValue,
  hasLogMetadata,
  formatLogMessage,
  getLogMessageForType,
  shouldArchiveLog,
  getLogSeverityFromType,
  USER_LOG_TYPE,
  USER_LOG_TYPE_LABELS,
  USER_LOG_TYPE_DESCRIPTIONS,
  USER_LOG_TYPE_CATEGORIES,
  getLogTypeLabel,
  getLogTypeDescription,
  getLogCategory,
  getLogTypesByCategory,
  isOperationalLog,
  isSecurityLog,
  isPerformanceLog,
  isAuditLog,
  isSystemLog,
  USER_LOG_STATUS,
  USER_LOG_STATUS_LABELS,
  USER_LOG_STATUS_COLORS,
  ACTIVE_LOG_STATUSES,
  COMPLETED_LOG_STATUSES,
  FAILED_LOG_STATUSES,
  ARCHIVED_LOG_STATUSES,
  isLogActive as isLogStatusActive,
  isLogProcessed as isLogStatusProcessed,
  isLogFailed as isLogStatusFailed,
  isLogArchived as isLogStatusArchived,
  isLogFinished,
  getLogStatusLabel,
  getLogStatusColor,
  USER_ERROR,
  getUserErrorMessage,
  getUserErrorCategory,
  getHttpStatusForUserError,
  getUserErrorSeverity,
  getUserErrorRecoverySuggestion,
  // রিনেম করা ফাংশন - সঠিক নাম ব্যবহার করা হয়েছে
  isUserClientError,
  isUserServerError,
  isUserValidationError,
  isUserAuthenticationError,
  isUserAuthorizationError,
  isUserBusinessError,
  isUserAuditLog,
  isUserPerformanceLog,
  isUserSecurityLog,
  isUserSystemLog,
} from './log';

export type {
  UserLogSeverity,
  UserLogMetadataKey,
  UserLogType,
  UserLogCategory,
  UserLogStatus,
  UserErrorCategory,
  UserErrorCode,
} from './log';
