import { AUTH_ROLE } from '../auth/auth-role.constants';

export const USER_ROLE = {
  SUPER_ADMIN: AUTH_ROLE.SUPER_ADMIN,
  ADMIN: AUTH_ROLE.ADMIN,
  MODERATOR: AUTH_ROLE.MODERATOR,
  VENDOR: AUTH_ROLE.VENDOR,
  CUSTOMER: AUTH_ROLE.CUSTOMER,
  GUEST: AUTH_ROLE.GUEST,
  SUPPORT_AGENT: AUTH_ROLE.SUPPORT_AGENT,
  LOGISTICS_MANAGER: AUTH_ROLE.LOGISTICS_MANAGER,
} as const;

export type UserRoleType = (typeof USER_ROLE)[keyof typeof USER_ROLE];
