/**
 * User Permission Constants
 * All possible user permissions in the system
 * Imports common permission values where applicable
 */

/**
 * Core user permissions
 * Defines the fundamental permissions a user can have
 */
export const USER_PERMISSION = {
  // Profile Permissions
  PROFILE_VIEW: 'profile:view',
  PROFILE_UPDATE: 'profile:update',
  PROFILE_DELETE: 'profile:delete',
  PROFILE_EXPORT: 'profile:export',

  // Account Permissions
  ACCOUNT_VIEW: 'account:view',
  ACCOUNT_UPDATE: 'account:update',
  ACCOUNT_DELETE: 'account:delete',
  ACCOUNT_SUSPEND: 'account:suspend',
  ACCOUNT_ACTIVATE: 'account:activate',
  ACCOUNT_LOCK: 'account:lock',
  ACCOUNT_UNLOCK: 'account:unlock',

  // Address Permissions
  ADDRESS_VIEW: 'address:view',
  ADDRESS_CREATE: 'address:create',
  ADDRESS_UPDATE: 'address:update',
  ADDRESS_DELETE: 'address:delete',
  ADDRESS_VERIFY: 'address:verify',

  // Contact Permissions
  CONTACT_VIEW: 'contact:view',
  CONTACT_CREATE: 'contact:create',
  CONTACT_UPDATE: 'contact:update',
  CONTACT_DELETE: 'contact:delete',
  CONTACT_VERIFY: 'contact:verify',

  // KYC Permissions
  KYC_SUBMIT: 'kyc:submit',
  KYC_VIEW: 'kyc:view',
  KYC_UPDATE: 'kyc:update',
  KYC_APPROVE: 'kyc:approve',
  KYC_REJECT: 'kyc:reject',
  KYC_REVIEW: 'kyc:review',

  // Verification Permissions
  VERIFICATION_REQUEST: 'verification:request',
  VERIFICATION_VIEW: 'verification:view',
  VERIFICATION_APPROVE: 'verification:approve',
  VERIFICATION_REJECT: 'verification:reject',

  // Session Permissions
  SESSION_VIEW: 'session:view',
  SESSION_TERMINATE: 'session:terminate',
  SESSION_TERMINATE_ALL: 'session:terminate-all',

  // Activity Permissions
  ACTIVITY_VIEW: 'activity:view',
  ACTIVITY_EXPORT: 'activity:export',
  ACTIVITY_CLEAR: 'activity:clear',

  // Notification Permissions
  NOTIFICATION_VIEW: 'notification:view',
  NOTIFICATION_MARK_READ: 'notification:mark-read',
  NOTIFICATION_DELETE: 'notification:delete',
  NOTIFICATION_PREFERENCE: 'notification:preference',

  // Preference Permissions
  PREFERENCE_VIEW: 'preference:view',
  PREFERENCE_UPDATE: 'preference:update',
  PREFERENCE_RESET: 'preference:reset',

  // Settings Permissions
  SETTINGS_VIEW: 'settings:view',
  SETTINGS_UPDATE: 'settings:update',
  SETTINGS_RESET: 'settings:reset',

  // Security Permissions
  SECURITY_VIEW: 'security:view',
  SECURITY_UPDATE: 'security:update',
  SECURITY_LOGIN_HISTORY: 'security:login-history',
  SECURITY_DEVICE_MANAGE: 'security:device-manage',

  // Relationship Permissions
  RELATIONSHIP_VIEW: 'relationship:view',
  RELATIONSHIP_CREATE: 'relationship:create',
  RELATIONSHIP_UPDATE: 'relationship:update',
  RELATIONSHIP_DELETE: 'relationship:delete',
  RELATIONSHIP_BLOCK: 'relationship:block',
  RELATIONSHIP_UNBLOCK: 'relationship:unblock',

  // Subscription Permissions
  SUBSCRIPTION_VIEW: 'subscription:view',
  SUBSCRIPTION_CREATE: 'subscription:create',
  SUBSCRIPTION_CANCEL: 'subscription:cancel',
  SUBSCRIPTION_RENEW: 'subscription:renew',
  SUBSCRIPTION_UPGRADE: 'subscription:upgrade',
  SUBSCRIPTION_DOWNGRADE: 'subscription:downgrade',

  // Export Permissions
  EXPORT_USER_DATA: 'export:user-data',
  EXPORT_ACTIVITY: 'export:activity',
  EXPORT_SETTINGS: 'export:settings',
} as const;

/**
 * User permission categories
 * Grouping of permissions by functional area
 */
export const USER_PERMISSION_CATEGORY = {
  PROFILE: 'profile',
  ACCOUNT: 'account',
  ADDRESS: 'address',
  CONTACT: 'contact',
  KYC: 'kyc',
  VERIFICATION: 'verification',
  SESSION: 'session',
  ACTIVITY: 'activity',
  NOTIFICATION: 'notification',
  PREFERENCE: 'preference',
  SETTINGS: 'settings',
  SECURITY: 'security',
  RELATIONSHIP: 'relationship',
  SUBSCRIPTION: 'subscription',
  EXPORT: 'export',
} as const;

/**
 * User permission category mapping
 * Maps each permission to its category
 */
export const USER_PERMISSION_CATEGORY_MAP: Record<string, string> = {
  [USER_PERMISSION.PROFILE_VIEW]: USER_PERMISSION_CATEGORY.PROFILE,
  [USER_PERMISSION.PROFILE_UPDATE]: USER_PERMISSION_CATEGORY.PROFILE,
  [USER_PERMISSION.PROFILE_DELETE]: USER_PERMISSION_CATEGORY.PROFILE,
  [USER_PERMISSION.PROFILE_EXPORT]: USER_PERMISSION_CATEGORY.PROFILE,

  [USER_PERMISSION.ACCOUNT_VIEW]: USER_PERMISSION_CATEGORY.ACCOUNT,
  [USER_PERMISSION.ACCOUNT_UPDATE]: USER_PERMISSION_CATEGORY.ACCOUNT,
  [USER_PERMISSION.ACCOUNT_DELETE]: USER_PERMISSION_CATEGORY.ACCOUNT,
  [USER_PERMISSION.ACCOUNT_SUSPEND]: USER_PERMISSION_CATEGORY.ACCOUNT,
  [USER_PERMISSION.ACCOUNT_ACTIVATE]: USER_PERMISSION_CATEGORY.ACCOUNT,
  [USER_PERMISSION.ACCOUNT_LOCK]: USER_PERMISSION_CATEGORY.ACCOUNT,
  [USER_PERMISSION.ACCOUNT_UNLOCK]: USER_PERMISSION_CATEGORY.ACCOUNT,

  [USER_PERMISSION.ADDRESS_VIEW]: USER_PERMISSION_CATEGORY.ADDRESS,
  [USER_PERMISSION.ADDRESS_CREATE]: USER_PERMISSION_CATEGORY.ADDRESS,
  [USER_PERMISSION.ADDRESS_UPDATE]: USER_PERMISSION_CATEGORY.ADDRESS,
  [USER_PERMISSION.ADDRESS_DELETE]: USER_PERMISSION_CATEGORY.ADDRESS,
  [USER_PERMISSION.ADDRESS_VERIFY]: USER_PERMISSION_CATEGORY.ADDRESS,

  [USER_PERMISSION.CONTACT_VIEW]: USER_PERMISSION_CATEGORY.CONTACT,
  [USER_PERMISSION.CONTACT_CREATE]: USER_PERMISSION_CATEGORY.CONTACT,
  [USER_PERMISSION.CONTACT_UPDATE]: USER_PERMISSION_CATEGORY.CONTACT,
  [USER_PERMISSION.CONTACT_DELETE]: USER_PERMISSION_CATEGORY.CONTACT,
  [USER_PERMISSION.CONTACT_VERIFY]: USER_PERMISSION_CATEGORY.CONTACT,

  [USER_PERMISSION.KYC_SUBMIT]: USER_PERMISSION_CATEGORY.KYC,
  [USER_PERMISSION.KYC_VIEW]: USER_PERMISSION_CATEGORY.KYC,
  [USER_PERMISSION.KYC_UPDATE]: USER_PERMISSION_CATEGORY.KYC,
  [USER_PERMISSION.KYC_APPROVE]: USER_PERMISSION_CATEGORY.KYC,
  [USER_PERMISSION.KYC_REJECT]: USER_PERMISSION_CATEGORY.KYC,
  [USER_PERMISSION.KYC_REVIEW]: USER_PERMISSION_CATEGORY.KYC,

  [USER_PERMISSION.VERIFICATION_REQUEST]: USER_PERMISSION_CATEGORY.VERIFICATION,
  [USER_PERMISSION.VERIFICATION_VIEW]: USER_PERMISSION_CATEGORY.VERIFICATION,
  [USER_PERMISSION.VERIFICATION_APPROVE]: USER_PERMISSION_CATEGORY.VERIFICATION,
  [USER_PERMISSION.VERIFICATION_REJECT]: USER_PERMISSION_CATEGORY.VERIFICATION,

  [USER_PERMISSION.SESSION_VIEW]: USER_PERMISSION_CATEGORY.SESSION,
  [USER_PERMISSION.SESSION_TERMINATE]: USER_PERMISSION_CATEGORY.SESSION,
  [USER_PERMISSION.SESSION_TERMINATE_ALL]: USER_PERMISSION_CATEGORY.SESSION,

  [USER_PERMISSION.ACTIVITY_VIEW]: USER_PERMISSION_CATEGORY.ACTIVITY,
  [USER_PERMISSION.ACTIVITY_EXPORT]: USER_PERMISSION_CATEGORY.ACTIVITY,
  [USER_PERMISSION.ACTIVITY_CLEAR]: USER_PERMISSION_CATEGORY.ACTIVITY,

  [USER_PERMISSION.NOTIFICATION_VIEW]: USER_PERMISSION_CATEGORY.NOTIFICATION,
  [USER_PERMISSION.NOTIFICATION_MARK_READ]: USER_PERMISSION_CATEGORY.NOTIFICATION,
  [USER_PERMISSION.NOTIFICATION_DELETE]: USER_PERMISSION_CATEGORY.NOTIFICATION,
  [USER_PERMISSION.NOTIFICATION_PREFERENCE]: USER_PERMISSION_CATEGORY.NOTIFICATION,

  [USER_PERMISSION.PREFERENCE_VIEW]: USER_PERMISSION_CATEGORY.PREFERENCE,
  [USER_PERMISSION.PREFERENCE_UPDATE]: USER_PERMISSION_CATEGORY.PREFERENCE,
  [USER_PERMISSION.PREFERENCE_RESET]: USER_PERMISSION_CATEGORY.PREFERENCE,

  [USER_PERMISSION.SETTINGS_VIEW]: USER_PERMISSION_CATEGORY.SETTINGS,
  [USER_PERMISSION.SETTINGS_UPDATE]: USER_PERMISSION_CATEGORY.SETTINGS,
  [USER_PERMISSION.SETTINGS_RESET]: USER_PERMISSION_CATEGORY.SETTINGS,

  [USER_PERMISSION.SECURITY_VIEW]: USER_PERMISSION_CATEGORY.SECURITY,
  [USER_PERMISSION.SECURITY_UPDATE]: USER_PERMISSION_CATEGORY.SECURITY,
  [USER_PERMISSION.SECURITY_LOGIN_HISTORY]: USER_PERMISSION_CATEGORY.SECURITY,
  [USER_PERMISSION.SECURITY_DEVICE_MANAGE]: USER_PERMISSION_CATEGORY.SECURITY,

  [USER_PERMISSION.RELATIONSHIP_VIEW]: USER_PERMISSION_CATEGORY.RELATIONSHIP,
  [USER_PERMISSION.RELATIONSHIP_CREATE]: USER_PERMISSION_CATEGORY.RELATIONSHIP,
  [USER_PERMISSION.RELATIONSHIP_UPDATE]: USER_PERMISSION_CATEGORY.RELATIONSHIP,
  [USER_PERMISSION.RELATIONSHIP_DELETE]: USER_PERMISSION_CATEGORY.RELATIONSHIP,
  [USER_PERMISSION.RELATIONSHIP_BLOCK]: USER_PERMISSION_CATEGORY.RELATIONSHIP,
  [USER_PERMISSION.RELATIONSHIP_UNBLOCK]: USER_PERMISSION_CATEGORY.RELATIONSHIP,

  [USER_PERMISSION.SUBSCRIPTION_VIEW]: USER_PERMISSION_CATEGORY.SUBSCRIPTION,
  [USER_PERMISSION.SUBSCRIPTION_CREATE]: USER_PERMISSION_CATEGORY.SUBSCRIPTION,
  [USER_PERMISSION.SUBSCRIPTION_CANCEL]: USER_PERMISSION_CATEGORY.SUBSCRIPTION,
  [USER_PERMISSION.SUBSCRIPTION_RENEW]: USER_PERMISSION_CATEGORY.SUBSCRIPTION,
  [USER_PERMISSION.SUBSCRIPTION_UPGRADE]: USER_PERMISSION_CATEGORY.SUBSCRIPTION,
  [USER_PERMISSION.SUBSCRIPTION_DOWNGRADE]: USER_PERMISSION_CATEGORY.SUBSCRIPTION,

  [USER_PERMISSION.EXPORT_USER_DATA]: USER_PERMISSION_CATEGORY.EXPORT,
  [USER_PERMISSION.EXPORT_ACTIVITY]: USER_PERMISSION_CATEGORY.EXPORT,
  [USER_PERMISSION.EXPORT_SETTINGS]: USER_PERMISSION_CATEGORY.EXPORT,
};

/**
 * User permission labels
 * Human-readable labels for UI
 */
export const USER_PERMISSION_LABELS: Record<string, string> = {
  [USER_PERMISSION.PROFILE_VIEW]: 'View Profile',
  [USER_PERMISSION.PROFILE_UPDATE]: 'Update Profile',
  [USER_PERMISSION.PROFILE_DELETE]: 'Delete Profile',
  [USER_PERMISSION.PROFILE_EXPORT]: 'Export Profile',

  [USER_PERMISSION.ACCOUNT_VIEW]: 'View Account',
  [USER_PERMISSION.ACCOUNT_UPDATE]: 'Update Account',
  [USER_PERMISSION.ACCOUNT_DELETE]: 'Delete Account',
  [USER_PERMISSION.ACCOUNT_SUSPEND]: 'Suspend Account',
  [USER_PERMISSION.ACCOUNT_ACTIVATE]: 'Activate Account',
  [USER_PERMISSION.ACCOUNT_LOCK]: 'Lock Account',
  [USER_PERMISSION.ACCOUNT_UNLOCK]: 'Unlock Account',

  [USER_PERMISSION.ADDRESS_VIEW]: 'View Address',
  [USER_PERMISSION.ADDRESS_CREATE]: 'Create Address',
  [USER_PERMISSION.ADDRESS_UPDATE]: 'Update Address',
  [USER_PERMISSION.ADDRESS_DELETE]: 'Delete Address',
  [USER_PERMISSION.ADDRESS_VERIFY]: 'Verify Address',

  [USER_PERMISSION.CONTACT_VIEW]: 'View Contact',
  [USER_PERMISSION.CONTACT_CREATE]: 'Create Contact',
  [USER_PERMISSION.CONTACT_UPDATE]: 'Update Contact',
  [USER_PERMISSION.CONTACT_DELETE]: 'Delete Contact',
  [USER_PERMISSION.CONTACT_VERIFY]: 'Verify Contact',

  [USER_PERMISSION.KYC_SUBMIT]: 'Submit KYC',
  [USER_PERMISSION.KYC_VIEW]: 'View KYC',
  [USER_PERMISSION.KYC_UPDATE]: 'Update KYC',
  [USER_PERMISSION.KYC_APPROVE]: 'Approve KYC',
  [USER_PERMISSION.KYC_REJECT]: 'Reject KYC',
  [USER_PERMISSION.KYC_REVIEW]: 'Review KYC',

  [USER_PERMISSION.VERIFICATION_REQUEST]: 'Request Verification',
  [USER_PERMISSION.VERIFICATION_VIEW]: 'View Verification',
  [USER_PERMISSION.VERIFICATION_APPROVE]: 'Approve Verification',
  [USER_PERMISSION.VERIFICATION_REJECT]: 'Reject Verification',

  [USER_PERMISSION.SESSION_VIEW]: 'View Sessions',
  [USER_PERMISSION.SESSION_TERMINATE]: 'Terminate Session',
  [USER_PERMISSION.SESSION_TERMINATE_ALL]: 'Terminate All Sessions',

  [USER_PERMISSION.ACTIVITY_VIEW]: 'View Activity',
  [USER_PERMISSION.ACTIVITY_EXPORT]: 'Export Activity',
  [USER_PERMISSION.ACTIVITY_CLEAR]: 'Clear Activity',

  [USER_PERMISSION.NOTIFICATION_VIEW]: 'View Notifications',
  [USER_PERMISSION.NOTIFICATION_MARK_READ]: 'Mark Notification Read',
  [USER_PERMISSION.NOTIFICATION_DELETE]: 'Delete Notification',
  [USER_PERMISSION.NOTIFICATION_PREFERENCE]: 'Manage Notification Preferences',

  [USER_PERMISSION.PREFERENCE_VIEW]: 'View Preferences',
  [USER_PERMISSION.PREFERENCE_UPDATE]: 'Update Preferences',
  [USER_PERMISSION.PREFERENCE_RESET]: 'Reset Preferences',

  [USER_PERMISSION.SETTINGS_VIEW]: 'View Settings',
  [USER_PERMISSION.SETTINGS_UPDATE]: 'Update Settings',
  [USER_PERMISSION.SETTINGS_RESET]: 'Reset Settings',

  [USER_PERMISSION.SECURITY_VIEW]: 'View Security',
  [USER_PERMISSION.SECURITY_UPDATE]: 'Update Security',
  [USER_PERMISSION.SECURITY_LOGIN_HISTORY]: 'View Login History',
  [USER_PERMISSION.SECURITY_DEVICE_MANAGE]: 'Manage Devices',

  [USER_PERMISSION.RELATIONSHIP_VIEW]: 'View Relationships',
  [USER_PERMISSION.RELATIONSHIP_CREATE]: 'Create Relationship',
  [USER_PERMISSION.RELATIONSHIP_UPDATE]: 'Update Relationship',
  [USER_PERMISSION.RELATIONSHIP_DELETE]: 'Delete Relationship',
  [USER_PERMISSION.RELATIONSHIP_BLOCK]: 'Block Relationship',
  [USER_PERMISSION.RELATIONSHIP_UNBLOCK]: 'Unblock Relationship',

  [USER_PERMISSION.SUBSCRIPTION_VIEW]: 'View Subscription',
  [USER_PERMISSION.SUBSCRIPTION_CREATE]: 'Create Subscription',
  [USER_PERMISSION.SUBSCRIPTION_CANCEL]: 'Cancel Subscription',
  [USER_PERMISSION.SUBSCRIPTION_RENEW]: 'Renew Subscription',
  [USER_PERMISSION.SUBSCRIPTION_UPGRADE]: 'Upgrade Subscription',
  [USER_PERMISSION.SUBSCRIPTION_DOWNGRADE]: 'Downgrade Subscription',

  [USER_PERMISSION.EXPORT_USER_DATA]: 'Export User Data',
  [USER_PERMISSION.EXPORT_ACTIVITY]: 'Export Activity Data',
  [USER_PERMISSION.EXPORT_SETTINGS]: 'Export Settings',
};

/**
 * Permission dependency mapping
 * Some permissions require other permissions
 */
export const USER_PERMISSION_DEPENDENCIES: Record<string, string[]> = {
  [USER_PERMISSION.PROFILE_UPDATE]: [USER_PERMISSION.PROFILE_VIEW],
  [USER_PERMISSION.PROFILE_DELETE]: [USER_PERMISSION.PROFILE_VIEW],
  [USER_PERMISSION.PROFILE_EXPORT]: [USER_PERMISSION.PROFILE_VIEW],

  [USER_PERMISSION.ACCOUNT_UPDATE]: [USER_PERMISSION.ACCOUNT_VIEW],
  [USER_PERMISSION.ACCOUNT_DELETE]: [USER_PERMISSION.ACCOUNT_VIEW],
  [USER_PERMISSION.ACCOUNT_SUSPEND]: [USER_PERMISSION.ACCOUNT_VIEW],
  [USER_PERMISSION.ACCOUNT_ACTIVATE]: [USER_PERMISSION.ACCOUNT_VIEW],
  [USER_PERMISSION.ACCOUNT_LOCK]: [USER_PERMISSION.ACCOUNT_VIEW],
  [USER_PERMISSION.ACCOUNT_UNLOCK]: [USER_PERMISSION.ACCOUNT_VIEW],

  [USER_PERMISSION.ADDRESS_UPDATE]: [USER_PERMISSION.ADDRESS_VIEW],
  [USER_PERMISSION.ADDRESS_DELETE]: [USER_PERMISSION.ADDRESS_VIEW],
  [USER_PERMISSION.ADDRESS_VERIFY]: [USER_PERMISSION.ADDRESS_VIEW],

  [USER_PERMISSION.CONTACT_UPDATE]: [USER_PERMISSION.CONTACT_VIEW],
  [USER_PERMISSION.CONTACT_DELETE]: [USER_PERMISSION.CONTACT_VIEW],
  [USER_PERMISSION.CONTACT_VERIFY]: [USER_PERMISSION.CONTACT_VIEW],

  [USER_PERMISSION.KYC_UPDATE]: [USER_PERMISSION.KYC_VIEW],
  [USER_PERMISSION.KYC_APPROVE]: [USER_PERMISSION.KYC_VIEW],
  [USER_PERMISSION.KYC_REJECT]: [USER_PERMISSION.KYC_VIEW],
  [USER_PERMISSION.KYC_REVIEW]: [USER_PERMISSION.KYC_VIEW],

  [USER_PERMISSION.VERIFICATION_APPROVE]: [USER_PERMISSION.VERIFICATION_VIEW],
  [USER_PERMISSION.VERIFICATION_REJECT]: [USER_PERMISSION.VERIFICATION_VIEW],

  [USER_PERMISSION.SESSION_TERMINATE]: [USER_PERMISSION.SESSION_VIEW],
  [USER_PERMISSION.SESSION_TERMINATE_ALL]: [USER_PERMISSION.SESSION_VIEW],

  [USER_PERMISSION.ACTIVITY_EXPORT]: [USER_PERMISSION.ACTIVITY_VIEW],
  [USER_PERMISSION.ACTIVITY_CLEAR]: [USER_PERMISSION.ACTIVITY_VIEW],

  [USER_PERMISSION.NOTIFICATION_MARK_READ]: [USER_PERMISSION.NOTIFICATION_VIEW],
  [USER_PERMISSION.NOTIFICATION_DELETE]: [USER_PERMISSION.NOTIFICATION_VIEW],
  [USER_PERMISSION.NOTIFICATION_PREFERENCE]: [USER_PERMISSION.NOTIFICATION_VIEW],

  [USER_PERMISSION.PREFERENCE_UPDATE]: [USER_PERMISSION.PREFERENCE_VIEW],
  [USER_PERMISSION.PREFERENCE_RESET]: [USER_PERMISSION.PREFERENCE_VIEW],

  [USER_PERMISSION.SETTINGS_UPDATE]: [USER_PERMISSION.SETTINGS_VIEW],
  [USER_PERMISSION.SETTINGS_RESET]: [USER_PERMISSION.SETTINGS_VIEW],

  [USER_PERMISSION.SECURITY_UPDATE]: [USER_PERMISSION.SECURITY_VIEW],
  [USER_PERMISSION.SECURITY_LOGIN_HISTORY]: [USER_PERMISSION.SECURITY_VIEW],
  [USER_PERMISSION.SECURITY_DEVICE_MANAGE]: [USER_PERMISSION.SECURITY_VIEW],

  [USER_PERMISSION.RELATIONSHIP_UPDATE]: [USER_PERMISSION.RELATIONSHIP_VIEW],
  [USER_PERMISSION.RELATIONSHIP_DELETE]: [USER_PERMISSION.RELATIONSHIP_VIEW],
  [USER_PERMISSION.RELATIONSHIP_BLOCK]: [USER_PERMISSION.RELATIONSHIP_VIEW],
  [USER_PERMISSION.RELATIONSHIP_UNBLOCK]: [USER_PERMISSION.RELATIONSHIP_VIEW],

  [USER_PERMISSION.SUBSCRIPTION_CANCEL]: [USER_PERMISSION.SUBSCRIPTION_VIEW],
  [USER_PERMISSION.SUBSCRIPTION_RENEW]: [USER_PERMISSION.SUBSCRIPTION_VIEW],
  [USER_PERMISSION.SUBSCRIPTION_UPGRADE]: [USER_PERMISSION.SUBSCRIPTION_VIEW],
  [USER_PERMISSION.SUBSCRIPTION_DOWNGRADE]: [USER_PERMISSION.SUBSCRIPTION_VIEW],
};

/**
 * Check if user permission is valid
 */
export function isValidUserPermission(permission: string): boolean {
  return Object.values(USER_PERMISSION).includes(
    permission as (typeof USER_PERMISSION)[keyof typeof USER_PERMISSION]
  );
}

/**
 * Check if user permission category is valid
 */
export function isValidUserPermissionCategory(category: string): boolean {
  return Object.values(USER_PERMISSION_CATEGORY).includes(
    category as (typeof USER_PERMISSION_CATEGORY)[keyof typeof USER_PERMISSION_CATEGORY]
  );
}

/**
 * Get user permission label
 */
export function getUserPermissionLabel(permission: string): string {
  return USER_PERMISSION_LABELS[permission] || permission;
}

/**
 * Get user permission category
 */
export function getUserPermissionCategory(permission: string): string {
  return USER_PERMISSION_CATEGORY_MAP[permission] || USER_PERMISSION_CATEGORY.PROFILE;
}

/**
 * Get user permission dependencies
 */
export function getUserPermissionDependencies(permission: string): string[] {
  return USER_PERMISSION_DEPENDENCIES[permission] || [];
}

/**
 * Check if user has permission
 */
export function hasUserPermission(userPermissions: string[], requiredPermission: string): boolean {
  return userPermissions.includes(requiredPermission);
}

/**
 * Check if user has all permissions
 */
export function hasAllUserPermissions(
  userPermissions: string[],
  requiredPermissions: string[]
): boolean {
  return requiredPermissions.every((permission) => userPermissions.includes(permission));
}

/**
 * Check if user has any permission
 */
export function hasAnyUserPermission(
  userPermissions: string[],
  requiredPermissions: string[]
): boolean {
  return requiredPermissions.some((permission) => userPermissions.includes(permission));
}

/**
 * Get all user permissions by category
 */
export function getUserPermissionsByCategory(category: string): string[] {
  return Object.keys(USER_PERMISSION_CATEGORY_MAP).filter(
    (key) => USER_PERMISSION_CATEGORY_MAP[key] === category
  );
}

/**
 * Get all user permissions
 */
export function getAllUserPermissions(): string[] {
  return Object.values(USER_PERMISSION);
}

/**
 * Get profile permissions
 */
export function getProfileUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.PROFILE);
}

/**
 * Get account permissions
 */
export function getAccountUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.ACCOUNT);
}

/**
 * Get address permissions
 */
export function getAddressUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.ADDRESS);
}

/**
 * Get contact permissions
 */
export function getContactUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.CONTACT);
}

/**
 * Get KYC permissions
 */
export function getKycUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.KYC);
}

/**
 * Get verification permissions
 */
export function getVerificationUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.VERIFICATION);
}

/**
 * Get session permissions
 */
export function getSessionUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.SESSION);
}

/**
 * Get activity permissions
 */
export function getActivityUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.ACTIVITY);
}

/**
 * Get notification permissions
 */
export function getNotificationUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.NOTIFICATION);
}

/**
 * Get preference permissions
 */
export function getPreferenceUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.PREFERENCE);
}

/**
 * Get settings permissions
 */
export function getSettingsUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.SETTINGS);
}

/**
 * Get security permissions
 */
export function getSecurityUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.SECURITY);
}

/**
 * Get relationship permissions
 */
export function getRelationshipUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.RELATIONSHIP);
}

/**
 * Get subscription permissions
 */
export function getSubscriptionUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.SUBSCRIPTION);
}

/**
 * Get export permissions
 */
export function getExportUserPermissions(): string[] {
  return getUserPermissionsByCategory(USER_PERMISSION_CATEGORY.EXPORT);
}

/**
 * Permission status (for feature flags)
 */
export const USER_PERMISSION_STATUS = {
  ENABLED: 'enabled',
  DISABLED: 'disabled',
  DEPRECATED: 'deprecated',
  EXPERIMENTAL: 'experimental',
} as const;

/**
 * Permission security level
 */
export const USER_PERMISSION_SECURITY_LEVEL = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
} as const;

/**
 * Permission security level mapping
 */
export const USER_PERMISSION_SECURITY_LEVEL_MAP: Record<string, string> = {
  // Low security permissions
  [USER_PERMISSION.PROFILE_VIEW]: USER_PERMISSION_SECURITY_LEVEL.LOW,
  [USER_PERMISSION.ADDRESS_VIEW]: USER_PERMISSION_SECURITY_LEVEL.LOW,
  [USER_PERMISSION.CONTACT_VIEW]: USER_PERMISSION_SECURITY_LEVEL.LOW,
  [USER_PERMISSION.NOTIFICATION_VIEW]: USER_PERMISSION_SECURITY_LEVEL.LOW,
  [USER_PERMISSION.PREFERENCE_VIEW]: USER_PERMISSION_SECURITY_LEVEL.LOW,
  [USER_PERMISSION.SETTINGS_VIEW]: USER_PERMISSION_SECURITY_LEVEL.LOW,

  // Medium security permissions
  [USER_PERMISSION.PROFILE_UPDATE]: USER_PERMISSION_SECURITY_LEVEL.MEDIUM,
  [USER_PERMISSION.ADDRESS_CREATE]: USER_PERMISSION_SECURITY_LEVEL.MEDIUM,
  [USER_PERMISSION.ADDRESS_UPDATE]: USER_PERMISSION_SECURITY_LEVEL.MEDIUM,
  [USER_PERMISSION.CONTACT_CREATE]: USER_PERMISSION_SECURITY_LEVEL.MEDIUM,
  [USER_PERMISSION.CONTACT_UPDATE]: USER_PERMISSION_SECURITY_LEVEL.MEDIUM,
  [USER_PERMISSION.NOTIFICATION_MARK_READ]: USER_PERMISSION_SECURITY_LEVEL.MEDIUM,
  [USER_PERMISSION.PREFERENCE_UPDATE]: USER_PERMISSION_SECURITY_LEVEL.MEDIUM,
  [USER_PERMISSION.SETTINGS_UPDATE]: USER_PERMISSION_SECURITY_LEVEL.MEDIUM,

  // High security permissions
  [USER_PERMISSION.ACCOUNT_VIEW]: USER_PERMISSION_SECURITY_LEVEL.HIGH,
  [USER_PERMISSION.ACCOUNT_UPDATE]: USER_PERMISSION_SECURITY_LEVEL.HIGH,
  [USER_PERMISSION.ADDRESS_DELETE]: USER_PERMISSION_SECURITY_LEVEL.HIGH,
  [USER_PERMISSION.CONTACT_DELETE]: USER_PERMISSION_SECURITY_LEVEL.HIGH,
  [USER_PERMISSION.KYC_VIEW]: USER_PERMISSION_SECURITY_LEVEL.HIGH,
  [USER_PERMISSION.SESSION_VIEW]: USER_PERMISSION_SECURITY_LEVEL.HIGH,
  [USER_PERMISSION.SESSION_TERMINATE]: USER_PERMISSION_SECURITY_LEVEL.HIGH,
  [USER_PERMISSION.ACTIVITY_VIEW]: USER_PERMISSION_SECURITY_LEVEL.HIGH,
  [USER_PERMISSION.SECURITY_VIEW]: USER_PERMISSION_SECURITY_LEVEL.HIGH,
  [USER_PERMISSION.RELATIONSHIP_VIEW]: USER_PERMISSION_SECURITY_LEVEL.HIGH,
  [USER_PERMISSION.SUBSCRIPTION_VIEW]: USER_PERMISSION_SECURITY_LEVEL.HIGH,

  // Critical security permissions
  [USER_PERMISSION.PROFILE_DELETE]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.PROFILE_EXPORT]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.ACCOUNT_DELETE]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.ACCOUNT_SUSPEND]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.ACCOUNT_ACTIVATE]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.ACCOUNT_LOCK]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.ACCOUNT_UNLOCK]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.KYC_APPROVE]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.KYC_REJECT]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.VERIFICATION_APPROVE]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.VERIFICATION_REJECT]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.SESSION_TERMINATE_ALL]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.ACTIVITY_EXPORT]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.SECURITY_UPDATE]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.SECURITY_DEVICE_MANAGE]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.RELATIONSHIP_DELETE]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.RELATIONSHIP_BLOCK]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.SUBSCRIPTION_CANCEL]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
  [USER_PERMISSION.EXPORT_USER_DATA]: USER_PERMISSION_SECURITY_LEVEL.CRITICAL,
};

/**
 * Get user permission security level
 */
export function getUserPermissionSecurityLevel(permission: string): string {
  return USER_PERMISSION_SECURITY_LEVEL_MAP[permission] || USER_PERMISSION_SECURITY_LEVEL.LOW;
}

/**
 * Check if permission is high security
 */
export function isUserPermissionHighSecurity(permission: string): boolean {
  const level = getUserPermissionSecurityLevel(permission);
  return (
    level === USER_PERMISSION_SECURITY_LEVEL.HIGH ||
    level === USER_PERMISSION_SECURITY_LEVEL.CRITICAL
  );
}

/**
 * Check if permission is critical
 */
export function isUserPermissionCritical(permission: string): boolean {
  return getUserPermissionSecurityLevel(permission) === USER_PERMISSION_SECURITY_LEVEL.CRITICAL;
}

/**
 * User permission category labels
 */
export const USER_PERMISSION_CATEGORY_LABELS: Record<string, string> = {
  [USER_PERMISSION_CATEGORY.PROFILE]: 'Profile Permissions',
  [USER_PERMISSION_CATEGORY.ACCOUNT]: 'Account Permissions',
  [USER_PERMISSION_CATEGORY.ADDRESS]: 'Address Permissions',
  [USER_PERMISSION_CATEGORY.CONTACT]: 'Contact Permissions',
  [USER_PERMISSION_CATEGORY.KYC]: 'KYC Permissions',
  [USER_PERMISSION_CATEGORY.VERIFICATION]: 'Verification Permissions',
  [USER_PERMISSION_CATEGORY.SESSION]: 'Session Permissions',
  [USER_PERMISSION_CATEGORY.ACTIVITY]: 'Activity Permissions',
  [USER_PERMISSION_CATEGORY.NOTIFICATION]: 'Notification Permissions',
  [USER_PERMISSION_CATEGORY.PREFERENCE]: 'Preference Permissions',
  [USER_PERMISSION_CATEGORY.SETTINGS]: 'Settings Permissions',
  [USER_PERMISSION_CATEGORY.SECURITY]: 'Security Permissions',
  [USER_PERMISSION_CATEGORY.RELATIONSHIP]: 'Relationship Permissions',
  [USER_PERMISSION_CATEGORY.SUBSCRIPTION]: 'Subscription Permissions',
  [USER_PERMISSION_CATEGORY.EXPORT]: 'Export Permissions',
};

/**
 * Get user permission category label
 */
export function getUserPermissionCategoryLabel(category: string): string {
  return USER_PERMISSION_CATEGORY_LABELS[category] || category;
}
