/**
 * User Permission Constants
 * ইউজার পারমিশন সম্পর্কিত কনস্ট্যান্টস
 */

import { USER_ROLES } from './user-role.constants';

export const USER_PERMISSIONS = {
  // User management
  USER_CREATE: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  USER_READ: [
    USER_ROLES.SUPER_ADMIN,
    USER_ROLES.ADMIN,
    USER_ROLES.MANAGER,
    USER_ROLES.MODERATOR,
    USER_ROLES.SUPPORT,
  ],
  USER_UPDATE: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  USER_DELETE: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN],
  USER_SUSPEND: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN, USER_ROLES.MODERATOR],
  USER_UNLOCK: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN],
  USER_ROLE_ASSIGN: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN],
  USER_ROLE_REVOKE: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN],

  // Profile management
  PROFILE_READ: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN, USER_ROLES.USER],
  PROFILE_UPDATE: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN, USER_ROLES.USER],
  PROFILE_DELETE: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN],
  PROFILE_VERIFY: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN, USER_ROLES.MODERATOR],

  // User settings
  SETTINGS_READ: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN, USER_ROLES.USER],
  SETTINGS_UPDATE: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN, USER_ROLES.USER],
  SETTINGS_RESET: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN],

  // User preferences
  PREFERENCES_READ: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN, USER_ROLES.USER],
  PREFERENCES_UPDATE: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN, USER_ROLES.USER],
  PREFERENCES_RESET: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN],
} as const;
