/**
 * User Type Constants
 * ইউজার টাইপ সম্পর্কিত কনস্ট্যান্টস
 */

export const USER_TYPES = {
  REGULAR: 'regular',
  PREMIUM: 'premium',
  ENTERPRISE: 'enterprise',
  VIP: 'vip',
  GUEST: 'guest',
  FREE: 'free',
  TRIAL: 'trial',
  PRO: 'pro',
  BUSINESS: 'business',
  AGENCY: 'agency',
} as const;

export const USER_TYPE_METADATA = {
  REGULAR: {
    name: 'Regular',
    nameBangla: 'সাধারণ',
    level: 1,
    features: ['Basic features', 'Limited support'],
    maxUsers: 1,
    maxProducts: 10,
    storageLimit: 100,
  },
  PREMIUM: {
    name: 'Premium',
    nameBangla: 'প্রিমিয়াম',
    level: 2,
    features: ['Advanced features', 'Priority support', 'Analytics'],
    maxUsers: 5,
    maxProducts: 50,
    storageLimit: 500,
  },
  ENTERPRISE: {
    name: 'Enterprise',
    nameBangla: 'এন্টারপ্রাইজ',
    level: 3,
    features: ['All features', '24/7 support', 'Custom integrations'],
    maxUsers: 100,
    maxProducts: 1000,
    storageLimit: 5000,
  },
  VIP: {
    name: 'VIP',
    nameBangla: 'ভিআইপি',
    level: 4,
    features: ['All premium features', 'Dedicated support', 'Early access'],
    maxUsers: 10,
    maxProducts: 100,
    storageLimit: 1000,
  },
  GUEST: {
    name: 'Guest',
    nameBangla: 'অতিথি',
    level: 0,
    features: ['Read-only access'],
    maxUsers: 0,
    maxProducts: 0,
    storageLimit: 0,
  },
  FREE: {
    name: 'Free',
    nameBangla: 'বিনামূল্যে',
    level: 1,
    features: ['Basic features', 'Community support'],
    maxUsers: 1,
    maxProducts: 5,
    storageLimit: 50,
  },
  TRIAL: {
    name: 'Trial',
    nameBangla: 'ট্রায়াল',
    level: 2,
    features: ['All premium features', 'Limited time'],
    maxUsers: 3,
    maxProducts: 20,
    storageLimit: 200,
  },
  PRO: {
    name: 'Pro',
    nameBangla: 'প্রো',
    level: 2,
    features: ['Advanced features', 'Priority support'],
    maxUsers: 3,
    maxProducts: 30,
    storageLimit: 300,
  },
  BUSINESS: {
    name: 'Business',
    nameBangla: 'ব্যবসা',
    level: 3,
    features: ['All features', 'Team management', 'Reporting'],
    maxUsers: 50,
    maxProducts: 500,
    storageLimit: 2000,
  },
  AGENCY: {
    name: 'Agency',
    nameBangla: 'এজেন্সি',
    level: 3,
    features: ['All features', 'Client management', 'White label'],
    maxUsers: 20,
    maxProducts: 200,
    storageLimit: 1000,
  },
} as const;
