/**
 * Authentication SSO Status Constants
 * Status values for Single Sign-On authentication
 */

export const AUTH_SSO_STATUS = {
  PENDING: 'pending',
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  EXPIRED: 'expired',
  REVOKED: 'revoked',
  BLOCKED: 'blocked',

  AUTHENTICATED: 'authenticated',
  UNAUTHENTICATED: 'unauthenticated',
  AUTHENTICATION_PENDING: 'authentication_pending',
  AUTHENTICATION_FAILED: 'authentication_failed',

  SAML_RESPONSE_RECEIVED: 'saml_response_received',
  SAML_RESPONSE_VALIDATED: 'saml_response_validated',
  SAML_RESPONSE_INVALID: 'saml_response_invalid',
  SAML_ASSERTION_CREATED: 'saml_assertion_created',
  SAML_ASSERTION_VALIDATED: 'saml_assertion_validated',

  LDAP_BIND_SUCCESS: 'ldap_bind_success',
  LDAP_BIND_FAILED: 'ldap_bind_failed',
  LDAP_SEARCH_SUCCESS: 'ldap_search_success',
  LDAP_SEARCH_FAILED: 'ldap_search_failed',

  KERBEROS_TICKET_ISSUED: 'kerberos_ticket_issued',
  KERBEROS_TICKET_VALIDATED: 'kerberos_ticket_validated',
  KERBEROS_TICKET_EXPIRED: 'kerberos_ticket_expired',

  SESSION_ACTIVE: 'session_active',
  SESSION_EXPIRED: 'session_expired',
  SESSION_TERMINATED: 'session_terminated',
  SESSION_CREATED: 'session_created',
  SESSION_DESTROYED: 'session_destroyed',

  LOGOUT_INITIATED: 'logout_initiated',
  LOGOUT_SUCCESS: 'logout_success',
  LOGOUT_FAILED: 'logout_failed',
  LOGOUT_PENDING: 'logout_pending',

  METADATA_FETCHED: 'metadata_fetched',
  METADATA_FAILED: 'metadata_failed',
  METADATA_PENDING: 'metadata_pending',

  SECURE: 'secure',
  SUSPICIOUS: 'suspicious',
  COMPROMISED: 'compromised',
} as const;

export type AuthssoStatus = (typeof AUTH_SSO_STATUS)[keyof typeof AUTH_SSO_STATUS];

export const AUTHS_ACTIVE_SSO_STATUSES: AuthssoStatus[] = [
  AUTH_SSO_STATUS.ACTIVE,
  AUTH_SSO_STATUS.AUTHENTICATED,
  AUTH_SSO_STATUS.SAML_RESPONSE_VALIDATED,
  AUTH_SSO_STATUS.SAML_ASSERTION_VALIDATED,
  AUTH_SSO_STATUS.LDAP_BIND_SUCCESS,
  AUTH_SSO_STATUS.KERBEROS_TICKET_VALIDATED,
  AUTH_SSO_STATUS.SESSION_ACTIVE,
  AUTH_SSO_STATUS.SESSION_CREATED,
  AUTH_SSO_STATUS.SECURE,
  AUTH_SSO_STATUS.METADATA_FETCHED,
];

export const AUTHS_PENDING_SSO_STATUSES: AuthssoStatus[] = [
  AUTH_SSO_STATUS.PENDING,
  AUTH_SSO_STATUS.AUTHENTICATION_PENDING,
  AUTH_SSO_STATUS.LOGOUT_PENDING,
  AUTH_SSO_STATUS.METADATA_PENDING,
  AUTH_SSO_STATUS.SAML_RESPONSE_RECEIVED,
];

export const AUTHS_INACTIVE_SSO_STATUSES: AuthssoStatus[] = [
  AUTH_SSO_STATUS.INACTIVE,
  AUTH_SSO_STATUS.EXPIRED,
  AUTH_SSO_STATUS.REVOKED,
  AUTH_SSO_STATUS.UNAUTHENTICATED,
  AUTH_SSO_STATUS.SESSION_EXPIRED,
  AUTH_SSO_STATUS.SESSION_TERMINATED,
  AUTH_SSO_STATUS.SESSION_DESTROYED,
  AUTH_SSO_STATUS.KERBEROS_TICKET_EXPIRED,
];

export const AUTHS_FAILED_SSO_STATUSES: AuthssoStatus[] = [
  AUTH_SSO_STATUS.AUTHENTICATION_FAILED,
  AUTH_SSO_STATUS.SAML_RESPONSE_INVALID,
  AUTH_SSO_STATUS.LDAP_BIND_FAILED,
  AUTH_SSO_STATUS.LDAP_SEARCH_FAILED,
  AUTH_SSO_STATUS.LOGOUT_FAILED,
  AUTH_SSO_STATUS.METADATA_FAILED,
  AUTH_SSO_STATUS.BLOCKED,
];

export const AUTHS_SECURITY_SSO_STATUSES: AuthssoStatus[] = [
  AUTH_SSO_STATUS.SUSPICIOUS,
  AUTH_SSO_STATUS.COMPROMISED,
];

export const AUTHS_SAML_SSO_STATUSES: AuthssoStatus[] = [
  AUTH_SSO_STATUS.SAML_RESPONSE_RECEIVED,
  AUTH_SSO_STATUS.SAML_RESPONSE_VALIDATED,
  AUTH_SSO_STATUS.SAML_RESPONSE_INVALID,
  AUTH_SSO_STATUS.SAML_ASSERTION_CREATED,
  AUTH_SSO_STATUS.SAML_ASSERTION_VALIDATED,
];

export const AUTHS_LDAP_SSO_STATUSES: AuthssoStatus[] = [
  AUTH_SSO_STATUS.LDAP_BIND_SUCCESS,
  AUTH_SSO_STATUS.LDAP_BIND_FAILED,
  AUTH_SSO_STATUS.LDAP_SEARCH_SUCCESS,
  AUTH_SSO_STATUS.LDAP_SEARCH_FAILED,
];

export const AUTHS_LOGOUT_SSO_STATUSES: AuthssoStatus[] = [
  AUTH_SSO_STATUS.LOGOUT_INITIATED,
  AUTH_SSO_STATUS.LOGOUT_SUCCESS,
  AUTH_SSO_STATUS.LOGOUT_FAILED,
  AUTH_SSO_STATUS.LOGOUT_PENDING,
];

export function isAuthssoActive(status: AuthssoStatus): boolean {
  return AUTHS_ACTIVE_SSO_STATUSES.includes(status);
}

export function isAuthssoPending(status: AuthssoStatus): boolean {
  return AUTHS_PENDING_SSO_STATUSES.includes(status);
}

export function isAuthssoInactive(status: AuthssoStatus): boolean {
  return AUTHS_INACTIVE_SSO_STATUSES.includes(status);
}

export function isAuthssoFailed(status: AuthssoStatus): boolean {
  return AUTHS_FAILED_SSO_STATUSES.includes(status);
}

export function isAuthssoSecurityIssue(status: AuthssoStatus): boolean {
  return AUTHS_SECURITY_SSO_STATUSES.includes(status);
}

export function isAuthssoSAMLStatus(status: AuthssoStatus): boolean {
  return AUTHS_SAML_SSO_STATUSES.includes(status);
}

export function isAuthssoLDAPStatus(status: AuthssoStatus): boolean {
  return AUTHS_LDAP_SSO_STATUSES.includes(status);
}

export function isAuthssoLogoutStatus(status: AuthssoStatus): boolean {
  return AUTHS_LOGOUT_SSO_STATUSES.includes(status);
}

export function getAuthssoStatusLabel(status: AuthssoStatus): string {
  const labels: Record<AuthssoStatus, string> = {
    [AUTH_SSO_STATUS.PENDING]: 'Pending',
    [AUTH_SSO_STATUS.ACTIVE]: 'Active',
    [AUTH_SSO_STATUS.INACTIVE]: 'Inactive',
    [AUTH_SSO_STATUS.EXPIRED]: 'Expired',
    [AUTH_SSO_STATUS.REVOKED]: 'Revoked',
    [AUTH_SSO_STATUS.BLOCKED]: 'Blocked',
    [AUTH_SSO_STATUS.AUTHENTICATED]: 'Authenticated',
    [AUTH_SSO_STATUS.UNAUTHENTICATED]: 'Unauthenticated',
    [AUTH_SSO_STATUS.AUTHENTICATION_PENDING]: 'Authentication Pending',
    [AUTH_SSO_STATUS.AUTHENTICATION_FAILED]: 'Authentication Failed',
    [AUTH_SSO_STATUS.SAML_RESPONSE_RECEIVED]: 'SAML Response Received',
    [AUTH_SSO_STATUS.SAML_RESPONSE_VALIDATED]: 'SAML Response Validated',
    [AUTH_SSO_STATUS.SAML_RESPONSE_INVALID]: 'SAML Response Invalid',
    [AUTH_SSO_STATUS.SAML_ASSERTION_CREATED]: 'SAML Assertion Created',
    [AUTH_SSO_STATUS.SAML_ASSERTION_VALIDATED]: 'SAML Assertion Validated',
    [AUTH_SSO_STATUS.LDAP_BIND_SUCCESS]: 'LDAP Bind Success',
    [AUTH_SSO_STATUS.LDAP_BIND_FAILED]: 'LDAP Bind Failed',
    [AUTH_SSO_STATUS.LDAP_SEARCH_SUCCESS]: 'LDAP Search Success',
    [AUTH_SSO_STATUS.LDAP_SEARCH_FAILED]: 'LDAP Search Failed',
    [AUTH_SSO_STATUS.KERBEROS_TICKET_ISSUED]: 'Kerberos Ticket Issued',
    [AUTH_SSO_STATUS.KERBEROS_TICKET_VALIDATED]: 'Kerberos Ticket Validated',
    [AUTH_SSO_STATUS.KERBEROS_TICKET_EXPIRED]: 'Kerberos Ticket Expired',
    [AUTH_SSO_STATUS.SESSION_ACTIVE]: 'Session Active',
    [AUTH_SSO_STATUS.SESSION_EXPIRED]: 'Session Expired',
    [AUTH_SSO_STATUS.SESSION_TERMINATED]: 'Session Terminated',
    [AUTH_SSO_STATUS.SESSION_CREATED]: 'Session Created',
    [AUTH_SSO_STATUS.SESSION_DESTROYED]: 'Session Destroyed',
    [AUTH_SSO_STATUS.LOGOUT_INITIATED]: 'Logout Initiated',
    [AUTH_SSO_STATUS.LOGOUT_SUCCESS]: 'Logout Success',
    [AUTH_SSO_STATUS.LOGOUT_FAILED]: 'Logout Failed',
    [AUTH_SSO_STATUS.LOGOUT_PENDING]: 'Logout Pending',
    [AUTH_SSO_STATUS.METADATA_FETCHED]: 'Metadata Fetched',
    [AUTH_SSO_STATUS.METADATA_FAILED]: 'Metadata Failed',
    [AUTH_SSO_STATUS.METADATA_PENDING]: 'Metadata Pending',
    [AUTH_SSO_STATUS.SECURE]: 'Secure',
    [AUTH_SSO_STATUS.SUSPICIOUS]: 'Suspicious',
    [AUTH_SSO_STATUS.COMPROMISED]: 'Compromised',
  };

  return labels[status] || 'Unknown Status';
}

export function getAuthssoStatusColor(status: AuthssoStatus): string {
  const colors: Record<AuthssoStatus, string> = {
    [AUTH_SSO_STATUS.PENDING]: '#F59E0B',
    [AUTH_SSO_STATUS.ACTIVE]: '#10B981',
    [AUTH_SSO_STATUS.INACTIVE]: '#6B7280',
    [AUTH_SSO_STATUS.EXPIRED]: '#6B7280',
    [AUTH_SSO_STATUS.REVOKED]: '#6B7280',
    [AUTH_SSO_STATUS.BLOCKED]: '#DC2626',
    [AUTH_SSO_STATUS.AUTHENTICATED]: '#10B981',
    [AUTH_SSO_STATUS.UNAUTHENTICATED]: '#6B7280',
    [AUTH_SSO_STATUS.AUTHENTICATION_PENDING]: '#F59E0B',
    [AUTH_SSO_STATUS.AUTHENTICATION_FAILED]: '#EF4444',
    [AUTH_SSO_STATUS.SAML_RESPONSE_RECEIVED]: '#3B82F6',
    [AUTH_SSO_STATUS.SAML_RESPONSE_VALIDATED]: '#10B981',
    [AUTH_SSO_STATUS.SAML_RESPONSE_INVALID]: '#EF4444',
    [AUTH_SSO_STATUS.SAML_ASSERTION_CREATED]: '#3B82F6',
    [AUTH_SSO_STATUS.SAML_ASSERTION_VALIDATED]: '#10B981',
    [AUTH_SSO_STATUS.LDAP_BIND_SUCCESS]: '#10B981',
    [AUTH_SSO_STATUS.LDAP_BIND_FAILED]: '#EF4444',
    [AUTH_SSO_STATUS.LDAP_SEARCH_SUCCESS]: '#10B981',
    [AUTH_SSO_STATUS.LDAP_SEARCH_FAILED]: '#EF4444',
    [AUTH_SSO_STATUS.KERBEROS_TICKET_ISSUED]: '#8B5CF6',
    [AUTH_SSO_STATUS.KERBEROS_TICKET_VALIDATED]: '#10B981',
    [AUTH_SSO_STATUS.KERBEROS_TICKET_EXPIRED]: '#6B7280',
    [AUTH_SSO_STATUS.SESSION_ACTIVE]: '#10B981',
    [AUTH_SSO_STATUS.SESSION_EXPIRED]: '#6B7280',
    [AUTH_SSO_STATUS.SESSION_TERMINATED]: '#6B7280',
    [AUTH_SSO_STATUS.SESSION_CREATED]: '#3B82F6',
    [AUTH_SSO_STATUS.SESSION_DESTROYED]: '#6B7280',
    [AUTH_SSO_STATUS.LOGOUT_INITIATED]: '#F59E0B',
    [AUTH_SSO_STATUS.LOGOUT_SUCCESS]: '#10B981',
    [AUTH_SSO_STATUS.LOGOUT_FAILED]: '#EF4444',
    [AUTH_SSO_STATUS.LOGOUT_PENDING]: '#F59E0B',
    [AUTH_SSO_STATUS.METADATA_FETCHED]: '#10B981',
    [AUTH_SSO_STATUS.METADATA_FAILED]: '#EF4444',
    [AUTH_SSO_STATUS.METADATA_PENDING]: '#F59E0B',
    [AUTH_SSO_STATUS.SECURE]: '#10B981',
    [AUTH_SSO_STATUS.SUSPICIOUS]: '#F59E0B',
    [AUTH_SSO_STATUS.COMPROMISED]: '#DC2626',
  };

  return colors[status] || '#6B7280';
}

export function getAuthssoStatusPriority(status: AuthssoStatus): number {
  const priorities: Record<AuthssoStatus, number> = {
    [AUTH_SSO_STATUS.PENDING]: 5,
    [AUTH_SSO_STATUS.ACTIVE]: 10,
    [AUTH_SSO_STATUS.INACTIVE]: 3,
    [AUTH_SSO_STATUS.EXPIRED]: 3,
    [AUTH_SSO_STATUS.REVOKED]: 3,
    [AUTH_SSO_STATUS.BLOCKED]: 1,
    [AUTH_SSO_STATUS.AUTHENTICATED]: 10,
    [AUTH_SSO_STATUS.UNAUTHENTICATED]: 3,
    [AUTH_SSO_STATUS.AUTHENTICATION_PENDING]: 5,
    [AUTH_SSO_STATUS.AUTHENTICATION_FAILED]: 2,
    [AUTH_SSO_STATUS.SAML_RESPONSE_RECEIVED]: 6,
    [AUTH_SSO_STATUS.SAML_RESPONSE_VALIDATED]: 8,
    [AUTH_SSO_STATUS.SAML_RESPONSE_INVALID]: 2,
    [AUTH_SSO_STATUS.SAML_ASSERTION_CREATED]: 7,
    [AUTH_SSO_STATUS.SAML_ASSERTION_VALIDATED]: 9,
    [AUTH_SSO_STATUS.LDAP_BIND_SUCCESS]: 8,
    [AUTH_SSO_STATUS.LDAP_BIND_FAILED]: 2,
    [AUTH_SSO_STATUS.LDAP_SEARCH_SUCCESS]: 7,
    [AUTH_SSO_STATUS.LDAP_SEARCH_FAILED]: 2,
    [AUTH_SSO_STATUS.KERBEROS_TICKET_ISSUED]: 7,
    [AUTH_SSO_STATUS.KERBEROS_TICKET_VALIDATED]: 8,
    [AUTH_SSO_STATUS.KERBEROS_TICKET_EXPIRED]: 3,
    [AUTH_SSO_STATUS.SESSION_ACTIVE]: 9,
    [AUTH_SSO_STATUS.SESSION_EXPIRED]: 3,
    [AUTH_SSO_STATUS.SESSION_TERMINATED]: 3,
    [AUTH_SSO_STATUS.SESSION_CREATED]: 7,
    [AUTH_SSO_STATUS.SESSION_DESTROYED]: 3,
    [AUTH_SSO_STATUS.LOGOUT_INITIATED]: 5,
    [AUTH_SSO_STATUS.LOGOUT_SUCCESS]: 8,
    [AUTH_SSO_STATUS.LOGOUT_FAILED]: 2,
    [AUTH_SSO_STATUS.LOGOUT_PENDING]: 5,
    [AUTH_SSO_STATUS.METADATA_FETCHED]: 7,
    [AUTH_SSO_STATUS.METADATA_FAILED]: 2,
    [AUTH_SSO_STATUS.METADATA_PENDING]: 5,
    [AUTH_SSO_STATUS.SECURE]: 10,
    [AUTH_SSO_STATUS.SUSPICIOUS]: 4,
    [AUTH_SSO_STATUS.COMPROMISED]: 1,
  };

  return priorities[status] || 5;
}

export function getAuthssoStatusBadgeType(
  status: AuthssoStatus
): 'success' | 'warning' | 'error' | 'info' | 'default' {
  const types: Record<AuthssoStatus, 'success' | 'warning' | 'error' | 'info' | 'default'> = {
    [AUTH_SSO_STATUS.PENDING]: 'warning',
    [AUTH_SSO_STATUS.ACTIVE]: 'success',
    [AUTH_SSO_STATUS.INACTIVE]: 'default',
    [AUTH_SSO_STATUS.EXPIRED]: 'default',
    [AUTH_SSO_STATUS.REVOKED]: 'default',
    [AUTH_SSO_STATUS.BLOCKED]: 'error',
    [AUTH_SSO_STATUS.AUTHENTICATED]: 'success',
    [AUTH_SSO_STATUS.UNAUTHENTICATED]: 'default',
    [AUTH_SSO_STATUS.AUTHENTICATION_PENDING]: 'warning',
    [AUTH_SSO_STATUS.AUTHENTICATION_FAILED]: 'error',
    [AUTH_SSO_STATUS.SAML_RESPONSE_RECEIVED]: 'info',
    [AUTH_SSO_STATUS.SAML_RESPONSE_VALIDATED]: 'success',
    [AUTH_SSO_STATUS.SAML_RESPONSE_INVALID]: 'error',
    [AUTH_SSO_STATUS.SAML_ASSERTION_CREATED]: 'info',
    [AUTH_SSO_STATUS.SAML_ASSERTION_VALIDATED]: 'success',
    [AUTH_SSO_STATUS.LDAP_BIND_SUCCESS]: 'success',
    [AUTH_SSO_STATUS.LDAP_BIND_FAILED]: 'error',
    [AUTH_SSO_STATUS.LDAP_SEARCH_SUCCESS]: 'success',
    [AUTH_SSO_STATUS.LDAP_SEARCH_FAILED]: 'error',
    [AUTH_SSO_STATUS.KERBEROS_TICKET_ISSUED]: 'info',
    [AUTH_SSO_STATUS.KERBEROS_TICKET_VALIDATED]: 'success',
    [AUTH_SSO_STATUS.KERBEROS_TICKET_EXPIRED]: 'default',
    [AUTH_SSO_STATUS.SESSION_ACTIVE]: 'success',
    [AUTH_SSO_STATUS.SESSION_EXPIRED]: 'default',
    [AUTH_SSO_STATUS.SESSION_TERMINATED]: 'default',
    [AUTH_SSO_STATUS.SESSION_CREATED]: 'info',
    [AUTH_SSO_STATUS.SESSION_DESTROYED]: 'default',
    [AUTH_SSO_STATUS.LOGOUT_INITIATED]: 'warning',
    [AUTH_SSO_STATUS.LOGOUT_SUCCESS]: 'success',
    [AUTH_SSO_STATUS.LOGOUT_FAILED]: 'error',
    [AUTH_SSO_STATUS.LOGOUT_PENDING]: 'warning',
    [AUTH_SSO_STATUS.METADATA_FETCHED]: 'success',
    [AUTH_SSO_STATUS.METADATA_FAILED]: 'error',
    [AUTH_SSO_STATUS.METADATA_PENDING]: 'warning',
    [AUTH_SSO_STATUS.SECURE]: 'success',
    [AUTH_SSO_STATUS.SUSPICIOUS]: 'warning',
    [AUTH_SSO_STATUS.COMPROMISED]: 'error',
  };

  return types[status] || 'default';
}
