/**
 * Logistics Error Constants
 * Error definitions for logistics system - Bangladesh based
 */

export const LOGISTICS_ERROR = {
  // Error Codes
  CODES: {
    // General Errors (10000-10099)
    GENERAL_ERROR: 10000,
    VALIDATION_ERROR: 10001,
    NOT_FOUND: 10002,
    UNAUTHORIZED: 10003,
    FORBIDDEN: 10004,
    BAD_REQUEST: 10005,
    INTERNAL_ERROR: 10006,
    SERVICE_UNAVAILABLE: 10007,
    TIMEOUT: 10008,
    RATE_LIMIT: 10009,

    // Shipment Errors (10100-10199)
    SHIPMENT_NOT_FOUND: 10100,
    SHIPMENT_INVALID_STATUS: 10101,
    SHIPMENT_INVALID_TYPE: 10102,
    SHIPMENT_INVALID_PRIORITY: 10103,
    SHIPMENT_ALREADY_DELIVERED: 10104,
    SHIPMENT_CANNOT_CANCEL: 10105,
    SHIPMENT_WEIGHT_EXCEEDED: 10106,
    SHIPMENT_VOLUME_EXCEEDED: 10107,
    SHIPMENT_INVALID_ADDRESS: 10108,
    SHIPMENT_TRACKING_FAILED: 10109,

    // Delivery Errors (10200-10299)
    DELIVERY_NOT_FOUND: 10200,
    DELIVERY_INVALID_STATUS: 10201,
    DELIVERY_INVALID_TYPE: 10202,
    DELIVERY_ALREADY_DELIVERED: 10203,
    DELIVERY_CANNOT_CANCEL: 10204,
    DELIVERY_ADDRESS_INVALID: 10205,
    DELIVERY_TIME_SLOT_UNAVAILABLE: 10206,
    DELIVERY_ZONE_UNSERVICEABLE: 10207,
    DELIVERY_FAILED_ATTEMPT: 10208,
    DELIVERY_RETURN_INITIATED: 10209,

    // Courier Errors (10300-10399)
    COURIER_NOT_FOUND: 10300,
    COURIER_INVALID_STATUS: 10301,
    COURIER_UNSERVICEABLE: 10302,
    COURIER_SERVICE_UNAVAILABLE: 10303,
    COURIER_INVALID_TYPE: 10304,

    // Vehicle Errors (10400-10499)
    VEHICLE_NOT_FOUND: 10400,
    VEHICLE_INVALID_STATUS: 10401,
    VEHICLE_UNAVAILABLE: 10402,
    VEHICLE_MAINTENANCE_REQUIRED: 10403,
    VEHICLE_CAPACITY_EXCEEDED: 10404,
    VEHICLE_TYPE_INVALID: 10405,

    // Driver Errors (10500-10599)
    DRIVER_NOT_FOUND: 10500,
    DRIVER_INVALID_STATUS: 10501,
    DRIVER_UNAVAILABLE: 10502,
    DRIVER_LICENSE_INVALID: 10503,
    DRIVER_ON_LEAVE: 10504,
    DRIVER_MAX_HOURS_EXCEEDED: 10505,

    // Warehouse Errors (10600-10699)
    WAREHOUSE_NOT_FOUND: 10600,
    WAREHOUSE_INVALID_STATUS: 10601,
    WAREHOUSE_FULL: 10602,
    WAREHOUSE_MAINTENANCE: 10603,
    WAREHOUSE_INVENTORY_LOW: 10604,

    // Tracking Errors (10700-10799)
    TRACKING_NOT_FOUND: 10700,
    TRACKING_INVALID_STATUS: 10701,
    TRACKING_UPDATE_FAILED: 10702,
    TRACKING_EVENT_INVALID: 10703,

    // Route Errors (10800-10899)
    ROUTE_NOT_FOUND: 10800,
    ROUTE_INVALID_STATUS: 10801,
    ROUTE_BLOCKED: 10802,
    ROUTE_MAINTENANCE: 10803,
    ROUTE_WEATHER_DISRUPTION: 10804,

    // Zone Errors (10900-10999)
    ZONE_NOT_FOUND: 10900,
    ZONE_INVALID_STATUS: 10901,
    ZONE_UNSERVICEABLE: 10902,
    ZONE_RESTRICTED: 10903,

    // Return Errors (11000-11099)
    RETURN_NOT_FOUND: 11000,
    RETURN_INVALID_STATUS: 11001,
    RETURN_REASON_INVALID: 11002,
    RETURN_WINDOW_EXPIRED: 11003,
    RETURN_ALREADY_PROCESSED: 11004,

    // Insurance Errors (11100-11199)
    INSURANCE_NOT_FOUND: 11100,
    INSURANCE_INVALID_STATUS: 11101,
    INSURANCE_CLAIM_FAILED: 11102,
    INSURANCE_EXPIRED: 11103,
    INSURANCE_COVERAGE_INSUFFICIENT: 11104,

    // Permission Errors (11200-11299)
    PERMISSION_DENIED: 11200,
    PERMISSION_INSUFFICIENT: 11201,
    PERMISSION_INVALID_ROLE: 11202,
    PERMISSION_INVALID_ACTION: 11203,

    // Report Errors (11300-11399)
    REPORT_NOT_FOUND: 11300,
    REPORT_GENERATION_FAILED: 11301,
    REPORT_EXPORT_FAILED: 11302,
    REPORT_INVALID_FORMAT: 11303,
    REPORT_TOO_LARGE: 11304,

    // Analytics Errors (11400-11499)
    ANALYTICS_NOT_FOUND: 11400,
    ANALYTICS_GENERATION_FAILED: 11401,
    ANALYTICS_INVALID_METRIC: 11402,
    ANALYTICS_INVALID_PERIOD: 11403,
  } as const,

  // Error Categories
  CATEGORIES: {
    VALIDATION: 'validation',
    AUTHORIZATION: 'authorization',
    NOT_FOUND: 'not_found',
    CONFLICT: 'conflict',
    INTERNAL: 'internal',
    EXTERNAL: 'external',
    RATE_LIMIT: 'rate_limit',
    BUSINESS: 'business',
  } as const,

  // Error Severities
  SEVERITIES: {
    CRITICAL: 'critical',
    HIGH: 'high',
    MEDIUM: 'medium',
    LOW: 'low',
    INFO: 'info',
  } as const,
} as const;

// Error Codes
export type LogisticsErrorCode = (typeof LOGISTICS_ERROR.CODES)[keyof typeof LOGISTICS_ERROR.CODES];

// Error Categories
export type LogisticsErrorCategory =
  (typeof LOGISTICS_ERROR.CATEGORIES)[keyof typeof LOGISTICS_ERROR.CATEGORIES];

// Error Severities
export type LogisticsErrorSeverity =
  (typeof LOGISTICS_ERROR.SEVERITIES)[keyof typeof LOGISTICS_ERROR.SEVERITIES];

// Utility Functions
export function logisticsErrorGetMessage(code: LogisticsErrorCode): string {
  const messages: Record<LogisticsErrorCode, string> = {
    [LOGISTICS_ERROR.CODES.GENERAL_ERROR]: 'A general error occurred',
    [LOGISTICS_ERROR.CODES.VALIDATION_ERROR]: 'Validation failed',
    [LOGISTICS_ERROR.CODES.NOT_FOUND]: 'Resource not found',
    [LOGISTICS_ERROR.CODES.UNAUTHORIZED]: 'Unauthorized access',
    [LOGISTICS_ERROR.CODES.FORBIDDEN]: 'Forbidden access',
    [LOGISTICS_ERROR.CODES.BAD_REQUEST]: 'Bad request',
    [LOGISTICS_ERROR.CODES.INTERNAL_ERROR]: 'Internal server error',
    [LOGISTICS_ERROR.CODES.SERVICE_UNAVAILABLE]: 'Service unavailable',
    [LOGISTICS_ERROR.CODES.TIMEOUT]: 'Request timeout',
    [LOGISTICS_ERROR.CODES.RATE_LIMIT]: 'Rate limit exceeded',

    [LOGISTICS_ERROR.CODES.SHIPMENT_NOT_FOUND]: 'Shipment not found',
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_STATUS]: 'Invalid shipment status',
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_TYPE]: 'Invalid shipment type',
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_PRIORITY]: 'Invalid shipment priority',
    [LOGISTICS_ERROR.CODES.SHIPMENT_ALREADY_DELIVERED]: 'Shipment already delivered',
    [LOGISTICS_ERROR.CODES.SHIPMENT_CANNOT_CANCEL]: 'Shipment cannot be cancelled',
    [LOGISTICS_ERROR.CODES.SHIPMENT_WEIGHT_EXCEEDED]: 'Shipment weight exceeded',
    [LOGISTICS_ERROR.CODES.SHIPMENT_VOLUME_EXCEEDED]: 'Shipment volume exceeded',
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_ADDRESS]: 'Invalid shipment address',
    [LOGISTICS_ERROR.CODES.SHIPMENT_TRACKING_FAILED]: 'Shipment tracking failed',

    [LOGISTICS_ERROR.CODES.DELIVERY_NOT_FOUND]: 'Delivery not found',
    [LOGISTICS_ERROR.CODES.DELIVERY_INVALID_STATUS]: 'Invalid delivery status',
    [LOGISTICS_ERROR.CODES.DELIVERY_INVALID_TYPE]: 'Invalid delivery type',
    [LOGISTICS_ERROR.CODES.DELIVERY_ALREADY_DELIVERED]: 'Already delivered',
    [LOGISTICS_ERROR.CODES.DELIVERY_CANNOT_CANCEL]: 'Delivery cannot be cancelled',
    [LOGISTICS_ERROR.CODES.DELIVERY_ADDRESS_INVALID]: 'Invalid delivery address',
    [LOGISTICS_ERROR.CODES.DELIVERY_TIME_SLOT_UNAVAILABLE]: 'Time slot unavailable',
    [LOGISTICS_ERROR.CODES.DELIVERY_ZONE_UNSERVICEABLE]: 'Zone unserviceable',
    [LOGISTICS_ERROR.CODES.DELIVERY_FAILED_ATTEMPT]: 'Delivery attempt failed',
    [LOGISTICS_ERROR.CODES.DELIVERY_RETURN_INITIATED]: 'Return initiated',

    [LOGISTICS_ERROR.CODES.COURIER_NOT_FOUND]: 'Courier not found',
    [LOGISTICS_ERROR.CODES.COURIER_INVALID_STATUS]: 'Invalid courier status',
    [LOGISTICS_ERROR.CODES.COURIER_UNSERVICEABLE]: 'Courier unserviceable',
    [LOGISTICS_ERROR.CODES.COURIER_SERVICE_UNAVAILABLE]: 'Courier service unavailable',
    [LOGISTICS_ERROR.CODES.COURIER_INVALID_TYPE]: 'Invalid courier type',

    [LOGISTICS_ERROR.CODES.VEHICLE_NOT_FOUND]: 'Vehicle not found',
    [LOGISTICS_ERROR.CODES.VEHICLE_INVALID_STATUS]: 'Invalid vehicle status',
    [LOGISTICS_ERROR.CODES.VEHICLE_UNAVAILABLE]: 'Vehicle unavailable',
    [LOGISTICS_ERROR.CODES.VEHICLE_MAINTENANCE_REQUIRED]: 'Maintenance required',
    [LOGISTICS_ERROR.CODES.VEHICLE_CAPACITY_EXCEEDED]: 'Vehicle capacity exceeded',
    [LOGISTICS_ERROR.CODES.VEHICLE_TYPE_INVALID]: 'Invalid vehicle type',

    [LOGISTICS_ERROR.CODES.DRIVER_NOT_FOUND]: 'Driver not found',
    [LOGISTICS_ERROR.CODES.DRIVER_INVALID_STATUS]: 'Invalid driver status',
    [LOGISTICS_ERROR.CODES.DRIVER_UNAVAILABLE]: 'Driver unavailable',
    [LOGISTICS_ERROR.CODES.DRIVER_LICENSE_INVALID]: 'Invalid driver license',
    [LOGISTICS_ERROR.CODES.DRIVER_ON_LEAVE]: 'Driver on leave',
    [LOGISTICS_ERROR.CODES.DRIVER_MAX_HOURS_EXCEEDED]: 'Driver hours exceeded',

    [LOGISTICS_ERROR.CODES.WAREHOUSE_NOT_FOUND]: 'Warehouse not found',
    [LOGISTICS_ERROR.CODES.WAREHOUSE_INVALID_STATUS]: 'Invalid warehouse status',
    [LOGISTICS_ERROR.CODES.WAREHOUSE_FULL]: 'Warehouse at full capacity',
    [LOGISTICS_ERROR.CODES.WAREHOUSE_MAINTENANCE]: 'Warehouse under maintenance',
    [LOGISTICS_ERROR.CODES.WAREHOUSE_INVENTORY_LOW]: 'Warehouse inventory low',

    [LOGISTICS_ERROR.CODES.TRACKING_NOT_FOUND]: 'Tracking not found',
    [LOGISTICS_ERROR.CODES.TRACKING_INVALID_STATUS]: 'Invalid tracking status',
    [LOGISTICS_ERROR.CODES.TRACKING_UPDATE_FAILED]: 'Tracking update failed',
    [LOGISTICS_ERROR.CODES.TRACKING_EVENT_INVALID]: 'Invalid tracking event',

    [LOGISTICS_ERROR.CODES.ROUTE_NOT_FOUND]: 'Route not found',
    [LOGISTICS_ERROR.CODES.ROUTE_INVALID_STATUS]: 'Invalid route status',
    [LOGISTICS_ERROR.CODES.ROUTE_BLOCKED]: 'Route blocked',
    [LOGISTICS_ERROR.CODES.ROUTE_MAINTENANCE]: 'Route under maintenance',
    [LOGISTICS_ERROR.CODES.ROUTE_WEATHER_DISRUPTION]: 'Weather disruption',

    [LOGISTICS_ERROR.CODES.ZONE_NOT_FOUND]: 'Zone not found',
    [LOGISTICS_ERROR.CODES.ZONE_INVALID_STATUS]: 'Invalid zone status',
    [LOGISTICS_ERROR.CODES.ZONE_UNSERVICEABLE]: 'Zone unserviceable',
    [LOGISTICS_ERROR.CODES.ZONE_RESTRICTED]: 'Zone restricted',

    [LOGISTICS_ERROR.CODES.RETURN_NOT_FOUND]: 'Return not found',
    [LOGISTICS_ERROR.CODES.RETURN_INVALID_STATUS]: 'Invalid return status',
    [LOGISTICS_ERROR.CODES.RETURN_REASON_INVALID]: 'Invalid return reason',
    [LOGISTICS_ERROR.CODES.RETURN_WINDOW_EXPIRED]: 'Return window expired',
    [LOGISTICS_ERROR.CODES.RETURN_ALREADY_PROCESSED]: 'Return already processed',

    [LOGISTICS_ERROR.CODES.INSURANCE_NOT_FOUND]: 'Insurance not found',
    [LOGISTICS_ERROR.CODES.INSURANCE_INVALID_STATUS]: 'Invalid insurance status',
    [LOGISTICS_ERROR.CODES.INSURANCE_CLAIM_FAILED]: 'Insurance claim failed',
    [LOGISTICS_ERROR.CODES.INSURANCE_EXPIRED]: 'Insurance expired',
    [LOGISTICS_ERROR.CODES.INSURANCE_COVERAGE_INSUFFICIENT]: 'Insufficient coverage',

    [LOGISTICS_ERROR.CODES.PERMISSION_DENIED]: 'Permission denied',
    [LOGISTICS_ERROR.CODES.PERMISSION_INSUFFICIENT]: 'Insufficient permissions',
    [LOGISTICS_ERROR.CODES.PERMISSION_INVALID_ROLE]: 'Invalid role',
    [LOGISTICS_ERROR.CODES.PERMISSION_INVALID_ACTION]: 'Invalid action',

    [LOGISTICS_ERROR.CODES.REPORT_NOT_FOUND]: 'Report not found',
    [LOGISTICS_ERROR.CODES.REPORT_GENERATION_FAILED]: 'Report generation failed',
    [LOGISTICS_ERROR.CODES.REPORT_EXPORT_FAILED]: 'Report export failed',
    [LOGISTICS_ERROR.CODES.REPORT_INVALID_FORMAT]: 'Invalid report format',
    [LOGISTICS_ERROR.CODES.REPORT_TOO_LARGE]: 'Report too large',

    [LOGISTICS_ERROR.CODES.ANALYTICS_NOT_FOUND]: 'Analytics not found',
    [LOGISTICS_ERROR.CODES.ANALYTICS_GENERATION_FAILED]: 'Analytics generation failed',
    [LOGISTICS_ERROR.CODES.ANALYTICS_INVALID_METRIC]: 'Invalid metric',
    [LOGISTICS_ERROR.CODES.ANALYTICS_INVALID_PERIOD]: 'Invalid period',
  };
  return messages[code] || 'Unknown error';
}

export function logisticsErrorGetCategory(code: LogisticsErrorCode): LogisticsErrorCategory {
  const categories: Record<LogisticsErrorCode, LogisticsErrorCategory> = {
    [LOGISTICS_ERROR.CODES.GENERAL_ERROR]: LOGISTICS_ERROR.CATEGORIES.INTERNAL,
    [LOGISTICS_ERROR.CODES.VALIDATION_ERROR]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.NOT_FOUND]: LOGISTICS_ERROR.CATEGORIES.NOT_FOUND,
    [LOGISTICS_ERROR.CODES.UNAUTHORIZED]: LOGISTICS_ERROR.CATEGORIES.AUTHORIZATION,
    [LOGISTICS_ERROR.CODES.FORBIDDEN]: LOGISTICS_ERROR.CATEGORIES.AUTHORIZATION,
    [LOGISTICS_ERROR.CODES.BAD_REQUEST]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.INTERNAL_ERROR]: LOGISTICS_ERROR.CATEGORIES.INTERNAL,
    [LOGISTICS_ERROR.CODES.SERVICE_UNAVAILABLE]: LOGISTICS_ERROR.CATEGORIES.EXTERNAL,
    [LOGISTICS_ERROR.CODES.TIMEOUT]: LOGISTICS_ERROR.CATEGORIES.EXTERNAL,
    [LOGISTICS_ERROR.CODES.RATE_LIMIT]: LOGISTICS_ERROR.CATEGORIES.RATE_LIMIT,

    [LOGISTICS_ERROR.CODES.SHIPMENT_NOT_FOUND]: LOGISTICS_ERROR.CATEGORIES.NOT_FOUND,
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_STATUS]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_TYPE]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_PRIORITY]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.SHIPMENT_ALREADY_DELIVERED]: LOGISTICS_ERROR.CATEGORIES.CONFLICT,
    [LOGISTICS_ERROR.CODES.SHIPMENT_CANNOT_CANCEL]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.SHIPMENT_WEIGHT_EXCEEDED]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.SHIPMENT_VOLUME_EXCEEDED]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_ADDRESS]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.SHIPMENT_TRACKING_FAILED]: LOGISTICS_ERROR.CATEGORIES.INTERNAL,

    [LOGISTICS_ERROR.CODES.DELIVERY_NOT_FOUND]: LOGISTICS_ERROR.CATEGORIES.NOT_FOUND,
    [LOGISTICS_ERROR.CODES.DELIVERY_INVALID_STATUS]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.DELIVERY_INVALID_TYPE]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.DELIVERY_ALREADY_DELIVERED]: LOGISTICS_ERROR.CATEGORIES.CONFLICT,
    [LOGISTICS_ERROR.CODES.DELIVERY_CANNOT_CANCEL]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.DELIVERY_ADDRESS_INVALID]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.DELIVERY_TIME_SLOT_UNAVAILABLE]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.DELIVERY_ZONE_UNSERVICEABLE]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.DELIVERY_FAILED_ATTEMPT]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.DELIVERY_RETURN_INITIATED]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,

    [LOGISTICS_ERROR.CODES.COURIER_NOT_FOUND]: LOGISTICS_ERROR.CATEGORIES.NOT_FOUND,
    [LOGISTICS_ERROR.CODES.COURIER_INVALID_STATUS]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.COURIER_UNSERVICEABLE]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.COURIER_SERVICE_UNAVAILABLE]: LOGISTICS_ERROR.CATEGORIES.EXTERNAL,
    [LOGISTICS_ERROR.CODES.COURIER_INVALID_TYPE]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,

    [LOGISTICS_ERROR.CODES.VEHICLE_NOT_FOUND]: LOGISTICS_ERROR.CATEGORIES.NOT_FOUND,
    [LOGISTICS_ERROR.CODES.VEHICLE_INVALID_STATUS]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.VEHICLE_UNAVAILABLE]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.VEHICLE_MAINTENANCE_REQUIRED]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.VEHICLE_CAPACITY_EXCEEDED]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.VEHICLE_TYPE_INVALID]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,

    [LOGISTICS_ERROR.CODES.DRIVER_NOT_FOUND]: LOGISTICS_ERROR.CATEGORIES.NOT_FOUND,
    [LOGISTICS_ERROR.CODES.DRIVER_INVALID_STATUS]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.DRIVER_UNAVAILABLE]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.DRIVER_LICENSE_INVALID]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.DRIVER_ON_LEAVE]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.DRIVER_MAX_HOURS_EXCEEDED]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,

    [LOGISTICS_ERROR.CODES.WAREHOUSE_NOT_FOUND]: LOGISTICS_ERROR.CATEGORIES.NOT_FOUND,
    [LOGISTICS_ERROR.CODES.WAREHOUSE_INVALID_STATUS]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.WAREHOUSE_FULL]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.WAREHOUSE_MAINTENANCE]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.WAREHOUSE_INVENTORY_LOW]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,

    [LOGISTICS_ERROR.CODES.TRACKING_NOT_FOUND]: LOGISTICS_ERROR.CATEGORIES.NOT_FOUND,
    [LOGISTICS_ERROR.CODES.TRACKING_INVALID_STATUS]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.TRACKING_UPDATE_FAILED]: LOGISTICS_ERROR.CATEGORIES.INTERNAL,
    [LOGISTICS_ERROR.CODES.TRACKING_EVENT_INVALID]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,

    [LOGISTICS_ERROR.CODES.ROUTE_NOT_FOUND]: LOGISTICS_ERROR.CATEGORIES.NOT_FOUND,
    [LOGISTICS_ERROR.CODES.ROUTE_INVALID_STATUS]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.ROUTE_BLOCKED]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.ROUTE_MAINTENANCE]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.ROUTE_WEATHER_DISRUPTION]: LOGISTICS_ERROR.CATEGORIES.EXTERNAL,

    [LOGISTICS_ERROR.CODES.ZONE_NOT_FOUND]: LOGISTICS_ERROR.CATEGORIES.NOT_FOUND,
    [LOGISTICS_ERROR.CODES.ZONE_INVALID_STATUS]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.ZONE_UNSERVICEABLE]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.ZONE_RESTRICTED]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,

    [LOGISTICS_ERROR.CODES.RETURN_NOT_FOUND]: LOGISTICS_ERROR.CATEGORIES.NOT_FOUND,
    [LOGISTICS_ERROR.CODES.RETURN_INVALID_STATUS]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.RETURN_REASON_INVALID]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.RETURN_WINDOW_EXPIRED]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.RETURN_ALREADY_PROCESSED]: LOGISTICS_ERROR.CATEGORIES.CONFLICT,

    [LOGISTICS_ERROR.CODES.INSURANCE_NOT_FOUND]: LOGISTICS_ERROR.CATEGORIES.NOT_FOUND,
    [LOGISTICS_ERROR.CODES.INSURANCE_INVALID_STATUS]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.INSURANCE_CLAIM_FAILED]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.INSURANCE_EXPIRED]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,
    [LOGISTICS_ERROR.CODES.INSURANCE_COVERAGE_INSUFFICIENT]: LOGISTICS_ERROR.CATEGORIES.BUSINESS,

    [LOGISTICS_ERROR.CODES.PERMISSION_DENIED]: LOGISTICS_ERROR.CATEGORIES.AUTHORIZATION,
    [LOGISTICS_ERROR.CODES.PERMISSION_INSUFFICIENT]: LOGISTICS_ERROR.CATEGORIES.AUTHORIZATION,
    [LOGISTICS_ERROR.CODES.PERMISSION_INVALID_ROLE]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.PERMISSION_INVALID_ACTION]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,

    [LOGISTICS_ERROR.CODES.REPORT_NOT_FOUND]: LOGISTICS_ERROR.CATEGORIES.NOT_FOUND,
    [LOGISTICS_ERROR.CODES.REPORT_GENERATION_FAILED]: LOGISTICS_ERROR.CATEGORIES.INTERNAL,
    [LOGISTICS_ERROR.CODES.REPORT_EXPORT_FAILED]: LOGISTICS_ERROR.CATEGORIES.INTERNAL,
    [LOGISTICS_ERROR.CODES.REPORT_INVALID_FORMAT]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.REPORT_TOO_LARGE]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,

    [LOGISTICS_ERROR.CODES.ANALYTICS_NOT_FOUND]: LOGISTICS_ERROR.CATEGORIES.NOT_FOUND,
    [LOGISTICS_ERROR.CODES.ANALYTICS_GENERATION_FAILED]: LOGISTICS_ERROR.CATEGORIES.INTERNAL,
    [LOGISTICS_ERROR.CODES.ANALYTICS_INVALID_METRIC]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
    [LOGISTICS_ERROR.CODES.ANALYTICS_INVALID_PERIOD]: LOGISTICS_ERROR.CATEGORIES.VALIDATION,
  };
  return categories[code] || LOGISTICS_ERROR.CATEGORIES.INTERNAL;
}

export function logisticsErrorGetSeverity(code: LogisticsErrorCode): LogisticsErrorSeverity {
  const severities: Record<LogisticsErrorCode, LogisticsErrorSeverity> = {
    [LOGISTICS_ERROR.CODES.GENERAL_ERROR]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.VALIDATION_ERROR]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.NOT_FOUND]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.UNAUTHORIZED]: LOGISTICS_ERROR.SEVERITIES.HIGH,
    [LOGISTICS_ERROR.CODES.FORBIDDEN]: LOGISTICS_ERROR.SEVERITIES.HIGH,
    [LOGISTICS_ERROR.CODES.BAD_REQUEST]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.INTERNAL_ERROR]: LOGISTICS_ERROR.SEVERITIES.CRITICAL,
    [LOGISTICS_ERROR.CODES.SERVICE_UNAVAILABLE]: LOGISTICS_ERROR.SEVERITIES.CRITICAL,
    [LOGISTICS_ERROR.CODES.TIMEOUT]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.RATE_LIMIT]: LOGISTICS_ERROR.SEVERITIES.LOW,

    [LOGISTICS_ERROR.CODES.SHIPMENT_NOT_FOUND]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_STATUS]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_TYPE]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_PRIORITY]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.SHIPMENT_ALREADY_DELIVERED]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.SHIPMENT_CANNOT_CANCEL]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.SHIPMENT_WEIGHT_EXCEEDED]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.SHIPMENT_VOLUME_EXCEEDED]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_ADDRESS]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.SHIPMENT_TRACKING_FAILED]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,

    [LOGISTICS_ERROR.CODES.DELIVERY_NOT_FOUND]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.DELIVERY_INVALID_STATUS]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.DELIVERY_INVALID_TYPE]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.DELIVERY_ALREADY_DELIVERED]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.DELIVERY_CANNOT_CANCEL]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.DELIVERY_ADDRESS_INVALID]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.DELIVERY_TIME_SLOT_UNAVAILABLE]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.DELIVERY_ZONE_UNSERVICEABLE]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.DELIVERY_FAILED_ATTEMPT]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.DELIVERY_RETURN_INITIATED]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,

    [LOGISTICS_ERROR.CODES.COURIER_NOT_FOUND]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.COURIER_INVALID_STATUS]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.COURIER_UNSERVICEABLE]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.COURIER_SERVICE_UNAVAILABLE]: LOGISTICS_ERROR.SEVERITIES.HIGH,
    [LOGISTICS_ERROR.CODES.COURIER_INVALID_TYPE]: LOGISTICS_ERROR.SEVERITIES.LOW,

    [LOGISTICS_ERROR.CODES.VEHICLE_NOT_FOUND]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.VEHICLE_INVALID_STATUS]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.VEHICLE_UNAVAILABLE]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.VEHICLE_MAINTENANCE_REQUIRED]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.VEHICLE_CAPACITY_EXCEEDED]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.VEHICLE_TYPE_INVALID]: LOGISTICS_ERROR.SEVERITIES.LOW,

    [LOGISTICS_ERROR.CODES.DRIVER_NOT_FOUND]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.DRIVER_INVALID_STATUS]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.DRIVER_UNAVAILABLE]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.DRIVER_LICENSE_INVALID]: LOGISTICS_ERROR.SEVERITIES.HIGH,
    [LOGISTICS_ERROR.CODES.DRIVER_ON_LEAVE]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.DRIVER_MAX_HOURS_EXCEEDED]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,

    [LOGISTICS_ERROR.CODES.WAREHOUSE_NOT_FOUND]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.WAREHOUSE_INVALID_STATUS]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.WAREHOUSE_FULL]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.WAREHOUSE_MAINTENANCE]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.WAREHOUSE_INVENTORY_LOW]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,

    [LOGISTICS_ERROR.CODES.TRACKING_NOT_FOUND]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.TRACKING_INVALID_STATUS]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.TRACKING_UPDATE_FAILED]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.TRACKING_EVENT_INVALID]: LOGISTICS_ERROR.SEVERITIES.LOW,

    [LOGISTICS_ERROR.CODES.ROUTE_NOT_FOUND]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.ROUTE_INVALID_STATUS]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.ROUTE_BLOCKED]: LOGISTICS_ERROR.SEVERITIES.HIGH,
    [LOGISTICS_ERROR.CODES.ROUTE_MAINTENANCE]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.ROUTE_WEATHER_DISRUPTION]: LOGISTICS_ERROR.SEVERITIES.HIGH,

    [LOGISTICS_ERROR.CODES.ZONE_NOT_FOUND]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.ZONE_INVALID_STATUS]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.ZONE_UNSERVICEABLE]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.ZONE_RESTRICTED]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,

    [LOGISTICS_ERROR.CODES.RETURN_NOT_FOUND]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.RETURN_INVALID_STATUS]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.RETURN_REASON_INVALID]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.RETURN_WINDOW_EXPIRED]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.RETURN_ALREADY_PROCESSED]: LOGISTICS_ERROR.SEVERITIES.LOW,

    [LOGISTICS_ERROR.CODES.INSURANCE_NOT_FOUND]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.INSURANCE_INVALID_STATUS]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.INSURANCE_CLAIM_FAILED]: LOGISTICS_ERROR.SEVERITIES.HIGH,
    [LOGISTICS_ERROR.CODES.INSURANCE_EXPIRED]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.INSURANCE_COVERAGE_INSUFFICIENT]: LOGISTICS_ERROR.SEVERITIES.HIGH,

    [LOGISTICS_ERROR.CODES.PERMISSION_DENIED]: LOGISTICS_ERROR.SEVERITIES.HIGH,
    [LOGISTICS_ERROR.CODES.PERMISSION_INSUFFICIENT]: LOGISTICS_ERROR.SEVERITIES.HIGH,
    [LOGISTICS_ERROR.CODES.PERMISSION_INVALID_ROLE]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.PERMISSION_INVALID_ACTION]: LOGISTICS_ERROR.SEVERITIES.LOW,

    [LOGISTICS_ERROR.CODES.REPORT_NOT_FOUND]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.REPORT_GENERATION_FAILED]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.REPORT_EXPORT_FAILED]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.REPORT_INVALID_FORMAT]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.REPORT_TOO_LARGE]: LOGISTICS_ERROR.SEVERITIES.LOW,

    [LOGISTICS_ERROR.CODES.ANALYTICS_NOT_FOUND]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.ANALYTICS_GENERATION_FAILED]: LOGISTICS_ERROR.SEVERITIES.MEDIUM,
    [LOGISTICS_ERROR.CODES.ANALYTICS_INVALID_METRIC]: LOGISTICS_ERROR.SEVERITIES.LOW,
    [LOGISTICS_ERROR.CODES.ANALYTICS_INVALID_PERIOD]: LOGISTICS_ERROR.SEVERITIES.LOW,
  };
  return severities[code] || LOGISTICS_ERROR.SEVERITIES.MEDIUM;
}

export function logisticsErrorIsRetryable(code: LogisticsErrorCode): boolean {
  const retryableCodes: LogisticsErrorCode[] = [
    LOGISTICS_ERROR.CODES.INTERNAL_ERROR,
    LOGISTICS_ERROR.CODES.SERVICE_UNAVAILABLE,
    LOGISTICS_ERROR.CODES.TIMEOUT,
    LOGISTICS_ERROR.CODES.RATE_LIMIT,
    LOGISTICS_ERROR.CODES.SHIPMENT_TRACKING_FAILED,
    LOGISTICS_ERROR.CODES.REPORT_GENERATION_FAILED,
    LOGISTICS_ERROR.CODES.REPORT_EXPORT_FAILED,
    LOGISTICS_ERROR.CODES.ANALYTICS_GENERATION_FAILED,
    LOGISTICS_ERROR.CODES.INSURANCE_CLAIM_FAILED,
  ];
  return retryableCodes.includes(code);
}

export function logisticsErrorGetHttpStatus(code: LogisticsErrorCode): number {
  const httpStatuses: Record<LogisticsErrorCode, number> = {
    [LOGISTICS_ERROR.CODES.GENERAL_ERROR]: 500,
    [LOGISTICS_ERROR.CODES.VALIDATION_ERROR]: 400,
    [LOGISTICS_ERROR.CODES.NOT_FOUND]: 404,
    [LOGISTICS_ERROR.CODES.UNAUTHORIZED]: 401,
    [LOGISTICS_ERROR.CODES.FORBIDDEN]: 403,
    [LOGISTICS_ERROR.CODES.BAD_REQUEST]: 400,
    [LOGISTICS_ERROR.CODES.INTERNAL_ERROR]: 500,
    [LOGISTICS_ERROR.CODES.SERVICE_UNAVAILABLE]: 503,
    [LOGISTICS_ERROR.CODES.TIMEOUT]: 408,
    [LOGISTICS_ERROR.CODES.RATE_LIMIT]: 429,

    [LOGISTICS_ERROR.CODES.SHIPMENT_NOT_FOUND]: 404,
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_STATUS]: 400,
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_TYPE]: 400,
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_PRIORITY]: 400,
    [LOGISTICS_ERROR.CODES.SHIPMENT_ALREADY_DELIVERED]: 409,
    [LOGISTICS_ERROR.CODES.SHIPMENT_CANNOT_CANCEL]: 422,
    [LOGISTICS_ERROR.CODES.SHIPMENT_WEIGHT_EXCEEDED]: 400,
    [LOGISTICS_ERROR.CODES.SHIPMENT_VOLUME_EXCEEDED]: 400,
    [LOGISTICS_ERROR.CODES.SHIPMENT_INVALID_ADDRESS]: 400,
    [LOGISTICS_ERROR.CODES.SHIPMENT_TRACKING_FAILED]: 500,

    [LOGISTICS_ERROR.CODES.DELIVERY_NOT_FOUND]: 404,
    [LOGISTICS_ERROR.CODES.DELIVERY_INVALID_STATUS]: 400,
    [LOGISTICS_ERROR.CODES.DELIVERY_INVALID_TYPE]: 400,
    [LOGISTICS_ERROR.CODES.DELIVERY_ALREADY_DELIVERED]: 409,
    [LOGISTICS_ERROR.CODES.DELIVERY_CANNOT_CANCEL]: 422,
    [LOGISTICS_ERROR.CODES.DELIVERY_ADDRESS_INVALID]: 400,
    [LOGISTICS_ERROR.CODES.DELIVERY_TIME_SLOT_UNAVAILABLE]: 409,
    [LOGISTICS_ERROR.CODES.DELIVERY_ZONE_UNSERVICEABLE]: 400,
    [LOGISTICS_ERROR.CODES.DELIVERY_FAILED_ATTEMPT]: 422,
    [LOGISTICS_ERROR.CODES.DELIVERY_RETURN_INITIATED]: 409,

    [LOGISTICS_ERROR.CODES.COURIER_NOT_FOUND]: 404,
    [LOGISTICS_ERROR.CODES.COURIER_INVALID_STATUS]: 400,
    [LOGISTICS_ERROR.CODES.COURIER_UNSERVICEABLE]: 400,
    [LOGISTICS_ERROR.CODES.COURIER_SERVICE_UNAVAILABLE]: 503,
    [LOGISTICS_ERROR.CODES.COURIER_INVALID_TYPE]: 400,

    [LOGISTICS_ERROR.CODES.VEHICLE_NOT_FOUND]: 404,
    [LOGISTICS_ERROR.CODES.VEHICLE_INVALID_STATUS]: 400,
    [LOGISTICS_ERROR.CODES.VEHICLE_UNAVAILABLE]: 404,
    [LOGISTICS_ERROR.CODES.VEHICLE_MAINTENANCE_REQUIRED]: 503,
    [LOGISTICS_ERROR.CODES.VEHICLE_CAPACITY_EXCEEDED]: 400,
    [LOGISTICS_ERROR.CODES.VEHICLE_TYPE_INVALID]: 400,

    [LOGISTICS_ERROR.CODES.DRIVER_NOT_FOUND]: 404,
    [LOGISTICS_ERROR.CODES.DRIVER_INVALID_STATUS]: 400,
    [LOGISTICS_ERROR.CODES.DRIVER_UNAVAILABLE]: 404,
    [LOGISTICS_ERROR.CODES.DRIVER_LICENSE_INVALID]: 400,
    [LOGISTICS_ERROR.CODES.DRIVER_ON_LEAVE]: 404,
    [LOGISTICS_ERROR.CODES.DRIVER_MAX_HOURS_EXCEEDED]: 400,

    [LOGISTICS_ERROR.CODES.WAREHOUSE_NOT_FOUND]: 404,
    [LOGISTICS_ERROR.CODES.WAREHOUSE_INVALID_STATUS]: 400,
    [LOGISTICS_ERROR.CODES.WAREHOUSE_FULL]: 503,
    [LOGISTICS_ERROR.CODES.WAREHOUSE_MAINTENANCE]: 503,
    [LOGISTICS_ERROR.CODES.WAREHOUSE_INVENTORY_LOW]: 400,

    [LOGISTICS_ERROR.CODES.TRACKING_NOT_FOUND]: 404,
    [LOGISTICS_ERROR.CODES.TRACKING_INVALID_STATUS]: 400,
    [LOGISTICS_ERROR.CODES.TRACKING_UPDATE_FAILED]: 500,
    [LOGISTICS_ERROR.CODES.TRACKING_EVENT_INVALID]: 400,

    [LOGISTICS_ERROR.CODES.ROUTE_NOT_FOUND]: 404,
    [LOGISTICS_ERROR.CODES.ROUTE_INVALID_STATUS]: 400,
    [LOGISTICS_ERROR.CODES.ROUTE_BLOCKED]: 400,
    [LOGISTICS_ERROR.CODES.ROUTE_MAINTENANCE]: 503,
    [LOGISTICS_ERROR.CODES.ROUTE_WEATHER_DISRUPTION]: 503,

    [LOGISTICS_ERROR.CODES.ZONE_NOT_FOUND]: 404,
    [LOGISTICS_ERROR.CODES.ZONE_INVALID_STATUS]: 400,
    [LOGISTICS_ERROR.CODES.ZONE_UNSERVICEABLE]: 400,
    [LOGISTICS_ERROR.CODES.ZONE_RESTRICTED]: 403,

    [LOGISTICS_ERROR.CODES.RETURN_NOT_FOUND]: 404,
    [LOGISTICS_ERROR.CODES.RETURN_INVALID_STATUS]: 400,
    [LOGISTICS_ERROR.CODES.RETURN_REASON_INVALID]: 400,
    [LOGISTICS_ERROR.CODES.RETURN_WINDOW_EXPIRED]: 400,
    [LOGISTICS_ERROR.CODES.RETURN_ALREADY_PROCESSED]: 409,

    [LOGISTICS_ERROR.CODES.INSURANCE_NOT_FOUND]: 404,
    [LOGISTICS_ERROR.CODES.INSURANCE_INVALID_STATUS]: 400,
    [LOGISTICS_ERROR.CODES.INSURANCE_CLAIM_FAILED]: 500,
    [LOGISTICS_ERROR.CODES.INSURANCE_EXPIRED]: 400,
    [LOGISTICS_ERROR.CODES.INSURANCE_COVERAGE_INSUFFICIENT]: 400,

    [LOGISTICS_ERROR.CODES.PERMISSION_DENIED]: 403,
    [LOGISTICS_ERROR.CODES.PERMISSION_INSUFFICIENT]: 403,
    [LOGISTICS_ERROR.CODES.PERMISSION_INVALID_ROLE]: 400,
    [LOGISTICS_ERROR.CODES.PERMISSION_INVALID_ACTION]: 400,

    [LOGISTICS_ERROR.CODES.REPORT_NOT_FOUND]: 404,
    [LOGISTICS_ERROR.CODES.REPORT_GENERATION_FAILED]: 500,
    [LOGISTICS_ERROR.CODES.REPORT_EXPORT_FAILED]: 500,
    [LOGISTICS_ERROR.CODES.REPORT_INVALID_FORMAT]: 400,
    [LOGISTICS_ERROR.CODES.REPORT_TOO_LARGE]: 400,

    [LOGISTICS_ERROR.CODES.ANALYTICS_NOT_FOUND]: 404,
    [LOGISTICS_ERROR.CODES.ANALYTICS_GENERATION_FAILED]: 500,
    [LOGISTICS_ERROR.CODES.ANALYTICS_INVALID_METRIC]: 400,
    [LOGISTICS_ERROR.CODES.ANALYTICS_INVALID_PERIOD]: 400,
  };
  return httpStatuses[code] || 500;
}
