import { SHIPMENT_STATUS, SHIPMENT_TYPE, SHIPMENT_PRIORITY, SHIPMENT } from './shipment.constants.js';
import {
  DELIVERY_STATUS,
  DELIVERY_TYPE,
  DELIVERY_ATTEMPT_STATUS,
  DELIVERY,
} from './delivery.constants.js';
import { COURIER_STATUS, COURIER_TYPE, COURIER_NAME, COURIER } from './courier.constants.js';
import { TRACKING_EVENT, TRACKING_STATUS, TRACKING_SOURCE, TRACKING } from './tracking.constants.js';
import { WAREHOUSE_STATUS, WAREHOUSE_TYPE, WAREHOUSE_ZONE, WAREHOUSE } from './warehouse.constants.js';
import {
  FULFILLMENT_STATUS,
  FULFILLMENT_TYPE,
  FULFILLMENT_PRIORITY,
  FULFILLMENT,
} from './fulfillment.constants.js';
import { DISPATCH_STATUS, DISPATCH_TYPE, DISPATCH } from './dispatch.constants.js';
import { VEHICLE_STATUS, VEHICLE_TYPE, VEHICLE_FUEL_TYPE, VEHICLE } from './vehicle.constants.js';
import { DRIVER_STATUS, DRIVER_TYPE, DRIVER_LICENSE_TYPE, DRIVER } from './driver.constants.js';
import { ROUTE_STATUS, ROUTE_TYPE, ROUTE_OPTIMIZATION, ROUTE } from './route.constants.js';
import { ZONE_STATUS, ZONE_TYPE, ZONE_PRICING_TYPE, ZONE } from './zone.constants.js';
import {
  SHIPPING_METHOD,
  SHIPPING_METHOD_STATUS,
  SHIPPING_RATE_TYPE,
  SHIPPING_METHOD_LIMIT,
} from './shipping-method.constants.js';
import {
  PACKAGING_TYPE,
  PACKAGING_MATERIAL,
  PACKAGING_STATUS,
  PACKAGING,
} from './packaging.constants.js';
import {
  RETURN_SHIPMENT_STATUS,
  RETURN_SHIPMENT_TYPE,
  RETURN_SHIPMENT_REASON,
  RETURN_SHIPMENT,
} from './return-shipment.constants.js';
import {
  INSURANCE_STATUS,
  INSURANCE_TYPE,
  INSURANCE_COVERAGE,
  INSURANCE_CLAIM_STATUS,
  INSURANCE,
} from './insurance.constants.js';
import {
  LOGISTICS_ANALYTICS_METRIC,
  LOGISTICS_ANALYTICS_PERIOD,
  LOGISTICS_ANALYTICS,
} from './logistics-analytics.constants.js';
import { LOGISTICS_PERMISSION } from './logistics-permission.constants.js';

export const LOGISTICS_LIMIT = {
  MAX_SHIPMENTS_PER_DAY: 100000,
  MAX_ACTIVE_SHIPMENTS: 1000000,
  MAX_WAREHOUSES: 100,
  MAX_COURIERS: 50,
  MAX_VEHICLES: 5000,
  MAX_DRIVERS: 10000,
  MAX_ROUTES: 5000,
  MAX_ZONES: 5000,
  MAX_DELIVERY_ATTEMPTS: 3,
  MAX_WEIGHT_KG: 500,
  MAX_DIMENSION_CM: 300,
  MAX_DECLARED_VALUE: 10000000,
  RETENTION_DAYS: 730,
} as const;

export const LOGISTICS = {
  LIMIT: LOGISTICS_LIMIT,

  SHIPMENT: {
    STATUS: SHIPMENT_STATUS,
    TYPE: SHIPMENT_TYPE,
    PRIORITY: SHIPMENT_PRIORITY,
    LIMIT: SHIPMENT,
  },

  DELIVERY: {
    STATUS: DELIVERY_STATUS,
    TYPE: DELIVERY_TYPE,
    ATTEMPT_STATUS: DELIVERY_ATTEMPT_STATUS,
    LIMIT: DELIVERY,
  },

  COURIER: {
    STATUS: COURIER_STATUS,
    TYPE: COURIER_TYPE,
    NAME: COURIER_NAME,
    LIMIT: COURIER,
  },

  TRACKING: {
    EVENT: TRACKING_EVENT,
    STATUS: TRACKING_STATUS,
    SOURCE: TRACKING_SOURCE,
    LIMIT: TRACKING,
  },

  WAREHOUSE: {
    STATUS: WAREHOUSE_STATUS,
    TYPE: WAREHOUSE_TYPE,
    ZONE: WAREHOUSE_ZONE,
    LIMIT: WAREHOUSE,
  },

  FULFILLMENT: {
    STATUS: FULFILLMENT_STATUS,
    TYPE: FULFILLMENT_TYPE,
    PRIORITY: FULFILLMENT_PRIORITY,
    LIMIT: FULFILLMENT,
  },

  DISPATCH: {
    STATUS: DISPATCH_STATUS,
    TYPE: DISPATCH_TYPE,
    LIMIT: DISPATCH,
  },

  VEHICLE: {
    STATUS: VEHICLE_STATUS,
    TYPE: VEHICLE_TYPE,
    FUEL_TYPE: VEHICLE_FUEL_TYPE,
    LIMIT: VEHICLE,
  },

  DRIVER: {
    STATUS: DRIVER_STATUS,
    TYPE: DRIVER_TYPE,
    LICENSE_TYPE: DRIVER_LICENSE_TYPE,
    LIMIT: DRIVER,
  },

  ROUTE: {
    STATUS: ROUTE_STATUS,
    TYPE: ROUTE_TYPE,
    OPTIMIZATION: ROUTE_OPTIMIZATION,
    LIMIT: ROUTE,
  },

  ZONE: {
    STATUS: ZONE_STATUS,
    TYPE: ZONE_TYPE,
    PRICING_TYPE: ZONE_PRICING_TYPE,
    LIMIT: ZONE,
  },

  SHIPPING_METHOD: {
    TYPE: SHIPPING_METHOD,
    STATUS: SHIPPING_METHOD_STATUS,
    RATE_TYPE: SHIPPING_RATE_TYPE,
    LIMIT: SHIPPING_METHOD_LIMIT,
  },

  PACKAGING: {
    TYPE: PACKAGING_TYPE,
    MATERIAL: PACKAGING_MATERIAL,
    STATUS: PACKAGING_STATUS,
    LIMIT: PACKAGING,
  },

  RETURN_SHIPMENT: {
    STATUS: RETURN_SHIPMENT_STATUS,
    TYPE: RETURN_SHIPMENT_TYPE,
    REASON: RETURN_SHIPMENT_REASON,
    LIMIT: RETURN_SHIPMENT,
  },

  INSURANCE: {
    STATUS: INSURANCE_STATUS,
    TYPE: INSURANCE_TYPE,
    COVERAGE: INSURANCE_COVERAGE,
    CLAIM_STATUS: INSURANCE_CLAIM_STATUS,
    LIMIT: INSURANCE,
  },

  ANALYTICS: {
    METRIC: LOGISTICS_ANALYTICS_METRIC,
    PERIOD: LOGISTICS_ANALYTICS_PERIOD,
    LIMIT: LOGISTICS_ANALYTICS,
  },

  PERMISSION: LOGISTICS_PERMISSION,
} as const;

export type LogisticsType = typeof LOGISTICS;
