// External libraries
// No external libraries needed

// Shared packages
// No shared packages needed

// Project files
export {
  AUTH_APP_NAME,
  AUTH_DEFAULT_TIMEOUT,
  AUTH_SUPPORTED_LANGUAGES,
  AUTH_DEFAULT_LANGUAGE,
  AUTH_DATE_FORMAT,
  AUTH_TIMEZONE,
  type AuthSupportedLanguage,
} from './auth.constants';

export {
  AUTH_STATUS,
  ACTIVE,
  INACTIVE,
  BLOCKED,
  PENDING,
  EXPIRED,
  SUSPENDED,
  type AuthStatus,
} from './auth-status.constants';

export {
  AUTH_TYPE,
  BASIC,
  SOCIAL,
  SSO,
  OAUTH,
  JWT,
  API_KEY,
  type AuthType,
} from './auth-type.constants';

export {
  AUTH_PROVIDER,
  GOOGLE,
  FACEBOOK,
  GITHUB,
  APPLE,
  MICROSOFT,
  TWITTER,
  type AuthProvider,
} from './auth-provider.constants';

export {
  AUTH_METHOD,
  PASSWORD,
  OTP,
  MAGIC_LINK,
  BIOMETRIC,
  TOTP,
  SMS,
  EMAIL,
  type AuthMethod,
} from './auth-method.constants';

export {
  AUTH_ERROR_CODE,
  INVALID_CREDENTIALS,
  ACCOUNT_LOCKED,
  ACCOUNT_NOT_VERIFIED,
  TOKEN_EXPIRED,
  INVALID_TOKEN,
  MFA_REQUIRED,
  INVALID_MFA,
  SESSION_EXPIRED,
  RATE_LIMIT_EXCEEDED,
  AUTH_ERROR_MESSAGE,
  type AuthErrorCode,
  type AuthErrorMessage,
} from './auth-error.constants';

export {
  AUTH_PERMISSION,
  READ_USERS,
  WRITE_USERS,
  DELETE_USERS,
  MANAGE_ROLES,
  MANAGE_PERMISSIONS,
  MANAGE_SETTINGS,
  type AuthPermission,
} from './auth-permission.constants';

export {
  AUTH_ROLE,
  SUPER_ADMIN,
  ADMIN,
  SELLER,
  CUSTOMER,
  GUEST,
  MODERATOR,
  type AuthRole,
} from './auth-role.constants';

export {
  SESSION_MAX_AGE,
  SESSION_REFRESH_THRESHOLD,
  SESSION_COOKIE_NAME,
  SESSION_MAX_DEVICES,
  SESSION_SAME_SITE,
  SESSION_SECURE,
  SESSION_COOKIE_OPTIONS,
  type SessionSameSite,
  type SessionCookieOptions,
} from './auth-session.constants';

export {
  TOKEN_TYPE,
  ACCESS,
  REFRESH,
  VERIFICATION,
  PASSWORD_RESET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
  VERIFICATION_TOKEN_EXPIRY,
  PASSWORD_RESET_TOKEN_EXPIRY,
  TOKEN_EXPIRY,
  type TokenType,
  type TokenExpiry,
} from './auth-token.constants';

export {
  VERIFICATION_TYPE,
  EMAIL_VERIFICATION,
  PHONE_VERIFICATION,
  VERIFICATION_CODE_LENGTH,
  VERIFICATION_CODE_EXPIRY,
  VERIFICATION_MAX_ATTEMPTS,
  VERIFICATION_CONFIG,
  type VerificationType,
  type VerificationConfig,
} from './auth-verification.constants';

export {
  PASSWORD_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
  PASSWORD_REQUIRE_UPPERCASE,
  PASSWORD_REQUIRE_LOWERCASE,
  PASSWORD_REQUIRE_NUMBER,
  PASSWORD_REQUIRE_SPECIAL,
  PASSWORD_BCRYPT_ROUNDS,
  PASSWORD_POLICY,
  PASSWORD_VALIDATION_MESSAGES,
  type PasswordPolicy,
  type PasswordValidationMessages,
} from './auth-password.constants';

export {
  MFA_ENABLED_DEFAULT,
  MFA_MAX_ATTEMPTS,
  MFA_RETRY_DELAY,
  MFA_CODE_LENGTH,
  MFA_CODE_EXPIRY,
  MFA_BACKUP_CODES_COUNT,
  MFA_BACKUP_CODES_LENGTH,
  MFA_SESSION_TIMEOUT,
  MFA_ALLOWED_TYPES,
  MFA_DEFAULT_TYPE,
  MFA_CONFIG,
  type MfaConfig,
  type MfaAllowedType,
} from './auth-mfa.constants';

export {
  MFA_TYPE,
  MFA_TOTP,
  MFA_SMS,
  MFA_EMAIL,
  MFA_AUTHENTICATOR,
  MFA_HARDWARE_TOKEN,
  MFA_PUSH_NOTIFICATION,
  MFA_RECOVERY_CODE,
  type MfaType,
} from './auth-mfa-type.constants';

export {
  MFA_STATUS,
  MFA_STATUS_ENABLED,
  MFA_STATUS_DISABLED,
  MFA_STATUS_PENDING,
  MFA_STATUS_VERIFIED,
  MFA_STATUS_EXPIRED,
  MFA_STATUS_LOCKED,
  MFA_STATUS_REQUIRED,
  type MfaStatus,
} from './auth-mfa-status.constants';

export {
  RECOVERY_CODE_LENGTH,
  RECOVERY_CODE_COUNT,
  RECOVERY_CODE_EXPIRY,
  RECOVERY_CODE_FORMAT,
  RECOVERY_MAX_USAGE,
  RECOVERY_CODE_CHARSET,
  RECOVERY_SESSION_TIMEOUT,
  RECOVERY_CONFIG,
  type RecoveryCodeFormat,
  type RecoveryConfig,
} from './auth-recovery-code.constants';

export {
  RECOVERY_CODE_STATUS,
  RECOVERY_CODE_ACTIVE,
  RECOVERY_CODE_USED,
  RECOVERY_CODE_EXPIRED,
  RECOVERY_CODE_REVOKED,
  RECOVERY_CODE_PENDING,
  type RecoveryCodeStatus,
} from './auth-recovery-code-status.constants';

export {
  ACCOUNT_LOCK_MAX_ATTEMPTS,
  ACCOUNT_LOCK_DURATION,
  ACCOUNT_LOCK_RESET_TIME,
  ACCOUNT_LOCK_PERMANENT_THRESHOLD,
  ACCOUNT_LOCK_NOTIFICATION,
  ACCOUNT_LOCK_REASON,
  ACCOUNT_LOCK_REASON_TOO_MANY_ATTEMPTS,
  ACCOUNT_LOCK_REASON_SUSPICIOUS_ACTIVITY,
  ACCOUNT_LOCK_REASON_ADMIN_ACTION,
  ACCOUNT_LOCK_REASON_SECURITY_POLICY,
  ACCOUNT_LOCK_REASON_PERMANENT_LOCK,
  ACCOUNT_LOCK_CONFIG,
  type AccountLockReason,
  type AccountLockConfig,
} from './auth-account-lock.constants';

export {
  ACCOUNT_LOCK_STATUS,
  ACCOUNT_LOCK_STATUS_LOCKED,
  ACCOUNT_LOCK_STATUS_UNLOCKED,
  ACCOUNT_LOCK_STATUS_PERMANENTLY_LOCKED,
  ACCOUNT_LOCK_STATUS_PENDING_UNLOCK,
  ACCOUNT_LOCK_STATUS_SUSPENDED,
  type AccountLockStatus,
} from './auth-account-lock-status.constants';

export {
  LOGIN_ATTEMPT_MAX_FAILED,
  LOGIN_ATTEMPT_WINDOW,
  LOGIN_ATTEMPT_MAX_HISTORY,
  LOGIN_ATTEMPT_BLOCK_DURATION,
  LOGIN_ATTEMPT_SUSPICIOUS_THRESHOLD,
  LOGIN_ATTEMPT_CONFIG,
  type LoginAttemptConfig,
} from './auth-login-attempt.constants';

export {
  LOGIN_ATTEMPT_STATUS,
  LOGIN_ATTEMPT_STATUS_SUCCESS,
  LOGIN_ATTEMPT_STATUS_FAILED,
  LOGIN_ATTEMPT_STATUS_BLOCKED,
  LOGIN_ATTEMPT_STATUS_SUSPICIOUS,
  LOGIN_ATTEMPT_STATUS_TIMEOUT,
  LOGIN_ATTEMPT_STATUS_CANCELLED,
  type LoginAttemptStatus,
} from './auth-login-attempt-status.constants';

export {
  DEVICE_FINGERPRINT_SALT,
  DEVICE_MAX_PER_USER,
  DEVICE_SESSION_TIMEOUT,
  DEVICE_TRUST_DURATION,
  DEVICE_FINGERPRINT_COMPONENTS,
  DEVICE_UNKNOWN_ALLOWED,
  DEVICE_NOTIFICATION_ON_NEW,
  DEVICE_CONFIG,
  type DeviceFingerprintComponent,
  type DeviceConfig,
} from './auth-device.constants';

export {
  DEVICE_TYPE,
  DEVICE_TYPE_DESKTOP,
  DEVICE_TYPE_LAPTOP,
  DEVICE_TYPE_MOBILE,
  DEVICE_TYPE_TABLET,
  DEVICE_TYPE_TV,
  DEVICE_TYPE_WEARABLE,
  DEVICE_TYPE_UNKNOWN,
  type DeviceType,
} from './auth-device-type.constants';

export {
  DEVICE_STATUS,
  DEVICE_STATUS_ACTIVE,
  DEVICE_STATUS_INACTIVE,
  DEVICE_STATUS_BLOCKED,
  DEVICE_STATUS_SUSPENDED,
  DEVICE_STATUS_TRUSTED,
  DEVICE_STATUS_PENDING,
  type DeviceStatus,
} from './auth-device-status.constants';

export {
  SOCIAL_ENABLED_PROVIDERS,
  SOCIAL_DEFAULT_PROVIDER,
  SOCIAL_CALLBACK_TIMEOUT,
  SOCIAL_STATE_EXPIRY,
  SOCIAL_SCOPES,
  SOCIAL_CONFIG,
  type SocialProvider,
  type SocialScopes,
  type SocialConfig,
} from './auth-social.constants';

export {
  SOCIAL_PROVIDER,
  SOCIAL_PROVIDER_GOOGLE,
  SOCIAL_PROVIDER_FACEBOOK,
  SOCIAL_PROVIDER_GITHUB,
  SOCIAL_PROVIDER_APPLE,
  SOCIAL_PROVIDER_MICROSOFT,
  SOCIAL_PROVIDER_TWITTER,
  SOCIAL_PROVIDER_LINKEDIN,
  SOCIAL_PROVIDER_INSTAGRAM,
  type SocialProviderEnum,
} from './auth-social-provider.constants';

export {
  SOCIAL_STATUS,
  SOCIAL_STATUS_CONNECTED,
  SOCIAL_STATUS_DISCONNECTED,
  SOCIAL_STATUS_PENDING,
  SOCIAL_STATUS_FAILED,
  SOCIAL_STATUS_EXPIRED,
  type SocialStatus,
} from './auth-social-status.constants';

export {
  OAUTH_DEFAULT_PROVIDER,
  OAUTH_GRANT_TYPES,
  OAUTH_TOKEN_EXPIRY,
  OAUTH_REFRESH_TOKEN_EXPIRY,
  OAUTH_SCOPES,
  OAUTH_CONFIG,
  type OAuthGrantType,
  type OAuthScope,
  type OAuthConfig,
} from './auth-oauth.constants';

export {
  OAUTH_PROVIDER,
  OAUTH_PROVIDER_GOOGLE,
  OAUTH_PROVIDER_FACEBOOK,
  OAUTH_PROVIDER_GITHUB,
  OAUTH_PROVIDER_MICROSOFT,
  OAUTH_PROVIDER_TWITTER,
  OAUTH_PROVIDER_LINKEDIN,
  type OAuthProviderEnum,
} from './auth-oauth-provider.constants';

export {
  OAUTH_STATUS,
  OAUTH_STATUS_ACTIVE,
  OAUTH_STATUS_EXPIRED,
  OAUTH_STATUS_REVOKED,
  OAUTH_STATUS_PENDING,
  OAUTH_STATUS_FAILED,
  OAUTH_STATUS_REFRESHED,
  type OAuthStatus,
} from './auth-oauth-status.constants';

export {
  SSO_ENABLED_PROVIDERS,
  SSO_SESSION_TIMEOUT,
  SSO_TOKEN_EXPIRY,
  SSO_DEFAULT_PROVIDER,
  SSO_CONFIG,
  type SsoProvider,
  type SsoConfig,
} from './auth-sso.constants';

export {
  SSO_PROVIDER,
  SSO_PROVIDER_GOOGLE,
  SSO_PROVIDER_MICROSOFT,
  SSO_PROVIDER_OKTA,
  SSO_PROVIDER_AUTH0,
  SSO_PROVIDER_KEYCLOAK,
  SSO_PROVIDER_PING,
  SSO_PROVIDER_FORGEOK,
  SSO_PROVIDER_SAML,
  type SsoProviderEnum,
} from './auth-sso-provider.constants';

export {
  SSO_STATUS,
  SSO_STATUS_ACTIVE,
  SSO_STATUS_EXPIRED,
  SSO_STATUS_REVOKED,
  SSO_STATUS_PENDING,
  SSO_STATUS_FAILED,
  SSO_STATUS_LOGGED_OUT,
  type SsoStatus,
} from './auth-sso-status.constants';

export {
  TWO_FA_ENABLED_DEFAULT,
  TWO_FA_CODE_LENGTH,
  TWO_FA_CODE_EXPIRY,
  TWO_FA_MAX_ATTEMPTS,
  TWO_FA_RETRY_DELAY,
  TWO_FA_CONFIG,
  type TwoFaConfig,
} from './auth-2fa.constants';

export {
  TWO_FA_TYPE,
  TWO_FA_TYPE_TOTP,
  TWO_FA_TYPE_SMS,
  TWO_FA_TYPE_EMAIL,
  TWO_FA_TYPE_AUTHENTICATOR,
  TWO_FA_TYPE_HARDWARE_TOKEN,
  TWO_FA_TYPE_PUSH_NOTIFICATION,
  TWO_FA_TYPE_BACKUP_CODE,
  type TwoFaType,
} from './auth-2fa-type.constants';

export {
  TWO_FA_STATUS,
  TWO_FA_STATUS_ENABLED,
  TWO_FA_STATUS_DISABLED,
  TWO_FA_STATUS_PENDING,
  TWO_FA_STATUS_VERIFIED,
  TWO_FA_STATUS_EXPIRED,
  TWO_FA_STATUS_LOCKED,
  TWO_FA_STATUS_REQUIRED,
  TWO_FA_STATUS_SETUP,
  type TwoFaStatus,
} from './auth-2fa-status.constants';

export {
  BIOMETRIC_ENABLED_DEFAULT,
  BIOMETRIC_ALLOWED_TYPES,
  BIOMETRIC_SESSION_TIMEOUT,
  BIOMETRIC_MAX_ATTEMPTS,
  BIOMETRIC_CONFIDENCE_THRESHOLD,
  BIOMETRIC_CONFIG,
  type BiometricType,
  type BiometricConfig,
} from './auth-biometric.constants';

export {
  BIOMETRIC_TYPE,
  BIOMETRIC_TYPE_FINGERPRINT,
  BIOMETRIC_TYPE_FACIAL,
  BIOMETRIC_TYPE_IRIS,
  BIOMETRIC_TYPE_VOICE,
  BIOMETRIC_TYPE_HAND_GEOMETRY,
  BIOMETRIC_TYPE_RETINA,
  BIOMETRIC_TYPE_PALM,
  BIOMETRIC_TYPE_EAR,
  type BiometricTypeEnum,
} from './auth-biometric-type.constants';

export {
  BIOMETRIC_STATUS,
  BIOMETRIC_STATUS_ENABLED,
  BIOMETRIC_STATUS_DISABLED,
  BIOMETRIC_STATUS_PENDING,
  BIOMETRIC_STATUS_VERIFIED,
  BIOMETRIC_STATUS_FAILED,
  BIOMETRIC_STATUS_LOCKED,
  BIOMETRIC_STATUS_NOT_AVAILABLE,
  BIOMETRIC_STATUS_SETUP,
  type BiometricStatus,
} from './auth-biometric-status.constants';
