/**
 * Lead Generation Status Constants
 * Status definitions for lead generation lifecycle
 */

export const MARKETINGLEAD_STATUS = {
  // Lead Generation Statuses
  STATUSES: {
    PENDING: 'pending',
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
    FAILED: 'failed',
    PAUSED: 'paused',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    OPTIMIZING: 'optimizing',
    OPTIMIZED: 'optimized',
    SCALING: 'scaling',
    SCALED: 'scaled',
    REVIEWING: 'reviewing',
    APPROVED: 'approved',
    REJECTED: 'rejected',
    SCHEDULED: 'scheduled',
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    DRAFT: 'draft',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    PENDING: '#F59E0B',
    IN_PROGRESS: '#3B82F6',
    COMPLETED: '#10B981',
    FAILED: '#EF4444',
    PAUSED: '#F59E0B',
    CANCELLED: '#6B7280',
    ARCHIVED: '#6B7280',
    OPTIMIZING: '#8B5CF6',
    OPTIMIZED: '#10B981',
    SCALING: '#3B82F6',
    SCALED: '#10B981',
    REVIEWING: '#F59E0B',
    APPROVED: '#10B981',
    REJECTED: '#EF4444',
    SCHEDULED: '#3B82F6',
    ACTIVE: '#10B981',
    INACTIVE: '#6B7280',
    DRAFT: '#6B7280',
  } as const,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    ACTIVE: 'active',
    COMPLETED: 'completed',
    FAILED: 'failed',
    PAUSED: 'paused',
    ARCHIVED: 'archived',
    DRAFT: 'draft',
  } as const,

  // Status Priority Order
  ORDER: {
    DRAFT: 0,
    PENDING: 1,
    SCHEDULED: 2,
    REVIEWING: 3,
    APPROVED: 4,
    REJECTED: 5,
    IN_PROGRESS: 6,
    ACTIVE: 7,
    OPTIMIZING: 8,
    OPTIMIZED: 9,
    SCALING: 10,
    SCALED: 11,
    PAUSED: 12,
    COMPLETED: 13,
    FAILED: 14,
    CANCELLED: 15,
    INACTIVE: 16,
    ARCHIVED: 17,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    DRAFT_TO_PENDING: 'draft_to_pending',
    DRAFT_TO_CANCELLED: 'draft_to_cancelled',
    PENDING_TO_REVIEWING: 'pending_to_reviewing',
    PENDING_TO_CANCELLED: 'pending_to_cancelled',
    REVIEWING_TO_APPROVED: 'reviewing_to_approved',
    REVIEWING_TO_REJECTED: 'reviewing_to_rejected',
    REVIEWING_TO_CANCELLED: 'reviewing_to_cancelled',
    APPROVED_TO_SCHEDULED: 'approved_to_scheduled',
    APPROVED_TO_IN_PROGRESS: 'approved_to_in_progress',
    APPROVED_TO_CANCELLED: 'approved_to_cancelled',
    REJECTED_TO_DRAFT: 'rejected_to_draft',
    REJECTED_TO_ARCHIVED: 'rejected_to_archived',
    SCHEDULED_TO_IN_PROGRESS: 'scheduled_to_in_progress',
    SCHEDULED_TO_CANCELLED: 'scheduled_to_cancelled',
    IN_PROGRESS_TO_ACTIVE: 'in_progress_to_active',
    IN_PROGRESS_TO_PAUSED: 'in_progress_to_paused',
    IN_PROGRESS_TO_FAILED: 'in_progress_to_failed',
    IN_PROGRESS_TO_CANCELLED: 'in_progress_to_cancelled',
    ACTIVE_TO_OPTIMIZING: 'active_to_optimizing',
    ACTIVE_TO_SCALING: 'active_to_scaling',
    ACTIVE_TO_PAUSED: 'active_to_paused',
    ACTIVE_TO_COMPLETED: 'active_to_completed',
    ACTIVE_TO_FAILED: 'active_to_failed',
    ACTIVE_TO_CANCELLED: 'active_to_cancelled',
    PAUSED_TO_IN_PROGRESS: 'paused_to_in_progress',
    PAUSED_TO_ACTIVE: 'paused_to_active',
    PAUSED_TO_CANCELLED: 'paused_to_cancelled',
    OPTIMIZING_TO_OPTIMIZED: 'optimizing_to_optimized',
    OPTIMIZING_TO_PAUSED: 'optimizing_to_paused',
    OPTIMIZING_TO_FAILED: 'optimizing_to_failed',
    OPTIMIZED_TO_ACTIVE: 'optimized_to_active',
    OPTIMIZED_TO_SCALING: 'optimized_to_scaling',
    SCALING_TO_SCALED: 'scaling_to_scaled',
    SCALING_TO_FAILED: 'scaling_to_failed',
    SCALED_TO_ACTIVE: 'scaled_to_active',
    COMPLETED_TO_ARCHIVED: 'completed_to_archived',
    FAILED_TO_DRAFT: 'failed_to_draft',
    FAILED_TO_ARCHIVED: 'failed_to_archived',
    CANCELLED_TO_ARCHIVED: 'cancelled_to_archived',
    INACTIVE_TO_ACTIVE: 'inactive_to_active',
    INACTIVE_TO_ARCHIVED: 'inactive_to_archived',
  } as const,
} as const;

// Lead Generation Statuses
export type MarketingLeadStatusType =
  (typeof MARKETINGLEAD_STATUS.STATUSES)[keyof typeof MARKETINGLEAD_STATUS.STATUSES];

// Status Colors
export type MarketingLeadStatusColor =
  (typeof MARKETINGLEAD_STATUS.COLORS)[keyof typeof MARKETINGLEAD_STATUS.COLORS];

// Status Categories
export type MarketingLeadStatusCategory =
  (typeof MARKETINGLEAD_STATUS.CATEGORIES)[keyof typeof MARKETINGLEAD_STATUS.CATEGORIES];

// Status Priority Order
export type MarketingLeadStatusOrder =
  (typeof MARKETINGLEAD_STATUS.ORDER)[keyof typeof MARKETINGLEAD_STATUS.ORDER];

// Status Transitions
export type MarketingLeadStatusTransition =
  (typeof MARKETINGLEAD_STATUS.TRANSITIONS)[keyof typeof MARKETINGLEAD_STATUS.TRANSITIONS];

// Utility Functions
export function marketingleadGetStatusLabel(status: MarketingLeadStatusType): string {
  const labels: Record<MarketingLeadStatusType, string> = {
    [MARKETINGLEAD_STATUS.STATUSES.PENDING]: 'Pending',
    [MARKETINGLEAD_STATUS.STATUSES.IN_PROGRESS]: 'In Progress',
    [MARKETINGLEAD_STATUS.STATUSES.COMPLETED]: 'Completed',
    [MARKETINGLEAD_STATUS.STATUSES.FAILED]: 'Failed',
    [MARKETINGLEAD_STATUS.STATUSES.PAUSED]: 'Paused',
    [MARKETINGLEAD_STATUS.STATUSES.CANCELLED]: 'Cancelled',
    [MARKETINGLEAD_STATUS.STATUSES.ARCHIVED]: 'Archived',
    [MARKETINGLEAD_STATUS.STATUSES.OPTIMIZING]: 'Optimizing',
    [MARKETINGLEAD_STATUS.STATUSES.OPTIMIZED]: 'Optimized',
    [MARKETINGLEAD_STATUS.STATUSES.SCALING]: 'Scaling',
    [MARKETINGLEAD_STATUS.STATUSES.SCALED]: 'Scaled',
    [MARKETINGLEAD_STATUS.STATUSES.REVIEWING]: 'Reviewing',
    [MARKETINGLEAD_STATUS.STATUSES.APPROVED]: 'Approved',
    [MARKETINGLEAD_STATUS.STATUSES.REJECTED]: 'Rejected',
    [MARKETINGLEAD_STATUS.STATUSES.SCHEDULED]: 'Scheduled',
    [MARKETINGLEAD_STATUS.STATUSES.ACTIVE]: 'Active',
    [MARKETINGLEAD_STATUS.STATUSES.INACTIVE]: 'Inactive',
    [MARKETINGLEAD_STATUS.STATUSES.DRAFT]: 'Draft',
  };
  return labels[status] || 'Unknown Status';
}

export function marketingleadGetStatusColor(
  status: MarketingLeadStatusType
): MarketingLeadStatusColor {
  const colors: Record<MarketingLeadStatusType, MarketingLeadStatusColor> = {
    [MARKETINGLEAD_STATUS.STATUSES.PENDING]: MARKETINGLEAD_STATUS.COLORS.PENDING,
    [MARKETINGLEAD_STATUS.STATUSES.IN_PROGRESS]: MARKETINGLEAD_STATUS.COLORS.IN_PROGRESS,
    [MARKETINGLEAD_STATUS.STATUSES.COMPLETED]: MARKETINGLEAD_STATUS.COLORS.COMPLETED,
    [MARKETINGLEAD_STATUS.STATUSES.FAILED]: MARKETINGLEAD_STATUS.COLORS.FAILED,
    [MARKETINGLEAD_STATUS.STATUSES.PAUSED]: MARKETINGLEAD_STATUS.COLORS.PAUSED,
    [MARKETINGLEAD_STATUS.STATUSES.CANCELLED]: MARKETINGLEAD_STATUS.COLORS.CANCELLED,
    [MARKETINGLEAD_STATUS.STATUSES.ARCHIVED]: MARKETINGLEAD_STATUS.COLORS.ARCHIVED,
    [MARKETINGLEAD_STATUS.STATUSES.OPTIMIZING]: MARKETINGLEAD_STATUS.COLORS.OPTIMIZING,
    [MARKETINGLEAD_STATUS.STATUSES.OPTIMIZED]: MARKETINGLEAD_STATUS.COLORS.OPTIMIZED,
    [MARKETINGLEAD_STATUS.STATUSES.SCALING]: MARKETINGLEAD_STATUS.COLORS.SCALING,
    [MARKETINGLEAD_STATUS.STATUSES.SCALED]: MARKETINGLEAD_STATUS.COLORS.SCALED,
    [MARKETINGLEAD_STATUS.STATUSES.REVIEWING]: MARKETINGLEAD_STATUS.COLORS.REVIEWING,
    [MARKETINGLEAD_STATUS.STATUSES.APPROVED]: MARKETINGLEAD_STATUS.COLORS.APPROVED,
    [MARKETINGLEAD_STATUS.STATUSES.REJECTED]: MARKETINGLEAD_STATUS.COLORS.REJECTED,
    [MARKETINGLEAD_STATUS.STATUSES.SCHEDULED]: MARKETINGLEAD_STATUS.COLORS.SCHEDULED,
    [MARKETINGLEAD_STATUS.STATUSES.ACTIVE]: MARKETINGLEAD_STATUS.COLORS.ACTIVE,
    [MARKETINGLEAD_STATUS.STATUSES.INACTIVE]: MARKETINGLEAD_STATUS.COLORS.INACTIVE,
    [MARKETINGLEAD_STATUS.STATUSES.DRAFT]: MARKETINGLEAD_STATUS.COLORS.DRAFT,
  };
  return colors[status] || MARKETINGLEAD_STATUS.COLORS.PENDING;
}

export function marketingleadGetStatusCategory(
  status: MarketingLeadStatusType
): MarketingLeadStatusCategory {
  const categories: Record<MarketingLeadStatusType, MarketingLeadStatusCategory> = {
    [MARKETINGLEAD_STATUS.STATUSES.DRAFT]: MARKETINGLEAD_STATUS.CATEGORIES.DRAFT,
    [MARKETINGLEAD_STATUS.STATUSES.PENDING]: MARKETINGLEAD_STATUS.CATEGORIES.PENDING,
    [MARKETINGLEAD_STATUS.STATUSES.SCHEDULED]: MARKETINGLEAD_STATUS.CATEGORIES.PENDING,
    [MARKETINGLEAD_STATUS.STATUSES.REVIEWING]: MARKETINGLEAD_STATUS.CATEGORIES.PENDING,
    [MARKETINGLEAD_STATUS.STATUSES.APPROVED]: MARKETINGLEAD_STATUS.CATEGORIES.PENDING,
    [MARKETINGLEAD_STATUS.STATUSES.IN_PROGRESS]: MARKETINGLEAD_STATUS.CATEGORIES.ACTIVE,
    [MARKETINGLEAD_STATUS.STATUSES.ACTIVE]: MARKETINGLEAD_STATUS.CATEGORIES.ACTIVE,
    [MARKETINGLEAD_STATUS.STATUSES.OPTIMIZING]: MARKETINGLEAD_STATUS.CATEGORIES.ACTIVE,
    [MARKETINGLEAD_STATUS.STATUSES.OPTIMIZED]: MARKETINGLEAD_STATUS.CATEGORIES.ACTIVE,
    [MARKETINGLEAD_STATUS.STATUSES.SCALING]: MARKETINGLEAD_STATUS.CATEGORIES.ACTIVE,
    [MARKETINGLEAD_STATUS.STATUSES.SCALED]: MARKETINGLEAD_STATUS.CATEGORIES.ACTIVE,
    [MARKETINGLEAD_STATUS.STATUSES.PAUSED]: MARKETINGLEAD_STATUS.CATEGORIES.PAUSED,
    [MARKETINGLEAD_STATUS.STATUSES.COMPLETED]: MARKETINGLEAD_STATUS.CATEGORIES.COMPLETED,
    [MARKETINGLEAD_STATUS.STATUSES.FAILED]: MARKETINGLEAD_STATUS.CATEGORIES.FAILED,
    [MARKETINGLEAD_STATUS.STATUSES.CANCELLED]: MARKETINGLEAD_STATUS.CATEGORIES.ARCHIVED,
    [MARKETINGLEAD_STATUS.STATUSES.INACTIVE]: MARKETINGLEAD_STATUS.CATEGORIES.ARCHIVED,
    [MARKETINGLEAD_STATUS.STATUSES.ARCHIVED]: MARKETINGLEAD_STATUS.CATEGORIES.ARCHIVED,
    [MARKETINGLEAD_STATUS.STATUSES.REJECTED]: MARKETINGLEAD_STATUS.CATEGORIES.ARCHIVED,
  };
  return categories[status] || MARKETINGLEAD_STATUS.CATEGORIES.PENDING;
}

export function marketingleadIsActive(status: MarketingLeadStatusType): boolean {
  const activeStatuses: MarketingLeadStatusType[] = [
    MARKETINGLEAD_STATUS.STATUSES.ACTIVE,
    MARKETINGLEAD_STATUS.STATUSES.IN_PROGRESS,
    MARKETINGLEAD_STATUS.STATUSES.OPTIMIZING,
    MARKETINGLEAD_STATUS.STATUSES.OPTIMIZED,
    MARKETINGLEAD_STATUS.STATUSES.SCALING,
    MARKETINGLEAD_STATUS.STATUSES.SCALED,
  ];
  return activeStatuses.includes(status);
}

export function marketingleadIsPending(status: MarketingLeadStatusType): boolean {
  const pendingStatuses: MarketingLeadStatusType[] = [
    MARKETINGLEAD_STATUS.STATUSES.PENDING,
    MARKETINGLEAD_STATUS.STATUSES.REVIEWING,
    MARKETINGLEAD_STATUS.STATUSES.APPROVED,
    MARKETINGLEAD_STATUS.STATUSES.SCHEDULED,
  ];
  return pendingStatuses.includes(status);
}

export function marketingleadIsCompleted(status: MarketingLeadStatusType): boolean {
  const completedStatuses: MarketingLeadStatusType[] = [
    MARKETINGLEAD_STATUS.STATUSES.COMPLETED,
    MARKETINGLEAD_STATUS.STATUSES.ARCHIVED,
  ];
  return completedStatuses.includes(status);
}

export function marketingleadCanTransition(
  currentStatus: MarketingLeadStatusType,
  targetStatus: MarketingLeadStatusType
): boolean {
  const validTransitions: Record<MarketingLeadStatusType, MarketingLeadStatusType[]> = {
    [MARKETINGLEAD_STATUS.STATUSES.DRAFT]: [
      MARKETINGLEAD_STATUS.STATUSES.PENDING,
      MARKETINGLEAD_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGLEAD_STATUS.STATUSES.PENDING]: [
      MARKETINGLEAD_STATUS.STATUSES.REVIEWING,
      MARKETINGLEAD_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGLEAD_STATUS.STATUSES.REVIEWING]: [
      MARKETINGLEAD_STATUS.STATUSES.APPROVED,
      MARKETINGLEAD_STATUS.STATUSES.REJECTED,
      MARKETINGLEAD_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGLEAD_STATUS.STATUSES.APPROVED]: [
      MARKETINGLEAD_STATUS.STATUSES.SCHEDULED,
      MARKETINGLEAD_STATUS.STATUSES.IN_PROGRESS,
      MARKETINGLEAD_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGLEAD_STATUS.STATUSES.REJECTED]: [
      MARKETINGLEAD_STATUS.STATUSES.DRAFT,
      MARKETINGLEAD_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGLEAD_STATUS.STATUSES.SCHEDULED]: [
      MARKETINGLEAD_STATUS.STATUSES.IN_PROGRESS,
      MARKETINGLEAD_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGLEAD_STATUS.STATUSES.IN_PROGRESS]: [
      MARKETINGLEAD_STATUS.STATUSES.ACTIVE,
      MARKETINGLEAD_STATUS.STATUSES.PAUSED,
      MARKETINGLEAD_STATUS.STATUSES.FAILED,
      MARKETINGLEAD_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGLEAD_STATUS.STATUSES.ACTIVE]: [
      MARKETINGLEAD_STATUS.STATUSES.OPTIMIZING,
      MARKETINGLEAD_STATUS.STATUSES.SCALING,
      MARKETINGLEAD_STATUS.STATUSES.PAUSED,
      MARKETINGLEAD_STATUS.STATUSES.COMPLETED,
      MARKETINGLEAD_STATUS.STATUSES.FAILED,
      MARKETINGLEAD_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGLEAD_STATUS.STATUSES.OPTIMIZING]: [
      MARKETINGLEAD_STATUS.STATUSES.OPTIMIZED,
      MARKETINGLEAD_STATUS.STATUSES.PAUSED,
      MARKETINGLEAD_STATUS.STATUSES.FAILED,
    ],
    [MARKETINGLEAD_STATUS.STATUSES.OPTIMIZED]: [
      MARKETINGLEAD_STATUS.STATUSES.ACTIVE,
      MARKETINGLEAD_STATUS.STATUSES.SCALING,
    ],
    [MARKETINGLEAD_STATUS.STATUSES.SCALING]: [
      MARKETINGLEAD_STATUS.STATUSES.SCALED,
      MARKETINGLEAD_STATUS.STATUSES.FAILED,
    ],
    [MARKETINGLEAD_STATUS.STATUSES.SCALED]: [MARKETINGLEAD_STATUS.STATUSES.ACTIVE],
    [MARKETINGLEAD_STATUS.STATUSES.PAUSED]: [
      MARKETINGLEAD_STATUS.STATUSES.IN_PROGRESS,
      MARKETINGLEAD_STATUS.STATUSES.ACTIVE,
      MARKETINGLEAD_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGLEAD_STATUS.STATUSES.COMPLETED]: [MARKETINGLEAD_STATUS.STATUSES.ARCHIVED],
    [MARKETINGLEAD_STATUS.STATUSES.FAILED]: [
      MARKETINGLEAD_STATUS.STATUSES.DRAFT,
      MARKETINGLEAD_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGLEAD_STATUS.STATUSES.CANCELLED]: [MARKETINGLEAD_STATUS.STATUSES.ARCHIVED],
    [MARKETINGLEAD_STATUS.STATUSES.INACTIVE]: [
      MARKETINGLEAD_STATUS.STATUSES.ACTIVE,
      MARKETINGLEAD_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGLEAD_STATUS.STATUSES.ARCHIVED]: [],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
