/**
 * Lead Source Constants
 * Source definitions for lead generation
 */

export const MARKETINGLEAD_SOURCE = {
  // Lead Sources
  SOURCES: {
    WEBSITE: 'website',
    LANDING_PAGE: 'landing_page',
    BLOG: 'blog',
    SOCIAL_MEDIA: 'social_media',
    FACEBOOK: 'facebook',
    INSTAGRAM: 'instagram',
    TWITTER: 'twitter',
    LINKEDIN: 'linkedin',
    YOUTUBE: 'youtube',
    TIKTOK: 'tiktok',
    PINTEREST: 'pinterest',
    EMAIL: 'email',
    NEWSLETTER: 'newsletter',
    EMAIL_CAMPAIGN: 'email_campaign',
    SMS: 'sms',
    PHONE: 'phone',
    CHAT: 'chat',
    LIVE_CHAT: 'live_chat',
    WHATSAPP: 'whatsapp',
    WEBINAR: 'webinar',
    EVENT: 'event',
    TRADE_SHOW: 'trade_show',
    CONFERENCE: 'conference',
    WORKSHOP: 'workshop',
    SEMINAR: 'seminar',
    REFERRAL: 'referral',
    PARTNERSHIP: 'partnership',
    AFFILIATE: 'affiliate',
    INFLUENCER: 'influencer',
    SEARCH_ENGINE: 'search_engine',
    GOOGLE: 'google',
    BING: 'bing',
    YAHOO: 'yahoo',
    PAID_ADS: 'paid_ads',
    GOOGLE_ADS: 'google_ads',
    FACEBOOK_ADS: 'facebook_ads',
    INSTAGRAM_ADS: 'instagram_ads',
    LINKEDIN_ADS: 'linkedin_ads',
    DISPLAY_ADS: 'display_ads',
    RETARGETING: 'retargeting',
    NATIVE_ADS: 'native_ads',
    DIRECT_MAIL: 'direct_mail',
    OUTBOUND_CALL: 'outbound_call',
    INBOUND_CALL: 'inbound_call',
    CONTACT_FORM: 'contact_form',
    POPUP: 'popup',
    SLIDE_IN: 'slide_in',
    EMBEDDED_FORM: 'embedded_form',
    QR_CODE: 'qr_code',
    REFERRAL_CODE: 'referral_code',
    COUPON: 'coupon',
    CUSTOM: 'custom',
    OTHER: 'other',
  } as const,

  // Source Categories
  CATEGORIES: {
    ORGANIC: 'organic',
    PAID: 'paid',
    DIRECT: 'direct',
    REFERRAL: 'referral',
    SOCIAL: 'social',
    EMAIL: 'email',
    SEARCH: 'search',
    DISPLAY: 'display',
    EVENT: 'event',
    PARTNERSHIP: 'partnership',
    OTHER: 'other',
  } as const,

  // Source Quality Scores
  QUALITY_SCORES: {
    HIGH: 10,
    MEDIUM: 5,
    LOW: 2,
    VERY_LOW: 1,
    DEFAULT: 5,
  } as const,

  // Source Trust Levels
  TRUST_LEVELS: {
    HIGH: 'high',
    MEDIUM: 'medium',
    LOW: 'low',
    UNKNOWN: 'unknown',
  } as const,

  // Source Cost Levels
  COST_LEVELS: {
    FREE: 'free',
    LOW: 'low',
    MEDIUM: 'medium',
    HIGH: 'high',
    VERY_HIGH: 'very_high',
  } as const,

  // Source Defaults
  DEFAULTS: {
    DEFAULT_SOURCE: 'website',
    DEFAULT_CATEGORY: 'organic',
    DEFAULT_QUALITY_SCORE: 5,
    DEFAULT_TRUST_LEVEL: 'medium',
    DEFAULT_COST_LEVEL: 'free',
    DEFAULT_CONVERSION_RATE: 3,
    DEFAULT_LEAD_VALUE: 0,
  } as const,
} as const;

// Lead Sources
export type MarketingLeadSource =
  (typeof MARKETINGLEAD_SOURCE.SOURCES)[keyof typeof MARKETINGLEAD_SOURCE.SOURCES];

// Source Categories
export type MarketingLeadSourceCategory =
  (typeof MARKETINGLEAD_SOURCE.CATEGORIES)[keyof typeof MARKETINGLEAD_SOURCE.CATEGORIES];

// Source Quality Scores
export type MarketingLeadSourceQualityScore =
  (typeof MARKETINGLEAD_SOURCE.QUALITY_SCORES)[keyof typeof MARKETINGLEAD_SOURCE.QUALITY_SCORES];

// Source Trust Levels
export type MarketingLeadSourceTrustLevel =
  (typeof MARKETINGLEAD_SOURCE.TRUST_LEVELS)[keyof typeof MARKETINGLEAD_SOURCE.TRUST_LEVELS];

// Source Cost Levels
export type MarketingLeadSourceCostLevel =
  (typeof MARKETINGLEAD_SOURCE.COST_LEVELS)[keyof typeof MARKETINGLEAD_SOURCE.COST_LEVELS];

// Source Defaults
export type MarketingLeadSourceDefault =
  (typeof MARKETINGLEAD_SOURCE.DEFAULTS)[keyof typeof MARKETINGLEAD_SOURCE.DEFAULTS];

// Utility Functions
export function marketingleadGetSourceLabel(source: MarketingLeadSource): string {
  const labels: Record<MarketingLeadSource, string> = {
    [MARKETINGLEAD_SOURCE.SOURCES.WEBSITE]: 'Website',
    [MARKETINGLEAD_SOURCE.SOURCES.LANDING_PAGE]: 'Landing Page',
    [MARKETINGLEAD_SOURCE.SOURCES.BLOG]: 'Blog',
    [MARKETINGLEAD_SOURCE.SOURCES.SOCIAL_MEDIA]: 'Social Media',
    [MARKETINGLEAD_SOURCE.SOURCES.FACEBOOK]: 'Facebook',
    [MARKETINGLEAD_SOURCE.SOURCES.INSTAGRAM]: 'Instagram',
    [MARKETINGLEAD_SOURCE.SOURCES.TWITTER]: 'Twitter/X',
    [MARKETINGLEAD_SOURCE.SOURCES.LINKEDIN]: 'LinkedIn',
    [MARKETINGLEAD_SOURCE.SOURCES.YOUTUBE]: 'YouTube',
    [MARKETINGLEAD_SOURCE.SOURCES.TIKTOK]: 'TikTok',
    [MARKETINGLEAD_SOURCE.SOURCES.PINTEREST]: 'Pinterest',
    [MARKETINGLEAD_SOURCE.SOURCES.EMAIL]: 'Email',
    [MARKETINGLEAD_SOURCE.SOURCES.NEWSLETTER]: 'Newsletter',
    [MARKETINGLEAD_SOURCE.SOURCES.EMAIL_CAMPAIGN]: 'Email Campaign',
    [MARKETINGLEAD_SOURCE.SOURCES.SMS]: 'SMS',
    [MARKETINGLEAD_SOURCE.SOURCES.PHONE]: 'Phone',
    [MARKETINGLEAD_SOURCE.SOURCES.CHAT]: 'Chat',
    [MARKETINGLEAD_SOURCE.SOURCES.LIVE_CHAT]: 'Live Chat',
    [MARKETINGLEAD_SOURCE.SOURCES.WHATSAPP]: 'WhatsApp',
    [MARKETINGLEAD_SOURCE.SOURCES.WEBINAR]: 'Webinar',
    [MARKETINGLEAD_SOURCE.SOURCES.EVENT]: 'Event',
    [MARKETINGLEAD_SOURCE.SOURCES.TRADE_SHOW]: 'Trade Show',
    [MARKETINGLEAD_SOURCE.SOURCES.CONFERENCE]: 'Conference',
    [MARKETINGLEAD_SOURCE.SOURCES.WORKSHOP]: 'Workshop',
    [MARKETINGLEAD_SOURCE.SOURCES.SEMINAR]: 'Seminar',
    [MARKETINGLEAD_SOURCE.SOURCES.REFERRAL]: 'Referral',
    [MARKETINGLEAD_SOURCE.SOURCES.PARTNERSHIP]: 'Partnership',
    [MARKETINGLEAD_SOURCE.SOURCES.AFFILIATE]: 'Affiliate',
    [MARKETINGLEAD_SOURCE.SOURCES.INFLUENCER]: 'Influencer',
    [MARKETINGLEAD_SOURCE.SOURCES.SEARCH_ENGINE]: 'Search Engine',
    [MARKETINGLEAD_SOURCE.SOURCES.GOOGLE]: 'Google',
    [MARKETINGLEAD_SOURCE.SOURCES.BING]: 'Bing',
    [MARKETINGLEAD_SOURCE.SOURCES.YAHOO]: 'Yahoo',
    [MARKETINGLEAD_SOURCE.SOURCES.PAID_ADS]: 'Paid Ads',
    [MARKETINGLEAD_SOURCE.SOURCES.GOOGLE_ADS]: 'Google Ads',
    [MARKETINGLEAD_SOURCE.SOURCES.FACEBOOK_ADS]: 'Facebook Ads',
    [MARKETINGLEAD_SOURCE.SOURCES.INSTAGRAM_ADS]: 'Instagram Ads',
    [MARKETINGLEAD_SOURCE.SOURCES.LINKEDIN_ADS]: 'LinkedIn Ads',
    [MARKETINGLEAD_SOURCE.SOURCES.DISPLAY_ADS]: 'Display Ads',
    [MARKETINGLEAD_SOURCE.SOURCES.RETARGETING]: 'Retargeting',
    [MARKETINGLEAD_SOURCE.SOURCES.NATIVE_ADS]: 'Native Ads',
    [MARKETINGLEAD_SOURCE.SOURCES.DIRECT_MAIL]: 'Direct Mail',
    [MARKETINGLEAD_SOURCE.SOURCES.OUTBOUND_CALL]: 'Outbound Call',
    [MARKETINGLEAD_SOURCE.SOURCES.INBOUND_CALL]: 'Inbound Call',
    [MARKETINGLEAD_SOURCE.SOURCES.CONTACT_FORM]: 'Contact Form',
    [MARKETINGLEAD_SOURCE.SOURCES.POPUP]: 'Popup',
    [MARKETINGLEAD_SOURCE.SOURCES.SLIDE_IN]: 'Slide-In',
    [MARKETINGLEAD_SOURCE.SOURCES.EMBEDDED_FORM]: 'Embedded Form',
    [MARKETINGLEAD_SOURCE.SOURCES.QR_CODE]: 'QR Code',
    [MARKETINGLEAD_SOURCE.SOURCES.REFERRAL_CODE]: 'Referral Code',
    [MARKETINGLEAD_SOURCE.SOURCES.COUPON]: 'Coupon',
    [MARKETINGLEAD_SOURCE.SOURCES.CUSTOM]: 'Custom',
    [MARKETINGLEAD_SOURCE.SOURCES.OTHER]: 'Other',
  };
  return labels[source] || 'Unknown Source';
}

export function marketingleadGetSourceCategory(
  source: MarketingLeadSource
): MarketingLeadSourceCategory {
  const categories: Record<MarketingLeadSource, MarketingLeadSourceCategory> = {
    [MARKETINGLEAD_SOURCE.SOURCES.WEBSITE]: MARKETINGLEAD_SOURCE.CATEGORIES.ORGANIC,
    [MARKETINGLEAD_SOURCE.SOURCES.LANDING_PAGE]: MARKETINGLEAD_SOURCE.CATEGORIES.ORGANIC,
    [MARKETINGLEAD_SOURCE.SOURCES.BLOG]: MARKETINGLEAD_SOURCE.CATEGORIES.ORGANIC,
    [MARKETINGLEAD_SOURCE.SOURCES.SOCIAL_MEDIA]: MARKETINGLEAD_SOURCE.CATEGORIES.SOCIAL,
    [MARKETINGLEAD_SOURCE.SOURCES.FACEBOOK]: MARKETINGLEAD_SOURCE.CATEGORIES.SOCIAL,
    [MARKETINGLEAD_SOURCE.SOURCES.INSTAGRAM]: MARKETINGLEAD_SOURCE.CATEGORIES.SOCIAL,
    [MARKETINGLEAD_SOURCE.SOURCES.TWITTER]: MARKETINGLEAD_SOURCE.CATEGORIES.SOCIAL,
    [MARKETINGLEAD_SOURCE.SOURCES.LINKEDIN]: MARKETINGLEAD_SOURCE.CATEGORIES.SOCIAL,
    [MARKETINGLEAD_SOURCE.SOURCES.YOUTUBE]: MARKETINGLEAD_SOURCE.CATEGORIES.SOCIAL,
    [MARKETINGLEAD_SOURCE.SOURCES.TIKTOK]: MARKETINGLEAD_SOURCE.CATEGORIES.SOCIAL,
    [MARKETINGLEAD_SOURCE.SOURCES.PINTEREST]: MARKETINGLEAD_SOURCE.CATEGORIES.SOCIAL,
    [MARKETINGLEAD_SOURCE.SOURCES.EMAIL]: MARKETINGLEAD_SOURCE.CATEGORIES.EMAIL,
    [MARKETINGLEAD_SOURCE.SOURCES.NEWSLETTER]: MARKETINGLEAD_SOURCE.CATEGORIES.EMAIL,
    [MARKETINGLEAD_SOURCE.SOURCES.EMAIL_CAMPAIGN]: MARKETINGLEAD_SOURCE.CATEGORIES.EMAIL,
    [MARKETINGLEAD_SOURCE.SOURCES.SMS]: MARKETINGLEAD_SOURCE.CATEGORIES.EMAIL,
    [MARKETINGLEAD_SOURCE.SOURCES.PHONE]: MARKETINGLEAD_SOURCE.CATEGORIES.DIRECT,
    [MARKETINGLEAD_SOURCE.SOURCES.CHAT]: MARKETINGLEAD_SOURCE.CATEGORIES.DIRECT,
    [MARKETINGLEAD_SOURCE.SOURCES.LIVE_CHAT]: MARKETINGLEAD_SOURCE.CATEGORIES.DIRECT,
    [MARKETINGLEAD_SOURCE.SOURCES.WHATSAPP]: MARKETINGLEAD_SOURCE.CATEGORIES.DIRECT,
    [MARKETINGLEAD_SOURCE.SOURCES.WEBINAR]: MARKETINGLEAD_SOURCE.CATEGORIES.EVENT,
    [MARKETINGLEAD_SOURCE.SOURCES.EVENT]: MARKETINGLEAD_SOURCE.CATEGORIES.EVENT,
    [MARKETINGLEAD_SOURCE.SOURCES.TRADE_SHOW]: MARKETINGLEAD_SOURCE.CATEGORIES.EVENT,
    [MARKETINGLEAD_SOURCE.SOURCES.CONFERENCE]: MARKETINGLEAD_SOURCE.CATEGORIES.EVENT,
    [MARKETINGLEAD_SOURCE.SOURCES.WORKSHOP]: MARKETINGLEAD_SOURCE.CATEGORIES.EVENT,
    [MARKETINGLEAD_SOURCE.SOURCES.SEMINAR]: MARKETINGLEAD_SOURCE.CATEGORIES.EVENT,
    [MARKETINGLEAD_SOURCE.SOURCES.REFERRAL]: MARKETINGLEAD_SOURCE.CATEGORIES.REFERRAL,
    [MARKETINGLEAD_SOURCE.SOURCES.PARTNERSHIP]: MARKETINGLEAD_SOURCE.CATEGORIES.PARTNERSHIP,
    [MARKETINGLEAD_SOURCE.SOURCES.AFFILIATE]: MARKETINGLEAD_SOURCE.CATEGORIES.PARTNERSHIP,
    [MARKETINGLEAD_SOURCE.SOURCES.INFLUENCER]: MARKETINGLEAD_SOURCE.CATEGORIES.PARTNERSHIP,
    [MARKETINGLEAD_SOURCE.SOURCES.SEARCH_ENGINE]: MARKETINGLEAD_SOURCE.CATEGORIES.SEARCH,
    [MARKETINGLEAD_SOURCE.SOURCES.GOOGLE]: MARKETINGLEAD_SOURCE.CATEGORIES.SEARCH,
    [MARKETINGLEAD_SOURCE.SOURCES.BING]: MARKETINGLEAD_SOURCE.CATEGORIES.SEARCH,
    [MARKETINGLEAD_SOURCE.SOURCES.YAHOO]: MARKETINGLEAD_SOURCE.CATEGORIES.SEARCH,
    [MARKETINGLEAD_SOURCE.SOURCES.PAID_ADS]: MARKETINGLEAD_SOURCE.CATEGORIES.PAID,
    [MARKETINGLEAD_SOURCE.SOURCES.GOOGLE_ADS]: MARKETINGLEAD_SOURCE.CATEGORIES.PAID,
    [MARKETINGLEAD_SOURCE.SOURCES.FACEBOOK_ADS]: MARKETINGLEAD_SOURCE.CATEGORIES.PAID,
    [MARKETINGLEAD_SOURCE.SOURCES.INSTAGRAM_ADS]: MARKETINGLEAD_SOURCE.CATEGORIES.PAID,
    [MARKETINGLEAD_SOURCE.SOURCES.LINKEDIN_ADS]: MARKETINGLEAD_SOURCE.CATEGORIES.PAID,
    [MARKETINGLEAD_SOURCE.SOURCES.DISPLAY_ADS]: MARKETINGLEAD_SOURCE.CATEGORIES.DISPLAY,
    [MARKETINGLEAD_SOURCE.SOURCES.RETARGETING]: MARKETINGLEAD_SOURCE.CATEGORIES.DISPLAY,
    [MARKETINGLEAD_SOURCE.SOURCES.NATIVE_ADS]: MARKETINGLEAD_SOURCE.CATEGORIES.DISPLAY,
    [MARKETINGLEAD_SOURCE.SOURCES.DIRECT_MAIL]: MARKETINGLEAD_SOURCE.CATEGORIES.DIRECT,
    [MARKETINGLEAD_SOURCE.SOURCES.OUTBOUND_CALL]: MARKETINGLEAD_SOURCE.CATEGORIES.DIRECT,
    [MARKETINGLEAD_SOURCE.SOURCES.INBOUND_CALL]: MARKETINGLEAD_SOURCE.CATEGORIES.DIRECT,
    [MARKETINGLEAD_SOURCE.SOURCES.CONTACT_FORM]: MARKETINGLEAD_SOURCE.CATEGORIES.DIRECT,
    [MARKETINGLEAD_SOURCE.SOURCES.POPUP]: MARKETINGLEAD_SOURCE.CATEGORIES.DIRECT,
    [MARKETINGLEAD_SOURCE.SOURCES.SLIDE_IN]: MARKETINGLEAD_SOURCE.CATEGORIES.DIRECT,
    [MARKETINGLEAD_SOURCE.SOURCES.EMBEDDED_FORM]: MARKETINGLEAD_SOURCE.CATEGORIES.DIRECT,
    [MARKETINGLEAD_SOURCE.SOURCES.QR_CODE]: MARKETINGLEAD_SOURCE.CATEGORIES.DIRECT,
    [MARKETINGLEAD_SOURCE.SOURCES.REFERRAL_CODE]: MARKETINGLEAD_SOURCE.CATEGORIES.REFERRAL,
    [MARKETINGLEAD_SOURCE.SOURCES.COUPON]: MARKETINGLEAD_SOURCE.CATEGORIES.REFERRAL,
    [MARKETINGLEAD_SOURCE.SOURCES.CUSTOM]: MARKETINGLEAD_SOURCE.CATEGORIES.OTHER,
    [MARKETINGLEAD_SOURCE.SOURCES.OTHER]: MARKETINGLEAD_SOURCE.CATEGORIES.OTHER,
  };
  return categories[source] || MARKETINGLEAD_SOURCE.CATEGORIES.OTHER;
}

export function marketingleadGetSourceQualityScore(
  source: MarketingLeadSource
): MarketingLeadSourceQualityScore {
  const scores: Record<MarketingLeadSource, MarketingLeadSourceQualityScore> = {
    [MARKETINGLEAD_SOURCE.SOURCES.WEBSITE]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.LANDING_PAGE]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.BLOG]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.SOCIAL_MEDIA]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.FACEBOOK]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.INSTAGRAM]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.TWITTER]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.LINKEDIN]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.YOUTUBE]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.TIKTOK]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.PINTEREST]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.EMAIL]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.NEWSLETTER]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.EMAIL_CAMPAIGN]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.SMS]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.PHONE]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.CHAT]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.LIVE_CHAT]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.WHATSAPP]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.WEBINAR]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.EVENT]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.TRADE_SHOW]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.CONFERENCE]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.WORKSHOP]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.SEMINAR]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.REFERRAL]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.PARTNERSHIP]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.AFFILIATE]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.INFLUENCER]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.SEARCH_ENGINE]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.GOOGLE]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.BING]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.YAHOO]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.PAID_ADS]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.GOOGLE_ADS]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.FACEBOOK_ADS]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.INSTAGRAM_ADS]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.LINKEDIN_ADS]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.DISPLAY_ADS]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.RETARGETING]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.NATIVE_ADS]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.DIRECT_MAIL]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.OUTBOUND_CALL]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.INBOUND_CALL]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.CONTACT_FORM]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.POPUP]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.SLIDE_IN]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.EMBEDDED_FORM]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.QR_CODE]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.REFERRAL_CODE]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.COUPON]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.CUSTOM]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.OTHER]: MARKETINGLEAD_SOURCE.QUALITY_SCORES.LOW,
  };
  return scores[source] || MARKETINGLEAD_SOURCE.QUALITY_SCORES.DEFAULT;
}

export function marketingleadGetSourceTrustLevel(
  source: MarketingLeadSource
): MarketingLeadSourceTrustLevel {
  const trustLevels: Record<MarketingLeadSource, MarketingLeadSourceTrustLevel> = {
    [MARKETINGLEAD_SOURCE.SOURCES.WEBSITE]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.LANDING_PAGE]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.BLOG]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.SOCIAL_MEDIA]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.FACEBOOK]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.INSTAGRAM]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.TWITTER]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.LINKEDIN]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.YOUTUBE]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.TIKTOK]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.PINTEREST]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.EMAIL]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.NEWSLETTER]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.EMAIL_CAMPAIGN]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.SMS]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.PHONE]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.CHAT]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.LIVE_CHAT]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.WHATSAPP]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.WEBINAR]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.EVENT]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.TRADE_SHOW]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.CONFERENCE]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.WORKSHOP]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.SEMINAR]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.REFERRAL]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.PARTNERSHIP]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.AFFILIATE]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.INFLUENCER]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.SEARCH_ENGINE]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.GOOGLE]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.BING]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.YAHOO]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.PAID_ADS]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.GOOGLE_ADS]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.FACEBOOK_ADS]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.INSTAGRAM_ADS]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.LINKEDIN_ADS]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.DISPLAY_ADS]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.RETARGETING]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.NATIVE_ADS]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.DIRECT_MAIL]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.OUTBOUND_CALL]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.INBOUND_CALL]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.CONTACT_FORM]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.POPUP]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.SLIDE_IN]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.EMBEDDED_FORM]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.QR_CODE]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.REFERRAL_CODE]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.COUPON]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.CUSTOM]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.OTHER]: MARKETINGLEAD_SOURCE.TRUST_LEVELS.LOW,
  };
  return trustLevels[source] || MARKETINGLEAD_SOURCE.TRUST_LEVELS.UNKNOWN;
}

export function marketingleadGetSourceCostLevel(
  source: MarketingLeadSource
): MarketingLeadSourceCostLevel {
  const costLevels: Record<MarketingLeadSource, MarketingLeadSourceCostLevel> = {
    [MARKETINGLEAD_SOURCE.SOURCES.WEBSITE]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.LANDING_PAGE]: MARKETINGLEAD_SOURCE.COST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.BLOG]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.SOCIAL_MEDIA]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.FACEBOOK]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.INSTAGRAM]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.TWITTER]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.LINKEDIN]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.YOUTUBE]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.TIKTOK]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.PINTEREST]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.EMAIL]: MARKETINGLEAD_SOURCE.COST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.NEWSLETTER]: MARKETINGLEAD_SOURCE.COST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.EMAIL_CAMPAIGN]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.SMS]: MARKETINGLEAD_SOURCE.COST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.PHONE]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.CHAT]: MARKETINGLEAD_SOURCE.COST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.LIVE_CHAT]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.WHATSAPP]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.WEBINAR]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.EVENT]: MARKETINGLEAD_SOURCE.COST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.TRADE_SHOW]: MARKETINGLEAD_SOURCE.COST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.CONFERENCE]: MARKETINGLEAD_SOURCE.COST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.WORKSHOP]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.SEMINAR]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.REFERRAL]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.PARTNERSHIP]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.AFFILIATE]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.INFLUENCER]: MARKETINGLEAD_SOURCE.COST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.SEARCH_ENGINE]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.GOOGLE]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.BING]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.YAHOO]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.PAID_ADS]: MARKETINGLEAD_SOURCE.COST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.GOOGLE_ADS]: MARKETINGLEAD_SOURCE.COST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.FACEBOOK_ADS]: MARKETINGLEAD_SOURCE.COST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.INSTAGRAM_ADS]: MARKETINGLEAD_SOURCE.COST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.LINKEDIN_ADS]: MARKETINGLEAD_SOURCE.COST_LEVELS.VERY_HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.DISPLAY_ADS]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.RETARGETING]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.NATIVE_ADS]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.DIRECT_MAIL]: MARKETINGLEAD_SOURCE.COST_LEVELS.HIGH,
    [MARKETINGLEAD_SOURCE.SOURCES.OUTBOUND_CALL]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.INBOUND_CALL]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.CONTACT_FORM]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.POPUP]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.SLIDE_IN]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.EMBEDDED_FORM]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.QR_CODE]: MARKETINGLEAD_SOURCE.COST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.REFERRAL_CODE]: MARKETINGLEAD_SOURCE.COST_LEVELS.FREE,
    [MARKETINGLEAD_SOURCE.SOURCES.COUPON]: MARKETINGLEAD_SOURCE.COST_LEVELS.LOW,
    [MARKETINGLEAD_SOURCE.SOURCES.CUSTOM]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
    [MARKETINGLEAD_SOURCE.SOURCES.OTHER]: MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM,
  };
  return costLevels[source] || MARKETINGLEAD_SOURCE.COST_LEVELS.MEDIUM;
}

export function marketingleadGetDefaultSource(): MarketingLeadSource {
  return MARKETINGLEAD_SOURCE.DEFAULTS.DEFAULT_SOURCE;
}

export function marketingleadIsOrganicSource(category: MarketingLeadSourceCategory): boolean {
  return category === MARKETINGLEAD_SOURCE.CATEGORIES.ORGANIC;
}

export function marketingleadIsPaidSource(category: MarketingLeadSourceCategory): boolean {
  const paidCategories: MarketingLeadSourceCategory[] = [
    MARKETINGLEAD_SOURCE.CATEGORIES.PAID,
    MARKETINGLEAD_SOURCE.CATEGORIES.DISPLAY,
  ];
  return paidCategories.includes(category);
}

export function marketingleadIsHighQualitySource(source: MarketingLeadSource): boolean {
  return marketingleadGetSourceQualityScore(source) >= MARKETINGLEAD_SOURCE.QUALITY_SCORES.HIGH;
}
