module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/*.module.ts',
    '!**/*.interface.ts',
    '!**/index.ts',
    '!**/*.dto.ts',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@vubon/shared-constants$': '<rootDir>/../../../packages/shared-constants/src',
    '^@vubon/shared-constants/(.*)$': '<rootDir>/../../../packages/shared-constants/src/$1',
    '^@vubon/shared-types$': '<rootDir>/../../../packages/shared-types/src',
    '^@vubon/shared-types/(.*)$': '<rootDir>/../../../packages/shared-types/src/$1',
    '^@vubon/shared-schemas$': '<rootDir>/../../../packages/shared-schemas/src',
    '^@vubon/shared-schemas/(.*)$': '<rootDir>/../../../packages/shared-schemas/src/$1',
    '^@vubon/shared-utils$': '<rootDir>/../../../packages/shared-utils/src',
    '^@vubon/shared-utils/(.*)$': '<rootDir>/../../../packages/shared-utils/src/$1',
    '^@vubon/shared-config$': '<rootDir>/../../../packages/shared-config/src',
    '^@vubon/shared-config/(.*)$': '<rootDir>/../../../packages/shared-config/src/$1',
    '^@vubon/shared-api$': '<rootDir>/../../../packages/shared-api/src',
    '^@vubon/shared-api/(.*)$': '<rootDir>/../../../packages/shared-api/src/$1',
    '^@vubon/shared-auth$': '<rootDir>/../../../packages/shared-auth/src',
    '^@vubon/shared-auth/(.*)$': '<rootDir>/../../../packages/shared-auth/src/$1',
    '^@/(.*)$': '<rootDir>/$1',
    '^@domain/(.*)$': '<rootDir>/module/domain/$1',
    '^@application/(.*)$': '<rootDir>/module/application/$1',
    '^@infrastructure/(.*)$': '<rootDir>/module/infrastructure/$1',
    '^@interfaces/(.*)$': '<rootDir>/module/interfaces/$1',
    '^@modules/(.*)$': '<rootDir>/module/modules/$1',
  },
};
