/**
 * Currency Constants
 * @module shared-constants/common/currency.constants
 */

export const CURRENCY = {
  // Major currencies
  BDT: {
    code: 'BDT',
    symbol: '৳',
    name: 'Bangladeshi Taka',
    name_plural: 'Bangladeshi Takas',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  USD: {
    code: 'USD',
    symbol: '$',
    name: 'US Dollar',
    name_plural: 'US Dollars',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  EUR: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    name_plural: 'Euros',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  GBP: {
    code: 'GBP',
    symbol: '£',
    name: 'British Pound',
    name_plural: 'British Pounds',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  JPY: {
    code: 'JPY',
    symbol: '¥',
    name: 'Japanese Yen',
    name_plural: 'Japanese Yen',
    decimal_digits: 0,
    rounding: 0,
    format: 'symbol',
  },
  CNY: {
    code: 'CNY',
    symbol: '¥',
    name: 'Chinese Yuan',
    name_plural: 'Chinese Yuans',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  INR: {
    code: 'INR',
    symbol: '₹',
    name: 'Indian Rupee',
    name_plural: 'Indian Rupees',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  PKR: {
    code: 'PKR',
    symbol: '₨',
    name: 'Pakistani Rupee',
    name_plural: 'Pakistani Rupees',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  AED: {
    code: 'AED',
    symbol: 'د.إ',
    name: 'UAE Dirham',
    name_plural: 'UAE Dirhams',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  SAR: {
    code: 'SAR',
    symbol: 'ر.س',
    name: 'Saudi Riyal',
    name_plural: 'Saudi Riyals',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  SGD: {
    code: 'SGD',
    symbol: 'S$',
    name: 'Singapore Dollar',
    name_plural: 'Singapore Dollars',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  AUD: {
    code: 'AUD',
    symbol: 'A$',
    name: 'Australian Dollar',
    name_plural: 'Australian Dollars',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  CAD: {
    code: 'CAD',
    symbol: 'C$',
    name: 'Canadian Dollar',
    name_plural: 'Canadian Dollars',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  CHF: {
    code: 'CHF',
    symbol: 'Fr',
    name: 'Swiss Franc',
    name_plural: 'Swiss Francs',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  MYR: {
    code: 'MYR',
    symbol: 'RM',
    name: 'Malaysian Ringgit',
    name_plural: 'Malaysian Ringgits',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  THB: {
    code: 'THB',
    symbol: '฿',
    name: 'Thai Baht',
    name_plural: 'Thai Bahts',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  VND: {
    code: 'VND',
    symbol: '₫',
    name: 'Vietnamese Dong',
    name_plural: 'Vietnamese Dongs',
    decimal_digits: 0,
    rounding: 0,
    format: 'symbol',
  },
  PHP: {
    code: 'PHP',
    symbol: '₱',
    name: 'Philippine Peso',
    name_plural: 'Philippine Pesos',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  IDR: {
    code: 'IDR',
    symbol: 'Rp',
    name: 'Indonesian Rupiah',
    name_plural: 'Indonesian Rupiahs',
    decimal_digits: 0,
    rounding: 0,
    format: 'symbol',
  },
  KRW: {
    code: 'KRW',
    symbol: '₩',
    name: 'South Korean Won',
    name_plural: 'South Korean Wons',
    decimal_digits: 0,
    rounding: 0,
    format: 'symbol',
  },
  RUB: {
    code: 'RUB',
    symbol: '₽',
    name: 'Russian Ruble',
    name_plural: 'Russian Rubles',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  BRL: {
    code: 'BRL',
    symbol: 'R$',
    name: 'Brazilian Real',
    name_plural: 'Brazilian Reals',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  ZAR: {
    code: 'ZAR',
    symbol: 'R',
    name: 'South African Rand',
    name_plural: 'South African Rands',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  NZD: {
    code: 'NZD',
    symbol: 'NZ$',
    name: 'New Zealand Dollar',
    name_plural: 'New Zealand Dollars',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
  TRY: {
    code: 'TRY',
    symbol: '₺',
    name: 'Turkish Lira',
    name_plural: 'Turkish Liras',
    decimal_digits: 2,
    rounding: 0,
    format: 'symbol',
  },
} as const;

export type CurrencyCode = keyof typeof CURRENCY;

export const DEFAULT_CURRENCY: CurrencyCode = 'BDT';

export const CURRENCY_LIST = Object.keys(CURRENCY) as CurrencyCode[];

export const CURRENCY_FORMATS = {
  BDT: {
    locale: 'bn-BD',
    style: 'currency',
    currency: 'BDT',
    currencyDisplay: 'symbol',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  },
  USD: {
    locale: 'en-US',
    style: 'currency',
    currency: 'USD',
    currencyDisplay: 'symbol',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  },
  EUR: {
    locale: 'de-DE',
    style: 'currency',
    currency: 'EUR',
    currencyDisplay: 'symbol',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  },
  GBP: {
    locale: 'en-GB',
    style: 'currency',
    currency: 'GBP',
    currencyDisplay: 'symbol',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  },
} as const;

export const CURRENCY_SYMBOLS: Record<CurrencyCode, string> = {
  BDT: '৳',
  USD: '$',
  EUR: '€',
  GBP: '£',
  JPY: '¥',
  CNY: '¥',
  INR: '₹',
  PKR: '₨',
  AED: 'د.إ',
  SAR: 'ر.س',
  SGD: 'S$',
  AUD: 'A$',
  CAD: 'C$',
  CHF: 'Fr',
  MYR: 'RM',
  THB: '฿',
  VND: '₫',
  PHP: '₱',
  IDR: 'Rp',
  KRW: '₩',
  RUB: '₽',
  BRL: 'R$',
  ZAR: 'R',
  NZD: 'NZ$',
  TRY: '₺',
};

export const CURRENCY_NAMES: Record<CurrencyCode, string> = {
  BDT: 'Bangladeshi Taka',
  USD: 'US Dollar',
  EUR: 'Euro',
  GBP: 'British Pound',
  JPY: 'Japanese Yen',
  CNY: 'Chinese Yuan',
  INR: 'Indian Rupee',
  PKR: 'Pakistani Rupee',
  AED: 'UAE Dirham',
  SAR: 'Saudi Riyal',
  SGD: 'Singapore Dollar',
  AUD: 'Australian Dollar',
  CAD: 'Canadian Dollar',
  CHF: 'Swiss Franc',
  MYR: 'Malaysian Ringgit',
  THB: 'Thai Baht',
  VND: 'Vietnamese Dong',
  PHP: 'Philippine Peso',
  IDR: 'Indonesian Rupiah',
  KRW: 'South Korean Won',
  RUB: 'Russian Ruble',
  BRL: 'Brazilian Real',
  ZAR: 'South African Rand',
  NZD: 'New Zealand Dollar',
  TRY: 'Turkish Lira',
};
