/**
 * Bangladesh Districts Constants
 * @module shared-constants/common/districts.constants
 */

import { DIVISIONS } from './divisions.constants';

export const DISTRICTS = {
  // Dhaka Division
  DHAKA: 'ঢাকা',
  GAZIPUR: 'গাজীপুর',
  NARAYANGANJ: 'নারায়ণগঞ্জ',
  TANGAIL: 'টাঙ্গাইল',
  KISHOREGANJ: 'কিশোরগঞ্জ',
  MANIKGANJ: 'মানিকগঞ্জ',
  MUNSHIGANJ: 'মুন্সীগঞ্জ',
  NARSINGDI: 'নরসিংদী',
  FARIDPUR: 'ফরিদপুর',
  RAJBARI: 'রাজবাড়ী',
  MADARIPUR: 'মাদারীপুর',
  SHARIATPUR: 'শরীয়তপুর',
  GOPALGANJ: 'গোপালগঞ্জ',

  // Chittagong Division
  CHITTAGONG: 'চট্টগ্রাম',
  COX_BAZAR: 'কক্সবাজার',
  RANGAMATI: 'রাঙ্গামাটি',
  KHAGRACHHARI: 'খাগড়াছড়ি',
  BANDARBAN: 'বান্দরবান',
  FENI: 'ফেনী',
  NOAKHALI: 'নোয়াখালী',
  LAKSHMIPUR: 'লক্ষ্মীপুর',
  COMILLA: 'কুমিল্লা',
  BRAHMANBARIA: 'ব্রাহ্মণবাড়িয়া',
  CHANDPUR: 'চাঁদপুর',

  // Rajshahi Division
  RAJSHAHI: 'রাজশাহী',
  NATORE: 'নাটোর',
  CHAPAI_NAWABGANJ: 'চাঁপাইনবাবগঞ্জ',
  NAOGAON: 'নওগাঁ',
  JOYPURHAT: 'জয়পুরহাট',
  BOGURA: 'বগুড়া',
  SIRAJGANJ: 'সিরাজগঞ্জ',
  PABNA: 'পাবনা',

  // Khulna Division
  KHULNA: 'খুলনা',
  JASHORE: 'যশোর',
  SATKHIRA: 'সাতক্ষীরা',
  NARAIL: 'নড়াইল',
  MAGURA: 'মাগুরা',
  JHENIDAH: 'ঝিনাইদহ',
  CHUADANGA: 'চুয়াডাঙ্গা',
  KUSHTIA: 'কুষ্টিয়া',
  MEHERPUR: 'মেহেরপুর',
  BAGERHAT: 'বাগেরহাট',

  // Barishal Division
  BARISHAL: 'বরিশাল',
  PIROJPUR: 'পিরোজপুর',
  JHALOKATHI: 'ঝালকাঠি',
  PATUAKHALI: 'পটুয়াখালী',
  BHOLA: 'ভোলা',
  BARGUNA: 'বরগুনা',

  // Sylhet Division
  SYLHET: 'সিলেট',
  MOULVIBAZAR: 'মৌলভীবাজার',
  HABIGANJ: 'হবিগঞ্জ',
  SUNAMGANJ: 'সুনামগঞ্জ',

  // Rangpur Division
  RANGPUR: 'রংপুর',
  KURIGRAM: 'কুড়িগ্রাম',
  GAIBANDHA: 'গাইবান্ধা',
  LALMONIRHAT: 'লালমনিরহাট',
  NILPHAMARI: 'নীলফামারী',
  DINAJPUR: 'দিনাজপুর',
  THAKURGAON: 'ঠাকুরগাঁও',
  PANCHAGARH: 'পঞ্চগড়',

  // Mymensingh Division
  MYMENSINGH: 'ময়মনসিংহ',
  JAMALPUR: 'জামালপুর',
  SHERPUR: 'শেরপুর',
  NETROKONA: 'নেত্রকোনা',
} as const;

export type District = (typeof DISTRICTS)[keyof typeof DISTRICTS];

export const DISTRICT_DIVISION_MAP: Record<keyof typeof DISTRICTS, keyof typeof DIVISIONS> = {
  // Dhaka Division
  DHAKA: 'DHAKA',
  GAZIPUR: 'DHAKA',
  NARAYANGANJ: 'DHAKA',
  TANGAIL: 'DHAKA',
  KISHOREGANJ: 'DHAKA',
  MANIKGANJ: 'DHAKA',
  MUNSHIGANJ: 'DHAKA',
  NARSINGDI: 'DHAKA',
  FARIDPUR: 'DHAKA',
  RAJBARI: 'DHAKA',
  MADARIPUR: 'DHAKA',
  SHARIATPUR: 'DHAKA',
  GOPALGANJ: 'DHAKA',

  // Chittagong Division
  CHITTAGONG: 'CHITTAGONG',
  COX_BAZAR: 'CHITTAGONG',
  RANGAMATI: 'CHITTAGONG',
  KHAGRACHHARI: 'CHITTAGONG',
  BANDARBAN: 'CHITTAGONG',
  FENI: 'CHITTAGONG',
  NOAKHALI: 'CHITTAGONG',
  LAKSHMIPUR: 'CHITTAGONG',
  COMILLA: 'CHITTAGONG',
  BRAHMANBARIA: 'CHITTAGONG',
  CHANDPUR: 'CHITTAGONG',

  // Rajshahi Division
  RAJSHAHI: 'RAJSHAHI',
  NATORE: 'RAJSHAHI',
  CHAPAI_NAWABGANJ: 'RAJSHAHI',
  NAOGAON: 'RAJSHAHI',
  JOYPURHAT: 'RAJSHAHI',
  BOGURA: 'RAJSHAHI',
  SIRAJGANJ: 'RAJSHAHI',
  PABNA: 'RAJSHAHI',

  // Khulna Division
  KHULNA: 'KHULNA',
  JASHORE: 'KHULNA',
  SATKHIRA: 'KHULNA',
  NARAIL: 'KHULNA',
  MAGURA: 'KHULNA',
  JHENIDAH: 'KHULNA',
  CHUADANGA: 'KHULNA',
  KUSHTIA: 'KHULNA',
  MEHERPUR: 'KHULNA',
  BAGERHAT: 'KHULNA',

  // Barishal Division
  BARISHAL: 'BARISHAL',
  PIROJPUR: 'BARISHAL',
  JHALOKATHI: 'BARISHAL',
  PATUAKHALI: 'BARISHAL',
  BHOLA: 'BARISHAL',
  BARGUNA: 'BARISHAL',

  // Sylhet Division
  SYLHET: 'SYLHET',
  MOULVIBAZAR: 'SYLHET',
  HABIGANJ: 'SYLHET',
  SUNAMGANJ: 'SYLHET',

  // Rangpur Division
  RANGPUR: 'RANGPUR',
  KURIGRAM: 'RANGPUR',
  GAIBANDHA: 'RANGPUR',
  LALMONIRHAT: 'RANGPUR',
  NILPHAMARI: 'RANGPUR',
  DINAJPUR: 'RANGPUR',
  THAKURGAON: 'RANGPUR',
  PANCHAGARH: 'RANGPUR',

  // Mymensingh Division
  MYMENSINGH: 'MYMENSINGH',
  JAMALPUR: 'MYMENSINGH',
  SHERPUR: 'MYMENSINGH',
  NETROKONA: 'MYMENSINGH',
};

export const DISTRICT_CODES: Record<keyof typeof DISTRICTS, string> = {
  DHAKA: '30',
  GAZIPUR: '31',
  NARAYANGANJ: '32',
  TANGAIL: '33',
  KISHOREGANJ: '34',
  MANIKGANJ: '35',
  MUNSHIGANJ: '36',
  NARSINGDI: '37',
  FARIDPUR: '38',
  RAJBARI: '39',
  MADARIPUR: '40',
  SHARIATPUR: '41',
  GOPALGANJ: '42',
  CHITTAGONG: '20',
  COX_BAZAR: '21',
  RANGAMATI: '22',
  KHAGRACHHARI: '23',
  BANDARBAN: '24',
  FENI: '25',
  NOAKHALI: '26',
  LAKSHMIPUR: '27',
  COMILLA: '28',
  BRAHMANBARIA: '29',
  CHANDPUR: '30',
  RAJSHAHI: '50',
  NATORE: '51',
  CHAPAI_NAWABGANJ: '52',
  NAOGAON: '53',
  JOYPURHAT: '54',
  BOGURA: '55',
  SIRAJGANJ: '56',
  PABNA: '57',
  KHULNA: '40',
  JASHORE: '41',
  SATKHIRA: '42',
  NARAIL: '43',
  MAGURA: '44',
  JHENIDAH: '45',
  CHUADANGA: '46',
  KUSHTIA: '47',
  MEHERPUR: '48',
  BAGERHAT: '49',
  BARISHAL: '10',
  PIROJPUR: '11',
  JHALOKATHI: '12',
  PATUAKHALI: '13',
  BHOLA: '14',
  BARGUNA: '15',
  SYLHET: '60',
  MOULVIBAZAR: '61',
  HABIGANJ: '62',
  SUNAMGANJ: '63',
  RANGPUR: '55',
  KURIGRAM: '56',
  GAIBANDHA: '57',
  LALMONIRHAT: '58',
  NILPHAMARI: '59',
  DINAJPUR: '60',
  THAKURGAON: '61',
  PANCHAGARH: '62',
  MYMENSINGH: '45',
  JAMALPUR: '46',
  SHERPUR: '47',
  NETROKONA: '48',
};

export const DISTRICT_EN_NAMES: Record<keyof typeof DISTRICTS, string> = {
  DHAKA: 'Dhaka',
  GAZIPUR: 'Gazipur',
  NARAYANGANJ: 'Narayanganj',
  TANGAIL: 'Tangail',
  KISHOREGANJ: 'Kishoreganj',
  MANIKGANJ: 'Manikganj',
  MUNSHIGANJ: 'Munshiganj',
  NARSINGDI: 'Narsingdi',
  FARIDPUR: 'Faridpur',
  RAJBARI: 'Rajbari',
  MADARIPUR: 'Madaripur',
  SHARIATPUR: 'Shariatpur',
  GOPALGANJ: 'Gopalganj',
  CHITTAGONG: 'Chittagong',
  COX_BAZAR: "Cox's Bazar",
  RANGAMATI: 'Rangamati',
  KHAGRACHHARI: 'Khagrachhari',
  BANDARBAN: 'Bandarban',
  FENI: 'Feni',
  NOAKHALI: 'Noakhali',
  LAKSHMIPUR: 'Lakshmipur',
  COMILLA: 'Comilla',
  BRAHMANBARIA: 'Brahmanbaria',
  CHANDPUR: 'Chandpur',
  RAJSHAHI: 'Rajshahi',
  NATORE: 'Natore',
  CHAPAI_NAWABGANJ: 'Chapai Nawabganj',
  NAOGAON: 'Naogaon',
  JOYPURHAT: 'Joypurhat',
  BOGURA: 'Bogura',
  SIRAJGANJ: 'Sirajganj',
  PABNA: 'Pabna',
  KHULNA: 'Khulna',
  JASHORE: 'Jashore',
  SATKHIRA: 'Satkhira',
  NARAIL: 'Narail',
  MAGURA: 'Magura',
  JHENIDAH: 'Jhenidah',
  CHUADANGA: 'Chuadanga',
  KUSHTIA: 'Kushtia',
  MEHERPUR: 'Meherpur',
  BAGERHAT: 'Bagerhat',
  BARISHAL: 'Barishal',
  PIROJPUR: 'Pirojpur',
  JHALOKATHI: 'Jhalokathi',
  PATUAKHALI: 'Patuakhali',
  BHOLA: 'Bhola',
  BARGUNA: 'Barguna',
  SYLHET: 'Sylhet',
  MOULVIBAZAR: 'Moulvibazar',
  HABIGANJ: 'Habiganj',
  SUNAMGANJ: 'Sunamganj',
  RANGPUR: 'Rangpur',
  KURIGRAM: 'Kurigram',
  GAIBANDHA: 'Gaibandha',
  LALMONIRHAT: 'Lalmonirhat',
  NILPHAMARI: 'Nilphamari',
  DINAJPUR: 'Dinajpur',
  THAKURGAON: 'Thakurgaon',
  PANCHAGARH: 'Panchagarh',
  MYMENSINGH: 'Mymensingh',
  JAMALPUR: 'Jamalpur',
  SHERPUR: 'Sherpur',
  NETROKONA: 'Netrokona',
};
