export const ERROR_CODE = {
  AUTH_INVALID_CREDENTIALS: 'AUTH-001',
  AUTH_TOKEN_EXPIRED: 'AUTH-002',
  AUTH_TOKEN_INVALID: 'AUTH-003',
  AUTH_UNAUTHORIZED: 'AUTH-004',
  AUTH_FORBIDDEN: 'AUTH-005',
  AUTH_MFA_REQUIRED: 'AUTH-006',
  AUTH_ACCOUNT_LOCKED: 'AUTH-007',

  VAL_REQUIRED: 'VAL-001',
  VAL_INVALID_FORMAT: 'VAL-002',
  VAL_OUT_OF_RANGE: 'VAL-003',
  VAL_DUPLICATE: 'VAL-004',

  USER_NOT_FOUND: 'USR-001',
  USER_ALREADY_EXISTS: 'USR-002',
  USER_INACTIVE: 'USR-003',

  PRODUCT_NOT_FOUND: 'PRD-001',
  PRODUCT_OUT_OF_STOCK: 'PRD-002',

  CART_EMPTY: 'CRT-001',
  CART_ITEM_NOT_FOUND: 'CRT-002',

  ORDER_NOT_FOUND: 'ORD-001',
  ORDER_ALREADY_CANCELLED: 'ORD-002',

  PAYMENT_FAILED: 'PAY-001',
  PAYMENT_DECLINED: 'PAY-002',

  SERVER_INTERNAL: 'SRV-001',
  SERVER_UNAVAILABLE: 'SRV-002',
  SERVER_TIMEOUT: 'SRV-003',

  RATE_LIMIT_EXCEEDED: 'RATE-001',
} as const;

export type ErrorCodeType = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
