/**
 * Common Constants Exports
 * Export all common constants from a single entry point
 */

// Export Product constants
export {
  ProductHttpStatus,
  ProductHttpStatusMessages,
  type ProductHttpStatusCode,
  ProductRegex,
  ProductRegexTester,
  ProductCache,
  ProductCacheKey,
  ProductCacheTTL,
  ProductQueue,
  ProductQueueConfig,
  type ProductQueueName,
  type ProductQueueEvent,
  type ProductJobType,
} from './product';

// Export Checkout constants
export {
  CheckoutHttpStatus,
  CheckoutHttpStatusMessages,
  CheckoutHttpStatusCategories,
  type CheckoutHttpStatusCode,
  CheckoutRegex,
  CheckoutRegexTester,
  CheckoutCache,
  CheckoutCacheKey,
  CheckoutCacheTTL,
  CheckoutQueue,
  CheckoutQueueConfig,
  type CheckoutQueueName,
  type CheckoutQueueEvent,
  type CheckoutJobType,
} from './checkout';

// Export Cart constants
export {
  CartHttpStatus,
  CartHttpStatusMessages,
  CartHttpStatusCategories,
  type CartHttpStatusCode,
  CartRegex,
  CartRegexTester,
  CartCache,
  CartCacheKey,
  CartCacheTTL,
  CartQueue,
  CartQueueConfig,
  type CartQueueName,
  type CartQueueEvent,
  type CartJobType,
} from './cart';

// Export Search & Discovery constants
export {
  SearchHttpStatus,
  SearchHttpStatusMessages,
  SearchHttpStatusCategories,
  type SearchHttpStatusCode,
  SearchRegex,
  SearchRegexTester,
  SearchCache,
  SearchCacheKey,
  SearchCacheTTL,
  SearchQueue,
  SearchQueueConfig,
  type SearchQueueName,
  type SearchQueueEvent,
  type SearchJobType,
} from './search-discovery';

// Export Vendor constants
export {
  VendorHttpStatus,
  VendorHttpStatusMessages,
  VendorHttpStatusCategories,
  VendorHttpStatusDescriptions,
  type VendorHttpStatusCode,
  VendorRegex,
  VendorRegexDescriptions,
  VendorRegexExamples,
  VendorRegexValidationMessages,
  VendorRegexTester,
  VendorCache,
  VendorCacheKey,
  VendorCacheTTL,
  VendorCacheStrategy,
  VendorQueue,
  VendorQueueConfig,
  type VendorQueueName,
  type VendorQueueEvent,
  type VendorJobType,
} from './vendor';

// Export Logistics constants
export {
  LogisticsHttpStatus,
  LogisticsHttpStatusMessages,
  LogisticsHttpStatusCategories,
  type LogisticsHttpStatusCode,
  LogisticsRegex,
  LogisticsRegexTester,
  LogisticsCache,
  LogisticsCacheKey,
  LogisticsCacheTTL,
  LogisticsCacheConfig,
  LogisticsQueue,
  LogisticsQueueConfig,
  type LogisticsQueueName,
  type LogisticsQueueEvent,
  type LogisticsJobType,
  type LogisticsExchangeType,
} from './logistics';

// Export Support constants
export {
  SupportHttpStatus,
  SupportHttpStatusMessages,
  SupportHttpStatusCategories,
  type SupportHttpStatusCode,
  SupportRegex,
  SupportRegexTester,
  SupportCache,
  SupportCacheKey,
  SupportCacheTTL,
  SupportCacheConfig,
  SupportQueue,
  SupportQueueConfig,
  type SupportQueueName,
  type SupportQueueEvent,
  type SupportJobType,
} from './support';

// Export Notification constants
export {
  NotificationHttpStatus,
  NotificationHttpStatusMessages,
  NotificationHttpStatusCategories,
  type NotificationHttpStatusCode,
  NotificationRegex,
  NotificationRegexTester,
  NotificationCache,
  NotificationCacheKey,
  NotificationCacheTTL,
  NotificationCacheConfig,
  NotificationQueue,
  NotificationQueueConfig,
  type NotificationQueueName,
  type NotificationQueueEvent,
  type NotificationJobType,
} from './notification';

// Export Content & Marketing constants
export {
  ContentMarketingHttpStatus,
  ContentMarketingHttpStatusMessages,
  ContentMarketingHttpStatusCategories,
  type ContentMarketingHttpStatusCode,
  ContentMarketingRegex,
  ContentMarketingRegexTester,
  ContentMarketingCache,
  ContentMarketingCacheKey,
  ContentMarketingCacheTTL,
  ContentMarketingCacheConfig,
  ContentMarketingQueue,
  ContentMarketingQueueConfig,
  type ContentMarketingQueueName,
  type ContentMarketingQueueEvent,
  type ContentMarketingJobType,
} from './Content-Marketing';

/**
 * Common Constants Exports
 * Export all common constants from a single entry point
 * This file serves as the main entry point for all common constants
 */

// Export Flash Sales & Deals constants
export {
  // HTTP Status
  FlashSalesDealsHttpStatus,
  FlashSalesDealsHttpStatusMessages,
  FlashSalesDealsHttpStatusCategories,
  FlashSalesDealsBusinessErrors,
  FlashSalesDealsBusinessErrorMessages,
  type FlashSalesDealsHttpStatusCode,
  type FlashSalesDealsBusinessErrorCode,
  type FlashSalesDealsHttpStatusCategory,
  isFlashSalesDealsBusinessError,
  getFlashSalesDealsErrorMessage,
  getFlashSalesDealsStatusCategory,

  // Regex
  FlashSalesDealsRegex,
  FlashSalesDealsRegexTester,
  FlashSalesDealsRegexValidation,

  // Cache
  FlashSalesDealsCache,
  FlashSalesDealsCacheKey,
  FlashSalesDealsCacheTTL,
  FlashSalesDealsCacheTTLHelper,
  FlashSalesDealsCacheConfig,
  FlashSalesDealsCachePrefixes,
  FlashSalesDealsCacheDelimiters,
  FlashSalesDealsCacheVersion,
  FlashSalesDealsCacheStrategies,
  FlashSalesDealsCacheEviction,
  FlashSalesDealsCacheEvents,
  FlashSalesDealsCacheBatch,
  FlashSalesDealsCachePagination,
  FlashSalesDealsCacheCompression,
  FlashSalesDealsCacheSerialization,
  FlashSalesDealsCacheIgnorePatterns,
  FlashSalesDealsCacheNoCachePatterns,
  type FlashSalesDealsCachePrefix,
  type FlashSalesDealsCacheDelimiter,
  type FlashSalesDealsCacheStrategy,
  type FlashSalesDealsCacheEvictionPolicy,
  type FlashSalesDealsCacheEvent,

  // Queue
  FlashSalesDealsQueue,
  FlashSalesDealsQueueHelper,
  FlashSalesDealsQueueNames,
  FlashSalesDealsQueuePrefixes,
  FlashSalesDealsQueueConfig,
  FlashSalesDealsJobConfig,
  FlashSalesDealsDeadLetterConfig,
  FlashSalesDealsDelayedConfig,
  FlashSalesDealsScheduledConfig,
  FlashSalesDealsPriorities,
  FlashSalesDealsQueueEvents,
  FlashSalesDealsDeliveryModes,
  FlashSalesDealsExchangeTypes,
  FlashSalesDealsQueueTypes,
  FlashSalesDealsJobTypes,
  FlashSalesDealsRetryConfig,
  FlashSalesDealsConcurrency,
  FlashSalesDealsQueueArguments,
  FlashSalesDealsBatchConfig,
  FlashSalesDealsMetricsConfig,
  FlashSalesDealsMonitoringConfig,
  type FlashSalesDealsQueueName,
  type FlashSalesDealsQueuePrefix,
  type FlashSalesDealsQueueEvent,
  type FlashSalesDealsJobType,
  type FlashSalesDealsPriority,
  type FlashSalesDealsQueueType,
  type FlashSalesDealsExchangeType,
  type FlashSalesDealsDeliveryMode,
  type FlashSalesDealsRetryStrategy,
  type FlashSalesDealsConcurrencyLevel,
} from './Flash-Sales-Deals';

// Export Analytics constants
export {
  AnalyticsHttpStatus,
  AnalyticsHttpStatusMessages,
  AnalyticsHttpStatusCategories,
  AnalyticsHttpStatusDescriptions,
  type AnalyticsHttpStatusCode,
  AnalyticsRegex,
  AnalyticsRegexTester,
  AnalyticsCache,
  AnalyticsCacheKey,
  AnalyticsCacheTTL,
  AnalyticsCacheConfig,
  AnalyticsQueue,
  AnalyticsQueueConfig,
  type AnalyticsQueueName,
  type AnalyticsQueueEvent,
  type AnalyticsJobType,
  type AnalyticsExchangeType,
} from './Analytics';

// Export SEO & AI constants
export {
  SeoAiHttpStatus,
  SeoAiHttpStatusMessage,
  SeoAiHttpStatusGroup,
  type SeoAiHttpStatusCode,
  SeoAiRegex,
  SeoAiRegexTester,
  SeoAiCache,
  SeoAiCacheKey,
  SeoAiCacheTTL,
  SeoAiCacheConfig,
  SeoAiQueue,
  SeoAiQueueConfig,
  type SeoAiQueueName,
  type SeoAiQueueEvent,
  type SeoAiJobType,
  type SeoAiJobStatus,
} from './seo-ai';

// Export Auth constants
export {
  AuthHttpStatus,
  AuthHttpStatusMessages,
  AuthHttpStatusCategories,
  AuthHttpStatusHelpers,
  type AuthHttpStatusCode,
  type AuthHttpStatusCategory,
  AuthRegex,
  AuthRegexDescriptions,
  AuthRegexValidationMessages,
  AuthRegexTester,
  AuthCache,
  AuthCacheKey,
  AuthCacheTTL,
  AuthCacheConfig,
  AuthCacheEvent,
  AuthQueue,
  AuthQueueConfig,
  AuthQueueValidator,
  type AuthQueueName,
  type AuthQueueEvent,
  type AuthJobType,
  type AuthQueueType,
} from './auth';

// Export Admin constants
export {
  // HTTP Status
  adminHTTP_STATUS,
  adminHTTP_STATUS_NAMES,
  adminHTTP_STATUS_CATEGORIES,
  adminHTTP_STATUS_CATEGORY_MAP,
  adminHTTP_STATUS_DESCRIPTIONS,
  adminHTTP_STATUS_DEFAULT_MESSAGES,
  adminHTTP_STATUS_GROUPS,
  adminHTTP_STATUS_COLORS,
  adminHTTP_STATUS_ICONS,

  // Regex
  REGEX_EMAIL,
  REGEX_PHONE,
  REGEX_PASSWORD,
  REGEX_URL,
  REGEX_USERNAME,
  REGEX_ALPHANUMERIC,
  REGEX_DATE,
  REGEX_TIME,
  REGEX_IP_ADDRESS,
  REGEX_UUID,
  REGEX_STRIP_HTML,
  REGEX_EXTRACT_EMAIL,
  REGEX_PHONE_FORMAT,
  REGEX_HEX_COLOR,
  REGEX_SLUG,
  REGEX_DOMAIN,
  REGEX_ARTIST_NAME,
  REGEX_TRACK_TITLE,
  REGEX_BOOLEAN,
  REGEX_NUMBER,
  REGEX_DECIMAL,
  REGEX_ALPHA,
  REGEX_ALPHA_SPACE,
  REGEX_POSTAL_CODE,
  REGEX_CREDIT_CARD,
  REGEX_CSV,
  REGEX_JSON,
  REGEX_BASE64,
  REGEX_MD5,
  REGEX_SHA1,
  REGEX_SHA256,
  REGEX_JWT,
  REGEX_MAC_ADDRESS,
  REGEX_SEMVER,

  // Cache
  CACHE_TYPES,
  DEFAULT_CACHE_TIMEOUT,
  CACHE_CLEANUP_INTERVAL,
  CACHE_MAX_SIZE,
  CACHE_KEY_PREFIX,
  CACHE_TAGS,
  CACHE_STRATEGIES,
  CACHE_EVICTION_POLICIES,
  CACHE_BATCH_SIZE,
  CACHE_RATE_LIMIT,
  CACHE_RETRY_LIMIT,
  CACHE_RETRY_DELAY,
  CACHE_COMPRESSION_THRESHOLD,
  CACHE_DEFAULT_TTL,
  CACHE_KEY_PATTERNS,
  CACHE_MONITORING,
  CACHE_ENCRYPTION,
  CACHE_READ_THROUGH,
  CACHE_WRITE_BEHIND,

  // Queue
  QUEUE_TYPES,
  DEFAULT_QUEUE_DELAY,
  DEFAULT_QUEUE_RETRY_LIMIT,
  QUEUE_CONCURRENCY_LIMIT,
  DEFAULT_QUEUE_TIMEOUT,
  QUEUE_PRIORITY_LEVELS,
  QUEUE_DEAD_LETTER_EXCHANGE,
  QUEUE_DEAD_LETTER_ROUTING_KEY,
  QUEUE_RETRY_DELAY,
  QUEUE_CLEANUP_INTERVAL,
  QUEUE_MONITORING_INTERVAL,
  QUEUE_BATCH_PROCESSING_SIZE,
  QUEUE_NAMES,
  QUEUE_DELIVERY_MODES,
  QUEUE_EXCHANGE_TYPES,
  QUEUE_PREFETCH_COUNT,
  QUEUE_MAX_MESSAGE_SIZE,
  QUEUE_TIMEOUT_SETTINGS,
  QUEUE_RECONNECT,
  QUEUE_MONITORING,
  QUEUE_ENCRYPTION,
  QUEUE_ACKNOWLEDGMENT_MODES,
  QUEUE_MESSAGE_TYPES,
} from './admin';
