/**
 * Message Constants
 * @module shared-constants/common/message.constants
 */

export const MESSAGE = {
  // Success messages
  SUCCESS: {
    CREATED: 'Resource created successfully',
    UPDATED: 'Resource updated successfully',
    DELETED: 'Resource deleted successfully',
    FETCHED: 'Resource fetched successfully',
    LOGIN_SUCCESS: 'Login successful',
    LOGOUT_SUCCESS: 'Logout successful',
    REGISTRATION_SUCCESS: 'Registration successful',
    VERIFICATION_SUCCESS: 'Verification successful',
    PASSWORD_RESET_SUCCESS: 'Password reset successful',
    PASSWORD_CHANGE_SUCCESS: 'Password changed successfully',
    EMAIL_SENT: 'Email sent successfully',
    SMS_SENT: 'SMS sent successfully',
    UPLOAD_SUCCESS: 'File uploaded successfully',
    DOWNLOAD_SUCCESS: 'File downloaded successfully',
    PAYMENT_SUCCESS: 'Payment successful',
    ORDER_SUCCESS: 'Order placed successfully',
    SHIPMENT_SUCCESS: 'Shipment processed successfully',
    REFUND_SUCCESS: 'Refund processed successfully',
    REVIEW_SUCCESS: 'Review submitted successfully',
    SUBSCRIPTION_SUCCESS: 'Subscription successful',
    CONTACT_SUCCESS: 'Contact form submitted successfully',
    FEEDBACK_SUCCESS: 'Feedback submitted successfully',
  },

  // Error messages
  ERROR: {
    NOT_FOUND: 'Resource not found',
    BAD_REQUEST: 'Bad request',
    UNAUTHORIZED: 'Unauthorized access',
    FORBIDDEN: 'Forbidden access',
    INTERNAL_ERROR: 'Internal server error',
    SERVICE_UNAVAILABLE: 'Service unavailable',
    VALIDATION_ERROR: 'Validation error',
    DUPLICATE_ENTRY: 'Duplicate entry found',
    INVALID_CREDENTIALS: 'Invalid credentials',
    ACCOUNT_LOCKED: 'Account locked',
    ACCOUNT_DISABLED: 'Account disabled',
    ACCOUNT_EXPIRED: 'Account expired',
    TOKEN_EXPIRED: 'Token expired',
    TOKEN_INVALID: 'Invalid token',
    TOKEN_MISSING: 'Missing token',
    REFRESH_TOKEN_INVALID: 'Invalid refresh token',
    REFRESH_TOKEN_EXPIRED: 'Refresh token expired',
    PASSWORD_MISMATCH: 'Password mismatch',
    PASSWORD_WEAK: 'Password too weak',
    EMAIL_TAKEN: 'Email already taken',
    PHONE_TAKEN: 'Phone number already taken',
    USERNAME_TAKEN: 'Username already taken',
    INSUFFICIENT_PERMISSIONS: 'Insufficient permissions',
    RATE_LIMIT_EXCEEDED: 'Rate limit exceeded',
    REQUEST_TIMEOUT: 'Request timeout',
    PAYMENT_FAILED: 'Payment failed',
    PAYMENT_DECLINED: 'Payment declined',
    INSUFFICIENT_FUNDS: 'Insufficient funds',
    INVENTORY_INSUFFICIENT: 'Insufficient inventory',
    ORDER_CANCELLED: 'Order cancelled',
    ORDER_NOT_FOUND: 'Order not found',
    SHIPPING_FAILED: 'Shipping failed',
    UPLOAD_FAILED: 'Upload failed',
    DOWNLOAD_FAILED: 'Download failed',
    FILE_TOO_LARGE: 'File too large',
    INVALID_FILE_TYPE: 'Invalid file type',
    FILE_CORRUPTED: 'File corrupted',
    INTEGRATION_ERROR: 'Integration error',
    THIRD_PARTY_ERROR: 'Third party error',
    WEBHOOK_FAILED: 'Webhook failed',
    CALLBACK_FAILED: 'Callback failed',
    API_ERROR: 'API error',
    NETWORK_ERROR: 'Network error',
    CONNECTION_ERROR: 'Connection error',
  },

  // Warning messages
  WARNING: {
    SESSION_EXPIRING: 'Session expiring soon',
    SESSION_EXPIRED: 'Session expired',
    PASSWORD_EXPIRING: 'Password expiring soon',
    PASSWORD_EXPIRED: 'Password expired',
    ACCOUNT_INACTIVE: 'Account inactive',
    ACCOUNT_SUSPENDED: 'Account suspended',
    EMAIL_UNVERIFIED: 'Email unverified',
    PHONE_UNVERIFIED: 'Phone unverified',
    KYC_REQUIRED: 'KYC required',
    TWO_FA_REQUIRED: 'Two-factor authentication required',
    DEVICE_UNTRUSTED: 'Untrusted device',
    LOCATION_UNTRUSTED: 'Untrusted location',
  },

  // Info messages
  INFO: {
    WELCOME: 'Welcome to the platform',
    WELCOME_BACK: 'Welcome back',
    ACCOUNT_CREATED: 'Account created successfully',
    ACCOUNT_VERIFIED: 'Account verified successfully',
    PROFILE_COMPLETED: 'Profile completed',
    SETUP_COMPLETED: 'Setup completed',
    ONBOARDING_STARTED: 'Onboarding started',
    ONBOARDING_COMPLETED: 'Onboarding completed',
    TUTORIAL_STARTED: 'Tutorial started',
    TUTORIAL_COMPLETED: 'Tutorial completed',
    HELP_REQUESTED: 'Help requested',
    SUPPORT_CONTACTED: 'Support contacted',
    FEEDBACK_SUBMITTED: 'Feedback submitted',
    SURVEY_COMPLETED: 'Survey completed',
    ACHIEVEMENT_UNLOCKED: 'Achievement unlocked',
    MILESTONE_REACHED: 'Milestone reached',
  },

  // Confirmation messages
  CONFIRMATION: {
    DELETE: 'Are you sure you want to delete this?',
    UPDATE: 'Are you sure you want to update this?',
    CANCEL: 'Are you sure you want to cancel this?',
    LOGOUT: 'Are you sure you want to logout?',
    EXIT: 'Are you sure you want to exit?',
    PAYMENT: 'Are you sure you want to proceed with payment?',
    ORDER: 'Are you sure you want to place this order?',
    SHIPMENT: 'Are you sure you want to process this shipment?',
    REFUND: 'Are you sure you want to process this refund?',
    REJECT: 'Are you sure you want to reject this?',
    APPROVE: 'Are you sure you want to approve this?',
    UNSUBSCRIBE: 'Are you sure you want to unsubscribe?',
    DELETE_ACCOUNT: 'Are you sure you want to delete your account? This action cannot be undone.',
  },

  // Notification messages
  NOTIFICATION: {
    NEW_ORDER: 'New order received',
    ORDER_UPDATE: 'Order status updated',
    ORDER_SHIPPED: 'Order shipped',
    ORDER_DELIVERED: 'Order delivered',
    PAYMENT_RECEIVED: 'Payment received',
    PAYMENT_FAILED: 'Payment failed',
    REFUND_PROCESSED: 'Refund processed',
    PRODUCT_APPROVED: 'Product approved',
    PRODUCT_REJECTED: 'Product rejected',
    NEW_REVIEW: 'New review received',
    NEW_QUESTION: 'New question received',
    NEW_ANSWER: 'New answer received',
    NEW_MESSAGE: 'New message received',
    NEW_FOLLOWER: 'New follower',
    NEW_LIKE: 'New like',
    NEW_COMMENT: 'New comment',
    NEW_MENTION: 'New mention',
    REMINDER: 'Reminder',
    ALERT: 'Alert',
    UPDATE: 'Update',
  },

  // Placeholder messages
  PLACEHOLDER: {
    SEARCH: 'Search...',
    ENTER_EMAIL: 'Enter email address',
    ENTER_PASSWORD: 'Enter password',
    ENTER_USERNAME: 'Enter username',
    ENTER_PHONE: 'Enter phone number',
    ENTER_NAME: 'Enter name',
    ENTER_MESSAGE: 'Enter message',
    ENTER_COMMENT: 'Enter comment',
    ENTER_ADDRESS: 'Enter address',
    ENTER_CITY: 'Enter city',
    ENTER_STATE: 'Enter state',
    ENTER_ZIP: 'Enter zip code',
    ENTER_COUNTRY: 'Enter country',
    SELECT_OPTION: 'Select option',
    SELECT_DATE: 'Select date',
    SELECT_TIME: 'Select time',
    SELECT_CATEGORY: 'Select category',
    SELECT_PRODUCT: 'Select product',
    TYPE_TO_SEARCH: 'Type to search...',
    NO_RESULTS: 'No results found',
    LOADING: 'Loading...',
    UPLOADING: 'Uploading...',
    PROCESSING: 'Processing...',
  },
} as const;

export type MessageCategory = keyof typeof MESSAGE;
export type SuccessMessage = keyof typeof MESSAGE.SUCCESS;
export type ErrorMessage = keyof typeof MESSAGE.ERROR;
export type WarningMessage = keyof typeof MESSAGE.WARNING;
export type InfoMessage = keyof typeof MESSAGE.INFO;
export type ConfirmationMessage = keyof typeof MESSAGE.CONFIRMATION;
export type NotificationMessage = keyof typeof MESSAGE.NOTIFICATION;
export type PlaceholderMessage = keyof typeof MESSAGE.PLACEHOLDER;
