/**
 * Shared Schemas - Root Barrel Export
 * Enterprise Grade for vubon.com.bd - Bangladesh's #1 E-commerce
 * 
 * @module shared-schemas/index
 * 
 * @description
 * Central export point for all Zod validation schemas across the monorepo.
 * Organized by domain (Auth, Role, Session) with clear naming to avoid conflicts.
 * 
 * RULES:
 * ✅ ONLY re-exports - NO logic, NO initialization
 * ✅ NO functions, NO side effects
 * ✅ Pure Zod schema exports only
 * ✅ Type-safe with complete type exports
 */

// ============================================================
// 1. Auth Domain Schemas & Types
// ============================================================
export {
  // ---- User Schemas ----
  UserIdSchema,
  UserEmailSchema,
  UserPhoneSchema,
  UserPhoneRequiredSchema,
  UserFirstNameSchema,
  UserLastNameSchema,
  UserDisplayNameSchema,
  UserAvatarSchema,
  UserPasswordSchema,
  UserStrongPasswordSchema,
  UserStatusSchema,
  UserVerificationStatusSchema,
  UserRoleSchema,
  UserTierSchema,
  UserMetadataSchema,
  PasswordSchema,
  
  // ---- User Domain Schemas ----
  UserSchema,
  CreateUserSchema,
  UpdateUserSchema,
  UpdateUserProfileSchema,
  UpdateUserRoleSchema,
  UpdateUserStatusSchema,
  UserFiltersSchema,
  
  // ---- User Response Schemas ----
  UserResponseSchema,
  UserProfileResponseSchema,
  UserListResponseSchema,
  UserActivitySummarySchema,
  UserPreferencesSchema,
  UserErrorSchema,

  // ---- Login Schemas ----
  LoginMethodSchema,
  RememberMeSchema,
  LoginDeviceIdSchema,
  ClientInfoSchema,
  LoginCaptchaTokenSchema,
  EmailLoginSchema,
  PhoneLoginSchema,
  UsernameLoginSchema,
  OtpLoginSchema,
  MfaLoginSchema,
  RefreshTokenRequestSchema,
  LogoutRequestSchema,
  LoginResponseSchema,
  RefreshTokenResponseSchema,
  LogoutResponseSchema,
  LoginErrorSchema,
  MagicLinkRequestSchema,
  MagicLinkVerifySchema,

  // ---- Register Schemas ----
  RegisterEmailSchema,
  RegisterPhoneSchema,
  RegisterPhoneRequiredSchema,
  RegisterFirstNameSchema,
  RegisterLastNameSchema,
  RegisterDisplayNameSchema,
  RegisterPasswordSchema,
  RegisterStrongPasswordSchema,
  UsernameSchema,
  AcceptTermsSchema,
  AcceptPrivacySchema,
  MarketingConsentSchema,
  AgeVerificationSchema,
  ReferralCodeSchema,
  RegisterSchema,
  EmailRegisterSchema,
  PhoneRegisterSchema,
  OTPRegisterSchema,
  SocialRegisterSchema,
  VendorRegisterSchema,
  RegisterResponseSchema,
  EmailVerificationRequiredSchema,
  PhoneVerificationRequiredSchema,
  RegisterErrorSchema,
  UsernameRegisterSchema,
  RegistrationMethodSchema,
  RegistrationMetadataSchema,
  RegistrationRateLimitSchema,

  // ---- MFA Schemas ----
  MFAProviderSchema,
  MFAVerificationTypeSchema,
  MFAStatusSchema,
  OTPCodeSchema,
  BackupCodeSchema,
  MFAMethodIdSchema,
  MFAChallengeIdSchema,
  TOTPSecretSchema,
  WebAuthnChallengeSchema,
  MFASetupRequestSchema,
  MFAVerifyRequestSchema,
  MFARecoveryRequestSchema,
  MFAChallengeRequestSchema,
  DisableMFARequestSchema,
  TOTPSetupRequestSchema,
  WebAuthnRegistrationRequestSchema,
  WebAuthnAuthRequestSchema,
  WhatsAppMFARequestSchema,
  MFSMFARequestSchema,
  MFASetupResponseSchema,
  MFAChallengeResponseSchema,
  MFAVerifyResponseSchema,
  MFARecoveryResponseSchema,
  MFAMethodSchema,
  MFAStatusResponseSchema,
  TOTPSetupResponseSchema,
  WebAuthnRegistrationResponseSchema,
  WebAuthnAuthResponseSchema,

  // ---- Verification Schemas ----
  VerificationTypeSchema,
  VerificationStatusSchema,
  VerificationMethodSchema,
  VerificationCodeSchema,
  VerificationUserIdSchema,
  SessionIdSchema as VerificationSessionIdSchema,
  SendVerificationSchema,
  VerifyEmailSchema,
  VerifyCodeSchema,
  ResendVerificationSchema,
  VerificationMagicLinkRequestSchema,
  VerificationMagicLinkVerifySchema,
  EmailChangeRequestSchema,
  EmailChangeVerifySchema,
  PhoneChangeRequestSchema,
  PhoneChangeVerifySchema,
  SendOTPRequestSchema,
  ResendOTPRequestSchema,
  WhatsAppVerificationSchema,
  VoiceVerificationSchema,
  VerificationResponseSchema,
  ResendVerificationResponseSchema,
  VerificationStatusResponseSchema,
  MagicLinkResponseSchema,
  MagicLinkVerifyResponseSchema,
  SendOTPResponseSchema,
  EmailChangeResponseSchema,
  PhoneChangeResponseSchema,
  WhatsAppVerificationResponseSchema,
  VoiceVerificationResponseSchema,
  VerificationErrorSchema,

  // ---- Password Reset Schemas ----
  ResetEmailSchema,
  ResetPhoneSchema,
  ResetPasswordSchema,
  ResetPasswordStrengthSchema,
  ResetVerificationTokenSchema,
  ResetUserIdSchema,
  ResetSessionIdSchema,
  ResetCaptchaTokenSchema,
  ForgotPasswordSchema,
  ForgotPasswordPhoneSchema,
  ResetPasswordRequestSchema,
  StrongResetPasswordRequestSchema,
  ValidateResetTokenSchema,
  RequestResetOTPSchema,
  VerifyResetOTPSchema,
  ForgotPasswordResponseSchema,
  ForgotPasswordPhoneResponseSchema,
  ResetPasswordResponseSchema,
  TokenValidationResponseSchema,
  RequestResetOTPResponseSchema,
  VerifyResetOTPResponseSchema,
  PasswordResetErrorSchema,

  // ---- Social Auth Schemas ----
  SocialProviderSchema,
  OAuthStateSchema,
  OAuthCodeSchema,
  OAuthScopeSchema,
  RedirectUriSchema,
  PKCECodeVerifierSchema,
  PKCECodeChallengeSchema,
  GoogleOAuthDataSchema,
  FacebookOAuthDataSchema,
  GitHubOAuthDataSchema,
  AppleOAuthDataSchema,
  WhatsAppOAuthDataSchema,
  BkashOAuthDataSchema,
  NagadOAuthDataSchema,
  RocketOAuthDataSchema,
  SocialLoginRequestSchema,
  SocialLoginResponseSchema,
  SocialCallbackSchema,
  SocialConnectRequestSchema,
  SocialDisconnectRequestSchema,
  SocialOTPRequestSchema,
  SocialOTPVerificationSchema,
  MFSAuthRequestSchema,
  SocialUserInfoSchema,
  SocialCallbackResponseSchema,
  SocialAccountSchema,
  SocialAccountsResponseSchema,
  SocialOTPResponseSchema,
  MFSAuthResponseSchema,
  SocialAuthErrorSchema,

  // ---- Email Schemas ----
  EmailSchema,
  StrictEmailSchema,
  BangladeshEmailSchema,
  EducationalEmailSchema,
  GovernmentEmailSchema,
  CorporateEmailSchema,
  EmailWithSubaddressSchema,
  LoginEmailSchema,
  RegistrationEmailSchema,
  ProfessionalEmailSchema,
  BangladeshPhoneSchema,
  getEmailCategory,
  isValidEmail,
  isFreeEmail,
  isDisposableEmail,
  isBangladeshEmail,
  isEducationalEmail,
  isGovernmentEmail,
  normalizeEmail,
  maskEmail,

  // ---- Phone Schemas ----
  BasePhoneSchema,
  PhoneSchema,
  LenientPhoneSchema,
  PhoneWithOperatorSchema,
  PhoneWithTypeSchema,
  PhoneVerificationRequestSchema,
  PhoneVerificationResponseSchema,
  PhoneListSchema,
  PhoneListWithOperatorSchema,
  MFAPhoneSchema,
  WhatsAppPhoneSchema,
  VoiceCallPhoneSchema,
  PhoneComponentsSchema,
  PhoneErrorSchema,
  isValidBangladeshMobile,
  getBangladeshOperator,
  normalizeBangladeshPhone,
  maskPhoneNumber,
} from './auth';



// ============================================================
// 2. Role & Permission Domain Schemas & Types
// ============================================================
export {
  // ---- Permission Schemas ----
  PermissionResourceSchema,
  PermissionActionSchema,
  PermissionStringSchema,
  PermissionIdSchema,
  RoleIdSchema as PermissionRoleIdSchema,
  UserIdSchema as PermissionUserIdSchema,
  PermissionSchema,
  PermissionGroupSchema,
  RolePermissionAssignmentSchema,
  CheckPermissionSchema,
  BulkCheckPermissionSchema,
  GrantPermissionSchema,
  RevokePermissionSchema,
  CreatePermissionSchema,
  UpdatePermissionSchema,
  DeletePermissionSchema,
  PermissionSyncSchema,
  PermissionFilterSchema,
  PermissionCheckResponseSchema,
  BulkPermissionCheckResponseSchema,
  UserPermissionsResponseSchema,
  PermissionListResponseSchema,
  PermissionSyncResponseSchema,
  PermissionStatisticsResponseSchema,
  PermissionErrorSchema,
  createPermissionString,
  parsePermissionString,

  // ---- Role Schemas ----
  RoleNameSchema,
  RoleIdSchema as RoleIdSchemaAlias,
  RoleCategorySchema,
  RoleColorSchema,
  RoleMetadataSchema,
  RoleSchema,
  RoleInheritanceSchema,
  CreateRoleSchema,
  UpdateRoleSchema,
  DeleteRoleSchema,
  AssignRoleSchema,
  RemoveRoleSchema,
  BulkAssignRoleSchema,
  BulkRemoveRoleSchema,
  RoleFilterSchema,
  RoleResponseSchema,
  RoleListResponseSchema,
  UserRolesResponseSchema,
  AssignRoleResponseSchema,
  BulkAssignRoleResponseSchema,
  RoleHierarchyCheckResponseSchema,
  RoleStatisticsResponseSchema,
  RoleErrorSchema,
} from './role';

// ---- Role & Permission Type Exports ----
export type {
  // Permission Types
  PermissionResource,
  PermissionAction,
  PermissionString,
  PermissionId,
  PermissionRoleId,
  PermissionUserId,
  Permission,
  PermissionGroup,
  RolePermissionAssignment,
  CheckPermissionRequest,
  BulkCheckPermissionRequest,
  GrantPermissionRequest,
  RevokePermissionRequest,
  CreatePermissionRequest,
  UpdatePermissionRequest,
  DeletePermissionRequest,
  PermissionSyncRequest,
  PermissionFilterRequest,
  PermissionCheckResponse,
  BulkPermissionCheckResponse,
  UserPermissionsResponse,
  PermissionListResponse,
  PermissionSyncResponse,
  PermissionStatisticsResponse,
  PermissionError,
  PermissionTreeNode,

  // Role Types
  RoleName,
  RoleId,
  RoleCategory,
  RoleColor,
  RoleMetadata,
  Role,
  RoleInheritance,
  CreateRoleRequest,
  UpdateRoleRequest,
  DeleteRoleRequest,
  AssignRoleRequest,
  RemoveRoleRequest,
  BulkAssignRoleRequest,
  BulkRemoveRoleRequest,
  RoleFilterRequest,
  RoleResponse,
  RoleListResponse,
  UserRolesResponse,
  AssignRoleResponse,
  BulkAssignRoleResponse,
  RoleHierarchyCheckResponse,
  RoleStatisticsResponse,
  RoleError,

  // Cross-Domain Types
  RolePermissionString,
  RolePermissionId,
  RoleDefinitionId,
} from './role';

// ============================================================
// 3. Session & Device Domain Schemas & Types
// (Renamed to avoid conflicts with Auth domain)
// ============================================================
export {
  // ---- Device Schemas ----
  DeviceIdSchema,
  DeviceTypeSchema,
  OSTypeSchema,
  BrowserTypeSchema,
  DeviceTrustLevelSchema,
  NetworkTypeSchema,
  MobileOperatorSchema,
  DeviceInfoSchema,
  DeviceFingerprintSchema,
  TrustedDeviceSchema,
  DeviceRiskAssessmentSchema,
  DeviceActivitySchema,
  RegisterDeviceSchema,
  UpdateDeviceTrustSchema,
  RemoveDeviceSchema,
  DeviceSessionTransferSchema,
  DevicePairingSchema,
  DeviceUnpairSchema,
  DeviceFilterSchema,
  DeviceResponseSchema,
  DeviceListResponseSchema,
  DeviceSessionTransferResponseSchema,
  DevicePairingResponseSchema,
  DeviceStatisticsResponseSchema,
  DeviceErrorSchema,

  // ---- Session Schemas (Renamed) ----
  SessionIdSchema as SessionDocumentIdSchema,
  RefreshTokenSchema,
  AccessTokenSchema,
  TokenIdSchema,
  UserIdSchema as SessionUserIdSchema,
  SessionStatusSchema,
  SessionTrustLevelSchema,
  NetworkTypeSchema as SessionNetworkTypeSchema,
  MobileOperatorSchema as SessionMobileOperatorSchema,
  LocationInfoSchema,
  SessionTokensSchema,
  SessionSchema,
  CreateSessionSchema,
  RefreshSessionSchema,
  TerminateSessionSchema,
  TerminateSessionsSchema,
  ValidateSessionSchema,
  SessionHeartbeatSchema,
  SessionTransferRequestSchema,
  SessionFilterSchema,
  SessionCleanupRequestSchema,
  CreateSessionResponseSchema,
  RefreshSessionResponseSchema,
  TerminateSessionsResponseSchema,
  SessionValidationResponseSchema,
  SessionHeartbeatResponseSchema,
  SessionTransferResponseSchema,
  SessionListResponseSchema,
  SessionStatisticsResponseSchema,
  SessionCleanupResponseSchema,
  SessionErrorSchema,
} from './session';

// ---- Session & Device Type Exports ----
export type {
  // Device Types
  DeviceId,
  DeviceType,
  OSType,
  BrowserType,
  DeviceTrustLevel,
  DeviceNetworkType,
  MobileOperator,
  DeviceInfo,
  DeviceFingerprint,
  TrustedDevice,
  DeviceRiskAssessment,
  DeviceActivity,
  RegisterDeviceRequest,
  UpdateDeviceTrustRequest,
  RemoveDeviceRequest,
  DeviceSessionTransferRequest,
  DevicePairingRequest,
  DeviceUnpairRequest,
  DeviceFilterRequest,
  DeviceResponse,
  DeviceListResponse,
  DeviceSessionTransferResponse,
  DevicePairingResponse,
  DeviceStatisticsResponse,
  DeviceError,
  DeviceRegistrationFormData,
  DeviceTrustFormData,
  DevicePairingFormData,

  // Session Types
  SessionId,
  RefreshToken,
  AccessToken,
  TokenId,
  SessionUserId,
  SessionStatus,
  SessionTrustLevel,
  SessionNetworkType,
  SessionMobileOperator,
  LocationInfo,
  SessionTokens,
  Session,
  CreateSessionRequest,
  CreateSessionResponse,
  RefreshSessionRequest,
  RefreshSessionResponse,
  TerminateSessionRequest,
  TerminateSessionsRequest,
  TerminateSessionsResponse,
  ValidateSessionRequest,
  SessionValidationResponse,
  SessionHeartbeatRequest,
  SessionHeartbeatResponse,
  SessionTransferRequest,
  SessionTransferResponse,
  SessionFilterRequest,
  SessionListResponse,
  SessionStatisticsResponse,
  SessionCleanupRequest,
  SessionCleanupResponse,
  SessionError,

  // Cross-Domain Types
  SessionDeviceInfo,
  SessionDeviceType,
  SessionDeviceTrustLevel,
  SessionNetwork,
  SessionMobileOperatorType,
} from './session';
