export const SECURITY = {
  BCRYPT_ROUNDS: 12,
  BCRYPT_MIN_ROUNDS: 10,
  BCRYPT_MAX_ROUNDS: 15,

  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,
  PASSWORD_REQUIRE_UPPERCASE: true,
  PASSWORD_REQUIRE_LOWERCASE: true,
  PASSWORD_REQUIRE_NUMBER: true,
  PASSWORD_REQUIRE_SYMBOL: true,
  PASSWORD_HISTORY_COUNT: 5,
  PASSWORD_EXPIRY_DAYS: 90,

  JWT_ACCESS_EXPIRY: '15m',
  JWT_REFRESH_EXPIRY: '7d',
  JWT_ALGORITHM: 'HS256',
  JWT_ISSUER: 'shared-constants',

  RATE_LIMIT_WINDOW_SECONDS: 60,
  RATE_LIMIT_MAX_REQUESTS: 60,
  RATE_LIMIT_AUTH_MAX: 5,
  RATE_LIMIT_OTP_MAX: 3,
  RATE_LIMIT_API_MAX: 100,

  CSRF_TOKEN_LENGTH: 32,
  CSRF_HEADER_NAME: 'x-csrf-token',

  CORS_MAX_AGE_SECONDS: 86400,
  HELMET_ENABLED: true,
  HSTS_MAX_AGE_SECONDS: 31536000,

  ENCRYPTION_ALGORITHM: 'aes-256-gcm',
  ENCRYPTION_IV_LENGTH: 16,
  ENCRYPTION_SALT_LENGTH: 32,
  ENCRYPTION_KEY_LENGTH: 32,

  MAX_LOGIN_ATTEMPTS: 5,
  LOCKOUT_DURATION_SECONDS: 900,
} as const;

export const SECURITY_HEADER = {
  X_FRAME_OPTIONS: 'X-Frame-Options',
  X_CONTENT_TYPE_OPTIONS: 'X-Content-Type-Options',
  X_XSS_PROTECTION: 'X-XSS-Protection',
  STRICT_TRANSPORT_SECURITY: 'Strict-Transport-Security',
  CONTENT_SECURITY_POLICY: 'Content-Security-Policy',
  REFERRER_POLICY: 'Referrer-Policy',
  PERMISSIONS_POLICY: 'Permissions-Policy',
} as const;

export type SecurityType = typeof SECURITY;
