/**
 * Admin Verification Constants
 * Admin verification and validation definitions
 */

export const ADMIN_VERIFICATION = {
  // Verification types
  TYPES: {
    EMAIL: 'email',
    PHONE: 'phone',
    IDENTITY: 'identity',
    ADDRESS: 'address',
    BANK: 'bank',
    DOCUMENT: 'document',
    FACE: 'face',
    FINGERPRINT: 'fingerprint',
    VOICE: 'voice',
    TWO_FA: 'two_fa',
    DEVICE: 'device',
    LOCATION: 'location',
    IP: 'ip',
    SOCIAL: 'social',
    PROFESSIONAL: 'professional',
    ACADEMIC: 'academic',
    GOVERNMENT: 'government',
    BIOMETRIC: 'biometric',
    BEHAVIORAL: 'behavioral',
    KNOWLEDGE: 'knowledge',
    POSSESSION: 'possession',
    INHERENT: 'inherent',
  },

  // Verification statuses
  STATUSES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    VERIFIED: 'verified',
    REJECTED: 'rejected',
    FAILED: 'failed',
    EXPIRED: 'expired',
    CANCELLED: 'cancelled',
    SUSPENDED: 'suspended',
    REVIEWING: 'reviewing',
    APPROVED: 'approved',
    INCOMPLETE: 'incomplete',
    SKIPPED: 'skipped',
    TIMEOUT: 'timeout',
    ERROR: 'error',
  },

  // Verification methods
  METHODS: {
    OTP: 'otp',
    SMS: 'sms',
    EMAIL_LINK: 'email_link',
    QR_CODE: 'qr_code',
    NFC: 'nfc',
    BLUETOOTH: 'bluetooth',
    FACE_SCAN: 'face_scan',
    FINGER_SCAN: 'finger_scan',
    VOICE_RECOGNITION: 'voice_recognition',
    DOCUMENT_SCAN: 'document_scan',
    VIDEO_CALL: 'video_call',
    SECURITY_QUESTIONS: 'security_questions',
    KNOWLEDGE_BASED: 'knowledge_based',
    THIRD_PARTY: 'third_party',
    SOCIAL_LOGIN: 'social_login',
    PHYSICAL_TOKEN: 'physical_token',
    DIGITAL_TOKEN: 'digital_token',
    CERTIFICATE: 'certificate',
    BIOMETRIC: 'biometric',
    BEHAVIORAL: 'behavioral',
  },

  // Verification levels
  LEVELS: {
    BASIC: 'basic',
    STANDARD: 'standard',
    ENHANCED: 'enhanced',
    HIGH: 'high',
    MAXIMUM: 'maximum',
  },

  // Verification purposes
  PURPOSES: {
    REGISTRATION: 'registration',
    LOGIN: 'login',
    PASSWORD_RESET: 'password_reset',
    TRANSACTION: 'transaction',
    KYC: 'kyc',
    AML: 'aml',
    COMPLIANCE: 'compliance',
    AUDIT: 'audit',
    SUPPORT: 'support',
    ESCALATION: 'escalation',
  },

  // Verification channels
  CHANNELS: {
    EMAIL: 'email',
    SMS: 'sms',
    PUSH: 'push',
    IN_APP: 'in_app',
    WEB: 'web',
    API: 'api',
    CALL: 'call',
    VIDEO: 'video',
    IN_PERSON: 'in_person',
    MAIL: 'mail',
    FAX: 'fax',
  },

  // Verification limits
  LIMITS: {
    MAX_ATTEMPTS: 3,
    MAX_RESEND: 5,
    OTP_EXPIRY: 300, // 5 minutes
    CODE_LENGTH: 6,
    SESSION_TIMEOUT: 900, // 15 minutes
    MAX_PENDING: 10,
  },

  // Verification tokens
  TOKENS: {
    LENGTH: 32,
    EXPIRY: 3600, // 1 hour
    REFRESH_EXPIRY: 86400, // 24 hours
  },
} as const;

export type AdminVerificationType =
  (typeof ADMIN_VERIFICATION.TYPES)[keyof typeof ADMIN_VERIFICATION.TYPES];
export type AdminVerificationStatus =
  (typeof ADMIN_VERIFICATION.STATUSES)[keyof typeof ADMIN_VERIFICATION.STATUSES];
export type AdminVerificationMethod =
  (typeof ADMIN_VERIFICATION.METHODS)[keyof typeof ADMIN_VERIFICATION.METHODS];
export type AdminVerificationLevel =
  (typeof ADMIN_VERIFICATION.LEVELS)[keyof typeof ADMIN_VERIFICATION.LEVELS];
export type AdminVerificationPurpose =
  (typeof ADMIN_VERIFICATION.PURPOSES)[keyof typeof ADMIN_VERIFICATION.PURPOSES];
export type AdminVerificationChannel =
  (typeof ADMIN_VERIFICATION.CHANNELS)[keyof typeof ADMIN_VERIFICATION.CHANNELS];

// ... (লেবেল অবজেক্টগুলো আগের মতোই থাকবে, শুধু ফাংশনের নাম পরিবর্তন করা হবে)

export const ADMIN_VERIFICATION_TYPE_LABELS: Record<AdminVerificationType, string> = {
  [ADMIN_VERIFICATION.TYPES.EMAIL]: 'Email Verification',
  [ADMIN_VERIFICATION.TYPES.PHONE]: 'Phone Verification',
  [ADMIN_VERIFICATION.TYPES.IDENTITY]: 'Identity Verification',
  [ADMIN_VERIFICATION.TYPES.ADDRESS]: 'Address Verification',
  [ADMIN_VERIFICATION.TYPES.BANK]: 'Bank Account Verification',
  [ADMIN_VERIFICATION.TYPES.DOCUMENT]: 'Document Verification',
  [ADMIN_VERIFICATION.TYPES.FACE]: 'Face Recognition',
  [ADMIN_VERIFICATION.TYPES.FINGERPRINT]: 'Fingerprint Verification',
  [ADMIN_VERIFICATION.TYPES.VOICE]: 'Voice Recognition',
  [ADMIN_VERIFICATION.TYPES.TWO_FA]: 'Two-Factor Authentication',
  [ADMIN_VERIFICATION.TYPES.DEVICE]: 'Device Verification',
  [ADMIN_VERIFICATION.TYPES.LOCATION]: 'Location Verification',
  [ADMIN_VERIFICATION.TYPES.IP]: 'IP Address Verification',
  [ADMIN_VERIFICATION.TYPES.SOCIAL]: 'Social Media Verification',
  [ADMIN_VERIFICATION.TYPES.PROFESSIONAL]: 'Professional Verification',
  [ADMIN_VERIFICATION.TYPES.ACADEMIC]: 'Academic Verification',
  [ADMIN_VERIFICATION.TYPES.GOVERNMENT]: 'Government ID Verification',
  [ADMIN_VERIFICATION.TYPES.BIOMETRIC]: 'Biometric Verification',
  [ADMIN_VERIFICATION.TYPES.BEHAVIORAL]: 'Behavioral Verification',
  [ADMIN_VERIFICATION.TYPES.KNOWLEDGE]: 'Knowledge-based Verification',
  [ADMIN_VERIFICATION.TYPES.POSSESSION]: 'Possession-based Verification',
  [ADMIN_VERIFICATION.TYPES.INHERENT]: 'Inherent Attribute Verification',
};

export const ADMIN_VERIFICATION_TYPE_ICONS: Record<AdminVerificationType, string> = {
  [ADMIN_VERIFICATION.TYPES.EMAIL]: '✉️',
  [ADMIN_VERIFICATION.TYPES.PHONE]: '📱',
  [ADMIN_VERIFICATION.TYPES.IDENTITY]: '🪪',
  [ADMIN_VERIFICATION.TYPES.ADDRESS]: '📍',
  [ADMIN_VERIFICATION.TYPES.BANK]: '🏦',
  [ADMIN_VERIFICATION.TYPES.DOCUMENT]: '📄',
  [ADMIN_VERIFICATION.TYPES.FACE]: '👤',
  [ADMIN_VERIFICATION.TYPES.FINGERPRINT]: '🖐️',
  [ADMIN_VERIFICATION.TYPES.VOICE]: '🎤',
  [ADMIN_VERIFICATION.TYPES.TWO_FA]: '🔐',
  [ADMIN_VERIFICATION.TYPES.DEVICE]: '📱',
  [ADMIN_VERIFICATION.TYPES.LOCATION]: '📍',
  [ADMIN_VERIFICATION.TYPES.IP]: '🌐',
  [ADMIN_VERIFICATION.TYPES.SOCIAL]: '📱',
  [ADMIN_VERIFICATION.TYPES.PROFESSIONAL]: '💼',
  [ADMIN_VERIFICATION.TYPES.ACADEMIC]: '🎓',
  [ADMIN_VERIFICATION.TYPES.GOVERNMENT]: '🪪',
  [ADMIN_VERIFICATION.TYPES.BIOMETRIC]: '🔬',
  [ADMIN_VERIFICATION.TYPES.BEHAVIORAL]: '🧠',
  [ADMIN_VERIFICATION.TYPES.KNOWLEDGE]: '🧠',
  [ADMIN_VERIFICATION.TYPES.POSSESSION]: '🔑',
  [ADMIN_VERIFICATION.TYPES.INHERENT]: '🧬',
};

export const ADMIN_VERIFICATION_STATUS_LABELS: Record<AdminVerificationStatus, string> = {
  [ADMIN_VERIFICATION.STATUSES.PENDING]: 'Pending',
  [ADMIN_VERIFICATION.STATUSES.PROCESSING]: 'Processing',
  [ADMIN_VERIFICATION.STATUSES.VERIFIED]: 'Verified',
  [ADMIN_VERIFICATION.STATUSES.REJECTED]: 'Rejected',
  [ADMIN_VERIFICATION.STATUSES.FAILED]: 'Failed',
  [ADMIN_VERIFICATION.STATUSES.EXPIRED]: 'Expired',
  [ADMIN_VERIFICATION.STATUSES.CANCELLED]: 'Cancelled',
  [ADMIN_VERIFICATION.STATUSES.SUSPENDED]: 'Suspended',
  [ADMIN_VERIFICATION.STATUSES.REVIEWING]: 'Under Review',
  [ADMIN_VERIFICATION.STATUSES.APPROVED]: 'Approved',
  [ADMIN_VERIFICATION.STATUSES.INCOMPLETE]: 'Incomplete',
  [ADMIN_VERIFICATION.STATUSES.SKIPPED]: 'Skipped',
  [ADMIN_VERIFICATION.STATUSES.TIMEOUT]: 'Timeout',
  [ADMIN_VERIFICATION.STATUSES.ERROR]: 'Error',
};

export const ADMIN_VERIFICATION_STATUS_COLORS: Record<AdminVerificationStatus, string> = {
  [ADMIN_VERIFICATION.STATUSES.PENDING]: '#F59E0B',
  [ADMIN_VERIFICATION.STATUSES.PROCESSING]: '#3B82F6',
  [ADMIN_VERIFICATION.STATUSES.VERIFIED]: '#10B981',
  [ADMIN_VERIFICATION.STATUSES.REJECTED]: '#EF4444',
  [ADMIN_VERIFICATION.STATUSES.FAILED]: '#DC2626',
  [ADMIN_VERIFICATION.STATUSES.EXPIRED]: '#9CA3AF',
  [ADMIN_VERIFICATION.STATUSES.CANCELLED]: '#6B7280',
  [ADMIN_VERIFICATION.STATUSES.SUSPENDED]: '#F97316',
  [ADMIN_VERIFICATION.STATUSES.REVIEWING]: '#6366F1',
  [ADMIN_VERIFICATION.STATUSES.APPROVED]: '#34D399',
  [ADMIN_VERIFICATION.STATUSES.INCOMPLETE]: '#FCD34D',
  [ADMIN_VERIFICATION.STATUSES.SKIPPED]: '#9CA3AF',
  [ADMIN_VERIFICATION.STATUSES.TIMEOUT]: '#F97316',
  [ADMIN_VERIFICATION.STATUSES.ERROR]: '#DC2626',
};

export const ADMIN_VERIFICATION_METHOD_LABELS: Record<AdminVerificationMethod, string> = {
  [ADMIN_VERIFICATION.METHODS.OTP]: 'One-Time Password',
  [ADMIN_VERIFICATION.METHODS.SMS]: 'SMS Verification',
  [ADMIN_VERIFICATION.METHODS.EMAIL_LINK]: 'Email Link',
  [ADMIN_VERIFICATION.METHODS.QR_CODE]: 'QR Code',
  [ADMIN_VERIFICATION.METHODS.NFC]: 'NFC',
  [ADMIN_VERIFICATION.METHODS.BLUETOOTH]: 'Bluetooth',
  [ADMIN_VERIFICATION.METHODS.FACE_SCAN]: 'Face Scan',
  [ADMIN_VERIFICATION.METHODS.FINGER_SCAN]: 'Fingerprint Scan',
  [ADMIN_VERIFICATION.METHODS.VOICE_RECOGNITION]: 'Voice Recognition',
  [ADMIN_VERIFICATION.METHODS.DOCUMENT_SCAN]: 'Document Scan',
  [ADMIN_VERIFICATION.METHODS.VIDEO_CALL]: 'Video Call',
  [ADMIN_VERIFICATION.METHODS.SECURITY_QUESTIONS]: 'Security Questions',
  [ADMIN_VERIFICATION.METHODS.KNOWLEDGE_BASED]: 'Knowledge-based',
  [ADMIN_VERIFICATION.METHODS.THIRD_PARTY]: 'Third-party Verification',
  [ADMIN_VERIFICATION.METHODS.SOCIAL_LOGIN]: 'Social Login',
  [ADMIN_VERIFICATION.METHODS.PHYSICAL_TOKEN]: 'Physical Token',
  [ADMIN_VERIFICATION.METHODS.DIGITAL_TOKEN]: 'Digital Token',
  [ADMIN_VERIFICATION.METHODS.CERTIFICATE]: 'Digital Certificate',
  [ADMIN_VERIFICATION.METHODS.BIOMETRIC]: 'Biometric',
  [ADMIN_VERIFICATION.METHODS.BEHAVIORAL]: 'Behavioral Analysis',
};

export const ADMIN_VERIFICATION_LEVEL_LABELS: Record<AdminVerificationLevel, string> = {
  [ADMIN_VERIFICATION.LEVELS.BASIC]: 'Basic',
  [ADMIN_VERIFICATION.LEVELS.STANDARD]: 'Standard',
  [ADMIN_VERIFICATION.LEVELS.ENHANCED]: 'Enhanced',
  [ADMIN_VERIFICATION.LEVELS.HIGH]: 'High',
  [ADMIN_VERIFICATION.LEVELS.MAXIMUM]: 'Maximum',
};

export const ADMIN_VERIFICATION_LEVEL_PRIORITY: Record<AdminVerificationLevel, number> = {
  [ADMIN_VERIFICATION.LEVELS.BASIC]: 1,
  [ADMIN_VERIFICATION.LEVELS.STANDARD]: 2,
  [ADMIN_VERIFICATION.LEVELS.ENHANCED]: 3,
  [ADMIN_VERIFICATION.LEVELS.HIGH]: 4,
  [ADMIN_VERIFICATION.LEVELS.MAXIMUM]: 5,
};

export const ADMIN_VERIFICATION_PURPOSE_LABELS: Record<AdminVerificationPurpose, string> = {
  [ADMIN_VERIFICATION.PURPOSES.REGISTRATION]: 'Registration',
  [ADMIN_VERIFICATION.PURPOSES.LOGIN]: 'Login',
  [ADMIN_VERIFICATION.PURPOSES.PASSWORD_RESET]: 'Password Reset',
  [ADMIN_VERIFICATION.PURPOSES.TRANSACTION]: 'Transaction',
  [ADMIN_VERIFICATION.PURPOSES.KYC]: 'Know Your Customer',
  [ADMIN_VERIFICATION.PURPOSES.AML]: 'Anti-Money Laundering',
  [ADMIN_VERIFICATION.PURPOSES.COMPLIANCE]: 'Compliance',
  [ADMIN_VERIFICATION.PURPOSES.AUDIT]: 'Audit',
  [ADMIN_VERIFICATION.PURPOSES.SUPPORT]: 'Support',
  [ADMIN_VERIFICATION.PURPOSES.ESCALATION]: 'Escalation',
};

export const ADMIN_VERIFICATION_CHANNEL_LABELS: Record<AdminVerificationChannel, string> = {
  [ADMIN_VERIFICATION.CHANNELS.EMAIL]: 'Email',
  [ADMIN_VERIFICATION.CHANNELS.SMS]: 'SMS',
  [ADMIN_VERIFICATION.CHANNELS.PUSH]: 'Push Notification',
  [ADMIN_VERIFICATION.CHANNELS.IN_APP]: 'In-App',
  [ADMIN_VERIFICATION.CHANNELS.WEB]: 'Web',
  [ADMIN_VERIFICATION.CHANNELS.API]: 'API',
  [ADMIN_VERIFICATION.CHANNELS.CALL]: 'Phone Call',
  [ADMIN_VERIFICATION.CHANNELS.VIDEO]: 'Video',
  [ADMIN_VERIFICATION.CHANNELS.IN_PERSON]: 'In Person',
  [ADMIN_VERIFICATION.CHANNELS.MAIL]: 'Mail',
  [ADMIN_VERIFICATION.CHANNELS.FAX]: 'Fax',
};

export function getAdminVerificationTypeLabel(type: AdminVerificationType): string {
  return ADMIN_VERIFICATION_TYPE_LABELS[type] || 'Unknown Type';
}

export function getAdminVerificationTypeIcon(type: AdminVerificationType): string {
  return ADMIN_VERIFICATION_TYPE_ICONS[type] || '❓';
}

export function getAdminVerificationStatusLabel(status: AdminVerificationStatus): string {
  return ADMIN_VERIFICATION_STATUS_LABELS[status] || 'Unknown Status';
}

export function getAdminVerificationStatusColor(status: AdminVerificationStatus): string {
  return ADMIN_VERIFICATION_STATUS_COLORS[status] || '#6B7280';
}

export function getAdminVerificationMethodLabel(method: AdminVerificationMethod): string {
  return ADMIN_VERIFICATION_METHOD_LABELS[method] || 'Unknown Method';
}

export function getAdminVerificationLevelLabel(level: AdminVerificationLevel): string {
  return ADMIN_VERIFICATION_LEVEL_LABELS[level] || 'Unknown Level';
}

export function getAdminVerificationLevelPriority(level: AdminVerificationLevel): number {
  return ADMIN_VERIFICATION_LEVEL_PRIORITY[level] || 0;
}

export function getAdminVerificationPurposeLabel(purpose: AdminVerificationPurpose): string {
  return ADMIN_VERIFICATION_PURPOSE_LABELS[purpose] || 'Unknown Purpose';
}

export function getAdminVerificationChannelLabel(channel: AdminVerificationChannel): string {
  return ADMIN_VERIFICATION_CHANNEL_LABELS[channel] || 'Unknown Channel';
}

// রিনেম করা ফাংশনগুলো (Admin প্রিফিক্স যোগ করা হয়েছে)
export function isAdminVerificationComplete(status: AdminVerificationStatus): boolean {
  return (
    status === ADMIN_VERIFICATION.STATUSES.VERIFIED ||
    status === ADMIN_VERIFICATION.STATUSES.APPROVED
  );
}

export function isAdminVerificationFailed(status: AdminVerificationStatus): boolean {
  return (
    status === ADMIN_VERIFICATION.STATUSES.FAILED ||
    status === ADMIN_VERIFICATION.STATUSES.REJECTED ||
    status === ADMIN_VERIFICATION.STATUSES.ERROR
  );
}

export function isAdminVerificationPending(status: AdminVerificationStatus): boolean {
  return (
    status === ADMIN_VERIFICATION.STATUSES.PENDING ||
    status === ADMIN_VERIFICATION.STATUSES.PROCESSING ||
    status === ADMIN_VERIFICATION.STATUSES.REVIEWING
  );
}

export function isAdminVerificationExpired(status: AdminVerificationStatus): boolean {
  return (
    status === ADMIN_VERIFICATION.STATUSES.EXPIRED || status === ADMIN_VERIFICATION.STATUSES.TIMEOUT
  );
}

export function isAdminVerificationTerminal(status: AdminVerificationStatus): boolean {
  return (
    isAdminVerificationComplete(status) ||
    isAdminVerificationFailed(status) ||
    isAdminVerificationExpired(status) ||
    status === ADMIN_VERIFICATION.STATUSES.CANCELLED ||
    status === ADMIN_VERIFICATION.STATUSES.SKIPPED
  );
}

export function getAdminVerificationLevelForType(
  type: AdminVerificationType
): AdminVerificationLevel {
  const levelMap: Record<AdminVerificationType, AdminVerificationLevel> = {
    [ADMIN_VERIFICATION.TYPES.EMAIL]: ADMIN_VERIFICATION.LEVELS.BASIC,
    [ADMIN_VERIFICATION.TYPES.PHONE]: ADMIN_VERIFICATION.LEVELS.BASIC,
    [ADMIN_VERIFICATION.TYPES.IDENTITY]: ADMIN_VERIFICATION.LEVELS.STANDARD,
    [ADMIN_VERIFICATION.TYPES.ADDRESS]: ADMIN_VERIFICATION.LEVELS.STANDARD,
    [ADMIN_VERIFICATION.TYPES.BANK]: ADMIN_VERIFICATION.LEVELS.ENHANCED,
    [ADMIN_VERIFICATION.TYPES.DOCUMENT]: ADMIN_VERIFICATION.LEVELS.ENHANCED,
    [ADMIN_VERIFICATION.TYPES.FACE]: ADMIN_VERIFICATION.LEVELS.HIGH,
    [ADMIN_VERIFICATION.TYPES.FINGERPRINT]: ADMIN_VERIFICATION.LEVELS.HIGH,
    [ADMIN_VERIFICATION.TYPES.VOICE]: ADMIN_VERIFICATION.LEVELS.HIGH,
    [ADMIN_VERIFICATION.TYPES.TWO_FA]: ADMIN_VERIFICATION.LEVELS.ENHANCED,
    [ADMIN_VERIFICATION.TYPES.DEVICE]: ADMIN_VERIFICATION.LEVELS.STANDARD,
    [ADMIN_VERIFICATION.TYPES.LOCATION]: ADMIN_VERIFICATION.LEVELS.STANDARD,
    [ADMIN_VERIFICATION.TYPES.IP]: ADMIN_VERIFICATION.LEVELS.BASIC,
    [ADMIN_VERIFICATION.TYPES.SOCIAL]: ADMIN_VERIFICATION.LEVELS.BASIC,
    [ADMIN_VERIFICATION.TYPES.PROFESSIONAL]: ADMIN_VERIFICATION.LEVELS.ENHANCED,
    [ADMIN_VERIFICATION.TYPES.ACADEMIC]: ADMIN_VERIFICATION.LEVELS.ENHANCED,
    [ADMIN_VERIFICATION.TYPES.GOVERNMENT]: ADMIN_VERIFICATION.LEVELS.HIGH,
    [ADMIN_VERIFICATION.TYPES.BIOMETRIC]: ADMIN_VERIFICATION.LEVELS.MAXIMUM,
    [ADMIN_VERIFICATION.TYPES.BEHAVIORAL]: ADMIN_VERIFICATION.LEVELS.HIGH,
    [ADMIN_VERIFICATION.TYPES.KNOWLEDGE]: ADMIN_VERIFICATION.LEVELS.STANDARD,
    [ADMIN_VERIFICATION.TYPES.POSSESSION]: ADMIN_VERIFICATION.LEVELS.ENHANCED,
    [ADMIN_VERIFICATION.TYPES.INHERENT]: ADMIN_VERIFICATION.LEVELS.HIGH,
  };
  return levelMap[type] || ADMIN_VERIFICATION.LEVELS.BASIC;
}

export function getAdminVerificationMethodsForType(
  type: AdminVerificationType
): AdminVerificationMethod[] {
  const methodMap: Record<AdminVerificationType, AdminVerificationMethod[]> = {
    [ADMIN_VERIFICATION.TYPES.EMAIL]: [
      ADMIN_VERIFICATION.METHODS.OTP,
      ADMIN_VERIFICATION.METHODS.EMAIL_LINK,
    ],
    [ADMIN_VERIFICATION.TYPES.PHONE]: [
      ADMIN_VERIFICATION.METHODS.OTP,
      ADMIN_VERIFICATION.METHODS.SMS,
    ],
    [ADMIN_VERIFICATION.TYPES.IDENTITY]: [
      ADMIN_VERIFICATION.METHODS.DOCUMENT_SCAN,
      ADMIN_VERIFICATION.METHODS.VIDEO_CALL,
    ],
    [ADMIN_VERIFICATION.TYPES.ADDRESS]: [
      ADMIN_VERIFICATION.METHODS.DOCUMENT_SCAN,
      ADMIN_VERIFICATION.METHODS.THIRD_PARTY,
    ],
    [ADMIN_VERIFICATION.TYPES.BANK]: [
      ADMIN_VERIFICATION.METHODS.THIRD_PARTY,
      ADMIN_VERIFICATION.METHODS.DOCUMENT_SCAN,
    ],
    [ADMIN_VERIFICATION.TYPES.DOCUMENT]: [ADMIN_VERIFICATION.METHODS.DOCUMENT_SCAN],
    [ADMIN_VERIFICATION.TYPES.FACE]: [ADMIN_VERIFICATION.METHODS.FACE_SCAN],
    [ADMIN_VERIFICATION.TYPES.FINGERPRINT]: [ADMIN_VERIFICATION.METHODS.FINGER_SCAN],
    [ADMIN_VERIFICATION.TYPES.VOICE]: [ADMIN_VERIFICATION.METHODS.VOICE_RECOGNITION],
    [ADMIN_VERIFICATION.TYPES.TWO_FA]: [
      ADMIN_VERIFICATION.METHODS.OTP,
      ADMIN_VERIFICATION.METHODS.DIGITAL_TOKEN,
    ],
    [ADMIN_VERIFICATION.TYPES.DEVICE]: [
      ADMIN_VERIFICATION.METHODS.DIGITAL_TOKEN,
      ADMIN_VERIFICATION.METHODS.CERTIFICATE,
    ],
    [ADMIN_VERIFICATION.TYPES.LOCATION]: [ADMIN_VERIFICATION.METHODS.THIRD_PARTY],
    [ADMIN_VERIFICATION.TYPES.IP]: [ADMIN_VERIFICATION.METHODS.THIRD_PARTY],
    [ADMIN_VERIFICATION.TYPES.SOCIAL]: [ADMIN_VERIFICATION.METHODS.SOCIAL_LOGIN],
    [ADMIN_VERIFICATION.TYPES.PROFESSIONAL]: [
      ADMIN_VERIFICATION.METHODS.DOCUMENT_SCAN,
      ADMIN_VERIFICATION.METHODS.THIRD_PARTY,
    ],
    [ADMIN_VERIFICATION.TYPES.ACADEMIC]: [
      ADMIN_VERIFICATION.METHODS.DOCUMENT_SCAN,
      ADMIN_VERIFICATION.METHODS.THIRD_PARTY,
    ],
    [ADMIN_VERIFICATION.TYPES.GOVERNMENT]: [
      ADMIN_VERIFICATION.METHODS.DOCUMENT_SCAN,
      ADMIN_VERIFICATION.METHODS.THIRD_PARTY,
    ],
    [ADMIN_VERIFICATION.TYPES.BIOMETRIC]: [ADMIN_VERIFICATION.METHODS.BIOMETRIC],
    [ADMIN_VERIFICATION.TYPES.BEHAVIORAL]: [ADMIN_VERIFICATION.METHODS.BEHAVIORAL],
    [ADMIN_VERIFICATION.TYPES.KNOWLEDGE]: [
      ADMIN_VERIFICATION.METHODS.KNOWLEDGE_BASED,
      ADMIN_VERIFICATION.METHODS.SECURITY_QUESTIONS,
    ],
    [ADMIN_VERIFICATION.TYPES.POSSESSION]: [
      ADMIN_VERIFICATION.METHODS.PHYSICAL_TOKEN,
      ADMIN_VERIFICATION.METHODS.DIGITAL_TOKEN,
    ],
    [ADMIN_VERIFICATION.TYPES.INHERENT]: [
      ADMIN_VERIFICATION.METHODS.BIOMETRIC,
      ADMIN_VERIFICATION.METHODS.BEHAVIORAL,
    ],
  };
  return methodMap[type] || [];
}
