/**
 * Tracking Event Constants
 * Event definitions for tracking
 */

export const LOGISTICS_TRACKING_EVENT = {
  // Event Types
  TYPES: {
    BOOKED: 'booked',
    PICKED_UP: 'picked_up',
    PROCESSED: 'processed',
    DISPATCHED: 'dispatched',
    IN_TRANSIT: 'in_transit',
    ARRIVED: 'arrived',
    OUT_FOR_DELIVERY: 'out_for_delivery',
    DELIVERED: 'delivered',
    FAILED: 'failed',
    RETURNED: 'returned',
    CANCELLED: 'cancelled',
  } as const,

  // Event Categories
  CATEGORIES: {
    BOOKING: 'booking',
    PICKUP: 'pickup',
    PROCESSING: 'processing',
    TRANSPORT: 'transport',
    DELIVERY: 'delivery',
    EXCEPTION: 'exception',
    RETURN: 'return',
  } as const,

  // Event Severities
  SEVERITIES: {
    INFO: 'info',
    SUCCESS: 'success',
    WARNING: 'warning',
    ERROR: 'error',
  } as const,

  // Event Colors (for UI)
  COLORS: {
    BOOKED: '#blue-400',
    PICKED_UP: '#purple-400',
    PROCESSED: '#blue-500',
    DISPATCHED: '#blue-500',
    IN_TRANSIT: '#orange-400',
    ARRIVED: '#yellow-400',
    OUT_FOR_DELIVERY: '#green-400',
    DELIVERED: '#green-600',
    FAILED: '#red-500',
    RETURNED: '#red-400',
    CANCELLED: '#gray-500',
  } as const,

  // Event Icons (for UI)
  ICONS: {
    BOOKED: '📋',
    PICKED_UP: '📦',
    PROCESSED: '⚙️',
    DISPATCHED: '🚚',
    IN_TRANSIT: '🚛',
    ARRIVED: '📍',
    OUT_FOR_DELIVERY: '🚲',
    DELIVERED: '✅',
    FAILED: '❌',
    RETURNED: '↩️',
    CANCELLED: '🚫',
  } as const,

  // Event Descriptions
  DESCRIPTIONS: {
    BOOKED: 'Shipment has been booked',
    PICKED_UP: 'Shipment has been picked up',
    PROCESSED: 'Shipment is being processed',
    DISPATCHED: 'Shipment has been dispatched',
    IN_TRANSIT: 'Shipment is in transit',
    ARRIVED: 'Shipment has arrived at destination',
    OUT_FOR_DELIVERY: 'Shipment is out for delivery',
    DELIVERED: 'Shipment has been delivered',
    FAILED: 'Delivery attempt failed',
    RETURNED: 'Shipment has been returned',
    CANCELLED: 'Shipment has been cancelled',
  } as const,
} as const;

// Event Types
export type LogisticsTrackingEventType =
  (typeof LOGISTICS_TRACKING_EVENT.TYPES)[keyof typeof LOGISTICS_TRACKING_EVENT.TYPES];

// Event Categories
export type LogisticsTrackingEventCategory =
  (typeof LOGISTICS_TRACKING_EVENT.CATEGORIES)[keyof typeof LOGISTICS_TRACKING_EVENT.CATEGORIES];

// Event Severities
export type LogisticsTrackingEventSeverity =
  (typeof LOGISTICS_TRACKING_EVENT.SEVERITIES)[keyof typeof LOGISTICS_TRACKING_EVENT.SEVERITIES];

// Event Colors
export type LogisticsTrackingEventColor =
  (typeof LOGISTICS_TRACKING_EVENT.COLORS)[keyof typeof LOGISTICS_TRACKING_EVENT.COLORS];

// Event Icons
export type LogisticsTrackingEventIcon =
  (typeof LOGISTICS_TRACKING_EVENT.ICONS)[keyof typeof LOGISTICS_TRACKING_EVENT.ICONS];

// Utility Functions
export function logisticsTrackingEventGetLabel(event: LogisticsTrackingEventType): string {
  const labels: Record<LogisticsTrackingEventType, string> = {
    [LOGISTICS_TRACKING_EVENT.TYPES.BOOKED]: 'Booked',
    [LOGISTICS_TRACKING_EVENT.TYPES.PICKED_UP]: 'Picked Up',
    [LOGISTICS_TRACKING_EVENT.TYPES.PROCESSED]: 'Processed',
    [LOGISTICS_TRACKING_EVENT.TYPES.DISPATCHED]: 'Dispatched',
    [LOGISTICS_TRACKING_EVENT.TYPES.IN_TRANSIT]: 'In Transit',
    [LOGISTICS_TRACKING_EVENT.TYPES.ARRIVED]: 'Arrived',
    [LOGISTICS_TRACKING_EVENT.TYPES.OUT_FOR_DELIVERY]: 'Out for Delivery',
    [LOGISTICS_TRACKING_EVENT.TYPES.DELIVERED]: 'Delivered',
    [LOGISTICS_TRACKING_EVENT.TYPES.FAILED]: 'Failed',
    [LOGISTICS_TRACKING_EVENT.TYPES.RETURNED]: 'Returned',
    [LOGISTICS_TRACKING_EVENT.TYPES.CANCELLED]: 'Cancelled',
  };
  return labels[event] || 'Unknown';
}

export function logisticsTrackingEventGetCategory(
  event: LogisticsTrackingEventType
): LogisticsTrackingEventCategory {
  const categories: Record<LogisticsTrackingEventType, LogisticsTrackingEventCategory> = {
    [LOGISTICS_TRACKING_EVENT.TYPES.BOOKED]: LOGISTICS_TRACKING_EVENT.CATEGORIES.BOOKING,
    [LOGISTICS_TRACKING_EVENT.TYPES.PICKED_UP]: LOGISTICS_TRACKING_EVENT.CATEGORIES.PICKUP,
    [LOGISTICS_TRACKING_EVENT.TYPES.PROCESSED]: LOGISTICS_TRACKING_EVENT.CATEGORIES.PROCESSING,
    [LOGISTICS_TRACKING_EVENT.TYPES.DISPATCHED]: LOGISTICS_TRACKING_EVENT.CATEGORIES.TRANSPORT,
    [LOGISTICS_TRACKING_EVENT.TYPES.IN_TRANSIT]: LOGISTICS_TRACKING_EVENT.CATEGORIES.TRANSPORT,
    [LOGISTICS_TRACKING_EVENT.TYPES.ARRIVED]: LOGISTICS_TRACKING_EVENT.CATEGORIES.TRANSPORT,
    [LOGISTICS_TRACKING_EVENT.TYPES.OUT_FOR_DELIVERY]: LOGISTICS_TRACKING_EVENT.CATEGORIES.DELIVERY,
    [LOGISTICS_TRACKING_EVENT.TYPES.DELIVERED]: LOGISTICS_TRACKING_EVENT.CATEGORIES.DELIVERY,
    [LOGISTICS_TRACKING_EVENT.TYPES.FAILED]: LOGISTICS_TRACKING_EVENT.CATEGORIES.EXCEPTION,
    [LOGISTICS_TRACKING_EVENT.TYPES.RETURNED]: LOGISTICS_TRACKING_EVENT.CATEGORIES.RETURN,
    [LOGISTICS_TRACKING_EVENT.TYPES.CANCELLED]: LOGISTICS_TRACKING_EVENT.CATEGORIES.EXCEPTION,
  };
  return categories[event] || LOGISTICS_TRACKING_EVENT.CATEGORIES.PROCESSING;
}

export function logisticsTrackingEventGetSeverity(
  event: LogisticsTrackingEventType
): LogisticsTrackingEventSeverity {
  const severities: Record<LogisticsTrackingEventType, LogisticsTrackingEventSeverity> = {
    [LOGISTICS_TRACKING_EVENT.TYPES.BOOKED]: LOGISTICS_TRACKING_EVENT.SEVERITIES.INFO,
    [LOGISTICS_TRACKING_EVENT.TYPES.PICKED_UP]: LOGISTICS_TRACKING_EVENT.SEVERITIES.SUCCESS,
    [LOGISTICS_TRACKING_EVENT.TYPES.PROCESSED]: LOGISTICS_TRACKING_EVENT.SEVERITIES.INFO,
    [LOGISTICS_TRACKING_EVENT.TYPES.DISPATCHED]: LOGISTICS_TRACKING_EVENT.SEVERITIES.INFO,
    [LOGISTICS_TRACKING_EVENT.TYPES.IN_TRANSIT]: LOGISTICS_TRACKING_EVENT.SEVERITIES.INFO,
    [LOGISTICS_TRACKING_EVENT.TYPES.ARRIVED]: LOGISTICS_TRACKING_EVENT.SEVERITIES.INFO,
    [LOGISTICS_TRACKING_EVENT.TYPES.OUT_FOR_DELIVERY]: LOGISTICS_TRACKING_EVENT.SEVERITIES.INFO,
    [LOGISTICS_TRACKING_EVENT.TYPES.DELIVERED]: LOGISTICS_TRACKING_EVENT.SEVERITIES.SUCCESS,
    [LOGISTICS_TRACKING_EVENT.TYPES.FAILED]: LOGISTICS_TRACKING_EVENT.SEVERITIES.ERROR,
    [LOGISTICS_TRACKING_EVENT.TYPES.RETURNED]: LOGISTICS_TRACKING_EVENT.SEVERITIES.WARNING,
    [LOGISTICS_TRACKING_EVENT.TYPES.CANCELLED]: LOGISTICS_TRACKING_EVENT.SEVERITIES.WARNING,
  };
  return severities[event] || LOGISTICS_TRACKING_EVENT.SEVERITIES.INFO;
}

export function logisticsTrackingEventGetColor(
  event: LogisticsTrackingEventType
): LogisticsTrackingEventColor {
  const colors: Record<LogisticsTrackingEventType, LogisticsTrackingEventColor> = {
    [LOGISTICS_TRACKING_EVENT.TYPES.BOOKED]: LOGISTICS_TRACKING_EVENT.COLORS.BOOKED,
    [LOGISTICS_TRACKING_EVENT.TYPES.PICKED_UP]: LOGISTICS_TRACKING_EVENT.COLORS.PICKED_UP,
    [LOGISTICS_TRACKING_EVENT.TYPES.PROCESSED]: LOGISTICS_TRACKING_EVENT.COLORS.PROCESSED,
    [LOGISTICS_TRACKING_EVENT.TYPES.DISPATCHED]: LOGISTICS_TRACKING_EVENT.COLORS.DISPATCHED,
    [LOGISTICS_TRACKING_EVENT.TYPES.IN_TRANSIT]: LOGISTICS_TRACKING_EVENT.COLORS.IN_TRANSIT,
    [LOGISTICS_TRACKING_EVENT.TYPES.ARRIVED]: LOGISTICS_TRACKING_EVENT.COLORS.ARRIVED,
    [LOGISTICS_TRACKING_EVENT.TYPES.OUT_FOR_DELIVERY]:
      LOGISTICS_TRACKING_EVENT.COLORS.OUT_FOR_DELIVERY,
    [LOGISTICS_TRACKING_EVENT.TYPES.DELIVERED]: LOGISTICS_TRACKING_EVENT.COLORS.DELIVERED,
    [LOGISTICS_TRACKING_EVENT.TYPES.FAILED]: LOGISTICS_TRACKING_EVENT.COLORS.FAILED,
    [LOGISTICS_TRACKING_EVENT.TYPES.RETURNED]: LOGISTICS_TRACKING_EVENT.COLORS.RETURNED,
    [LOGISTICS_TRACKING_EVENT.TYPES.CANCELLED]: LOGISTICS_TRACKING_EVENT.COLORS.CANCELLED,
  };
  return colors[event] || '#blue-400';
}

export function logisticsTrackingEventGetIcon(
  event: LogisticsTrackingEventType
): LogisticsTrackingEventIcon {
  const icons: Record<LogisticsTrackingEventType, LogisticsTrackingEventIcon> = {
    [LOGISTICS_TRACKING_EVENT.TYPES.BOOKED]: LOGISTICS_TRACKING_EVENT.ICONS.BOOKED,
    [LOGISTICS_TRACKING_EVENT.TYPES.PICKED_UP]: LOGISTICS_TRACKING_EVENT.ICONS.PICKED_UP,
    [LOGISTICS_TRACKING_EVENT.TYPES.PROCESSED]: LOGISTICS_TRACKING_EVENT.ICONS.PROCESSED,
    [LOGISTICS_TRACKING_EVENT.TYPES.DISPATCHED]: LOGISTICS_TRACKING_EVENT.ICONS.DISPATCHED,
    [LOGISTICS_TRACKING_EVENT.TYPES.IN_TRANSIT]: LOGISTICS_TRACKING_EVENT.ICONS.IN_TRANSIT,
    [LOGISTICS_TRACKING_EVENT.TYPES.ARRIVED]: LOGISTICS_TRACKING_EVENT.ICONS.ARRIVED,
    [LOGISTICS_TRACKING_EVENT.TYPES.OUT_FOR_DELIVERY]:
      LOGISTICS_TRACKING_EVENT.ICONS.OUT_FOR_DELIVERY,
    [LOGISTICS_TRACKING_EVENT.TYPES.DELIVERED]: LOGISTICS_TRACKING_EVENT.ICONS.DELIVERED,
    [LOGISTICS_TRACKING_EVENT.TYPES.FAILED]: LOGISTICS_TRACKING_EVENT.ICONS.FAILED,
    [LOGISTICS_TRACKING_EVENT.TYPES.RETURNED]: LOGISTICS_TRACKING_EVENT.ICONS.RETURNED,
    [LOGISTICS_TRACKING_EVENT.TYPES.CANCELLED]: LOGISTICS_TRACKING_EVENT.ICONS.CANCELLED,
  };
  return icons[event] || '📋';
}

export function logisticsTrackingEventGetDescription(event: LogisticsTrackingEventType): string {
  const descriptions: Record<LogisticsTrackingEventType, string> = {
    [LOGISTICS_TRACKING_EVENT.TYPES.BOOKED]: LOGISTICS_TRACKING_EVENT.DESCRIPTIONS.BOOKED,
    [LOGISTICS_TRACKING_EVENT.TYPES.PICKED_UP]: LOGISTICS_TRACKING_EVENT.DESCRIPTIONS.PICKED_UP,
    [LOGISTICS_TRACKING_EVENT.TYPES.PROCESSED]: LOGISTICS_TRACKING_EVENT.DESCRIPTIONS.PROCESSED,
    [LOGISTICS_TRACKING_EVENT.TYPES.DISPATCHED]: LOGISTICS_TRACKING_EVENT.DESCRIPTIONS.DISPATCHED,
    [LOGISTICS_TRACKING_EVENT.TYPES.IN_TRANSIT]: LOGISTICS_TRACKING_EVENT.DESCRIPTIONS.IN_TRANSIT,
    [LOGISTICS_TRACKING_EVENT.TYPES.ARRIVED]: LOGISTICS_TRACKING_EVENT.DESCRIPTIONS.ARRIVED,
    [LOGISTICS_TRACKING_EVENT.TYPES.OUT_FOR_DELIVERY]:
      LOGISTICS_TRACKING_EVENT.DESCRIPTIONS.OUT_FOR_DELIVERY,
    [LOGISTICS_TRACKING_EVENT.TYPES.DELIVERED]: LOGISTICS_TRACKING_EVENT.DESCRIPTIONS.DELIVERED,
    [LOGISTICS_TRACKING_EVENT.TYPES.FAILED]: LOGISTICS_TRACKING_EVENT.DESCRIPTIONS.FAILED,
    [LOGISTICS_TRACKING_EVENT.TYPES.RETURNED]: LOGISTICS_TRACKING_EVENT.DESCRIPTIONS.RETURNED,
    [LOGISTICS_TRACKING_EVENT.TYPES.CANCELLED]: LOGISTICS_TRACKING_EVENT.DESCRIPTIONS.CANCELLED,
  };
  return descriptions[event] || 'Unknown event';
}
