/**
 * Push Status Constants
 * Status definitions for push notifications
 */

export const NOTIFICATIONPUSH_STATUS = {
  // Push Statuses
  STATUSES: {
    PENDING: 'pending',
    QUEUED: 'queued',
    PROCESSING: 'processing',
    SENT: 'sent',
    DELIVERED: 'delivered',
    FAILED: 'failed',
    REJECTED: 'rejected',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    EXPIRED: 'expired',
    DRAFT: 'draft',
    SCHEDULED: 'scheduled',
    OPENED: 'opened',
    CLICKED: 'clicked',
    DISMISSED: 'dismissed',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    DRAFT: '#6B7280',
    PENDING: '#F59E0B',
    QUEUED: '#8B5CF6',
    PROCESSING: '#3B82F6',
    SCHEDULED: '#3B82F6',
    SENT: '#3B82F6',
    DELIVERED: '#10B981',
    FAILED: '#EF4444',
    REJECTED: '#EF4444',
    CANCELLED: '#6B7280',
    ARCHIVED: '#6B7280',
    EXPIRED: '#6B7280',
    OPENED: '#10B981',
    CLICKED: '#10B981',
    DISMISSED: '#6B7280',
  } as const,

  // Status Categories
  CATEGORIES: {
    DRAFT: 'draft',
    PENDING: 'pending',
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    ENGAGED: 'engaged',
  } as const,

  // Status Priority Order
  ORDER: {
    DRAFT: 0,
    PENDING: 1,
    SCHEDULED: 2,
    QUEUED: 3,
    PROCESSING: 4,
    SENT: 5,
    DELIVERED: 6,
    OPENED: 7,
    CLICKED: 8,
    DISMISSED: 9,
    EXPIRED: 10,
    REJECTED: 11,
    FAILED: 12,
    CANCELLED: 13,
    ARCHIVED: 14,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    DRAFT_TO_PENDING: 'draft_to_pending',
    DRAFT_TO_CANCELLED: 'draft_to_cancelled',
    DRAFT_TO_ARCHIVED: 'draft_to_archived',
    PENDING_TO_SCHEDULED: 'pending_to_scheduled',
    PENDING_TO_QUEUED: 'pending_to_queued',
    PENDING_TO_CANCELLED: 'pending_to_cancelled',
    SCHEDULED_TO_QUEUED: 'scheduled_to_queued',
    SCHEDULED_TO_CANCELLED: 'scheduled_to_cancelled',
    QUEUED_TO_PROCESSING: 'queued_to_processing',
    QUEUED_TO_CANCELLED: 'queued_to_cancelled',
    PROCESSING_TO_SENT: 'processing_to_sent',
    PROCESSING_TO_FAILED: 'processing_to_failed',
    PROCESSING_TO_CANCELLED: 'processing_to_cancelled',
    SENT_TO_DELIVERED: 'sent_to_delivered',
    SENT_TO_FAILED: 'sent_to_failed',
    SENT_TO_REJECTED: 'sent_to_rejected',
    DELIVERED_TO_OPENED: 'delivered_to_opened',
    DELIVERED_TO_DISMISSED: 'delivered_to_dismissed',
    DELIVERED_TO_FAILED: 'delivered_to_failed',
    OPENED_TO_CLICKED: 'opened_to_clicked',
    OPENED_TO_DISMISSED: 'opened_to_dismissed',
    FAILED_TO_ARCHIVED: 'failed_to_archived',
    REJECTED_TO_ARCHIVED: 'rejected_to_archived',
    CANCELLED_TO_ARCHIVED: 'cancelled_to_archived',
    EXPIRED_TO_ARCHIVED: 'expired_to_archived',
    OPENED_TO_ARCHIVED: 'opened_to_archived',
    CLICKED_TO_ARCHIVED: 'clicked_to_archived',
    DISMISSED_TO_ARCHIVED: 'dismissed_to_archived',
  } as const,
} as const;

// Push Statuses
export type NotificationPushStatusType =
  (typeof NOTIFICATIONPUSH_STATUS.STATUSES)[keyof typeof NOTIFICATIONPUSH_STATUS.STATUSES];

// Status Colors
export type NotificationPushStatusColor =
  (typeof NOTIFICATIONPUSH_STATUS.COLORS)[keyof typeof NOTIFICATIONPUSH_STATUS.COLORS];

// Status Categories
export type NotificationPushStatusCategory =
  (typeof NOTIFICATIONPUSH_STATUS.CATEGORIES)[keyof typeof NOTIFICATIONPUSH_STATUS.CATEGORIES];

// Status Priority Order
export type NotificationPushStatusOrder =
  (typeof NOTIFICATIONPUSH_STATUS.ORDER)[keyof typeof NOTIFICATIONPUSH_STATUS.ORDER];

// Status Transitions
export type NotificationPushStatusTransition =
  (typeof NOTIFICATIONPUSH_STATUS.TRANSITIONS)[keyof typeof NOTIFICATIONPUSH_STATUS.TRANSITIONS];

// Utility Functions
export function notificationpushGetStatusLabel(status: NotificationPushStatusType): string {
  const labels: Record<NotificationPushStatusType, string> = {
    [NOTIFICATIONPUSH_STATUS.STATUSES.DRAFT]: 'Draft',
    [NOTIFICATIONPUSH_STATUS.STATUSES.PENDING]: 'Pending',
    [NOTIFICATIONPUSH_STATUS.STATUSES.QUEUED]: 'Queued',
    [NOTIFICATIONPUSH_STATUS.STATUSES.PROCESSING]: 'Processing',
    [NOTIFICATIONPUSH_STATUS.STATUSES.SENT]: 'Sent',
    [NOTIFICATIONPUSH_STATUS.STATUSES.DELIVERED]: 'Delivered',
    [NOTIFICATIONPUSH_STATUS.STATUSES.FAILED]: 'Failed',
    [NOTIFICATIONPUSH_STATUS.STATUSES.REJECTED]: 'Rejected',
    [NOTIFICATIONPUSH_STATUS.STATUSES.CANCELLED]: 'Cancelled',
    [NOTIFICATIONPUSH_STATUS.STATUSES.ARCHIVED]: 'Archived',
    [NOTIFICATIONPUSH_STATUS.STATUSES.EXPIRED]: 'Expired',
    [NOTIFICATIONPUSH_STATUS.STATUSES.SCHEDULED]: 'Scheduled',
    [NOTIFICATIONPUSH_STATUS.STATUSES.OPENED]: 'Opened',
    [NOTIFICATIONPUSH_STATUS.STATUSES.CLICKED]: 'Clicked',
    [NOTIFICATIONPUSH_STATUS.STATUSES.DISMISSED]: 'Dismissed',
  };
  return labels[status] || 'Unknown Status';
}

export function notificationpushGetStatusColor(
  status: NotificationPushStatusType
): NotificationPushStatusColor {
  const colors: Record<NotificationPushStatusType, NotificationPushStatusColor> = {
    [NOTIFICATIONPUSH_STATUS.STATUSES.DRAFT]: NOTIFICATIONPUSH_STATUS.COLORS.DRAFT,
    [NOTIFICATIONPUSH_STATUS.STATUSES.PENDING]: NOTIFICATIONPUSH_STATUS.COLORS.PENDING,
    [NOTIFICATIONPUSH_STATUS.STATUSES.QUEUED]: NOTIFICATIONPUSH_STATUS.COLORS.QUEUED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.PROCESSING]: NOTIFICATIONPUSH_STATUS.COLORS.PROCESSING,
    [NOTIFICATIONPUSH_STATUS.STATUSES.SCHEDULED]: NOTIFICATIONPUSH_STATUS.COLORS.SCHEDULED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.SENT]: NOTIFICATIONPUSH_STATUS.COLORS.SENT,
    [NOTIFICATIONPUSH_STATUS.STATUSES.DELIVERED]: NOTIFICATIONPUSH_STATUS.COLORS.DELIVERED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.FAILED]: NOTIFICATIONPUSH_STATUS.COLORS.FAILED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.REJECTED]: NOTIFICATIONPUSH_STATUS.COLORS.REJECTED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.CANCELLED]: NOTIFICATIONPUSH_STATUS.COLORS.CANCELLED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.ARCHIVED]: NOTIFICATIONPUSH_STATUS.COLORS.ARCHIVED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.EXPIRED]: NOTIFICATIONPUSH_STATUS.COLORS.EXPIRED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.OPENED]: NOTIFICATIONPUSH_STATUS.COLORS.OPENED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.CLICKED]: NOTIFICATIONPUSH_STATUS.COLORS.CLICKED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.DISMISSED]: NOTIFICATIONPUSH_STATUS.COLORS.DISMISSED,
  };
  return colors[status] || NOTIFICATIONPUSH_STATUS.COLORS.PENDING;
}

export function notificationpushGetStatusCategory(
  status: NotificationPushStatusType
): NotificationPushStatusCategory {
  const categories: Record<NotificationPushStatusType, NotificationPushStatusCategory> = {
    [NOTIFICATIONPUSH_STATUS.STATUSES.DRAFT]: NOTIFICATIONPUSH_STATUS.CATEGORIES.DRAFT,
    [NOTIFICATIONPUSH_STATUS.STATUSES.PENDING]: NOTIFICATIONPUSH_STATUS.CATEGORIES.PENDING,
    [NOTIFICATIONPUSH_STATUS.STATUSES.SCHEDULED]: NOTIFICATIONPUSH_STATUS.CATEGORIES.PENDING,
    [NOTIFICATIONPUSH_STATUS.STATUSES.QUEUED]: NOTIFICATIONPUSH_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONPUSH_STATUS.STATUSES.PROCESSING]: NOTIFICATIONPUSH_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONPUSH_STATUS.STATUSES.SENT]: NOTIFICATIONPUSH_STATUS.CATEGORIES.IN_PROGRESS,
    [NOTIFICATIONPUSH_STATUS.STATUSES.DELIVERED]: NOTIFICATIONPUSH_STATUS.CATEGORIES.COMPLETED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.OPENED]: NOTIFICATIONPUSH_STATUS.CATEGORIES.ENGAGED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.CLICKED]: NOTIFICATIONPUSH_STATUS.CATEGORIES.ENGAGED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.DISMISSED]: NOTIFICATIONPUSH_STATUS.CATEGORIES.COMPLETED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.FAILED]: NOTIFICATIONPUSH_STATUS.CATEGORIES.FAILED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.REJECTED]: NOTIFICATIONPUSH_STATUS.CATEGORIES.FAILED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.EXPIRED]: NOTIFICATIONPUSH_STATUS.CATEGORIES.FAILED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.CANCELLED]: NOTIFICATIONPUSH_STATUS.CATEGORIES.CANCELLED,
    [NOTIFICATIONPUSH_STATUS.STATUSES.ARCHIVED]: NOTIFICATIONPUSH_STATUS.CATEGORIES.ARCHIVED,
  };
  return categories[status] || NOTIFICATIONPUSH_STATUS.CATEGORIES.PENDING;
}

export function notificationpushIsDelivered(status: NotificationPushStatusType): boolean {
  const deliveredStatuses: NotificationPushStatusType[] = [
    NOTIFICATIONPUSH_STATUS.STATUSES.DELIVERED,
    NOTIFICATIONPUSH_STATUS.STATUSES.OPENED,
    NOTIFICATIONPUSH_STATUS.STATUSES.CLICKED,
  ];
  return deliveredStatuses.includes(status);
}

export function notificationpushIsEngaged(status: NotificationPushStatusType): boolean {
  const engagedStatuses: NotificationPushStatusType[] = [
    NOTIFICATIONPUSH_STATUS.STATUSES.OPENED,
    NOTIFICATIONPUSH_STATUS.STATUSES.CLICKED,
  ];
  return engagedStatuses.includes(status);
}

export function notificationpushIsFailed(status: NotificationPushStatusType): boolean {
  const failedStatuses: NotificationPushStatusType[] = [
    NOTIFICATIONPUSH_STATUS.STATUSES.FAILED,
    NOTIFICATIONPUSH_STATUS.STATUSES.REJECTED,
    NOTIFICATIONPUSH_STATUS.STATUSES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}

export function notificationpushIsPending(status: NotificationPushStatusType): boolean {
  const pendingStatuses: NotificationPushStatusType[] = [
    NOTIFICATIONPUSH_STATUS.STATUSES.PENDING,
    NOTIFICATIONPUSH_STATUS.STATUSES.QUEUED,
    NOTIFICATIONPUSH_STATUS.STATUSES.PROCESSING,
    NOTIFICATIONPUSH_STATUS.STATUSES.SENT,
    NOTIFICATIONPUSH_STATUS.STATUSES.SCHEDULED,
  ];
  return pendingStatuses.includes(status);
}

export function notificationpushIsSent(status: NotificationPushStatusType): boolean {
  const sentStatuses: NotificationPushStatusType[] = [
    NOTIFICATIONPUSH_STATUS.STATUSES.SENT,
    NOTIFICATIONPUSH_STATUS.STATUSES.DELIVERED,
    NOTIFICATIONPUSH_STATUS.STATUSES.OPENED,
    NOTIFICATIONPUSH_STATUS.STATUSES.CLICKED,
  ];
  return sentStatuses.includes(status);
}

export function notificationpushCanTransition(
  currentStatus: NotificationPushStatusType,
  targetStatus: NotificationPushStatusType
): boolean {
  const validTransitions: Record<NotificationPushStatusType, NotificationPushStatusType[]> = {
    [NOTIFICATIONPUSH_STATUS.STATUSES.DRAFT]: [
      NOTIFICATIONPUSH_STATUS.STATUSES.PENDING,
      NOTIFICATIONPUSH_STATUS.STATUSES.CANCELLED,
      NOTIFICATIONPUSH_STATUS.STATUSES.ARCHIVED,
    ],
    [NOTIFICATIONPUSH_STATUS.STATUSES.PENDING]: [
      NOTIFICATIONPUSH_STATUS.STATUSES.SCHEDULED,
      NOTIFICATIONPUSH_STATUS.STATUSES.QUEUED,
      NOTIFICATIONPUSH_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONPUSH_STATUS.STATUSES.SCHEDULED]: [
      NOTIFICATIONPUSH_STATUS.STATUSES.QUEUED,
      NOTIFICATIONPUSH_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONPUSH_STATUS.STATUSES.QUEUED]: [
      NOTIFICATIONPUSH_STATUS.STATUSES.PROCESSING,
      NOTIFICATIONPUSH_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONPUSH_STATUS.STATUSES.PROCESSING]: [
      NOTIFICATIONPUSH_STATUS.STATUSES.SENT,
      NOTIFICATIONPUSH_STATUS.STATUSES.FAILED,
      NOTIFICATIONPUSH_STATUS.STATUSES.CANCELLED,
    ],
    [NOTIFICATIONPUSH_STATUS.STATUSES.SENT]: [
      NOTIFICATIONPUSH_STATUS.STATUSES.DELIVERED,
      NOTIFICATIONPUSH_STATUS.STATUSES.FAILED,
      NOTIFICATIONPUSH_STATUS.STATUSES.REJECTED,
    ],
    [NOTIFICATIONPUSH_STATUS.STATUSES.DELIVERED]: [
      NOTIFICATIONPUSH_STATUS.STATUSES.OPENED,
      NOTIFICATIONPUSH_STATUS.STATUSES.DISMISSED,
      NOTIFICATIONPUSH_STATUS.STATUSES.FAILED,
    ],
    [NOTIFICATIONPUSH_STATUS.STATUSES.OPENED]: [
      NOTIFICATIONPUSH_STATUS.STATUSES.CLICKED,
      NOTIFICATIONPUSH_STATUS.STATUSES.DISMISSED,
      NOTIFICATIONPUSH_STATUS.STATUSES.ARCHIVED,
    ],
    [NOTIFICATIONPUSH_STATUS.STATUSES.CLICKED]: [NOTIFICATIONPUSH_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONPUSH_STATUS.STATUSES.DISMISSED]: [NOTIFICATIONPUSH_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONPUSH_STATUS.STATUSES.FAILED]: [NOTIFICATIONPUSH_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONPUSH_STATUS.STATUSES.REJECTED]: [NOTIFICATIONPUSH_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONPUSH_STATUS.STATUSES.CANCELLED]: [NOTIFICATIONPUSH_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONPUSH_STATUS.STATUSES.EXPIRED]: [NOTIFICATIONPUSH_STATUS.STATUSES.ARCHIVED],
    [NOTIFICATIONPUSH_STATUS.STATUSES.ARCHIVED]: [],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
