/**
 * সার্চ ডিসকভারি মডিউল থেকে সব কনস্ট্যান্ট এক্সপোর্ট
 */

// সার্চ বেসিক কনস্ট্যান্ট
export {
  DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE,
  DEFAULT_PAGE,
  SEARCH_TIMEOUT_MS,
  DEFAULT_SEARCH_LANGUAGE,
  MIN_SEARCH_QUERY_LENGTH,
  MAX_SEARCH_QUERY_LENGTH,
  SEARCH_VALIDATION_ERRORS,
  type SearchQuery,
} from './search/search.constants';

// সার্চ টাইপ কনস্ট্যান্ট
export {
  SearchType,
  DEFAULT_SEARCH_TYPE,
  SEARCH_TYPE_LABELS,
  SEARCH_TYPE_VALUES,
  SEARCH_TYPE_OPTIONS,
  DEFAULT_SEARCH_TYPE_CONFIG,
  type SearchTypeConfig,
} from './search/search-type.constants';

// সার্চ সর্ট কনস্ট্যান্ট
export {
  SortField,
  SortOrder,
  DEFAULT_SORT_FIELD,
  DEFAULT_SORT_ORDER,
  SORT_LABELS,
  SORT_LABELS_EN,
  SORT_FIELD_VALUES,
  SORT_ORDER_VALUES,
  SORT_OPTIONS,
  DEFAULT_SORT_CONFIG,
  SORT_FIELD_DESCRIPTIONS,
  type SortConfig,
} from './search/search-sort.constants';

// সার্চ ফিল্টার কনস্ট্যান্ট
export {
  FilterType,
  FilterOperator,
  FILTER_LABELS,
  FILTER_LABELS_EN,
  FILTER_OPERATOR_LABELS,
  DEFAULT_FILTER_OPTIONS,
  FILTER_TYPE_VALUES,
  FILTER_OPERATOR_VALUES,
  FILTER_CONFIGS,
  FILTER_VALIDATION_RULES,
  FILTER_ERROR_MESSAGES as FILTER_ERROR_MESSAGES_FILTER,
  type FilterConfig,
  type FilterValue,
  type FilterCondition,
  type FilterGroup,
} from './search/search-filter.constants';

// সার্চ অপারেটর কনস্ট্যান্ট
export {
  BooleanOperator,
  QueryOperator,
  BOOLEAN_OPERATOR_LABELS,
  BOOLEAN_OPERATOR_LABELS_EN,
  QUERY_OPERATOR_LABELS,
  QUERY_OPERATOR_LABELS_EN,
  BOOLEAN_OPERATOR_DESCRIPTIONS,
  QUERY_OPERATOR_DESCRIPTIONS,
  BOOLEAN_OPERATOR_VALUES,
  QUERY_OPERATOR_VALUES,
  BOOLEAN_OPERATOR_CONFIGS,
  QUERY_OPERATOR_CONFIGS,
  DEFAULT_BOOLEAN_OPERATOR,
  DEFAULT_QUERY_OPERATOR,
  type OperatorConfig,
} from './search/search-operator.constants';

// সার্চ ম্যাচ কনস্ট্যান্ট
export {
  MatchType,
  MATCH_TYPE_LABELS,
  MATCH_TYPE_LABELS_EN,
  MATCH_TYPE_DESCRIPTIONS,
  FUZZY_DEFAULT_CONFIG,
  PREFIX_DEFAULT_CONFIG,
  PHRASE_DEFAULT_CONFIG,
  WILDCARD_DEFAULT_CONFIG,
  MATCH_TYPE_VALUES,
  MATCH_CONFIGS,
  DEFAULT_MATCH_TYPE,
  MATCH_ERROR_MESSAGES,
  type MatchConfig,
} from './search/search-match.constants';

// সার্চ বুস্ট কনস্ট্যান্ট
export {
  BOOST_FACTORS,
  BOOST_FACTOR_LABELS,
  BOOST_FACTOR_LABELS_EN,
  DEFAULT_BOOST,
  MIN_BOOST_LIMIT,
  MAX_BOOST_LIMIT,
  SEASONAL_BOOST_FACTORS,
  SEASONAL_BOOST_LABELS,
  BOOST_CONFIGS,
  BOOST_ERROR_MESSAGES,
  type BoostConfig,
} from './search/search-boost.constants';

// সার্চ অ্যানালিটিক্স কনস্ট্যান্ট
export {
  AnalyticsEventType,
  AnalyticsTimeFrame,
  AnalyticsMetric,
  ANALYTICS_EVENT_LABELS,
  ANALYTICS_EVENT_LABELS_EN,
  ANALYTICS_TIME_FRAME_LABELS,
  ANALYTICS_TIME_FRAME_LABELS_EN,
  ANALYTICS_METRIC_LABELS,
  ANALYTICS_METRIC_LABELS_EN,
  DEFAULT_ANALYTICS_PERIOD_DAYS,
  DEFAULT_ANALYTICS_TIME_FRAME,
  ANALYTICS_DATA_RETENTION_DAYS,
  ANALYTICS_RATE_LIMIT,
  ANALYTICS_CACHE_TIMEOUT_SECONDS,
  ANALYTICS_DEFAULT_WAIT_TIME_MS,
  DEFAULT_ANALYTICS_CONFIG,
  ANALYTICS_ERROR_MESSAGES,
  type AnalyticsConfig,
} from './search/search-analytics.constants';

// সার্চ সাজেশন কনস্ট্যান্ট
export {
  SuggestionType,
  SUGGESTION_TYPE_LABELS,
  SUGGESTION_TYPE_LABELS_EN,
  SUGGESTION_TYPE_DESCRIPTIONS,
  DEFAULT_SUGGESTION_COUNT,
  MAX_SUGGESTION_COUNT,
  MIN_SUGGESTION_COUNT,
  SUGGESTION_CACHE_TTL_SECONDS,
  SUGGESTION_SCORE_THRESHOLD,
  MIN_SUGGESTION_SCORE,
  MAX_SUGGESTION_SCORE,
  SUGGESTION_TYPE_VALUES,
  DEFAULT_SUGGESTION_TYPE,
  SUGGESTION_CONFIGS,
  SUGGESTION_ERROR_MESSAGES,
  type SuggestionConfig,
} from './search/search-suggestion.constants';

// সার্চ সিনোনিম কনস্ট্যান্ট
export {
  SynonymType,
  SYNONYM_TYPE_LABELS,
  SYNONYM_TYPE_LABELS_EN,
  SYNONYM_TYPE_DESCRIPTIONS,
  SYNONYM_FORMAT,
  SYNONYM_FORMAT_EXAMPLE,
  DEFAULT_SYNONYM_FILE_PATH,
  MAX_SYNONYM_SET_SIZE,
  MIN_SYNONYM_SET_SIZE,
  SYNONYM_CACHE_TTL_SECONDS,
  SYNONYM_TYPE_VALUES,
  DEFAULT_SYNONYM_TYPE,
  SYNONYM_CONFIGS,
  SYNONYM_ERROR_MESSAGES,
  type SynonymConfig,
  type SynonymData,
  type SynonymGroup,
} from './search/search-synonym.constants';

// সার্চ স্টপওয়ার্ড কনস্ট্যান্ট
export {
  BENGALI_STOPWORDS,
  ENGLISH_STOPWORDS,
  StopwordLanguage,
  STOPWORD_LANGUAGE_LABELS,
  STOPWORD_LANGUAGE_LABELS_EN,
  STOPWORD_LANGUAGE_VALUES,
  DEFAULT_STOPWORD_LANGUAGE,
  STOPWORD_FILE_PATH,
  BENGALI_STOPWORD_FILE_PATH,
  ENGLISH_STOPWORD_FILE_PATH,
  STOPWORD_CACHE_TTL_SECONDS,
  STOPWORD_CONFIGS,
  STOPWORD_ERROR_MESSAGES,
  type StopwordConfig,
  type StopwordData,
  type StopwordGroup,
} from './search/search-stopword.constants';

// সার্চ ইন্ডেক্স কনস্ট্যান্ট
export {
  IndexName,
  IndexAlias,
  INDEX_NAME_LABELS,
  INDEX_NAME_LABELS_EN,
  INDEX_ALIAS_LABELS,
  INDEX_ALIAS_LABELS_EN,
  DEFAULT_INDEX_SETTINGS,
  MAX_INDEX_FIELDS,
  MIN_INDEX_FIELDS,
  INDEX_REFRESH_INTERVAL_SECONDS,
  INDEX_REFRESH_INTERVAL_OPTIONS,
  INDEX_NAME_VALUES,
  INDEX_ALIAS_VALUES,
  DEFAULT_INDEX_NAME,
  DEFAULT_INDEX_ALIAS,
  INDEX_CONFIGS,
  INDEX_ERROR_MESSAGES,
  type IndexConfig,
  type IndexMapping,
} from './search/search-index.constants';

// সার্চ রিলেভেন্স কনস্ট্যান্ট
export {
  RelevanceThreshold,
  RelevanceFactor,
  RelevanceMethod,
  RELEVANCE_THRESHOLD_LABELS,
  RELEVANCE_THRESHOLD_LABELS_EN,
  RELEVANCE_FACTOR_LABELS,
  RELEVANCE_FACTOR_LABELS_EN,
  RELEVANCE_METHOD_LABELS,
  RELEVANCE_METHOD_LABELS_EN,
  DEFAULT_BM25_PARAMS,
  DEFAULT_TF_IDF_PARAMS,
  RELEVANCE_SCORE_RANGE,
  RELEVANCE_FACTOR_VALUES,
  RELEVANCE_METHOD_VALUES,
  RELEVANCE_THRESHOLD_VALUES,
  DEFAULT_RELEVANCE_THRESHOLD,
  DEFAULT_RELEVANCE_METHOD,
  DEFAULT_RELEVANCE_CONFIG,
  RELEVANCE_ERROR_MESSAGES,
  type RelevanceConfig,
} from './search/search-relevance.constants';

// অটোকমপ্লিট কনস্ট্যান্ট
export {
  AutocompleteType,
  AUTOCOMPLETE_TYPE_LABELS,
  AUTOCOMPLETE_TYPE_LABELS_EN,
  AUTOCOMPLETE_TYPE_DESCRIPTIONS,
  DEFAULT_AUTOCOMPLETE_COUNT,
  MAX_AUTOCOMPLETE_COUNT,
  MIN_AUTOCOMPLETE_COUNT,
  AUTOCOMPLETE_MIN_CHARACTERS,
  AUTOCOMPLETE_MAX_CHARACTERS,
  AUTOCOMPLETE_CACHE_TTL_SECONDS,
  AUTOCOMPLETE_TYPE_VALUES,
  DEFAULT_AUTOCOMPLETE_TYPE,
  AUTOCOMPLETE_CONFIGS,
  AUTOCOMPLETE_ERROR_MESSAGES,
  type AutocompleteConfig,
  type AutocompleteData,
  type AutocompleteResponse,
} from './search/autocomplete.constants';

// ফ্যাসেট কনস্ট্যান্ট
export {
  FacetField,
  FacetType,
  FacetOrder,
  FACET_FIELD_LABELS,
  FACET_FIELD_LABELS_EN,
  FACET_TYPE_LABELS,
  FACET_TYPE_LABELS_EN,
  FACET_ORDER_LABELS,
  FACET_ORDER_LABELS_EN,
  DEFAULT_FACET_SIZE,
  MAX_FACET_SIZE,
  MIN_FACET_SIZE,
  DEFAULT_FACET_ORDER,
  FACET_FIELD_VALUES,
  FACET_TYPE_VALUES,
  FACET_ORDER_VALUES,
  FACET_CONFIGS,
  FACET_RANGE_DEFAULTS,
  FACET_ERROR_MESSAGES,
  type FacetConfig,
} from './search/facet.constants';

// ফিল্টার UI কনস্ট্যান্ট
export {
  FilterUIType,
  FilterDefaultState,
  FILTER_UI_TYPE_LABELS,
  FILTER_UI_TYPE_LABELS_EN,
  FILTER_DEFAULT_STATE_LABELS,
  FILTER_DEFAULT_STATE_LABELS_EN,
  FILTER_APPLY_BUTTON_TEXT,
  FILTER_APPLY_BUTTON_TEXT_EN,
  FILTER_CLEAR_BUTTON_TEXT,
  FILTER_CLEAR_BUTTON_TEXT_EN,
  FILTER_RESET_BUTTON_TEXT,
  FILTER_RESET_BUTTON_TEXT_EN,
  FILTER_TITLES,
  FILTER_TITLES_EN,
  FILTER_PLACEHOLDER_TEXT,
  FILTER_PLACEHOLDER_TEXT_EN,
  FILTER_UI_TYPE_VALUES,
  FILTER_DEFAULT_STATE_VALUES,
  DEFAULT_FILTER_STATE,
  FILTER_UI_CONFIGS,
  FILTER_ERROR_MESSAGES as FILTER_UI_ERROR_MESSAGES,
  type FilterUIConfig,
} from './search/filter.constants';

// সর্ট অপশন কনস্ট্যান্ট
export {
  SortOption,
  SORT_OPTION_LABELS,
  SORT_OPTION_LABELS_EN,
  SORT_OPTION_ICONS,
  SORT_OPTION_DESCRIPTIONS,
  SORT_OPTION_DESCRIPTIONS_EN,
  DEFAULT_SORT_OPTION,
  SORT_OPTION_VALUES,
  SORT_OPTION_GROUPS,
  SORT_CONFIGS,
  SORT_ERROR_MESSAGES,
  type SortConfig as SortOptionConfig,
} from './search/sort.constants';

// সার্চ এরর কনস্ট্যান্ট
export {
  ErrorCategory,
  SearchErrorCode,
  SEARCH_ERROR_MESSAGES_BN,
  SEARCH_ERROR_MESSAGES_EN,
  SEARCH_ERROR_HTTP_STATUS,
  HTTP_STATUS_TO_SEARCH_ERROR,
  SEARCH_ERROR_CATEGORY,
  ERROR_CATEGORY_LABELS_BN,
  ERROR_CATEGORY_LABELS_EN,
  ERROR_CATEGORY_DESCRIPTIONS_BN,
  ERROR_CATEGORY_DESCRIPTIONS_EN,
  DEFAULT_ERROR_CATEGORY,
  ERROR_RETRY_CONFIG,
  SEARCH_ERROR_CONFIGS,
  SEARCH_ERROR_EXTRA_MESSAGES,
  type SearchErrorConfig,
  type SearchErrorResponse,
} from './search/search-error.constants';

// ডিসকভারি কনস্ট্যান্ট
export {
  DiscoveryType,
  DISCOVERY_TYPE_LABELS_BN,
  DISCOVERY_TYPE_LABELS_EN,
  DISCOVERY_TYPE_DESCRIPTIONS_BN,
  DISCOVERY_TYPE_DESCRIPTIONS_EN,
  DEFAULT_DISCOVERY_COUNT,
  MAX_DISCOVERY_COUNT,
  MIN_DISCOVERY_COUNT,
  DEFAULT_DISCOVERY_TIMEOUT_MS,
  DISCOVERY_CACHE_TTL_SECONDS,
  DEFAULT_DISCOVERY_TYPE,
  DISCOVERY_TYPE_VALUES,
  DISCOVERY_CONFIGS,
  DISCOVERY_ERROR_MESSAGES,
  type DiscoveryConfig,
  type DiscoveryResponse,
} from './discovery/discovery.constants';

// রেকমেন্ডেশন কনস্ট্যান্ট
export {
  RecommendationType,
  RECOMMENDATION_TYPE_LABELS_BN,
  RECOMMENDATION_TYPE_LABELS_EN,
  RECOMMENDATION_TYPE_DESCRIPTIONS_BN,
  RECOMMENDATION_TYPE_DESCRIPTIONS_EN,
  DEFAULT_RECOMMENDATION_COUNT,
  MAX_RECOMMENDATION_COUNT,
  MIN_RECOMMENDATION_COUNT,
  RECOMMENDATION_TIMEOUT_MS,
  RECOMMENDATION_CACHE_TTL_SECONDS,
  DEFAULT_RECOMMENDATION_TYPE,
  RECOMMENDATION_TYPE_VALUES,
  RECOMMENDATION_CONFIGS,
  RECOMMENDATION_ERROR_MESSAGES,
  type RecommendationConfig,
  type RecommendationResponse,
} from './discovery/recommendation.constants';

// রেকমেন্ডেশন টাইপ কনস্ট্যান্ট
export {
  RecommendationItemType,
  RECOMMENDATION_ITEM_TYPE_LABELS_BN,
  RECOMMENDATION_ITEM_TYPE_LABELS_EN,
  RECOMMENDATION_ITEM_TYPE_DESCRIPTIONS_BN,
  RECOMMENDATION_ITEM_TYPE_DESCRIPTIONS_EN,
  RECOMMENDATION_ITEM_TYPE_ICONS,
  RECOMMENDATION_ITEM_TYPE_COLORS,
  DEFAULT_RECOMMENDATION_ITEM_TYPE,
  RECOMMENDATION_ITEM_TYPE_VALUES,
  RECOMMENDATION_ITEM_TYPE_CONFIGS,
  type RecommendationItemTypeConfig,
} from './discovery/recommendation-type.constants';

// রেকমেন্ডেশন স্ট্র্যাটেজি কনস্ট্যান্ট
export {
  StrategyType,
  STRATEGY_TYPE_LABELS_BN,
  STRATEGY_TYPE_LABELS_EN,
  STRATEGY_TYPE_DESCRIPTIONS_BN,
  STRATEGY_TYPE_DESCRIPTIONS_EN,
  STRATEGY_WEIGHTS,
  DEFAULT_STRATEGY_TYPE,
  STRATEGY_TYPE_VALUES,
  STRATEGY_CONFIGS,
  STRATEGY_ERROR_MESSAGES,
  type StrategyConfig,
  type StrategyParams,
  type StrategyCombinedResponse,
} from './discovery/recommendation-strategy.constants';

// পার্সোনালাইজেশন কনস্ট্যান্ট
export {
  PersonalizationType,
  UserInterestCategory,
  PERSONALIZATION_TYPE_LABELS_BN,
  PERSONALIZATION_TYPE_LABELS_EN,
  PERSONALIZATION_TYPE_DESCRIPTIONS_BN,
  PERSONALIZATION_TYPE_DESCRIPTIONS_EN,
  USER_INTEREST_CATEGORY_LABELS_BN,
  USER_INTEREST_CATEGORY_LABELS_EN,
  USER_INTEREST_CATEGORY_WEIGHTS,
  INTEREST_SCORE_THRESHOLD,
  MIN_INTEREST_SCORE,
  MAX_INTEREST_SCORE,
  INTEREST_UPDATE_INTERVAL_HOURS,
  INTEREST_UPDATE_INTERVAL_MS,
  DEFAULT_PERSONALIZATION_TYPE,
  PERSONALIZATION_TYPE_VALUES,
  USER_INTEREST_CATEGORY_VALUES,
  PERSONALIZATION_CONFIGS,
  PERSONALIZATION_ERROR_MESSAGES,
  type PersonalizationConfig,
  type UserInterest,
  type UserProfile,
} from './discovery/personalization.constants';

// ট্রেন্ডিং কনস্ট্যান্ট
export {
  TrendingTimeFrame,
  TrendingScoreFactor,
  TRENDING_TIME_FRAME_LABELS_BN,
  TRENDING_TIME_FRAME_LABELS_EN,
  TRENDING_SCORE_FACTOR_LABELS_BN,
  TRENDING_SCORE_FACTOR_LABELS_EN,
  TRENDING_SCORE_FACTOR_WEIGHTS,
  DEFAULT_TRENDING_COUNT,
  MAX_TRENDING_COUNT,
  MIN_TRENDING_COUNT,
  TRENDING_CACHE_TTL_SECONDS,
  DEFAULT_TRENDING_TIME_FRAME,
  TRENDING_TIME_FRAME_VALUES,
  TRENDING_SCORE_FACTOR_VALUES,
  TRENDING_CONFIGS,
  TRENDING_ERROR_MESSAGES,
  type TrendingConfig,
  type TrendingItem,
  type TrendingResponse,
} from './discovery/trending.constants';

// পপুলার কনস্ট্যান্ট
export {
  PopularityTimeFrame,
  PopularityMetric,
  POPULARITY_TIME_FRAME_LABELS_BN,
  POPULARITY_TIME_FRAME_LABELS_EN,
  POPULARITY_METRIC_LABELS_BN,
  POPULARITY_METRIC_LABELS_EN,
  POPULARITY_METRIC_WEIGHTS,
  DEFAULT_POPULAR_COUNT,
  MAX_POPULAR_COUNT,
  MIN_POPULAR_COUNT,
  POPULAR_CACHE_TTL_SECONDS,
  DEFAULT_POPULARITY_TIME_FRAME,
  POPULARITY_TIME_FRAME_VALUES,
  POPULARITY_METRIC_VALUES,
  POPULAR_CONFIGS,
  POPULAR_ERROR_MESSAGES,
  type PopularConfig,
  type PopularItem,
  type PopularResponse,
} from './discovery/popular.constants';

// রিসেন্টলি ভিউড কনস্ট্যান্ট
export {
  RecentlyViewedItemType,
  RECENTLY_VIEWED_ITEM_TYPE_LABELS_BN,
  RECENTLY_VIEWED_ITEM_TYPE_LABELS_EN,
  MAX_HISTORY_SIZE,
  MIN_HISTORY_SIZE,
  DEFAULT_HISTORY_SIZE,
  DEFAULT_DISPLAY_COUNT,
  MAX_DISPLAY_COUNT,
  MIN_DISPLAY_COUNT,
  HISTORY_TIMEOUT_DAYS,
  HISTORY_TIMEOUT_MS,
  RECENTLY_VIEWED_CACHE_TTL_SECONDS,
  DEFAULT_RECENTLY_VIEWED_ITEM_TYPE,
  RECENTLY_VIEWED_ITEM_TYPE_VALUES,
  RECENTLY_VIEWED_CONFIGS,
  RECENTLY_VIEWED_ERROR_MESSAGES,
  type RecentlyViewedConfig,
  type RecentlyViewedItem,
  type RecentlyViewedHistory,
  type RecentlyViewedResponse,
} from './discovery/recently-viewed.constants';

// ফ্রিকোয়েন্টলি বট কনস্ট্যান্ট
export {
  MIN_CO_PURCHASE_COUNT,
  ASSOCIATION_RULE_MIN_CONFIDENCE,
  ASSOCIATION_RULE_MIN_SUPPORT,
  ASSOCIATION_RULE_MIN_LIFT,
  DEFAULT_FREQUENTLY_BOUGHT_DISPLAY_COUNT,
  MAX_FREQUENTLY_BOUGHT_DISPLAY_COUNT,
  MIN_FREQUENTLY_BOUGHT_DISPLAY_COUNT,
  FREQUENTLY_BOUGHT_CACHE_TTL_SECONDS,
  AssociationRuleType,
  ASSOCIATION_RULE_TYPE_LABELS_BN,
  ASSOCIATION_RULE_TYPE_LABELS_EN,
  DEFAULT_ASSOCIATION_RULE_TYPE,
  ASSOCIATION_RULE_TYPE_VALUES,
  FREQUENTLY_BOUGHT_CONFIGS,
  FREQUENTLY_BOUGHT_ERROR_MESSAGES,
  type FrequentlyBoughtConfig,
  type AssociationRule,
  type FrequentlyBoughtResponse,
} from './discovery/frequently-bought.constants';

// কমপ্লিমেন্টারি কনস্ট্যান্ট
export {
  ComplementaryItemType,
  SimilarityMetric,
  COMPLEMENTARY_ITEM_TYPE_LABELS_BN,
  COMPLEMENTARY_ITEM_TYPE_LABELS_EN,
  SIMILARITY_METRIC_LABELS_BN,
  SIMILARITY_METRIC_LABELS_EN,
  MIN_SIMILARITY_SCORE,
  MAX_SIMILARITY_SCORE,
  DEFAULT_COMPLEMENTARY_DISPLAY_COUNT,
  MAX_COMPLEMENTARY_DISPLAY_COUNT,
  MIN_COMPLEMENTARY_DISPLAY_COUNT,
  DEFAULT_SIMILARITY_METRIC,
  SIMILARITY_METRIC_VALUES,
  COMPLEMENTARY_ITEM_TYPE_VALUES,
  COMPLEMENTARY_CONFIGS,
  COMPLEMENTARY_ERROR_MESSAGES,
  type ComplementaryConfig,
  type ComplementaryItem,
  type ComplementaryResponse,
} from './discovery/complementary.constants';

// সাবস্টিটিউট কনস্ট্যান্ট
export {
  SubstituteCategory,
  SUBSTITUTE_CATEGORY_LABELS_BN,
  SUBSTITUTE_CATEGORY_LABELS_EN,
  SUBSTITUTE_CATEGORY_DESCRIPTIONS_BN,
  SUBSTITUTE_CATEGORY_DESCRIPTIONS_EN,
  SUBSTITUTE_MATCH_THRESHOLD,
  DEFAULT_SUBSTITUTE_DISPLAY_COUNT,
  MAX_SUBSTITUTE_DISPLAY_COUNT,
  MIN_SUBSTITUTE_DISPLAY_COUNT,
  SUBSTITUTE_CACHE_TTL_SECONDS,
  DEFAULT_SUBSTITUTE_CATEGORY,
  SUBSTITUTE_CATEGORY_VALUES,
  SUBSTITUTE_CONFIGS,
  SUBSTITUTE_ERROR_MESSAGES,
  type SubstituteConfig,
  type SubstituteItem,
  type SubstituteResponse,
} from './discovery/substitute.constants';

// আপসেলিং কনস্ট্যান্ট
export {
  UpsellType,
  UPSELL_TYPE_LABELS_BN,
  UPSELL_TYPE_LABELS_EN,
  UPSELL_TYPE_DESCRIPTIONS_BN,
  UPSELL_TYPE_DESCRIPTIONS_EN,
  PRICE_DIFFERENCE_THRESHOLD,
  FEATURE_COMPARISON_FACTORS,
  DEFAULT_UPSELL_DISPLAY_COUNT,
  MAX_UPSELL_DISPLAY_COUNT,
  MIN_UPSELL_DISPLAY_COUNT,
  DEFAULT_UPSELL_TYPE,
  UPSELL_TYPE_VALUES,
  UPSELL_CONFIGS,
  UPSELL_ERROR_MESSAGES,
  type UpsellConfig,
  type UpsellItem,
  type UpsellResponse,
} from './discovery/upselling.constants';

// ক্রস-সেলিং কনস্ট্যান্ট
export {
  CrossSellCategory,
  CROSS_SELL_CATEGORY_LABELS_BN,
  CROSS_SELL_CATEGORY_LABELS_EN,
  CROSS_SELL_CATEGORY_DESCRIPTIONS_BN,
  CROSS_SELL_CATEGORY_DESCRIPTIONS_EN,
  CROSS_SELL_RELATIONSHIP_THRESHOLD,
  DEFAULT_CROSS_SELL_DISPLAY_COUNT,
  MAX_CROSS_SELL_DISPLAY_COUNT,
  MIN_CROSS_SELL_DISPLAY_COUNT,
  CROSS_SELL_CACHE_TTL_SECONDS,
  DEFAULT_CROSS_SELL_CATEGORY,
  CROSS_SELL_CATEGORY_VALUES,
  CROSS_SELL_CONFIGS,
  CROSS_SELL_ERROR_MESSAGES,
  type CrossSellConfig,
  type CrossSellItem,
  type CrossSellResponse,
} from './discovery/cross-selling.constants';

// বান্ডল কনস্ট্যান্ট
export {
  BundleType,
  BUNDLE_TYPE_LABELS_BN,
  BUNDLE_TYPE_LABELS_EN,
  BUNDLE_TYPE_DESCRIPTIONS_BN,
  BUNDLE_TYPE_DESCRIPTIONS_EN,
  BUNDLE_LABELS,
  DEFAULT_BUNDLE_MIN_SIZE,
  DEFAULT_BUNDLE_MAX_SIZE,
  BUNDLE_DISCOUNT_THRESHOLD,
  DEFAULT_BUNDLE_DISPLAY_COUNT,
  MAX_BUNDLE_DISPLAY_COUNT,
  MIN_BUNDLE_DISPLAY_COUNT,
  DEFAULT_BUNDLE_TYPE,
  BUNDLE_TYPE_VALUES,
  BUNDLE_CONFIGS,
  BUNDLE_ERROR_MESSAGES,
  type BundleConfig,
  type BundleItem,
  type BundleResponse,
} from './discovery/bundle.constants';

// ট্রেন্ডিং নাও কনস্ট্যান্ট
export {
  TrendingMetric,
  TRENDING_METRIC_LABELS_BN,
  TRENDING_METRIC_LABELS_EN,
  TRENDING_METRIC_DESCRIPTIONS_BN,
  TRENDING_METRIC_DESCRIPTIONS_EN,
  TRENDING_METRIC_WEIGHTS,
  TRENDING_UPDATE_INTERVAL_MINUTES,
  TRENDING_UPDATE_INTERVAL_MS,
  DEFAULT_TRENDING_NOW_DISPLAY_COUNT,
  MAX_TRENDING_NOW_DISPLAY_COUNT,
  MIN_TRENDING_NOW_DISPLAY_COUNT,
  TRENDING_NOW_CACHE_TTL_SECONDS,
  DEFAULT_TRENDING_METRIC,
  TRENDING_METRIC_VALUES,
  TRENDING_NOW_CONFIGS,
  TRENDING_NOW_ERROR_MESSAGES,
  type TrendingNowConfig,
  type TrendingNowItem,
  type TrendingNowResponse,
} from './discovery/trending-now.constants';

// সিজনাল কনস্ট্যান্ট
export {
  Season,
  SeasonalEvent,
  SEASON_LABELS_BN,
  SEASON_LABELS_EN,
  SEASONAL_EVENT_LABELS_BN,
  SEASONAL_EVENT_LABELS_EN,
  SEASONAL_DURATION_DAYS,
  SEASONAL_CACHE_TTL_SECONDS,
  SEASONAL_DURATION_RANGE,
  SEASON_VALUES,
  SEASONAL_EVENT_VALUES,
  SEASONAL_CONFIGS,
  SEASONAL_ERROR_MESSAGES,
  type SeasonalConfig,
  type SeasonalItem,
  type SeasonalResponse,
} from './discovery/seasonal.constants';

// এডিটোরিয়াল কনস্ট্যান্ট
export {
  EditorialType,
  EditorialStatus,
  EDITORIAL_TYPE_LABELS_BN,
  EDITORIAL_TYPE_LABELS_EN,
  EDITORIAL_TYPE_DESCRIPTIONS_BN,
  EDITORIAL_TYPE_DESCRIPTIONS_EN,
  EDITORIAL_STATUS_LABELS_BN,
  EDITORIAL_STATUS_LABELS_EN,
  EDITORIAL_STATUS_COLORS,
  DEFAULT_EDITORIAL_DISPLAY_COUNT,
  MAX_EDITORIAL_DISPLAY_COUNT,
  MIN_EDITORIAL_DISPLAY_COUNT,
  EDITORIAL_CACHE_TTL_SECONDS,
  DEFAULT_EDITORIAL_TYPE,
  EDITORIAL_TYPE_VALUES,
  EDITORIAL_STATUS_VALUES,
  EDITORIAL_CONFIGS,
  EDITORIAL_ERROR_MESSAGES,
  type EditorialConfig,
  type EditorialItem,
  type EditorialResponse,
} from './discovery/editorial.constants';

// ডিসকভারি এরর কনস্ট্যান্ট
export {
  DiscoveryErrorCategory,
  DiscoveryErrorCode,
  DISCOVERY_ERROR_MESSAGES_BN,
  DISCOVERY_ERROR_MESSAGES_EN,
  DISCOVERY_ERROR_HTTP_STATUS,
  DISCOVERY_ERROR_CATEGORY,
  DISCOVERY_ERROR_CATEGORY_LABELS_BN,
  DISCOVERY_ERROR_CATEGORY_LABELS_EN,
  DISCOVERY_ERROR_RETRY_CONFIG,
  DISCOVERY_ERROR_CONFIGS,
  DISCOVERY_ERROR_EXTRA_MESSAGES,
  type DiscoveryErrorConfig,
  type DiscoveryErrorResponse,
} from './discovery/discovery-error.constants';
