/**
 * Knowledge Base Category Constants
 * Categories for knowledge base articles
 */

export const KNOWLEDGE_BASE_CATEGORY = {
  // Category Types
  TYPES: {
    GENERAL: 'general',
    ACCOUNT: 'account',
    PAYMENT: 'payment',
    ORDER: 'order',
    SHIPPING: 'shipping',
    PRODUCT: 'product',
    TECHNICAL: 'technical',
    BILLING: 'billing',
    SECURITY: 'security',
    PRIVACY: 'privacy',
    LEGAL: 'legal',
    TROUBLESHOOTING: 'troubleshooting',
    TUTORIAL: 'tutorial',
    FAQ: 'faq',
    RELEASE: 'release',
    POLICY: 'policy',
  } as const,

  // Category Icons (for UI)
  ICONS: {
    GENERAL: '📋',
    ACCOUNT: '👤',
    PAYMENT: '💳',
    ORDER: '📦',
    SHIPPING: '🚚',
    PRODUCT: '🛍️',
    TECHNICAL: '🔧',
    BILLING: '💰',
    SECURITY: '🔒',
    PRIVACY: '🔐',
    LEGAL: '⚖️',
    TROUBLESHOOTING: '🔍',
    TUTORIAL: '📚',
    FAQ: '❓',
    RELEASE: '📢',
    POLICY: '📜',
  } as const,

  // Category Colors (for UI)
  COLORS: {
    GENERAL: '#gray-500',
    ACCOUNT: '#blue-500',
    PAYMENT: '#green-500',
    ORDER: '#purple-500',
    SHIPPING: '#orange-500',
    PRODUCT: '#pink-500',
    TECHNICAL: '#red-500',
    BILLING: '#yellow-500',
    SECURITY: '#red-600',
    PRIVACY: '#purple-600',
    LEGAL: '#gray-700',
    TROUBLESHOOTING: '#orange-600',
    TUTORIAL: '#blue-400',
    FAQ: '#teal-500',
    RELEASE: '#green-600',
    POLICY: '#gray-600',
  } as const,

  // Category Priorities
  PRIORITIES: {
    GENERAL: 'low',
    ACCOUNT: 'high',
    PAYMENT: 'high',
    ORDER: 'medium',
    SHIPPING: 'medium',
    PRODUCT: 'medium',
    TECHNICAL: 'high',
    BILLING: 'high',
    SECURITY: 'critical',
    PRIVACY: 'high',
    LEGAL: 'high',
    TROUBLESHOOTING: 'medium',
    TUTORIAL: 'medium',
    FAQ: 'medium',
    RELEASE: 'low',
    POLICY: 'high',
  } as const,
} as const;

// Category Types
export type KnowledgeBaseCategoryType =
  (typeof KNOWLEDGE_BASE_CATEGORY.TYPES)[keyof typeof KNOWLEDGE_BASE_CATEGORY.TYPES];

// Category Icons
export type KnowledgeBaseCategoryIcon =
  (typeof KNOWLEDGE_BASE_CATEGORY.ICONS)[keyof typeof KNOWLEDGE_BASE_CATEGORY.ICONS];

// Category Colors
export type KnowledgeBaseCategoryColor =
  (typeof KNOWLEDGE_BASE_CATEGORY.COLORS)[keyof typeof KNOWLEDGE_BASE_CATEGORY.COLORS];

// Utility Functions
export function knowledgeBaseCategoryGetLabel(category: KnowledgeBaseCategoryType): string {
  const labels: Record<KnowledgeBaseCategoryType, string> = {
    [KNOWLEDGE_BASE_CATEGORY.TYPES.GENERAL]: 'General',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.ACCOUNT]: 'Account',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.PAYMENT]: 'Payment',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.ORDER]: 'Order',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.SHIPPING]: 'Shipping',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.PRODUCT]: 'Product',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.TECHNICAL]: 'Technical',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.BILLING]: 'Billing',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.SECURITY]: 'Security',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.PRIVACY]: 'Privacy',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.LEGAL]: 'Legal',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.TROUBLESHOOTING]: 'Troubleshooting',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.TUTORIAL]: 'Tutorial',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.FAQ]: 'FAQ',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.RELEASE]: 'Release',
    [KNOWLEDGE_BASE_CATEGORY.TYPES.POLICY]: 'Policy',
  };
  return labels[category] || 'Unknown';
}

export function knowledgeBaseCategoryGetIcon(
  category: KnowledgeBaseCategoryType
): KnowledgeBaseCategoryIcon {
  const icons: Record<KnowledgeBaseCategoryType, KnowledgeBaseCategoryIcon> = {
    [KNOWLEDGE_BASE_CATEGORY.TYPES.GENERAL]: KNOWLEDGE_BASE_CATEGORY.ICONS.GENERAL,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.ACCOUNT]: KNOWLEDGE_BASE_CATEGORY.ICONS.ACCOUNT,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.PAYMENT]: KNOWLEDGE_BASE_CATEGORY.ICONS.PAYMENT,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.ORDER]: KNOWLEDGE_BASE_CATEGORY.ICONS.ORDER,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.SHIPPING]: KNOWLEDGE_BASE_CATEGORY.ICONS.SHIPPING,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.PRODUCT]: KNOWLEDGE_BASE_CATEGORY.ICONS.PRODUCT,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.TECHNICAL]: KNOWLEDGE_BASE_CATEGORY.ICONS.TECHNICAL,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.BILLING]: KNOWLEDGE_BASE_CATEGORY.ICONS.BILLING,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.SECURITY]: KNOWLEDGE_BASE_CATEGORY.ICONS.SECURITY,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.PRIVACY]: KNOWLEDGE_BASE_CATEGORY.ICONS.PRIVACY,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.LEGAL]: KNOWLEDGE_BASE_CATEGORY.ICONS.LEGAL,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.TROUBLESHOOTING]: KNOWLEDGE_BASE_CATEGORY.ICONS.TROUBLESHOOTING,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.TUTORIAL]: KNOWLEDGE_BASE_CATEGORY.ICONS.TUTORIAL,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.FAQ]: KNOWLEDGE_BASE_CATEGORY.ICONS.FAQ,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.RELEASE]: KNOWLEDGE_BASE_CATEGORY.ICONS.RELEASE,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.POLICY]: KNOWLEDGE_BASE_CATEGORY.ICONS.POLICY,
  };
  return icons[category] || '📋';
}

export function knowledgeBaseCategoryGetColor(
  category: KnowledgeBaseCategoryType
): KnowledgeBaseCategoryColor {
  const colors: Record<KnowledgeBaseCategoryType, KnowledgeBaseCategoryColor> = {
    [KNOWLEDGE_BASE_CATEGORY.TYPES.GENERAL]: KNOWLEDGE_BASE_CATEGORY.COLORS.GENERAL,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.ACCOUNT]: KNOWLEDGE_BASE_CATEGORY.COLORS.ACCOUNT,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.PAYMENT]: KNOWLEDGE_BASE_CATEGORY.COLORS.PAYMENT,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.ORDER]: KNOWLEDGE_BASE_CATEGORY.COLORS.ORDER,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.SHIPPING]: KNOWLEDGE_BASE_CATEGORY.COLORS.SHIPPING,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.PRODUCT]: KNOWLEDGE_BASE_CATEGORY.COLORS.PRODUCT,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.TECHNICAL]: KNOWLEDGE_BASE_CATEGORY.COLORS.TECHNICAL,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.BILLING]: KNOWLEDGE_BASE_CATEGORY.COLORS.BILLING,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.SECURITY]: KNOWLEDGE_BASE_CATEGORY.COLORS.SECURITY,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.PRIVACY]: KNOWLEDGE_BASE_CATEGORY.COLORS.PRIVACY,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.LEGAL]: KNOWLEDGE_BASE_CATEGORY.COLORS.LEGAL,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.TROUBLESHOOTING]: KNOWLEDGE_BASE_CATEGORY.COLORS.TROUBLESHOOTING,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.TUTORIAL]: KNOWLEDGE_BASE_CATEGORY.COLORS.TUTORIAL,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.FAQ]: KNOWLEDGE_BASE_CATEGORY.COLORS.FAQ,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.RELEASE]: KNOWLEDGE_BASE_CATEGORY.COLORS.RELEASE,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.POLICY]: KNOWLEDGE_BASE_CATEGORY.COLORS.POLICY,
  };
  return colors[category] || '#gray-400';
}

export function knowledgeBaseCategoryGetPriority(category: KnowledgeBaseCategoryType): string {
  const priorities: Record<KnowledgeBaseCategoryType, string> = {
    [KNOWLEDGE_BASE_CATEGORY.TYPES.GENERAL]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.GENERAL,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.ACCOUNT]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.ACCOUNT,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.PAYMENT]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.PAYMENT,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.ORDER]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.ORDER,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.SHIPPING]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.SHIPPING,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.PRODUCT]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.PRODUCT,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.TECHNICAL]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.TECHNICAL,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.BILLING]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.BILLING,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.SECURITY]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.SECURITY,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.PRIVACY]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.PRIVACY,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.LEGAL]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.LEGAL,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.TROUBLESHOOTING]:
      KNOWLEDGE_BASE_CATEGORY.PRIORITIES.TROUBLESHOOTING,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.TUTORIAL]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.TUTORIAL,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.FAQ]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.FAQ,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.RELEASE]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.RELEASE,
    [KNOWLEDGE_BASE_CATEGORY.TYPES.POLICY]: KNOWLEDGE_BASE_CATEGORY.PRIORITIES.POLICY,
  };
  return priorities[category] || 'medium';
}
