/**
 * Cart HTTP Status Codes Constants
 * Contains all HTTP status codes used in cart management
 */

export const CartHttpStatus = {
  // 2xx Success
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,

  // 3xx Redirection
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,

  // 4xx Client Errors
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,

  // 5xx Server Errors
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
} as const;

export type CartHttpStatusCode = (typeof CartHttpStatus)[keyof typeof CartHttpStatus];

export const CartHttpStatusMessages: Record<CartHttpStatusCode, string> = {
  [CartHttpStatus.OK]: 'Success',
  [CartHttpStatus.CREATED]: 'Cart created successfully',
  [CartHttpStatus.ACCEPTED]: 'Cart update accepted',
  [CartHttpStatus.NON_AUTHORITATIVE_INFORMATION]: 'Non-authoritative information',
  [CartHttpStatus.NO_CONTENT]: 'No content',
  [CartHttpStatus.RESET_CONTENT]: 'Reset content',
  [CartHttpStatus.PARTIAL_CONTENT]: 'Partial content',

  [CartHttpStatus.MULTIPLE_CHOICES]: 'Multiple choices',
  [CartHttpStatus.MOVED_PERMANENTLY]: 'Moved permanently',
  [CartHttpStatus.FOUND]: 'Found',
  [CartHttpStatus.SEE_OTHER]: 'See other',
  [CartHttpStatus.NOT_MODIFIED]: 'Not modified',
  [CartHttpStatus.USE_PROXY]: 'Use proxy',
  [CartHttpStatus.TEMPORARY_REDIRECT]: 'Temporary redirect',
  [CartHttpStatus.PERMANENT_REDIRECT]: 'Permanent redirect',

  [CartHttpStatus.BAD_REQUEST]: 'Bad request',
  [CartHttpStatus.UNAUTHORIZED]: 'Unauthorized',
  [CartHttpStatus.PAYMENT_REQUIRED]: 'Payment required',
  [CartHttpStatus.FORBIDDEN]: 'Forbidden',
  [CartHttpStatus.NOT_FOUND]: 'Cart not found',
  [CartHttpStatus.METHOD_NOT_ALLOWED]: 'Method not allowed',
  [CartHttpStatus.NOT_ACCEPTABLE]: 'Not acceptable',
  [CartHttpStatus.PROXY_AUTHENTICATION_REQUIRED]: 'Proxy authentication required',
  [CartHttpStatus.REQUEST_TIMEOUT]: 'Request timeout',
  [CartHttpStatus.CONFLICT]: 'Conflict',
  [CartHttpStatus.GONE]: 'Gone',
  [CartHttpStatus.LENGTH_REQUIRED]: 'Length required',
  [CartHttpStatus.PRECONDITION_FAILED]: 'Precondition failed',
  [CartHttpStatus.PAYLOAD_TOO_LARGE]: 'Payload too large',
  [CartHttpStatus.URI_TOO_LONG]: 'URI too long',
  [CartHttpStatus.UNSUPPORTED_MEDIA_TYPE]: 'Unsupported media type',
  [CartHttpStatus.RANGE_NOT_SATISFIABLE]: 'Range not satisfiable',
  [CartHttpStatus.EXPECTATION_FAILED]: 'Expectation failed',
  [CartHttpStatus.IM_A_TEAPOT]: 'Im a teapot',
  [CartHttpStatus.MISDIRECTED_REQUEST]: 'Misdirected request',
  [CartHttpStatus.UNPROCESSABLE_ENTITY]: 'Unprocessable entity',
  [CartHttpStatus.LOCKED]: 'Locked',
  [CartHttpStatus.FAILED_DEPENDENCY]: 'Failed dependency',
  [CartHttpStatus.TOO_EARLY]: 'Too early',
  [CartHttpStatus.UPGRADE_REQUIRED]: 'Upgrade required',
  [CartHttpStatus.PRECONDITION_REQUIRED]: 'Precondition required',
  [CartHttpStatus.TOO_MANY_REQUESTS]: 'Too many requests',
  [CartHttpStatus.REQUEST_HEADER_FIELDS_TOO_LARGE]: 'Request header fields too large',
  [CartHttpStatus.UNAVAILABLE_FOR_LEGAL_REASONS]: 'Unavailable for legal reasons',

  [CartHttpStatus.INTERNAL_SERVER_ERROR]: 'Internal server error',
  [CartHttpStatus.NOT_IMPLEMENTED]: 'Not implemented',
  [CartHttpStatus.BAD_GATEWAY]: 'Bad gateway',
  [CartHttpStatus.SERVICE_UNAVAILABLE]: 'Service unavailable',
  [CartHttpStatus.GATEWAY_TIMEOUT]: 'Gateway timeout',
  [CartHttpStatus.HTTP_VERSION_NOT_SUPPORTED]: 'HTTP version not supported',
  [CartHttpStatus.VARIANT_ALSO_NEGOTIATES]: 'Variant also negotiates',
  [CartHttpStatus.INSUFFICIENT_STORAGE]: 'Insufficient storage',
  [CartHttpStatus.LOOP_DETECTED]: 'Loop detected',
  [CartHttpStatus.NOT_EXTENDED]: 'Not extended',
  [CartHttpStatus.NETWORK_AUTHENTICATION_REQUIRED]: 'Network authentication required',
};

export const CartHttpStatusCategories = {
  SUCCESS: [200, 201, 202, 203, 204, 205, 206],
  REDIRECTION: [300, 301, 302, 303, 304, 305, 307, 308],
  CLIENT_ERROR: [
    400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418,
    421, 422, 423, 424, 425, 426, 428, 429, 431, 451,
  ],
  SERVER_ERROR: [500, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511],
} as const;
