/**
 * Social Media Status Constants
 * Status definitions for social media content lifecycle
 */

export const MARKETINGSOCIAL_STATUS = {
  // Social Media Content Statuses
  STATUSES: {
    DRAFT: 'draft',
    PENDING_APPROVAL: 'pending_approval',
    APPROVED: 'approved',
    REJECTED: 'rejected',
    SCHEDULED: 'scheduled',
    QUEUED: 'queued',
    PROCESSING: 'processing',
    PUBLISHED: 'published',
    LIVE: 'live',
    ENDED: 'ended',
    FAILED: 'failed',
    DELETED: 'deleted',
    ARCHIVED: 'archived',
    PAUSED: 'paused',
    EXPIRED: 'expired',
    BOOSTED: 'boosted',
    PROMOTED: 'promoted',
    SPONSORED: 'sponsored',
    REPORTED: 'reported',
    UNDER_REVIEW: 'under_review',
    CANCELLED: 'cancelled',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    DRAFT: '#6B7280',
    PENDING_APPROVAL: '#F59E0B',
    APPROVED: '#10B981',
    REJECTED: '#EF4444',
    SCHEDULED: '#3B82F6',
    QUEUED: '#8B5CF6',
    PROCESSING: '#3B82F6',
    PUBLISHED: '#10B981',
    LIVE: '#10B981',
    ENDED: '#6B7280',
    FAILED: '#EF4444',
    DELETED: '#6B7280',
    ARCHIVED: '#6B7280',
    PAUSED: '#F59E0B',
    EXPIRED: '#6B7280',
    BOOSTED: '#10B981',
    PROMOTED: '#10B981',
    SPONSORED: '#10B981',
    REPORTED: '#EF4444',
    UNDER_REVIEW: '#F59E0B',
    CANCELLED: '#6B7280',
  } as const,

  // Status Categories
  CATEGORIES: {
    DRAFT: 'draft',
    PENDING: 'pending',
    APPROVED: 'approved',
    SCHEDULED: 'scheduled',
    PUBLISHED: 'published',
    FAILED: 'failed',
    ARCHIVED: 'archived',
    CANCELLED: 'cancelled',
    ACTIVE: 'active',
  } as const,

  // Status Priority Order
  ORDER: {
    DRAFT: 0,
    PENDING_APPROVAL: 1,
    APPROVED: 2,
    REJECTED: 3,
    SCHEDULED: 4,
    QUEUED: 5,
    PROCESSING: 6,
    PUBLISHED: 7,
    LIVE: 8,
    BOOSTED: 9,
    PROMOTED: 10,
    SPONSORED: 11,
    ENDED: 12,
    PAUSED: 13,
    EXPIRED: 14,
    REPORTED: 15,
    UNDER_REVIEW: 16,
    FAILED: 17,
    DELETED: 18,
    CANCELLED: 19,
    ARCHIVED: 20,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    DRAFT_TO_PENDING: 'draft_to_pending',
    DRAFT_TO_CANCELLED: 'draft_to_cancelled',
    DRAFT_TO_ARCHIVED: 'draft_to_archived',
    PENDING_TO_APPROVED: 'pending_to_approved',
    PENDING_TO_REJECTED: 'pending_to_rejected',
    PENDING_TO_CANCELLED: 'pending_to_cancelled',
    APPROVED_TO_SCHEDULED: 'approved_to_scheduled',
    APPROVED_TO_REJECTED: 'approved_to_rejected',
    APPROVED_TO_CANCELLED: 'approved_to_cancelled',
    REJECTED_TO_DRAFT: 'rejected_to_draft',
    REJECTED_TO_ARCHIVED: 'rejected_to_archived',
    SCHEDULED_TO_QUEUED: 'scheduled_to_queued',
    SCHEDULED_TO_CANCELLED: 'scheduled_to_cancelled',
    QUEUED_TO_PROCESSING: 'queued_to_processing',
    QUEUED_TO_CANCELLED: 'queued_to_cancelled',
    PROCESSING_TO_PUBLISHED: 'processing_to_published',
    PROCESSING_TO_LIVE: 'processing_to_live',
    PROCESSING_TO_FAILED: 'processing_to_failed',
    PROCESSING_TO_CANCELLED: 'processing_to_cancelled',
    PUBLISHED_TO_LIVE: 'published_to_live',
    PUBLISHED_TO_BOOSTED: 'published_to_boosted',
    PUBLISHED_TO_PROMOTED: 'published_to_promoted',
    PUBLISHED_TO_SPONSORED: 'published_to_sponsored',
    PUBLISHED_TO_ENDED: 'published_to_ended',
    PUBLISHED_TO_PAUSED: 'published_to_paused',
    PUBLISHED_TO_EXPIRED: 'published_to_expired',
    PUBLISHED_TO_REPORTED: 'published_to_reported',
    LIVE_TO_ENDED: 'live_to_ended',
    LIVE_TO_PAUSED: 'live_to_paused',
    LIVE_TO_EXPIRED: 'live_to_expired',
    LIVE_TO_REPORTED: 'live_to_reported',
    BOOSTED_TO_ENDED: 'boosted_to_ended',
    BOOSTED_TO_EXPIRED: 'boosted_to_expired',
    PROMOTED_TO_ENDED: 'promoted_to_ended',
    PROMOTED_TO_EXPIRED: 'promoted_to_expired',
    SPONSORED_TO_ENDED: 'sponsored_to_ended',
    SPONSORED_TO_EXPIRED: 'sponsored_to_expired',
    ENDED_TO_ARCHIVED: 'ended_to_archived',
    PAUSED_TO_PUBLISHED: 'paused_to_published',
    PAUSED_TO_LIVE: 'paused_to_live',
    PAUSED_TO_CANCELLED: 'paused_to_cancelled',
    EXPIRED_TO_ARCHIVED: 'expired_to_archived',
    FAILED_TO_DRAFT: 'failed_to_draft',
    FAILED_TO_ARCHIVED: 'failed_to_archived',
    REPORTED_TO_UNDER_REVIEW: 'reported_to_under_review',
    REPORTED_TO_ARCHIVED: 'reported_to_archived',
    UNDER_REVIEW_TO_PUBLISHED: 'under_review_to_published',
    UNDER_REVIEW_TO_FAILED: 'under_review_to_failed',
    UNDER_REVIEW_TO_ARCHIVED: 'under_review_to_archived',
    CANCELLED_TO_ARCHIVED: 'cancelled_to_archived',
    DELETED_TO_ARCHIVED: 'deleted_to_archived',
  } as const,
} as const;

// Social Media Statuses
export type MarketingSocialStatusType =
  (typeof MARKETINGSOCIAL_STATUS.STATUSES)[keyof typeof MARKETINGSOCIAL_STATUS.STATUSES];

// Status Colors
export type MarketingSocialStatusColor =
  (typeof MARKETINGSOCIAL_STATUS.COLORS)[keyof typeof MARKETINGSOCIAL_STATUS.COLORS];

// Status Categories
export type MarketingSocialStatusCategory =
  (typeof MARKETINGSOCIAL_STATUS.CATEGORIES)[keyof typeof MARKETINGSOCIAL_STATUS.CATEGORIES];

// Status Priority Order
export type MarketingSocialStatusOrder =
  (typeof MARKETINGSOCIAL_STATUS.ORDER)[keyof typeof MARKETINGSOCIAL_STATUS.ORDER];

// Status Transitions
export type MarketingSocialStatusTransition =
  (typeof MARKETINGSOCIAL_STATUS.TRANSITIONS)[keyof typeof MARKETINGSOCIAL_STATUS.TRANSITIONS];

// Utility Functions
export function marketingsocialGetStatusLabel(status: MarketingSocialStatusType): string {
  const labels: Record<MarketingSocialStatusType, string> = {
    [MARKETINGSOCIAL_STATUS.STATUSES.DRAFT]: 'Draft',
    [MARKETINGSOCIAL_STATUS.STATUSES.PENDING_APPROVAL]: 'Pending Approval',
    [MARKETINGSOCIAL_STATUS.STATUSES.APPROVED]: 'Approved',
    [MARKETINGSOCIAL_STATUS.STATUSES.REJECTED]: 'Rejected',
    [MARKETINGSOCIAL_STATUS.STATUSES.SCHEDULED]: 'Scheduled',
    [MARKETINGSOCIAL_STATUS.STATUSES.QUEUED]: 'Queued',
    [MARKETINGSOCIAL_STATUS.STATUSES.PROCESSING]: 'Processing',
    [MARKETINGSOCIAL_STATUS.STATUSES.PUBLISHED]: 'Published',
    [MARKETINGSOCIAL_STATUS.STATUSES.LIVE]: 'Live',
    [MARKETINGSOCIAL_STATUS.STATUSES.ENDED]: 'Ended',
    [MARKETINGSOCIAL_STATUS.STATUSES.FAILED]: 'Failed',
    [MARKETINGSOCIAL_STATUS.STATUSES.DELETED]: 'Deleted',
    [MARKETINGSOCIAL_STATUS.STATUSES.ARCHIVED]: 'Archived',
    [MARKETINGSOCIAL_STATUS.STATUSES.PAUSED]: 'Paused',
    [MARKETINGSOCIAL_STATUS.STATUSES.EXPIRED]: 'Expired',
    [MARKETINGSOCIAL_STATUS.STATUSES.BOOSTED]: 'Boosted',
    [MARKETINGSOCIAL_STATUS.STATUSES.PROMOTED]: 'Promoted',
    [MARKETINGSOCIAL_STATUS.STATUSES.SPONSORED]: 'Sponsored',
    [MARKETINGSOCIAL_STATUS.STATUSES.REPORTED]: 'Reported',
    [MARKETINGSOCIAL_STATUS.STATUSES.UNDER_REVIEW]: 'Under Review',
    [MARKETINGSOCIAL_STATUS.STATUSES.CANCELLED]: 'Cancelled',
  };
  return labels[status] || 'Unknown Status';
}

export function marketingsocialGetStatusColor(
  status: MarketingSocialStatusType
): MarketingSocialStatusColor {
  const colors: Record<MarketingSocialStatusType, MarketingSocialStatusColor> = {
    [MARKETINGSOCIAL_STATUS.STATUSES.DRAFT]: MARKETINGSOCIAL_STATUS.COLORS.DRAFT,
    [MARKETINGSOCIAL_STATUS.STATUSES.PENDING_APPROVAL]:
      MARKETINGSOCIAL_STATUS.COLORS.PENDING_APPROVAL,
    [MARKETINGSOCIAL_STATUS.STATUSES.APPROVED]: MARKETINGSOCIAL_STATUS.COLORS.APPROVED,
    [MARKETINGSOCIAL_STATUS.STATUSES.REJECTED]: MARKETINGSOCIAL_STATUS.COLORS.REJECTED,
    [MARKETINGSOCIAL_STATUS.STATUSES.SCHEDULED]: MARKETINGSOCIAL_STATUS.COLORS.SCHEDULED,
    [MARKETINGSOCIAL_STATUS.STATUSES.QUEUED]: MARKETINGSOCIAL_STATUS.COLORS.QUEUED,
    [MARKETINGSOCIAL_STATUS.STATUSES.PROCESSING]: MARKETINGSOCIAL_STATUS.COLORS.PROCESSING,
    [MARKETINGSOCIAL_STATUS.STATUSES.PUBLISHED]: MARKETINGSOCIAL_STATUS.COLORS.PUBLISHED,
    [MARKETINGSOCIAL_STATUS.STATUSES.LIVE]: MARKETINGSOCIAL_STATUS.COLORS.LIVE,
    [MARKETINGSOCIAL_STATUS.STATUSES.ENDED]: MARKETINGSOCIAL_STATUS.COLORS.ENDED,
    [MARKETINGSOCIAL_STATUS.STATUSES.FAILED]: MARKETINGSOCIAL_STATUS.COLORS.FAILED,
    [MARKETINGSOCIAL_STATUS.STATUSES.DELETED]: MARKETINGSOCIAL_STATUS.COLORS.DELETED,
    [MARKETINGSOCIAL_STATUS.STATUSES.ARCHIVED]: MARKETINGSOCIAL_STATUS.COLORS.ARCHIVED,
    [MARKETINGSOCIAL_STATUS.STATUSES.PAUSED]: MARKETINGSOCIAL_STATUS.COLORS.PAUSED,
    [MARKETINGSOCIAL_STATUS.STATUSES.EXPIRED]: MARKETINGSOCIAL_STATUS.COLORS.EXPIRED,
    [MARKETINGSOCIAL_STATUS.STATUSES.BOOSTED]: MARKETINGSOCIAL_STATUS.COLORS.BOOSTED,
    [MARKETINGSOCIAL_STATUS.STATUSES.PROMOTED]: MARKETINGSOCIAL_STATUS.COLORS.PROMOTED,
    [MARKETINGSOCIAL_STATUS.STATUSES.SPONSORED]: MARKETINGSOCIAL_STATUS.COLORS.SPONSORED,
    [MARKETINGSOCIAL_STATUS.STATUSES.REPORTED]: MARKETINGSOCIAL_STATUS.COLORS.REPORTED,
    [MARKETINGSOCIAL_STATUS.STATUSES.UNDER_REVIEW]: MARKETINGSOCIAL_STATUS.COLORS.UNDER_REVIEW,
    [MARKETINGSOCIAL_STATUS.STATUSES.CANCELLED]: MARKETINGSOCIAL_STATUS.COLORS.CANCELLED,
  };
  return colors[status] || MARKETINGSOCIAL_STATUS.COLORS.DRAFT;
}

export function marketingsocialGetStatusCategory(
  status: MarketingSocialStatusType
): MarketingSocialStatusCategory {
  const categories: Record<MarketingSocialStatusType, MarketingSocialStatusCategory> = {
    [MARKETINGSOCIAL_STATUS.STATUSES.DRAFT]: MARKETINGSOCIAL_STATUS.CATEGORIES.DRAFT,
    [MARKETINGSOCIAL_STATUS.STATUSES.PENDING_APPROVAL]: MARKETINGSOCIAL_STATUS.CATEGORIES.PENDING,
    [MARKETINGSOCIAL_STATUS.STATUSES.APPROVED]: MARKETINGSOCIAL_STATUS.CATEGORIES.APPROVED,
    [MARKETINGSOCIAL_STATUS.STATUSES.REJECTED]: MARKETINGSOCIAL_STATUS.CATEGORIES.FAILED,
    [MARKETINGSOCIAL_STATUS.STATUSES.SCHEDULED]: MARKETINGSOCIAL_STATUS.CATEGORIES.SCHEDULED,
    [MARKETINGSOCIAL_STATUS.STATUSES.QUEUED]: MARKETINGSOCIAL_STATUS.CATEGORIES.SCHEDULED,
    [MARKETINGSOCIAL_STATUS.STATUSES.PROCESSING]: MARKETINGSOCIAL_STATUS.CATEGORIES.SCHEDULED,
    [MARKETINGSOCIAL_STATUS.STATUSES.PUBLISHED]: MARKETINGSOCIAL_STATUS.CATEGORIES.PUBLISHED,
    [MARKETINGSOCIAL_STATUS.STATUSES.LIVE]: MARKETINGSOCIAL_STATUS.CATEGORIES.ACTIVE,
    [MARKETINGSOCIAL_STATUS.STATUSES.BOOSTED]: MARKETINGSOCIAL_STATUS.CATEGORIES.ACTIVE,
    [MARKETINGSOCIAL_STATUS.STATUSES.PROMOTED]: MARKETINGSOCIAL_STATUS.CATEGORIES.ACTIVE,
    [MARKETINGSOCIAL_STATUS.STATUSES.SPONSORED]: MARKETINGSOCIAL_STATUS.CATEGORIES.ACTIVE,
    [MARKETINGSOCIAL_STATUS.STATUSES.ENDED]: MARKETINGSOCIAL_STATUS.CATEGORIES.ARCHIVED,
    [MARKETINGSOCIAL_STATUS.STATUSES.PAUSED]: MARKETINGSOCIAL_STATUS.CATEGORIES.SCHEDULED,
    [MARKETINGSOCIAL_STATUS.STATUSES.EXPIRED]: MARKETINGSOCIAL_STATUS.CATEGORIES.ARCHIVED,
    [MARKETINGSOCIAL_STATUS.STATUSES.FAILED]: MARKETINGSOCIAL_STATUS.CATEGORIES.FAILED,
    [MARKETINGSOCIAL_STATUS.STATUSES.DELETED]: MARKETINGSOCIAL_STATUS.CATEGORIES.CANCELLED,
    [MARKETINGSOCIAL_STATUS.STATUSES.CANCELLED]: MARKETINGSOCIAL_STATUS.CATEGORIES.CANCELLED,
    [MARKETINGSOCIAL_STATUS.STATUSES.ARCHIVED]: MARKETINGSOCIAL_STATUS.CATEGORIES.ARCHIVED,
    [MARKETINGSOCIAL_STATUS.STATUSES.REPORTED]: MARKETINGSOCIAL_STATUS.CATEGORIES.FAILED,
    [MARKETINGSOCIAL_STATUS.STATUSES.UNDER_REVIEW]: MARKETINGSOCIAL_STATUS.CATEGORIES.PENDING,
  };
  return categories[status] || MARKETINGSOCIAL_STATUS.CATEGORIES.DRAFT;
}

export function marketingsocialIsPublished(status: MarketingSocialStatusType): boolean {
  const publishedStatuses: MarketingSocialStatusType[] = [
    MARKETINGSOCIAL_STATUS.STATUSES.PUBLISHED,
    MARKETINGSOCIAL_STATUS.STATUSES.LIVE,
    MARKETINGSOCIAL_STATUS.STATUSES.BOOSTED,
    MARKETINGSOCIAL_STATUS.STATUSES.PROMOTED,
    MARKETINGSOCIAL_STATUS.STATUSES.SPONSORED,
  ];
  return publishedStatuses.includes(status);
}

export function marketingsocialIsActive(status: MarketingSocialStatusType): boolean {
  const activeStatuses: MarketingSocialStatusType[] = [
    MARKETINGSOCIAL_STATUS.STATUSES.LIVE,
    MARKETINGSOCIAL_STATUS.STATUSES.BOOSTED,
    MARKETINGSOCIAL_STATUS.STATUSES.PROMOTED,
    MARKETINGSOCIAL_STATUS.STATUSES.SPONSORED,
    MARKETINGSOCIAL_STATUS.STATUSES.PUBLISHED,
  ];
  return activeStatuses.includes(status);
}

export function marketingsocialIsPending(status: MarketingSocialStatusType): boolean {
  const pendingStatuses: MarketingSocialStatusType[] = [
    MARKETINGSOCIAL_STATUS.STATUSES.PENDING_APPROVAL,
    MARKETINGSOCIAL_STATUS.STATUSES.APPROVED,
    MARKETINGSOCIAL_STATUS.STATUSES.SCHEDULED,
    MARKETINGSOCIAL_STATUS.STATUSES.QUEUED,
    MARKETINGSOCIAL_STATUS.STATUSES.PROCESSING,
    MARKETINGSOCIAL_STATUS.STATUSES.UNDER_REVIEW,
  ];
  return pendingStatuses.includes(status);
}

export function marketingsocialCanTransition(
  currentStatus: MarketingSocialStatusType,
  targetStatus: MarketingSocialStatusType
): boolean {
  const validTransitions: Record<MarketingSocialStatusType, MarketingSocialStatusType[]> = {
    [MARKETINGSOCIAL_STATUS.STATUSES.DRAFT]: [
      MARKETINGSOCIAL_STATUS.STATUSES.PENDING_APPROVAL,
      MARKETINGSOCIAL_STATUS.STATUSES.CANCELLED,
      MARKETINGSOCIAL_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.PENDING_APPROVAL]: [
      MARKETINGSOCIAL_STATUS.STATUSES.APPROVED,
      MARKETINGSOCIAL_STATUS.STATUSES.REJECTED,
      MARKETINGSOCIAL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.APPROVED]: [
      MARKETINGSOCIAL_STATUS.STATUSES.SCHEDULED,
      MARKETINGSOCIAL_STATUS.STATUSES.REJECTED,
      MARKETINGSOCIAL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.REJECTED]: [
      MARKETINGSOCIAL_STATUS.STATUSES.DRAFT,
      MARKETINGSOCIAL_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.SCHEDULED]: [
      MARKETINGSOCIAL_STATUS.STATUSES.QUEUED,
      MARKETINGSOCIAL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.QUEUED]: [
      MARKETINGSOCIAL_STATUS.STATUSES.PROCESSING,
      MARKETINGSOCIAL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.PROCESSING]: [
      MARKETINGSOCIAL_STATUS.STATUSES.PUBLISHED,
      MARKETINGSOCIAL_STATUS.STATUSES.LIVE,
      MARKETINGSOCIAL_STATUS.STATUSES.FAILED,
      MARKETINGSOCIAL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.PUBLISHED]: [
      MARKETINGSOCIAL_STATUS.STATUSES.LIVE,
      MARKETINGSOCIAL_STATUS.STATUSES.BOOSTED,
      MARKETINGSOCIAL_STATUS.STATUSES.PROMOTED,
      MARKETINGSOCIAL_STATUS.STATUSES.SPONSORED,
      MARKETINGSOCIAL_STATUS.STATUSES.ENDED,
      MARKETINGSOCIAL_STATUS.STATUSES.PAUSED,
      MARKETINGSOCIAL_STATUS.STATUSES.EXPIRED,
      MARKETINGSOCIAL_STATUS.STATUSES.REPORTED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.LIVE]: [
      MARKETINGSOCIAL_STATUS.STATUSES.ENDED,
      MARKETINGSOCIAL_STATUS.STATUSES.PAUSED,
      MARKETINGSOCIAL_STATUS.STATUSES.EXPIRED,
      MARKETINGSOCIAL_STATUS.STATUSES.REPORTED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.BOOSTED]: [
      MARKETINGSOCIAL_STATUS.STATUSES.ENDED,
      MARKETINGSOCIAL_STATUS.STATUSES.EXPIRED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.PROMOTED]: [
      MARKETINGSOCIAL_STATUS.STATUSES.ENDED,
      MARKETINGSOCIAL_STATUS.STATUSES.EXPIRED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.SPONSORED]: [
      MARKETINGSOCIAL_STATUS.STATUSES.ENDED,
      MARKETINGSOCIAL_STATUS.STATUSES.EXPIRED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.PAUSED]: [
      MARKETINGSOCIAL_STATUS.STATUSES.PUBLISHED,
      MARKETINGSOCIAL_STATUS.STATUSES.LIVE,
      MARKETINGSOCIAL_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.ENDED]: [MARKETINGSOCIAL_STATUS.STATUSES.ARCHIVED],
    [MARKETINGSOCIAL_STATUS.STATUSES.EXPIRED]: [MARKETINGSOCIAL_STATUS.STATUSES.ARCHIVED],
    [MARKETINGSOCIAL_STATUS.STATUSES.FAILED]: [
      MARKETINGSOCIAL_STATUS.STATUSES.DRAFT,
      MARKETINGSOCIAL_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.REPORTED]: [
      MARKETINGSOCIAL_STATUS.STATUSES.UNDER_REVIEW,
      MARKETINGSOCIAL_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.UNDER_REVIEW]: [
      MARKETINGSOCIAL_STATUS.STATUSES.PUBLISHED,
      MARKETINGSOCIAL_STATUS.STATUSES.FAILED,
      MARKETINGSOCIAL_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGSOCIAL_STATUS.STATUSES.CANCELLED]: [MARKETINGSOCIAL_STATUS.STATUSES.ARCHIVED],
    [MARKETINGSOCIAL_STATUS.STATUSES.DELETED]: [MARKETINGSOCIAL_STATUS.STATUSES.ARCHIVED],
    [MARKETINGSOCIAL_STATUS.STATUSES.ARCHIVED]: [],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
