/**
 * AI Insight Status Constants
 * Status tracking for insight lifecycle
 */

// First define the status types
export const AI_INSIGHT_STATUS_TYPES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Discovery States
  DISCOVERING: 'discovering',
  ANALYZING: 'analyzing',
  GENERATING: 'generating',
  VALIDATING: 'validating',

  // Intermediate States
  DISCOVERED: 'discovered',
  ANALYZED: 'analyzed',
  GENERATED: 'generated',
  VALIDATED: 'validated',
  OPTIMIZED: 'optimized',

  // Delivery States
  DELIVERING: 'delivering',
  DELIVERED: 'delivered',
  CACHED: 'cached',

  // Terminal States
  COMPLETED: 'completed',
  FAILED: 'failed',
  EXPIRED: 'expired',
  ARCHIVED: 'archived',
} as const;

export type AIInsightStatusType =
  (typeof AI_INSIGHT_STATUS_TYPES)[keyof typeof AI_INSIGHT_STATUS_TYPES];

export const AI_INSIGHT_STATUS = {
  // Status Types
  STATUSES: AI_INSIGHT_STATUS_TYPES,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    DELIVERED: 'delivered',
    COMPLETED: 'completed',
    FAILED: 'failed',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_INSIGHT_STATUS_TYPES.CREATED]: '#gray',
    [AI_INSIGHT_STATUS_TYPES.QUEUED]: '#gray',
    [AI_INSIGHT_STATUS_TYPES.PENDING]: '#yellow',
    [AI_INSIGHT_STATUS_TYPES.DISCOVERING]: '#blue',
    [AI_INSIGHT_STATUS_TYPES.ANALYZING]: '#blue',
    [AI_INSIGHT_STATUS_TYPES.GENERATING]: '#blue',
    [AI_INSIGHT_STATUS_TYPES.VALIDATING]: '#purple',
    [AI_INSIGHT_STATUS_TYPES.DISCOVERED]: '#green',
    [AI_INSIGHT_STATUS_TYPES.ANALYZED]: '#green',
    [AI_INSIGHT_STATUS_TYPES.GENERATED]: '#green',
    [AI_INSIGHT_STATUS_TYPES.VALIDATED]: '#green',
    [AI_INSIGHT_STATUS_TYPES.OPTIMIZED]: '#green',
    [AI_INSIGHT_STATUS_TYPES.DELIVERING]: '#orange',
    [AI_INSIGHT_STATUS_TYPES.DELIVERED]: '#green',
    [AI_INSIGHT_STATUS_TYPES.CACHED]: '#green',
    [AI_INSIGHT_STATUS_TYPES.COMPLETED]: '#green',
    [AI_INSIGHT_STATUS_TYPES.FAILED]: '#red',
    [AI_INSIGHT_STATUS_TYPES.EXPIRED]: '#gray',
    [AI_INSIGHT_STATUS_TYPES.ARCHIVED]: '#gray',
  } as const,
} as const;

// Status Categories
export type AIInsightStatusCategory =
  (typeof AI_INSIGHT_STATUS.CATEGORIES)[keyof typeof AI_INSIGHT_STATUS.CATEGORIES];

// Status Severity
export type AIInsightStatusSeverity =
  (typeof AI_INSIGHT_STATUS.SEVERITY)[keyof typeof AI_INSIGHT_STATUS.SEVERITY];

// Status Colors
export type AIInsightStatusColor =
  (typeof AI_INSIGHT_STATUS.COLORS)[keyof typeof AI_INSIGHT_STATUS.COLORS];

// Utility Functions
export function getInsightStatusLabel(status: AIInsightStatusType): string {
  const labels: Record<AIInsightStatusType, string> = {
    [AI_INSIGHT_STATUS_TYPES.CREATED]: 'Created',
    [AI_INSIGHT_STATUS_TYPES.QUEUED]: 'Queued',
    [AI_INSIGHT_STATUS_TYPES.PENDING]: 'Pending',
    [AI_INSIGHT_STATUS_TYPES.DISCOVERING]: 'Discovering',
    [AI_INSIGHT_STATUS_TYPES.ANALYZING]: 'Analyzing',
    [AI_INSIGHT_STATUS_TYPES.GENERATING]: 'Generating',
    [AI_INSIGHT_STATUS_TYPES.VALIDATING]: 'Validating',
    [AI_INSIGHT_STATUS_TYPES.DISCOVERED]: 'Discovered',
    [AI_INSIGHT_STATUS_TYPES.ANALYZED]: 'Analyzed',
    [AI_INSIGHT_STATUS_TYPES.GENERATED]: 'Generated',
    [AI_INSIGHT_STATUS_TYPES.VALIDATED]: 'Validated',
    [AI_INSIGHT_STATUS_TYPES.OPTIMIZED]: 'Optimized',
    [AI_INSIGHT_STATUS_TYPES.DELIVERING]: 'Delivering',
    [AI_INSIGHT_STATUS_TYPES.DELIVERED]: 'Delivered',
    [AI_INSIGHT_STATUS_TYPES.CACHED]: 'Cached',
    [AI_INSIGHT_STATUS_TYPES.COMPLETED]: 'Completed',
    [AI_INSIGHT_STATUS_TYPES.FAILED]: 'Failed',
    [AI_INSIGHT_STATUS_TYPES.EXPIRED]: 'Expired',
    [AI_INSIGHT_STATUS_TYPES.ARCHIVED]: 'Archived',
  };
  return labels[status] || 'Unknown';
}

export function getInsightStatusCategory(status: AIInsightStatusType): AIInsightStatusCategory {
  const categories: Record<AIInsightStatusType, AIInsightStatusCategory> = {
    [AI_INSIGHT_STATUS_TYPES.CREATED]: AI_INSIGHT_STATUS.CATEGORIES.PENDING,
    [AI_INSIGHT_STATUS_TYPES.QUEUED]: AI_INSIGHT_STATUS.CATEGORIES.PENDING,
    [AI_INSIGHT_STATUS_TYPES.PENDING]: AI_INSIGHT_STATUS.CATEGORIES.PENDING,
    [AI_INSIGHT_STATUS_TYPES.DISCOVERING]: AI_INSIGHT_STATUS.CATEGORIES.PROCESSING,
    [AI_INSIGHT_STATUS_TYPES.ANALYZING]: AI_INSIGHT_STATUS.CATEGORIES.PROCESSING,
    [AI_INSIGHT_STATUS_TYPES.GENERATING]: AI_INSIGHT_STATUS.CATEGORIES.PROCESSING,
    [AI_INSIGHT_STATUS_TYPES.VALIDATING]: AI_INSIGHT_STATUS.CATEGORIES.PROCESSING,
    [AI_INSIGHT_STATUS_TYPES.DISCOVERED]: AI_INSIGHT_STATUS.CATEGORIES.PROCESSING,
    [AI_INSIGHT_STATUS_TYPES.ANALYZED]: AI_INSIGHT_STATUS.CATEGORIES.PROCESSING,
    [AI_INSIGHT_STATUS_TYPES.GENERATED]: AI_INSIGHT_STATUS.CATEGORIES.PROCESSING,
    [AI_INSIGHT_STATUS_TYPES.VALIDATED]: AI_INSIGHT_STATUS.CATEGORIES.PROCESSING,
    [AI_INSIGHT_STATUS_TYPES.OPTIMIZED]: AI_INSIGHT_STATUS.CATEGORIES.PROCESSING,
    [AI_INSIGHT_STATUS_TYPES.DELIVERING]: AI_INSIGHT_STATUS.CATEGORIES.DELIVERED,
    [AI_INSIGHT_STATUS_TYPES.DELIVERED]: AI_INSIGHT_STATUS.CATEGORIES.DELIVERED,
    [AI_INSIGHT_STATUS_TYPES.CACHED]: AI_INSIGHT_STATUS.CATEGORIES.DELIVERED,
    [AI_INSIGHT_STATUS_TYPES.COMPLETED]: AI_INSIGHT_STATUS.CATEGORIES.COMPLETED,
    [AI_INSIGHT_STATUS_TYPES.FAILED]: AI_INSIGHT_STATUS.CATEGORIES.FAILED,
    [AI_INSIGHT_STATUS_TYPES.EXPIRED]: AI_INSIGHT_STATUS.CATEGORIES.FAILED,
    [AI_INSIGHT_STATUS_TYPES.ARCHIVED]: AI_INSIGHT_STATUS.CATEGORIES.COMPLETED,
  };
  return categories[status] || AI_INSIGHT_STATUS.CATEGORIES.PENDING;
}

export function getInsightStatusSeverity(status: AIInsightStatusType): AIInsightStatusSeverity {
  const severities: Record<AIInsightStatusType, AIInsightStatusSeverity> = {
    [AI_INSIGHT_STATUS_TYPES.CREATED]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.QUEUED]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.PENDING]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.DISCOVERING]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.ANALYZING]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.GENERATING]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.VALIDATING]: AI_INSIGHT_STATUS.SEVERITY.WARNING,
    [AI_INSIGHT_STATUS_TYPES.DISCOVERED]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.ANALYZED]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.GENERATED]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.VALIDATED]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.OPTIMIZED]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.DELIVERING]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.DELIVERED]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.CACHED]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.COMPLETED]: AI_INSIGHT_STATUS.SEVERITY.INFO,
    [AI_INSIGHT_STATUS_TYPES.FAILED]: AI_INSIGHT_STATUS.SEVERITY.ERROR,
    [AI_INSIGHT_STATUS_TYPES.EXPIRED]: AI_INSIGHT_STATUS.SEVERITY.WARNING,
    [AI_INSIGHT_STATUS_TYPES.ARCHIVED]: AI_INSIGHT_STATUS.SEVERITY.INFO,
  };
  return severities[status] || AI_INSIGHT_STATUS.SEVERITY.INFO;
}

export function getInsightStatusColor(status: AIInsightStatusType): AIInsightStatusColor {
  return AI_INSIGHT_STATUS.COLORS[status] || '#gray';
}

export function isInsightActive(status: AIInsightStatusType): boolean {
  const activeStatuses: AIInsightStatusType[] = [
    AI_INSIGHT_STATUS_TYPES.CREATED,
    AI_INSIGHT_STATUS_TYPES.QUEUED,
    AI_INSIGHT_STATUS_TYPES.PENDING,
    AI_INSIGHT_STATUS_TYPES.DISCOVERING,
    AI_INSIGHT_STATUS_TYPES.ANALYZING,
    AI_INSIGHT_STATUS_TYPES.GENERATING,
    AI_INSIGHT_STATUS_TYPES.VALIDATING,
    AI_INSIGHT_STATUS_TYPES.DISCOVERED,
    AI_INSIGHT_STATUS_TYPES.ANALYZED,
    AI_INSIGHT_STATUS_TYPES.GENERATED,
    AI_INSIGHT_STATUS_TYPES.VALIDATED,
    AI_INSIGHT_STATUS_TYPES.OPTIMIZED,
    AI_INSIGHT_STATUS_TYPES.DELIVERING,
  ];
  return activeStatuses.includes(status);
}

export function isInsightDelivered(status: AIInsightStatusType): boolean {
  const deliveredStatuses: AIInsightStatusType[] = [
    AI_INSIGHT_STATUS_TYPES.DELIVERED,
    AI_INSIGHT_STATUS_TYPES.CACHED,
  ];
  return deliveredStatuses.includes(status);
}

export function isInsightCompleted(status: AIInsightStatusType): boolean {
  const completedStatuses: AIInsightStatusType[] = [
    AI_INSIGHT_STATUS_TYPES.COMPLETED,
    AI_INSIGHT_STATUS_TYPES.ARCHIVED,
  ];
  return completedStatuses.includes(status);
}

export function isInsightFailed(status: AIInsightStatusType): boolean {
  const failedStatuses: AIInsightStatusType[] = [
    AI_INSIGHT_STATUS_TYPES.FAILED,
    AI_INSIGHT_STATUS_TYPES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}

export function getInsightStatusProgress(status: AIInsightStatusType): number {
  const progress: Record<AIInsightStatusType, number> = {
    [AI_INSIGHT_STATUS_TYPES.CREATED]: 0,
    [AI_INSIGHT_STATUS_TYPES.QUEUED]: 5,
    [AI_INSIGHT_STATUS_TYPES.PENDING]: 10,
    [AI_INSIGHT_STATUS_TYPES.DISCOVERING]: 25,
    [AI_INSIGHT_STATUS_TYPES.ANALYZING]: 40,
    [AI_INSIGHT_STATUS_TYPES.GENERATING]: 60,
    [AI_INSIGHT_STATUS_TYPES.VALIDATING]: 70,
    [AI_INSIGHT_STATUS_TYPES.DISCOVERED]: 30,
    [AI_INSIGHT_STATUS_TYPES.ANALYZED]: 50,
    [AI_INSIGHT_STATUS_TYPES.GENERATED]: 65,
    [AI_INSIGHT_STATUS_TYPES.VALIDATED]: 75,
    [AI_INSIGHT_STATUS_TYPES.OPTIMIZED]: 85,
    [AI_INSIGHT_STATUS_TYPES.DELIVERING]: 90,
    [AI_INSIGHT_STATUS_TYPES.DELIVERED]: 95,
    [AI_INSIGHT_STATUS_TYPES.CACHED]: 95,
    [AI_INSIGHT_STATUS_TYPES.COMPLETED]: 100,
    [AI_INSIGHT_STATUS_TYPES.FAILED]: 0,
    [AI_INSIGHT_STATUS_TYPES.EXPIRED]: 0,
    [AI_INSIGHT_STATUS_TYPES.ARCHIVED]: 100,
  };
  return progress[status] || 0;
}
