import { RECOMMENDATION_TYPE } from './recommendation-type.constants';
import {
  RECOMMENDATION_STRATEGY,
  RECOMMENDATION_STRATEGY_WEIGHT,
  RECOMMENDATION_STRATEGY_STATUS,
} from './recommendation-strategy.constants';

export const RECOMMENDATION_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  TRAINING: 'training',
  DEPLOYED: 'deployed',
  EXPIRED: 'expired',
  ARCHIVED: 'archived',
} as const;

export const RECOMMENDATION = {
  TYPE: RECOMMENDATION_TYPE,
  STATUS: RECOMMENDATION_STATUS,
  STRATEGY: {
    TYPE: RECOMMENDATION_STRATEGY,
    WEIGHT: RECOMMENDATION_STRATEGY_WEIGHT,
    STATUS: RECOMMENDATION_STRATEGY_STATUS,
  },
  MAX_RECOMMENDATIONS: 50,
  DEFAULT_COUNT: 10,
  MIN_SCORE: 0.1,
  CACHE_TTL_SECONDS: 300,
  REFRESH_INTERVAL_SECONDS: 3600,
  PERSONALIZATION_ENABLED: true,
  DIVERSITY_ENABLED: true,
  EXCLUDE_OUT_OF_STOCK: true,
  EXCLUDE_PURCHASED: false,
  RETENTION_DAYS: 90,
} as const;

export type RecommendationType = typeof RECOMMENDATION;
