/**
 * মার্কেটিং কনস্ট্যান্টস এক্সপোর্ট
 * @module Content-Marketing/marketing
 */

// মার্কেটিং বেসিক কনস্ট্যান্টসমূহ
export {
  MARKETING_MODULE_NAME,
  DEFAULT_CAMPAIGN_STATUS as DEFAULT_MARKETING_CAMPAIGN_STATUS,
  MARKETING_SORT_FIELDS,
  isValidMarketingSortField,
  isValidCampaignStatus as isValidMarketingCampaignStatus,
  isValidCampaignName as isValidMarketingCampaignName,
  isValidBudget,
  isCampaignActive as isMarketingCampaignActive,
  isCampaignCompleted as isMarketingCampaignCompleted,
  calculateRemainingBudget,
  calculateSpentPercentage,
  isCampaignEditable as isMarketingCampaignEditable,
  getDefaultCampaignStatus as getDefaultMarketingCampaignStatus,
  type MarketingSortField,
  type CampaignStatus as MarketingCampaignStatus,
  type CampaignInterface as MarketingCampaignInterface,
  type CampaignMetadata as MarketingCampaignMetadata,
  type CreateCampaignInput as CreateMarketingCampaignInput,
  type UpdateCampaignInput as UpdateMarketingCampaignInput,
  type CampaignFilter as MarketingCampaignFilter,
} from './marketing.constants';

// ক্যাম্পেইন কনস্ট্যান্টসমূহ
export {
  CAMPAIGN_MODULE_NAME,
  DEFAULT_CAMPAIGN_STATUS,
  MAX_CAMPAIGN_NAME_LENGTH,
  MAX_CAMPAIGN_DESCRIPTION_LENGTH,
  CAMPAIGN_SORT_FIELDS,
  isValidCampaignSortField,
  isValidCampaignStatus as isValidCampaignStatusBase,
  isValidCampaignName,
  isValidCampaignDescription,
  isValidCampaignBudget,
  generateCampaignSlug,
  isCampaignActive,
  isCampaignCompleted,
  calculateCampaignRemainingBudget,
  calculateCampaignSpentPercentage,
  isCampaignEditable,
  getDefaultCampaignStatus as getDefaultCampaignStatusBase,
  getAllCampaignTypes as getAllCampaignTypesBase,
  type CampaignSortField,
  type CampaignStatus as CampaignStatusBase,
  type CampaignType as CampaignTypeBase,
  type CampaignInterface,
  type CampaignMetadata,
  type CreateCampaignInput,
  type UpdateCampaignInput,
  type CampaignFilter,
} from './campaign.constants';

// ক্যাম্পেইন টাইপ কনস্ট্যান্টসমূহ
export {
  CAMPAIGN_TYPES,
  CAMPAIGN_TYPE_LABELS,
  getCampaignTypeLabel,
  getAllCampaignTypes,
  isValidCampaignType,
  isDigitalMarketingType,
  isContentMarketingType,
  isPaidAdvertisingType,
  isOrganicType,
  getDefaultCampaignType,
  type CampaignType,
} from './campaign-type.constants';

// ক্যাম্পেইন স্ট্যাটাস কনস্ট্যান্টসমূহ
export {
  CAMPAIGN_STATUSES,
  CAMPAIGN_STATUS_COLORS,
  CAMPAIGN_STATUS_LABELS,
  getCampaignStatusColor,
  getCampaignStatusLabel,
  getAllCampaignStatuses,
  isValidCampaignStatus,
  isActiveStatus,
  isCompletedStatus,
  isEditableStatus,
  isPausableStatus,
  isResumableStatus,
  isCancellableStatus,
  canCampaignTransitionTo,
  getDefaultCampaignStatus,
  type CampaignStatus,
} from './campaign-status.constants';

// ক্যাম্পেইন চ্যানেল কনস্ট্যান্টসমূহ
export {
  CAMPAIGN_CHANNELS,
  CAMPAIGN_CHANNEL_LABELS,
  getCampaignChannelLabel,
  getAllCampaignChannels,
  isValidCampaignChannel,
  isDigitalChannel,
  isPushChannel,
  isMessagingChannel,
  isAdvertisingChannel,
  getDefaultCampaignChannel,
  getChannelIcon,
  getChannelColor,
  type CampaignChannel,
} from './campaign-channel.constants';

// ক্যাম্পেইন বাজেট কনস্ট্যান্টসমূহ
export {
  BUDGET_CURRENCIES,
  DEFAULT_CURRENCY,
  MIN_CAMPAIGN_BUDGET,
  MAX_CAMPAIGN_BUDGET,
  CURRENCY_SYMBOLS,
  CURRENCY_NAMES,
  EXCHANGE_RATES,
  isValidCurrency,
  getCurrencySymbol,
  getCurrencyName,
  getAllCurrencies,
  getDefaultCurrency,
  isValidBudget as isValidBudgetAmount,
  convertCurrency,
  createBudgetManagement,
  getBudgetStatus,
  formatBudget,
  getBudgetColor,
  type Currency,
  type BudgetManagement,
  type BudgetStatus,
} from './campaign-budget.constants';

// ক্যাম্পেইন টার্গেট কনস্ট্যান্টসমূহ
export {
  TARGET_AUDIENCES,
  TARGET_TYPE_LABELS,
  getTargetAudienceLabel,
  getAllTargetAudiences,
  isValidTargetAudience,
  isNewUserTarget,
  isExistingUserTarget,
  isHighValueTarget,
  isInactiveTarget,
  isAllUserTarget,
  isSegmentedTarget,
  getDefaultTargetAudience,
  getTargetDescription,
  getTargetIcon,
  getTargetColor,
  type TargetAudience,
} from './campaign-target.constants';

// প্রমোশন কনস্ট্যান্টসমূহ
export {
  PROMOTION_MODULE_NAME,
  DEFAULT_PROMOTION_STATUS,
  MAX_PROMOTION_NAME_LENGTH,
  MAX_DISCOUNT_PERCENTAGE,
  MIN_DISCOUNT_AMOUNT,
  isValidPromotionStatus as isValidPromotionStatusBase,
  isValidPromotionName,
  isValidDiscountPercentage,
  isValidDiscountAmount,
  generatePromotionSlug,
  isPromotionActive,
  isPromotionExpired,
  isPromotionLimitReached,
  calculateDiscount,
  isValidDiscountType as isValidDiscountTypeBase,
  getDefaultPromotionStatus as getDefaultPromotionStatusBase,
  getAllDiscountTypes as getAllDiscountTypesBase,
  type PromotionStatus as PromotionStatusBase,
  type DiscountType as DiscountTypeBase,
  type PromotionInterface,
  type PromotionMetadata,
  type CreatePromotionInput,
  type UpdatePromotionInput,
  type PromotionFilter,
} from './promotion.constants';

// প্রমোশন টাইপ কনস্ট্যান্টসমূহ
export {
  PROMOTION_TYPES,
  PROMOTION_TYPE_LABELS,
  getPromotionTypeLabel,
  getAllPromotionTypes,
  isValidPromotionType,
  isDiscountType,
  isBogofType,
  isFreeShippingType,
  isGiftType,
  isCouponType,
  hasDiscount,
  hasFreeItem,
  requiresCoupon,
  getDefaultPromotionType,
  getPromotionTypeIcon,
  getPromotionTypeColor,
  getPromotionTypeDescription,
  type PromotionType,
} from './promotion-type.constants';

// প্রমোশন স্ট্যাটাস কনস্ট্যান্টসমূহ
export {
  PROMOTION_STATUSES,
  PROMOTION_STATUS_COLORS,
  PROMOTION_STATUS_LABELS,
  getPromotionStatusColor,
  getPromotionStatusLabel,
  getAllPromotionStatuses,
  isValidPromotionStatus,
  isActivePromotionStatus,
  isExpiredPromotionStatus,
  isDisabledPromotionStatus,
  isDraftPromotionStatus,
  isEditablePromotionStatus,
  isPublishablePromotionStatus,
  isDisableablePromotionStatus,
  canPromotionTransitionTo,
  getDefaultPromotionStatus,
  type PromotionStatus,
} from './promotion-status.constants';

// প্রমোশন ডিসকাউন্ট টাইপ কনস্ট্যান্টসমূহ
export {
  DISCOUNT_TYPES,
  DISCOUNT_TYPE_LABELS,
  getDiscountTypeLabel,
  getAllDiscountTypes,
  isValidDiscountType,
  isPercentageDiscountType,
  isFixedAmountDiscountType,
  isFreeDiscountType,
  isMoneyBasedDiscount,
  getDiscountTypeMaxValue,
  getDiscountTypeMinValue,
  getDiscountTypeIcon,
  getDefaultDiscountType,
  type DiscountType,
} from './promotion-discount-type.constants';

// প্রমোশন রেস্ট্রিকশন কনস্ট্যান্টসমূহ
export {
  RESTRICTION_TYPES,
  RESTRICTION_LABELS,
  getRestrictionLabel,
  getAllRestrictionTypes,
  isValidRestrictionType,
  isPurchaseBasedRestriction,
  isLimitBasedRestriction,
  isTimeBasedRestriction,
  getRestrictionDefaultValue,
  getRestrictionMinValue,
  getRestrictionMaxValue,
  getRestrictionUnit,
  getRestrictionIcon,
  getRestrictionDescription,
  type RestrictionType,
  type RestrictionInterface,
} from './promotion-restriction.constants';

// প্রমোশন টার্গেট কনস্ট্যান্টসমূহ
export {
  PROMOTION_TARGETS,
  PROMOTION_TARGET_LABELS,
  getPromotionTargetLabel,
  getAllPromotionTargets,
  isValidPromotionTarget,
  isAllUserPromotionTarget,
  isNewUserPromotionTarget,
  isExistingUserPromotionTarget,
  isSpecificUserPromotionTarget,
  isSegmentedPromotionTarget,
  isNewOrExistingUserTarget,
  getDefaultPromotionTarget,
  getPromotionTargetDescription,
  getPromotionTargetIcon,
  getPromotionTargetColor,
  type PromotionTarget,
} from './promotion-target.constants';

// অ্যাফিলিয়েট কনস্ট্যান্টসমূহ
export {
  AFFILIATE_MODULE_NAME,
  DEFAULT_AFFILIATE_STATUS,
  MAX_AFFILIATE_NAME_LENGTH,
  MIN_COMMISSION_RATE,
  MAX_COMMISSION_RATE,
  isValidAffiliateStatus as isValidAffiliateStatusBase,
  isValidAffiliateType as isValidAffiliateTypeBase,
  isValidAffiliateName,
  isValidCommissionRate,
  generateReferralCode as generateAffiliateReferralCode,
  isAffiliateActive,
  isAffiliateEditable,
  updateAffiliateEarnings,
  getDefaultAffiliateStatus as getDefaultAffiliateStatusBase,
  getAllAffiliateTypes as getAllAffiliateTypesBase,
  getAffiliateTypeLabel as getAffiliateTypeLabelBase,
  type AffiliateStatus as AffiliateStatusBase,
  type AffiliateType as AffiliateTypeBase,
  type AffiliateInterface,
  type AffiliateMetadata,
  type CreateAffiliateInput,
  type UpdateAffiliateInput,
  type AffiliateFilter,
} from './affiliate.constants';

// অ্যাফিলিয়েট স্ট্যাটাস কনস্ট্যান্টসমূহ
export {
  AFFILIATE_STATUSES,
  AFFILIATE_STATUS_COLORS,
  AFFILIATE_STATUS_LABELS,
  getAffiliateStatusColor,
  getAffiliateStatusLabel,
  getAllAffiliateStatuses,
  isValidAffiliateStatus,
  isActiveAffiliateStatus,
  isPendingAffiliateStatus,
  isSuspendedAffiliateStatus,
  isTerminatedAffiliateStatus,
  isEditableAffiliateStatus,
  isActivatableAffiliateStatus,
  isSuspendableAffiliateStatus,
  isTerminatableAffiliateStatus,
  canAffiliateTransitionTo,
  getDefaultAffiliateStatus,
  type AffiliateStatus,
} from './affiliate-status.constants';

// অ্যাফিলিয়েট টাইপ কনস্ট্যান্টসমূহ
export {
  AFFILIATE_TYPES,
  AFFILIATE_TYPE_LABELS,
  getAffiliateTypeLabel,
  getAllAffiliateTypes,
  isValidAffiliateType,
  isIndividualAffiliateType,
  isBusinessAffiliateType,
  isInfluencerAffiliateType,
  isCorporateAffiliateType,
  getDefaultAffiliateType,
  getAffiliateTypeIcon,
  getAffiliateTypeDescription,
  type AffiliateType,
} from './affiliate-type.constants';

// অ্যাফিলিয়েট কমিশন কনস্ট্যান্টসমূহ
export {
  COMMISSION_TYPES,
  DEFAULT_COMMISSION_TYPE,
  COMMISSION_PAYOUT_SCHEDULES,
  COMMISSION_TYPE_LABELS,
  COMMISSION_PAYOUT_LABELS,
  getCommissionTypeLabel,
  isValidCommissionType,
  isValidPayoutSchedule,
  getPayoutScheduleLabel,
  getAllCommissionTypes,
  getAllPayoutSchedules,
  getDefaultCommissionType,
  isPercentageCommission,
  isFixedCommission,
  isDailyPayout,
  isWeeklyPayout,
  isMonthlyPayout,
  calculateCommission,
  isCommissionValid,
  createDefaultCommission,
  getPayoutScheduleIcon,
  getCommissionTypeIcon,
  type CommissionType,
  type CommissionPayoutSchedule,
  type CommissionInterface,
} from './affiliate-commission.constants';

// অ্যাফিলিয়েট পেআউট কনস্ট্যান্টসমূহ
export {
  PAYOUT_METHODS,
  MIN_PAYOUT_AMOUNT,
  MAX_PAYOUT_AMOUNT,
  PAYOUT_METHOD_LABELS,
  getPayoutMethodLabel,
  isValidPayoutMethod,
  getAllPayoutMethods,
  isValidPayoutAmount,
  isValidPayoutStatus as isValidPayoutStatusBase,
  getPayoutStatusLabel as getPayoutStatusLabelBase,
  getPayoutMethodIcon,
  getPayoutMethodDescription,
  isPayoutCompleted,
  isPayoutFailed,
  isPayoutProcessing,
  getDefaultPayoutMethod,
  type PayoutMethod,
  type PayoutInterface,
  type PayoutStatus as PayoutStatusBase,
  type PayoutMetadata,
  type CreatePayoutInput,
  type UpdatePayoutInput,
  type PayoutFilter,
} from './affiliate-payout.constants';

// অ্যাফিলিয়েট পেআউট স্ট্যাটাস কনস্ট্যান্টসমূহ
export {
  PAYOUT_STATUSES,
  PAYOUT_STATUS_COLORS,
  PAYOUT_STATUS_LABELS,
  getPayoutStatusColor,
  getPayoutStatusLabel,
  getAllPayoutStatuses,
  isValidPayoutStatus,
  isPendingPayoutStatus,
  isProcessingPayoutStatus,
  isCompletedPayoutStatus,
  isFailedPayoutStatus,
  isCancelledPayoutStatus,
  isActivePayoutStatus,
  isTerminalPayoutStatus,
  isSuccessfulPayoutStatus,
  isEditablePayoutStatus,
  canPayoutTransitionTo,
  getDefaultPayoutStatus,
  getPayoutStatusIcon,
  type PayoutStatus,
} from './affiliate-payout-status.constants';

// রেফারেল কনস্ট্যান্টসমূহ
export {
  REFERRAL_MODULE_NAME,
  DEFAULT_REFERRAL_STATUS,
  MAX_REFERRAL_CODE_LENGTH,
  MAX_REFERRAL_REWARDS,
  isValidReferralStatus as isValidReferralStatusBase,
  isValidRewardType as isValidRewardTypeBase,
  isValidRewardStatus,
  generateReferralCode,
  isValidReferralCode,
  isValidRewardValue,
  isReferralActive,
  isRewardClaimable,
  isRewardExpired,
  claimReward,
  getRewardTypeLabel as getRewardTypeLabelBase,
  getRewardStatusLabel,
  getDefaultReferralStatus as getDefaultReferralStatusBase,
  getAllRewardTypes as getAllRewardTypesBase,
  getAllRewardStatuses,
  type ReferralStatus as ReferralStatusBase,
  type RewardType as RewardTypeBase,
  type ReferralInterface,
  type RewardStatus,
  type ReferralMetadata,
  type CreateReferralInput,
  type UpdateReferralInput,
  type ReferralFilter,
} from './referral.constants';

// রেফারেল স্ট্যাটাস কনস্ট্যান্টসমূহ
export {
  REFERRAL_STATUSES,
  REFERRAL_STATUS_COLORS,
  REFERRAL_STATUS_LABELS,
  getReferralStatusColor,
  getReferralStatusLabel,
  getAllReferralStatuses,
  isValidReferralStatus,
  isActiveReferralStatus,
  isExpiredReferralStatus,
  isDisabledReferralStatus,
  isEditableReferralStatus,
  isDisableableReferralStatus,
  canReferralTransitionTo,
  getDefaultReferralStatus,
  getReferralStatusIcon,
  type ReferralStatus,
} from './referral-status.constants';

// রেফারেল টাইপ কনস্ট্যান্টসমূহ
export {
  REFERRAL_TYPES,
  REFERRAL_TYPE_LABELS,
  getReferralTypeLabel,
  getAllReferralTypes,
  isValidReferralType,
  isUserReferralType,
  isSellerReferralType,
  isAffiliateReferralType,
  isPartnerReferralType,
  getDefaultReferralType,
  getReferralTypeIcon,
  getReferralTypeDescription,
  getReferralTypeColor,
  type ReferralType,
} from './referral-type.constants';

// রেফারেল রিওয়ার্ড কনস্ট্যান্টসমূহ
export {
  REWARD_TYPES,
  REWARD_TYPE_LABELS,
  getRewardTypeLabel,
  getAllRewardTypes,
  isValidRewardType,
  isDiscountRewardType,
  isPointsRewardType,
  isCashRewardType,
  isGiftRewardType,
  isMoneyBasedRewardType,
  isNonMoneyBasedRewardType,
  getDefaultRewardType,
  getRewardTypeIcon,
  getRewardTypeColor,
  getRewardTypeDescription,
  getRewardTypeDefaultValue,
  getRewardTypeMaxValue,
  getRewardTypeMinValue,
  type RewardType,
} from './referral-reward.constants';

// লয়্যালটি কনস্ট্যান্টসমূহ
export {
  LOYALTY_MODULE_NAME,
  DEFAULT_LOYALTY_STATUS,
  POINTS_PER_PURCHASE,
  POINTS_REDEMPTION_RATE,
  isValidLoyaltyStatus as isValidLoyaltyStatusBase,
  isValidLoyaltyTier as isValidLoyaltyTierBase,
  getTierName as getTierNameBase,
  getTierRequiredPoints,
  getTierDiscountRate as getTierDiscountRateBase,
  getTierIcon as getTierIconBase,
  addPoints,
  redeemPoints,
  calculateValueFromPoints,
  calculatePointsFromValue,
  determineTier as determineTierBase,
  isLoyaltyActive,
  isValidPoints,
  getDefaultLoyaltyStatus as getDefaultLoyaltyStatusBase,
  getAllTiers as getAllTiersBase,
  getTierDescription as getTierDescriptionBase,
  type LoyaltyStatus as LoyaltyStatusBase,
  type LoyaltyTier as LoyaltyTierBase,
  type LoyaltyInterface,
  type LoyaltyMetadata,
  type CreateLoyaltyInput,
  type UpdateLoyaltyInput,
  type LoyaltyFilter,
} from './loyalty.constants';

// লয়্যালটি স্ট্যাটাস কনস্ট্যান্টসমূহ
export {
  LOYALTY_STATUSES,
  LOYALTY_STATUS_COLORS,
  LOYALTY_STATUS_LABELS,
  getLoyaltyStatusColor,
  getLoyaltyStatusLabel,
  getAllLoyaltyStatuses,
  isValidLoyaltyStatus,
  isActiveLoyaltyStatus,
  isInactiveLoyaltyStatus,
  isSuspendedLoyaltyStatus,
  isEditableLoyaltyStatus,
  isActivatableLoyaltyStatus,
  isSuspendableLoyaltyStatus,
  canLoyaltyTransitionTo,
  getDefaultLoyaltyStatus,
  getLoyaltyStatusIcon,
  type LoyaltyStatus,
} from './loyalty-status.constants';

// লয়্যালটি টাইপ কনস্ট্যান্টসমূহ
export {
  LOYALTY_TYPES,
  LOYALTY_TYPE_LABELS,
  getLoyaltyTypeLabel,
  getAllLoyaltyTypes,
  isValidLoyaltyType,
  isPointsBasedLoyaltyType,
  isTierBasedLoyaltyType,
  isHybridLoyaltyType,
  supportsPoints,
  supportsTiers,
  getDefaultLoyaltyType,
  getLoyaltyTypeIcon,
  getLoyaltyTypeDescription,
  getLoyaltyTypeColor,
  type LoyaltyType,
} from './loyalty-type.constants';

// লয়্যালটি পয়েন্ট কনস্ট্যান্টসমূহ
export {
  POINTS_EARNING_RULES,
  POINTS_EXPIRY_DAYS,
  MIN_POINTS_REDEEM,
  POINTS_EARNING_RULE_LABELS,
  POINTS_EARNING_VALUES,
  POINTS_EARNING_MAX,
  getPointsEarningRuleLabel,
  getAllPointsEarningRules,
  isValidPointsEarningRule,
  getPointsEarningValue,
  getPointsEarningMax,
  calculatePointsExpiryDate,
  isPointsExpired,
  isPointsRedeemable,
  getRedeemablePoints,
  calculatePointsValue,
  calculateDiscountFromPoints,
  calculatePointsFromDiscount,
  getPointsEarningRuleIcon,
  getPointsEarningRuleDescription,
  type PointsEarningRule,
} from './loyalty-points.constants';

// লয়্যালটি টায়ার কনস্ট্যান্টসমূহ
export {
  LOYALTY_TIERS,
  TIER_BENEFITS,
  TIER_UPGRADE_REQUIREMENTS,
  TIER_DISCOUNT_RATES,
  getTierName,
  getTierNameBn,
  getTierBenefits,
  getTierUpgradeRequirement,
  getTierDiscountRate,
  getAllTiers,
  isValidTier,
  determineTierFromPoints,
  getNextTier,
  getPointsToNextTier,
  getTierIcon,
  getTierColor,
  getTierDescription,
  type LoyaltyTier,
} from './loyalty-tier.constants';

// লয়্যালটি রিওয়ার্ড কনস্ট্যান্টসমূহ
export {
  REWARD_CATEGORIES,
  REWARD_AVAILABILITY,
  REWARD_CATEGORY_LABELS,
  REWARD_AVAILABILITY_LABELS,
  getRewardCategoryLabel,
  getRewardAvailabilityLabel,
  getAllRewardCategories,
  getAllRewardAvailabilities,
  isValidRewardCategory,
  isValidRewardAvailability,
  isRewardAvailable,
  redeemReward,
  getRewardCategoryIcon,
  getRewardCategoryColor,
  getRewardCategoryDescription,
  getDefaultRewardCategory,
  getDefaultRewardAvailability,
  type RewardCategory,
  type RewardAvailability,
  type RewardInterface,
  type RewardMetadata,
  type CreateRewardInput,
  type UpdateRewardInput,
  type RewardFilter,
} from './loyalty-reward.constants';

// ইমেইল মার্কেটিং কনস্ট্যান্টসমূহ
export {
  EMAIL_MARKETING_MODULE_NAME,
  DEFAULT_EMAIL_STATUS,
  MAX_EMAIL_SUBJECT_LENGTH,
  MAX_EMAIL_BODY_LENGTH,
  MAX_EMAIL_RECIPIENTS,
  isValidEmailStatus as isValidEmailStatusBase,
  isValidEmailType as isValidEmailTypeBase,
  isValidEmailPlatform,
  isValidEmailSubject,
  isValidEmailBody,
  isValidEmailRecipients,
  isValidEmail as isValidEmailMarketing,
  calculateOpenRate,
  calculateClickRate,
  calculateBounceRate,
  isEmailSent,
  isEmailScheduled,
  isEmailDraft,
  getDefaultEmailStatus as getDefaultEmailStatusBase,
  getAllEmailTypes as getAllEmailTypesBase,
  getAllEmailPlatforms,
  getEmailTypeLabel as getEmailTypeLabelBase,
  getEmailPlatformLabel,
  type EmailStatus as EmailStatusBase,
  type EmailType as EmailTypeBase,
  type EmailPlatform,
  type EmailInterface,
  type EmailMetadata,
  type EmailAttachment,
  type CreateEmailInput,
  type UpdateEmailInput,
  type EmailFilter,
} from './email-marketing.constants';

// ইমেইল মার্কেটিং টাইপ কনস্ট্যান্টসমূহ
export {
  EMAIL_TYPES,
  EMAIL_TYPE_LABELS,
  getEmailTypeLabel,
  getAllEmailTypes,
  isValidEmailType,
  isNewsletterType,
  isPromotionalType,
  isTransactionalType,
  isWelcomeType,
  isAbandonedCartType,
  isMarketingEmailType,
  isTransactionalEmailType,
  isAutomatedEmailType,
  getDefaultEmailType,
  getEmailTypeIcon,
  getEmailTypeColor,
  getEmailTypeDescription,
  type EmailType,
} from './email-marketing-type.constants';

// ইমেইল মার্কেটিং স্ট্যাটাস কনস্ট্যান্টসমূহ
export {
  EMAIL_STATUSES,
  EMAIL_STATUS_COLORS,
  EMAIL_STATUS_LABELS,
  getEmailStatusColor,
  getEmailStatusLabel,
  getAllEmailStatuses,
  isValidEmailStatus,
  isDraftEmailStatus,
  isScheduledEmailStatus,
  isSendingEmailStatus,
  isSentEmailStatus,
  isFailedEmailStatus,
  isTerminalEmailStatus,
  isActiveEmailStatus,
  isEditableEmailStatus,
  canEmailTransitionTo,
  getDefaultEmailStatus,
  getEmailStatusIcon,
  type EmailStatus,
} from './email-marketing-status.constants';

// এসএমএস মার্কেটিং কনস্ট্যান্টসমূহ
export {
  SMS_MARKETING_MODULE_NAME,
  DEFAULT_SMS_STATUS,
  MAX_SMS_BODY_LENGTH,
  MAX_SMS_RECIPIENTS,
  isValidSmsStatus as isValidSmsStatusBase,
  isValidSmsType as isValidSmsTypeBase,
  isValidSmsProvider,
  isValidSmsBody,
  isValidSmsRecipients,
  isValidPhoneNumber,
  calculateSmsDeliveryRate,
  calculateSmsFailureRate,
  isSmsSent,
  isSmsScheduled,
  isSmsDraft,
  countSmsCharacters,
  countSmsParts,
  getDefaultSmsStatus as getDefaultSmsStatusBase,
  getAllSmsTypes as getAllSmsTypesBase,
  getAllSmsProviders,
  getSmsTypeLabel as getSmsTypeLabelBase,
  getSmsProviderLabel,
  type SmsStatus as SmsStatusBase,
  type SmsType as SmsTypeBase,
  type SmsProvider,
  type SmsInterface,
  type SmsMetadata,
  type CreateSmsInput,
  type UpdateSmsInput,
  type SmsFilter,
} from './sms-marketing.constants';

// এসএমএস মার্কেটিং টাইপ কনস্ট্যান্টসমূহ
export {
  SMS_TYPES,
  SMS_TYPE_LABELS,
  getSmsTypeLabel,
  getAllSmsTypes,
  isValidSmsType,
  isPromotionalSmsType,
  isTransactionalSmsType,
  isOtpSmsType,
  isAlertSmsType,
  isMarketingSmsType,
  isTransactionalSmsTypeGroup,
  isVerificationSmsType,
  isNotificationSmsType,
  getDefaultSmsType,
  getSmsTypeIcon,
  getSmsTypeColor,
  getSmsTypeDescription,
  type SmsType,
} from './sms-marketing-type.constants';

// এসএমএস মার্কেটিং স্ট্যাটাস কনস্ট্যান্টসমূহ
export {
  SMS_STATUSES,
  SMS_STATUS_COLORS,
  SMS_STATUS_LABELS,
  getSmsStatusColor,
  getSmsStatusLabel,
  getAllSmsStatuses,
  isValidSmsStatus,
  isDraftSmsStatus,
  isScheduledSmsStatus,
  isSendingSmsStatus,
  isSentSmsStatus,
  isFailedSmsStatus,
  isTerminalSmsStatus,
  isActiveSmsStatus,
  isEditableSmsStatus,
  canSmsTransitionTo,
  getDefaultSmsStatus,
  getSmsStatusIcon,
  type SmsStatus,
} from './sms-marketing-status.constants';

// সোশ্যাল মিডিয়া কনস্ট্যান্টসমূহ
export {
  SOCIAL_MEDIA_MODULE_NAME,
  DEFAULT_SOCIAL_STATUS,
  MAX_POST_LENGTH,
  MAX_HASHTAGS,
  isValidSocialPlatform as isValidSocialPlatformBase,
  isValidSocialStatus as isValidSocialStatusBase,
  isValidPostContent,
  isValidHashtags,
  getPlatformName,
  getPlatformIcon as getPlatformIconBase,
  getPlatformColor as getPlatformColorBase,
  getPlatformMaxLength as getPlatformMaxLengthBase,
  calculateEngagementRate,
  calculateViralityScore,
  isPostPublished,
  isPostScheduled,
  isPostDraft,
  getDefaultSocialStatus as getDefaultSocialStatusBase,
  getAllSocialPlatforms as getAllSocialPlatformsBase,
  getPlatformMaxHashtags as getPlatformMaxHashtagsBase,
  type SocialPlatform as SocialPlatformBase,
  type SocialStatus as SocialStatusBase,
  type SocialPostInterface,
  type SocialMetadata,
  type CreateSocialPostInput,
  type UpdateSocialPostInput,
  type SocialPostFilter,
} from './social-media.constants';

// সোশ্যাল মিডিয়া প্ল্যাটফর্ম কনস্ট্যান্টসমূহ
export {
  SOCIAL_PLATFORMS,
  PLATFORM_LABELS,
  PLATFORM_ICONS,
  PLATFORM_COLORS,
  PLATFORM_MAX_LENGTHS,
  PLATFORM_MAX_HASHTAGS,
  PLATFORM_URLS,
  getPlatformLabel,
  getPlatformIcon,
  getPlatformColor,
  getPlatformMaxLength,
  getPlatformMaxHashtags,
  getPlatformUrl,
  getAllSocialPlatforms,
  isValidSocialPlatform,
  isMicrobloggingPlatform,
  isVisualPlatform,
  isProfessionalPlatform,
  isVideoPlatform,
  isSocialNetworkPlatform,
  getPlatformCategory,
  getDefaultSocialPlatform,
  getPlatformDescription,
  type SocialPlatform,
} from './social-media-platform.constants';

// সোশ্যাল মিডিয়া স্ট্যাটাস কনস্ট্যান্টসমূহ
export {
  SOCIAL_STATUSES,
  SOCIAL_STATUS_COLORS,
  SOCIAL_STATUS_LABELS,
  getSocialStatusColor,
  getSocialStatusLabel,
  getAllSocialStatuses,
  isValidSocialStatus,
  isDraftSocialStatus,
  isScheduledSocialStatus,
  isPublishedSocialStatus,
  isFailedSocialStatus,
  isTerminalSocialStatus,
  isActiveSocialStatus,
  isEditableSocialStatus,
  canSocialTransitionTo,
  getDefaultSocialStatus,
  getSocialStatusIcon,
  type SocialStatus,
} from './social-media-status.constants';

// সোশ্যাল মিডিয়া পোস্ট টাইপ কনস্ট্যান্টসমূহ
export {
  POST_TYPES,
  POST_TYPE_LABELS,
  getPostTypeLabel,
  getAllPostTypes,
  isValidPostType,
  isTextPostType,
  isImagePostType,
  isVideoPostType,
  isCarouselPostType,
  isStoryPostType,
  isVisualPostType,
  isMediaPostType,
  isMultiMediaPostType,
  isTemporaryPostType,
  getDefaultPostType,
  getPostTypeIcon,
  getPostTypeColor,
  getPostTypeDescription,
  type PostType,
} from './social-media-post-type.constants';

// SEO মার্কেটিং কনস্ট্যান্টসমূহ
export {
  SEO_MARKETING_MODULE_NAME,
  DEFAULT_SEO_STATUS,
  SEO_TOOLS,
  isValidSeoStatus as isValidSeoStatusBase,
  isValidSeoTool,
  isValidSeoTaskType,
  isValidSeoPriority,
  getSeoToolLabel,
  getSeoTaskTypeLabel,
  getSeoPriorityLabel,
  getAllSeoTools,
  getAllSeoTaskTypes,
  getAllSeoPriorities,
  isSeoTaskCompleted,
  isSeoTaskDraft,
  calculateSeoProgress,
  getDefaultSeoStatus as getDefaultSeoStatusBase,
  getSeoToolIcon,
  getSeoTaskTypeIcon,
  getSeoPriorityColor,
  type SeoStatus as SeoStatusBase,
  type SeoTool,
  type SeoTaskType,
  type SeoPriority,
  type SeoInterface,
  type SeoMetadata,
  type CreateSeoTaskInput,
  type UpdateSeoTaskInput,
  type SeoFilter,
} from './seo-marketing.constants';

// SEO মার্কেটিং টাইপ কনস্ট্যান্টসমূহ
export {
  SEO_TYPES,
  SEO_TYPE_LABELS,
  getSeoTypeLabel,
  getAllSeoTypes,
  isValidSeoType,
  isOnPageSeoType,
  isOffPageSeoType,
  isTechnicalSeoType,
  isLocalSeoType,
  isContentBasedSeoType,
  isLinkBasedSeoType,
  isTechnicalBasedSeoType,
  isLocationBasedSeoType,
  isVisibilityBasedSeoType,
  getDefaultSeoType,
  getSeoTypeIcon,
  getSeoTypeColor,
  getSeoTypeDescription,
  type SeoType,
} from './seo-marketing-type.constants';

// SEO মার্কেটিং স্ট্যাটাস কনস্ট্যান্টসমূহ
export {
  SEO_STATUSES,
  SEO_STATUS_COLORS,
  SEO_STATUS_LABELS,
  getSeoStatusColor,
  getSeoStatusLabel,
  getAllSeoStatuses,
  isValidSeoStatus,
  isDraftSeoStatus,
  isActiveSeoStatus,
  isPausedSeoStatus,
  isCompletedSeoStatus,
  isTerminalSeoStatus,
  isActiveSeoStatusGroup,
  isEditableSeoStatus,
  canSeoTransitionTo,
  getDefaultSeoStatus,
  getSeoStatusIcon,
  type SeoStatus,
} from './seo-marketing-status.constants';

// লিড জেনারেশন কনস্ট্যান্টসমূহ
export {
  LEAD_GENERATION_MODULE_NAME,
  DEFAULT_LEAD_STATUS,
  MAX_LEAD_SCORE,
  LEAD_SCORE_THRESHOLDS,
  isValidLeadStatus as isValidLeadStatusBase,
  isValidLeadSource as isValidLeadSourceBase,
  isValidLeadScore,
  getLeadScoreCategory,
  getLeadScoreCategoryLabel,
  getLeadScoreCategoryColor,
  isHotLead,
  isWarmLead,
  isColdLead,
  isLeadConverted,
  convertLead,
  updateLeadScore,
  incrementLeadScore,
  decrementLeadScore,
  getDefaultLeadStatus as getDefaultLeadStatusBase,
  getAllLeadSources as getAllLeadSourcesBase,
  getLeadSourceLabel as getLeadSourceLabelBase,
  getLeadSourceIcon as getLeadSourceIconBase,
  type LeadStatus as LeadStatusBase,
  type LeadScoreCategory,
  type LeadSource as LeadSourceBase,
  type LeadInterface,
  type LeadMetadata,
  type CreateLeadInput,
  type UpdateLeadInput,
  type LeadFilter,
} from './lead-generation.constants';

// লিড জেনারেশন স্ট্যাটাস কনস্ট্যান্টসমূহ
export {
  LEAD_GEN_STATUSES,
  LEAD_GEN_STATUS_COLORS,
  LEAD_GEN_STATUS_LABELS,
  getLeadGenStatusColor,
  getLeadGenStatusLabel,
  getAllLeadGenStatuses,
  isValidLeadGenStatus,
  isActiveLeadGenStatus,
  isPausedLeadGenStatus,
  isCompletedLeadGenStatus,
  isTerminalLeadGenStatus,
  isActiveLeadGenStatusGroup,
  canLeadGenTransitionTo,
  getDefaultLeadGenStatus,
  getLeadGenStatusIcon,
  type LeadGenStatus,
} from './lead-generation-status.constants';

// লিড জেনারেশন টাইপ কনস্ট্যান্টসমূহ
export {
  LEAD_GEN_TYPES,
  LEAD_GEN_TYPE_LABELS,
  getLeadGenTypeLabel,
  getAllLeadGenTypes,
  isValidLeadGenType,
  isFormLeadGenType,
  isLandingPageLeadGenType,
  isPopupLeadGenType,
  isChatLeadGenType,
  isInboundLeadGenType,
  isOutboundLeadGenType,
  isInteractiveLeadGenType,
  getDefaultLeadGenType,
  getLeadGenTypeIcon,
  getLeadGenTypeColor,
  getLeadGenTypeDescription,
  type LeadGenType,
} from './lead-generation-type.constants';

// লিড স্ট্যাটাস কনস্ট্যান্টসমূহ
export {
  LEAD_STATUSES,
  LEAD_STATUS_COLORS,
  LEAD_STATUS_LABELS,
  getLeadStatusColor,
  getLeadStatusLabel,
  getAllLeadStatuses,
  isValidLeadStatus,
  isNewLeadStatus,
  isContactedLeadStatus,
  isQualifiedLeadStatus,
  isConvertedLeadStatus,
  isLostLeadStatus,
  isTerminalLeadStatus,
  isActiveLeadStatus,
  isEditableLeadStatus,
  canLeadTransitionTo,
  getDefaultLeadStatus,
  getLeadStatusIcon,
  getLeadStageNumber,
  getLeadStatusDescription,
  type LeadStatus,
} from './lead-status.constants';

// লিড সোর্স কনস্ট্যান্টসমূহ
export {
  LEAD_SOURCES,
  LEAD_SOURCE_LABELS,
  LEAD_SOURCE_ICONS,
  LEAD_SOURCE_COLORS,
  getLeadSourceLabel,
  getLeadSourceIcon,
  getLeadSourceColor,
  getAllLeadSources,
  isValidLeadSource,
  isOrganicLeadSource,
  isSocialLeadSource,
  isEmailLeadSource,
  isReferralLeadSource,
  isPaidLeadSource,
  isOtherLeadSource,
  isInboundLeadSource,
  isOutboundLeadSource,
  isOrganicOrReferralLeadSource,
  isDigitalLeadSource,
  getDefaultLeadSource,
  getLeadSourceDescription,
  getLeadSourceCategory,
  type LeadSource,
} from './lead-source.constants';

// মার্কেটিং অ্যানালিটিক্স কনস্ট্যান্টসমূহ
export {
  MARKETING_ANALYTICS_MODULE_NAME,
  METRICS as MARKETING_METRICS,
  DEFAULT_TIME_RANGE_DAYS as MARKETING_DEFAULT_TIME_RANGE_DAYS,
  METRIC_LABELS as MARKETING_METRIC_LABELS,
  METRIC_DEFAULT_VALUES,
  METRIC_UNITS,
  getMetricLabel as getMarketingMetricLabel,
  getAllMetrics as getAllMarketingMetrics,
  isValidMetric as isValidMarketingMetric,
  getMetricDefaultValue,
  getMetricUnit,
  isCountMetric,
  isPercentageMetric,
  isCurrencyMetric,
  calculateCtr,
  calculateRoi,
  calculateCpc,
  calculateConversionRate,
  createAnalyticsSummary as createMarketingAnalyticsSummary,
  getDefaultTimeRange as getDefaultMarketingTimeRange,
  getMetricIcon as getMarketingMetricIcon,
  getMetricColor as getMarketingMetricColor,
  type Metric as MarketingMetric,
  type AnalyticsData as MarketingAnalyticsData,
  type AnalyticsMetadata,
  type AnalyticsFilter as MarketingAnalyticsFilter,
  type AnalyticsSummary as MarketingAnalyticsSummary,
} from './marketing-analytics.constants';

// মার্কেটিং অ্যানালিটিক্স টাইপ কনস্ট্যান্টসমূহ
export {
  ANALYTICS_TYPES as MARKETING_ANALYTICS_TYPES,
  ANALYTICS_TYPE_LABELS as MARKETING_ANALYTICS_TYPE_LABELS,
  getAnalyticsTypeLabel as getMarketingAnalyticsTypeLabel,
  getAllAnalyticsTypes as getAllMarketingAnalyticsTypes,
  isValidAnalyticsType as isValidMarketingAnalyticsType,
  isCampaignAnalyticsType,
  isChannelAnalyticsType,
  isSourceAnalyticsType,
  isDemographicAnalyticsType,
  isMarketingAnalyticsType,
  isAudienceAnalyticsType,
  isPerformanceAnalyticsType,
  getDefaultAnalyticsType as getDefaultMarketingAnalyticsType,
  getAnalyticsTypeIcon as getMarketingAnalyticsTypeIcon,
  getAnalyticsTypeColor as getMarketingAnalyticsTypeColor,
  getAnalyticsTypeDescription as getMarketingAnalyticsTypeDescription,
  type AnalyticsType as MarketingAnalyticsType,
} from './marketing-analytics-type.constants';

// মার্কেটিং রিপোর্ট কনস্ট্যান্টসমূহ
export {
  REPORT_TYPES as REPORT_TYPES_BASE,
  REPORT_FORMATS,
  REPORT_TYPE_LABELS as REPORT_TYPE_LABELS_BASE,
  REPORT_FORMAT_LABELS,
  REPORT_MIME_TYPES,
  REPORT_EXTENSIONS,
  getReportTypeLabel as getReportTypeLabelBase,
  getReportFormatLabel,
  getAllReportTypes as getAllReportTypesBase,
  getAllReportFormats,
  isValidReportType as isValidReportTypeBase,
  isValidReportFormat,
  getReportMimeType,
  getReportExtension,
  isPerformanceReportType as isPerformanceReportTypeBase,
  isRoiReportType as isRoiReportTypeBase,
  isCampaignReportType as isCampaignReportTypeBase,
  isChannelReportType as isChannelReportTypeBase,
  isPdfReportFormat,
  isExcelReportFormat,
  isCsvReportFormat,
  isHtmlReportFormat,
  isSpreadsheetReportFormat,
  isDocumentReportFormat,
  getDefaultReportType as getDefaultReportTypeBase,
  getDefaultReportFormat,
  getReportTypeIcon as getReportTypeIconBase,
  getReportFormatIcon,
  getReportTypeColor as getReportTypeColorBase,
  getReportFormatColor,
  getReportTypeDescription as getReportTypeDescriptionBase,
  type ReportType as ReportTypeBase,
  type ReportFormat,
  type ReportInterface,
  type ReportMetadata,
  type CreateReportInput,
  type ReportFilter,
} from './marketing-report.constants';

// মার্কেটিং রিপোর্ট টাইপ কনস্ট্যান্টসমূহ
export {
  REPORT_TYPES,
  REPORT_TYPE_LABELS,
  REPORT_TYPE_ICONS,
  REPORT_TYPE_COLORS,
  getReportTypeLabel,
  getReportTypeIcon,
  getReportTypeColor,
  getAllReportTypes,
  isValidReportType,
  isPerformanceReportType,
  isRoiReportType,
  isCampaignReportType,
  isChannelReportType,
  isConversionReportType,
  isEngagementReportType,
  isFinancialReportType,
  isMarketingReportType,
  isAudienceReportType,
  isConversionReportTypeGroup,
  getDefaultReportType,
  getReportTypeDescription,
  type ReportType,
} from './marketing-report-type.constants';

// মার্কেটিং অটোমেশন কনস্ট্যান্টসমূহ
export {
  AUTOMATION_MODULE_NAME,
  DEFAULT_AUTOMATION_STATUS,
  MAX_WORKFLOW_STEPS,
  AUTOMATION_TRIGGER_LABELS,
  AUTOMATION_ACTION_LABELS,
  isValidAutomationStatus,
  isValidAutomationTrigger,
  isValidAutomationAction as isValidAutomationActionBase,
  getAutomationTriggerLabel,
  getAutomationActionLabel as getAutomationActionLabelBase,
  getAllAutomationTriggers,
  getAllAutomationActions as getAllAutomationActionsBase,
  isAutomationActive,
  isAutomationEditable,
  enableAutomation,
  disableAutomation,
  getDefaultAutomationStatus,
  getAutomationTriggerIcon,
  getAutomationActionIcon as getAutomationActionIconBase,
  getAutomationTriggerColor,
  getAutomationActionColor as getAutomationActionColorBase,
  getAutomationTriggerDescription,
  type AutomationStatus,
  type AutomationTrigger,
  type AutomationAction as AutomationActionBase,
  type AutomationInterface,
  type WorkflowStep,
  type WorkflowCondition,
  type AutomationMetadata,
  type CreateAutomationInput,
  type UpdateAutomationInput,
  type AutomationFilter,
} from './marketing-automation.constants';

// মার্কেটিং অটোমেশন টাইপ কনস্ট্যান্টসমূহ
export {
  AUTOMATION_TYPES,
  AUTOMATION_TYPE_LABELS,
  AUTOMATION_TYPE_ICONS,
  AUTOMATION_TYPE_COLORS,
  getAutomationTypeLabel,
  getAutomationTypeIcon,
  getAutomationTypeColor,
  getAllAutomationTypes,
  isValidAutomationType,
  isEmailAutomationType,
  isSmsAutomationType,
  isPushAutomationType,
  isSocialAutomationType,
  isMultiChannelAutomationType,
  isSingleChannelAutomationType,
  isMessagingAutomationType,
  isCommunicationAutomationType,
  getDefaultAutomationType,
  getAutomationTypeDescription,
  type AutomationType,
} from './marketing-automation-type.constants';

// মার্কেটিং অটোমেশন ট্রিগার কনস্ট্যান্টসমূহ
export {
  TRIGGER_TYPES,
  TRIGGER_EVENTS,
  TRIGGER_TYPE_LABELS,
  TRIGGER_EVENT_LABELS,
  TRIGGER_TYPE_ICONS,
  TRIGGER_EVENT_ICONS,
  TRIGGER_TYPE_COLORS,
  TRIGGER_EVENT_COLORS,
  getTriggerTypeLabel,
  getTriggerEventLabel,
  getTriggerTypeIcon,
  getTriggerEventIcon,
  getTriggerTypeColor,
  getTriggerEventColor,
  getAllTriggerTypes,
  getAllTriggerEvents,
  isValidTriggerType,
  isValidTriggerEvent,
  isUserActionTriggerType,
  isDateBasedTriggerType,
  isEventBasedTriggerType,
  isConditionBasedTriggerType,
  isSignupTriggerEvent,
  isPurchaseTriggerEvent,
  isAbandonedCartTriggerEvent,
  isBirthdayTriggerEvent,
  isAnniversaryTriggerEvent,
  isTransactionalTriggerEvent,
  isPersonalTriggerEvent,
  isAcquisitionTriggerEvent,
  getDefaultTriggerType,
  getDefaultTriggerEvent,
  getTriggerTypeDescription,
  getTriggerEventDescription,
  type TriggerType,
  type TriggerEvent,
} from './marketing-automation-trigger.constants';

// মার্কেটিং অটোমেশন অ্যাকশন কনস্ট্যান্টসমূহ
export {
  ACTION_TYPES,
  ACTION_TYPE_LABELS,
  ACTION_TYPE_ICONS,
  ACTION_TYPE_COLORS,
  ACTION_TYPE_CATEGORIES,
  getActionTypeLabel,
  getActionTypeIcon,
  getActionTypeColor,
  getActionTypeCategory,
  getAllActionTypes,
  isValidActionType,
  isCommunicationActionType,
  isTaggingActionType,
  isPointsActionType,
  isSendEmailActionType,
  isSendSmsActionType,
  isSendPushActionType,
  isAddTagActionType,
  isRemoveTagActionType,
  isAddPointsActionType,
  isTagModificationActionType,
  getDefaultActionType,
  getActionTypeDescription,
  type ActionType,
} from './marketing-automation-action.constants';

// মার্কেটিং পারমিশন কনস্ট্যান্টসমূহ
export {
  PERMISSIONS,
  PERMISSION_LABELS,
  PERMISSION_CATEGORIES,
  PERMISSION_ACTIONS,
  PERMISSION_GROUPS,
  getPermissionLabel,
  getPermissionCategory,
  getPermissionAction,
  getAllPermissions,
  isValidPermission,
  getPermissionsByCategory,
  isReadPermission,
  isWritePermission,
  isDeletePermission,
  isManagePermission,
  isSendPermission,
  isPublishPermission,
  isMarketingPermission,
  getPermissionIcon,
  getPermissionDescription,
  getDefaultPermissionGroup,
  getAllPermissionGroups,
  type Permission,
} from './marketing-permission.constants';

// মার্কেটিং এরর মেসেজ কনস্ট্যান্টসমূহ
export {
  ERROR_MESSAGES as MARKETING_ERROR_MESSAGES,
  ERROR_MESSAGES_BN as MARKETING_ERROR_MESSAGES_BN,
  ERROR_CODES,
  ERROR_HTTP_STATUS,
  getErrorMessageBn as getMarketingErrorMessageBn,
  getErrorCode,
  getErrorHttpStatus as getMarketingErrorHttpStatus,
  createErrorObject,
  isValidErrorKey,
  getAllErrorKeys,
  getAllErrorMessages as getAllMarketingErrorMessages,
  getErrorsByCategory,
  getErrorDescription,
  type ErrorMessageKey as MarketingErrorMessageKey,
  type ErrorMessage,
} from './marketing-error.constants';
