/**
 * Ticket Tag Constants
 * Tags for support tickets
 */

export const TICKET_TAG = {
  // Tag Types
  TYPES: {
    URGENT: 'urgent',
    VIP: 'vip',
    BUG: 'bug',
    FEATURE: 'feature',
    ENHANCEMENT: 'enhancement',
    DOCUMENTATION: 'documentation',
    TRAINING: 'training',
    ONBOARDING: 'onboarding',
    RETENTION: 'retention',
    CANCELLATION: 'cancellation',
    REFUND: 'refund',
    DISPUTE: 'dispute',
    COMPLIANCE: 'compliance',
    REGULATORY: 'regulatory',
    ESCALATED: 'escalated',
    FOLLOW_UP: 'follow_up',
    SCHEDULED: 'scheduled',
    IN_PROGRESS: 'in_progress',
    REVIEW: 'review',
    APPROVED: 'approved',
    REJECTED: 'rejected',
  } as const,

  // Tag Categories
  CATEGORIES: {
    PRIORITY: 'priority',
    TYPE: 'type',
    STATUS: 'status',
    ACTION: 'action',
    OUTCOME: 'outcome',
  } as const,

  // Tag Colors (for UI)
  COLORS: {
    URGENT: '#red-500',
    VIP: '#gold-500',
    BUG: '#red-400',
    FEATURE: '#green-500',
    ENHANCEMENT: '#blue-500',
    DOCUMENTATION: '#blue-400',
    TRAINING: '#purple-500',
    ONBOARDING: '#green-400',
    RETENTION: '#pink-500',
    CANCELLATION: '#red-600',
    REFUND: '#orange-500',
    DISPUTE: '#red-500',
    COMPLIANCE: '#gray-600',
    REGULATORY: '#gray-700',
    ESCALATED: '#red-700',
    FOLLOW_UP: '#blue-300',
    SCHEDULED: '#purple-400',
    IN_PROGRESS: '#yellow-500',
    REVIEW: '#orange-400',
    APPROVED: '#green-600',
    REJECTED: '#red-600',
  } as const,

  // Tag Priorities
  PRIORITIES: {
    URGENT: 'critical',
    VIP: 'high',
    BUG: 'high',
    FEATURE: 'medium',
    ENHANCEMENT: 'medium',
    DOCUMENTATION: 'low',
    TRAINING: 'medium',
    ONBOARDING: 'medium',
    RETENTION: 'high',
    CANCELLATION: 'high',
    REFUND: 'high',
    DISPUTE: 'critical',
    COMPLIANCE: 'high',
    REGULATORY: 'high',
    ESCALATED: 'critical',
    FOLLOW_UP: 'medium',
    SCHEDULED: 'low',
    IN_PROGRESS: 'medium',
    REVIEW: 'medium',
    APPROVED: 'low',
    REJECTED: 'low',
  } as const,
} as const;

// Tag Types
export type TicketTagType = (typeof TICKET_TAG.TYPES)[keyof typeof TICKET_TAG.TYPES];

// Tag Categories
export type TicketTagCategory = (typeof TICKET_TAG.CATEGORIES)[keyof typeof TICKET_TAG.CATEGORIES];

// Tag Colors
export type TicketTagColor = (typeof TICKET_TAG.COLORS)[keyof typeof TICKET_TAG.COLORS];

// Utility Functions
export function ticketTagGetLabel(tag: TicketTagType): string {
  const labels: Record<TicketTagType, string> = {
    [TICKET_TAG.TYPES.URGENT]: 'Urgent',
    [TICKET_TAG.TYPES.VIP]: 'VIP',
    [TICKET_TAG.TYPES.BUG]: 'Bug',
    [TICKET_TAG.TYPES.FEATURE]: 'Feature',
    [TICKET_TAG.TYPES.ENHANCEMENT]: 'Enhancement',
    [TICKET_TAG.TYPES.DOCUMENTATION]: 'Documentation',
    [TICKET_TAG.TYPES.TRAINING]: 'Training',
    [TICKET_TAG.TYPES.ONBOARDING]: 'Onboarding',
    [TICKET_TAG.TYPES.RETENTION]: 'Retention',
    [TICKET_TAG.TYPES.CANCELLATION]: 'Cancellation',
    [TICKET_TAG.TYPES.REFUND]: 'Refund',
    [TICKET_TAG.TYPES.DISPUTE]: 'Dispute',
    [TICKET_TAG.TYPES.COMPLIANCE]: 'Compliance',
    [TICKET_TAG.TYPES.REGULATORY]: 'Regulatory',
    [TICKET_TAG.TYPES.ESCALATED]: 'Escalated',
    [TICKET_TAG.TYPES.FOLLOW_UP]: 'Follow Up',
    [TICKET_TAG.TYPES.SCHEDULED]: 'Scheduled',
    [TICKET_TAG.TYPES.IN_PROGRESS]: 'In Progress',
    [TICKET_TAG.TYPES.REVIEW]: 'Review',
    [TICKET_TAG.TYPES.APPROVED]: 'Approved',
    [TICKET_TAG.TYPES.REJECTED]: 'Rejected',
  };
  return labels[tag] || 'Unknown';
}

export function ticketTagGetColor(tag: TicketTagType): TicketTagColor {
  const colors: Record<TicketTagType, TicketTagColor> = {
    [TICKET_TAG.TYPES.URGENT]: TICKET_TAG.COLORS.URGENT,
    [TICKET_TAG.TYPES.VIP]: TICKET_TAG.COLORS.VIP,
    [TICKET_TAG.TYPES.BUG]: TICKET_TAG.COLORS.BUG,
    [TICKET_TAG.TYPES.FEATURE]: TICKET_TAG.COLORS.FEATURE,
    [TICKET_TAG.TYPES.ENHANCEMENT]: TICKET_TAG.COLORS.ENHANCEMENT,
    [TICKET_TAG.TYPES.DOCUMENTATION]: TICKET_TAG.COLORS.DOCUMENTATION,
    [TICKET_TAG.TYPES.TRAINING]: TICKET_TAG.COLORS.TRAINING,
    [TICKET_TAG.TYPES.ONBOARDING]: TICKET_TAG.COLORS.ONBOARDING,
    [TICKET_TAG.TYPES.RETENTION]: TICKET_TAG.COLORS.RETENTION,
    [TICKET_TAG.TYPES.CANCELLATION]: TICKET_TAG.COLORS.CANCELLATION,
    [TICKET_TAG.TYPES.REFUND]: TICKET_TAG.COLORS.REFUND,
    [TICKET_TAG.TYPES.DISPUTE]: TICKET_TAG.COLORS.DISPUTE,
    [TICKET_TAG.TYPES.COMPLIANCE]: TICKET_TAG.COLORS.COMPLIANCE,
    [TICKET_TAG.TYPES.REGULATORY]: TICKET_TAG.COLORS.REGULATORY,
    [TICKET_TAG.TYPES.ESCALATED]: TICKET_TAG.COLORS.ESCALATED,
    [TICKET_TAG.TYPES.FOLLOW_UP]: TICKET_TAG.COLORS.FOLLOW_UP,
    [TICKET_TAG.TYPES.SCHEDULED]: TICKET_TAG.COLORS.SCHEDULED,
    [TICKET_TAG.TYPES.IN_PROGRESS]: TICKET_TAG.COLORS.IN_PROGRESS,
    [TICKET_TAG.TYPES.REVIEW]: TICKET_TAG.COLORS.REVIEW,
    [TICKET_TAG.TYPES.APPROVED]: TICKET_TAG.COLORS.APPROVED,
    [TICKET_TAG.TYPES.REJECTED]: TICKET_TAG.COLORS.REJECTED,
  };
  return colors[tag] || '#gray-400';
}

export function ticketTagGetCategory(tag: TicketTagType): TicketTagCategory {
  const categories: Record<TicketTagType, TicketTagCategory> = {
    [TICKET_TAG.TYPES.URGENT]: TICKET_TAG.CATEGORIES.PRIORITY,
    [TICKET_TAG.TYPES.VIP]: TICKET_TAG.CATEGORIES.PRIORITY,
    [TICKET_TAG.TYPES.BUG]: TICKET_TAG.CATEGORIES.TYPE,
    [TICKET_TAG.TYPES.FEATURE]: TICKET_TAG.CATEGORIES.TYPE,
    [TICKET_TAG.TYPES.ENHANCEMENT]: TICKET_TAG.CATEGORIES.TYPE,
    [TICKET_TAG.TYPES.DOCUMENTATION]: TICKET_TAG.CATEGORIES.TYPE,
    [TICKET_TAG.TYPES.TRAINING]: TICKET_TAG.CATEGORIES.TYPE,
    [TICKET_TAG.TYPES.ONBOARDING]: TICKET_TAG.CATEGORIES.TYPE,
    [TICKET_TAG.TYPES.RETENTION]: TICKET_TAG.CATEGORIES.TYPE,
    [TICKET_TAG.TYPES.CANCELLATION]: TICKET_TAG.CATEGORIES.TYPE,
    [TICKET_TAG.TYPES.REFUND]: TICKET_TAG.CATEGORIES.TYPE,
    [TICKET_TAG.TYPES.DISPUTE]: TICKET_TAG.CATEGORIES.TYPE,
    [TICKET_TAG.TYPES.COMPLIANCE]: TICKET_TAG.CATEGORIES.TYPE,
    [TICKET_TAG.TYPES.REGULATORY]: TICKET_TAG.CATEGORIES.TYPE,
    [TICKET_TAG.TYPES.ESCALATED]: TICKET_TAG.CATEGORIES.STATUS,
    [TICKET_TAG.TYPES.FOLLOW_UP]: TICKET_TAG.CATEGORIES.ACTION,
    [TICKET_TAG.TYPES.SCHEDULED]: TICKET_TAG.CATEGORIES.ACTION,
    [TICKET_TAG.TYPES.IN_PROGRESS]: TICKET_TAG.CATEGORIES.STATUS,
    [TICKET_TAG.TYPES.REVIEW]: TICKET_TAG.CATEGORIES.STATUS,
    [TICKET_TAG.TYPES.APPROVED]: TICKET_TAG.CATEGORIES.OUTCOME,
    [TICKET_TAG.TYPES.REJECTED]: TICKET_TAG.CATEGORIES.OUTCOME,
  };
  return categories[tag] || TICKET_TAG.CATEGORIES.TYPE;
}

export function ticketTagGetPriority(tag: TicketTagType): string {
  const priorities: Record<TicketTagType, string> = {
    [TICKET_TAG.TYPES.URGENT]: TICKET_TAG.PRIORITIES.URGENT,
    [TICKET_TAG.TYPES.VIP]: TICKET_TAG.PRIORITIES.VIP,
    [TICKET_TAG.TYPES.BUG]: TICKET_TAG.PRIORITIES.BUG,
    [TICKET_TAG.TYPES.FEATURE]: TICKET_TAG.PRIORITIES.FEATURE,
    [TICKET_TAG.TYPES.ENHANCEMENT]: TICKET_TAG.PRIORITIES.ENHANCEMENT,
    [TICKET_TAG.TYPES.DOCUMENTATION]: TICKET_TAG.PRIORITIES.DOCUMENTATION,
    [TICKET_TAG.TYPES.TRAINING]: TICKET_TAG.PRIORITIES.TRAINING,
    [TICKET_TAG.TYPES.ONBOARDING]: TICKET_TAG.PRIORITIES.ONBOARDING,
    [TICKET_TAG.TYPES.RETENTION]: TICKET_TAG.PRIORITIES.RETENTION,
    [TICKET_TAG.TYPES.CANCELLATION]: TICKET_TAG.PRIORITIES.CANCELLATION,
    [TICKET_TAG.TYPES.REFUND]: TICKET_TAG.PRIORITIES.REFUND,
    [TICKET_TAG.TYPES.DISPUTE]: TICKET_TAG.PRIORITIES.DISPUTE,
    [TICKET_TAG.TYPES.COMPLIANCE]: TICKET_TAG.PRIORITIES.COMPLIANCE,
    [TICKET_TAG.TYPES.REGULATORY]: TICKET_TAG.PRIORITIES.REGULATORY,
    [TICKET_TAG.TYPES.ESCALATED]: TICKET_TAG.PRIORITIES.ESCALATED,
    [TICKET_TAG.TYPES.FOLLOW_UP]: TICKET_TAG.PRIORITIES.FOLLOW_UP,
    [TICKET_TAG.TYPES.SCHEDULED]: TICKET_TAG.PRIORITIES.SCHEDULED,
    [TICKET_TAG.TYPES.IN_PROGRESS]: TICKET_TAG.PRIORITIES.IN_PROGRESS,
    [TICKET_TAG.TYPES.REVIEW]: TICKET_TAG.PRIORITIES.REVIEW,
    [TICKET_TAG.TYPES.APPROVED]: TICKET_TAG.PRIORITIES.APPROVED,
    [TICKET_TAG.TYPES.REJECTED]: TICKET_TAG.PRIORITIES.REJECTED,
  };
  return priorities[tag] || 'medium';
}
