/**
 * Promotion Status Constants
 * Status definitions for promotion lifecycle
 */

export const MARKETINGPROMOTION_STATUS = {
  // Promotion Statuses
  STATUSES: {
    DRAFT: 'draft',
    PENDING_APPROVAL: 'pending_approval',
    UNDER_REVIEW: 'under_review',
    APPROVED: 'approved',
    REJECTED: 'rejected',
    SCHEDULED: 'scheduled',
    READY: 'ready',
    ACTIVE: 'active',
    PAUSED: 'paused',
    EXPIRED: 'expired',
    COMPLETED: 'completed',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
    FAILED: 'failed',
    ON_HOLD: 'on_hold',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    DRAFT: '#6B7280',
    PENDING_APPROVAL: '#F59E0B',
    UNDER_REVIEW: '#8B5CF6',
    APPROVED: '#10B981',
    REJECTED: '#EF4444',
    SCHEDULED: '#3B82F6',
    READY: '#10B981',
    ACTIVE: '#10B981',
    PAUSED: '#F59E0B',
    EXPIRED: '#6B7280',
    COMPLETED: '#10B981',
    CANCELLED: '#6B7280',
    ARCHIVED: '#6B7280',
    FAILED: '#EF4444',
    ON_HOLD: '#F59E0B',
  } as const,

  // Status Priority Order
  ORDER: {
    DRAFT: 0,
    PENDING_APPROVAL: 1,
    UNDER_REVIEW: 2,
    APPROVED: 3,
    REJECTED: 4,
    SCHEDULED: 5,
    READY: 6,
    ACTIVE: 7,
    PAUSED: 8,
    EXPIRED: 9,
    COMPLETED: 10,
    CANCELLED: 11,
    ARCHIVED: 12,
    FAILED: 13,
    ON_HOLD: 14,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    DRAFT_TO_PENDING: 'draft_to_pending',
    DRAFT_TO_CANCELLED: 'draft_to_cancelled',
    PENDING_TO_UNDER_REVIEW: 'pending_to_under_review',
    PENDING_TO_DRAFT: 'pending_to_draft',
    UNDER_REVIEW_TO_APPROVED: 'under_review_to_approved',
    UNDER_REVIEW_TO_REJECTED: 'under_review_to_rejected',
    APPROVED_TO_SCHEDULED: 'approved_to_scheduled',
    APPROVED_TO_READY: 'approved_to_ready',
    REJECTED_TO_DRAFT: 'rejected_to_draft',
    SCHEDULED_TO_READY: 'scheduled_to_ready',
    SCHEDULED_TO_CANCELLED: 'scheduled_to_cancelled',
    READY_TO_ACTIVE: 'ready_to_active',
    READY_TO_CANCELLED: 'ready_to_cancelled',
    ACTIVE_TO_PAUSED: 'active_to_paused',
    ACTIVE_TO_COMPLETED: 'active_to_completed',
    ACTIVE_TO_EXPIRED: 'active_to_expired',
    ACTIVE_TO_CANCELLED: 'active_to_cancelled',
    PAUSED_TO_ACTIVE: 'paused_to_active',
    PAUSED_TO_CANCELLED: 'paused_to_cancelled',
    PAUSED_TO_ON_HOLD: 'paused_to_on_hold',
    ON_HOLD_TO_ACTIVE: 'on_hold_to_active',
    ON_HOLD_TO_PAUSED: 'on_hold_to_paused',
    EXPIRED_TO_ARCHIVED: 'expired_to_archived',
    COMPLETED_TO_ARCHIVED: 'completed_to_archived',
    CANCELLED_TO_ARCHIVED: 'cancelled_to_archived',
    FAILED_TO_DRAFT: 'failed_to_draft',
    FAILED_TO_ARCHIVED: 'failed_to_archived',
  } as const,
} as const;

// Promotion Statuses
export type MarketingPromotionStatusType =
  (typeof MARKETINGPROMOTION_STATUS.STATUSES)[keyof typeof MARKETINGPROMOTION_STATUS.STATUSES];

// Status Colors
export type MarketingPromotionStatusColor =
  (typeof MARKETINGPROMOTION_STATUS.COLORS)[keyof typeof MARKETINGPROMOTION_STATUS.COLORS];

// Status Priority Order
export type MarketingPromotionStatusOrder =
  (typeof MARKETINGPROMOTION_STATUS.ORDER)[keyof typeof MARKETINGPROMOTION_STATUS.ORDER];

// Status Transitions
export type MarketingPromotionStatusTransition =
  (typeof MARKETINGPROMOTION_STATUS.TRANSITIONS)[keyof typeof MARKETINGPROMOTION_STATUS.TRANSITIONS];

// Utility Functions
export function marketingpromotionGetStatusLabel(status: MarketingPromotionStatusType): string {
  const labels: Record<MarketingPromotionStatusType, string> = {
    [MARKETINGPROMOTION_STATUS.STATUSES.DRAFT]: 'Draft',
    [MARKETINGPROMOTION_STATUS.STATUSES.PENDING_APPROVAL]: 'Pending Approval',
    [MARKETINGPROMOTION_STATUS.STATUSES.UNDER_REVIEW]: 'Under Review',
    [MARKETINGPROMOTION_STATUS.STATUSES.APPROVED]: 'Approved',
    [MARKETINGPROMOTION_STATUS.STATUSES.REJECTED]: 'Rejected',
    [MARKETINGPROMOTION_STATUS.STATUSES.SCHEDULED]: 'Scheduled',
    [MARKETINGPROMOTION_STATUS.STATUSES.READY]: 'Ready',
    [MARKETINGPROMOTION_STATUS.STATUSES.ACTIVE]: 'Active',
    [MARKETINGPROMOTION_STATUS.STATUSES.PAUSED]: 'Paused',
    [MARKETINGPROMOTION_STATUS.STATUSES.EXPIRED]: 'Expired',
    [MARKETINGPROMOTION_STATUS.STATUSES.COMPLETED]: 'Completed',
    [MARKETINGPROMOTION_STATUS.STATUSES.CANCELLED]: 'Cancelled',
    [MARKETINGPROMOTION_STATUS.STATUSES.ARCHIVED]: 'Archived',
    [MARKETINGPROMOTION_STATUS.STATUSES.FAILED]: 'Failed',
    [MARKETINGPROMOTION_STATUS.STATUSES.ON_HOLD]: 'On Hold',
  };
  return labels[status] || 'Unknown Status';
}

export function marketingpromotionGetStatusColor(
  status: MarketingPromotionStatusType
): MarketingPromotionStatusColor {
  const colors: Record<MarketingPromotionStatusType, MarketingPromotionStatusColor> = {
    [MARKETINGPROMOTION_STATUS.STATUSES.DRAFT]: MARKETINGPROMOTION_STATUS.COLORS.DRAFT,
    [MARKETINGPROMOTION_STATUS.STATUSES.PENDING_APPROVAL]:
      MARKETINGPROMOTION_STATUS.COLORS.PENDING_APPROVAL,
    [MARKETINGPROMOTION_STATUS.STATUSES.UNDER_REVIEW]:
      MARKETINGPROMOTION_STATUS.COLORS.UNDER_REVIEW,
    [MARKETINGPROMOTION_STATUS.STATUSES.APPROVED]: MARKETINGPROMOTION_STATUS.COLORS.APPROVED,
    [MARKETINGPROMOTION_STATUS.STATUSES.REJECTED]: MARKETINGPROMOTION_STATUS.COLORS.REJECTED,
    [MARKETINGPROMOTION_STATUS.STATUSES.SCHEDULED]: MARKETINGPROMOTION_STATUS.COLORS.SCHEDULED,
    [MARKETINGPROMOTION_STATUS.STATUSES.READY]: MARKETINGPROMOTION_STATUS.COLORS.READY,
    [MARKETINGPROMOTION_STATUS.STATUSES.ACTIVE]: MARKETINGPROMOTION_STATUS.COLORS.ACTIVE,
    [MARKETINGPROMOTION_STATUS.STATUSES.PAUSED]: MARKETINGPROMOTION_STATUS.COLORS.PAUSED,
    [MARKETINGPROMOTION_STATUS.STATUSES.EXPIRED]: MARKETINGPROMOTION_STATUS.COLORS.EXPIRED,
    [MARKETINGPROMOTION_STATUS.STATUSES.COMPLETED]: MARKETINGPROMOTION_STATUS.COLORS.COMPLETED,
    [MARKETINGPROMOTION_STATUS.STATUSES.CANCELLED]: MARKETINGPROMOTION_STATUS.COLORS.CANCELLED,
    [MARKETINGPROMOTION_STATUS.STATUSES.ARCHIVED]: MARKETINGPROMOTION_STATUS.COLORS.ARCHIVED,
    [MARKETINGPROMOTION_STATUS.STATUSES.FAILED]: MARKETINGPROMOTION_STATUS.COLORS.FAILED,
    [MARKETINGPROMOTION_STATUS.STATUSES.ON_HOLD]: MARKETINGPROMOTION_STATUS.COLORS.ON_HOLD,
  };
  return colors[status] || MARKETINGPROMOTION_STATUS.COLORS.DRAFT;
}

export function marketingpromotionGetStatusOrder(
  status: MarketingPromotionStatusType
): MarketingPromotionStatusOrder {
  const order: Record<MarketingPromotionStatusType, MarketingPromotionStatusOrder> = {
    [MARKETINGPROMOTION_STATUS.STATUSES.DRAFT]: MARKETINGPROMOTION_STATUS.ORDER.DRAFT,
    [MARKETINGPROMOTION_STATUS.STATUSES.PENDING_APPROVAL]:
      MARKETINGPROMOTION_STATUS.ORDER.PENDING_APPROVAL,
    [MARKETINGPROMOTION_STATUS.STATUSES.UNDER_REVIEW]: MARKETINGPROMOTION_STATUS.ORDER.UNDER_REVIEW,
    [MARKETINGPROMOTION_STATUS.STATUSES.APPROVED]: MARKETINGPROMOTION_STATUS.ORDER.APPROVED,
    [MARKETINGPROMOTION_STATUS.STATUSES.REJECTED]: MARKETINGPROMOTION_STATUS.ORDER.REJECTED,
    [MARKETINGPROMOTION_STATUS.STATUSES.SCHEDULED]: MARKETINGPROMOTION_STATUS.ORDER.SCHEDULED,
    [MARKETINGPROMOTION_STATUS.STATUSES.READY]: MARKETINGPROMOTION_STATUS.ORDER.READY,
    [MARKETINGPROMOTION_STATUS.STATUSES.ACTIVE]: MARKETINGPROMOTION_STATUS.ORDER.ACTIVE,
    [MARKETINGPROMOTION_STATUS.STATUSES.PAUSED]: MARKETINGPROMOTION_STATUS.ORDER.PAUSED,
    [MARKETINGPROMOTION_STATUS.STATUSES.EXPIRED]: MARKETINGPROMOTION_STATUS.ORDER.EXPIRED,
    [MARKETINGPROMOTION_STATUS.STATUSES.COMPLETED]: MARKETINGPROMOTION_STATUS.ORDER.COMPLETED,
    [MARKETINGPROMOTION_STATUS.STATUSES.CANCELLED]: MARKETINGPROMOTION_STATUS.ORDER.CANCELLED,
    [MARKETINGPROMOTION_STATUS.STATUSES.ARCHIVED]: MARKETINGPROMOTION_STATUS.ORDER.ARCHIVED,
    [MARKETINGPROMOTION_STATUS.STATUSES.FAILED]: MARKETINGPROMOTION_STATUS.ORDER.FAILED,
    [MARKETINGPROMOTION_STATUS.STATUSES.ON_HOLD]: MARKETINGPROMOTION_STATUS.ORDER.ON_HOLD,
  };
  return order[status] || MARKETINGPROMOTION_STATUS.ORDER.DRAFT;
}

export function marketingpromotionIsActiveStatus(status: MarketingPromotionStatusType): boolean {
  const activeStatuses: MarketingPromotionStatusType[] = [
    MARKETINGPROMOTION_STATUS.STATUSES.ACTIVE,
    MARKETINGPROMOTION_STATUS.STATUSES.READY,
  ];
  return activeStatuses.includes(status);
}

export function marketingpromotionIsPausedStatus(status: MarketingPromotionStatusType): boolean {
  const pausedStatuses: MarketingPromotionStatusType[] = [
    MARKETINGPROMOTION_STATUS.STATUSES.PAUSED,
    MARKETINGPROMOTION_STATUS.STATUSES.ON_HOLD,
  ];
  return pausedStatuses.includes(status);
}

export function marketingpromotionIsEndedStatus(status: MarketingPromotionStatusType): boolean {
  const endedStatuses: MarketingPromotionStatusType[] = [
    MARKETINGPROMOTION_STATUS.STATUSES.COMPLETED,
    MARKETINGPROMOTION_STATUS.STATUSES.EXPIRED,
    MARKETINGPROMOTION_STATUS.STATUSES.CANCELLED,
    MARKETINGPROMOTION_STATUS.STATUSES.ARCHIVED,
    MARKETINGPROMOTION_STATUS.STATUSES.REJECTED,
    MARKETINGPROMOTION_STATUS.STATUSES.FAILED,
  ];
  return endedStatuses.includes(status);
}

export function marketingpromotionIsEditableStatus(status: MarketingPromotionStatusType): boolean {
  const editableStatuses: MarketingPromotionStatusType[] = [
    MARKETINGPROMOTION_STATUS.STATUSES.DRAFT,
    MARKETINGPROMOTION_STATUS.STATUSES.PENDING_APPROVAL,
    MARKETINGPROMOTION_STATUS.STATUSES.REJECTED,
    MARKETINGPROMOTION_STATUS.STATUSES.SCHEDULED,
    MARKETINGPROMOTION_STATUS.STATUSES.PAUSED,
    MARKETINGPROMOTION_STATUS.STATUSES.ON_HOLD,
  ];
  return editableStatuses.includes(status);
}

export function marketingpromotionCanTransition(
  currentStatus: MarketingPromotionStatusType,
  targetStatus: MarketingPromotionStatusType
): boolean {
  const validTransitions: Record<MarketingPromotionStatusType, MarketingPromotionStatusType[]> = {
    [MARKETINGPROMOTION_STATUS.STATUSES.DRAFT]: [
      MARKETINGPROMOTION_STATUS.STATUSES.PENDING_APPROVAL,
      MARKETINGPROMOTION_STATUS.STATUSES.CANCELLED,
      MARKETINGPROMOTION_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGPROMOTION_STATUS.STATUSES.PENDING_APPROVAL]: [
      MARKETINGPROMOTION_STATUS.STATUSES.UNDER_REVIEW,
      MARKETINGPROMOTION_STATUS.STATUSES.DRAFT,
      MARKETINGPROMOTION_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGPROMOTION_STATUS.STATUSES.UNDER_REVIEW]: [
      MARKETINGPROMOTION_STATUS.STATUSES.APPROVED,
      MARKETINGPROMOTION_STATUS.STATUSES.REJECTED,
      MARKETINGPROMOTION_STATUS.STATUSES.DRAFT,
    ],
    [MARKETINGPROMOTION_STATUS.STATUSES.APPROVED]: [
      MARKETINGPROMOTION_STATUS.STATUSES.SCHEDULED,
      MARKETINGPROMOTION_STATUS.STATUSES.READY,
      MARKETINGPROMOTION_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGPROMOTION_STATUS.STATUSES.REJECTED]: [
      MARKETINGPROMOTION_STATUS.STATUSES.DRAFT,
      MARKETINGPROMOTION_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGPROMOTION_STATUS.STATUSES.SCHEDULED]: [
      MARKETINGPROMOTION_STATUS.STATUSES.READY,
      MARKETINGPROMOTION_STATUS.STATUSES.CANCELLED,
      MARKETINGPROMOTION_STATUS.STATUSES.DRAFT,
    ],
    [MARKETINGPROMOTION_STATUS.STATUSES.READY]: [
      MARKETINGPROMOTION_STATUS.STATUSES.ACTIVE,
      MARKETINGPROMOTION_STATUS.STATUSES.CANCELLED,
      MARKETINGPROMOTION_STATUS.STATUSES.SCHEDULED,
    ],
    [MARKETINGPROMOTION_STATUS.STATUSES.ACTIVE]: [
      MARKETINGPROMOTION_STATUS.STATUSES.PAUSED,
      MARKETINGPROMOTION_STATUS.STATUSES.COMPLETED,
      MARKETINGPROMOTION_STATUS.STATUSES.EXPIRED,
      MARKETINGPROMOTION_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGPROMOTION_STATUS.STATUSES.PAUSED]: [
      MARKETINGPROMOTION_STATUS.STATUSES.ACTIVE,
      MARKETINGPROMOTION_STATUS.STATUSES.ON_HOLD,
      MARKETINGPROMOTION_STATUS.STATUSES.CANCELLED,
      MARKETINGPROMOTION_STATUS.STATUSES.COMPLETED,
    ],
    [MARKETINGPROMOTION_STATUS.STATUSES.ON_HOLD]: [
      MARKETINGPROMOTION_STATUS.STATUSES.ACTIVE,
      MARKETINGPROMOTION_STATUS.STATUSES.PAUSED,
      MARKETINGPROMOTION_STATUS.STATUSES.CANCELLED,
    ],
    [MARKETINGPROMOTION_STATUS.STATUSES.EXPIRED]: [MARKETINGPROMOTION_STATUS.STATUSES.ARCHIVED],
    [MARKETINGPROMOTION_STATUS.STATUSES.COMPLETED]: [MARKETINGPROMOTION_STATUS.STATUSES.ARCHIVED],
    [MARKETINGPROMOTION_STATUS.STATUSES.CANCELLED]: [MARKETINGPROMOTION_STATUS.STATUSES.ARCHIVED],
    [MARKETINGPROMOTION_STATUS.STATUSES.FAILED]: [
      MARKETINGPROMOTION_STATUS.STATUSES.DRAFT,
      MARKETINGPROMOTION_STATUS.STATUSES.ARCHIVED,
    ],
    [MARKETINGPROMOTION_STATUS.STATUSES.ARCHIVED]: [],
  };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
