/**
 * Search & Discovery HTTP Status Codes Constants
 * Contains all HTTP status codes used in search and discovery management
 */

export const SearchHttpStatus = {
  // 2xx Success
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,

  // 3xx Redirection
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,

  // 4xx Client Errors
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,

  // 5xx Server Errors
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
} as const;

export type SearchHttpStatusCode = (typeof SearchHttpStatus)[keyof typeof SearchHttpStatus];

export const SearchHttpStatusMessages: Record<SearchHttpStatusCode, string> = {
  [SearchHttpStatus.OK]: 'সফল',
  [SearchHttpStatus.CREATED]: 'তৈরি হয়েছে',
  [SearchHttpStatus.ACCEPTED]: 'অনুরোধ গৃহীত হয়েছে',
  [SearchHttpStatus.NON_AUTHORITATIVE_INFORMATION]: 'অননুমোদিত তথ্য',
  [SearchHttpStatus.NO_CONTENT]: 'কোন কন্টেন্ট নেই',
  [SearchHttpStatus.RESET_CONTENT]: 'কন্টেন্ট রিসেট হয়েছে',
  [SearchHttpStatus.PARTIAL_CONTENT]: 'আংশিক কন্টেন্ট',

  [SearchHttpStatus.MULTIPLE_CHOICES]: 'একাধিক পছন্দ',
  [SearchHttpStatus.MOVED_PERMANENTLY]: 'স্থায়ীভাবে সরানো হয়েছে',
  [SearchHttpStatus.FOUND]: 'পাওয়া গেছে',
  [SearchHttpStatus.SEE_OTHER]: 'অন্য দেখুন',
  [SearchHttpStatus.NOT_MODIFIED]: 'পরিবর্তন করা হয়নি',
  [SearchHttpStatus.USE_PROXY]: 'প্রক্সি ব্যবহার করুন',
  [SearchHttpStatus.TEMPORARY_REDIRECT]: 'অস্থায়ী পুনর্নির্দেশ',
  [SearchHttpStatus.PERMANENT_REDIRECT]: 'স্থায়ী পুনর্নির্দেশ',

  [SearchHttpStatus.BAD_REQUEST]: 'অনুরোধটি সঠিক নয়',
  [SearchHttpStatus.UNAUTHORIZED]: 'অননুমোদিত',
  [SearchHttpStatus.PAYMENT_REQUIRED]: 'পেমেন্ট প্রয়োজন',
  [SearchHttpStatus.FORBIDDEN]: 'নিষিদ্ধ',
  [SearchHttpStatus.NOT_FOUND]: 'পাওয়া যায়নি',
  [SearchHttpStatus.METHOD_NOT_ALLOWED]: 'মেথড অনুমোদিত নয়',
  [SearchHttpStatus.NOT_ACCEPTABLE]: 'গ্রহণযোগ্য নয়',
  [SearchHttpStatus.PROXY_AUTHENTICATION_REQUIRED]: 'প্রক্সি প্রমাণীকরণ প্রয়োজন',
  [SearchHttpStatus.REQUEST_TIMEOUT]: 'অনুরোধের সময় শেষ',
  [SearchHttpStatus.CONFLICT]: 'দ্বন্দ্ব',
  [SearchHttpStatus.GONE]: 'চলে গেছে',
  [SearchHttpStatus.LENGTH_REQUIRED]: 'দৈর্ঘ্য প্রয়োজন',
  [SearchHttpStatus.PRECONDITION_FAILED]: 'পূর্বশর্ত ব্যর্থ',
  [SearchHttpStatus.PAYLOAD_TOO_LARGE]: 'পেলোড খুব বড়',
  [SearchHttpStatus.URI_TOO_LONG]: 'URI খুব লম্বা',
  [SearchHttpStatus.UNSUPPORTED_MEDIA_TYPE]: 'অসমর্থিত মিডিয়া টাইপ',
  [SearchHttpStatus.RANGE_NOT_SATISFIABLE]: 'পরিসীমা সন্তোষজনক নয়',
  [SearchHttpStatus.EXPECTATION_FAILED]: 'প্রত্যাশা ব্যর্থ',
  [SearchHttpStatus.IM_A_TEAPOT]: 'আমি একটি চায়ের পাত্র',
  [SearchHttpStatus.MISDIRECTED_REQUEST]: 'ভুল নির্দেশিত অনুরোধ',
  [SearchHttpStatus.UNPROCESSABLE_ENTITY]: 'প্রক্রিয়াযোগ্য নয়',
  [SearchHttpStatus.LOCKED]: 'লক করা হয়েছে',
  [SearchHttpStatus.FAILED_DEPENDENCY]: 'নির্ভরতা ব্যর্থ',
  [SearchHttpStatus.TOO_EARLY]: 'খুব তাড়াতাড়ি',
  [SearchHttpStatus.UPGRADE_REQUIRED]: 'আপগ্রেড প্রয়োজন',
  [SearchHttpStatus.PRECONDITION_REQUIRED]: 'পূর্বশর্ত প্রয়োজন',
  [SearchHttpStatus.TOO_MANY_REQUESTS]: 'অনেক বেশি অনুরোধ',
  [SearchHttpStatus.REQUEST_HEADER_FIELDS_TOO_LARGE]: 'অনুরোধ হেডার ফিল্ড খুব বড়',
  [SearchHttpStatus.UNAVAILABLE_FOR_LEGAL_REASONS]: 'আইনি কারণে অনুপলব্ধ',

  [SearchHttpStatus.INTERNAL_SERVER_ERROR]: 'সার্ভারের অভ্যন্তরীণ ত্রুটি',
  [SearchHttpStatus.NOT_IMPLEMENTED]: 'বাস্তবায়িত নয়',
  [SearchHttpStatus.BAD_GATEWAY]: 'খারাপ গেটওয়ে',
  [SearchHttpStatus.SERVICE_UNAVAILABLE]: 'সার্ভিস অনুপলব্ধ',
  [SearchHttpStatus.GATEWAY_TIMEOUT]: 'গেটওয়ে সময় শেষ',
  [SearchHttpStatus.HTTP_VERSION_NOT_SUPPORTED]: 'HTTP সংস্করণ সমর্থিত নয়',
  [SearchHttpStatus.VARIANT_ALSO_NEGOTIATES]: 'ভেরিয়েন্টও আলোচনা করে',
  [SearchHttpStatus.INSUFFICIENT_STORAGE]: 'অপর্যাপ্ত স্টোরেজ',
  [SearchHttpStatus.LOOP_DETECTED]: 'লুপ সনাক্ত করা হয়েছে',
  [SearchHttpStatus.NOT_EXTENDED]: 'প্রসারিত নয়',
  [SearchHttpStatus.NETWORK_AUTHENTICATION_REQUIRED]: 'নেটওয়ার্ক প্রমাণীকরণ প্রয়োজন',
};

export const SearchHttpStatusCategories = {
  SUCCESS: [200, 201, 202, 203, 204, 205, 206],
  REDIRECTION: [300, 301, 302, 303, 304, 305, 307, 308],
  CLIENT_ERROR: [
    400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418,
    421, 422, 423, 424, 425, 426, 428, 429, 431, 451,
  ],
  SERVER_ERROR: [500, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511],
} as const;
