/**
 * Common Types Export
 * All common type definitions exported from this index
 * Based on shared-constants
 * @module CommonTypes
 */

// ============================================================
// Core exports - প্রতিটি ফাইল থেকে আলাদা করে export
// ============================================================

// Core primitives (base types)
export {
  // Base types
  BaseEntity,
  SoftDeletable,
  Timestamp,
  Status,
  Priority,
  Severity,
  Level,
  Metadata,
  Options,
  ID,
  Slug,
  Email,
  PhoneNumber,
  URL,
  Currency,
  Language,
  Timezone,
  Nullable,
  Optional,
  DeepPartial,
  DeepReadonly,
  NonEmptyArray,
  // Pagination
  PaginationParams,
  SortOrder,
  SortDirection,
  Range,
  DateRange,
  // References
  Reference,
  Name,
  FullName,
  Address,
  Coordinates,
  GeoLocation,
  KeyValue,
  SortField,
  FilterCondition,
  FilterOperator,
  LogicalOperator,
  FilterGroup,
  PagedResponse,
  // API
  ResponseMetadata,
  // Audit & Session
  AuditLog,
  Session,
  DeviceInfo,
  DeviceType,
  // Environment & Features
  Environment,
  FeatureFlag,
  RateLimitConfig,
  // Constants
  HTTP_STATUS,
  REGEX,
  CACHE,
  QUEUE,
} from './core-primitives.types';

// API types (ApiError, ApiResponse এখানে থেকে আসবে)
export {
  ApiError,
  ApiResponse,
  ApiRequest,
  AuthenticatedApiRequest,
  SuccessApiResponse,
  ErrorApiResponse,
  ApiVersion,
  ApiEndpoint,
  ApiMethod,
  RateLimit,
  ApiQueryParams,
  ApiPaginationMetadata,
  ApiResponseMetadata,
  BulkOperationRequest,
  BulkOperationResponse,
  BulkOperationError,
  HealthCheckResponse,
  ServiceHealth,
  ApiErrorCode,
  ValidationError,
  ApiValidator,
  ApiValidationSchema,
  ApiValidationRule,
  ApiMiddleware,
  ApiHandler,
  WebSocketMessage,
  WebSocketResponse,
  SSEEvent,
} from './api.types';

// Pagination types
export {
  BasePaginationParams,
  CursorPaginationParams,
  OffsetPaginationParams,
  PaginationMetadata,
  CursorPaginationMetadata,
  PaginatedResponse,
  CursorPaginatedResponse,
  PaginationInfo,
  SortConfig,
  MultiSortConfig,
  FilterConfig,
  FilterGroupConfig,
  SearchConfig,
  AdvancedSearchConfig,
  FacetConfig,
  FacetResult,
  FacetBucket,
  AggregationConfig,
  AggregationResult,
  PaginatedRequest,
  AggregatedPaginatedResponse,
  PageInfo,
  Connection,
  Edge,
  PageRequest,
  BatchPaginationRequest,
  BatchPaginationResponse,
} from './pagination.types';

// Audit types - সব টাইপ এবং ফাংশন audit.types থেকে
export {
  // Core types
  AdminAuditAction,
  AdminAuditSeverity,
  AdminAuditCategory,
  AdminAuditStatus,
  AdminAuditSource,
  AdminAuditRetention,
  AdminAuditLog,
  AuditMetadata,
  AuditFilter,
  AuditChange,
  ChangeType,
  AuditSummary,
  AuditConfig,
  AuditEvent,
  // Core constants
  ADMIN_AUDIT,
  ADMIN_AUDIT_ACTION_LABELS,
  ADMIN_AUDIT_SEVERITY_LABELS,
  ADMIN_AUDIT_SEVERITY_COLORS,
  ADMIN_AUDIT_SEVERITY_PRIORITY,
  ADMIN_AUDIT_CATEGORY_LABELS,
  ADMIN_AUDIT_STATUS_LABELS,
  ADMIN_AUDIT_STATUS_COLORS,
  ADMIN_AUDIT_SOURCE_LABELS,
  // Core functions
  getAdminAuditActionLabel,
  getAdminAuditSeverityLabel,
  getAdminAuditSeverityColor,
  getAdminAuditSeverityPriority,
  getAdminAuditCategoryLabel,
  getAdminAuditStatusLabel,
  getAdminAuditStatusColor,
  getAdminAuditSourceLabel,
  isAdminAuditHighSeverity,
  isAdminAuditSuccessStatus,
  isAdminAuditFailureStatus,
  isAdminAuditPendingStatus,
  getAdminAuditRetentionDays,
  // Audit Type
  ADMIN_AUDIT_TYPE,
  ADMIN_AUDIT_TYPE_CATEGORIES,
  ADMIN_AUDIT_TYPE_LABELS_DETAIL,
  AdminAuditTypeDetail,
  getAdminAuditTypeCategory,
  getAdminAuditTypeLabel,
  isAdminAuditSecurity,
  isAdminAuditCompliance,
  isAdminAuditFinancial,
  isAdminAuditUser,
  isAdminAuditSystem,
  // Audit Status
  ADMIN_AUDIT_STATUS,
  ADMIN_AUDIT_STATUS_LABELS_DETAIL,
  ADMIN_AUDIT_STATUS_COLORS_DETAIL,
  ADMIN_AUDIT_STATUS_GROUPS,
  AdminAuditStatusDetail,
  getAdminAuditStatusLabelDetail,
  getAdminAuditStatusColorDetail,
  isAdminAuditSuccessStatusDetail,
  isAdminAuditFailureStatusDetail,
  isAdminAuditPendingStatusDetail,
  isAdminAuditIntermediateStatus,
  isAdminAuditTerminalStatus,
  isAdminAuditActiveStatus,
  isAdminAuditCompliantStatus,
  isAdminAuditNonCompliantStatus,
  getAdminAuditStatusPriority,
  getAdminAuditStatuses,
  getAdminAuditSuccessStatuses,
  getAdminAuditFailureStatuses,
  getAdminAuditPendingStatuses,
  getAdminAuditIntermediateStatuses,
} from './audit.types';

// SEO types
export {
  SEOStatus,
  SEOPriority,
  SEOStrategyType,
  SEOKeywordType,
  SEOKeywordIntent,
  SEOContentType,
  SEOLinkType,
  SEOAuditType,
  SEOAuditSeverity,
  SEOScoreType,
  SEOSitemapType,
  SEORobotsDirective,
  SEOSchemaType,
  SEOOpenGraphType,
  SEOTwitterCardType,
  SearchEngine,
  SeoMetadata,
  SeoRobots,
  SeoStrategy,
  SeoKeyword,
  SeoContent,
  SeoContentOptimization,
  SeoLink,
  SeoLinkAttributes,
  SeoAudit,
  SeoFinding,
  SeoScore,
  SeoRanking,
  SeoSitemap,
  SeoSitemapUrl,
  SeoRobotsTxt,
  SeoRobotsTxtRule,
  StructuredData,
  OpenGraph,
  TwitterCard,
  SeoAnalytics,
  SeoReport,
  SeoReportMetrics,
  SEOErrorCode,
  getSEOPriorityLabel,
  getSEOStatusLabel,
  getSEOScoreLabel,
  getSEOScoreColor,
  isSEOTitleValid,
  isSEODescriptionValid,
  getSEOOptimalTitleLength,
  getSEOOptimalDescriptionLength,
  getSEOErrorLabel,
  getSEORecommendationLabel,
  getSEOMetaTagName,
  getSEOPageTypeLabel,
  getSEOSearchEngineLabel,
  getSEORichSnippetLabel,
  getSEOEcommerceTypeLabel,
  getSEOMobileTypeLabel,
  getSEOTaskStatusLabel,
  getSEOPageStatusLabel,
  getSEOLinkStatusLabel,
  getSEOIndexStatusLabel,
  getSEOTaskPriorityLabel,
  getSEOStatusCategory,
  getSEOStatusColor,
  isSEOTaskComplete,
  isSEOTaskBlocked,
  isSEOPagePublished,
  isSEOIndexed,
  getSEOPriorityLevelLabel,
  getSEOPriorityScoreLabel,
  getSEOPriorityImpactLabel,
  getSEOPriorityEffortLabel,
  getSEOPriorityTimeFrameLabel,
  calculateSEOPriorityScore,
  getSEOPriorityLevelFromScore,
  getSEOPriorityValue,
  shouldSEOPrioritizeOver,
  getSEOPriorityColor,
  getSEOError,
  getSEOMessage,
  getSEODescription,
  isSEOError,
  getSEOErrorCategory,
} from './seo.types';
