/**
 * Flash Sale Error Constants
 * Error codes, messages, and types for flash sale operations
 */

// Error Codes
export const FLASH_SALE_ERROR_CODES = {
  // Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_DATE: 'INVALID_DATE',
  INVALID_TIME: 'INVALID_TIME',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_QUANTITY: 'INVALID_QUANTITY',
  INVALID_DISCOUNT: 'INVALID_DISCOUNT',

  // Authentication Errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // Authorization Errors
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  ROLE_NOT_ALLOWED: 'ROLE_NOT_ALLOWED',

  // Not Found Errors
  NOT_FOUND: 'NOT_FOUND',
  FLASH_SALE_NOT_FOUND: 'FLASH_SALE_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  DEAL_NOT_FOUND: 'DEAL_NOT_FOUND',
  COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
  VOUCHER_NOT_FOUND: 'VOUCHER_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Conflict Errors
  CONFLICT: 'CONFLICT',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  ALREADY_ACTIVE: 'ALREADY_ACTIVE',
  ALREADY_EXPIRED: 'ALREADY_EXPIRED',
  ALREADY_CANCELLED: 'ALREADY_CANCELLED',

  // Inventory Errors
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVENTORY_LOCK_FAILED: 'INVENTORY_LOCK_FAILED',
  INVENTORY_RESERVATION_FAILED: 'INVENTORY_RESERVATION_FAILED',
  INVENTORY_RELEASE_FAILED: 'INVENTORY_RELEASE_FAILED',

  // Payment Errors
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_TIMEOUT: 'PAYMENT_TIMEOUT',
  PAYMENT_REFUND_FAILED: 'PAYMENT_REFUND_FAILED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',

  // System Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  CACHE_ERROR: 'CACHE_ERROR',
  QUEUE_ERROR: 'QUEUE_ERROR',

  // Network Errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  CONNECTION_TIMEOUT: 'CONNECTION_TIMEOUT',
  CONNECTION_REFUSED: 'CONNECTION_REFUSED',

  // Rate Limit Errors
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  REQUEST_THROTTLED: 'REQUEST_THROTTLED',

  // Business Logic Errors
  SALE_NOT_ACTIVE: 'SALE_NOT_ACTIVE',
  SALE_NOT_STARTED: 'SALE_NOT_STARTED',
  SALE_ALREADY_ENDED: 'SALE_ALREADY_ENDED',
  SALE_FULLY_BOOKED: 'SALE_FULLY_BOOKED',
  MAX_PARTICIPANTS_REACHED: 'MAX_PARTICIPANTS_REACHED',
  MAX_ITEMS_PER_USER_REACHED: 'MAX_ITEMS_PER_USER_REACHED',
  MIN_ORDER_REQUIREMENT_NOT_MET: 'MIN_ORDER_REQUIREMENT_NOT_MET',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_USED: 'COUPON_USED',
  VOUCHER_EXPIRED: 'VOUCHER_EXPIRED',
  VOUCHER_USED: 'VOUCHER_USED',
  RESTRICTION_VIOLATION: 'RESTRICTION_VIOLATION',
  ELIGIBILITY_FAILED: 'ELIGIBILITY_FAILED',
} as const;

// Error Categories
export const FLASH_SALE_ERROR_CATEGORIES = {
  VALIDATION: 'validation',
  AUTHENTICATION: 'authentication',
  AUTHORIZATION: 'authorization',
  NOT_FOUND: 'not_found',
  CONFLICT: 'conflict',
  INVENTORY: 'inventory',
  PAYMENT: 'payment',
  SYSTEM: 'system',
  NETWORK: 'network',
  TIMEOUT: 'timeout',
  RATE_LIMIT: 'rate_limit',
  BUSINESS: 'business',
} as const;

// Error Severity
export const FLASH_SALE_ERROR_SEVERITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
} as const;

// Error Retry
export const FLASH_SALE_ERROR_RETRY = {
  NOT_RETRYABLE: 'not_retryable',
  RETRYABLE: 'retryable',
  MUST_RETRY: 'must_retry',
} as const;

// Error Messages
export const FLASH_SALE_ERROR_MESSAGES: Record<string, string> = {
  // Validation Errors
  [FLASH_SALE_ERROR_CODES.VALIDATION_ERROR]: 'Validation error occurred',
  [FLASH_SALE_ERROR_CODES.INVALID_INPUT]: 'Invalid input provided',
  [FLASH_SALE_ERROR_CODES.MISSING_REQUIRED_FIELD]: 'Required field is missing',
  [FLASH_SALE_ERROR_CODES.INVALID_FORMAT]: 'Invalid format provided',
  [FLASH_SALE_ERROR_CODES.INVALID_DATE]: 'Invalid date provided',
  [FLASH_SALE_ERROR_CODES.INVALID_TIME]: 'Invalid time provided',
  [FLASH_SALE_ERROR_CODES.INVALID_AMOUNT]: 'Invalid amount provided',
  [FLASH_SALE_ERROR_CODES.INVALID_QUANTITY]: 'Invalid quantity provided',
  [FLASH_SALE_ERROR_CODES.INVALID_DISCOUNT]: 'Invalid discount provided',

  // Authentication Errors
  [FLASH_SALE_ERROR_CODES.UNAUTHORIZED]: 'Authentication required',
  [FLASH_SALE_ERROR_CODES.INVALID_TOKEN]: 'Invalid token provided',
  [FLASH_SALE_ERROR_CODES.TOKEN_EXPIRED]: 'Token has expired',
  [FLASH_SALE_ERROR_CODES.SESSION_EXPIRED]: 'Session has expired',
  [FLASH_SALE_ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid credentials provided',

  // Authorization Errors
  [FLASH_SALE_ERROR_CODES.FORBIDDEN]: 'Access forbidden',
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 'Insufficient permissions',
  [FLASH_SALE_ERROR_CODES.ROLE_NOT_ALLOWED]: 'Role not allowed',

  // Not Found Errors
  [FLASH_SALE_ERROR_CODES.NOT_FOUND]: 'Resource not found',
  [FLASH_SALE_ERROR_CODES.FLASH_SALE_NOT_FOUND]: 'Flash sale not found',
  [FLASH_SALE_ERROR_CODES.PRODUCT_NOT_FOUND]: 'Product not found',
  [FLASH_SALE_ERROR_CODES.DEAL_NOT_FOUND]: 'Deal not found',
  [FLASH_SALE_ERROR_CODES.COUPON_NOT_FOUND]: 'Coupon not found',
  [FLASH_SALE_ERROR_CODES.VOUCHER_NOT_FOUND]: 'Voucher not found',
  [FLASH_SALE_ERROR_CODES.USER_NOT_FOUND]: 'User not found',

  // Conflict Errors
  [FLASH_SALE_ERROR_CODES.CONFLICT]: 'Resource conflict occurred',
  [FLASH_SALE_ERROR_CODES.DUPLICATE_ENTRY]: 'Duplicate entry detected',
  [FLASH_SALE_ERROR_CODES.ALREADY_EXISTS]: 'Resource already exists',
  [FLASH_SALE_ERROR_CODES.ALREADY_ACTIVE]: 'Resource is already active',
  [FLASH_SALE_ERROR_CODES.ALREADY_EXPIRED]: 'Resource has already expired',
  [FLASH_SALE_ERROR_CODES.ALREADY_CANCELLED]: 'Resource is already cancelled',

  // Inventory Errors
  [FLASH_SALE_ERROR_CODES.OUT_OF_STOCK]: 'Product is out of stock',
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_STOCK]: 'Insufficient stock available',
  [FLASH_SALE_ERROR_CODES.INVENTORY_LOCK_FAILED]: 'Failed to lock inventory',
  [FLASH_SALE_ERROR_CODES.INVENTORY_RESERVATION_FAILED]: 'Failed to reserve inventory',
  [FLASH_SALE_ERROR_CODES.INVENTORY_RELEASE_FAILED]: 'Failed to release inventory',

  // Payment Errors
  [FLASH_SALE_ERROR_CODES.PAYMENT_FAILED]: 'Payment processing failed',
  [FLASH_SALE_ERROR_CODES.PAYMENT_TIMEOUT]: 'Payment processing timeout',
  [FLASH_SALE_ERROR_CODES.PAYMENT_REFUND_FAILED]: 'Payment refund failed',
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_BALANCE]: 'Insufficient balance',

  // System Errors
  [FLASH_SALE_ERROR_CODES.INTERNAL_SERVER_ERROR]: 'Internal server error occurred',
  [FLASH_SALE_ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service is temporarily unavailable',
  [FLASH_SALE_ERROR_CODES.DATABASE_ERROR]: 'Database error occurred',
  [FLASH_SALE_ERROR_CODES.CACHE_ERROR]: 'Cache error occurred',
  [FLASH_SALE_ERROR_CODES.QUEUE_ERROR]: 'Queue processing error occurred',

  // Network Errors
  [FLASH_SALE_ERROR_CODES.NETWORK_ERROR]: 'Network error occurred',
  [FLASH_SALE_ERROR_CODES.CONNECTION_TIMEOUT]: 'Connection timeout',
  [FLASH_SALE_ERROR_CODES.CONNECTION_REFUSED]: 'Connection refused',

  // Rate Limit Errors
  [FLASH_SALE_ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded',
  [FLASH_SALE_ERROR_CODES.TOO_MANY_REQUESTS]: 'Too many requests',
  [FLASH_SALE_ERROR_CODES.REQUEST_THROTTLED]: 'Request has been throttled',

  // Business Logic Errors
  [FLASH_SALE_ERROR_CODES.SALE_NOT_ACTIVE]: 'Sale is not active',
  [FLASH_SALE_ERROR_CODES.SALE_NOT_STARTED]: 'Sale has not started yet',
  [FLASH_SALE_ERROR_CODES.SALE_ALREADY_ENDED]: 'Sale has already ended',
  [FLASH_SALE_ERROR_CODES.SALE_FULLY_BOOKED]: 'Sale is fully booked',
  [FLASH_SALE_ERROR_CODES.MAX_PARTICIPANTS_REACHED]: 'Maximum participants reached',
  [FLASH_SALE_ERROR_CODES.MAX_ITEMS_PER_USER_REACHED]: 'Maximum items per user reached',
  [FLASH_SALE_ERROR_CODES.MIN_ORDER_REQUIREMENT_NOT_MET]: 'Minimum order requirement not met',
  [FLASH_SALE_ERROR_CODES.COUPON_EXPIRED]: 'Coupon has expired',
  [FLASH_SALE_ERROR_CODES.COUPON_USED]: 'Coupon has already been used',
  [FLASH_SALE_ERROR_CODES.VOUCHER_EXPIRED]: 'Voucher has expired',
  [FLASH_SALE_ERROR_CODES.VOUCHER_USED]: 'Voucher has already been used',
  [FLASH_SALE_ERROR_CODES.RESTRICTION_VIOLATION]: 'Restriction violation',
  [FLASH_SALE_ERROR_CODES.ELIGIBILITY_FAILED]: 'Eligibility check failed',
};

// Error HTTP Status Codes
export const FLASH_SALE_ERROR_HTTP_STATUS: Record<string, number> = {
  [FLASH_SALE_ERROR_CODES.VALIDATION_ERROR]: 400,
  [FLASH_SALE_ERROR_CODES.INVALID_INPUT]: 400,
  [FLASH_SALE_ERROR_CODES.MISSING_REQUIRED_FIELD]: 400,
  [FLASH_SALE_ERROR_CODES.INVALID_FORMAT]: 400,
  [FLASH_SALE_ERROR_CODES.INVALID_DATE]: 400,
  [FLASH_SALE_ERROR_CODES.INVALID_TIME]: 400,
  [FLASH_SALE_ERROR_CODES.INVALID_AMOUNT]: 400,
  [FLASH_SALE_ERROR_CODES.INVALID_QUANTITY]: 400,
  [FLASH_SALE_ERROR_CODES.INVALID_DISCOUNT]: 400,
  [FLASH_SALE_ERROR_CODES.UNAUTHORIZED]: 401,
  [FLASH_SALE_ERROR_CODES.INVALID_TOKEN]: 401,
  [FLASH_SALE_ERROR_CODES.TOKEN_EXPIRED]: 401,
  [FLASH_SALE_ERROR_CODES.SESSION_EXPIRED]: 401,
  [FLASH_SALE_ERROR_CODES.INVALID_CREDENTIALS]: 401,
  [FLASH_SALE_ERROR_CODES.FORBIDDEN]: 403,
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 403,
  [FLASH_SALE_ERROR_CODES.ROLE_NOT_ALLOWED]: 403,
  [FLASH_SALE_ERROR_CODES.NOT_FOUND]: 404,
  [FLASH_SALE_ERROR_CODES.FLASH_SALE_NOT_FOUND]: 404,
  [FLASH_SALE_ERROR_CODES.PRODUCT_NOT_FOUND]: 404,
  [FLASH_SALE_ERROR_CODES.DEAL_NOT_FOUND]: 404,
  [FLASH_SALE_ERROR_CODES.COUPON_NOT_FOUND]: 404,
  [FLASH_SALE_ERROR_CODES.VOUCHER_NOT_FOUND]: 404,
  [FLASH_SALE_ERROR_CODES.USER_NOT_FOUND]: 404,
  [FLASH_SALE_ERROR_CODES.CONFLICT]: 409,
  [FLASH_SALE_ERROR_CODES.DUPLICATE_ENTRY]: 409,
  [FLASH_SALE_ERROR_CODES.ALREADY_EXISTS]: 409,
  [FLASH_SALE_ERROR_CODES.ALREADY_ACTIVE]: 409,
  [FLASH_SALE_ERROR_CODES.ALREADY_EXPIRED]: 409,
  [FLASH_SALE_ERROR_CODES.ALREADY_CANCELLED]: 409,
  [FLASH_SALE_ERROR_CODES.OUT_OF_STOCK]: 409,
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_STOCK]: 409,
  [FLASH_SALE_ERROR_CODES.INVENTORY_LOCK_FAILED]: 409,
  [FLASH_SALE_ERROR_CODES.INVENTORY_RESERVATION_FAILED]: 409,
  [FLASH_SALE_ERROR_CODES.INVENTORY_RELEASE_FAILED]: 409,
  [FLASH_SALE_ERROR_CODES.PAYMENT_FAILED]: 402,
  [FLASH_SALE_ERROR_CODES.PAYMENT_TIMEOUT]: 408,
  [FLASH_SALE_ERROR_CODES.PAYMENT_REFUND_FAILED]: 402,
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_BALANCE]: 402,
  [FLASH_SALE_ERROR_CODES.INTERNAL_SERVER_ERROR]: 500,
  [FLASH_SALE_ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
  [FLASH_SALE_ERROR_CODES.DATABASE_ERROR]: 500,
  [FLASH_SALE_ERROR_CODES.CACHE_ERROR]: 500,
  [FLASH_SALE_ERROR_CODES.QUEUE_ERROR]: 500,
  [FLASH_SALE_ERROR_CODES.NETWORK_ERROR]: 500,
  [FLASH_SALE_ERROR_CODES.CONNECTION_TIMEOUT]: 504,
  [FLASH_SALE_ERROR_CODES.CONNECTION_REFUSED]: 500,
  [FLASH_SALE_ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,
  [FLASH_SALE_ERROR_CODES.TOO_MANY_REQUESTS]: 429,
  [FLASH_SALE_ERROR_CODES.REQUEST_THROTTLED]: 429,
  [FLASH_SALE_ERROR_CODES.SALE_NOT_ACTIVE]: 400,
  [FLASH_SALE_ERROR_CODES.SALE_NOT_STARTED]: 400,
  [FLASH_SALE_ERROR_CODES.SALE_ALREADY_ENDED]: 400,
  [FLASH_SALE_ERROR_CODES.SALE_FULLY_BOOKED]: 400,
  [FLASH_SALE_ERROR_CODES.MAX_PARTICIPANTS_REACHED]: 400,
  [FLASH_SALE_ERROR_CODES.MAX_ITEMS_PER_USER_REACHED]: 400,
  [FLASH_SALE_ERROR_CODES.MIN_ORDER_REQUIREMENT_NOT_MET]: 400,
  [FLASH_SALE_ERROR_CODES.COUPON_EXPIRED]: 400,
  [FLASH_SALE_ERROR_CODES.COUPON_USED]: 400,
  [FLASH_SALE_ERROR_CODES.VOUCHER_EXPIRED]: 400,
  [FLASH_SALE_ERROR_CODES.VOUCHER_USED]: 400,
  [FLASH_SALE_ERROR_CODES.RESTRICTION_VIOLATION]: 400,
  [FLASH_SALE_ERROR_CODES.ELIGIBILITY_FAILED]: 400,
};

// Error Category Mapping
export const FLASH_SALE_ERROR_CATEGORY_MAP: Record<string, string> = {
  [FLASH_SALE_ERROR_CODES.VALIDATION_ERROR]: FLASH_SALE_ERROR_CATEGORIES.VALIDATION,
  [FLASH_SALE_ERROR_CODES.INVALID_INPUT]: FLASH_SALE_ERROR_CATEGORIES.VALIDATION,
  [FLASH_SALE_ERROR_CODES.MISSING_REQUIRED_FIELD]: FLASH_SALE_ERROR_CATEGORIES.VALIDATION,
  [FLASH_SALE_ERROR_CODES.INVALID_FORMAT]: FLASH_SALE_ERROR_CATEGORIES.VALIDATION,
  [FLASH_SALE_ERROR_CODES.INVALID_DATE]: FLASH_SALE_ERROR_CATEGORIES.VALIDATION,
  [FLASH_SALE_ERROR_CODES.INVALID_TIME]: FLASH_SALE_ERROR_CATEGORIES.VALIDATION,
  [FLASH_SALE_ERROR_CODES.INVALID_AMOUNT]: FLASH_SALE_ERROR_CATEGORIES.VALIDATION,
  [FLASH_SALE_ERROR_CODES.INVALID_QUANTITY]: FLASH_SALE_ERROR_CATEGORIES.VALIDATION,
  [FLASH_SALE_ERROR_CODES.INVALID_DISCOUNT]: FLASH_SALE_ERROR_CATEGORIES.VALIDATION,
  [FLASH_SALE_ERROR_CODES.UNAUTHORIZED]: FLASH_SALE_ERROR_CATEGORIES.AUTHENTICATION,
  [FLASH_SALE_ERROR_CODES.INVALID_TOKEN]: FLASH_SALE_ERROR_CATEGORIES.AUTHENTICATION,
  [FLASH_SALE_ERROR_CODES.TOKEN_EXPIRED]: FLASH_SALE_ERROR_CATEGORIES.AUTHENTICATION,
  [FLASH_SALE_ERROR_CODES.SESSION_EXPIRED]: FLASH_SALE_ERROR_CATEGORIES.AUTHENTICATION,
  [FLASH_SALE_ERROR_CODES.INVALID_CREDENTIALS]: FLASH_SALE_ERROR_CATEGORIES.AUTHENTICATION,
  [FLASH_SALE_ERROR_CODES.FORBIDDEN]: FLASH_SALE_ERROR_CATEGORIES.AUTHORIZATION,
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_PERMISSIONS]: FLASH_SALE_ERROR_CATEGORIES.AUTHORIZATION,
  [FLASH_SALE_ERROR_CODES.ROLE_NOT_ALLOWED]: FLASH_SALE_ERROR_CATEGORIES.AUTHORIZATION,
  [FLASH_SALE_ERROR_CODES.NOT_FOUND]: FLASH_SALE_ERROR_CATEGORIES.NOT_FOUND,
  [FLASH_SALE_ERROR_CODES.FLASH_SALE_NOT_FOUND]: FLASH_SALE_ERROR_CATEGORIES.NOT_FOUND,
  [FLASH_SALE_ERROR_CODES.PRODUCT_NOT_FOUND]: FLASH_SALE_ERROR_CATEGORIES.NOT_FOUND,
  [FLASH_SALE_ERROR_CODES.DEAL_NOT_FOUND]: FLASH_SALE_ERROR_CATEGORIES.NOT_FOUND,
  [FLASH_SALE_ERROR_CODES.COUPON_NOT_FOUND]: FLASH_SALE_ERROR_CATEGORIES.NOT_FOUND,
  [FLASH_SALE_ERROR_CODES.VOUCHER_NOT_FOUND]: FLASH_SALE_ERROR_CATEGORIES.NOT_FOUND,
  [FLASH_SALE_ERROR_CODES.USER_NOT_FOUND]: FLASH_SALE_ERROR_CATEGORIES.NOT_FOUND,
  [FLASH_SALE_ERROR_CODES.CONFLICT]: FLASH_SALE_ERROR_CATEGORIES.CONFLICT,
  [FLASH_SALE_ERROR_CODES.DUPLICATE_ENTRY]: FLASH_SALE_ERROR_CATEGORIES.CONFLICT,
  [FLASH_SALE_ERROR_CODES.ALREADY_EXISTS]: FLASH_SALE_ERROR_CATEGORIES.CONFLICT,
  [FLASH_SALE_ERROR_CODES.ALREADY_ACTIVE]: FLASH_SALE_ERROR_CATEGORIES.CONFLICT,
  [FLASH_SALE_ERROR_CODES.ALREADY_EXPIRED]: FLASH_SALE_ERROR_CATEGORIES.CONFLICT,
  [FLASH_SALE_ERROR_CODES.ALREADY_CANCELLED]: FLASH_SALE_ERROR_CATEGORIES.CONFLICT,
  [FLASH_SALE_ERROR_CODES.OUT_OF_STOCK]: FLASH_SALE_ERROR_CATEGORIES.INVENTORY,
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_STOCK]: FLASH_SALE_ERROR_CATEGORIES.INVENTORY,
  [FLASH_SALE_ERROR_CODES.INVENTORY_LOCK_FAILED]: FLASH_SALE_ERROR_CATEGORIES.INVENTORY,
  [FLASH_SALE_ERROR_CODES.INVENTORY_RESERVATION_FAILED]: FLASH_SALE_ERROR_CATEGORIES.INVENTORY,
  [FLASH_SALE_ERROR_CODES.INVENTORY_RELEASE_FAILED]: FLASH_SALE_ERROR_CATEGORIES.INVENTORY,
  [FLASH_SALE_ERROR_CODES.PAYMENT_FAILED]: FLASH_SALE_ERROR_CATEGORIES.PAYMENT,
  [FLASH_SALE_ERROR_CODES.PAYMENT_TIMEOUT]: FLASH_SALE_ERROR_CATEGORIES.PAYMENT,
  [FLASH_SALE_ERROR_CODES.PAYMENT_REFUND_FAILED]: FLASH_SALE_ERROR_CATEGORIES.PAYMENT,
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_BALANCE]: FLASH_SALE_ERROR_CATEGORIES.PAYMENT,
  [FLASH_SALE_ERROR_CODES.INTERNAL_SERVER_ERROR]: FLASH_SALE_ERROR_CATEGORIES.SYSTEM,
  [FLASH_SALE_ERROR_CODES.SERVICE_UNAVAILABLE]: FLASH_SALE_ERROR_CATEGORIES.SYSTEM,
  [FLASH_SALE_ERROR_CODES.DATABASE_ERROR]: FLASH_SALE_ERROR_CATEGORIES.SYSTEM,
  [FLASH_SALE_ERROR_CODES.CACHE_ERROR]: FLASH_SALE_ERROR_CATEGORIES.SYSTEM,
  [FLASH_SALE_ERROR_CODES.QUEUE_ERROR]: FLASH_SALE_ERROR_CATEGORIES.SYSTEM,
  [FLASH_SALE_ERROR_CODES.NETWORK_ERROR]: FLASH_SALE_ERROR_CATEGORIES.NETWORK,
  [FLASH_SALE_ERROR_CODES.CONNECTION_TIMEOUT]: FLASH_SALE_ERROR_CATEGORIES.NETWORK,
  [FLASH_SALE_ERROR_CODES.CONNECTION_REFUSED]: FLASH_SALE_ERROR_CATEGORIES.NETWORK,
  [FLASH_SALE_ERROR_CODES.RATE_LIMIT_EXCEEDED]: FLASH_SALE_ERROR_CATEGORIES.RATE_LIMIT,
  [FLASH_SALE_ERROR_CODES.TOO_MANY_REQUESTS]: FLASH_SALE_ERROR_CATEGORIES.RATE_LIMIT,
  [FLASH_SALE_ERROR_CODES.REQUEST_THROTTLED]: FLASH_SALE_ERROR_CATEGORIES.RATE_LIMIT,
  [FLASH_SALE_ERROR_CODES.SALE_NOT_ACTIVE]: FLASH_SALE_ERROR_CATEGORIES.BUSINESS,
  [FLASH_SALE_ERROR_CODES.SALE_NOT_STARTED]: FLASH_SALE_ERROR_CATEGORIES.BUSINESS,
  [FLASH_SALE_ERROR_CODES.SALE_ALREADY_ENDED]: FLASH_SALE_ERROR_CATEGORIES.BUSINESS,
  [FLASH_SALE_ERROR_CODES.SALE_FULLY_BOOKED]: FLASH_SALE_ERROR_CATEGORIES.BUSINESS,
  [FLASH_SALE_ERROR_CODES.MAX_PARTICIPANTS_REACHED]: FLASH_SALE_ERROR_CATEGORIES.BUSINESS,
  [FLASH_SALE_ERROR_CODES.MAX_ITEMS_PER_USER_REACHED]: FLASH_SALE_ERROR_CATEGORIES.BUSINESS,
  [FLASH_SALE_ERROR_CODES.MIN_ORDER_REQUIREMENT_NOT_MET]: FLASH_SALE_ERROR_CATEGORIES.BUSINESS,
  [FLASH_SALE_ERROR_CODES.COUPON_EXPIRED]: FLASH_SALE_ERROR_CATEGORIES.BUSINESS,
  [FLASH_SALE_ERROR_CODES.COUPON_USED]: FLASH_SALE_ERROR_CATEGORIES.BUSINESS,
  [FLASH_SALE_ERROR_CODES.VOUCHER_EXPIRED]: FLASH_SALE_ERROR_CATEGORIES.BUSINESS,
  [FLASH_SALE_ERROR_CODES.VOUCHER_USED]: FLASH_SALE_ERROR_CATEGORIES.BUSINESS,
  [FLASH_SALE_ERROR_CODES.RESTRICTION_VIOLATION]: FLASH_SALE_ERROR_CATEGORIES.BUSINESS,
  [FLASH_SALE_ERROR_CODES.ELIGIBILITY_FAILED]: FLASH_SALE_ERROR_CATEGORIES.BUSINESS,
};

// Error Severity Mapping
export const FLASH_SALE_ERROR_SEVERITY_MAP: Record<string, string> = {
  [FLASH_SALE_ERROR_CODES.VALIDATION_ERROR]: FLASH_SALE_ERROR_SEVERITY.LOW,
  [FLASH_SALE_ERROR_CODES.INVALID_INPUT]: FLASH_SALE_ERROR_SEVERITY.LOW,
  [FLASH_SALE_ERROR_CODES.MISSING_REQUIRED_FIELD]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.INVALID_FORMAT]: FLASH_SALE_ERROR_SEVERITY.LOW,
  [FLASH_SALE_ERROR_CODES.INVALID_DATE]: FLASH_SALE_ERROR_SEVERITY.LOW,
  [FLASH_SALE_ERROR_CODES.INVALID_TIME]: FLASH_SALE_ERROR_SEVERITY.LOW,
  [FLASH_SALE_ERROR_CODES.INVALID_AMOUNT]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.INVALID_QUANTITY]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.INVALID_DISCOUNT]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.UNAUTHORIZED]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.INVALID_TOKEN]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.TOKEN_EXPIRED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.SESSION_EXPIRED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.INVALID_CREDENTIALS]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.FORBIDDEN]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_PERMISSIONS]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.ROLE_NOT_ALLOWED]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.NOT_FOUND]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.FLASH_SALE_NOT_FOUND]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.PRODUCT_NOT_FOUND]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.DEAL_NOT_FOUND]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.COUPON_NOT_FOUND]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.VOUCHER_NOT_FOUND]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.USER_NOT_FOUND]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.CONFLICT]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.DUPLICATE_ENTRY]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.ALREADY_EXISTS]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.ALREADY_ACTIVE]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.ALREADY_EXPIRED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.ALREADY_CANCELLED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.OUT_OF_STOCK]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_STOCK]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.INVENTORY_LOCK_FAILED]: FLASH_SALE_ERROR_SEVERITY.CRITICAL,
  [FLASH_SALE_ERROR_CODES.INVENTORY_RESERVATION_FAILED]: FLASH_SALE_ERROR_SEVERITY.CRITICAL,
  [FLASH_SALE_ERROR_CODES.INVENTORY_RELEASE_FAILED]: FLASH_SALE_ERROR_SEVERITY.CRITICAL,
  [FLASH_SALE_ERROR_CODES.PAYMENT_FAILED]: FLASH_SALE_ERROR_SEVERITY.CRITICAL,
  [FLASH_SALE_ERROR_CODES.PAYMENT_TIMEOUT]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.PAYMENT_REFUND_FAILED]: FLASH_SALE_ERROR_SEVERITY.CRITICAL,
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_BALANCE]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.INTERNAL_SERVER_ERROR]: FLASH_SALE_ERROR_SEVERITY.CRITICAL,
  [FLASH_SALE_ERROR_CODES.SERVICE_UNAVAILABLE]: FLASH_SALE_ERROR_SEVERITY.CRITICAL,
  [FLASH_SALE_ERROR_CODES.DATABASE_ERROR]: FLASH_SALE_ERROR_SEVERITY.CRITICAL,
  [FLASH_SALE_ERROR_CODES.CACHE_ERROR]: FLASH_SALE_ERROR_SEVERITY.CRITICAL,
  [FLASH_SALE_ERROR_CODES.QUEUE_ERROR]: FLASH_SALE_ERROR_SEVERITY.CRITICAL,
  [FLASH_SALE_ERROR_CODES.NETWORK_ERROR]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.CONNECTION_TIMEOUT]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.CONNECTION_REFUSED]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.RATE_LIMIT_EXCEEDED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.TOO_MANY_REQUESTS]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.REQUEST_THROTTLED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.SALE_NOT_ACTIVE]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.SALE_NOT_STARTED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.SALE_ALREADY_ENDED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.SALE_FULLY_BOOKED]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.MAX_PARTICIPANTS_REACHED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.MAX_ITEMS_PER_USER_REACHED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.MIN_ORDER_REQUIREMENT_NOT_MET]: FLASH_SALE_ERROR_SEVERITY.LOW,
  [FLASH_SALE_ERROR_CODES.COUPON_EXPIRED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.COUPON_USED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.VOUCHER_EXPIRED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.VOUCHER_USED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
  [FLASH_SALE_ERROR_CODES.RESTRICTION_VIOLATION]: FLASH_SALE_ERROR_SEVERITY.HIGH,
  [FLASH_SALE_ERROR_CODES.ELIGIBILITY_FAILED]: FLASH_SALE_ERROR_SEVERITY.MEDIUM,
};

// Error Retry Mapping
export const FLASH_SALE_ERROR_RETRY_MAP: Record<string, string> = {
  [FLASH_SALE_ERROR_CODES.VALIDATION_ERROR]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.INVALID_INPUT]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.MISSING_REQUIRED_FIELD]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.INVALID_FORMAT]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.INVALID_DATE]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.INVALID_TIME]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.INVALID_AMOUNT]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.INVALID_QUANTITY]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.INVALID_DISCOUNT]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.UNAUTHORIZED]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.INVALID_TOKEN]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.TOKEN_EXPIRED]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.SESSION_EXPIRED]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.INVALID_CREDENTIALS]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.FORBIDDEN]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_PERMISSIONS]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.ROLE_NOT_ALLOWED]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.NOT_FOUND]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.FLASH_SALE_NOT_FOUND]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.PRODUCT_NOT_FOUND]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.DEAL_NOT_FOUND]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.COUPON_NOT_FOUND]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.VOUCHER_NOT_FOUND]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.USER_NOT_FOUND]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.CONFLICT]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.DUPLICATE_ENTRY]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.ALREADY_EXISTS]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.ALREADY_ACTIVE]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.ALREADY_EXPIRED]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.ALREADY_CANCELLED]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.OUT_OF_STOCK]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_STOCK]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.INVENTORY_LOCK_FAILED]: FLASH_SALE_ERROR_RETRY.MUST_RETRY,
  [FLASH_SALE_ERROR_CODES.INVENTORY_RESERVATION_FAILED]: FLASH_SALE_ERROR_RETRY.MUST_RETRY,
  [FLASH_SALE_ERROR_CODES.INVENTORY_RELEASE_FAILED]: FLASH_SALE_ERROR_RETRY.MUST_RETRY,
  [FLASH_SALE_ERROR_CODES.PAYMENT_FAILED]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.PAYMENT_TIMEOUT]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.PAYMENT_REFUND_FAILED]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.INSUFFICIENT_BALANCE]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.INTERNAL_SERVER_ERROR]: FLASH_SALE_ERROR_RETRY.MUST_RETRY,
  [FLASH_SALE_ERROR_CODES.SERVICE_UNAVAILABLE]: FLASH_SALE_ERROR_RETRY.MUST_RETRY,
  [FLASH_SALE_ERROR_CODES.DATABASE_ERROR]: FLASH_SALE_ERROR_RETRY.MUST_RETRY,
  [FLASH_SALE_ERROR_CODES.CACHE_ERROR]: FLASH_SALE_ERROR_RETRY.MUST_RETRY,
  [FLASH_SALE_ERROR_CODES.QUEUE_ERROR]: FLASH_SALE_ERROR_RETRY.MUST_RETRY,
  [FLASH_SALE_ERROR_CODES.NETWORK_ERROR]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.CONNECTION_TIMEOUT]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.CONNECTION_REFUSED]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.RATE_LIMIT_EXCEEDED]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.TOO_MANY_REQUESTS]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.REQUEST_THROTTLED]: FLASH_SALE_ERROR_RETRY.RETRYABLE,
  [FLASH_SALE_ERROR_CODES.SALE_NOT_ACTIVE]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.SALE_NOT_STARTED]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.SALE_ALREADY_ENDED]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.SALE_FULLY_BOOKED]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.MAX_PARTICIPANTS_REACHED]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.MAX_ITEMS_PER_USER_REACHED]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.MIN_ORDER_REQUIREMENT_NOT_MET]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.COUPON_EXPIRED]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.COUPON_USED]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.VOUCHER_EXPIRED]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.VOUCHER_USED]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.RESTRICTION_VIOLATION]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
  [FLASH_SALE_ERROR_CODES.ELIGIBILITY_FAILED]: FLASH_SALE_ERROR_RETRY.NOT_RETRYABLE,
};

// Export Combined Object for Backward Compatibility
export const FLASH_SALE_ERROR = {
  CATEGORIES: FLASH_SALE_ERROR_CATEGORIES,
  CODES: FLASH_SALE_ERROR_CODES,
  MESSAGES: FLASH_SALE_ERROR_MESSAGES,
  HTTP_STATUS: FLASH_SALE_ERROR_HTTP_STATUS,
  SEVERITY: FLASH_SALE_ERROR_SEVERITY,
  RETRY: FLASH_SALE_ERROR_RETRY,
} as const;

// Types
export type FlashSaleErrorCategory =
  (typeof FLASH_SALE_ERROR_CATEGORIES)[keyof typeof FLASH_SALE_ERROR_CATEGORIES];
export type FlashSaleErrorCode =
  (typeof FLASH_SALE_ERROR_CODES)[keyof typeof FLASH_SALE_ERROR_CODES];
export type FlashSaleErrorSeverity =
  (typeof FLASH_SALE_ERROR_SEVERITY)[keyof typeof FLASH_SALE_ERROR_SEVERITY];
export type FlashSaleErrorRetry =
  (typeof FLASH_SALE_ERROR_RETRY)[keyof typeof FLASH_SALE_ERROR_RETRY];

// Utility Functions
export function flashsalesErrorGetMessage(code: FlashSaleErrorCode): string {
  return FLASH_SALE_ERROR_MESSAGES[code] || 'An unknown error occurred';
}

export function flashsalesErrorGetHttpStatus(code: FlashSaleErrorCode): number {
  return FLASH_SALE_ERROR_HTTP_STATUS[code] || 500;
}

export function flashsalesErrorGetCategory(code: FlashSaleErrorCode): FlashSaleErrorCategory {
  return (FLASH_SALE_ERROR_CATEGORY_MAP[code] ||
    FLASH_SALE_ERROR_CATEGORIES.SYSTEM) as FlashSaleErrorCategory;
}

export function flashsalesErrorGetSeverity(code: FlashSaleErrorCode): FlashSaleErrorSeverity {
  return (FLASH_SALE_ERROR_SEVERITY_MAP[code] ||
    FLASH_SALE_ERROR_SEVERITY.MEDIUM) as FlashSaleErrorSeverity;
}

export function flashsalesErrorGetRetryType(code: FlashSaleErrorCode): FlashSaleErrorRetry {
  return (FLASH_SALE_ERROR_RETRY_MAP[code] ||
    FLASH_SALE_ERROR_RETRY.RETRYABLE) as FlashSaleErrorRetry;
}

export function flashsalesErrorIsRetryable(code: FlashSaleErrorCode): boolean {
  const retryType = flashsalesErrorGetRetryType(code);
  return (
    retryType === FLASH_SALE_ERROR_RETRY.RETRYABLE ||
    retryType === FLASH_SALE_ERROR_RETRY.MUST_RETRY
  );
}

export function flashsalesErrorIsCritical(code: FlashSaleErrorCode): boolean {
  return flashsalesErrorGetSeverity(code) === FLASH_SALE_ERROR_SEVERITY.CRITICAL;
}

export function flashsalesErrorIsClientError(code: FlashSaleErrorCode): boolean {
  const status = flashsalesErrorGetHttpStatus(code);
  return status >= 400 && status < 500;
}

export function flashsalesErrorIsServerError(code: FlashSaleErrorCode): boolean {
  const status = flashsalesErrorGetHttpStatus(code);
  return status >= 500 && status < 600;
}
