export const AUTH_VERIFICATION = {
  OTP_LENGTH: 6,
  OTP_EXPIRY_SECONDS: 300,
  OTP_MAX_ATTEMPTS: 5,
  OTP_RESEND_COOLDOWN_SECONDS: 60,
  OTP_MAX_RESEND: 3,
  EMAIL_TOKEN_EXPIRY_SECONDS: 86400,
  PHONE_TOKEN_EXPIRY_SECONDS: 600,
  MAGIC_LINK_EXPIRY_SECONDS: 900,
} as const;

export const AUTH_VERIFICATION_CHANNEL = {
  EMAIL: 'email',
  SMS: 'sms',
  WHATSAPP: 'whatsapp',
  PUSH: 'push',
} as const;

export type AuthVerificationChannelType =
  (typeof AUTH_VERIFICATION_CHANNEL)[keyof typeof AUTH_VERIFICATION_CHANNEL];
