import { NOTIFICATION_STATUS } from './notification-status.constants';
import { NOTIFICATION_TYPE } from './notification-type.constants';
import {
  NOTIFICATION_CHANNEL,
  NOTIFICATION_CHANNEL_PRIORITY,
  NOTIFICATION_CHANNEL_LIMIT,
} from './notification-channel.constants';
import {
  NOTIFICATION_PRIORITY,
  NOTIFICATION_PRIORITY_WEIGHT,
  NOTIFICATION_PRIORITY_TTL,
} from './notification-priority.constants';
import { NOTIFICATION_CATEGORY } from './notification-category.constants';
import {
  NOTIFICATION_DELIVERY_STATUS,
  NOTIFICATION_DELIVERY_FAILURE_REASON,
} from './notification-delivery-status.constants';
import { NOTIFICATION_READ_STATUS, NOTIFICATION_READ } from './notification-read-status.constants';
import { NOTIFICATION_ACTION, NOTIFICATION_ACTION_TYPE } from './notification-action.constants';
import { EMAIL_PROVIDER, EMAIL_STATUS, EMAIL_PRIORITY, EMAIL } from './email.constants';
import { SMS_PROVIDER, SMS_STATUS, SMS_TYPE, SMS } from './sms.constants';
import { PUSH_PROVIDER, PUSH_PLATFORM, PUSH_STATUS, PUSH_PRIORITY, PUSH } from './push.constants';
import { IN_APP_TYPE, IN_APP_POSITION, IN_APP_STATUS, IN_APP } from './in-app.constants';
import {
  WEBHOOK_METHOD,
  WEBHOOK_STATUS,
  WEBHOOK_DELIVERY_STATUS,
  WEBHOOK_EVENT,
  WEBHOOK,
} from './webhook.constants';
import {
  NOTIFICATION_TEMPLATE_TYPE,
  NOTIFICATION_TEMPLATE_STATUS,
  NOTIFICATION_TEMPLATE_CATEGORY,
  NOTIFICATION_TEMPLATE,
} from './notification-template.constants';
import {
  NOTIFICATION_SCHEDULE_TYPE,
  NOTIFICATION_SCHEDULE_RECURRENCE,
  NOTIFICATION_SCHEDULE_STATUS,
  NOTIFICATION_SCHEDULE,
} from './notification-schedule.constants';
import {
  NOTIFICATION_BROADCAST_TYPE,
  NOTIFICATION_BROADCAST_STATUS,
  NOTIFICATION_BROADCAST_TARGET,
  NOTIFICATION_BROADCAST,
} from './notification-broadcast.constants';
import {
  NOTIFICATION_DIGEST_FREQUENCY,
  NOTIFICATION_DIGEST_TYPE,
  NOTIFICATION_DIGEST_STATUS,
  NOTIFICATION_DIGEST,
} from './notification-digest.constants';
import {
  NOTIFICATION_RULE_TYPE,
  NOTIFICATION_RULE_CONDITION,
  NOTIFICATION_RULE_ACTION,
  NOTIFICATION_RULE_STATUS,
  NOTIFICATION_RULE,
} from './notification-rule.constants';
import {
  NOTIFICATION_PREFERENCE_TYPE,
  NOTIFICATION_PREFERENCE_FREQUENCY,
  NOTIFICATION_PREFERENCE_DEFAULT,
  NOTIFICATION_PREFERENCE,
} from './notification-preference.constants';
import {
  NOTIFICATION_DEVICE_TYPE,
  NOTIFICATION_DEVICE_STATUS,
  NOTIFICATION_DEVICE,
} from './notification-device.constants';
import {
  NOTIFICATION_ANALYTICS_METRIC,
  NOTIFICATION_ANALYTICS_PERIOD,
  NOTIFICATION_ANALYTICS,
} from './notification-analytics.constants';
import {
  NOTIFICATION_REPORT_TYPE,
  NOTIFICATION_REPORT_FORMAT,
  NOTIFICATION_REPORT_SCHEDULE,
  NOTIFICATION_REPORT,
} from './notification-report.constants';

export const NOTIFICATION_LIMIT = {
  MAX_RECIPIENTS: 1000000,
  MAX_PER_BATCH: 1000,
  MAX_TEMPLATES: 1000,
  MAX_SCHEDULES: 10000,
  MAX_BROADCASTS: 100,
  MAX_RULES: 500,
  MAX_DEVICES_PER_USER: 10,
  MAX_ACTIVE_WEBHOOKS: 50,
  RETENTION_DAYS: 365,
  DELIVERY_TIMEOUT_SECONDS: 60,
  RETRY_ATTEMPTS: 3,
} as const;

export const NOTIFICATION = {
  TYPE: NOTIFICATION_TYPE,
  STATUS: NOTIFICATION_STATUS,
  CATEGORY: NOTIFICATION_CATEGORY,
  LIMIT: NOTIFICATION_LIMIT,

  CHANNEL: {
    TYPE: NOTIFICATION_CHANNEL,
    PRIORITY: NOTIFICATION_CHANNEL_PRIORITY,
    LIMIT: NOTIFICATION_CHANNEL_LIMIT,
  },

  PRIORITY: {
    TYPE: NOTIFICATION_PRIORITY,
    WEIGHT: NOTIFICATION_PRIORITY_WEIGHT,
    TTL: NOTIFICATION_PRIORITY_TTL,
  },

  DELIVERY: {
    STATUS: NOTIFICATION_DELIVERY_STATUS,
    FAILURE_REASON: NOTIFICATION_DELIVERY_FAILURE_REASON,
  },

  READ: {
    STATUS: NOTIFICATION_READ_STATUS,
    LIMIT: NOTIFICATION_READ,
  },

  ACTION: {
    TYPE: NOTIFICATION_ACTION,
    BUTTON_TYPE: NOTIFICATION_ACTION_TYPE,
  },

  EMAIL: {
    PROVIDER: EMAIL_PROVIDER,
    STATUS: EMAIL_STATUS,
    PRIORITY: EMAIL_PRIORITY,
    LIMIT: EMAIL,
  },

  SMS: {
    PROVIDER: SMS_PROVIDER,
    STATUS: SMS_STATUS,
    TYPE: SMS_TYPE,
    LIMIT: SMS,
  },

  PUSH: {
    PROVIDER: PUSH_PROVIDER,
    PLATFORM: PUSH_PLATFORM,
    STATUS: PUSH_STATUS,
    PRIORITY: PUSH_PRIORITY,
    LIMIT: PUSH,
  },

  IN_APP: {
    TYPE: IN_APP_TYPE,
    POSITION: IN_APP_POSITION,
    STATUS: IN_APP_STATUS,
    LIMIT: IN_APP,
  },

  WEBHOOK: {
    METHOD: WEBHOOK_METHOD,
    STATUS: WEBHOOK_STATUS,
    DELIVERY_STATUS: WEBHOOK_DELIVERY_STATUS,
    EVENT: WEBHOOK_EVENT,
    LIMIT: WEBHOOK,
  },

  TEMPLATE: {
    TYPE: NOTIFICATION_TEMPLATE_TYPE,
    STATUS: NOTIFICATION_TEMPLATE_STATUS,
    CATEGORY: NOTIFICATION_TEMPLATE_CATEGORY,
    LIMIT: NOTIFICATION_TEMPLATE,
  },

  SCHEDULE: {
    TYPE: NOTIFICATION_SCHEDULE_TYPE,
    RECURRENCE: NOTIFICATION_SCHEDULE_RECURRENCE,
    STATUS: NOTIFICATION_SCHEDULE_STATUS,
    LIMIT: NOTIFICATION_SCHEDULE,
  },

  BROADCAST: {
    TYPE: NOTIFICATION_BROADCAST_TYPE,
    STATUS: NOTIFICATION_BROADCAST_STATUS,
    TARGET: NOTIFICATION_BROADCAST_TARGET,
    LIMIT: NOTIFICATION_BROADCAST,
  },

  DIGEST: {
    FREQUENCY: NOTIFICATION_DIGEST_FREQUENCY,
    TYPE: NOTIFICATION_DIGEST_TYPE,
    STATUS: NOTIFICATION_DIGEST_STATUS,
    LIMIT: NOTIFICATION_DIGEST,
  },

  RULE: {
    TYPE: NOTIFICATION_RULE_TYPE,
    CONDITION: NOTIFICATION_RULE_CONDITION,
    ACTION: NOTIFICATION_RULE_ACTION,
    STATUS: NOTIFICATION_RULE_STATUS,
    LIMIT: NOTIFICATION_RULE,
  },

  PREFERENCE: {
    TYPE: NOTIFICATION_PREFERENCE_TYPE,
    FREQUENCY: NOTIFICATION_PREFERENCE_FREQUENCY,
    DEFAULT: NOTIFICATION_PREFERENCE_DEFAULT,
    LIMIT: NOTIFICATION_PREFERENCE,
  },

  DEVICE: {
    TYPE: NOTIFICATION_DEVICE_TYPE,
    STATUS: NOTIFICATION_DEVICE_STATUS,
    LIMIT: NOTIFICATION_DEVICE,
  },

  ANALYTICS: {
    METRIC: NOTIFICATION_ANALYTICS_METRIC,
    PERIOD: NOTIFICATION_ANALYTICS_PERIOD,
    LIMIT: NOTIFICATION_ANALYTICS,
  },

  REPORT: {
    TYPE: NOTIFICATION_REPORT_TYPE,
    FORMAT: NOTIFICATION_REPORT_FORMAT,
    SCHEDULE: NOTIFICATION_REPORT_SCHEDULE,
    LIMIT: NOTIFICATION_REPORT,
  },
} as const;

export type NotificationType = typeof NOTIFICATION;
