/**
 * AI Similarity Status Constants
 * Status tracking for similarity operations
 */

// First define the status types
export const AI_SIMILARITY_STATUS_TYPES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Processing States
  INITIALIZING: 'initializing',
  CALCULATING: 'calculating',
  COMPARING: 'comparing',
  ANALYZING: 'analyzing',
  VALIDATING: 'validating',

  // Intermediate States
  CALCULATED: 'calculated',
  COMPARED: 'compared',
  ANALYZED: 'analyzed',
  VALIDATED: 'validated',
  OPTIMIZED: 'optimized',

  // Storage States
  STORING: 'storing',
  STORED: 'stored',
  CACHING: 'caching',
  CACHED: 'cached',

  // Terminal States
  COMPLETED: 'completed',
  FAILED: 'failed',
  EXPIRED: 'expired',
  ARCHIVED: 'archived',
} as const;

export type AISimilarityStatusType =
  (typeof AI_SIMILARITY_STATUS_TYPES)[keyof typeof AI_SIMILARITY_STATUS_TYPES];

export const AI_SIMILARITY_STATUS = {
  // Status Types
  STATUSES: AI_SIMILARITY_STATUS_TYPES,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CACHED: 'cached',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_SIMILARITY_STATUS_TYPES.CREATED]: '#gray',
    [AI_SIMILARITY_STATUS_TYPES.QUEUED]: '#gray',
    [AI_SIMILARITY_STATUS_TYPES.PENDING]: '#yellow',
    [AI_SIMILARITY_STATUS_TYPES.INITIALIZING]: '#blue',
    [AI_SIMILARITY_STATUS_TYPES.CALCULATING]: '#blue',
    [AI_SIMILARITY_STATUS_TYPES.COMPARING]: '#blue',
    [AI_SIMILARITY_STATUS_TYPES.ANALYZING]: '#blue',
    [AI_SIMILARITY_STATUS_TYPES.VALIDATING]: '#purple',
    [AI_SIMILARITY_STATUS_TYPES.CALCULATED]: '#green',
    [AI_SIMILARITY_STATUS_TYPES.COMPARED]: '#green',
    [AI_SIMILARITY_STATUS_TYPES.ANALYZED]: '#green',
    [AI_SIMILARITY_STATUS_TYPES.VALIDATED]: '#green',
    [AI_SIMILARITY_STATUS_TYPES.OPTIMIZED]: '#green',
    [AI_SIMILARITY_STATUS_TYPES.STORING]: '#orange',
    [AI_SIMILARITY_STATUS_TYPES.STORED]: '#green',
    [AI_SIMILARITY_STATUS_TYPES.CACHING]: '#orange',
    [AI_SIMILARITY_STATUS_TYPES.CACHED]: '#green',
    [AI_SIMILARITY_STATUS_TYPES.COMPLETED]: '#green',
    [AI_SIMILARITY_STATUS_TYPES.FAILED]: '#red',
    [AI_SIMILARITY_STATUS_TYPES.EXPIRED]: '#gray',
    [AI_SIMILARITY_STATUS_TYPES.ARCHIVED]: '#gray',
  } as const,
} as const;

export type AISimilarityStatusCategory =
  (typeof AI_SIMILARITY_STATUS.CATEGORIES)[keyof typeof AI_SIMILARITY_STATUS.CATEGORIES];
export type AISimilarityStatusSeverity =
  (typeof AI_SIMILARITY_STATUS.SEVERITY)[keyof typeof AI_SIMILARITY_STATUS.SEVERITY];
export type AISimilarityStatusColor =
  (typeof AI_SIMILARITY_STATUS.COLORS)[keyof typeof AI_SIMILARITY_STATUS.COLORS];

export function getAiSimilarityStatusLabel(status: AISimilarityStatusType): string {
  const labels: Record<AISimilarityStatusType, string> = {
    [AI_SIMILARITY_STATUS_TYPES.CREATED]: 'Created',
    [AI_SIMILARITY_STATUS_TYPES.QUEUED]: 'Queued',
    [AI_SIMILARITY_STATUS_TYPES.PENDING]: 'Pending',
    [AI_SIMILARITY_STATUS_TYPES.INITIALIZING]: 'Initializing',
    [AI_SIMILARITY_STATUS_TYPES.CALCULATING]: 'Calculating',
    [AI_SIMILARITY_STATUS_TYPES.COMPARING]: 'Comparing',
    [AI_SIMILARITY_STATUS_TYPES.ANALYZING]: 'Analyzing',
    [AI_SIMILARITY_STATUS_TYPES.VALIDATING]: 'Validating',
    [AI_SIMILARITY_STATUS_TYPES.CALCULATED]: 'Calculated',
    [AI_SIMILARITY_STATUS_TYPES.COMPARED]: 'Compared',
    [AI_SIMILARITY_STATUS_TYPES.ANALYZED]: 'Analyzed',
    [AI_SIMILARITY_STATUS_TYPES.VALIDATED]: 'Validated',
    [AI_SIMILARITY_STATUS_TYPES.OPTIMIZED]: 'Optimized',
    [AI_SIMILARITY_STATUS_TYPES.STORING]: 'Storing',
    [AI_SIMILARITY_STATUS_TYPES.STORED]: 'Stored',
    [AI_SIMILARITY_STATUS_TYPES.CACHING]: 'Caching',
    [AI_SIMILARITY_STATUS_TYPES.CACHED]: 'Cached',
    [AI_SIMILARITY_STATUS_TYPES.COMPLETED]: 'Completed',
    [AI_SIMILARITY_STATUS_TYPES.FAILED]: 'Failed',
    [AI_SIMILARITY_STATUS_TYPES.EXPIRED]: 'Expired',
    [AI_SIMILARITY_STATUS_TYPES.ARCHIVED]: 'Archived',
  };
  return labels[status] || 'Unknown';
}

export function getAiSimilarityStatusCategory(
  status: AISimilarityStatusType
): AISimilarityStatusCategory {
  const categories: Record<AISimilarityStatusType, AISimilarityStatusCategory> = {
    [AI_SIMILARITY_STATUS_TYPES.CREATED]: AI_SIMILARITY_STATUS.CATEGORIES.PENDING,
    [AI_SIMILARITY_STATUS_TYPES.QUEUED]: AI_SIMILARITY_STATUS.CATEGORIES.PENDING,
    [AI_SIMILARITY_STATUS_TYPES.PENDING]: AI_SIMILARITY_STATUS.CATEGORIES.PENDING,
    [AI_SIMILARITY_STATUS_TYPES.INITIALIZING]: AI_SIMILARITY_STATUS.CATEGORIES.PROCESSING,
    [AI_SIMILARITY_STATUS_TYPES.CALCULATING]: AI_SIMILARITY_STATUS.CATEGORIES.PROCESSING,
    [AI_SIMILARITY_STATUS_TYPES.COMPARING]: AI_SIMILARITY_STATUS.CATEGORIES.PROCESSING,
    [AI_SIMILARITY_STATUS_TYPES.ANALYZING]: AI_SIMILARITY_STATUS.CATEGORIES.PROCESSING,
    [AI_SIMILARITY_STATUS_TYPES.VALIDATING]: AI_SIMILARITY_STATUS.CATEGORIES.PROCESSING,
    [AI_SIMILARITY_STATUS_TYPES.CALCULATED]: AI_SIMILARITY_STATUS.CATEGORIES.PROCESSING,
    [AI_SIMILARITY_STATUS_TYPES.COMPARED]: AI_SIMILARITY_STATUS.CATEGORIES.PROCESSING,
    [AI_SIMILARITY_STATUS_TYPES.ANALYZED]: AI_SIMILARITY_STATUS.CATEGORIES.PROCESSING,
    [AI_SIMILARITY_STATUS_TYPES.VALIDATED]: AI_SIMILARITY_STATUS.CATEGORIES.PROCESSING,
    [AI_SIMILARITY_STATUS_TYPES.OPTIMIZED]: AI_SIMILARITY_STATUS.CATEGORIES.PROCESSING,
    [AI_SIMILARITY_STATUS_TYPES.STORING]: AI_SIMILARITY_STATUS.CATEGORIES.PROCESSING,
    [AI_SIMILARITY_STATUS_TYPES.STORED]: AI_SIMILARITY_STATUS.CATEGORIES.COMPLETED,
    [AI_SIMILARITY_STATUS_TYPES.CACHING]: AI_SIMILARITY_STATUS.CATEGORIES.PROCESSING,
    [AI_SIMILARITY_STATUS_TYPES.CACHED]: AI_SIMILARITY_STATUS.CATEGORIES.CACHED,
    [AI_SIMILARITY_STATUS_TYPES.COMPLETED]: AI_SIMILARITY_STATUS.CATEGORIES.COMPLETED,
    [AI_SIMILARITY_STATUS_TYPES.FAILED]: AI_SIMILARITY_STATUS.CATEGORIES.FAILED,
    [AI_SIMILARITY_STATUS_TYPES.EXPIRED]: AI_SIMILARITY_STATUS.CATEGORIES.FAILED,
    [AI_SIMILARITY_STATUS_TYPES.ARCHIVED]: AI_SIMILARITY_STATUS.CATEGORIES.COMPLETED,
  };
  return categories[status] || AI_SIMILARITY_STATUS.CATEGORIES.PENDING;
}

export function getAiSimilarityStatusSeverity(
  status: AISimilarityStatusType
): AISimilarityStatusSeverity {
  const severities: Record<AISimilarityStatusType, AISimilarityStatusSeverity> = {
    [AI_SIMILARITY_STATUS_TYPES.CREATED]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.QUEUED]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.PENDING]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.INITIALIZING]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.CALCULATING]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.COMPARING]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.ANALYZING]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.VALIDATING]: AI_SIMILARITY_STATUS.SEVERITY.WARNING,
    [AI_SIMILARITY_STATUS_TYPES.CALCULATED]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.COMPARED]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.ANALYZED]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.VALIDATED]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.OPTIMIZED]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.STORING]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.STORED]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.CACHING]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.CACHED]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.COMPLETED]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
    [AI_SIMILARITY_STATUS_TYPES.FAILED]: AI_SIMILARITY_STATUS.SEVERITY.ERROR,
    [AI_SIMILARITY_STATUS_TYPES.EXPIRED]: AI_SIMILARITY_STATUS.SEVERITY.WARNING,
    [AI_SIMILARITY_STATUS_TYPES.ARCHIVED]: AI_SIMILARITY_STATUS.SEVERITY.INFO,
  };
  return severities[status] || AI_SIMILARITY_STATUS.SEVERITY.INFO;
}

export function getAiSimilarityStatusColor(
  status: AISimilarityStatusType
): AISimilarityStatusColor {
  return AI_SIMILARITY_STATUS.COLORS[status] || '#gray';
}

export function isAiSimilarityActiveStatus(status: AISimilarityStatusType): boolean {
  const activeStatuses: AISimilarityStatusType[] = [
    AI_SIMILARITY_STATUS_TYPES.CREATED,
    AI_SIMILARITY_STATUS_TYPES.QUEUED,
    AI_SIMILARITY_STATUS_TYPES.PENDING,
    AI_SIMILARITY_STATUS_TYPES.INITIALIZING,
    AI_SIMILARITY_STATUS_TYPES.CALCULATING,
    AI_SIMILARITY_STATUS_TYPES.COMPARING,
    AI_SIMILARITY_STATUS_TYPES.ANALYZING,
    AI_SIMILARITY_STATUS_TYPES.VALIDATING,
    AI_SIMILARITY_STATUS_TYPES.CALCULATED,
    AI_SIMILARITY_STATUS_TYPES.COMPARED,
    AI_SIMILARITY_STATUS_TYPES.ANALYZED,
    AI_SIMILARITY_STATUS_TYPES.VALIDATED,
    AI_SIMILARITY_STATUS_TYPES.OPTIMIZED,
    AI_SIMILARITY_STATUS_TYPES.STORING,
    AI_SIMILARITY_STATUS_TYPES.CACHING,
  ];
  return activeStatuses.includes(status);
}

export function isAiSimilarityCompleted(status: AISimilarityStatusType): boolean {
  const completedStatuses: AISimilarityStatusType[] = [
    AI_SIMILARITY_STATUS_TYPES.COMPLETED,
    AI_SIMILARITY_STATUS_TYPES.STORED,
    AI_SIMILARITY_STATUS_TYPES.CACHED,
    AI_SIMILARITY_STATUS_TYPES.ARCHIVED,
  ];
  return completedStatuses.includes(status);
}

export function isAiSimilarityFailedStatus(status: AISimilarityStatusType): boolean {
  const failedStatuses: AISimilarityStatusType[] = [
    AI_SIMILARITY_STATUS_TYPES.FAILED,
    AI_SIMILARITY_STATUS_TYPES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}

export function getAiSimilarityStatusProgress(status: AISimilarityStatusType): number {
  const progress: Record<AISimilarityStatusType, number> = {
    [AI_SIMILARITY_STATUS_TYPES.CREATED]: 0,
    [AI_SIMILARITY_STATUS_TYPES.QUEUED]: 5,
    [AI_SIMILARITY_STATUS_TYPES.PENDING]: 10,
    [AI_SIMILARITY_STATUS_TYPES.INITIALIZING]: 15,
    [AI_SIMILARITY_STATUS_TYPES.CALCULATING]: 30,
    [AI_SIMILARITY_STATUS_TYPES.COMPARING]: 45,
    [AI_SIMILARITY_STATUS_TYPES.ANALYZING]: 55,
    [AI_SIMILARITY_STATUS_TYPES.VALIDATING]: 60,
    [AI_SIMILARITY_STATUS_TYPES.CALCULATED]: 50,
    [AI_SIMILARITY_STATUS_TYPES.COMPARED]: 55,
    [AI_SIMILARITY_STATUS_TYPES.ANALYZED]: 60,
    [AI_SIMILARITY_STATUS_TYPES.VALIDATED]: 65,
    [AI_SIMILARITY_STATUS_TYPES.OPTIMIZED]: 75,
    [AI_SIMILARITY_STATUS_TYPES.STORING]: 80,
    [AI_SIMILARITY_STATUS_TYPES.STORED]: 85,
    [AI_SIMILARITY_STATUS_TYPES.CACHING]: 88,
    [AI_SIMILARITY_STATUS_TYPES.CACHED]: 92,
    [AI_SIMILARITY_STATUS_TYPES.COMPLETED]: 100,
    [AI_SIMILARITY_STATUS_TYPES.FAILED]: 0,
    [AI_SIMILARITY_STATUS_TYPES.EXPIRED]: 0,
    [AI_SIMILARITY_STATUS_TYPES.ARCHIVED]: 100,
  };
  return progress[status] || 0;
}
