import { ANALYTICS_STATUS } from './analytics-status.constants';
import { ANALYTICS_TYPE } from './analytics-type.constants';
import { ANALYTICS_CATEGORY } from './analytics-category.constants';
import { ANALYTICS_SOURCE, ANALYTICS_SOURCE_PLATFORM } from './analytics-source.constants';
import { ANALYTICS_MEDIUM } from './analytics-medium.constants';
import {
  ANALYTICS_CAMPAIGN_TYPE,
  ANALYTICS_CAMPAIGN,
  ANALYTICS_UTM_PARAM,
} from './analytics-campaign.constants';
import { ANALYTICS_EVENT, ANALYTICS_EVENT_CATEGORY } from './analytics-event.constants';
import { ANALYTICS_METRIC, ANALYTICS_METRIC_UNIT } from './analytics-metric.constants';
import { ANALYTICS_DIMENSION, ANALYTICS_DIMENSION_TYPE } from './analytics-dimension.constants';
import {
  ANALYTICS_FILTER_OPERATOR,
  ANALYTICS_FILTER_LOGIC,
  ANALYTICS_FILTER,
} from './analytics-filter.constants';
import { ANALYTICS_PERIOD, ANALYTICS_PERIOD_DAYS } from './analytics-period.constants';
import { ANALYTICS_INTERVAL, ANALYTICS_INTERVAL_SECONDS } from './analytics-interval.constants';
import {
  ANALYTICS_AGGREGATION,
  ANALYTICS_PERCENTILE,
  ANALYTICS_AGGREGATION_LIMIT,
} from './analytics-aggregation.constants';
import {
  ANALYTICS_COMPARISON,
  ANALYTICS_CHANGE_TYPE,
  ANALYTICS_COMPARISON_LIMIT,
} from './analytics-comparison.constants';
import {
  ANALYTICS_TREND_TYPE,
  ANALYTICS_TREND_STRENGTH,
  ANALYTICS_TREND_LIMIT,
} from './analytics-trend.constants';
import { ANALYTICS_PERMISSION } from './analytics-permission.constants';

export const ANALYTICS_LIMIT = {
  MAX_DASHBOARDS: 100,
  MAX_WIDGETS_PER_DASHBOARD: 50,
  MAX_REPORTS: 500,
  MAX_EVENTS_PER_SECOND: 10000,
  MAX_METRICS_PER_QUERY: 50,
  MAX_DIMENSIONS_PER_QUERY: 10,
  MAX_FILTERS_PER_QUERY: 20,
  MAX_DATE_RANGE_DAYS: 730,
  MAX_ROWS_RETURNED: 100000,
  DATA_RETENTION_DAYS: 730,
  REAL_TIME_WINDOW_SECONDS: 300,
  QUERY_TIMEOUT_SECONDS: 30,
} as const;

export const ANALYTICS = {
  TYPE: ANALYTICS_TYPE,
  STATUS: ANALYTICS_STATUS,
  CATEGORY: ANALYTICS_CATEGORY,
  LIMIT: ANALYTICS_LIMIT,

  SOURCE: {
    TYPE: ANALYTICS_SOURCE,
    PLATFORM: ANALYTICS_SOURCE_PLATFORM,
  },

  MEDIUM: ANALYTICS_MEDIUM,

  CAMPAIGN: {
    TYPE: ANALYTICS_CAMPAIGN_TYPE,
    UTM_PARAM: ANALYTICS_UTM_PARAM,
    LIMIT: ANALYTICS_CAMPAIGN,
  },

  EVENT: {
    TYPE: ANALYTICS_EVENT,
    CATEGORY: ANALYTICS_EVENT_CATEGORY,
  },

  METRIC: {
    TYPE: ANALYTICS_METRIC,
    UNIT: ANALYTICS_METRIC_UNIT,
  },

  DIMENSION: {
    TYPE: ANALYTICS_DIMENSION,
    DATA_TYPE: ANALYTICS_DIMENSION_TYPE,
  },

  FILTER: {
    OPERATOR: ANALYTICS_FILTER_OPERATOR,
    LOGIC: ANALYTICS_FILTER_LOGIC,
    LIMIT: ANALYTICS_FILTER,
  },

  PERIOD: {
    TYPE: ANALYTICS_PERIOD,
    DAYS: ANALYTICS_PERIOD_DAYS,
  },

  INTERVAL: {
    TYPE: ANALYTICS_INTERVAL,
    SECONDS: ANALYTICS_INTERVAL_SECONDS,
  },

  AGGREGATION: {
    TYPE: ANALYTICS_AGGREGATION,
    PERCENTILE: ANALYTICS_PERCENTILE,
    LIMIT: ANALYTICS_AGGREGATION_LIMIT,
  },

  COMPARISON: {
    TYPE: ANALYTICS_COMPARISON,
    CHANGE_TYPE: ANALYTICS_CHANGE_TYPE,
    LIMIT: ANALYTICS_COMPARISON_LIMIT,
  },

  TREND: {
    TYPE: ANALYTICS_TREND_TYPE,
    STRENGTH: ANALYTICS_TREND_STRENGTH,
    LIMIT: ANALYTICS_TREND_LIMIT,
  },

  PERMISSION: ANALYTICS_PERMISSION,
} as const;

export type AnalyticsType = typeof ANALYTICS;
