/**
 * Notification Template Status Constants
 * Status definitions for notification templates
 */

export const NOTIFICATIONTEMPLATE_STATUS = {
  // Template Statuses
  STATUSES: {
    DRAFT: 'draft',
    PENDING_APPROVAL: 'pending_approval',
    UNDER_REVIEW: 'under_review',
    APPROVED: 'approved',
    REJECTED: 'rejected',
    PUBLISHED: 'published',
    UNPUBLISHED: 'unpublished',
    ARCHIVED: 'archived',
    DEPRECATED: 'deprecated',
    INACTIVE: 'inactive',
    ACTIVE: 'active',
    PENDING_CHANGES: 'pending_changes',
    CHANGES_APPROVED: 'changes_approved',
    CHANGES_REJECTED: 'changes_rejected',
  } as const,

  // Status Colors (for UI)
  COLORS: {
    DRAFT: '#6B7280',
    PENDING_APPROVAL: '#F59E0B',
    UNDER_REVIEW: '#8B5CF6',
    APPROVED: '#10B981',
    REJECTED: '#EF4444',
    PUBLISHED: '#10B981',
    UNPUBLISHED: '#6B7280',
    ARCHIVED: '#6B7280',
    DEPRECATED: '#6B7280',
    INACTIVE: '#6B7280',
    ACTIVE: '#10B981',
    PENDING_CHANGES: '#F59E0B',
    CHANGES_APPROVED: '#10B981',
    CHANGES_REJECTED: '#EF4444',
  } as const,

  // Status Categories
  CATEGORIES: {
    DRAFT: 'draft',
    PENDING: 'pending',
    REVIEW: 'review',
    APPROVED: 'approved',
    PUBLISHED: 'published',
    ARCHIVED: 'archived',
    DEPRECATED: 'deprecated',
  } as const,

  // Status Priority Order
  ORDER: {
    DRAFT: 0,
    PENDING_APPROVAL: 1,
    UNDER_REVIEW: 2,
    APPROVED: 3,
    REJECTED: 4,
    PENDING_CHANGES: 5,
    CHANGES_APPROVED: 6,
    CHANGES_REJECTED: 7,
    PUBLISHED: 8,
    UNPUBLISHED: 9,
    ACTIVE: 10,
    INACTIVE: 11,
    DEPRECATED: 12,
    ARCHIVED: 13,
  } as const,

  // Status Transitions
  TRANSITIONS: {
    DRAFT_TO_PENDING_APPROVAL: 'draft_to_pending_approval',
    DRAFT_TO_ARCHIVED: 'draft_to_archived',
    DRAFT_TO_CANCELLED: 'draft_to_cancelled',
    PENDING_APPROVAL_TO_UNDER_REVIEW: 'pending_approval_to_under_review',
    PENDING_APPROVAL_TO_DRAFT: 'pending_approval_to_draft',
    UNDER_REVIEW_TO_APPROVED: 'under_review_to_approved',
    UNDER_REVIEW_TO_REJECTED: 'under_review_to_rejected',
    APPROVED_TO_PUBLISHED: 'approved_to_published',
    APPROVED_TO_ARCHIVED: 'approved_to_archived',
    REJECTED_TO_DRAFT: 'rejected_to_draft',
    REJECTED_TO_ARCHIVED: 'rejected_to_archived',
    PUBLISHED_TO_UNPUBLISHED: 'published_to_unpublished',
    PUBLISHED_TO_PENDING_CHANGES: 'published_to_pending_changes',
    PUBLISHED_TO_ARCHIVED: 'published_to_archived',
    PUBLISHED_TO_DEPRECATED: 'published_to_deprecated',
    UNPUBLISHED_TO_DRAFT: 'unpublished_to_draft',
    UNPUBLISHED_TO_ARCHIVED: 'unpublished_to_archived',
    PENDING_CHANGES_TO_UNDER_REVIEW: 'pending_changes_to_under_review',
    PENDING_CHANGES_TO_ARCHIVED: 'pending_changes_to_archived',
    CHANGES_APPROVED_TO_PUBLISHED: 'changes_approved_to_published',
    CHANGES_APPROVED_TO_ARCHIVED: 'changes_approved_to_archived',
    CHANGES_REJECTED_TO_PENDING_CHANGES: 'changes_rejected_to_pending_changes',
    ACTIVE_TO_INACTIVE: 'active_to_inactive',
    ACTIVE_TO_DEPRECATED: 'active_to_deprecated',
    ACTIVE_TO_ARCHIVED: 'active_to_archived',
    INACTIVE_TO_ACTIVE: 'inactive_to_active',
    INACTIVE_TO_ARCHIVED: 'inactive_to_archived',
    DEPRECATED_TO_ARCHIVED: 'deprecated_to_archived',
  } as const,
} as const;

// Template Statuses
export type NotificationTemplateStatusType =
  (typeof NOTIFICATIONTEMPLATE_STATUS.STATUSES)[keyof typeof NOTIFICATIONTEMPLATE_STATUS.STATUSES];

// Status Colors
export type NotificationTemplateStatusColor =
  (typeof NOTIFICATIONTEMPLATE_STATUS.COLORS)[keyof typeof NOTIFICATIONTEMPLATE_STATUS.COLORS];

// Status Categories
export type NotificationTemplateStatusCategory =
  (typeof NOTIFICATIONTEMPLATE_STATUS.CATEGORIES)[keyof typeof NOTIFICATIONTEMPLATE_STATUS.CATEGORIES];

// Status Priority Order
export type NotificationTemplateStatusOrder =
  (typeof NOTIFICATIONTEMPLATE_STATUS.ORDER)[keyof typeof NOTIFICATIONTEMPLATE_STATUS.ORDER];

// Status Transitions
export type NotificationTemplateStatusTransition =
  (typeof NOTIFICATIONTEMPLATE_STATUS.TRANSITIONS)[keyof typeof NOTIFICATIONTEMPLATE_STATUS.TRANSITIONS];

// Utility Functions
export function notificationtemplateGetStatusLabel(status: NotificationTemplateStatusType): string {
  const labels: Record<NotificationTemplateStatusType, string> = {
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.DRAFT]: 'Draft',
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.PENDING_APPROVAL]: 'Pending Approval',
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.UNDER_REVIEW]: 'Under Review',
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.APPROVED]: 'Approved',
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.REJECTED]: 'Rejected',
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.PUBLISHED]: 'Published',
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.UNPUBLISHED]: 'Unpublished',
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED]: 'Archived',
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.DEPRECATED]: 'Deprecated',
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.INACTIVE]: 'Inactive',
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.ACTIVE]: 'Active',
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.PENDING_CHANGES]: 'Pending Changes',
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.CHANGES_APPROVED]: 'Changes Approved',
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.CHANGES_REJECTED]: 'Changes Rejected',
  };
  return labels[status] || 'Unknown Status';
}

export function notificationtemplateGetStatusColor(
  status: NotificationTemplateStatusType
): NotificationTemplateStatusColor {
  const colors: Record<NotificationTemplateStatusType, NotificationTemplateStatusColor> = {
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.DRAFT]: NOTIFICATIONTEMPLATE_STATUS.COLORS.DRAFT,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.PENDING_APPROVAL]:
      NOTIFICATIONTEMPLATE_STATUS.COLORS.PENDING_APPROVAL,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.UNDER_REVIEW]:
      NOTIFICATIONTEMPLATE_STATUS.COLORS.UNDER_REVIEW,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.APPROVED]: NOTIFICATIONTEMPLATE_STATUS.COLORS.APPROVED,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.REJECTED]: NOTIFICATIONTEMPLATE_STATUS.COLORS.REJECTED,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.PUBLISHED]: NOTIFICATIONTEMPLATE_STATUS.COLORS.PUBLISHED,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.UNPUBLISHED]:
      NOTIFICATIONTEMPLATE_STATUS.COLORS.UNPUBLISHED,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED]: NOTIFICATIONTEMPLATE_STATUS.COLORS.ARCHIVED,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.DEPRECATED]:
      NOTIFICATIONTEMPLATE_STATUS.COLORS.DEPRECATED,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.INACTIVE]: NOTIFICATIONTEMPLATE_STATUS.COLORS.INACTIVE,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.ACTIVE]: NOTIFICATIONTEMPLATE_STATUS.COLORS.ACTIVE,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.PENDING_CHANGES]:
      NOTIFICATIONTEMPLATE_STATUS.COLORS.PENDING_CHANGES,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.CHANGES_APPROVED]:
      NOTIFICATIONTEMPLATE_STATUS.COLORS.CHANGES_APPROVED,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.CHANGES_REJECTED]:
      NOTIFICATIONTEMPLATE_STATUS.COLORS.CHANGES_REJECTED,
  };
  return colors[status] || NOTIFICATIONTEMPLATE_STATUS.COLORS.DRAFT;
}

export function notificationtemplateGetStatusCategory(
  status: NotificationTemplateStatusType
): NotificationTemplateStatusCategory {
  const categories: Record<NotificationTemplateStatusType, NotificationTemplateStatusCategory> = {
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.DRAFT]: NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.DRAFT,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.PENDING_APPROVAL]:
      NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.PENDING,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.UNDER_REVIEW]:
      NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.REVIEW,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.APPROVED]:
      NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.APPROVED,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.REJECTED]: NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.DRAFT,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.PUBLISHED]:
      NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.PUBLISHED,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.UNPUBLISHED]:
      NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.DRAFT,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED]:
      NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.ARCHIVED,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.DEPRECATED]:
      NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.DEPRECATED,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.INACTIVE]: NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.DRAFT,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.ACTIVE]: NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.PUBLISHED,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.PENDING_CHANGES]:
      NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.PENDING,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.CHANGES_APPROVED]:
      NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.APPROVED,
    [NOTIFICATIONTEMPLATE_STATUS.STATUSES.CHANGES_REJECTED]:
      NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.DRAFT,
  };
  return categories[status] || NOTIFICATIONTEMPLATE_STATUS.CATEGORIES.DRAFT;
}

export function notificationtemplateIsPublished(status: NotificationTemplateStatusType): boolean {
  const publishedStatuses: NotificationTemplateStatusType[] = [
    NOTIFICATIONTEMPLATE_STATUS.STATUSES.PUBLISHED,
    NOTIFICATIONTEMPLATE_STATUS.STATUSES.ACTIVE,
  ];
  return publishedStatuses.includes(status);
}

export function notificationtemplateIsDraft(status: NotificationTemplateStatusType): boolean {
  const draftStatuses: NotificationTemplateStatusType[] = [
    NOTIFICATIONTEMPLATE_STATUS.STATUSES.DRAFT,
    NOTIFICATIONTEMPLATE_STATUS.STATUSES.UNPUBLISHED,
    NOTIFICATIONTEMPLATE_STATUS.STATUSES.CHANGES_REJECTED,
  ];
  return draftStatuses.includes(status);
}

export function notificationtemplateIsApproved(status: NotificationTemplateStatusType): boolean {
  const approvedStatuses: NotificationTemplateStatusType[] = [
    NOTIFICATIONTEMPLATE_STATUS.STATUSES.APPROVED,
    NOTIFICATIONTEMPLATE_STATUS.STATUSES.PUBLISHED,
    NOTIFICATIONTEMPLATE_STATUS.STATUSES.ACTIVE,
    NOTIFICATIONTEMPLATE_STATUS.STATUSES.CHANGES_APPROVED,
  ];
  return approvedStatuses.includes(status);
}

export function notificationtemplateIsArchived(status: NotificationTemplateStatusType): boolean {
  const archivedStatuses: NotificationTemplateStatusType[] = [
    NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED,
    NOTIFICATIONTEMPLATE_STATUS.STATUSES.DEPRECATED,
  ];
  return archivedStatuses.includes(status);
}

export function notificationtemplateCanTransition(
  currentStatus: NotificationTemplateStatusType,
  targetStatus: NotificationTemplateStatusType
): boolean {
  const validTransitions: Record<NotificationTemplateStatusType, NotificationTemplateStatusType[]> =
    {
      [NOTIFICATIONTEMPLATE_STATUS.STATUSES.DRAFT]: [
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.PENDING_APPROVAL,
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED,
      ],
      [NOTIFICATIONTEMPLATE_STATUS.STATUSES.PENDING_APPROVAL]: [
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.UNDER_REVIEW,
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.DRAFT,
      ],
      [NOTIFICATIONTEMPLATE_STATUS.STATUSES.UNDER_REVIEW]: [
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.APPROVED,
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.REJECTED,
      ],
      [NOTIFICATIONTEMPLATE_STATUS.STATUSES.APPROVED]: [
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.PUBLISHED,
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED,
      ],
      [NOTIFICATIONTEMPLATE_STATUS.STATUSES.REJECTED]: [
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.DRAFT,
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED,
      ],
      [NOTIFICATIONTEMPLATE_STATUS.STATUSES.PUBLISHED]: [
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.UNPUBLISHED,
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.PENDING_CHANGES,
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED,
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.DEPRECATED,
      ],
      [NOTIFICATIONTEMPLATE_STATUS.STATUSES.UNPUBLISHED]: [
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.DRAFT,
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED,
      ],
      [NOTIFICATIONTEMPLATE_STATUS.STATUSES.PENDING_CHANGES]: [
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.UNDER_REVIEW,
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED,
      ],
      [NOTIFICATIONTEMPLATE_STATUS.STATUSES.CHANGES_APPROVED]: [
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.PUBLISHED,
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED,
      ],
      [NOTIFICATIONTEMPLATE_STATUS.STATUSES.CHANGES_REJECTED]: [
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.PENDING_CHANGES,
      ],
      [NOTIFICATIONTEMPLATE_STATUS.STATUSES.ACTIVE]: [
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.INACTIVE,
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.DEPRECATED,
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED,
      ],
      [NOTIFICATIONTEMPLATE_STATUS.STATUSES.INACTIVE]: [
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.ACTIVE,
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED,
      ],
      [NOTIFICATIONTEMPLATE_STATUS.STATUSES.DEPRECATED]: [
        NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED,
      ],
      [NOTIFICATIONTEMPLATE_STATUS.STATUSES.ARCHIVED]: [],
    };

  return validTransitions[currentStatus]?.includes(targetStatus) || false;
}
