/**
 * AI Cluster Status Constants
 * Status tracking for clustering operations
 */

// First define the status types
export const AI_CLUSTER_STATUS_TYPES = {
  // Initial States
  CREATED: 'created',
  QUEUED: 'queued',
  PENDING: 'pending',

  // Processing States
  INITIALIZING: 'initializing',
  CLUSTERING: 'clustering',
  OPTIMIZING: 'optimizing',
  VALIDATING: 'validating',

  // Intermediate States
  CLUSTERED: 'clustered',
  OPTIMIZED: 'optimized',
  VALIDATED: 'validated',

  // Storage States
  STORING: 'storing',
  STORED: 'stored',
  CACHING: 'caching',
  CACHED: 'cached',

  // Terminal States
  COMPLETED: 'completed',
  FAILED: 'failed',
  EXPIRED: 'expired',
  ARCHIVED: 'archived',
} as const;

export type AIClusterStatusType =
  (typeof AI_CLUSTER_STATUS_TYPES)[keyof typeof AI_CLUSTER_STATUS_TYPES];

export const AI_CLUSTER_STATUS = {
  // Status Types
  STATUSES: AI_CLUSTER_STATUS_TYPES,

  // Status Categories
  CATEGORIES: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CACHED: 'cached',
  } as const,

  // Status Severity
  SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  } as const,

  // Status Colors
  COLORS: {
    [AI_CLUSTER_STATUS_TYPES.CREATED]: '#gray',
    [AI_CLUSTER_STATUS_TYPES.QUEUED]: '#gray',
    [AI_CLUSTER_STATUS_TYPES.PENDING]: '#yellow',
    [AI_CLUSTER_STATUS_TYPES.INITIALIZING]: '#blue',
    [AI_CLUSTER_STATUS_TYPES.CLUSTERING]: '#blue',
    [AI_CLUSTER_STATUS_TYPES.OPTIMIZING]: '#blue',
    [AI_CLUSTER_STATUS_TYPES.VALIDATING]: '#purple',
    [AI_CLUSTER_STATUS_TYPES.CLUSTERED]: '#green',
    [AI_CLUSTER_STATUS_TYPES.OPTIMIZED]: '#green',
    [AI_CLUSTER_STATUS_TYPES.VALIDATED]: '#green',
    [AI_CLUSTER_STATUS_TYPES.STORING]: '#orange',
    [AI_CLUSTER_STATUS_TYPES.STORED]: '#green',
    [AI_CLUSTER_STATUS_TYPES.CACHING]: '#orange',
    [AI_CLUSTER_STATUS_TYPES.CACHED]: '#green',
    [AI_CLUSTER_STATUS_TYPES.COMPLETED]: '#green',
    [AI_CLUSTER_STATUS_TYPES.FAILED]: '#red',
    [AI_CLUSTER_STATUS_TYPES.EXPIRED]: '#gray',
    [AI_CLUSTER_STATUS_TYPES.ARCHIVED]: '#gray',
  } as const,
} as const;

export type AIClusterStatusCategory =
  (typeof AI_CLUSTER_STATUS.CATEGORIES)[keyof typeof AI_CLUSTER_STATUS.CATEGORIES];
export type AIClusterStatusSeverity =
  (typeof AI_CLUSTER_STATUS.SEVERITY)[keyof typeof AI_CLUSTER_STATUS.SEVERITY];
export type AIClusterStatusColor =
  (typeof AI_CLUSTER_STATUS.COLORS)[keyof typeof AI_CLUSTER_STATUS.COLORS];

export function getAiClusterStatusLabel(status: AIClusterStatusType): string {
  const labels: Record<AIClusterStatusType, string> = {
    [AI_CLUSTER_STATUS_TYPES.CREATED]: 'Created',
    [AI_CLUSTER_STATUS_TYPES.QUEUED]: 'Queued',
    [AI_CLUSTER_STATUS_TYPES.PENDING]: 'Pending',
    [AI_CLUSTER_STATUS_TYPES.INITIALIZING]: 'Initializing',
    [AI_CLUSTER_STATUS_TYPES.CLUSTERING]: 'Clustering',
    [AI_CLUSTER_STATUS_TYPES.OPTIMIZING]: 'Optimizing',
    [AI_CLUSTER_STATUS_TYPES.VALIDATING]: 'Validating',
    [AI_CLUSTER_STATUS_TYPES.CLUSTERED]: 'Clustered',
    [AI_CLUSTER_STATUS_TYPES.OPTIMIZED]: 'Optimized',
    [AI_CLUSTER_STATUS_TYPES.VALIDATED]: 'Validated',
    [AI_CLUSTER_STATUS_TYPES.STORING]: 'Storing',
    [AI_CLUSTER_STATUS_TYPES.STORED]: 'Stored',
    [AI_CLUSTER_STATUS_TYPES.CACHING]: 'Caching',
    [AI_CLUSTER_STATUS_TYPES.CACHED]: 'Cached',
    [AI_CLUSTER_STATUS_TYPES.COMPLETED]: 'Completed',
    [AI_CLUSTER_STATUS_TYPES.FAILED]: 'Failed',
    [AI_CLUSTER_STATUS_TYPES.EXPIRED]: 'Expired',
    [AI_CLUSTER_STATUS_TYPES.ARCHIVED]: 'Archived',
  };
  return labels[status] || 'Unknown';
}

export function getAiClusterStatusCategory(status: AIClusterStatusType): AIClusterStatusCategory {
  const categories: Record<AIClusterStatusType, AIClusterStatusCategory> = {
    [AI_CLUSTER_STATUS_TYPES.CREATED]: AI_CLUSTER_STATUS.CATEGORIES.PENDING,
    [AI_CLUSTER_STATUS_TYPES.QUEUED]: AI_CLUSTER_STATUS.CATEGORIES.PENDING,
    [AI_CLUSTER_STATUS_TYPES.PENDING]: AI_CLUSTER_STATUS.CATEGORIES.PENDING,
    [AI_CLUSTER_STATUS_TYPES.INITIALIZING]: AI_CLUSTER_STATUS.CATEGORIES.PROCESSING,
    [AI_CLUSTER_STATUS_TYPES.CLUSTERING]: AI_CLUSTER_STATUS.CATEGORIES.PROCESSING,
    [AI_CLUSTER_STATUS_TYPES.OPTIMIZING]: AI_CLUSTER_STATUS.CATEGORIES.PROCESSING,
    [AI_CLUSTER_STATUS_TYPES.VALIDATING]: AI_CLUSTER_STATUS.CATEGORIES.PROCESSING,
    [AI_CLUSTER_STATUS_TYPES.CLUSTERED]: AI_CLUSTER_STATUS.CATEGORIES.PROCESSING,
    [AI_CLUSTER_STATUS_TYPES.OPTIMIZED]: AI_CLUSTER_STATUS.CATEGORIES.PROCESSING,
    [AI_CLUSTER_STATUS_TYPES.VALIDATED]: AI_CLUSTER_STATUS.CATEGORIES.PROCESSING,
    [AI_CLUSTER_STATUS_TYPES.STORING]: AI_CLUSTER_STATUS.CATEGORIES.PROCESSING,
    [AI_CLUSTER_STATUS_TYPES.STORED]: AI_CLUSTER_STATUS.CATEGORIES.COMPLETED,
    [AI_CLUSTER_STATUS_TYPES.CACHING]: AI_CLUSTER_STATUS.CATEGORIES.PROCESSING,
    [AI_CLUSTER_STATUS_TYPES.CACHED]: AI_CLUSTER_STATUS.CATEGORIES.CACHED,
    [AI_CLUSTER_STATUS_TYPES.COMPLETED]: AI_CLUSTER_STATUS.CATEGORIES.COMPLETED,
    [AI_CLUSTER_STATUS_TYPES.FAILED]: AI_CLUSTER_STATUS.CATEGORIES.FAILED,
    [AI_CLUSTER_STATUS_TYPES.EXPIRED]: AI_CLUSTER_STATUS.CATEGORIES.FAILED,
    [AI_CLUSTER_STATUS_TYPES.ARCHIVED]: AI_CLUSTER_STATUS.CATEGORIES.COMPLETED,
  };
  return categories[status] || AI_CLUSTER_STATUS.CATEGORIES.PENDING;
}

export function getAiClusterStatusSeverity(status: AIClusterStatusType): AIClusterStatusSeverity {
  const severities: Record<AIClusterStatusType, AIClusterStatusSeverity> = {
    [AI_CLUSTER_STATUS_TYPES.CREATED]: AI_CLUSTER_STATUS.SEVERITY.INFO,
    [AI_CLUSTER_STATUS_TYPES.QUEUED]: AI_CLUSTER_STATUS.SEVERITY.INFO,
    [AI_CLUSTER_STATUS_TYPES.PENDING]: AI_CLUSTER_STATUS.SEVERITY.INFO,
    [AI_CLUSTER_STATUS_TYPES.INITIALIZING]: AI_CLUSTER_STATUS.SEVERITY.INFO,
    [AI_CLUSTER_STATUS_TYPES.CLUSTERING]: AI_CLUSTER_STATUS.SEVERITY.INFO,
    [AI_CLUSTER_STATUS_TYPES.OPTIMIZING]: AI_CLUSTER_STATUS.SEVERITY.INFO,
    [AI_CLUSTER_STATUS_TYPES.VALIDATING]: AI_CLUSTER_STATUS.SEVERITY.WARNING,
    [AI_CLUSTER_STATUS_TYPES.CLUSTERED]: AI_CLUSTER_STATUS.SEVERITY.INFO,
    [AI_CLUSTER_STATUS_TYPES.OPTIMIZED]: AI_CLUSTER_STATUS.SEVERITY.INFO,
    [AI_CLUSTER_STATUS_TYPES.VALIDATED]: AI_CLUSTER_STATUS.SEVERITY.INFO,
    [AI_CLUSTER_STATUS_TYPES.STORING]: AI_CLUSTER_STATUS.SEVERITY.INFO,
    [AI_CLUSTER_STATUS_TYPES.STORED]: AI_CLUSTER_STATUS.SEVERITY.INFO,
    [AI_CLUSTER_STATUS_TYPES.CACHING]: AI_CLUSTER_STATUS.SEVERITY.INFO,
    [AI_CLUSTER_STATUS_TYPES.CACHED]: AI_CLUSTER_STATUS.SEVERITY.INFO,
    [AI_CLUSTER_STATUS_TYPES.COMPLETED]: AI_CLUSTER_STATUS.SEVERITY.INFO,
    [AI_CLUSTER_STATUS_TYPES.FAILED]: AI_CLUSTER_STATUS.SEVERITY.ERROR,
    [AI_CLUSTER_STATUS_TYPES.EXPIRED]: AI_CLUSTER_STATUS.SEVERITY.WARNING,
    [AI_CLUSTER_STATUS_TYPES.ARCHIVED]: AI_CLUSTER_STATUS.SEVERITY.INFO,
  };
  return severities[status] || AI_CLUSTER_STATUS.SEVERITY.INFO;
}

export function getAiClusterStatusColor(status: AIClusterStatusType): AIClusterStatusColor {
  return AI_CLUSTER_STATUS.COLORS[status] || '#gray';
}

export function isAiClusterActive(status: AIClusterStatusType): boolean {
  const activeStatuses: AIClusterStatusType[] = [
    AI_CLUSTER_STATUS_TYPES.CREATED,
    AI_CLUSTER_STATUS_TYPES.QUEUED,
    AI_CLUSTER_STATUS_TYPES.PENDING,
    AI_CLUSTER_STATUS_TYPES.INITIALIZING,
    AI_CLUSTER_STATUS_TYPES.CLUSTERING,
    AI_CLUSTER_STATUS_TYPES.OPTIMIZING,
    AI_CLUSTER_STATUS_TYPES.VALIDATING,
    AI_CLUSTER_STATUS_TYPES.CLUSTERED,
    AI_CLUSTER_STATUS_TYPES.OPTIMIZED,
    AI_CLUSTER_STATUS_TYPES.VALIDATED,
    AI_CLUSTER_STATUS_TYPES.STORING,
    AI_CLUSTER_STATUS_TYPES.CACHING,
  ];
  return activeStatuses.includes(status);
}

export function isAiClusterCompleted(status: AIClusterStatusType): boolean {
  const completedStatuses: AIClusterStatusType[] = [
    AI_CLUSTER_STATUS_TYPES.COMPLETED,
    AI_CLUSTER_STATUS_TYPES.STORED,
    AI_CLUSTER_STATUS_TYPES.CACHED,
    AI_CLUSTER_STATUS_TYPES.ARCHIVED,
  ];
  return completedStatuses.includes(status);
}

export function isAiClusterFailed(status: AIClusterStatusType): boolean {
  const failedStatuses: AIClusterStatusType[] = [
    AI_CLUSTER_STATUS_TYPES.FAILED,
    AI_CLUSTER_STATUS_TYPES.EXPIRED,
  ];
  return failedStatuses.includes(status);
}

export function getAiClusterStatusProgress(status: AIClusterStatusType): number {
  const progress: Record<AIClusterStatusType, number> = {
    [AI_CLUSTER_STATUS_TYPES.CREATED]: 0,
    [AI_CLUSTER_STATUS_TYPES.QUEUED]: 5,
    [AI_CLUSTER_STATUS_TYPES.PENDING]: 10,
    [AI_CLUSTER_STATUS_TYPES.INITIALIZING]: 20,
    [AI_CLUSTER_STATUS_TYPES.CLUSTERING]: 40,
    [AI_CLUSTER_STATUS_TYPES.OPTIMIZING]: 60,
    [AI_CLUSTER_STATUS_TYPES.VALIDATING]: 70,
    [AI_CLUSTER_STATUS_TYPES.CLUSTERED]: 50,
    [AI_CLUSTER_STATUS_TYPES.OPTIMIZED]: 65,
    [AI_CLUSTER_STATUS_TYPES.VALIDATED]: 75,
    [AI_CLUSTER_STATUS_TYPES.STORING]: 80,
    [AI_CLUSTER_STATUS_TYPES.STORED]: 85,
    [AI_CLUSTER_STATUS_TYPES.CACHING]: 88,
    [AI_CLUSTER_STATUS_TYPES.CACHED]: 92,
    [AI_CLUSTER_STATUS_TYPES.COMPLETED]: 100,
    [AI_CLUSTER_STATUS_TYPES.FAILED]: 0,
    [AI_CLUSTER_STATUS_TYPES.EXPIRED]: 0,
    [AI_CLUSTER_STATUS_TYPES.ARCHIVED]: 100,
  };
  return progress[status] || 0;
}
