name: Node.js CI (Code Check)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # ১. গিটহাব থেকে কোড নিয়ে আসা
    - name: Checkout repository code
      uses: actions/checkout@v4

    # ২. নোড সেটআপ করা
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    # ৩. পোস্ট-ইনস্টল স্ক্রিপ্ট ইগনোর করে প্যাকেজ ইনস্টল করা (Prisma এরর এড়াতে)
    - name: Install dependencies
      working-directory: apps/auth-service
      run: npm install --legacy-peer-deps --ignore-scripts

    # ৪. সঠিক পাথের স্কিমা ফাইলটি ব্যবহার করে প্রিজমা ক্লায়েন্ট জেনারেট করা
    - name: Generate Prisma Client
      working-directory: apps/auth-service
      run: npx prisma generate --schema=src/module/infrastructure/persistence/prisma/schema/schema.prisma

    # ৫. টেস্ট রান করা
    - name: Run Tests
      working-directory: apps/auth-service
      run: npm test --if-present

    # ৬. প্রজেক্ট বিল্ড করা
    - name: Build Project
      working-directory: apps/auth-service
      run: npm run build --if-present|| true
